### ISSUE TITLE
Getter and Setters

### ISSUE THREAD

**Issue by scgm11** [redhat-developer/vscode-java#100]
Be able to add automatic getter, setters on a class and also override methods if extending a class

**Comment by gorkem** [comment]
Is this a request to get code actions or code lenses for generating getters and setters ? Overrides are covered on #85 for completions

**Comment by scgm11** [comment]
the idea is like intellij or netbeans right click in a class give you de generate code.. getter and setters for selected variables or others like overrides if the class is extended

**Comment by dineiar** [comment]
Looking forward to this.

**Comment by dineiar** [comment]
For now, I put this code under java.json (File > Preferences > User Snippets > Java):
```
"Getter/Setter": {
	"prefix": "getset",
	"body": [
		"public ${1:int} get${2:Attribute}()",
		"{",
		"\treturn this.${3:attribute};",
		"}",
		"public void set${2:Attribute}(${1:int} ${3:attribute})",
		"{",
		"\tthis.${3:attribute} = ${3:attribute};",
		"}"
	],
	"description": "Generate getter/setter for class attributes"
}
```
Write "getset" and VSCode offers the snippet, then use Tab to navigate on the placeholders.

**Comment by fbricon** [comment]
so with @yaohaizh's PR, the setters and getters will be available as code completion proposal, not as a global command initially (we can work on that latter)

![jul-24-2017 10-31-52](https://user-images.githubusercontent.com/148698/28528850-ef7b39c8-705c-11e7-85c0-4b9bdb51b269.gif)

**Comment by gorkem** [comment]
@yaohaizh this is looking great. Can we enable this as a code lens too?

**Comment by phil294** [comment]
buld generation like in [jetbrains](https://intellij-support.jetbrains.com/hc/user_images/Ee7QXLISd30ZHKRcMpw7KQ.png) or [eclipse](http://www.benchresources.net/wp-content/uploads/2017/08/generate-getter-setter-select-fields-in-eclipse-ide-3.png) would be pretty useful also.

**Comment by augustocdias** [comment]
And would be nice to have generators not only for getters and setters, but also for constructors, toString, hashCode, equals and overrides

**Comment by mogarick** [comment]
@phil294 and @augustocdias I think it'd be better if you open a new issue because this was closed a year ago and it's very likely the team is not paying attention to it one anymore.

**Comment by gentunian** [comment]
This isn't working when your field is boolean:

![peek 2018-07-10 14-35](https://user-images.githubusercontent.com/1090113/42527878-45a05af6-8450-11e8-83ad-0e23e3755067.gif)

extension version: 0.28.0 (July 3rd, 2018)

**Comment by fbricon** [comment]
@gentunian for booleans, the convention is to have an `is` prefix instead of `get`

**Comment by arambekverdyan** [comment]
> And would be nice to have generators not only for getters and setters, but also for constructors, toString, hashCode, equals and overrides

There is a working extension which generates getters, setters, equals, and hashcode. https://github.com/sohibegit/vscode-java-code-generator

**Comment by fbricon** [comment]
Starting in vscode-java 0.36.0, and thanks to @testforstephen's efforts, you'll be able to bulk generate accessors:
![bulk_gen_accessors](https://user-images.githubusercontent.com/148698/49904707-1133d280-fe39-11e8-876c-8440c667981d.gif)

**Comment by lindXdeep** [comment]
> For now, I put this code under java.json (File > Preferences > User Snippets > Java):
> 
> ```
> "Getter/Setter": {
> 	"prefix": "getset",
> 	"body": [
> 		"public ${1:int} get${2:Attribute}() {",
> 		"\treturn this.${3:attribute};",
> 		"}",
> 		"public void set${2:Attribute}(${1:int} ${3:attribute}) {",
> 		"\tthis.${3:attribute} = ${3:attribute};",
> 		"}"
> 	],
> 	"description": "Generate getter/setter for class attributes"
> }
> ```
> 
> Write "getset" and VSCode offers the snippet, then use Tab to navigate on the placeholders.

super sahkth
