### ISSUE TITLE
Issue with JDK version changed

### ISSUE THREAD

**Issue by B1ex1ayU** [redhat-developer/vscode-java#1003]
I have installed JDK 12 before and the code can run well, but I need JDK 11 for some reason so I uninstall JDK12 and install JDK11. (and I have already changed the environment variable, JAVA_HOME to \jdk-11.0.4)

Then, my VScode can't run it...( I have tried to delete and create a new java file and run )
But it still works on cmd and Powershell with the right version of JDK.

![微信截图_20190725152140](https://user-images.githubusercontent.com/53289934/61850381-8c915280-aef7-11e9-83bb-e37d0c27c23d.png)

![微信截图_20190725152531](https://user-images.githubusercontent.com/53289934/61850425-a6329a00-aef7-11e9-8e6c-eb2cd27d3698.png)

##### Environment
- Operating System: Windows 10
- JDK version: 11.0.4
- Visual Studio Code version: 1.36.1
- Java extension version: 0.7.1

##### Steps To Reproduce
1. [step 1] install JDK 12 and VScode and Java Extention (then everything works well)
2. [step 2] uninstall JDK 12 and install JDK 11
3. [step 3] change the environment variable
4. [step 4] code can't run on VScode but can run on cmd

**Comment by testforstephen** [comment]
Could you try VS Code command `Java: Clean the Java language server workspace`?

**Comment by B1ex1ayU** [comment]
it works! thanks!! @testforstephen
