### ISSUE TITLE
Broken images in javadoc when images are included in source JAR

### ISSUE THREAD

**Issue by jnesspro** [redhat-developer/vscode-java#1007]
When I hover cursor over the method I see docs. But images are broken, see screenshot
<img width="570" alt="Screenshot 2019-07-26 at 14 33 09" src="https://user-images.githubusercontent.com/5245360/61949296-09cdcd80-afb3-11e9-9a7c-0ac4351dde2b.png">

It is very useful to see this algorithm image in case of reactor project, but I can not with VSCode java

##### Environment
- Operating System:
MacOS
- Visual Studio Code version:
Insiders 1.37-0, 6d82826e990407364d5c829b73602a19ecdf7d00
- Java extension version:
0.47

**Comment by fbricon** [comment]
mmm works for me on macOS
<img width="847" alt="Screen Shot 2019-07-26 at 1 47 27 PM" src="https://user-images.githubusercontent.com/148698/61949744-1569c600-afac-11e9-9942-cf9aaab59cfb.png">

**Comment by fbricon** [comment]
can you please provide the verbose [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server), to see what is returned by the server on the hover request?

**Comment by jnesspro** [comment]
Oh, thanks. Here they are, attached. It isn't working for me from the beginning. I also tried download clean vscode, installed only java extension pack, result still the same
[lang_server.log.zip](https://github.com/redhat-developer/vscode-java/files/3435661/lang_server.log.zip)

**Comment by fbricon** [comment]
please provide the **verbose** logs. ("java.trace.server":"verbose")

**Comment by jnesspro** [comment]
<img width="711" alt="Screenshot 2019-07-26 at 15 09 07" src="https://user-images.githubusercontent.com/5245360/61950738-76e36200-afb7-11e9-9a58-45dd7cd7cd53.png">

But logs look still the same. Ok. I will reboot few times

**Comment by jnesspro** [comment]
and I see images with another ide. I also tried gradle / maven projects, still the same. I also removed gradle and .m2 caches too refresh all dependencies

**Comment by fbricon** [comment]
Please provide the full message logging in the **Output view** (select Language support for Java in the view menu)

**Comment by jnesspro** [comment]
[Trace - 3:30:16 PM] Sending request 'textDocument/hover - (43)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jness/Downloads/demo/src/main/java/com/example/demo/DemoApplication.java"
    },
    "position": {
        "line": 11,
        "character": 11
    }
}


[Trace - 3:30:16 PM] Received response 'textDocument/hover - (43)' in 39ms.
Result: {
    "contents": [
        {
            "language": "java",
            "value": "<Object> Mono<Object> reactor.core.publisher.Mono.empty()"
        },
        "Create a [Mono](jdt://contents/reactor-core-3.2.10.RELEASE.jar/reactor.core.publisher/Mono.class?=demo/%5C/Users%5C/jness%5C/.m2%5C/repository%5C/io%5C/projectreactor%5C/reactor-core%5C/3.2.10.RELEASE%5C/reactor-core-3.2.10.RELEASE.jar%3Creactor.core.publisher%28Mono.class#101) that completes without emitting any item.\n\n![Image]()\n\n *  **Type Parameters:**\n    \n     *  **<T>** the reified Subscriber type\n *  **Returns:**\n    \n     *  a completed [Mono](jdt://contents/reactor-core-3.2.10.RELEASE.jar/reactor.core.publisher/Mono.class?=demo/%5C/Users%5C/jness%5C/.m2%5C/repository%5C/io%5C/projectreactor%5C/reactor-core%5C/3.2.10.RELEASE%5C/reactor-core-3.2.10.RELEASE.jar%3Creactor.core.publisher%28Mono.class#101)"
    ]
}

**Comment by fbricon** [comment]
Ah now we can see the image link is not returned. Whereas I'm getting `![Image](https://raw.githubusercontent.com/reactor/reactor-core/v3.0.5.RELEASE/src/docs/marble/error.png)`

Which version of mono are you using? please share a standalone java project reproducing this issue.

**Comment by jnesspro** [comment]
yeah, I see. This is actual for any project with reactor, also I just tried start.spring.io web-flux.
I don't know any other java doc with images to check...
[demo.zip](https://github.com/redhat-developer/vscode-java/files/3435745/demo.zip)

**Comment by fbricon** [comment]
Ok I see the issue now. With 3.2.10.RELEASE, the image is embedded in the jar:
```
/**
	 * Create a {@link Mono} that terminates with the specified error immediately after
	 * being subscribed to.
	 * <p>
	 * <img class="marble" src="doc-files/marbles/error.svg" alt="">
	 * <p>
	 * @param error the onError signal
	 * @param <T> the reified {@link Subscriber} type
	 *
	 * @return a failing {@link Mono}
	 */
```

**Comment by fbricon** [comment]
to fix that we'd need to automatically extract embedded images and rewrite the image links for the generated markdown. Might be tricky

**Comment by fbricon** [comment]
@NikolasKomonen is this something you want to look at?

**Comment by NikolasKomonen** [comment]
Looking into this one
