### ISSUE TITLE
Allow user to pick Gradle or Maven as build tool if it is ambiguous

### ISSUE THREAD

**Issue by dsyer** [redhat-developer/vscode-java#1008]
I noticed that if you open VSCode in a directory that has both Maven and Gradle build config it always starts up the Gradle daemon. I know it's a bit unusual, but we do it with all the Guides in Spring, for instance: https://github.com/spring-guides/gs-rest-service/tree/master/complete. I would like an option to pick either Maven or Gradle in such cases.

**Comment by snjeza** [comment]
You can try the following property:
```
"java.import.gradle.enabled": false,
```

**Comment by dsyer** [comment]
That helps thanks. Possibly related: the Gradle daemon never seems to die when the workspace exits. The LS process doe go away but Gradle is still running (and multiple instances build up over time).

**Comment by dsyer** [comment]
Actually, it doesn't help. The Gradle daemon is still there whatever I try to do:

```
$ jps
22481 org.eclipse.equinox.launcher_1.5.500.v20190715-1310.jar
22645 GradleDaemon
22745 BootLanguagServerBootApp
22766 Jps
```

**Comment by snjeza** [comment]
Can you kill the Gradle daemon?

**Comment by dsyer** [comment]
I did. but it always comes back when I open this folder in code.

**Comment by fbricon** [comment]
Try to clean the workspace directory

**Comment by dsyer** [comment]
I vaguely remember you asked me to try that once before. Where is it? It’s something buried under a uuid-names directory somewhere in my home dir?

**Comment by fbricon** [comment]
- Open the command palette (F1)
- select Java: Clean the Java language server workspace
- click Restart and delete

**Comment by fbricon** [comment]
Deleting the eclipse .project files to remove the Gradle builder might be useful too

**Comment by dsyer** [comment]
That did it. Thanks. I had to kill the LS and the Gradle daemon again as well, but once all that was done it started to behave.

**Comment by hanct** [comment]
> You can try the following property:
> 
> ```
> "java.import.gradle.enabled": false,
> ```

Is this setting enabled by default? Cos the guide does not state the default

**Comment by dsyer** [comment]
The default is `true` (so both Gradle and Maven try to build the project if both are available).
