### ISSUE TITLE
Gradle dependencies for non-main sourcesets not processed

### ISSUE THREAD

**Issue by jgarbers** [redhat-developer/vscode-java#1009]
##### Environment
- Operating System: macOS Mojave 10.14.5
- JDK version: 11.0.2
- Visual Studio Code version: 1.36.1
- Java extension version: 0.47.0

##### Steps To Reproduce
1. Open attached project in VS Code.

[gtest.zip](https://github.com/redhat-developer/vscode-java/files/3449109/gtest.zip)

##### Current Result
_gradle build_ completes successfully, but VS Code "Problems" pane reports three errors in _AltApp.java_: "The import org.apache cannot be resolved", "Fraction cannot be resolved to a type", and "Fraction cannot be resolved to a variable"

##### Expected Result
As Apache Commons Lang is specified as a dependency of _altCompile_, no errors should be reported.

##### Additional Information
I'm fairly new to gradle and VS Code and may be missing something basic. I've tried to reduce the problem to as small a case as possible. I am able to work around the issue by including dependencies in _compile_ as well as _altCompile_ with no apparent impact on the resulting jar, but that doesn't seem right. Thanks in advance for any guidance you can offer.

**Comment by fbricon** [comment]
Can you reproduce the problem in Eclipse?

**Comment by jgarbers** [comment]
Well,that was quick - thanks! Sorry, I don't have Eclipse installed, but if it would help in troubleshooting I can get it and try. Would you like me to do that?

**Comment by fbricon** [comment]
Yes please. None of our team members are in your timezone, so it'll help speed up troubleshooting when we come back online.

**Comment by jgarbers** [comment]
Just installed Eclipse 2019-06 (4.12.0) and opened the project. I am indeed getting the same three errors as I see in VS Code.

**Comment by snjeza** [comment]
I can reproduce the issue in Eclipse.

**Comment by fbricon** [comment]
@donat is this a known bug? Or should we open a ticket in https://github.com/eclipse/buildship/issues?

**Comment by snjeza** [comment]
@jgarbers you can try the following patch:

```
diff --git a/bin/alt/com/jgarbers/gtestAlt/AltApp.class b/bin/alt/com/jgarbers/gtestAlt/AltApp.class
index f5b7d94..36cf0df 100644
Binary files a/bin/alt/com/jgarbers/gtestAlt/AltApp.class and b/bin/alt/com/jgarbers/gtestAlt/AltApp.class differ
diff --git a/build.gradle b/build.gradle
index d0d4471..a1f93dd 100644
--- a/build.gradle
+++ b/build.gradle
@@ -19,7 +19,7 @@ sourceSets {
     }
 }
 dependencies {
-    altCompile 'org.apache.commons:commons-lang3:3.3.2'
+    compile 'org.apache.commons:commons-lang3:3.3.2'
 }
```

**Comment by fbricon** [comment]
Not sure the attached project is valid. It doesn't seem compiled from CLI. If you introduce a compilation error in the code and try a CLI build, you'll see no errors

**Comment by snjeza** [comment]
@fbricon you can try
```
gradle compileAltJava
```

**Comment by jgarbers** [comment]
@snjeza thank you so much - that took care of the problem! I figured there was a magic spell or two missing.

@fbricon sorry if it didn't build; I may have pruned away a bit too much in trying to provide a minimal example.

Wonderful support... thanks to both of you!
