### ISSUE TITLE
Java runtime (JDK, not JRE) could not be located - but it is installed with sdkman

### ISSUE THREAD

**Issue by moanrose** [redhat-developer/vscode-java#1014]
I am using sdkman to manage my sdk's including java

The extension does not seem to acknowledge my java sdk, even though the sdk should be present

`sdk current java
Using java version 8.0.212-zulu

echo $JAVA_HOME
/home/USER/.sdkman/candidates/java/current

ls /home/USER/.sdkman/candidates/java/current
ASSEMBLY_EXCEPTION
DISCLAIMER  LICENSE
sample
bin
include
man
src.zip
CLASSPATH_EXCEPTION_NOTE
jre
readme.txt
THIRD_PARTY_README
demo
lib
release
Welcome.html
`

What does it look for?

##### Environment
- Operating System: Ubuntu 19.04
- JDK version: 8.0.212
- Visual Studio Code version: 1.36.1
- Java extension version: 0.47.0

##### Steps To Reproduce
1. [step 1] Install jdk using sdkman
2. [step 2] Install extension

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Did you install vscode with flatpack?

**Comment by moanrose** [comment]
I installed vscode using the "Ubuntu software" GUI - i am not sure if that is using flatpack under the hood

**Comment by fbricon** [comment]
try to set "java.home":"/home/USER/.sdkman/candidates/java/current" in vscode's settings.json

**Comment by moanrose** [comment]
Yes, that worked

Funny that vscode does not pick up the $JAVA_HOME - is that because its a "sandboxed" installation?

**Comment by fbricon** [comment]
most likely yes

**Comment by Daniel-Monroy** [comment]
someone found a solution? :(

**Comment by tonymcneil** [comment]
For anybody else at the time of writing I've noticed that "java.home" has a comment in the default settings saying:
`// This setting is deprecated, please use 'java.jdt.ls.java.home' instead.`

So I set it as follows in settings.json and it seemed to work:
```
"java.jdt.ls.java.home": "~/.sdkman/candidates/java/current",
```

I'm using VSCode version:
```
Version: 1.67.1 (Universal)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:16.526Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
```
