### ISSUE TITLE
@interface breaks syntax highlighting

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1019]
When adding a @annotation interface the syntax highlighting breaks

- OSX 10.12.6
All latest versions of date of writing

correct:
<img width="209" alt="Screen Shot 2019-08-05 at 09 03 58" src="https://user-images.githubusercontent.com/738650/62445433-7b9ad980-b760-11e9-9d1f-e62cb6c8fe6b.png">

with annotation:
<img width="305" alt="Screen Shot 2019-08-05 at 09 03 13" src="https://user-images.githubusercontent.com/738650/62445447-82c1e780-b760-11e9-9004-c025004cd96b.png">

(Also using a $ will break the syntax of the return type).

**Comment by clankill3r** [comment]
This one is even worse, notice that the commented line is not commented at all:

<img width="317" alt="Screen Shot 2019-08-05 at 10 11 14" src="https://user-images.githubusercontent.com/738650/62448998-69716900-b769-11e9-91aa-d7286cbab397.png">

**Comment by fbricon** [comment]
It seems this only breaks when the `@interface` is not a top level type.

The issue needs to be reported for the upstream textmate grammar for Java that vscode embeds. See: 
- https://github.com/microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json
- https://github.com/atom/language-java.

**Comment by clankill3r** [comment]
https://github.com/microsoft/vscode/issues/79892

**Comment by clankill3r** [comment]
https://github.com/atom/language-java/issues/203

**Comment by Eskibear** [comment]
It works now 

<img width="346" alt="Screen Shot 2019-11-21 at 3 49 55 PM" src="https://user-images.githubusercontent.com/2351748/69317752-9b55ff00-0c76-11ea-8a2d-53b8b87b1e05.png">

**Comment by fbricon** [comment]
Closing since this is fixed in latest VS Code
