### ISSUE TITLE
new feature: Be able to find duplicated code

### ISSUE THREAD

**Issue by scgm11** [redhat-developer/vscode-java#102]
Most IDEs highlight duplicated code, so improve programing to be able to refactor manually but at least a way to find out.

**Comment by fbricon** [comment]
We currently don't have the resources to work on that kind of static analysis tools. You can certainly find [3rd party extensions](https://marketplace.visualstudio.com/items?itemName=paulhoughton.vscode-jscpd) providing that kind of feature.

**Comment by gorkem** [comment]
This probably should be resolved on extensions that use static analyzers or similar solutions. Closing.
