### ISSUE TITLE
Javadoc popups doesn't show documented annotation

### ISSUE THREAD

**Issue by niudai** [redhat-developer/vscode-java#1036]
[provide a description of the issue]

##### Environment
- Operating System: Microsoft Windows 10 Pro Insider Preview
- JDK version: 1.8
- Visual Studio Code version: 1.3.7
- Java extension version: newest

##### Steps To Reproduce
1. Add an annotation to a class or a method, but the javadoc popup doesn't show the annotation.
![image](https://user-images.githubusercontent.com/44165182/63355601-f6870580-c398-11e9-8a88-50cd38608b9b.png)

The annotation has @Documented annotation on it, so the javadoc should show the annotation in terms of the java oracle standard.

This is not a bug, but a good feature to be implemented.

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
You want the javadoc from the annotations added to the javadoc of the class?
Does that feature exist in other IDEs? If so a screenshot would help better understand.
