### ISSUE TITLE
organize imports selects wrong lib, no way to correct it

### ISSUE THREAD

**Issue by lonpalmer** [redhat-developer/vscode-java#1038]
When trying to use @Getter and @Setter from Lombok (lombok.Getter, lombok.Setter), the auto import feature keeps importing @Getter and @Setter from jdk.nashorn.internal.objects.annotations and gives me no opportunity to correct it.  

##### Environment
- Operating System: Windows
- JDK version: 1.8
- Visual Studio Code version: 1.37.1
- Java extension version: 0.47.0

##### Steps To Reproduce
1. Maven Project, use Lombok 1.18.8
2. Create a POJO and annotate it with "@Getter"

##### Current Result
auto import only grabs jdk.nashorn.internal.objects.annotations.Getter.  No ability to correct it as it overwrites my changes "e.g. import lombok.Getter gets over written" 

##### Expected Result
Either allow me to disambiguate manually or don't over write my changes if I edit imports. 

##### Additional Information
I have to disable "auto organize imports" just to use VS code with java.

**Comment by fbricon** [comment]
Works for me. I don't even get Nashorn annotations proposed when autocompleting. 
![lombok-ok](https://user-images.githubusercontent.com/148698/63389353-c39a3d00-c3ab-11e9-8cfe-b145eadeb051.gif)

Can you share a sample project (including .classpath, .settings/) reproducing the error?

**Comment by lonpalmer** [comment]
I don't get the red underlines like you do. It simply organizes my imports automatically.  Do you have "automatic organize imports" enabled in your config?

**Comment by lonpalmer** [comment]
Also, this may have to do with me using Spock (Groovy) in my project.  I think they might use Nashorn as a script runner and that might be where the imports engine is getting confused.

**Comment by fbricon** [comment]
I set "java.saveActions.organizeImports": true, but I don't have autosave enabled.
The funny thing is, when running with JDK 1.8, I get no automatic import on save (there must be some ambiguous results), but it works with JDK 11.

Again, a sample project reproducing the issue would help

**Comment by lonpalmer** [comment]
After a few restarts and some refactoring to try to send you code, I now see what you're seeing.

I'm not getting automatic organize imports any more, but I am getting the chance to pick "lombok.Getter" when I click the yellow light bulb.  Still want the sample project?

**Comment by fbricon** [comment]
Not useful if we can't reproduce. Can you at least share your project's pom, .classpath, .project and .settings/ ?

**Comment by rafaelrenanpacheco** [comment]
Lombok imports are ok for me as well when using organize imports on maven projects. I saw that wrong import once when I opened a .java file without any project related (open a new workspace and open a random .java file), then organize imports imported the wrong lib. But I didn't care because I was not in a maven project, and was just testing some themes.
