### ISSUE TITLE
How to use javac option with the following project setup

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1042]
My project is setup like this:
https://github.com/clankill3r/p5_vscode_template

In short I have a `.classpath` and a `.project` and eventually a `launch.json`.
Now I would like to use the `javac` `-parameters` option. Is this possible?

I don't wan't to use maven or gradle.

**Comment by fbricon** [comment]
create a .settings/org.eclipse.jdt.core.prefs file containing: 
```
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
org.eclipse.jdt.core.compiler.compliance=1.8
org.eclipse.jdt.core.compiler.problem.assertIdentifier=error
org.eclipse.jdt.core.compiler.problem.enumIdentifier=error
org.eclipse.jdt.core.compiler.source=1.8
org.eclipse.jdt.core.compiler.codegen.methodParameters=generate
```
`org.eclipse.jdt.core.compiler.codegen.methodParameters=generate` is the property equivalent to  the `-parameter` flag in javac

**Comment by clankill3r** [comment]
Thank you so much for this quick answer.
