### ISSUE TITLE
The extension download binaries without asking

### ISSUE THREAD

**Issue by marmistrz** [redhat-developer/vscode-java#1043]
It's ok to provide easy onboarding, but the extension should ask before downloading anything. What if the user is on a metered connection or prefers to install the language server themselves.

That's what the official Rust Language Server extension for VS Code does.

##### Environment
- Operating System: Arch Linux
- JDK version: 12
- Visual Studio Code version: 1.37
- Java extension version: 0.47.0

(other sections are N/A)

**Comment by fbricon** [comment]
Which binaries? (I suspect the Gradle runtime)

**Comment by marmistrz** [comment]
I've just realized that I mistook the prebuilt language server that is shipped with the .vsix for some binaries downloaded from the Internet after installation. Sorry for that!

Anyway, I think that shipping the binaries with the .vsix is not the best idea. As a Linux user, I have my package manager for this ([link](https://aur.archlinux.org/packages/jdtls/)). The way I see it:

* the extension should not ship any binaries, be as lightweight as possible
* the extension should look for jdtls on `$PATH`
* if jdtls is not available in PATH, the extension proposes to download the binaries for the OS, which are downloaded if and only if the user agrees to

This enables to reuse the language server between different editors.
