### ISSUE TITLE
when use chinese even can‘t compile

### ISSUE THREAD

**Issue by bonaluo** [redhat-developer/vscode-java#1045]
Issue Type: <b>Bug</b>

I can't compile because i have chinese in class's comment . When i remove chinese comment it can compile again. I use 'code runner'  extension to run single java class, it is very convenient.

![unreadable code](https://user-images.githubusercontent.com/27731323/63844212-63faed80-c9ba-11e9-89c9-c6284b1e17e2.png)
![can't compile](https://user-images.githubusercontent.com/27731323/63844218-65c4b100-c9ba-11e9-8fee-71931a198ee5.png)

Extension version: 0.47.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bonaluo** [comment]
I delete three chinese letter "问顺序" then it hasn't warned again.

![image](https://user-images.githubusercontent.com/27731323/63844888-95c08400-c9bb-11e9-843d-1e518de2755f.png)

**Comment by jdneo** [comment]
Running code via `code runner` is out of the scope of this extension.
