### ISSUE TITLE
Attaching debugger causes temporary java file to be created 

### ISSUE THREAD

**Issue by gitorko** [redhat-developer/vscode-java#1046]
Attaching a debugger and inserting a break point is causing a temporary .java file to be created under following location
/home/user/.config/Code/User/workspaceStorage/7be5e099f5eab375ac8263262a29bd8f/shengchen.vscode-checkstyle/sync/11237118ee2d10dd6bc3775ae5da8a98/MyClass.java

This wasnt the case earlier (a few releases back), the breakpoint used to hit on the same class file and not create a temporary class file. The source and destination jvm version is same.

Server running via terminal command
./gradlew bootRun --debug-jvm

Debugger attached
{
"type": "java",
"name": "Debug (Attach) - Remote",
"request": "attach",
"hostName": "localhost",
"port": 5005
}

Extension version: 0.7.1
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.0.0-25-generic

**Comment by testforstephen** [comment]
Looks like the temporary file is created by checkstyle extension. @jdneo could you take a look?

**Comment by fbricon** [comment]
Issue should be fixed downstream: https://github.com/jdneo/vscode-checkstyle/issues/224
