### ISSUE TITLE
Auto Completion swallows the code

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#1047]
##### Environment
- Operating System: Win 10
- JDK version: 1.8.0_221
- Visual Studio Code version: 1.37.1
- Java extension version: 0.47.0

##### Steps To Reproduce
![demo](https://user-images.githubusercontent.com/6193897/63987885-55bce680-cb0c-11e9-891c-3ddddea8eae9.gif)

##### Current Result

As the gif shows, the variable `myStrings[0]` will be swallowed after we select a completion item.

**Comment by snjeza** [comment]
You can try to set the following property:
```
"java.completion.overwrite": false,
```

**Comment by jdneo** [comment]
Thanks @snjeza . Setting it to false solves my issue.

While, IMO, default value to false seems makes more sense to me. 😃
