### ISSUE TITLE
symbol java visual studio code

### ISSUE THREAD

**Issue by ghost** [redhat-developer/vscode-java#1049]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10
- JDK version: jdk-12.0.2
- Visual Studio Code version: 1.37.1 (user setup)
- Java extension version: VSCodeJavaInstaller-online-win-0.1.1

Good morning

I have followed the visual studio code installation, and even several times, deleting configuration folders. but even so I get this error message and also when I create a java file, the java symbol does not appear, I use Windows10 and I have installed JDK with the JAVA_HOME and path environment variables, I need help,

Attached captures:
https://github.com/Rypleyx/images/blob/master/README.md

Thanks.

**Comment by TobyLarone85** [comment]
The icon is part of your vscode icons theme. Go to settings -> File Icon Set and select the set of icons you want
