### ISSUE TITLE
java.errors.incompleteClasspath.severity is not working

### ISSUE THREAD

**Issue by DanielMoreno58** [redhat-developer/vscode-java#1050]
I tried to ignore the errors of java, specifically of imports due to I dont want to show them with java.errors.incompleteClasspath.severity, but even with that configuration i don't get the expected result.

##### Environment
- Operating System: Windows 7 Professional
- JDK version: 1.8
- Visual Studio Code version: 1.37.1
- Java extension version: 0.47

##### Steps To Reproduce
1. Open extension settings
2. Rewrite "java.errors.incompleteClasspath.severity" to "ignore"
3. Expect not to show error messages in log with java imports.

##### Current Result

Errors in import:
![imagen](https://user-images.githubusercontent.com/25211032/64128351-bf8ef780-cd7b-11e9-8bda-d4cc7505d46e.png)

##### Expected Result

What I expect after configuration:
![imagen](https://user-images.githubusercontent.com/25211032/64128377-e6e5c480-cd7b-11e9-9897-a8c8e96903e5.png)

**Comment by fbricon** [comment]
this setting is actually for errors caused by vscode-java's inability to properly compute the project classpath from a build descriptor.
If your project actually has a Maven, Gradle or even Eclipse descriptor, then compilation errors will be computed, regardless of the "java.errors.incompleteClasspath.severity" value.
How is your project configured?

**Comment by DanielMoreno58** [comment]
Oh, I see!

My project is currently configured with Maven with `<modelVersion> 4.0.0 </modelVersion>`

But, in my pom.xml i have the correct dependencies, for example:

![imagen](https://user-images.githubusercontent.com/25211032/64129185-3b8b3e80-cd80-11e9-97f7-cec9a325a193.png)

**Comment by fbricon** [comment]
you might have some other errors in your problems view that cause the project classpath to be incorrectly resolved. Can you please list them? or attach your project?
