### ISSUE TITLE
Cannot create Java project with RED Hat Extension installed and java openJDK8 installed in WSL

### ISSUE THREAD

**Issue by JacobGeoGeek** [redhat-developer/vscode-java#1052]
hello everyone, 
Show I have java jdk 8 in WSL and i trying to create java project with Red Hat extension. but whenever i click `CTRL+SHIT+P` and i choose Create Java project, I have this Error:

```
EPERM: operation not permitted, copyfile '/home/jacobchaar/.vscode-server/extensions/vscjava.vscode-java-dependency-0.5.1/templates/.project' -> '/mnt/c/Users/jacob/Documents/Programmation/Java/Tuto/HelloWorld/.project'
```

Note that I use Remote WSL

**Comment by fbricon** [comment]
Sorry but "Create Java project" is not a feature coming from vscode-java. Please open a ticket in https://github.com/Microsoft/vscode-java-dependency/issues
