### ISSUE TITLE
Selecting the content of the suggested smart prompt directly before the existing content will replace the existing content. 

### ISSUE THREAD

**Issue by czfadmin** [redhat-developer/vscode-java#1058]
When inserting some content before an existing character, if you do not add a space before the existing content, the content selected by using Enter will replace the existing content, which is different from the expected result.

![image](https://user-images.githubusercontent.com/13393959/64830294-6a1bdb80-d602-11e9-90e0-ef67c636f682.gif)

![image2](https://user-images.githubusercontent.com/13393959/64830299-71db8000-d602-11e9-8e60-7916247118bd.gif)

- JDK version: 1.8 
- Visual Studio Code version:1.38.1
- Java extension version:0.8.0
- Extension version: 0.7.1
- VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
- OS version: Windows_NT x64 10.0.18362

**Comment by snjeza** [comment]
See https://github.com/redhat-developer/vscode-java/issues/1047#issuecomment-526427181

**Comment by czfadmin** [comment]
I've set this option to False, but it's still going to work out like this.

**Comment by JoeyRxy** [comment]
> I've set this option to False, but it's still going to work out like this.

@czfadmin  you sure you make `java.completion.overwrite` to False? Cause there's a similar setting `editor.suggest.insertMode` which won't work for java extension, hope u not confusing them.

**Comment by czfadmin** [comment]
@JoeyRxy Yes, I did send this set ` false `, at the same time I put option ` editor. Suggest. InsertMode ` of content to try again, you can still have this phenomenon.

**Comment by rgrunber** [comment]
Looks like we're going to reconsider the default in the above newly listed issue. Closing this one so discussion can happen in the new issue.
