### ISSUE TITLE
Move deprecated classes lower down in the import order list

### ISSUE THREAD

**Issue by ThadHouse** [redhat-developer/vscode-java#1063]
Our users are getting confused, because over the past few years we have been repackaging our classes to enable modules, but deprecating classes in the original package.  These classes, depending on the package, show up higher in the list of selectable imports and causes confusion to our users. It would be nice if deprecated classes would be moved to the bottom of the list. Or maybe an option to make that configurable.

**Comment by snjeza** [comment]
You can try to use the java.completion.importOrder property.
