### ISSUE TITLE
High Cpu utilization in vscode build 1.38.1

### ISSUE THREAD

**Issue by gitorko** [redhat-developer/vscode-java#1069]
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:30:08.229Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-27-generic

After upgrading to 1.38.1 i have started noticing high cpu utilization when using vscode. The top process consuming 90% CPU is the java process. This happens occasionally and havent been able to determine a particular sequence of steps that will cause this to occur.
Oddly enough every time it is says 'Publishing Diagnostics' the CPU touches 100%. I didnt see this message in the version 1.38.0 so not sure if its related.

asurend+ 16778 16623 99 15:00 tty2     00:06:21 /opt/jdk-1.8.0_181/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:/home/asurendra/.vscode/extensions/gabrielbb.vscode-lombok-0.9.9/server/lombok.jar -jar /home/asurendra/.vscode/extensions/redhat.java-0.49.0/server/plugins/org.eclipse.equinox.launcher_1.5.500.v20190715-1310.jar -configuration /home/asurendra/.vscode/extensions/redhat.java-0.49.0/server/config_linux -data /home/asurendra/.config/Code/User/workspaceStorage/ce82c6256cb05ece372e339a42f6de5b/redhat.java/jdt_ws

Even after doing a 'Clean the java language server workspace' the CPU keeps touching 100% utilization.

Java Language server logs:

>[Error - 3:13:13 PM] 19 Sep, 2019 3:13:13 PM Problem with folding range for /assessment-service/src/test/java/com/vmware/assessment/common/helper/TestCommonUtils.java
>Invalid_Char_In_String
>org.eclipse.jdt.core.compiler.InvalidInputException: Invalid_Char_In_String
>	at org.eclipse.jdt.internal.core.util.PublicScanner.getNextToken(PublicScanner.java:1470)
>	at org.eclipse.jdt.ls.core.internal.handlers.FoldingRangeHandler.computeFoldingRanges(FoldingRangeHandler.java:110)
>	at org.eclipse.jdt.ls.core.internal.handlers.FoldingRangeHandler.foldingRange(FoldingRangeHandler.java:61)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:789)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$46(JDTLanguageServer.java:941)
>	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
>	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
>	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
>	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
>
>[Error - 3:13:13 PM] 19 Sep, 2019 3:13:13 PM Problem with folding range for /assessment-service/src/test/java/com/vmware/assessment/common/helper/TestCommonUtils.java
>Unterminated_Comment
>org.eclipse.jdt.core.compiler.InvalidInputException: Unterminated_Comment
>	at org.eclipse.jdt.internal.core.util.PublicScanner.getNextToken(PublicScanner.java:1725)
>	at org.eclipse.jdt.ls.core.internal.handlers.FoldingRangeHandler.computeFoldingRanges(FoldingRangeHandler.java:110)
>	at org.eclipse.jdt.ls.core.internal.handlers.FoldingRangeHandler.foldingRange(FoldingRangeHandler.java:61)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:789)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$46(JDTLanguageServer.java:941)
>	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
>	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
>	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
>	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
>
>[Warn  - 3:15:56 PM] 19 Sep, 2019 3:15:56 PM Cannot collect dependency scope information for launch configuration 1568886356134
>The input type of the launch configuration does not exist
>org.eclipse.core.runtime.CoreException: The input type of the launch configuration does not exist
>	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.abort(JUnitLaunchConfigurationDelegate.java:752)
>	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getTestTarget(JUnitLaunchConfigurationDelegate.java:746)
>	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.evaluateTests(JUnitLaunchConfigurationDelegate.java:347)
>	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType$RelaxedJUnitLaunchConfigurationDelegate.evaluateTests(SupportedLaunchConfigType.java:138)
>	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType$2.getSourceFolders(SupportedLaunchConfigType.java:69)
>	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType.collectSourceFolders(SupportedLaunchConfigType.java:109)
>	at org.eclipse.buildship.core.internal.launch.LaunchConfigurationScope.from(LaunchConfigurationScope.java:56)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.filterUnusedDependencies(GradleClasspathProvider.java:70)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.computeUnresolvedClasspath(GradleClasspathProvider.java:60)
>	at org.eclipse.jdt.internal.launching.RuntimeClasspathProvider.computeUnresolvedClasspath(RuntimeClasspathProvider.java:60)
>	at org.eclipse.jdt.launching.JavaRuntime.computeUnresolvedRuntimeClasspath(JavaRuntime.java:1642)
>	at com.microsoft.java.test.plugin.util.RuntimeClassPathUtils.resolveClasspath(RuntimeClassPathUtils.java:86)
>	at com.microsoft.java.test.plugin.util.RuntimeClassPathUtils.resolveRuntimeClassPath(RuntimeClassPathUtils.java:77)
>	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:42)
>	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:213)
>	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
>	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:203)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:462)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$45(JDTLanguageServer.java:935)
>	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
>	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
>	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
>	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
>
>[Warn  - 3:15:56 PM] 19 Sep, 2019 3:15:56 PM Cannot collect dependency scope information for launch configuration 1568886356134
>The input type of the launch configuration does not exist
>org.eclipse.core.runtime.CoreException: The input type of the launch configuration does not exist
>	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.abort(JUnitLaunchConfigurationDelegate.java:752)
>	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getTestTarget(JUnitLaunchConfigurationDelegate.java:746)
>	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.evaluateTests(JUnitLaunchConfigurationDelegate.java:347)
>	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType$RelaxedJUnitLaunchConfigurationDelegate.evaluateTests(SupportedLaunchConfigType.java:138)
>	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType$2.getSourceFolders(SupportedLaunchConfigType.java:69)
>	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType.collectSourceFolders(SupportedLaunchConfigType.java:109)
>	at org.eclipse.buildship.core.internal.launch.LaunchConfigurationScope.from(LaunchConfigurationScope.java:56)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveProject(GradleClasspathProvider.java:144)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveProject(GradleClasspathProvider.java:128)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveClasspath(GradleClasspathProvider.java:97)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveOther(GradleClasspathProvider.java:117)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveClasspath(GradleClasspathProvider.java:94)
>	at org.eclipse.jdt.internal.launching.RuntimeClasspathProvider.resolveClasspath(RuntimeClasspathProvider.java:68)
>	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1690)
>	at com.microsoft.java.test.plugin.util.RuntimeClassPathUtils.resolveClasspath(RuntimeClassPathUtils.java:87)
>	at com.microsoft.java.test.plugin.util.RuntimeClassPathUtils.resolveRuntimeClassPath(RuntimeClassPathUtils.java:77)
>	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:42)
>	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:213)
>	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
>	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:203)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:462)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$45(JDTLanguageServer.java:935)
>	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
>	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
>	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
>	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
>
>[Warn  - 3:15:56 PM] 19 Sep, 2019 3:15:56 PM Cannot collect dependency scope information for launch configuration 1568886356134
>The input type of the launch configuration does not exist
>org.eclipse.core.runtime.CoreException: The input type of the launch configuration does not exist
>	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.abort(JUnitLaunchConfigurationDelegate.java:752)
>	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getTestTarget(JUnitLaunchConfigurationDelegate.java:746)
>	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.evaluateTests(JUnitLaunchConfigurationDelegate.java:347)
>	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType$RelaxedJUnitLaunchConfigurationDelegate.evaluateTests(SupportedLaunchConfigType.java:138)
>	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType$2.getSourceFolders(SupportedLaunchConfigType.java:69)
>	at org.eclipse.buildship.core.internal.launch.SupportedLaunchConfigType.collectSourceFolders(SupportedLaunchConfigType.java:109)
>	at org.eclipse.buildship.core.internal.launch.LaunchConfigurationScope.from(LaunchConfigurationScope.java:56)
>	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:46)
>	at org.eclipse.jdt.internal.launching.RuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(RuntimeClasspathEntryResolver.java:49)
>	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:1266)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveClasspath(GradleClasspathProvider.java:100)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveOther(GradleClasspathProvider.java:117)
>	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveClasspath(GradleClasspathProvider.java:94)
>	at org.eclipse.jdt.internal.launching.RuntimeClasspathProvider.resolveClasspath(RuntimeClasspathProvider.java:68)
>	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1690)
>	at com.microsoft.java.test.plugin.util.RuntimeClassPathUtils.resolveClasspath(RuntimeClassPathUtils.java:87)
>	at com.microsoft.java.test.plugin.util.RuntimeClassPathUtils.resolveRuntimeClassPath(RuntimeClassPathUtils.java:77)
>	at com.microsoft.java.test.plugin.handler.TestDelegateCommandHandler.executeCommand(TestDelegateCommandHandler.java:42)
>	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:213)
>	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
>	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:203)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:462)
>	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$45(JDTLanguageServer.java:935)
>	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
>	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
>	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
>	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
>

**Comment by fbricon** [comment]
Can you reproduce the problem after disabling all other extensions?

**Comment by gitorko** [comment]
I am unable to reproduce this now. May be it was some build issue or checkstyle plugin issue. Interestingly i dont see the 'Publishing Diagnostics' message anymore as well.
