### ISSUE TITLE
Running Spring boot application via launch.json prints classpath and exits

### ISSUE THREAD

**Issue by mkkhedawat** [redhat-developer/vscode-java#1071]
##### Environment
- Operating System: MAC OSX
- JDK version: 11
- Visual Studio Code version: 1.36.1
- Java extension version: latest

##### Steps To Reproduce
1. Create a new spring-boot project via JAVA: Overview
2. Go to Main.java and run the application

##### Current Result
Running the application via Gradle works fine but not via clicking run link in Main.java

##### Expected Result

Running application by clicking run should behave normally like Gradle

**Comment by fbricon** [comment]
vscode-java itself doesn't provide support for running the code. Please report this issue in https://github.com/microsoft/vscode-java-debug/issues
