### ISSUE TITLE
autocomplete didn't show all public method when coding Java swing

### ISSUE THREAD

**Issue by ymyh** [redhat-developer/vscode-java#1072]
[provide a description of the issue]

##### Environment
- Operating System: win10 1909
- JDK version: 1.8
- Visual Studio Code version: 1.38.1
- Java extension version: latest

didn't show more item inside awt.
![image](https://user-images.githubusercontent.com/42105828/65383388-95f83900-dd47-11e9-866a-84775aae011a.png)

didn't show actionListener even I  import java.awt.event.* manually.
![image](https://user-images.githubusercontent.com/42105828/65383395-b0321700-dd47-11e9-8972-54d9579b85ed.png)

didn't show the method add(). But if I write it down manually and hover the mouse on it, vscode shows me details as usual.
![image](https://user-images.githubusercontent.com/42105828/65383427-1e76d980-dd48-11e9-9672-32a766b5810e.png)

##### Expected Result
show all public method
##### Additional Informations
Working well few days ago, it seems didn't work suddenly.

**Comment by fbricon** [comment]
This is due to java.awt.* packages now being excluded from autocompletion/import by default (See #710).
Simply remove java.awt.* from the list of excluded packages in `java.completion.filteredTypes` in your settings.json.

**Comment by xendren** [comment]
I am having the same problem with javax.swing.* components.  I have checked my settings file, and there aren't any "java.completion.filteredTypes" entries in my settings files.  I do not see the default value of "java.awt.*" as indicated in the last post.

**Comment by ymyh** [comment]
> I am having the same problem with javax.swing.* components. I have checked my settings file, and there aren't any "java.completion.filteredTypes" entries in my settings files. I do not see the default value of "java.awt.*" as indicated in the last post.

You should type "java.completion" first, then you will see it.

**Comment by xendren** [comment]
Interesting.  So the setting will not show unless you add it first?  That's odd behavior.  Once I add it, it defaults only the "java.awt.*" and "com.sun.*" classes.  Neither of those entries should be filtering the javax.swing.* class methods.  If I import "javax.swing.JTextField", for instance, create a new instance and type "myField.setName", the method does not show in code completion box.  It seems most of the setters and getters are missing.

**Comment by ymyh** [comment]
> Interesting. So the setting will not show unless you add it first? That's odd behavior. Once I add it, it defaults only the "java.awt._" and "com.sun._" classes. Neither of those entries should be filtering the javax.swing.* class methods. If I import "javax.swing.JTextField", for instance, create a new instance and type "myField.setName", the method does not show in code completion box. It seems most of the setters and getters are missing.

well... I don't know this time.

**Comment by omokolataiwo** [comment]
> Interesting. So the setting will not show unless you add it first? That's odd behavior. Once I add it, it defaults only the "java.awt._" and "com.sun._" classes. Neither of those entries should be filtering the javax.swing.* class methods. If I import "javax.swing.JTextField", for instance, create a new instance and type "myField.setName", the method does not show in code completion box. It seems most of the setters and getters are missing.

You also need to increase the value of Java>Completion:Max Results. It is defaulted to 50 for performance reasons.

**Comment by MuhammadimYusoff** [comment]
> This is due to java.awt.* packages now being excluded from autocompletion/import by default (See #710).
> Simply remove java.awt.* from the list of excluded packages in `java.completion.filteredTypes` in your settings.json.

I cant understand this because I have issues with the 'javax.swing.*' and GUI related Libraries. 
Can someone explain this step-by-step on how to do this? 
Maybe some screenshot?

**Comment by Marian-Tataru** [comment]
Since the file settings.json is read-only puroposes  , to remove the package java.awt.* from the java.completion.filteredTypes  you have to do the following : 1) press ctrl + shift + P   2) write : open user settings  3)  ctrl +f and search for java.completion.filteredTypes  . Then you can edit  json and exclude java.awt.* .
