### ISSUE TITLE
Move... refactoring everywhere

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#1074]
When my cursor stays on any non-empty line, there's always a yellow bulb containing "Move..." refactoring action for current method. 

![mov](https://user-images.githubusercontent.com/2351748/65398924-8da60980-ddec-11e9-8ec8-9a951410631b.gif)

For me, it's a little bit noisy, and it would be better if it: 
- a) Shows "Move..." **only** under "Refactor..."
or
- b) Shows "Move..." **only** when cursor is on the signature.

##### Environment
- Operating System: any
- JDK version: OpenJDK8
- Visual Studio Code version: 1.38.1
- Java extension version: 0.49.0

**Comment by Eskibear** [comment]
> Right now when I open quickfix (cmd+.) it always suggests "Move..." and in what feels like 95% of the cases it always errors with "this method cannot be moved, since no possible targets have been..".

And it's also reported in #1068 that it somehow brings a little bit noise instead of help.

**Comment by maxandersen** [comment]
+100 on making this operation show up when its most likely possible (when put on proper symbols) rather than show up always.

**Comment by Eskibear** [comment]
Below is current behavior in v0.65.0: 
```java
package com.example;			// <-- Move `Foo.java`
					// <-- Move `Foo.java`
public class Foo {			// <-- Move `Foo.java`
					// <-- Move `Foo.java`
  private String bar; 	 		// <-- N/A
  public static String barStatic;	// <-- Move `barStatic`
					// <-- Move `Foo.java`
  public void method() {		// <-- Move `method()`, but fail with error.
    System.out.println("body");		// <-- Move `method()`, but fail with error.
  }					// <-- Move `method()`, but fail with error.
					// <-- Move `Foo.java`
  public static void staticMethod() {	// <-- Move `staticMethod()`
					// <-- Move `staticMethod()`
  }					// <-- Move `staticMethod()`
					// <-- Move `Foo.java`
  public class InnerFoo {		// <-- Move `InnerFoo`
					// <-- Move `InnerFoo`
  }					// <-- Move `InnerFoo`
}					// <-- Move `Foo.java`
```

To remove the noise as much as possible, I suggest not to show the Move action when cursor is in the body (both class body and method body). By showing "Move..." only on the signature, I assume it would look like below:
```java
package com.example;			// <-- N/A
					// <-- N/A
public class Foo {			// <-- Move `Foo.java`
					// <-- N/A
  private String bar; 	 		// <-- N/A
  public static String barStatic;	// <-- Move `barStatic`
					// <-- N/A
  public void method() {		// <-- N/A
    System.out.println("body");		// <-- N/A
  }					// <-- N/A
					// <-- N/A
  public static void staticMethod() {	// <-- Move `staticMethod()`
					// <-- N/A
  }					// <-- N/A
					// <-- N/A
  public class InnerFoo {		// <-- Move `InnerFoo`
					// <-- N/A
  }					// <-- N/A
}					// <-- N/A
```

**Comment by fbricon** [comment]
+1
