### ISSUE TITLE
JVM is always running. 

### ISSUE THREAD

**Issue by zhangqiannh** [redhat-developer/vscode-java#1078]
[provide a description of the issue]

##### Environment
- Operating System: Win10
- JDK version:jdk1.8.0_162
- Visual Studio Code version:1.38.1
- Java extension version:
Java Extension Pack 0.8.0
Language Support for Java(TM) by Red Hat redhat.java 0.49.0

##### Steps To Reproduce
When I open a maven project, tips tell me a starting a Java language Server.
I think it's compiling，so JVM starts.
but  JVM is always running and doesn't stop! why?
##### Current Result
JVM is always running. 
##### Expected Result
JVM stops automatically after compilation 
![Javaprocess](https://user-images.githubusercontent.com/55779832/65575427-5c6f3a00-dfa2-11e9-884d-e3de13c0d76f.png)
unless I need to run a project

**Comment by Eskibear** [comment]
> A Language Server is meant to provide the language-specific smarts and communicate with development tools over a protocol that enables inter-process communication.

Refer to [LSP](https://microsoft.github.io/language-server-protocol/), it is not a compiler.

**Comment by fbricon** [comment]
the Java process is running in the background to provide linting, compilation, general Java tooling support when in vscode. It's totally expected it keeps running while once activated in vscode, until vscode itself is closed.
