### ISSUE TITLE
class and interface snippet

### ISSUE THREAD

**Issue by simahao** [redhat-developer/vscode-java#1082]
Hi,i want to know this plugin how to insert class and interface snippets, i cannt find any snippets config in snippets/java.json file, but when you input class or interface, snippet is inserted. thanks.

**Comment by fbricon** [comment]
Those snippets come from the Java Language server (https://github.com/eclipse/eclipse.jdt.ls/). There's no way to contribute to those server side snippets at this time. Maybe this will become possible after we fix https://github.com/eclipse/eclipse.jdt.ls/issues/977.

In the meantime, you can provide your own java snippets by following the instructions at https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by simahao** [comment]
thanks for your reply.
