### ISSUE TITLE
Include folders to import

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#1084]
importing quarkus repo I end up with an almost impossible vscode which keeps waiting on maven to refresh on every java related action.

Was suggested to use `java.import.exclusions` to tell which projects to not import.

That’s rather tedious and I was realizing if I could just do `java.import.exclusions=**` and then `java.import.inclusions=integration-tests/maven/*,devtools/*' then I would be good.

As opposed to listing ~300 individual lines in exclusion.

Pretty please :)

**Comment by fbricon** [comment]
@maxandersen as usual with that kind of thing, there's always the problem of who takes precedence.
In your exemple java.import.inclusions takes precedence over java.import.exclusions, to a point where it would not even be necessary to define `java.import.exclusions=**`
But then, what if someone needed to include=foo/**, but exclude=foo/bar/** ?

**Comment by maxandersen** [comment]
Alternatively adopt the convention/format of things like .gitignore/.dockerignore where a "!" negates the pattern. see https://git-scm.com/docs/gitignore#_pattern_format

Then it would be:
`java.import.exclusions=foo/bar/**,!foo/**`

**Comment by hanct** [comment]
> ```json
> "java.import.exclusions": [
>         "**/node_modules/**",
>         "**/.metadata/**",
>         "**/archetype-resources/**",
>         "**/META-INF/maven/**",
>         "**/quarkus/**",
>         "!**/quarkus",
>         "!**/quarkus/build-parent",
>         "!**/quarkus/bom",
>         "!**/quarkus/bom/*",
>         "!**/integration-tests",
>         "!**/integration-tests/maven",
>         "!**/devtools/*",
>         "**/devtools/gradle"
>     ]
> ```
> 
> You have to include a parent directory. The order is important.

what does it mean by "include a parent directory"?  How does the ordering works? Wonder if there is any guide that explains this in details.

**Comment by snjeza** [comment]
> what does it mean by "include a parent directory"? How does the ordering works? Wonder if there is any guide that explains this in details.

if you want to include only the **/quarkus/bom/*, you have to set the following:
```
"java.import.exclusions": [
...
        "**/quarkus/**", // exclude **/quarkus/**
        "!**/quarkus", // include **/quarkus - parent
        "!**/quarkus/bom", // include **/quarkus/bom - parent
        "!**/quarkus/bom/*", //  // include **/quarkus/bom/*
...
    ]
```
**!** means _include_ instead of _exclude_.
