### ISSUE TITLE
Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 13

### ISSUE THREAD

**Issue by xCuri0** [redhat-developer/vscode-java#1086]
Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 13

##### Environment
- Operating System: Windows 10 x64
- JDK version: tested OpenJDK 11, Oracle JDK 12, Oracle JDK 13
- Visual Studio Code version: 1.38.1 (user setup)
- Java extension version: 0.50

##### Steps To Reproduce
1. Start the program
2. You will get the error

```
public class HelloWorld {
    public static void main(String[] args) {
       System.out.println("Hello world!");
    }
 }
```
##### Current Result
```
[Error - 12:22:14 PM] Oct 3, 2019, 12:22:14 PM Error occured while building workspace. Details: 
 message: Preview features enabled at an invalid source release level 12, preview can be enabled only at source level 13; code: 2098258; resource: D:/Documents/workspace/HelloWorld.java;
```
in language support for java log
##### Expected Result
Compile and run

**Comment by fbricon** [comment]
can you try running the "Java: clean the Java language server workspace" command?

**Comment by Halfbax** [comment]
Updating to the latest version helped me. (12.01 to 13 Build 33)
