### ISSUE TITLE
Object update failed

### ISSUE THREAD

**Issue by FERViborg** [redhat-developer/vscode-java#1087]
Issue Type: <b>Bug</b>

1. Declare Integer, String or Boolean variable in code.
2. Debug code.
3. In "VARIABLES" view find variable and try to modiy value.
--> In "OUTPUT" view there is an error message:
Failed to set variable. Reason: java.lang.UnsupportedOperationException: SetVariableRequest: Final field value cannot be changed.
Currently, by using same JDK I can modifiy value in eclipse.

Extension version: 0.50.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by fbricon** [comment]
This feature is not provided by vscode-java. Please open a ticket in https://github.com/microsoft/vscode-java-debug/issues
