### ISSUE TITLE
is it a way to show all method suggestion

### ISSUE THREAD

**Issue by bgladosd** [redhat-developer/vscode-java#1093]
![image](https://user-images.githubusercontent.com/19308825/66709642-251ecc80-ed9b-11e9-8155-7784f8c95c28.png)

why the code suggestion above seems to be covering most of the frame.set functions but no frame.setSize();? 

and at line 6 i type it manually and it seems to be knowing what method it is

**Comment by snjeza** [comment]
@bgladosd could you try the following property:

``` 
"java.completion.filteredTypes" : [
        "java.awt.List",
        "com.sun.*"
    ],
```

**Comment by KingDarBoja** [comment]
@snjeza I will try your solution since I have the same issue whiletrying to display the methdos from some java libraries.

**Comment by fbricon** [comment]
Closing as it's working as expected, `java.completion.filteredTypes` preference needs to be changed to support java.awt..*

**Comment by bgladosd** [comment]
> @bgladosd could you try the following property:
> 
> ```
> "java.completion.filteredTypes" : [
>         "java.awt.List",
>         "com.sun.*"
>     ],
> ```

Thank you!!this really help a lot,this is the best portable java ide to me now
