### ISSUE TITLE
Java Dependencies not showing projects

### ISSUE THREAD

**Issue by sandeepamilineni** [redhat-developer/vscode-java#1094]
[provide a description of the issue]

##### Environment
JAVA_VERSION="1.8.0_201"
OS_VERSION="5.2"
OS_ARCH="amd64"
VSCODE Version: 1.39.1 (user setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

##### Steps To Reproduce

1. Install Java extension pack
2.  Import 4 existing maven projects.
3.  

I[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
![image](https://user-images.githubusercontent.com/2767069/66720839-76709f80-ee1f-11e9-92b5-8929d03f686a.png)

only 2 projects are visible in **Java Dependencies** section. 
##### Expected Result
All java projects should be visible in **Java Dependencies** section

**Comment by testforstephen** [comment]
Move it to https://github.com/microsoft/vscode-java-dependency/issues/189
