### ISSUE TITLE
Suggestions for java.awt not working

### ISSUE THREAD

**Issue by spvessel** [redhat-developer/vscode-java#1096]
Suggestions for the entire JAVA AWT library do not work:
Color:
![color](https://user-images.githubusercontent.com/45689928/66746658-1b749200-ee8b-11e9-969a-35b9dd100862.png)

Image:
![image](https://user-images.githubusercontent.com/45689928/66746686-2b8c7180-ee8b-11e9-877b-891ca9a7dd24.png)

Font:
![font](https://user-images.githubusercontent.com/45689928/66746704-321ae900-ee8b-11e9-97b4-d9bdda500a42.png)

But other java classes work fine:
![list](https://user-images.githubusercontent.com/45689928/66746729-452db900-ee8b-11e9-8c6d-2dcca2782337.png)

##### Environment
- Operating System: Windows 10 64 bit
- JDK version: Open JDK 13, Oracle JDK 8, Oracle JDK 13
- Visual Studio Code version: 1.39.1
- Java extension version: Java Extension Pack 0.8.0, Language support for Java 0.50.0

**Comment by snjeza** [comment]
@spvessel See https://github.com/redhat-developer/vscode-java/issues/1093#issuecomment-541450689

**Comment by spvessel** [comment]
> @spvessel See [#1093 (comment)](https://github.com/redhat-developer/vscode-java/issues/1093#issuecomment-541450689)

Thanks, it works
