### ISSUE TITLE
How can show completion tips in method bracket after previous completion

### ISSUE THREAD

**Issue by lvxingtu** [redhat-developer/vscode-java#1097]
[provide a description of the issue]

![Jietu20191015-101834](https://user-images.githubusercontent.com/22794227/66794799-47e4e880-ef35-11e9-986f-6fba10f092c8.gif)

The completion prompt will lost in the automatic completion method bracket. Only I end statement and then move the cursor to the front，the completion prompt reappear. So this behavior doesn't like other ide tools. Is there some configuration can solve it?

##### Environment
- Operating System:mac os, win 10 
- JDK version:openjdk 12.0.2
- Visual Studio Code version:newest
- Java extension version: 0.8.0

**Comment by fbricon** [comment]
When inserting the snippet, you're in "snippet mode", that'd allow you to cycle through potential placeholders with tab. In that mode, completion request are not issued (this is a VS Code thing, not us). Hit `Esc`, to exit the snippet mode, you should be able to get completions again.

**Comment by fbricon** [comment]
... or it might just be that the server is to slow to return completions

**Comment by lvxingtu** [comment]
@fbricon Thank you.  Hit Esc, it's work for me. But I use vim in vscode, so maybe I should look for other ways.

**Comment by Eskibear** [comment]
@lvxingtu Open command palette, "Trigger Suggest".  By default the shortcut is `ctrl + space`

**Comment by lvxingtu** [comment]
@Eskibear Thank you. 谢谢
