### ISSUE TITLE
Auto-import was not triggered automatically in some cases

### ISSUE THREAD

**Issue by EricZhangzf** [redhat-developer/vscode-java#1098]
#### Environment
- Operating System: Win/Mac/Linux
- JDK version: 13/12/8
- Visual Studio Code version:1.39.2
- Java extension version:0.51.0

#### Steps To Reproduce
1. Make sure java.actionsOnPaste.organizeImports in settings is true.
2. New Foo.java with codes as below: 
```
import java.io.File;
 
public class Foo {
 
     public static void main(String[] args) {
        File f =new File("A.txt");
    }
}
```

#### Result:
1. If copy the main method to another empty java file
Auto-import was not triggered automatically.
![image](https://user-images.githubusercontent.com/44559777/66895620-d6389780-f025-11e9-8457-975447fcb05b.png)

2. If copy the all class to another empty java file
Auto-import was triggered automatically.
![image](https://user-images.githubusercontent.com/44559777/66895526-9d002780-f025-11e9-82a2-b2785ec9f001.png)

**Comment by fbricon** [comment]
The feature is expected to work when pasting into an empty file. It seems you're trying to paste in a file that already has a class definition, so it's not empty.

Triggering autoimport when pasting in non-empty files might cause some issues eventually, that's why I'd prefer not to enable it at this time.

**Comment by testforstephen** [comment]
Copying a method to an existing class is a higher frequency operation, so supporting copying a method is more helpful for me.

**Comment by fbricon** [comment]
> Copying a method (even a code block) to an existing class is a higher frequency operation, so supporting copying a method is more helpful for me.
Fair enough. Let's try it then, I'll mark the feature as experimental.

**Comment by leonardofel** [comment]
oh very nice feature, but has a little problem...
![wtf](https://user-images.githubusercontent.com/34713362/67128365-cfe71e80-f1d1-11e9-9e8c-4b8269dcc076.gif)
Is an automatically activated experimental feature really necessary?

**Comment by fbricon** [comment]
@leonardofel can you please open a new ticket?

The best way to expose users to the new feature is to enable it automatically. I reckon this was a bit risky, but since this can be disabled, I'm not too worried. In any case, we'll either fix your problem or backpedal on the enable-by-default bit.

**Comment by fbricon** [comment]
@leonardofel  #1112 was opened about that issue

**Comment by leonardofel** [comment]
> @leonardofel can you please open a new ticket?
> 
> The best way to expose users to the new feature is to enable it automatically. I reckon this was a bit risky, but since this can be disabled, I'm not too worried. In any case, we'll either fix your problem or backpedal on the enable-by-default bit.

I understand... this bug occurs when I paste during multicursor, anyway thx for the reply, waiting for future fix

**Comment by fbricon** [comment]
@leonardofel you can install the latest CI build containing the fix, from https://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D
