### ISSUE TITLE
Stuck on "5% Update project ..." for a long time

### ISSUE THREAD

**Issue by akieling** [redhat-developer/vscode-java#1102]
After adding a new Maven dependency to `pom.xml`, a message saying "5% Update project ..." is shown in the status bar and takes a long time to complete. The plugin doesn't react quickly to dependency changes.

##### Environment
- Operating System: Fedora 30
- JDK version: 1.8
- Visual Studio Code version: 1.39.2
- Java extension version: 0.50.0

##### Steps To Reproduce
1. git clone git@github.com:apache/camel.git
1. Open components/camel-http project in VS Code
1. Open `pom.xml`
2. Add or remove a dependency

##### Current Result

The classes from the new dependency aren't available for a long time.

##### Expected Result

The classes from the new dependency should be available quickly.

##### Additional Informations

I don't think the long delay is due to downloading the new dependency. The same issue happens with already downloaded dependencies.

**Comment by snjeza** [comment]
I can't reproduce the issue.
@alexkieling Could you provide a log - https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging

**Comment by snjeza** [comment]
> The logs don't show any error.

It isn't important.  Could you attach it?

**Comment by alexkieling** [comment]
I've updated the steps to reproduce the issue. It happens when working on an Apache Camel component.

**Comment by snjeza** [comment]
@alexkieling could you try to include only required folders/projects. See https://github.com/redhat-developer/vscode-java/issues/1084 and https://github.com/eclipse/eclipse.jdt.ls/pull/1200

**Comment by alexkieling** [comment]
I'm not opening the main project, just one of the component projects.

**Comment by snjeza** [comment]
What project did you open?

**Comment by alexkieling** [comment]
I'm working on a new component [here](https://github.com/apache/camel/pull/3232) but have tested changing the pom of an existing component (camel-http) and the same behavior was seen.

**Comment by snjeza** [comment]
@alexkieling Could you test test the issue using https://raw.githubusercontent.com/snjeza/vscode-test/master/java-0.52.0.vsix?

**Comment by alexkieling** [comment]
The issue doesn't happen when using the version 0.52.0 you provided.

**Comment by snjeza** [comment]
@alexkieling Thanks.
The issue happens because Java LS forcibly updates Snapshots/Releases.
@fbricon I will create  a PR.

**Comment by fbricon** [comment]
A new `java.maven.updateSnapshots` preference was added, set to `false` by default. When set to `true`, it forces an update of Snapshots/Releases.

**Comment by Foxhunter981** [comment]
This issue is happening for me again in version 1.8.0. I imported another submodule and found that attempting to update the project would start a process  that would freeze up  at 5%. It has been like this for a long time. No logs to indicate the problem. 
![image](https://user-images.githubusercontent.com/74263544/158252126-c5d7b464-c5b4-4d71-836b-dfeb40f4d581.png)
