### ISSUE TITLE
Creation of a new Project always uses JDK 8

### ISSUE THREAD

**Issue by Z3roCoder** [redhat-developer/vscode-java#1108]
[provide a description of the issue]

##### Environment
- Operating System: Windows
- JDK version: 13
- Visual Studio Code version: Latest
- Java extension version: 0.51.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
Just use the VSCode-Command to create a new project

##### Current Result
Settings:
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
org.eclipse.jdt.core.compiler.compliance=1.8
org.eclipse.jdt.core.compiler.problem.assertIdentifier=error
org.eclipse.jdt.core.compiler.problem.enumIdentifier=error
org.eclipse.jdt.core.compiler.source=1.8

Classpath:
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
##### Expected Result
Using JDK 13 instead of 8

Why is it still using JDK 8? I dont even have it installed

**Comment by zeen1x** [comment]
@Z3roCoder Can you link your settings.json file ?

**Comment by Z3roCoder** [comment]
@zeen1x Where do I find this file? It's not in my workspace

**Comment by Z3roCoder** [comment]
Is there any progress on this?

**Comment by zeen1x** [comment]
@Z3roCoder you can find the settings.json file under C:\Users\{YOUR_USER}\AppData\Roaming\Code\User or you can simply hit F1 or Ctrl + Shift + P to open the vscode commands and type in "Preferences: Open Settings (JSON)"

**Comment by Z3roCoder** [comment]
@zeen1x I have merely set the Java path to the jdk13 folder.
With new projects, all config files keep referencing 1.8/jre-8

I have installed everything freshly after installing jdk13

Is it not automatically supported?

**Comment by Z3roCoder** [comment]
I used the installer from the VSCode page.

**Comment by zeen1x** [comment]
What does it say if you type in "java -version" in a command prompt ? Is your JAVA_HOME variable set to your JDK13 folder path? You can force vscode to look upon a custom folder for your jdk by adding `"java.home": "C:\\Program Files\\...\\<JDK13 ROOT FOLDER>",` in your settings.json. See if it helps.

**Comment by fbricon** [comment]
Sorry but vscode-java has no command to create a new project. This is provided by the [vscode-java-dependency](https://github.com/microsoft/vscode-java-dependency) extension. Please open a bug in https://github.com/microsoft/vscode-java-dependency/issues
