### ISSUE TITLE
"On paste: organize imports" fires all the time, not just when file is blank

### ISSUE THREAD

**Issue by jmoses-ds** [redhat-developer/vscode-java#1110]
The "Java > Actions On Paste: Organize Imports" action is triggering on any paste, not just into an empty document, like the help text says.  This is especially annoying as it lead to me fighting with vs-code to add new imports by copy/pasting an existing line and modifying it.  I would copy, paste, the action would trigger and remove the "duplicate" import.

##### Environment
- osx high sierra 10.13.6
- Java(TM) SE Runtime Environment 18.9 (build 11.0.2+7-LTS)
- Version: 1.40.0-insider
Commit: 5aec74ad3b55bb9463e717ec950e665288accd0f
Date: 2019-10-18T05:32:01.162Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 17.7.0
- Java extension version: 0.8.0

##### Steps To Reproduce
1. Copy/paste an existing import
2. Observe it immediately removed.

**Comment by fbricon** [comment]
Sorry, the description was not updated to indicate we expanded the feature to all pastes.
You can disable it though

**Comment by jmoses-ds** [comment]
Yeah, that's what I did, and then it was fine, but it sure was a weird few minutes until I figured it out. :D

This issue can just be to update the wording then, or closed if there's another one
