### ISSUE TITLE
Bug with copy/paste

### ISSUE THREAD

**Issue by deather** [redhat-developer/vscode-java#1112]
Hi,

Since the version 0.51.0 is out, I had strange bugs. Some copy/paste fonctionnality is buggy, like paste with multi-selector or the copy/paste of a line.

## First case

**Steps to reproduce :**
1. Copy a text with ctrl+c
2. Use multiselection
3. Paste the text with ctrl+v

##### Current Result
Paste the text only on the first selection.

##### Expected Result
The text copied should be paste on all selection.

## Second case

**Steps to reproduce :**
1. Put your cursor anywhere on a line without selection
2. Hit ctrl+c
3. Hit ctrl+v

##### Current Result
Paste the line copied at the cursor.

##### Expected Result
A copy of the line should be pasted above the line where the cursor is located.

I hope this post is clear and thanks for reading.

##### Environment
```Version : 1.39.2
Validation : 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date : 2019-10-15T15:33:40.634Z
Électron : 4.2.10
Chrome : 69.0.3497.128
Node.js : 10.11.0
V8 : 6.9.427.31-electron.0
OS : Linux x64 5.2.0-2-amd64
```

**Comment by fbricon** [comment]
Indeed, this was mentioned in #1098 
See: 
![](https://user-images.githubusercontent.com/34713362/67128365-cfe71e80-f1d1-11e9-9e8c-4b8269dcc076.gif)

For now you should disable the autoimport on paste feature with 
```json
"java.saveActions.organizeImports": false
```

**Comment by deather** [comment]
Thanks for the response but this doesn't fix the bug. The only way I found is to downgrade to version 0.50.0.

**Comment by fbricon** [comment]
sorry, that was the wrong preference, try `"java.actionsOnPaste.organizeImports": false`

**Comment by deather** [comment]
It seems to be ok with this settings :+1: 

Really thanks @fbricon

**Comment by fbricon** [comment]
@deather you can install the latest CI build containing the fix, from https://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D
