### ISSUE TITLE
Please do not override paste

### ISSUE THREAD

**Issue by alexandrudima** [redhat-developer/vscode-java#1115]
Hi, I'm a VS Code developer and we started to notice a number of issues lately regarding paste being broken:
 - https://github.com/microsoft/vscode/issues/83080
 - https://github.com/microsoft/vscode/issues/83063
 - https://github.com/microsoft/vscode/issues/83017
 - https://github.com/microsoft/vscode/issues/83003
 - https://github.com/microsoft/vscode/issues/82850

Please consider removing this functionality or talk to us so we can add necessary API to enable format on paste. cc @jrieken @egamma

---

##### Steps To Reproduce
1. create multiple cursors and copy
2. move to another region and paste

**Comment by egamma** [comment]
//fyi @akaroml

**Comment by fbricon** [comment]
The bug is fixed, but I'll disable the feature by default for starters, will release an update ASAP.

**Comment by fbricon** [comment]
@alexandrudima @akaroml @testforstephen see proposed fix in #1116. I'll cut a release once merged.

**Comment by jrieken** [comment]
@fbricon What are you trying to do on paste? Run formatter or run code actions? The former already exists via `editor.formatOnPaste` and it will call available `DocumentRangeFormattingEditProvider`s, the latter doesn't exists but would be a valid feature request imo (/cc @mjbvz)

**Comment by fbricon** [comment]
@jrieken I want to trigger organize import on paste. See https://github.com/microsoft/vscode/issues/43718

**Comment by jrieken** [comment]
Thanks - I'll make sure it's on our radar

**Comment by fbricon** [comment]
vscode-java 0.52.0 has been released with the fix. The original paste action is no longer overridden. You now need to paste with Ctrl+Shift+v (Cmd+Shift+v on mac) to enjoy the auto import on paste.

**Comment by alexandrudima** [comment]
Thank you for the prompt fix :heart: !
