### ISSUE TITLE
Autocomplete not working for attributes of type boolean

### ISSUE THREAD

**Issue by ThomasBiede** [redhat-developer/vscode-java#1119]
I created a class with a few attributes. After that I wanted to create getters and setters for the attributes. It was working perfectly for every attribute except for the ones which where of the type boolean

##### Environment
- Operating System: Windows 10
- JDK version: 1.8
- Visual Studio Code version: 1.39
- Java extension version: 0.52.0

##### Steps To Reproduce
1. Create a class with a private boolean attribute called isLocked
2. Enter getIsL...

##### Current Result
No autocomplete option for the boolean attribute

##### Expected Result
Get and Set autocoplete options for the attribute

**Comment by Eskibear** [comment]
I just reproduced it. It doesn't work for `boolean`, but it does work for `Boolean`.
