### ISSUE TITLE
Java language server failed to import jar files using relative path in the .classpath file

### ISSUE THREAD

**Issue by elichyb** [redhat-developer/vscode-java#1122]
##### Environment
- Operating System: windows 10
- JDK version: 1.8
- Visual Studio Code version:1.39.2
- Java extension version: 0.52.0

##### Steps To Reproduce
1. Open vscode in this folder
2. Run java server in vscode
3. Errors appear 

Tree directories:
├───cg
│   ├───.settings
│   ├───bin
│   │   ├───.settings
│   │   └───com
│   │       └───foo
│   │           └───bar
│   │               └───cg
│   │                   ├───csm
│   │                   └───test
│   └───com
│       └───foo
│           └───bar
│               └───cg
│                   ├───csm
│                   └───test
├───lib
│   ├───.settings
│   ├───ant
│   │   └───apache-ant-1.8.2
│   │       ├───bin
│   │       ├───etc
│   │       │   └───checkstyle
│   │       └───lib
│   ├───jmockit1.org
│   ├───junit
│   └───jython
├───mm
│   ├───.settings
│   └───com
│       └───foo
│           └───bar
│               └───mm
│                   ├───csm
│                   └───test
│                       └───client

.classpath file

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path=""/>
	<classpathentry combineaccessrules="false" kind="src" path="/platform"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="lib" path="/lib/junit/asm-3.0.jar"/>
	<classpathentry kind="lib" path="/lib/junit/asm-tree-3.0.jar"/>
	<classpathentry kind="lib" path="/lib/junit/cobertura.jar"/>
	<classpathentry kind="lib" path="/lib/junit/emma_ant.jar"/>
	<classpathentry kind="lib" path="/lib/junit/emma.jar"/>
	<classpathentry kind="lib" path="/lib/junit/jacocoagent.jar"/>
	<classpathentry kind="lib" path="/lib/junit/jacocoant.jar"/>
	<classpathentry kind="lib" path="/lib/junit/jakarta-oro-2.0.8.jar"/>
	<classpathentry kind="lib" path="/lib/junit/junit.jar"/>
	<classpathentry kind="lib" path="/lib/junit/log4j-1.2.9.jar"/>
	<classpathentry combineaccessrules="false" kind="src" path="/bin"/>
	<classpathentry combineaccessrules="false" kind="src" path="/JavaParser"/>
	<classpathentry kind="output" path=""/>
</classpath>


```
##### Error
The import org.junit cannot be resolved

* As you can see it is find in our classpath and the file exist there.

##### We would like to import jar files by relative path in the .classpath file.
Currently we see in process monitor that the extension search after the jar files under c:\ folder
and not the relative path we give in the project.

**Comment by fbricon** [comment]
@elichyb can you attach your project?

**Comment by elichyb** [comment]
I can't share it

**Comment by snjeza** [comment]
@elichyb you can try the following:

```
...
<classpathentry kind="lib" path="lib/junit/junit.jar"/>
...
```

instead of

```
... 
<classpathentry kind="lib" path="/lib/junit/junit.jar"/>
...
```

**Comment by elichyb** [comment]
well the .classpath found under folder CG so when I remove the '/' from the start of the lib it look after directory lib inside the CG.

**Comment by elichyb** [comment]
My workspace is lodestone directory and I have there several projects CG is one of them....
In eclipse when I open the same workspace all the projects knows to take the junit class from lib directory that found next to them in the workspace but in VSCode it doesn't work the same.

For example:
1. Create Workspace Foo.
2. Create java project bar1 inside Foo and bar2 also inside Foo.
3. Create directory lib under Foo and put there the junit.jar file.
4. Try to use This Junit in your projects and you can without give the absolute path to them.

**Comment by elichyb** [comment]
Here is a simple example:
[foo.zip](https://github.com/redhat-developer/vscode-java/files/3782793/foo.zip)

**Comment by elichyb** [comment]
@snjeza do you hava any idea why in eclipse this behavior works and in vsc it doesn't?

**Comment by snjeza** [comment]
>Here is a simple example:

It doesn't work in Eclipse too.

**Comment by elichyb** [comment]
The project that I add here doesn;t work in eclipse but our real project does works this way...
What I added here is only an example...

Is there any way to do workaround to this problem?
Thanks

**Comment by snjeza** [comment]
> Is there any way to do workaround to this problem?

Could you attach your .project and .classpath files?

**Comment by elichyb** [comment]
We succeed to solve this problem by adding file .classpath in our lib directory and change the container from:
`<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>`
to 
`<classpathentry exported="true" kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
`

**Comment by elichyb** [comment]
See comment above
