### ISSUE TITLE
Autocompletion deletes the following character

### ISSUE THREAD

**Issue by jackroi** [redhat-developer/vscode-java#1124]
Autocompletion occasionally deletes the following character.

##### Environment
- Operating System: macOS High Sierra 10.13.6 and Ubuntu 19.10 (probably also Windows 10)
- JDK version: Oracle 13.0.1 and Oracle 12.0.2
- Visual Studio Code version: 1.39.2
- Java extension version: 0.52

##### Steps To Reproduce
I am unable to reproduce this problem consistently. But apparently it happens when I write an `if` or a `for` and I use the autocompletion inside the round brackets.
To try to reproduce the issues I suggest you to:
1. Create a new method
2. Insert an `if`
3. Use the autocompletion to write `this` keyword
4. Use autocompletion to refer to an instance field
5. Repeat until the issue occurs (statistically it happens to me once every 5)

Here you can see an example:

![vscode-autocompletion-bug](https://user-images.githubusercontent.com/32576989/67815595-a8ccfe80-faa7-11e9-94d2-8e6fc5235557.gif)

As you can see after autocompleting `this` the right parenthesis is gone.

Log files:

[vscode-java logs.log](https://github.com/redhat-developer/vscode-java/files/3786208/vscode-java.logs-2.log)
[Java Language Server's workspace logs.log](https://github.com/redhat-developer/vscode-java/files/3786200/Java.Language.Server.s.workspace.logs-1.log)

##### Current Result
The right parenthesis disappears (occasionally).

##### Expected Result
The right parenthesis should remain.

##### Additional Informations
Seems related to #352

**Comment by snjeza** [comment]
@jackroi could you try to reproduce the issue without the Visual Studio IntelliCode extension?

**Comment by jackroi** [comment]
> @jackroi could you try to reproduce the issue without the Visual Studio IntelliCode extension?

I've tried with Visual Studio IntelliCode extension disabled and I've never been able to reproduce the issue, while reactivating the extension it appeared again. I've tried from both macOS 10.13.6 and Ubuntu 19.10.

At this point the problem seems to be related to IntelliCode, somehow the two extensions interfere with each other. What do you think?

As a side note, the issue apparently occurs more frequently on macOS than on Ubuntu.

PS: I've updated the title of the issue, since autocompletion deletes, more generally, the following character, regardless of whether it is a parenthesis or not.

**Comment by jdneo** [comment]
The completion will using `insert` by default now so the deleting behavior mentioned in this issue is addressed.
