### ISSUE TITLE
How to specify External Dependency JavaDocs and Source Locations

### ISSUE THREAD

**Issue by astrelsky** [redhat-developer/vscode-java#1125]
I have searched for hours on how to do this and cannot find the correct information or documentation anywhere. I'm trying to specify the sourcepath and javadoc_location values for external java dependencies so that I have the documentation and sources available on hover and "Go To Definition"

Attempting to "Attach Source" result in the following every time:
`The JAR of this class file belongs to container {0} which does not allow modifications to source attachments on its entries.`

##### Environment
- Operating System: Microsoft Windows [Version 10.0.18362.418]
- JDK version: 11, 12 & 13.0.1
- Visual Studio Code version: 1.40.0-insiders
- Java extension version: 0.52

 [build.gradle](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/blob/master/build.gradle)
[.project](https://github.com/redhat-developer/vscode-java/files/3786468/project.txt)

I'm aware that I can specify the locations within the .classpath file. However vscode decides it wants to keep overwriting my changes. I read somewhere that the source files should get picked up automatically if laid out
```
/lib.jar
/lib-src.jar
```

however the layout of the install directory I'm creating a plugin for is as follows:
```
/lib.jar
/lib-src.zip
```
Is there a way to tell vscode-java or the jdt.ls to look for the zip file instead?
Is there a vscode-java setting I can use to specify additional javadoc locations besides the jdk docs?

**Comment by snjeza** [comment]
You can try the following:

```
...
apply plugin: 'java'
apply plugin: 'eclipse'
...

eclipse {
    classpath {
        file {
            whenMerged { 
                def lib = entries.find { it.path.contains 'lib.jar' }
                lib.sourcePath = fileReference(file('<your_folder>/lib-src.zip'))
		lib.javadocPath = fileReference(file('<your_folder>/lib-javadoc.jar'))
            }
        }
    }
}
...

```

**Comment by astrelsky** [comment]
> You can try the following:
> 
> ```
> ...
> apply plugin: 'java'
> apply plugin: 'eclipse'
> ...
> 
> eclipse {
>     classpath {
>         file {
>             whenMerged { 
>                 def lib = entries.find { it.path.contains 'lib.jar' }
>                 lib.sourcePath = fileReference(file('<your_folder>/lib-src.zip'))
> 		lib.javadocPath = fileReference(file('<your_folder>/lib-javadoc.jar'))
>             }
>         }
>     }
> }
> ...
> ```

this is essentially what I was doing. [older build.gradle](https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer/blob/ce0615035fec307f0f2140da3c705d3f5dab86aa/build.gradle#L40-L54)
The problem is that I have to run `gradle eclipseClasspath` and then vscode just decides to go ahead and overwrite those .classpath changes.

**Comment by snjeza** [comment]
> The problem is that I have to run gradle eclipseClasspath

If you set build.gradle properly, you can skip this step. Java LS (buildship) will add sources/javadoc.

**Comment by astrelsky** [comment]
> > The problem is that I have to run gradle eclipseClasspath
> 
> If you set build.gradle properly, you can skip this step. Java LS (buildship) will add sources/javadoc.
> See https://discuss.gradle.org/t/buildship-1-0-18-is-now-available/19012

Oh ok I was confused because running gradle eclipseClasspath generates this massive 779 line .classpath file but when vscode sychronizes the gradle build it gets overwritten and becomes only 19 lines. Everything does appear to work with the small .classpath though. Thank you very much!
