### ISSUE TITLE
Add support format fluent

### ISSUE THREAD

**Issue by juandiii** [redhat-developer/vscode-java#1126]
[Add support format fluent]

##### Environment
- Operating System: MacOS Catalina, also Windows 10
- JDK version: 8, 11
- Visual Studio Code version: Latest
- Java extension version : 

I want support format fluent like: 

```java
myInstance.call()
          .again()
          .eclipseIsRubbish(true)
          .cestfin();
```

Thanks

**Comment by snjeza** [comment]
@juandiii you can try the following:

```
"java.format.settings.url": "https://raw.githubusercontent.com/snjeza/vscode-test/master/fluent.xml"
```

I have created fluent.xml based on https://stackoverflow.com/questions/4172937/how-to-indent-the-fluent-interface-pattern-correctly-with-eclipse?rq=1
