### ISSUE TITLE
Javadoc: popup horizontal autosize & scroll

### ISSUE THREAD

**Issue by jnesspro** [redhat-developer/vscode-java#1128]
Can our documentation popup just autosize itself based on content and does not show horizontal scroll?

<img width="652" alt="Screenshot 2019-11-01 at 12 56 09" src="https://user-images.githubusercontent.com/5245360/68017544-07f96180-fca8-11e9-850b-9467cf3b1d5b.png">

**Comment by fbricon** [comment]
It's usually fine when there's just text, but the image breaks everything. Anyways, this is managed by VS Code itself, there's nothing we can do. Please open an issue there. See also https://github.com/microsoft/vscode/issues/29757 for completion

**Comment by fbricon** [comment]
You can probably ask the VS Code team for images to be automatically scaled to the popup dimensions.
