### ISSUE TITLE
`;` not possible in vmArgs

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1129]
good day,

If I use the following vmArgs:

```json
"vmArgs": "-ea -javaagent:build/static_agent.jar=\"doeke.application.TestApplication;test\"",
```

Then in `public static void premain(String agentArgs, Instrumentation inst) {`

the string `agentArgs` will be `"doeke.application.TestApplication"` instead of the expected `"doeke.application.TestApplication;test"`.

For now I use `:` instead of `;` but since it feels like a bug I thought I report.
In the terminal using `;` works fine so it is really a problem in vscode.

##### Environment
- OSX
- 1.8
- 1.39.2
- 0.8.0

**Comment by testforstephen** [comment]
@clankill3r Do you mean `vmArgs` in launch.json? That is a [debugger](https://github.com/Microsoft/vscode-java-debug) extension issue.

**Comment by clankill3r** [comment]
https://github.com/microsoft/vscode-java-debug/issues/707
