### ISSUE TITLE
No standard documentation on hover

### ISSUE THREAD

**Issue by mddigaetano** [redhat-developer/vscode-java#1133]
I can't seem to be able to display documentation on hover for any class, even standard ones.
I've searched online for some settings to specify my javadoc location (/usr/share/doc/java-openjdk) with no success. Thanks for your help

##### Environment
- Operating System: Manjaro 18
- JDK version: 13
- Visual Studio Code version: 1.39.2
- Java extension version: 0.52.0

##### Current Result
The popup hover only displays full class name (for example java.lang.String)

##### Expected Result
The popup should show the relative javadoc

##### Additional Informations
My jdk path is listed correctly as /usr/lib/jvm/default but under source and type column there is "other"

**Comment by snjeza** [comment]
@mddigaetano could you try to install the openjdk-src or openjdk-doc package? See https://wiki.archlinux.org/index.php/Java#OpenJDK

**Comment by mddigaetano** [comment]
I had already installed openjdk-doc, but adding openjdk-src made it work. Thank you for your help
