### ISSUE TITLE
Issue adding jars to classpath

### ISSUE THREAD

**Issue by BrandonKi** [redhat-developer/vscode-java#1134]
I can run this perfectly fine on Eclipse. However when I try to run this in VSCode I get this error.

Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path:

[GameEngine.zip](https://github.com/redhat-developer/vscode-java/files/3816981/GameEngine.zip)

##### Environment
- Operating System: Windows 
- JDK version:  13.0.1
- Visual Studio Code version: 1.39.2
- latest version of all extensions

**Comment by fbricon** [comment]
Sorry vscode-java isn't responsible for running code. Most likely you want to open a ticket in   https://github.com/microsoft/vscode-java-debug/issues.

cc @testforstephen @Eskibear

**Comment by notrue** [comment]
@BrandonKi `vmArgs` must be used to pass `java.library.path`
