### ISSUE TITLE
Is there any method or solution to generate serialversionuid automatically? like IDEA

### ISSUE THREAD

**Issue by jkryanchou** [redhat-developer/vscode-java#1140]
[provide a description of the issue]

##### Environment
- Operating System: MacOSX
- JDK version: 1.8
- Visual Studio Code version: 1.40.0
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Expected Result

Generate serialVersionUID of FooDO which implement Serializable .

**Comment by snjeza** [comment]
Yes, it there is.

![serial](https://user-images.githubusercontent.com/388609/68730979-e4e77f80-05ce-11ea-98f0-70278aa3145e.gif)

**Comment by jkryanchou** [comment]
Got it. Thanks +1

**Comment by nutmix** [comment]
> Yes, it there is.
> 
> ![serial](https://user-images.githubusercontent.com/388609/68731304-e6fe0e00-05cf-11ea-9ec1-dfe976b66f75.gif)

For me, it just says "no quickfix avaiable", and doesn't work.  M1 Mac. version: April 2021 (version 1.56)

**Comment by trinhpham-da** [comment]
"no quickfix avaiable" also on
- Windows 10 21H1
- VSCode 1.57.1
- redhat.java v0.79.2

**Comment by minherz** [comment]
The functionality shown in the animated image in previous comments does not work both for a class that implements Serializable or inherits from a class that implements it. No matter what class modificators are.
VS Code version:
```
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:53:55.113Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.10.40-1rodete2-amd64
```

**Comment by minherz** [comment]
@fbricon what is an idea to close an existing issue? is it a way to treat users and developers? by ignoring it?

**Comment by fbricon** [comment]
@minherz question from OP was answered and the issue was closed. I don't see the problem.

Now, if it doesn't work in some cases, then please open a new ticket with sample code and steps to reproduce, the team will take a look when they can (there's a lot of issues in the backlog already).

**Comment by fbricon** [comment]
Looks like it's caused by the warning now being ignored by default (https://github.com/eclipse/eclipse.jdt.ls/pull/1721). No warning == no quickfix.

So, for now, you need to set `org.eclipse.jdt.core.compiler.problem.missingSerialVersion=warning` in your project's .settings/org.eclipse.jdt.core.prefs

Alternatively, you can create a JDT settings file somewhere on your machine, say `~/path/to/org.eclipse.jdt.core.prefs` (the file name doesn't matter in that case) and then reference it from vscode's setting.json:
`"java.settings.url": "~/path/to/org.eclipse.jdt.core.prefs"`

**Comment by minherz** [comment]
I would argue that publishing an animated gif does not answer the question, especially given a large number of reports that it does not work.
Thank you for taking time and drilling down into a possible cause. Can you please describe what extensions are expected to be installed in order for this settings change to work? My understanding was that this functionality is either provided by vscode language description or implemented by [Java extension](https://github.com/Microsoft/vscode-java-pack). However, having it and defining
```json
{
 ...
 "org.eclipse.jdt.core.prefs": "org.eclipse.jdt.core.compiler.problem.missingSerialVersion=warning"
 ...
}
```
did not work for me. It is just another reason why that animated answer cannot be considered valid. It helps to avoid biased approach like one that assumes that everyone use the same IDE configuration when working with Java.

**Comment by fbricon** [comment]
vscode-java delegates the Java support to a headless version of Eclipse JDT. Eclipse has over 400 Java specific settings, growing with each Eclipse release. It doesn't scale to redeclare each of those settings as vscode specific ones. So we just have a single setting that points to an Eclipse compatible preference file instead.

You just need vscode-java installed, then:
- create a new file on your machine, let's call it vscode-java.prefs
- put `org.eclipse.jdt.core.compiler.problem.missingSerialVersion=warning` in that file
- save it
- in vscode settings, set `"java.settings.url": "~/path/to/vscode-java.prefs"` 

Your project should immediately display warnings.

Click on the warning, press `Ctrl+.` (`Cmd+.` on Mac) or click on the light bulb, choose the proposed quickfix, as seen in prior gif).

Again, this used to work OOTB when the question was asked. It stopped working on April 2021. That's a different problem.

**Comment by minherz** [comment]
Thank you. It finally worked for me. Unfortunately, it proposed generating a "default" serialVersionUID which is `1L`...

**Comment by lakshyads** [comment]
> vscode-java delegates the Java support to a headless version of Eclipse JDT. Eclipse has over 400 Java specific settings, growing with each Eclipse release. It doesn't scale to redeclare each of those settings as vscode specific ones. So we just have a single setting that points to an Eclipse compatible preference file instead.
> 
> You just need vscode-java installed, then:
> - create a new file on your machine, let's call it vscode-java.prefs
> - put `org.eclipse.jdt.core.compiler.problem.missingSerialVersion=warning` in that file
> - save it
> - in vscode settings, set `"java.settings.url": "~/path/to/vscode-java.prefs"` 
> 
> Your project should immediately display warnings.
> 
> Click on the warning, press `Ctrl+.` (`Cmd+.` on Mac) or click on the light bulb, choose the proposed quickfix (as seen in prior gif).
> 
> Again, this used to work OOTB when the question was asked. It stopped working on April 2021. That's a different problem.
> 
> 

Thankyou. This worked for me finally.

**Comment by tgarijo** [comment]
The file solution vscode-java.prefs its worked for some days. Now its doesn't work. 

![serial](https://user-images.githubusercontent.com/7958523/133987319-ed1dd7cc-fd09-438e-a7af-0c39eef51413.PNG)

**Comment by kengreenlee** [comment]
@tgarijo I just got it to work.  I had to open the Problems view, find the file, and click on the warning there.  It auto-added a generated serialVerUUID.

**Comment by schulzf** [comment]
> Thank you. It finally worked for me. Unfortunately, it proposed generating a "default" serialVersionUID which is `1L`...

Doesn't it propose a generated option?

I have two options on mine:
-Add default serial version ID
-Add generated serial version ID

The latter generates a 20 char long ID.

**Comment by Osolemio44** [comment]
The proposed solution of creating a separate file has worked for me. Even after restarting VSCode. However, it seems to me a not very aesthetic solution. Couldn't this setting be included directly in the plugin and enabled by default? Or at least a configuration of the plugin itself to avoid having to create a separate file for this?

**Comment by sofiaponteb** [comment]
> vscode-java delegates the Java support to a headless version of Eclipse JDT. Eclipse has over 400 Java specific settings, growing with each Eclipse release. It doesn't scale to redeclare each of those settings as vscode specific ones. So we just have a single setting that points to an Eclipse compatible preference file instead.
> 
> You just need vscode-java installed, then:
> 
> * create a new file on your machine, let's call it vscode-java.prefs
> * put `org.eclipse.jdt.core.compiler.problem.missingSerialVersion=warning` in that file
> * save it
> * in vscode settings, set `"java.settings.url": "~/path/to/vscode-java.prefs"`
> 
> Your project should immediately display warnings.
> 
> Click on the warning, press `Ctrl+.` (`Cmd+.` on Mac) or click on the light bulb, choose the proposed quickfix (as seen in prior gif).
> 
> Again, this used to work OOTB when the question was asked. It stopped working on April 2021. That's a different problem.

I tried this on windows and it worked when I replaced the path  "\path\to\vscode-java.prefs"  with "\\path\\to\\vscode-java.prefs"

**Comment by technologyfreak** [comment]
I got it to work by creating a `.settings` folder in the root of my parent workspace and then placed the `org.eclipse.jdt.core.prefs` file inside that and added the line `org.eclipse.jdt.core.compiler.problem.missingSerialVersion=error` . Seems like it needs to be `error` rather than `warning` to actual generate anything besides the default `1L` value.

**Comment by kengreenlee** [comment]
Yes, that's how I solved it.  But this is not an easy solution.  It should just work.

**Comment by fellipetav** [comment]
The issue is closed but it's not an acceptable solution. It requires a workaround instead of something built-in from the plugin itself. That is weird.
