### ISSUE TITLE
how to debug single java file in a project whether other java file build fail or not 

### ISSUE THREAD

**Issue by Limbozombie** [redhat-developer/vscode-java#1143]
[provide a description of the issue]

##### Environment
- Operating System: windows 10
- JDK version: 1.8.0_191
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by jdneo** [comment]
Supported via https://github.com/microsoft/vscode-java-debug/pull/1263
