### ISSUE TITLE
java.error.incomplete.classpath.severity not working

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1144]
In the readme there is a description off:

`java.error.incomplete.classpath.severity`.

But in vscode it does nothing:

<img width="423" alt="Screen Shot 2019-11-15 at 19 35 30" src="https://user-images.githubusercontent.com/738650/68966748-1f276b80-07df-11ea-8f8b-1ac8a58df65f.png">

OSX 10.12.6
extension 0.52.0

**Comment by fbricon** [comment]
See https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning

**Comment by clankill3r** [comment]
nevermind, I can't copy text from the extension page from within vscode so I googled the beginning of the error so google would autocomplete. But there where still two typos in it :(
