### ISSUE TITLE
jump to definition on break 

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1145]
I think it would be really great if you use "Go to Defenition" on a break that you jump to the while or for loop that will break.

Think about it.

**Comment by fbricon** [comment]
Seems reasonable

**Comment by fbricon** [comment]
This is how it looks in vscode:

![breakcontinue](https://user-images.githubusercontent.com/388609/69441438-08d35f80-0d4b-11ea-8297-b37fd4f4c8f5.gif).

Note that, as of today, vscode-insiders is broken. See microsoft/vscode#85403

**Comment by clankill3r** [comment]
@fbricon This is really great! Thanks for adding this.
