### ISSUE TITLE
Disable TODO and other markers in the gutter

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1146]
Is there a way to disable those gutter bars for the TODO's and quick fix?

I mean this: (I rotated the images 90 degrees)

<img width="812" alt="Screen Shot 2019-11-15 at 19 46 13" src="https://user-images.githubusercontent.com/738650/68967730-29e30000-07e1-11ea-914b-6d58fffd6cd8.png">

And is there a way to disable the scribble line under the TODO's?

##### Environment
- Operating System: OSX
- JDK version: 1.8
- Visual Studio Code version: 1.40.1
- Java extension version: 0.53.1

**Comment by fbricon** [comment]
In your project's .settings/org.eclipse.jdt.core.prefs, you can set `org.eclipse.jdt.core.compiler.taskTags=` (no value) to disable all task tags. Default value is `org.eclipse.jdt.core.compiler.taskTags=TODO,FIXME,XXX`

**Comment by clankill3r** [comment]
Thank you so much. I like the clean look so much better.
