### ISSUE TITLE
Suggestions for java.awt not working

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1147]
I have seen those 2 topics:
https://github.com/redhat-developer/vscode-java/issues/1096
https://github.com/redhat-developer/vscode-java/issues/1093

About adding:

```json
"java.completion.filteredTypes" : [
        "java.awt.*",
        "com.sun.*"
    ],
```
But for me that is not working:

<img width="489" alt="Screen Shot 2019-11-15 at 21 44 32" src="https://user-images.githubusercontent.com/738650/68974930-3885e300-07f2-11ea-82c1-3d1a843de5bc.png">

If I type it fully it works:

<img width="282" alt="Screen Shot 2019-11-15 at 21 44 55" src="https://user-images.githubusercontent.com/738650/68974964-489dc280-07f2-11ea-80a3-5542434ee022.png">

##### Environment
- Operating System: OSX 10.12.6
- JDK version: 1.8
- Visual Studio Code version: 1.40.1
- Java extension version: 0.53.0

**Comment by snjeza** [comment]
Could you try the following:

```
"java.completion.filteredTypes" : [
        "java.awt.List",
        "com.sun.*"
    ],
```

**Comment by clankill3r** [comment]
Yeah that seems to work. I did `java.awt.*` in the hope of enabling all.
Why is this needed anyway?

Op vr 15 nov. 2019 om 22:10 schreef Snjeza <notifications@github.com>:

**Comment by snjeza** [comment]
You may want to take a look at https://github.com/redhat-developer/vscode-java/pull/1059

**Comment by fbricon** [comment]
@clankill3r adding those namespaces effectively excludes them from automatic imports/completion. Since `java.awt.* are excluded by default, you need to remove it from the list so its types can be proposed again

**Comment by fwcd** [comment]
Is there a reason why AWT classes are hidden by default? These are commonly needed in Swing projects.

**Comment by jdoe1024** [comment]
@snjeza Why did you decide to filter out all the AWT classes from completion by default in your original PR?

**Comment by snjeza** [comment]
> @snjeza Why did you decide to filter out all the AWT classes from completion by default in your original PR?

See https://github.com/redhat-developer/vscode-java/issues/710#issuecomment-442335518

**Comment by jdoe1024** [comment]
@snjeza I see thanks. Out of the [50 name collisions](https://gist.github.com/jdoe1024/945cda9e72312147adb12cac0c7d5c2d#file-jdk11-collisions) there is in JDK11, only 2 concern `java.awt` classes, the most problematic being `java.awt.List`. Blacklisting the whole package by default is definitely overkill then. Could you change the default setting value for `java.completion.filteredTypes` to the one you gave [above](https://github.com/redhat-developer/vscode-java/issues/1147#issuecomment-554529618) so that it is less confusing for users please?

**Comment by fbricon** [comment]
only filtering java.awt.List would be even more confusing IMHO (why all AWT classes are proposed except this one?). Besides, even though there's only a couple collisions, listing AWT classes is just noise for a vast majority of Java users

**Comment by MilkBiscuit** [comment]
> Could you try the following:
> 
> ```
> "java.completion.filteredTypes" : [
>         "java.awt.List",
>         "com.sun.*"
>     ],
> ```

Thanks a lot! You made my day!

**Comment by DAflamingFOX** [comment]
> Could you try the following:
> 
> ```
> "java.completion.filteredTypes" : [
>         "java.awt.List",
>         "com.sun.*"
>     ],
> ```

Thank you very much; was about to bash my head in if I had to manually import all java.awt stuff

**Comment by B-M33K** [comment]
check this:
https://stackoverflow.com/questions/67823988/exception-in-thread-main-java-lang-unsatisfiedlinkerror-cant-load-library
