### ISSUE TITLE
Suddenly language server failed

### ISSUE THREAD

**Issue by SIGMIX0KKoba** [redhat-developer/vscode-java#1165]
The workspace that had no problems with java develop suddenly had an issue several days ago.

A import package suggestion is not working.
`Go to definition` and any kind java code navigate is failed.
(FYI: typescript at same workspace hasn't problem)

I already tried reinstall vscode, jdk and all extension pack for vscode.
(Cleared %USERPROFILE%\.vscode folder after uninstall)
Tried `clean the java language server workspace` many times;)

Any idea?

##### Environment
- Operating System: Windows 10 Pro
- JDK version: 1.8
- Visual Studio Code version: 1.40.1
- Java extension version: 0.8.0

##### Steps To Reproduce
I don't have any idea;(

##### Current Result

- A import package suggestion is not working.

![importSuggestFaild](https://user-images.githubusercontent.com/36154078/69786264-6b21d980-11fd-11ea-8f88-2a6a5fcf8f7d.jpg)

- `Go to definition` and any kind java code navigate is failed.

SUB: 'classname' Definition not found
(It's own namespace class)
![definitionNotFound](https://user-images.githubusercontent.com/36154078/69783243-73c2e180-11f6-11ea-9560-156655482d1f.jpg)

##### Additional Informations
[languageServerWorkspaceLog.txt](https://github.com/redhat-developer/vscode-java/files/3900253/languageServerWorkspaceLog.txt)
[vscode-java-console.txt](https://github.com/redhat-developer/vscode-java/files/3900254/vscode-java-console.txt)
[languageSupportTrace.txt](https://github.com/redhat-developer/vscode-java/files/3900255/languageSupportTrace.txt)

settings:
[workspace_settings.txt](https://github.com/redhat-developer/vscode-java/files/3900344/workspace_settings.txt)
[user_settings.txt](https://github.com/redhat-developer/vscode-java/files/3900440/user_settings.txt)

**Comment by fbricon** [comment]
can you share your .project, .classpath, .settings/?

**Comment by SIGMIX0KKoba** [comment]
- .project
```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>Eureka</name>
	<comment>Project Eureka created by Buildship.</comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.wst.common.project.facet.core.builder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.wst.validation.validationbuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.buildship.core.gradleprojectbuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>org.eclipse.buildship.core.gradleprojectnature</nature>
	</natures>
</projectDescription>

```

- .classpath
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="src/main/resources">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry kind="con" path="org.eclipse.jst.j2ee.internal.web.container"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
```

- .settings/?

(org.eclipse.buildship.core.prefs)
```
connection.project.dir=
eclipse.preferences.version=1

```

**Comment by SIGMIX0KKoba** [comment]
I've self resolved. It's Gradle settings matter.
@fbricon 
I'm sorry to have caused trouble.

FYI: 
There was no Gradle error, but I reviewed setting around `include 'src'` in the settings.gradle.

**Comment by fbricon** [comment]
ok, thanks for letting us know
