### ISSUE TITLE
The java.import.gradle.arguments setting is a No-Op

### ISSUE THREAD

**Issue by lingocoder** [redhat-developer/vscode-java#1169]
The [*Supported VS Code settings*](https://github.com/redhat-developer/vscode-java#supported-vs-code-settings) section of this project's Code page lists: „*`java.import.gradle.arguments: Arguments to pass to Gradle`*“. Disappointingly, setting that property's value to *`--gradle-user-home=<my.specified.location>`* has absolutely no effect. Likewise, setting its value to *`--refresh-dependencies`* has absolutely zero effect.

##### Environment
- Operating System: Windows amd64
- JDK version: OpenJDK 12
- Visual Studio Code version: 1.40.1 (system setup)
- Java extension version: 0.53.1
- Gradle 5.2.1 - 6.0.1

##### Steps To Reproduce
1. Open a Gradle project
2. Type *`Ctrl + ,`* for *`Settings`*
    * enter *`java.import.gradle.arguments`* in the *`Settings`* field
    * select the *`Workspace`* tab
    * enter *`--gradle-user-home=<some.user.specified.location>`* in the *`Arguments to pass to Gradle.`* field
3. Do something that causes Gradle to execute a build. For instance...
    * *`Ctrl + Shift + B`*
4. Observe that regardless of the value set for *`--gradle-user-home`*, it is never used by Gradle.

##### Current Result
Regardless of the value set for *`java.import.gradle.arguments`* in vscode-java's *`Settings`*, the arguments given to it are ***never*** used by Gradle.

##### Expected Result
In the case of *`java.import.gradle.arguments`* being set to *`--gradle-user-home=<some.user.specified.location>`*, Gradle is expected to do [*the same thing it is documented to do*](https://docs.gradle.org/current/userguide/command_line_interface.html#environment_options) when the same argument is passed to Gradle's command line interface. That is, Gradle should use the specified existing location. If the location given to *`--gradle-user-home`* does not exist already, then [*Gradle should automatically create it and then use that newly-created location*](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home).

**Comment by fbricon** [comment]
might be a limitation of Buildship (or not). Can you check if this works as expected in Eclipse?

**Comment by lingocoder** [comment]
Assuming the wizard in this screenshot is the way to set those properties for Eclipse...

![1169 a](https://user-images.githubusercontent.com/49788472/70072206-75254d00-15ee-11ea-9af0-bda7290d7902.png)

...,then yeah, this screenshot of Eclipse shows what I would expect to see from setting that *`--refresh-dependencies`* argument in the above wizard and invoking Eclipse's/Buildship's *`Gradle — Refresh Gradle Project*` context menu...

![1169 b](https://user-images.githubusercontent.com/49788472/70072603-380d8a80-15ef-11ea-948e-8843fa97c89d.png)

I can confirm with total certainty that the above wizard's *`Gradle user home`* field does exactly what I expect too.

**Comment by hanct** [comment]
Has this been solved? I also trying to set Gradle User home in VSCode , so that VSCode 's JAVA DEPENDENCIES section would display the correct paths (based on the value set in the Gradle User home) for the libraries listed under "Project and External Dependencies".

**Comment by snjeza** [comment]
Related to #1310 and #1319

**Comment by ob** [comment]
Is this issue resolved? I have a custom init script that we pass to `./gradlew` with the `-I` option:

```
./gradlew -I Path/to/my/custom/gradle-init-script.gradle
```

I tried adding the following to `.vscode/settings.json`:
```
{
  "java.import.gradle.arguments": "-I Path/to/my/custom/gradle-init-script.gradle"
}
```
but it doesn't seem to have any effect.

**Comment by snjeza** [comment]
See https://github.com/redhat-developer/vscode-java/issues/1310#issuecomment-600726259

**Comment by sarahcpage** [comment]
please fix this

**Comment by jumble** [comment]
Is there a path forward on this issue?

**Comment by mozhuanzuojing** [comment]
@CsCherrYY please watch this . 
It related by https://github.com/microsoft/vscode-gradle/issues/1077

**Comment by snjeza** [comment]
> I tried adding the following to .vscode/settings.json:
 Is there a path forward on this issue?

@jumble could you try to add the java.import.gradle.arguments property to User Settings?

**Comment by mozhuanzuojing** [comment]
> > I tried adding the following to .vscode/settings.json:
> > Is there a path forward on this issue?
> 
> @jumble could you try to add the java.import.gradle.arguments property to User Settings?

#### After I tested, the gradle service failed to start

> C:\Users\Administrator\AppData\Roaming\Code - Insiders\User\settings.json
```json
"java.import.gradle.jvmArguments": "-XX:+UseShenandoahGC -Xms1g -Xmx4g",
```

**Comment by snjeza** [comment]
@mozhuanzuojing Could you try to set java.import.gradle.arguments instead of java.import.gradle.jvmArguments and attach your logs?

**Comment by mozhuanzuojing** [comment]
@snjeza arguments is not effect. I think this parameter is not recognized by https://github.com/microsoft/vscode-gradle .
because `java.import.gradle.user.home` is ok.

> settings.json

```json
// Arguments to pass to Gradle.
"java.import.gradle.arguments": "--gradle-user-home=D:/java/gradlehome",
// Setting for GRADLE_USER_HOME.
// "java.import.gradle.user.home": "D:/java/gradlehome",
```

> gradle home sreen

![image](https://user-images.githubusercontent.com/63572041/140630631-fa58cf71-fad2-4b88-8629-4745bd1df2a2.png)

**Comment by CsCherrYY** [comment]
> @CsCherrYY please watch this . It related by [microsoft/vscode-gradle#1077](https://github.com/microsoft/vscode-gradle/issues/1077)

Not sure If it's related, currently `vscode-java` and `vscode-gradle` are separate extensions and `vscode-gradle` will consume some settings of `vscode-java`. That's the only way the two extensions work together **now**, though we have a plan to reuse the daemons and so on. 

In the above discussion, I find vscode-gradle supports `java.import.gradle.jvmArguments` only, not `java.import.gradle.arguments`.

**Comment by jumble** [comment]
> > I tried adding the following to .vscode/settings.json:
> > Is there a path forward on this issue?
> 
> @jumble could you try to add the java.import.gradle.arguments property to User Settings?

I can partially verify @CsCherrYY 's above statement. Specifying values for `java.import.gradle.arguments` in user settings does not affect Java or Gradle execution.

**Comment by CsCherrYY** [comment]
With the newest extension (1.5.0), I can pass the arguments like `--gradle-user-home` mentioned via `java.import.gradle.arguments` and Gradle makes use of them successfully.
