### ISSUE TITLE
Launching Compilation through tasks.json - recommendation for problemMatcher

### ISSUE THREAD

**Issue by joewood** [redhat-developer/vscode-java#117]
What's the recommendation for a configure problemMatcher in tasks.json?

##### Environment
- Operating System: RHEL7
- JDK version: 8
- Visual Studio Code version: 1.7.2
- Java extension version:

**Comment by fbricon** [comment]
We're not using problemMatchers so I can't really help other than say just follow the instructions from https://code.visualstudio.com/Docs/editor/tasks#_defining-a-problem-matcher.

But the java extension already returns compilation or syntax errors. What exactly are you trying to achieve?

**Comment by gatimus** [comment]
Not sure if its the scope of this extension but it'd be nice if an extension defined `$java` as in you could use

    {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "someTask",
                "type": "shell",
                "command": "java -jar path/to/my.jar",
                "problemMatcher": ["$java"],
            }
        ]
    }

in `task.json`
