### ISSUE TITLE
The references codelens is enabled by mistake

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#1172]
In the vscode-java.0.54.0 RC bits, the references codelens is enabled by default. Actually the switch is off in my user settings.

![image](https://user-images.githubusercontent.com/14052197/70114332-18ca3800-1697-11ea-86ce-9ee9f00dc950.png)

After a look, the root cause is the **didChangeConfiguration** didn't pass the right setting format to the LSP.

Below is the wrong format.
[Trace - 12:58:19 PM] Sending notification 'workspace/didChangeConfiguration'.
```json
Params: {
    "settings": {
        "decompiler": {
            "fernflower": {},
            "cfr": {},
            "procyon": null
        },
        "home": "C:\\Program Files\\Java\\jdk1.8.0_231",
        "jdt": {
            "ls": {
                "vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication"
            }
        },
        "errors": {
            "incompleteClasspath": {
                "severity": "warning"
            }
        },
       ...
```

The right format should be:
```
Params: {
    "settings": {
        "java": {
           ...
        }
```

**Comment by ZhengJun003** [comment]
In the vscode-java.0.54.0 RC bits, this notification always pops up after clicking the `Always` button. 
whatever I click which buttons, the value of `editor.minimap.enabled` is always false.
![image](https://user-images.githubusercontent.com/41051257/70123184-107cf780-16ad-11ea-9a18-65704625e34f.png)
