### ISSUE TITLE
Right click to copy a class reference

### ISSUE THREAD

**Issue by bonaluo** [redhat-developer/vscode-java#1178]
Issue Type: <b>Feature Request</b>

Right click to copy a class reference

Extension version: 0.54.1
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by fbricon** [comment]
how do you define a class reference? Fully Qualified Class Name (then it's a duplicate of #374), hyperlink to referenced class? Simple class name?

**Comment by bonaluo** [comment]
Fully Qualified Class Name

**Comment by fbricon** [comment]
ok then closing as a dupe of #374
