### ISSUE TITLE
Provide a setting to disable the behavior of automatically popping the build status terminal

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-java#1181]
还有一点，就是每次打开新的项目窗口，都会自动弹出 Java Build Status 的 Teminal 窗口，确实有点碍眼。真心希望将这个功能点改回老版本的样子，辛苦！谢谢！

_Originally posted by @EminemRap in https://github.com/redhat-developer/vscode-java/issues/1179#issuecomment-561949437_

**Comment by fbricon** [comment]
Seems we're getting a bit of flak about this one. @akaroml can you quickly provide a PR for this, so we can release a 0.54.2 version today?

**Comment by akaroml** [comment]
> Seems we're getting a bit of flak about this one. @akaroml can you quickly provide a PR for this, so we can release a 0.54.2 version today?

I'm on it. One point, do we want to default to show or not show the terminal on start?
I'm thinking default to not popping the terminal because the spinning icon is already indicating something happening.

**Comment by fbricon** [comment]
yes, hide by default
