### ISSUE TITLE
Question: How do you verify local path in "java.format.settings.url" is pointing to the right file?

### ISSUE THREAD

**Issue by tommai78101** [redhat-developer/vscode-java#1186]
Currently, I have a file, `eclipse-formatter.xml`, located at `${workspaceRoot}/.vscode` directory.

I understand environment variables are not supported in VSCode-Java.

So, if I were to start from:

`"java.format.settings.url": "",`

How do I know where the current working directory for "java.format.settings.url" defaults to? Or this is actually based on where the ".code-workspace" file is located? Or this is based off of where "settings.json" is located?

##### Environment
- Operating System: Windows 10 Pro & Ubuntu
- JDK version: 12.0.1
- Visual Studio Code version: 1.40.2
- Java extension version: 0.54.2

**Comment by snjeza** [comment]
@tommai78101 you can try the following:
```
 "java.format.settings.url": ".vscode/eclipse-formatter.xml",
```

**Comment by tommai78101** [comment]
Thanks, but I would like to know if there's a way to detect the current working directory?

**Comment by snjeza** [comment]
See https://code.visualstudio.com/docs/editor/variables-reference

```
${cwd} - the task runner's current working directory on startup
```

**Comment by tommai78101** [comment]
Thanks. 

I'll figure something out for printing the ${cwd} within Visual Studio Code.

**Comment by saumilsdk** [comment]
This seems not working in latest VC code version 1.54.3

**Comment by tommai78101** [comment]
@saumilsdk Open a new issue and reference this ticket.

**Comment by saumilsdk** [comment]
@tommai78101 Hey this seems to work with file: prefix.

` "java.format.settings.url": "file:/eclipse-formatter.xml"`

**Comment by kulynyak** [comment]
`"java.format.settings.url": "file:.vscode/eclipse-formatter.xml",` should work

**Comment by kristian** [comment]
Yep, latest VSCode broke referencing local files without a `file:` protocol... @saumilsdk and @kulynyak tipps fixed the issue for me! Thanks so much!

**Comment by tommai78101** [comment]
@saumilsdk @kulynyak  Thanks to both. Didn't know there's a new protocol to specify the file.

**Comment by fbricon** [comment]
It's a bug that'll be fixed in the next release (end of March)

**Comment by fbricon** [comment]
Duplicate of #1827
