### ISSUE TITLE
osx 系统上的vscode-java插件为什么不能跳转到接口的实现

### ISSUE THREAD

**Issue by crab890715** [redhat-developer/vscode-java#1190]
[provide a description of the issue]

##### Environment
- Operating System: osx
- JDK version: jdk1.8
- Visual Studio Code version:1.4.0.2
- Java extension version:v0.54.2
 

所有java接口都没办法跳转到它的实现类里面的方法，类似eclipse里面的接口，点击方法可以查找到它所有的实现类，选择需要跳转的实现进入
![image](https://user-images.githubusercontent.com/12027117/70675524-5f85e680-1cc4-11ea-99eb-1ea0c3b11d33.png)

**Comment by Eskibear** [comment]
Go to Implementations: <kbd>cmd + F12</kbd>

<img width="479" alt="Screen Shot 2019-12-12 at 10 11 02 AM" src="https://user-images.githubusercontent.com/2351748/70676616-bb9e3a00-1cc7-11ea-882d-11fcc7b3a7fb.png">

**Comment by crab890715** [comment]
试了，完全没有反应

**Comment by Eskibear** [comment]
> 试了，完全没有反应  (tried, but it didn't work) 

I cannot reproduce. It works well for me.
<img width="858" alt="Screen Shot 2019-12-12 at 10 24 19 AM" src="https://user-images.githubusercontent.com/2351748/70677248-9a3e4d80-1cc9-11ea-8110-b7891863daab.png">

Can you attach your project and describe the steps to reproduce? And please use English if possible, so that others can also help.

**Comment by crab890715** [comment]
我的vscode貌似无法对它设置快捷键导致的

**Comment by meydominic** [comment]
It's the same on my end:
![image](https://user-images.githubusercontent.com/2743382/70975258-d565c580-20a9-11ea-8588-75758a77702e.png)

VSCode 1.41, latest extension, JDK1.8, macOS 10.14

**Comment by fbricon** [comment]
@meydominic  you can not override static methods in Java, so it's expected you won't find other implementations

**Comment by meydominic** [comment]
Oh wow... I think I misunderstood this function all the time 🤦‍♂ What I was looking for is the equivalent of jumping to or showing all places where this method/class is used in code. But it's "Go to references". I'm pretty sure it was not working for me all the time. But it's working now. Thank you mate
