### ISSUE TITLE
Wrong highlighting on 'new' keyword on inner classes

### ISSUE THREAD

**Issue by Meir017** [redhat-developer/vscode-java#1195]
creating a new instance of an inner class doesn't highlight the `new` keyword properly

##### Environment
- Operating System: Win10
- JDK version: 1.8
- Visual Studio Code version: 1.41
- Java extension version: 0.54.2

##### Steps To Reproduce
1. Create a class and an inner class
```java
// Outer.java
class Outer {
    class Inner {
    }
}

// Program.java
class Program {
    public static void main(String[] args) {
        Outer outer = new Outer();
        Outer.Inner inner = outer.new Inner();
    }
}
```

##### Current Result
![image](https://user-images.githubusercontent.com/9786571/70889983-9291e800-1fec-11ea-9b14-3df4b266963c.png)

##### Expected Result

![image](https://user-images.githubusercontent.com/9786571/70890037-b5240100-1fec-11ea-9af0-4c25218e57bd.png)

**Comment by fbricon** [comment]
The textmate grammar is defined in [vscode itself](https://github.com/microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json), but the source of the grammar is actually atom, so the problem should be reported there: https://github.com/atom/language-java/issues

**Comment by Meir017** [comment]
sounds similar to https://github.com/atom/language-java/issues/216

**Comment by Eskibear** [comment]
https://github.com/atom/language-java/issues/216 looks more about the identifiers in new statements, not the `new` keyword itself. So I just created https://github.com/atom/language-java/issues/228 dedicated for this one
