### ISSUE TITLE
Java Overview will break the import of invisible project

### ISSUE THREAD

**Issue by Vigilans** [redhat-developer/vscode-java#1198]
When opening a folder containing an invisible project, if `Java Overview` pops up, the project will fail to be imported, because `initializationOptions` does not contain a trigger file:

```java
Collection<IPath> triggerFiles = preferencesManager.getPreferences().getTriggerFiles();
if (triggerFiles == null || triggerFiles.isEmpty()) {
    return;
}
```

from https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/InvisibleProjectImporter.java#L72-L75

It is root-caused in `getTriggerFiles`, where it only retrives text editors. When `Java Overview` pops up, the triggered file actually goes to background, and cannot be retrieved in `window.visibleTextEditors`.

https://github.com/redhat-developer/vscode-java/blob/6f82e4d209eccea74149cc4176f4173c0edbc372/src/extension.ts#L846-L852

#### Environment
- Operating System: Windows 10 
- Java version: openjdk 1.8
- Visual Studio Code Version:  1.40.2
- Java extension version: master branch

#### Reproduce steps
1. Make sure `Show overview page when using Java` is set
2. Open a folder containing an invisible project.

Sample project: https://github.com/santiontanon/microrts

#### Current Result

"Classpath is incomplete. Only syntax error is reported."

#### Expected Result

Project should successfully build.

**Comment by fbricon** [comment]
No idea how we can fix this one

**Comment by Vigilans** [comment]
Maybe we can use `workspace.textDocuments` instead? I would like to have a try, let me know if this alternative has ever been considered and rejected.
