### ISSUE TITLE
怎么快捷创建java类

### ISSUE THREAD

**Issue by crab890715** [redhat-developer/vscode-java#1200]
有什么方式可以快捷创建java类等

**Comment by rectcircle** [comment]
> 有什么方式可以快捷创建java类等

I develop a vscode extensions to quick create file.

https://marketplace.visualstudio.com/items?itemName=Rectcircle.new-file-by-type
https://github.com/rectcircle/new-file-by-type

I am refactoring, It should be available soon

**Comment by testforstephen** [comment]
Please see the comments https://github.com/redhat-developer/vscode-java/issues/579#issuecomment-402261125
