### ISSUE TITLE
Multi-module Gradle project doesn't seem to work very well

### ISSUE THREAD

**Issue by dsyer** [redhat-developer/vscode-java#1203]
A multi-module Gradle project (e.g. https://github.com/spring-guides/gs-multi-module/tree/master/complete or https://github.com/spring-io/sagan) doesn't seem to work very well in VSCode. When I open a .java source file I can see the LSP server start, and a `.project` is created, but I never see a `.classpath` file (which does appear in a single module project). Also the main classes and tests never pick up the "Run" links. The Java Dependencies view is empty (unsurprisingly I suppose given the missing `.classpath`). Am I doing something wrong?

**Comment by dsyer** [comment]
Just noticed: if you add an empty `build.gradle` to the root folder it works (at least with the gs-multi-module example).

**Comment by fbricon** [comment]
yes jdt.ls uses build.gradle as a mechanism to detect gradle projects to import. We may have to tweak that a bit

**Comment by dsyer** [comment]
That would be good. Then could you open the parent's parent (https://github.com/spring-guides/gs-multi-module) and use Java language features in all the subprojects? It's actually 2 independent builds in that project.

**Comment by fbricon** [comment]
would detecting the presence of settings.gradle be enough, or even preferable? I must admit I way more familiar with Maven than with Gradle, so please bear with me

**Comment by dsyer** [comment]
Pretty sure that would work for the `complete` sample, but not for the parent's parent use case. So better than nothing, if that's easier.

**Comment by johnrengelman** [comment]
`build.gradle` can also be renamed to something else within the `settings.gradle` file (eg. ` ratpack.gradle` instead of `build.gradle`)

**Comment by arnaldobadin** [comment]
I'm facing this issue, can't load a multi-module gradle. Putting a empty build.gradle solves my problem, but it isn't much practical. And sometimes it just won't work. I think that detection of settings.gradle would be a nice/easy approach.

**Comment by jdneo** [comment]
Tested with 0.80.0. Seems the problem has been fixed. (at least for https://github.com/spring-guides/gs-multi-module/tree/master/complete)
