### ISSUE TITLE
Add Assign statement to new variable/field quick action

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#1208]
using vscode its extract to local variable seem to take the nearest value rather than nearest statement to extract to variable. It should take the nearest statement instead.

This makes it very tedious to use compared to other IDE's to quickly create java code.

##### Steps To Reproduce
1. have code like:

```
        session.createNativeQuery("select * from Gift").scroll();
```
2.  use ctrl+. while cursor is on `session` and use extract to local variable

##### Current Result
```
        StatelessSession session2 = session;
        session2.createNativeQuery("select * from Gift").scroll();
```

##### Expected Result
```
        ScrollableResults scroll = session.createNativeQuery("select * from Gift").scroll();
```

##### Additional Informations

Furthermore the refactoring should be possible to do anywhere in the statement  and not just on a exact value.

**Comment by fbricon** [comment]
This is the behaviour from Eclipse JDT:
<img width="860" alt="Screen Shot 2019-12-20 at 9 14 50 AM" src="https://user-images.githubusercontent.com/148698/71240392-4b1b9c80-2309-11ea-8d4f-2b60397707b6.png">

I'm not saying it's right, I'm just challenging the "very tedious to use compared to other IDE's" statement ;-)

**Comment by maxandersen** [comment]
well, i'm saying you are missing Assign Statement refactoring  then, extract field is much less used :)

it is eclipse that I referred to  above since it provide assign statement anywhere on the code line, vscode does not.

**Comment by maxandersen** [comment]
![2019-12-20_09-36-05](https://user-images.githubusercontent.com/54129/71241540-270d8a80-230c-11ea-8a03-5f51e27c35b4.png)

eclipse screenshot

**Comment by maxandersen** [comment]
renaming as i noticed eclipse has both extract and assign - I just never remember using extract daily ;)
