### ISSUE TITLE
intellisense is so slow in showing suggestion

### ISSUE THREAD

**Issue by islam-taha** [redhat-developer/vscode-java#121]
This happens every time working on any java project in vscode with the extension applied, with quick suggestions enabled, even if when i stop writing and waiting for the suggestions to appear it take long time to appear.
When i stop typing and pressing cmd+space instead it shows loading for a while until it shows the suggestions in the Intellisense.

##### Environment
- Operating System: Mac os
- JDK version: 1.8.0_45
- Visual Studio Code version: 1.8.0
- Java extension version: 0.0.7

**Comment by fbricon** [comment]
How big is your project? Nb of classes, dependencies?
Have you tried increasing the amount of memory given to the Java Language server? In the user or workspace preferences, add 
```
"java.jdt.ls.vmargs":"-Xmx1G"
```
Or more memory

**Comment by islam-taha** [comment]
It's large with a large number of dependencies and classes. I have already increased the amount of memory but no changes has happened still slow suggestions. 
Also when i created a small project with 2-5 dependencies it still showing suggestions slowly.

**Comment by fbricon** [comment]
Have you tried importing the project in Eclipse? How does it compare?

**Comment by islam-taha** [comment]
no i was mainly using intellij only

**Comment by fbricon** [comment]
can you do a screencast of the small project exhibiting slow content assist?

**Comment by islam-taha** [comment]
here it is
![](http://g.recordit.co/cJp0K3ryRx.gif)

**Comment by islam-taha** [comment]
Also in case i typed all small case word it appears wrong in the suggestions like `system` instead of `System`. I believe this is not the case in all words like the one in the screen case `sortedset`.

**Comment by fbricon** [comment]
Ok, it's a bit slow. I'm not sure we can improve that from our side, since we're calling Eclipse JDT under the hood. @gorkem is the content-assist expert :-)

And yeah we still have a bit of work to do on the relevance part

**Comment by gorkem** [comment]
We also calculate the replacement strings upfront for **all** completions so it is probably affecting the performance. There is some room for improvement.

**Comment by fbricon** [comment]
@gorkem indeed, it's much snappier when commenting that line in CompletionProposalRequestor:
```java
this.proposalProvider.updateReplacement(proposal,$, '\0',new ArrayList<Integer>());
```

So now we need to find a way to compute the replacement at the moment the proposal is selected. No idea how to do it.

**Comment by fbricon** [comment]
Fixed with https://github.com/gorkem/java-language-server/commit/1f53c45faf8feb18500f83e031516a14e66ec8d9

**Comment by Marti2203** [comment]
Hi, I am currently having the same issue. There are 4 files in the folder and 1 jar and the intellisense is quite slow.

**Comment by fbricon** [comment]
@Marti2203 can you try disabling all other Java extensions, see if performance improves?

**Comment by Marti2203** [comment]
Yes, the performance got a lot better - all 12 cores are now at 50% for a small period of time and not at 100%. I had the java extension pack only, this is quite strange.

**Comment by AYiXi** [comment]
spring boot package makes java very slow, I tested

**Comment by olyop** [comment]
Same problem here at least 5 seconds for me. Java extensions I use are:

vscjava.vscode-java-debug
vscjava.vscode-gradle
vscjava.vscode-java-dependency
redhat.java
pivotal.vscode-spring-boot
