### ISSUE TITLE
Custom Source Actions

### ISSUE THREAD

**Issue by astrelsky** [redhat-developer/vscode-java#1216]
It would be a really cool feature to be able to write custom source actions by writing a script in java. As an example you would simply create a new java file which would extend VscodeSourceAction and then do what you'd like. A setting for the directory to search for these java files would likely be appropriate. 

This can make minor wants, such as an action to only generate getters and not setters, easier to achieve. This would also remove the need to create an entire vscode plugin to implement additional source actions.

**Comment by testforstephen** [comment]
Not fully understand your scenario. Do you mean something like [folder source actions](https://marketplace.visualstudio.com/items?itemName=bierner.folder-source-actions)?

**Comment by astrelsky** [comment]
> Not fully understand your scenario. Do you mean something like [folder source actions](https://marketplace.visualstudio.com/items?itemName=bierner.folder-source-actions)?

I don't think so. Its more to add to the list of Source Actions you implemented. (Organize imports, generate getters/setters, generate constructors, etc). It would be handy to be able to write our own without having to create an entire vscode extension.

**Comment by testforstephen** [comment]
> It would be handy to be able to write our own without having to create an entire vscode extension.

Is there anything blocking you do that? Or what change is required for vscode-java to achieve that?

**Comment by astrelsky** [comment]
> > It would be handy to be able to write our own without having to create an entire vscode extension.
> 
> Is there anything blocking you do that? Or what change is required for vscode-java to achieve that?

I've setup a repo for a simple example of what I'm suggesting to be able to do. Hopefully this provides some better insight.

https://github.com/astrelsky/vscode-java-source-action-example

**Comment by testforstephen** [comment]
This may be an interesting idea, but it's not possible for now. Worth a look in future.

Java is a language that needs to be compiled, and apparently we cannot ensure the contributed Java snippets are correctly written. Besides, the language features needs parse AST and generate workspace edit, i don't believe it's easy to write in one Java file.

If you'are interested, please take a look about how to contribute Java features by leverage vscode-java. https://github.com/redhat-developer/vscode-java/wiki/Contribute-a-Java-Extension

**Comment by astrelsky** [comment]
> This may be an interesting idea, but it's not possible for now. Worth a look in future.
> 
> Java is a language that needs to be compiled, and apparently we cannot ensure the contributed Java snippets are correctly written. Besides, the language features needs parse AST and generate workspace edit, i don't believe it's easy to write in one Java file.
> 
> If you'are interested, please take a look about how to contribute Java features by leverage vscode-java. https://github.com/redhat-developer/vscode-java/wiki/Contribute-a-Java-Extension

Ideally the handling of language features would be done in a base class in vscode-java. However, I was under the impression that they were being done through eclipse.jdt.ls instead of via the vscode api.

I have come to the conclusion that it is simply impossible to contribute a Java extension. At least by following the wiki. I'll be opening a separate issue regarding that.
