### ISSUE TITLE
Intellisense not work on close source jar

### ISSUE THREAD

**Issue by Fubuchi** [redhat-developer/vscode-java#1217]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10
- JDK version: openjdk 12.0.2 2019-07-16
- Visual Studio Code version: 14.1.1
- Java extension version: 0.55.1

##### Steps To Reproduce
1. Create a maven project that use a close source dependency (e.g: [aspose words](https://repository.aspose.com/repo/com/aspose/aspose-words/15.12.0/))
2. Use the dependency in project

Sample project: 
[aspose-word-test.zip](https://github.com/redhat-developer/vscode-java/files/3998973/aspose-word-test.zip)

##### Current Result

- Auto import classes from aspose word works.
- Auto complete for methods of classes in aspose word doesn't work, when I type a variable and press the dot key, no suggestion is shown. When I hover on a method, the language server log say:

> [Error - 02:58:34] 02:58:34, 25 thg 12, 2019 Error computing hover
> null
> java.lang.NullPointerException
> 	at java.base/java.lang.String.<init>(String.java:260)
> 	at java.base/java.lang.String.valueOf(String.java:3056)
> 	at org.eclipse.jdt.internal.core.JavadocContents.getMethodDoc(JavadocContents.java:178)
> 	at org.eclipse.jdt.internal.core.BinaryMethod.getAttachedJavadoc(BinaryMethod.java:751)
> 	at org.eclipse.jdt.ls.core.internal.javadoc.JavadocContentAccess2.getHTMLContent(JavadocContentAccess2.java:593)
> 	at org.eclipse.jdt.ls.core.internal.javadoc.JavadocContentAccess2.getMarkdownContentReader(JavadocContentAccess2.java:2500)
> 	at org.eclipse.jdt.ls.core.internal.HoverInfoProvider.computeJavadoc(HoverInfoProvider.java:254)
> 	at org.eclipse.jdt.ls.core.internal.HoverInfoProvider.computeHover(HoverInfoProvider.java:135)
> 	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.computeHover(HoverHandler.java:52)
> 	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.hover(HoverHandler.java:41)
> 	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$6(JDTLanguageServer.java:527)
> 	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:963)
> 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

##### Expected Result
- Auto complete work for method.

**Comment by fbricon** [comment]
I confirm something's odd with this project. I initially got it to work when I imported the project with JDK 13, then switched to JDK 11, 12 and back to 13 and got the same NPE.
Need to debug what's happening. cc @snjeza

**Comment by fbricon** [comment]
I don't understand how I could see any doc on hover. Must have been something else. Anyways, Eclipse has the same NPE issue with the javadoc jar bound to aspose-words jar.
Not being able to compute javadoc is one thing, but crashing completion is another issue. Failing to  compute the completion item description should be logged, but not prevent completion at all. org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalDescriptionProvider.updateDescription(CompletionProposalDescriptionProvider.java:635) should be surrounded by a try/catch block:

```
java.lang.NullPointerException
	at java.base/java.lang.String.<init>(String.java:267)
	at java.base/java.lang.String.valueOf(String.java:3366)
	at org.eclipse.jdt.internal.core.JavadocContents.getMethodDoc(JavadocContents.java:178)
	at org.eclipse.jdt.internal.core.BinaryMethod.getParameterNames(BinaryMethod.java:371)
	at org.eclipse.jdt.internal.codeassist.InternalCompletionProposal.findMethodParameterNames(InternalCompletionProposal.java:324)
	at org.eclipse.jdt.internal.codeassist.InternalCompletionProposal.findParameterNames(InternalCompletionProposal.java:942)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalDescriptionProvider.appendUnboundedParameterList(CompletionProposalDescriptionProvider.java:140)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalDescriptionProvider.createMethodProposalDescription(CompletionProposalDescriptionProvider.java:80)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalDescriptionProvider.createMethodProposalLabel(CompletionProposalDescriptionProvider.java:297)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalDescriptionProvider.updateDescription(CompletionProposalDescriptionProvider.java:635)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.toCompletionItem(CompletionProposalRequestor.java:212)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:196)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:147)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:76)
```

**Comment by Fubuchi** [comment]
Aspose word require a separate java doc dependency, I'm not sure it has any thing to do with the NPE

```
<dependency>
          <groupId>com.aspose</groupId>
          <artifactId>aspose-words</artifactId>
          <version>15.12.0</version>
          <classifier>jdk16</classifier>
        </dependency>
        <dependency>
          <groupId>com.aspose</groupId>
          <artifactId>aspose-words</artifactId>
          <version>15.12.0</version>
          <classifier>javadoc</classifier>
      </dependency>
```

**Comment by snjeza** [comment]
Eclipse JDT can't parse the com.aspose:aspose-words:15.12.0 javadoc.
@Fubuchi you can try to exclude the the com.aspose:aspose-words:15.12.0:javadoc dependency or update to the 19.12 version.

**Comment by Fubuchi** [comment]
I update to the latest version and the NPE gone but some methods of com.aspose.words.Document still do not have intellisense like save or getMailMerge

**Comment by snjeza** [comment]
@Fubuchi You can try https://raw.githubusercontent.com/snjeza/vscode-test/master/java-0.56.0.vsix
You will still see the exception, but intellisense and hover will work.

**Comment by Fubuchi** [comment]
@snjeza confirmed, intellisense and hover works now.
