### ISSUE TITLE
When run main function in test,Maven project couldn't locate the test-classes folders

### ISSUE THREAD

**Issue by zxc2012** [redhat-developer/vscode-java#1218]
[provide a description of the issue]

##### Environment
- Operating System:Windows 10
- JDK version:1.8.0
- Visual Studio Code version:January 2020 (version 1.42)
- Java extension version:0.55.1
## `maven project tree:`
-pom.xml
-src
---main
-----java
-----resource
----------hanlp.properties
---test
##### Steps To Reproduce
1. debug/test class in main folder--OK
### Run test test\...\HelloWord,java\void test--OK(as shown in the picture)
Output in console
![image](https://user-images.githubusercontent.com/30518986/71446275-97793900-275c-11ea-9a99-3f78bef18172.png)

### 2. Run test\...\HelloWord,java\void main--Not found
as is shown in the picture,target\test-classes couldn't be located,it pointed to target\classes
![QQ截图20191225212903](https://user-images.githubusercontent.com/30518986/71446381-98f73100-275d-11ea-937b-9ebf971d394f.png)
### Then I tried fix the command manually,and it works
![image](https://user-images.githubusercontent.com/30518986/71446351-43228900-275d-11ea-878c-360081746c1d.png)

##### Current Result
maven project could't locate the right folders,but test is ok,very confusing
##### Expected Result
be able to run main function in test folders as well
##### Additional Informations
eclipse is ok
### The project relies on many packages,so I made a simple project
in /Cylinder/src/test/java/com/qianxu/cylinder/CylinderTest.java
you may try running *void main* and *void Test* ,I still got the same problem
[maven test](https://github.com/zxc2012/NXP_Creative/tree/master/Cylinder)

**Comment by testforstephen** [comment]
Could you try to add "java.debug.settings.console": "internalConsole" to your user setting?

**Comment by testforstephen** [comment]
This issue is related with https://github.com/microsoft/vscode-java-debug/issues, please move the issue there.
