### ISSUE TITLE
Allow users to enable automatic project configuration

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#122]
When modifying a pom.xml or a gradle file, java project configuration and classpath should be updated. While it's possible do trigger a manual update (ctrl+alt+u or cmd+alt+u), it'd be more convenient to do it automatically, as requested by @pmuir.

The proposed change is to display a warning when a build file has been modified, asking the user to update the java configuration. Choices are
- Never: no project configuration will be triggered and the message won't show up again 
- Now:  project configuration will be triggered and the message will show up next time
- Always: project configuration will be triggered from now on and  and the message won't show up again

**Comment by pmuir** [comment]
@fbricon my other comment was that I wouldn't necessarily realise that "Update project configuration" would be what would cause the project classpath to update (unless I had used Eclipse).

**Comment by fbricon** [comment]
@pmuir that should be clearer, hopefully:
<img width="843" alt="capture d ecran 2016-12-21 a 14 50 20" src="https://cloud.githubusercontent.com/assets/148698/21403919/d8125b0a-c78c-11e6-8c6c-e5b2fc101721.png">
