### ISSUE TITLE
Don't show notifications right after startup

### ISSUE THREAD

**Issue by jrieken** [redhat-developer/vscode-java#1225]
👋 vscode dev playing with the java extension here. I noticed some notification spam after first startup. One is about missing maven-exec which seems somewhat reasonable, the other is about configuring excludes for Java project files. I think that's quite annoying esp. in contrast to the maven notification and my suggestion would be to move that into the "Java Getting Started" page.

<img width="1296" alt="Screenshot 2020-01-03 at 11 56 19" src="https://user-images.githubusercontent.com/1794099/71727116-9372a880-2e39-11ea-8d6a-2bf418cb8d94.png">

**Comment by akaroml** [comment]
This specific issue is tracked by #618 
We received a lot of complaints about the Java LS generating files in the repository. The notification is a workaround we provided to ease the pain a bit.
We'll revisit this in the first half of 2020.

**Comment by jdneo** [comment]
Addressed by https://github.com/redhat-developer/vscode-java/pull/2153.

This notification won't appear now.
