### ISSUE TITLE
Format On Save not working in presence of semantic error

### ISSUE THREAD

**Issue by jrieken** [redhat-developer/vscode-java#1226]
##### Environment
- Operating System:
- JDK version: using Java8-dev-container, https://github.com/microsoft/vscode-dev-containers/blob/6c963f93705796aef2166502a2030866987e5a4f/containers/java-8/.devcontainer/Dockerfile
- Visual Studio Code version: insider
- Java extension pack: 0.8.1

##### Steps To Reproduce
1. enable format on save
1. add a semantic error, like calling a constructor without arguments
1. save

##### Current Result

no formatting happening

##### Expected Result

formatting should happen

**Comment by jrieken** [comment]
hm, this might actually be caused by a missing semicolon which makes this a syntax error... 🤔

**Comment by akaroml** [comment]
@testforstephen let's see if the formatting could work when there are syntax errors.

**Comment by fbricon** [comment]
Works as intended. The method in which there's a missing semicolon won't be formatted, but the rest of the file will be (provided there are no other syntax errors. 
![Feb-04-2020 17-27-23](https://user-images.githubusercontent.com/148698/73764667-b44d5700-4773-11ea-85e7-be57a2254148.gif)
