### ISSUE TITLE
Align settings categories names

### ISSUE THREAD

**Issue by jrieken** [redhat-developer/vscode-java#1227]
See attached screen capture. It upper-case every except for "Java configuration". I would drop "configuration" because that pretty obvious from the context you are in. Iff not make it "*C*onfiguration" to be aligned with other setting categories

<img width="243" alt="Screenshot 2020-01-03 at 16 41 24" src="https://user-images.githubusercontent.com/1794099/71732580-ee130100-2e47-11ea-9ae1-b8c805abe6c0.png">

**Comment by akaroml** [comment]
Agreed. @Eskibear could you help quickly send a PR?
