### ISSUE TITLE
The java.home variable defined in Visual Studio Code settings points to a missing or inaccessible folder (C:\Program Files\Java\jdk-11)

### ISSUE THREAD

**Issue by UbaidurRehman1** [redhat-developer/vscode-java#1228]
I have done all troubleshooting procedures to define java.home variable. 
I have created java.home in both user settings and workspace settings in VS code. Then I have define JAVA_HOME and JDK_HOME in system varibles. Then define the path of jdk-11/bin in the system path.

##### Environment
- Windows 10 Education Version 2004 OS Build 19037.1
- JDK version: openjdk 11 2018-09-25
- Visual Studio Code version: 1.41.1
- Java extension version: 0.8.1

##### Steps To Reproduce
1. Add remote WSL: Ubunut-18.04 distro
2. Now install Java Extension Pack.
3. When opening the Java Source Code (Maven) then pop up opening that "The java.home variable defined in Visual Studio Code settings points to a missing or inaccessible folder (C:\Program Files\Java\jdk-11)"

##### Additional Informations
Error Screen
https://res.cloudinary.com/student1234567/image/upload/v1578290692/error1.png

**Comment by danielshoun** [comment]
I also started getting this error despite having no problems just a couple days ago.

**Comment by fbricon** [comment]
I honestly don't know how remote wsl works, I'm on a mac. I don't know if it's a problem caused by the remote wsl not having access to your local jdk. That's a question for @akaroml's team

**Comment by UbaidurRehman1** [comment]
> I honestly don't know how remote wsl works, I'm on a mac. I don't know if it's a problem caused by the remote wsl not having access to your local jdk. That's a question for @akaroml's team

Yup, this is the real problem: **Remote WSL 2 has no access to local JDK**

**Comment by fbricon** [comment]
@UbaidurRehman1 then you might want to install a JDK directly from WSL2. See if this provides any help: https://stackoverflow.com/questions/36478741/installing-oracle-jdk-on-windows-subsystem-for-linux

**Comment by UbaidurRehman1** [comment]
Alright, I have found **the solution,** 
Actually the mistake was on my end, I mistakenly thought that the path should be in Windows. 
But the path of **JDK should be in WSL distro.** 

Solution:
- Install JDK in WSL 
- Export the path of JDK in WSL (write **export JDK_HOME=/path/to/jdk/**) in ~/.bashrc file and source it
-  Now restart VS Code 

VS Code will automatically detect the JDK.

**Comment by danuvian** [comment]
I had the same issue. The problem was, I opened VS Code in Windows and then I got that error message.  In you are developing in WSL2, you have to open VSC in WSL2. So, in your WSL2 terminal, go to your repo, and type "code ." This will open VSC in WSL2 and the error goes away.
