### ISSUE TITLE
 // Failed to get sources. Instead, stub sources have been generated by the disassembler.

### ISSUE THREAD

**Issue by sukanzubair** [redhat-developer/vscode-java#1231]
[provide a description of the issue]

##### Environment
- Operating System: Win10
- JDK version: 13
- Visual Studio Code version:1.1.11
- Java extension version: 0.55.1

##### Steps To Reproduce
1. open a muti root project
2. navigate(go to implemetation ) of class that is in the referenced project

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Get the .class file opening with the message
"Failed to get sources. Instead, stub sources have been generated by the disassembler."

##### Expected Result
Navigation to the .java file in the workspace folder
##### Additional Informations
I opened the projects in Intelli J and experienced the same problem.
I invalidated the cache in intelli j and then it worked in intelli j, the problem is still persisting in vs code

**Comment by sukanzubair** [comment]
Package name is case sensitive and if not exact in the POM file the dependency struggles to resolve

**Comment by DAflamingFOX** [comment]
what was the solution to this?

**Comment by sukanzubair** [comment]
@DAflamingFOX - As per my last comment, the package names were case sensitive and I the name (casing) did not match in the POM files.

**Comment by DAflamingFOX** [comment]
Ok, then I am having a different cause, or the code from developers is wrong.
