### ISSUE TITLE
Lombok issues when running vscode remote to ssh linux server

### ISSUE THREAD

**Issue by cameronbraid** [redhat-developer/vscode-java#1233]
##### Environment
- Operating System:

VSCode running on OSX Catalina 10.15.2 (19C57)
VSCode ssh to Ubuntu 19.10

- JDK version:

1.8.0_161

- Visual Studio Code version:

1.41.1

- Java extension version:

v0.55.1

##### Steps To Reproduce
1. Open VSCode
2. Connect to remote linux via SSH
3. Open java project

The same java project has no lombok issues when using VSCode locally, or when building with maven.

When using VSCode remote over SSH it has issues like :

cannot find symbol
  symbol:   method builder()
  location: class ....

![image](https://user-images.githubusercontent.com/672405/72203388-60768780-34bf-11ea-99f0-a80308f409cc.png)

**Comment by testforstephen** [comment]
Java extension already provides built-in lombok support, assume that this is fixed in latest version. Closing it. Feel free to reopen it if it still exists.
