### ISSUE TITLE
Auto-completion doesn't work between round bracket of auto completed function call.

### ISSUE THREAD

**Issue by euphooria** [redhat-developer/vscode-java#1239]
[provide a description of the issue]
No auto-completion between round bracket of function call.
##### Environment
- Operating System: Ubuntu16.04
- JDK version: openjdk 1.8.0_232
- Visual Studio Code version: 1.41.1
- Java extension version: 0.55.0

##### Steps To Reproduce
1. call function using autocompletion.
2. try to input vairable between round bracket of called function.

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
[step 2] Auto-completion does not work.
##### Expected Result
[step 2] Auto-completion works.
##### Additional Informations
As operation A: Auto-completion does not work between brackets.
As operation B: If I delete auto-generated variable between brackets, then move cursor out of brackets, then move cursor into brackets again. Auto-completion works again!
![out](https://user-images.githubusercontent.com/47882481/72514592-b1082f00-3889-11ea-9cb3-992ef65c1d06.gif)

**Comment by fbricon** [comment]
When inserting the method body, vscode is in "snippet mode", it allows you to jump from one placeholder to the next by pressing tab. In that mode, completion is disabled. To exit snippet mode, just press esc, then try to complete again

**Comment by euphooria** [comment]
Thanks for your answer. 
But any solution to keep completion enalbed while in "snippet mode"? Or how can I close "snippet mode"? Because I think it is better to keep completion then snippet if both of them cannot keep enabled at same time.
