### ISSUE TITLE
Cannot read property 'startLineNumber' of undefined

### ISSUE THREAD

**Issue by JamesChan** [redhat-developer/vscode-java#124]
[provide a description of the issue]

##### Environment
- Operating System: Windows 7
- JDK version: 1.8.0_111
- Visual Studio Code version:  1.8.1
- Java extension version:

##### Steps To Reproduce
When open [NOS project](https://github.com/opennetworkinglab/onos), message hints: "Cannot read property 'startLineNumber' of undefined"

[attach a sample project reproducing the error]

**Comment by gorkem** [comment]
I can not reproduce this with the 0.0.8 release. Can you produce more specific instructions which files did you open. Also can you make sure it is the java extension that causes the error by disabling your other extensions?

**Comment by leonardosnt** [comment]
@gorkem 

![gif](https://cloud.githubusercontent.com/assets/13869336/21559302/c7f71b84-ce30-11e6-986b-2fbd93316415.gif)

**Comment by gorkem** [comment]
Ahh I see.. Happens when no Java code is on the cursor position.
