### ISSUE TITLE
Java project: Import all jar in folder

### ISSUE THREAD

**Issue by carlitador** [redhat-developer/vscode-java#1240]
I would like to import all jar files into my vscode project classpath.
If I do this it works, but only for one library of course:

In my case I have almost 100 .jar files to import. If I put them in lib and put try this:
 `<classpathentry kind="lib" path="lib"/>`

Or this:

` <classpathentry kind="lib" path="lib/*.jar"/>`

Or this

`<classpathentry kind="lib" path="lib/*"/>`

Do not work

I also tried putting with changing the settings this way:
```
"java.project.referencedLibraries": [
   "lib/mylib/*.jar"
 ]
```
But it doesnt work either
Any idea?

**Comment by Eskibear** [comment]
https://github.com/microsoft/vscode-java-dependency/releases/tag/0.8.0

See if it's what you want.

**Comment by jdneo** [comment]
@carlitador Is your project an `Eclipse project`?

**Comment by carlitador** [comment]
> @carlitador Is your project an `Eclipse project`?

I think it is.
I created a Java project inside vscode and I have some settings files mentioning eclipse inside. So I suppose it is the case.
Thank you

**Comment by jdneo** [comment]
@carlitador 

If you triggered `Create Project` in VS Code, it will generate an `Eclipse` project for you. But the `"java.project.referencedLibraries"` won't work in Eclipse project.

I think you can just create an **empty** folder and put your java files inside that folder. By default, the Language Server will [add all `jar`s inside the `lib` folder into the project's classpath](https://code.visualstudio.com/docs/java/java-project#_adding-external-jar).

If you don't want to put jars inside `lib` folder, then `java.project.referencedLibraries` can be used -- Glob pattern is supported.

**Comment by carlitador** [comment]
> @carlitador
> 
> If you triggered `Create Project` in VS Code, it will generate an `Eclipse` project for you. But the `"java.project.referencedLibraries"` won't work in Eclipse project.
> 
> I think you can just create an **empty** folder and put your java files inside that folder. By default, the Language Server will [add all `jar`s inside the `lib` folder into the project's classpath](https://code.visualstudio.com/docs/java/java-project#_adding-external-jar).
> 
> If you don't want to put jars inside `lib` folder, then `java.project.referencedLibraries` can be used -- Glob pattern is supported.

I just tried that. I don't have errors when importing (not red lines under "import lib") but I don't have access to any attributes or methods of the objects coming from these lib...
Any idea?
Thank you

**Comment by jdneo** [comment]
Could you please share the `settings.json`? Also, is there anything suspicious in the Language Server's output channel?

**Comment by carlitador** [comment]
Here is the settings.json:
`{
    "java.dependency.syncWithFolderExplorer": true
}`

The language server's output channel asks:
"Do you want to exclude the vscode java project settings file (.classpath, .project, .settings, .factorypath)"
And also says:
"Classpath is incomplete. Only syntax errors will be reported"

**Comment by jdneo** [comment]
@carlitador 

Since you get the notification: `"Do you want to exclude the vscode java project settings file (.classpath, .project, .settings, .factorypath)"`, I guess you are still in an Eclipse project.

Please make sure the empty folder is just created manually by yourself, which means, it's literally new and  empty. Then you can copy your files/libs into it.

If the project is created from the VS Code command, that will still be an Eclipse project.

**Comment by carlitador** [comment]
> @carlitador
> 
> Since you get the notification: `"Do you want to exclude the vscode java project settings file (.classpath, .project, .settings, .factorypath)"`, I guess you are still in an Eclipse project.
> 
> Please make sure the empty folder is just created manually by yourself, which means, it's literally new and empty. Then you can copy your files/libs into it.
> 
> If the project is created from the VS Code command, that will still be an Eclipse project.

I am sure I started from a new empty folder manually. I've just a java script inside, the libraries, thats all.

**Comment by jdneo** [comment]
Hmm, the folder structure looks fine to me. Not sure what's wrong happening 🤔 

@testforstephen Do you have any idea?

**Comment by carlitador** [comment]
> Hmm, the folder structure looks fine to me. Not sure what's wrong happening thinking
> 
> @testforstephen Do you have any idea?

**Comment by carlitador** [comment]
> Hmm, the folder structure looks fine to me. Not sure what's wrong happening thinking
> 
> @testforstephen Do you have any idea?

Hi jdneo,
Seemed to be a problem with my JDK on Linux Mint. Just installed JDK 13 and it works fines now.
Sorry for that
Cheers
