### ISSUE TITLE
paste a multi-line string should create a java string

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#1249]
try paste this into a string, i.e. between two quotes "":

```
SELECT payment_date, amount, sum(amount) OVER (ORDER BY payment_date)
FROM (
  SELECT CAST(payment_date AS DATE) AS payment_date, SUM(amount) AS amount
  FROM payment
  GROUP BY CAST(payment_date AS DATE)
) p
ORDER BY payment_date;
```

in eclipse it becomes a valid java string in vscode it generates non-compilable code.

Would be great if vscode could help here :)

**Comment by akaroml** [comment]
Since the `Paste` event is now available to extension, we can definitely provide some help here. @jdneo please also help track this in the area of adopting editor events.

**Comment by datho7561** [comment]
It looks like the relevant API is still just a proposal (https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.documentPaste.d.ts), but I'll see if I can get a prototype working. (Also, maybe I'm looking in the wrong place)

**Comment by fbricon** [comment]
You need to set `"editor.experimental.pasteActions.enabled": true` for this to work.
i.e.
<img width="963" alt="Screenshot 2023-01-17 at 08 58 14" src="https://user-images.githubusercontent.com/148698/212841179-c6a18b4c-ac86-46cc-a224-a0ad642e85c6.png">

**Comment by gakkiyomi** [comment]
> "editor.experimental.pasteActions.enabled": true

i have no this settings in my vscode

**Comment by rgrunber** [comment]
I think the paste action setting has been replaced by `editor.pasteAs.enabled`. It should default to enabled though. See https://github.com/microsoft/vscode/pull/181375 .
