### ISSUE TITLE
please support @SuppressWarnings({"foo", "bar"})

### ISSUE THREAD

**Issue by jessefarinacci** [redhat-developer/vscode-java#1251]
Other Java IDEs support the ability to suppress specific warnings in source code via the `@SuppressWarnings` annotation. Please extend the vscode-java project with the same ability, it is quite useful and a de facto standard.

##### Environment
- Operating System: *
- JDK version: *
- Visual Studio Code version: *
- Java extension version: *

##### Current Result

Warnings are shown even when the Java annotation `@SuppressWarnings("deprecated")` is placed on any particular class or method that uses a deprecated method internally.

##### Expected Result

Code marked as `@SuppressWarnings`, scoped to wherever it is placed, class or method, ought not to report warnings in the Problems area for that specific type, if specified.

##### Additional Informations

Eclipse: https://help.eclipse.org/2019-12/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-suppress_warnings.htm

**Comment by jdneo** [comment]
The `@SuppressWarnings()` should work. Could you please try annotate with `@SuppressWarnings("deprecation")` instead of `@SuppressWarnings("deprecated")`?

**Comment by jessefarinacci** [comment]
My apologies, I had `deprecated` and not `deprecation` as is documented. Changing it to `deprecation` does indeed silence the warnings. Thanks for your help, closing.
