### ISSUE TITLE
Lombok support documentation is not being specific

### ISSUE THREAD

**Issue by GabrielBB** [redhat-developer/vscode-java#1253]
The [Lombok Support documentation](https://github.com/redhat-developer/vscode-java/wiki/Lombok-support) says this:

> Old versions of Java might need an additional -Xbootclasspath/a:/path/to/lombok.jar flag. The a: prefix in the Xbootclasspath flag is critical, make sure it's added.

I would like to know which "Old versions of Java" need that argument

**Comment by akaroml** [comment]
@jdneo could you take a look?

**Comment by jdneo** [comment]
Lombok and JDK runtime are all embedded now.
