### ISSUE TITLE
Quick fix to create a local variable

### ISSUE THREAD

**Issue by rustyx** [redhat-developer/vscode-java#1254]
This is a request to implement quick fix / refactoring shortcuts for

* Create local variable
* Create field
* Create parameter

Like it is done in Eclipse:

![eclipse quick fixes java](https://rustyx.org/temp/eclipse-java-create-local-variable.gif)

##### Steps To Reproduce

1. Write `int x = 1; y = x;`
2. Place the cursor at `y`, press `Ctrl`-`.`

##### Current Result

* Change modifiers to final where possible
* Move

##### Expected Result

* Create local variable
* Create field
* Create parameter
* Change modifiers to final where possible
* Move

##### Environment

- Visual Studio Code version: 1.41.1
- Java extension version: 0.55.0

**Comment by NikolasKomonen** [comment]
Looks like its already there. I see the confusion though because you have to specifically click the variable and then the lightbulb will give the correct quickfixes

![variable](https://user-images.githubusercontent.com/32624665/73598348-44d23000-4505-11ea-9a0b-0566266ab260.gif)

**Comment by rustyx** [comment]
OK thanks. I have *never* seen these appear for me.

For me these appear only after saving the document, and even then after a delay of about a second or sometimes never at all. I don't save files that I know won't compile, hence I have never seen these.
In Eclipse the quick fix is available as soon as I type a valid statement, without having to save anything.

Also if the mouse pointer is nearby, it auto-selects the option underneath it, which is quite inconvenient if I want to use a keyboard instead (`Ctrl`-`.`, `Enter`). This does not happen in Eclipse, there "Create local variable" is always the default choice when pressing `Enter`, unless the mouse is moved.

And in VSCode it sometimes overwrites or damages the line after the replacement.

**Comment by akaroml** [comment]
@jdneo this could also be a candidate for inferring the proper selection range to provide code actions.

Here, users may look for potential fixes for the problems in the SAME LINE. Now users have to put the cursor right next to the variable name for the fix to appear.

**Comment by jdneo** [comment]
This seems already fixed by today (0.77.0)


https://user-images.githubusercontent.com/6193897/115502805-124a5980-a2a8-11eb-83c9-89906828b05e.mp4

**Comment by testforstephen** [comment]
@jdneo thanks for verification.
