### ISSUE TITLE
Completion result limit causes items to not be found

### ISSUE THREAD

**Issue by jmbockhorst** [redhat-developer/vscode-java#1257]
Because of the new completion result limit of 50, items that are not in the initial list are not found when the list is narrowed down. If the limit is removed, it works as intended. At first I thought this was due to intellicode and reported here: https://github.com/MicrosoftDocs/intellicode/issues/164

##### Environment
- Operating System: Windows_NT x64 10.0.19546
- JDK version: 1.8.0_202
- Visual Studio Code version: 1.42.0-insider (Commit: 5dcf2c96b6562b3aa879dbb455de4b58e17cb804)
- Java extension version: 0.55.1

**Steps to Reproduce / Scenario:**

1. Use Spring Boot `JdbcTemplate` (org.springframework.jdbc.core.JdbcTemplate) variable
2. Try find the `update()` functions bring pressing "." after the variable name.

![completion](https://user-images.githubusercontent.com/44308390/73199548-a4da6800-40fa-11ea-884d-6142b8e4e8f7.gif)

##### Current Result
The `update()` function is not listed for completion due to the 50 completion item limit. 

##### Expected Result
`update()` functions should appear after the list is narrowed down.

**Comment by fbricon** [comment]
Can you provide a sample project reproducing the error? So we compare with similar classpaths.
Are you certain disabling intellicode doesn't change anything?

**Comment by fbricon** [comment]
Ok that's an issue we discussed already with @akaroml and his team. We need to introduce an extension point for 3rd party ranking strategies (intellicode) to be called from the full search result list.

**Comment by jmbockhorst** [comment]
Disabling intellicode does fix it, which is why I initial made the issue there.

**Comment by Harvtronix** [comment]
I am hitting this 50 entry limit issue as well.

To reproduce:
- In a Java file, type `java.nio.file.Files.` and expect to see `readAllBytes`, `readAllLines`, etc..., but list ends at `probeContentType`.
- Typing `java.nio.file.Files.read` only shows 3 entries, none of which are readAll*.
- If I then click off and back on the line (to make the autocomplete window disappear) and then type "a" at the end, the results come up as expected.

```Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362```

**Comment by dragondove** [comment]
![limit items](https://user-images.githubusercontent.com/24190403/74207204-8909c100-4cb9-11ea-8099-8132e72329a5.png)
A simple way to reproduce is to input new FileInputStream().

**Comment by Yiotis98** [comment]
![screenshot](https://user-images.githubusercontent.com/57769091/74254702-7ca55880-4cf9-11ea-83f3-2a05b141dd7c.png)

It happens also at my javafx application.

**Comment by akaroml** [comment]
@eskibear is working on a fix to resolve this issue.
To mitigate, you can try either of the following:
1. Disable IntelliCode extension for now.
or 
2. Set `java.completion.maxResults` to `0` to not limit the search result count. (could be running slow though).

**Comment by fbricon** [comment]
@akaroml: trying the latest vscode-java build, with Intellicode 1.2.5 (released today), I see some completions are now back, but there are still issues (see #1316):
- typing Arrays -> java.util.Arrays is not proposed
- with java.util.Arrays imported, typing Arrays.sort doesn't propose the sort methods 

Disabling Intellicode once again fixes it.

**Comment by Eskibear** [comment]
IntelliCode 1.2.5 was released on 2/6/2020, 4:25:18 AM. The fixes will be in 1.2.6.

**Comment by fbricon** [comment]
my bad. I saw 2/5/2020, 9:25:18 PM on the marketplace and thought we were still in February ;-)

So when will 1.2.6 be released then?

**Comment by Eskibear** [comment]
I just asked the team about it, and I’ll let you know as soon as they reply.

**Comment by Eskibear** [comment]
@fbricon IntelliCode 1.2.6 has been released with the fix.

**Comment by jmbockhorst** [comment]
Verified that the update fixes this.
