### ISSUE TITLE
Peek Definition for .class files seems to work inconsistently

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-java#126]
[Peek Definition](https://code.visualstudio.com/docs/editor/editingevolved#_peek) for Java elements referenced from .class files does not work.

**Comment by fbricon** [comment]
I've seen `⌥F12` both work and fail. It's inconsistent.

**Comment by fbricon** [comment]
Do you have a consistent way to see it fail?

**Comment by gorkem** [comment]
Not really. Today it just works 😕
