### ISSUE TITLE
Format Switch Statement

### ISSUE THREAD

**Issue by spottedmahn** [redhat-developer/vscode-java#1261]
##### Environment
- Operating System: WSL 1 on Win 10
- JDK version: 11.0.5 2019-10-15
- Visual Studio Code version: 1.41.1
- Java extension version: 0.55.1

##### Steps To Reproduce
1. Add a `switch` statement format the document

[sample project](https://github.com/spottedmahn/experiments-2020/blob/format-switch-issue/java-tests-issue/src/main/java/miked/javatestsissue/Library.java)

##### Current Result
![image](https://user-images.githubusercontent.com/14079228/73784100-dab6c680-4762-11ea-85cc-c563ac57dac5.png)

##### Expected Result
![image](https://user-images.githubusercontent.com/14079228/73784081-d25e8b80-4762-11ea-9dd0-c20528307584.png)

##### Additional Informations
Is this configurable?  This is the extension that is formatting the code, right?

**Comment by snjeza** [comment]
@spottedmahn You can try to set the following property:

```
org.eclipse.jdt.core.formatter.indent_switchstatements_compare_to_switch=true
```

to <your_project>/.settings/org.eclipse.jdt.core.prefs or your formatter file.
See https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings

**Comment by spottedmahn** [comment]
thanks for the reply!

No luck though 🤷‍♂️.  I also closed and reopened VSCode just incase.

![image](https://user-images.githubusercontent.com/14079228/73874700-f92fc700-4821-11ea-8b1f-09632ec6c7f3.png)

**Comment by snjeza** [comment]
@spottedmahn could you use
```
<your_project>/.settings/org.eclipse.jdt.core.prefs 
```
instead of 
```
<your_project>/.settings/org.eclipse.buildship.core.prefs 
```

**Comment by spottedmahn** [comment]
Oh, I should pay closer attention to the details 😜

GTG 🎉, thanks! 🤝

![image](https://user-images.githubusercontent.com/14079228/73876379-e4a0fe00-4824-11ea-9873-57ecf51ec907.png)

![image](https://user-images.githubusercontent.com/14079228/73876420-eff42980-4824-11ea-815e-773b667e0780.png)

**Comment by fbricon** [comment]
@snjeza can you please make it the default setting in jdt.ls. Current formatting of switch cases makes no sense at all.

**Comment by spottedmahn** [comment]
>Current formatting of switch cases makes no sense at all

Glad I don't stand alone! 😀

**Comment by fbricon** [comment]
There's a rationale for not indenting cases: https://stackoverflow.com/questions/4509039/why-the-strange-indentation-on-switch-statements

But I still find it hurts my eyes. Also Oracle's doc on switch shows indentation: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/switch.html.

The google formatter does the same: 
https://google.github.io/styleguide/javaguide.html#s4.8.4-switch

IntelliJ IDEA and Netbeans indent cases by default too.

**Comment by spottedmahn** [comment]
>Current formatting of switch cases makes no sense at all

After reviewing [the PR](https://github.com/eclipse/eclipse.jdt.ls/pull/1343) it makes more sense.  It's **not** that someone said "default it this way".  It's that **it was missed**.

Thanks for fixing the default!

**Comment by fbricon** [comment]
someone said "default it this way" -> that someone is Eclipse JDT. Our fix overrides JDT's default
