### ISSUE TITLE
Maven and Java "auto build" and Maven profiles

### ISSUE THREAD

**Issue by pyramid-johng** [redhat-developer/vscode-java#1263]
When you have a POM with multiple profiles, there seems to be no way to tell M2E what profile to build with.  It will only build the profile that has "active by default" attached to it.  if there is no such profile, the build output is incomplete.

Also, when running MVN build in the terminal on a different profile, the "auto build" may kick in and modify the "target" folder simultaneously with the terminal's MVN execution.  This causes many hard-to-diagnose problems, like the "target" folder's contents are incorrect, or the JAR contents is incorrect.  I only figured this out when i set my other profile to build to a completely separate "target-xxx" folder.

I can disable Java "auto build" and use the "standard" output folder, and a terminal-based MVN works correctly.

I tried setting the Maven plugins options (e.g. -Pdev), but apparently that does not get used when M2E runs MVN.

I don't really want all my profiles to output to different locations, and I don't want to selectively disable "auto build", so is there a way to tell M2E what profile to use, preferably on a per-folder or per-workspace basis.

##### Environment
- Operating System: Windows 10
- JDK version: JDK 8
- Visual Studio Code version: 1.41.1
- Java extension version: 0.55.1
- Maven for Java: 0.22.1
- Maven version: 3.6.0

##### Steps To Reproduce
1. Have a POM with multiple profiles, e.g. **dev** and **prod**, e.g. a JAR package.
2. Have Java "auto build" enabled.
3. Have "update configuration" set to automatic.
4. Have the "dev" profile be "active by default"
5. Important: to easily observe the issue, the "prod" and "dev" profiles **must** have some mutually-exclusive content, e.g. the "prod" profile may make minimized JS files that go into the JAR file, and excludes (some of) the files from the "dev" profile, e.g. non-minified JS files.
5. At this point M2E auto-builds the "dev" profile into "target".
6. Go to the terminal window and build the "prod" profile via command line.
7. There will be "interference" with what the "prod" profile does, and the "dev" profile, because "dev" is "active by default" and apparently always gets executed.  The most-common outcome is the "prod" execution gets "cleaned" by M2E while it runs the other profile.
8. Removing "active by default" from "dev" now causes an incomplete build, because any resources etc. that are in the "dev" profile do not execute.  This is likely because M2E doesn't have an explicit profile to run (we just deactivated it).
9. Now if you run the "prod" profile in terminal, everything flows normally.

##### Current Result
1. Have to force one of the profiles to be "active by default" so "normal" IDE functions work, e.g. compiled files end up in the "right location".
2. Have to temporarily disable "auto build" when executing any other profile, then remember to re-enable it afterward :-(

##### Expected Result
1. Be able to tell M2E what profile to use when it rebuilds on an auto-build.
2. Not be forced to have the "makes-IDE-work" profile be active by default.
3. Honor the Maven Plugins "opts" when it runs maven.
4. Don't trigger auto-build when the "target" folder changes.

##### Additional Informations
Is there a way to do this currently?

**Comment by snjeza** [comment]
> Be able to tell M2E what profile to use when it rebuilds on an auto-build.

@pyramid-johng you can try to add the following property:

```
activeProfiles=prod
```
to <your_project>/.settings/org.eclipse.m2e.core.prefs

**Comment by GuillaumeDesforges** [comment]
We are missing a setting in this extension to pass parameters to Maven for the build before the run.

**Comment by herna** [comment]
Any updates on this? It'd be nice a property to specify the active profile.

**Comment by jdneo** [comment]
I found that seems after updating `org.eclipse.m2e.core.prefs`. An `update project action` is also needed to be triggered to make the change active.

**Comment by AndreaCardamone** [comment]
> > Be able to tell M2E what profile to use when it rebuilds on an auto-build.
> 
> @pyramid-johng you can try to add the following property:
> 
> ```
> activeProfiles=prod
> ```
> 
> to <your_project>/.settings/org.eclipse.m2e.core.prefs


Thank you very much. You solved this tedious issue for me!

**Comment by CarlPer** [comment]
I am having the same issue, that the autobuild randomly during a maven build modifies the generated files.
With eclipse I, nor my team, has ever had this issue.

activeProfiles=prod does not work for us.

**Comment by escape-llc** [comment]
just to follow up, we ended up going with separate folders for each profile's build output, it was just easier that way.

**Comment by deekshithanand** [comment]
This is a nice feature to have , vs code currently doesnt let to select a profile by default. I am looking for something like this https://www.jetbrains.com/help/idea/work-with-maven-profiles.html#activate_maven_profiles. I can activate a profile when I run via mvn, but am not sure how to do this via autobuild feature used by vscode. Is there any update on this? Its really painful when there are multiple profiles and you need to switch between them or different build configs.

**Comment by snjeza** [comment]
@deekshithanand you have to edit _<your_project>/.settings/org.eclipse.m2e.core.prefs_

**Comment by rantoniuk** [comment]
Why does VSCode ignore the built-in [`maven.executable.options": "-Pprofile"` setting](https://stackoverflow.com/questions/54550365/how-to-set-the-maven-profiles-in-visual-studio-code) ?

**Comment by snjeza** [comment]
> Why does this extension ignore the built-in [maven.executable.options": "-Pprofile" setting](https://stackoverflow.com/questions/54550365/how-to-set-the-maven-profiles-in-visual-studio-code) ?
Also [this is just for reference](https://code.visualstudio.com/docs/java/java-build).

@rantoniuk You may want to take a look at https://github.com/Microsoft/vscode-maven/issues/117#issuecomment-546752800

**Comment by mujiannan** [comment]
It hasn't been fixed yet.  
**Idea** is better for enterprise project.

**Comment by pbodnar** [comment]
> Also, when running MVN build in the terminal on a different profile, the "auto build" may kick in and modify the "target" folder simultaneously with the terminal's MVN execution. This causes many hard-to-diagnose problems, like the "target" folder's contents are incorrect, or the JAR contents is incorrect. I only figured this out when i set my other profile to build to a completely separate "target-xxx" folder.
> 
> I can disable Java "auto build" and use the "standard" output folder, and a terminal-based MVN works correctly.

Note that this part of the issue, which is not purely about _Maven profiles_, is reported & discussed in detail here: #1381.

**Comment by jdneo** [comment]
With the latest `Language Support for Java(TM) by Red Hat` (1.31.0) and latest `Extension Pack for Java` (0.27.0). You can now change the Maven active profile with a GUI with following steps:

1. Click the java status bar
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/82fa54f1-36a2-4982-9c3e-c7b581bb80a0)
2. Select `Open Project Settings`
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/3f8491a1-ceda-4ccb-bffd-4cb1fb64dbc0)
3. Go to the `Maven` tab, and type the profile names (comma separated) which you want to enable. For example: `profile1,profile2`
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/c69aedd0-b8db-440c-845f-49c199a7d709)

**Comment by mucsi96** [comment]
Is it possible to presist this in workspace settings? Or where is this persisted?

**Comment by jdneo** [comment]
It's persisted in the project's metadata files, which are per project. By default those files are hidden.

**Comment by mucsi96** [comment]
Thx. I think I found a better way.

```xml
<profiles>
		<profile>
			<id>local</id>
			<activation>
				<property>
					<name>m2e.version</name>
				</property>
			</activation>
			<dependencies>
				<dependency>
					<groupId>com.h2database</groupId>
					<artifactId>h2</artifactId>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
						<configuration>
							<profiles>
								<profile>local</profile>
							</profiles>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
```

This way I can share the config with my team without any manual steps.
