### ISSUE TITLE
No error for missing import

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-java#1266]
As a follow-up to #1265: sometimes there's no error reported for a missing import

##### Environment
- Operating System: Windows 10
- JDK version: JDK 13
- Visual Studio Code version: VS Code 1.42.0
- Java extension version: 0.55.1

##### Steps To Reproduce
Copy-paste the code below in a Java file. Note that there's no error reported for the missing import of `java.util.List`

````java
import java.util.Map;

class Test {

    static class Employee {

        final String name;

        Employee(String name) {
            this.name = name;
        }

        String name() {
            return name;
        }

    }

    public static void main(String... args) {
        var totals = Map.of(new Employee("John"), 0);
        Employee e = new Employee("Jane");
        //totals.put(e., 0);
        List.of("foo").forEach(item -> {
            totals.put(null, 0);
        });
    }

}
````

##### Current Result
![image](https://user-images.githubusercontent.com/15714253/74273791-48d62d00-4d11-11ea-8fa7-09385d81c025.png)

##### Expected Result
An error is reported on the usage of `List.of`

**Comment by snjeza** [comment]
I can't reproduce the issue.

![1266](https://user-images.githubusercontent.com/388609/74276013-378f1f80-4d15-11ea-8ca1-a43a12761131.gif)

Could you attach a project example?

**Comment by anthonyvdotbe** [comment]
Most likely it's because I was using a stand-alone file, and so had an "[incomplete classpath](https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning)", isn't it? If so, you can close this issue.

**Comment by testforstephen** [comment]
@anthonyvdotbe When you open an external Java (aka stand-alone) file in VS Code, we only show syntax errors. The quickfix for missing import won't be enabled. If you want to import all missing types quickly, you can use the global **Organize imports** command (**Shift + Alt + O**) for that.

**Comment by anthonyvdotbe** [comment]
@testforstephen Thanks for the tip. While I know about the command, because there are no visual clues that doing **Organize imports** might help, I simply don't think of doing it. I filed #1270 as a follow-up issue to improve support for standalone files.
