### ISSUE TITLE
Unverified Breakpoint

### ISSUE THREAD

**Issue by atg22896** [redhat-developer/vscode-java#1268]
Should I be able to place a breakpoint on any line of code?

<img width="1680" alt="Screen Shot 2020-02-12 at 12 06 17 AM" src="https://user-images.githubusercontent.com/33287665/74304668-b42cf880-4d2b-11ea-984a-1d6402928884.png">

As the image shows, the breakpoints on lines 46 and 47 are grey and unverified, and do not stop the code, while the lines which are red are working as expected.

**Comment by testforstephen** [comment]
`Unverified` means not supported. Currently only support breaking on method implementation, not support method declaration and annotation.

The progress about function breakpoint is tracked with issue https://github.com/microsoft/vscode-java-debug/issues/258
