### ISSUE TITLE
Support lazy loading invisible project

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#1274]
Use Case:
1.	Open folder A in VS Code.
2.	Open an external java file B.java.                 ---> the extension will be activated. but because no trigger files from folder A are opened, no invisible project is created.
3.	Open a file C.java under the directory A.     -->  C.java will be linked to the default project. And the user get the warning "classpath is incomplete".

Currently the extension only initializes the invisible project during initialization stage, it cannot handle the case above. The solution is to support lazy creation, and create one anytime if the java folder matches the invisible project rule.

**Comment by fbricon** [comment]
+1000. I've been wanting to do that for a long time
