### ISSUE TITLE
Intellisense / autocomplete list incomplete

### ISSUE THREAD

**Issue by spottedmahn** [redhat-developer/vscode-java#1276]
The autocomplete listing on the Elasticsearch `RestHighLevelClient` is incomplete.

##### Environment
- Operating System: Win 10 v1909
- JDK version: openjdk version "11.0.5" 2019-10-15
- Visual Studio Code version: 1.42.1 (user setup)
- Java extension version: version: 0.55.1

##### Steps To Reproduce
1. Start a project w/ the [Elasticsearch RestHighLevelClient](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-getting-started-initialization.html) 
1. Initialize a `RestHighLevelClient`
1. Perform intellisense on the client

##### Current Result
![image](https://user-images.githubusercontent.com/14079228/74659089-a9c29280-5161-11ea-9a89-bdc79a6cf09b.png)

##### Expected Result
A full listing of all accessible methods (other things, fields, etc.).

For example, [`search()`](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-search.html) is missing.

##### Additional Informations
Pretty sure I've seen this on other objects and this is **not** specific to the `RestHighLevelClient`.

**Comment by fbricon** [comment]
The completion list is limited to 50 items by default, for performance purposes. You can either continue typing `client.s`, to fetch the next matching results or increase the `java.completion.maxResults` preference value. See https://github.com/eclipse/eclipse.jdt.ls/pull/1298 for more details.

**Comment by spottedmahn** [comment]
>The completion list is limited to 50 items by default, for performance purposes

Fair enough.

What about an **indicator** that the list is **incomplete**?  As a newbie to Java w/ VS Code it is not obvious, at least not to me!

And on that "incomplete list indictator", what about a "load all option"?

---

And thanks for the super quick reply! ⚡🤝

**Comment by fbricon** [comment]
Not sure that is possible with vscode. We'll look into it.

**Comment by akaroml** [comment]
If `isIncomplete` is set to `true`, then vscode will request for another completion list whenever users type something new. When set to `false`, then vscode will consider the list complete and will be able to do filtering as users type more without requesting the LS for more completion suggestions.

In short,
`isIncomplete == true` => LS does the filtering (by handling more requests)
`isIncomplete == false` => vscode does the filtering

**Comment by jdneo** [comment]
The `java.completion.maxResults` is now default to `0`, which means the limitation is disabled.

I guess this issue should be addressed already and can be closed. @testforstephen

**Comment by fbricon** [comment]
All results now returned by default. Closing.
