### ISSUE TITLE
Custom color for arguments used in method body

### ISSUE THREAD

**Issue by 0y0y** [redhat-developer/vscode-java#1277]
It's not possible to identify arguments used in the method body. So we can't use the same color for better code readability.

##### Environment
- Operating System: windows10
- JDK version: Oracle 10.0.2
- Visual Studio Code version: 1.42.1
- Java extension version: 0.55.1

##### Current Result
![image](https://user-images.githubusercontent.com/18117142/74665813-ad293e80-51a0-11ea-89f9-5a3f27339cec.png)

![image](https://user-images.githubusercontent.com/18117142/74665847-b9ad9700-51a0-11ea-9544-4262c5e8d1e7.png)

##### Expected Result
Textmate scope for arguments in method body

**Comment by fbricon** [comment]
The textmate grammar is defined in [vscode itself](https://github.com/microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json), but the source of the grammar is actually atom, so the problem should be reported there: https://github.com/atom/language-java/issues

**Comment by 0y0y** [comment]
Ok thanks.

https://github.com/atom/language-java/issues/222

**Comment by akaroml** [comment]
@Vigilans did you happen to fix this at Atom side? If so, please help integrate that to vscode repo.

**Comment by fbricon** [comment]
This is partially fixed with the new semantic highlighting support in vscode-java 0.61.0. Requires `"java.semanticHighlighting.enabled": true` in settings.json. Without semantic highlighting, the Textmate grammar is still broken.
