### ISSUE TITLE
Trigger to re-generate .classpath file?

### ISSUE THREAD

**Issue by spottedmahn** [redhat-developer/vscode-java#1279]
I was having trouble building my project on different branches due to:

>Project 'my-project' is missing required source folder: 'src/main/resources'

I tracked my problem down to `.classpath` file differences [using this clue](https://github.com/redhat-developer/vscode-java/issues/504#issuecomment-380925326).

##### Environment
- Operating System: Win10 v1909 WSL 1 Ubuntu 18.04
- JDK version: openjdk version "11.0.5" 2019-10-15
- Visual Studio Code version: 1.42.1 (user setup)
- Java extension version: 0.55.1

##### Steps To Reproduce
I don't know exactly but I can tell you how I got the differences, kinda:

1. Started a new java project under `~/repos/blah`
1. Committed to branch A w/o a resources folder
1. Made some more changes that included a resources folder
1. Committed to branch B
1. Cloned it again on a different path `~/repos/blah-2`
1. Checkout branch B on `~/repos/blah-2`
1. Checkout branch A on `~/repos/blah-2`, got the above error

##### Current Result
`.classpath` gets generated once it appears and doesn't get updated

##### Expected Result
The `.classpath` file should get regenerated when switching branches (**maybe**, I don't know the exact time to trigger)

##### Additional Informations

>[Error - 1:35:17 PM] Feb 17, 2020, 1:35:17 PM Error occured while building workspace. Details: 
 message: The project cannot be built until build path errors are resolved; code: 0; resource: /mnt/c/Users/mdepouw/source/repos/blah;
 message: Project 'blah' is missing required source folder: 'src/main/resources'; code: 964; resource: /mnt/c/Users/mdepouw/source/repos/blah;

**Comment by spottedmahn** [comment]
Maybe that's the `Clean the Java language server workspace` command?

![image](https://user-images.githubusercontent.com/14079228/74681373-3cc6f100-5191-11ea-8d1f-fea6e491083b.png)

![image](https://user-images.githubusercontent.com/14079228/74681392-49e3e000-5191-11ea-9005-57c8b87ab930.png)

**Comment by akaroml** [comment]
This command is always the lifesaver. And this one also helps sometimes `Java: Update project configuration`.
