### ISSUE TITLE
Error Message "Classpath is incomplete. Only syntax errors will be reported" is always shown

### ISSUE THREAD

**Issue by rephchunhoong** [redhat-developer/vscode-java#128]
##### Environment
- Operating System: Windows 10
- JDK version: Oracle 1.8.0 Update 111
- Visual Studio Code version: 1.8.1
- Java extension version: 0.0.8

##### Steps To Reproduce
1. Open any .java file.
2. Click on "Don't show again" when the error message is shown.
3. Close the file and reopen. The message will be shown again.

##### Current Result
Click on "Don't show again" when the error message is shown. The message will be re-shown. 

##### Expected Result
The message will not be shown in future when "Don't show again" is clicked.

**Comment by fbricon** [comment]
Can you make sure `java.errors.incompleteClasspath.severity` is set to `ignore` in VS Code's user preferences?
