### ISSUE TITLE
Refresh the invisible project's classpath on-demand

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#1282]
When the invisible project is initialized, the importer only adds the source directories of those opened files to the project classpath, which causes some potential source paths to be missed. But scanning the directory statically to get all would be time-consuming for some deep directories. A natural approach is to update the source path on-demand. Every time you open a new Java file, automatically add those that are not on classpath to the classpath.

**Comment by jdneo** [comment]
How about provide a page to specify some project settings like:
- Specify the source directories
- Specify the output path
- ...
