### ISSUE TITLE
Undesirable autoformatting of code

### ISSUE THREAD

**Issue by spottedmahn** [redhat-developer/vscode-java#1284]
The following code gets "mangled" when I autoformat the code.

##### Environment
- Operating System: Win10 v1909 WSL 1 Ubuntu 18.04
- JDK version: openjdk version "11.0.5" 2019-10-15
- Visual Studio Code version: 1.42.1 (user setup)
- Java extension version: 0.55.1

##### Steps To Reproduce
1. Add the following code to a class
```java
// before auto format
// https://stackoverflow.com/a/30026710/185123
static<T> CompletableFuture<List<T>> sequence1(List<CompletableFuture<T>> com) {
    return CompletableFuture.allOf(com.toArray(new CompletableFuture<?>[0]))
            .thenApply(v -> com.stream()
                .map(CompletableFuture::join)
                .collect(Collectors.toList())
            );
}
```
2. ALT + SHIFT + F

##### Current Result
![image](https://user-images.githubusercontent.com/14079228/74776493-a6183400-5265-11ea-9e74-38332b38ba9c.png)

##### Expected Result
![image](https://user-images.githubusercontent.com/14079228/74776548-be884e80-5265-11ea-9220-9a0222e0badb.png)
##### Additional Informations
[Sample file](https://github.com/spottedmahn/experiments-2020/blob/master/java-tests-issue/src/main/java/miked/autoformat/AutoFormatIssue.java)

**Comment by snjeza** [comment]
@spottedmahn you may want to take a look at https://github.com/redhat-developer/vscode-java/issues/1126#issuecomment-548085982

**Comment by spottedmahn** [comment]
really appreciate the quick response ⚡!

---

![image](https://user-images.githubusercontent.com/14079228/74778519-bd592080-5269-11ea-8f5c-40b2f90711f9.png)

after:

![image](https://user-images.githubusercontent.com/14079228/74778484-b0d4c800-5269-11ea-8c4a-757ac25f0009.png)

🤔, I think I like it.  Lost the "red" formatting though 🤔, i.e. `CompletableFuture`, `com`, etc.

**Comment by spottedmahn** [comment]
Wonder if we can get it to not put the **first** method on a new line 🤔.  Isn't that the generally accepted format?

i.e.

![image](https://user-images.githubusercontent.com/14079228/74778854-6e5fbb00-526a-11ea-9272-5e78f5378b66.png)

**Comment by snjeza** [comment]
You can configure your own formatter. See https://stackoverflow.com/questions/4172937/how-to-indent-the-fluent-interface-pattern-correctly-with-eclipse?rq=1

**Comment by spottedmahn** [comment]
![image](https://user-images.githubusercontent.com/14079228/75051676-51123300-549c-11ea-8e00-54d80459c348.png)

is: `<setting id="org.eclipse.jdt.core.formatter.alignment_for_selector_in_method_invocation" value="81"/>`

Which produces:

![image](https://user-images.githubusercontent.com/14079228/75051596-2c1dc000-549c-11ea-92b8-06be245c6f61.png)

not 100% but pretty close

thanks @snjeza!
