### ISSUE TITLE
Gradle project fails to build while fetching non-existing snapshot distro

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-java#1285]
Source: microsoft/vscode-docs#3409 from @n8s16

> I can't seem to find a solution to this problem so I think this might be a bug. Before, I can easily run my _spring boot gradle project_ in **VSCode** (with Java and Spring Boot extensions) _migrated_ from **STS3**. I tried to setup VSCode and project (the same way how I setup before) to a new machine. And I encountered this issue:

```
Could not fetch model of type 'BuildEnvironment' using Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-6.0-20191016123526+0000-bin.zip'.
The specified Gradle distribution 'https://services.gradle.org/distributions-snapshots/gradle-6.0-20191016123526+0000-bin.zip' does not exist.
https://downloads.gradle-dn.com/distributions-snapshots/gradle-6.0-20191016123526+0000-bin.zip
```

>To my understanding, VSCode cannot fetch the specific gradle distribution. But when I tried to build and run the code to STS3 again, it's seems working properly. Thanks in advance.

Not familiar with Gradle part. @fbricon @snjeza do you have any idea what this is about?

**Comment by snjeza** [comment]
@akaroml See https://github.com/eclipse/eclipse.jdt.ls/pull/1355 and https://github.com/eclipse/che/issues/16051

**Comment by akaroml** [comment]
> @akaroml See [eclipse/eclipse.jdt.ls#1355](https://github.com/eclipse/eclipse.jdt.ls/pull/1355) and [eclipse/che#16051](https://github.com/eclipse/che/issues/16051)

Thank you @snjeza. Good to know that the issue is fixed in the coming release.

**Comment by fbricon** [comment]
I'll release the fix today

**Comment by fbricon** [comment]
Until then you can manually [install](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) the latest CI build (0.57.0) from [http://download.jboss.org/jbosstools/jdt.ls/staging/](http://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D).

Better manually delete .project, .settings/, ~/.toolings/ and clean the workspace directory

**Comment by vaclavbenes** [comment]
Hi , I use latest version of gradle tasks and Language support for Java, but it seems still usue with 
```log
[debug] SERVER MESSAGE: {"error":{"message":"Could not fetch model of type 'GradleProject' using Gradle distribution 'https://artifactory.int.avast.com/artifactory/Generic/org/gradle/gradle-5.6.2-all.zip'."}}
[error] Could not fetch model of type 'GradleProject' using Gradle distribution 'https://artifactory.int.avast.com/artifactory/Generic/org/gradle/gradle-5.6.2-all.zip'.
[debug] SERVER MESSAGE: {"getTasks":{"message":"Completed ACTION_GET_TASKS","tasksList":[]}}

```
