### ISSUE TITLE
Extension breaks loading the default project

### ISSUE THREAD

**Issue by aminpaks** [redhat-developer/vscode-java#1289]
I followed the instructions on VSCode website but there are some errors that breaks the extension completely.

##### Environment
- Operating System: macOS
- JDK version: 13.0.2
- Visual Studio Code version: 1.42.1
- Java extension version: 0.57.0

##### Steps To Reproduce
1. clone this repo
2. open it in vscode
3. observe the output panel for the extension

[sample project](https://github.com/spring-guides/gs-spring-boot)

[Full logs](https://pastebin.com/8V6rTMmx)
[Last lines of logs](https://pastebin.com/M62ma22d)

[VSCode instruction](https://code.visualstudio.com/docs/java/java-webapp)

##### Current Result
After loading the project extension stops working

##### Expected Result
Should work

**Comment by snjeza** [comment]
I can't reproduce the issue.
@aminpaks try to call _Java: Clean the Java language server workspace_
You should also set the following property:
```
 "java.import.exclusions": [
        "**/node_modules/**",
        "**/.metadata/**",
        "**/archetype-resources/**",
        "**/META-INF/maven/**",
        "**/initial"
    ],
```
or
```
 "java.import.exclusions": [
        "**/node_modules/**",
        "**/.metadata/**",
        "**/archetype-resources/**",
        "**/META-INF/maven/**",
        "**/complete"
    ],
```

**Comment by aminpaks** [comment]
@snjeza where should I add these settings?
Also it seems you want to exclude one of the projects, would you explain why is that necessary?

**Comment by aminpaks** [comment]
Updated the stack error and logs.

**Comment by aminpaks** [comment]
Could be related to the JDK version?

**Comment by snjeza** [comment]
> @snjeza where should I add these settings?

File>Preferences>Settings

> Also it seems you want to exclude one of the projects, would you explain why is that necessary?

https://github.com/spring-guides/gs-spring-boot includes two projects with the same name.

> Could be related to the JDK version?

Your project requires JDK 1.8

**Comment by aminpaks** [comment]
Added the settings, the issue still persists.

Do you think I should install v1.8 and try that?
I tried with other projects but they work with the same settings and JDK version!

**Comment by aminpaks** [comment]
Just tried with [this project](https://github.com/springframeworkguru/springbootwebapp) and worked too 😞

**Comment by snjeza** [comment]
> Do you think I should install v1.8 and try that?

I have tried JDK 1.8 and JDK 13. It works fine. You can try to clone the project to a new directory.

**Comment by aminpaks** [comment]
Tired a fresh clone in a new directory, didn't help. I have no clue why is this happening. I always get the same error.

**Comment by aminpaks** [comment]
The problem was Gradle, I had an old version and it's not compatible with Java 13.
Installed the latest (at the time 6.2) and cleaned the project and it's working now 😄
