### ISSUE TITLE
VS Code Java Cannot Run from Read-Only Location

### ISSUE THREAD

**Issue by tsmaeder** [redhat-developer/vscode-java#1301]
When running VS Code Java, some files are created in `server\config_win\org.eclipse.core.runtime` (this is on Windows, but likely not Windows-specific). 
The problem with this is that you cannot run VS Code Java from a location where you don't have write access. This prevents VS Code Java from running as a built-int extension in Theia, for example.
To me it seems that the files in question are created by the eclipse configuration management. IMO, those files should be created in the directory obtained from `ExtensionContext#globalStoragePath`. Eclipse has a startup parameter to set the osgi configuration area (see [here](https://help.eclipse.org/2019-12/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html&cp%3D2_1_5_0&anchor=osgiconfigurationarea) and [here](https://help.eclipse.org/2019-12/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html))

**Comment by snjeza** [comment]
See https://github.com/redhat-developer/vscode-java/pull/1307#issuecomment-594066710

**Comment by fbricon** [comment]
#1314 fixed the dev mode issue
