### ISSUE TITLE
Ignoring settings for Java version

### ISSUE THREAD

**Issue by chriscamplejohn** [redhat-developer/vscode-java#1305]
I have JAVA_HOME set to /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
I also have "java.home": "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home" in my user configuration file.

##### Environment
- Operating System: macOS Catalina 10.15.1
- JDK version: Multiple (AdoptOpenJDK 11, AdoptOpenJDK 8, Java SE 8)
- Visual Studio Code version: 1.42.1
- Java extension version: 0.57.0

##### Steps To Reproduce
1. Set the settings detailed above with the above JDKs installed
2. Debug or Run a Java application

##### Current Result
Runs with Open JDK 11.
<img width="1145" alt="Java Version Issue" src="https://user-images.githubusercontent.com/2816218/75444456-5f0ffa00-595b-11ea-9e07-f83105cca153.png">

##### Expected Result
Runs with Open JDK 8.

**Comment by fbricon** [comment]
Sorry, this is out of scope of vscode-java. Can you please open a bug in https://github.com/microsoft/vscode-java-debug/issues?
