### ISSUE TITLE
Warnings and Errors from compiler plugins?

### ISSUE THREAD

**Issue by gdoenlen** [redhat-developer/vscode-java#1309]
Is there anything specific that needs to be done to get errors from compiler plugins (i.e. errorprone) in the gui?  It looks like @fbricon did some work around non-standard compilerIds in https://github.com/eclipse/eclipse.jdt.ls/issues/196 but, with java 11 error prone docs point you to use the compiler plugin instead of the compilerId.

**Comment by fbricon** [comment]
Errorprone errors are never reported because eclipse jdt is the compiler used by eclipse.jdt.ls, errorprone is always ignored. Nothing we can do about it unless there's a way for jdt to behave exactly the same way, after doing some configuration, which I doubt is possible

**Comment by gdoenlen** [comment]
Ok makes sense. Is there anyway to pass arguments like -Werror to the
eclipse compiler?
