### ISSUE TITLE
Add GRADLE_USER_HOME preference

### ISSUE THREAD

**Issue by hanct** [redhat-developer/vscode-java#1310]
How to set GRADLE_USER_HOME in VSCode, so that the libs' path displayed under the Project and External Dependencies node of the JAVA DEPENDENCIES section is showing the path value set in the GRADE_USER_HOME.

I learnt about java.import.gradle.arguments  and java.import.gradle.jvmArguments settings which i can set in the workspace settings. But how to use them to achieve what i want?

##### Environment
- Operating System: Windows 10
- JDK version: Java 1.8
- Visual Studio Code version:1.42.1
- Java extension version:0.8.1

**Comment by hanct** [comment]
I am still stuck at this issue. I tries using java.import.gradle.arguments, but its not working. Is this a bug?

**Comment by snjeza** [comment]
@hanct you can try the following settings:

```
set GRADLE_USER_HOME=<your_gradle_user_home>
code .
```
You also can try to set the GRADLE_USER_HOME environment variable.

**Comment by hanct** [comment]
> @hanct you can try the following settings:
> 
> ```
> set GRADLE_USER_HOME=<your_gradle_user_home>
> code .
> ```
> 
> You also can try to set the GRADLE_USER_HOME environment variable.

Hi, 
Thanks for the reply. But I assume u mean set the environment variable in my OS, which I try avoid doing that. The purpose of query is to avoid configuring environment variables in OS as much as possible, and to do that in vscode where-ever possible. 

Also, is there any sample on how to use the java.import.gradle.arguments and java.import.gradle.jvmArguments, as i couldn't find an official samples online.  In addition, setting java.import.gradle.home also not work.

**Comment by snjeza** [comment]
> Thanks for the reply. But I assume u mean set the environment variable in my OS, which I try avoid doing that. The purpose of query is to avoid configuring environment variables in OS as much as possible, and to do that in vscode where-ever possible.

I will add a new preference - java.import.gradle.userHome

> Also, is there any sample on how to use the java.import.gradle.arguments and java.import.gradle.jvmArguments, as i couldn't find an official samples online. In addition, setting java.import.gradle.home also not work.

See #1319

**Comment by hanct** [comment]
> > Thanks for the reply. But I assume u mean set the environment variable in my OS, which I try avoid doing that. The purpose of query is to avoid configuring environment variables in OS as much as possible, and to do that in vscode where-ever possible.
> 
> I will add a new preference - java.import.gradle.user.home
> 
> > Also, is there any sample on how to use the java.import.gradle.arguments and java.import.gradle.jvmArguments, as i couldn't find an official samples online. In addition, setting java.import.gradle.home also not work.
> 
> See #1319

Thanks snjeza! by the way, for your info, another user also face similar issue at https://github.com/redhat-developer/vscode-java/issues/1169

**Comment by snjeza** [comment]
You are right.

**Comment by hanct** [comment]
Hi, just curious, when will 0.59 (which include this change) can be released for updates as visual studio code etrensions?

**Comment by fbricon** [comment]
next release planned for the end of the month. Until then you can use the CI builds

**Comment by hanct** [comment]
> next release planned for the end of the month. Until then you can use the CI builds

Thanks. Would prefer to wait for visual studio code extensions, which hopefully can be released anytime this week or early next week.

**Comment by alejophotoart** [comment]
> @hanct puedes probar las siguientes configuraciones:
> 
> ```
> set GRADLE_USER_HOME=<your_gradle_user_home>
> code .
> ```
> 
> También puede intentar configurar la variable de entorno GRADLE_USER_HOME.

Hi @snjeza, i have same problem that @hanct. if implement this solution in my project, it will work?

**Comment by hanct** [comment]
> > @hanct puedes probar las siguientes configuraciones:
> > 
> > ```
> > set GRADLE_USER_HOME=<your_gradle_user_home>
> > code .
> > ```
> > 
> > También puede intentar configurar la variable de entorno GRADLE_USER_HOME.
> 
> Hi @snjeza, i have same problem that @hanct. if implement this solution in my project, it will work?

Hi,
U can try to use this setting java.import.gradle.user.home
