### ISSUE TITLE
Warnings are hidden by an error when editing a file

### ISSUE THREAD

**Issue by lmcbout** [redhat-developer/vscode-java#1313]
Warning in problem view is hidden by error on a different line. It looks like the language server does not report all errors/warnings when editing a java file.

##### Environment
- Operating System: Ubuntu 18.04
- JDK version: openjdk version "11.0.6" 2020-01-14
- Visual Studio Code version: 1.42.1
- Java extension version: 0.57.0
Same error was reported on Theia with a different java (redhat-version 0.54.2)
https://github.com/eclipse-theia/theia/issues/6147

##### Steps To Reproduce
0. Open the problem view
1. Create a java file
2. Insert a warning in the file
3. Now insert an error on a different line
--> Notice in the problem view, initially you see the warning, then when inserting an error on the next line, the warning is not shown anymore until you fix the error.
![JavaWarningErrorNotShowing](https://user-images.githubusercontent.com/419051/75694893-3ea3b080-5c77-11ea-8576-ed29a9865d3d.gif)

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by snjeza** [comment]
The issue can be reproduced in Eclipse.

**Comment by snjeza** [comment]
Related issue #621

**Comment by fbricon** [comment]
Closing, according to https://bugs.eclipse.org/bugs/show_bug.cgi?id=533592#c2:

> This is by design: as long as resolve errors are present, unused imports warning would in general not be reliable. So it's better to focus on definite and more severe errors first.
