### ISSUE TITLE
Plugin automatically uses Gradle 1.12 if no wrapper is provided

### ISSUE THREAD

**Issue by jakegt1** [redhat-developer/vscode-java#1321]
This is a really weird bug where gradle will always use 1.12 if available, even if the `java.import.gradle.version` is set. My default gradle (as in gradle on my $PATH) is 5.3.1, but whatever i do i get the the `Support for builds using Gradle versions older than 2.6 was removed in tooling API version 5.0. You are currently using Gradle version 1.12. You should upgrade your Gradle build to use Gradle 2.6 or later.` error.

##### Environment
- Operating System: Mac OSX Catalina
- JDK version: 1.8.0
- Visual Studio Code version: 1.42.1
- Java extension version: 58.0

##### Steps To Reproduce
1. Use a project without gradle wrapper.

##### Current Result
Project attempts to use gradle 1.12 even if gradle >2 is the default for your $PATH.

##### Expected Result
Project uses whatever is defined in `java.import.gradle.version` or the default in your $PATH.

##### Additional Informations
I was also using buildSrc in this project where i opened up the buildSrc as its own project.

**Comment by snjeza** [comment]
Could you send your settings.json and server log?
You can try to set the following preference:
```
"java.import.gradle.home": "your_gradle_home",
```

**Comment by jakegt1** [comment]
`java.import.gradle.home` fixed it (just set it to my 5.3.1 install.)

do wonder why it was defaulting to gradle1 otherwise tho... How do i get the logs again?

**Comment by snjeza** [comment]
>  How do i get the logs again?

https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging

**Comment by jakegt1** [comment]
!ENTRY org.eclipse.jdt.ls.core 1 0 2020-03-10 15:28:11.141
!MESSAGE Invalid gradle version5.4.1

seems like the relevant line

**Comment by jakegt1** [comment]
Problem with the downstream it looks like. Unsure what changed, might be proxy issues (i am using a proxy).

**Comment by snjeza** [comment]
>  might be proxy issues (i am using a proxy).

See https://github.com/redhat-developer/vscode-java/wiki/Using-a-Proxy

>  Invalid gradle version5.4.1

You can try the following:

```
"java.import.gradle.wrapper.enabled": false,
"java.import.gradle.version": "5.4.1",
```

**Comment by jakegt1** [comment]
Have tried that, also doesn't work.

**Comment by jakegt1** [comment]
Will note this is a regression for me - i have added those values in 'Using a Proxy'.

**Comment by jakegt1** [comment]
Weirdly, this is doing the same thing also on my linux machine, but defaults to gradle 6 (which i have no where on the machine.)

However, it seems that gradle wrapper actually works with a proxy now anyway, so can just use that to avoid any issues.
