### ISSUE TITLE
java.lang.UnsatisfiedLinkError with native libraries

### ISSUE THREAD

**Issue by VilimKrajinovic** [redhat-developer/vscode-java#1324]
I'm trying to move to VSCode from IntelliJ, and im running into some problems with starting my application (it works normally in IntelliJ and in Eclipse). 

When i start my application in VSCode i get greeted with this exception:

```
PS C:\Users\Vilim\Desktop\zavrsni>  cd 'c:\Users\Vilim\Desktop\zavrsni'; & 'C:\Users\Vilim\.vscode\extensions\vscjava.vscode-java-debug-0.25.1\scripts\launcher.bat' 'C:\Program Files\Java\jdk1.8.0_191\bin\java.exe' '-Dfile.encoding=UTF-8' '-cp' 'C:\Users\Vilim\AppData\Local\Temp\cp_5z818spwjwl03kk6ft20i3cif.jar' 'engineTester.Main' '-Djava.library.path=lib/natives'
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.lwjgl.Sys$1.run(Sys.java:73)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:95)
        at org.lwjgl.Sys.<clinit>(Sys.java:112)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
        at renderEngine.DisplayManager.createDisplay(DisplayManager.java:18)
        at engineTester.Main.main(Main.java:21)
```

Here its visible that i tried including the native libraries with the `-Djava.library.path=lib/natives` argument, but that doesnt work in vscode (works in intellij). In Eclipse the equivalent is going right click on project > Build Path > Configure Build Path > JRE System Library > Native library location > click edit on the right, and point to the lib/natives folder. And the project runs as expected in both IntelliJ and Eclipse.

Am i missing something? I tried adding the .dll files in .classpath file like this

<classpathentry kind="lib" path="lib/natives/lwjgl.dll"/>

but that didnt work either

##### Environment
- Operating System:  Windows 10
- JDK version: java version "1.8.0_191"
- Visual Studio Code version: 1.43.0
- Java extension version: 0.8.1

##### Steps To Reproduce
1. [step 1]
Clone https://github.com/VilimKrajinovic/thesis-game-engine
2. [step 2]
Create a .vscode folder and add settings.json and launch.json files (if im understanding it correclty they are needed for vscode)
3.
settings.json
```
{
  "files.exclude": {
    "**/.classpath": true,
    "**/.project": true,
    "**/.settings": true,
    "**/.factorypath": true
  },
  "java.project.referencedLibraries": ["lib/**/*.jar"],
  "java.dependency.syncWithFolderExplorer": true
}
```

launch.json
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "Debug (Launch) - Current File",
      "request": "launch",
      "mainClass": "${file}"
    },
    {
      "type": "java",
      "name": "Debug (Launch)-Main<zavrsni>",
      "request": "launch",
      "mainClass": "engineTester.Main",
      "projectName": "zavrsni",
      "args": ["-Djava.library.path=lib/natives"]
    }
  ]
}
```
4.Try to launch the src\main\java\engineTester\Main.java main method
5. get the mentioned exception

[attach a sample project reproducing the error]
https://github.com/VilimKrajinovic/thesis-game-engine

[attach logs]
```
PS C:\Users\Vilim\Desktop\zavrsni>  cd 'c:\Users\Vilim\Desktop\zavrsni'; & 'C:\Users\Vilim\.vscode\extensions\vscjava.vscode-java-debug-0.25.1\scripts\launcher.bat' 'C:\Program Files\Java\jdk1.8.0_191\bin\java.exe' '-Dfile.encoding=UTF-8' '-cp' 'C:\Users\Vilim\AppData\Local\Temp\cp_5z818spwjwl03kk6ft20i3cif.jar' 'engineTester.Main' '-Djava.library.path=lib/natives'
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.lwjgl.Sys$1.run(Sys.java:73)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
        at org.lwjgl.Sys.loadLibrary(Sys.java:95)
        at org.lwjgl.Sys.<clinit>(Sys.java:112)
        at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
        at renderEngine.DisplayManager.createDisplay(DisplayManager.java:18)
        at engineTester.Main.main(Main.java:21)
```

##### Current Result
Getting the exception that it cant find the lwjgl native library
##### Expected Result
Program should run like in both eclipse and intellij.

**Comment by snjeza** [comment]
@VilimKrajinovic could you try the following:

```
"vmArgs": "-Djava.library.path=lib/natives"
```
instead of

```
"args": ["-Djava.library.path=lib/natives"]
```

**Comment by VilimKrajinovic** [comment]
> @VilimKrajinovic could you try the following:
> 
> ```
> "vmArgs": "-Djava.library.path=lib/natives"
> ```
> 
> instead of
> 
> ```
> "args": ["-Djava.library.path=lib/natives"]
> ```

Yes! That fixes it! Thank you so much!

I googled for hours trying to fix this issue (although didnt google well enough i guess :D )! I didn't assume args was faulty because i saw it in the output with the rest of the arguments, so i assumed it was passed in correctly!

**Comment by snjeza** [comment]
Drago mi je :)  Pozdrav iz Beograda.

**Comment by pocketdr** [comment]
Maybe stupid, I would like to add something about this.
`"vmArgs": "-Djava.library.path=lib/natives"`
It's not works for me.
Instead of it, I use 
`"vmArgs": "-Djava.library.path=lib/natives/"`
