### ISSUE TITLE
Multiple Java server crash on codercom/code-server

### ISSUE THREAD

**Issue by karngyan** [redhat-developer/vscode-java#1326]
Currently, I have [v0.47.0](https://github.com/redhat-developer/vscode-java/releases/tag/v0.47.0) running on [code-server](https://github.com/cdr/code-server). I tried to upgrade it to  [v0.55.1](https://github.com/redhat-developer/vscode-java/releases/tag/v0.55.1)

It crashes multiple times with the following logs:
```
...
{
  message: 'The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.',
  level: 'error',
  timestamp: '2020-03-12 08:19:21.172'
}
{
  message: '[Error - 8:19:21 AM] Connection to server got closed. Server will not be restarted.',
  level: 'info',
  timestamp: '2020-03-12 08:19:21.174'
}
```
[Complete log file](https://gist.github.com/karngyan/76b6ceca292bb18da029a90732ce360f)

Any update on the support of the above version is highly appreciated.

##### Environment
- Operating System: Ubuntu 18.04
- JDK version: 8
- Code Server Version: 2.1698-vsc1.41.1

**Comment by fbricon** [comment]
There in your logs: 'java.io.FileNotFoundException: /home/crio-user/.vscode-builtin-extensions/redhat.java-0.55.1/server/config_linux/1584001160258.log (Permission denied)

**Comment by fbricon** [comment]
It's a change introduced by https://github.com/redhat-developer/vscode-java/issues/1301

**Comment by fbricon** [comment]
Can you make ExtensionContext#globalStoragePath writable?
