### ISSUE TITLE
Is the latest version supporting JDK 14?

### ISSUE THREAD

**Issue by 773780238** [redhat-developer/vscode-java#1342]
[provide a description of the issue]
I downloaded JDK 14 today, but the VSCODE cannot compile and run my code correctly. However, the code can be compiled and run perfectly using  Powershell command line. It says that Language Support for Java by Red Hat in VSCODE is not supporting JAVA 14 now, then when can we expect it supporting.
##### Environment
- Operating System: Windows 10
- JDK version: 14
- Visual Studio Code version: 1.43.2
- Java extension version: 0.58.0

##### Steps To Reproduce
1. [step 1] write a HelloWorld java file
2. [step 2] compile and run

##### Current Result
Error: LinkageError occurred while loading main class CleanTree
        java.lang.UnsupportedClassVersionError: CleanTree (class file version 57.65535) was compiled with preview features that are unsupported. This version of the Java Runtime only recognizes preview features for class file version 58.65535
##### Expected Result
"Hello World"

**Comment by fbricon** [comment]
We should release a Java 14 compatible version next week. In the meantime, you can install the latest CI build from [http://download.jboss.org/jbosstools/jdt.ls/staging/](http://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D). Download the most recent `java-<version>.vsix` file and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

Keep in mind there's a few [limitations](https://github.com/redhat-developer/vscode-java/pull/1300#issuecomment-602590170) for now.
