### ISSUE TITLE
VSCode Condense Folder Causing Issue with Java Path

### ISSUE THREAD

**Issue by vb-software** [redhat-developer/vscode-java#1348]
Issue Type: <b>Bug</b>

The condense folder feature of VSCode causes issues when using the Java context menu to add the folder to java path.  Instead of adding the folder I click on, it takes the entire path to the destination folder that is condensed.  In the meantime I had to turn the condense feature off.

Extension version: 0.58.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.88GB (42.45GB free)|
|Process Argv|--folder-uri file:///c%3A/Development/crsp|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by testforstephen** [comment]
this is a VS Code bug https://github.com/microsoft/vscode/issues/93709

**Comment by testforstephen** [comment]
this issue has been fixed in vscode 1.44.
