### ISSUE TITLE
Support Building/Running/Debuging of Java application via Gradle Tasks

### ISSUE THREAD

**Issue by hannah23280** [redhat-developer/vscode-java#1352]
Hi,

I would like know if it is possible for the vscode-java extension to support run/debug/build/clean java application via gradle tasks. 

Currently, when we run java application in vscode,  it seems that gradle is not involved. This is evidenced from the fact that the compiled java class goes into the bin folder. If it goes via gradle, it would have been in the build folder.

Currently to debug my spring boot application via gradle, I have to do 2 steps

**Step 1**
Run the gradle task called bootRun. Note that the build.gradle is configured with the below
```
bootRun {
jvmArgs=["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=32323"]
}
```
**Step 2**
With the below configured in the launch.json, run the configuration to attach the debugger to the listener port 32323.
```
{
"type": "java",
"name": "Debug (Attach)",
"request": "attach",
"hostName": "localhost",
"port": 32323
}
```

Finally, i can see my vscode break at my custom breakpoint in the code editor.

However, everytime i make a changes to the Java code, i have to stop everything above, and rerun the 2 steps. It is really tedious. 

I have been doing lot of research online, on how to achieve the above in one single step, but with no avail.  So not so sure if vscode-java extension can be enhanced to achieve this?

**Comment by hanct** [comment]
Do note that VSCode has a feature called auto attach. But that is applicable only to node.js. There seems to be no similar kind of "auto-attach" , when running java application via gradle.

**Comment by jdneo** [comment]
I guess this extension may help you: https://github.com/microsoft/vscode-gradle.

Let us know if it's not.
