### ISSUE TITLE
Trouble publishing to Open VSX

### ISSUE THREAD

**Issue by jankeromnes** [redhat-developer/vscode-java#1353]
Hello! 👋 We would love to have the `redhat.java` extension available in https://open-vsx.org

So we've recently [added it](https://github.com/open-vsx/publish-extensions/blob/9eedf9c5563aeddc1c48808595a5dc8491820fe5/extensions.json#L288-L292) to an [auto-publishing script](https://github.com/open-vsx/publish-extensions), but it turns out that our script is not packaging the `redhat.java` extension correctly.

Here is the steps that it currently runs to publish `redhat.java`:

```
git clone https://github.com/redhat-developer/vscode-java
cd vscode-java/
npm install
npx ovsx publish
```

This results in a [broken](https://github.com/open-vsx/publish-extensions/issues/18) extension: https://open-vsx.org/extension/redhat/java which we are trying to remove from https://open-vsx.org and republish correctly.

We found that the extension is missing at least the Java Language Server, and that it would require at least one extra step between `npm install` and `ovsx publish`:

```
./node_modules/.bin/gulp download_server
```

However, I wonder why this isn't part of the [vscode:prepublish](https://github.com/redhat-developer/vscode-java/blob/912a574b66e23cf40c71dd2b19aa91605286aaff/package.json#L653) steps? (The [`ovsx` CLI](https://github.com/eclipse/openvsx/tree/master/cli) will automatically run that before publishing.)

Also, if you're interested in taking over the publishing to https://open-vsx.org from this repository (which may be better long-term), you can simply call [`npx ovsx publish`](https://github.com/eclipse/openvsx/blob/master/cli/README.md#publish-extensions) in your CI (you'll also need a `OVSX_PAT` environment variable, containing a token from https://open-vsx.org/user-settings/tokens).

##### Environment
- Operating System: Ubuntu
- JDK version: ?
- Visual Studio Code version: *
- Java extension version: *

##### Steps To Reproduce
1. Run `npm install`
2. Run `npx ovsx publish`
3. Notice that the extension published to https://open-vsx.org/extension/redhat/java is incomplete (i.e. broken)

See also https://github.com/eclipse-theia/theia/issues/7448

##### Current Result

Published extension is missing Java Language Server.

##### Expected Result

... should include Java Language Server.

##### Additional Informations

Currently auto-published from https://github.com/open-vsx/publish-extensions/blob/f23b96303537f99369bf6878075045de89663a3a/extensions.json#L288-L293, but publishing needs to be fixed and/or migrated to this repository.

**Comment by fbricon** [comment]
Currently, most releases of vscode-java can not be rebuilt from source after a certain time, because the server is rebuilt by the CI, instead of being downloaded from a known place. Yes, we know we need to improve that.
In the meantime, would it make things easier if you downloaded the released builds directly from our github releases page?

**Comment by jankeromnes** [comment]
Thanks for this information. Then I think it would make sense if the vscode-java CI, after rebuilding the Language Server and packaging a `redhat.java` extension, also calls `npx ovsx publish <extension>.vsix`.

If that's not possible, we could also publish the `.vsix` from your GitHub Releases to https://open-vsx.org. I'm happy to do that manually this week, but it's not really a sustainable approach.

**Comment by akosyakov** [comment]
@fbricon Please consider to claim namespace ownership in Open VSX Registry: https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace and publish with how @jankeromnes suggested in https://github.com/redhat-developer/vscode-java/issues/1353#issuecomment-607337884

It will totally resolves this issue and make sure that no one else can publish under `redhat` namespace (publisher).

**Comment by fbricon** [comment]
@jankeromnes @akosyakov trying but: https://github.com/eclipse/openvsx/issues/60

**Comment by fbricon** [comment]
Ok I pushed it manually for now: https://open-vsx.org/extension/redhat/java
I also claimed the redhat namespace: https://github.com/eclipse/open-vsx.org/issues/6

Now I need to configure the Jenkins jobs on the RH side to do the publishing automatically

**Comment by apupier** [comment]
@fbricon any news on automated publishing?

**Comment by fbricon** [comment]
@apupier sorry no, I just need to bump the priority of that task in my todo list :-)
