### ISSUE TITLE
ignore missingSerialVersion

### ISSUE THREAD

**Issue by hasanmumin** [redhat-developer/vscode-java#1356]
##### Environment
- Operating System: macOS 10.15.4
- JDK version: 1.8
- Visual Studio Code version: 1.43.2
- Java extension version: 0.58.0

##### Steps To Reproduce
Hi, I am trying to ignore missingSerialVersion warning,
I created .settings/org.eclipse.jdt.core.prefs at project root folder with this settings:

```
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.problem.missingSerialVersion=ignore
org.eclipse.jdt.core.compiler.codegen.inlineJsrBytecode=enabled
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
org.eclipse.jdt.core.compiler.compliance=1.8
org.eclipse.jdt.core.compiler.problem.assertIdentifier=error
org.eclipse.jdt.core.compiler.problem.enumIdentifier=error
org.eclipse.jdt.core.compiler.source=1.8
```
but looks like does not works, can you explain why ?

##### Current Result
Still I can see warning messages about missingSerialVersion
##### Expected Result
Hide warning messages about missingSerialVersion

**Comment by snjeza** [comment]
I can't reproduce the issue. Could you provide a sample project?

**Comment by starrykai** [comment]
I have the same problem，the project created by Intellij Idea. when I  use the vscode open it,I can see warning messages about missingSerialVersion

**Comment by hasanmumin** [comment]
You have to copy the same file to all modules.

**Comment by starrykai** [comment]
> You have to copy the same file to all modules.

I solved the problem in this way
