### ISSUE TITLE
Too many codelenses shown in lombok'ed project

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#137]
Opening an `@Data` annotated class from a lombok-powered project shows multiple codelenses for that annotation

##### Steps To Reproduce
1. setup lombok support according to https://github.com/redhat-developer/vscode-java/wiki/Lombok-support
2. clone https://github.com/springfuse/project-lombok-example
3. Open https://github.com/springfuse/project-lombok-example/blob/master/src/main/java/com/springfuse/blog/projectlombok/bean/UsingProjectLombok.java

See 
<img width="908" alt="capture d ecran 2017-01-10 a 15 49 56" src="https://cloud.githubusercontent.com/assets/148698/21824383/31232178-d74d-11e6-9301-0e83762b7886.png">

**Comment by fbricon** [comment]
So that's an interesting one :-)

Basically, the compilation unit lists all the methods generated by lombok (getters, setters...). For each element, the same sourcerange is returned (at the `@Data` location), so we generate and return 13 similar codelenses. 

So, while we can mitigate the issue by only returning 1 of those codelenses, there's a larger problem here: how should we handle references of methods/variables only existing in the bytecode, but not at the source level? Or, in the case of lombok, how are we supposed to map a variable annotated `@Getter` or `@Setter` to actual references of `getter` and `setter`. I don't think we can handle that unless providing lombok specific behavior at the server level.

@gorkem ideas?

**Comment by fbricon** [comment]
anyways I think we should not even display the codelens when there are 0 references. Not sure if we should do it at the server level.

**Comment by fbricon** [comment]
@othomann you wanne take a look at that one?

**Comment by othomann** [comment]
@fbricon yes I will as soon as I am in a position to do so. Hopefully today.

**Comment by othomann** [comment]
Working on it.

**Comment by othomann** [comment]
So this explains why the source methods are returned even if there is no source inside the actual unit on disk.

**Comment by othomann** [comment]
I think this issue should be moved to the java-language-server repo. It is the server that returns too many code lens result. It is not VS Code's issue. Any client that supports lsp with code lens would have the same issue.

**Comment by fbricon** [comment]
Fixed with https://github.com/gorkem/java-language-server/commit/1935314d50df01190db17b753a3283c191e550ce
