### ISSUE TITLE
"Language Support For Java" Extension is slowing down my CPU

### ISSUE THREAD

**Issue by nspeedzy** [redhat-developer/vscode-java#1371]
I had just installed the "Language support for Java" Extension on vscode but I find out that it takes too long to load whenever I open a `.java` file. It also slows my computer down when other tasks are running. 

##### Environment
- Operating System: Windows
- JDK version: 14
- Visual Studio Code version: 1.43.2
- Java extension version: 0.59.1

##### Steps To Reproduce
1. Restarted vscode
2. Uninstalled and installed The "Language Support For Java" Extension
3. Uninstalled and installed vscode
4. Cleaned the workspace cache and history

##### Current Result

Extension taking too long to load and also slowing down the whole system

##### Expected Result

Extension to be fully loaded and ready

**Comment by fbricon** [comment]
Please define "long"

**Comment by nspeedzy** [comment]
It is like taking almost half an hour to load fully and during the duration of the load, It is slowing down my computer

**Comment by testforstephen** [comment]
What do you mean "slowing down my computer"? High CPU usage?

Could you disable all other extensions and only keep "Language Support For Java" Extension, then try again?

**Comment by nspeedzy** [comment]
Ok

**Comment by nspeedzy** [comment]
Ok

**Comment by nspeedzy** [comment]
It is saying: "100% Starting Java language server". I have a log file to show that:

[link to log](https://github.com/nspeedzy/projects/blob/master/javalangext.log)

**Comment by testforstephen** [comment]
@nspeedzy thank you for sharing the video. I think I probably understand your issue. it's hanging at copying resource. Your project is a polyglot project, and you just create a Java file in a frontend project. The Java extension will initialize the whole folder as an invisible project, and the java builder tool will take the folders with the same level as the java file to be resources of your java file, and copy them to the output folder. That will take a long time to complete. See https://github.com/redhat-developer/vscode-java/issues/634#issuecomment-514495292

**Comment by nspeedzy** [comment]
Thanks a lot! I hope you fix this error of the extension. I will close this issue for now. But if i have anymore problems, I will reach out!

**Comment by testforstephen** [comment]
Move the java file to a separate folder, and use vscode to open the new folder directly. besides, in your frontend project, try **F1** -> **Java: Clean the Java language server workspace** to clean the java cache.

**Comment by nspeedzy** [comment]
Thanks a lot! I am going to close this issue for now. If i have anymore questions, I will reach out.

**Comment by hosain-ghoraba** [comment]
In my case, there was a vscode extension that was conflicting with java extensions and making them very very slow, try to identify this problamatic extension and disable / uninstall it.

I identified that problamatic extension by looking at the extensions tab in vscode, then I noticed there was a small text beside one of them, it was : "extension (...) has reported one message, i opened that message and it said that the extension took a huge amount of time to run, so uninstalling it solved the proplem
