### ISSUE TITLE
Press up-key does not recall last input

### ISSUE THREAD

**Issue by ICHx** [redhat-developer/vscode-java#1376]
- VSCode Version: 1.43.2
- OS Version: Manjaro rolling
```
CPU: Quad Core Intel Core i5-4460 (-MCP-) speed/min/max: 798/800/3400 MHz
Kernel: 5.4.30-1-MANJARO x86_64 Up: 2d 23h 54m Mem: 4328.2/7835.9 MiB (55.2%)
Storage: 698.65 GiB (36.9% used) Procs: 247 Shell: bash 5.0.16 inxi: 3.0.37
```

Steps to Reproduce:

1. Press UP in integrated terminal after pressing run/debug
![Screenshot_20200410_181241](https://user-images.githubusercontent.com/11556527/78983484-e190f980-7b56-11ea-88ca-18d0de4c754d.jpeg)
2. bind '"\e[A": history-search-backward'
3. Working as expected.
![Screenshot_20200410_181515](https://user-images.githubusercontent.com/11556527/78983686-3d5b8280-7b57-11ea-913f-5ac583936c2f.jpeg)
4. Not working again after pressing run/debug
![Screenshot_20200410_182007](https://user-images.githubusercontent.com/11556527/78984016-ec985980-7b57-11ea-8b23-587c876e5ac4.jpeg)

I wonder why is vscode not bind to history-search by default, while my other terminal emulator are working as expected : Konsole, tty, etc.  However, it is working on Windows 10

Does this issue occur when all extensions are disabled?: Cannot determine

**Comment by jdneo** [comment]
The integrated terminal is controlled by VS Code, this extension has nothing to do with that.
