### ISSUE TITLE
Access java doc inside vscode

### ISSUE THREAD

**Issue by jvesouza** [redhat-developer/vscode-java#1378]
[provide a description of the issue]
One feature I didn't find was how to quickly access the documentation for a class or method. In eclipse I can place the cursor on the method / class name and press the f2 key. If the source of the class is available and if there is documentation present in the source, it is displayed.
Am I doing something wrong?
##### Environment
- Operating System: linux 
- JDK version: openjdk version "1.8.0_242"
- Visual Studio Code version: 1.45.0-insider
- Java extension version: redhat.java@0.59.1

**Comment by snjeza** [comment]
@jvesouza you may want to take a look at https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition

**Comment by jvesouza** [comment]
@snjeza  Thanks for the tip, but unless I'm doing something wrong the go to type definition command opens the class where the method is declared. It is possible to access the documentation but it is not presented in a formatted way as it is in the eclipse. In eclipse, when I press f2, only the documentation is displayed.

**Comment by snjeza** [comment]
@jvesouza You can try Ctrl+K Ctrl+I (Show Hover)

**Comment by jvesouza** [comment]
@snjeza Thank you very much for this excellent tip. I started using VSCode recently and I didn't know about this feature. Another point is that as I am blind I use a screen reader in Linux to work with VSCode. Sometimes I run into accessibility problems.
I think that this issue can be closed.
Thanks again.

**Comment by jvesouza** [comment]
I am closing this issue once it has been clarified.
