### ISSUE TITLE
The problem in the console has not been fixed, and this error has not been fixed for a long time. . .It's really frustrating!

### ISSUE THREAD

**Issue by 395053994** [redhat-developer/vscode-java#1382]
The problem in the console has not been fixed, and this error has not been fixed for a long time. . .
It's really frustrating!

[provide a description of the issue]

##### Environment
- Operating System: win10
- JDK version: 1.8
- Visual Studio Code version: 1.44
- Java extension version: 
![fffffffffffffffffffffffffffffffffff](https://user-images.githubusercontent.com/27546390/79069143-72560980-7cfe-11ea-9ede-6bd84c4ab77a.png)
![fffffffffffffffffffffffffffffffffff](https://user-images.githubusercontent.com/27546390/79069158-97e31300-7cfe-11ea-813c-69784c8dcf6b.png)
![fffffffffffffffffffffffffffffffffff](https://user-images.githubusercontent.com/27546390/79069178-c234d080-7cfe-11ea-8832-2997d6f4e9ef.png)

**Comment by fbricon** [comment]
This indicates a problem with your SQL query, when running your application (the table in your database may not have been created properly during the test). Moreover, vscode-java is not responsible for running applications and tests, you're probably using [vscode-java-debug](https://github.com/microsoft/vscode-java-debug/issues).
Sorry but this issue has nothing to do with vscode-java.
