### ISSUE TITLE
Organize Imports should resolve static imports as well

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-java#1386]
When doing `Organize Imports`, static imports should be resolved as well by using the setting `java.completion.favoriteStaticMembers`.
The editor already "knows" what I want, because when I press `Ctrl+.` on one of the unresolved static imports, it proposes to `Add static import for ...` So I'd like for `Organize Imports` to go over any remaining syntax errors in the file, and see if it could be resolved by doing a static import of one of my configured favorites.

##### Environment
- Operating System: Windows 10
- JDK version: 14
- Visual Studio Code version: 1.44.0
- Java extension version: 0.59.1

##### Steps To Reproduce
1. configure `java.completion.favoriteStaticMembers` as follows:
````json
"java.completion.favoriteStaticMembers": ["java.util.stream.Collectors.*"]
````
2. create a file `App.java` as below
3. do `Organize Imports`

````java
import java.util.List;

class App {
    public void foo() {
        return List.of(1).stream().collect(toList());
    }
}
````

##### Current Result
No changes are made.

##### Expected Result
The following import is added automatically:
> import static java.util.stream.Collectors.toList;

**Comment by snjeza** [comment]
The issue can be reproduced in Eclipse. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=283287

**Comment by fbricon** [comment]
@snjeza do you think it would be possible for jdt.ls to be able to easily compute autimports based on `java.completion.favoriteStaticMembers`, until this is fixed upstream?

**Comment by snjeza** [comment]
@fbricon Yes, I do. I will check.

**Comment by N-benitha** [comment]
hey! can you help me, I want to import a static member 'of' from the package 'java.util.List' but i don't know how to insert it in "java.completion.favoriteStaticMembers":

**Comment by fbricon** [comment]
For some reason "java.util.List.*" doesn't work, but "java.util.List.of" does:

> "java.completion.favoriteStaticMembers": [
>         "java.util.List.of",
>         ...
>     ]

<img width="554" alt="Screenshot 2024-04-05 at 00 34 46" src="https://github.com/redhat-developer/vscode-java/assets/148698/2fcc2a22-aa44-4c3b-91d1-841dc4d08362">

**Comment by N-benitha** [comment]
I figured, thank you
