### ISSUE TITLE
Organize Imports should not propose module-encapsulated classes

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-java#1387]
If I do `Organize Imports`, it should not propose classes which are in a module package that isn't exported.

##### Environment
- Operating System: Windows 10
- JDK version: 14
- Visual Studio Code version: 1.44.0
- Java extension version: 0.59.1

##### Steps To Reproduce
1. create a file `App.java` as below
2. do `Organize Imports`

````java
class App {
    void run() {
        HttpClient client;
    }
}
````

##### Current Result
2 classes are proposed: `sun.net.www.http.HttpClient` and `java.net.http.HttpClient`

##### Expected Result
`java.net.http.HttpClient` is automatically imported, since the `sun.net.www.http` package is not exported by `java.base`

**Comment by CsCherrYY** [comment]
I can't reproduce in the newest version (1.16.0).
