### ISSUE TITLE
import spring-boot project，can‘t start

### ISSUE THREAD

**Issue by spiritelf** [redhat-developer/vscode-java#1392]
[provide a description of the issue]

##### Environment
- Operating System:win8
- JDK version: jdk1.8.0_22
- Visual Studio Code version:1.44.0
- Java extension version:0.9.0

##### Steps To Reproduce
1. 
![image](https://user-images.githubusercontent.com/8556186/79247698-6d838800-7ead-11ea-8a9e-cd27771ffa96.png)

2. 
![image](https://user-images.githubusercontent.com/8556186/79247726-75432c80-7ead-11ea-9193-225bbdc7ad00.png)

3.
![image](https://user-images.githubusercontent.com/8556186/79247768-82f8b200-7ead-11ea-8ad1-6e8fc5c9748e.png)

have no error for start spring-boot?

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Closing, as stated in the issue template you read when creating this ticket:

>      IF YOUR ISSUE CONCERNS RUNNING/DEBUGGING JAVA CODE, 
>      PLEASE OPEN YOUR TICKET IN https://github.com/microsoft/vscode-java-debug/issues

**Comment by spiritelf** [comment]
i use spring-boot dashboard ，the same error

**Comment by Eskibear** [comment]
@spiritelf sprint-boot dashboard depends on the java debugger extension to run. 
Go ahead to create a new issue in https://github.com/microsoft/vscode-java-debug/issues
