### ISSUE TITLE
Any way to suppress langserver.log file creation?

### ISSUE THREAD

**Issue by fish47** [redhat-developer/vscode-java#140]
##### Steps To Reproduce
There's a langserver.log in home directory after open a java file, no matter the file is read only or not.

##### Environment
archlinux 4.8.13-1
vscode 1.8.1-1
vscode-java 0.0.8
jdk 8u112-1

**Comment by fbricon** [comment]
Already fixed with https://github.com/gorkem/java-language-server/commit/76338688eec055c3969105f8396e62b81db6a5ac
