### ISSUE TITLE
Avoid reporting wrong & distracting errors

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-java#1400]
In the event of a seemingly innocent syntax error, it regularly happens that other, incorrect errors are reported across the file, which makes it a lot harder to find the culprit. Note that the sample below serves just as a reproducer, but in reality, files are often several hundreds of lines of code, so finding the syntax error that actually matters can be a real challenge.

##### Environment
- Operating System: Windows 10
- JDK version: 14
- Visual Studio Code version: 1.44.2
- Java extension version: 0.60.0

##### Steps To Reproduce
1. create a file as below

````java
public class App {
    
    static record Baz(String foo, String bar) {

        Baz(String foo) {
            this(foo, foo);
        }

    }

    static record Any {

    }

}
````

##### Current Result
![image](https://user-images.githubusercontent.com/15714253/79689031-8cd63880-8252-11ea-80cf-ba0df3d513f8.png)

##### Expected Result
Compare this with IntelliJ IDEA, which gives a single error that tells me exactly what the issue is:
![image](https://user-images.githubusercontent.com/15714253/79689060-b3946f00-8252-11ea-91ce-3a7c7bb973b5.png)

**Comment by anthonyvdotbe** [comment]
As another example: there's a missing comma after the first method parameter.

In VS Code this also results in a confusing error on the enum:
![image](https://user-images.githubusercontent.com/15714253/81427014-6113e780-915a-11ea-9cc6-caccffb9ac54.png)

In IntelliJ IDEA there's a single error on the second method parameter:
![image](https://user-images.githubusercontent.com/15714253/81427274-de3f5c80-915a-11ea-8255-872e1b551b73.png)

**Comment by mickaelistria** [comment]
The behavior I see currently in Eclipse IDE and vscode-java matches the expectation. This issue should most likely be closed.
