### ISSUE TITLE
Debug will fail to run if user folder contains whitespace.

### ISSUE THREAD

**Issue by euseanwoon2016** [redhat-developer/vscode-java#1401]
Debug will fail to run if user folder contains whitespace.

##### Environment
- Operating System: Windows 10
- JDK version: 14.0.1
- Visual Studio Code version: 1.44.2
- Java extension version: 0.60.0

##### Steps To Reproduce
1. Log into an account where the user folder has whitespace.
2. Attempt to debug a .java file.

Sample project is a simple hello world project.
There is no issue related to Java, it is just the issue of whitespace causing the debug to not run.

##### Current Result
Shown in terminal:
```
$  "C:\\Users\\John Doe\\.vscode\\extensions\\vscjava.vscode-java-debug-0.25.1\\scripts\\launcher.bat" "C:\\Program Files\\Java\\jdk-14.0.1\\bin\\java.exe" -agentlib:jdwp=transport=dt_socket,serve 
r=n,suspend=y,address=localhost:53028 --enable-preview -Dfile.encoding=UTF-8 -cp "C:\\Users\\John Doe\\AppData\\Roaming\\Code\\User\\workspaceStorage\\0354e799023600b12167dce898629ca7\\redhat.java 
\\jdt_ws\\java-vscode_77f09d7f\\bin" vscodejava
'C:\Users\John' is not recognized as an internal or external command,
operable program or batch file.
```

##### Expected Result
It shows "Hello World!" in console.

**Comment by fbricon** [comment]
Closing, as stated in the issue template you read when creating this ticket:

>      IF YOUR ISSUE CONCERNS RUNNING/DEBUGGING JAVA CODE, 
>      PLEASE OPEN YOUR TICKET IN https://github.com/microsoft/vscode-java-debug/issues
