### ISSUE TITLE
New File -> (module|package)-info.java should be handled properly

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-java#1405]
As the title says. The steps below are for module, but package-info.java has the same issue

##### Environment
- Operating System: Windows 10
- JDK version: 14
- Visual Studio Code version: 1.44.2
- Java extension version: 0.60.0

##### Steps To Reproduce
1. New File -> module-info.java

##### Current Result
![image](https://user-images.githubusercontent.com/15714253/79876542-76171980-83eb-11ea-83e5-2974ebbe5159.png)

##### Expected Result
A proper module declaration

**Comment by fbricon** [comment]
New module-info.java:
![module-info](https://user-images.githubusercontent.com/148698/80476464-b6761a80-894a-11ea-8f70-39617b5c5485.gif)

New package-info.java:
![package-info](https://user-images.githubusercontent.com/148698/80476469-b83fde00-894a-11ea-8e16-0e20e40888e2.gif)
