### ISSUE TITLE
Get and Set method generation through intellicode generates javadoc when shouldn't

### ISSUE THREAD

**Issue by cesarrew** [redhat-developer/vscode-java#1411]
Get and Set method generation through intellicode generates javadoc as well, even with the property "java.codeGeneration.generateComments" defined as "false".

##### Environment
- Operating System: Ubuntu 19.10
- JDK version: openjdk 11.0.7 2020-04-14
- Visual Studio Code version: 1.44.2
- Java extension version: 0.60.0

1. Create a POJO Java Class
2. Define an attribute
3. Using intellicode, generate get or set method for the attribute.

![code_generation_get_set](https://user-images.githubusercontent.com/17600341/80317644-6167c680-87db-11ea-8266-a6f40b2f79cb.png)

**Comment by fbricon** [comment]
The language server has different ways of creating methods, typically this setting is respected only when calling the Generate Getters/Setters source action. This is a discrepancy we definitely need to fix.

**Comment by fbricon** [comment]
https://github.com/eclipse/eclipse.jdt.ls/pull/1437 should fix it
