### ISSUE TITLE
Alt+Shift+U = command not found

### ISSUE THREAD

**Issue by knm1993** [redhat-developer/vscode-java#1414]
Briefing :  
command 'java.projectConfiguration.update' not found

##### Environment
- Operating System: Windows 7 64-bit
- JDK version: Java jdk-14.0.1
- Visual Studio Code version: 1.44.2 System version
- Java extension version: jre1.8.0_251

##### Steps To Reproduce
1. Create a Springboot project with Maven setup
2. Go to the pom.xml to change the maven target version
3. Press Alt+Shift+U
4. bottom right pop up: command 'java.projectConfiguration.update' not found

[Please attach a sample project reproducing the error]
https://github.com/knm1993/java-vscode-springboot-demo-case1  

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
[log.txt](https://github.com/redhat-developer/vscode-java/files/4543300/log.txt)

##### Current Result
When you press Alt+Shift+U, you see command not found
##### Expected Result
When you press Alt+Shift+U, you should expect that works properly, update.
##### Additional Informations
To make the troubleshooting more easily, I have already make a clean uninstall of vs code, as well as removing all extension.

The current extension in my vscode only contains the following 4 extension -

1. 2077 theme
2. Beautify
3. Git Graph
4. Language Support For Java(TM) by Red Hat

**Comment by fbricon** [comment]
For some reason, the java server files can not be copied to "C:\Users\01705441\AppData\Roaming\Code\User\globalStorage\redhat.java\0.60.0\config_win\org.eclipse.osgi\"  It's not caused by the windows file path limit, as we're well below 260 characters. Possibly caused by write access to that directory?
Anyways, if the server fails to install and start, then the vscode-java extension can not register the  `java.projectConfiguration.update` command.
Are you working in a sort of limited environment?

**Comment by knm1993** [comment]
Thanks for the advice.
I think I am under a company policy PC, which strictly limited to my own personal user's folder.
I will try to give a try on permission setting to see if it's related.

**Comment by knm1993** [comment]
I have tried to look into the folders but I saw all of the security permission are checked as allowed already.
The vs-code is also under "run with administrator" mode.
Trying to reinstall the extension does not resolve the problem.

However I quite believe that there are something limited the extension to register the command as there are some other people who successfully do it.

May there be any work around like manual register the command/ manual reflect the update of pom.xml?

**Comment by knm1993** [comment]
Found an workaround based on VS-Code.

The above issue is proved to be access right/ limited user environment related.

The workaround is simple, move all your extensions and user data out of the %APPDATA%, and move into a workspace where your account can be accessed.

Quick(Lazy) Guide:
1. Open "Cmd prompt"
2. Input "code --extension-dir <dir> --user-data-dir <dir>"
3. The vs code will open as a brand new one, without any ext/user pref. (first time)
4. install the red hat extension
5. it register successfully.

Hope this guide may help others. And I think this info is worth to be placed into troubleshooting for limited user.
