### ISSUE TITLE
Provide goToDefinition API 

### ISSUE THREAD

**Issue by KaihangXing** [redhat-developer/vscode-java#1416]
#### [This is not an issue but a requirement]

I want to get the symbol's defination but not the Document defination through ExtensionAPI in another vscode plugin. Such as a method's class, package and parameters. 

I can't find suitable method in current ExtensionAPI. 

Could anyone help me?  Thanks a lot~

**Comment by fbricon** [comment]
Sorry, this is currently not possible at the moment

**Comment by KaihangXing** [comment]
> Sorry, this is currently not possible at the moment

I just commit a PR for this enhancement https://github.com/redhat-developer/vscode-java/pull/1425

**Comment by fbricon** [comment]
@KaihangXing this will be part of the next release, mid-May 2020
