### ISSUE TITLE
Use default JVM when importing gradle project

### ISSUE THREAD

**Issue by jakegt1** [redhat-developer/vscode-java#1426]
So, i have a gradle project and have set the following configuration:

```
{
    "java.configuration.runtimes": [
        {
          "name": "JavaSE-1.8",
          "path": "path/to/jdk8",
          "default": true
        }
    ],
    "java.home": "/path/to/jdk11"
}
```

However, my problems section is complaining about missing the javax classes which were removed after java 8, indicating that it's not using jdk 8.

##### Environment
- Operating System: Linux
- JDK version: 11/8
- Visual Studio Code version: 1.44.2
- Java extension version: 0.60.0

##### Steps To Reproduce
1. Set java.home to JDK11.
2. Set java.configurations.runtime default to JDK8.
3. See that you're not using JDK8 in problems screen.

##### Current Result

Doesn't use JDK8

##### Expected Result

Uses JDK8

**Comment by fbricon** [comment]
Did you add
> sourceCompatibility = '1.8'
targetCompatibility = '1.8'

at the root of your build.gradle (not in the [compileJava block](https://github.com/eclipse/buildship/issues/978))?

**Comment by jakegt1** [comment]
I tried this but (imo) this is not a good solution. I don't need currently to use JDK 11 for development (plus I think it's a poor idea to just assume java.home as the default if I set it manually in java.configuration.runtime.)

I set it in a subproject (not the root project) and it didn't work. Setting the comparability mode for every single project I work on is unfeasible (especially if I try to work on an old project, or a project I cannot edit.) I could manually add it every time I guess, but this is quite the pain while developing.

Is it possible to always use the default java.configuration.runtime option? Or at least have a manual setting to always use a different jdk to compile?

**Comment by jakegt1** [comment]
Other then that, it seems awkward to do that in the root of build.gradle when the gradle docs tell you to do that differently.

**Comment by fbricon** [comment]
- you should definitely, define sourceCompatibility/targetCompatibility in your build.gradle, as a best practice, to ensure build reproducibility, across platforms. The fact that the compileJava block is not respected is a different, upstream issue
- when setting JavaSE-8 as the default, it should definitely be used by default in your project, instead of Java 11. If not, then it's a bug. @snjeza did work on that part, she can investigate.

**Comment by jakegt1** [comment]
I'm not saying it isn't best practice (as long as the downstream is fixed anyway), but it isn't feasible to do this for every single project in a big team. 

I will start doing it in the future , but I see nothing wrong with if you set the default runtime, it should just use that one.

**Comment by jakegt1** [comment]
@fbricon @snjeza just to say thanks for the real quick turnaround on this, understand that it's pretty frustrating to support people on aging JDKs.
