### ISSUE TITLE
Inconsistent autocompletion behavior for constructors

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#143]
When triggering autocompletion on a constructor, when one continues typing, the selected/relevant proposal is lost, as some leading characters seem to be missing from the selection.

Additionally, in some circumstances, eg. after triggering autocomplete then deleting the previous character, the injected text is missing the leading characters (one or many). 

See https://www.screencast.com/t/17vjLA8vC0hq

**Comment by fbricon** [comment]
@othomann do you a similar behavior in Orion? I wonder if this is a server or client problem (my guts say the latter)

**Comment by othomann** [comment]
No, I don't think I ever seen anything like this in Orion.
