### ISSUE TITLE
Setting a different jdk version in settings.json (workspace)

### ISSUE THREAD

**Issue by n8s16** [redhat-developer/vscode-java#1431]
##### Environment
- Operating System: Windows 10
- JDK version: Multiple JDK (Java Home is Java1.8)
- Visual Studio Code version: 1.44.2
- Java extension version: 0.61.0

##### Steps To Reproduce
- I created a simple java hello world project.
- I setup my _java.home_ in settings.json (workspace) to
```json
{
    "java.home": "C:\\Program Files\\Java\\jdk11.0.2",
    "java.configuration.runtimes": [
        {
          "name": "JavaSE-1.8",
          "path": "C:\\Program Files\\Java\\jdk1.8.0_121",
        },
        {
          "name": "JavaSE-11",
          "path": "C:\\Program Files\\Java\\jdk11.0.2",
          "default": true
        }
      ]
}
``` 
   because I want to use Java11.

- Java version in my environmental variables is set to `C:\\Program Files\\Java\\jdk1.8.0_121`.

As per the instruction posted here: https://github.com/redhat-developer/vscode-java#setting-the-jdk, vscode will use the workspace settings.json.

But when I tried running/debugging my application it has an error:
```
$  C:\Users\userX\.vscode\extensions\vscjava.vscode-java-debug-0.25.1\scripts\launcher.bat "C:\Program Files\Java\jdk1.8.0_121\bin\java.exe" -agentlib:jdwp=transport=dt_socket,server=ntlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:54576 -Dfile.encoding=UTF-8 -cp C:\test\test-java11\bin app.App
bash: C:UsersuserX.vscodeextensionsvscjava.vscode-java-debug-0.25.1scriptslauncher.bat: command not found
```

Is this an existing issue or am I doing it wrong? Thank you!

**Comment by fbricon** [comment]
Sorry but running code is out of scope of vcode-java. As you probably saw when opening this ticket: 

> IF YOUR ISSUE CONCERNS RUNNING/DEBUGGING JAVA CODE, 
PLEASE OPEN YOUR TICKET IN https://github.com/microsoft/vscode-java-debug/issues

**Comment by testforstephen** [comment]
The debugger will use the corresponding JDK with your project file. Could you share the `.classpath` file of your project?
