### ISSUE TITLE
Overriden class in test package causes "type is already defined" error

### ISSUE THREAD

**Issue by ricmzn** [redhat-developer/vscode-java#1432]
##### Environment
- Operating System: Windows 10 version 1909 (x64)
- JDK version: AdoptOpenJDK 11.0.5 (x64)
- Visual Studio Code version: 1.44.2
- Java extension version: 0.61.0

##### Steps To Reproduce
Example project:  [duplicate-class-in-test-v2.zip](https://github.com/redhat-developer/vscode-java/files/4577534/duplicate-class-in-test-v2.zip)

1. Open the example project in VS Code
2. Open `src/main/java/com/example/Hello.java`
3. Wait for background compilation to finish
4. Observe the following error in the problems panel:
![image](https://user-images.githubusercontent.com/6194377/81013213-272ca380-8e31-11ea-854f-7b76883302f0.png)

##### Current Result

The editor will complain about a duplicate class because of there are two classes with matching packages and names in `src/main` and `src/test`.

##### Expected Result

There should be no error, as the class in `src/test` is only in the classpath during tests, and it overrides the one in `src/main`, which is useful for mocking classes from dependencies or classes which rely on static initializers.

##### Additional Information

Opening the class in `src/test` in the text editor will clear the error in the problems panel after a few seconds. While this is a valid workaround, this has to be done every time the editor is launched, and not doing so breaks debugging, as the debugger does not start if there are any errors logged, regardless of actual compilation status (probably another bug, unrelated to this one).

The project can also be verified as working properly by compiling and testing it with `mvn package` from a clean version.

**Edit:** sorry, the original example didn't have tests configured to run properly. It's fixed now.

**Comment by fbricon** [comment]
This is a limitation of the ECJ compiler. Even though this is a deviation from the regular CLI Maven build behavior, this won't be fixed, as there is practically no legitimate reason to redefine a class in the test directory. If you want to mock classes for testing purposes, you can either create a new class that extends Hello, or use an actual mocking framework.
