### ISSUE TITLE
System cannot be resolved, VsCode

### ISSUE THREAD

**Issue by chidiadi01** [redhat-developer/vscode-java#1433]
System cannot be resolved Java(570425394)

##### Environment
- Windows 10:
- JDK version 8:
- Visual Studio Code version 1.42.1:
- Java Extension Pack 0.9.0:

##### Steps To Reproduce
1. Create a public class
2.  Inside it, type system.out.println("test");

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
