### ISSUE TITLE
No Property Completion in properties file?

### ISSUE THREAD

**Issue by hanct** [redhat-developer/vscode-java#1436]
Hi,

does vscode-java extension support property completion? Cos i am currently developing a gradle-based Spring boot application. With the usage of @ConfigurationProperties annotation from Spring Boot libraries, i was expecting some completion intellisense in the properties editor.  But I could not see this.

**Comment by fbricon** [comment]
No it doesn't, this is out of scope of vscode-java. But The Spring Boot Tools provides just that: https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-spring-boot#code-completions
