### ISSUE TITLE
encoded problem？

### ISSUE THREAD

**Issue by H749119662** [redhat-developer/vscode-java#1443]
My English is poor. I tried to translate it as faithfully as possible.  
On my computer,running the code below,return chinese is null.
`import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

public class testA {
    public static void main(String[] args) throws IOException {
        InputStream a = System.in;
        InputStreamReader b = new InputStreamReader(a, "UTF-8");
        BufferedReader br = new BufferedReader(b);
        System.out.println("=======");
        System.out.print("输入:");
        String msg = br.readLine();
        System.out.print("输出:" + msg + "\n");
        System.out.println("=======");
    }
}`
![A](https://user-images.githubusercontent.com/48521235/81702600-17026d00-949e-11ea-8fd2-2e4a805a0fae.jpg)

##### Environment
- Operating System: Windows 10
- JDK version : 14.0.1
- Visual Studio Code version:  1.45
- Java extension version: ava Extension Pack 0.9.0

**Comment by H749119662** [comment]
![A](https://user-images.githubusercontent.com/48521235/81702842-634dad00-949e-11ea-8870-e93c922bb09f.jpg)

**Comment by H749119662** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS D:\File\Java\SXT\02>  & 'c:\Users\User\.vscode\extensions\vscjava.vscode-java-debug-0.25.1\scripts\launcher.bat' 'D:\Software\Java\jdk-14.0.1\bin\java.exe' '-Dfile.encoding=UTF-8' '@C:\Users\User\AppData\Local\Temp\cp_2dq6usd00k9gcoqw4k2itw4jk.argfile' 'testA'
===Output===
输入:中文English
输出:  English
===Output===
PS D:\File\Java\SXT\02> mode

Status for device CON:
----------------------
    Lines:          21
    Columns:        150
    Keyboard rate:  31
    Keyboard delay: 1
    Code page:      65001

**Comment by fbricon** [comment]
There's an encoding issue on your machine, as it works for me, but I'm sorry, this is out of scope of vscode-java. As you might have seen when opening this ticket:

>  IF YOUR ISSUE CONCERNS RUNNING/DEBUGGING JAVA CODE, 
     PLEASE OPEN YOUR TICKET IN https://github.com/microsoft/vscode-java-debug/issues 

The vscode-java-debug team is based in Shanghai, so I'm fairly confident they can help you better
