### ISSUE TITLE
Multiline inner "record" not properly highlighted

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#1444]
2nd part of #1442: Inner Java 14's record, when the record keyword is on a separate line, is not properly colored, even with semantic highlighting turned on.

```java
public class Demo {
  public static void main(String[] args) {
    record
    Foo(int i,int j){}
    Foo foo = new Foo(0, 1);
    System.out.println(foo);
  }
}
```
is displayed as:
<img width="549" alt="Screen Shot 2020-05-12 at 5 12 08 PM" src="https://user-images.githubusercontent.com/148698/81711248-bc541b80-9473-11ea-8fca-3447dd34cd3a.png">

**Comment by fbricon** [comment]
@Eskibear is this something you can help with?

**Comment by Eskibear** [comment]
I find that the issue also exists for multi-line inner class. 
```java
public class Foo {
    public static void main(String[] args) {
        class 
        Bar {
            
        }
    }
}
```
In the main function you'll see both `class` and `Bar` are not highlighted. Turn semantic highlighting on, it will highlight `Bar` (types and variables have been supported), but the `class` is still not highlighted (semantic highlighting for keywords hasn't been implemented). 

Semantic highlighting should be the right way to go, but some investigation is required as I don't know how far RecordDeclaration has been supported in upstream JDT core.

**Comment by Eskibear** [comment]
As for keywords like "class" and "record", it's would be good and cheap to leverage syntax highlighting (as long as they got  https://github.com/atom/language-java/issues/186 fixed).
