### ISSUE TITLE
Completion adds more duplicate snippets as you type

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#1445]
With latest vscode insiders and vscode-java 0.61.0, completion adds more duplicate snippets as you type. eg. with the `main` snippet:

![May-13-2020 01-59-08](https://user-images.githubusercontent.com/148698/81757302-ba637a00-94be-11ea-894c-bcf30233e268.gif)

I checked the server response, and the snippets are nowhere to be found. So it looks like this is coming from the vscode extension itself. Might be a regression in vscode-insiders or a change in behavior that highlights an issue in vscode-java.

@jdneo can you please investigate?

**Comment by jdneo** [comment]
Sure, will take a look.

**Comment by jdneo** [comment]
@fbricon The upstream bug has been fixed: https://github.com/microsoft/vscode/issues/97659

I've verified in the newest insider and the completion works fine.

---

Version: 1.46.0-insider (user setup)
Commit: e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb
Date: 2020-05-13T18:20:10.752Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by jdneo** [comment]
@fbricon I think we can close this issue now.

**Comment by fbricon** [comment]
Yup, everything works now
