### ISSUE TITLE
Convert a lambda expression to method reference?

### ISSUE THREAD

**Issue by lordofthejars** [redhat-developer/vscode-java#1448]
##### Steps To Reproduce

It will be nice to have a refactor option and underlying in yellow, when a lambda expression can be rewritten using method reference.

##### Current Result

Not supported

##### Expected Result

Have an option to refactor automatically, and mark as a warning to advice the developer that this could be refactored.

**Comment by fbricon** [comment]
New "Convert to lambda expression"/"Convert to Method reference" code actions:

![1448](https://user-images.githubusercontent.com/388609/96165565-13778400-0f1d-11eb-9071-6e8a6fd72395.gif)
