### ISSUE TITLE
The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by AdityaGovardhan** [redhat-developer/vscode-java#1449]
Installed Oracle JDK, created JAVA_HOME variable. 
```
$ echo $JAVA_HOME
/home/adi/Software/jdk1.8.0_251
```

Installed Language Support for Java(TM) by Red Hat (Extension)

Restarted VS Code but it leads to the following error display
![image](https://user-images.githubusercontent.com/29920883/81877153-3ef2de80-9539-11ea-920b-0fe3868383d9.png)

##### Environment
- Operating System: Ubuntu 20.04
- JDK version: jdk1.8.0_251
- Visual Studio Code version: 1.45.0
- Java extension version: 0.61.0

vscode-java logs
![image](https://user-images.githubusercontent.com/29920883/81877432-ea9c2e80-9539-11ea-9abb-c56be6cc2d2e.png)

Java Language Server's workspace logs
![image](https://user-images.githubusercontent.com/29920883/81877614-639b8600-953a-11ea-8827-191c754c49ba.png)

##### Current Result
JDK should be detected from JAVA_HOME environment variable as per https://github.com/redhat-developer/vscode-java#setting-the-jdk but it is not able to

##### Expected Result
installed java, VS Code and Red Hat extension should work together seamlessly

**Comment by fbricon** [comment]
Can you paste the content of your user settings.json?

**Comment by AdityaGovardhan** [comment]
Hi @fbricon 
I was able to figure out the issue, turns out that I was defining the JAVA_HOME variable in my ~/.bashrc but not exporting it. This lead to vs-code process being unaware of the JAVA_HOME variable. Rookie mistake, sorry. https://stackoverflow.com/questions/1158091/defining-a-variable-with-or-without-export

Thanks for your comment, closing the issue.
