### ISSUE TITLE
Java Language Server is not working even I Clean the Java language server workspace

### ISSUE THREAD

**Issue by mannok** [redhat-developer/vscode-java#1451]
I am currently using the plugin for my companies project, it is a large project and we use a private package repository. This plugin has never worked successfully in the project even I have cleaned up the Java Language Server Workspace.

##### Environment
- Operating System: Windows 10
- JDK version: jdk1.8.0_151 (by setting it on settings.json with "java.home": "C:\\Program Files\\Java\\jdk1.8.0_151")
- Visual Studio Code version: 1.45.0
- Java extension version: 0.61.0

##### Steps To Reproduce
1. Open my Maven project with VS Code in the same level with pom.xml
2. Open an arbitrary .java file
3. F1 -> Clean up the Java Language Server Workspace -> wait to restart
4. Click on certain highlighted class name and click F12 and it will show me `No definition found for 'xxxxxxxx'`

Server Log:
[https://gist.github.com/mannok/e441a123806d71bc169f9f8d0d3cdb28](https://gist.github.com/mannok/e441a123806d71bc169f9f8d0d3cdb28)

Seems that it is a problem relate to artifact. However, my project can be compile successfully. How come Java Language Server cannot work properly?

##### Current Result
Language Server is not working as all

##### Expected Result
Language Server should be functionable

**Comment by fbricon** [comment]
Looks like it's failing to download dependencies.Are you behind a proxy?, do you use a user or global maven settings.xml?

**Comment by mannok** [comment]
> Looks like it's failing to download dependencies.Are you behind a proxy?, do you use a user or global maven settings.xml?

@fbricon Yes, I am behind a proxy, but I can fetch all my dependencies when I run `mvn install -f "c:\projects\xxx.yyy.zzz\pom.xml"`. Isn't Java Language Server runs in the same way?

I do not have any settings.xml in %USERPROFILE%\.m2, so global maven settings.xml should be used (C:\apache-maven-3.3.9\conf\settings.xml as I have installed it at this path)

**Comment by fbricon** [comment]
The language server embeds its own Maven runtime, so ignores the global maven settings.xml set in your local copy of apache-maven-3.3.9. I **strongly** suggest you move your proxy settings in your %USERPROFILE%.m2/settings.xml, so those settings will survive any future Maven update, and can be automatically picked up by both Eclipse (if you ever want to use it) and vscode-java.

Alternatively, you can try setting `"java.configuration.maven.userSettings":"C:\apache-maven-3.3.9\conf\settings.xml"` in your user settings.json, in vscode

**Comment by mannok** [comment]
@fbricon WOOOOOOOOOO!!!   THANK YOU SOOOOOOOO MUCHHHHHHH BRO!!!!!!!!     You save my life!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by pythonpadawanEXE** [comment]
I also had this problem where getting the rror"PKIX path building failed" and "unable to find valid certification path to requested target" thanks for this solution i didn't realise there would be not only a separate java installation but also a separate maven installation
