### ISSUE TITLE
Allow support of standalone java files in subfolders

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-java#1453]
I have a use case a bit particular for VS Code java related VS Code Camel K.
Apache Camel K is using standalone java files.
VS Code Camel K is downloading the required dependencies and providing them through the java.referencedLibraries setting of VS Code Java.
it works great for standalone Java files which are at the root of the workspace.
The Apache Camel K examples folders ([here](https://github.com/apache/camel-k/tree/master/examples) and [here](https://github.com/apache/camel-k-examples/)) is providing a lot of examples, including some that are contained in a specific subfolder.
VS Code Java is reporting error complaining that `The declared package "" does not match the expected package "<thefoldername>"`

would it be possible to import each subfolder as an invisible project?

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. install [VS Code Camel K extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-camelk)
2. install Language support for java
3. clone https://github.com/apache/camel-k
4. open `examples` folder in VS Code instance
5. open one of the java file
--> there is error  `The declared package "" does not match the expected package "<thefoldername>"`
--> note that there are also errors due to missing dependencies which are a problem at VS code Camel K and not at VS Code Java at all

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by apupier** [comment]
@jdneo any ideas on it? (@fbricon suggested me to ping you ;-))

**Comment by jdneo** [comment]
@apupier Sorry, but I didn't see any java file in the examples folder contains the package statement. Could you provide the specific file name that I should open?

**Comment by apupier** [comment]
none of these files should have a package statement inside it. SO that's normal that you don't find one. The problem is that VS COe Java is reporting an error about this missing package statement.

Some of java files:
- at the "root" examples folder https://github.com/apache/camel-k/blob/master/examples/Sample.java
- in subfolder of "examples" folder https://github.com/apache/camel-k/blob/master/examples/saga/Flight.java

I mentioing "examples" as the root as it is the one that makes sense in my use case to be opened as root folder for VS Code instance.

**Comment by jdneo** [comment]
I see. After I added the `camel-core-2.8.1.jar`, I can see the error: `The declared package "" does not match the expected package "xxxx"`.

@testforstephen Does the invisible project importer support standalone java files in subfolders?

**Comment by testforstephen** [comment]
@jdneo Yes, it does. What you need is to manually mark each subfolder as a source root. You can achieve that through File Explorer context menu "**Add Folder to Java Source Path**"/"**Remove Folder from Java Source Path**".

**Comment by jdneo** [comment]
> @jdneo Yes, it does. What you need is to manually mark each subfolder as a source root. You can achieve that through File Explorer context menu "**Add Folder to Java Source Path**"/"**Remove Folder from Java Source Path**".

@apupier will this help to solve your problem?

**Comment by apupier** [comment]
> > @jdneo Yes, it does. What you need is to manually mark each subfolder as a source root. You can achieve that through File Explorer context menu "**Add Folder to Java Source Path**"/"**Remove Folder from Java Source Path**".
> 
> @apupier Would you mind have a try and let us know if this solves your problem?

(sorry, llate answer, I was on PTO)

Unfortunately, it is not working. I have this error message:

`Cannot add the folder '/examples_2d1f0b05/_/kafka' to the source path because it's parent folder is already in the source path of the project 'examples_2d1f0b05'.`

![Screenshot from 2020-06-05 10-41-52](https://user-images.githubusercontent.com/1105127/83856001-3006e280-a719-11ea-8f44-9b831f23a83c.png)


I guess that i tis because the parent folder also contains Java files and thus is considered as a source root folder and we cannot add a source root folder when it is inside another source root folder.

**Comment by testforstephen** [comment]
A workaround is to remove the parent folder from source path first, then add the sub folder to source path, finally add the parent folder to source path again.

**Comment by apupier** [comment]
ok so this is a workaround which is mostly working.
I have the error removed when I open the file but if i open the file of another subfolder, the error is shown in Problems view.

![declarepackeError-afterworkaround](https://user-images.githubusercontent.com/1105127/83858502-e7e9bf00-a71c-11ea-812d-f3ea64e22584.gif)


another question: how to avoid the manual workaround?

**Comment by testforstephen** [comment]
Because standalone folders are not well structured, it's hard for extension to know which folder should be taken as source root. If you have multiple source folders, you must manually mark them as source folder one by one.

**Comment by jdneo** [comment]
The command `Java: Configure Classpath` should somehow mitigate the problem

**Comment by testforstephen** [comment]
> The command `Java: Configure Classpath` should somehow mitigate the problem

Also user can configure it in workspace settings.json via `java.project.sourcePaths` key.

Closing it. Feel free to reopen it if you want further discusson. @apupier
