### ISSUE TITLE
Auto import static constant not working

### ISSUE THREAD

**Issue by ganezdragon** [redhat-developer/vscode-java#1462]
When using constants defined in another java final class, the auto import doesn't automatically import the required constant. Instead the user has to manually import the package containing the constants.

##### Environment
- Operating System: macOs mojave 10.14.6
- JDK version: openJDK 11
- Visual Studio Code version:  1.45.1
- Java extension version:  0.62.0

##### Steps To Reproduce
1. Constants.java -> have constants as below.
```
public final class SampleConstants {
  /**
   * Private constructor
   */
  private SampleConstants() {
  }

  public static final String SAMPLE_CONSTANT = "sample";
}
```
2. AnotherFile.java -> try if autocomplete works, when you type `SAMPLE_CONSTANT`

##### Current Result
Auto complete / auto import doesn't work

##### Expected Result
Auto complete / auto import should work

**Comment by thomas0306** [comment]
Hi I am having the same issue since yesterday, below is the error in Log(Extension Host):
`[2020-05-22 16:31:16.167] [exthost] [error] [redhat.java] provider FAILED
[2020-05-22 16:31:16.168] [exthost] [error] Error: The request (id: 19, method: 'textDocument/hover') has been cancelled
	at /Users/leekwa/.vscode/extensions/redhat.java-0.62.0/dist/extension.js:1:73520
	at /Users/leekwa/.vscode/extensions/redhat.java-0.62.0/dist/extension.js:1:73814
	at Immediate.<anonymous> (/Users/leekwa/.vscode/extensions/redhat.java-0.62.0/dist/extension.js:1:74175)
	at processImmediate (internal/timers.js:439:21)`

**Comment by snjeza** [comment]
@ganezdragon Could you try to define the following property:

```
"java.completion.favoriteStaticMembers": [
        "<your_package>.YourConstants.*", 
    ],
```

**Comment by ganezdragon** [comment]
@snjeza so I should do this for all the java projects I have? That doesn't seem right.

**Comment by snjeza** [comment]
@ganezdragon you can add this property to the user's settings.json.

**Comment by ganezdragon** [comment]
@snjeza okay.. but this will need change for each project. Can't vs code's language server look up automatically just like how intelij does?

**Comment by fbricon** [comment]
That behavior is derived from upstream Eclipse. We need to add the enhancement there 1st

**Comment by ganezdragon** [comment]
@fbricon  that is interesting. Do you know its repo? I can try to raise a issue there.

**Comment by fbricon** [comment]
@ganezdragon https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT

**Comment by ganezdragon** [comment]
Thank you.
