### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by Mike-the-one** [redhat-developer/vscode-java#1463]
I have a gradle project, with sub gradle projects.

The root gradle project I have the following

```sh
buildscript {	
	repositories {
    maven {
            url "https://plugins.gradle.org/m2/"
        }
    }

    dependencies {
	    classpath ("com.eriwen:gradle-js-plugin:2.14.1")
        classpath ("com.eriwen:gradle-css-plugin:2.14.0")

	}
}
```

and in sub gradle projects, I have the following:

```sh
apply plugin: 'js'
apply plugin: 'css'
```

It worked before build 0.61 (including 0.61).  After I upgrade to 0.62, it stopped working.

Error is 

```sh
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'.
Build file '/home/test/work/git/my-prohect/sub-project/build.gradle' line: 29
A problem occurred evaluating root project 'sub-project'.
Plugin with id 'js' not found.
```

After I rollback to 0.61, deleted .gradle folder and VScode user workspacgestorage, then the build worked.

##### Environment
- Operating System: Linux
- JDK version: 1.8
- Visual Studio Code version: 1.45.1
- Java extension version: 0.62

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

Build failed

##### Expected Result

Build should not fail

**Comment by snjeza** [comment]
@Mike-the-one do you use a gradle wrapper? If so, which version of the gradle wrapper you use?
See https://github.com/redhat-developer/vscode-java/wiki/Gradle-Support#suspicious-gradle-wrapper-detection-

**Comment by Mike-the-one** [comment]
@snjeza I use this:

> distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-bin.zip

Yes I remember I saw that message and I clicked trust, but still error

**Comment by Mike-the-one** [comment]
Searched in settings here is what I have:

![image](https://user-images.githubusercontent.com/37592183/82760309-aeca5a00-9dc0-11ea-8864-37e582d2e69d.png)


and json file:

![image](https://user-images.githubusercontent.com/37592183/82760329-c7d30b00-9dc0-11ea-9b0a-3bb58c6c9cce.png)

**Comment by snjeza** [comment]
@Mike-the-one could you send your settings.json, <your_project>/gradle/wrapper/gradle-wrapper.jar and <your_project>/gradle/wrapper/gradle-wrapper.properties?
You may want to take a look at https://github.com/eclipse/eclipse.jdt.ls/issues/1431#issuecomment-630896572?

**Comment by Mike-the-one** [comment]
@snjeza  here you go

[settings.json.zip](https://github.com/redhat-developer/vscode-java/files/4674098/settings.json.zip)
[wrapper.zip](https://github.com/redhat-developer/vscode-java/files/4674100/wrapper.zip)


This is another project also has the problem. This project was OK yesterday when I downgraded java plugin to 0.61, but it has the same problem today (still 0.61)

**Comment by pecko** [comment]
@Mike-the-one do you have something like the following in your build.gradle:

```
wrapper {
  ...
  jarFile = '<some_jar>'
}
```

**Comment by Mike-the-one** [comment]
@pecko No, I don't

**Comment by snjeza** [comment]
@Mike-the-one your gradle-wrapper.jar has the following sha256:
3dc39ad650d40f6c029bd8ff605c6d95865d657dbfdeacd, 5.5b079db0ddfffedf9f
It is official sha256 for the versions: 5.3, 5.4, 5.5 and 5.6. 
Could you try the following settings:
```
"java.import.gradle.version": "5.4.1",
"java.import.gradle.wrapper.enabled": false,
```

**Comment by Mike-the-one** [comment]
@snjeza I tried that, I don't get consistent result. 

0.61:
For a root project with more than 7 projects, one of the project won't build, same error as the pasted previously.
For a root project with less sub projects, it works

0.62:
Non worked,

then I tried to add jar in the build.wrapper file like this: (`jarFile` part)

```json
wrapper {
  gradleVersion = '5.4.1'
  jarFile = '.wrapper/gradle-wrapper.jar'
}
```

0.61 worked for all
0.62 didn't

**Comment by Mike-the-one** [comment]
This is the error with 0.62:

```sh
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.6.4-bin.zip'.
Build file '/home/user/work/git/root-project/sub-project/build.gradle' line: 23
A problem occurred evaluating root project 'sub-project'.
Plugin with id 'js' not found.
```

**Comment by Mike-the-one** [comment]
this is my .workspace file:

```json
{
  "folders": [
    {
      "path": "."
    }
  ],

  "settings": {
    //"java.home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home",
    "java.home": "/opt/jdk/jdk1.8.0_212",
    "java.configuration.updateBuildConfiguration": "automatic",
    "java.import.gradle.version": "5.6.4",
    "java.import.gradle.wrapper.enabled": false

    "files.watcherExclude": {
      "**/tomcatBase/**": true,
      "**/.git/**": true,
      "**/node_modules/*/**": true,
      "**/gradle/**": true,
      "**/bin/**": true,
      "**/build/**": true
    }
  }
}

```

**Comment by snjeza** [comment]
@Mike-the-one could you try the following:

- remove 
```
wrapper {
  gradleVersion = '5.4.1'
  jarFile = '.wrapper/gradle-wrapper.jar'
}
```
- set the following:
```
... 
"java.import.gradle.version": "4.10.2",
"java.import.gradle.wrapper.enabled": false
...

**Comment by Mike-the-one** [comment]
@snjeza 

It didn't work with 0.62.
It worked with 0.61.

**Comment by snjeza** [comment]
@Mike-the-one could you try the following:
- comment or remove

```
wrapper {
  gradleVersion = '5.4.1'
  jarFile = '.wrapper/gradle-wrapper.jar'
}
```
and
```
// "java.import.gradle.version": "4.10.2",
// "java.import.gradle.wrapper.enabled": false
```
- run
```
$ cd /home/user/work/git/root-project
$ ./gradlew wrapper --gradle-version 4.10.2 
$ ./gradlew wrapper build
$ cd sub-project
$ ./gradlew wrapper --gradle-version 4.10.2 
$ ./gradlew wrapper build
$ cd /home/user/work/git/root-project
$ code .
```

**Comment by Mike-the-one** [comment]
@snjeza  same error

**Comment by Mike-the-one** [comment]
hmm, not sure what happened, the error is back.  I am using 0.61, 

```sh
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.3-bin.zip'.
Build file '/home/beyond/work/git/root-project/sub-project/build.gradle' line: 23
A problem occurred evaluating root project 'sub-project'.
Plugin with id 'js' not found.
```

My workspace setting has this:

```sh
"java.import.gradle.version": "5.6.4",
    "java.import.gradle.wrapper.enabled": false,
```

and in my root build.gradle:

```sh
wrapper {
    gradleVersion = '5.6.4'
    jarFile = '.wrapper/gradle-wrapper.jar'
}
```

**Comment by snjeza** [comment]
@Mike-the-one Could you please remove the following:

```
wrapper {
    gradleVersion = '5.6.4'
    jarFile = '.wrapper/gradle-wrapper.jar'
}
```
See https://github.com/eclipse/buildship/issues/462

**Comment by Mike-the-one** [comment]
It did not work with 0.62, but worked with 0.61, this is the message:

```sh
Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-5.6.4-bin.zip'.
Build file '/home/user/work/git/root-project/sub-project/build.gradle' line: 23
A problem occurred evaluating root project 'sub-project'.
Plugin with id 'js' not found.
```

**Comment by Mike-the-one** [comment]
My setup was working for at least half year if not more, and I have not touched my build script for ages.  The problem started 2-3 days ago, so something changed in VS code, or the 0.62 of JLS, since 0.62 was released 3 days ago.

**Comment by snjeza** [comment]
> My setup was working for at least half year if not more, and I have not touched my build script for ages. The problem started 2-3 days ago, so something changed in VS code, or the 0.62 of JLS, since 0.62 was released 3 days ago.

@Mike-the-one 0.62 adds https://github.com/redhat-developer/vscode-java/wiki/Gradle-Support#suspicious-gradle-wrapper-detection-
Could you provide a project sample reproducing the issue?  (build.gradle, settings.gradle, gradlew, gradlew.bat, gradle/*).

**Comment by Mike-the-one** [comment]
@snjeza thanks. I will try to create one asap.

Also for the sha256, it checks the sha256 of jar file specified in the wrapper?

```sh
wrapper {
    gradleVersion = '5.6.4'
    jarFile = '.wrapper/gradle-wrapper.jar'
}
```
The sha256 of that file is 
`3dc39ad650d40f6c029bd8ff605c6d95865d657dbfdeacdb079db0ddfffedf9f`

and it is not in my User/settings.json, l will add that and try again.

**Comment by snjeza** [comment]
@Mike-the-one please remove the following:

```
wrapper {
    gradleVersion = '5.6.4'
    jarFile = '.wrapper/gradle-wrapper.jar'
}
```
buildship (and Java LS) doesn't support this settings.

> The sha256 of that file is
3dc39ad650d40f6c029bd8ff605c6d95865d657dbfdeacdb079db0ddfffedf9f
and it is not in my User/settings.json, l will add that and try again.

This sha256 is official gradle sha256 - https://services.gradle.org/distributions/gradle-5.6.4-wrapper.jar.sha256. You shouldn't add it.

**Comment by Mike-the-one** [comment]
yes, remove that doesn't help.  As soon as I install 0.62 I have issues

**Comment by jsaulou** [comment]
I also have an issue with the latest version and multi-project build.

It seems the extension is treating each subproject like a root project. Doing so, it doesn't use the Gradle wrapper for subprojects, and tries to use the default `gradle` command which is in the path (this is a very old version on my computer). Also, this breaks links between subprojects.

I think my issue is related to the one from @Mike-the-one. In his case, the plugin `js` can't be applied because his subproject is not evaluated as a subproject and thus the plugin `com.eriwen:gradle-js-plugin` is not declared as a dependency.

For now, I cannot use version `0.62.0`. Reverting to `0.61.0`, everything works back as normal.

**Comment by fbricon** [comment]
@jsaulou please provide a set of sample projects reproducing this issue. We'll hold off our planned release until this issue is fixed (cc @akaroml)

**Comment by jsaulou** [comment]
Ok I'll try to make one today.
Thanks for the quick feedback.

**Comment by jsaulou** [comment]
I created a very simple multi-project build ([vscode-java-bug-gradle.zip](https://github.com/redhat-developer/vscode-java/files/4716298/vscode-java-bug-gradle.zip)).


We can see the extension doesn't seem to be treating this as a multi-project build and is not using the Gradle wrapper for the subprojects.

In the problems panel, I get:

```
Support for builds using Gradle versions older than 2.6 was removed in tooling API version 5.0.
You are currently using Gradle version 2.1. You should upgrade your Gradle build to use Gradle 2.6 or later.
```

Gradle 2.1 is the version I have on my path and is not used anymore since Gradle wrapper is the way now :)

**Comment by snjeza** [comment]
I can reproduce the issue by setting GRADLE_HOME=<gradle_2.1>. It happens with VS Code 0.61.0 and 0.62.0.

@jsaulou could you try the following:

```
cd <your_project>
set GRADLE_HOME=
code .
```
You can also try to add the property to your VS Code settings.json:
```
"java.import.gradle.version": "6.4.1",
```

**Comment by jsaulou** [comment]
It's strange, it works fine for me with version 0.61.0. I think I need to run the `Clean the Java language server workspace` command after switching back to 0.61.0 for it to work properly.

Setting the `GRADLE_HOME` is not really a solution, the Gradle wrapper is the one setting the version.
The problem is that the root project does use the wrapper but the subprojects do not and use the default Gradle in PATH.

**Comment by snjeza** [comment]
> Setting the GRADLE_HOME is not really a solution, the Gradle wrapper is the one setting the version.
The problem is that the root project does use the wrapper but the subprojects do not and use the default Gradle in PATH.

@jsaulou you should unset GRADLE_HOME.

**Comment by snjeza** [comment]
@jsaulou @Mike-the-one could you check https://github.com/snjeza/vscode-test/raw/master/java-0.62.1.vsix

**Comment by Mike-the-one** [comment]
Thanks @snjeza 

It worked.

I was on 0.61.

1. Installed 0.62.1, worked.
2. Switched back to 0.62, failed.  
3. cleaned workspacestorage folder and .gradle folder, still failed.
4. switched to 0.62.1, failed
5.  cleaned workspacestorage folder and .gradle folder, worked,

Thanks

**Comment by jsaulou** [comment]
Thanks @snjeza.

First of all, sorry for the mix up with `GRADLE_HOME`, I didn't read that right, thought you expected to set `GRADLE_HOME`, my bad.

I tried 0.62.1 and now it builds correctly.

---

I still have an issue though regarding the time it takes compared to 0.61.0. This seems to be what is discussed in bug #1362 now even though I don't think it's related to large folders.

The extension now updates all subprojects and included projects (some are included using `includeBuild`) individually and not only the root project. This takes a long time.

![vscode-gradle-0 61 0](https://user-images.githubusercontent.com/40004761/83737031-c02e2480-a652-11ea-905f-553bd127762c.png)

Is there a reason for this? Is it now the expected behavior?

**Comment by snjeza** [comment]
> Is there a reason for this? Is it now the expected behavior?

@jsaulou could you check https://github.com/snjeza/vscode-test/raw/master/java-0.62.2.vsix

**Comment by jsaulou** [comment]
Just tested it and unfortunately I still have all projects being updated/refreshed.

I just noticed they are actually updated twice, not sure if it was the case in version 0.62.0.
This might have to do with using `includeBuild`, not sure.

**Comment by snjeza** [comment]
> Just tested it and unfortunately I still have all projects being updated/refreshed.

@jsaulou please check https://github.com/snjeza/vscode-test/raw/master/java-0.62.3.vsix

**Comment by jsaulou** [comment]
This worked for me.
Subprojects are not updated and the time seems to be comparable to version 0.61.0.

Thanks a lot @snjeza.

**Comment by Slay3r** [comment]
@snjeza I tested the 0.62.3.
I can confirm it's a lot better than 0.62.0.
It's comparable to 0.61.0.

Thank you for your efforts.

**Comment by a-st** [comment]
@snjeza I don't know what's the difference between your version (https://github.com/snjeza/vscode-test/raw/master/java-0.62.3.vsix) and the latest version I've tried from here https://download.jboss.org/jbosstools/jdt.ls/staging/ (which currently is java-0.62.0-2166.vsix), but both seem comparable

**Comment by snjeza** [comment]
> @snjeza I don't know what's the difference between your version (https://github.com/snjeza/vscode-test/raw/master/java-0.62.3.vsix) and the latest version I've tried from here https://download.jboss.org/jbosstools/jdt.ls/staging/ (which currently is java-0.62.0-2166.vsix), but both seem comparable

0.62.3 includes https://github.com/eclipse/eclipse.jdt.ls/pull/1467
