### ISSUE TITLE
Failed integrity check for Gradle wrapper yet wrapper is valid

### ISSUE THREAD

**Issue by sixlettervariables** [redhat-developer/vscode-java#1465]
I'm receiving a warning regarding the integrity of the Gradle Wrapper in our repos, stating that `e55e7e47a79e04c26363805b31e2f40b7a9cc89ea12113be7de750a3b2cede85` is not recognized. Reading https://gradle.org/release-checksums/ I find that is a valid sha256 for 4.9.

##### Environment
- Operating System: Windows 10
- JDK version: 8
- Visual Studio Code version: 1.46.0-insiders
- Java extension version: 0.9.1 (MS Java Pack)

##### Steps To Reproduce
1. Loaded MegaMek's main repo

##### Current Result
![image](https://user-images.githubusercontent.com/8238690/82827558-468d7e00-9e7d-11ea-8da1-149d68af94ce.png)

##### Expected Result
No warning as the SHA256 is valid.

**Comment by fbricon** [comment]
got a link to the repo?

**Comment by snjeza** [comment]
I can't reproduce the issue.
@sixlettervariables Could you enable Java LS tracing and attach the logs from the output view (Java Language server)?
See https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server

**Comment by sixlettervariables** [comment]
@fbricon https://github.com/MegaMek/megamek

@snjeza I'll work on that tonight, thanks for the link.

**Comment by sixlettervariables** [comment]
Sorry for the delay. After changing the log settings per @snjeza I restarted VSCode...which updated it, and now I don't have any issues.

New version:
```
Version: 1.46.0-insider (user setup)
Commit: b26e0bcf39c1b8faaf770265391b5a387d1d9172
Date: 2020-05-26T15:51:05.752Z
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362
```
