### ISSUE TITLE
java debug console code completion

### ISSUE THREAD

**Issue by jzdayz** [redhat-developer/vscode-java#1466]
[provide a description of the issue]

##### Environment
- Operating System: Mac os 10.15.4
- JDK version: 1.8
- Visual Studio Code version:  April 2020 (version 1.45)
- Java extension version: 0.9.1

##### Steps To Reproduce

please visit https://github.com/microsoft/vscode/issues/98468

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
The code completion on debug console is provided by the debugger. Could you open an issue there? https://github.com/microsoft/vscode-java-debug/issues

**Comment by jzdayz** [comment]
> The code completion on debug console is provided by the debugger. Could you open an issue there? https://github.com/microsoft/vscode-java-debug/issues

ok, i will do that
