### ISSUE TITLE
ERROR: transport error 202: bind failed: Address already in use when starting an debugging extension

### ISSUE THREAD

**Issue by HaoboGu** [redhat-developer/vscode-java#1468]
Hello, I am an extension developer, I am writing my own java extension, which depends on this vscode-java extension. When I started to debug my extension, I always receive the error information: 
> The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

Here is the log I found: 

![image](https://user-images.githubusercontent.com/8640918/82974752-4e7c2800-a00d-11ea-8e30-e5f3a4ec343a.png)

I think the language server started in the parent vscode window should not cause the server start failure in debugging vscode window. 

##### Environment
- Operating System: macOS
- JDK version: 1.8
- Visual Studio Code version: 1.45.1
- Java extension version: 0.62.0

##### Steps To Reproduce
1. Install redhat extension
2. Start my extension using "Run Extension"

**Comment by testforstephen** [comment]
In extension host mode, the java extension will auto enable debug mode. https://github.com/redhat-developer/vscode-java/blob/master/src/javaServerStarter.ts#L46-L48

The reason is probably that debug port is already occupied by other process.

**Comment by HaoboGu** [comment]
The error disappeared after I killed the process.

Thank you!

**Comment by AlbertMZhou** [comment]
> The error disappeared after I killed the process.
> 
> Thank you!

i meet the same issue, could you please teach me how to fix it? which process should i killed? which port is occupied? i dont find :(
