### ISSUE TITLE
Support envfile in launch.json

### ISSUE THREAD

**Issue by jahan01** [redhat-developer/vscode-java#1469]
Hello,

I searched for similar feature request opened previously but couldnt find any. 

I would like have support for specifying envfile in `launch.json` and the debugger session is started with those variables set. Basically I'm requesting for something that is already set in vscode-python extension ([see here](https://code.visualstudio.com/docs/python/debugging#_envfile))

I current use `env` and specify values there, I have large number of variables set, and its difficult for me debug when I try different group of variables. If this support is provided I can have `dev.env`, `test.env` and so on, I can easily switch between them

**Comment by fbricon** [comment]
Sorry this is out-of-scope of vscode-java. Everything problems/questions related to running/debugging your application should be opened in https://github.com/Microsoft/vscode-java-debug/issues
