### ISSUE TITLE
Extension not updating Maven dependency versions 

### ISSUE THREAD

**Issue by aaronkavlie-wf** [redhat-developer/vscode-java#147]
When upgrading a library that makes breaking changes (in a `pom.xml` for a Maven project), the editor does not seem to have awareness of the version change — even if you manually trigger the "Update project configuration" command.

For instance, if an import is no longer available in the new version, an error to the effect that "The import cannot be resolved" is expected (IntelliJ does this). However, the editor still treats it as a valid import.

##### Environment
- Operating System: Mac OS X 10.11.6
- JDK version: 8
- Visual Studio Code version: 1.8.1
- Java extension version: 0.0.9

##### Steps To Reproduce
1. Do a major version upgrade to a dependency that has removed an import present in your project
2. Trigger "Update project configuration"
3. Observe that no error shows for the invalid import

**Comment by fbricon** [comment]
Well, it works for me: 
![update-classpath](https://cloud.githubusercontent.com/assets/148698/22561777/bca6e2a0-e947-11e6-95de-c7cee447851f.gif)

The project in the screencast has "java.configuration.updateBuildConfiguration": "automatic" but that should be inconsequential.

**Comment by aaronkavlie-wf** [comment]
Thanks for the example. I cannot share the code base where I encountered this.
If I can reproduce in a repeatable way I may reopen in the future, otherwise disregard.
