### ISSUE TITLE
Allow devs to override default snippets

### ISSUE THREAD

**Issue by JasonWThompson** [redhat-developer/vscode-java#1470]
When I create a new java file, I'm able to immediately select if I want to create a class, interface, or enum. However, there does not seem to be a way to configure what said generated type looks like. Specifically for the team I work on, there's an expectation that a certain file header comment appears at the top and specific boiler plate javadoc appears before each type.

Because this isn't possible in VSCode, I often forget to put these in there manually and thus receive embarrassing comments on my code reviews about forgetting these things. 😅

In Eclipse, I could configure the template for types and files by going to Preferences->Java->Code Style->Code Templates and control what is generated. This is what I want. (This is different from Preferences->Java->Editor->Templates which is closer to VSCode snippets).

##### Environment
- Operating System: Windows 10
- JDK version: JDK 11
- Visual Studio Code version: 1.45.1
- Java extension version: 0.62.0

**Comment by wangchengxin** [comment]
I also want to make this suggestion, it is particularly inconvenient to use other "header" plugins, I hope developers add this feature

**Comment by fbricon** [comment]
* `java.templates.fileHeader`: Specifies the file header comment for new Java file. Supports configuring multi-line comments with an array of strings, and using ${variable} to reference the [predefined variables](https://github.com/redhat-developer/vscode-java/wiki/Predefined-Variables-for-Java-Template-Snippets).

* `java.templates.typeComment`: Specifies the type comment for new Java type. Supports configuring multi-line comments with an array of strings, and using ${variable} to reference the [predefined variables](https://github.com/redhat-developer/vscode-java/wiki/Predefined-Variables-for-Java-Template-Snippets).

Predefined variables:
- `${file_name}` - name of the current Java file
- `${package_name}` - name of the enclosing package
- `${type_name}` - name of the current type
- `${user}` - current user system login name
- `${date}` - current system date
- `${time}` - current system time
- `${year}` - current year
- `${month}` - current month
- `${day}` - current day of the month
- `${hour}` - current hour
- `${minute}` - current minute

**Comment by fbricon** [comment]
For instance, you can define a copyright header like:
```json
"java.templates.fileHeader": [
  "/**",
  "*  Copyright (c) ${year} Red Hat, Inc.",
  "*  All rights reserved. This program and the accompanying materials",
  "*  are made available under the terms of the Eclipse Public License v2.0",
  "*  which accompanies this distribution, and is available at",
  "*  http://www.eclipse.org/legal/epl-v20.html",
  "*",
  "* SPDX-License-Identifier: EPL-2.0",
  "*/"
],
```

and a new type Javadoc like:
```json 
"java.templates.typeComment": [
  "/**",
  "* ${type_name}",
  "* @author: ${user}",
  "*/"
]
```
