### ISSUE TITLE
Organize import on save should not add fulfilled packages

### ISSUE THREAD

**Issue by JasonWThompson** [redhat-developer/vscode-java#1472]
If I have static favorites configured that have classes with the same name (as is the case with things like Hamcrest and Mocikto), then when I save the IDE adds in a bunch of imports making my types ambiguous.

##### Environment
- Operating System: Windows 10
- JDK version: Adapt OpenJDK 11
- Visual Studio Code version: 1.45.1
- Java extension version: 0.62.0

##### Steps To Reproduce
1. Edit user settings for favorite static members.
2. Add in the following favorites:
```
        "org.junit.jupiter.api.Assertions.*",
        "org.junit.jupiter.api.Assumptions.*",
        "org.junit.jupiter.api.DynamicContainer.*",
        "org.junit.jupiter.api.DynamicTest.*",
        "org.hamcrest.MatcherAssert.*",
        "org.hamcrest.Matchers.*",
        "org.mockito.Mockito.*",
        "org.mockito.ArgumentMatchers.*",
        "org.mockito.Answers.*",
        "org.mockito.hamcrest.MockitoHamcrest.*",
        "org.mockito.Matchers.*"
```
3. Write some code that statically includes methods that have the same name in multiple classes such as `assertThat` and `any`.
4. Organize imports

##### Current Result
Other imports are added to the file making the static includes ambiguous.

##### Expected Result
Fulfilled static imports are not resolved further.

**Comment by fbricon** [comment]
can you provide a standalone project reproducing this issue?

**Comment by JasonWThompson** [comment]
I'll try mocking up something soon and posting it here.
