### ISSUE TITLE
[Feature request] Add getCompletionItems to extensionAPI

### ISSUE THREAD

**Issue by HaoboGu** [redhat-developer/vscode-java#1474]
Hello, 

I am an extension developer, I am writing a code auto-completion extension for Java. 

vscode-java is a great extension which provides amazing completion results. But those result cannot be used by other extensions. 

Can you please add getCompletionItems API so that other extensions can use it for providing better completion service?

Or, is there any way to contribute this feature? 

Thanks if you can help!

**Comment by fbricon** [comment]
Can you explain your use case in more details?

**Comment by HaoboGu** [comment]
> Can you explain your use case in more details?

I am writing an auto-complete extension. The extension would generate some completionItems, I want to re-rank my list by combining with the result given by your extension. Besides, I also want to enrich the documentation of my list using the doc/detail field of the result from your extension.

**Comment by fbricon** [comment]
Would your autocompletion be triggered inside java files? My concern is potential conflicts between several java completion invocations

**Comment by HaoboGu** [comment]
> Would your autocompletion be triggered inside java files? 

Yes

> My concern is potential conflicts between several java completion invocations

I will remove the duplicate results from my list. And VSCode would do the merging of results from multiple extensions, I think it's not a risk.

**Comment by fbricon** [comment]
I don't understand, why do you want to have the same completion triggered twice for Java files, only to filter out the second set of results?

**Comment by fbricon** [comment]
my point is Java completion requests are pretty expensive. Doing it twice will certainly result in a much degraded UX

**Comment by HaoboGu** [comment]
> I don't understand, why do you want to have the same completion triggered twice for Java files, only to filter out the second set of results?

It's not only to do filtering, the result also helps to enhance and rerank my list, which is different from the list from your extension. 

For example, if there are two results from my extension with leading `re`:
```
1. reader.Close();
2. return null;
```
And, if I found in your list, `reader` exists but `return` not, I would give `reader.Close()` a higher rank.

The results from my extension will have no effect on vscode-java's result. 

What's more, if we can request once and then do both things(I mean showing the raw results in vscode and pass them to my extension), it would be great!
