### ISSUE TITLE
Syntax error with Java 14 records

### ISSUE THREAD

**Issue by pascalpoizat** [redhat-developer/vscode-java#1475]
I get a syntax error when using Java 14 records, while all is OK when I build & run the project in the CLI using gradle.

##### Environment
- Operating System: macOS Mojave 10.14.6
- JDK version: 14.0.1 2020-04-14
- Visual Studio Code version: 1.45.1
- Java extension version: Java extension pack 0.9.1, language support for Java 0.62.0

##### Steps To Reproduce
1. git clone https://github.com/pascalpoizat/previews
2. cd previews
3. open . -a Visual\ Studio\ Code
4. open file src/main/java/App.java or src/main/java/Person.java

Sample project is at: https://github.com/pascalpoizat/previews

Screenshots of the error(s), together with logs can be found at : https://github.com/pascalpoizat/previews/tree/master/ERROR

##### Current Result

Syntax error on the ```record``` keyword.

```
Syntax error on token "record", record expectedJava(1610612940)
```

##### Expected Result

No error, the project builds.

##### Additional Informations

- my settings.json file is also in https://github.com/pascalpoizat/previews/tree/master/ERROR.
- there ```java.home``` points to JDK 14
- my build.gradle file includes arguments relative to Java 14 new features, see https://github.com/pascalpoizat/previews/blob/master/build.gradle

**Comment by snjeza** [comment]
@pascalpoizat could you try the following patch:

```
diff --git a/build.gradle b/build.gradle
index 3da2620..1e84d6b 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,6 +1,7 @@
 plugins {
     id 'java'
     id 'application'
+    id 'eclipse'
 }
 
 repositories {
@@ -27,5 +28,11 @@ tasks.withType(JavaExec) {
 }
 
 test {
+    jvmArgs '--enable-preview'
     useTestNG()
 }
+
+eclipse.jdt.file.withProperties { props ->
+    props['org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures']= 'enabled'
+    props['org.eclipse.jdt.core.compiler.problem.reportPreviewFeatures']= 'ignore'
+}
```
and run the following command:
```
$ ./gradlew eclipseJdt 
```
See https://github.com/redhat-developer/vscode-java/issues/671#issuecomment-477379761

**Comment by fbricon** [comment]
Instructions to enable Preview features are available in the wiki: https://github.com/redhat-developer/vscode-java/wiki/Enabling-Java-preview-features

**Comment by pascalpoizat** [comment]
Thanks you @snjeza. I tried it. Same issue.

**Comment by pascalpoizat** [comment]
Thank you @fbricon. I added this:

```
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-14",
            "path": "/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home",
            "default": true
         }
     ],
```

(I already had this, I thought it was enough:

```
    "java.home": "/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home",
```
)

I also updated the ```build.gradle``` file as required (@snjeza also had some of the changes).
It works (still) perfectly in the shell (I had to add:

```
tasks.withType(JavaExec) {
    jvmArgs += "--enable-preview"
}
```

still).

But same error in the IDE (as first I have no error, then after some time I have the error).
I will try removing the thing I have in addition (application and java plugins, TestNG, etc).

**Comment by pascalpoizat** [comment]
Note : I have no JAVA_HOME nor JDK_HOME set up. From the doc I though 'java.home' is sufficient but I will try to add these also.

**Comment by snjeza** [comment]
@pascalpoizat have you executed './gradlew eclipseJdt'?

![jdk14](https://user-images.githubusercontent.com/388609/83188998-d6a71e00-a130-11ea-9740-61b0f60b6151.png)

**Comment by pascalpoizat** [comment]
Shame on me :-(
Sorry, no (I used my usual workflow, in the shell, ./gradlew build or run, only).
I did now run ```./gradlew eclipseJdt``` in the shell, then opened VSCode and ... it no more error :-)
Thanks a lot for your help (and patience) !
I will try tomorrow with a bigger project where I originally had the issue.

**Comment by pascalpoizat** [comment]
@snjeza @fbricon thank you for your help. It works on my bigger project.
Here is the "minimal" ```build.gradle``` I could come up with.
Plus the mandatory run of ```./gradlew eclipseJdt``` of course.

```gradle
plugins {
    id 'java'
    id 'application'
    id 'eclipse'
}

sourceCompatibility = JavaVersion.VERSION_14

repositories {
    jcenter()
}

dependencies {
    testImplementation 'org.testng:testng:6.14.3'
}

application {
    mainClassName = 'previews.App'
}

tasks.withType(JavaCompile) {
    options.compilerArgs += '--enable-preview'
}
tasks.withType(Test) {
    jvmArgs += "--enable-preview"
}
tasks.withType(JavaExec) {
    jvmArgs += "--enable-preview"
}

eclipse.jdt.file.withProperties { props ->
    props['org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures']= 'enabled'
    props['org.eclipse.jdt.core.compiler.problem.reportPreviewFeatures']= 'ignore'
}

test {
    useTestNG()
}
```
