### ISSUE TITLE
Setting the JDK on remote is not possible

### ISSUE THREAD

**Issue by kusnier** [redhat-developer/vscode-java#1479]
As described under https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#java.configuration.runtimes the runtime for the remote can not be set up over this way.

This option is ignored on the remote machine. Vscode is showing the following message:

![image](https://user-images.githubusercontent.com/726429/83487443-53c4f100-a4ab-11ea-8e22-cdee6d2674ff.png)

**Comment by fbricon** [comment]
The setting uses scope:"machine"

<img width="630" alt="Screen Shot 2020-06-02 at 1 33 42 PM" src="https://user-images.githubusercontent.com/148698/83515541-d662a600-a4d5-11ea-86bb-e67da08dfd08.png">

So I don't know why it doesn't work. @jdneo @testforstephen @Eskibear any idea?

**Comment by kusnier** [comment]
I have it. This has to be configured on the remote machine. Then is works.

![image](https://user-images.githubusercontent.com/726429/83520056-58a29880-a4dd-11ea-9705-4cbe1a7c5327.png)
