### ISSUE TITLE
Option to remove "References" inline option

### ISSUE THREAD

**Issue by mooman219** [redhat-developer/vscode-java#148]
![image](https://cloud.githubusercontent.com/assets/865769/22558569/24398e7e-e93c-11e6-8cc8-0614cf52fa43.png)

The "references" option inline is rather cumbersome when editing, could there be an option to not display it?

**Comment by fbricon** [comment]
Yes I think it's doable...but a bit tricky

We've been discussing about not displaying the `0 references` label as it's completely useless, but we realized it would require eagerly computing all references early, which would kill performance. We haven't found a good

**Comment by mooman219** [comment]
Thanks for the quick response. Would it be realistic to have an option to disable showing CodeLenses altogether in the mean time? There's already the option to view references on demand.

**Comment by fbricon** [comment]
@mooman219 yeah I think so, it's pretty straightforward to implement, but I want to discuss with @gorkem first, before introducing new preferences that might get deprecated soon

**Comment by gorkem** [comment]
The new [register/unregisterCapability](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#client_registerCapability) calls will allow us to have a cleaner solution but for now receiving a single call per file should not be a problem. I think we can use 
`java.referencesCodeLens.enabled` to align with typescript.

**Comment by fbricon** [comment]
There: 
![disabling-reference-codelenses](https://cloud.githubusercontent.com/assets/148698/22663622/4f2b3b04-ec7b-11e6-9028-54b46684233d.gif)

**Comment by fbricon** [comment]
@gorkem since vscode has typescript reference codelenses disabled by default, should vscode-java do the same, to stay consistent?

**Comment by ErEllison** [comment]
i was using vs code for unity at the moment and i disabled it by 
`"csharp.referencesCodeLens.enabled": false`
in my workspace setting

**Comment by aaronfranke** [comment]
Also `"editor.codeLens"` can be set to `false`.

**Comment by SuryaDev-chaturvedi** [comment]
Just open Visual Studio.
Go in Tools > Environment > Text editor > Codelens.
and then disable them .
[](https://youtu.be/XHI3_dfYFtY)
I got solution from this video .
Hope it helps You too :)

**Comment by SuryaDev-chaturvedi** [comment]
Just open Visual Studio.
Go in Tools > Environment > Text editor > Codelens.
and then disable them .

[https://youtu.be/XHI3_dfYFtY](url)
I got solution from this video .
Hope it helps You too :)

**Comment by Khoa-NT** [comment]
Go to settings > Text Editor > Code Lens 
Uncheck it

**Comment by LWChris** [comment]
> Just open Visual Studio. Go in Tools > Environment > Text editor > Codelens. and then disable them.

I think you missed that this is about "Visual Studio Code" (the text editor) and not "Visual Studio" (the IDE). 😊
