### ISSUE TITLE
dead code tips error

### ISSUE THREAD

**Issue by idlesysman** [redhat-developer/vscode-java#1485]
[provide a description of the issue]

##### Environment
- Operating System:win10
- JDK version:jdk 11
- Visual Studio Code version:1.45.1
- Java extension version:Language Support for Java(TM) by Red Hat redhat.java 0.62.0

##### Steps To Reproduce
1. [step 1]
```
 String xm1="abc",xm2="bcd";

 String[] xm1CharPy=.....
 String[] xm2CharPy=...
 if ((xm1CharPy == null || xm2CharPy != null)
	|| (xm1CharPy != null || xm2CharPy == null)
	|| (xm1CharPy == null || xm2CharPy == null)
) {
    if(ObjectUtils.compare(xm1.charAt(i),xm2.charAt(i))!=0){
	return false;
    }else{
	continue;
    }
}
// balabala

```
2. [step 2]
will tips "Dead code Java(536871061)"

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Dead code Java(536871061)
##### Expected Result
while xm1CharPy!=null && xm2CharPy!=null
not Dead code

**Comment by fbricon** [comment]
Where is the dead code warning? 
Can't reproduce with this snippet. Please provide a fully functional sample of code.

**Comment by idlesysman** [comment]
```java
public static Boolean testLogic(){
		String xm1="张三",xm2="李四";
		for (int i = 0; i < xm1.length(); i++) {     
                String[] xm1CharPy =new String[]{"abc"};
                String[] xm2CharPy = new String[]{"bac"};
                if ((xm1CharPy == null || xm2CharPy != null)
                        || (xm1CharPy != null || xm2CharPy == null)
                        || (xm1CharPy == null || xm2CharPy == null)
                ) {
                    if(xm1.charAt(i)!=xm2.charAt(i)){
                        return false;
                    }else{
                        continue;
                    }
                }
                for (String xm1CharMSoundsPy : xm1CharPy) {
                    boolean hasFound = false;
                    for (String xm2CharMSoundsPy : xm2CharPy) {
                        if (xm1CharMSoundsPy.equals(xm2CharMSoundsPy)) {
                            hasFound = true;
                            continue;
                        }
                    }
                    if (!hasFound) {
                        return false;
                    }
                }
		}
		return true;
	}
```

**Comment by idlesysman** [comment]
![screenshot](https://github.com/idlesysman/java/blob/master/resources/0.png?raw=true)

**Comment by jdneo** [comment]
@idlesysman You can simply add a `sysout` before your for loop to see if the code reached or not.

```java
System.out.println("is dead code?");
for (String xm1CharMSoundsPy : xm1CharPy) {
    ...
}
```

and you will see there is no output in the console.

**Comment by fbricon** [comment]
The dead code warning is legit. Basically, you always enter in the if block (whether both arrays are null -which is impossible- or one of them is non-null, which is always true), which then has 2 branches ending the loop, so you never reach the inner loop. 
You should fix the logic in your if 1st if block.
