### ISSUE TITLE
what is the preferred way to launch the java app?

### ISSUE THREAD

**Issue by martinlippert** [redhat-developer/vscode-java#149]
(this is more a question than an issue report)
What is the preferred way to launch the Java app in VS Code with the JDT language server in place? Via the tasks mechanism, for example executing the maven run command? Or is there a better way (also to avoid extra builds)?

Thanks a lot for your help!!!

**Comment by fbricon** [comment]
The (suboptimal) way vscode is currently following is:
- have vscode-java and java-language-server (JLS) checked out under the same parent directory
- hack JLS
- [run `npm run-script build-server` from CLI in the vscode-java directory](https://github.com/redhat-developer/vscode-java/blob/master/CONTRIBUTING.md#building-java-language-server). Takes about 35sec or less, dependending on your machine
- (re) [launch the vscode-java extension from vscode](https://code.visualstudio.com/Docs/extensions/debugging-extensions#_running-and-debugging-your-extension)

We have yet to implement a better way to work between the 2 projects, to eliminate the intermediary JLS build. We discussed some options but haven't settled on one yet

**Comment by martinlippert** [comment]
Hey Fred,

not asking about the language server itself, just a regular Java app that you are hacking on USING the Java language support in VSCode... Not the language support itself... :-)

**Comment by fbricon** [comment]
Sorry my bad, it's too early :-)

Well I guess it's a matter of personal preferences. Either defining commands in a tasks.json file or running from CLI. We have no recommendations at this point. Either way, chances are you'll end up running Maven (or Gradle) commands.

**Comment by gorkem** [comment]
@martinlippert I think we will have a better recommendation after we do our homework for the debug support. At this time, my recommendation is using mvn/gradle commands from tasks.json. This works really well especially if you are working with a framework that can pickup the changes and auto-deploy.

**Comment by martinlippert** [comment]
Ok, thanks for the advice and the details about the status quo. Much appreciated.
