### ISSUE TITLE
[JAVA] can't find reference when java build status finished 

### ISSUE THREAD

**Issue by tcsecchen** [redhat-developer/vscode-java#1490]
[provide a description of the issue]

##### Environment
- Operating System: Win10
- JDK version: jdk 1.8.0_181
- Visual Studio Code version: latest
- Java extension version: 0.6.2

##### Steps To Reproduce
1. when i start vscode , i can find the reference by F12
2. But when the java build status shows complete, i presh F12 but it tell me can't find reference
the problem:
![图片](https://user-images.githubusercontent.com/25191604/84190727-f98ae800-aac9-11ea-8ad4-cc3526dca2e3.png)

how can i resolve this problem , tks

**Comment by testforstephen** [comment]
Did you observe this exception in other project? or just this project?

**Comment by tcsecchen** [comment]
一些项目是正常的，有一些就不正常
刚开始打开F12可以找到引用，但是当它自动build完成以后，就会提示找不到符号

**Comment by tcsecchen** [comment]
> 
> 
> Did you observe this exception in other project? or just this project?

一些项目是正常的，有一些就不正常
刚开始打开F12可以找到引用，但是当它自动build完成以后，就会提示找不到符号

**Comment by testforstephen** [comment]
Could you mind sharing the project you observe the exception?

**Comment by tcsecchen** [comment]
> Could you mind sharing the project you observe the exception?

https://github.com/alibaba/fastjson
1.git clone https://github.com/alibaba/fastjson
2.use vscode to open the "fastjson" folder
3.before the build finish, use F12 can find Reference
4.after the build finish, use F12 can't find Reference

**Comment by testforstephen** [comment]
I played the sample project, i didn't observe any exception for Go to References feature. See the screenshot below, it runs after the build finished.

![image](https://user-images.githubusercontent.com/14052197/85197946-1a97d800-b317-11ea-9cb9-e47b128b1517.png)

If you keep getting the failure, maybe you can try to **F1 -> Java: Clean the Java language server workspace**.

**Comment by tcsecchen** [comment]
> 
> 
> I played the sample project, i didn't observe any exception for Go to References feature. See the screenshot below, it runs after the build finished.
> 
> ![image](https://user-images.githubusercontent.com/14052197/85197946-1a97d800-b317-11ea-9cb9-e47b128b1517.png)
> 
> If you keep getting the failure, maybe you can try to **F1 -> Java: Clean the Java language server workspace**.

ok! thanks!
