### ISSUE TITLE
Extension not finding jar files

### ISSUE THREAD

**Issue by erjdriver** [redhat-developer/vscode-java#1491]
When I open my java workspace in vscode - some packages are not found.

`import org.apache.http.StatusLine;` - `org.apache.http` is high-lighted in squiggly red lines with "cannot be resolved" message.

I assume the jar file is not being found.

I went into the extension settings and set the referencedlibraries under User.

```
    "java.project.referencedLibraries": [
        "/Users/mini/git/httpcore-4.4.3.jar"
    ],
```

Not sure whether this is the correct way.

The above was under User. If I do it under workspace - it gets overrridden to blank.

I'm trying to tell vscode-java extension where the jar file is to resolve that package import.

Any help appreciated.

**Comment by testforstephen** [comment]
What kind of Java project are you using? Maven? Gradle? or Standalone Java files?

**Comment by erjdriver** [comment]
It's a plain java project.

I've got 'Run on Save' and 'RedHat Support for Java' extensions loaded - parts of it.

Also Visual Studio Intellicode - which I think is part of the RedHat package.

I think the squiggly lines in the editor is coming from the VS Intellicode - but looking at the extension settings - there doesn't seem to be a way to tell it where the libs are.

The referencedLibraries settings where for Language Support Java settings.

It seems to save it only for the User tab - if I save for Workspace - it's not set when I reopen it.

**Comment by testforstephen** [comment]
`referencedLibraries` setting is only applicable to a very restricted scenario, and it only works when you opened standalone Java files. If your workspace contains any explicit projects such as Eclipse, Maven, Gradle, this setting won't work.

Could you share a screenshot about your workspace structure?

**Comment by erjdriver** [comment]
It's as follows:

workspace (folder containing all the jar files)
   project1 (containing the java files)
      bin (containing the class files)
   project2
      bin

I'm not using gradle, maven etc...but in Language Support for Java extension settings - there's some settings specific to them.
![Screen-shot 2020-06-20 at 8 26 24 PM](https://user-images.githubusercontent.com/1229041/85214057-5d1bdd80-b334-11ea-82b6-9fa05ae17f06.png)

Here's the error i'm getting in vscode.

![Screen-shot 2020-06-20 at 8 27 42 PM](https://user-images.githubusercontent.com/1229041/85214078-8f2d3f80-b334-11ea-8dab-0f08fc144b02.png)

**Comment by testforstephen** [comment]
> I'm not using gradle, maven etc...but in Language Support for Java extension settings - there's some settings specific to them.

It doesn't matter.

Are there any explicit .project/.classpath files in your current workspace directory?

**Comment by erjdriver** [comment]
Neither in the workspace folder root/parent folder

But in the projects sub-folders - there are...I added the libs to the sub-folder `.classpath` file and everything worked!

Thanks!

Should these files be in the workspace root/parent folder or in the project sub-folders?
