### ISSUE TITLE
The java.home variable defined in Visual Studio Code settings points to a missing or inaccessible folder (C:\Users\username\AppData\Local\Programs\AdoptOpenJDK) (WSL)

### ISSUE THREAD

**Issue by nduchuyvp123** [redhat-developer/vscode-java#1493]
When I open VSCode in WSL, it show this notification. Nothing happen when I open VSCode in Windows. I have define JAVA_HOME and JDK_HOME in system varibles. Then define the path of jdk-11/bin in the system path. The problem is VSCode in WSL use the same 'setting.json' as VSCode in Windows. 

##### Environment
- Operating System: Windows 10 Education Version 2004 OS Build 19640.1
- Local JDK version: AdoptOpenJDK 11
- Visual Studio Code version: 1.46.0
- Java extension version: 0.8.1

##### Steps To Reproduce
1. Add remote WSL: Ubuntu-20.04 distro
2. Install JDK for WSL with ```apt install jdk-11-openjdk```
3. Now install Java Extension Pack for WSL
4. When opening the Java Source Code (Maven) then pop up opening that "The java.home variable defined in Visual Studio Code settings points to a missing or inaccessible folder (C:\Users\username\AppData\Local\Programs\AdoptOpenJDK)"

Error Screen when I try to open VSCode in WSL: Ubuntu (https://imgur.com/mbnwBqT)
Nothing happen when I open VSCode in Windows.
![SharedScreenshot](https://user-images.githubusercontent.com/61613859/84667048-084f2000-af4c-11ea-9496-44a0f4b6fb8f.jpg)

Here is my 'setting.json'
{

<pre>&quot;java.home&quot;: &quot;C:\\Users\\Huy\\AppData\\Local\\Programs\\AdoptOpenJDK&quot;,

&quot;java.help.firstView&quot;: &quot;gettingStarted&quot;,

&quot;editor.suggestSelection&quot;: &quot;first&quot;,

&quot;files.exclude&quot;: {

&quot;\*\*/.classpath&quot;: true,

&quot;\*\*/.project&quot;: true,

&quot;\*\*/.settings&quot;: true,

&quot;\*\*/.factorypath&quot;: true

},

&quot;[java]&quot;: {

&quot;editor.defaultFormatter&quot;: &quot;redhat.java&quot;

},

&quot;java.refactor.renameFromFileExplorer&quot;: &quot;autoApply&quot;, </pre>

}

**Comment by testforstephen** [comment]
"java.home" is a path related with your local machine, it cannot be shared between windows and ubuntu, please set different java.home for different machine. 

Also, "C:\\Users\\Huy\\AppData\\Local\\Programs\\AdoptOpenJDK" is not a complete JDK path, a valid sample is ike  C:\\Users\\Huy\\AppData\\Local\\Programs\\AdoptOpenJDK\\**jdk-11-openjdk**.

**Comment by Eskibear** [comment]
> C:\Users\Huy\AppData\Local\Programs\AdoptOpenJDK
@testforstephen above path is valid (on Windows only), which is the default AdoptOpenJDK installation folder in vscode java installer. The problem is, `java.home` should not be shared accross machines (E.g. Windows & WSL). 
If I remember correctly, we proposed to change [scope of setting](https://github.com/redhat-developer/vscode-java/blob/26c90466c6ebe25048ec5d740671aabd0c6d7270/package.json#L63-L70) `java.home` to "machine" before, and that's exactly for such cases.

@nduchuyvp123 In WSL, you may try removing `java.home` from your settings. After that, `/usr/lib/jvm/java-14-openjdk-amd64` will take effect automatically.

**Comment by Eskibear** [comment]
See: 
- spec of `machine-overridable`: https://code.visualstudio.com/api/references/contribution-points  
- original discussion: https://github.com/microsoft/vscode/issues/73985#issuecomment-522013185

**Comment by nduchuyvp123** [comment]
> > C:\Users\Huy\AppData\Local\Programs\AdoptOpenJDK
> 
> @testforstephen above path is valid (on Windows only), which is the default AdoptOpenJDK installation folder in vscode java installer. The problem is, `java.home` should not be shared accross machines (E.g. Windows & WSL).
> If I remember correctly, we proposed to change [scope of setting](https://github.com/redhat-developer/vscode-java/blob/26c90466c6ebe25048ec5d740671aabd0c6d7270/package.json#L63-L70) `java.home` to "machine" before, and that's exactly for such cases.
> 
> @nduchuyvp123 In WSL, you may try removing `java.home` from your settings. After that, `/usr/lib/jvm/java-14-openjdk-amd64` will take effect automatically.

Thanks for your attention.Windows and WSL use the same 'setting.json', so I remove 'java.home' in setting.json that I remove 'java.home' in both

**Comment by testforstephen** [comment]
> If I remember correctly, we proposed to change scope of setting java.home to "machine" before, and that's exactly for such cases.

@Eskibear Agree, we need change it to machine scope. Regarding the remote scenario becomes popular, global `java.home` setting is a big pain.


@nduchuyvp123 You can use the workspace user setting `.vscode/settings.json` to define a different `java.home`.

**Comment by nduchuyvp123** [comment]
I removed line <br> "java.home": "C:\\Users\\Huy\\AppData\\Local\\Programs\\AdoptOpenJDK", </br> in my 'setting.json' so the notice is not appear again. After I remove it, I can complie java file normally. I don't know what "java.home" actually is.
