### ISSUE TITLE
Unprocessed markdown in settings

### ISSUE THREAD

**Issue by astrelsky** [redhat-developer/vscode-java#1498]
I've removed most of the template as it isn't relevant. I'm not certain if this is due to a setting on my end or if this was an oversight when writing the descriptions for the plugin settings.

![Capture](https://user-images.githubusercontent.com/46897303/85136813-32d00000-b20e-11ea-84d3-91f930fe45bb.PNG)

##### Environment
- Operating System: Microsoft Windows [Version 10.0.19041.329]
- JDK version: 14.0.1
- Visual Studio Code version: 1.47.0-insider 8cd3fe080bee38d28ba01d0d71713d6ec22b254e
- Java extension version: 0.63.0

**Comment by astrelsky** [comment]
@fbricon Thank you!

**Comment by fbricon** [comment]
Fixed in 6129734 by using markdownDescription instead of description:
<img width="453" alt="Screen Shot 2020-06-19 at 4 47 59 PM" src="https://user-images.githubusercontent.com/148698/85145293-a98bee00-b24c-11ea-8dce-72f5ec017ebc.png">
