### ISSUE TITLE
Scroll terminal window console logs using arrow keyboard keys when focus change from command to terminal log.

### ISSUE THREAD

**Issue by subhashvaishnav** [redhat-developer/vscode-java#1500]
[provide a description of the issue]

##### Environment
- Operating System: windows
- JDK version: 8
- Visual Studio Code version: 1.46
- Java extension version:

##### Steps To Reproduce
1. Run code 
2. Try to moniter terminal consol logs

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
The rendering of the terminal logs are controlled by VS Code, could you please open an issue to the upstream VS Code repo? https://github.com/microsoft/vscode/issues
