### ISSUE TITLE
JRE version being overriden

### ISSUE THREAD

**Issue by ViniciusAtaide** [redhat-developer/vscode-java#151]
When I come from eclipse I always have to change my version of java from 1.5 to 1.6 in the .workspace file, that triggers a rebuild phase in my eclipse IDE, I would like to ditch eclipse completely but my work uses some hidden depedencies inside JBoss to Eclipse so I can't work without it.

##### Environment
- Operating System: Windows 7
- JDK version: 1.8
- Visual Studio Code version: 1.9
- Java extension version: lastest

##### Steps To Reproduce
1. Open Project that has JRE 1.6 inside workspace folder
2. Navigate to a file
3. open workspace file

##### Additional Informations
Maybe that could be another hidden dependency in my maven/gradle since the project uses both but I can't find inside pom since the file is too big.

**Comment by fbricon** [comment]
Which one are you using: Maven or Gradle?
If using Maven, make sure your maven-compiler-plugin is configured to use the proper [source/target settings](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html).

For Gradle, you need to perform [similar configuration](http://mrhaki.blogspot.ca/2010/11/gradle-goodness-set-java-version.html)

**Comment by ViniciusAtaide** [comment]
Oh that's why, the project is configured for maven in eclipse, which has version 1.6, and gradle has 1.5. Didn't know that gradle would override, I just updated the version from gradle and now it works.

**Comment by fbricon** [comment]
Ok, closing then.
