### ISSUE TITLE
Auto completion support for gradle multi-project builds

### ISSUE THREAD

**Issue by RDIL** [redhat-developer/vscode-java#1511]
Right now, if you are working on a subproject in VSCode with gradle, autocompletion in the Java source for the specific dependencies that are for that sub project only, not the root project.  This would be extremely helpful.

**Comment by fbricon** [comment]
Can you provide a set of sample projects and step by step instructions to reproduce this problem?

**Comment by RDIL** [comment]
Sure @fbricon.

So basically, projects such as https://github.com/RDIL/Cherry have Gradle subprojects (in my case, they are named Willow and Oak), and when I edit a source file in one of them, not only do I get classpath warnings, but also, autocompletion does not work for the dependencies that are defined on the subproject, and not on the root project. 

If you clone it, you should be able to see that classes from the net.minecraft package don’t actually show details when hovered over, because both subprojects define the dependency on the jar that holds that code.

**Comment by fbricon** [comment]
Does it work if you import the projects in Eclipse?

**Comment by RDIL** [comment]
I use IntelliJ since it’s better

**Comment by CsCherrYY** [comment]
![1511](https://user-images.githubusercontent.com/45906942/163089105-b392f635-1a39-4ebf-8090-7f4521b5772c.png)

@RDIL I can see the auto-completion list in project `Willow`, with the newest extension (1.4.0)

For the hover, I find your dependency has no source attached so the extension won't provide hover information. You can use `Go to definition` to view the .class files.

**Comment by RDIL** [comment]
This issue is probably outdated anyway, since I haven't used VSCode in at least a year.  I'll close it, but anybody else who experiences it can feel free to let me know and I'll reopen it.
