### ISSUE TITLE
Endless Importing Maven project(s) loop

### ISSUE THREAD

**Issue by bangroot** [redhat-developer/vscode-java#1515]
I'm not 100% positive this is an issue with the VSCode plugin, but starting in the last 24 hours, when I open my workspace, I'm stuck in a loop that looks like `68769839 Importing Maven project(s): Importing Maven project(s) - project service-funding-source [436/1000]`.

My biggest hope right now is to see if there is a way to get more diagnostics out of the JDT LS. I'm under crunch time and I can't stop to get a project set up to produce. Here's what I do know:

* I work in a mono-repo with several (20+) maven projects. These are *not* parent/child. All are standalone maven projects.
* I downgraded plugin versions (to 0.63.0), same issue
* Fresh workspace, same git working dir.
* Fresh git clone into new Workspace. Same issue.
* Clean Java workspace, no help.

The LS logs are no help as currently configured as they just say
```
!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-09 11:22:47.450
!MESSAGE Importing Maven project(s)

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-07-09 11:27:44.252
!MESSAGE Timeout while waiting for completion of job: Initialize Workspace(33)
```

##### Environment
- Operating System: Mac OS 10.14.6
- JDK version: 13.0.2.hs-adpt (SDKman label)
- Visual Studio Code version: 1.46.1
- Java extension version: 0.64.1

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

Endless loop of Importing Maven projects.

##### Expected Result

Finish eventually.

**Comment by bangroot** [comment]
I've added `-Dlog.level=ALL` to my `java.jdt.ls.vmargs` but nothing changed in the LS logs.

**Comment by bangroot** [comment]
Nevermind - for posterity I had an circular dependency between projects (not maven modules, just the projects depended on each other)

**Comment by pac0rro** [comment]
In my case it was a shortcut / symlink of a folder I created in a subfolder by distraction. I found it copying the folders with DoubleCommander when it asked me "Do you want to follow the symlink ....?"
