### ISSUE TITLE
REFACTOR SETTING NOT WORKING  --  Java>Refactor: Rename From File Explorer

### ISSUE THREAD

**Issue by maleko48** [redhat-developer/vscode-java#1517]
#### Environment #####
- Operating System: Windows 10 Home x64 v1909 / Build: 18363.900
- JDK version: 1.8.0_161
- Visual Studio Code version: 1.47.0
- Java extension version:  WORKS in 0.62.0 - 0.63.0  //  BROKEN in v0.64.0 - 0.64.1

##### Steps To Reproduce #####
1.)  Set Java>Refactor: Rename From File Explorer setting to: "AutoApply"

2.)  Create new java file: test.java via VSCode File Explorer

3.)  Save test.java

4.)  Select test.java via VSCode File Explorer

5.)  Press F2 to rename test.java to test1.java and complete rename by pressing ENTER

6.)  class name in test1.java should automatically refactor from "public class test" to "public class test1" along with other relevant references in the class definition, but does not.

**Comment by testforstephen** [comment]
@maleko48 Nice catch!
