### ISSUE TITLE
Detect Gradle project not only by finding build.gradle but settings.gradle too

### ISSUE THREAD

**Issue by jnesspro** [redhat-developer/vscode-java#1528]
If I open miltiproject folder with such structure:

settings.gradle
gradlew.sh
server
|_ build.gradle
client
|_ build.gradle

It will be detected as project only if I include empty build.project file.
Also, vscode will try handle this subprojects as separated projects.

settings.gradle defines subprojects. I think our java plugin should read it

**Comment by fbricon** [comment]
can you please attach a sample project?

**Comment by testforstephen** [comment]
Here is a sample to reproduce the issue.
[TestGradle.zip](https://github.com/microsoft/vscode-java-debug/files/5496156/TestGradle.zip)

For example, a multi-project build could be like this. When opening the root folder, jdt.ls should detect the root folder as a gradle project.
```
 |── app
 │   ...
 │   └── build.gradle
 |── settings.gradle
```

**Comment by testforstephen** [comment]
fixed by https://github.com/eclipse/eclipse.jdt.ls/pull/1617
