### ISSUE TITLE
Prevent tab key appending asterisk for import autocompletion

### ISSUE THREAD

**Issue by rnorm** [redhat-developer/vscode-java#1532]
I want to `import org.springframework.boot.SpringApplication;`. When I type `import org.spring` and then press tab key, the autocompleted code is `import org.springframework.*;`. I want to have the autocompleted code as `import org.springframework` so that I can type `.bo` for further completion. Or is there another way to autocomplete this import statement?

##### Environment
- Operating System: macOS 10.15.5
- JDK version: openjdk 14.0.2
- Visual Studio Code version: 1.47.2
- Java extension version: v0.64.1

##### Steps To Reproduce
1. type `import org.spring`
2. press tab key

##### Current Result
`import org.springframework.*;`
##### Expected Result
`import org.springframework`

**Comment by fbricon** [comment]
That's the default behavior of Eclipse JDT. I think our best option, if it's possible to override that behavior, is to return `org.springframework.${0:*;}` so that you could keep typing, after the 1st tab, to get type imports. 
@snjeza WDYT? is this easy to do?

**Comment by fbricon** [comment]
See new behavior:


![importcompletion](https://user-images.githubusercontent.com/388609/87959012-8d30da80-cab2-11ea-87bc-18f3b7092db8.gif)

**Comment by rnorm** [comment]
Thanks for the quick response!
