### ISSUE TITLE
Java extention doesn't recognize my Java OpenJDK 11 in the JAVA_HOME env var

### ISSUE THREAD

**Issue by ppatierno** [redhat-developer/vscode-java#1546]
As for the current updates I have installed Java OpenJDK 11.
I have set the `JAVA_HOME` env var to `/usr/lib/jvm/java-11-openjdk-11.0.7.10-1.fc31.x86_64` but when VS Code starts the following error shows up.

The JAVA_HOME environment variable (/usr/lib/jvm/java-11-openjdk-11.0.7.10-1.fc31.x86_64/) does not point to a JDK.

Actually, that path contains the `bin` folder and as stated [here](https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements) "Note: The path should end at the parent folder that contains the bin folder. Example Path: Use /usr/lib/jvm/java-1.8.0 if bin exists at /usr/lib/jvm/java-1.8.0/bin" ... my setting should work. What am I doing wrong?

##### Environment
- Operating System: Fedora 31
- JDK version: OpenJDK 11
- Visual Studio Code version: 1.47.2
- Java extension version: 0.65.0

##### Steps To Reproduce

See description above.

**Comment by snjeza** [comment]
@ppatierno could you try the following:

```
sudo dnf install java-11-openjdk-devel
sudo dnf install java-11-openjdk-src
```

**Comment by ppatierno** [comment]
Yeah, I needed the `devel` package. That was the problem. Anyway, I don't think we need the `src` one.
Why are you suggesting to install it as well?

**Comment by snjeza** [comment]
See https://github.com/eclipse/eclipse.jdt.ls/issues/1006

**Comment by ppatierno** [comment]
ok thanks!
