### ISSUE TITLE
Is there have some way to search class in classpath?

### ISSUE THREAD

**Issue by sheiy** [redhat-developer/vscode-java#1550]
for example input text Thread and go to Thread.java
like idea double shift
![image](https://user-images.githubusercontent.com/12210038/88766737-221a8e80-d1ab-11ea-8827-556aa10ea8aa.png)

**Comment by testforstephen** [comment]
Windows: Ctrl + T
MacOS: ⌘T

**Comment by sheiy** [comment]
@testforstephen thanks
