### ISSUE TITLE
import jar failed

### ISSUE THREAD

**Issue by moxue361** [redhat-developer/vscode-java#1553]
Operating System:windows 10
- JDK version:8.0
-java extension version:0.64.0
shows ''Successfully added 'jjjj\lib' to the project jjjj_1396602e's source path'',but the result of running is that the package does not exist
The result can be seen in the figure below
![1](https://user-images.githubusercontent.com/64472550/88814825-2ebfd680-d1ed-11ea-92f6-24feefe42772.png)

**Comment by testforstephen** [comment]
You're using javac to compile the Java file, this is out of scope of the Java extension.
