### ISSUE TITLE
Search and replace input text fields are unusable with multi-line text

### ISSUE THREAD

**Issue by stodge** [redhat-developer/vscode-java#1558]
##### Environment
- Operating System: 

Fedora 30 (I think)
Linux 5.7.9-100.fc31.x86_64 #1 SMP Fri Jul 17 17:18:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- JDK version: 

```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment 18.9 (build 11.0.8+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10, mixed mode, sharing)
```

- Visual Studio Code version: 

```Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.7.9-100.fc31.x86_64
```

- Java extension version: v0.65.0

##### Steps To Reproduce

1. Press `CTRL+SHIFT+H` to initiate a global replace
2. Paste multiple lines of text into the Search box (e.g. 10+ lines)
3. Try to use the cursor keys to move around the input box - weird things happen and the input box is unusable
4. Use the mouse wheel to scroll and click in different spots to place the cursor - weird things happen and the input box is unusable
5. Repeat this for the second input box (replace text input box)

##### Current Result

Both input boxes (search text and replace text) display anomalies and are unusable

##### Expected Result

You should be able to move the cursor around both input boxes using the cursor keys and add/delete/modify the text content.

You should also be able to use the mouse to scroll around the input boxes and click to position the cursor.

**Comment by testforstephen** [comment]
@stodge This feature is provided by VS Code, not by Java extension. Could you open an issue at https://github.com/microsoft/vscode/issues?

**Comment by stodge** [comment]
Ah, of course. My mistake! Thanks.
