### ISSUE TITLE
Ctrl + Click is not working VS Code Editor(Java file)

### ISSUE THREAD

**Issue by softboy99** [redhat-developer/vscode-java#1560]
#### Environment
- Operating System: win 10 x64
- JDK version: 1.8
- Visual Studio Code version: 1.47.3
- Java extension version: 0.9.1

**Comment by Eskibear** [comment]
> JDK version: 1.8

It requires JDK 11 now. See https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692

**Comment by meeowwwww** [comment]
Go to Setting

Search : multiCursor

change to : ctrlCmd

**Comment by santhu210** [comment]
If this is relevant still, below this worked for me.

- Uninstall java extensions pack
- Change the server launch mode to light weight in settings - `"java.server.launchMode": "LightWeight"`
- Re-install the java extensions pack
