### ISSUE TITLE
The import javax.smartcardio cannot be resolved

### ISSUE THREAD

**Issue by mkilburn60** [redhat-developer/vscode-java#1561]
This problem happens with eclipse but there is a workaround - manually import the java.smartcardio lib via the menu. But the VS plugin has no menu. Is there a way to do the same as the following https://stackoverflow.com/questions/58917664/eclipse-doesnt-recognize-smartcardio-library

**Comment by testforstephen** [comment]
@mkilburn60 Could you explain your user scenario a bit more? For example, what kind of project you're working on? Can it be added via maven/gradle dependency?

**Comment by mikekilburn** [comment]
javax.smartcardio is part of JDK. Other packages from the JDK resolve ok. How does one add a standard JDK package dependency via maven? I'll look into that. Meanwhile, what is the equivalent of  https://stackoverflow.com/questions/58917664/eclipse-doesnt-recognize-smartcardio-library in the VS extension?

**Comment by gorkem** [comment]
Do you have a module-info.java file that adds `requires java.smartcardio;`? 

@snjeza should the module-info be enough for language server to resolve the module?

**Comment by testforstephen** [comment]
@mikekilburn The equivalent is the generated **.classpath** file in your workspace, we don't prevent you modifying it directly, but we don't recommend it. 

It's better to let the build tool to manage the classpath or buildpath. Different project type may have different fix. For example, what @gorkem mentioned is appropriate for modular project.

If you could provide more details on your project setup, that would help us understand the gap better. Would you mind sharing a simple sample project to reproduce the issue?

**Comment by snjeza** [comment]
> @snjeza should the module-info be enough for language server to resolve the module?

I have checked and it works. You can also set the following classpath entry:
```
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11">
		<attributes>
			<attribute name="module" value="true"/>
			<attribute name="limit-modules" value="java.se,jdk.accessibility,jdk.attach,jdk.compiler,jdk.httpserver,jdk.jartool,jdk.javadoc,jdk.jconsole,jdk.jdi,jdk.management,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported,jdk.dynalink,jdk.jfr,jdk.jshell,jdk.jsobject,jdk.management.jfr,jdk.net,jdk.scripting.nashorn,jdk.unsupported.desktop,jdk.xml.dom,java.smartcardio,jdk.aot,jdk.charsets,jdk.crypto.cryptoki,jdk.crypto.ec,jdk.editpad,jdk.hotspot.agent,jdk.internal.vm.ci,jdk.internal.vm.compiler,jdk.internal.vm.compiler.management,jdk.jcmd,jdk.jdeps,jdk.jlink,jdk.jstatd,jdk.localedata,jdk.naming.dns,jdk.naming.rmi,jdk.pack,jdk.rmic,jdk.scripting.nashorn.shell,jdk.zipfs"/>
		</attributes>
	</classpathentry>
```

**Comment by mkilburn60** [comment]
@snjeza That worked. You rock man thanks!
