### ISSUE TITLE
Incorrect runtime name displayed in status bar when runtime path is invalid

### ISSUE THREAD

**Issue by paulo-mu-axur** [redhat-developer/vscode-java#1568]
When you set an invalid `path` value for the JavaSE-1.8 runtime in the `java.configuration.runtimes` property, the extension assumes it must use the value of the `java.home` property (a fallback behaviour I guess), but the runtime displayed name does not get updated in the VS Code status bar. Check it out:

1. Given the following settings.json file:

```json
{
    "java.home": "/usr/lib/jvm/java-11-openjdk-amd64",
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java",
            "default": true
        },
        {
            "name": "JavaSE-11",
            "path": "/usr/lib/jvm/java-11-openjdk-amd64"
        }
    ],
    "java.dependency.packagePresentation": "hierarchical",
    "java.dependency.showMembers": true,
}
```

(notice the `path` value from JavaSE-1.8 is wrong, it should be `/usr/lib/jvm/java-8-openjdk-amd64`)

2. The following happens in VS Code:

![e67Y57ZFQi](https://user-images.githubusercontent.com/52720321/89693751-c7d5a800-d8e5-11ea-8cb9-49189d82e427.png)

(notice the path is from `java.home` - JDK11)

##### Environment
- Operating System: Windows 10 (running VS Code on WSL with Ubuntu 18.04)
- JDK version: 8, 11
- Visual Studio Code version: 1.47.3
- Java extension version: 0.65.0

##### Steps To Reproduce

1. Set the `java.home` property to JDK 11's path.
2. Set a default runtime in `java.configuration.runtime` with an invalid path.
3. Run the command "Java: Clean the Java language server workspace" and restart VS Code.
4. Open a Java file and check the runtime name in the status bar, then hover your mouse into it and check the displayed path.
5. Optionally run the application and check the Java runtime path in the command line.

[java_language_server.log](https://github.com/redhat-developer/vscode-java/files/5044140/java_language_server.log)

##### Current Result

The wrong runtime name is displayed in the status bar.

##### Expected Result

Display the right runtime name in the status bar. Would be good to get an error message, too.

##### Additional Informations

Java language server does show that the runtime is invalid, which is good:

```
!ENTRY org.eclipse.jdt.ls.core 1 0 2020-08-07 19:54:28.607
!MESSAGE Invalid runtime: JavaEnvironment [name=JavaSE-1.8, path=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java, javadoc=null, sources=null]

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-08-07 19:54:28.664
!MESSAGE Setting /usr/lib/jvm/java-11-openjdk-amd64 as 'JavaSE-11' environment (id:1596840868628)

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-08-07 19:54:28.668
```

Took me a while to figure this out, I hope this issue can help other people too.

**Comment by jdneo** [comment]
What's your project's language level? 

The JDK path is not necessarily equal with the language level, you can use JDK 11 writing code with Java 8's grammar.

So it depends on your project configuration. Could you please check this for your project?

**Comment by fbricon** [comment]
The way this was addressed is an error message is shown if your settings point to an invalid JDK.

The status bar still shows the actual JDK used to fulfill the JavaSE-level requirement, as this is legit.
