### ISSUE TITLE
Surround with try/catch reformats document

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1572]
This behaviour is more then a year old, but it often bugs me so hard that I thought it's time for a report.
It just happened again on a really large file where I noticed it way too late.

Ok, when using try/catch the whole document gets reformatted:

before:
<img width="434" alt="Screen Shot 2020-08-11 at 22 00 03" src="https://user-images.githubusercontent.com/738650/89943343-53b93e00-dc1e-11ea-84a6-e466c4a2bcd9.png">

after:
<img width="511" alt="Screen Shot 2020-08-11 at 22 00 13" src="https://user-images.githubusercontent.com/738650/89943346-56b42e80-dc1e-11ea-8b41-a5b29f996494.png">

##### Environment
- Operating System: OSX
- JDK version: OpenJDK 11
- Visual Studio Code version: latest
- Java extension version: latest

**Comment by fbricon** [comment]
Can you check if it is the same behavior in Eclipse? If yes, then that would need to be fixed in upstream JDT

**Comment by ronakg** [comment]
I can confirm this. It doesn't happen on Eclipse. Tried with Version: 2020-06 (4.16.0) Build id: 20200615-1200.

**Comment by clankill3r** [comment]
I just noticed, when you type `var` and use the "Change type of '...' to
'...'" then this reformats happens as well.

It is also really aggressive with comments, for example:

Op wo 12 aug. 2020 om 01:18 schreef Ronak Gandhi <notifications@github.com>:

**Comment by ronakg** [comment]
Any updates on this issue? I noticed that this happens for any source action in VSCode. Today I tried to automatically add getter setter for a particular field and it reformatted the whole class.

However, the source action and formatting are happening in 2 separate stages. I was able to undo the formatting and keep the source action result.

**Comment by ronakg** [comment]
Wondering if this is being looked into.
