### ISSUE TITLE
[feature request] allow `var` to be fully specified with using 'Show Fixes'

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#1573]
When I have this for example:

<img width="492" alt="Screen Shot 2020-08-11 at 22 19 30" src="https://user-images.githubusercontent.com/738650/89945021-012d5100-dc21-11ea-9efc-2eb2c3a5bceb.png">

Then the VSCode extension knows what it is:
<img width="694" alt="Screen Shot 2020-08-11 at 22 19 39" src="https://user-images.githubusercontent.com/738650/89945057-0d191300-dc21-11ea-8bbf-2defe3e7e085.png">

Typing var is so much faster, but I like things to be explicit. 

I would really really like that if you bring up the 'Show Fixes' menu:

<img width="355" alt="Screen Shot 2020-08-11 at 22 19 49" src="https://user-images.githubusercontent.com/738650/89945222-51a4ae80-dc21-11ea-8a34-3611be156145.png">

That there would be an option with something like "Fully specify var", that would change it to this:

<img width="695" alt="Screen Shot 2020-08-11 at 22 24 52" src="https://user-images.githubusercontent.com/738650/89945341-83b61080-dc21-11ea-99fc-98d32b21cdd3.png">

**Comment by fbricon** [comment]
JDT already has such quickfix, we need to port it to JDT.LS. @testforstephen, @jdneo, @Eskibear anyone of you interested in taking this one?

**Comment by snjeza** [comment]
See https://github.com/eclipse/eclipse.jdt.ls/issues/696 and https://github.com/eclipse/eclipse.jdt.ls/issues/697

![var](https://user-images.githubusercontent.com/388609/89954022-8a984f80-dc30-11ea-9440-58e105c96c4c.gif)

**Comment by Eskibear** [comment]
@clankill3r As shown above, you trigger "Show fixes" on the content with the squiggle line,  `t` in your case. 

The problem is, "Move..." and "Change to final where possible" are showing everywhere, tracked in https://github.com/redhat-developer/vscode-java/issues/1074 .

**Comment by clankill3r** [comment]
I had no idea this was in, but it would be nice if you can pop up that
context on 'var', since that is the actual thing changing.

Op wo 12 aug. 2020 om 04:19 schreef Yan Zhang <notifications@github.com>:

**Comment by snjeza** [comment]
> I had no idea this was in, but it would be nice if you can pop up that
context on 'var', since that is the actual thing changing.

That has been done intentionally. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=531039#c9
