### ISSUE TITLE
Duplicate snippets displayed in lightweight mode

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#1579]
When running in in lightweight mode, duplicate syserr and sysout snippets are displayed for completion. The https://github.com/redhat-developer/vscode-java/blob/master/snippets/server.json is still used instead of being discarded.

**Comment by fbricon** [comment]
@jdneo can you please look into this one?

**Comment by jdneo** [comment]
Sure, raised a PR: https://github.com/redhat-developer/vscode-java/pull/1580
