### ISSUE TITLE
Not loading existing servers on startup with WSL

### ISSUE THREAD

**Issue by epomatti** [redhat-developer/vscode-java#1582]
##### Environment
- Operating System: WSL2 with Ubuntu 20.04
- JDK version: openjdk 11.0.8 2020-07-14
- Visual Studio Code version: 1.48.0
- Java extension version: openjdk 11.0.8 2020-07-14

I installed a WildFly server and it is running OK. However, when I close VS Code and open it again the server is gone:

![image](https://user-images.githubusercontent.com/6530769/90429821-c56d0e00-e09c-11ea-94de-b7b9706a47f2.png)

If I create another server then the previous server shows up along with the new one. This happens every time I close and open VS Code:

![image](https://user-images.githubusercontent.com/6530769/90429964-02390500-e09d-11ea-8d6b-f31e3e378c18.png)

Here is a video:

![maibeer-httpsonly](https://user-images.githubusercontent.com/6530769/90519163-0f5a0080-e13e-11ea-9273-a970d70f1730.gif)

**Comment by lstocchi** [comment]
@epomatti can you open this issue into https://github.com/redhat-developer/rsp-server? This is the wrong repo. Thank you :)

**Comment by epomatti** [comment]
https://github.com/redhat-developer/rsp-server/issues/594
