### ISSUE TITLE
autocompletion inherided interface method insert wrong code

### ISSUE THREAD

**Issue by zhangbaogithub** [redhat-developer/vscode-java#1593]
[provide a description of the issue]
autocompletion insert wrong code

##### Environment
- Operating System: Windows_NT x64 10.0.18362
- JDK version: 14.0.2
- Visual Studio Code version: 1.48.1
- Java extension version: 0.65.0

##### Steps To Reproduce
1. [step 1] Passing anonymous interface in function parameters
2. [step 2] Overwrite interface's abstract method

![](https://user-images.githubusercontent.com/20422981/91305682-f7d5e400-e7dd-11ea-8d85-2aec5660dccf.gif)

##### Current Result
overwrite `onFailure` method, it can associate `onFailure` but insert `null`
##### Expected Result
it can complete specified method correctly

**Comment by snjeza** [comment]
I can't reproduce the issue. 
@zhangbaogithub could you attach a sample project?

**Comment by zhangbaogithub** [comment]
@snjeza yes, here is reproduce the issue steps:

1. git clone https://github.com/square/okhttp.git
2. git checkout parent-3.14.9
3. open file(PostExample.java)
4. add following code
```java
client.newCall(request).enqueue(new Callback() {

});
```
