### ISSUE TITLE
No option to disable Configure Java Runtime window from appearing when opening .java file

### ISSUE THREAD

**Issue by cnmoise** [redhat-developer/vscode-java#1598]
When opening a Java project for the first time, it is typical for a pop-up page to appear informing the user if they haven't added configured their local java environment. However when developing on a remote system the notification will pop up every. single. time. And there is no way to permanently dismiss it using a GUI.

Suggestion: add a checkbox similar to the VSCode welcome page that disables the behavior that opens the Configure Java Runtime window when opening a Java file for situations where Java isn't detected on a remote system.

##### Environment
- Operating System: Windows_NT x64 10.0.17763
- JDK version: 13.0.2
- Visual Studio Code version: 1.48.2
- Java extension version: 0.28.0

##### Steps To Reproduce
1. Use SSH extension to connect to remote host
2. Open a .java file

**Comment by fbricon** [comment]
Can you attach a screenshot of the pop-up, I want to make sure there's no confusion

**Comment by cnmoise** [comment]
Sure thing, here is what I see every time I open a .java file in a new window https://i.imgur.com/Imiz79x.png

**Comment by fbricon** [comment]
So that page is provided by the Microsoft's Java Extension Pack, not vscode-java. Please open a ticket in https://github.com/Microsoft/vscode-java-pack
