### ISSUE TITLE
Switching between open editor tabs using keyboard shortcut is slow.

### ISSUE THREAD

**Issue by safield** [redhat-developer/vscode-java#1600]
- Operating System: Linux Mint 20 (Ubuntu 20.04 base)
- JDK version: Open JDK 11
- Visual Studio Code version: 1.48.2
- Java extension version: 0.65.0

Switching between editor tabs is slow.

When I disable all extensions, then open multiple java files (easier to observe with 3 or more), I can **press and hold** the cycle editor tab left/right hotkey, and the editor tab will cycle smoothly, as fast as my key repeat.

If I enable just the redhat java extension, when I perform the same action, there is severe lag. The cycling takes a long time (~800-1000ms), and when it does switch tabs, it jumps a random amount of editor tabs.

**Comment by fbricon** [comment]
Can you record that slow behavior? I tested on my mac and saw no such problem. While cycling, no request is sent to the Language Server, so everything is happening on the vscode side. I can't think of a piece of code in vscode-java that could explain the issue TBH.

**Comment by fbricon** [comment]
No problem either on my Ubuntu 20.04 box

**Comment by fbricon** [comment]
I tried Ctrl+Tab, (cycles through recently used tabs) and Ctrl+page up/down (open next/previous tab)
