### ISSUE TITLE
tiny AutoComplete request

### ISSUE THREAD

**Issue by ericsia** [redhat-developer/vscode-java#1604]
Hi great developers out there, first I want to say thank you for you guys to make this possible happening.
I enjoyed using vscode so much and love using it with java. ❤
I think it can be agreed that everyone use:
System.out.print();
and 
System.out.println();

very often especially in debugging. Can you guys kindly include that in the suggestion completion box please?
I love to see that in next update
![800](https://user-images.githubusercontent.com/24624808/91893368-95da1a80-ecc6-11ea-855d-afec45d8a440.png)

Also I wish junit package is available for single java file. 
It is so troublesome I have to create maven project in order to use it.
It will make this plugin so so much powerful if a single opened java file can use junit.
because asserEqual() is used quite often when testing Object
![imagine3](https://user-images.githubusercontent.com/24624808/91893631-02edb000-ecc7-11ea-8756-5ef51d93c4f0.png)

**Comment by fbricon** [comment]
you can type `sysout` for System.out.println() and `syserr` for System.err.println(). See also `systrace` to print the current method name.

To get Junit completion for a single file, you just need to create a lib folder containing the junit jar(s) like that:

![auto-add-jar](https://user-images.githubusercontent.com/148698/91914499-86ec6b80-ecb8-11ea-9f8c-3c9e1ac672a4.gif)

**Comment by ericsia** [comment]
> you can type `sysout` for System.out.println() and `syserr` for System.err.println(). See also `systrace` to print the current method name.
> 
> To get Junit completion for a single file, you just need to create a lib folder containing the junit jar(s) like that:
> 

@fbricon  Omg!!! Thank you so much, I didn't know it was there the whole time.
I never download a single junit.jar before, am I doing it correctly?
I downloaded from here: https://search.maven.org/search?q=g:junit
I think vscode still need implementation to work with junit though, because right now when I do simple test:

assertEquals(2, 2); // assertEquals(Expected, Result);
assertEquals(2, 1);

Vscode doesn't ouput boolean or result

it is quite violent when there is an error like this:
![imagine2](https://user-images.githubusercontent.com/24624808/91928359-6bac4b00-ed0e-11ea-9a45-864d94c1acdd.png)

It still end the program even when there is try_catch wrapped around 😅
I don't expect to have beautiful output like this:
![imagine2](https://user-images.githubusercontent.com/24624808/91928615-17559b00-ed0f-11ea-9ccb-2f84626cd3e3.png)

but I wish the console output can display Ran how many test, how many Fail/Pass  😀

**Comment by testforstephen** [comment]
@ericsia The unit test support is provided by https://github.com/microsoft/vscode-java-test/issues, could you move the unit test discussion there?

**Comment by ericsia** [comment]
> @ericsia The unit test support is provided by https://github.com/microsoft/vscode-java-test/issues, could you move the unit test discussion there?

everything is ok now. I followed this video https://www.youtube.com/watch?v=60yrTfVdFwo
Although I wish vscode came with that setting

**Comment by fbricon** [comment]
which value would that setting have? The Junit jar location is user specific

**Comment by ericsia** [comment]
> which value would that setting have? The Junit jar location is user specific
1. Maybe include junit.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13/junit-4.13.jar 
2. then add this to setting.json:
"java.project.referencedLibraries": [
        "lib/**/*.jar",
          "C:\\extensionpath\\junit.jar"
    ],

  This configuration basically allowed any opened folder to import:
  import org.junit.Test;
  import org.junit.Assert.assertEquals;
 ![weird](https://user-images.githubusercontent.com/24624808/91990544-7396da00-ed64-11ea-8211-69b83d642c08.png)

3. even more perfect add a right-click "Generate Junit Test", because right-now I have to type it out manually.
  ![imagine](https://user-images.githubusercontent.com/24624808/91990646-90cba880-ed64-11ea-9f21-4024188ac4b1.png)

**Comment by fbricon** [comment]
I'd rather prefer we don't ship any Junit version. It evolves constantly, Junit 4 is fairly different from Junit 5, in the end, better leave that choice to the users.
The `Generate JUnit Testfile` command is not coming from vscode-java, I don't know where it's coming from. But you can probably open an enhancement request in the extension contributing it.
