### ISSUE TITLE
Intellisense For Java Not Working

### ISSUE THREAD

**Issue by TrevorBrown-dev** [redhat-developer/vscode-java#1608]
I opened VSCode today and found that intellisense for java has stopped working. I reinstalled the extension pack, reloaded VSCode, restarted my PC, none of it worked, any suggestions?

**Comment by fbricon** [comment]
Which version of Java are you using? have you checked the [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting)?
