### ISSUE TITLE
java11 can't debug

### ISSUE THREAD

**Issue by yuan8ba** [redhat-developer/vscode-java#1612]
[provide a description of the issue]

##### Environment
- Operating System: window 10
- JDK version:java 11
- Visual Studio Code version: 1.49.0
- Java extension version:

##### Steps To Reproduce
1. Create a Spring Boot project maven
2. mvn clear package
3. F5
4.Error: the main class could not be found or could not be loaded

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by jdneo** [comment]
@yuan8ba Are the class files compiled in the `target` folder?
