### ISSUE TITLE
`java.configuration.runtimes` option configuration error will not prompt an error

### ISSUE THREAD

**Issue by basecell** [redhat-developer/vscode-java#1614]
I configured `java.home` as the installation directory of jdk11, and I deliberately set a non-existent path for `JavaSE-1.8` in the `java.configuration.runtimes` option. Then when vscode opens Java8's project, **the Java plug-in does not prompt for configuration errors, but used the jdk11 configured by java.home to compile and debug my project!**  This is a hidden trouble, If users misconfigure the `path` in the `java.configuration.runtimes` option, they will be more confused when the error occurs, just like I did before: [vscode-java-debug/issues/873](https://github.com/microsoft/vscode-java-debug/issues/873#issue-687124746)

##### Environment
- Operating System: Windows 10
- JDK version: openjdk version "1.8.0_265"
- Visual Studio Code version: 1.49.0
- Java extension version: 0.66.0

##### Current Result
![image](https://user-images.githubusercontent.com/14192199/93172299-2ef44100-f75d-11ea-91a7-2fe1a98ef3cf.png)

##### Expected Result
When the `path` configuration of the `java.configuration.runtimes` option is incorrect, an error is displayed

**Comment by jdneo** [comment]
Thanks for reporting, it's dup with https://github.com/redhat-developer/vscode-java/issues/1481.

I believe @testforstephen is already working on this issue.
