### ISSUE TITLE
potential failure of activation when JDK <11 is also installed

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#1621]
### Context
It simply finds the first available JDK in below order:
* java.home
* JDK_HOME
* JAVA_HOME
* fallback to call [node-find-java-home](https://github.com/jsdevel/node-find-java-home#algorithm)

### Steps
Now since it requires JDK 11+, a broken case is:
* both JDK 8 and JDK 11 installed 
* `java.home` not set (for most new users)
* JAVA_HOME points to JDK 8

It will pick JDK 8, and request users to install JDK 11+.

### Possible solution

Add new options to find-java-home, like `minVersion` (requires the library to check version), or request the library to return all possible java homes.

**Comment by Eskibear** [comment]
ultimately it would be perfect to provide new APIs in upstream, tracked in  https://github.com/jsdevel/node-find-java-home/issues/28

**Comment by testforstephen** [comment]
A good finding, looks like this is not a rare case.
