### ISSUE TITLE
Unable to format java code/snippets in untitled document which is not yet saved

### ISSUE THREAD

**Issue by overtomanu** [redhat-developer/vscode-java#1623]
[Unable to format java code/snippets in untitled document]

##### Environment
- Operating System: Windows 10
- JDK version: 11
- Visual Studio Code version:1.49.0
- Java extension version: 0.67.0

##### Steps To Reproduce
1.  Create new file in vs code ctrl+N
2.  paste some java method
3. Invoke command palette (Ctrl+Shift+p) and then type change language mode ->java
4. Right click and format document, nothing happens

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Not formatting java code in untitled file
##### Expected Result
Should be able to format java code snippets in untitled file

**Comment by fbricon** [comment]
This is expected. 
In the early days of vscode-java, I tried to get Java support for unsaved new files, but it led to extremely complicated hacks on the backend side, with unreliable results, so I decided to abandon this option.

Workaround is just : save the file.

Not planning on fixing this, sorry.

**Comment by overtomanu** [comment]
ok but i am able to format XML in unsaved files. Maybe things changed after early days. I understand that formatting single java file without its dependent java class files might not be perfect, but some basic formatting with indentation would have been nice. like how this website does 
https://www.tutorialspoint.com/online_java_formatter.htm
