### ISSUE TITLE
Inexplicable color highlight being affected by Java extension.

### ISSUE THREAD

**Issue by safield** [redhat-developer/vscode-java#1624]
- Operating System: Ubuntu 20.04
- JDK version: openjdk 11
- Visual Studio Code version: 1.49.0
- Java extension version: 0.67

I am working on a color theme, and I am observing some inexplicable editor background highlighting going on. This highlighting only occurs when the Java Extension is enabled and I am in a Java source file. After disabling the Java Extension, the color highlighting goes away.

I have implemented a blank color theme extension. This extension has no colors defined for anything other than text forground and text background. It should be a two color theme.

But when I place the caret on any symbol name, there is a dark blue/green background highlight behind the declaration of that symbol, and a grey background drawn behind all references to that symbol.

![weird_highlighting](https://user-images.githubusercontent.com/12876404/93548926-e2ac2b00-f92d-11ea-972c-9f53a5f2ae4c.jpg)

The expected behaviour is that no coloring would be occuring unless that color is specified in my color theme.

**Comment by testforstephen** [comment]
This looks like a default behavior from VS Code.

If you try it in a js file, it has same behavior. The position declaring the symbol has blue background, and the reference position has grey background.
![image](https://user-images.githubusercontent.com/14052197/93550754-b2e93b80-f99e-11ea-84d0-5386999cbee0.png)

**Comment by testforstephen** [comment]
This seems the default VS Code behavior, will close it in Java side.
