### ISSUE TITLE
jdk15 is not support

### ISSUE THREAD

**Issue by sunbos** [redhat-developer/vscode-java#1627]
[provide a description of the issue]
jdk15 is not support
错误: 加载主类 App 时出现 LinkageError
        java.lang.UnsupportedClassVersionError: App (class file version 58.65535) was compiled with preview features that are unsupported. This version of 
the Java Runtime only recognizes preview features for class file version 59.65535

##### Environment
- Operating System:Window10
- JDK version:15
- Visual Studio Code version:1.49.1
- Java extension version:v0.10.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Please note that Java 15 support has not been released yet. You can manually install the latest CI build with Java 15 support from https://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D, give it a try and report back any issues

**Comment by cyruscchan** [comment]
> Please note that Java 15 support has not been released yet. You can manually install the latest CI build with Java 15 support from https://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D, give it a try and report back any issues

Okay, but when it release JDK 15 supported in vs code since I want to use stable version

**Comment by fbricon** [comment]
Wednesday next week, give or take.

**Comment by fbricon** [comment]
See https://github.com/redhat-developer/vscode-java/wiki/Enabling-Java-preview-features to learn how to enable preview features
