### ISSUE TITLE
Use local project as maven dependency

### ISSUE THREAD

**Issue by jccazeaux** [redhat-developer/vscode-java#1634]
Hi,
I have two Java Maven projects. Project One uses project Two as maven dependency. I would like to use local project Two as dependency instead of using packaged jar.
This is a interesting feature in eclipse where the ide detects that a maven dependency (groupid, artifactid and version) match a local project's pom definition. In this case project one would not include project two as jar but as local directory.
This means in development I can modify project two and directly test it in project one with breakpoints.

Is it possible to add such a feature in vscode?

**Comment by fbricon** [comment]
This should be possible already. If not, please provide a set of sample projects reproducing your setup

**Comment by jccazeaux** [comment]
Maybe I missed something. I'll try again and come back

**Comment by jccazeaux** [comment]
Ok it works as you said. Don't know what i was doing wrong. Thank you
