### ISSUE TITLE
Java code formatter rules is ignored

### ISSUE THREAD

**Issue by CarlPer** [redhat-developer/vscode-java#1640]
This rule is ignored when formatting:
`<setting id="org.eclipse.jdt.core.formatter.insert_new_line_in_empty_anonymous_type_declaration" value="do not insert"/>`

##### Environment
- Operating System: Windows 10 Enterprise v.1909
- JDK version: Amazon Corretto jdk1.8.0_252
- Visual Studio Code version: 1.49.2
- Java extension version: 0.68.0

##### Steps To Reproduce
1. Format : List<String> fromJson = new Gson().fromJson("String", new TypeToken<List<String>>() {}.getType());

##### Current Result
    List<String> fromJson = new Gson().fromJson("String", new TypeToken<List<String>>() {
    }.getType());
##### Expected Result
    List<String> fromJson = new Gson().fromJson("String", new TypeToken<List<String>>() {}.getType());

**Comment by testforstephen** [comment]
@CsCherrYY Could you please take a look at this formatting issue?

**Comment by CsCherrYY** [comment]
Hi, @CarlPer , it seems a formatter version bug. The formatter version of template in `vscode-java` is `13`. And the current version of eclipse is `21`. There are some differences between the two versions so your settings may be ignored. We are trying to add a formatter version updater into the language server, and it will make effect at the next jdt version. 
Now you can simply replace this setting by `<setting id="org.eclipse.jdt.core.formatter.keep_anonymous_type_declaration_on_one_line" value="one_line_if_empty"/>` to solve this problem as a workaround.

**Comment by achaphiv** [comment]
For anyone else stumbling on this issue, I had to add more config:

```xml
    <setting id="org.eclipse.jdt.core.formatter.keep_type_declaration_on_one_line" value="one_line_if_empty" />
    <setting id="org.eclipse.jdt.core.formatter.keep_anonymous_type_declaration_on_one_line" value="one_line_if_empty" />
    <setting id="org.eclipse.jdt.core.formatter.keep_method_body_on_one_line" value="one_line_if_empty" />
```

to support:

```java
class Foo {
  Foo() {}
}
```

and

```java
class Foo extends TypeReference<Bar> {}
```

**Comment by rgrunber** [comment]
https://github.com/eclipse/eclipse.jdt.ui/blob/master/org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/ui/preferences/formatter/ProfileVersionerCore.java#L32 mentions the current version as well as a utility method to update older settings to any version.

**Comment by CsCherrYY** [comment]
@rgrunber Yes. https://github.com/eclipse/eclipse.jdt.ls/pull/1675/commits/704e50bf09711ebb72f09e91a7c1fef66ffc9d72 uses the utility you mentioned to check if there is any need to update the profile.
