### ISSUE TITLE
Run/debug multiple single file programs with the same name

### ISSUE THREAD

**Issue by matjazmav** [redhat-developer/vscode-java#1645]
I have a folder structure where each example lives inside a folder with a single java file that is always named `Solution.java`. Problem is that because classes are cached I have to manually clean cache before executing 2nd, 3rd, ... example, is there a way to configure VS Code to support such case, without changing folder structure and file names?

**Launch configuration:**
```
{
      "name": "Java",
      "type": "java",
      "request": "launch",
      "mainClass": "${file}",
      "cwd": "${fileDirname}"
    }
```

**Folder structure:**
```
root/
  example1/
    Solution.java
  example2/
    Solution.java
```

**Comment by fbricon** [comment]
use packages, example1 and example2.
alternatively, open example1 folder, then add example2 to the workspace

**Comment by fbricon** [comment]
Closing as running/debugging code is outside the scope of vscode-java. 
Please open a ticket in https://github.com/microsoft/vscode-java-debug/issues
