### ISSUE TITLE
problem with visual studio code !! "This path is not pointing to a JDK."

### ISSUE THREAD

**Issue by hichemkanon** [redhat-developer/vscode-java#1647]
hello guys, i have problem in my visual studio code that always show this message"This path is not pointing to a JDK." after trying many way to set it but always this message
any suggestion or solution ?

i have windows 7 pro 64bit
java and jdk all is ok when trying " java -version or javac -version !
please help

image of issue : https://ibb.co/nf1s23M

**Comment by hichemkanon** [comment]
sorry, gys SOLVED for me just now 
i created another path to JDK
 JAVA_PATH in user variables user as here in this screenshot ; https://ibb.co/6mPXtvf

maybe this help someone,

**Comment by rgrunber** [comment]
The path for JAVA_HOME appears to terminate on semicolon in addition to using two backslashes for path separation. The path is annotated as invalid, so perhaps that was the issue ?

Closing as it seems to be resolved.
