### ISSUE TITLE
with update to java11，I get some errors on building java project

### ISSUE THREAD

**Issue by GKilm** [redhat-developer/vscode-java#1650]
with update to java11，I get some errors on building java project.
 
> The project cannot be built until its prerequisite * is built. Cleaning and building all projects is recommended

when I try to change to Java8,it's ok again.
when update to java 11, I also wrote the java runtimes configuration to `settings.json` file.
```json{
"java.configuration.runtimes": [
        {
            "name":"JavaSE-1.8",
            "path": "C:\\Program Files\\AdoptOpenJDK\\jdk-8.0.252.09-hotspot",
            "default": true
        },
        {
            "name":"JavaSE-11",
            "path": "C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.7.10-hotspot"
        },
    ]
}
```

##### Environment
- Operating System: win 10
- JDK version: 11
- Visual Studio Code version:1.50
- Java extension version:0.68.0
- System Maven version:3.6.3 
- System Java vesion:1.8

##### others
1. I also use the extensions `java extension pack`  and `lombok`,now the version of `maven for java` is 0.24.2，`Project Manager for Java` is 0.13.0.
2. I have cleaned the java server workspace and reload the window many a time,but it doesn't work.

**Comment by testforstephen** [comment]
Could you please explain what specific error you got?

**Comment by GKilm** [comment]
> Could you please explain what specific error you got?

happy with your enthusiasm

**Comment by GKilm** [comment]
I resolve this issues by reading the .log opened with the command `java: open java language server log file`.

It shows me some errors about lombok. There are the following examples.

> !MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class lombok.launch.PatchFixesHider$Transform

> !MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor

I think the version of lombok is incompatible Firstly, then had the `lombok` extension uninstalled and configured the `lombok` in the older version manually, but the second problem of the example occurred.I had to clean the workspace, import the project and reset the version of `lombok` again and again.

I felt very depressed, but I tried the way in the issues #652.When I remove `-Xbootclasspath/a:path` and just remain the `-javaagent:path` from the `java.jdt.ls.vmargs` parameter  in the `setting.json` file,it works well with cleaning the workspace.

It's awful to resolve the incompatible problems. Please fix or explain compatibility issues to make it easier to use `lombok`.Thanks for your pay. @GabrielBB

**Comment by GabrielBB** [comment]
@fbricon @testforstephen Guys, if you want just remove my extension from your docs, I no longer have the time to maintain this.

**Comment by GKilm** [comment]
> @fbricon @testforstephen Guys, if you want just remove my extension from your docs, I no longer have the time to maintain this. Sorry. (Basically what it needs is to download the jar depending on the version you want to use or have in your pom.xml or gradle file)

I'm so sorry that I didn't make myself clear.I mean that the `lombok` jar used in the `lombok Annotations Support for VS Code` extension is incompatible.
The java version is 1.8 in my `pom.xml`. It's normal when type `mvn package` in the terminal, but failed when build in the `VSCode`.I download `lombok-1.16.18.jar` to replace the jar in the extension, it work well. So I think `lombok` in the extension is incompatible, just this.
