### ISSUE TITLE
Source actions generate getters should suport boolean with isXxx format

### ISSUE THREAD

**Issue by taoistwar** [redhat-developer/vscode-java#1653]
eg. Class Frog has property alive, should generate a getter is either Alive or getAlive，If had writen isAlive, should not generate getAlive.

```java
public class Frog {
    private Boolean alive = true;

    /**
     * @return the alive
     */
    public Boolean isAlive() {
        return alive;
    }

    /**
     * @param alive the alive to set
     */
    public void setAlive(Boolean alive) {
        this.alive = alive;
    }
}
```

**Comment by taoistwar** [comment]
the property type is Boolean，generate is getXxx. it should be isXxx. 
![GIF 2020-10-14 16-29-36](https://user-images.githubusercontent.com/674212/95963968-e5217800-0e3a-11eb-8d93-705e7b158b97.gif)

**Comment by fbricon** [comment]
This is Eclipse's behavior. You can find some valid explanations in https://stackoverflow.com/questions/19023548/eclipse-generating-getters-setters.

I think it makes sense to expect an isAlive method to never return null, which can definitely happen with a Boolean.

**Comment by fbricon** [comment]
use a boolean instead
