### ISSUE TITLE
Can't get document symbols

### ISSUE THREAD

**Issue by ShimonBenYair** [redhat-developer/vscode-java#1656]
Hi

I am writing a vscode extension and I want to get the symbols of a JAVA file.

##### Environment
- Operating System: windows 10
- Visual Studio Code version: 1.50.0

##### Steps To Reproduce
If I run this sample code :

const pathToJavaFile = path.join(
  __dirname,
  "AdminServiceHandler.java"
);
const vscodeCDSExtension = extensions.getExtension("redhat.java");
const javaDocParams : DocumentSymbolParams = {
  textDocument: {
    uri:pathToJavaFile
  }
};

if (vscodeCDSExtension && vscodeCDSExtension.isActive) {
  const symbols = await vscodeCDSExtension.exports.getDocumentSymbols(javaDocParams);
  console.log(symbols.length);
}

##### Current Result

symbols is an empty array of length 0

##### Expected Result
To get the symbols of the java file

Is it the correct way of doing it ?
Maybe i need to use another API ( can'f find such ...)
Do you have any sample for doing something similar ?
[AdminServiceHandler.zip](https://github.com/redhat-developer/vscode-java/files/5385279/AdminServiceHandler.zip)

**Comment by fbricon** [comment]
See https://github.com/redhat-developer/vscode-java/blob/f29528f3f353aba2546bb697640583728ca93e87/test/standard-mode-suite/publicApi.test.ts#L52

**Comment by ShimonBenYair** [comment]
great, thanks a lot
