### ISSUE TITLE
Range of methods in the document symbols returned from "getDocumentSymbols" API are not ok

### ISSUE THREAD

**Issue by ShimonBenYair** [redhat-developer/vscode-java#1659]
Hi

I am writing a vscode extension and I want to get the symbols of a JAVA file.
Range of methods in the document symbols returned from "getDocumentSymbols" API seems to be wrong.
They are also not containing empty lines.
I need to insert code to a file exactly in the position that the last method in the class ends, do I have an option for that ? 
because right now the range values seems to be wrong

**Environment**
Operating System: windows 10
Visual Studio Code version: 1.50.0

**Steps To Reproduce**
If I run this sample code :

`const vscodeCDSExtension = extensions.getExtension("redhat.java");
const javaDocParams : DocumentSymbolParams = {
textDocument: {
uri: Uri.file(filePath).toString()
}
};

if (vscodeCDSExtension && vscodeCDSExtension.isActive) {
const symbols = await vscodeCDSExtension.exports.getDocumentSymbols(javaDocParams);
console.log(symbols.length);
}`

**Current Result**
e.g. the last method starts at line 25 and ends in line 28

**Expected Result**
last method starts at line 26 and ends in line 29

The JAVA file is attached
[CatalogServiceHandler.zip](https://github.com/redhat-developer/vscode-java/files/5388927/CatalogServiceHandler.zip)

**Comment by testforstephen** [comment]
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#range The range returned by LSP is zero based. The display line number in the VS Code editor is one based. You need translate it to the correct value.

**Comment by ShimonBenYair** [comment]
[CatalogServiceHandler.zip](https://github.com/redhat-developer/vscode-java/files/5389383/CatalogServiceHandler.zip)

No, sometimes the gap/delta is more than one 
for example , in the attached file, it is a gap of 3 lines and not one

**Comment by ShimonBenYair** [comment]
I don't have the option to reopen again this issue, please assist

**Comment by testforstephen** [comment]
In your sample, which symbol returns the wrong range?

**Comment by ShimonBenYair** [comment]
@testforstephen 

the class ("CatalogServiceHandler") has wrong range and also its methods has wrong ranges

**Comment by testforstephen** [comment]
It includes the annotation to the range either.

Below is the file you provided, the class starts with line 15 and ends with line 38. And protocol returns result [14, 37], that's correct because of zero based.
![image](https://user-images.githubusercontent.com/14052197/96219045-913c9d80-0fb8-11eb-8e8e-769899580d9b.png)
