### ISSUE TITLE
maven invoked with wrong Java version - regression

### ISSUE THREAD

**Issue by shoffmeister** [redhat-developer/vscode-java#1662]
VS Code recently started requiring JDK11+ to run the Java *extension*. Alas, this seems to have uncovered an implementation defect in the extension.

maven is always invoked with the *java.home* defined for the VS Code extension; maven ist not invoked with the JDK version that has been chosen in the *java.configuration.runtimes*. This is a very subtle difference, which makes a difference where breaking changes were introduced into the JDKs - in my case, this is XML catalogs and JAXB.

So, basically, maven should be invoked with the Java runtime version detected by the extension (in my case 1.8), not with the extension's java.home Java version.

Full steps below. 

##### Environment
- Operating System: Windows 10
- JDK version: 8 _and_ 14
- Visual Studio Code version: 1.50
- Java extension version: ?

##### Steps To Reproduce
* install RedHat 14 and RedHat 8 JDK; make sure that JDK 8 is the default

$ env | grep -E ^J
JAVA_HOME=C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.265-3
JDK_HOME=C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.265-3

* download maven, put maven on path
* start VS Code
* configure both JDKs in *java.configuration.runtimes*
* configure JDK 14 as *java.home* - VS Code Java extension requirement
* open attached pom.xml [pom.zip](https://github.com/redhat-developer/vscode-java/files/5397153/pom.zip)

-> detects as Java project - good!
-> detects as Java *1.8* project ("JAVA PROJECTS" pane) -> good!
-> in extension, pane "MAVEN", right-click on "problem", then click "compile"

Inspect terminal output and (indirectly) observe that maven itself detected that is being run under JDK 14 (the check goes for JDK 9+), see below. If maven had been executed with the JDK as detected by the extension, maven would have emitted the expected lines.

##### Current Result
[WARNING]      [echo] This is profile java8-schema-catalog
[WARNING]      [echo] env.JAVA_HOME C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.265-3

##### Expected Result
[WARNING]      [echo] This is profile java9_plus-schema-catalog
[WARNING]      [echo] env.JAVA_HOME C:/Program Files/RedHat/java-14-openjdk-14.0.2-1

**Comment by shoffmeister** [comment]
Background on JAXB - Oracle changed the catalog resolver implementation. Catalog definitions that worked in JDK 8 no longer work in, e.g. JDK 14. This then makes it quite important that the "right" JDK is present for the JAXB _plugin_ inside maven to pick up the right implementation of the catalog resolver.

In light of the documentation, https://devblogs.microsoft.com/java/about-upgrading-to-java-11-for-vs-code-for-java/ and https://code.visualstudio.com/docs/java/java-project#_configure-jdk, with the extension picking up the correct and intended Java version, it should actually consistently use that also for invoking, e.g. maven. As maven is invoked as an external tool (as opposed to being "hooked into" (I think that's the m2e dance?)), there does not seem to be any reason to have a consistent environment.

FWIW, IntelliJ, when flipping between project JDKs, does the right thing - it flips the JDK (JRE) for the project _and_ the JDK for the tooling.

**Comment by shoffmeister** [comment]
FWIW, I am a bit irritated by the configuration name "java.configuration.runtimes" - wouldn't this rather be "java.configuration.developmentkits" (yes, I know, this would be hard to change now)

**Comment by fbricon** [comment]
Sorry but those Maven features are not provided by vscode-java. Please open a ticket in https://github.com/microsoft/vscode-maven/issues
