### ISSUE TITLE
support download of sources for classes in jar with maven coordinates

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#1664]
when editing java code in projects with no maven/gradle and use 3rd party dependencies it would
be awesome if vscode java would be able to identify jars maven metadata and try fetch the right source
as all the info is there to go locate it.

**Comment by fbricon** [comment]
yeah I had that working, only had tests to write, but never pushed my branch to github. Now my laptop is dead, I need to figure out a way to access the SSD to access it. Or rewrite everything from scratch

**Comment by maxandersen** [comment]
You can do it! :)

**Comment by fbricon** [comment]
@maxandersen lucky you ;-) eclipse/eclipse.jdt.ls#1580
