### ISSUE TITLE
Change the scope of 'java.home' to machine-overridable?

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#1667]
Currently the setting `java.home`'s scope is `window`. This may have some problems when it comes to remote scenario.

Here is an example:

![WeChat Screenshot_20201022155632](https://user-images.githubusercontent.com/6193897/96845701-8fc11880-1483-11eb-9497-add75f076bc6.png)

My user(local) setting point the `java.home` to my local installation path, once my vscode linked to the remote container, it will be consumed and get this error.

After change to `machine-overridable`, it becomes fine

Local setting will not be taken by remote:
![WeChat Screenshot_20201022155117](https://user-images.githubusercontent.com/6193897/96845936-d747a480-1483-11eb-83f9-dde2e69952b9.png)

![WeChat Screenshot_20201022155138](https://user-images.githubusercontent.com/6193897/96845991-e7f81a80-1483-11eb-9b2a-40caf7d0d7d2.png)

The next question is, if change to `machine-overridable`, will it still be configurable in the workspace level? The answer is yes:

![WeChat Screenshot_20201022155329](https://user-images.githubusercontent.com/6193897/96846196-24c41180-1484-11eb-9747-4e3c96575214.png)

This prevents to make breakings since currently the `java.home` is `window` scope and can be set to workspace as well.

**Comment by rgrunber** [comment]
So If I understand correctly, it should still be possible for someone testing vscode to configure the setting at the ["workspace" level](https://github.com/microsoft/vscode/issues/73985), just no longer at the "user" level.

@fbricon does that seem more reasonable ?

**Comment by jdneo** [comment]
@rgrunber, yes, users can still set the setting in the "workspace" level. If we want to avoid the `java.home` setting taken by the remote side, we can use:

- `machine`: This can totally solve the problem, but by doing this we break those users who set the setting in workspace level
- `machine-overridable`: Only help those users who set the setting in the `user` level and avoid making breakings.

**Comment by Eskibear** [comment]
Switching it from `window` to `machine-overridable`, the only effect is, it will disallow user level settings to be synced in remote machines. 

Below is my 2 cents about `machine` vs `machine-overridable`. 
Now we have to settings `java.configuration.runtimes` (run project) and `java.home` (launch LS). For me as a user, I don't care `java.home` unless LS fails to start. I don't even have to know there is an LS and what it is. And I don't see a common use case to use different JDKs to launch LS for different workspaces.
What I might care about is `java.configuration.runtimes`.  I might want to use different JDK to run my projects in different workspaces. (unfortunately it's a user level setting for the moment).

**Comment by testforstephen** [comment]
From the discussion, at least we reached an agreement that it should be limited to the machine, right?

The controversy is over whether it's `machine` or `machine-overridable`.

I prefer to set it to `machine-overridable`. Since `java.home` will be used to launch LS and project if no runtimes are specified. `machine-overriable` can avoid feature break in case some users still use it at workspace level.

Regarding `java.configuration.runtimes`, it's already set to `machine` scope so far. Since what users care more is this setting, and change it to `machine-overridable` will give more flexibility to the invisible project with workspace level settings.
