### ISSUE TITLE
JavaFX Project runs in a temp directory, which doesn't allow importing fonts in stylesheets

### ISSUE THREAD

**Issue by ksh-r** [redhat-developer/vscode-java#1669]
I am running a JavaFX application. Does VSC before running, build a temporary environment/directory and then runs the code from that.
I have a stylesheet which uses '@fontface'. The font's .ttf file is present inside the project directory itself. When I run the main java file, it gives a warning 'Could not load @fontface.
The following command is executed when I click on Run Project (I have a project.json file in .vscode)
```
keshar@Keshars-MacBook-Air FTP-Project %  cd /Users/keshar/OneDrive/Documents/s5_cn/CN_Project/FTP-Project ; /Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:53519 --module-path /Library/Java/Extensions/javafx-sdk-11.0.2/lib --add-modules javafx.controls,javafx.fxml -Dfile.encoding=UTF-8 @/var/folders/1z/b0nhrzfn3kz1h3swpnj7qglm0000gn/T/cp_2an02mwlmzj91bhxxwucqhc2e.argfile app.App 
```
The ending of the above command is given below and my project is not located in this directory.
`-Dfile.encoding=UTF-8 @/var/folders/1z/b0nhrzfn3kz1h3swpnj7qglm0000gn/T/cp_2an02mwlmzj91bhxxwucqhc2e.argfile app.App`

The warning that it gives is:
`Oct 23, 2020 7:02:23 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
INFO: Could not load @font-face font [file:/Users/keshar/Library/Application%20Support/Code/User/workspaceStorage/13500534c7f134388e0c57a339b26045/redhat.java/jdt_ws/FTP-Project_ad912ab4/bin/app/fonts/SimploCustom.ttf]`

The project itself is not located in `Library/Application Support/Code` so why is it searching the .ttf file in the above path?
How can I disable the creation of the temporary directory ?
##### Environment
- Operating System: macOS Catalina
- JDK version: 11.0.2
- Visual Studio Code version: 1.50.1
- Java extension version: 0.69.0

##### Steps To Reproduce
1. [step 1] Make a JavaFX project.
2. [step 2] Add a stylesheet and import a font using '@fontface'

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Sorry but vscode-java is not responsible for running the code. Please open a ticket in https://github.com/microsoft/vscode-java-debug/issues
