### ISSUE TITLE
Eclipse settings files not being generated by VSCode Extension

### ISSUE THREAD

**Issue by markexperience** [redhat-developer/vscode-java#167]
When using 0.0.12 of the plugin, and opening a folder with a pom file, the eclipse related configuration files .classpath, .project and those under .settings are not generated. 

When using 0.0.11 the files are generated, and code completion and classpath resolution work as expected.

##### Environment
- Operating System: Window 10
- JDK version: 1.8.0_121
- Visual Studio Code version: 1.10.2
- Java extension version: 0.0.12

##### Steps To Reproduce
1. Create a simple maven project
2. Open the project in VSCode

[java-interview.zip](https://github.com/redhat-developer/vscode-java/files/851789/java-interview.zip)

##### Current Result 
No .project, .classpath and .settings/ files are produced.
This is when opening with 0.1.12
##### Expected Result
The files are created and code completion and classpath resolution occurs as expected.
This works as expected with 0.1.11

**Comment by fbricon** [comment]
Indeed, we just discovered the regression (https://github.com/eclipse/eclipse.jdt.ls/issues/191), an update will be published later today.

**Comment by markexperience** [comment]
No problem, for what it's worth I love the tool (and VS Code).

**Comment by fbricon** [comment]
vscode-java 0.0.13 has been published to the VS Code Marketplace
