### ISSUE TITLE
Import Java Project into Workspace: Default to configured Java Version

### ISSUE THREAD

**Issue by Z3roCoder** [redhat-developer/vscode-java#1670]
[provide a description of the issue]

Whenever I import a Java-Project into my Workspace in VSCode via the prompt "Java Projects discovered. Would you like to import the project into the workspace?" and I click "Yes", it imports the Project but configures it for Java 1.8

But my Settings are set to Java-14

##### Environment
- Operating System: Windows 10
- JDK version: JDK-14
- Visual Studio Code version: Latest (Freshly downloaded)
- Java extension version: Latest (Freshly downloaded)

##### Steps To Reproduce
1. Create a Maven-Project outside of VSCode
2. Open Maven Project in VSCode
3. Click "Yes" when you are asked to import the project

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

In .classpath:
`<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8">`

In .settings/org.eclipse.jdt.core.prefs:
```
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
org.eclipse.jdt.core.compiler.compliance=1.8
org.eclipse.jdt.core.compiler.source=1.8
```

##### Expected Result

In .classpath:
`<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-14">`

In .settings/org.eclipse.jdt.core.prefs:
```
org.eclipse.jdt.core.compiler.codegen.targetPlatform=14
org.eclipse.jdt.core.compiler.compliance=14
org.eclipse.jdt.core.compiler.source=14
```

##### Additional Informations
None

**Comment by fbricon** [comment]
Most likely your pom targets Java 1.8 for compilation. Check your maven.compiler.* properties and maven-compiler-plugin configuration.
Maven configuration always wins over the default vscode settings.

**Comment by Z3roCoder** [comment]
Hm... Could this be the problem?

pom.xml
```
...
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
...
```

**Comment by fbricon** [comment]
That's it. Vscode-java does exactly what Maven tells it to do

**Comment by Z3roCoder** [comment]
Thank you!
