### ISSUE TITLE
Improve support for Gradle projects

### ISSUE THREAD

**Issue by csaltos** [redhat-developer/vscode-java#1677]
When using Maven based projects everything is OK and with a lot of support but with Gradle some feature are missing like source code autocomplete and even importing classes from other packages. On top of that VS Code shows a lot of warnings and error that are not present at Gradle when called from the command line.

##### Environment
- Operating System: macOS Catalina 10.15.7
- JDK version: OpenJDK 11.0.7 
- Visual Studio Code version: 1.50.1
- Java extension version: 0.69.0

##### Steps To Reproduce
1. Clone https://github.com/csaltos/java-gradle-spring-template
2. Imported at VS Code

##### Current Result

* Autocomplete not working properly
* Many warnings and error that are not actually present in the project when called with gradle from the command line

##### Expected Result

* The project is imported with ease and all features work like it would be a Maven project or even better.

##### Additional Informations

Thanks for VSCode Java, it's really useful !!

**Comment by fbricon** [comment]
Works for me.
<img width="1440" alt="Screen Shot 2020-10-27 at 11 06 12 AM" src="https://user-images.githubusercontent.com/148698/97287120-7b469c80-1844-11eb-92cc-8a1a9b4a9f6c.png">


Please share your settings.json and the Java server logs (F1 > Java: Open Java Language server log file)

**Comment by csaltos** [comment]
Great, thanks !! ... it was an error on my end, good to know Gradle is working !!
