### ISSUE TITLE
disable auto build not work

### ISSUE THREAD

**Issue by wjx0912** [redhat-developer/vscode-java#1689]
![2](https://user-images.githubusercontent.com/5556482/97843944-1c41c580-1d25-11eb-825b-257103a365ae.png)

hi, i have set   "java.autobuild.enabled": false,   in my settings.json,

but it also auto build after vscode startup(it  waste some times),  
i note a very old issue https://github.com/redhat-developer/vscode-java/issues/406      but it not work.

can someone help, thanks.

**Comment by testforstephen** [comment]
`"java.autobuild.enabled"` is just used to control whether to auto compile your project.

What's displayed in the `Java Build Status` terminal is the status of importing Java projects. If you didn't import the projects, you won't get the full feature list.

**Comment by wjx0912** [comment]
@testforstephen 
thanks.
