### ISSUE TITLE
java.home not being honored in a remote development environment

### ISSUE THREAD

**Issue by ryanpagefico** [redhat-developer/vscode-java#1696]
When attempting to use this extension in a remote development environment with SSH, the java.home property seems to be ignored and the "Install JDK 11" message pops up. I have jdk11 installed on my virtual machine and the path is correct.

##### Environment
- Operating System: centos 7
- JDK version: openjdk11
- Visual Studio Code version: 1.50
- Java extension version: 0.70.0

##### Steps To Reproduce
1. Create a new virtual machine, install remote development plugin for VSCode
2. Install openjdk 11 on virtual machine
3. SSH into virtual machine and try and set `java.home` to the correct location, it will be greyed out by vscode

**Comment by ryanpagefico** [comment]
For those like me unaware, there is a specific settings.json for remote development environments.

**Comment by wecharyu** [comment]
I have the same problem, which options should be set?
