### ISSUE TITLE
method snippets need to be type aware

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#1697]
When in the body of an interface, the `public_method` snippet inserts:

```
    public void name() {
        
    }
```

instead of 
```
    public void name();
```

There might be a way to return an interface-friendly snippet, depending on the context. Same issue with the `private_method` snippet.

Actually, a bunch of snippets irrelevant to the interface body context are proposed: `try_catch`, `try_resources`, `switch`, `ctor`, `protected_method`. We shouldn't see them here. Actually `try_catch`, `try_resources`, `switch` should only be proposed when completing inside a code block, regardless of the type.

**Comment by rgrunber** [comment]
@hopehadfield , were you looking at this issue when you considered making our method snippets more context aware ?

**Comment by hopehadfield** [comment]
@rgrunber yes, this is the one.
