### ISSUE TITLE
[Feature Request]  Java Code  auto folding

### ISSUE THREAD

**Issue by honghuhu** [redhat-developer/vscode-java#1708]
Guide package **auto folding**，would be much better.

![image](https://wx3.sinaimg.cn/large/008ckdHCly1gkvht9jktmj30km04mwez.jpg)

**Comment by testforstephen** [comment]
Folding the imports by default will depend on a feature request https://github.com/microsoft/vscode/issues/40338

**Comment by honghuhu** [comment]
souka
