### ISSUE TITLE
Connection to server got closed. Server will restart.

### ISSUE THREAD

**Issue by y1m6** [redhat-developer/vscode-java#1711]
Continuous restart after startup about one minute.

##### Environment
- Operating System: WSL Alpine
- JDK version: 
  openjdk 11.0.9 2020-10-20
  OpenJDK Runtime Environment (build 11.0.9+11-alpine-r0)
  OpenJDK 64-Bit Server VM (build 11.0.9+11-alpine-r0, mixed mode)
- Visual Studio Code version:1.51.1
- Java extension version: v0.71.0

client.log:
{
  message: 'The Language Support for Java server crashed and will restart.',
  level: 'error',
  timestamp: '2020-11-20 22:36:20.974'
}

.log:
!SESSION 2020-11-20 14:19:12.373 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.9
java.vendor=Alpine
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /root/.vscode-server/data/User/workspaceStorage/a9dd53b2dc762a96b3d0b9c07d87b111/redhat.java/jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-11-20 14:19:14.880
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

....

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-11-20 14:19:47.582
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-11-20 14:19:47.585
!MESSAGE >> watchers registered

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-11-20 14:20:25.187
!MESSAGE Parent process stopped running, forcing server exit

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-11-20 14:20:25.188
!MESSAGE Shutdown received... waking up main thread

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-11-20 14:20:25.198
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is stopping:

!ENTRY org.eclipse.core.resources 2 10035 2020-11-20 14:20:25.840
!MESSAGE The workspace will exit with unsaved changes in this session.
!SESSION 2020-11-20 14:20:26.599 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.9
java.vendor=Alpine
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /root/.vscode-server/data/User/workspaceStorage/a9dd53b2dc762a96b3d0b9c07d87b111/redhat.java/jdt_ws

!ENTRY org.eclipse.core.resources 2 10035 2020-11-20 14:20:27.429
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-11-20 14:20:28.122
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

**Comment by fbricon** [comment]
Can you try to run the "Java: Clean Java Language server workspace" command?

**Comment by y1m6** [comment]
> Can you try to run the "Java: Clean Java Language server workspace" command?

Still continuous restart, I also tried to reboot my computer

**Comment by fbricon** [comment]
Since the server restarts without logging anything, if you can locate the $HOME/.config/Code/User/globalStorage/redhat.java/0.71.0/config_win folder in the WSL machine, there might be a log file there containing infos on the crashes

**Comment by y1m6** [comment]
> Since the server restarts without logging anything, if you can locate the $HOME/.config/Code/User/globalStorage/redhat.java/0.71.0/config_linux folder in the WSL machine, there might be a log file there containing infos on the crashes

no log file found.

config_linux > pwd
/root/.vscode-server/data/User/globalStorage/redhat.java/0.71.0/config_linux
config_linux > la
total 8.0K
-rwxr-xr-x 1 root root 5.7K 2020-11-20 12:59 config.ini
drwxrwxrwx 1 root root 4.0K 2020-11-20 17:20 org.eclipse.core.runtime
drwxrwxrwx 1 root root 4.0K 2020-11-20 13:10 org.eclipse.equinox.app
drwxrwxrwx 1 root root 4.0K 2020-11-20 13:10 org.eclipse.equinox.launcher
drwxrwxrwx 1 root root 4.0K 2020-11-20 13:40 org.eclipse.osgi

**Comment by fbricon** [comment]
You can try uninstalling all other java related extensions, only keep vscode-java, delete /root/.vscode-server/data/User/globalStorage/redhat.java/0.71.0/, then "Clean Java Language server workspace",

**Comment by fbricon** [comment]
@snjeza any other suggestions?

**Comment by y1m6** [comment]
> You can try uninstalling all other java related extensions, only keep vscode-java, delete /root/.vscode-server/data/User/globalStorage/redhat.java/0.71.0/, then "Clean Java Language server workspace",

Still continuous restart

**Comment by snjeza** [comment]
@y1m6 could you zip and attach the  /root/.vscode-server/data/User/workspaceStorage/*/redhat.java directory?

**Comment by y1m6** [comment]
> @y1m6 could you zip and attach the /root/.vscode-server/data/User/workspaceStorage/*/redhat.java directory?

[redhat.java.tar.gz](https://github.com/redhat-developer/vscode-java/files/5575384/redhat.java.tar.gz)

**Comment by snjeza** [comment]
> You can try uninstalling all other java related extensions, only keep vscode-java, delete /root/.vscode-server/data/User/globalStorage/redhat.java/0.71.0/, then "Clean Java Language server workspace",

Could you try the following:
- add 
```
"java.jdt.ls.vmargs": "-Dlog.level=ALL -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx3G -Xms512m",
```
to your settings.json
- close VS Code
- remove all directories except redhat.java-0.71.0 in /root/.vscode-server/extensions
- remove /root/.vscode-server/data/User/globalStorage/redhat.java/0.71.0/
- remove /root/.vscode-server/data/User/workspaceStorage
- start VS Code
-  zip and attach the /root/.vscode-server/data/User/workspaceStorage/*/redhat.java directory

**Comment by y1m6** [comment]
> > You can try uninstalling all other java related extensions, only keep vscode-java, delete /root/.vscode-server/data/User/globalStorage/redhat.java/0.71.0/, then "Clean Java Language server workspace",
> 
> Could you try the following:
> 
> * add
> 
> ```
> "java.jdt.ls.vmargs": "-Dlog.level=ALL -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx3G -Xms512m",
> ```
> 
> to your settings.json
> 
> * close VS Code
> * remove all directories except redhat.java-0.71.0 in /root/.vscode-server/extensions
> * remove /root/.vscode-server/data/User/globalStorage/redhat.java/0.71.0/
> * remove /root/.vscode-server/data/User/workspaceStorage
> * start VS Code
> * zip and attach the /root/.vscode-server/data/User/workspaceStorage/*/redhat.java directory

data too large and github doesn't support xz, plz rename to redhat.java.tar.xz and unzx

[redhat.java.tar.xz.zip](https://github.com/redhat-developer/vscode-java/files/5578160/redhat.java.tar.xz.zip)

**Comment by snjeza** [comment]
Could you attach your demo project (/root/temp/demo)?

**Comment by y1m6** [comment]
> Could you attach your demo project (/root/temp/demo)? 
> 
> 
> 
> 

just demo project download from [spring boot](https://start.spring.io), my spring boot project also continuous restart.

**Comment by snjeza** [comment]
Could you run:
```
ls /root/.vscode-server/extensions/
```

**Comment by y1m6** [comment]
redhat.java-0.71.0
visualstudioexptteam.vscodeintellicode-1.2.10
vscjava.vscode-java-debug-0.29.0
vscjava.vscode-java-dependency-0.15.0
vscjava.vscode-java-pack-0.10.0
vscjava.vscode-java-test-0.26.0
vscjava.vscode-maven-0.25.0

**Comment by y1m6** [comment]
> Could you run:
> 
> ```
> ls /root/.vscode-server/extensions/
> ```

redhat.java-0.71.0
visualstudioexptteam.vscodeintellicode-1.2.10
vscjava.vscode-java-debug-0.29.0
vscjava.vscode-java-dependency-0.15.0
vscjava.vscode-java-pack-0.10.0
vscjava.vscode-java-test-0.26.0
vscjava.vscode-maven-0.25.0

**Comment by snjeza** [comment]
Could you remove
```
visualstudioexptteam.vscodeintellicode-1.2.10
vscjava.vscode-java-debug-0.29.0
vscjava.vscode-java-dependency-0.15.0
vscjava.vscode-java-pack-0.10.0
vscjava.vscode-java-test-0.26.0
vscjava.vscode-maven-0.25.0
```
and retry https://github.com/redhat-developer/vscode-java/issues/1711#issuecomment-731618281

**Comment by y1m6** [comment]
> Could you remove
> 
> ```
> visualstudioexptteam.vscodeintellicode-1.2.10
> vscjava.vscode-java-debug-0.29.0
> vscjava.vscode-java-dependency-0.15.0
> vscjava.vscode-java-pack-0.10.0
> vscjava.vscode-java-test-0.26.0
> vscjava.vscode-maven-0.25.0
> ```
> 
> and retry [#1711 (comment)](https://github.com/redhat-developer/vscode-java/issues/1711#issuecomment-731618281)

Still restart
Found those exceptions:
!MESSAGE An internal error occurred during: "Initialize workspace".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin.getProjectsManager(JavaLanguageServerPlugin.java:478)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.getProblemMarkers(WorkspaceDiagnosticsHandler.java:229)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.publishDiagnostics(WorkspaceDiagnosticsHandler.java:217)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:298)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.jobs 4 2 2020-11-22 17:32:09.160
!MESSAGE An internal error occurred during: "Register Watchers".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jdt.ls.core.internal.ProjectUtils.isVisibleProject(ProjectUtils.java:260)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:357)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager$1.run(StandardProjectsManager.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SESSION 2020-11-22 17:32:19.571 -----------------------------------------------

**Comment by snjeza** [comment]
How you start VS Code? In the WSL terminal using _code ._ ?
Could you retry:
```
ls /root/.vscode-server/extensions/
```

**Comment by y1m6** [comment]
> How you start VS Code? In the WSL terminal using _'code .'_ ?
> Could you retry:
> 
> ```
> ls /root/.vscode-server/extensions/
> ```

Using "Code Remote - WSL" plugin

**Comment by snjeza** [comment]
Could you try start it in the WSL terminal?

```
cd /root/.vscode-server/extensions/
rm -rf visualstudioexptteam.vscodeintellicode-1.2.10 vscjava.vscode-java-debug-0.29.0 vscjava.vscode-java-dependency-0.15.0 vscjava.vscode-java-pack-0.10.0 vscjava.vscode-java-test-0.26.0 vscjava.vscode-maven-0.25.0
cd /root/temp/demo
code .
```

**Comment by y1m6** [comment]
> Could you try start it in the WSL terminal?
> 
> ```
> cd /root/.vscode-server/extensions/
> rm -rf visualstudioexptteam.vscodeintellicode-1.2.10 vscjava.vscode-java-debug-0.29.0 vscjava.vscode-java-dependency-0.15.0 vscjava.vscode-java-pack-0.10.0 vscjava.vscode-java-test-0.26.0 vscjava.vscode-maven-0.25.0
> cd /root/temp/demo
> code .
> ```

Still restart

**Comment by snjeza** [comment]
Could you, please, retry:
```
ls /root/.vscode-server/extensions/
```

**Comment by y1m6** [comment]
> Could you, please, retry:
> 
> ```
> ls /root/.vscode-server/extensions/
> ```

demo > ls /root/.vscode-server/extensions
redhat.java-0.71.0

**Comment by snjeza** [comment]
Could you please retry the following:

    - close VS Code
    - ~~remove all directories except redhat.java-0.71.0 in /root/.vscode-server/extensions~~ 
    - remove /root/.vscode-server/data/User/globalStorage/redhat.java/0.71.0/
    - remove /root/.vscode-server/data/User/workspaceStorage
    - start VS Code in the WSL terminal
cd /root/temp/demo
code .
   - zip and attach the /root/.vscode-server/data/User/workspaceStorage/*/redhat.java directory

**Comment by y1m6** [comment]
> Could you, please, retry the following:
> 
> * close VS Code
>   ~remove all directories except redhat.java-0.71.0 in /root/.vscode-server/extensions~
> * remove /root/.vscode-server/data/User/globalStorage/redhat.java/0.71.0/
> * remove /root/.vscode-server/data/User/workspaceStorage
> * start VS Code in the WSL terminal
>   cd /root/temp/demo
>   code .
> * zip and attach the /root/.vscode-server/data/User/workspaceStorage/*/redhat.java directory

data too large and github doesn't support xz, plz rename to redhat.java.tar.xz and unxz

[redhat.java.tar.xz.zip](https://github.com/redhat-developer/vscode-java/files/5581937/redhat.java.tar.xz.zip)

**Comment by snjeza** [comment]
Could you try the following:

- close VS Code
- open the WSL terminal and run
- apk update
- apk add procps
- start VS Code

**Comment by testforstephen** [comment]
Also can reproduce it in the alpine wsl. But it seems this error doesn't break the language server, because the language server will be started successfully after several restarts.

Will update here if i found more information.

**Comment by snjeza** [comment]
@testforstephen Have you executed

```
apk update
apk add procps
```
in the alpine WSL terminal?

**Comment by snjeza** [comment]
The issue happens because Java LS uses the 'ps -p <pid>' command. The alpine distribution includes the busybox ps command which doesn't recognize the -p option. The solution is to install the procps package.
@testforstephen you can always reproduce the issue if you start the VS Code and wait 30+ seconds without any activities.

**Comment by y1m6** [comment]
> The issue happens because Java LS uses the 'ps -p pid' command. The alpine distribution includes the busybox ps command which doesn't recognize the -p option. The solution is to install the procps package.
> @testforstephen you can always reproduce the issue if you start the VS Code and wait 30+ seconds without any activities.

It work fine after install  procps, thx.

**Comment by testforstephen** [comment]
@snjeza Nice finding.

Below is the Java code that the jdt.ls used to detect whether the parent process is running.
```java
private boolean parentProcessStillRunning() {
    String command = "ps -p " + pid;
    Process process = Runtime.getRuntime().exec(command);
    boolean finished = process.waitFor(POLL_DELAY_SECS, TimeUnit.SECONDS);
    return !finished || process.exitValue() == 0;
}
```

In alpine linux, `-p` is unrecognized option when running `ps -p` command. And the `process.exitValue()` will return `1` so that `parentProcessStillRunning()` always returns `false`. The language server would mistakenly think that the parent process has exited and kill itself.

Since VS Code allows running extensions in Docker and WSL, and it's not rare to use various linux distributions. We should add more coverage for this problem. 

Here is my initial idea to improve this issue:
- A simple workaround is to prompt user to manually install `procps` tool when detecting the Java extension is running on alpine.
- Use different approach to check if a process is running when running in different distributions.
   For example, for alpine, `ps` still works and we can check if the target pid is in the result list.

Any other thoughts?

**Comment by snjeza** [comment]
> Use different approach to check if a process is running when running in different distributions.
For example, for alpine, ps still works and we can check if the target pid is in the result list.

We can use 'kill -0 pid' instead of 'ps -p pid'. It is POSIX compliant.
```
diff --git a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java
index e66351ea..b75ad37d 100644
--- a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java
+++ b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java
@@ -69,7 +69,7 @@ public final class ParentProcessWatcher implements Runnable, Function<MessageCon
                if (Platform.OS_WIN32.equals(Platform.getOS())) {
                        command = "cmd /c \"tasklist /FI \"PID eq " + pid + "\" | findstr " + pid + "\"";
                } else {
-                       command = "ps -p " + pid;
+                       command = "kill -0 " + pid;
                }
                Process process = null;
                boolean finished = false;
```

**Comment by testforstephen** [comment]
`kill -0 pid` will return non-zero when you don't own the process. Since Java LS and the parent process are created by the same user, the permission should not be a problem.

I tried `kill -0 pid` in alpine wsl, it works at most cases. However sometimes it also returns 0 when checking some non existing pid, this is weird.
![image](https://user-images.githubusercontent.com/14052197/100059541-370be380-2e66-11eb-8c16-5723b272d921.png)

**Comment by snjeza** [comment]
> I tried kill -0 pid in alpine wsl, it works at most cases. However sometimes it also returns 0 when checking some non existing pid, this is weird.

Could you run
```
ps -efj
```
and repeat 'kill -0 2396; echo $?' a few times.
I think that the 2396 process is a zombie process or process group ID.
See also https://man7.org/linux/man-pages/man2/kill.2.html
> If sig is 0, then no signal is sent, but existence and permission checks are still performed; this can be used to check for the existence of a process ID or process group ID that the caller is permitted to signal.

**Comment by snjeza** [comment]
@testforstephen @y1m6 Could you check https://github.com/snjeza/vscode-test/raw/master/java-0.72.0.vsix ? Java LS should work on WSL Alpine without installing the procps package.
@fbricon  Could you test the issue on Mac OS? Java LS should be stopped when VS Code exits.

**Comment by y1m6** [comment]
> @testforstephen @y1m6 Could you check https://github.com/snjeza/vscode-test/raw/master/java-0.72.0.vsix ? Java LS should work on WSL Alpine without installing the procps package.
> @fbricon Could you test the issue on Mac OS? Java LS should be stopped when VS Code exits.

No more restart without procps in WSL Alpine. thx
