### ISSUE TITLE
Dependencies weren't recognized after being added in gradle project

### ISSUE THREAD

**Issue by Fubuchi** [redhat-developer/vscode-java#1714]
When I added a dependency in build.gradle, the dependency wasn't recognized in code unless I run `Java: Clean the Java language server workspace` and restart vscode.

##### Environment
- Operating System: Microsoft Windows 10 [18363.1082]
- JDK version: openjdk version "13.0.2" 2020-01-14
- Visual Studio Code version: 1.51.1
- Java extension version: v0.71.0

##### Steps To Reproduce
1. Create a gradle project using `gradle init --type java-application --test-framework junit-jupiter`
2. Add a new dependency in build.gradle, e.x: `implementation 'org.apache.commons:commons-lang3:3.11'`
3. Try to use Classes of the new dependency

Sample project: [sample.zip](https://github.com/redhat-developer/vscode-java/files/5587410/sample.zip)

##### Current Result
The dependency can not be used unless I clean the language server workspace.
##### Expected Result
The dependency can be used after being added to build.gradle
##### Additional Informations
Gradle version 6.7.1
Setting `java.configuration.updateBuildConfiguration` is automatic

**Comment by snjeza** [comment]
Related issue - #1528
