### ISSUE TITLE
Support to access the pom file corresponding to the jar package by clicking on the dependency

### ISSUE THREAD

**Issue by msdemt** [redhat-developer/vscode-java#1718]
##### Environment
- Operating System: win10
- JDK version: jdk1.8
- Visual Studio Code version: 1.15.1
- Java extension version: 0.71.0

##### Steps To Reproduce
1. [step 1]  open a maven project and add some dependency, for example 
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.4.0</version>
        </dependency>
```

2. [step 2]

hold crtl and click the artifactId can't access the spring-boot-starter-2.4.0.pom

##### Current Result
can't access the spring-boot-starter-2.4.0.pom by clicking the dependency on maven project
##### Expected Result
vscode could access the spring-boot-starter-2.4.0.pom by clicking the dependency on maven project

**Comment by fbricon** [comment]
Sorry but this is out of scope of vscode-java. Please open your request at https://github.com/microsoft/vscode-maven/issues
