### ISSUE TITLE
The language tools is not fully loaded

### ISSUE THREAD

**Issue by mdabdulnazar** [redhat-developer/vscode-java#1724]
I don't see the thumbs icon for the language tools in the status bar. The status was in a loading state even after a long time.

##### Environment
- Operating System: MacOS 10.14.6
- JDK version: openjdk version "11.0.8" 2020-07-14
- Visual Studio Code version: 1.51.1
- Java extension version: 0.71.0

I don't see any log printed in the output view under "Language Support for Java" even after enabling "java.trace.server". 

Please [click here](https://github.com/redhat-developer/vscode-java/files/5613666/console.log) to see the log from developer tools.

##### Additional Informations
I have installed only the following extensions for Java.
- Language Support for Java(TM) by Red Hat
- Project Manager for Java
- Visual Studio IntelliCode

**Comment by testforstephen** [comment]
Could you also share the server logs?

**F1 -> Java: Open the Java language server log file**

**Comment by mdabdulnazar** [comment]
@testforstephen No log file available.

**Comment by testforstephen** [comment]
from the logs in your developer tool, i only see the lightweight mode is started, no any logs about starting the standard language server.

What kind of workspace did you open? Did you see any info to ask you to import Java projects?

**Comment by mdabdulnazar** [comment]
> What kind of workspace did you open? Did you see any info to ask you to import Java projects?
<img width="309" alt="Screenshot 2020-11-30 at 12 40 12 PM" src="https://user-images.githubusercontent.com/26316839/100578920-37dec280-3309-11eb-8a79-fae4087a4d35.png">
It is a simple project without any build tools. No, I didn't see any info asking me to import Java projects.

I don't have a command to switch the language server to standard mode in Command Palette.
<img width="602" alt="Screenshot 2020-11-30 at 12 42 28 PM" src="https://user-images.githubusercontent.com/26316839/100579162-b2a7dd80-3309-11eb-9ca7-1dac2debb339.png">

**Comment by testforstephen** [comment]
i guess i get the reason for this error.

There is an environment variable `SERVER_PORT` in your machine, which is used by Java extension for debugging purpose and will try to connect to a remote language server. The workaround is to remove `SERVER_PORT` env variable.

**Comment by mdabdulnazar** [comment]
@testforstephen Works after removing the SERVER_PORT variable. Thanks.
