### ISSUE TITLE
Hitting Tab through an autocomplete writes the full text and not just the identifier

### ISSUE THREAD

**Issue by joewood** [redhat-developer/vscode-java#175]
If I start to type text and make a selection from the the autocomplete list using the arrow keys, hitting tab to select the text will output the entire text of the autocomplete, not just complete on the identifier.

##### Environment
- Operating System: RHEL2.7
- JDK version:1.8
- Visual Studio Code version: 1.10.2
- Java extension version: 0.0.13

##### Steps To Reproduce
1. In java code type `import java.util.Collections;` 
2. Further down in a function type `return Coll`
2. Use arrow keys and select `Collections`
3. Hit tab

##### Current Result
4. Text output is `return Collections - java.util`

##### Expected Result
5. Text output should `return Collections` or, even better `return Collections.` with the next set of suggestions.

**Comment by fbricon** [comment]
Works for me on MacOS. I need to setup a VM to check linux.
Can you try to attach [trace messages](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server)?

**Comment by qindj** [comment]
I had the same issue

**Environment**
Operating System: Windows Server 2008 R2 on Azure
JDK version:1.8
Visual Studio Code version: 1.10
Java extension version: 0.0.13

**After upgrade VS Code to 1.10.2 And Java Extension to 0.1.0, issue fixed**

**Comment by gorkem** [comment]
I suspect https://github.com/eclipse/eclipse.jdt.ls/commit/e763fc3292f4d2fa66cdd1c5471ad84d741a6fe3 has done the job @fbricon

**Comment by fbricon** [comment]
@gorkem I'm not quite sure this is related. In the previous version package-less classes would cause autocompletion to throw an exception, so no completion items would be sent back to vscode. You would not have been able to see the `Collections - java.util` proposal.

I'd like to hear from @joewood about testing 0.1.0 though.

**Comment by joewood** [comment]
Just tested with 0.1.0 and still seeing the problem.

**Comment by fbricon** [comment]
@joewood can you attach the [logs for vscode and the server](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)?

**Comment by fbricon** [comment]
ping @joewood ^^

**Comment by joewood** [comment]
I'm attaching the log. This may be related to #176.
[error.txt](https://github.com/redhat-developer/vscode-java/files/930284/error.txt)

**Comment by fbricon** [comment]
Thanks, I can see now how the proxy issue might prevent the completion item resolution, leading to that weird autocompletion result. Maybe we can make that part more robust to getAttachedJavadoc() failures, but I'd rather look into the actual proxy problem in #176. Fixing that will certainly fix this.

**Comment by fbricon** [comment]
As a workaround, you might try installing OpenJDK sources on RHEL, if they're not already there. If the JDK sources are found, it won't try to download the javadoc
