### ISSUE TITLE
Symbolize Interfaces, enums with different icons

### ISSUE THREAD

**Issue by mhash17** [redhat-developer/vscode-java#1750]
It would be very helpful when interfaces, enums, classes etc. have a different icon than the red J-dot for a quick visual distinction.

##### Environment
- Operating System:win10
- JDK version:11
- Visual Studio Code version:1.52
- Java extension version:0.73

**Comment by fbricon** [comment]
The default theme providing the icons is provided by vscode. vscode-java doesn't provide any of those.
You can install and try other file icon themes from the marketplace.
AFAIK, there's probably no way to provide specific icons depending on the file contents (class vs interface).

**Comment by mhash17** [comment]
ok thanks, could've guessed it.
