### ISSUE TITLE
Why this plugins can't support Oracle JDK? SO,I need remove this plugins?

### ISSUE THREAD

**Issue by jingyuexing** [redhat-developer/vscode-java#1751]

**Comment by fbricon** [comment]
Can you please describe your issue? We provide you with guidelines on how to open actionable bug reports: https://github.com/redhat-developer/vscode-java/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by jingyuexing** [comment]
No broblem now,I fixed this broblem

**Comment by jingyuexing** [comment]
Haven't problem now,I fixed this problem
