### ISSUE TITLE
suggest auto completion: enter for insert and tab for replace

### ISSUE THREAD

**Issue by toadzky** [redhat-developer/vscode-java#1757]
I'm used to Intellij and I'm looking to reproduce a behavior there (Eclipse as a similar option). When Intellisense gives me completion options, I can choose between `Tab` and `Enter`. If I choose `Tab`, it will overwrite the rest of the current word, but if I choose `Enter` it will insert the completion instead.

There's support for it in VS Code to an extent as the final comment here says: https://github.com/microsoft/vscode/issues/112613 but that solution doesn't work with this plugin.

**Comment by testforstephen** [comment]
At the moment the Java extension is using a user setting `java.completion.overwrite` to control insert or replace.

To support the new behavior as below about choosing between `Tab` and `Enter`, it will require the Java extension to adopt a new capability [insertReplaceSupport](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion) introduced by LSP. See https://github.com/microsoft/language-server-protocol/issues/846
<img alt="Screenshot 2020-12-16 at 09 09 49" width="531" src="https://user-images.githubusercontent.com/1794099/102321935-a2853480-3f7e-11eb-86bd-1eed4381d16a.png">

**Comment by jdneo** [comment]
This is supported in https://github.com/eclipse/eclipse.jdt.ls/pull/2057. The issue can be closed.

**Comment by testforstephen** [comment]
This has been supported in [vscode-java@1.6.0](https://github.com/redhat-developer/vscode-java/blob/master/CHANGELOG.md#160-may-5th-2022), closing it.
