### ISSUE TITLE
fetch wrong argument if comma existing in java main argument

### ISSUE THREAD

**Issue by woderchen** [redhat-developer/vscode-java#1762]
1. this is java project,  jdk：1.8.0_191

2. input args param in lanuch.json.
example:
{
"type": "java",
"name": "light-core-generator",
"request": "launch",
"mainClass": "daq.light.core.Generator",
"projectName": "light-job-core",
"vmArgs": "-Ddaq.job.forbid-period=22:00~21:00 ",
"args": "-sSortPkColumn \\"{deptdict:'dept_code',staffdict:'dept_code'}\\" -sSortPkColumnType char -sSqlMethod pk"
}

3. run main method in java and check those arguments with debug mode
i want to fetch argument according to args[++i]) in main(String[] args), but the string "{deptdict:'dept_code',staffdict:'dept_code'}" will be divided into two argument as comma existing. if change the comma to "{deptdict:'dept_code'_staffdict:'dept_code'}",  it's my expectation.

i try to debug on IDEA, input arguments at Program Agruments in Run/Debug Configurations as below:
-sSortPkColumn "{tb_deptdict:'dept_code',tb_staffdict:'dept_code'}" -sSortPkColumnType char -sSqlMethod pk
, no this issue.
if you need more info. pls let me know, thanks.

VS Code version: Code 1.52.1 (ea3859d, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

**Comment by testforstephen** [comment]
The debugger feature is contributed by Java debugger extension, could you please move this issue to https://github.com/microsoft/vscode-java-debug/issues?

**Comment by woderchen** [comment]
> The debugger feature is contributed by Java debugger extension, could you please move this issue to https://github.com/microsoft/vscode-java-debug/issues?

 thanks for your reply, not just debug mode, even if i click the "Run" in java code, i got the same issue.

**Comment by testforstephen** [comment]
they both are added by Java debugger extension, need fix there.

**Comment by woderchen** [comment]
> they both are added by Java debugger extension, need fix there.
Got it! thanks.
