### ISSUE TITLE
Recommend "redhat.fabric8-analytics" extension if workspace contains "pom.xml"

### ISSUE THREAD

**Issue by arajkumar** [redhat-developer/vscode-java#1763]
The goal of this issue is to get opinion on showing the recommendation popup to install Dependency Analytics [extension.](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics)

### [Dependency Analytics Platform](https://github.com/fabric8-analytics)
Hosted SaaS platform, provides following insights about the dependencies used in the application stack.
- Security vulnerabilities
- Dependency Statistics
- License Analysis
- Addons

### [Dependency Analytics Extension](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics)
VSCode extension to help developers to find and fix the dependency issues with their application stack by using the REST APIs exposed by the Dependency Analytics platform. Currently this extension supports following ecosystems,
1. Maven (Java)
2. NPM (NodeJS)
3. PyPi (Python)
4. Gomod (Golang)

[Dependency Analytics](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics) a is developer centric extension and definitely will be a great value add to vscode-java extension.

### Integration Strategy
Show a recommendation popup to install Dependency Analytics from vscode-java if workspace contains `pom.xml`.

CC: @fbricon

**Comment by apupier** [comment]
seems ti has been implemented with https://github.com/redhat-developer/vscode-java/pull/1771
