### ISSUE TITLE
How can I format my java code in such that the curly braces will automatically move the the next line?

### ISSUE THREAD

**Issue by leozhang1** [redhat-developer/vscode-java#1768]
void myFunc() {

}

becomes....

void myFunc()
{

}

**Comment by snjeza** [comment]
@leozhang1 you may want to take a look at https://stackoverflow.com/questions/44823701/visual-studio-code-java-format-document-braces-new-line

**Comment by leozhang1** [comment]
@snjeza Thank you. I've seen this one before. Not sure why I didn't try to do what it said. But the comment with the most likes works but it's annoying to have to create a formatting.xml for every java project I would have. For anyone with the same issue as me, I would recommend installing this: https://marketplace.visualstudio.com/items?itemName=ryannaddy.vscode-format

and then going to settings.json and pasting this in:

"format.newLine": {
        "brace": true
    },

**Comment by snjeza** [comment]
>  But the comment with the most likes works but it's annoying to have to create a formatting.xml for every java project I would have.

You can set the _java.format.settings.url_ preference in your [User Settings](https://code.visualstudio.com/docs/getstarted/settings)

**Comment by leozhang1** [comment]
> > But the comment with the most likes works but it's annoying to have to create a formatting.xml for every java project I would have.
> 
> You can set the _java.format.settings.url_ preference in your [User Settings](https://code.visualstudio.com/docs/getstarted/settings)

Okay.  I will take a look.

Also. I take back what I said earlier. That extension didn't take indenting into account (but if anyone disagrees, lemme know), so using the xml file is better.
