### ISSUE TITLE
The plugin is inefficient and unresponsive on Apple M1 devices

### ISSUE THREAD

**Issue by zoain-it** [redhat-developer/vscode-java#1770]
[provide a description of the issue]

##### Environment
- Operating System: macOS 11.1
- JDK version: OpenJDK 11.0.9.1 from Zulu
- Visual Studio Code version: 1.53.0-insider
- Java extension version: v0.73.0

##### Steps To Reproduce
1. Open a .java file, do not rely on hints, write code faster and you can reproduce
2. If you can't reproduce it, please try more times

https://user-images.githubusercontent.com/43292634/104814618-f3709d00-584a-11eb-820a-352780b7ba49.mov

**Comment by zoain-it** [comment]
Noticeable lag in the video. I tried editing with all plugins turned off and it doesn't get very stuck. Then I tried opening just the java plugin again and as soon as I write code faster than the code prompt box, it appears to be slow to respond.

**Comment by zoain-it** [comment]
No one came to deal with it

**Comment by mircoianese** [comment]
+1. Almost unusable on large projects.
