### ISSUE TITLE
Java project initialization

### ISSUE THREAD

**Issue by ikovaltaras** [redhat-developer/vscode-java#1784]
Issue Type: <b>Bug</b>

Project initialization never stops
Nothing helps, removed ~/.vscode and user settings

Extension version: 0.74.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (1.38GB free)|
|Process Argv|--crash-reporter-id c4c2e6d8-5961-4758-9575-51a0219cb951|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry914:30250197
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by snjeza** [comment]
Could you try to remove the workspace directory? See [Clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)

**Comment by ikovaltaras** [comment]
I completely removed $HOME/Library/Application Support/Code and it helped
