### ISSUE TITLE
Are there any keybindings for generating equals and hashcode ?

### ISSUE THREAD

**Issue by joyous-coder** [redhat-developer/vscode-java#1786]
I tried to bind  the java.action.hashCodeEqualsPrompt but it didn't work.  Is there a way??

**Comment by testforstephen** [comment]
You could assign a shortcut for it with the following keybindings config.

```json
    {
        "key": "ctrl+shift+f",
        "command": "editor.action.codeAction",
        "args": {
          "kind": "source.generate.hashCodeEquals"
        }
    }
```

Click [VS Code docs](https://code.visualstudio.com/docs/getstarted/keybindings#_custom-keybindings-for-refactorings) to see more details for keybindings.

**Comment by joyous-coder** [comment]
Thanks!!
