### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by blackcave0** [redhat-developer/vscode-java#1787]
- Issue Type: `Bug`
- Extension Name: `java`
- Extension Version: `0.74.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jdneo** [comment]
@blackcave0 Could you describe the problem you have met?

**Comment by apupier** [comment]
closing. Please open another issue with more details.
