### ISSUE TITLE
Correct the project import status reports

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-java#179]
There is a difference between the reported status percentages and the actually change of the _Starting Java Language Server_ message to started. I can observe it easily with Maven projects.

**Comment by fbricon** [comment]
Can you be more specific?

**Comment by gorkem** [comment]
If you look at the traces, server sends `language/status as 100%` but it takes a long time after the actual server started is sent.

**Comment by fbricon** [comment]
Apparently, this is caused by the monitor being set to 100% once the projects are imported, but then  we're waiting for a workspace build to set the server status as started.
