### ISSUE TITLE
Support of customizing generated method stub

### ISSUE THREAD

**Issue by pingu8007** [redhat-developer/vscode-java#1792]
Can I customize template of generated method stub?

##### Environment
- Operating System: Windows_NT x64 10.0.18363
- JDK version: JDK-8 (project) / JDK-14 (language server)
- Visual Studio Code version: 1.53.0 (user setup)
- Java extension version: v0.74.0

##### Steps To Reproduce
1. Implement an interface
2. Generate unimplemented method

##### Current Result
It generate something like this

```java
@Override
public String doSomething(String arg1) {
    // TODO Auto-generated method stub
    return null;
}
```

##### Expected Result
Although `return null` is acceptable, I would prefer it throw something more self-described just like `UnsupportedOperationException`.
```java
@Override
public String doSomething(String arg1) {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("Unimplemented method `doSomething(String)`");
}
```

##### Additional Informations
Nothing will be hurted without this feature. But I think it's a nice-to-have feature.

**Comment by lud** [comment]
That would be great.

The default stubs are footguns.

**Comment by akaroml** [comment]
@testforstephen this makes a lot of sense to me to throw exceptions instead of returning null. Do you think we can change it?

**Comment by rgrunber** [comment]
We can definitely customize these https://github.com/eclipse/eclipse.jdt.ls/blob/c7b80fcefa0b2182f6fe546ba9c0641570c96211/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/CodeTemplatePreferences.java#L176
