### ISSUE TITLE
‘\u’ is invalid in comments

### ISSUE THREAD

**Issue by JunjieChou** [redhat-developer/vscode-java#1796]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by Weidows** [comment]
- When I use `'\u'` in comment as follows

  ```Java
  // \demo3\utils\DbcpUtils.java
  
  /*
   * @FilePath: \demo3\utils\DbcpUtils.java
   */
  ```

- Where's an error :
  
  ```
  Invalid unicode
  ```

---

- But i found i can use `'\U'` or `'\xxx'` ,ext.
- `Help wanted.`

**Comment by apupier** [comment]
Hi,

`\u` is used to provide escaped Unicode characters.
You need to escape the `\` to specify to the compiler that in your case it needs to not be interpreted.

So writing something like:

```
// \demo3\\utils\DbcpUtils.java

/*
 * @FilePath: \demo3\\utils\DbcpUtils.java
 */
 ```
