### ISSUE TITLE
Formatting: limit column lines to 80

### ISSUE THREAD

**Issue by ItachiSan** [redhat-developer/vscode-java#180]
As in title.
Oracle suggest to limit the column lines to 80 as stated [here](http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-136091.html).
Google use 100.
Also, other IDEs (Eclipse and IntelliJ for sure) do hard-wrapping by default, if setted up properly.
So, the request can be expressed with such features:
- [ ] Add hard-wrapping to auto-format request
- [ ] Add a customizable number field for the hard-wrapping

##### Environment
- Operating System: Windows 10 and Linux
- JDK version: Java 8
- Visual Studio Code version: 1.11.1
- Java extension version: 0.1.0

##### Steps To Reproduce
1. Auto-format any Java code.

##### Current Result
Code is properly formatted, but no column limit is respected.
Soft-wrapping is present

##### Expected Result
To respect some column limit conventions.

##### Additional Informations
Will be added if requested or if the issue has progress.

**Comment by gorkem** [comment]
I think #2 will fix this.

**Comment by ItachiSan** [comment]
@gorkem hope so! If people can set the column numbers to any preferred ones, it would be great 😄
