### ISSUE TITLE
Import cannot be resolved but exist in JAR? 

### ISSUE THREAD

**Issue by vwkng** [redhat-developer/vscode-java#1804]
Hi everyone, when I do `import com.mypackage.abcde.ForecastRequestV1;`, I am getting the error: `The import com.mypackage.abcde cannot be resolved Java(268435846)`. 

In my project's .code-workspace file, under **"java.project.referencedLibraries"** I have the entry `"/path/to/my/jar-1.0.jar"`. When I open the jar file with vim, I see that `com/mypackage/abcde/ForecastRequestV1.class` is inside.

Does anyone know how I can go about debugging why VSCode is complaining that `com.mypackage.abcde` cannot be resolved?

(I've disabled all other JARs in my workspace and the results are the same)

##### Environment
- Operating System: Mac 
- JDK version: 11 
- Visual Studio Code version:1.53.1
- Java extension version:0.74.0

##### Steps To Reproduce
1. `import com.mypackage.abcde.ForecastRequestV1;`
2. See that the import cannot be found. 

##### Current Result
The import com.mypackage.abcde cannot be resolved

##### Expected Result
No import error.

**Comment by snjeza** [comment]
@vwkng could you attach your settings.json and .classpath?

**Comment by WarthaDev** [comment]
Use JDK version 1.8
