### ISSUE TITLE
how to debug jdk and edit jdk source code in vscode

### ISSUE THREAD

**Issue by ffashion** [redhat-developer/vscode-java#1805]
How should I debug and edit JDK source code
##### Environment
- Operating System:  Ubuntu20.04
- JDK version:   openjdk 15-internal
- Visual Studio Code version: 1.53.1
- Java extension version:  0.12.1
my user settings.json
``` json 
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    //set project jdk
    "java.configuration.runtimes": [
        {
          "name": "JavaSE-15",
          "path": "/home/fashion/Desktop/openjdk/build/linux-x86_64-server-slowdebug/images/jdk",
          "sources": "/home/fashion/Desktop/openjdk/build/linux-x86_64-server-slowdebug/support/src.zip",
          // "sources": "/home/fashion/Desktop/src!/",
          "default": true,
        },
        {
            "name" :"JavaSE-14",
            "path" :"/usr/lib/jvm/java-14-openjdk-amd64",
        },
      ],
      //set editor jre
      "java.home" :"/usr/lib/jvm/java-14-openjdk-amd64",
      "java.trace.server": "verbose"
}

```
now ,i can debug jdk but can't edit it , how can i  resolve it ,thanks

**Comment by testforstephen** [comment]
When you're using JDK as your program's runtime, it's taken as read-only system libraries. We didn't support editing and compiling the source code of the libraries. 

If your purpose is to edit jdk source code and debug it, you need find the contribution guide of the JDK project about that.
