### ISSUE TITLE
Is there a way to override .CLASSPATH file?

### ISSUE THREAD

**Issue by ShreyashSaitwal** [redhat-developer/vscode-java#1808]
### Environment
- Operating System: Windows 10
- JDK version: 11
- Visual Studio Code version: 1.53.2
- Java extension version: 0.75.0

Is there any way to override the .classpath file of my Java project? I want to do this because, for some reason, the vscode-java extension doesn't add my project's JAR files to the .classpath automatically and shows red squiggly lines under imports and whatnot. 

But when I manually edit the .classpath file that resides in `USER\AppData\Roaming\Code\User\workspaceStorage\<some_hash>\redhat.java\jdt_ws\<project_name>` these errors go away. I don't want to do this. I need to add my own .classpath file in the project's root, which currently doesn't work.

**Comment by snjeza** [comment]
@ShreyashSaitwal Could you attach your .project and .classpath files?

**Comment by ShreyashSaitwal** [comment]
.classpath
```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```
---
.project
```xml
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>jdt.ls-java-project</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
	</natures>
</projectDescription>
````

**Comment by snjeza** [comment]
@ShreyashSaitwal You can try the following:

- copy your project to a separate directory (myproject, for instance)
- change .project to
```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
	<name>myproject</name>
	<comment></comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.jdt.core.javanature</nature>
	</natures>
</projectDescription>
```
- open the myproject directory in VS Code

**Comment by ShreyashSaitwal** [comment]
Worked. 👍🏻
