### ISSUE TITLE
how to --enable-preview for standalone java file (neither maven nor gradle)

### ISSUE THREAD

**Issue by xetum** [redhat-developer/vscode-java#1812]
I want to use preview features of java 14 (`record`). I know I've to put in `launch.json`:

    "configurations": [
        {
            "vmArgs": "--enable-preview"
        }

but how to add option to the compiler stage? What to put in `settings.json`?

**Comment by testforstephen** [comment]
We just enable preview for the latest JDK (aka 15) by default, no way for old JDKs. If you just want to try record feature, you could install jdk 15, which also supports record.

**Comment by xetum** [comment]
I just installed jdk-15. Same error. record is underlined: `'record' is not a valid type name; it is a restricted identifier and not allowed as a type identifier in Java 15`. Language level shows JavaSE-15. How do I configure preview in Java 15 for standalone files?

**Comment by fbricon** [comment]
See https://github.com/redhat-developer/vscode-java/wiki/Enabling-Java-preview-features

**Comment by fbricon** [comment]
Can you share your file?

**Comment by xetum** [comment]
I just edited `settings.json` to add java-15 without reloading VScode. Now it works, thanks
