### ISSUE TITLE
How can I add bazel support?

### ISSUE THREAD

**Issue by dbushenko** [redhat-developer/vscode-java#1825]
Hello,

I'm trying to add bazel support to vascode-java using the lsp server. Unfortunately some hardcode in vscode-java prevents me from doing this. For instance, in standardLanguageClient.ts there is a function:

function isJavaConfigFile(path: String) {
	return path.endsWith('pom.xml') || path.endsWith('.gradle');
}

When the project file is updated, this function prevents from sending the command to eclipse.jdt.ls to update the project. More or less correct function should look like this:

function isJavaConfigFile(path: String) {
	return path.endsWith('pom.xml') || path.endsWith('.gradle')
		|| path.endsWith('BUILD') || path.endsWith('WORKSPACE');
}

But if the bazel support is not added to vscode, then this function will contain invalid behavior.

So my question is the following: what is the correct way to add bazel support in general and fix function isJavaConfigFile() in particular?

**Comment by jdneo** [comment]
Seems that we need to have a new contribution point that allow other extension to register the build file pattern. (Something like what we have for `javaExtensions` in package.json)

### Proposal

Maybe a new entry named as `javaBuildFilePatterns`? For example:

```
"javaBuildFilePatterns": ["BUILD", "WORKSPACE"]
```

Any other ideas are open for discussion.
