### ISSUE TITLE
regression: java.format.settings.url no longer loads project .xml file

### ISSUE THREAD

**Issue by rothfels** [redhat-developer/vscode-java#1827]
Some of our teammates just upgraded to the latest version of this extension and noticed that the formatter's behavior has changed.

Before upgrading extension:

- open a file, run `Format document` -- no diff

After upgrading extension:

- open a file, run `Format document` -- large diff

Our formatter configuration is and has been set from an .xml config file. Our `.vscode/settings.json` looks like this:

```
  "java.format.settings.url": "path/to/code-style.xml",
```

I opened the project in Eclipse and imported the same code-style.xml file, and verified that the Eclipse formatter running with that config produces no diff.

I've concluded the formatter on the most recent version of this extension has regressed.

##### Environment
- Operating System: `MacOS 11.2.1`
- JDK version: `openjdk version "15.0.1" 2020-10-20`
- Visual Studio Code version: `1.54.1`
- Java extension version: `v0.76.0`

##### Steps To Reproduce
1. Create custom code style .xml file
2. Configure via `.vscode/settings.json`
3. Run `Format document`

##### Current Result

Formatter generating unwanted diffs on newest extension version.

##### Expected Result

No formatting diffs on files that were formatted with prior extension version.

**Comment by rothfels** [comment]
It discovered works with a file URL:

```
  "java.format.settings.url": "file:///Users/me/path/to/code-style.xml",
```

However to make this work for the team I would need to use `${workspaceFolder}`, but this doesn't work with file URLs.

Please advise, a relative path to a project file sufficient before.

**Comment by lpedrosa** [comment]
What is the workaround that we can use in the meantime? 

For example, assuming you have the formatter file in the `${workspaceFolder}` like `${workspaceFolder}/eclipse-formatter.xml`, what should the url be?

Currently I have it set as `eclipse-formatter.xml` and it doesn't seem to pick it up.

**Comment by lpedrosa** [comment]
I guess I should've read @rothfels answer more carefully 😅, since it is mentioned that the URI could be relative to the `${workspaceFolder}`. 

A workaround for the scenario I've described above is to set the `java.format.settings.url` property like:

```bash
# assuming your formatter xml file in on ${workspaceFolder}
# and is called 'eclipse-formatter.xml'
"java.format.settings.url": "file:./eclipse-formatter.xml"
```

**Comment by boom-mug** [comment]
For me relative with ~ didn't work, nor did absolute, but adding file: did work, than you @rothfels .

**Comment by kristian** [comment]
Question: To mitigate this regression, we switched to the "file:" protocol as a workaround. After this regression is fixed, will the "file:" workaround break again or also continue to work, just to inform our developers. Thanks!

**Comment by snjeza** [comment]
@kristian It will work.

**Comment by llgcode** [comment]
Hi,
How to reference an absolute file path?
Not seems to work

```json
"java.format.settings.url": "file://E:/tools/config/eclipse-java-mystyle.xml",
```

**Comment by snjeza** [comment]
@llgcode Could you try

```
"java.format.settings.url": "file:///E:/tools/config/eclipse-java-mystyle.xml",
```

**Comment by llgcode** [comment]
Hi @snjeza 
it seems to load now, not error message in Java output console.
But I'm still not sure my profile (may be too old):

```xml
<setting id="org.eclipse.jdt.core.formatter.lineSplit" value="200"/>
```

When formatting, the code is splitted after 100 chars

Thank you for your help

**Comment by kristian** [comment]
Using this without the "file:" protocol again fails for me, is it also anyone else? Could there be another regression on this?

**Comment by snjeza** [comment]
> Using this without the "file:" protocol again fails for me, is it also anyone else? Could there be another regression on this?

The issue is related to https://github.com/eclipse/eclipse.jdt.ls/pull/1893
