### ISSUE TITLE
Add support in VS Code settings for THIRDPARTY_HOME

### ISSUE THREAD

**Issue by mbrdev** [redhat-developer/vscode-java#183]
Eclipse has a THIRDPARTY_HOME variable that can be used in .classpath files it would be great to have this in VS Code to avoid manually updating paths when cloning from source control.

**Comment by fbricon** [comment]
THIRDPARTY_HOME is not a standard Eclipse variable. But users can indeed set custom classpath variables in Eclipse.

We could probably support preferences like 
```json
java.configuration.classpath.variables: [
{ THIRDPARTY_HOME: "/some/path/"},
{ OTHER_VAR: "/some/other/path/"},
]
```

But I'm a bit skeptic about exposing more eclipse internals to the rest of the world. 
@gorkem WDYT?

**Comment by gorkem** [comment]
@fbricon agreed, maven & gradle is the only form of defining build paths we should really support.
