### ISSUE TITLE
Typo When Trying to Add Folder to Java Source Path That Is Already Included By Parent

### ISSUE THREAD

**Issue by b0ssi** [redhat-developer/vscode-java#1833]
Issue Type: <b>Bug</b>

The error that pops up when trying to add a folder to the source path (explorer > right-click on folder > *"Add Folder to Java Source Path"*) contains a minor grammatical mistake:

> Cannot add the folder '[path]' to the source path because it's parent folder is already in the source path of the project '[projectId]'.

I couldn't find where these strings are to be found spontaneously - if someone wants to point me into the right direction, happy to do it.

Extension version: 0.76.0
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.10.22-2-lts

**Comment by testforstephen** [comment]
https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java#L175

Feel free to open a pull request.

**Comment by b0ssi** [comment]
Cheers, [PR here](https://github.com/eclipse/eclipse.jdt.ls/pull/1687).

Couldn't find contribution info (spontaneously) re: what branch to branch off off/merge into and branch naming, so followed what I've seen being done in recent PRs. Let me know, easy to change.
