### ISSUE TITLE
regression: autobuild doesn't watch resources

### ISSUE THREAD

**Issue by rothfels** [redhat-developer/vscode-java#1834]
We have a `.classpath` like this:

```
<classpath>
	<classpathentry kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="target/classes" path="src/main/resources">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
        ...
```

Until recently, the Java language server would automatically update `target/classes` whenever files in `src/main/resources` would change. This was useful; we run a watch process in development to compile TS -> JS and output the generated code in `src/main/resources`.

Now, it seems only Java sources (in `src/main/java`) are being watched. The autobuild setting correctly generates new bytecode whenever .java files change. But it does not copy over resources that are updated.

We can work around this by putting our compiled resources directly in `target/classes`, but it seems like the language server should follow the classpath directives and do this automatically for us (as it used to). Instead, we now have to `Java: Force Java Compilation (Full)` to get the language server to copy over the resources whenever they change.

##### Environment
- Operating System: `MacOS 11.2.1`
- JDK version: `openjdk 15.0.1 2020-10-20`
- Visual Studio Code version: `1.54.3`
- Java extension version: `0.76.0`

**Comment by rubensa** [comment]
Looks like I have same problem.  Whenever I change a Java source file, looks like the file is compiled (at least syntax is checked and any error in the file is reported) but the rest of the classes are not validated (If, for example, I change a method name, errors from other classes referencing the old name are not shown in the PROBLEMS tab).  I have to **Java: Force Java Compilation (Full)** to get the errors.

**Environment**

-  Operating System: Ubuntu 20.04
- JDK version: AdoptOpenJDK (build 11.0.10+9)
- Visual Studio Code version: 1.54.3
- Java extension version: 0.76.0

**Comment by snjeza** [comment]
I can't reproduce the issue. Could you try the following:

- close VS Code
- remove all .project, .classpath and .settings files/directories
- start VS Code
- call [Clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)

**Comment by rubensa** [comment]
Looks like that fixed my problem.  Thanks @snjeza

**Comment by rothfels** [comment]
@snjeza my issue is still reproducible after following your troubleshooting steps. I don't think I have the same problem as @rubensa; he's complaining about Java source files. My issue is about resources in `src/main/resources`, not Java sources in `src/main/java` (we're using the [standard Maven directory](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) layout).

After following your steps, I still see that updating a file in `src/main/resources` will *not* update `target` until you manually run `Java: Force Java Compilation (Full)`. This was not always the case.

**Comment by snjeza** [comment]
> After following your steps, I still see that updating a file in src/main/resources will not update target until you manually run Java: Force Java Compilation (Full). This was not always the case.

@rothfels Could you attach your .project, .classpath and settings.json files?

**Comment by rothfels** [comment]
Sorry for the delay @snjeza. I made a [minimal example](https://github.com/rothfels/java-test) with our project configs.

However I cannot reproduce this issue in that project.

I dug a little deeper, I think there is something specific to our project causing this error:

```
!ENTRY org.eclipse.core.jobs 4 2 2021-04-16 09:06:57.377
!MESSAGE An internal error occurred during: "Register Watchers".
!STACK 0
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:421)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.addWatcher(StandardProjectsManager.java:479)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:404)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager$1.run(StandardProjectsManager.java:107)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-04-16 09:06:57.392
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.core.jobs 4 2 2021-04-16 09:06:57.394
!MESSAGE An internal error occurred during: "Initialize workspace".
!STACK 0
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:421)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.addWatcher(StandardProjectsManager.java:479)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:404)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:309)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

If this is not a general problem, feel free to close the issue.

If you have recommendations to help me identify the file/resource(s) causing this failure, please let me know. :)

**Comment by rothfels** [comment]
Ah, I think I found the cause.

Our Java project root is actually in a subdirectory of our repo/workspace: `${workspaceFolder}/java`

If I open the Java project root in VS Code, the file watcher initializes properly.

Is there a way to set the Java project root for the language server?

Perhaps this isn't a bug, but I think it's a regression from previous behavior. We didn't have problems with the file watcher until somewhat recently, whereas our project structure has been static for quite some time. We've always had our VS Code workspace root one directory above our Java project directory.

**Comment by snjeza** [comment]
@rothfels could you attach your settings. json or the java.format.settings.url property?

**Comment by rothfels** [comment]
`"java.format.settings.url": "file:developers/code-style.xml",`

^ we modified it to workaround https://github.com/redhat-developer/vscode-java/issues/1827

**Comment by rothfels** [comment]
Removing `java.format.settings.url` fixes the problem, so pretty clear the regression is from #1827

**Comment by snjeza** [comment]
@rothfels Could you try
```
"java.format.settings.url": "developers/code-style.xml",
```

**Comment by rothfels** [comment]
@snjeza yes, that also fixes the problem. Thank you.
