### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by kirankotari** [redhat-developer/vscode-java#1837]
Cannot uninstall 'Language Support for Java(TM) by Red Hat' extension. 'Java Test Runner' extension depends on this.

I had installed 0.76.0 and facing a issue with Java 11+, with the help other tickets I have downgraded it to 0.64.1 but it's still asking for 11+, I thought of uninstalling and installing again.

##### Environment
- Operating System: Cent Os
- JDK version: 1.8
- Visual Studio Code version: 1.54.1
- Java extension version: 1.64.1

##### Steps To Reproduce
1. install 0.76.0
2. downgrade to 0.64.1
3. It's still asking for java 11+
4. uninstall the extension

##### Expected
Looking for steps to uninstall

**Comment by kirankotari** [comment]
@fbricon how to it's dependencies any hint where can i look for them.

**Comment by fbricon** [comment]
VS Code doesn't provide a way to list extensions depending on one particular extension.
But, if you installed the Java Extension Pack (which lists its dependencies) and uninstall it, you'll most likely remove everything depending on Java. If that doesn't work you'll have to uninstall them one-by-one: remove extension 1 -> if blocked by extension 2, ten remove extension 2, rinse, repeat.

**Comment by apupier** [comment]
This can be improved efficiently at VS Code level only. Please vote for https://github.com/microsoft/vscode/issues/119243

**Comment by Hamza141** [comment]
I ended up manually deleting all the redhat.java* and vscjava* folders in the vscode [extensions folder](https://stackoverflow.com/a/36751445)

**Comment by fbricon** [comment]
Closing as https://github.com/microsoft/vscode/issues/119243 has been fixed upstream
