### ISSUE TITLE
gitRepository dependencies not recognized, but they should be

### ISSUE THREAD

**Issue by gabrielseaver9678** [redhat-developer/vscode-java#1844]
The problem is that vscode isn't recognizing gradle gitRepository at all. However, gradlew build works completely fine and the program runs as normal. Here are the error messages:
`The project cannot be built until build path errors are resolved`
`Project '[project name]' is missing required Java project: '[library name]'`
It also is showing problems with extending classes from the library, even though, again, the program built by gradlew functions perfectly when run.

**Comment by snjeza** [comment]
@gabrielseaver9678 could you attach your project or the build.gradle file(s)?
