### ISSUE TITLE
reachable code is prompted as dead code

### ISSUE THREAD

**Issue by shjyh** [redhat-developer/vscode-java#1846]
[provide a description of the issue]

##### Environment
- Operating System: windows 10 (19043.899)
- JDK version: openjdk 11
- Visual Studio Code version: 1.54.3
- Java extension version: 0.76.0

##### Steps To Reproduce

```java
public static Node findIntersectNodeWithNoLoop(Node h1, Node h2){
    if(h1 == null || h2 == null) return null;

    var p1 = h1;
    var p2 = h2;

    var n = 0;
    while(p1 != null){
        ++n;
        p1 = p1.next;
    }
    
    while(p2!=null){
        --n;
        p2 = p2.next;
    }

    if(p1 != p2) return null;
    
    p1 = n > 0 ? h1 : h2;
    p2 = p1 == h1 ? h2 : h1;

    n = Math.abs(n);
    while(n != 0){
        --n;
        p1 = p1.next;
    }
    while(p1 != p2){
        p1 = p1.next;
        p2 = p2.next;
    }

    return p1;
}
```
![image](https://user-images.githubusercontent.com/7910808/112325249-7a7c3e80-8cee-11eb-9a97-d411de5b47a3.png)

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

the yellow wavy underline told me this is **`dead code`**

##### Expected Result

the code is reachable

**Comment by fbricon** [comment]
The warning is correct.

The only way to exit each loop is for p1 and p2 to be null. 
So both are null, thus equal, when reaching the if statement. Making that block dead code.
