### ISSUE TITLE
How do I turn off plug-in version updates?

### ISSUE THREAD

**Issue by daidai21** [redhat-developer/vscode-java#1853]
[provide a description of the issue]

##### Environment
- Operating System: Don't need
- JDK version:Don't need
- Visual Studio Code version:Don't need
- Java extension version:Don't need

##### Steps To Reproduce

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

The background automatically updates to the latest version.

##### Expected Result

Keep the old version.

**Comment by snjeza** [comment]
@daidai21 you can add

```
 "update.mode": "manual"
```
to your settings.json

**Comment by 0dinD** [comment]
@snjeza @daidai21 I'm pretty sure the `update.mode` setting is for VS Code itself. Extension auto-updates can be disabled via the `extensions.autoUpdate` setting. If it's specifically the Java extension you don't want to auto-update it should also be possible by right clicking it in the extension gallery and selecting "Install Another Version..." (see microsoft/vscode#30579).

**Comment by testforstephen** [comment]
@daidai21 i believe @0dinD has answered your question, please have a try.

**Comment by daidai21** [comment]
thx all !
