### ISSUE TITLE
Java 16 doesn't require --enable-preview for Records, Pattern Matching, but VS Code still complains

### ISSUE THREAD

**Issue by murphye** [redhat-developer/vscode-java#1854]
I have upgraded to Java 16, and removed `--enable-preview` from my `pom.xml` for the `maven-compiler-plugin`.

<img width="652" alt="Screen Shot 2021-03-29 at 12 05 32 AM" src="https://user-images.githubusercontent.com/643097/112798931-7fa8f880-9022-11eb-98e8-5df7c6b109aa.png">

Because VS Code Java doesn't seem to recognize Java 16 and language changes in regards to preview, I still get this error:

<img width="901" alt="Screen Shot 2021-03-29 at 12 03 56 AM" src="https://user-images.githubusercontent.com/643097/112798830-525c4a80-9022-11eb-8a3a-20dfa39d24df.png">

I assume that you already are working on Java 16 support, but wanted to document this specific problem for you.

**Comment by murphye** [comment]
As a workaround, you can still use `--enable-preview` with Java 16, but also impacts the running `java` if you use it in compile, you must enable for runtime as well. Not very ideal.

**Comment by fbricon** [comment]
Java 16 support will be released in a few days. Until then you can try a CI build to play with it: https://download.jboss.org/jbosstools/jdt.ls/staging/java-0.77.0-108.vsix (later builds have Java 16 disabled temporarily, so stick with this one)

**Comment by rafaelcoelho** [comment]
The [redhat.java 0.77](https://download.jboss.org/jbosstools/jdt.ls/staging/java-0.77.0-108.vsix) extension works fine with latest VSCode version [VSCode 1.55](https://code.visualstudio.com/updates/v1_55).

I'm lookling forward to get release version 🚀

**Comment by ganzah** [comment]
Hi! Any update on this one? Version 0.77 was released, but I'm still having problems using java 16.

**Comment by fbricon** [comment]
We had to pull it from 0.77.0, but Java 16 support will be released in a couple days at most, in 0.78.0. In the meantime, you can test the latest CI build in https://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D


Fixed with #1891
