### ISSUE TITLE
The import com.sun.jdi cannot be resolved！

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#1861]
I am compiling the plug-in ***java-debug***, and the java file is imported into the package ***import com.sun.jdi.Location***;

##### Environment
- Operating System: Windows_NT x64 10.0.17134
- JDK version:15
- Visual Studio Code version:56
- Java extension version:76

##### Steps To Reproduce
1. settings.xml add 
```json
{
"java.completion.filteredTypes": [
		"java.awt.*"
    ],
}
```
but redhat-java Not effective

project location :
https://github.com/microsoft/java-debug.git

##### Current Result
error : 
The import com.sun.jdi cannot be resolvedJava(268435846)

![image](https://user-images.githubusercontent.com/63572041/113425027-bb1d3b80-9403-11eb-8c16-9d0cfb8cd867.png)

##### Expected Result
no error

**Comment by snjeza** [comment]
@mozhuanzuojing you can try the following patch:

```
diff --git a/com.microsoft.java.debug.core/pom.xml b/com.microsoft.java.debug.core/pom.xml
index 7c20a8a..8e06ec4 100644
--- a/com.microsoft.java.debug.core/pom.xml
+++ b/com.microsoft.java.debug.core/pom.xml
@@ -94,5 +94,20 @@
                 </dependency>
             </dependencies>
         </profile>
+        <profile>
+            <id>default-profile</id>
+            <activation>
+                <activeByDefault>true</activeByDefault>
+            </activation>
+            <dependencies>
+                <dependency>
+                    <groupId>com.sun</groupId>
+                    <artifactId>tools</artifactId>
+                    <version>1.8</version>
+                    <scope>system</scope>
+                    <systemPath>${YOUR_JDK8_HOME}/lib/tools.jar</systemPath>
+                </dependency>
+            </dependencies>
+        </profile>
     </profiles>
 </project>
```
