### ISSUE TITLE
Code completion on import is jamming code

### ISSUE THREAD

**Issue by Pascal-Klinkenbergh** [redhat-developer/vscode-java#1863]
https://user-images.githubusercontent.com/41929781/113493006-14589e00-94dc-11eb-991a-90b1eb1ac328.mov

Code completion on `import` is jamming code, as seen in the video.

##### Environment
- Operating System: macOS 11.2.3 (20D91)
- JDK version: adoptopenjdk-11-openj9.jdk
- Visual Studio Code version: March 2021 (version 1.55)
- Java extension version: Language Support for Java(TM) by Red Hat v0.76.0

Appears to only occur with the first `import` statement.

**Comment by snjeza** [comment]
Related issue - #1860

**Comment by testforstephen** [comment]
Duplicate, will use #1860 to track it.
