### ISSUE TITLE
Visual Code wrong workspace and project into this

### ISSUE THREAD

**Issue by drakgoku** [redhat-developer/vscode-java#1864]
https://stackoverflow.com/questions/66936942/visual-code-wrong-workspace-and-project-into-this

**Comment by testforstephen** [comment]
"Page Not Found".

Could you please share more details about the issue?

**Comment by drakgoku** [comment]
Stackoverflow deleted the post without notice. I am not going to rewrite what I wrote or the solution. You can thank Stackoverflow for his behavior.
