### ISSUE TITLE
Autocompletion is not cancelled on space

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#187]
If I have `Collection c = ne|` autocompletion will propose `new` among other things. If I continue typing without hitting tab or escape, then `new Arr`, despite the space, will continue proposing new and all other stuff containing  these letters.
<img width="652" alt="screen shot 2017-04-19 at 9 48 50 am" src="https://cloud.githubusercontent.com/assets/148698/25183422/8cf94726-24e5-11e7-9d5b-9f53b9c8183a.png">

I think hitting space should cancel autocompletion. But I'm not sure if it's a vscode proper or vscode-java configuration. @jrieken?

**Comment by jrieken** [comment]
That is happens when proposals still match. VS Code doesn't have a static rule when to hide/show/retrigger completions but uses the information provided by completions. Those are the `label` (and `filterText` if present) and the `range` of the completion (which defaults to the current word). The existing text that is *selected* by the `range` is used to score against `label`, in above sample `new Arr` against `NewLineEvent - groovyjarjarantlr.debug`.

> ne| autocompletion will propose new among other things.

Is this just `new` or a full ctor-call, like `new Collection`? Or is 'among other things' other globals like `NewLineEvent`?

**Comment by fbricon** [comment]
I just keep on typing, no Ctrl+Space involved. So new is proposed, as well as other classes:
![apr-19-2017 10-03-14](https://cloud.githubusercontent.com/assets/148698/25184132/8a3fad7a-24e7-11e7-9573-c03833469f15.gif)

**Comment by fbricon** [comment]
Ok, so the fact the labels contain spaces is fucking us up

```
{
            "label": "NewInstanceInstantiator - org.springframework.objenesis.instantiator.basic",
            "kind": 7,
            "sortText": "zzzzzzzdhc",
            "data": {
                "decl_signature": "Lorg.springframework.objenesis.instantiator.basic.NewInstanceInstantiator;",
                "pid": "16",
                "rid": "29",
                "uri": "file:/Users/fbricon/Dev/projects/spring-boot-mongodb/src/main/java/guru/springframework/SpringBootMongodbApplication.java"
            }
        },
        {
            "label": "new",
            "kind": 14,
            "sortText": "zzzzzzzbej",
            "data": {
                "pid": "17",
                "rid": "29",
                "uri": "file:/Users/fbricon/Dev/projects/spring-boot-mongodb/src/main/java/guru/springframework/SpringBootMongodbApplication.java"
            }
        }
```

**Comment by jrieken** [comment]
> Ok, so the fact the labels contain spaces is fucking us up

Yes, you could try putting that extra bit (`org.springframework.objenesis.instantiator.basic` et al) into detail

Works as I have to tried to describe above. What confuses me is that `ArrayList` is proposed towards the end of the gif. Are the completion lists you return marked as incomplete?

**Comment by fbricon** [comment]
Ok, I can try to put stuff into the detail field. Sounds better than my thinking about using some unicode trick to look like a space :-)

Seems we return `"isIncomplete": false`

**Comment by fbricon** [comment]
Ok so using `detail` seems to fix most of the problems when typing space. Changing all cases server-side to use `detail` is gonna be tedious, but doable. There would still be a minor problem with method completion though, because we display all overridden methods including parameters separated by space (We chose not to use SignatureHelp as we found it less productive), but I think that's manageable. 

But the main problem with using `detail` is the proposal needs to be selected for the detail to be displayed. Currently, you can see all proposals with a `Type - package` pattern. We'd lose that package information.

<img width="645" alt="screen shot 2017-04-19 at 11 03 15 am" src="https://cloud.githubusercontent.com/assets/148698/25187015/dfcf60ca-24ef-11e7-8f2e-1f63852d13ec.png">

**Comment by jrieken** [comment]
> But the main problem with using detail is the proposal needs to be selected for the detail to be displayed. Currently, you can see all proposals with a Type - package pattern. We'd lose that package information.

Yeah, that's part of our design of being minimal. /cc @stevencl

**Comment by fbricon** [comment]
@jrieken so as an alternative, I tried using [filterText](https://github.com/Microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#completion-request): 

```js
/**
 * A string that should be used when filtering a set of
 * completion items. When `falsy` the label is used.
 */
filterText?: string;
```

So our completionItems now look like
```json
{
  "label": "Map - java.util",
   "kind": 7,
   "sortText": "zzzzzzzbge",
   "filterText": "Map",
   "data": {
       "decl_signature": "Ljava.util.Map;",
       "pid": "62",
       "rid": "6",
       "uri": "file:/Users/fbricon/Dev/vertx-game-server/src/main/java/com/redhat/middleware/keynote/GameUtils.java"
     }
},
```

But vscode still seems to filter using the label
![may-15-2017 13-24-42](https://cloud.githubusercontent.com/assets/148698/26070249/ef46c688-3971-11e7-8694-0a59fc6d7cea.gif)

So either I don't grok how filterText is supposed to work or vscode ignores filterText. The former is the most plausible.

**Comment by jrieken** [comment]
> But vscode still seems to filter using the label

Yeah, we always try with the label first and use the filter text only when not matching the label. Mostly because when using the filter text we cannot render the blue highlights. But it could be considered a bug

**Comment by fbricon** [comment]
Initial tests with filterText and latest insiders build look good. Will provide a proper PR on jdt.ls soon.
