### ISSUE TITLE
fill

### ISSUE THREAD

**Issue by 1nrt0** [redhat-developer/vscode-java#1870]
Issue Type: <b>Feature Request</b>

{
"success":true,
"active":false,
"message":"<type> You're almost done ! wE SENT AN ACTIVATION MAIL TO <B>fakezabanfdsdhendas98d9188508d00dsf6@mail.ru<b>. Please follow the in struction sth email to activate your account,</
p><p>IFIT DOESN'T arrive, check your garbage files in mail box </p>",
"user_id":7777
 } zi xo
nutkase at Z

Extension version: 0.76.0
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.17134

**Comment by fbricon** [comment]
garbage
