### ISSUE TITLE
I can't run the same code twice

### ISSUE THREAD

**Issue by DumbestThan** [redhat-developer/vscode-java#1873]
[provide a description of the issue]
Every time I tried to run a java code (TWICE) it fails.
If I clicked the rubbish buttin for "kill the active terminal instances" it works, but if I clicked run again it stopped.

##### Environment
- Operating System:
- Windows 10 version 2004
- JDK version:
- 11.0.10
- Visual Studio Code version:
- 1.55.1
- Java extension version:
- 0.76.0

##### Steps To Reproduce
1. [step 1]
2. run the Java code
2. [step 2]
3. run it again

[Please attach a sample project reproducing the error]

https://user-images.githubusercontent.com/82240394/114447784-718ad880-9bdb-11eb-8e0e-c7f128989585.mp4

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
C:\Users\ٌRayan\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1 xterm.js: writeSync is unreliable and will be removed soon.
e._log @ C:\Users\ٌRayan\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\xterm\lib\xterm.js:1
/C:/Users/ٌRayan/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1917 Overwriting grammar scope name to file mapping for scope source.java.
Old grammar file: file:///c%3A/Users/%D9%8CRayan/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/java/syntaxes/java.tmLanguage.json.
New grammar file: file:///c%3A/Users/%D9%8CRayan/.vscode/extensions/redhat.java-0.76.0/syntaxes/java.tmLanguage.json
register @ /C:/Users/ٌRayan/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1917
/C:/Users/ٌRayan/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798 Extension Host
/C:/Users/ٌRayan/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798 {  message: 'Starting Java server with: C:\\Users\\ٌRayan\\AppData\\Local\\Programs\\AdoptOpenJDK\\jdk-11.0.10.9-hotspot\\bin\\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar c:\\Users\\ٌRayan\\.vscode\\extensions\\redhat.java-0.76.0\\server\\plugins\\org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration c:\\Users\\ٌRayan\\AppData\\Roaming\\Code\\User\\globalStorage\\redhat.java\\0.76.0\\config_ss_win -data c:\\Users\\ٌRayan\\AppData\\Roaming\\Code\\User\\workspaceStorage\\26dca011ebe91b906ce971d351becdb8\\redhat.java\\ss_ws',  level: 'info',  timestamp: '2021-04-12 21:59:54.009'}
/C:/Users/ٌRayan/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798 Extension Host
/C:/Users/ٌRayan/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2798 {  message: 'Starting Java server with: C:\\Users\\ٌRayan\\AppData\\Local\\Programs\\AdoptOpenJDK\\jdk-11.0.10.9-hotspot\\bin\\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar c:\\Users\\ٌRayan\\.vscode\\extensions\\redhat.java-0.76.0\\server\\plugins\\org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration c:\\Users\\ٌRayan\\AppData\\Roaming\\Code\\User\\globalStorage\\redhat.java\\0.76.0\\config_win -data c:\\Users\\ٌRayan\\AppData\\Roaming\\Code\\User\\workspaceStorage\\26dca011ebe91b906ce971d351becdb8\\redhat.java\\jdt_ws',  level: 'info',  timestamp: '2021-04-12 21:59:54.554'}
/C:/Users/ٌRayan/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:62 [Extension Host] Git installation not found.
v @ /C:/Users/ٌRayan/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:62

##### Current Result
![image](https://user-images.githubusercontent.com/82240394/114448206-ecec8a00-9bdb-11eb-8800-250df0a59b11.png)

##### Expected Result
printing "Hello, World!"

**Comment by testforstephen** [comment]
I cannot reproduce it with VS Code 1.55.1 and PowerShell as terminal. Can you try other terminals such as cmd?

![image](https://user-images.githubusercontent.com/14052197/114516265-ced06980-9c6f-11eb-98d5-922125c00d50.png)

Anyway, the run feature is provided by "Debugger for Java" extension, i moved this to the issue https://github.com/microsoft/vscode-java-debug/issues/979. Please use that issue for more discussion.
