### ISSUE TITLE
Syntax highlighting of Java "properties" files is broken with array syntax

### ISSUE THREAD

**Issue by ZigZag59** [redhat-developer/vscode-java#1878]
The syntax highlighting of Java "properties" files do not work with properties mapped with lists.

I am using SpringBoot with the @ConfigurationProperties directive for property mapping. My Java file contains a property : `List<String> myValues;`.

##### Environment
- Operating System: Windows_NT x64 10.0.19042
- JDK version: openjdk 11.0.9.1 2020-11-04 LTS
- Visual Studio Code version: 1.55.2 (user setup)
- Java extension version: v0.76.0

##### Steps To Reproduce
1. Open file with the ".properties" extension
2. Add the following lines :
project.properties.my-values[0]=value1
project.properties.my-values[1]=value2

##### Current Result
![SyntaxHighlightingResult](https://user-images.githubusercontent.com/46565570/114827287-c6d80d00-9dc8-11eb-9786-ff80d1118a5e.jpg)

##### Expected Result
![SyntaxHighlightingExpected](https://user-images.githubusercontent.com/46565570/114827293-c770a380-9dc8-11eb-9cc9-56dc84e59428.jpg)

**Comment by fbricon** [comment]
The textmate grammar for properties files is provided by VS Code proper: https://github.com/microsoft/vscode/blob/e51173f3b6f18f67a2ab9937374aa771f0483665/extensions/ini/package.json#L60-L62

Please open a ticket in the upstream repo: https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md
