### ISSUE TITLE
Java 16 Not Supported? 

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [redhat-developer/vscode-java#1879]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10
- JDK version: 16
- Visual Studio Code version: 1.55.2
- Java extension version: 0.76.0

##### Steps To Reproduce
1. Download Java JDK 16 from Java website
2. Add new name and path with "name" of java.configuration.runtimes" to JavaSE-16 instead of JavaSE-15

[Please attach a sample project reproducing the error]
(Projects are not really affected. Image below)
![image](https://user-images.githubusercontent.com/45579671/114833370-5b6c4c00-9d84-11eb-9099-e2d8f8380faf.png)

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
N/A
##### Current Result
Check photo
##### Expected Result
To work and not bounce up an error.

**Comment by delassiops** [comment]
Hi,

you can run your java program using jdk16 but visual studio know language level for the jdk15,

try using jdk 16 build from azul,

also set settings.json

{
    "java.home": "C:\\path_to_jdk16"
}

thanks

**Comment by rgrunber** [comment]
Java 16 language support will be added very soon. The plan is to release it as part of 0.78.0 which is planned for end of April, but likely should be coming by the end of next week.

**Comment by ENTPRESTIGIOUS** [comment]
> Java 16 language support will be added very soon. The plan is to release it as part of 0.78.0 which is planned for end of April, but likely should be coming by the end of next week.

Ahh okay, thought you guys forgot. Well thanks!
