### ISSUE TITLE
Java 16 Support 

### ISSUE THREAD

**Issue by Rafi-99** [redhat-developer/vscode-java#1896]
Is there any Java 16 Support? I am having problems with trying to get my code to compile.

![Screenshot 2021-04-23](https://user-images.githubusercontent.com/58924129/115932922-8d9c3e80-a453-11eb-9e2e-a7455742f616.png)

![image](https://user-images.githubusercontent.com/58924129/115933147-e66bd700-a453-11eb-8399-7bff2e3a33fe.png)

**Comment by TomerFi** [comment]
https://github.com/redhat-developer/vscode-java/issues/1879#issuecomment-821414335
