### ISSUE TITLE
Question: Getting Eclipse Workspaces to Open

### ISSUE THREAD

**Issue by jsinglet** [redhat-developer/vscode-java#190]
Hi,

I have a very complex eclipse workspace-based project with a number of interrelated projects. What are my prospects for getting something like this to be editable with this extension? Is that on the roadmap? Is it currently possible?

Best,
JLS

**Comment by fbricon** [comment]
It depends ;-)

Basic Java projects are supported. No JavaEE/WTP/PDE support though, this is not on the roadmap.
You have greater chances of seeing your projects being opened successfully if they're based on Maven or Gradle.

**Comment by fbricon** [comment]
To try it, simply open the root directory containing your projects. Eclipse project discovery is limited to 3 directories down the root, so it works best for projects in a flat layout.

**Comment by jsinglet** [comment]
Works! There are a few crashy looking things in the logs, but it mostly seems to work! Thanks for the info. Is there a built in way to run the projects with the eclipse run configurations?

**Comment by fbricon** [comment]
No. We have plans on [providing a debugger](https://github.com/redhat-developer/vscode-java/issues/9) (no ETA just yet), that will involve running code from vscode tasks, at some point. We haven't discussed whether we'll support running Eclipse Launch configurations.

**Comment by fbricon** [comment]
@jsinglet opening bugs for the crashy things you see might be helpful, [attaching logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging) and all ;-)

**Comment by fbricon** [comment]
Closing as the question has been answered. Please open new, specific tickets for bugs you encounter.
