### ISSUE TITLE
Extension in Visual Studio marketplace version 0.77.0 does not support JavaSE-16

### ISSUE THREAD

**Issue by zihengCat** [redhat-developer/vscode-java#1900]
Visual Studio Marketplace version `0.77.0` does not support `JavaSE-16`.

![Screen Shot 2021-04-25 at 11 54 02](https://user-images.githubusercontent.com/19472493/115980169-08349d80-a5bd-11eb-8fa7-5ec34c07f06a.png)

##### Environment
- Operating System: `Mac OS X 10.11.6 (15G31)`
- JDK version: `AdoptOpenJDK-16.0.1+9`
- Visual Studio Code version: `1.55.2`
- Java extension version: `0.77.0`

**Comment by TomerFi** [comment]
https://github.com/redhat-developer/vscode-java/issues/1879#issuecomment-821414335

**Comment by kdaham** [comment]
Any ETA on when 0.78 will be released?

**Comment by zihengCat** [comment]
Version 0.78.0 released, JavaSE-16 has been supported.
![Screen Shot 2021-04-30 at 16 23 25](https://user-images.githubusercontent.com/19472493/116668856-753a9f80-a9d0-11eb-92cf-f6f80f8b624c.png)
