### ISSUE TITLE
'java.apply.workspaceEdit' failed. error while auto importing

### ISSUE THREAD

**Issue by mrigankdembla** [redhat-developer/vscode-java#1901]
Whenever we are trying to do Alt+Enter for importing the package of any Java Class, we are seeing this error everytime "Running the contributed command: 'java.apply.workspaceEdit' failed." and it doesn't work

**Comment by rgrunber** [comment]
Do you have a sample project on which this can be reproduced ? Are you able to see any failures in the logs ?
