### ISSUE TITLE
Refactor method signature

### ISSUE THREAD

**Issue by itaygoz** [redhat-developer/vscode-java#1905]
##### Environment
- Operating System: WIN10
- JDK version: 11
- Visual Studio Code version: 1.55.2
- Java extension version: 0.77.0

There is no option to refactor method signature as in Eclipse.
I would like to have this feature here.

Thanks, Itay

**Comment by DreamFulFil** [comment]
It would be wonderful if this can be supported in the plugin

**Comment by fbricon** [comment]
What exactly are you missing? Can you give a concrete example?
<img width="449" alt="Screenshot 2021-07-28 at 11 01 30" src="https://user-images.githubusercontent.com/148698/127295188-9277a884-d5a3-4886-a39f-b44f9240336d.png">

**Comment by stefanrybacki** [comment]
> What exactly are you missing? Can you give a concrete example?
> <img alt="Screenshot 2021-07-28 at 11 01 30" width="449" src="https://user-images.githubusercontent.com/148698/127295188-9277a884-d5a3-4886-a39f-b44f9240336d.png">

It is missing the entire refactor method signature feature as stated.

**Comment by palunel** [comment]
I support this request.  There is no obvious way to refactor a method signature in Code.

**Comment by itaygoz** [comment]
Hi, any news?

**Comment by mbolis** [comment]
I need this badly, too.

As use case, I need to change the order of parameters in a method with many call sites.

**Comment by testforstephen** [comment]
Assign to @CsCherrYY since he is working on this.

**Comment by CsCherrYY** [comment]
supported via https://github.com/redhat-developer/vscode-java/pull/2967
