### ISSUE TITLE
Static css resources are not compiled by Java builder

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#1910]
When opening https://github.com/spring-projects/spring-petclinic in VS Code, everything is fine except that static css resources are not compiled. The reason for this is that this project uses a 3rd party maven plugin wro4j-maven-plugin to generate css from less files, but the plugin does not seem to be executed by Java builder of VS Code Java extension.

```xml
<plugin>
        <groupId>ro.isdc.wro4j</groupId>
        <artifactId>wro4j-maven-plugin</artifactId>
        <version>${wro4j.version}</version>
        <executions>
          <execution>
            <phase>generate-resources</phase>
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
...
</plugin>
```

**Comment by testforstephen** [comment]
A workaround is to configure an inline m2e lifecycle mapping for wro4j-maven-plugin.

```xml
<?m2e execute onConfiguration,onIncremental?>
```

```xml
<plugin>
        <groupId>ro.isdc.wro4j</groupId>
        <artifactId>wro4j-maven-plugin</artifactId>
        <version>${wro4j.version}</version>
        <executions>
          <execution>
            <phase>generate-resources</phase>
            <?m2e execute onConfiguration,onIncremental?> // Configure an inline m2e lifecycle mapping metadata.
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
       ...
<plugin>
```

**Comment by testforstephen** [comment]
This issue is similar as https://github.com/redhat-developer/vscode-java/issues/935 and https://github.com/redhat-developer/vscode-java/issues/177, where some custom source generation maven goals are not executed by m2e builder.

Since it is not trivial to improve m2e to automatically recognize these 3rd party maven plugins, one idea in my mind is that we provide quick fixes in the pom.xml if there are maven execution goals not executed by Java builder. If the user clicks the quick fix, it will insert the inline m2e lifecycle mapping to the pom.xml for the corresponding maven plugin.

// @fbricon @rgrunber thoughts?

**Comment by rgrunber** [comment]
Marking this as closed since we merged the patch that tries to improve this.
