### ISSUE TITLE
Java formatter switches to default settings every few days unless custom settings file is modified.

### ISSUE THREAD

**Issue by abrahammurciano** [redhat-developer/vscode-java#1925]
Every couple of days (this started a long time ago), the formatter stops using my custom `eclipse-formatter.xml` and goes back to use the default settings. In order to make it use mine again, I'm forced to modify the file. (I just bump the version number in the `<profiles>` tag.).

This happened when I used a URL and when I store the file locally. Currently I have the XML file in my workspace root, with my workspace `settings.json` containing this:
```json
"java.format.settings.url": "eclipse-formatter.xml"
```

##### Environment
- Operating System: Arch Linux (kernel 5.11.16-arch1-1)
- JDK version: openjdk 15.0.2 2021-01-19
- Visual Studio Code version: 1.55.2
- Java extension version: v0.79.1

##### Steps To Reproduce
1. Create a Java project.
2. Write some code.
3. Run VSCode command "Java: Open Java formatter settings".
4. Use the default name, create it when prompted.
5. Modify the settings, formatter will use modified settings.
6. Wait a few days.
7. Format the code again.

##### Example Project
https://github.com/abrahammurciano/rey-trace

##### Current Result
The formatter uses the default settings.

##### Expected Result
The formatter should use the modified settings.

**Comment by snjeza** [comment]
@abrahammurciano You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/1917#issuecomment-830652380
