### ISSUE TITLE
Java Language Server crashed when opening Spring Boot project

### ISSUE THREAD

**Issue by vasouv** [redhat-developer/vscode-java#1930]
When I open a Spring Boot project in VS Code, the Language Server seems to start but instead it generates a bunch of .dmp, .trc and javacore files. Please see screenshot below.

I have set JAVA_HOME in environment variables but not in VS Code settings (knowing it will look for the env variable).

This crash happened with JDK 15 and 14 as well, when it was released. If I recall correctly, when I set JDK 11 to JAVA_HOME, the crash didn't happen. But with JDK14+ it crashes.

I emptied the userWorkspace directory but there was no difference.

The core dmp files are large in size, 1+GB each. The javacore and jit dump ones are much smaller, the trc as well. I can upload them somewhere if they are needed.

![crash files](https://user-images.githubusercontent.com/65785/117257014-0f2c9d00-ae54-11eb-822b-e71689a91a19.png)

##### Environment
- Operating System: Windows 10 Home
- JDK version: AdoptOpenJDK 16.0.0.36-openj9
- Visual Studio Code version: 1.56
- Java extension version: 0.79.1

##### Steps To Reproduce
1. Download project from start.spring.io (Java 16, SB 2.5.0 RC)
[demo-project.zip](https://github.com/redhat-developer/vscode-java/files/6432483/demo-project.zip)

2. Open project in VS Code

##### Logs after crash
[dot log.log](https://github.com/redhat-developer/vscode-java/files/6432504/dot.log.log)

[client.log](https://github.com/redhat-developer/vscode-java/files/6432510/client.log)

**Comment by fbricon** [comment]
Can you try with an hotspot-based JDK 16?

**Comment by vasouv** [comment]
It worked with Hotspot! It didn't occur to me to try with other than OpenJ9 because the JDK11 that worked, was OpenJ9.

Many thanks Fred!
