### ISSUE TITLE
URGENT - JavaFX import issues

### ISSUE THREAD

**Issue by Nacandcheese** [redhat-developer/vscode-java#1932]
I have had dozens of issues as of recent, one being a classpath issue, and I thankfully got around it for the first time. It is still an ongoing issue, though, and will occasionally pop up. For now, though, I have a different issue popping up. Every time I try to import JavaFX, it states it is an invalid import, and all my code that is written specifically FOR JavaFX highlights.

Same as here:
# https://github.com/redhat-developer/vscode-java/issues/1886

Steps To Reproduce
1. Open up a project and import JavaFX
2. Try to use JavaFX to code. The errors should be right there.

[Test.zip](https://github.com/redhat-developer/vscode-java/files/6436868/Test.zip)

##### Current Result

Dozens of highlights in my program, and the inability to finish creating my JavaFX program (in test.zip)

##### Expected Result

A working JavaFX import for my project that is due in two days

**Comment by rgrunber** [comment]
What JDK version are you using for the project ? Does it actually contain the javafx libraries ?

For my Linux distro, Java 1.8.0 came with an optional package that includes javafx and it worked for me. However if I set my JDK for 11 and beyond, there was no such package, and it seems like javafx is expected to be downloaded like any other library from https://gluonhq.com/products/javafx/ .

**Comment by Nacandcheese** [comment]
> What JDK version are you using for the project ? Does it actually contain the javafx libraries ?
> 
> For my Linux distro, Java 1.8.0 came with an optional package that includes javafx and it worked for me. However if I set my JDK for 11 and beyond, there was no such package, and it seems like javafx is expected to be downloaded like any other library from https://gluonhq.com/products/javafx/ .

I sent a link to another issue I posted just a couple of weeks ago that should have the JDK and everything. Test.zip should also contain my own JDK for this, as this was a school project I am working on. I will check the link you have sent, however, and see if that does fix anything.

**Comment by Nacandcheese** [comment]
Alright, I went through the installation, and set up everything. Everything works really well, and in the process, my other issue seems to have died down a bit. Thanks so much for helping, @rgrunber !

**Comment by fbricon** [comment]
@Nacandcheese you need to import the JavaFX classes in your code

```java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

//_______________\\
/*                 *\
|Dominic DeLaughter |
|JDK version 15.0.2 |
\*_________________*/
//A program that asks if you want to get more groceries. Nothing but a simple UI and images, but hey, everything works.
public class Groceries extends Application
{
    public static void main(String[] args)
    {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage)
    {
        primaryStage.setTitle("Out of groceries!");
        Label label1 = new Label("It seems you are out of groceries. Would you like more?");
        Button button1 = new Button("Yes");
        VBox vbox = new VBox(label1, button1);
        Scene scene = new Scene(vbox);
        
        Image image = new Image("file:Store.gif");
        ImageView imageView = new ImageView(image);
        imageView.setPreserveRatio(true);

        primaryStage.setScene(scene);
        primaryStage.show();
    }
}

```
