### ISSUE TITLE
java.settings.url preference not working

### ISSUE THREAD

**Issue by carlgmz** [redhat-developer/vscode-java#1939]
I want to disable globally the warning `org.eclipse.jdt.core.compiler.problem.staticAccessReceiver`. For that, I have set the preference in Eclipse, exported the preference file from Eclipse, and set the property `java.settings.url` to the exported file (I tried both a file:// URL and the absolute path). In both cases, the extension shows the disabled warning in the problems view.

##### Environment
- Operating System: Arch Linux 5.12.1-arch1-1 on x86_64
- JDK version: 11.0.11
- Visual Studio Code version: 1.56.0
- Java extension version: 0.79.1

[settings.prefs.txt](https://github.com/redhat-developer/vscode-java/files/6451503/settings.prefs.txt)

##### Steps To Reproduce
1. Set the global preferences to the attached file
2. Write Java code accessing a static field through an object instance.

##### Current Result

The static access warning is reported

##### Expected Result

The warning is not reported

##### Additional Informations

If the preference is set in the project's prefs file, it is honored.

**Comment by rgrunber** [comment]
One case I'm aware of that has issues is modifying `java.settings.url` through some external tool (eg. some other editor) while VSCode is running. It came down to having trouble responding to changes in external files (hence why project-level files work).

Not sure if this that situation, but I've seen such behaviour.

**Comment by snjeza** [comment]
@carlgmz could you try 
[settings.prefs.txt](https://github.com/redhat-developer/vscode-java/files/6453360/settings.prefs.txt)

**Comment by carlgmz** [comment]
Thank you, @snjeza, that worked.

I see the format is plain preferences, instead of the format produced by the Eclipse preference exportation (I was using Eclipse 2021-03). I think the [Setting global preferences](https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences) guide should be updated.

Thank you!

**Comment by snjeza** [comment]
@carlgmz There is a bug. I'm preparing a fix.
