### ISSUE TITLE
...

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#1945]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by rgrunber** [comment]
I'm able to reproduce and it seems like its enforced by the default formatter. Specifically, [`FORMATTER_LINE_SPLITS`](https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/formatter/org/eclipse/jdt/core/formatter/DefaultCodeFormatterConstants.java#L5041), at 120 characters, and 80 for comments. There's a few ways to get around this for now :

1) Disable the formatter, which would probably be a bit extreme, but can be done. In settings, simply disable under Java -> Format -> Enabled. You can also just add the option `"java.format.enabled": true` to `.vscode/settings.json`

2) Create your own custom formatter. I created a file `never-wrap.xml` :
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="21">
    <profile kind="CodeFormatterProfile" name="test" version="21">
        <setting id="org.eclipse.jdt.core.formatter.lineSplit" value="500"/>
        <setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="500"/>
    </profile>
</profiles>
```
and I created a settings file `.vscode/settings.json` in the project :
```
{
    "java.format.settings.url": "/path/to/never-wrap.xml"
}
```

For more information on how to create the xml file, see https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings .

**Comment by zhouxinghong** [comment]
Thank you for your help, you are great, great, great!
1. The setting "java.format.enabled": false will disable all Java formatting, which is not what I want. I just don't want to force line breaks. You can choose line breaks to keep the format consistent with the interllij idea. Therefore it is not feasible.
3. Create your own custom format.
Create a file: never-wrap.xml
I am currently using this method, but it is forced to wrap, so it is not feasible.
2. Add to the preference settings file
You can create or attach to the workspace called: .settings/org.eclipse.jdt.core.prefs
This configuration will overwrite other Java custom format configurations in the "java.format.settings.url": "/java/eclipse-format.xml" file, so it is not feasible.
This is a bug that directly affects the basic coding standards and cannot be consistent with the formatting of the IDEA editor.
