### ISSUE TITLE
File contents would be strange when renaming java file name (with lombok)

### ISSUE THREAD

**Issue by vagusX** [redhat-developer/vscode-java#1951]
File contents would be strange when renaming java file name (with lombok)

##### Environment
- Operating System: MacOS
- JDK version: jdk8
- Visual Studio Code version: 1.56.2
- Java extension version: v0.79.1 

##### Steps To Reproduce
1. Renaming on `src/main/java/com/example/foo/DataExample.java`
2. Accept additional edits from vscode-java/jdt.ls 
3. You will see: the `@Data public` will be replaced with the new interface name

![image](https://user-images.githubusercontent.com/6828924/118643862-acea7980-b80f-11eb-9021-44668a92aba4.png)

https://user-images.githubusercontent.com/6828924/118749240-b3b8d100-b88f-11eb-90af-8408088a9fb3.mp4

Log File

[log.txt](https://github.com/redhat-developer/vscode-java/files/6505666/log.txt)

Sample Project
https://github.com/vagusX/spring-boot-with-lombok

##### Current Result
`@Data public` will be replaced with the new interface name

##### Expected Result

Just change interface name and keep `@Data public`

##### Additional Informations

with vscode-lombok v1.0.1

This is the response `WorkspaceEdit` payload from jdt.ls server in vscode-java extension

![image](https://user-images.githubusercontent.com/6828924/118773045-fb9f1e80-b8b6-11eb-8eff-0943857bb4d0.png)

```json
[
  [
    {
      "$mid": 1,
      "external": "file:///Users/vagusx/Project/test/spring-boot/src/main/java/com/example/foo/DataExample.java",
      "path": "/Users/vagusx/Project/test/spring-boot/src/main/java/com/example/foo/DataExample.java",
      "scheme": "file"
    },
    [
      {
        "_range": [
          {
            "line": 7,
            "character": 0
          },
          {
            "line": 8,
            "character": 24
          }
        ],
        "_newText": "ABCDataExamplec class ABCDataExample"
      }
    ]
  ],
  [
    {
      "$mid": 1,
      "external": "file:///Users/vagusx/Project/test/spring-boot/src/main/java/com/example/demo/DemoApplication.java",
      "path": "/Users/vagusx/Project/test/spring-boot/src/main/java/com/example/demo/DemoApplication.java",
      "scheme": "file"
    },
    [
      {
        "_range": [
          {
            "line": 2,
            "character": 23
          },
          {
            "line": 12,
            "character": 13
          }
        ],
        "_newText": "ABCDataExample;\nimport com.example.bar.TestSample;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class DemoApplication {\n\n\tpublic static void main(String[] args) {\n\t\tABCDataExample"
      }
    ]
  ]
]
```

**Comment by vagusX** [comment]
This is the response `WorkspaceEdit` payload from jdt.ls server in vscode-java extension

![image](https://user-images.githubusercontent.com/6828924/118773045-fb9f1e80-b8b6-11eb-8eff-0943857bb4d0.png)

```json
[
  [
    {
      "$mid": 1,
      "external": "file:///Users/vagusx/Project/test/spring-boot/src/main/java/com/example/foo/DataExample.java",
      "path": "/Users/vagusx/Project/test/spring-boot/src/main/java/com/example/foo/DataExample.java",
      "scheme": "file"
    },
    [
      {
        "_range": [
          {
            "line": 7,
            "character": 0
          },
          {
            "line": 8,
            "character": 24
          }
        ],
        "_newText": "ABCDataExamplec class ABCDataExample"
      }
    ]
  ],
  [
    {
      "$mid": 1,
      "external": "file:///Users/vagusx/Project/test/spring-boot/src/main/java/com/example/demo/DemoApplication.java",
      "path": "/Users/vagusx/Project/test/spring-boot/src/main/java/com/example/demo/DemoApplication.java",
      "scheme": "file"
    },
    [
      {
        "_range": [
          {
            "line": 2,
            "character": 23
          },
          {
            "line": 12,
            "character": 13
          }
        ],
        "_newText": "ABCDataExample;\nimport com.example.bar.TestSample;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class DemoApplication {\n\n\tpublic static void main(String[] args) {\n\t\tABCDataExample"
      }
    ]
  ]
]
```

**Comment by snjeza** [comment]
@vagusX Could you check https://github.com/snjeza/vscode-test/raw/master/java-0.80.1.vsix ?

**Comment by vagusX** [comment]
@snjeza it works as expected 👍

**Comment by snjeza** [comment]
See https://github.com/eclipse/eclipse.jdt.ls/pull/1779

**Comment by vagusX** [comment]
Just wondering when it would ship out so I could use the stable version vsix
