### ISSUE TITLE
Explicitly report OutOfMemory error to user

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#1959]
When opening some large Java projects (e.g. https://github.com/Azure/azure-sdk-for-java) in VS Code, the language server may fail silently due to OutOfMemory error. The setting `"java.jdt.ls.vmargs"` of Java extension specifies a default `"-Xmx1G"` memory during starting language server, that's not enough for some large project. We need some way to explicitly tell user to increase the memory args in this case.

**Comment by rgrunber** [comment]
Relevant : https://github.com/microsoft/vscode-languageserver-node/issues/688
