### ISSUE TITLE
when programming a swing application, it offers to import from javax.swing but not from java.awt

### ISSUE THREAD

**Issue by xetum** [redhat-developer/vscode-java#1966]
Sure it's a misconfigured option but when editing a swing application, extension doesn't detect automatically lacking imports from p.e. `java.awt`. Hovewer symbols from `javax.swing` are detected. Code sample:

    public class A {
        public void a() {
            JButton c; // import 'JButton' (javax.swing)
            Button d;  // doesn't offer import 'Button' (java.awt)
        }
    }

**Comment by fbricon** [comment]
By default, vscode-java [hides](https://github.com/redhat-developer/vscode-java/issues/710) "java.awt.*" from completion/auto import. You can edit the `java.completion.filteredTypes` preference in your settings to remove the `java.awt.*` exclusion, like: 
```json
"java.completion.filteredTypes": [
    "com.sun.*",
    "sun.*"
]
```

**Comment by xetum** [comment]
Checked, but can I know why? including j`ava.awt` package is quite usual...
