### ISSUE TITLE
Code is compiled with preview features for no reason, causing the project not to run

### ISSUE THREAD

**Issue by Artur-** [redhat-developer/vscode-java#1971]
Seemingly after running "Clean the Java language server workspace" my project no longer works properly.

Any time VS code compiles a Java file in my project, the version is set to `60.65535` which apparently indicates it has enabled preview features for some reason. I am using Java 16 and not using any preview features in the code.

Because this happens, running the project using Maven with the same Java 16 fails with
```
classfile for /.../DataUtil.class uses preview features of Java SE 16.
  (use --enable-preview to allow loading of classfiles which contain preview features)
```
Then I need to clean the project outside VS Code, run `mvn install` again and everything works fine.

I have not added `--enable-preview` which the FAQ says you should do for VS Code to enable preview features: https://code.visualstudio.com/docs/java/java-faq#_how-can-i-use-visual-studio-code-with-new-java-versions

The only even remotely new feature used in the project is text blocks `"""` but those haven't been in preview for quite some time.

##### Environment
- Operating System: macOS Big Sur
- JDK version: 16
- Visual Studio Code version: 1.56.2
- Java extension version: 0.79.2

##### Steps To Reproduce
Not sure

**Comment by Artur-** [comment]
Adding
```
org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=disabled
```

to `.settings/org.eclipse.jdt.core.prefs` apparently works around the problem

**Comment by rgrunber** [comment]
We only force `org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures` to `enabled` if Java 16 is used and the project is also unmanaged (eg. not Maven, Gradle, etc.). However, since your project is clearly Maven, I don't think this should be happening.

Are you able to share the full project ? The project without sources ? Just the poms ?

**Comment by Artur-** [comment]
It is a private project. I tried to reproduce it in another project but was unable to. I suspected either text blocks or using Lombok to be causing it but neither seems to do it in another project.

Is there an easy way for me to see/debug why it enables preview features?

**Comment by rgrunber** [comment]
Yes, it should be in https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/JVMConfigurator.java#L344 . I believe it's the only place we enable preview features.

**Comment by snjeza** [comment]
Steps to reproduce:

- set VS Code preferences
```
"java.server.launchMode": "Hybrid",
"java.home": "<jdk16_home>",
```
- git clone https://github.com/mac-comp127/welcome-app.git
- cd welcome-app
- code .
- run Java: Clean Java Language Server Workspace

It is always reproducible.

**Comment by snjeza** [comment]
@fbricon @rgrunber @Artur- @pcantrell Could you try to reproduce the issue using https://github.com/snjeza/vscode-test/raw/master/java-0.82.3.vsix

**Comment by fbricon** [comment]
@snjeza that works for me

**Comment by snjeza** [comment]
> that works for me

@fbricon Thanks. I will try to create a PR with a test.
