### ISSUE TITLE
MAVEN clean lifecycle command errors out

### ISSUE THREAD

**Issue by dbnex14** [redhat-developer/vscode-java#1973]
[provide a description of the issue]
Maven clean lifecycle command fails with error below

##### Environment
- Operating System: Windows 10
- JDK version: 11
- Visual Studio Code version: 1.56.2
- Java extension version: Not sure where to find this information

##### Steps To Reproduce

1. In VSC, I created a Springboot project.
2. When I open the project in VSC, there is tab named MAVEN
3. In there there are LIfecycle methods for maven
4. When I run clean lifecicly method, I get error shown below.

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
I get following error
```
C:\Windows>"\\path-to-my-project\mvnw.cmd" clean -f "\\path-to-my-project\pom.xml"
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:1 char:282
+ ... pe]::Tls12; $webclient.DownloadFile('https://repo.maven.apache.org/ma ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
```

##### Expected Result
clean maven lifecycle command should execute

**Comment by testforstephen** [comment]
Could you please move the issue to https://github.com/microsoft/vscode-maven/issues, which is the owner of Maven explorer. It's better to share a sample project there to help reproduce the issue.

**Comment by Eskibear** [comment]
See https://github.com/microsoft/vscode-maven/issues/606#issuecomment-819170892
