### ISSUE TITLE
openjdk 15 is not getting recognized

### ISSUE THREAD

**Issue by akhiljns** [redhat-developer/vscode-java#1979]
[provide a description of the issue]

##### Environment
- Operating System: windows
- JDK version: 15.0.1
- Visual Studio Code version: 1.57.0
- Java extension version: 0.79.2

##### Steps To Reproduce
1. add to vs code settings.json

 "java.configuration.runtimes": [
 {
            "name": "JavaSE-15",
            "path": "C:\\Program Files\\Java\\jdk-15.0.1",
            "default": true
 }
]

##### Current Result

failing to recognize java 15 and recognizes as JavaSE-1.7
fails to register lambda expressions

##### Expected Result

recognize java 15 and recognizes as JavaSE-15

**Comment by snjeza** [comment]
@akhiljns could you try
```
"java.configuration.runtimes": [
{
"name": "JavaSE-15",
"path": "C:\\Program Files\\Java\\jdk-15.0.1",
"default": true
}
]
```
backslashes on Windows must be escaped.

**Comment by akhiljns** [comment]
@snjeza 

I have tried this already, it's mentioned in the description of the issue, it makes no difference in recognition.

**Comment by snjeza** [comment]
Could you show your project?

**Comment by testforstephen** [comment]
> failing to recognize java 15 and recognizes as JavaSE-1.7
> fails to register lambda expressions

The compiler level is controlled by your project's build file, not by setting `"java.configuration.runtimes"`, which is only used to map a correct runtime to your project compiler level. 

Here is how to change your project JDK level.

In pom.xml of a Maven project:
```xml
<properties>
  <maven.compiler.source>1.8</maven.compiler.source>
  <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```

In build.gradle of a Gradle project:
```groovy
sourceCompatibility = 1.8
targetCompatibility = 1.8
```
