### ISSUE TITLE
Unable to run azure function through Visual studio code

### ISSUE THREAD

**Issue by sashwinee** [redhat-developer/vscode-java#1985]
Please refer below link for more details of the issue. 
I have posted all required information here:

https://stackoverflow.com/questions/67998376/azure-functions-java-project-visual-studio-code-error-for-dependencies

I have tried it with both jdk 8 and jdk 11 but no luck.

expected results:
to be able to run Azure function through VS mentioned here -
https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-vs-code?pivots=programming-language-java.

Any help would be appreciated. Thanks in advance.

**Comment by jdneo** [comment]
@Flanker32 Could you please help take a look at this. :)

**Comment by Flanker32** [comment]
@sashwinee Thanks for your report and sorry for the trouble, it seems that the project is generated by an deprecated version of archetype. Could you please upgrade to the latest VSCode Azure Functions extension and try again? If the issue still reproduce, could you please try clean the local cached archetype (in `%YOUR_M2_HOME%\com\microsoft\azure\azure-functions-archetype`) and retry?

Besides, as a workaround, you may generate the project with maven archetype directly by `mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype -DarchetypeVersion=1.39` and import the result to VSCode.

**Comment by jdneo** [comment]
Closing as it's inactive for a long time.

If you still have questions, please file issues at: https://github.com/microsoft/vscode-azurefunctions/issues
