### ISSUE TITLE
Add additional variables for java.template snippets

### ISSUE THREAD

**Issue by JasonWThompson** [redhat-developer/vscode-java#1987]
Like most teams, I have a required set of content that belongs in the header of my Java documents. One of the required items is a creation date. The format of the creation date is _shortmonth day, year_. So something like Jan 24, 2025. There doesn't seem to be a way using the predefined variables to add this to my template. Using `${date}` gets me `1/24/2025`. Using `${month} ${day}, ${year}` gets me `01 24, 2025`.

I would like it if `shortmonth` was added as a predefined variable. There are likely additional predefined variables that other developers would want.

##### Environment
- Operating System: Windows 10
- JDK version: JDK 11
- Visual Studio Code version: 1.57.1
- Java extension version: 0.79.2

##### Steps To Reproduce
1. Configure template in the settings file.
2. Create a new file.

##### Current Result
It is not possible to generate a date in the format required by my team.

##### Expected Result
It is possible to generate a date in the format required by my team.

##### Additional Informations
Documentation for existing predefined variables: https://github.com/redhat-developer/vscode-java/wiki/Predefined-Variables-for-Java-Template-Snippets

Example template configuration
```
    "java.templates.fileHeader": [
        "/**",
        " * Created: ${date}",
        " */"
    ],
```

**Comment by rgrunber** [comment]
Something like this should probably work.

```
diff --git a/src/fileEventHandler.ts b/src/fileEventHandler.ts
index fca00b2..d53eae9 100644
--- a/src/fileEventHandler.ts
+++ b/src/fileEventHandler.ts
@@ -71,6 +71,7 @@ async function handleNewJavaFiles(e: FileCreateEvent) {
             time: date.toLocaleTimeString(),
             year: date.getFullYear(),
             month: formatNumber(date.getMonth()),
+            shortmonth: date.toLocaleDateString(undefined, {"month": "short"}),
             day: formatNumber(date.getDay()),
             hour: formatNumber(date.getHours()),
             minute: formatNumber(date.getMinutes()),
```
