### ISSUE TITLE
Type mismatch: cannot convert from Map<Boolean,List<Integer>> to Map<Boolean,List<Integer>>

### ISSUE THREAD

**Issue by donkey55** [redhat-developer/vscode-java#1988]
When I try to run the following code, Vscode tell me this error: Type mismatch: cannot convert from Map<Boolean,List<Integer>> to Map<Boolean,List<Integer>>Java(16777233)
Environment: 
* Operating System: Windows 10
* JDK version: JDK 16
* Visual Studio Code version: 1.57.1
* Java extension version: 0.79.2

Code :
```Java
public static void main(String[] args) {
        List<Integer> foo = Arrays.asList(1,2,3,4,5);
        Map <Boolean, List<Integer>> bar = foo.stream().collect(Collectors.partitioningBy(item -> item > 2));
        System.out.println(foo.get(false));
    }
```

**Comment by testforstephen** [comment]
The snippet works for me. Could you share the sample project you used?

![image](https://user-images.githubusercontent.com/14052197/122697041-11698000-d277-11eb-917c-5a41d6a9fc38.png)

**Comment by donkey55** [comment]
Thanks!
This is my problem.
I forget to import the java.util.Map
