### ISSUE TITLE
The tool didn't generate the correct classpath for a maven project with multiple compile executions

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#1989]
Here is a minimum sample maven project [**parentproject.zip**](https://github.com/redhat-developer/vscode-java/files/6685281/parentproject.zip) to reproduce the issue.
```
parentproject
├── app
│   ├── pom.xml
│   ├── src
│   │   └── main
│   │       └── java
│   │           ├── com
│   │           │   └── example
│   │           │       └── App.java
│   │           └── module-info.java
├── core
│   ├── pom.xml
│   ├── src
│   │   ├── main
│   │   │   └── java
│   │   │       ├── core
│   │   │       │   └── util
│   │   │       │       └── WorkerUtil.java
│   │   │       └── module-info.java
│   
└── pom.xml
```

The submodule `app` is a normal Java 9+ module, the generate .classpath is correct.

The submodule `core` is a common SDK library that's expected to be compatible with both Java 9 modular and Java 8. So its pom.xml defines two compile executions in the maven-compiler-plugin. The first time it is compiled with module-info for Java 9+, the second time it is compiled without module-info.java. When importing such a module in VS Code, the Java extension doesn't handle its classpath very well. The Java extension recognizes it as Java 11 project and compiles it only to Java 11 classes, that's no problem. The problem is that it excludes the module-info.java from its source path.

The pom.xml of the module `core`:
```xml
<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version> <!-- {x-version-update;org.apache.maven.plugins:maven-compiler-plugin;external_dependency} -->
        <executions>
          <!-- compile first with module-info for Java 9+ -->
          <execution>
            <id>default-compile</id>
            <configuration>
              <release>11</release>
            </configuration>
          </execution>
          <!-- then compile without module-info for Java 8 -->
          <execution>
            <id>base-compile</id>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <release>8</release>
              <excludes>
                <exclude>module-info.java</exclude>
              </excludes>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
</build>
```

The generated .classpath of module `core`:
```xml
<classpath>
	<classpathentry excluding="module-info.java" kind="src" output="target/classes" path="src/main/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	...
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11">
		<attributes>
			<attribute name="maven.pomderived" value="true"/>
		</attributes>
	</classpathentry>
	...
</classpath>
```

**Expected:**
The JDT compiler can only choose to compile once, which is fine. But when it selects this project `core` as Java 11, it should not exclude module-info.java from the source path.

This problem also exists in Eclipse and should be an issue with m2e importer.

**Comment by testforstephen** [comment]
The upstream issue: https://github.com/eclipse-m2e/m2e-core/issues/246

**Comment by snjeza** [comment]
> The upstream issue: eclipse-m2e/m2e-core#246

The upstream issue has been fixed.
