### ISSUE TITLE
Unused method/constructor parameters show no warning

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#199]
Unused method/constructor parameters show no warning

##### Steps To Reproduce
1. Create a method with a parameter
2. the parameter should be unused

##### Current Result
No warning is displayed
<img width="504" alt="screen shot 2017-05-04 at 10 23 13 am" src="https://cloud.githubusercontent.com/assets/148698/25713236/0983ede0-30c2-11e7-8db0-61a8dc822b53.png">

##### Expected Result
A warning should be displayed, like for unused local variables

**Comment by fbricon** [comment]
This is actually the same behaviour in Eclipse, so not a bug

**Comment by fbricon** [comment]
We probably don't want to generate a warning actually, in case a method is being overridden, it's ok for the params not to be used.

**Comment by matter-it-does** [comment]
Could it be optional at least.. Idea generates this optionally. @snjeza  ?

**Comment by Trass3r** [comment]
I agree, can't it be an controlled by a setting?
