### ISSUE TITLE
java build status doesn't work

### ISSUE THREAD

**Issue by whitesweet** [redhat-developer/vscode-java#1990]
- Issue Type: `Bug`
- Extension Name: `java`
- Extension Version: `0.79.2`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.57.1`

I import a maven project. but i cannot open java build status terminal. 

and I get a bug can be reported in running extesions view .

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 50,
		"activateCallTime": 20,
		"activateResolvedTime": 13831,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscjava.vscode-java-test",
				"_lower": "vscjava.vscode-java-test"
			},
			"activationEvent": "onLanguage:java"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "write after end"
		}
	]
}
```
![无标题](https://user-images.githubusercontent.com/15253628/122850921-a1bfc780-d340-11eb-9341-931f0563bc78.png)

**Comment by jdneo** [comment]
The test runner should not affect the logs in the `Java Build Status`, they should be two separate issues.

Meanwhile, If you update the extension `vscjava.vscode-java-test` to latest (0.30.1), will you still see the errors?

**Comment by whitesweet** [comment]
@jdneo thanks.
vscjava.vscode-java-test is the latest  (0.30.1), but the issue still exists. 
It seams that only terminal cannot display correctly. All java features I used work well.

**Comment by jdneo** [comment]
By saying `terminal cannot display correctly`, do you mean nothing shows in the terminal?

Or could you provide some screenshots?

**Comment by whitesweet** [comment]
![image](https://user-images.githubusercontent.com/15253628/126287763-f3782bae-41f4-4220-a905-af4cbc44e780.png)
status is always loading and nothing shows in the terminal

**Comment by jdneo** [comment]
@whitesweet What's your `java.progressReports.enabled` setting?

**Comment by whitesweet** [comment]
er.. the setting is false.
when I change it to true, java build status terminal works.
Thanks
