### ISSUE TITLE
prevent import to put above first comments

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#1993]
if you have:

```
///usr/bin/env jbang "$0" "$@" ; exit $?
// Update the Quarkus version to what you want here or run jbang with
// `-Dquarkus.version=<version>` to override it.
//DEPS io.quarkus:quarkus-bom:${quarkus.version:2.0.0.CR3}@pom
```

at top of your  file vscode on import action puts the import above these lines.

```
import javax.inject.Inject;

///usr/bin/env jbang "$0" "$@" ; exit $?
// Update the Quarkus version to what you want here or run jbang with
// `-Dquarkus.version=<version>` to override it.
//DEPS io.quarkus:quarkus-bom:${quarkus.version:2.0.0.CR3}@pom
```
should do it on the first empty line to avoid breaking those users writing jbang or single source java code files.

**Comment by rgrunber** [comment]
The behaviour seems the same in Eclipse JDT as well so maybe we can fix this upstream. The import declarations are placed below the package declaration, and when there's no package declaration, they seem to go at the very top of the file.

This also means you should be able to work around the issue by having a basic package declaration below the comments.

**Comment by rgrunber** [comment]
I think the entry point to fix this (or add an option to change the behaviour should be at https://github.com/eclipse-jdt/eclipse.jdt.core/blob/c58f581d8cef2c38a339b8056b3f48f1d5365731/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java#L317 .

If there's no existing import region (no imports), and no existing package declaration (default package), then find the offset of the first non-comment node and begin from there.

This pretty basic patch seems to do the job.

```diff
diff --git a/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java b/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java
index 200be49a4f..d8b6fdbdfb 100644
--- a/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java
+++ b/org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/imports/ImportRewriteAnalyzer.java
@@ -40,6 +40,7 @@ import org.eclipse.jdt.core.dom.ASTNode;
 import org.eclipse.jdt.core.dom.Comment;
 import org.eclipse.jdt.core.dom.CompilationUnit;
 import org.eclipse.jdt.core.dom.ImportDeclaration;
+import org.eclipse.jdt.core.dom.LineComment;
 import org.eclipse.jdt.core.dom.PackageDeclaration;
 import org.eclipse.jdt.core.formatter.DefaultCodeFormatterConstants;
 import org.eclipse.jdt.core.search.SearchEngine;
@@ -315,6 +316,16 @@ public final class ImportRewriteAnalyzer {
            }
            else {
                surroundingStart = 0;
+               ASTNode topNode = nodesTreeMap.firstEntry().getValue();
+               if (topNode instanceof LineComment) {
+                   for (ASTNode node : nodesTreeMap.values()) {
+                       if (!(node instanceof LineComment)) {
+                           break;
+                       } else {
+                           surroundingStart = node.getStartPosition() + node.getLength();
+                       }
+                   }
+               }
            }

            positionAfterImports = surroundingStart;

```

**Comment by fbricon** [comment]
Opened https://github.com/eclipse-jdt/eclipse.jdt.core/issues/649 upstream

**Comment by rgrunber** [comment]
According to https://github.com/eclipse-jdt/eclipse.jdt.core/commit/40fa81de93d65b85d6a8eb8cfc2c381b045bfcd2 , we should be able to close this as soon as JDT-LS updates to an I-build of `I20230324-1800` (4.28-I-build) or newer.
