### ISSUE TITLE
vscode-extension: Provide an action to open the formatter settings file

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-java#2]
_From @egamma on July 11, 2016 8:20_

_Copied from original issue: gorkem/java-language-server#42_

**Comment by houman-babai** [comment]
I wanted to open a enhancement-request to provide a configuration surface for the formatter.  Currently I use eclipse, and I would like to move over to vs code.  But I do need a way to format the code according to a formatting policy.

Is this ticket addressing the same problem?

**Comment by gorkem** [comment]
@houman-babai Yes, this is a request to use and edit eclipse formatting policies

**Comment by houman-babai** [comment]
Thanks @gorkem.  This is a great tool, but unfortunately I cannot use it without the formatter.  Over the next few month I'll see if I can learn to contribute to the project :-) In the meantime i would be grateful to know if there are any workarounds...

**Comment by concatime** [comment]
I would love to see it in future releases too!

**Comment by bowiegou** [comment]
Yes. please have this feature.

**Comment by Dangoo** [comment]
I'd vote for that too!

**Comment by magnusart** [comment]
This is very annoying. We have a specialized eclipse formatting settings but when using visual code  I muck that up and there is no documented way to change it. Is there any workaround?

**Comment by musiKk** [comment]
FWIW there is a [maven plugin](https://github.com/revelc/formatter-maven-plugin) which uses the Eclipse formatter and can use any provided formatting configuration. A native solution would be better of course.

**Comment by KaRkY** [comment]
What is teh status of the issue? 

It is the only thing preventing me from using this instead of eclipse proper.

**Comment by DiabolusExMachina** [comment]
Any news on this? I think this is really important. 

Even a property like "java.formater.file" in vscode to point to my global company rules would really help. I don't want to copy the file in all of our projects by hand...

**Comment by fbricon** [comment]
Sorry guys, there's been no new development in that area yet. As a workaround for your formatting options, please read https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings

**Comment by subpandu** [comment]
Trying to use the given workaround, how do you tell vscode to pick the formatting rules from .settings/org.eclipse.jdt.core.prefs

Just including the file in the project did not work

**Comment by DiabolusExMachina** [comment]
it did not work for me aswell.

**Comment by magnusart** [comment]
I can recommend the gradle/maven plugin `spotless` as a work around (https://github.com/diffplug/spotless). Your build tool then makes sure everything is formatted. It can reformat your code automatically via the command spotlessApply. Not a replacement but makes things more tolerable and enforces a single code formatting standard.

**Comment by fbricon** [comment]
can anyone provide a sample project where .settings/org.eclipse.jdt.core.prefs are ignored?

**Comment by gitorko** [comment]
After copying the .settings/org.eclipse.jdt.core.prefs file you need to restart vscode for the changes to be picked. It was working for me after restart. 1.21.1 version. However now i have to copy this file to each project to get formatting to work. Is there a global location to place this file?

**Comment by AngelFraga** [comment]
I would like to see this feature in the next releases. In spite of the workaround works fine, could be great declared in vscode user settings a global ./settings folder to use for each project. Also, for example, org.eclipse.jdt.ui.prefs is needed as well to sort import statements.
