### ISSUE TITLE
The import javax.servlet cannot be resolved

### ISSUE THREAD

**Issue by wzdnzd** [redhat-developer/vscode-java#200]
[provide a description of the issue]

##### Environment
- Operating System: win10
- JDK version: 1.8.0_131
- Visual Studio Code version: 1.12.1
- Java extension version: 0.3.0

![image](https://cloud.githubusercontent.com/assets/8565764/25731644/9eacf9f8-317a-11e7-81ff-bbc71bec6c69.png)

**Comment by fbricon** [comment]
Can you please provide more details, is this a standalone java file, a Maven, Gradle or plain eclipse project? Can you provide a sample project reproducing the issue?

**Comment by wzdnzd** [comment]
Caused by: org.eclipse.core.internal.resources.ResourceException: Invalid project description.
	at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:169)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:53)
	at org.eclipse.core.internal.resources.Project.create(Project.java:263)
	at org.eclipse.core.internal.resources.Project.create(Project.java:247)
	at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.importDir(EclipseProjectImporter.java:86)

it seem to have some problems for my project,and now it works well,thx.

**Comment by bastlaca** [comment]
It's working for me:
`$ cp /tomcathome/lib/servlet-api.jar /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/`

**Comment by SlumpShrimp** [comment]
I'm using macOS Catalina and java13. Please tell me how to import Servlet on VScode.

**Comment by SlumpShrimp** [comment]
I can't find the directory /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/.
please tell me how to find this.

**Comment by bastlaca** [comment]
> I can't find the directory /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/.
> please tell me how to find this.

Try:
`java -verbose | grep 'Loaded java.lang.Shutdown from'`
Output:
[Loaded java.lang.Shutdown from /usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar]

The copy command will be: 
`$ cp ~/tomcathome/lib/servlet-api.jar  /usr/lib/jvm/java-8-openjdk/jre/lib/ext/`

**Comment by chaoren5** [comment]
> Caused by: org.eclipse.core.internal.resources.ResourceException: Invalid project description. at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:169) at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:53) at org.eclipse.core.internal.resources.Project.create(Project.java:263) at org.eclipse.core.internal.resources.Project.create(Project.java:247) at org.eclipse.jdt.ls.core.internal.managers.EclipseProjectImporter.importDir(EclipseProjectImporter.java:86)
> 
> it seem to have some problems for my project,and now it works well,thx.

jdk verion is different from jre version, just put path first in system enviroment
