### ISSUE TITLE
eclipse-formatter.xml not found and how to modiffy snippets

### ISSUE THREAD

**Issue by Xandor19** [redhat-developer/vscode-java#2005]
[provide a description of the issue]
When I run the Java: Open Java Formatter Settings I get the message "eclipse-formatter.xml does not exists", however, when formatting at a .java file it works just fine
On the other hand, i would like to know if there's a way of customizing some of the built-in snippets of the extension

##### Environment
- Operating System: Ubuntu 20.04 LTS
- JDK version: openjdk 11
- Visual Studio Code version: 1.57.1
- Java extension version: 0.79.2

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by snjeza** [comment]
> When I run the Java: Open Java Formatter Settings I get the message "eclipse-formatter.xml does not exists",

@Xandor19 Could you show your setting.json?

**Comment by Xandor19** [comment]
![Captura de pantalla de 2021-06-29 17-13-46](https://user-images.githubusercontent.com/77125505/123868264-7408ee80-d8fd-11eb-81f5-51beb550e4ff.png)

Here it is, sorry for the delay

**Comment by snjeza** [comment]
@Xandor19 you should set the java.format.settings.url property.

**Comment by Xandor19** [comment]
How would that be?
And about the snippets question?

**Comment by snjeza** [comment]
> How would that be?

You can add the following

```
"java.format.settings.url": "<path_to_your_formatter.xml>"
```

> And about the snippets question?

I think that you can't customize it.

> And about the snippets question?

See [Predefined Variables for Java Template Snippets](https://github.com/redhat-developer/vscode-java/wiki/Predefined-Variables-for-Java-Template-Snippets)

**Comment by florinCer** [comment]
You need to provide setting path as below:
"java.format.settings.url": "file:///C:/SettingsFolder/.eclipse_formatter_files/eclipse-formatter.xml",

and should work

**Comment by Xandor19** [comment]
Thank you both
