### ISSUE TITLE
Retire the asking importing dialog

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#2014]
Long time ago we introduced a feature that asking user whether to import the projects when opening the workspace for the first time:

![image](https://user-images.githubusercontent.com/6193897/124707685-06853100-deae-11eb-932e-6778a3a5d9cb.png)

According to the user's selection, we will determine which server mode will be used.

Now, since VS Code has introduced the workspace trust feature as a platform solution, I think it's a good time to retire this dialog. By doing so, we can also reduce the popping-ups and get a better UX.

Any thoughts? @rgrunber @fbricon @testforstephen 

_// I'm willing to propose a PR if we agree on this._

**Comment by rgrunber** [comment]
Looks like we're in favour of changing the default option to "always", but would like to keep the settings itself around for now so users still have the option to change it.

If we determine at a later point that this isn't a deal breaker for anyone, then we can remove it completely.

**Comment by jdneo** [comment]
Sounds good.
