### ISSUE TITLE
Gradle support configuration procedure

### ISSUE THREAD

**Issue by intoCL** [redhat-developer/vscode-java#202]
We're trying to get gradle support working from the extension, but there are no obvious directions as to how to configure the extension correctly in order to accomplish this. Either that or we're blind.

We've looked at the [Marketplace writeup](https://marketplace.visualstudio.com/items?itemName=redhat.java) and watched this [video](https://www.youtube.com/watch?v=MHYGkbAzdms), and in both cases the UI shows gradle build files (also .gitgnore amongst others) being recognised in the project directory tree. When we open the root folder in code, nothing is recognised. No icons appear next to the filenames in the directory tree.

There is also no thumbs up icon on the right hand side of the status bar.

Thanks in advance.

PS. I can't see where to add the question label to this so I assume that's done by a mod.

##### Environment
- Operating System: Kubuntu 14.04 LTS
- JDK version: 8
- Visual Studio Code version: Version 1.11.2
- Java extension version: 0.3.0

##### Steps To Reproduce

Current configuration settings as follows:

"java.home": "/home/[username]/.sdkman/candidates/java/current"
"java.jdt.ls.vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication"
"java.configuration.updateBuildConfiguration": "interactive"
"java.errors.incompleteClasspath.severity": "warning"
"java.trace.server": "off"
"java.referencesCodeLens.enabled": true
"java.configuration.maven.userSettings": null

**Comment by gorkem** [comment]
Do you have a [file icon set](https://code.visualstudio.com/blogs/2016/09/08/icon-themes#_file-icon-themes) enabled? The status of the Java extension is only displayed on status bar when a Java file is opened did you have a Java file open?

**Comment by fbricon** [comment]
@intoCL it should work OOTB normally. The Java Language Server starts as soon as a pm.xml or gradle file is found at the root of the folder, or the 1st time a java file is opened. Once started, the thumb up is displayed. The status is not displayed when the currently opened file is a non-java, non-build file.

Can you please look at the [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging) and report what you find here?

**Comment by intoCL** [comment]
Hi Gorkem and Fred,

I managed to get the icons sorted as per Gorkem's suggestion. The Language Server also appears to be working as I can jump to definitions and such.

After discovering and watching your very helpful `[Devoxx demo](https://www.youtube.com/watch?v=l96vUqfB3R4)`, I was able to convert your maven example to gradle by putting this in tasks.json
`{
    "version": "0.1.0",
    "command": "./gradlew",
    "isShellCommand": true,
    //"args": ["build"],
    "showOutput": "always",
    "suppressTaskName": true//,
    /*"tasks": [
        {
            "taskName": "build",
            "args": ["build"]//,
            //"isBuildCommand": true
         },
        {
            "taskName": "load",
            "args": ["load"]//,
            //"isBuildCommand": true
        },
        {
            "taskName": "run",
            "args": ["run"]//,
            //"isBackground": true
         }
        
    ]*/
}`

I just changed your ./mvnw reference to ./gradlew. Ctrl+Shift+B now executes the default gradle build. We want to add some tasks that will allow creating shortcuts to parameterised build calls. So for example, our gradle tasks include [build] (which the default), [load] and [run]. But we want to add them to their own keyboard shortcuts. I am busy digging around VS Code documentation, but if you have any suggestions on this I'd appreciate it.

Thanks for both your help so far especially with the Devoxx demo. That helped a lot to get a taster on how everything hangs together.

**Comment by intoCL** [comment]
Hi guys.

I'm sorted.

I made the following changes based on what I read about tasks [here](https://code.visualstudio.com/docs/editor/tasks#_command-and-tasks), and keyboard bindings [here](https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks).

For anyone else who wants to set their environment up similarly, I modified the respective files as follows:

**tasks.json**
{
    "version": "0.1.0",
    "command": "./gradlew",
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build",
            "args": ["build"],
            "isBuildCommand": true
         },
        {
            "taskName": "load",
            "args": ["load"]
        },
        {
            "taskName": "run",
            "args": ["run"]
         }
    ]
}

**keybindings.json**

[
    {
        "key": "ctrl+shift+l",
        "command": "workbench.action.tasks.runTask",
        "args": "load"
    },
    {
        "key": "ctrl+shift+r",
        "command": "workbench.action.tasks.runTask",
        "args": "run"
    }
]

With this configuration the listed keyboard shortcuts run each of the corresponding configured tasks.

Ctrl+Shift+B: **build**
Ctrl+Shift+L: **load**
Ctrl+Shift+R: **run**

Hope this helps.
