### ISSUE TITLE
Try to run normal spring boot project on win 10 with JDK 16 It will stuck on 68%

### ISSUE THREAD

**Issue by itsmaheshkariya** [redhat-developer/vscode-java#2020]
![image](https://user-images.githubusercontent.com/16520789/125202425-255e3b80-e291-11eb-88ab-55cfb14a0505.png)

**Comment by snjeza** [comment]
@itsmaheshkariya could you attach a project example?

**Comment by Moses-Everlytic** [comment]
I'm having the same issue, I just created a new project project from https://start.spring.io.
I even test an old application from this repository (https://github.com/springframeworkguru/spring-rest-client-examples) still had the same issue.

**Comment by snjeza** [comment]
The issue has been caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=573595, commit https://git.eclipse.org/c/platform/eclipse.platform.resources.git/commit/?id=6f51e1b87d52320dceed8ee115898b8d43e91f1a

@v-yuyul @itsmaheshkariya @Moses-Everlytic could you test https://raw.githubusercontent.com/snjeza/vscode-test/master/java-0.80.2.vsix

**Comment by Moses-Everlytic** [comment]
@snjeza It no longer hangs, I tested on multiple projects. (Works)

**Comment by fbricon** [comment]
@snjeza what's the fix? Shouldn't you open a bug upstream?

**Comment by Moses-Everlytic** [comment]
@fbricon Just install this version of JLS 
https://raw.githubusercontent.com/snjeza/vscode-test/master/java-0.80.2.vsix

The issue was the v.0.80.0 which has a bug.

**Comment by fbricon** [comment]
@Moses-Everlytic yeah I get that. I want to know what the actual fix is (in terms of code change in jdt/jdt.ls)

**Comment by snjeza** [comment]
> what's the fix? Shouldn't you open a bug upstream?

@fbricon you may want to take a look at 
https://github.com/eclipse/eclipse.jdt.ls/pull/1816
https://bugs.eclipse.org/bugs/show_bug.cgi?id=573595
https://bugs.eclipse.org/bugs/show_bug.cgi?id=549500
https://bugs.eclipse.org/bugs/show_bug.cgi?id=574227

**Comment by xiaomaimuchanyiyiba** [comment]
> The issue has been caused by
> 
> * https://bugs.eclipse.org/bugs/show_bug.cgi?id=573595, commit https://git.eclipse.org/c/platform/eclipse.platform.resources.git/commit/?id=6f51e1b87d52320dceed8ee115898b8d43e91f1a
> * https://bugs.eclipse.org/bugs/show_bug.cgi?id=574227, commit https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/commit/?id=298e47435e19b1217e5593f3c29652720857f6e1
> 
> @v-yuyul @itsmaheshkariya @Moses-Everlytic could you test https://raw.githubusercontent.com/snjeza/vscode-test/master/java-0.80.2.vsix

useful

**Comment by MridulaKamath** [comment]
For others like me who couldn't understand what to do with a vsix file, have a look at this [VSCode doc](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix).

**Comment by wecharyu** [comment]
Rolling back to 0.79.2 still not work for me, my environment is wsl2 ubuntu with code-server, the imported project is apache/hive. Any suggestions?

**Comment by rcarmonad** [comment]
> Rolling back to 0.79.2 still not work for me, my environment is wsl2 ubuntu with code-server, the imported project is apache/hive. Any suggestions?

Finally... happens the same. I've removed all the plugins that use for java (Ms pack, Spring, Redhat) and reinstalled again.
Now works with no issues.

**Comment by wecharyu** [comment]
> > Rolling back to 0.79.2 still not work for me, my environment is wsl2 ubuntu with code-server, the imported project is apache/hive. Any suggestions?
> 
> Finally... happens the same. I've removed all the plugins that use for java (Ms pack, Spring, Redhat) and reinstalled again.
> Now works with no issues.
Which version you chose when reinstalling? My mac osx with 0.82.0 version work fine, but wsl2 in win10 not.
