### ISSUE TITLE
Tune the import UX.

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#2021]
Importing experience is the very important part for our getting start experience. If we go through our issues list, we can find there are several parts that we can improve:

### 1. Provide more transparency
- How to get the import status?
  - We have a spinning icon but that is not straightforward/easy to find.
- What's the result after import finished?

Proposal: #2022 

https://user-images.githubusercontent.com/6193897/126450147-266d9659-6b13-4c59-aaba-37c8c8fc8973.mp4

### 2. Provide more controls
- 2.1 Let user control the active build tool when there are conflicts

Proposal: #2037

https://user-images.githubusercontent.com/6193897/126450128-0b9c968a-e18c-4947-8d53-059bbeb49977.mp4

- 2.2 Let user control the project configuration files that will be used to discover projects to import. (WIP)

### Eliminate the side-effect
- Importing project will generate `.project`, `.classpath`, etc... into users workspace. This is discussed in #618, so won't be discussed here.

**Comment by Eskibear** [comment]
> And maybe an action to switch between the build tools once the project got imported?
_from @martinlippert_

**Comment by Eskibear** [comment]
IMO ideally we need a “imported project manager”, let users explicit choose which projects to import and how to import them. It’s very useful when I open a giant repo containing hundreds of projects and I only want to import a few projects I’m interested in. 

E.g. https://github.com/Azure/azure-sdk-for-java/tree/main/sdk
I'm working on only some of the SDKs but all are in a mono repo.
