### ISSUE TITLE
JDK installed by asdf is not being detected

### ISSUE THREAD

**Issue by danielporto** [redhat-developer/vscode-java#2025]
I'm trying to use remote code development with VScode and java plugin, however the java plugin is not detecting the java installation on the remote node and therefore the language server cannot start.

the issue is similar to  #1092 which even mention that the problem also happens when installation  of sdk is done with asdf, however the issue was closed but the asdf installation is still broken.

JAVA_HOME is correctly exported by asdf for both bash and zsh.

##### Environment
- Operating System: OSX with remote containers to debian buster
- JDK version: tried with both Zulu and AdoptOpenjdk version 11.
- Visual Studio Code version: 1.58.1
- Java extension version: 0.80.0

##### Steps To Reproduce
1. remote linux installation debian buster without systems jdk. installed via asdf
2. connect to the remote node with vscode and try to open a project with java files.

[Please attach a sample project reproducing the error]
https://github.com/danielporto/gRPC-Java-snippet/

##### Current Result
vscode stuck in java plugin welcome page and never detects the jdk installation on the remote node.

##### Expected Result
vscode detect java installation.

**Comment by Eskibear** [comment]
JDK detection logic here: https://github.com/redhat-developer/vscode-java/blob/8542c61c70bc078a1b0557345a114e9b1cb39ecb/src/findJavaRuntimes.ts#L26

Note that, please make sure you are using a JDK instead of JRE by checking whether "./bin/javac" exists under JAVA_HOME.

You can run command "Java: Configure Java Runtime", see if your JDK is successfully listed in "Installed JDKs" tab.

**Comment by Nicryc** [comment]
I'm facing a similar issue on Windows 10. 

I have downloaded several JDK builds of OpenJDK from **Eclipse Temurin** and from **IBM Semeru**. The `vscode-java` extension seems to only search for the common Java directories `Program Files\Java` (for the Oracle JDK) and `Program Files\AdoptOpenJDK` (for the AdoptOpenJDK ones). Although [AdoptOpenJDK have recently migrated](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/) to Eclipse Adoptium for Hotspot JVM builds and to IBM Semeru for OpenJ9 JVM builds. Thus the paths have changed to `Program Files\Eclipse Foundation` and `Program Files\Semeru` and my JDKs aren't listed in the "Installed JDKs" tab (except for the one that is in the JAVA_HOME environment variable)

Maybe it would be a good thing to let the user define where to check for JDKs.

**Comment by Eskibear** [comment]
@MiruhiMiruhi I'm considering supporting asdf-vm but I didn't find any Java related instructions in its official docs. 
- How do you set up it for Java?
- What's the folder structure of `~/.asdf/installs/java/`directory? JDK distros for each subfolder?
- Can `~/.asdf` be a different path? E.g. via some env like ASDF_DIR just like SDKMan does.

**Comment by Nightenom** [comment]
Can confirm the issue for Windows 10 (setup info below, extension v1.2.0). I have JDKs installed on separate work SSD at `P:\\apps\\frameworks\\windows64\\jdk-V` and I'm sure that JAVA_HOME is correctly set.

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by lisy09** [comment]
> @MiruhiMiruhi I'm considering supporting asdf-vm but I didn't find any Java related instructions in its official docs.
> 
> * How do you set up it for Java?
> * What's the folder structure of `~/.asdf/installs/java/`directory? JDK distros for each subfolder?
> * Can `~/.asdf` be a different path? E.g. via some env like ASDF_DIR just like SDKMan does.

@Eskibear Facing same problem.
asdf-vm using plugin mechanism to many different tools.
The most widely use asdf java plugin should be https://github.com/halcyon/asdf-java.

Here is the directory architecture:
```
> asdf which javac
/home/lisy09/.asdf/installs/java/adoptopenjdk-11.0.14+101/bin/javac
```

**Comment by Eskibear** [comment]
tracked in https://github.com/Eskibear/node-jdk-utils/issues/6

please provide more details there, e.g. whether `.asdf` can be a different folder. Or otherwise I will probably hardcode the location to search for available jdks.

**Comment by lisy09** [comment]
> tracked in [Eskibear/node-jdk-utils#6](https://github.com/Eskibear/node-jdk-utils/issues/6)
> 
> please provide more details there, e.g. whether `.asdf` can be a different folder. Or otherwise I will probably hardcode the location to search for available jdks.

@Eskibear Generally speaking .asdf can be a different folder but I think most users of asdf is not doing so.
But I think it is better to call `asdf` command to retrieve java location.
Simply using `asdf which java` it will return the java location if defined in asdf.

**Comment by Eskibear** [comment]
ASDF support has been contributed by @fcrespo82 in jdk-utils@0.4.3
