### ISSUE TITLE
Unrecognized VM option 'UseStringDeduplication'

### ISSUE THREAD

**Issue by FutureProg** [redhat-developer/vscode-java#203]
I'm simply starting up a java project (that can be located here: [https://github.com/FutureProg/InteractionDesigner](https://github.com/FutureProg/InteractionDesigner) and the extension closes with a message saying it can't start "client Language Support for Java". I looked at the console and this is all I've found. 

##### Environment
- Operating System: OSX El Capitan
- JDK version: 8.1.0
- Visual Studio Code version: 1.12.1
- Java extension version: 0.3.0

##### Steps To Reproduce
1. Open VSCode with a java project 
2. Message says that it is unable to start the client

##### Additional Informations
- No server logs are produced
- Everything was fine until I updated from the previous to the latest version
- I'm adding gradle to my project but that shouldn't affect anything, right?
- the following is in the developer console:
> [Extension Host] stderr: Unrecognized VM option 'UseStringDeduplication'
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.

**Comment by fbricon** [comment]
Damn, I basically did bet noone would experience that. This is a JVM flag that was introduced in JFK 1.8.0_20, 3 years ago. So you have 2 options. Either update your jdk to the latest version, or open vscode preferences and remove -XXUseStringDeduplication and -XXG1GC from java.jdt.ls.vmargs

**Comment by FutureProg** [comment]
Haha alright, thanks, I just updated and it's all good

**Comment by jtsiros** [comment]
I experienced this also running version "1.8.0_05".

**Comment by fbricon** [comment]
@jtsiros you should definitely update your Java version
