### ISSUE TITLE
导入tycho项目，一直卡在66%

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2030]
我在导入tycho<https://github.com/eclipse/tycho.git>，进度一直在66%，有一个多小时不动！而且好像是有死循环。

##### Environment
- Operating System:Windows_NT x64 10.0.19043
- JDK version:16
- Visual Studio Code version:1.59.0-insider (system setup)
- Java extension version:0.80.0

##### Steps To Reproduce
1. git clone https://github.com/eclipse/tycho.git
2. vscode添加tycho

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
![image](https://user-images.githubusercontent.com/63572041/125867350-c980653b-777c-4a72-abd0-74b69c236d74.png)

##### Expected Result
- Refreshing workspace [Done]
- Building [Done]
##### Additional Informations
在循环导入一样的子项目，没有结束

**Comment by fbricon** [comment]
See if https://github.com/redhat-developer/vscode-java/issues/2020#issuecomment-880272712 fixes your issue.

As a side note: can you please use English to comment on https://github.com/redhat-developer/vscode-java/issues/? If you're not comfortable, just use a translation service (like https://translate.google.com/?hl=en&sl=zh-CN&tl=en&op=translate) and paste your translated comments in Github
