### ISSUE TITLE
Language server getting stuck at 68%

### ISSUE THREAD

**Issue by jatin711-debug** [redhat-developer/vscode-java#2038]
its been last month, this error is occurred after updating vs-code to 1.58 version, before I used Spring boot in vs for around 5-6 months, no problems but now its just stuck, I had viewed same issues from earlier, used jps and tried to kill one of the org.eclipse instance, but its  just pops out again with new pid 

server language always gets stuck at 68%.
I had tried clearing workspace - didnt work
tried cleaning server language -didnt work

##### Environment
- JDK -16.0
- Java extension version: v0.80.0
- VS code -Version: 1.58.2 (user setup)
OS: Windows_NT x64 10.0.19043

project sample available on ->https://github.com/jatin711-debug/SecurityLoginSpringBoot

###Logs
!SESSION 2021-07-23 19:19:24.541 -----------------------------------------------
eclipse.buildId=unknown
java.version=16.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Command-line arguments:  -data c:\Users\hp\AppData\Roaming\Code\User\workspaceStorage\020e4300336bc410fdd3741119adb288\redhat.java\jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:35.181
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:36.226
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:36.447
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:36.669
!MESSAGE Initializing Java Language Server 1.2.0.202106301426

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:36.762
!MESSAGE Runtime JavaEnvironment [name=null, path=null, javadoc=null, sources=null] is not valid.

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.663
!MESSAGE Setting C:\Program Files\Java\jdk-16.0.1 as 'JavaSE-16' environment (id:1627082377345)

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.671
!MESSAGE JVM Runtimes changed, saving new configuration

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.897
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.898
!MESSAGE Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.navigate.openTypeHierarchy, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.provideSemanticTokens, java.project.resolveStackTraceLocation, java.project.getAll, java.project.isTestFile, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.project.getSemanticTokensLegend, java.edit.stringFormatting, java.project.getSettings, java.project.updateSourceAttachment, java.project.resolveSourceAttachment, java.project.addToSourcePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.900
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.901
!MESSAGE Non-Static Commands: [java.intellicode.completion, java.intellicode.completion.resolve, java.intellicode.enable]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.904
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.917
!MESSAGE Non-Static Commands: [vscode.java.checkProjectSettings, vscode.java.isOnClasspath, vscode.java.fetchUsageData, vscode.java.validateLaunchConfig, vscode.java.resolveInlineVariables, vscode.java.resolveClassFilters, vscode.java.resolveMainMethod, vscode.java.resolveClasspath, vscode.java.resolveBuildFiles, vscode.java.resolveMainClass, vscode.java.updateDebugSettings, vscode.java.resolveSourceUri, vscode.java.fetchPlatformSettings, vscode.java.buildWorkspace, vscode.java.startDebugSession, vscode.java.inferLaunchCommandLength, vscode.java.resolveElementAtSelection, vscode.java.resolveJavaExecutable]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.920
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.933
!MESSAGE Non-Static Commands: [java.project.refreshLib, java.project.list, java.project.generateJar, java.project.getMainClasses, java.getPackageData, java.resolvePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.936
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.938
!MESSAGE Non-Static Commands: [vscode.java.test.search.codelens, vscode.java.test.search.items.all, vscode.java.test.search.location, vscode.java.test.search.items, vscode.java.test.get.testpath, vscode.java.test.junit.argument, vscode.java.test.generateTests]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.947
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.956
!MESSAGE Non-Static Commands: [java.maven.initializeSearcher, java.maven.searchArtifact, java.maven.addDependency, java.maven.controlContext]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.970
!MESSAGE Static Commands: [sts.java.addClasspathListener, sts.java.removeClasspathListener]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.977
!MESSAGE Non-Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:37.984
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.001
!MESSAGE Non-Static Commands: [sts.java.javadoc]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.019
!MESSAGE Static Commands: [sts.java.type]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.021
!MESSAGE Non-Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.022
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.031
!MESSAGE Non-Static Commands: [sts.java.javadocHoverLink]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.032
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.035
!MESSAGE Non-Static Commands: [sts.java.location]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.051
!MESSAGE Static Commands: [sts.java.search.packages, sts.java.search.types]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.067
!MESSAGE Non-Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.068
!MESSAGE Static Commands: [sts.java.hierarchy.supertypes, sts.java.hierarchy.subtypes]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.070
!MESSAGE Non-Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.083
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.084
!MESSAGE Non-Static Commands: [sts.java.code.completions]

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:38.411
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:39.816
!MESSAGE Creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:40.303
!MESSAGE Finished creating the Java project jdt.ls-java-project

!ENTRY org.eclipse.jdt.ls.core 1 0 2021-07-23 19:19:42.933
!MESSAGE Importing Maven project(s)

**Comment by snjeza** [comment]
@jatin711-debug could you check https://github.com/redhat-developer/vscode-java/issues/2020#issuecomment-880272712

**Comment by jatin711-debug** [comment]
> @jatin711-debug could you check [#2020 (comment)](https://github.com/redhat-developer/vscode-java/issues/2020#issuecomment-880272712)

Yup it kinda worked for me for now, I will close this issue after 3 days of testing your .vsix file
Thanks For Now
