### ISSUE TITLE
java.configuration.runtimes not work when use remote connect to centos

### ISSUE THREAD

**Issue by smiecj** [redhat-developer/vscode-java#2043]
##### Environment
- Operating System: windows10
- JDK version: system JDK11, project need jdk1.8
- Visual Studio Code version: 1.58.2
- Java extension version: Java Extension Pack 0.17.0

##### Steps To Reproduce
1. centos: set env $JAVA_HOME to jdk11 path
```
export JAVA_HOME=/usr/java/jdk-11.0.11
export JDK_HOME=/usr/java/jdk-11.0.11
```

2. check "Configure Java Runtime", seems that the java tooling runtime is normal
![image](https://user-images.githubusercontent.com/14009307/127114690-4a528648-7270-4918-9b9a-fd3038fdd767.png)

3. config remote settings.json and set java.configuration.runtimes with jdk1.8 and jdk16
![image](https://user-images.githubusercontent.com/14009307/127115377-ca820fe4-c538-45d4-81fd-1049a8b22451.png)

![image](https://user-images.githubusercontent.com/14009307/127114916-efc11940-84dc-453f-837e-d28c6b274871.png)

4. both jdk1.8 and jdk16 cannot be recognized in "installed jdks" tag 
![image](https://user-images.githubusercontent.com/14009307/127114858-3c677257-0247-4060-b92c-d930c507ec13.png)

**Comment by qinlinwang** [comment]
I hava the similer problem.

**Comment by Eskibear** [comment]
https://github.com/redhat-developer/vscode-java/blob/b9032f1b319e6077f5c3e7783e9c58362114dd67/src/findJavaRuntimes.ts#L30-L34

It detects JDK by checking JAVA_HOME, JDK_HOME, PATH, and some hardcoded locations. `/usr/java` is not included.

**Comment by smiecj** [comment]
Thanks for reply. I will try those vars later.

**Comment by smiecj** [comment]
@Eskibear Thanks! That solve my problem.
What only need to do is add JDK_HOME config in /etc/profile. This env is pointed to JDK11. JAVA_HOME is still pointed to JDK1.8.

`
export JAVA_HOME=/usr/java/jdk1.8.0_291
export JDK_HOME=/usr/java/jdk-11.0.11
`

@qinlinwang Maybe you can try this method.

**Comment by smiecj** [comment]
By the way, after configuration:

![image](https://user-images.githubusercontent.com/14009307/129698591-a7d74779-261f-4c49-8bab-05cca85cc8f5.png)

![image](https://user-images.githubusercontent.com/14009307/129698759-02449665-37f8-4809-968a-f8952b8ec3c7.png)

![image](https://user-images.githubusercontent.com/14009307/129698804-906c2b6f-7d09-4aef-a204-24a971b6b206.png)

You may need to restart remote machine(centos) after add JDK_HOME env.

**Comment by khourig** [comment]
@Eskibear This isn't a solution for me. My company administered Linux machine has 8 and we have a network share with a slew of versions including ones in current use: 11, 17, 21. I set `java.configuration.runtimes` in the remote user folder with 21 as the default. When I try to configure the project runtime, it shows 21 but the drop down list only contains 8.
