### ISSUE TITLE
"Open Call Hierarchy" does not jump to the reference where it is invoked at

### ISSUE THREAD

**Issue by tommai78101** [redhat-developer/vscode-java#2044]
When you invoke "Open Call Hierarchy" (`Shift+Alt+H`), it shows a list of references where it gets called. However, when the list of reference is shown and the user jumps to that reference, instead of jumping to where the reference is at in the code, it jumps to the method invoking the reference.

For example:

Let's say we have a simple code with 2 different Java documents:

```java
//Foo.java
public class Foo {
     public int getValue() {
          return 1;
     }
}
```
```java
//Main.java
public static void main(String[] args) {
    System.out.println("skip");
    System.out.println("skip");
    System.out.println("skip");
    //... Repeat for 1500 lines.
    new Foo().getValue();
}
```

And we used "Open Call Hierarchy" for `getValue()` defined in Foo.java. When the user expands the `getValue()` reference node and clicks on `main(String[] args)` in the Call Hierarchy list, instead of jumping to `new Foo().getValue()` in Main.java down at the bottom, it jumps to `main(String[] args)` near the top.

I expected that we shouldn't be jumping to the beginning of the scope where the call is invoked in. Instead, we should be jumping to where the reference is located at. 

I don't know if there are any options at this point in time, to change the behavior so that we can jump to the reference location, rather than the beginning of the scope. If not, may I ask if this behavior can be fixed / suggested?

##### Environment
- Operating System: Ubuntu 20.04.2 LTS
- JDK version: 11.0.11+9
- Visual Studio Code version: 
```
Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-63-generic snap
```
- Java extension version: 0.80.0

##### Steps To Reproduce
1. Create a new Java project.
2. Copy the Foo.java at the top and create class `Foo`.
3. Copy the Main.java at the top and create class `Main`.
4. Fill in the `//...` with actual `System.out.println("skip");` 1,500 times, or enough times where you have to scroll the page up and down.
4. Navigate to `Foo` and do `Open Call Hierarchy` on the method `getValue()`.
5. When `Main.java` is opened, observe how you have to scroll all the way down to get to the `getValue()` from the top.

##### Current Result

After opening Call Hierarchy on the `Foo.getValue()` method, Visual Studio Code redirects the user to the `main(String[] args)` method near the top.

##### Expected Result

After opening Call Hierarchy on the `Foo.getValue()` method, Visual Studio Code should redirect the user to the `getValue()` method near the bottom.

##### Additional Informations

N/A

**Comment by fbricon** [comment]
@snjeza it works fine in Eclipse so we must be doing something wrong

**Comment by snjeza** [comment]
> What about if multiple references occur in the same member (eg. method). Do we just show the first one ?

We show all references. You can try to import https://github.com/eclipse/eclipse.jdt.ls/tree/master/org.eclipse.jdt.ls.tests/projects/eclipse/hello and call Show Call Hierarchy for org.sample.Foo.someMethod(). 
See https://github.com/eclipse/eclipse.jdt.ls/pull/1824/commits/6df9731a6e74c123a95bf808c9d7316626546e07#diff-8a2bd8e047f727ec4f8c8b4cdab733fae8c04372ebaff87705381404c406e35bR106

**Comment by snjeza** [comment]
>  IDEs like Eclipse, which group references by the method declaration under which they occur, as opposed to having each one be a separate item.

Eclipse show them in a separate view.
Eclipse:
![eclipse](https://user-images.githubusercontent.com/388609/128283417-241b7fd6-7136-4471-9431-c8142c0cdc9f.png)

VS Code (0.80.0)
![vscode](https://user-images.githubusercontent.com/388609/128283492-35d9c326-2710-480d-80e1-42ae02e04107.png)

VS Code with this PR
![vscodepatched](https://user-images.githubusercontent.com/388609/128283535-65bade4d-28d5-402e-811c-5202c732b1a1.png)

**Comment by rgrunber** [comment]
Thanks for posting these to make it clear what will be changing. So it basically comes down to either showing 1 instance of a method that may contain multiple references without any indication there are multiple references (until clicking on the item), or creating a single item for every reference.

I think the PR's approach is a bit better. @snjeza Is there any place in the VS Code client that would make use of the selectionRange of the parent item of a reference (eg. "main" ) ? My only concern is if we slightly break the spec by duplicating the content of fromRanges.

**Comment by snjeza** [comment]
> Is there any place in the VS Code client that would make use of the selectionRange of the parent item of a reference (eg. "main" ) ?

I don't know. 

>  My only concern is if we slightly break the spec by duplicating the content of fromRanges.

I think the VS Code client doesn't use the fromRanges property.

BTW this issue can be reproduced in typescript.

**Comment by Eskibear** [comment]
I can reproduce it with both TS and Java. By a quick glance, the response is correctly following LSP, so it's probably VS Code's strategy of rendering items. I don't think break the spec is our best choice if we could fix that in vscode. 

Below is a simple TS sample. I think the response is correct, and a better behavior would be:
- list two items for `bar2()`, representing both calls of `foo()`
- and by clicking, it navigates to corresponding `fromRange` instead of `selectionRange`.

@jrieken Is current behavior on purpose? And what do you think about this use case?

```ts
function foo() { }

function bar1(){
    foo();
}

function bar2(){
    foo();
    foo();
}
```


![image](https://user-images.githubusercontent.com/2351748/131884754-86451d23-0ceb-47c0-ae2d-716a03b25165.png)

Two `fromRange` elements but only one `bar2()` item.

```
[Trace  - 16:41:43.25] <semantic> Response received: provideCallHierarchyIncomingCalls (491). Request took 2 ms. Success: true 
Result: [
    {
        "from": {
            "name": "bar1",
            "kind": "function",
            "kindModifiers": "",
            "file": "c:/Users/admin/git/microsoft/vscode-maven/src/testCallH.ts",
            "span": {
                "start": {
                    "line": 3,
                    "offset": 1
                },
                "end": {
                    "line": 5,
                    "offset": 2
                }
            },
            "selectionSpan": {
                "start": {
                    "line": 3,
                    "offset": 10
                },
                "end": {
                    "line": 3,
                    "offset": 14
                }
            }
        },
        "fromSpans": [
            {
                "start": {
                    "line": 4,
                    "offset": 5
                },
                "end": {
                    "line": 4,
                    "offset": 8
                }
            }
        ]
    },
    {
        "from": {
            "name": "bar2",
            "kind": "function",
            "kindModifiers": "",
            "file": "c:/Users/admin/git/microsoft/vscode-maven/src/testCallH.ts",
            "span": {
                "start": {
                    "line": 7,
                    "offset": 1
                },
                "end": {
                    "line": 10,
                    "offset": 2
                }
            },
            "selectionSpan": {
                "start": {
                    "line": 7,
                    "offset": 10
                },
                "end": {
                    "line": 7,
                    "offset": 14
                }
            }
        },
        "fromSpans": [
            {
                "start": {
                    "line": 8,
                    "offset": 5
                },
                "end": {
                    "line": 8,
                    "offset": 8
                }
            },
            {
                "start": {
                    "line": 9,
                    "offset": 5
                },
                "end": {
                    "line": 9,
                    "offset": 8
                }
            }
        ]
    }
]
```

**Comment by rgrunber** [comment]
Also, would be interesting to know why `Peek -> Call Hierarchy` does exactly the expected behaviour (show the caller/callee methods in the tree view but takes you to the fromRanges rather than the selectionRange). Seems like they should behave the same way.

As for the change, I would be fine with merging as long as we get a better idea as to whether this is a bug or intended. Also, we'd have to keep in mind that we're misusing CallHierarchyItem & selectionRange to get the behaviour we want.

**Comment by Eskibear** [comment]
I'm fine with merging the change in jdtls as a workaround for the moment. And I would suggest to leave this issue open and refer it in code changes for better clarity.
