### ISSUE TITLE
What about Gradle Java Application project support?

### ISSUE THREAD

**Issue by Baneeishaque** [redhat-developer/vscode-java#2048]
[provide a description of the issue]

##### Environment
- Operating System: 
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by snjeza** [comment]
See https://github.com/redhat-developer/vscode-java/wiki/Gradle-Support

**Comment by rgrunber** [comment]
If there's some issue, with Gradle support, we'd probably need a specific example, or the error you're seeing. We do provide Gradle project support as mentioned above.

**Comment by fbricon** [comment]
Closing as ticket is not actionable
