### ISSUE TITLE
Mixed Java/Groovy project support

### ISSUE THREAD

**Issue by intoCL** [redhat-developer/vscode-java#205]
OK. So after getting our gradle project configured and executing build tasks, we set about trying to eliminate what we initially thought were tons of build errors due to unresolved symbols.

We hacked our way through the weeds trying to figure out where the classpaths were configured in order to try and see if maybe some paths were missing. What was curious was that some helper classes which you would expect to be in the same packages as their caller classes just weren't. Then we realised what the issue was. All the unresolved symbols appear to be defined in Groovy files.

So the question is, does this extension support Groovy, and if not, what are our options?

Thanks in advance.

##### Environment
- Operating System: Kubuntu 14.04 LTS
- JDK version: 8
- Visual Studio Code version: Version 1.11.2
- Java extension version: 0.3.0

**Comment by fbricon** [comment]
Unfortunately we don't support groovy at the moment. This is a very difficult subject. We can't just ship support for all other JVM languages, that'd be well beyond the scope of this project.

Ideally, we'd need to find a way for multiple language servers to interact with each other, but that's a whole new paradigm that needs to be invented. 

cc @martinlippert

**Comment by martinlippert** [comment]
I think there is a Groovy extension for VSCode somewhere on their marketplace, but I don't know the details. Ideally it would be great if you could just install both extensions and go from there, but having references from Groovy code to Java and vice versa causes an interesting problem. Who should compile first? I am not even sure of the Groovy extension compiles the Groovy code or does just syntax highlighting etc. But definitely worth a try.

**Comment by intoCL** [comment]
Thanks guys.

@fbricon Completely understand. Was just taking a flyer. Sadly, we may have to use IntelliJ and VS Code for the rest of the stuff, which is a pity cos, having being spoilt with proper Visual Studio historically, our impression of IntelliJ based on our use of it previously was quite negative. We were hoping to get integrated support for everything in one place. I wonder if IKVM.net/Mono might not be a solution to future language interop via the CLI runtime one day, but that would probably require getting rid of language servers in totality. Or maybe I'm just displaying my total ignorance of these low-level compilation issues.

@martinlippert We found [this](https://github.com/Microsoft/vscode/tree/255a8cec275dc6e1e71915251b5ff4adcfc4ba97/extensions/groovy) last night but there don't seem to be any instructions to install from source and we can't find it on the Marketplace anywhere. I have been pondering the same issues you raised myself this morning so we will try and hack that extension in today but we are not going to pursue that avenue for too long if it works in IntelliJ out of the box. I'll let you know how we get on.

**Comment by martinlippert** [comment]
There is still the groovy-eclipse implementation around (we don't work on it ourselves anymore, but someone else took that over), which uses a compiler that cam compile Java and Groovy at the same time. In case you need a close interop between Java and Groovy, this might be worth exploring. It is a plugin for Eclipse only (so not related to language servers, VSCode, or anything like that), but since I don't know exactly what you are looking for, I thought it is worth mentioning.

**Comment by intoCL** [comment]
Thanks for the suggestion. Yeah, we were wanting Java/Groovy compilation in VSCode in the ideal situation. I'm pretty sure IntelliJ supports it but we will discover that later. We're even less than impressed with Eclipse than IntelliJ to be honest (extremely slow) so we converted a lot of our projects to IntelliJ for evaluation purposes. I don't mean to sound like a snob, but our experience has been all Visual Studio over the years, and it really is the bees'. We were hoping that VS Code could cover all our bases in our excursion into the open source world.

**Comment by intoCL** [comment]
We realised [this](https://github.com/Microsoft/vscode/tree/255a8cec275dc6e1e71915251b5ff4adcfc4ba97/extensions/groovy) was at best syntax highlighting and did not give cross-compilation and debugging features. So we have migrated our Java/Groovy stuff to IntelliJ. Closing this issue now.

**Comment by SanjayGautam** [comment]
was this feature implemented any time later ?

**Comment by tekleayele** [comment]
Has there been any update since the last convo on this issue/blocker ?

**Comment by Gaming32** [comment]
I'm personally not asking for Groovy syntax support, but simply support to be able to load Groovy code from Java. This wouldn't require any fancy language server stuff for Groovy, but just the ability to compile Groovy, which can be added with just adding Groovy as a dependency.
