### ISSUE TITLE
Cannot build the Java Language Server repo

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#2051]
When I run `npm run build-server` today, it fails to resolve the target definition with the following errors:

```
[ERROR] Failed to resolve target definition C:\<redacted>\eclipse.jdt.ls\org.eclipse.jdt.ls.target\org.eclipse.jdt.ls.tp.target: Failed to load p2 metadata 
repository from location https://download.eclipse.org/technology/m2e/snapshots/1.18.2/latest/: No repository found at https://download.eclipse.org/technology/m2e/snapshots/1.18.2/latest. -> [Help 1]
```

The link [https://download.eclipse.org/technology/m2e/snapshots/1.18.2/latest/](https://download.eclipse.org/technology/m2e/snapshots/1.18.2/latest/) is forbidden.

Also I found [https://download.eclipse.org/releases/2021-06/](https://download.eclipse.org/releases/2021-06/) becomes inaccessible as well.

@rgrunber @fbricon Do you know if there is anything happen upstream?

**Comment by jdneo** [comment]
It's working now.

**Comment by rgrunber** [comment]
I believe there were some access issues yesterday affecting everyone, that have since been resolved.

**Comment by rgrunber** [comment]
Outage appears to be ongoing so we should expect some issues https://bugs.eclipse.org/bugs/show_bug.cgi?id=565644#c31 .
