### ISSUE TITLE
When setting date variables in typeComment and generate comment manually, some variables can't be parse.

### ISSUE THREAD

**Issue by duskmont** [redhat-developer/vscode-java#2052]
When setting "${year}-${month}-${day} ${hour}:${minute}" in "java.templates.typeComment" and generate comment manually, some variables can't be parse.

##### Environment
- Operating System: Windows
- JDK version: java 8
- Visual Studio Code version: 1.58.2
- Java extension version: v0.80.0

##### Steps To Reproduce
1. setting "java.templates.typeComment" as follow
```json
  "java.templates.typeComment": [
    "/**",
    " * ",
    " * @author  username",
    " * @date    ${year}-${month}-${day} ${hour}:${minute}",
    " */"
  ]
```
2. type "/**" above “class” line
3. Select "javadoc comment" and Enter
4. Comment generated as follow
```java
/**
 *
 * @author  username
 * @date    2021-month-day hour:minute
 */
```

##### Current Result
```java
/**
 *
 * @author  username
 * @date    2021-month-day hour:minute
 */
```

##### Expected Result
```java
/**
 *
 * @author  username
 * @date    2021-08-05 09:00
 */
```

##### Additional Informations
Such case happened when generate class comment manually. Create java file is OK.

**Comment by testforstephen** [comment]
Currently only creating new file consumed these variable templates. Generating javadoc didn't.

**Comment by rgrunber** [comment]
It seems to work for newly created files for fileHeader templates, but the mechanism should be the same for typeComment. In fact, I remembered https://github.com/redhat-developer/vscode-java/issues/1987 , which I really should merge.

Since ${year} is getting resolved (and not other placeholders, I wonder if there's some resolution happening on the language server side that we could potentially extend.

**Comment by rgrunber** [comment]
Our docs are slightly inaccurate at https://github.com/redhat-developer/vscode-java/wiki/Predefined-Variables-for-Java-Template-Snippets .

fileHeader is handled by vscode-java (which defines the terms directly in fileEventHandler.ts . However typeComment uses JDT-LS, and doesn't seem to support month, day, hour minute.

We could probably contribute these back into JDT at : https://git.eclipse.org/c/gerrit/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.core.manipulation/common/org/eclipse/jdt/internal/core/manipulation/CodeTemplateContextType.java#n181 . The implementation is pretty easy : https://git.eclipse.org/c/platform/eclipse.platform.text.git/tree/org.eclipse.text/src/org/eclipse/jface/text/templates/GlobalTemplateVariables.java#n208

**Comment by rgrunber** [comment]
We could also just make the change on our end until it finally makes it upstream.

```
diff --git a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
index 9b2a855b..21337104 100644
--- a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
+++ b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
@@ -15,6 +15,7 @@ package org.eclipse.jdt.ls.core.internal.preferences;
 import java.io.IOException;
 import java.io.StringWriter;
 import java.io.Writer;
+import java.util.Calendar;
 import java.util.Hashtable;
 import java.util.LinkedHashMap;
 import java.util.List;
@@ -46,7 +47,10 @@ import org.eclipse.jdt.internal.corext.util.CodeFormatterUtil;
 import org.eclipse.jdt.ls.core.internal.IConstants;
 import org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin;
 import org.eclipse.jdt.ls.core.internal.StatusFactory;
+import org.eclipse.jface.text.templates.SimpleTemplateVariableResolver;
 import org.eclipse.jface.text.templates.Template;
+import org.eclipse.jface.text.templates.TemplateContext;
+import org.eclipse.jface.text.templates.TemplateContextType;
 import org.eclipse.lsp4j.ClientCapabilities;
 import org.eclipse.text.templates.ContextTypeRegistry;
 import org.eclipse.text.templates.TemplatePersistenceData;
@@ -104,6 +108,9 @@ public class PreferenceManager {
 		registry.addContextType(new CodeTemplateContextType(CodeTemplatePreferences.INTERFACESNIPPET_CONTEXTTYPE));
 		registry.addContextType(new CodeTemplateContextType(CodeTemplatePreferences.RECORDSNIPPET_CONTEXTTYPE));
 
+		TemplateContextType tmp = registry.getContextType(CodeTemplateContextType.TYPECOMMENT_CONTEXTTYPE);
+		tmp.addResolver(new Month());
+
 		JavaManipulation.setCodeTemplateContextRegistry(registry);
 
 		// Initialize templates
@@ -123,6 +130,16 @@ public class PreferenceManager {
 		reloadTemplateStore();
 	}
 
+	public static class Month extends SimpleTemplateVariableResolver {
+		public Month() {
+			super("month", "Month Description"); //$NON-NLS-1$ //$NON-NLS-2$
+		}
+		@Override
+		protected String resolve(TemplateContext context) {
+			return Integer.toString(Calendar.getInstance().get(Calendar.MONTH) + 1);
+		}
+	}
+
 	public static void initializeJavaCoreOptions() {
 		Hashtable<String, String> javaCoreOptions = JavaCore.getOptions();
 		javaCoreOptions.put(JavaCore.CODEASSIST_VISIBILITY_CHECK, JavaCore.ENABLED);
```

**Comment by duskmont** [comment]
> We could also just make the change on our end until it finally makes it upstream.
> 
> ```
> diff --git a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
> index 9b2a855b..21337104 100644
> --- a/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
> +++ b/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/PreferenceManager.java
> @@ -15,6 +15,7 @@ package org.eclipse.jdt.ls.core.internal.preferences;
>  import java.io.IOException;
>  import java.io.StringWriter;
>  import java.io.Writer;
> +import java.util.Calendar;
>  import java.util.Hashtable;
>  import java.util.LinkedHashMap;
>  import java.util.List;
> @@ -46,7 +47,10 @@ import org.eclipse.jdt.internal.corext.util.CodeFormatterUtil;
>  import org.eclipse.jdt.ls.core.internal.IConstants;
>  import org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin;
>  import org.eclipse.jdt.ls.core.internal.StatusFactory;
> +import org.eclipse.jface.text.templates.SimpleTemplateVariableResolver;
>  import org.eclipse.jface.text.templates.Template;
> +import org.eclipse.jface.text.templates.TemplateContext;
> +import org.eclipse.jface.text.templates.TemplateContextType;
>  import org.eclipse.lsp4j.ClientCapabilities;
>  import org.eclipse.text.templates.ContextTypeRegistry;
>  import org.eclipse.text.templates.TemplatePersistenceData;
> @@ -104,6 +108,9 @@ public class PreferenceManager {
>  		registry.addContextType(new CodeTemplateContextType(CodeTemplatePreferences.INTERFACESNIPPET_CONTEXTTYPE));
>  		registry.addContextType(new CodeTemplateContextType(CodeTemplatePreferences.RECORDSNIPPET_CONTEXTTYPE));
>  
> +		TemplateContextType tmp = registry.getContextType(CodeTemplateContextType.TYPECOMMENT_CONTEXTTYPE);
> +		tmp.addResolver(new Month());
> +
>  		JavaManipulation.setCodeTemplateContextRegistry(registry);
>  
>  		// Initialize templates
> @@ -123,6 +130,16 @@ public class PreferenceManager {
>  		reloadTemplateStore();
>  	}
>  
> +	public static class Month extends SimpleTemplateVariableResolver {
> +		public Month() {
> +			super("month", "Month Description"); //$NON-NLS-1$ //$NON-NLS-2$
> +		}
> +		@Override
> +		protected String resolve(TemplateContext context) {
> +			return Integer.toString(Calendar.getInstance().get(Calendar.MONTH) + 1);
> +		}
> +	}
> +
>  	public static void initializeJavaCoreOptions() {
>  		Hashtable<String, String> javaCoreOptions = JavaCore.getOptions();
>  		javaCoreOptions.put(JavaCore.CODEASSIST_VISIBILITY_CHECK, JavaCore.ENABLED);
> ```

**Comment by duskmont** [comment]
Thanks for replay and support @rgrunber
