### ISSUE TITLE
Convert class to record

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#2053]
Add code action to convert class to Java 16 record.

**Comment by fbricon** [comment]
AFAIK, there's no such refactoring available in JDT. So it'd have to be contributed upstream first, ideally.

**Comment by GavinRay97** [comment]
Coincidentally, had just filed this here:
https://github.com/eclipse/eclipse.jdt.ls/issues/1841

Please thumbs-up if you also would like this! 🙂

**Comment by rgrunber** [comment]
Closing as a duplicate of https://github.com/eclipse/eclipse.jdt.ls/issues/1841 . We can track the progress there.
