### ISSUE TITLE
Failed to get sources. Instead, stub sources have been generated by the disassembler.

### ISSUE THREAD

**Issue by DanieleStrafile** [redhat-developer/vscode-java#2055]
Hello, 

I have a multi project workspace and whenever I try to open from one project a java class belonging to another project, I get a .class "stub" file, rather than the proper .java file. The shown class is just a skeleton of the real implementation class. It seems that the link between projects is broken, they are not able to find one another. At the top of each "stub" class file I see the following comment:

 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.

I also observe that whenever one of these stub classes is opened, I see the following output in the Language Support For Java extension: "Unable to load IDecompiler class for jarFileContentProvider". Could you guys help me with it? What could be going wrong?? Since it is a work project, I may be constrained in what kind of information I can give about the project itself, but I will do my best.

##### Environment
- Operating System: Windows 10
- JDK version: 11
- Visual Studio Code version: 1.59
- Java extension version: v0.80.0

**Comment by snjeza** [comment]
@DanieleStrafile could you attach a project example?

**Comment by DanieleStrafile** [comment]
@snjeza I could, but it may take some time. In the meantime, could you please help me to understand how does the vscode connect project sources with one another? Via the pom.xml files? thanks!

**Comment by DanieleStrafile** [comment]
@snjeza  I have activated the verbose mode of the extension, via "java.trace.server": "verbose". Here is what I see when I try to navigate from one project to another

[Trace - 10:46:55 AM] Sending request 'workspace/executeCommand - (265)'.
Params: {
    "command": "vscode.java.resolveMainMethod",
    "arguments": [
        "jdt://contents/common-0.0.1-20210727090511-482ea35bb6f4d07411a59697e31703127306f0f4.jar/<censoredpath>/Tenant.class"
    ]
}


Does that give us a clue about what is going on? I am navigating from project stripe to project common and opening class "Tenant" which is contained in common. However, instead of navigating to project common, the IDE navigates to the target folder of project stripe and opens the compiled file "Tenant.class" !!

**Comment by DanieleStrafile** [comment]
@snjeza any idea? I would really like to continue using vscode, but without being able to debug or see references from one project to another that is a show stopper unfortunately. I am using the workspace feature of vscode to show all projects (6 in total) in one screen

**Comment by jialigit** [comment]
I also encounter this, and i really want to debug the lib sources.   desperate. Does someone know how to kick it out?

**Comment by testforstephen** [comment]
@jialigit Are you using any build tools? For maven, Java extension will download its sources on demand, it may have some latency while the library sources are available.

You can also use mvn cli to download the sources and javadoc manually.

```bash
mvn dependency:sources dependency:resolve -Dclassifier=javadoc
```

**Comment by jialigit** [comment]
> @jialigit Are you using any build tools? For maven, Java extension will download its sources on demand, it may have some latency while the library sources are available.
> 
> You can also use mvn cli to download the sources and javadoc manually.
> 
> ```shell
> mvn dependency:sources dependency:resolve -Dclassifier=javadoc
> ```

Oh, can not thank you more.  yes, I am using vs code. After downloaded the decompiler extension, it works. 

And I am trying to find if I can use vs code for work only, and for now find it not quickly as I thought. So I am curious what is the best practice workflow using vs code. I really do not want a IDE block my system too much. Every time I see the process bar signaling something is in the way , just wait, I feel desperate. Nowadays, project often has many modules so that eat much mem. IDE stuck there...Restart annoying. And I find vs code can not save file automatically while I edit a file, which IDEA  do it very well. En, hope to see it come soon.

**Comment by fbricon** [comment]
vscode does support autosave. 

![Screenshot 2021-12-10 at 11 09 13](https://user-images.githubusercontent.com/148698/145557274-b2bbc9dc-7b26-4ed9-bcff-389191b8d8b8.png)

For Java files, If you're using afterDelay, I recommend increasing the files.autoSaveDelay to 2000ms, to limit CPU usage
