### ISSUE TITLE
Added Classpathentry to .classpath vanishes for every build in Maven java project 

### ISSUE THREAD

**Issue by KameshwarB** [redhat-developer/vscode-java#2058]
### Added Classpathentry to .classpath vanishes for every build in Maven java project 
Hello there, 
    My project uses mustache templates to get the list of the POJO classes and add to target/generated-sources, during each build the classpathentry added is deleted automatically and only the set of classpath entries which is by default added.
whatever the entries that was added to the project classpath should be there. but, entries vanishes after each build,  i do build by both integrated terminal as well as git bash, both cases remain the same.
Note: this is can't be replicated at first time , but with multiple retires it is replicated.

##### Environment
- Operating System: Windows 10
- JDK version: open JDK 11
- Visual Studio Code version: 1.59.0 latest
- Java extension version:  Language Support for Java(TM) by Red Hat  v0.80.0

##### Steps To Reproduce
1. add a class path entry in .classpathfile like below 
```
		<classpathentry kind="src" path="target/generated-sources/swagger/src/main/java">
			<attributes>
				<attribute name="optional" value="true"/>
				<attribute name="maven.pomderived" value="true"/>
			</attributes>
		</classpathentry>
		<classpathentry kind="src" path="project-app/target/generated-sources/swagger/src/main/java">
			<attributes>
				<attribute name="optional" value="true" />
				<attribute name="maven.pomderived" value="true" />
			</attributes>
		</classpathentry>
```
2. then try to build your project with `mvn clean install` 
**Additional information**
please use a maven project  to check this and build your app each time and multiple time.

**Comment by rgrunber** [comment]
Could you use https://www.mojohaus.org/build-helper-maven-plugin/usage.html to configure additional source directories in your pom file ? I tried adding that goal to a Maven project, and it seemed to persist the sources into the .classpath.

Generally, the `.classpath` file is not meant to be touched since the language server is responsible for its contents.

@snjeza is there another way to do this ?

**Comment by snjeza** [comment]
>  is there another way to do this ?

You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/177

**Comment by KameshwarB** [comment]
thanks for quick response @snjeza and @rgrunber , this resolves my issue
