### ISSUE TITLE
Class outline doesn't work for .class files not in the workspace

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#206]
1. Have a java file with a reference to java.util.HashMap
2. Ctrl+click on java.util.HashMap to open it 
3. Try `Ctrl+Shift+o` (`Cmd+Shift+o` on Mac) to search for symbols 
=> no attributes or methods are found

This only works for classes physically present in the workspace.

This relates to method search for classpath references mentioned in #204

**Comment by fbricon** [comment]
@snjeza do you want to look at that one? It's something around https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/DocumentSymbolHandler.java#L65

**Comment by snjeza** [comment]
@fbricon I will try it.

**Comment by fbricon** [comment]
Thanks. My guess is the server receives a `jdt://` like URI and ignores it

**Comment by fbricon** [comment]
Fixed with https://github.com/eclipse/eclipse.jdt.ls/commit/40484c15ac025be2fe054b2ba148b6fe4e847859
