### ISSUE TITLE
Start VSCode after upgrading from junit4 to junit5 The Java service has been abnormal:

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#2062]
Deprecated. . .

**Comment by zhouxinghong** [comment]
After I upgraded from junit 4.13.2 to junit5.7.1, I received the exception message every time I started VSCode. The original junit4.13.2 did not have this problem during the VSCode startup process.
I am upgrading the maven pom file, please see below:
old:
`
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.13.2</version>
    <scope>test</scope>
</dependency>
`
new:
`
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-api</artifactId>
    <version>5.7.1</version>
    <scope>test</scope>
</dependency>
`

**Comment by zhouxinghong** [comment]
Before the upgrade, I cleared all the local junit4 dependency packages before upgrading.

**Comment by testforstephen** [comment]
could you please share a sample project for us to reproduce the problem?

**Comment by zhouxinghong** [comment]
The detailed process of my upgrade has been described above very clearly,
You can try SpringBoot2.4.5 Junit4.13.2~Junit5.7.1. . . .
