### ISSUE TITLE
Why is java.signatureHelp disabled by default?

### ISSUE THREAD

**Issue by fvclaus** [redhat-developer/vscode-java#2063]
I had a shortcut assigned to `Trigger parameter hints` which I always used when editing Typescript or Javascript files. I didn't work while editing Java files, and therefore I assumed that this extension does not support parameter hints. Why else would it not work? I did not take me too long to find this setting, but only because my `when` expression was assigned to `editorHasSignatureHelpProvider` which hinted me to LSP and I eventually stumbled over the setting by looking at the LS log and searching for `signatureHelp` inside the source code of this extension.

Why is this not enabled by default? Users coming from Typescript (or other languages) where this is enabled by default will probably not think about looking for a setting to activate it.

**Comment by fbricon** [comment]
Because Java completion already provides all overloaded signatures (contrary to Typescript), we found that enabling signatureHelp by default was more annoying than not.

**Comment by fvclaus** [comment]
When you say annoying, do you mean that the parameter hints and code completion is visible at the same time? 
![vscode_signatureHelp_enabled_both](https://user-images.githubusercontent.com/2384738/129693398-d6fd97ba-9e60-4eb3-a2ad-1448d011e497.png)

Overloaded signatures are available in the parameter hint popup. The parameter hint has up and down navigation arrows in the lower left corner to navigate through the different signatures:

Overloaded signature 1
![vscode_signaturehelp_1of2](https://user-images.githubusercontent.com/2384738/129692379-29df511b-cff1-4161-9739-1568508f38d3.png)
Overloaded signature 2
![vscode_signaturehelp_2of2](https://user-images.githubusercontent.com/2384738/129692387-8ee97a0f-fb30-40d4-b0c5-3cdf36514368.png)

There are even keyboard shortcuts for navigating:
- `showNextParameterHint` assigned to Alt+Down on my machine
- `showPrevParameterHint` assigned to Alt+Up on my machine

Would it be possible to hide the code completion when the parameter hint is visible? Code completion is inferior to parameter hints: It does not hightlight the current parameter and can only display a limited number of parameters.  In the first screenshot, the overloaded constructor with only 4 parameters could already not be displayed entirely. This would also align more closely with the way the Typescript completion works.

**Comment by fvclaus** [comment]
I looked into this a little bit and changed the language server to not return completions inside functions and constructors. This does not work in most cases, because vscode will only call `document/completion` under certain circumstances. If you type `ArrayL` and ask for completion, vscode will only ask the language server once and filter the `CompletionItems` as the user types.

![arraylist_completion](https://user-images.githubusercontent.com/2384738/132033514-469fd3db-54b1-44f1-845f-fff7a4a13248.gif)

I tracked down the code inside `vscode` that controls when the `CompletionItemProvider` is called:
https://github.com/microsoft/vscode/blob/fc1a1e8f13af4fcf9c5b60e0a24bd14074f8c810/src/vs/editor/contrib/suggest/suggestModel.ts#L330

This seems like a good idea and means that this cannot be solved by returning different `CompletionItem`s depending on the cursor position.

Next I tried to align the language server completions more closely with Typescript. Typscript will provide a completion `stringify` at `JSON.st`. In JS, that actually makes sense, because `JSON.stringify` would be a valid reference to a function. After pressing `(` only the parameter hint appears. Providing a completion `ArrayList` in Java does not make sense, because `new ArrayList` or `myString.substring` is not valid Java. Despite these problems, I tried to work with this for a few days and can conclude that it lowers productivity quite noticably. The problem is not typing the extra `(`. What gets lost is the `TextEdit` that will insert the parameters with the ability to tab through them:
![parameter_without_tab](https://user-images.githubusercontent.com/2384738/132036452-348dd105-1ade-4b14-bd51-88d6a65e1337.gif)

In contrast to the default:
![parameter_with_tab](https://user-images.githubusercontent.com/2384738/132036489-e48247ba-8219-40ed-9de3-30cc268a27f4.gif)

I will try to open a enhancement propals on vscode or the language server spec. I think a combination of the two: Selecting a completion with parameters and automatically opening parameter hints would probably be a better solution.

**Comment by Eskibear** [comment]
For the issue that candidate list remains open, I can think of several solutions:

#### filterText
> 	/**
	 * A string that should be used when filtering a set of
	 * completion items. When `falsy` the label is used as the
	 * filter text for this item.
	 */
	filterText?: string;

Set a proper `filterText` can possibly work. E.g. `label` is "substring(int index)" and `filterText` is "substring".

#### commitCharacters
> 	/**
	 * An optional set of characters that when pressed while this completion is
	 * active will accept it first and then type that character. *Note* that all
	 * commit characters should have `length=1` and that superfluous characters
	 * will be ignored.
	 */
	commitCharacters?: string[];

According to the spec, if we add `(` as a commit character, it might commit the item when you input `(`. But **maybe** we have to change the text to insert. E.g. for item "substring(int index)", use "substring" as the `insertText` or `textEdit.newText`, instead of the whole signature.

#### CompletionItemLableDetails
[CompletionItemLabelDetails](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItemLabelDetails) will be in LSP 3.17, might be an option to improve the experience. 

E.g. `label` is "substring" and `filterText` is "substring".

**Comment by jdneo** [comment]
I think currently there is another behavior which is confusing.

The selected completion item is different from the content provided by signature helper:


https://user-images.githubusercontent.com/6193897/154922793-8a260d6c-40da-4645-9e0b-44a959caca74.mp4
