### ISSUE TITLE
can we run java formatter in command line?

### ISSUE THREAD

**Issue by liuzqt** [redhat-developer/vscode-java#2066]
I'm wondering is there any way we can run java formatter in command line? I would like to set up some auto-format hooks in my git workflow and I want to have the same result as I format code in vscode.

**Comment by fbricon** [comment]
It might be doable, see https://www.beyondjava.net/run-eclipse-formatter-command-line for inspiration, but we won't provide support for it. If it doesn't work, it doesn't work.
