### ISSUE TITLE
Easier class path support.

### ISSUE THREAD

**Issue by squishybanana04** [redhat-developer/vscode-java#207]
I do all of my compiling using the built in `javac` compiler which lets you use `javac someJavaFile.java -cp .:somefolder/*.jar:ajarfile.jar:anotherFolder:*.class`. I was wondering if there was a way to use that syntax (`.:files:stuff`) as a format for the classpath with this plugin.

**Comment by fbricon** [comment]
No this extension won't help here, as 
1 - classes are already compiled automatically by the java language server language 
2 - we strongly encourage users to rely on a build tool for compiling java (Maven or Gradle, pick your poison)

**Comment by squishybanana04** [comment]
At the moment I have a fake gradle script that I use just to get the intellisense. I don't ever use the script to compile and I just thought that was a waste of time.

Thanks anyways!
