### ISSUE TITLE
Feature Request - Rearrange members in "Java Projects" view

### ISSUE THREAD

**Issue by JasonWThompson** [redhat-developer/vscode-java#2072]
The "Java Projects" view displays all of the projects, types, and members of said types. I would like to be able to drag and drop the members to new locations in order to rearrange the order of a type. It would be even more desirable if I could drag and drop members to different types as well.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8
- Visual Studio Code version: 1.59.0
- Java extension version: v0.80.0

##### Steps To Reproduce
1. Open the explorer view
2. Expand JAVA PROJECTS
3. Expand a project and a type
4. Click on a member field or method
5. Drag to a new location

##### Current Result
Nothing happens

##### Desired Result
The member is moved to the new location in the source code.

##### Additional Informations
To understand this feature request better, open up the outline view in Eclipse. Make sure that the ordering is not set to alphabetical. Then start dragging and dropping member variables and methods.

**Comment by fbricon** [comment]
The Java Projects view is contributed by [Project Manager for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency). Please open your request in https://github.com/microsoft/vscode-java-dependency/issues
