### ISSUE TITLE
Add command to open Java Language Server logs

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#209]
Instead of having to [open the dev tools to find out where the server logs are](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs), it'd be more convenient to provide a command similar to `TypeScript : Open TS Server log file`. That'd be `Java : Open Java Language Server log file`

**Comment by snjeza** [comment]
@fbricon works fine for me.
