### ISSUE TITLE
reset "Don't ask again" config when refactoring class

### ISSUE THREAD

**Issue by zill057** [redhat-developer/vscode-java#2091]
Once I clicked "Don't ask again", I can not configure if asking me before refactoring anymore.

<img width="372" alt="ScreenShot" src="https://user-images.githubusercontent.com/19730264/131650125-23feae86-1a32-4636-8dc8-7c0a58637312.png">

When I moved class file into different package, I checked "Don't ask again",  I don't know how to reset this option. It doesn't show in my vscode config file.

##### Environment
- Operating System: macOS Monterey Beta 6
- JDK version: 11
- Visual Studio Code version: 1.59.1
- Java extension version: 0.81.0

##### Steps To Reproduce
1. move class file into different package
2. checked "Don't ask again" when refactoring dialog showing
3. try to reset the option, so I can confirm refactoring before execution 

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by testforstephen** [comment]
This dialog is provided by VS Code, you have to open an issue there for this.

A quick search in VS Code repo, there is a duplicate issue for this. https://github.com/microsoft/vscode/issues/24815. But this issue is locked, maybe we should open a new issue to restate the problem.

**Comment by zill057** [comment]
Thanks @testforstephen
