### ISSUE TITLE
Gradle project is not recognized

### ISSUE THREAD

**Issue by vincenzocorso** [redhat-developer/vscode-java#2095]
I've created a gradle multi-project, but is not recognized and the auto completion doesn't work.
I have installed `Extension pack for Java` and `Gradle extension pack`.
I have gradle 7.0.2 installed and the latest version of vs code.

<img src="https://i.imgur.com/1Qrdfgs.png"></img>

##### Environment
- Operating System: Ubuntu 21.04
- JDK version: 11.0.11
- Visual Studio Code version: 1.60.0
- Java extension version: 0.81.0

**Comment by fbricon** [comment]
anything in the logs (try command `Java: Open All Log Files)`? 
can you share your project?

**Comment by vincenzocorso** [comment]
My project: [quarkus-playground.zip](https://github.com/redhat-developer/vscode-java/files/7106732/quarkus-playground.zip)
I created a root project using `gradle init` and then I created a Quarkus subproject called `task-service` (I have updated `settings.gradle` to include it).

**Comment by vincenzocorso** [comment]
Logs seems fine
[log.txt](https://github.com/redhat-developer/vscode-java/files/7106826/log.txt)
[client_log.txt](https://github.com/redhat-developer/vscode-java/files/7106829/client_log.txt)

**Comment by snjeza** [comment]
I can't reproduce the issue.
@vincenzocorso Could you show your settings.json?

**Comment by fbricon** [comment]
Works for me too. Did you create task-service after opening quarkus-playground in vscode?
Can you try the "Import Java projects into Workspace" command? If that doesn't work try "Clean Java Language Server workspace"

**Comment by vincenzocorso** [comment]
Yes, I've created `task-service` after opening `quarkus-playground`.

I tried `Java: Clean Java Language Server workspace` as you have suggested and it worked. Thanks 👍
