### ISSUE TITLE
`Go to References` Find the wrong package name

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2096]
When I use the Go to Reference command, the feedback result is not correct. Only the class name is the same, the package name is not the selected package name

##### Environment
- Operating System: windows10 21H1
- JDK version: 16
- Visual Studio Code version: 1.60
- Java extension version: 0.81.0

##### Steps To Reproduce
1. Open a class `javax.annotation.processing.Processor`
2. Run `Go to References`

[annotationProcessing.log](https://github.com/redhat-developer/vscode-java/files/7109074/annotationProcessing.log)

##### Current Result
![image](https://user-images.githubusercontent.com/63572041/132079267-8cd7c628-3446-4ef4-bc38-860b58e2cd6c.png)

##### Expected Result

Only find implementation classes belonging to ``javax.annotation.processing.Processor`

**Comment by snjeza** [comment]
@mozhuanzuojing could you attach a project example?
