### ISSUE TITLE
[Feature Request] Method Signature Refactoring

### ISSUE THREAD

**Issue by DreamFulFil** [redhat-developer/vscode-java#2104]
All prevalent IDEs such as Eclipse, IntelliJ, Netbeans provides a way to refactor method signatures.
It would be nice to have such a feature implemented in VSCode since the methods are usually spread across the entire project,  and currently no such refactoring actions are supported(checked the documentation and opened/closed issues).
Visual Studio seems to have such an existing [feature](https://docs.microsoft.com/en-us/visualstudio/ide/reference/change-method-signature?view=vs-2019)

Thank you for the hard work.

**Comment by rgrunber** [comment]
It should be possible, but the ricky part is creating a UI around it. We could probably have a look at https://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.ui/ui%20refactoring/org/eclipse/jdt/internal/ui/refactoring/ChangeSignatureWizard.java as a start point.

**Comment by Med-H** [comment]
any news on this?

**Comment by coltongoates** [comment]
I'm also anxiously awaiting this feature. How is feature work prioritized? Can we vote somewhere?

**Comment by ewot** [comment]
This is now implemented in the Netbeans language server plugin: https://marketplace.visualstudio.com/items?itemName=ASF.apache-netbeans-java

That plugins has other issues however, so I hope we will get this soon.

**Comment by CsCherrYY** [comment]
I'll take a look these days.

**Comment by CsCherrYY** [comment]
we have an upstream PR: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/428 which will make the processors available in jdt.ls.
