### ISSUE TITLE
After waiting for one night, it takes about 1 minute to hover on the class for the first time

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2108]
When I work every morning, I open a java file for the first time, place the mouse on a certain class, and wait for about 1 minutes before there is feedback. I used jProfiler to record the CPU activity graph of jdt.ls, help to see if it is the problem? I'm not sure if this is an issue.
##### Environment
- Operating System: windows10 21H1
- JDK version:16
- Visual Studio Code version:1.60
- Java extension version:0.81.0

##### Steps To Reproduce
1. Open a project and wait for one night
2. Make sure to open a java file for the first time, place the mouse on a class, and wait for hover feedback

![image](https://user-images.githubusercontent.com/63572041/133178211-31da18bd-8ee1-444f-8c22-5f6d79ec4f72.png)

##### Current Result
need wait about 1 minutes ，then receive feedback
##### Expected Result
hover，waiting time does not exceed 10 seconds

![image](https://user-images.githubusercontent.com/63572041/133179431-47f3da16-6a61-4f8a-8b6d-666eee87bb6d.png)

##### Additional Informations
I am also preparing to test the situation of different projects, which will be written here later.

**Comment by rgrunber** [comment]
Is there any indication that the project is being loaded/built when you do this ? The javadoc hover is dependent on the project build completing, so generally when one tries to hover over some type while that happens you would probably see some smaller "loading" popup until the project has finished loading.

However, if the project is already loaded, with the VSCode editor simply staying open the whole time, and you still see the loading, that could be an issue. It's strange because we do have code to abort loading beyond 500ms ( https://github.com/eclipse/eclipse.jdt.ls/issues/1664 ), and just display a much simpler hover.

**Comment by mozhuanzuojing** [comment]
> Is there any indication that the project is being loaded/built when you do this ? The javadoc hover is dependent on the project build completing, so generally when one tries to hover over some type while that happens you would probably see some smaller "loading" popup until the project has finished loading.
> 
> However, if the project is already loaded, with the VSCode editor simply staying open the whole time, and you still see the loading, that could be an issue. It's strange because we do have code to abort loading beyond 500ms ( [eclipse/eclipse.jdt.ls#1664](https://github.com/eclipse/eclipse.jdt.ls/issues/1664) ), and just display a much simpler hover.

@rgrunber  the project is already loaded, with the VSCode editor simply staying open the whole time, there is no compiling and building.   If it is a particularly small project, there are only a few java files. There will be no waiting.
I also found that as long as my mouse pointer is placed in VSCode, no matter whether the java file is opened or not. Will trigger org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didChangeWatchedFiles


> this is a hover normal CPU Call Tree
<img width="612" alt="hover normal CPU Call Tree" src="https://user-images.githubusercontent.com/63572041/133356659-a32f321e-c1c4-4ca6-b36b-151623578d69.png">


> [hover waiting a minute CPU Call Tree.html.zip](https://github.com/redhat-developer/vscode-java/files/7166055/hover.waiting.a.minute.CPU.Call.Tree.html.zip)

**Comment by mozhuanzuojing** [comment]
I also often encounter `loading` during the development process, and the workspace is not compiled. What I can see with Jprofiler is
`29.6%-69,487 ms org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.didChangeWatchedFiles`.
I will test with springboot later.

![image](https://user-images.githubusercontent.com/63572041/133541165-93b14b22-dc31-45b5-a3a8-ba7df108225f.png)

**Comment by mozhuanzuojing** [comment]
@rgrunber I tested the spring-boot project and had the same problem. the first hover until jdt.ls return information, which lasted 3 minutes.
```git
git clone -b 2.5.x https://github.com/spring-projects/spring-boot.git
```
> my settings.json and gradle.properties

+ [settings.json.zip](https://github.com/redhat-developer/vscode-java/files/7181858/settings.json.zip)
+ [gradle.properties.zip](https://github.com/redhat-developer/vscode-java/files/7181861/gradle.properties.zip)

**Comment by snjeza** [comment]
@mozhuanzuojing 

Could you try update the following gradle properties

```
org.gradle.vfs.watch=true
```
to
```
org.gradle.vfs.watch=false
```

**Comment by mozhuanzuojing** [comment]
#2081

**Comment by mozhuanzuojing** [comment]
> @mozhuanzuojing
> 
> Could you try update the following gradle properties
> 
> ```
> org.gradle.vfs.watch=true
> ```
> 
> to
> 
> ```
> org.gradle.vfs.watch=false
> ```

@snjeza @rgrunber it's ok, Thank you all! Hope this configuration can be introduced to the top.
## This great change saves an average of more than an hour per day!


Finally confident to continue to study the gradle plugin.

**Comment by snjeza** [comment]
Related issue - https://github.com/eclipse/eclipse.jdt.ls/pull/1876#issuecomment-920295715

**Comment by rgrunber** [comment]
I think it's worth adding an entry to our https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting .

**Comment by rgrunber** [comment]
I've added https://github.com/redhat-developer/vscode-java/wiki/Gradle-Support#performance-degrades-with-gradle-project for now. @snjeza Is the reasoning just performance degredation due to limited resources to support the Gradle VFS over long periods of time or is it something else ?
