### ISSUE TITLE
Support platform specific extension

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#2109]
See https://github.com/microsoft/vscode/issues/23251#issuecomment-918989339, VS Code Marketplace now allows extensions to publish different VSIXs for each platform (Windows, Linux, macOS). We might consider taking advantage of this by packaging a platform-specific Java runtime in the extension itself.

This document has all the details:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions

**Comment by rgrunber** [comment]
LGTM https://download.jboss.org/jbosstools/jdt.ls/staging/java-1.2.0-476/
