### ISSUE TITLE
VS Code adds or removes a folder (non-java project), triggering a rebuild of the workspace.

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2111]
The compiled Java project already exists in VS Code. Then I added a folder to the workspace, and I saw that the Java project started to recompile.

##### Environment
- Operating System: window10 21H1
- JDK version:16
- Visual Studio Code version: 1.60
- Java extension version: 0.81.0

##### Steps To Reproduce
1. In the VS Code workspace, open a Java project and wait for the compilation to complete.
2. Add a folder of normal files
3. Remove this newly added folder

##### Current Result
Re-refresh and compile the Java project
##### Expected Result
Does not trigger refresh and compile the Java project

**Comment by snjeza** [comment]
I can't reproduce the issue.
@mozhuanzuojing Do you add a folder to the source directory? Could you provide an example?

**Comment by mozhuanzuojing** [comment]
@snjeza  This problem happened by accident, and now I close it first.
