### ISSUE TITLE
Using VS Code same as Eclipse packages and classes

### ISSUE THREAD

**Issue by JJ1006** [redhat-developer/vscode-java#2113]
![Screenshot (20)](https://user-images.githubusercontent.com/74872123/133594008-709bd038-6be3-4cb8-93f9-7d6f56ea2391.png)
![Screenshot (21)](https://user-images.githubusercontent.com/74872123/133594020-3b54fb57-7076-499e-8d92-e21d0d4ce80c.png)

[provide a description of the issue]
I am unable to use packages properly as it shows that a class is not able to get another even if it is public. While I am able to perform the same task in other IDE. I always prefer VS Code over any other IDE, but this problem is not getting solved. Please see to it...

##### Environment
- Operating System: Windows 11
- JDK version:15
- Visual Studio Code version: 1.60.1
- Java extension version: Red Hat

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
please attach a sample project reproducing this issue

**Comment by JJ1006** [comment]
[videotutoriallecturetwentyseven.zip](https://github.com/redhat-developer/vscode-java/files/7178082/videotutoriallecturetwentyseven.zip)

**Comment by fbricon** [comment]
Works for me. I just opened the videotutoriallecturetwentyseven folder in VS Code.

<img width="1791" alt="Screenshot 2021-09-16 at 15 38 05" src="https://user-images.githubusercontent.com/148698/133622313-34f188ff-2713-4f77-9adf-cf8e9229f987.png">

Can you share your vscode settings.json?

**Comment by JJ1006** [comment]
ohh...that is absolutely great. Please can you help me figure it out. Please find the code of settings.json below

{
  "C_Cpp_Runner.cCompilerPath": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\gcc.exe",
  "C_Cpp_Runner.cppCompilerPath": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\g++.exe",
  "C_Cpp_Runner.debuggerPath": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\gdb.exe",
  "C_Cpp_Runner.makePath": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\make.exe",
  "C_Cpp_Runner.warnings": [
    "-Wall",
    "-Wextra",
    "-Wpedantic"
  ],
  "C_Cpp_Runner.compilerArgs": [],
  "C_Cpp_Runner.includePaths": [],
  "C_Cpp_Runner.linkerArgs": [],
  "C_Cpp_Runner.cStandard": "",
  "C_Cpp_Runner.cppStandard": "",
  "C_Cpp_Runner.excludeSearch": [],
  "C_Cpp_Runner.enableWarnings": true,
  "C_Cpp_Runner.warningsAsError": false,
  "cSpell.ignoreWords": [
    "onlinewebfonts",
    "worktext"
  ],
  "cSpell.words": [
    "collobarations",
    "workchangetext"
  ],
  "liveServer.settings.port": 5501,
  "php.validate.executablePath": "C:/PHP8/php.exe"
}

**Comment by fbricon** [comment]
I don't see anything that might interfere. Make sure you opened videotutoriallecturetwentyseven in code (see my screenshots), not videotutoriallecturetwentyseven/lecturetwentyseven.
If that was the case already, open the command palette and execute `Java: Clean Java language server workspace` command.
You should not see any warning on the 1st line (package ...), about file not being on the project classpath. If you do see it still, please open the logs from the `Java: Open All Log Files` command, and attach them here.

**Comment by JJ1006** [comment]
![Screenshot (23)](https://user-images.githubusercontent.com/74872123/133658518-dd245039-0ec3-402b-a4aa-737ad8dd2974.png)
I fixed the issue, it was the code runner extension that was letting java import files. Thank you so much for your kind support.
