### ISSUE TITLE
Does not detect Maven sample project

### ISSUE THREAD

**Issue by sguillia** [redhat-developer/vscode-java#2121]
Hi!

This extension works out of the box on the [official JUnit5 samples](https://github.com/junit-team/junit5-samples), but only on Gradle projects.

![Capture du 2021-09-17 16-03-41](https://user-images.githubusercontent.com/15984272/133798354-53aa7d76-f3cc-4d5f-961b-66b8e0e44967.png)

##### Environment
- Operating System: `Linux 4.15.0-142-generic #146~16.04.1-Ubuntu`
- JDK version: `java --version: java 11.0.11 2021-04-20 LTS`
- Visual Studio Code version: `1.60.0-insider`
- Java extension version: `redhat.java v0.82.0`

##### Steps To Reproduce
1. git clone git<span></span>@github.com:junit-team/junit5-samples.git
2. code junit5-samples
3. Open `junit5-migration-gradle/src/test/java/com/example/project/FirstTest.java`
4. Open `junit5-migration-maven/src/test/java/com/example/project/FirstTest.java`

Observe the first file has the _Run test_ decorations, while the second one doesn't.

##### Current Result

Has a warning in the maven FirstTest.java file

##### Expected Result

Has no warning in the maven FirstTest.java file

##### Additional Informations

- Works out of the box with IntelliJ IDEA Community
- When I click "_Add Folder to Java Source Path_" on `junit5-migration-maven/src/test/java`:
  - At first, it removes the warning at the top of the file
  - After reload, complains about `The import org.junit cannot be resolved`

I am afraid I have no professional Java experience, my goal is to have the **Run test** buttons on both editors in the screenshot.
Thanks in advance

**Comment by fbricon** [comment]
Works for me:
<img width="1417" alt="Screenshot 2021-09-17 at 17 16 41" src="https://user-images.githubusercontent.com/148698/133807286-60067aa3-e0a7-4c90-b935-3d88e9d8912c.png">

Projects not working are kotlin, groovy, as expected, and Bazel (there might be a bazel extension that make it works out there).

Can you:
- enable verbose logging ("java.trace.server"="verbose" in settings.json)
- execute "Java: Clean Java Language Server Workspace" command
- and share the logs from  the "Java: Open All Log Files" command

**Comment by sguillia** [comment]
Hi @fbricon, many thanks for your quick reply. Here are the log files.
[log.txt](https://github.com/redhat-developer/vscode-java/files/7227456/log.txt)
[client.log.2021-09-24.8.txt](https://github.com/redhat-developer/vscode-java/files/7227457/client.log.2021-09-24.8.txt)
[client.log.2021-09-24.7.txt](https://github.com/redhat-developer/vscode-java/files/7227458/client.log.2021-09-24.7.txt)

Hope it helps

**Comment by snjeza** [comment]
> Works for me:

It works for me too.

@sguillia Could you try the following:

- disable the Eclipse PDE support extension
- close VS Code
- rm -rf ~/.config/Code\ -\ Insiders/User/workspaceStorage/
- rm -rf ~/.config/Code\ -\ Insiders/User/globalStorage
- repeat your steps

**Comment by sguillia** [comment]
Had the `java.import.maven.enabled` setting set to false. Works like a charm now.

I'm really sorry for the issue. I forgot this setting was set, and as a Java beginner I had no clue when reading the warning.

I first found out it worked in [Portable mode](https://code.visualstudio.com/docs/editor/portable), then investigated the differences between portable and classic installation.
Portable mode might help other users troubleshoot problems. Thanks @snjeza for pointing me in this direction.
