### ISSUE TITLE
Formatter: "Remove blank lines in Javadoc" is being ignored.

### ISSUE THREAD

**Issue by rhystedstone** [redhat-developer/vscode-java#2122]
The option "Remove blank lines in Javadoc" (`org.eclipse.jdt.core.formatter.comment.clear_blank_lines_in_javadoc_comment`) is being ignored. The output remains the same regardless of this setting.

##### Environment
- Operating System: Windows NT 10.0
- JDK version: 16.0.27 Hotspot
- Visual Studio Code version: 1.60.1 (user setup)
- Java extension version: v0.82.0

##### Steps To Reproduce
1. Use a custom formatter for Java
2. Change the option `org.eclipse.jdt.core.formatter.comment.clear_blank_lines_in_javadoc_comment` to true, either in the formatter preview, or directly via the xml.
3. Blank lines in javadocs aren't cleared.

Project:
![A snippet of my project's javadoc which displays 5 blank lines](https://user-images.githubusercontent.com/12123847/133908150-8dbcd343-cb80-456c-97c9-4e2b1898d47c.png)
Formatter Preview:
![A screenshot of the formatter preview which displays a tick next to "Remove blank lines in javadoc", yet the preview next to it displays 3 blank lines in the javadoc](https://user-images.githubusercontent.com/12123847/133908141-f9f92b88-c64d-482b-b2bb-982dbdb38769.png)

[log.log](https://github.com/redhat-developer/vscode-java/files/7190630/log.log)
**The jdt_ws log is attached - The java.trace logs returned nothing.**

##### Current Result

Currently the lines aren't removed from the javadoc.
```java
/**
 * Some description of the method
 * 
 * 
 * 
 * 
 * @param arg1 A parameter
 * @param arg2 Another parameter
 */
```

##### Expected Result

The lines should be removed from the javadoc:
```java
/**
 * Some description of the method
 * @param arg1 A parameter
 * @param arg2 Another parameter
 */
```

**Comment by CsCherrYY** [comment]
I can't reproduce this issue locally, could you attach your formatter profile?

**Comment by rhystedstone** [comment]
Also ignores this formatter: [eclipse-formatter.xml](https://gist.githubusercontent.com/rhystedstone/ebf64ad3abab6a382ad0c7f9da42093b/raw/8df63eaa2cc7cc3e2d575eacae62077625948c74/eclipse-formatter.xml)

**Comment by snjeza** [comment]
@rhystedstone could you show your settings.json (the java.format.settings.url and java.settings.url preferences)?

**Comment by snjeza** [comment]
Related issue: https://github.com/redhat-developer/vscode-java/issues/2429

**Comment by rhystedstone** [comment]
@snjeza My `java.format.settings.url` points to: `file:///C:/Users/Rhys/Development/language/java/eclipse-formatter.xml`, which is a copy of the one I mentioned earlier.
My `java.settings.url` was originally blank, but I found a workaround for the formatter, which involves getting eclispe to generate the prefs file. So, it's currently set to that file, located at `file:///C:/Users/Rhys/Development/language/java/settings.pref`

[settings.prefs](https://gist.github.com/rhystedstone/e5a1b30afcc3f1612ae0effc71cfbd14)
[eclipse-formatter.xml](https://gist.githubusercontent.com/rhystedstone/ebf64ad3abab6a382ad0c7f9da42093b/raw/8df63eaa2cc7cc3e2d575eacae62077625948c74/eclipse-formatter.xml)

**Comment by snjeza** [comment]
@rhystedstone Could you try https://github.com/snjeza/vscode-test/raw/master/java-1.6.1.vsix? It includes https://github.com/redhat-developer/vscode-java/pull/2451 and https://github.com/eclipse/eclipse.jdt.ls/pull/2089
You should see an error message if your java.format.settings.url or java.settings.url are not valid.

**Comment by rhystedstone** [comment]
I can confirm that this version does notify me of an invalid URL. However, my current settings do not display the notification until I ammend them to a known invalid path.

**Comment by rhystedstone** [comment]
I just tried to use the xml settings file again, but it didn't work.
My steps:
1. Remove the `java.settings.url` setting and reload VSCode
2. Double-check the `java.settings.formatter.url` setting points to the correct formatter (It did)
3. Attempted to format a document which I purposefully changed to something which should be corrected with the formatter (See below)
4. The document formatted, but the formatting was different, despite the settings matching those of my `settings.prefs` file.
5. Re-added the `java.settings.url` setting and reloaded VSCode.
6. The document formatted correctly.

### My formatter test:
Add multiple lines of text to a javadoc, with a new line between each.

If the formatter is following my preferences, all the new lines would be removed and a space placed between each line of text.
If the formatter is not following my preference at all, nothing should change.
If the formatter is not following my preferences properly, it will remove blank lines, but will keep the lines of text separate, which is what happens currently.

**Comment by rhystedstone** [comment]
I just got it working by removing the `java.format.settings.profile` key.
I don't know if there was an invalid character, but without that setting, it works with the xml.

It may be a good idea to also add a warning for an invalid value as it fails too silently.

**Comment by rhystedstone** [comment]
This issue can be closed as the original issue is 8 months old, so the formatter has had several different settings.
It's possible that the old formatter file I used was invalid somehow, or an option I implemented was invalid.

**Comment by snjeza** [comment]
> I just got it working by removing the java.format.settings.profile key.
I don't know if there was an invalid character, but without that setting, it works with the xml.

You should see 
```
Invalid settings: java.format.settings.profile=<Incorrect_Profile>. The '<Incorrect_Profile' profile doesn't exist.
```
in your log
