### ISSUE TITLE
Quickfixes should be available at the line level

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#2130]
Given the following code:
```java
public class Foo {
    public static void main(String[] args) {
        System.out.println(greeting());
    }
}
```
`greeting` is underlined in red, because the method doesn't exist. If you put your cursor on it, and list the quickfixes (`ctrl+.`), you get to create the missing method.
Now it would be nice to click anywhere on that line to also see the same quickfix, like Intellij or Eclipse.

cc. @maxandersen

**Comment by rgrunber** [comment]
Seems to be working well for me. Should the quick-fixes on a particular line be suppressed if the code action request is made on a selection range (as opposed to an offset) ? We should definitely have a settings for this.

**Comment by rgrunber** [comment]
Another remark : It looks like the compilation errors override everything else on the line until the error is addressed. With the change disabled, `System.out.println(greeting());` (greeting undefined) has access to all the `Extract to ..`, `Convert to static ..` when triggering code actions on `out`. Now, the only code action one can get for the entire line is basically to generate the missing method. Only once that's fixed, can you see the other code actions from before.

@fbricon , let me know your thoughts on this. I could certainly see us saying that there's no point suggesting other actions when there's clearly a compilation error to be addressed.

**Comment by snjeza** [comment]
>  Now, the only code action one can get for the entire line is basically to generate the missing method. Only once that's fixed, can you see the other code actions from before.

@rgrunber Could you try https://github.com/snjeza/vscode-test/raw/master/java-0.83.1.vsix. It doesn't include a client specific code described at https://github.com/eclipse/eclipse.jdt.ls/pull/1908#discussion_r729495599
