### ISSUE TITLE
Do not ask to save a currently open .class file when launching in debug mode

### ISSUE THREAD

**Issue by Artur-** [redhat-developer/vscode-java#2131]
If you have a .class file open when launching e.g. a Maven target in debug mode, VS Code popups up a dialog that asks you to save the current `.class` file which is in a JAR file.

![image](https://user-images.githubusercontent.com/260340/134885508-27712491-7e06-4ea9-8d46-a24b516dc385.png)

I rarely want to save `.class` files

##### Environment
- Operating System: mac Big Sur
- JDK version: 16
- Visual Studio Code version: 1.60.2
- Java extension version: 0.82.0

##### Steps To Reproduce
1. Open a Java project
2. cmd-t ->  e.g. `#java.lang.string`
3. Launch a Maven target in debug mode

##### Current Result
A save popup

##### Expected Result
No popup

**Comment by fbricon** [comment]
This doesn't happen when simply running a java class, so this looks like a problem specific to vscode-maven. Please open a bug in https://github.com/Microsoft/vscode-maven/issues
