### ISSUE TITLE
import regions not computed for .class files

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#2133]
When opening a .class file, the import statements are not folded by default, with `"editor.foldingImportsByDefault": true`. Seems you can't even fold the import block manually. Something's fishy here.
I noticed that in https://github.com/redhat-developer/vscode-java/pull/2132#issuecomment-927960228

**Comment by rgrunber** [comment]
Explanation : https://bugs.eclipse.org/bugs/show_bug.cgi?id=72503

**Comment by rgrunber** [comment]
Just a note, this is still possible to implement. Just not from the Java model side. On the AST side, we could find the node corresponding the import statements, and use those offsets to generate the folding range. I would just be curious if the Java model side has anything at all to accomplish this.

**Comment by baincd** [comment]
As a workaround, I have created a VS Code extension that adds a folding region for imports on .class files: https://marketplace.visualstudio.com/items?itemName=baincd.java-class-imports-folding

**Comment by rgrunber** [comment]
Instead of using the AST parsing facility, @JessicaJHee  went with using the scanner's `ITerminalSymbols.TokenNameimport` to detect the import range, which we do use for other things. This should work as expected now.
