### ISSUE TITLE
Gradle kts build files

### ISSUE THREAD

**Issue by MatthewFagan** [redhat-developer/vscode-java#2135]
Hi. We are trying to get a client moved over from Eclipse to VS Code, but they are complaining about gradle kts build file support. The VS Code plugin does not provide any intellisense or other features. (I'm not totally sure of the details).

There was a recently closed issue: https://github.com/redhat-developer/vscode-java/issues/632

The client has tried it, but it is not sufficient for them and it remains a blocking issue for moving them to VS Code. Is there any work being done to add these features?

**Comment by fbricon** [comment]
We're using the same buildship support as in Eclipse, with the same limitations. Are you saying your client get gardle kts completion support in Eclipse?

**Comment by 0dinD** [comment]
#632 was just about adding support for importing Java projects using the Gradle Kotlin DSL. Anything else is probably out of scope for this extension.

There is ([as of recently](https://github.com/microsoft/vscode-gradle/blob/65ffe6c6145519848680b3899843ff115c831359/CHANGELOG.md?plain=1#L43)) work being done by Microsoft in [microsoft/vscode-gradle](https://github.com/microsoft/vscode-gradle), [the latest release](https://github.com/microsoft/vscode-gradle/releases/tag/3.8.0) just added an initial version of the intellisense (and it has a bunch of other nice features). Although as far as intellisense goes I think it only supports the Groovy DSL for now. You could try [fwcd/vscode-kotlin](https://github.com/fwcd/vscode-kotlin), but I'm not sure how well it works given that I don't use the Kotlin DSL.

**Comment by MatthewFagan** [comment]
OK, it looks like I might have misunderstood the client's issues. I will see if I can find out more info
