### ISSUE TITLE
Formatter doesn't load format config after update

### ISSUE THREAD

**Issue by gline9** [redhat-developer/vscode-java#2142]
After updating to the latest version of the plugin, the format configuration configured no longer is used when formatting files through vscode.

##### Environment
- Operating System: Windows
- JDK version: 11
- Visual Studio Code version: 1.60.2
- Java extension version: 0.82.0

##### Steps To Reproduce
1. Place eclipse xml file on the file system tested with version 18 format
2. Configure url to point to file in global settings Java > Format > Settings: Url with format `file:///D:/<file location>`
3. Open java project
4. Format java file in project
5. Formatting uses default formatting and not the formatting configured in the xml file.

##### Current Result

File is formatted with the default format profile not the provided xml config

##### Expected Result

File is formatted with the provided xml config

##### Additional Informations

Note that this issue happened before and was reported in #1917 this is looking like a similar issue and the same reproduction produces the issue. This minimal reproduction can be found [here](https://github.com/gline9/vscode-java-format-reproduction).

To reproduce format the provided java file, notice that the curly brace for the class is joined back to a single line instead of multiple lines as is configured in the xml file.

**Comment by snjeza** [comment]
This issue is related to https://github.com/eclipse/eclipse.jdt.ls/pull/1893
You can try https://github.com/snjeza/vscode-test/raw/master/java-0.83.0.vsix

**Comment by gline9** [comment]
@snjeza it looks like that fixes the problem. Thanks for your help.

**Comment by gline9** [comment]
I just updated to 1.0.0 and it looks like this issue is fixed in that version.
