### ISSUE TITLE
Generate `@Override` on save when applicable

### ISSUE THREAD

**Issue by NatoBoram** [redhat-developer/vscode-java#2144]
I want to know when a method is overriding its super class by automatically adding the `@Override` annotation on save.

##### Current Result

```java
public String toString() {
	return super.toString();
}
```

##### Expected Result

```java
@Override
public String toString() {
	return super.toString();
}
```

##### Additional Informations

Example config:
```json
{
	"editor.codeActionsOnSave": {
		"source.generate.finalModifiers": true,
		"source.generate.override": true
	}
}
```

**Comment by rgrunber** [comment]
Seems like this would just require migrating the https://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/fix/Java50CleanUp.java , or some portion of it to jdt.core.manipulation. It handles adding the override as needed.

**Comment by rgrunber** [comment]
This can now be accomplished by setting :

```
"java.cleanup.actionsOnSave": [
  "addOverride"
]
```

Default is currently `[]` as it's difficult to have something everyone would agree with. Going forward, we should add more of these cleanups though.

**Comment by NatoBoram** [comment]
Generally, these actions are there:

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.fixAll.eslint": true,
    "source.fixAll.markdownlint": true,
    "source.fixAll.sortJSON": false,
    "source.generate.finalModifiers": true,
    "source.organizeImports": true,
    "source.sortMembers": true
  }
}
```

**Comment by datho7561** [comment]
> Generally, these actions are there:

I looked into implementing it this way, but this setting and functionality is exclusive to VS Code, and the core of the plugin (the language server) is used in many different editors besides VS Code, such as neovim. We wanted to be able to provide the different clean up actions in a way that all these editors can use. Thanks for mentioning this, though!
