### ISSUE TITLE
CompletionItem.documentation should be plain text

### ISSUE THREAD

**Issue by aeschli** [redhat-developer/vscode-java#215]
v0.4.0
- in VSCode, create a sample project and do code assist on 
```java
package com.aeschli.testapp;

public class TestHelper {
    public static boolean compare(String a, String b) {
        return a.|
    }
}
```
This shows code assist proposals. Looking at the issue descriptions, they are not correctly rendered.
![image](https://cloud.githubusercontent.com/assets/6461412/26140618/0effc08a-3ad8-11e7-9e02-753b89ffd703.png)

Unfortunately, CompletionItem.documentation (and details) only support plain text.
On our side, the request to support rich text is https://github.com/Microsoft/vscode/issues/11877

**Comment by fbricon** [comment]
This is what I get when converting Html Javadoc to Eclipse Html JavaDoc to plain text.

<img width="788" alt="screen shot 2017-05-24 at 12 32 50 pm" src="https://cloud.githubusercontent.com/assets/148698/26414434/2c7d0528-407d-11e7-8762-d5cf0341fdd6.png">

Cheap to implement and while it's not absolutely perfect, it might be sufficient.

@gorkem @aeschli WDYT?

**Comment by fbricon** [comment]
basically, rendering nested lists from html to plaintext using that method sucks

**Comment by fbricon** [comment]
removing for current sprint as we're [waiting for CQ approval](https://github.com/eclipse/eclipse.jdt.ls/pull/238#discussion_r118979830) for forking a Jsoup class, on the server side.

**Comment by fbricon** [comment]
With new plain text renderer:
<img width="737" alt="screen shot 2017-07-12 at 4 06 36 pm" src="https://user-images.githubusercontent.com/148698/28137707-2b840bb0-671c-11e7-9c0d-4d88cc4985d5.png">
