### ISSUE TITLE
Allow for excluding files from the problem tab

### ISSUE THREAD

**Issue by FieteO** [redhat-developer/vscode-java#2150]
I have a java project that has a rather large proportion of files that are generated by [openapi-generator](https://github.com/OpenAPITools/openapi-generator). The generated code contains a lot of problems that I will not resolve (i.e `The import XY is never used`). This is cluttering the problems view.

![Cluttered problems view](https://user-images.githubusercontent.com/41323592/136029685-cc005904-5285-455e-88ad-d383e4090be3.png)

I know that this view can be filtered and that there is the `files.exclude` option. I also found feature requests ([#22289](https://github.com/Microsoft/vscode/issues/22289), [#43135](https://github.com/Microsoft/vscode/issues/43135)) for vscode to include a `files.problemExclude` option.

However [this comment](https://github.com/Microsoft/vscode/issues/22289#issuecomment-389926531) made me wonder if this could/should be rather implemented by this extension to ignore particular folders in the problem analysis.

**Comment by snjeza** [comment]
@FieteO you can try to add the following property

```
org.eclipse.jdt.core.compiler.problem.unusedImport=ignore
```
to <your_projects>/.settings/org.eclipse.jdt.core.prefs

See [Settings Global Preferences](https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences)

**Comment by rgrunber** [comment]
Could using `@SuppressWarnings("all")` on the type declaration work in your case ?

Supporting something like this properly might be possible, though maybe not as high priority given there's some ways of achieving roughly the same thing. I see that on the Eclipse side, the problem view filter settings are stored in the workspace in a file like `org.eclipse.ui.ide.prefs`. However, I assume much of the filtering is tied to the UI, so aside from some useful helper method, we'd probably end up writing this ourselves.

**Comment by FieteO** [comment]
Apologies if I am missing your point and at the risk of repeating myself: In our setup the source files (i.e the restcontrollers) are completely transient, they are not versioned and rebuild with each `gradle build`. So in my eyes it is not possible to annotate them (maybe except for an openapi generator option I am not aware of), do you get what I mean?

**Comment by rubensa** [comment]
I tried setting:
```json
"settings": {
  "java.import.generatesMetadataFilesAtProjectRoot": true,
```

Then opening the generated **.classpath** and adding the **ignore_optional_problems** attribute like:
```xml
	<classpathentry kind="src" output="target/classes" path="target/generated-sources/openapi/src/gen/java">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="ignore_optional_problems" value="true"/>
		</attributes>
	</classpathentry>
```

**Clean Language Server Workspace** and the problems are gone.

It would be great to be able to enable this for any "**target/generated-sources**" folder without the need to set **java.import.generatesMetadataFilesAtProjectRoot** and manually editing **.classpath**.

**Comment by rubensa** [comment]
**NOTE**:  It's curious that for **test-annotations** the **ignore_optional_problems** attribute is automatically set:
```xml
	<classpathentry kind="src" output="target/test-classes" path="target/generated-test-sources/test-annotations">
		<attributes>
			<attribute name="optional" value="true"/>
			<attribute name="maven.pomderived" value="true"/>
			<attribute name="ignore_optional_problems" value="true"/>
			<attribute name="m2e-apt" value="true"/>
			<attribute name="test" value="true"/>
		</attributes>
	</classpathentry>
```

**Comment by rgrunber** [comment]
Interesting! I didn't know about [`ignore_optional_problems`](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/85f9f37c76220812f3e506ad800de0f31b11af88/org.eclipse.jdt.core/model/org/eclipse/jdt/core/IClasspathAttribute.java#L95-L106). Definitely works for me.

Only disadvantage is according to `IClassPathEntry`, it represents a package fragment root (eg. `src/main/java`) so I don't think we could get as granular as a set of files, or folders (eg. `src/main/java/org/example/only/this/subpackage/`)

**Comment by heyarny** [comment]
Any updates on this?
`files.exclude` is hiding the folder altogether and not really hiding all warnings from the problems-tab, which is not what we want.
A solution with individual .devcontainer settings would be great.

**Comment by rgrunber** [comment]
Just a question for those interested in this feature. What should happen when you open a file that is in the "file exclude" list for problems ? If you type something in that file, and it's a compilation error, do you still expect the incorrect tokens to be annotated as errors ? The problems view is linked to this workflow so you can't have the errors show up in the file and not the problems view (as far as I understand). Should the exclude filter for a file only be active when a file isn't open and having focus ?

Are there certain kinds of errors that you specifically want excluded, and others that you never want to exclude (eg. compilation errors) ?

**Comment by rubensa** [comment]
I'll say that this should work just as **annotations** and **test-annotations** that automatically set the `ignore_optional_problems` attribute for the `classpathentry` for the generated source files (so really no need to explicitly set files to ignore).

That said, if there is a way to explicitly set what files should be ignored for error check...  that should be obeyed...  no error should be reported for those files.

Again, that said, I'll suggest to provide both a way to ignore all errors for specified files and another way to ignore only optional problem for specified files (so it would work as the **annotations** and **test-annotations** but manually specifying the files instead of automatically recognizing that the files are auto-generated).

**Comment by rgrunber** [comment]
This should be resolved with `"java.diagnostic.filter": [ ... ]` which should take a list of patterns. Any matching file will be excluded from having diagnostics published.
