### ISSUE TITLE
(Unsupported operation. Please use build.gradle file) How to change the default source path in Gradle projects?

### ISSUE THREAD

**Issue by aderchox** [redhat-developer/vscode-java#2159]
In a project, the root detected for the packages is deeper than it should be, so I get a red line under the package declaration in code which says: 
> The declared package "com.example" does not match the expected package "app.src.main.java.com.example" Java(536871240)

This is the hierarchy of the files in the project:
```
/
    app/
        src/
            main/
                java/
```
and then sources are in subdirectories of the `java/` directory (this is a structure automatically generated by the `gradle init` for a console application project). But when I try to add the `java/` directory to the source path (by right clicking on the `java/` directory in the files explorer and choosing the "Add Folder to Java Source Path") I get this error:
> Unsupported operation. Please use build.gradle file to manage the source directories of gradle project.

So in another attempt to fix the problem, I then edit the build.gradle file and add this line to it:
```sourceSets.main.java.srcDirs += ['app/src/main/java']```
but it still doesn't work. It doesn't give any errors, but doesn't have any effects either. The package declaration is still red underlined.

##### Environment
- Operating System: Windows 10
- JDK version: 11
- Visual Studio Code version: 1.61.0
- Java extension version: 0.82.0

##### Steps To Reproduce
1. create a new project using the command `gradle init`
2. choose the project type "application" (a console application)
3. add a class to the project in your main package, the package is detected wrong.

##### Current Result
> The declared package "com.example" does not match the expected package "app.src.main.java.com.example" Java(536871240)

##### Expected Result
No errors
P.S. By the way, the command `gradle run` runs the project successfully, so it's not an issue of the project.

**Comment by fireguy123** [comment]
Related problem here. Using JDK 17.0.1 and Gradle 7.3.3
[client.log.2022-01-05.2.txt](https://github.com/redhat-developer/vscode-java/files/7813156/client.log.2022-01-05.2.txt)
[log.txt](https://github.com/redhat-developer/vscode-java/files/7813171/log.txt)

**Comment by jdneo** [comment]
Close as the problem is solved.
