### ISSUE TITLE
Code Completion for imported libraries.

### ISSUE THREAD

**Issue by QihanLiu** [redhat-developer/vscode-java#2168]
I am using the algorithm library algs4 in VS code.
It seems like the code auto completion only work for standard libraries.
For example, it won't pop up the public functions of a class.
Is there a way for me to add support for this kind of library?

##### Environment
- Operating System: MacOS

**Comment by rgrunber** [comment]
You're referring to https://github.com/kevin-wayne/algs4 ? If I wanted to quickly set something up to use this I would just take the jar from http://algs4.cs.princeton.edu/code/algs4.jar and set up the following structure :

```
algs4-myproject/
algs4-myproject/Main.java
algs4-myproject/lib
algs4-myproject/lib/algs4.jar
```
(by default `lib/**.jar` is configured for referenced project libraries)

**Comment by rgrunber** [comment]
Closing this as this seems to be working. If the above isn't working for you, feel free to add some more info and maybe we could investigate what's going wrong.

`java.project.referencedLibraries` may also help with more advanced configurations.
