### ISSUE TITLE
Code completion will remove characters in if block

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#2171]
[provide a description of the issue]

##### Environment
Version: 1.61.1 (user setup)
Commit: c13f1abb110fc756f9b3a6f16670df9cd9d4cf63
Date: 2021-10-14T01:19:42.089Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
JDK version: 11
Java extension version: 0.83.0

##### Steps To Reproduce

https://user-images.githubusercontent.com/6193897/137853785-a61a1103-c25f-4afd-b40f-6e5c0722b444.mp4

##### Expected Result
the word `System` won't be deleted

**Comment by jdneo** [comment]
Turns out that there is a setting `java.completion.overwrite` to control the behavior. When it's set to false, `System` won't be replaced. 

In the meantime, Eclipse has the same behavior. But in Eclipse, users can easily toggle the behavior via `Ctrl` keystroke, which I guess is impossible in VS Code.

I was trying to imagine any cases that the overwriting is better than inserting, but not able to remind a valid case. I also checked the behavior in IntelliJ and it looks like IntelliJ always inserts items. The TS language server in VS Code also use insert.

**Comment by KyleRAnderson** [comment]
I think it would be great if this setting were synchronized with the existing `editor.suggest.insertMode` setting. If users want to set a specific value for this setting for Java, that's already possible in VSCode, so not too sure why another setting is needed here.

**Comment by jdneo** [comment]
> If users want to set a specific value for this setting for Java, that's already possible in VSCode, so not too sure why another setting is needed here.

@fbricon @rgrunber Is this for the consideration of supporting in other clients?

**Comment by rgrunber** [comment]
https://github.com/redhat-developer/vscode-java/issues/1047 ;) and https://github.com/redhat-developer/vscode-java/issues/1058 also.

Looks like we should consider changing the default if people are pointing it out as a bug often enough. If there's no historical reason for us to have a separate option then I would move to using the IDE specific one. Users can still customize with things like [`[java]`](https://code.visualstudio.com/docs/getstarted/settings#_languagespecific-editor-settings).

**Comment by rgrunber** [comment]
Closing this as the issue has been addressed. `java.completion.overwrite` has been removed and we now use `editor.suggest.insertMode`. We also leave it up to the client to toggle between insert/replace edits.
