### ISSUE TITLE
Could not fetch model of type 'GradleProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-7.2-bin.zip'

### ISSUE THREAD

**Issue by orange2222222222** [redhat-developer/vscode-java#2177]
When I tried to open build.gradle, normally it will just build it for me, but it returned with this error:
`Could not fetch model of type 'GradleProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-7.2-bin.zip'`

##### Environment
- Operating System: Windows 10
- JDK version: 16.0.2
- Visual Studio Code version: 1.61.2
- Java extension version: 1.1.0

##### Steps To Reproduce
1. opening build.gradle

##### Current Result
```
CONFIGURE FAILED in 14s
[error] [gradle-server] Could not fetch model of type 'GradleProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-7.2-bin.zip'.
[error] Error getting build for c:\Users\meee\OneDrive\Desktop\fabric-example-mod: Could not fetch model of type 'GradleProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-7.2-bin.zip'.
[info] Found 0 tasks
```
(this is part of the question I posted on StackOverflow: https://stackoverflow.com/questions/69591576/vscode-could-not-fetch-model-of-type-gradleproject-using-gradle-distribution)

##### Expected Result
build the project

**Comment by orange2222222222** [comment]
the output channel is from Gradle task extension, and the project I'm trying to build is: https://github.com/FabricMC/fabric-example-mod

**Comment by 0dinD** [comment]
> This error can be caused by an invalid gradle distribution in ~/.cache/tooling or ~/.gradle/wrapper/dists

@orange2222222222 Note: these are UNIX-style paths, the equivalent on Windows would be `C:\Users\<your username>\.cache\tooling\` and `C:\Users\<your username>\.gradle\wrapper\dists\`

**Comment by orange2222222222** [comment]
Running the gradle wrapper and gradle returned with the same error:
```
> Configure project :
Fabric Loom: 0.9.54
:remapping 47 mods (TinyRemapper, intermediary -> named)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'fabric-example-mod'.
> Failed to remap mods

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Also, which part of the log file do I upload? There are about 4000 lines and some seem to be repeating, This is the bottom of one of the stacktrace since that's normally where they put cause of the error:
```
Caused by: java.io.IOException: Could not create output consumer for C:\Users\meee\OneDrive\Desktop\fabric-example-mod\.gradle\loom-cache\remapped_mods\net_fabricmc_yarn_1_17_1_1_17_1_build_61_v2\net\fabricmc\fabric-api\fabric-transfer-api-v1\1.4.0+7931163218\fabric-transfer-api-v1-1.4.0+7931163218.jar
	at net.fabricmc.loom.configuration.mods.ModProcessor.remapJars(ModProcessor.java:183)
	at net.fabricmc.loom.configuration.mods.ModProcessor.processMods(ModProcessor.java:85)
	at net.fabricmc.loom.build.ModCompileRemapper.lambda$remapDependencies$5(ModCompileRemapper.java:143)
	... 182 more
```

**Comment by snjeza** [comment]
@orange2222222222 Could you try to remove 
```
C:\Users\meee\.gradle
C:\Users\meee\OneDrive\Desktop\fabric-example-mod\.gradle
```
and restart the build.

**Comment by orange2222222222** [comment]
Hi, it still returns with the same error :/

**Comment by snjeza** [comment]
Could you show your gradle.properties ( C:\Users\meee\OneDrive\Desktop\fabric-example-mod\gradle.properties)
and the output of the following command:
```
dir C:\Users\meee\.gradle\caches\fabric-loom
```
