### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by gorryyong** [redhat-developer/vscode-java#2180]
- Issue Type: `Bug`
- Extension Name: `java`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.22483`
- VS Code version: `1.62.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rgrunber** [comment]
Could you describe what issue you're seeing ? What were you doing when it occured ?
