### ISSUE TITLE
"The import java.util.Pair cannot be resolved"

### ISSUE THREAD

**Issue by J-Rohault-dF** [redhat-developer/vscode-java#2182]
Very simple problem. One of the files contains:
`import java.util.ArrayList;`
`import java.util.Pair;`
VSCode blocks on the second line, redlining it and telling me "The import java.util.Pair cannot be resolved".

I tried everything I could find.
- Delete the workspaceStorage directory contents: tried, nothing changed
- Run the command "Java: Clean Java language Server Workspace": tried, nothing changed
- Doing something with maven projects: no idea what Maven is, I can't even find it in the explorer window
- Set rootProject.name in some gradle extension: I don't have that extension installed and I can't find that setting in existing extensions
- Open every single file and save it: tried, nothing changed
- Comment out everything in main and run it: can't even run it when doing it

The only thing I haven't tried was copy-pasting everything into a new clean project because I'm working with someone else via github so I'm not sure it would be possible to do it.
So anyway, I don't really want to be that guy who's wasting his time solving weird bugs from the IDEs while the other does most of the actual coding (already had problems with getting vscode to recognize JDK then getting IntelliJ to recognize the files correctly)

##### Environment
- Operating System: Windows 10
- JDK version: 17 (I guess? It's the latest version (downloaded it yesterday) and the file ends in _17_35.msi)
- Visual Studio Code version: 1.61.2
- Java extension version: v1.0.0 (I guess, since it's indicated on the extension page?)

##### Steps To Reproduce
1. Open VSCode on my computer
2. Find the file with 8 problems (all linked to that import) and look at line 4 (`import java.util.Pair;`)

##### Current Result

The `import java.util.Pair;` has a red underline

##### Expected Result

That line not being red-underlined and importing that util correctly

**Comment by gaurav6386** [comment]
@J-Rohault-dF Pair class is part of javafx.util package of javafx(not java) library. Replacing java with javafx in your import statement will resolve that error.
In case you didn't have javafx library set up on your system you can get started with it from [here](https://openjfx.io/openjfx-docs/#introduction)

**Comment by rgrunber** [comment]
Thanks for confirming. I'm closing this for now since there's clearly some ways to get some kind of Pair object.
