### ISSUE TITLE
"Access restriction" java warning not solveable

### ISSUE THREAD

**Issue by handmade-it** [redhat-developer/vscode-java#219]
Hi,

I am freshly using your extension with vs code for a new java project. The project itself had been generated via maven command line tool. The extension itself works, but i cannot get rid of this (and similar) warnings: 

[Java] Access restriction: The type 'Endpoint' is not API (restriction on required library '/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar')

I tried to set java.home to a custom jdk but it either didn't worked or the java.home setting maybe got ignored. At least the warnings persits and point always to the same jdk. It never used the path of my custom jdk.

Any help would be great
Thanks in advance

##### Environment
- Operating System: Linux / Ubuntu 16.04
- JDK version: OpenJDK 1.8
- Visual Studio Code version: 1.12.2
- Java extension version:

##### Steps To Reproduce
1. Create barebone maven java project
2. Open project in vs code with your extension enabled
3. Import any usual class like javax.jws.WebMethod

**Comment by fbricon** [comment]
mmm I can't reproduce the warning on Mac. @snjeza can you check on linux?

As for the changing java.home, I've noticed some weird behavior too, on Mac. It seems jdt.ls initializes a JVM environment which not necessarily matches the JDK version used to run the server, but uses some Java version automatically found by Eclipse on the platform. I think we can consider that a bug in itself (Java environment should match passed java.home value)

**Comment by handmade-it** [comment]
Hi, thanks for the reply. I agree with your consideration. 
BTW: The error even occured at a time when i definitly had just on jdk installed at all. The java.home problem was a followup after it started trying to use a different jdk

I will test i with a blank java project (without any maven, just to sort out that this might be the problem)

**Comment by handmade-it** [comment]
Hi, one more feedback. I cloned my project and removed everything relevant to maven (pom.xml, .settings-folder, .classpath and .project file) and the strange warning went away. Can it be, that the maven files somehow interfere with your extensions settings?

The maven project I use had been created with this command:

mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false

As I also started using maven there might be an mistake on my side too

**Comment by fbricon** [comment]
I don't know what caused the warning. We need to be able to reproduce the issue. See if you see anything relevant in the [server log](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs).

**Comment by handmade-it** [comment]
Oh man... i'm going to hit myself. I found the problem.

The maven command above created a .settings folder with a file org.eclipse.jdt.core.prefs

This file contains a setting named: org.eclipse.jdt.core.compiler.problem.forbiddenReference that was set to "warning" and caused... well, the warning. So your language server somehow fetched this setting and used it. Maybe this should get documented alongside with the other options that are available for settings.json

best regards

**Comment by fbricon** [comment]
I see now :-) 

The `.settings\org.eclipse.jdt.core.prefs` file is actually created by vscode-java. `org.eclipse.jdt.core.compiler.problem.forbiddenReference` is actually a very important setting to keep.

Basically, your issue is the Maven project uses the default maven-compiler settings where  [`the default source setting is 1.5 and the default target setting is 1.5, independently of the JDK you run Maven with`](https://maven.apache.org/plugins/maven-compiler-plugin/index.html). But your JDK 8 leaks new APIs. That means if your app was really supposed to run on Java 1.5, it'd fail because it was compiled with references to Endpoint and WebMethod from 1.8, but those don't exist in 1.5. 

You should modify your pom.xm to [target Java 1.8](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html) and then make sure you [update the project configuration](https://github.com/redhat-developer/vscode-java/issues/113#issuecomment-266824408).

**Comment by handmade-it** [comment]
Great! Thanks for the quick support!!

**Comment by engtuncay** [comment]
I set org.eclipse.jdt.core.compiler.problem.forbiddenReference = ignore  which is in org.eclipse.jdt.core.prefs file

it fixed.

**Comment by Zied-Guesmi** [comment]
Hey,

**Comment by Zied-Guesmi** [comment]
Hey,

I'm having the same issue here with a spring project even after adding `org.eclipse.jdt.core.compiler.problem.forbiddenReference = ignore`

**Code insider version**: 1.32.0-insider (1.32.0-insider)  11416de365a1e96302e171c9eebc2547872ac230
**Marketplace Version**: 0.39.0

**org.eclipse.buildship.core.prefs** content:
```
connection.project.dir=
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.problem.forbiddenReference=ignore
```

**To reproduce**:

- Use vscode's spring intializr to create a spring project.
- In the Application class import this:
`import static java.lang.management.ManagementFactory.getOperatingSystemMXBean;`
- Copy/pase:
```
public int getMemorySize() {
	com.sun.management.OperatingSystemMXBean os = (com.sun.management.OperatingSystemMXBean) getOperatingSystemMXBean();
	return new Long(os.getTotalPhysicalMemorySize()).intValue();
}
```

This should result in the error message:
`Access restriction: The type 'OperatingSystemMXBean' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/lib/rt.jar')`

**PS**: This problem disappears when creating a java project and adding the line `org.eclipse.jdt.core.compiler.problem.forbiddenReference=ignore` to `org.eclipse.buildship.core.prefs` file

**Comment by fbricon** [comment]
@Zied-Guesmi you need to put the pref in .settings\org.eclipse.jdt.core.prefs, not .settings\org.eclipse.buildship.core.prefs

**Comment by Zied-Guesmi** [comment]
@fbricon thank you and sorry for not paying attention to that detail.
I noticed that in a java project the file created by default is **.settings\org.eclipse.jdt.core.prefs** but in a spring project **.settings\org.eclipse.buildship.core.prefs** is created instead. shouldn't it be the same for both cases? Shouldn't the correct file be generated by default?

**Comment by ai-chen2050** [comment]
some info as follow:

!ENTRY org.eclipse.jdt.ls.core 4 0 2022-06-24 00:40:59.039
!MESSAGE Error occured while building workspace. Details: 
 message: Access restriction: The method 'OperatingSystemMXBean.getProcessCpuLoad()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 70
 message: Access restriction: The method 'OperatingSystemMXBean.getSystemCpuLoad()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 78
 message: Access restriction: The method 'OperatingSystemMXBean.getTotalPhysicalMemorySize()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 94
 message: Access restriction: The method 'OperatingSystemMXBean.getFreePhysicalMemorySize()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 102
 message: Access restriction: The method 'OperatingSystemMXBean.getTotalSwapSpaceSize()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 109
 message: Access restriction: The method 'OperatingSystemMXBean.getFreeSwapSpaceSize()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 116
 message: Access restriction: The type 'OperatingSystemMXBean' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 5
 message: Access restriction: The type 'OperatingSystemMXBean' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 44
 message: Access restriction: The type 'OperatingSystemMXBean' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 47
 message: Access restriction: The type 'OperatingSystemMXBean' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/common/src/main/java/org/tron/common/prometheus/OperatingSystemExports.java; line: 51
 message: Access restriction: The type 'OperatingSystemMXBean' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/framework/src/main/java/org/tron/core/services/NodeInfoService.java; line: 3
 message: Access restriction: The type 'OperatingSystemMXBean' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/framework/src/main/java/org/tron/core/services/NodeInfoService.java; line: 41
 message: Access restriction: The type 'OperatingSystemMXBean' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/framework/src/main/java/org/tron/core/services/NodeInfoService.java; line: 41
 message: Access restriction: The method 'OperatingSystemMXBean.getTotalPhysicalMemorySize()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/framework/src/main/java/org/tron/core/services/NodeInfoService.java; line: 75
 message: Access restriction: The method 'OperatingSystemMXBean.getFreePhysicalMemorySize()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/framework/src/main/java/org/tron/core/services/NodeInfoService.java; line: 76
 message: Access restriction: The method 'OperatingSystemMXBean.getSystemCpuLoad()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/framework/src/main/java/org/tron/core/services/NodeInfoService.java; line: 77
 message: Access restriction: The method 'OperatingSystemMXBean.getProcessCpuLoad()' is not API (restriction on required library '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/rt.jar'); code: 16777523; resource: /Users/blake.chen/work/code/opensource/java-tron/framework/src/main/java/org/tron/core/services/NodeInfoService.java; line: 84

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-06-24 00:41:01.712
!MESSAGE >> workspace/executeCommand vscode.java.resolveBuildFiles
