### ISSUE TITLE
Format on save

### ISSUE THREAD

**Issue by squishybanana04** [redhat-developer/vscode-java#220]
I've been playing around with the "Format Document" command and I was wondering if it would be possible to configure it to format the document whenever I save.

**Comment by snjeza** [comment]
You can try https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave

**Comment by fbricon** [comment]
Actually there's no need for a 3rd party extension.

Just add `"editor.formatOnSave": true` to VS Code preferences

**Comment by charlesferreira** [comment]
> Actually there's no need for a 3rd party extension.
> 
> Just add `"editor.formatOnSave": true` to VS Code preferences

Too bad it doesn't work for Java code.

**Comment by kipodd** [comment]
You need to select it as the default formatter for java files.

1. Press `CTRL + SHIFT + P`
2. Type and select `Format Document With...`
3. Select `Configure Default Formatter...`
4. Choose `Language Support for Java(TM) by Red Hat`

To test it, press `CTRL + SHIFT + P` again and select `Format Document`.

If it works you can also add `"editor.formatOnSave": true` in VSCode's settings.json to format automatically when saving.

**Comment by sbreakey** [comment]
Does anyone know what the rules it uses to format are? We (may) use checkstyle in future, and I assume the formatting rules could clash?
