### ISSUE TITLE
The package name is not automatically imported when create `H.java`

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2200]
When I create a new class `H.java`, under the package com. com is not automatically written

##### Environment
- Operating System:window 10 21H1
- JDK version:17
- Visual Studio Code version:1.63 insiders
- Java extension version:1.0.0

##### Steps To Reproduce
1. git clone https://gitee.com/mozhuanzuojing/java-bug01.git
2. open it and wait buiding
3. create `B\src\public\com\H.java`

[client.log.2021-11-06.log](https://github.com/redhat-developer/vscode-java/files/7489750/client.log.2021-11-06.log)
[jdt_ws.log](https://github.com/redhat-developer/vscode-java/files/7489753/jdt_ws.log)

#### Video ####

https://user-images.githubusercontent.com/63572041/140608486-cc1e9f3e-84c9-4387-a742-03f420ad6c80.mp4

##### Current Result

The newly created class has no package name and needs to be repaired manually

##### Expected Result

New class is automatically brought into the package name

##### Additional Informations
This problem has a related problem. When `Go to References` is executed on a method in H.java, it will also find all method references with the same name. Because there is no package name filtering.

**Comment by mozhuanzuojing** [comment]
https://user-images.githubusercontent.com/63572041/140598081-7306e6cf-4b8f-479a-aee9-f6a0fb29186a.MP4

**Comment by mozhuanzuojing** [comment]
@snjeza could you help me?

**Comment by snjeza** [comment]
@mozhuanzuojing src/public is not a source directory. You can try the following patch:

```
diff --git a/B/build.gradle b/B/build.gradle
index d66fb8c..625b517 100644
--- a/B/build.gradle
+++ b/B/build.gradle
@@ -8,7 +8,7 @@
 sourceSets{
     main{
         java{
-            srcDirs = ["src/private"]
+            srcDirs = ["src/private", "src/public"]
         }
     }
 }
```

**Comment by mozhuanzuojing** [comment]
> @mozhuanzuojing src/public is not a source directory. You can try the following patch:
> 
> ```
> diff --git a/B/build.gradle b/B/build.gradle
> index d66fb8c..625b517 100644
> --- a/B/build.gradle
> +++ b/B/build.gradle
> @@ -8,7 +8,7 @@
>  sourceSets{
>      main{
>          java{
> -            srcDirs = ["src/private"]
> +            srcDirs = ["src/private", "src/public"]
>          }
>      }
>  }
> ```

@snjeza I defined the source code location in module `S`
I must define the public source directory of all modules in `S`, centrally compile and avoid circular dependencies.

> S\build.gradle
```gradle
sourceSets{
    a {
        java{
            srcDirs = [
                "../A/src/public"
            ]
        }
    }

    b {
        java{
            srcDirs = [
                "../B/src/public"
            ]
        }
    }
}
````

**Comment by snjeza** [comment]
buildship doesn't add src/public to .classpath. You can try the following patch:

```
diff --git a/B/build.gradle b/B/build.gradle
index d66fb8c..53d7b50 100644
--- a/B/build.gradle
+++ b/B/build.gradle
@@ -15,4 +15,15 @@ sourceSets{
 
 dependencies {
     implementation project(":S")
-}
\ No newline at end of file
+}
+
+eclipse {
+    classpath {
+        containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
+        file.whenMerged { cp ->
+            def entries = cp.entries;
+            def src = new org.gradle.plugins.ide.eclipse.model.SourceFolder('src/public', null)
+            entries.add(src)
+        }
+    }
+}
```

**Comment by mozhuanzuojing** [comment]
@snjeza it work！amazing！
## Thank you very much for your generous help. This helped me solve a particularly big problem.

**Comment by mozhuanzuojing** [comment]
@snjeza But the `public` source code is compiled twice, module `S` is compiled once, and module `B` is compiled once.
Is there no better solution? If so, I will accept it
