### ISSUE TITLE
When there are blocks of text in the code, the indentation automatically becomes 8 Spaces.

### ISSUE THREAD

**Issue by alfadb** [redhat-developer/vscode-java#2206]
[provide a description of the issue]

##### Environment
- Operating System: Windows 11
- JDK version: 17
- Visual Studio Code version: 1.62.1
- Java extension version: 1.0.0

##### Steps To Reproduce
1. Set the editor default indentation to 4 space.
2. Open a java code file which have text block code.

Open the java code file which have not text block:
![image](https://user-images.githubusercontent.com/3182249/141047137-880944c5-f7f0-43ed-a9d5-1f88bb949c58.png)

Open the java code file which have text block:
![image](https://user-images.githubusercontent.com/3182249/141047211-dbd0e2aa-a9e0-4cf6-8881-8aa86634bfbe.png)
![image](https://user-images.githubusercontent.com/3182249/141047157-a2e4c9f9-46f8-4a8f-8ed8-3861f5f56832.png)

**Comment by fbricon** [comment]
Indentation detection is a feature from VS Code proper. Have you try setting the following?:

```json
    "[java]": {
       "editor.detectIndentation": false
    },
```

**Comment by alfadb** [comment]
> Indentation detection is a feature from VS Code proper. Have you try setting the following?:
> 
> ```json
>     "[java]": {
>        "editor.detectIndentation": false
>     },
> ```

Ok, it works, thanks.
