### ISSUE TITLE
relaod vscode or update pom.xml,  all compiled class file will delete, need to be recompile again

### ISSUE THREAD

**Issue by hhkrob1** [redhat-developer/vscode-java#2208]
[provide a description of the issue]

##### Environment
- Operating System: windows 11
- JDK version: jdk1.8 and jdk 11
- Visual Studio Code version: 1.62.1
- Java extension version: 1.0.0

##### Steps To Reproduce
1. [step 1]  
Use maven, Project directory structure
1): src is in ./src/main/java/com/example/App.java
2): out is in ./target/classes/com/example/App.class
2. [step 2]
1): vscode setting keep default, 
only disable auto build for maven compile:
when relaod vscode or update pom.xml,  all class(App.class) will delete, must be recompile
1): vscode setting keep default, 
only enable auto build for test the issue:
when relaod vscode or update pom.xml,  all class will delete,  because enableauto bulid, so compile will action again, I check class file create timetamp is change, so it must be recompile.

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
when relaod vscode or update pom.xml,  all class will delete, must recompile
I check log, will find clean workspace startup everytime, Is that the reason
##### Expected Result
why recompile everytime,  source file is not change!, if I have lot of large project, everytime recompile is not good, what do you think?
##### Additional Informations
Is there a solution, thanks, l like code not ideal, is so cool! thanks!

**Comment by hhkrob1** [comment]
![java_reload](https://user-images.githubusercontent.com/68175970/141111677-a13a6857-ec73-4f4b-b4d1-72850d562d80.gif)
Reproduce reload vscode gif, thanks.

**Comment by hhkrob1** [comment]
I just found the version 0.8.2 is work well. So I from 1.0.0 fallback to 0.8.2 now. But I'd like you to confirm it. Thanks!

**Comment by jdneo** [comment]
I can reproduce this bug on my side when the autobuild is turned off.

**Comment by snjeza** [comment]
@hhkrob1  @jdneo Could you, please, test https://github.com/snjeza/vscode-test/raw/master/java-1.1.0.vsix

**Comment by jdneo** [comment]
@snjeza Apologize for the late reply. The private bit works on my machine.

**Comment by hhkrob1** [comment]
> @hhkrob1 @jdneo Could you, please, test https://github.com/snjeza/vscode-test/raw/master/java-1.1.0.vsix ?

Thank you so much, now 1.1.0 is work!

**Comment by EricBuist** [comment]
Seems I have a variant of this problem. Each time I change the pom.xml file, VS Code cleans target directory but doesn't automatically recompile properly. I have to run "Clean Java Language Server" every time I change POM file now. This works for small projects, but for large projects, it can take minutes to rebuild everything.
