### ISSUE TITLE
Unable to set classpathVariable

### ISSUE THREAD

**Issue by fabianMendez** [redhat-developer/vscode-java#2210]
I have an eclipse project that references some libraries using a classpath variable in the `.classpath` file, like this:
```xml
<classpathentry kind="var" path="TOMCAT_HOME/lib/jsp-api.jar"/>
```

I found that this classpath variable is configured in the `.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.core.prefs` file inside the eclipse workspace, like this:
```prefs
org.eclipse.jdt.core.classpathVariable.TOMCAT_HOME=/opt/apache-tomcat-7.0.99
```

So I tried putting this preference in the `.settings/org.eclipse.jdt.core.prefs` file inside the project, restarted VS Code but the libraries still were not found.

I also configured the `java.settings.url` VS Code's setting to a file containing the above mentioned preference and it also did not work.

##### Environment
- Operating System: Linux x64 5.11.0-38-generic
- JDK version: Openjdk version "11.0.11" 2021-04-20
- Visual Studio Code version: 1.62.0
- Java extension version: v1.0.0

##### Steps To Reproduce
1. Clone the sample project: https://github.com/fabianMendez/vscode-java-classpath-variable-issue
2. Download and extract tomcat from https://tomcat.apache.org/download-80.cgi
3. Update the `org.eclipse.jdt.core.classpathVariable.TOMCAT_HOME` preference in the `.settings/org.eclipse.jdt.core.prefs` file with the path to tomcat

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

The App class (src/main/java/App.java) fails to compile with an error: `The import javax.servlet cannot be resolved`

##### Expected Result

The App class should compile

**Comment by snjeza** [comment]
org.eclipse.jdt.core.classpathVariable.* is an instance (workspace) preference. It can't be set at the project level.
Java LS doesn't support setting a classpath variable.
You can try to set it in
~/.config/Code/User/workspaceStorage/<YOUR_WORKSPACE>/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.core.prefs

**Comment by fabianMendez** [comment]
> org.eclipse.jdt.core.classpathVariable.* is an instance (workspace) preference. It can't be set at the project level.
> Java LS doesn't support setting a classpath variable.
> You can try to set it in
> ~/.config/Code/User/workspaceStorage/<YOUR_WORKSPACE>/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.core.prefs

Indeed it worked. Thanks

I used the `Java: Open Java Language Server log file` command to identify the workspace but is there a better way to do it?

**Comment by snjeza** [comment]
@fabianMendez You can use

```
ps -ef |grep id1
```

**Comment by fabianMendez** [comment]
Thanks
