### ISSUE TITLE
Same Error!

### ISSUE THREAD

**Issue by CodingBeast77** [redhat-developer/vscode-java#2217]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by rgrunber** [comment]
Can you describe what the issue is ? Is there an existing issue that already describes your issue ?

**Comment by rgrunber** [comment]
Closing as more info is needed to diagnose this. Feel free to provide some more info, and then we can definitely have a look.
