### ISSUE TITLE
Java: Option to lint only opened/active file

### ISSUE THREAD

**Issue by PROxZIMA** [redhat-developer/vscode-java#2221]
[provide a description of the issue]

##### Environment
- VS Code Version: 1.62.2
- Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
- Date: 2021-11-11T20:51:30.084Z
- Electron: 13.5.2
- Chrome: 91.0.4472.164
- Node.js: 14.16.0
- V8: 9.1.269.39-electron.0
- OS: Linux x64 5.13.0-7620-generic
- JDK version:
  - openjdk 11.0.11 2021-04-20
  - OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
  - OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)
- Java extension version: 1.0.0

##### Steps To Reproduce
1. Open any java project
2. The entire project is linted which is not necessary if the project is too big

Java extension lints the entire project rather than the active file, which uses lots of memory and fills up the file explorer with red flags.

I was trying to analyze an `APK` file but when I open VSCode, it lints all the files rather than the file opened in editor. I'm using [`Language Support for Java(TM) by Red Hat`](https://marketplace.visualstudio.com/items?itemName=redhat.java) extension. Does VSCode provide any option to lint only active files?

##### Current Result

![Screenshot from 2021-11-19 15-28-27](https://user-images.githubusercontent.com/43103163/142605159-4d845d10-a38d-4603-95a8-1ba9a91fa58e.png)

##### Expected Result

Option to lint only opened/active file

**Comment by fbricon** [comment]
The Java Language server treats the project as a whole, so doesn't build (then lint) only just opened files, however you have a couple options to mitigate that behavior:

- In the problems filter, select : show active file only. This is just a cosmetic workaround as all files are still processed behind the scenes
- Set `java.server.launchMode` to `lightweight` in your settings.json. LightWeight mode starts a syntax server with lower start-up cost. Only provides syntax features such as outline, navigation, javadoc, syntax errors. The lightweight mode won't load thirdparty extensions, such as java test runner, java debugger, etc.
