### ISSUE TITLE
”Go to References" result contain wrong referrences

### ISSUE THREAD

**Issue by whinc** [redhat-developer/vscode-java#2227]
[provide a description of the issue]

##### Environment
- Operating System: macos 10.14.6
- JDK version: openjdk 11.0.11 
- Visual Studio Code version: 1.62.3
- Java extension version: v1.0.0

##### Steps To Reproduce
1. define custom `User` class
2. click context menu "Go to referrences" on `User` class 

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

![image](https://user-images.githubusercontent.com/5096493/143439055-edb46316-29d9-469e-bbe9-e6decacaf91d.png)

**Comment by fbricon** [comment]
Can you please provide a sample project reproducing this issue?

**Comment by whinc** [comment]
@fbricon it'a a demo below generated by [spring initializr](https://start.spring.io/)

[demo.zip](https://github.com/redhat-developer/vscode-java/files/7612015/demo.zip)


![image](https://user-images.githubusercontent.com/5096493/143688441-f4ab25a3-1460-43e1-8393-2b847b67ad67.png)

**Comment by rgrunber** [comment]
@snjeza Wouldn't we also have to adjust things like CodeLensHandler (which uses its own SearchEngine for references and implementations) ?

**Comment by snjeza** [comment]
> Wouldn't we also have to adjust things like CodeLensHandler (which uses its own SearchEngine for references) ?

@rgrunber I have done it. See https://github.com/eclipse/eclipse.jdt.ls/pull/1984/commits/1aa927b1234e656163e14f6a52839ea3303549f8
