### ISSUE TITLE
When 'org.eclipse.jdt.core.prefs' exist both in project root and workspace storage, the project root one is not working

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#2228]
##### Environment
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
JDK: 1.8
Java extension version - v1.1.0

##### Steps To Reproduce
1. Make sure the settings `java.import.generatesMetadataFilesAtProjectRoot` is set to false
2. Open a project that does not contain metadata files at project root.
3. Manually add a `.settings/org.eclipse.jdt.core.prefs` file at the project root.
![image](https://user-images.githubusercontent.com/6193897/143557791-c24ffb37-6a8f-4d03-a595-bb982a28c250.png)

4. Change the preferences in the `.settings/org.eclipse.jdt.core.prefs`, it will not take effect unless reload window.

**Workaround**: use the setting `java.settings.url` to point to `.settings/org.eclipse.jdt.core.prefs`, then everything works.

**Comment by snjeza** [comment]
This issue has been fixed within https://github.com/eclipse/eclipse.jdt.ls/pull/1964
@jdneo Could you try https://github.com/snjeza/vscode-test/raw/master/java-1.2.5.vsix?

**Comment by jdneo** [comment]
Thank you @snjeza, Tried the 1.2.5 vsix and it fixed the problem!

**Comment by jdneo** [comment]
Close as fixed in eclipse/eclipse.jdt.ls#1964
