### ISSUE TITLE
Support for org.junit.jupiter.api.DynamicTest

### ISSUE THREAD

**Issue by raulvaldoleiros** [redhat-developer/vscode-java#2229]
It would be nice if the java extension for vscode support org.junit.jupiter.api.DynamicTest and org.junit.jupiter.api.TestFactory.
Today the generated tests don't appear in the test view and isn't possible to see the generated test output.

##### Steps To Reproduce
Create a dynamictest with testfactory and run it
The generated test will not appear in the test view

**Comment by jdneo** [comment]
I tested it with Test Runner 0.33.0 and cannot reproducible.

![image](https://user-images.githubusercontent.com/6193897/144170636-6783d62d-9a7f-4cd9-8e6d-05459d3b0d05.png)
