### ISSUE TITLE
Standard mode does not work on standalong java files

### ISSUE THREAD

**Issue by randombck4r** [redhat-developer/vscode-java#2231]
##### Environment
- Operating System: Windows 10
- JDK version: 17.0.1
- Visual Studio Code version: 1.62.3
- Java extension version: 1.1.0

##### Steps To Reproduce
1. Open any .java file
2. Switch to standard mode

logs:
TypeError: Cannot read property 'fsPath' of undefined
	at C:\Users\Username\\.vscode\extensions\redhat.java-1.1.0\dist\extension.js:2:801280
	at Object.t.prepareExecutable (C:\Users\Username\\.vscode\extensions\redhat.java-1.1.0\dist\extension.js:2:801967)
	at t.StandardLanguageClient.<anonymous> (C:\Users\Username\\.vscode\extensions\redhat.java-1.1.0\dist\extension.js:2:859054)
	at Generator.next (<anonymous>)
	at s (C:\Users\Username\\.vscode\extensions\redhat.java-1.1.0\dist\extension.js:2:856724)

##### Current Result
Language server starts in lightweight mode automatically while it should start in standard mode.
Switching to standard mode manually gives an error message: "command 'java.runtimeValidation.open' already exists".
##### Additional Informations
If a folder is opened in vscode then the language server will start in standard mode and will work just fine.
Version 1.0.0 and older work as well.

**Comment by mozhuanzuojing** [comment]
@randombck4r could you share your settings.json

**Comment by randombck4r** [comment]
> 

Once I delete java.home and java.configuration.runtimes settings from older versions and let it restart, the error is gone.

**Comment by randombck4r** [comment]
> @randombck4r could you share your settings.json

`
{
  "editor.insertSpaces": false,
  "java.home": "D:\\Tools\\Java\\jdk-17.0.1",
  "java.configuration.runtimes": [
    {
      "name": "JavaSE-11",
      "path": "D:\\Tools\\Java\\jdk-11.0.11+9",
    },
    {
      "name": "JavaSE-17",
      "path": "D:\\Tools\\Java\\jdk-17.0.1",
      "default": true
    },
  ],
  "editor.cursorSmoothCaretAnimation": true,
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "files.exclude": {
    "**/.classpath": true,
    "**/.project": true,
    "**/.settings": true,
    "**/.factorypath": true
  },
  "workbench.colorTheme": "Default Light+",
  "workbench.colorCustomizations": {
    "activityBar.border": "#d7d7d7",
    "activityBar.background": "#f3f3f3",
    "activityBar.foreground": "#2c2c2c"
  },
  "security.workspace.trust.untrustedFiles": "open",
  "editor.semanticHighlighting.enabled": true
}
`

**Comment by chaitanyabiswas** [comment]
Yes, for me also it's not working. 
the older version is working fine.

**Comment by francisco-zr** [comment]
Same here, i can't compile a single file with this version, needed to rollback to 1.0

**Comment by mozhuanzuojing** [comment]
@randombck4r  cannot reproduce

![image](https://user-images.githubusercontent.com/63572041/143795433-7872bb96-63d3-41f2-a356-2d899779f17e.png)

**Comment by rgrunber** [comment]
I suspect this might be due to https://github.com/redhat-developer/vscode-java/pull/2085/files#diff-2d9ec606b265a83596a734df153c4ef01523700dc2576dcf1a80c9092c14d6d3R114 . We should be using `storagePath` as that is set to handle the case where no workspace is opened.

If I can confirm it, I can push a change soon.

**Comment by rgrunber** [comment]
We should have a release to include this by early December, but you can try out https://download.jboss.org/jbosstools/jdt.ls/staging/java-1.2.0-470.vsix until then, and also to confirm it resolves the issue.

**Comment by mrrobot97** [comment]
I face the same issue which cause the plugin 'Debugger for java' not working. Downgrade plugin version to v1.0.0 fix the problem.
