### ISSUE TITLE
Duplicate quick fixes when shown at line

### ISSUE THREAD

**Issue by 0dinD** [redhat-developer/vscode-java#2236]
When `java.quickfix.showAt` is set to `line` (the default), duplicate quick fixes are shown in certain scenarios.

##### Environment
- Java extension version: 1.1.0

##### Steps To Reproduce
1. Have the following code:

```java
package com.example;

public class Foo {

	List list = List.of();

}
```

2. Show quick fixes for adding the missing import for `List`.

##### Current Result
The actions in the quick fix menu are duplicated (if `java.quickfix.showAt` is set to `line`).

##### Expected Result
The actions in the quick fix menu are *not* duplicated even if `java.quickfix.showAt` is set to `line`.

##### Additional Information
The problem appears to be that quick fixes for both problem occurrences are shown at the same time when they occur at the same line. I cannot reproduce the issue when I put a newline after the `=` operator.

**Comment by rgrunber** [comment]
Are there any other cases where 2 different types of problems/diagnostics with the same resolution can appear on the same line ?

**Comment by snjeza** [comment]
> Are there any other cases where 2 different types of problems/diagnostics with the same resolution can appear on the same line ?

In my opinion there aren't any.

**Comment by 0dinD** [comment]
I haven't had time to investigate it that much, but what I've found is that it occurs for variable declarations (fields and local variables), but not for parameter declarations:

```java
package com.example;

public class Foo {

	List list = List.of(); // Duplicate quick fixes

	public void bar(List list1, List list2) { // No duplicates
		List list = List.of(); // Duplicate quick fixes
	}

}
```

**Comment by snjeza** [comment]
@0dinD @rgrunber You can test https://github.com/snjeza/vscode-test/raw/master/java-1.2.6.vsix
