### ISSUE TITLE
Is there any way to make autocomplete/intellisense more "accurate"?

### ISSUE THREAD

**Issue by ayloncarrijo** [redhat-developer/vscode-java#2237]
Hello, I'm having problems when I need to search some classes and I can only remember their partial names. I made some comparisons with Eclipse.

VSCode:
![ZombieVSCode](https://user-images.githubusercontent.com/77859081/143946876-98b27f51-28dd-4c3f-b063-0dd9a72af56d.png)

Eclipse:
![Zombie](https://user-images.githubusercontent.com/77859081/143946828-05cf5a01-d9c3-48a4-90a8-0e560f2d1534.png)

VSCode:
![PickupVSCode](https://user-images.githubusercontent.com/77859081/143946554-04dfd1d7-c5cc-4fc5-a083-6e9a9f604228.png)

Eclipse:
![Pickup](https://user-images.githubusercontent.com/77859081/143946754-8446f531-13fa-4303-98b9-ae2a91283d63.png)

VSCode (many unrelated classes):
![TNTVSCode](https://user-images.githubusercontent.com/77859081/143946906-1a6ff946-f672-4342-8918-8de3ed22af9e.png)

Eclipse:
![TNT](https://user-images.githubusercontent.com/77859081/143946921-0cd0cf62-931d-415c-9eb0-e7c0030c997b.png)

Is there any setting to change this behavior?

**Comment by snjeza** [comment]
@ayloncarrijo you can try to set the following property

```
org.eclipse.jdt.core.codeComplete.subwordMatch = enabled
```

See [Settings Global Preferences](https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences)

**Comment by ayloncarrijo** [comment]
@snjeza thanks, it worked perfectly!
