### ISSUE TITLE
Java extension not running

### ISSUE THREAD

**Issue by cbdoubles** [redhat-developer/vscode-java#2239]
Hello, I am trying to run a java program but it doesn't finish running. It is not a debugging issue (see screenshot below). Nothing appears in the terminal after I start running the program stating that there is an error with the code and I still have the option to terminate the running of the code. In addition, there is a blue process bar running across Java Projects which might have something to do with the issue.

I tried doing "clean the workspace directory" but this didn't work. I also tried uninstalling and reinstalling VS code.

I posted in another channel and the person thought it may be something to do with the extension.

I'm new to coding, let me know what other information you need to help. Looking forward to your support.

Thank you!

##### Environment
- Operating System: Windows 10
- JDK version: 11.0.11 (not sure this could be the extension version)
- Visual Studio Code version: 13.5.2
- Java extension version: (not sure)

##### Steps To Reproduce
1. Run simple program e.g. Helloworld.

Image:
![image](https://user-images.githubusercontent.com/95439834/144516764-a6ed1858-d267-4255-93e7-6cd991af0856.png))
Logs:
![image](https://user-images.githubusercontent.com/95439834/144516201-cb09e73e-33b0-4eb7-89fc-bd1d4ab510d5.png)
![image](https://user-images.githubusercontent.com/95439834/144516255-958143ae-a035-4258-ba5e-629d301fe3d2.png)

##### Current Result
Code not running

##### Expected Result
Code to run program

**Comment by testforstephen** [comment]
Duplicates with https://github.com/redhat-developer/vscode-java/issues/2231, there is a regression about single file support (no folder opened in VS Code).

The CI build https://download.jboss.org/jbosstools/jdt.ls/staging/java-1.2.0-470.vsix has fixed it, you can [install from vsix](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix).

Another workaround is to open a folder containing your Java files on VS Code.

**Comment by cbdoubles** [comment]
That worked. Thanks very much!
