### ISSUE TITLE
The LS status bar item is not sync with the real status

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#2243]
[provide a description of the issue]

##### Environment
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
JDK version: 11
Java extension version: 1.1.0

##### Steps To Reproduce
1. Clone the latest [spring-boot](https://github.com/spring-projects/spring-boot) project, or whatever an invalid gradle java project
2. Open it in VS Code
3. The project is failed to import but the status bar shows a thumb up

![image](https://user-images.githubusercontent.com/6193897/144789295-48009019-0259-4d7d-aa2c-dde7a1c80b09.png)

**Comment by rgrunber** [comment]
@jdneo , will this also fix https://github.com/eclipse/eclipse.jdt.ls/issues/1827#issuecomment-916576183 ? The issue there was, that if a Gradle project build failed, the result wasn't reported to the language server. client assumed the standard server was successful, and shut off the syntax server, eliminating the only remaining form of completion support.

**Comment by jdneo** [comment]
@rgrunber The current change won't. Because at the server side, the exceptions happen during initialize request will be caught: https://github.com/eclipse/eclipse.jdt.ls/blob/0b3651f030e2e68e43019268f35880a07aa7a8c5/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java#L243-L252

The initialization will always be successful thus followed with a `ServiceReady` notification.

So the question is: Do we want to change the server side behavior to, fail the initialize request when importing failed?
Or, another approach could be, at the client, we ignore the `ServiceReady` notification when an `Error` notification has been received.

**Comment by jdneo** [comment]
Update: found a new approach in [#1962](https://github.com/eclipse/eclipse.jdt.ls/pull/1962). We can check the `IMarker`s after import and know if there are any errors when importing the projects. Meanwhile, this makes it possible to recover the server status once those errors are resolved.
