### ISSUE TITLE
Error: The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by TheBMPatil** [redhat-developer/vscode-java#2247]
Issue Type: <b>Performance Issue</b>

First time when i installed the Language Support for JAVA (TM) by Red Hat Extention its was not working but when i re-installed it then it was strted working perfectlly fine. But after some days later i reopened my java project then it is crassing(Extention) again and again so i tried to uninstall and re-intall the Extention but it does not helped. Then i updated everything (VS code, all the java extentions ) But it doesnt helped. So i didnt had choice other than reporting it.

its Reported on github too as issue #112 
i read it but isnt helpful at all.

 
I Hope it will fixed soon !!

Extension version: 1.1.0
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (4.57GB free)|
|Process Argv|--crash-reporter-id af82f520-3c76-4558-b03a-468b5c30ce81|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	    98	  7092	code main
    0	   238	  3192	   window (.log - DSA - Visual Studio Code)
    0	    26	  4556	   crashpad-handler
    0	   196	  5316	   shared-process
    0	    76	  3012	     ptyHost
    0	    62	   840	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	  5536	       console-window-host (Windows internal process)
    0	    80	 10156	     watcherServiceParcelSharedProcess
    0	   129	  6188	   extensionHost
    0	    78	  5892	     "C:\Users\bhagv\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\bhagv\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=6188
    0	   153	  9924	     "C:\Program Files\Java\jdk-13.0.2\bin\java" --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar c:\Users\bhagv\.vscode\extensions\redhat.java-1.1.0\server\plugins\org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration c:\Users\bhagv\AppData\Roaming\Code\User\globalStorage\redhat.java\1.1.0\config_ss_win -data c:\Users\bhagv\AppData\Roaming\Code\User\workspaceStorage\568b39bbf08391fe48cf48fa37781d81\redhat.java\ss_ws
    0	    11	  2100	       console-window-host (Windows internal process)
    6	    42	  8256	   utility-network-service
    7	    90	  8356	   issue-reporter
    6	   163	  8684	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (.log - DSA - Visual Studio Code)
|    Folder (DSA): 8 files
|      File types: java(6) class(2)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30405998
vscexrecpromp3t2:30407763

```

</details>

**Comment by snjeza** [comment]
@bmpatil96k could you, please,  attach the following files: 
-  c:\Users\bhagv\AppData\Roaming\Code\User\workspaceStorage\568b39bbf08391fe48cf48fa37781d81\redhat.java\ss_ws\.metadata\.log
- c:\Users\bhagv\AppData\Roaming\Code\User\workspaceStorage\568b39bbf08391fe48cf48fa37781d81\redhat.java\jdt_ws\.metadata\.log
- c:\Users\bhagv\AppData\Roaming\Code\User\workspaceStorage\568b39bbf08391fe48cf48fa37781d81\redhat.java\client.log.*
