### ISSUE TITLE
Language Support for Java(TM) by Red Hat from version 1.1.0(+) don`t work on JDK8 lambda 

### ISSUE THREAD

**Issue by itomcat666** [redhat-developer/vscode-java#2253]
##### Environment
- Operating System: win 10
- JDK version: jdk 11
- Visual Studio Code version: 1.63.2
- Language Support for Java(TM) by Red Hat version: 1.2.0

##### Steps To Reproduce
1. when you coding use lambda ,it can`t give you suggest on  Language Support for Java(TM) by Red Hat version 1.2.0

![avatar](https://raw.githubusercontent.com/itomcat666/mydoc/main/222.png)

2. when I use the extension 1.0.0 ,it work good:

![avatar](https://raw.githubusercontent.com/itomcat666/mydoc/main/111.png)

I guess if the file in the save folder,it work good,but the file in anthor module ,it don`t work

if this is a bug,please repair this bug as soon as possible,thank you !

I have to use the extension 1.0.0 now 😭

**Comment by snjeza** [comment]
@itomcat666 could you attach a project example?

**Comment by itomcat666** [comment]
![avatar](https://raw.githubusercontent.com/itomcat666/mydoc/main/3333.png)

this is the demo project:
[https://raw.githubusercontent.com/itomcat666/mydoc/main/demo.rar](https://raw.githubusercontent.com/itomcat666/mydoc/main/demo.rar)

my gradle version: 6.9.1
springboot version:2.5.7
jdk version:11
Language Support for Java(TM) by Red Hat version:1.2.0
@snjeza 
hope help you !

**Comment by snjeza** [comment]
@itomcat666 I can't reproduce the issue.

![vscode2](https://user-images.githubusercontent.com/388609/146686789-de6d44f3-654b-4c4e-9c57-8e6c0370c4c2.gif)

Could you, please, attach your logs?

- enable the "java.trace.server": "verbose" setting,
- restart vscode
- attach the logs (Command palette : Java: Open all log files)

See [Enable logging](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by itomcat666** [comment]
this is logs:
[https://raw.githubusercontent.com/itomcat666/mydoc/a051a13ff854fbaf1e99dbe4670e18d229b58d4a/client.log.2021-12-20.9](https://raw.githubusercontent.com/itomcat666/mydoc/a051a13ff854fbaf1e99dbe4670e18d229b58d4a/client.log.2021-12-20.9)
this is the project:
[https://raw.githubusercontent.com/itomcat666/mydoc/main/testjava.zip](https://raw.githubusercontent.com/itomcat666/mydoc/main/testjava.zip)

this is the video:
[![Watch the video]](https://raw.githubusercontent.com/itomcat666/mydoc/main/20211220_231927_Trim.mp4)

@snjeza hope help you,thank you very much !

**Comment by snjeza** [comment]
@itomcat666 Could you try to add the following property:

```
"vsintellicode.java.completionsEnabled": false,
```

cc @testforstephen @jdneo @Eskibear

**Comment by itomcat666** [comment]
@snjeza  after I add the property 
```
"vsintellicode.java.completionsEnabled": false,

```
,this extension "Language Support for Java(TM) by Red Hat from version" work well and it can suggest  tip

my god,the two extensions conflict?😭

**Comment by Eskibear** [comment]
I can reproduce it. More like a bug in intellicode extension. I'll work on that.

**Comment by Eskibear** [comment]
Found the culprit. IntelliCode doesn't cover new `LAMBDA_EXPRESSION` completion kind, leading to completion failure in such case. I'll fix that in IntelliCode.

`LAMBDA_EXPRESSION`  has been added into jdt.core since v3.28
https://git.eclipse.org/r/plugins/gitiles/jdt/eclipse.jdt.core/+/refs/tags/I20211126-1800/org.eclipse.jdt.core/model/org/eclipse/jdt/core/CompletionProposal.java?autodive=0%2F%2F#887

It's introduced into vscode-java@v1.1.0 by commit https://github.com/eclipse/eclipse.jdt.ls/commit/4208c420d89f20255235fb7f7226111a1cccdaa1#diff-f15305031e24556c35cc42f0684bf5bbe9451e76b57735163e51652610367dfbR34

**Comment by Eskibear** [comment]
BTW, eclipse.jdt.ls also has robustness issue without intellicode. Although the completion looks well, you'll find below error in output channel, because `LAMBDA_EXPRESSION` is not coverred.

```
[Error - 下午3:14:51] 2022年1月6日 下午3:14:51 assertion failed: 
assertion failed: 
org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalDescriptionProvider.updateDescription(CompletionProposalDescriptionProvider.java:688)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.toCompletionItem(CompletionProposalRequestor.java:230)
	at org.eclipse.jdt.ls.core.internal.contentassist.CompletionProposalRequestor.getCompletionItems(CompletionProposalRequestor.java:204)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.computeContentAssist(CompletionHandler.java:154)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionHandler.completion(CompletionHandler.java:79)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$5(JDTLanguageServer.java:524)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

**Comment by Eskibear** [comment]
@itomcat666 

I've made a patch in intelliCode, can you try the private build below?
- Close VS Code.
- Unzip [intellicode-fix2253.zip](https://github.com/redhat-developer/vscode-java/files/7825832/intellicode-fix2253.zip) and copy `com.microsoft.jdtls.intellicode.core-0.4.5.jar` into folder `C:\Users\<username>\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.15\dist`
- Start VS Code.
- Try with IntelliCode enabled.

Please let me know if it works.

**Comment by itomcat666** [comment]
@Eskibear yes,I try you private build just now,it work good on version 1.2.0, thank you !😊
