### ISSUE TITLE
Cannot add Java 18+ runtime to java.configuration.runtimes without mislabeling it as JavaSE-17 or below.

### ISSUE THREAD

**Issue by mattwelke** [redhat-developer/vscode-java#2255]
##### Environment
- Operating System:
```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
- JDK version:
```
> java --version
openjdk 18-loom 2022-03-15
OpenJDK Runtime Environment (build 18-loom+7-288)
OpenJDK 64-Bit Server VM (build 18-loom+7-288, mixed mode, sharing)
```
- Visual Studio Code version:
```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```
- Java extension version: `v1.2.0`

##### Steps To Reproduce
1. Install an early access build of Java 18. For example, https://jdk.java.net/loom/. Ensure JAVA_HOME and PATH are set correctly to use it. For example, I use SDKMAN (see https://stackoverflow.com/questions/70415814/how-do-i-set-up-a-custom-jdk-build-in-sdkman/70416690#70416690).
2. Create new Maven project using the quickstart archetype. Set source and target in `pom.xml` to "18":
```
<maven.compiler.source>18</maven.compiler.source>
<maven.compiler.target>18</maven.compiler.target>
```
3. Edit the `App.java` file that was created as part of the Maven project to include code that uses Java 18 features. For example:
```
Thread.ofVirtual().start(() -> System.out.println("Hello world from a virtual thread."));
```
4. Note how VS Code shows an error for that code, saying it doesn't recognize it:
![image](https://user-images.githubusercontent.com/7719209/146704444-529d1ff3-4290-4b2d-bc2c-b40b5d5bd732.png)
5. In settings, try to add the Java 18 JDK to the runtimes. Note how it doesn't allow it, because "JavaSE-18" isn't among the allowed values:
```
{
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-18",
            "path": "/home/matt/.sdkman/candidates/java/18-loom"
        }
    ]
}
```
![image](https://user-images.githubusercontent.com/7719209/146704308-d1089b75-f680-4d91-8012-c0d7f4ade55a.png)
6. Note how if you change the name of the runtime to one among the allowed values, for example "JavaSE-16", it allows the Java 18 runtime to be set:
```
{
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-16",
            "path": "/home/matt/.sdkman/candidates/java/18-loom"
        }
    ]
}
```
7. Note how in `App.java`, the error for the Java 18 code remains.
8. Change source and target in `pom.xml` from "18" to "16" (to match the mislabeled Java 18 runtime configured):
```
<maven.compiler.source>16</maven.compiler.source>
<maven.compiler.target>16</maven.compiler.target>
```
9. Note how, in `App.java`, VS Code now doesn't show an error. Intellisense works for the Java 18 code:
![image](https://user-images.githubusercontent.com/7719209/146704591-a516cfb7-3de2-4e39-aec4-a5d5bbade2b8.png)
10. Run `mvn clean compile`. Note how even though VS Code now understands the Java 18 code, Maven doesn't allow the build to continue because of the misconfigured `pom.xml` file:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project java18test: Compilation failure
[ERROR] invalid source release 16 with --enable-preview
[ERROR]   (preview language features are only supported for release 18)
```

[Please attach a sample project reproducing the error]
https://github.com/mattwelke/java-18-vscode-repro
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
https://gist.github.com/mattwelke/84af88070add794a8f115ee421e6e9c5

##### Current Result

Can only use Java 18 to develop Java code in VS Code if I mislabel it in the `java.configuration.runtimes` setting and set my language level in `pom.xml` to match the incorrect label I choose, which prevents Maven from being able to build my project (and is confusing in general).

##### Expected Result

That I am allowed to configure any Java runtime I have installed on my system to be the runtime VS Code uses to compile my code as I develop (so that I can, for example, use preview Java 18 features as of Dec 2021), being able to choose any label I want.

Also, that VS Code gives me the ability to override the automatic Java runtime choice it makes based on the `pom.xml` file so that, for example, if I have two builds of the same Java version (ex. JavaSE-18), I can choose which one to use at a given time.

**Comment by testforstephen** [comment]
Java 18 is in early access stage, and vscode-java extension does not support it yet.

**Comment by mattwelke** [comment]
I figured that's why I wasn't able to choose "JavaSE-18" as a name for the runtime in settings. But I was pleasantly surprised to see that I was able to use it to develop (see my screenshot where it shows Intellisense working for Java 18 virtual thread stuff). It just didn't play nice with the other Java features of VS Code like how it interacts with Maven. VS Code seemed to use my pom.xml file to determine which VS Code runtime it should use, which is how I was able to trick it into using my Java 18 runtime.

Are there plans to allow people to set custom Java runtimes in the future in VS Code, which would enable use cases like mine?

**Comment by talios** [comment]
I note that even now that Java 18 is released, one still can't use it as JDK name in the configuration.

**Comment by snjeza** [comment]
You may want to take a look at https://github.com/eclipse/eclipse.jdt.ls/pull/2028

**Comment by testforstephen** [comment]
Closing it since Java 18 is supported now.

**Comment by repoairteltigo** [comment]
I'm still having this issue with the newly release jdk-20

**Comment by snjeza** [comment]
@repoairteltigo You may want to take a look at https://github.com/eclipse/eclipse.jdt.ls/pull/2586

**Comment by kchristidis** [comment]
I am bumping into this issue too. Where can I find a list of allowed version strings?

**Comment by snjeza** [comment]
> Where can I find a list of allowed version strings?

@kchristidis You may want to take a look at
- https://github.com/redhat-developer/vscode-java/blob/master/package.json#L782
- [Project JDKs](https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#project-jdks)
