### ISSUE TITLE
Understand where vscode-java uses a `kind` property in QuickPick

### ISSUE THREAD

**Issue by TylerLeonhardt** [redhat-developer/vscode-java#2256]
👋 hi Java folks. We got an issue on vscode related to a new API we have added:
https://github.com/microsoft/vscode/issues/139333

In short, we added an API that lets you define separators/categories in your QuickPicks:
https://code.visualstudio.com/updates/v1_63#_quickpickitem-separators

We use the `kind` property to determine if an item is a separator or a regular item. From the issue I linked, it looks like Java already used this property and I wanna understand how it's used so that we don't end up breaking you.

I addressed that issue:
> * Uses a "less likely used by existing extensions" value for QuickPickItemKind.Separator: -1
> * Checks for that value and if that value is seen, then it checks Proposed API

Which I think should be good for most scenarios but I would like to know more.

##### Steps To Reproduce
1. open a Java source file with inner classes
2. with the cursor on an inner class name, press control-. (command: Quick Fix)
3. choose the first option, "Move 'classname'"
4. observe the error notification that pops up

> NOTE: these steps should no longer cause the error starting 12/21

**Comment by Eskibear** [comment]
Thank you for the mitigation. 

When applying refactoring like moving types, sometimes we expect user interaction e.g. (specify destination), thus we provide some choices in quickpick.

https://github.com/redhat-developer/vscode-java/blob/9f32875a67352487f5c414bb7fef04c9b00af89d/src/refactorAction.ts#L477-L489

And we take different actions according to value of property `kind`:

https://github.com/redhat-developer/vscode-java/blob/9f32875a67352487f5c414bb7fef04c9b00af89d/src/refactorAction.ts#L503

**Comment by TylerLeonhardt** [comment]
Sounds like the mitigation will be enough. Great!

My opinion is to recommend using a different property name (like `type`) or something so that you aren't overriding the meaning of this newly added property to the API, but that's totally your call. I'll go ahead and close this since I got my answer. Thanks!
