### ISSUE TITLE
how to custom format wrapper style

### ISSUE THREAD

**Issue by fyeeme** [redhat-developer/vscode-java#2257]
##### Environment
- Operating System: macos 12.1
- JDK version: 17
- Visual Studio Code version: 1Version: 1.64.0-insider
- Java extension version: 1.2.0

 How to stop it format code like this. 
now the wrapping config only have`length` config. Except  use `@formatter:off`, is there planing to add some more config for wrapping like **intellij idea**.
![image](https://user-images.githubusercontent.com/6078758/146861797-28b4260c-9391-4b06-a935-e758bea1cf36.png)

**Comment by snjeza** [comment]
@fyeeme you may want to take a look at https://github.com/redhat-developer/vscode-java/issues/1126#issuecomment-548085982

**Comment by fyeeme** [comment]
@snjeza  yes ,it works well ,many thanks. and I'll close this issue.
