### ISSUE TITLE
[BUG] annotations cause language service exceptions

### ISSUE THREAD

**Issue by Tarrowren** [redhat-developer/vscode-java#2261]
##### Environment

- Operating System: Win10
- JDK version: openjdk11
- Visual Studio Code version: 1.63.2
- Java extension version: 1.2.0

##### Steps To Reproduce

```java
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import lombok.Data;

@Data
public class TestData {

  private Long id;

  @JsonSetter(nulls = Nulls.SKIP)
  private String name;
}

```

Using both `@Data` and `@JsonSetter` and assigning values to the `nulls` will cause an exception in the language service

##### Current Result

![1](https://user-images.githubusercontent.com/35626141/147177437-335dd6d2-e9ff-46b0-ac21-da614a631b6d.gif)

**Comment by snjeza** [comment]
I can't reproduce the issue.
Test project:
[test.zip](https://github.com/redhat-developer/vscode-java/files/7830588/test.zip)

JVM arguments:
```
"java.jdt.ls.vmargs": "-Dlog.level=ALL -javaagent:/home/snjeza/.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar -Xms3g -XX:TieredStopAtLevel=1 -XX:+UseParallelGC -Dsun.zip.disableMemoryMapping=true"
```

**Comment by Tarrowren** [comment]
I found that it was a problem with the `Lombok Annotations Support for VS Code` plugin, using the jvm parameters provided by @snjeza  will solve it 
```
-javaagent:/.../.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar
```
