### ISSUE TITLE
Import completion

### ISSUE THREAD

**Issue by FooqX** [redhat-developer/vscode-java#2263]
This annoying feature, how to disable it?

##### Environment
- Operating System: Windows10
- JDK version: 17
- Visual Studio Code version: vscode insiders
- Java extension version: 1.2.0

##### Steps To Reproduce
1. Install redhat
2. Type something like sout and it will recommend imports like SourceDataLine which is very annoying behaviour

![Code_-_Insiders_rXq7C0tuVc](https://user-images.githubusercontent.com/65967000/147351436-b3ddc985-eb1d-48a8-a5b7-5826348d93b1.png)

**Comment by snjeza** [comment]
@FooqX you can try to add 

```
org.eclipse.jdt.core.codeComplete.subwordMatch=disabled
```
to <your_projects>/.settings/org.eclipse.jdt.core.prefs

See also [Settings Global Preferences](https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences)
