### ISSUE TITLE
Passing arguments to the Java compiler.

### ISSUE THREAD

**Issue by 4g3nt47** [redhat-developer/vscode-java#2269]
Is it not possible to pass arguments to the Java compiler on a project with no build tools? I just want to pass `-release 9` to java compiler to support older JVMs. I can't find anything in settings.

- Platform: Debian 10 Linux
- VScode: version 1.63.2

**Comment by rgrunber** [comment]
For the `-release` option, you should be able to use `org.eclipse.jdt.core.compiler.compliance=9` in a settings file. See https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences for more details. I'm not sure if there's a setting that allows one to pass arbitrary compiler options. CC'ing @snjeza in case there is a way.

**Comment by rgrunber** [comment]
See https://github.com/redhat-developer/vscode-java/issues/2304#issuecomment-1033134721 for the more general way to do this. You'd need to install vscode-java-debug
