### ISSUE TITLE
Provide a way to disable embedded JRE

### ISSUE THREAD

**Issue by cydparser** [redhat-developer/vscode-java#2276]
The embedded JRE assumes a traditional FHS directory structure on Linux. Nontraditional distributions, like NixOS, do not have directories like _/lib_ and so the embedded Java executable cannot be used. The following opaque error occurs when opening a Java file on NixOS:
```
no such file or directory: /home/user/.vscode/extensions/redhat.java-1.2.0/jre/17.0.1-linux-x86_64/bin/java
```

The file exists, but it requests a nonexistent interpreter, _/lib64/ld-linux-x86-64.so.2_. Deleting the _jre_ directory allows me to use the extension, but that is an unpleasant user experience. A setting to ignore the embedded JRE would be appreciated.

**Comment by Eskibear** [comment]
@cydparser One way I can think of is to manually install the vsix package without embedded JDK. See https://github.com/redhat-developer/vscode-java/releases/tag/v1.2.0

@testforstephen FYI, looks that the embedded JDK is not working on some unpopular Linux distros.

**Comment by testforstephen** [comment]
As far as I know (https://github.com/microsoft/vsmarketplace/issues/288#issuecomment-1004581787), NixOS is not installing extensions via VS Code marketplace, but explicitly download Java extension from the specified URL. If so, can NixOS download the generic version without embedded JRE from the URL https://github.com/redhat-developer/vscode-java/releases/download/v1.2.0/redhat.java-1.2.0.vsix?

Besides, if NixOS doesn't follow FHS directory structure, how would you install JDK on NixOS?

**Comment by cydparser** [comment]
@Eskibear
This [comment](https://github.com/redhat-developer/vscode-java/blob/3fe63b502adc2fe20e9e50ccb75ae854b7a44228/src/requirements.ts#L40) indicates that `java.home` is not used by the version installed from the marketplace.

**Comment by cydparser** [comment]
@testforstephen 
There are multiple ways to install VS Code and extensions on NixOS with different tradeoffs. I installed VS Code through NixOS, but the extensions through the marketplace. A downside to managing the extensions with NixOS is that the versions often lag far behind.

NixOS installs everything in _/nix/store/_ and creates symlinks in either _/run/current-system/sw/_ for system installs or _~/.nix-profile/_ for user installs.

**Comment by testforstephen** [comment]
Another idea I had was that we could detect if the underlying Linux distribution follows the traditional FHS and automatically disable the embedded JRE if it is running on a non-FHS distribution.

**Comment by testforstephen** [comment]
Next version 1.3.0 will have a new setting "java.jdt.ls.java.home" that allows you to use a different JDK to start Java extension.

**Comment by r4ks** [comment]
bytheway I'm having a similar problem but the fact is the buitin java exists, but don't execute on nixos!? is there a problem with these downloaded java binary from vscode or the extension or what can be the issue since the java is there? I refered here too for more information [https://github.com/nix-community/nixos-vscode-server/issues/76]
