### ISSUE TITLE
Java extension: Failed to get sources. Instead, stub sources have been generated by the disassembler.

### ISSUE THREAD

**Issue by hectortv9** [redhat-developer/vscode-java#2277]
While editing my Java code, I am not getting the Javadocs from JDK's source code whenever I hover an element or do a [CTRL]+[LEFT CLICK]. Instead, I am getting code generated by a disassembler.

```
// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
```
 The source file is there at:

```
"D:\Program Files\Java\jdk-17.0.1\lib\src.zip"
```

##### Environment
- Operating System: Windows 11
- JDK version: 
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
- Visual Studio Code version: 1.63.2
- Java extension version:  Language Support for Java(TM) by Red Hat v1.2.0

##### Steps To Reproduce
1. Create a simple java application.
2. Hover a method like System.out.**print()** to see its Javadocs.
3. While holding the CONTROL key, LEFT-CLICK the String class source code.

##### Current Result
1. While hovering the method you will see generic information like  `void java.io.PrintStream.println(String arg0)`
![image](https://user-images.githubusercontent.com/13821299/148634079-bba446f4-2688-4230-a04c-6f66a8557b70.png)
2. When CONTROL+RIGHT-CLICKING to open the source code you will see a decompiled version instead of the JDK's documented source code.
![image](https://user-images.githubusercontent.com/13821299/148634130-34ec4203-beb8-48d5-a8f6-c29597a68c9a.png)

##### Expected Result
1. While hovering the method you should see information like  
![image](https://user-images.githubusercontent.com/13821299/148634057-79bf3e1c-1594-45a0-8840-328d038de0a1.png)
2. When CONTROL+RIGHT-CLICKING to open the source code you should see the JDK's documented source code.
![image](https://user-images.githubusercontent.com/13821299/148634144-e8a37279-d663-4227-ae9d-f06cf870598f.png)

##### Additional Informations
[VS Code console.txt](https://github.com/redhat-developer/vscode-java/files/7832655/VS.Code.console.txt)
[vscode-app-1641621696309.log](https://github.com/redhat-developer/vscode-java/files/7832651/vscode-app-1641621696309.log)

**Comment by hectortv9** [comment]
Source code is now available and visible when hovering

**Comment by KAN19** [comment]
I got the same issues. Please show me how to fix it

**Comment by hectortv9** [comment]
I am sorry but I don't know how to reproduce the issue or when it got solved. I started clicking every related config I could find without any luck, and at some point, I realized that the issue was solved.
As far as I remember I tried a few things:
1) Made sure you have JAVA_HOME environment variable setup.
2) Created a symlink to "src.zip" which might be located at "C:\Program Files\Java\jdk-17.0.1\lib".
3) Recreated the .vscode folder from your project by deleting it and recreating the project from scratch.
4) At some point modified a setting's default value but I cannot remember or find what it was.
Restarted after each attempt without noticing improvement.

I wish I could help you in a substantial way but I really don't know the origin of the problem nor its solution.

Good luck and if you notice that something fixes the issue you might want to post the solution here so others won't struggle unnecessarily.

**Comment by joaotesch** [comment]
I solved it by configuring the same path as JAVA_HOME in the "java.jdt.ls.java.home" config, from the settings.json file.

My JAVA_HOME: 
![image](https://user-images.githubusercontent.com/40344135/152223452-9cfc202e-7679-4da8-9eea-77ad3a5b3da4.png)

settings.json config:
![image](https://user-images.githubusercontent.com/40344135/152223554-40229d9e-d2de-4647-83b2-079713586710.png)

**Comment by razertory** [comment]
I've install the decompiler and it works  https://marketplace.visualstudio.com/items?itemName=dgileadi.java-decompiler ?

**Comment by GustavoASC** [comment]
After configuring settings.json like @joaotesch suggested, I needed to clean the workspace cache with the command: 

`Java: Clean Java Language Server Workspace`

**Comment by CRSampaio** [comment]
Hi!
For me, I've to turn on these two options on extension settings and reload VS Code, then the mouse hover worked as expected:
```
"java.eclipse.downloadSources": true,
 "java.maven.downloadSources": true,
```
Which are these options on GUI:
![image](https://user-images.githubusercontent.com/38435459/207692083-7adff721-ff65-46f4-be19-0555394e3e50.png)
![image](https://user-images.githubusercontent.com/38435459/207692134-bd69f685-21ed-462c-8b58-9b7d403bd7b5.png)

The issue I've been facing was that the Javadocs from some Maven Dependencies weren't being displayed on mouse hover.

**Comment by tangllty** [comment]
I'm sorry for my bad english but you can fix it with the following configuration

setting.json config
![2022-12-27_04-34](https://user-images.githubusercontent.com/58468628/209581786-c9c966a5-9f8a-48fb-8043-aa0f06bcd34a.png)

I'm having the same issues and I'm not sure if it's the right way to do it.

**Comment by henriquedesousa** [comment]
Here's the copy-pasteable setting:

` "java.jdt.ls.java.home": "/opt/jdk-17.0.6+10/"`

**Comment by denispadua** [comment]
I have this problem and I tried all the suggestions and none worked

this is my settings.json file
``
"java.jdt.ls.java.home": "C:\\Program Files\\Java\\jdk1.8.0_333",
"java.maven.downloadSources": true,
"java.eclipse.downloadSources": true,
"maven.terminal.useJavaHome": true

My JAVA_HOME path is: "C:\Program Files\Java\jdk1.8.0_333",

**Comment by r0a0a8w** [comment]
I had this issue with external dependencies. Nothing helped me from the advises above.
I was also getting: "Unable to load IDecompiler class for jarFileContentProvider" every time I was trying to go into dep sources.
The only solution for me was going to ~/.m2/repositories folder and searching for "*.jar-in-progress" and "*.tmp" files.
Once you find them make sure they're not growing in size - these are "zombie" dependencies, crashed in the middle of downloading and there is no way to recover them rather than completely deleting their folders and re-running mvn install from scratch.

**Comment by thexiay** [comment]
It's ok to use extension 'decompiler'.But the code line is not correct.So it's difficult to debug.

**Comment by testforstephen** [comment]
@thexiay You can debug the decompiled source with [Debugger For Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug)@0.52.0. However, this feature only works with the fernflower decompiler that is included in redhat.java@1.20.0. It does not work with 3rd party decompiler extensions, because they don't feed the decompiled line number mappings to debugger.

**Comment by sldpzshdwz** [comment]
I clicked on maven in the explorer and it loaded just fine, it's kind of baffling
