### ISSUE TITLE
java.completion.filteredTypes is not filtering types

### ISSUE THREAD

**Issue by nortakales** [redhat-developer/vscode-java#2279]
I have `zaa.*` in my `java.completion.filteredTypes`, but things like `zaaa.com.google.common.collect.ImmutableMap` still show up in autocomplete.

##### Environment
- Operating System: Windows 10
- JDK version: 11
- Visual Studio Code version: 1.63.2
- Java extension version: 1.2.0

##### Steps To Reproduce
1. Nothing out of the ordinary... just create a Java project with some dependencies and try to use `java.completion.filteredTypes`, see that it still autocompletes what you put in that setting

##### Current Result

Autocompletes matches listed in `java.completion.filteredTypes`

##### Expected Result

Should not autocomplete matches listed in `java.completion.filteredTypes`

##### Additional Informations

See screenshot

![Screenshot 2022-01-10 141800](https://user-images.githubusercontent.com/25379568/148848320-8acb08a4-fc54-42f2-b8b8-3cb27ff373d4.png)

**Comment by AndrzejKowalski9917** [comment]
Hey,

might be a typo. Try `zaaa.*` with 3 _a_.

**Comment by nortakales** [comment]
I don't see a typo. My settings has both `zaaa.*` and `zaaa.com.google.common.collect.*`.

I did discover something interesting just now though. `java.completion.filteredTypes` does indeed work when auto completing a class. Example:

![Screenshot 2022-01-13 122421](https://user-images.githubusercontent.com/25379568/149403838-2d392c76-ac51-4f35-bca3-a889210ec45f.png)

But as you can see in my initial screenshots, it does *not* work when autocompleting methods of the class (when the class is not yet imported). It should filter out classes in both cases.

**Comment by jdneo** [comment]
Seems related with this change: https://github.com/eclipse/eclipse.jdt.ls/pull/1213

maybe we need to check the import statement when completion on methods/fields

**Comment by nortakales** [comment]
This appears to have been resolved by https://github.com/eclipse/eclipse.jdt.ls/pull/2007

**Comment by jdneo** [comment]
Yes it should have been fixed in the latest release.
