### ISSUE TITLE
Completing /** should generate Javadoc with params 

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#228]
typing `/**`+`Enter` on top of methods/constructors should generate Javadoc with parameters like in Eclipse or typescript support in VS Code:
![may-28-2017 01-05-06](https://cloud.githubusercontent.com/assets/148698/26526248/1e57952c-4342-11e7-86c2-07aeb02937b4.gif)

**Comment by spiker9** [comment]
It doesn't work

**Comment by fbricon** [comment]
No it doesn't, since the bug is still open

**Comment by erihanse** [comment]
Please use the voting button @spiker9

**Comment by msandim** [comment]
This!

**Comment by jagarcia-xumak** [comment]
This would be the dream, one step closer to get rid of IntelliJ, please make this happen

**Comment by fbricon** [comment]
Kudos to @snjeza for making it happen:

![aug-21-2018 19-43-00](https://user-images.githubusercontent.com/148698/44434685-8756b580-a57a-11e8-9333-149a641fc7ad.gif)

**Comment by timobehrens** [comment]
@fbricon How do I activate this? I don't get the javadoc comment autocomplete. I have the latest version of Language Support for Java installed.

**Comment by timobehrens** [comment]
OK, so I get it for some method signatures, but not for all.

This one is triggered correctly:
```
private CloudFile getCloudFile(String shareName, String folderPath, String fileName){
```

And this one isn't:
```
public boolean downloadFile(String shareName, String folderPath, String fileName, String destinationFolder) {
```

@snjeza

**Comment by fbricon** [comment]
I guess it's enabled for public methods only, for some reason

**Comment by timobehrens** [comment]
It's actually the other way round: Only private methods trigger it.

**Comment by amrtn** [comment]
I'm facing the same issue. Only javadoc is prompted for private methods.

 I'm on Code - Insiders  version `1.29.0-insider`: 

![image](https://user-images.githubusercontent.com/151747/48345942-c2e4b580-e679-11e8-93cf-f8a0bef6a49d.png)

**Comment by Monkatron95** [comment]
I have the lastest version of this language support installed, and the lastest version of vscode; this feature does not work for any functions withing my Spring Boot application, no matter what access modifier is used.

Is anyone else having issues with this feature?

**Comment by praenubilus** [comment]
Latest version, not triggered for either public or static version

**Comment by chuckb** [comment]
1.31.1 VSCode and 0.39.0 Language Support for Java. Javadocs will not format parameters. Used to work. Now does not.

**Comment by fbricon** [comment]
Please open a new ticket with steps to reproduce

**Comment by spottedmahn** [comment]
is there a way to trigger it to update the Javadoc comment for added/removed params?

**Comment by deekshithanand** [comment]
> is there a way to trigger it to update the Javadoc comment for added/removed params?

Well I dont know if this is feasible as a feature, but currently I remove the entire javadoc comment and regenerate it...(of course,I would have copied the content in between)!!!
