### ISSUE TITLE
How to ignore this error message,When actually compiling and running, it is allowed

### ISSUE THREAD

**Issue by 759852125** [redhat-developer/vscode-java#2281]
@apupier 

![image](https://user-images.githubusercontent.com/54934866/149079296-727a4957-2f97-46c8-b0aa-7b09cc08f5c1.png)

**Comment by apupier** [comment]
@759852125 Why am I tagged on this issue?

Few ideas:
- use @SuppressWarning annotation
- Provide the parameterized type (which is the best practice)

**Comment by 759852125** [comment]
> @759852125为什么我在这个问题上被标记？
> 
> 几个想法：
> 
> * 使用@SuppressWarning注解
> * 提供参数化类型（这是最佳实践）

thank you

**Comment by 759852125** [comment]
> @759852125为什么我在这个问题上被标记？
> 
> 几个想法：
> 
> * 使用@SuppressWarning注解
> * 提供参数化类型（这是最佳实践）

thank you
