### ISSUE TITLE
`Clean` should remove .`settings` `.classpath` `.project` in the project

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2286]
> feature request

Hopefully `Java: Clean Java Language Server Workspace` can delete `.settings`, `.classpath`, and `.project` at the same time.

> reason

The `.settings`, `.classpath`, and `.project` in the existing project may be wrong. After executing `Java: Clean Java Language Server Workspace`, the construction of the project will be affected by the wrong configuration in these three files, resulting in building the project error. It has to be removed manually before rebuilding will work. 

##### Environment
- Operating System:windows10 21H2
- JDK version:17
- Visual Studio Code version:1.63.2
- Java extension version:1.2.0
- Gradle version:7.3.3

##### Steps To Reproduce
No need to re-step, this is a feature request

##### Current Result
`.settings`, `.classpath`, and `.project` need to delete by manual.

##### Expected Result
`Java: Clean Java Language Server Workspace` can delete `.settings`, `.classpath`, and `.project`

**Comment by mozhuanzuojing** [comment]
This may cause ambiguity and may need to be handled by yourself. I will close

**Comment by wwwalohacampus** [comment]
After executing the 'Java: Clean Java Language Server Workspace' feature, there is an issue where the Live Reload functionality in Spring Boot does not work.
