### ISSUE TITLE
is not on the classpath of project , only syntax errors are reported

### ISSUE THREAD

**Issue by Ao-Last** [redhat-developer/vscode-java#2297]
[provide a description of the issue]
##### Environment
- Operating System: Windows 10 
- JDK version: 14
- Visual Studio Code version: 1.63.2
- Java extension version: 0.20.0 (The Extension pack)

##### Workspace files
![image](https://user-images.githubusercontent.com/63785048/150682314-a14b8d83-37c9-4328-845d-7d8d4e2a92f7.png)

##### Source configuration in pom.xml
![image](https://user-images.githubusercontent.com/63785048/150682360-49012462-26ef-42ad-a702-d311e5c38888.png)

##### Java Projects Interface
![image](https://user-images.githubusercontent.com/63785048/150686798-213e900a-34c9-437f-80a1-8c1b371fc2e7.png)

However, with the source directory set to others such as src/main/java, the Java Projects Interface shows that component.

##### Current Result
* Warnings and No language support except for basic syntax.
* Cannot run test from the Test Runner.
* Test runs well and show output in the terminal by clicking the test button in the Maven component.
* All works well open with IDEA.

##### Expected Result
* No warnings.
* Test runner could detect JUnits tests normally.

**Comment by mozhuanzuojing** [comment]
The source directory is wrong. It should be `Dog`

**Comment by Ao-Last** [comment]
> The source directory is wrong. It should be `Dog`
The folder `Dog` is a package which means the first lines of `Dog.java` and `DogTest.java` are `package Dog;`. After experiments, it was not supported to set the source directory as  ${project.basedir} in VSCode. If I changed it to ${project.basedir}/src and put the folder Dog into src, it worked well.

**Comment by Ao-Last** [comment]
> The source directory is wrong. It should be `Dog`

The folder Dog is a package which means the first lines of Dog.java and DogTest.java are package Dog;. After experiments, it was not supported to set the source directory as ${project.basedir} in VSCode. If I changed it to ${project.basedir}/src and put the folder Dog into src, it worked well.

**Comment by Ao-Last** [comment]
The problem is redefined hence the issue is closed and another issue #2298 is opened for the underlying problem.
