### ISSUE TITLE
Error when using lombok

### ISSUE THREAD

**Issue by Oualitsen** [redhat-developer/vscode-java#2301]
[provide a description of the issue]

##### Environment
- Operating System: Windows 11
- JDK version: 17
- Visual Studio Code version: 1.62.3
- Java extension version:1.3.0

##### Steps To Reproduce
1. Clone [https://github.com/Oualitsen/demo-lambok-vscode-issue](https://github.com/Oualitsen/demo-lambok-vscode-issue)
2. Open it in vscode with lombok extention installed.

in most of the time it works fine with lombok but when some base classes are annotated with `@FieldNameConstants` super classes will not recognize it. (take a look at the screen shots)
![1](https://user-images.githubusercontent.com/7974581/151223511-fda0c9c7-5951-4205-90f5-98ce32da29ea.jpg)
![2](https://user-images.githubusercontent.com/7974581/151223520-5af658ef-bb9f-48d1-b303-182da1b9b64f.jpg)

**Comment by snjeza** [comment]
> The project compiles and runs fine but the editor shows some errors

I can't reproduce the issue.
There are some warnings, but no errors.

![lombok](https://user-images.githubusercontent.com/388609/151895359-104f5fe8-ab8b-4bff-8ad0-72ff3adc0b8e.gif)


You can add the following properties

```
org.eclipse.jdt.core.compiler.problem.unusedImport=ignore
org.eclipse.jdt.core.compiler.problem.unusedLocal=ignore
org.eclipse.jdt.core.compiler.problem.unusedPrivateMember=ignore
```
to <your_project>/.settings/org.eclipse.jdt.core.prefs to disable these warnings.

![lombok2](https://user-images.githubusercontent.com/388609/151895481-0129a4b5-ccdd-408e-9c85-46d705ab6adf.gif)

**Comment by Oualitsen** [comment]
@snjeza thank you for your reply, if you want the error you should uncomment the `@FieldNameConstants` from the `Validatable.java` class.

**Comment by snjeza** [comment]
> @snjeza thank you for your reply, if you want the error you should uncomment the @FieldNameConstants from the Validatable.java class.

I have done it.
![lombok3](https://user-images.githubusercontent.com/388609/151909612-d18a3e7f-0013-402f-9f58-25a99db489fb.gif)

Could you show me an error? I can see only some warnings.
![lombok](https://user-images.githubusercontent.com/388609/151910218-d333ae83-66b4-4f05-9a37-c50e63d4abfb.png)

**Comment by snjeza** [comment]
> thank you for your reply, if you want the error you should uncomment the @FieldNameConstants from the Validatable.java class.

I still can't reproduce the issue.
![lombok3](https://user-images.githubusercontent.com/388609/151912435-61dc07c3-432a-4d85-95d0-72ba82066c46.gif)

Could you try to [Clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory) ?

**Comment by Oualitsen** [comment]
I did add all the required properties and the warnings were not the problem for me.
As I said, this issue can only be reproduced using lombok and I am sure you are using it.
I of course did clean the workspace directory (long before opening this issue).

Take a look at how I reproduced the issue
![ezgif-2-0d79d2c1f7](https://user-images.githubusercontent.com/7974581/152092270-17ddd6d6-d10b-43b8-86fd-b5ede0eda987.gif)
.

**Comment by Oualitsen** [comment]
Hey, I thing this is not the right place for the issue.
I've always used NetBeans so I am not really familiar with Eclipse.
I downloaded eclipse and Installed lombok. I open the project using eclipse and the I get the same error messages.
So the issue comes from eclipse language server (nothing to do with lombok nor this amazing plugin)

**Comment by snjeza** [comment]
> I did add all the required properties and the warnings were not the problem for me.
As I said, this issue can only be reproduced using lombok and I am sure you are using it.
I of course did clean the workspace directory (long before opening this issue).

I can reproduce the issue when opening UserBase.java or Client.java. It is an eclipse upstream issue.

**Comment by Oualitsen** [comment]
The issue has nothing to do with lombok and has nothing to do with vscode plugin. opening the same project in eclipse shows the same error unfortunately.

**Comment by snjeza** [comment]
> It is ~~an eclipse~~ lombok upstream issue.

You can try the following workaround:

```
diff --git a/src/main/java/lombok.config b/src/main/java/lombok.config
new file mode 100644
index 0000000..5979bfc
--- /dev/null
+++ b/src/main/java/lombok.config
@@ -0,0 +1 @@
+lombok.addSuppressWarnings = false
```
