### ISSUE TITLE
How to pass command line parameters to the java compiler

### ISSUE THREAD

**Issue by slPerryRhodan** [redhat-developer/vscode-java#2304]
In my project we use spring data with named parameter, which is running fine with IntelliJ, but in VSCode I get the following exception:
```
2022-01-28 11:01:15,170 |-ERROR in at.***.commons.exception.RestExceptionHandler - For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.; nested exception is java.lang.IllegalStateException: For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.
org.springframework.dao.InvalidDataAccessApiUsageException: For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.; nested exception is java.lang.IllegalStateException: For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:371)
EntityManagerFactoryUtils.java:371
	...
```

In IntelliJ I can set "Additional command line parameters" under _Settings -> Build, Execution, Deployment -> Compiler -> Java Compiler_. And this issue is solved, if I add "-parameters" as command line parameter in IntelliJ, but I have no clue how to do this in VSCode. I can only find information about passing _vmarg_ parameters in VSCode.

##### Environment
- Operating System: Win 10
- JDK version: 11
- Visual Studio Code version: 1.63.2
- Java extension version: Language Support for Java(TM) by Red Hat v1.3.0

##### Steps To Reproduce
Use Spring Data with named parameters ([Spring Docu Named Parameters](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.named-parameters)) without the annotation _@Param_ and the compiler flag 
_"-parameters"_ is not  #set.

##### Current Result
- Can run the applications until the the application tries to access via spring data the database and then it throws the mentioned exception
- Run & Debug Tests (e.g. Integration / Karate tests) not possible because of the mentioned excetpion
##### Expected Result
- pass java compiler flags like _"-parameters"_ should be possible
##### Additional Informations
#2269

**Comment by rgrunber** [comment]
I'm not sure if this is possible currently for unmanaged projects under vscode-java. CC'ing @snjeza. There's a bunch of compiler options that can be set listed at https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences but I don't think this is there.

**Comment by snjeza** [comment]
> Run & Debug Tests (e.g. Integration / Karate tests) not possible because of the mentioned excetpion

@slPerryRhodan @rgrunber You may want to take a look at https://code.visualstudio.com/docs/java/java-debugging#_configuration-options

**Comment by chad-russell** [comment]
For those running into this in the future: I was able to solve it by adding this to my `.prefs` file (the one specified by the `java.format.settings.url` setting)

```
org.eclipse.jdt.core.compiler.codegen.methodParameters=generate
```

**Comment by rgrunber** [comment]
Good catch! That definitely looks like the right thing, and https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core/batch/org/eclipse/jdt/internal/compiler/batch/Main.java#n2333 confirms it. So no need to use vscode-java-debug unless there's more customization that's needed. Closing this for now.

**Comment by slPerryRhodan** [comment]
@snjeza I looked at it many times and it's not helpful.

@chad-russell thanks, that.s good. A bit (very) inconvenient to configure compared to eclipse and intelliJ, but at least it's possible.

**Comment by thiagoprazeres** [comment]
Create file:
.settings/org.eclipse.jdt.core.prefs
Content:
org.eclipse.jdt.core.compiler.codegen.methodParameters=generate
