### ISSUE TITLE
help required on source file export in jar file

### ISSUE THREAD

**Issue by space192** [redhat-developer/vscode-java#2306]
Hey,
I'm currently trying to export my jar file with the default project creation, with no build tools
And I want to export the .java file inside of the .jar file is there any way to do it?

**Comment by CsCherrYY** [comment]
you can check here: https://github.com/microsoft/vscode-java-dependency/wiki/Export-Your-Project-to-a-Jar#advanced-custom-export-task, it's about how to customize the exported jar.

**Comment by testforstephen** [comment]
Close it since it has been solved. See https://github.com/microsoft/vscode-java-dependency/issues/590#issuecomment-1028474729
