### ISSUE TITLE
﻿Feature request: Allow test output output to be different than main output

### ISSUE THREAD

**Issue by schophil** [redhat-developer/vscode-java#2312]
I work with Maven projects. These projects are configured to use different output folders for main and test classes. However the vscode plugin does not follow this. All classes (test & main) come together in the same output folder. There also doesn't seem an option to force this. 

This generates errors when a test class overwrites a main class (same package and name). 

In Eclipse this can be forced if I am not mistaken.

**Comment by jdneo** [comment]
AFAIK, the extension should follow the pom configuration, which you can use `outputDirectory` & `testOutputDirectory` to specify the output path. See: https://maven.apache.org/pom.html#directories

If this is not working for your case, would you mind to share a sample project?

**Comment by schophil** [comment]
My mistake. The source of the problem is a class defined in both the main and test package (with the same name). This gave an error and I assumed it was because the class file was being overwritten (in the same output folder) but it is probably not that. The language server probably detects this before compilation? 

```
{
  message: '[Error - 7:21:54 AM] 10 Feb 2022, 07:21:54 Error occured while building workspace. Details: \n' +
    ' message: The type DemoApplication is already defined; code: 0; resource: /Users/schophil/Downloads/demo/src/test/java/com/example/demo/DemoApplication.java;',
  level: 'info',
  timestamp: '2022-02-10 07:21:54.536'
}
```

This doesn't give problems in IntelliJ and pure maven build though. 
Anyway I know it is not ideal but I am not the only programmer on the project :-)

Thanks for the answer.
