### ISSUE TITLE
Random underlining and unknown errors, No CodeRunner features

### ISSUE THREAD

**Issue by J2S3** [redhat-developer/vscode-java#2321]
[provide a description of the issue]

##### Environment
- Operating System: Mac OS
- JDK version: 17?
- Visual Studio Code version: 1.6.2
- Java extension version: JavaSE-17

##### Steps To Reproduce
1. Write any basic function
2. Get error: "Implicit super constructor Object() is undefined for default constructor. Must define an explicit constructor Java(134217868)"
3. Get error: "String cannot be resolved to a type Java(16777218)"
4. Get error: "System cannot be resolvedJava(570425394)"

##### Example 1
<img width="1117" alt="Screen Shot 2022-02-14 at 2 38 20 PM" src="https://user-images.githubusercontent.com/99507598/153934188-f06fdb74-127d-4b8d-be69-4c785565e176.png">

#### Example 2
<img width="1116" alt="Screen Shot 2022-02-14 at 2 49 50 PM" src="https://user-images.githubusercontent.com/99507598/153936029-025d37cd-4c1b-4a12-833a-802d8fb5c703.png">

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by rgrunber** [comment]
The thumbs down beside the Java status bar item (bottom right) would imply the project import failed.

When the project is in that state select `Java: Open All Log Files` from the comand palette. Do you see any errors ? Are you able to post the contents ?
