### ISSUE TITLE
"No definitions found"

### ISSUE THREAD

**Issue by rhystedstone** [redhat-developer/vscode-java#2328]
A lot of definitions for methods and classes do not work. I press F3 and "No definitions found" pops up. It doesn't happen for all methods - just some. It's not just inherited methods, and some still work completely fine.

##### Environment
- Operating System: Windows 11 21H2 (22000.493)
- JDK version: 17.0.1+12
- Visual Studio Code version: 1.64.2 (user setup)
- Java extension version: v1.3.0

##### Steps To Reproduce
1. Attempt to find a definition

[Please attach a sample project reproducing the error]

Devtools Log:
```
 INFO IExtensionHostStarter.start() took 99 ms.
log.ts:313   ERR [Extension Host] (node:13952) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:13952) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137
log.ts:313   ERR o.logFailedRequest is not a function: TypeError: o.logFailedRequest is not a function
	at c:\Users\Rhys\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:794075
	at async N.provideCodeActions (c:\Users\Rhys\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:96524)
log.ts:307  WARN Settings pattern "keyboard.*" doesn't match any settings
log.ts:313   ERR o.logFailedRequest is not a function: TypeError: o.logFailedRequest is not a function
	at c:\Users\Rhys\.vscode\extensions\redhat.java-1.3.0\dist\extension.js:2:794075
	at async N.provideCodeActions (c:\Users\Rhys\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:96524)
```

Language Server:
[java-language-server.txt](https://github.com/redhat-developer/vscode-java/files/8121409/java-language-server.txt)

##### Current Result
"No definitions found"

##### Expected Result
To find the definition(s)

##### Additional Information
I have tried this with only the Java Extension Pack enabled and it still occurs. There are no compiler or build issues - not even syntax errors. I can fully navigate to the methods manually, just the hotkey won't work (sometimes)]

![Project](https://user-images.githubusercontent.com/12123847/155251335-fdd95063-506c-4cbf-9ef7-0835c5203b96.png)

`Projectile.setBounce()` works:
![image](https://user-images.githubusercontent.com/12123847/155251373-54f9b788-be75-4a03-814e-0c291e137c8d.png)

`Projectile.setVelocity()` doesn't:
![image](https://user-images.githubusercontent.com/12123847/155251402-93f5e1fc-6894-477f-8cb2-d89e39db1b38.png)

`JavaPlugin.getLogger()` doesn't:
![image](https://user-images.githubusercontent.com/12123847/155251447-9ddd07c5-e8b0-4cce-b7b0-5921147db980.png)

**Comment by rgrunber** [comment]
The logs would seem to show this is for the standard language server, so the fact that no errors are shown would imply they have resolved. Does completion in the file work ? If you search for workspace symbols (`<ctrl>+<shift>+t`), are you able to locate any of the types like `Projectile` ?

Is the project publicly available somewhere to test ?

**Comment by rhystedstone** [comment]
I am unable to reproduce this issue as the example given above is heavily outdated.
However, this issue still occurs consistently.

I'll reply once it occurs again and try my best to provide the example in full.
