### ISSUE TITLE
<pre> section of the Javadoc is shown blank in the latest VS Code.

### ISSUE THREAD

**Issue by ArithAuth** [redhat-developer/vscode-java#2329]
Using previous version of VS Code can avoid this problem.
_JavaDoc Hovers_ ignores \<pre\> tag; Hovering over a class or method name, the Javadoc appears in a small window, but the \<pre\> section is completely blank. This problem occurs only in latest VS Code version 1.64 (January 2022), not in earlier versions such as v1.63 (November 2021). This also happens with other versions of JDK or Java extension.

##### Environment
- Operating System: macOS Monterey 12.2.1
- JDK version: 17.0.2+8
- Visual Studio Code version: 1.64.2 (Universal)
- Java extension version: v1.3.0

##### Steps To Reproduce
<pre>
/**
 * this will be shown
 * 
 * &lt;pre>
 * this won't be shown
 * in the preview section
 * &lt;/pre>
 */
public static void main(String[] args) {
}
</pre>

Hovered over the class name, but none of the preview section:

<pre>
void Test.main(String[] args)
----------------------------
this will be shown

    Parameters:
        args
</pre>

Do I need to attach a sample project or logs. I'm beginner.

##### Current Result
In latest VS Code version 1.64 (January 2022), happened
![スクリーンショット 2022-02-23 13 45 24](https://user-images.githubusercontent.com/100252514/155263140-d9b90b61-9b37-47ae-84ce-5e3ae5d1adba.png)

##### Expected Result
In previous (v1.63), not happened
![スクリーンショット 2022-02-23 13 48 24](https://user-images.githubusercontent.com/100252514/155263314-a5b33742-29d4-44f1-a15a-b3e2eccda2f2.png)

##### Additional Informations
Tags such as \<p\> and \<blockquote\> are working; Only \<pre\> is broken.

If this issue matters for VS Code, not Java extension, sorry.

**Comment by snjeza** [comment]
The issue has been fixed in the latest VS Code Insiders - https://code.visualstudio.com/insiders/ 
Commit: b7730c807c1e0fdacdcc91a854bb963715b2a89b
Date: 2022-02-28T14:42:24.336Z
I suppose https://github.com/microsoft/vscode/commit/52e65499654de7525e30df3a8228b69320796bf5 fixes it.

**Comment by rgrunber** [comment]
@ArithAuth can you verify that VS Code Insiders resolves the issue for you ?

**Comment by rgrunber** [comment]
Then let's close this for now as this should be fixed once 1.65.0 is released. Thanks for verifying.

I would have merged @snjeza's fix but despite restoring `<pre>` tag behaviour, it seemed to result in the entire [javadoc being unformatted](https://github.com/eclipse/eclipse.jdt.ls/pull/2012#issuecomment-1054711085).

**Comment by snjeza** [comment]
VS Code 1.65 has been released. The issue has been fixed.
