### ISSUE TITLE
Add ability to attach missing sources

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#233]
If a class file has no known source, a disassembled source is displayed instead. 
There should be a way to easily attach missing sources to the jar containing the file in question.

Originally suggested by @jtsiros on https://marketplace.visualstudio.com/items?itemName=redhat.java#review-details

**Comment by fbricon** [comment]
@yaohaizh @testforstephen I think this could be implemented via a menu/command with stock vscode-java

**Comment by akaroml** [comment]
Propose a workflow:
1. Show "Open Folder" dialog to let users pick the location of the additional source
2. Persist the location into user settings - "java.additionalSourceLocations: []"
3. Language server follows the setting and works with those additional source locations

**Comment by akaroml** [comment]
@testforstephen can you take a look?

**Comment by testforstephen** [comment]
The ux is adding a context menu `Update Source Attachment` on the disassembled source editor (JdtContentProvider). When the user clicks the menu, pop up a `Open File` dialog to select the source jar/zip file. Then binding the source attachment to the binary path, and re-rendering the class file contents in VS Code.

**Comment by fbricon** [comment]
Fixed with #699, thanks to @testforstephen 

<img width="821" alt="screen shot 2018-11-13 at 7 05 33 pm" src="https://user-images.githubusercontent.com/148698/48451159-1f79ca80-e777-11e8-8a9c-44a75a9b05b4.png">

**Comment by mikedoy** [comment]
When I attach source, where is this information stored? I'm not seeing it in my settings.json.
