### ISSUE TITLE
The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by liechtir** [redhat-developer/vscode-java#2335]
When using a non vanilla JVM, the language support crashes and cannot be used. All works fine when using a vanilla JDK.

##### Environment
- Operating System: Rocky Linux
- JDK version: openJDK enhanced with DCEVM, can be found on https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/download/dcevm-11.0.11%2B1/Openjdk11u-dcevm-linux-x64.tar.gz
- Visual Studio Code version: code-server 4.0.2 from https://github.com/coder/code-server
- Java extension version: 1.3.0

Motivation for DCEVM: it supports hot code deployment on a level like JRebel, which allows to add methods, change method signatures, change method body, add new java classes etc without the need to redeploy the application.

##### Steps To Reproduce
1. make sure to use dcevm jvm
```
java --version: $ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-dcevm-11.0.11+1-202105021744 (build 11.0.11+1-202105021744)
Dynamic Code Evolution 64-Bit Server VM AdoptOpenJDK-dcevm-11.0.11+1-202105021744 (build 11.0.11+1-202105021744, mixed mode)
```

3. start code-server and connect using browser to your vscode client, import some maven java project, get the error:
![image](https://user-images.githubusercontent.com/1678080/156164012-d5a99b20-8f52-4a50-866e-a44c50ff7dfb.png)

There is no need to attach a sample project as it happens with any java project right away.

##### Current Result
language support is not available

##### Expected Result
all runs smooth and even with a dcevm enhanced JVM the tool runs as it should, having java language support

**Log files attached:**
[redhatlogs.txt](https://github.com/redhat-developer/vscode-java/files/8161348/redhatlogs.txt)

**Comment by rgrunber** [comment]
```
{
  message: 'Must use the Serial, Concurrent Mark Sweep or G1 GC with enhanced class redefinition.\n' +
    'Error: Could not create the Java Virtual Machine.\n' +
    'Error: A fatal exception has occurred. Program will exit.\n',
  level: 'info',
  timestamp: '2022-03-01 10:20:09.815'
}
```

I think this is the root of all the other failures.

We use default vmargs of `"-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m"` (in addition to some options we add at runtime depending on some other factors) . This can be re-defined with `java.jdt.ls.vmargs`.

Does the problem go away if you set `java.jdt.ls.vmargs` to something like `"-XX:+UseG1GC -Xmx1G -Xms100m` with the DCEVM enhanced JDK ?

**Comment by rgrunber** [comment]
@liechtir changing the settings in `java.jdt.ls.vmargs` is a bit of a workaround. I think there's still a better solution to your problem.

There are 2 consumers of a JDK : 

1.  vscode-java's language server (JDT-LS)
2. Your project(s)

Currently you're overriding both to use your JDK with DCEVM support (`/usr/java/dcevm-11.0.11+1/bin/java`). However, you only need this JDK to compile your project, and as far as I know, there's no requirement to have the runtime itself use it.

In your case, you could define something like :

```json
"java.jdt.ls.java.home": "/usr/java/jdk-11.0.13_8/bin/java",
"java.configuration.runtimes": [
  {
    "name": "JavaSE-11",
    "path": "/usr/java/dcevm-11.0.11+1/bin/java",
  }
]
```

in your settings.json.

and that would allow your projects to be compiled with your non-vanilla JDK while ensuring vscode-java's runtime also has one that supports some standard options.

See https://github.com/redhat-developer/vscode-java#setting-the-jdk for more details.

**Comment by liechtir** [comment]
Agree, I basically need the DCEVM only for my application server so that when I change a source file and save, the changes are applied during runtime. I do not need it at all in vscode.
Thanks for pointing out the config, I believe I'll make it even simpler which is to have the vanilla JVM system wide and adopt the app servers JVM only.

Still for VSCode, it might be worthwhile to use common compatible default settings or at least come up with an obvious error message. Thanks for your help Roland =)

**Comment by rgrunber** [comment]
Yup, agreed. I recall we've been bitten by this in the past with things like https://github.com/redhat-developer/vscode-xml/pull/278#issuecomment-644977850 (not using default settings).

If the vscode-langaugeserver API provided us a way to get access to the [exit code](https://github.com/microsoft/vscode-languageserver-node/issues/688) , or maybe we could even re-launch with default arguments, that might help diagnose things. 

Starting to look like what we really need is to evaluate the top reasons for language server crash and have some programmatic workarounds for the first few. Maybe we call it something like "recovery mode", and it's activated once the "5 crashes in the last 3 minutes" occurs.
