### ISSUE TITLE
The number of method signatures cannot be displayed in some cases

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#2341]
Issue Type: <b>Bug</b>

The number of method signatures cannot be displayed in some cases
Continuing the previous question:
Signature Help sometimes doesn't work on constructors and qualified method declarations
https://github.com/redhat-developer/vscode-java/issues/2097
code 1.65
java(TM) by Red Hat 1.4

https://user-images.githubusercontent.com/54253524/156697650-6bcdf35c-4468-4885-bab9-ddcd534f87c3.mp4

Extension version: 1.4.0
VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:08.962Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|

**Comment by zhouxinghong** [comment]
@angelozerr @fbricon @snjeza @Eskibear @BoykoAlex There is also a long-standing unresolved issue that needs to be addressed urgently. . . Please see:

**Comment by rgrunber** [comment]
@zhouxinghong when you said a long-standing issue that needs to be addressed, you're pointing to this issue, #2341 . Did you mean some other issue ?

@snjeza , would be good to investigate if you have time, as it likely deals with that same block of code / methods we had to fix for #2097.

**Comment by zhouxinghong** [comment]
> @zhouxinghong when you said a long-standing issue that needs to be addressed, you're pointing to this issue, #2341 . Did you mean some other issue ?
> 
> @snjeza , would be good to investigate if you have time, as it likely deals with that same block of code / methods we had to fix for #2097.

@rgrunber 2341 is a continuation of the 2097 question. . . Since the problem of 2097 has not been completely solved in 1.4, there is only 2341

**Comment by rgrunber** [comment]
For `ResultData.fail()`there are 3 overloaded methods listed when signature help is activated outside the parameters, and only 1 when signature help is activated inside the parameters. For `ResultData.success()` there are 3 overloaded methods in both cases. That's what stood out to me as different.

**Comment by snjeza** [comment]
@rgrunber @zhouxinghong Could you, please, check https://github.com/snjeza/vscode-test/raw/master/java-1.5.0.vsix
Test class:
```
package test1;
@SuppressWarnings("all")
public class SignatureHelp2097 {
    private String name;
    SignatureHelp2097 signatureHelp;

    public SignatureHelp2097(String name) {
        this.name = name;
    }
    boolean test() {
        this.signatureHelp = new SignatureHelp2097(null);
        SignatureHelp2097 sh = new SignatureHelp2097(null);
        Result resultData = new Result();
        boolean flag = true;
        try {
            if (flag) {
                return resultData.success("abc, cde!", signatureHelp);
            } else {
                return resultData.fail(flag);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        return resultData.fail("abc, cde!", signatureHelp);
    }
}

class Result {
    private boolean flag;
    public Boolean success(int code, String msg, Object data) {
        return flag;
    }
    public Boolean success(String msg, Object data) {
        return flag;
    }
    public Boolean success(Object data) {
        return flag;
    }
    public Boolean fail(int code, String msg, Object data) {
        return flag;
    }
    public Boolean fail(String msg, Object data) {
        return flag;
    }
    public Boolean fail(Object data) {
        return flag;
    }
}
```

**Comment by rgrunber** [comment]
Seems to be working for me. Signature help works correctly now.

**Comment by zhouxinghong** [comment]
> @rgrunber @zhouxinghong Could you, please, check https://github.com/snjeza/vscode-test/raw/master/java-1.5.0.vsix Test class:
> 
> ```
> package test1;
> @SuppressWarnings("all")
> public class SignatureHelp2097 {
>     private String name;
>     SignatureHelp2097 signatureHelp;
> 
>     public SignatureHelp2097(String name) {
>         this.name = name;
>     }
>     boolean test() {
>         this.signatureHelp = new SignatureHelp2097(null);
>         SignatureHelp2097 sh = new SignatureHelp2097(null);
>         Result resultData = new Result();
>         boolean flag = true;
>         try {
>             if (flag) {
>                 return resultData.success("abc, cde!", signatureHelp);
>             } else {
>                 return resultData.fail(flag);
>             }
>         } catch (Exception e) {
>             System.out.println(e.getMessage());
>         }
>         return resultData.fail("abc, cde!", signatureHelp);
>     }
> }
> 
> class Result {
>     private boolean flag;
>     public Boolean success(int code, String msg, Object data) {
>         return flag;
>     }
>     public Boolean success(String msg, Object data) {
>         return flag;
>     }
>     public Boolean success(Object data) {
>         return flag;
>     }
>     public Boolean fail(int code, String msg, Object data) {
>         return flag;
>     }
>     public Boolean fail(String msg, Object data) {
>         return flag;
>     }
>     public Boolean fail(Object data) {
>         return flag;
>     }
> }
> ```

@snjeza @rgrunber After testing, it can meet the current usage scenarios.
