### ISSUE TITLE
"Classpath is incomplete" warning -- why not directly add current path into classpath?

### ISSUE THREAD

**Issue by zhangqunshi** [redhat-developer/vscode-java#235]
[provide a description of the issue]

##### Environment
- Operating System: windows7
- JDK version: 1.8
- Visual Studio Code version: 1.13.0
- Java extension version:

##### Steps To Reproduce
1. Open a single java file

##### Current Result
"Classpath is incomplete" warning

##### Expected Result
"Classpath is incomplete" warning don't show, directly add current directory into classpath.
Also i don't want to add a pom.xml or other build config file just only for one java file.
Hope one java file can directly compile and run it.

**Comment by fbricon** [comment]
You know you can choose to ignore the warning right (`Don't show again`)?
If you opened a folder containing multiple java files, each file, once opened is added to the same classpath.
