### ISSUE TITLE
Annotation processing regression

### ISSUE THREAD

**Issue by hwellmann** [redhat-developer/vscode-java#2353]
There is a regression in 1.4.0 for Maven projects that use source generation via annotation processing. The compiler run never finishes when there is a large number of generated files belonging to different packages. 

##### Environment
- Operating System: MacOS 10.15.7
- JDK version: OpenJDK 64-Bit Server VM Temurin-17.0.1+12
- Visual Studio Code version: 1.65.1
- Java extension version: 1.4.0

##### Steps To Reproduce
1. Import https://github.com/hwellmann/vscode-java-apt
2. Edit and save one of the `Somethingxxx.java` files. 

##### Current Result

Compilation never finishes. The following message keeps repeating:

```
Executing maven-processor-plugin:process
```

##### Expected Result

Compilation finishes successfully within seconds.

##### Additional Informations

Workaround: Downgrade to 1.3.0

```
code --install-extension redhat.java@1.3.0
```

**Comment by snjeza** [comment]
@hwellmann could you check https://github.com/snjeza/vscode-test/raw/master/java-1.5.1.vsix

**Comment by hwellmann** [comment]
Thanks, your patch seems to work for the sample project referenced above, but we still run into the same issue with our real (close source) project.

**Comment by snjeza** [comment]
@hwellmann could you, please, test https://github.com/snjeza/vscode-test/raw/master/java-1.5.2.vsix

**Comment by hwellmann** [comment]
This looks good now, even on our large project. Thank you!
