### ISSUE TITLE
[Formatter] Wrapping enum value declarations

### ISSUE THREAD

**Issue by mahyarmirrashed** [redhat-developer/vscode-java#2358]
Formatter will wrap enum values. This is, arguably, not good programming practice and makes the code harder to read. There should be an option to prevent this wrapping on the enums.

##### Environment
- Operating System: Fedora Linux 35 (KDE Plasma) x86_64
- JDK version: openjdk 17.0.2 2022-01-18
- Visual Studio Code version: 1.65.2
- Java extension version: Language support for Java ™ for Visual Studio Code v1.4.0

##### Steps To Reproduce
1. Set formatter to spaces and indent size of 2.
2. Type out the `enum` declaration in the **Current Result** section.
3. Format the document.

##### Current Result

![image](https://user-images.githubusercontent.com/59240843/158204858-347087ad-7aa7-4664-bcaf-6cdb1affc02b.png)

##### Expected Result

Only one enum constant should be present on each line.

![image](https://user-images.githubusercontent.com/59240843/158204803-90713505-e744-4ca2-8524-c561f6bed06c.png)

**Comment by rgrunber** [comment]
There's a setting for this.

```
$ cat .vscode/settings.json
{
	"java.settings.url": ".vscode/settings.prefs"
}

$ cat vscode/settings.prefs
org.eclipse.jdt.core.formatter.alignment_for_enum_constants=49
```

There's a lot of options that can be configured https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core/formatter/org/eclipse/jdt/core/formatter/DefaultCodeFormatterConstants.java .

![format-enum-constants](https://user-images.githubusercontent.com/1417342/158487333-da730272-256c-4b24-a762-919243184262.gif)

**Comment by rgrunber** [comment]
Closing this for now as I think the issue has been addressed. The formatter has many different options to allow users to customize how their sources are presented.

We're looking into a way to make the formatter options more discoverable.
