### ISSUE TITLE
Version 1.4.0 broke starting jhipster generated application

### ISSUE THREAD

**Issue by naris** [redhat-developer/vscode-java#2359]
As described in https://stackoverflow.com/questions/71473491/jhipster-java-spring-boot-app-wont-start-when-vs-code-is-running
if VS Code is running (with the vscode & the vscode-java extension enabled) then the java/jhipster/spring boot application either won't start or crashes due to unable to find the main class and/or some jar files. This does not happen with version 1.3.0 of this extension.

##### Environment
- Operating System: Windows 10 - Windows_NT x64 10.0.18363
- JDK version: 11
- Visual Studio Code version: 1.65.2
- Java extension version: 1.4.0
- Version: VS Code 1.65.2 (system setup)

##### Steps To Reproduce
1. Generate a JHipster application if you don't already have one.
2. Open a folder with a JHipster/Spring Boot application
3. Attempt too run the application with maven (./mvnw)either from within a VS Code Terminal session or a stand-alone Windows Terminal session
4. The application either won't start or crashes due to unable to find the main class and/or some jar files

[Please attach a sample project reproducing the error] I attempted to attach a zipped up sample project, but github won't allow it. All you need to doo is generate an application with JHipster (I chose SQL/H2 DB & angular), run it with ./mvnw from a windows terminal session to ensure it starts, then open it with VS Code and try to run it again.

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
WARN Settings pattern "keyboard.*" doesn't match any settings
workbench.desktop.main.js:3067 [c:\Users\mwilson\.vscode\extensions\ms-vscode-remote.vscode-remote-extensionpack-0.21.0]: property `extensionKind` can be defined only if property `main` is also defined.
_logMessageInConsole @ workbench.desktop.main.js:3067
workbench.desktop.main.js:3067 [redhat.vscode-commons]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:3067
workbench.desktop.main.js:3067 [redhat.vscode-yaml]: Cannot register 'redhat.telemetry.enabled'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:3067
workbench.desktop.main.js:3067 [vscjava.vscode-maven]: Cannot register 'maven.executable.path'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:3067
workbench.desktop.main.js:3067 [zobo.php-intellisense]: Cannot register 'php.memoryLimit'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:3067
workbench.desktop.main.js:3067 [zobo.php-intellisense]: Cannot register 'php.executablePath'. This property is already registered.
_logMessageInConsole @ workbench.desktop.main.js:3067
workbench.desktop.main.js:605  WARN Settings pattern "keyboard.*" doesn't match any settings
workbench.desktop.main.js:1940 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/mwilson/.vscode/extensions/pivotal.vscode-spring-boot-1.32.0/yaml-support/yaml.tmLanguage
register @ workbench.desktop.main.js:1940
workbench.desktop.main.js:1940 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Users/mwilson/.vscode/extensions/pivotal.vscode-spring-boot-1.32.0/yaml-support/yaml.tmLanguage.
New grammar file: file:///c%3A/Users/mwilson/.vscode/extensions/redhat.vscode-yaml-1.5.1/syntaxes/yaml.tmLanguage.json
register @ workbench.desktop.main.js:1940
workbench.desktop.main.js:1940 Overwriting grammar scope name to file mapping for scope source.scala.
Old grammar file: file:///c%3A/Users/mwilson/.vscode/extensions/lightbend.vscode-sbt-scala-0.2.4/syntaxes/Scala.tmLanguage.
New grammar file: file:///c%3A/Users/mwilson/.vscode/extensions/scala-lang.scala-0.5.5/syntaxes/Scala.tmLanguage.json
register @ workbench.desktop.main.js:1940
workbench.desktop.main.js:605  INFO Setting search error: XHR failed
bingsettingssearch.trafficmanager.net/api/Search:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
workbench.desktop.main.js:605  INFO Setting search error: XHR failed
bingsettingssearch.trafficmanager.net/api/Search:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
bingsettingssearch.trafficmanager.net/api/Search:1 Failed to load resource: net::ERR_CERT_DATE_INVALID
workbench.desktop.main.js:605  WARN Settings pattern "keyboard.*" doesn't match any settings
workbench.desktop.main.js:605   ERR spawn /opt/rh/rh-git29/root/usr/bin/git ENOENT: Error: spawn /opt/rh/rh-git29/root/usr/bin/git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
workbench.desktop.main.js:605  WARN Settings pattern "keyboard.*" doesn't match any settings
workbench.desktop.main.js:71 [Extension Host] 14 Mar 17:02:31 - Proposed protocol extensions loaded!
workbench.desktop.main.js:71 [Extension Host] rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
I @ workbench.desktop.main.js:71
workbench.desktop.main.js:71 [Extension Host] stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end	at Socket.Writable.write (internal/streams/writable.js:292:11)	at c:\Users\mwilson\.vscode\extensions\redhat.java-1.4.0\dist\extension.js:2:1014845	at new Promise (<anonymous>)	at c.write (c:\Users\mwilson\.vscode\extensions\redhat.java-1.4.0\dist\extension.js:2:1014763)	at _.doWrite (c:\Users\mwilson\.vscode\extensions\redhat.java-1.4.0\dist\extension.js:2:1004314)	at c:\Users\mwilson\.vscode\extensions\redhat.java-1.4.0\dist\extension.js:2:1004209
I @ workbench.desktop.main.js:71
workbench.desktop.main.js:2355 [[object Object]]write after end
$onExtensionRuntimeError @ workbench.desktop.main.js:2355
workbench.desktop.main.js:2355 Error [ERR_STREAM_WRITE_AFTER_END]: write after end
	at Socket.Writable.write (internal/streams/writable.js:292:11)
	at c:\Users\mwilson\.vscode\extensions\redhat.java-1.4.0\dist\extension.js:2:1014845
	at new Promise (<anonymous>)
	at c.write (c:\Users\mwilson\.vscode\extensions\redhat.java-1.4.0\dist\extension.js:2:1014763)
	at _.doWrite (c:\Users\mwilson\.vscode\extensions\redhat.java-1.4.0\dist\extension.js:2:1004314)
	at c:\Users\mwilson\.vscode\extensions\redhat.java-1.4.0\dist\extension.js:2:1004209
$onExtensionRuntimeError @ workbench.desktop.main.js:2355
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

##### Current Result
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[5,35] error: cannot find symbol
  symbol:   class User
  location: package com.epsilon.metadater.domain
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[6,40] error: cannot find symbol
  symbol:   class AdminUserDTO
  location: package com.epsilon.metadater.service.dto
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[7,40] error: cannot find symbol
  symbol:   class UserDTO
  location: package com.epsilon.metadater.service.dto
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[24,12] error: cannot find symbol
  symbol:   class UserMapper
  location: class UserMapperTest
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[25,12] error: cannot find symbol
  symbol:   class User
  location: class UserMapperTest
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[26,12] error: cannot find symbol
  symbol:   class AdminUserDTO
  location: class UserMapperTest
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[10,35] error: cannot find symbol
  symbol:   class Authority
  location: package com.epsilon.metadater.domain
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[16,43] error: cannot find symbol
  symbol:   class UserMapper
  location: package com.epsilon.metadater.service.mapper
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[68,12] error: cannot find symbol
  symbol:   class UserMapper
  location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[79,12] error: cannot find symbol
  symbol:   class User
  location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[93,18] error: cannot find symbol
  symbol:   class User
  location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[109,18] error: cannot find symbol
  symbol:   class User
  location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[586,52] error: cannot find symbol
  symbol:   class User
  location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\PublicUserResourceIT.java:[45,12] error: cannot find symbol
  symbol:   class User
  location: class PublicUserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefScriptVariablesResourceIT.java:[9,35] error: cannot find symbol
  symbol:   class GrefScriptVariables
  location: package com.epsilon.metadater.domain
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefScriptVariablesResourceIT.java:[51,12] error: cannot find symbol
  symbol:   class GrefScriptVariables
  location: class GrefScriptVariablesResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefScriptVariablesResourceIT.java:[59,18] error: cannot find symbol
  symbol:   class GrefScriptVariables
  location: class GrefScriptVariablesResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefScriptVariablesResourceIT.java:[70,18] error: cannot find symbol
  symbol:   class GrefScriptVariables
  location: class GrefScriptVariablesResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefNotUsedScriptsResourceIT.java:[9,35] error: cannot find symbol
  symbol:   class GrefNotUsedScripts
  location: package com.epsilon.metadater.domain
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefNotUsedScriptsResourceIT.java:[59,12] error: cannot find symbol
  symbol:   class GrefNotUsedScripts
  location: class GrefNotUsedScriptsResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefNotUsedScriptsResourceIT.java:[67,18] error: cannot find symbol
  symbol:   class GrefNotUsedScripts
  location: class GrefNotUsedScriptsResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefNotUsedScriptsResourceIT.java:[82,18] error: cannot find symbol
  symbol:   class GrefNotUsedScripts
  location: class GrefNotUsedScriptsResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\UserServiceIT.java:[59,12] error: cannot find symbol
  symbol:   class User
  location: class UserServiceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\config\NoOpMailConfiguration.java:[7,36] error: cannot find symbol
  symbol:   class MailService
  location: package com.epsilon.metadater.service
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\config\NoOpMailConfiguration.java:[14,18] error: cannot find symbol
  symbol:   class MailService
  location: class NoOpMailConfiguration
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\config\NoOpMailConfiguration.java:[22,11] error: cannot find symbol
  symbol:   class MailService
  location: class NoOpMailConfiguration
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\MailServiceIT.java:[65,12] error: cannot find symbol
  symbol:   class MailService
  location: class MailServiceIT
[INFO] 27 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.342 s
[INFO] Finished at: 2022-03-14T17:03:43-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project metadater: Compilation failure: Compilation failure: 
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[5,35] error: cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: package com.epsilon.metadater.domain
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[6,40] error: cannot find symbol
[ERROR]   symbol:   class AdminUserDTO
[ERROR]   location: package com.epsilon.metadater.service.dto
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[7,40] error: cannot find symbol
[ERROR]   symbol:   class UserDTO
[ERROR]   location: package com.epsilon.metadater.service.dto
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[24,12] error: cannot find symbol
[ERROR]   symbol:   class UserMapper
[ERROR]   location: class UserMapperTest
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[25,12] error: cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class UserMapperTest
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\mapper\UserMapperTest.java:[26,12] error: cannot find symbol
[ERROR]   symbol:   class AdminUserDTO
[ERROR]   location: class UserMapperTest
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[10,35] error: cannot find symbol
[ERROR]   symbol:   class Authority
[ERROR]   location: package com.epsilon.metadater.domain
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[16,43] error: cannot find symbol
[ERROR]   symbol:   class UserMapper
[ERROR]   location: package com.epsilon.metadater.service.mapper
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[68,12] error: cannot find symbol
[ERROR]   symbol:   class UserMapper
[ERROR]   location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[79,12] error: cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[93,18] error: cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[109,18] error: cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\UserResourceIT.java:[586,52] error: cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class UserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\PublicUserResourceIT.java:[45,12] error: cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class PublicUserResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefScriptVariablesResourceIT.java:[9,35] error: cannot find symbol
[ERROR]   symbol:   class GrefScriptVariables
[ERROR]   location: package com.epsilon.metadater.domain
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefScriptVariablesResourceIT.java:[51,12] error: cannot find symbol
[ERROR]   symbol:   class GrefScriptVariables
[ERROR]   location: class GrefScriptVariablesResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefScriptVariablesResourceIT.java:[59,18] error: cannot find symbol
[ERROR]   symbol:   class GrefScriptVariables
[ERROR]   location: class GrefScriptVariablesResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefScriptVariablesResourceIT.java:[70,18] error: cannot find symbol
[ERROR]   symbol:   class GrefScriptVariables
[ERROR]   location: class GrefScriptVariablesResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefNotUsedScriptsResourceIT.java:[9,35] error: cannot find symbol
[ERROR]   symbol:   class GrefNotUsedScripts
[ERROR]   location: package com.epsilon.metadater.domain
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefNotUsedScriptsResourceIT.java:[59,12] error: cannot find symbol
[ERROR]   symbol:   class GrefNotUsedScripts
[ERROR]   location: class GrefNotUsedScriptsResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefNotUsedScriptsResourceIT.java:[67,18] error: cannot find symbol
[ERROR]   symbol:   class GrefNotUsedScripts
[ERROR]   location: class GrefNotUsedScriptsResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\web\rest\GrefNotUsedScriptsResourceIT.java:[82,18] error: cannot find symbol
[ERROR]   symbol:   class GrefNotUsedScripts
[ERROR]   location: class GrefNotUsedScriptsResourceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\UserServiceIT.java:[59,12] error: cannot find symbol
[ERROR]   symbol:   class User
[ERROR]   location: class UserServiceIT
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\config\NoOpMailConfiguration.java:[7,36] error: cannot find symbol
[ERROR]   symbol:   class MailService
[ERROR]   location: package com.epsilon.metadater.service
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\config\NoOpMailConfiguration.java:[14,18] error: cannot find symbol
[ERROR]   symbol:   class MailService
[ERROR]   location: class NoOpMailConfiguration
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\config\NoOpMailConfiguration.java:[22,11] error: cannot find symbol
[ERROR]   symbol:   class MailService
[ERROR]   location: class NoOpMailConfiguration
[ERROR] C:\src\metadater\src\test\java\com\epsilon\metadater\service\MailServiceIT.java:[65,12] error: cannot find symbol
[ERROR]   symbol:   class MailService
[ERROR]   location: class MailServiceIT
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

##### Expected Result
Application starts without errors, as it does with version 1.3.0 of this extension.

**Comment by snjeza** [comment]
@naris could you try https://github.com/snjeza/vscode-test/raw/master/java-1.5.2.vsix ?

**Comment by naris** [comment]
@snjeza Yes that works. Thanks for the quick fix :)

**Comment by EmmyHermans** [comment]
We are having the same issue with our JHipster projects. I reverted the version back to 1.3.0. Hope this will be fixed soon with a new official version :) .

**Comment by snjeza** [comment]
@EmmyHermans you may want to take a look at https://github.com/redhat-developer/vscode-java/issues/2353#issuecomment-1071080426

**Comment by rgrunber** [comment]
Thanks @snjeza for tracking this down. Looks like you beat me to the fix by a few days :) Closing this for now as it will be fixed in our next release.

(and hopefully in the near future we can just provide insider builds of vscode-java)
