### ISSUE TITLE
Can't update this exension to 1.4.0 version

### ISSUE THREAD

**Issue by OOOHA** [redhat-developer/vscode-java#2361]
Issue Type: <b>Bug</b>

I can't update this extension via auto update or .vsix file.
I'v tried to unstall it and install it again.
It always stay at 1.3.0 version.
I can successfuly install the .vsix file but after the reload, it comes back to 1.3.0.

Extension version: 1.3.0
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|8.00GB (1.12GB free)|
|Process Argv|--crash-reporter-id 0391ab5f-ab72-484d-bb8e-2ee539c9edde|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflight:30433670
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvid1:30447480
pynewfile477:30450038

```

</details>

**Comment by rgrunber** [comment]
Is VS Code being access through a proxy or would something limit its ability to access external resources ? I did find https://github.com/microsoft/vscode/issues/71610 & https://github.com/microsoft/vscode/issues/84869 which seem similar.

**Comment by OOOHA** [comment]
I've searched for that kind of error but I think it's not the same type.
It's not working via a VPN too.
It can't install manually.
I've change the DNS to google's 8.8.8.8 but it's not working too so I Chang it back to default.
Since the setting is sync across my multiple computers, this is the only one got this error.

**Comment by OOOHA** [comment]
After updated to Mac OS 12.3.1 and VScode version 1.66.1(2022-04-06), it's fixed!
