### ISSUE TITLE
Add resource files in java projects view

### ISSUE THREAD

**Issue by raulvaldoleiros** [redhat-developer/vscode-java#2378]
It would be great if we can add files (property files,etc) in the java projects view. If this is already implemented can you share with me how to do it?

Thanks

**Comment by fbricon** [comment]
The Java project view is contributed by the [Project Manager for Java](https://github.com/microsoft/vscode-java-dependency/) extension. Please open a ticket in https://github.com/microsoft/vscode-java-dependency/issues
