### ISSUE TITLE
 java projects is in loading forever when I open this project in special directory

### ISSUE THREAD

**Issue by ahuigo** [redhat-developer/vscode-java#2379]
[provide a description of the issue]
 My java projects is in loading forever when I open this special project in special directory

##### Environment
```
macosx: 10.15.7
java: openjdk version "17.0.2" 2022-01-18
vscode: 1.65.2
java extensions:
 redhat.java@1.4.0
vscjava.vscode-java-debug@0.38.0
vscjava.vscode-java-dependency@0.19.0
vscjava.vscode-java-pack@0.22.1
vscjava.vscode-java-test@0.34.2
vscjava.vscode-maven@0.35.1
```

##### Steps To Reproduce
My project is very simple:  https://github.com/ahuigo/tos-java-sdk
1.  Open my project via terminal`code tos-java-sdk`
2.  The java projects is in loading forever, it can not work!!!
 ![image](https://user-images.githubusercontent.com/1781999/159974298-c47c1158-7086-463d-b5d8-821ed005471a.png)

Note:
1. I can only reproduce this problem on my Mac OSX in special directory which is ` /Users/ahui/www/devops/tos-java-sdk`.
2. If I move it to other place, and copy it back, e.g. `mv tos-java-sdk /tmp/tos-java-sdk && cp -r /tmp/tos-java-sdk/ ./tos-java-sdk && code ./tos-java-sdk`, it works!
3. If I rename directory name, e.g. `mv tos-java-sdk tos-java2 && code tos-java2`， it works!
4. **If I move it back to `mv tos-java2 /Users/ahui/www/devops/tos-java-sdk && code /Users/ahui/www/devops/tos-java-sdk`**, it **do not work!!!!!!!**
5. If I move this project to other directory,  for example, `mv tos-java-sdk /tmp/ && code /tmp/tos-java-sdk`, it works!
6. If I use git to clone it to the same directory `/Users/ahui/www/devops/tos-java-sdk`, it works!
e.g. `cd /Users/ahui/www/devops/ && git clone https://github.com/ahuigo/tos-java-sdk && code tos-java-sdk`, it works!

Why???

##### Current Result

I could not open my project, it is loading forever!
1. Language Support for java log [language-support-for-java.log](https://github.com/redhat-developer/vscode-java/files/8343943/language-support-for-java.log)
```
......
[Trace - 1:50:08 AM] Sending request 'shutdown - (1)'.
[Error - 1:50:10 AM] Connection to server is erroring. Shutting down server.
[Error - 1:50:10 AM] Connection to server got closed. Server will not be restarted.
```
2. 
[chrome-developer-console.log](https://github.com/redhat-developer/vscode-java/files/8344399/chrome-developer-console.log)
```
....
workbench.desktop.main.js:71 [Extension Host] (node:80407) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Electron --trace-deprecation ...` to show where the warning was created)
I @ workbench.desktop.main.js:71
workbench.desktop.main.js:71 [Extension Host] capabilities resolved immediately
workbench.desktop.main.js:605   ERR [Extension Host] Error: Unexpected SIGPIPE
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:1:370)
    at process.emit (events.js:315:20)
workbench.desktop.main.js:71 [Extension Host] Error: Unexpected SIGPIPE    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:1:370)    at process.emit (events.js:315:20)
I @ workbench.desktop.main.js:71
workbench.desktop.main.js:71 [Extension Host] rejected promise not handled within 1 second: Error: write EPIPE
I @ workbench.desktop.main.js:71
workbench.desktop.main.js:71 [Extension Host] stack trace: Error: write EPIPE    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
I @ workbench.desktop.main.js:71
workbench.desktop.main.js:605   ERR write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
....
```

##### Expected Result
Open project my java project successfully!

**Comment by dgh1000** [comment]
For a couple weeks the Java extension has been misbehaving for me. It spins forever. There is no "run" or "debug" button. If I create a new window and add a single folder with Java projects to it, it seems to work for a short time. Eventually the "run" and "debug" buttons go away. I'm not sure what action precedes this.

**Comment by snjeza** [comment]
@ahuigo @dgh1000 You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/2353#issuecomment-1071080426

**Comment by snjeza** [comment]
> If I move it back to mv tos-java2 /Users/ahui/www/devops/tos-java-sdk && code /Users/ahui/www/devops/tos-java-sdk, it do not work!!!!!!!

@ahuigo Could you try the following:

```
$ mv tos-java2 /Users/ahui/www/devops/tos-java-sdk
$ rm -rf ~/.config/Code/User/workspaceStorage/
$ code /Users/ahui/www/devops/tos-java-sdk
```
Could you reproduce the issue with the following settings:
```
"java.import.generatesMetadataFilesAtProjectRoot": true,
```

**Comment by dgh1000** [comment]
> @ahuigo @dgh1000 You may want to take a look at [#2353 (comment)](https://github.com/redhat-developer/vscode-java/issues/2353#issuecomment-1071080426)

Thank you. However I don't see the relevance, as I'm not  using Maven. Is there something I'm missing?

**Comment by ahuigo** [comment]
> > @ahuigo @dgh1000 You may want to take a look at [#2353 (comment)](https://github.com/redhat-developer/vscode-java/issues/2353#issuecomment-1071080426)
> 
> Thank you. However I don't see the relevance, as I'm not using Maven. Is there something I'm missing?

I've tested https://download.jboss.org/jbosstools/jdt.ls/staging/java-1.5.0-559/java-1.5.0-559.vsix via `code --install-extension ~/Downloads/java-1.5.0-559.vsix`
It still do not works.

**Comment by ahuigo** [comment]
> @ahuigo @dgh1000 You may want to take a look at [#2353 (comment)](https://github.com/redhat-developer/vscode-java/issues/2353#issuecomment-1071080426)


## First
 I've tested https://download.jboss.org/jbosstools/jdt.ls/staging/java-1.5.0-559/java-1.5.0-559.vsix via code --install-extension ~/Downloads/java-1.5.0-559.vsix
It still do not works.

## Then
I tried the following steps:
1. Set `"java.import.generatesMetadataFilesAtProjectRoot": true` in vscode
2. Execute these commands in shell, It finally works!
```
$ mv tos-java2 /Users/ahui/www/devops/tos-java-sdk
$ rm -r ~/.config/Code/User/workspaceStorage/
rm: /Users/ahui/.config/Code/User/workspaceStorage/: No such file or directory (**I don't have this directory**)
$ code /Users/ahui/www/devops/tos-java-sdk
```

3. Finally, **I removed `"java.import.generatesMetadataFilesAtProjectRoot": true`, it still works!**

**Comment by snjeza** [comment]
> $ rm -r ~/.config/Code/User/workspaceStorage/
rm: /Users/ahui/.config/Code/User/workspaceStorage/: No such file or directory (**I don't have this directory**)

@ahuigo You may want to take a look at [Clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)

**Comment by snjeza** [comment]
> Thank you. However I don't see the relevance, as I'm not using Maven. Is there something I'm missing?

See https://github.com/redhat-developer/vscode-java/issues/2360#issuecomment-1073940973
https://bugs.eclipse.org/bugs/show_bug.cgi?id=578640 is not maven specific.

**Comment by EvanGertis** [comment]
This is still a problem for me.

**Comment by ahuigo** [comment]
@EvanGertis 
Have you tried this? https://github.com/redhat-developer/vscode-java/issues/2379#issuecomment-1078723541
> 1. Install the latest java extension.
> 2. Set `"java.import.generatesMetadataFilesAtProjectRoot": true` in vscode
