### ISSUE TITLE
"Java: Clean Java Language Server Workspace" fails on Debian

### ISSUE THREAD

**Issue by Nightenom** [redhat-developer/vscode-java#2385]
Calling command "Java: Clean Java Language Server Workspace" results in error after window reload. The extension then looks like it did not clean itself up. Reproducibility 99% - the 1% stands for when the extension itself crash before, then I can clean without error.

##### Environment
- Operating System: `Debian GNU/Linux 11 (bullseye)`
- uname -a: `Linux user 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`
- JDK version: `Java: 17.0.2 JVM: 17.0.2+8(Eclipse Adoptium) Arch: amd64`
- Visual Studio Code version: 1.65.2
- Java extension version: v1.4.0

##### Steps To Reproduce
My app is not some kind of special setup. Just simple gradle project on J17 without modules. Publishing-stripped build.gradle attached with logs. Wrapper/Gradle version `7.4.1-all`

1. Press F1 and select "Java: Clean Java Language Server Workspace"
2. Watch the vscode window reload
3. Error message appears

[logs](https://gist.github.com/Nightenom/ad852ae779e185e8b5d140e0a96199eb)
The logs probably also contains errors when I try to rename variable in lambda with code-block.

##### Current Result

Error message <https://gist.github.com/Nightenom/ad852ae779e185e8b5d140e0a96199eb#file-error-message>

##### Expected Result

No error message

##### Additional Informations

Possibly does not happen on Windows with same project, but have not try yet

**Comment by rgrunber** [comment]
What happens if you remove `/media/user/progs/apps/linux64/vscode/data/user-data/User/workspaceStorage/cde71673b983c4eb779005d3a8ee6a2e/` and try the same thing again (ie. loading the project, maybe cleaning the workspace, etc.) ? Does the problem still occur ?

**Comment by snjeza** [comment]
Related issue - https://github.com/redhat-developer/vscode-java/issues/2471

**Comment by Nightenom** [comment]
> What happens if you remove `/media/user/progs/apps/linux64/vscode/data/user-data/User/workspaceStorage/cde71673b983c4eb779005d3a8ee6a2e/` and try the same thing again (ie. loading the project, maybe cleaning the workspace, etc.) ? Does the problem still occur ?

Obviously I can achieve cleaning by removing that directory, although the issue remains even on fresh new setup.

> Related issue - #2471

Seems true, will wait for update

**Comment by snjeza** [comment]
@Nightenom Could you, please, test with https://github.com/snjeza/vscode-test/raw/master/java-1.6.7.vsix

**Comment by Nightenom** [comment]
Seems to be fixed at 1.7.0 which contains previously mentioned fix
