### ISSUE TITLE
No refactorings available

### ISSUE THREAD

**Issue by StephaneAdeso** [redhat-developer/vscode-java#2389]
I have no idea why but in 80% of the Java files I open, when I try to do things like extract a method or a variable, I don't have refactoring available. I almost always get the "no refactorings available" message.
This happens to me both in Spring applications and in single dummy Java files. Could someone tell me what is the reason or what are the requirements for this to always work? I have already consulted[ this microsoft documentation](https://code.visualstudio.com/docs/java/java-refactoring), but it has not helped me at all. Also searched the issues without any success.

##### Environment
- Operating System: windows 11 x64
- JDK version: 17.0.2
- Visual Studio Code version: 1.66
- Java extension version: 0.22.2

**Comment by snjeza** [comment]
@Osolemio44 could you provide a sample project reproducing the error?

**Comment by Osolemio44** [comment]
Anyway, even if it doesn't work for me, I think this functionality should be present and enabled by default in VSCode.  as in all other IDEs

**Comment by snjeza** [comment]
> no sorry. it's a spring boot project from my work and i can't share it.

@Osolemio44 could you show any example?

**Comment by rgrunber** [comment]
A refactoring ( `Refactor...` menu items or default keybinding `<Ctrl>+<Shift>+R`)  request should be pretty much the same as a regular code action request except the accepted actions are restricted specifically to refactorings :

```
Sending request 'textDocument/codeAction - (245)'.
Params: {
    "textDocument": {
        ...
    },
    "range": {
        ...
    },
    "context": {
        "diagnostics": [],
        "only": [
            "refactor"
        ]
    }
}
```

Would you be able to go into your command palette after freshly importing the project and activating `Java: Open Java Extension Log File` ? If you could post the log that would be ideal.

Another thing to try is the `Java: Open Java Language Server Log File` and check to see if there's any exceptions thrown or errors of any kind.
