### ISSUE TITLE
Can't figure out how to link source jars/zips to a project

### ISSUE THREAD

**Issue by danschultequb** [redhat-developer/vscode-java#2391]
##### Environment
- Operating System: Windows 11
- JDK version: 17.0.1
- Visual Studio Code version: 1.66.0
- Java extension version: 1.4.0

##### Steps To Reproduce
1. Unzip the provided [example.zip](https://github.com/redhat-developer/vscode-java/files/8420385/example.zip) file.
2. Open the example folder in VS Code.
3. Open the Source.java file.
4. Attempt to go to the definition of the InMemoryCharacterToByteStream type.

##### Current Result

The disassembled class file is always shown, which doesn't provide any more information than autocompletion does.

##### Expected Result

Since the source files are right next to the jar file, I'd hope there'd be a way to tell the Java extension where to find those source files. I haven't found any documentation online on how to do that, unfortunately. I'd consider this issue resolved if either the extension could find those sources automatically, but honestly I'd prefer to just have some documentation on how to reference source jars/zips so that the extension doesn't have to do unnecessary work.

##### Additional information

I've attached the requested logs in the "logs" folder of the [example.zip](https://github.com/redhat-developer/vscode-java/files/8420385/example.zip) file.

**Comment by danschultequb** [comment]
That did the trick. I'll close this issue, but before I do I have to ask: is this documented anywhere, or was I just supposed to know about the magical naming convention?

**Comment by fbricon** [comment]
I thought it was documented but I couldn't find it, so we need to fix this.

**Comment by danschultequb** [comment]
Phew! I was going crazy trying to figure out it and it felt like the sort
of thing that would've been documented. I'm glad it wasn't just me missing
something obvious. 🙂 Thanks for looking into it!

**Comment by robaho** [comment]
This needs work. You should be able to configure source jars path(s) - it shouldn't have to be in the same directory.
