### ISSUE TITLE
module-info.java is not supported

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2396]
Could not build module project like module-info.java

##### Environment
- Operating System: windows 11
- JDK version: 17
- Visual Studio Code version: 1.66.1
- Java extension version:v1.4.0

##### Steps To Reproduce
1. please read doc <https://docs.gradle.org/current/samples/sample_java_modules_multi_project.html>
2. download  https://docs.gradle.org/current/samples/zips/sample_java_modules_multi_project-groovy-dsl.zip
3. unzip sample_java_modules_multi_project-groovy-dsl.zip
4. open sample_java_modules_multi_project-groovy-dsl by vscode

[Please attach a sample project reproducing the error]
[client.log.2022-04-08.zip](https://github.com/redhat-developer/vscode-java/files/8451787/client.log.2022-04-08.zip)
[jdt_ws.log](https://github.com/redhat-developer/vscode-java/files/8451793/jdt_ws.log)

##### Current Result
build error!

**Screenshots**
![image](https://user-images.githubusercontent.com/63572041/162350486-cc8c0906-2751-4fa6-a74e-3de4b69d4def.png)

##### Expected Result
Build succeeded

##### Additional Informations
IntelliJ IDEA 2021.3.4 (Edu) can build success!

**Comment by snjeza** [comment]
@mozhuanzuojing could you try to set the following property:

```
"java.import.gradle.java.home": "C:\\Program Files\\RedHat\\java-17-openjdk-17.0.2.0.8-1",
```

**Comment by mozhuanzuojing** [comment]
@snjeza this is my settings.json

```json
{
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "C:/Program Files/RedHat/java-1.8.0-openjdk-1.8.0.322-2"
        },
        {
            "name": "JavaSE-17",
            "path": "C:/Program Files/RedHat/java-17-openjdk-17.0.2.0.8-1",
            "default": true
        }
    ],
    "java.jdt.ls.java.home": "C:/Program Files/RedHat/java-17-openjdk-17.0.2.0.8-1",
    "java.import.gradle.java.home": "C:/Program Files/RedHat/java-17-openjdk-17.0.2.0.8-1",
    "spring-boot.ls.java.home": "C:/Program Files/RedHat/java-17-openjdk-17.0.2.0.8-1",
    "xml.java.home": "C:/Program Files/RedHat/java-17-openjdk-17.0.2.0.8-1",
}
```

**Comment by snjeza** [comment]
@mozhuanzuojing could you show your .settings/org.eclipse.buildship.core.prefs?

**Comment by mozhuanzuojing** [comment]
@snjeza

> .settings/org.eclipse.buildship.core.prefs  when `"java.import.generatesMetadataFilesAtProjectRoot": true`
```properties
arguments=
auto.sync=false
build.scans.enabled=false
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=
eclipse.preferences.version=1
gradle.user.home=D\:/java/gradlehome
java.home=C\:/Program Files/RedHat/java-17-openjdk-17.0.1.0.12-1
jvm.arguments=
offline.mode=false
override.workspace.settings=true
show.console.view=true
show.executions.view=true


```

[org.eclipse.jdt.core.prefs](https://github.com/redhat-developer/vscode-java/files/8456015/org.eclipse.jdt.core.zip)  when `"java.settings.url": "file:///C:/Users/Administrator/AppData/Roaming/Code/User/org.eclipse.jdt.core.prefs"`

**Comment by mozhuanzuojing** [comment]
@snjeza After I fixed the parameters of `gradle.properties`, the compilation result is much better than before. Although there are still a few errors

> D:/java/gradlehome/gradle.properties  when `"java.import.gradle.user.home": "D:/java/gradlehome"`
```properties
# 开启线程守护，第一次编译时开线程，之后就不会再开了
org.gradle.daemon=true
# org.gradle.java.home=C:/Program Files/RedHat/java-17-openjdk-17.0.2.0.8-1
# 检查虚拟内存必须是物理内存的2倍以上并且虚拟内存所在磁盘要有足够的空间，如果物理内存小于16G，这里最小堆必须是512m左右，否则会启动失败
org.gradle.jvmargs= --add-modules ALL-MODULE-PATH --add-opens jdk.jdeps/com.sun.tools.jdeps=ALL-UNNAMED --add-opens jdk.jdeps/com.sun.tools=ALL-UNNAMED -Dsun.jnu.encoding=utf8 -Dfile.encoding=utf8  -XX:+UseShenandoahGC -Xms1g -Xmx8g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
# 开启并行编译
org.gradle.parallel=true
# 启用新的孵化模式
org.gradle.configureondemand=true
# https://docs.gradle.org/current/userguide/build_environment.html#build_environment
org.gradle.caching=true
# redhat-java插件的文件监听和gradle的冲突，必须关闭gradle文件监听
org.gradle.vfs.watch=false
org.gradle.vfs.verbose=false
# 关闭依赖验证 see https://docs.gradle.org/current/userguide/dependency_verification.html#sec:disabling-verification
org.gradle.dependency.verification=off
```

## Current situation
> build success! but `module-info.java`  have syntax error.

![image](https://user-images.githubusercontent.com/63572041/162577262-6fcc7bc2-d97e-46d9-9a0b-e3447d2fc878.png)

**Comment by snjeza** [comment]
@mozhuanzuojing could you try the following:

utilities/build.gradle
```
plugins {
    id 'myproject.java-conventions'
    id 'java-library'
    id 'eclipse'
}

dependencies {
    api project(':list')
}

eclipse {
    classpath {
        containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
        file.whenMerged { cp ->
            def entries = cp.entries;
            entries.findAll { it.properties.kind.equals('lib') && !it.properties.path.contains("junit") }.each {
                it.entryAttributes['module'] = 'true'
            }
            entries.findAll { it.properties.path.startsWith('org.eclipse.jdt.launching.JRE_CONTAINER') }.each {
                it.entryAttributes['module'] = 'true'
            }
            def proj = new org.gradle.plugins.ide.eclipse.model.ProjectDependency('/list')
            proj.entryAttributes['module'] = 'true'
            entries.add(proj)
        } 
    }
}
```
application/build.gradle
```
plugins {
    id 'myproject.java-conventions'
    id 'application'
    id 'eclipse'
}

dependencies {
    implementation project(':utilities')
}

application {
    mainModule = 'org.gradle.sample.app'
    mainClass = 'org.gradle.sample.app.Main'
}

eclipse {
    classpath {
        containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
        file.whenMerged { cp ->
            def entries = cp.entries;
            entries.findAll { it.properties.kind.equals('lib') && !it.properties.path.contains("junit") }.each {
                it.entryAttributes['module'] = 'true'
            }
            entries.findAll { it.properties.path.startsWith('org.eclipse.jdt.launching.JRE_CONTAINER') }.each {
                it.entryAttributes['module'] = 'true'
            }
            def proj = new org.gradle.plugins.ide.eclipse.model.ProjectDependency('/list')
            proj.entryAttributes['module'] = 'true'
            entries.add(proj)
            proj = new org.gradle.plugins.ide.eclipse.model.ProjectDependency('/utilities')
            proj.entryAttributes['module'] = 'true'
            entries.add(proj)
        } 
    }
}
```

**Comment by mozhuanzuojing** [comment]
@snjeza I found that the problem is with the version of JDK, now it is JavaSE-1.8
The correct version should be 17
But no matter how I modify it, I can't change the version of the project to 17

**Comment by mozhuanzuojing** [comment]
> @mozhuanzuojing could you try the following:
> 
> utilities/build.gradle
> 
> ```
> plugins {
>     id 'myproject.java-conventions'
>     id 'java-library'
>     id 'eclipse'
> }
> 
> dependencies {
>     api project(':list')
> }
> 
> eclipse {
>     classpath {
>         containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
>         file.whenMerged { cp ->
>             def entries = cp.entries;
>             entries.findAll { it.properties.kind.equals('lib') && !it.properties.path.contains("junit") }.each {
>                 it.entryAttributes['module'] = 'true'
>             }
>             entries.findAll { it.properties.path.startsWith('org.eclipse.jdt.launching.JRE_CONTAINER') }.each {
>                 it.entryAttributes['module'] = 'true'
>             }
>             def proj = new org.gradle.plugins.ide.eclipse.model.ProjectDependency('/list')
>             proj.entryAttributes['module'] = 'true'
>             entries.add(proj)
>         } 
>     }
> }
> ```
> 
> application/build.gradle
> 
> ```
> plugins {
>     id 'myproject.java-conventions'
>     id 'application'
>     id 'eclipse'
> }
> 
> dependencies {
>     implementation project(':utilities')
> }
> 
> application {
>     mainModule = 'org.gradle.sample.app'
>     mainClass = 'org.gradle.sample.app.Main'
> }
> 
> eclipse {
>     classpath {
>         containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
>         file.whenMerged { cp ->
>             def entries = cp.entries;
>             entries.findAll { it.properties.kind.equals('lib') && !it.properties.path.contains("junit") }.each {
>                 it.entryAttributes['module'] = 'true'
>             }
>             entries.findAll { it.properties.path.startsWith('org.eclipse.jdt.launching.JRE_CONTAINER') }.each {
>                 it.entryAttributes['module'] = 'true'
>             }
>             def proj = new org.gradle.plugins.ide.eclipse.model.ProjectDependency('/list')
>             proj.entryAttributes['module'] = 'true'
>             entries.add(proj)
>             proj = new org.gradle.plugins.ide.eclipse.model.ProjectDependency('/utilities')
>             proj.entryAttributes['module'] = 'true'
>             entries.add(proj)
>         } 
>     }
> }
> ```

Tried this configuration, there is no change, there is still an error in module-info.java

**Comment by mozhuanzuojing** [comment]
@snjeza JDK version is always 1.8

![image](https://user-images.githubusercontent.com/63572041/162620321-a461411b-fcf7-4253-bae5-4d15cf768483.png)

**Comment by snjeza** [comment]
@mozhuanzuojing could you try 
[dsl.zip](https://github.com/redhat-developer/vscode-java/files/8459638/dsl.zip)

![dsl](https://user-images.githubusercontent.com/388609/162633272-61ce793d-b6fd-4c23-a70f-48bf2ed01358.gif)

**Comment by mozhuanzuojing** [comment]
@snjeza I use your example and have no problems. grateful.
