### ISSUE TITLE
Code completion "import java.u|" inserts repeated text "import java.java.util.*"

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#2406]
When using code completion on "import java.u|", it inserts the text as "import java.java.util.*".

![image](https://user-images.githubusercontent.com/14052197/163143594-8ca283d8-edb8-49ef-a3af-538155e3c6f5.png)

// @jdneo

**Comment by jdneo** [comment]
I was thinking that there is no harm to make insert/replace different for all kinds of proposals. Seems that I should not change the previous logic: https://github.com/eclipse/eclipse.jdt.ls/blob/c5cdd8f4c44b3f78160fec686603e5ef72b2ba92/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java#L164

**Comment by jdneo** [comment]
Wait...

I could not repro in Stable VS Code. But it's reproducible in Insider. Looks like it's a VS Code insider bug?

**Comment by testforstephen** [comment]
This has been fixed in IntelliCode, closing it.
