### ISSUE TITLE
Unexpected 'Project xxx has no explicit encoding set' warnings

### ISSUE THREAD

**Issue by a01fe** [redhat-developer/vscode-java#2416]
In a Gradle project with subprojects, each subproject directory has a " Project 'xxx' has no explicit encoding set" warning. This appears to have started with version 1.5.0 of the extension.

##### Environment
- Operating System: macOS 12.3.1
- JDK version: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)
- Visual Studio Code version: Version: 1.67.0-insider Commit: a9288be67bab4e9c4dbe62207f01fafc2bdaadcb
- Java extension version: 1.5.0

##### Steps To Reproduce
1. Create basic project with Groovy DSL with `gradle init`
2. Add empty subproject directory in project
3. Add subproject directory to `include` in `settings.gradle`
4. Open project in vscode

[encoding-test.zip](https://github.com/redhat-developer/vscode-java/files/8497242/encoding-test.zip)

##### Current Result

Subproject directory has "Project 'xxx' has no explicit encoding set" warning.

##### Expected Result

No warnings.

**Comment by snjeza** [comment]
Related Eclipse bug - https://bugs.eclipse.org/bugs/show_bug.cgi?id=479451

**Comment by EccentricVamp** [comment]
This warning is appearing for me as well

**Environment**
* Operating System: Windows 10.0.19044
* JDK: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)
* Visual Studio Code: 1.66.2
* Java extension: 1.5.0

**Comment by mishi321** [comment]
Similar gradle multi modules, waiting for solution.

**Comment by biuniun** [comment]
In my case, the issue can be solved by cleaning the workspace of the Java Language Server.

**Comment by snjeza** [comment]
A workaround:
You can create the <your_project>/.settings/org.eclipse.core.resources.prefs file with the following contents:

```
eclipse.preferences.version=1
encoding/<project>=utf8
```

**Comment by jmihalich** [comment]
Verified the above workaround fixes the issue, until we get the patch.

**Comment by snjeza** [comment]
You can check https://github.com/snjeza/vscode-test/raw/master/java-1.5.7.vsix
You can test the `java.project.encoding` property - https://github.com/redhat-developer/vscode-java/pull/2418/commits/74ab5c403fafd66c35ca5f2f5cd66e72ec35a0fa#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R204

**Comment by fbricon** [comment]
reopening as the fix hasn't been merged yet.

**Comment by HaraldKorneliussen** [comment]
The suggested workaround causes a followup problem:

`Missing Gradle project configuration file: .settings/org.eclipse.buildship.core.prefs`

**Comment by snjeza** [comment]
> The suggested workaround causes a followup problem:

@HaraldKorneliussen could you try to clean your workspace [Clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory) ?

**Comment by michaelmior** [comment]
@snjeza I tried the workaround and had the same problem as @HaraldKorneliussen. Cleaning the workspace directory did not solve the issue for me.

**Comment by Brahvim** [comment]
Hi there. Sorry to ping for a seemingly closed issue, but this problem seems to be back for those using the default build system. ...Am I doing something wrong?:

![image](https://github.com/redhat-developer/vscode-java/assets/69293652/b7a10fe7-c23d-48a2-afba-8d21b1724ac7)
