### ISSUE TITLE
jvm crash log, only for recording

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2419]
At work, vscode crashes, and there is only one log. Time: Tue Apr 19 14:46:37 2022

This problem can be tracked for a long time.

##### Environment
- Operating System:windows10
- JDK version:17
- Visual Studio Code version:1.66.2
- Java extension version:1.5.0

[hs_err_pid25356.log](https://github.com/redhat-developer/vscode-java/files/8512525/hs_err_pid25356.log)

##### Additional Informations
Because these days, there are frequent crashes, so I leave traces here.

**Comment by mozhuanzuojing** [comment]
add another log
[hs_err_pid66548.log](https://github.com/redhat-developer/vscode-java/files/8530188/hs_err_pid66548.log)

**Comment by rgrunber** [comment]
`EXCEPTION_ACCESS_VIOLATION` is what stands out. A quick search shows it could be a bug in the JVM itself. Maybe even specific to Windows ? https://ugetfix.com/ask/how-to-fix-exception-access-violation-error-on-windows-10/ .

What happens if you try a different JVM ?

**Comment by mozhuanzuojing** [comment]
@rgrunber I just switched to adoptium Openjdk17, and I guess it will be a while to test.
