### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by yuchuga** [redhat-developer/vscode-java#2428]
- Issue Type: `Bug`
- Extension Name: `java`
- Extension Version: `1.5.0`
- OS Version: `Darwin arm64 20.4.0`
- VS Code version: `1.67.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

Project 'Java_de230e2c' has no explicit encoding set

**Comment by snjeza** [comment]
A duplicate of https://github.com/redhat-developer/vscode-java/issues/2416
