### ISSUE TITLE
"Manage Workspace Trust" doesn't work

### ISSUE THREAD

**Issue by CsCherrYY** [redhat-developer/vscode-java#2431]
##### Steps To Reproduce
1. Open an untrusted workspace
2. Click "Load projects" in the language status item
3. In the notification, clicking "Manage Workspace Trust" will not open a workspace trust tab.

![image](https://user-images.githubusercontent.com/45906942/165033807-3a7c4d2b-78b7-412c-84c9-a6b6b27b2d47.png)

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
clicking "Manage Workspace Trust" will not open a workspace trust tab.
##### Expected Result
clicking "Manage Workspace Trust" will open a workspace trust tab.

**Comment by rgrunber** [comment]
Yup, `Error: command 'workbench.action.manageTrust' not found`
