### ISSUE TITLE
Mac OS X  after 1.4.0 quick fix "Create local variable" not work

### ISSUE THREAD

**Issue by cenggel** [redhat-developer/vscode-java#2437]
[provide a description of the issue]

##### Environment
- Operating System: Darwin x64 20.6.0
- JDK version: java version "16.0.1" 2021-04-20
- Visual Studio Code version: Version: 1.66.2 (Universal)
- Java extension version: 1.5.0

after 1.4.0 quick fix  Create local variable not work ,after select "Create local variable" happened  nothing.  1.3.0  worked well.

##### extension log

{
  message: '[Error - 3:28:23 PM] Request codeAction/resolve failed.',
  level: 'info',
  timestamp: '2022-04-27 15:28:23.696'
}
{
  message: '  Message: Internal error.\n' +
    '  Code: -32603 \n' +
    'java.util.concurrent.CompletionException: java.lang.VerifyError: Bad type on operand stack\n' +
    'Exception Details:\n' +
    '  Location:\n' +
    '    org/eclipse/jdt/internal/corext/dom/LinkedNodeFinder.findByNode(Lorg/eclipse/jdt/core/dom/ASTNode;Lorg/eclipse/jdt/core/dom/Name;)[Lorg/eclipse/jdt/core/dom/Name; @11: invokestatic\n' +
    '  Reason:\n' +
    "    Type '[Lorg/eclipse/jdt/core/dom/Name;' (current frame, stack[0]) is not assignable to '[Lorg/eclipse/jdt/core/dom/SimpleName;'\n" +
    '  Current Frame:\n' +
    '    bci: @11\n' +
    '    flags: { }\n' +
    "    locals: { 'org/eclipse/jdt/core/dom/ASTNode', 'org/eclipse/jdt/core/dom/Name', '[Lorg/eclipse/jdt/core/dom/Name;' }\n" +
    "    stack: { '[Lorg/eclipse/jdt/core/dom/Name;' }\n" +
    '  Bytecode:\n' +
    '    0000000: 2a2b b801 044d 2cc6 0008 2cb8 016b b02b\n' +
    '    0000010: b601 06b6 00f6 3e1d 101e 9f00 0f1d 100a\n' +
    '    0000020: 9f00 091d 1012 a000 32bb 00d0 59b7 00d2\n' +
    '    0000030: 3a04 bb01 0959 2b19 04b7 010b 3a05 2a19\n' +
    '    0000040: 05b6 00d8 1904 1904 b600 dcbd 0107 b600\n' +
    '    0000050: dfc0 010e b801 6bb0 04bd 0107 5903 2b53\n' +
    '    0000060: b801 6bb0                              \n' +
    '  Stackmap Table:\n' +
    '    append_frame(@15,Object[#270])\n' +
    '    append_frame(@41,Integer)\n' +
    '    same_frame(@88)\n' +
    '\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)\n' +
    '\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)\n' +
    'Caused by: java.lang.VerifyError: Bad type on operand stack\n' +
    'Exception Details:\n' +
    '  Location:\n' +
    '    org/eclipse/jdt/internal/corext/dom/LinkedNodeFinder.findByNode(Lorg/eclipse/jdt/core/dom/ASTNode;Lorg/eclipse/jdt/core/dom/Name;)[Lorg/eclipse/jdt/core/dom/Name; @11: invokestatic\n' +
    '  Reason:\n' +
    "    Type '[Lorg/eclipse/jdt/core/dom/Name;' (current frame, stack[0]) is not assignable to '[Lorg/eclipse/jdt/core/dom/SimpleName;'\n" +
    '  Current Frame:\n' +
    '    bci: @11\n' +
    '    flags: { }\n' +
    "    locals: { 'org/eclipse/jdt/core/dom/ASTNode', 'org/eclipse/jdt/core/dom/Name', '[Lorg/eclipse/jdt/core/dom/Name;' }\n" +
    "    stack: { '[Lorg/eclipse/jdt/core/dom/Name;' }\n" +
    '  Bytecode:\n' +
    '    0000000: 2a2b b801 044d 2cc6 0008 2cb8 016b b02b\n' +
    '    0000010: b601 06b6 00f6 3e1d 101e 9f00 0f1d 100a\n' +
    '    0000020: 9f00 091d 1012 a000 32bb 00d0 59b7 00d2\n' +
    '    0000030: 3a04 bb01 0959 2b19 04b7 010b 3a05 2a19\n' +
    '    0000040: 05b6 00d8 1904 1904 b600 dcbd 0107 b600\n' +
    '    0000050: dfc0 010e b801 6bb0 04bd 0107 5903 2b53\n' +
    '    0000060: b801 6bb0                              \n' +
    '  Stackmap Table:\n' +
    '    append_frame(@15,Object[#270])\n' +
    '    append_frame(@41,Integer)\n' +
    '    same_frame(@88)\n' +
    '\n' +
    '\tat org.eclipse.jdt.ls.core.internal.corrections.proposals.NewVariableCorrectionProposal.getAllReferences(NewVariableCorrectionProposal.java:329)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.corrections.proposals.NewVariableCorrectionProposal.doAddLocal(NewVariableCorrectionProposal.java:219)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.corrections.proposals.NewVariableCorrectionProposal.getRewrite(NewVariableCorrectionProposal.java:113)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.corrections.proposals.ASTRewriteCorrectionProposal.addEdits(ASTRewriteCorrectionProposal.java:89)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.corrections.proposals.CUCorrectionProposal.createTextChange(CUCorrectionProposal.java:109)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.corrections.proposals.CUCorrectionProposal.createChange(CUCorrectionProposal.java:115)\n' +
    '\tat org.eclipse.jdt.core.manipulation.ChangeCorrectionProposalCore.getChange(ChangeCorrectionProposalCore.java:150)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.CodeActionResolveHandler.resolve(CodeActionResolveHandler.java:46)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$16(JDTLanguageServer.java:683)\n' +
    '\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)\n' +
    '\t... 7 more\n',
  level: 'info',
  timestamp: '2022-04-27 15:28:23.696'
}

**Comment by snjeza** [comment]
@cenggel could you try lombok 1.18.24? You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/2417#issuecomment-1101910372

**Comment by cenggel** [comment]
@snjeza thanks . after replace to  lombok 1.18.24 "Create local variable"  works .
