### ISSUE TITLE
Java 11 or more recent is required to run dispalys every time I start VSC

### ISSUE THREAD

**Issue by eliassal** [redhat-developer/vscode-java#2445]
Since a couple of weekes I started getting an alert as indicated in the title. I downloaded last jdk, pointed VSC config to the new one but still getting the alert (snapshot hereunder).
Here is what I have in my settings.json

`"java.jdt.ls.java.home":"C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.9.101-hotspot\\bin\\java.exe",`

Really don't understand why this alert is popping again and again , can you please tell me what is needed to do?

##### Environment
- Operating System: Windows_NT x64 10.0.19044
- JDK version: 11
- Visual Studio Code version: 1.67.0
- Java extension version: v0.22.4

##### Steps To Reproduce
1. Open VSC
2. alert displays right away

##### Additional Informations
![JrunTimeAlert](https://user-images.githubusercontent.com/8447864/167256979-d37bc707-ab86-434c-bacd-6b68e6a3a651.jpg)

**Comment by snjeza** [comment]
@eliassal You can try

```
"java.jdt.ls.java.home":"C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.9.101-hotspot",
```

**Comment by eliassal** [comment]
snjeza, your suggestion did not help, always getting the alert

**Comment by snjeza** [comment]
Is there C:\Program Files\AdoptOpenJDK\jdk-11.0.9.101-hotspot?

**Comment by eliassal** [comment]
Yes of course
![jdk](https://user-images.githubusercontent.com/8447864/167269694-8d688dbe-259a-48eb-9f24-920a2f4ebf75.jpg)

**Comment by snjeza** [comment]
could you try to remove the java.jdt.ls.java.home property?

**Comment by eliassal** [comment]
Did not help neither. While I was doing this manipulation, I found at the end of the settings.json the following tag which is empty

```
     "java.configuration.runtimes": [

    ]
```

I inserted 

> "java.jdt.ls.java.home":"C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.9.101-hotspot"

but also it did not help, then I removed it

**Comment by snjeza** [comment]
Could you send your settings.json?
You can also try to reinstall VS Code Java.

**Comment by jdneo** [comment]
The pop-up is raised by the Sonarlint extension, Suggest: set `sonarlint.ls.javaHome` to point to your JDK11

**Comment by eliassal** [comment]
Thanks jdneo, I entered the path to the jdk in the settings.json but it did not work, then I entered the path in the settings directly as you can notice in the snapshot , saved and restarted VSC the alert disappeared  but I noticed a new section was created in the settings.json (2nd snapshot)

![sonalrlintDirect](https://user-images.githubusercontent.com/8447864/167365898-884c039c-d5ca-4511-aa4b-e83a239faa97.jpg)

![sonalrlintDirect_002](https://user-images.githubusercontent.com/8447864/167365938-766626ab-16a0-447a-a9e2-0c109bef636b.jpg)

**Comment by jdneo** [comment]
@eliassal The newly added section should be created by the sonarlint extension as well. (At least they are not generated by the Java extension)

If you have any concern about the behavior, maybe you can try to reach to the sonarlint team/repo.

**Comment by rgrunber** [comment]
Is this safe to close as not-a-bug given that it happens with the Sonarlint extension ? Another thing that might improve the situation is the Sonarlint extension can take advantage of the embedded JRE provided here (for the more popular platforms). See, for example https://github.com/redhat-developer/vscode-microprofile/commit/b6dd413dc4ad628c66790c8f4dbf164ec0cd08c1 .

They already use the Java extension for some things, https://github.com/SonarSource/sonarlint-vscode/blob/master/src/java.ts so I think they would just need to be informed.

**Comment by jdneo** [comment]
Yes, they already considered to adopt the platform specific extensions: https://jira.sonarsource.com/projects/SLVSCODE/issues/SLVSCODE-217?filter=allopenissues
