### ISSUE TITLE
about vscode extension ,underline error

### ISSUE THREAD

**Issue by MrYZhou** [redhat-developer/vscode-java#2448]
VS Code Version: 1.67.0
OS Version: windows_Nt x64 10.0.19043
Language Support for Java(TM) by Red Hat v1.6.0

this problem is that when i want to close the springboot banner by " .bannerMode(Banner.Mode.OFF) " .
ConfigurableApplicationContext context = new SpringApplicationBuilder() .sources(LarryApplication.class) .bannerMode(Banner.Mode.OFF).run(args);

you can jump to the Banner interface ,but vscode editor will show error underline on it ，and no optional quikfix to use.
can not start application normaly

**Comment by rgrunber** [comment]
When you hover over the `Banner` (which has the error), what does it show as the error ? What about in the problems view ? Also, do you have this sample project available somewhere so I can try to reproduce it ?

**Comment by MrYZhou** [comment]
thanks,i had dealt it
