### ISSUE TITLE
different values for java.jdt.ls.java.home based on os version

### ISSUE THREAD

**Issue by sombriks** [redhat-developer/vscode-java#2460]
[provide a description of the issue]

different values for java.jdt.ls.java.home based on os version

##### Environment
- Operating System: fedora 35 x86_64 and mac m1 
- JDK version: 11
- Visual Studio Code version: latest (1.67.2)
- Java extension version: latest (1.6.0)

##### Steps To Reproduce
1. opening a java project on fedora is fine
2. opening the same java project on mac m1 complains about invalid java.jdt.ls.java.home
3. i am using  settings sync so whenever i log in in vscode my default preferences come to the new setup.

**Comment by rgrunber** [comment]
I would track https://github.com/microsoft/vscode/issues/5595 as this seems to be what you want. If I'm wrong feel free to re-open.
