### ISSUE TITLE
Does anyone know how can I remove this ?

### ISSUE THREAD

**Issue by jvleles** [redhat-developer/vscode-java#2466]
I want to remove this label:
![image](https://user-images.githubusercontent.com/105935324/169560962-aa2e03a0-65b8-4487-99d3-cfdbe9adee4e.png)

**Comment by fbricon** [comment]
In your settings.json:

> `java.inlayHints.parameterNames.enabled`: Enable/disable inlay hints for parameter names. Supported values are: 
> * `none`(disable parameter name hints), 
> * `literals`(Enable parameter name hints only for literal arguments)
> * `all`(Enable parameter name hints for literal and non-literal arguments). 
Defaults to `literals`.

**Comment by Eskibear** [comment]
Or to set vscode's setting `editor.inlayHints.enabled` to "offUnlessPressed" in case you want to see it in some case.

> offUnlessPressed - Inlay hints hidden and shown with Ctrl+Alt

See https://code.visualstudio.com/updates/v1_67#_toggle-inlay-hints if you are interested in that.

**Comment by Sbrjt** [comment]
You may also search for it in the extension settings:

![image](https://github.com/redhat-developer/vscode-java/assets/83166133/85cd8171-9563-41e3-a23f-d85a20cbbdce)
