### ISSUE TITLE
Support vscode-languageclient@8.0.1

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#2474]
Starting from LanguageClient@8.0.1, the `BaseLanguageClient.start()` has been changed to return a promise instead of Dispose, and `onReady()` is removed, they're breaking changes to vscode-java. 

https://github.com/microsoft/vscode-languageserver-node/blob/release/client/8.0.1/client/src/common/client.ts#L933

We need to make changes to the client code in vscode-java to support the new behavior.

https://github.com/redhat-developer/vscode-java/blob/97b29fa68b7b5db8d05e805cbf6cc11b9d33efe5/src/standardLanguageClient.ts#L105

**Comment by rgrunber** [comment]
Just for reference, we're likely going to need to wait on Theia to support things like TypeHierarchyItem. Currently if we run the extension there, it will fail in the vscode-langaugeclient initialization code. See https://github.com/redhat-developer/vscode-java/pull/2377 .

We can just update that PR when ready.
