### ISSUE TITLE
Class-type suggestions do not overwrite existing class-types.

### ISSUE THREAD

**Issue by rhystedstone** [redhat-developer/vscode-java#2478]
When creating a new Java class, if you select a suggestion for class type, such as "interface", the original "class" class-type will not be overwritten - instead, the new class-type will be appended.

##### Environment
- Operating System: Windows 11 Pro (10.0.22000)
- JDK version: OpenJDK Temurin-17.0.1+12)
- Visual Studio Code version: v1.67.2
- Java extension version: v1.6.1

##### Steps To Reproduce
1. Create a new Java class.
2. Select a suggestion for the class-type.

[javaLanguageServer.log](https://github.com/redhat-developer/vscode-java/files/8793378/javaLanguageServer.log)
[vscode-java.log](https://github.com/redhat-developer/vscode-java/files/8793385/vscode-java.log)

##### Current Result
```java
1  package to.uk.rhystedstone.launcher;
2  
3  public class interface Example {
4  	
5  }
```
**Example Videos:** *(Both from wildy different projects)*
https://user-images.githubusercontent.com/12123847/170870111-fcb7951c-7fda-4b8c-877e-94c7bdadc136.mp4
https://user-images.githubusercontent.com/12123847/170870102-3c884760-9e09-420f-b172-a27bc94f056b.mp4
##### Expected Result
```java
1  package to.uk.rhystedstone.launcher;
2  
3  public interface Example {
4  	
5  }
```
##### Additional Information
This occurs on every single project I have.
What I have tried:
- Installing different versions of this extension and Intellicode
- Disabling all extensions except for this extension
- Cleaning the Java workspace
- Searching online for a similar issue
- Resetting all Java settings
- Resetting all Intellicode settings
- Disabling all extensions except for those in the extension pack

I assume since I can't find anyone else complaining that this is most definitely not reproduceable.

**Comment by jdneo** [comment]
Should be the same as https://github.com/redhat-developer/vscode-java/issues/2462.

This is a VS Code bug and will be fixed in next stable release. Or you can use Insider VS Code for now as a workaround.

**Comment by rhystedstone** [comment]
Thanks - I didn't think of it being a snippet, so I didn't search that.
