### ISSUE TITLE
Autocompletion needs an horizontal scrollbar

### ISSUE THREAD

**Issue by NaccOll** [redhat-developer/vscode-java#249]
Recently, I try to write java by VSCode. The extension is helpful for me to modify When the code needs minor repairs. I thank you for the great job you’re doing with this extension.
But, I have a terrible experience when I try to import module. As follows:
[![https://gyazo.com/9f0b536a9f71d72a4939ffbb4834340d](https://i.gyazo.com/9f0b536a9f71d72a4939ffbb4834340d.png)](https://gyazo.com/9f0b536a9f71d72a4939ffbb4834340d)
The picture show the issue when the name of module is too long to show completely, and there is not horizontal scroll bar. So, I can't correctly import module that I want.

I hope a new way to solve the problem, such as, adding horizontal scroll bar or complete the sub-module of module only.

**Comment by fbricon** [comment]
We can't add an horizontal scrollbar, it has to come from vscode proper.

In the mean time, if you already know the type you want to import you can do:

```java
import MyType<+enter>
```
It'll add the fully qualified class name

**Comment by ramya-rao-a** [comment]
@fbricon In the above case, can the completion provider be updated to not show `import.org.` in each of the results when the user has already typed `import.org.` ?

I believe `.` is a trigger character which means the completion provider will be triggered when the user types `.`. At this point, the completion provider should only return the remaining part of the import.

**Comment by Yanpas** [comment]
I suggest following way to fix it:
there is a "More" switcher in completion list 
![image](https://user-images.githubusercontent.com/7345761/57706290-20c87900-766e-11e9-9ff9-4fba42373086.png)
We can always show full class name in "More" section, currently it's empty.

with "More" on:
![image](https://user-images.githubusercontent.com/7345761/57705209-1907d500-766c-11e9-8bd7-913606a3c323.png)
with "More" off:
![image](https://user-images.githubusercontent.com/7345761/57705636-ead6c500-766c-11e9-9cb3-d57d354b4c4d.png)

**Comment by testforstephen** [comment]
@Yanpas i didn't see the "More" switcher in my environment, how did you enable it in completion list?

**Comment by testforstephen** [comment]
i see, clicking it will expand the java doc at the right side.

**Comment by Eskibear** [comment]
VS Code Insiders now supports to resize completion widget. 
See https://github.com/microsoft/vscode/issues/29126#issuecomment-716415112

**Comment by fbricon** [comment]
Closing since vscode upstream fixed it, will be available in the October release (prolly around the 1st week of November)
![readable-completions](https://user-images.githubusercontent.com/148698/97281781-33247b80-183e-11eb-8f12-f50aaf33d3e9.gif)

For the impatients, you can download vscode-insiders from https://code.visualstudio.com/insiders/
