### ISSUE TITLE
Inlay hints in lambdas

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-java#2498]
Parameter inlay hints don't appear to work within a lambda function.

##### Environment
- Operating System: RHEL 8
- JDK version: Temurin 11
- Visual Studio Code version: 1.67.2
- Java extension version: v1.7.0

##### Steps To Reproduce
For the following code snippet, I expect an inlay hint for the `message` parameter to the `consume` method, to be consistent with the other inlay hints.

I have `"java.inlayHints.parameterNames.enabled": "all"` set.

```java
@Override
public MessageConsumer apply(final MessageConsumer consumer) {
	return message -> {
		lastActivityTime=System.currentTimeMillis();
		consumer.consume(message);
	};
}
```

##### Current Result
No inlay hint for `message`.

##### Expected Result
Hint for the parameter name of `message`.

**Comment by jdneo** [comment]
What's the parameter's name of `MessageConsumer#consume()`? Is it named `message` as well?

**Comment by datho7561** [comment]
Oops. My bad. Yes, the parameter is named `message` as well. I didn't realize that would mean the hint doesn't get displayed, but that makes sense. When I rename the lambda parameter to something other than `message`, the hint appears.
