### ISSUE TITLE
Is there a way to create Multi-Module Maven in vscode

### ISSUE THREAD

**Issue by ydmykr** [redhat-developer/vscode-java#2505]
I read an [article](https://www.codejava.net/ides/intellij/create-multi-module-maven-project-intellij) about the multi-module Maven project on IDE.

I tried it on vscode but I faied when I want to creat a maven project in a maven project.

And I get the following error report.

`[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

[INFO] Total time:  01:48 min

[INFO] Finished at: 2022-06-13T09:48:26+08:00

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project standalone-pom: Unable to add module to the current project as it is not of packaging type 'pom' -> [Help 1]`

What I want to ask is whether there is a way to implement the method of this article in vscode

**Comment by snjeza** [comment]
@ydmykr The create maven project feature is a part of the vscode-maven extension. You can create a new issue at https://github.com/microsoft/vscode-maven/issues.
