### ISSUE TITLE
Is there a way to show type hierarchy or navigate to implementations of an interface?

### ISSUE THREAD

**Issue by bkbonner** [redhat-developer/vscode-java#251]
I'm trying to find a way to navigate to implementations of an method defined in an interface.   When I command click, it only takes me to the declaration of the method.

##### Environment
- Operating System:  OSX
- JDK version:  1.8
- Visual Studio Code version:  1.13.1
- Java extension version:   0.6.0

##### Steps To Reproduce
1. command click on a method in a piece of java code.   The method is declared in an interface and has one or more implementations.
##### Current Result
The user is navigated to the method declaration in the interface.

##### Expected Result
The user is navigated to the method implementation if there is only 1, or is presented with a list of implementations to choose from.  After choosing an implementation, the user is navigated to that implementation.

**Comment by fbricon** [comment]
Closest thing we have right now is the find all references (Click on references link or Shift+F12).

There's an enhancement request for the Java Language Server to provide Interface implementors, see https://github.com/eclipse/eclipse.jdt.ls/issues/99.

But I reckon ctrl+click on a method to jump to implementors would be a nice feature to have

**Comment by bkbonner** [comment]
Thanks for including the link to that request @fbricon.

**Comment by fbricon** [comment]
@bkbonner you can test implementor code lenses with the latest CI build: download the most recent `java-<version>.vsix` file and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

You need to set `java.implementationsCodeLens.enabled` to `true` in vscode settings.
