### ISSUE TITLE
Java formatter setting ignored - even with google's format

### ISSUE THREAD

**Issue by Dr-Irv** [redhat-developer/vscode-java#2516]
I am trying to get a custom formatter working by using the setting `java.format.settings.url`.  I am now convinced that there is a problem, even if I use google's formatter that is shown here:  https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings

##### Environment
- Operating System:   Windows 10
- JDK version:  Not relevant
- Visual Studio Code version:   1.68.1
- Java extension version:    1.7

##### Steps To Reproduce
```java
class HelloWorld {
    public static void main(String[] args) {
        int[] intArray = new int[]{1,2,3,4,5,6,7,8,9,10};
    }
}
```
In Eclipse, if you import the google formatter at https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml, there are NO spaces after the opening curly bracket and before the closing curly bracket in the array initializer.  You get this on that line:
```java
        int[] intArray = new int[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
```
In VS Code, with this setting file:
```json
{
  "java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml",
  "java.format.settings.profile": "GpogleStyle",
  "java.format.enabled": false,
  "[java]": {
    "editor.defaultFormatter": "redhat.java"
  }
}
```
I get a message: "There is no formatter for 'java' files installed.  To get rid of that message, I change the setting `"java.format.enabled"` to be `true`.  Then I get this format for that line:
```java
        int[] intArray = new int[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
```
There are spaces after the opening curly brace and before the closing curly brace because the default java formatter was used.  The setting `java.format.enabled` is documented as "Enable/disable default Java formatter", so it makes sense that changing it to true would add the spaces, because that is in the default java formatter.  I can see that by looking at what you get when you do "Java: Open Java Formatter Settings with Preview" to get the default java formatter without all those settings listed above.

If you look at the google style XML, the relevant settings for spaces in array initializers are:
```xml
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_opening_brace_in_array_initializer" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_closing_brace_in_array_initializer" value="do not insert"/>
```
In the default Java formatter that you get within VS Code, you get:
```xml
        <setting id="org.eclipse.jdt.core.formatter.insert_space_after_opening_brace_in_array_initializer" value="insert"/>
        <setting id="org.eclipse.jdt.core.formatter.insert_space_before_closing_brace_in_array_initializer" value="insert"/>
```
The settings for the default and google are different.  VS Code isn't applying the google ones.

I know you'd like to see the logs, but I don't see anything in there that is referring to the URL for pulling the google style.

**Comment by snjeza** [comment]
@Dr-Irv Could you try the following

``` 
{
  "java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml",
  "java.format.enabled": true,
  "[java]": {
    "editor.defaultFormatter": "redhat.java"
  }
}
```
remove 
```
"java.format.settings.profile": "GpogleStyle",
```

or set
``` 
"java.format.settings.profile": "GoogleStyle",
```

**Comment by Dr-Irv** [comment]
Thank.  I missed the typo.  And figured out that my formatter wasn't working because the XML (which was pretty old) didn't have `kind="CodeFormatterProfile"` in the `<profile>` tag.

**Comment by snjeza** [comment]
@Dr-Irv You can find
```
[Error - <date> Invalid settings: java.format.settings.profile=GpogleStyle. The 'GpogleStyle' profile doesn't exist.
```
in your server log.
