### ISSUE TITLE
Wiki entry for Java 17 requirement has a typo

### ISSUE THREAD

**Issue by jonahgraham** [redhat-developer/vscode-java#2520]
https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#about-the-java-17-requirement has a typo - because wiki's don't have PR ability (AFAIK) I file an issue so a maintainer can make the fix:

> The m2e team has decided to require Java 17 as the minimum requirement for its September 2020 release

Should read September **2022**

**Comment by fbricon** [comment]
@jonahgraham thanks for noticing. fixed.
