### ISSUE TITLE
Cross-compilation options feature missing

### ISSUE THREAD

**Issue by giatmanos** [redhat-developer/vscode-java#2529]
I have been working on creating an "Unmanaged Folder" project, i.e. without the use of Gradle/Maven and everything works fine except that I cannot find any option to enable java cross-compiling which is necessary for this particular project I work on. 

To be more specific, I would like to be able to mimic the Gradle sourceCompatibility and targetCompatibility configuration variables which in essence add the compiler flags -source and -target respectively. Is this possible in the current version of the vscode-java extension and I have missed it? If not, I would really like to see this feature being added.

**Comment by jdneo** [comment]
Not quite sure but seems that you can set a global setting first according to this guide: https://github.com/redhat-developer/vscode-java/wiki/Settings-Global-Preferences

And then specify the following settings:
- `org.eclipse.jdt.core.compiler.source`
- `org.eclipse.jdt.core.compiler.codegen.targetPlatform`
