### ISSUE TITLE
cannot automatically format java code

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#2530]
ctrl+s cannot automatically format java code

Triggering ctrl+s after entering code cannot automatically format code
"editor.formatOnSave": true,

[provide a description of the issue]

##### Environment
- Operating System: Windows 10 19044
- JDK version: 11
- Visual Studio Code version: 1.68.1
- Java extension version: 

Version | 1.8.2022062304 |  
-- | -- | --
Released on | 9/13/2016, 4:41:27 AM |  

Last updated | 6/23/2022, 4:28:15 PM

**Comment by zhouxinghong** [comment]
In version 0.8, triggering ctrl+s to automatically format is normal. This problem has not been fixed since version 1.5. . .

**Comment by jdneo** [comment]
I cannot repro within VS Code@1.68.1+vscode-java@1.7.0

![format](https://user-images.githubusercontent.com/6193897/175844302-c8dcb6b3-0d95-4e50-8af8-093bfd86d262.gif)
