### ISSUE TITLE
Feature request: add interface methods when coding a class

### ISSUE THREAD

**Issue by rajinder-yadav** [redhat-developer/vscode-java#2539]
Would be nice to have code auto-generated from the interface being implement in a class or an anonymous class.

Give the following interface:

```java
interface HelloWorld {
 String greet()
}
```

If I were to code a class that implemented this interface, would be nice to have the interface method auto include. 

So when I type the opening brace:

```java
class Foo implements HelloWorld {
``` 
I get interface code added:

```java
class Foo implements HelloWorld {

 String greet() {
 }
``` 

Likewise for an anonymous class, I type:

```java
  Foo f = new HelloWorld() {
```

I get interface code added:

```java
  Foo f = new HelloWorld() {
    String greet() {
    }
```

This way I don't need to lookup the definition of the interface to see what methods I need to support and then manually type them in.

Additional there should be a light-bulb option to "fix: add missing interface methods". This might be a case during coding, an interface is updated with additional methods. So code with class implementing this interface should detect the problem and add option to "fix" it.

**Comment by snjeza** [comment]
> Additional there should be a light-bulb option to "fix: add missing interface methods".

@rajinder-yadav You can check the "Add unimplemented methods" quickfix.

![qfix](https://user-images.githubusercontent.com/388609/177229458-0657d1da-b53f-4437-b82b-9eb300533c5f.gif)

**Comment by rajinder-yadav** [comment]
Hi @snjeza, there must be a quirk. I created a test project and was not seeing this option in the "fix" it. However after your reply I decided to delete and recreate the project and now the correct fix is showing up.

Closing this off, thanks!
