### ISSUE TITLE
The java.home variable defined in VS Code settings points to a missing folder

### ISSUE THREAD

**Issue by logandonovan11** [redhat-developer/vscode-java#254]
Getting the above error which prevents the client Language Support for Java from starting.

##### Environment
- Operating System: Windows 10
- JDK version: jdk1.8.0_131
- Visual Studio Code version: 1.13.1
- Java extension version: 0.7.0

##### Steps To Reproduce
Downloaded extension and supplied the java.home value in the VSCode workspace settings:
"java.home": "C:/ProgramFiles/Java/jdk1.8.0_131"

##### Current Result
Giving me the error: "The java.home variable defined in VS Code settings points to a missing folder" when I restart VS Code. The file path is correct and the jdk is indeed in the right folder. I re-installed the jdk and made sure the version numbers matched.

**Comment by fbricon** [comment]
are you sure it shouldn't be "C:/Program Files/Java/jdk1.8.0_131"?

**Comment by logandonovan11** [comment]
That was the issue. Silly of me to miss that, thanks for your help.
