### ISSUE TITLE
New java created project not detected as java project until a file is opened 

### ISSUE THREAD

**Issue by rajinder-yadav** [redhat-developer/vscode-java#2541]
Newly created java project not detected as java project.

Create a new java project.

Steps:
press ctrl + shift + p
Type "java: create"
Selected, create a new java project.

Once project is created, notice IDE has not detected it is a java project.
open the main java file, now IDE detects it is a java project.

Issue with this, before opening any java file, if I right-click in explorer on "src" folder to create a new java file, IDE creates a blank file. It should create a file with skeleton code of a Class.

![java](https://user-images.githubusercontent.com/439226/177422010-c414ed23-76fd-47e3-8aa3-ca324663a7ef.png)

##### Environment
- Operating System: Linux
- JDK version: openjdk version "18.0.1" 2022-04-19
- Visual Studio Code version: 1.69.0-insider
- Java extension version: 1.8.0

**Comment by rajinder-yadav** [comment]
The same happens if you cd in the root of the java project and then open vscode from the terminal.
vscode opens and doesn't know project is java.
note make sure no files are opened in edit window, if so close all open files, close vscode and redo steps.

**Comment by gnuchanos** [comment]
not a bug it's a future 
![2023-10-29-223956_1165x451_scrot](https://github.com/redhat-developer/vscode-java/assets/117280480/447a5f3e-81b3-43dc-ae6a-a941b1c82400)
