### ISSUE TITLE
Java extension is broken with some old lombok.jar (e.g. 1.14.4)

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#2549]
Issue Type: **Bug**

Just open a java file, the "Java Building" never stop (actually never start),
When click the "Show Build Status" , open a terminal shows nothing.
Developer tool console got error, says:
ERR [Extension Host] Error: Unexpected SIGPIPE
at process. (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:1:407)
at process.emit (node:events:390:28)
 
 ![图片](https://user-images.githubusercontent.com/4081996/177921673-3ba95627-6428-4bc6-90d6-e38d6e758c6d.png)
 
Extension version: 0.42.0
VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:41.511Z)
OS version: Darwin x64 21.3.0 
Restricted Mode: No

Yes, Clean Java Language Server Workspace don't help.  Uninstall whole extension and reinstall don't help.
**F1** -> **Java: Open All Log Files**  show a client.log and a message "No log file available":

![图片](https://user-images.githubusercontent.com/4081996/177924705-da743ece-ecf8-4ea7-9762-601a5dff7e02.png)

[client.log](https://github.com/microsoft/vscode-java-debug/files/9069216/client.log)

_Originally posted by @terrason in https://github.com/microsoft/vscode-java-debug/issues/1190_

**Comment by terrason** [comment]
Thank you for help.
There is an old lombok dependency in my "pom.xml"
```
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.14.4</version>
</dependency>
```
Setting `java.jdt.ls.lombokSupport.enabled: true` resolved this.
Better to consider adding warnings for lower versions of Lombok

**Comment by testforstephen** [comment]
Here are some ideas to better handle such kind of cases:
- Embed a latest lombok.jar in Java extension, and use it as the default lombok support. This can avoid the restart problem. And the language status provides a button to allow user to choose between the embedded lombok and project's lombok. The user experience could reference to the typescript's language status.

![image](https://user-images.githubusercontent.com/14052197/177936633-df993e5c-570d-44de-a571-e0b177c6815e.png)

![image](https://user-images.githubusercontent.com/14052197/177936855-5d50ebe1-d79a-441f-a37f-233b0c8485e3.png)

- For the unsupported lombok.jar (<= 1.18.2 is not compatible with JLS ?), Java extension should not load them into Java language server and give some warnings as @terrason mentioned above.

// @XiaoYuhao
