### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Zelakolase** [redhat-developer/vscode-java#2558]
- Issue Type: `Bug`
- Extension Name: `java`
- Extension Version: `1.8.0`
- OS Version: `Linux x64 5.18.9_1`
- VS Code version: `1.69.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 930,
		"activateCallTime": 69,
		"activateResolvedTime": 11477,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "redhat.java",
				"_lower": "redhat.java"
			},
			"activationEvent": "onLanguage:java"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Connection got disposed."
		}
	],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by jdneo** [comment]
Dup with https://github.com/redhat-developer/vscode-java/issues/2268

**Comment by Zelakolase** [comment]
Hello there,
I'd like to inform you that it is not a duplicate. The problem was that I updated linux kernel without updating electron. That resulted in this issue.

**Comment by Zelakolase** [comment]
However, I fixed it by updating electron.
