### ISSUE TITLE
wrong JRE embedded in pre-release package

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#2559]
For universal platform, should pre-pack no JRE. Probably because you didn't clear the staging folder.

![image](https://user-images.githubusercontent.com/2351748/178693043-dffd2205-0757-4cf9-a274-b4c9c4ae07ce.png)

@CsCherrYY

**Comment by CsCherrYY** [comment]
the root cause is that we didn't clean jre folder for generic pre-release versions: https://github.com/redhat-developer/vscode-java/blob/6c000d33fc51ba3041c6452b4879b532a43f1dae/Jenkinsfile#L95-L96

I'll add a PR to fix it.

**Comment by rgrunber** [comment]
Not saying we need to do this now, but down the road, we could potentially simplify basic flag inclusions like `--pre-release` by storing the flag (or empty value) in variable. That way one can always pass that to the package/publish call :

https://github.com/redhat-developer/vscode-xml/blob/faaac4e08384d7324bd0f0fbd61d2de055642f33/Jenkinsfile#L88
https://github.com/redhat-developer/vscode-xml/blob/faaac4e08384d7324bd0f0fbd61d2de055642f33/Jenkinsfile#L125
