### ISSUE TITLE
Code Completion Hint Box miss some of the object methods 

### ISSUE THREAD

**Issue by tianfudhe** [redhat-developer/vscode-java#2571]
Issue Type: <b>Bug</b>

I add dependency `hutool-all` in maven, i.e.,
```xml
<dependency>
  <groupId>cn.hutool</groupId>
  <artifactId>hutool-all</artifactId>
  <version>5.8.4</version>
</dependency>
```
and write
```java
package com.tianfudhe;
import cn.hutool.json.JSONObject;
public class App {
  public static void main( String[] args ) {
    JSONObject obj=new JSONObject();
    obj.set("data", new JSONObject());
    obj.getJSONObject("data");
    System.out.println( "Hello World!" );
  }
}
```
when I type `obj.` the candidate method `getJSONObject` does not pop up in HintBox, even though `obj.getJSONObject` is valid.

Extension version: 1.8.0
VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (7.01GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/tianfu/Documents --remote=wsl+Ubuntu --crash-reporter-id ade2656e-b88c-4d58-a0cb-ce0a38015e24|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics (16 x 3193)|
|Memory (System)|7.76GB (5.07GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by jdneo** [comment]
I cannot reproduce it on my machine

![image](https://user-images.githubusercontent.com/6193897/179435849-31fe22f4-2d94-45c9-81e3-98c7c3ed7509.png)
