### ISSUE TITLE
Extension never activates, throwing error "Header must provide a Content-Length property"

### ISSUE THREAD

**Issue by atcericandrews** [redhat-developer/vscode-java#2577]
As per the title, the extension never activates; the java language server status never switches to the thumbs-up. The extension runtime status shows 37 copies of the same uncaught error: `Header must provide a Content-Length property.` The developer tools logs show the same error, slightly more verbosely:

```
workbench.desktop.main.js:2272 Error: Header must provide a Content-Length property.
	at p.onData (c:\Users\Eric.Andrews\.vscode\extensions\redhat.java-1.8.0-win32-x64\dist\extension.js:2:1138205)
	at Socket.<anonymous> (c:\Users\Eric.Andrews\.vscode\extensions\redhat.java-1.8.0-win32-x64\dist\extension.js:2:1137926)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

##### Environment
- Operating System: Windows 10 Enterprise (10.0.19044)
- JDK version: Eclipse Adoptium 17.0.3.7-hotspot
- Visual Studio Code version: 1.69.2
- Java extension version: 1.8.0

##### Steps To Reproduce
1. Install jdk and VSCode
2. Install the Extension Pack for Java
3. Update settings.json to point to jdk: `"java.jdt.ls.java.home": "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.3.7-hotspot"`
4. Open any .java file

[language server logs](https://github.com/redhat-developer/vscode-java/files/9142497/language-server-log.txt)
[dev tools console logs](https://github.com/redhat-developer/vscode-java/files/9142505/devtool-logs.txt)

**Comment by devin-lo** [comment]
same issue on:

VS code versions 1.68.1 and 1.67.0
RedHat Java extension 1.7.0, 1.8.0, 1.90
(multiple combinations of the above were tried, all had same issue)

JDK version 11.0.12 (oracle)

**Comment by elizalde1981** [comment]
Seems to be similar to #2292

**Comment by victorlee0505** [comment]
same issue here, out of the blue it just stopped working.

**Comment by Foxhunter981** [comment]
Also happening to me. Its very annoying. I have to switch to Eclipse for now 
![image](https://user-images.githubusercontent.com/74263544/183524553-f6299781-0a37-4143-8a41-45366c4f501e.png)

**Comment by muchida6** [comment]
In my case, adding `-Xlog:jni+resolve=off` to `java.jdt.ls.vmargs` solved this problem.

languageclient has receiving rpc response with error messages as follows.
```
[0.158s][warning][jni,resolve] Re-registering of platform native method: java.lang.PanwHooks.NativeMethodEntry(Ljava/lang/Object;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V from code in a different classloader
Content-Length: 780
```

PanwHooks seems to be related to Palo Alto Networks products, which this product seems to  injecting DLLs into the JVM.

**Comment by sudheerkkumar** [comment]
@muchida6 
I am also facing the same issue. Getting same warning with Javac -version command in cmd as well. 
Can you bit more specific where to add the vmargs. I tried to add in vscode settings.json. But no luck.

**Comment by MarcSerret51** [comment]
I'm getting the same error. The workaround given by @muchida6 worked for me.
@sudheerkkumar To add this config line you have to go to Setting and type `java.jdt.ls.vmargs` and click `Edit in settings.json`.
![image](https://user-images.githubusercontent.com/32881340/183594240-ea3de086-d393-4999-accc-00b899588593.png)

**Comment by sudheerkkumar** [comment]
Thanks @MarcSerret51 . It is working now.

**Comment by fbricon** [comment]
@muchida6 thanks for finding that out. Where did you see the "Re-registering of platform native method: java.lang.PanwHooks.NativeMethodEntry" response? in some logs or while debugging vscode?

**Comment by Foxhunter981** [comment]
I would also like to know where this response was found. I didn't see it locally but that could just mean I missed an important debug step

**Comment by victorlee0505** [comment]
@muchida6 Great Thanks!! btw, now junit test stuck at resolving launch config from debugger for java extension, but I can live with that :-D

**Comment by muchida6** [comment]
@fbricon @Foxhunter981 I was just trying to debug.
![image](https://user-images.githubusercontent.com/64448195/183777963-35a82bb2-9619-4a67-b253-0cb4bacc6de8.png)

**Comment by muchida6** [comment]
@victorlee0505 Running the junit test by `vscode-java-test` worked for me, though `vscode-java-test` has `vmArgs` in `java.test.config` (https://github.com/Microsoft/vscode-java-test/wiki/Run-with-Configuration),
so adding `-Xlog:jni+resolve=off` might work better. I hope this helps.

**Comment by victorlee0505** [comment]
i added these 2 enties in setting.json to make test runner and springboot dashboard works!

    "java.debug.settings.vmArgs": "-Xlog:jni+resolve=off",
    "spring-boot.ls.java.vmargs": ["-Xlog:jni+resolve=off"],

**Comment by jundiaufa11** [comment]
@muchida6 thank's dude it's working on me :)

**Comment by jgriffin1** [comment]
@muchida6 
I spent so many hours trying to figure this out. Your solution was the answer. Thank you so much!

**Comment by snjeza** [comment]
@jmihalichuber could you, please, attach your logs - [Enable Logging](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by shivamfet** [comment]
Hi Joe @jmihalichuber Did you find any solution i am also stuck, i tried the workaround it is not working.?

Does installing another version will help ?
