### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by PSpringchill** [redhat-developer/vscode-java#2583]
- Issue Type: `Bug`
- Extension Name: `java`
- Extension Version: `1.8.0`
- OS Version: `Windows_NT x64 10.0.21996`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rgrunber** [comment]
Can you describe roughly what the issue is and a step by step of how to reproduce ?
