### ISSUE TITLE
Keep consistent style in notification when prompted to restart/reload VSCode

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#2585]
##### Environment
- Operating System: Mac intel
- JDK version: 17.0.2
- Visual Studio Code version: 1.69.2
- Java extension version: 1.9.0

##### Steps To Reproduce
1. [step 1] Change `java.jdt.ls.java.home` in settings > Notification dialog shows as screenshot 1
2. [step 2] Install a new extension, like debugger for java > Notification dialog shows as screenshot 2

##### Current Result
Screenshot 1:
![image](https://user-images.githubusercontent.com/31497677/180174035-20d78dde-2a6a-4b47-9196-f89c1bbb6167.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/31497677/180174047-fe6907d1-83de-456d-9c69-dfebb24f85af.png)

##### Expected Result
As restart and reload work in a same way, better to only keep one, both reload or both restart.

**Comment by jdneo** [comment]
We can consider make those wordings consistent in next iteration.
