### ISSUE TITLE
Clean Java Language Server Workspace command not found in 1.9.0

### ISSUE THREAD

**Issue by jcolladosp** [redhat-developer/vscode-java#2589]
##### Environment
- Operating System: Ubuntu 20.40
- JDK version: 17.0.3
- Visual Studio Code version: 1.69.2
- Java extension version: 1.9.0

##### Steps To Reproduce
1. Go to the command palette and run `Java: Clean Java Language Server Workspace`

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
![2022-07-22_11-52](https://user-images.githubusercontent.com/9121186/180414506-650fe89e-a118-4869-9fbe-711cee6a3ab8.png)

**Comment by fbricon** [comment]
This can happen if the extension has not yet been activated. Current activation events are configured in https://github.com/redhat-developer/vscode-java/blob/03d6bb42d02c95331957e1a75f1b8bc51bcd261a/package.json#L41-L51

So, as a workaround, you can just open a java file (or open a folder containing Maven or Gradle files) to trigger activation, then you can call the clean workspace command.

**Comment by jcolladosp** [comment]
@fbricon Hi, I just tried that and still not working

**Comment by jdneo** [comment]
Is the extension activated successfully on your machine?

**Comment by jcolladosp** [comment]
Hi @jdneo, the extension is not activated, but I cant find any log with errors in order to provide you with something useful

**Comment by Eskibear** [comment]
View -> Output -> Expand the dropdown menu-> scroll down and select `Log (Extension Host)`, you'll see how extensions are activated. Search `redhat.java` for related logs.

**Comment by jdneo** [comment]
> If I click the button nothing happens.

By saying nothing happens, does that mean VS Code does not restart? Or it does a restart but the issue still occur?

**Comment by jcolladosp** [comment]
> 



> > If I click the button nothing happens.
> 
> By saying nothing happens, does that mean VS Code does not restart? Or it does a restart but the issue still occur?

No restart and no clean workspace. Also I don't get any error message.

**Comment by jdneo** [comment]
@testforstephen Do you have any idea on this?

**Comment by testforstephen** [comment]
> Hi  here I attach my log with the java related extensions: `[2022-07-29 09:35:00.506] [exthost] [info] ExtensionService#_doActivateExtension redhat.java, startup: false, activationEvent: 'onLanguage:xml', root cause: Pivotal.vscode-spring-boot [2022-07-29 09:35:00.854] ...

The logs shows that redhat.java extension fails to startup. Looks like the extension got some unexpected exception before the clean workspace command is registered. To improve the user experience, I think we need to register troubleshooting commands such as open_logs and clean_workspace as early as possible.

@jcolladosp Could you show the logs of the following places?

- **Help -> Toggle Developer Tools -> Console**
![image](https://user-images.githubusercontent.com/14052197/182059991-d636123d-0c0b-4278-9760-f223b0194a80.png)

- **OUTPUT -> Language Support for Java**
![image](https://user-images.githubusercontent.com/14052197/182059700-a9669617-5466-479b-99cf-eb845f94e0b5.png)

**Comment by snjeza** [comment]
@jcolladosp could you try the following:

- exit VS Code
- run
```
rm -rf ~/.config/Code/User/workspaceStorage/
```
- start VS Code

**Comment by jcolladosp** [comment]
> @jcolladosp could you try the following:
> 
> * exit VS Code
> * run
> 
> ```
> rm -rf ~/.config/Code/User/workspaceStorage/
> ```
> 
> * start VS Code

Hi @snjeza,
that worked!
Thank you very much!
