### ISSUE TITLE
Clear out-of-date files in global storage

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#2597]
The extension will store some caches in global storage with each version. Each version will occupy around 15~20MB, which the total size will be quite large when users switched to the pre-release channel.

![image](https://user-images.githubusercontent.com/6193897/181176687-f95eb09d-83a4-4464-aa42-9059ccb65938.png)

We can consider detect the out-of-date version and remove it.

**Comment by CsCherrYY** [comment]
I remember @rgrunber mentioned this before: https://github.com/redhat-developer/vscode-java/issues/2285#issuecomment-1126151673 We have already updated to M2E 2.0, so is there any difference on size of the recent versions? 

Besides, we can have such logic to clean previous global storage folders.

**Comment by jdneo** [comment]
> so is there any difference on size of the recent versions?

Yes the size is smaller. For example, the size if the folder `1.3.0` is ~24MB, while the size of `1.10.2022072204` takes ~16MB

**Comment by rgrunber** [comment]
As per discussions, maybe there is some feature to have VS Code clear such cached folders at the platform level ? Or maybe there is something we can take advantage of in VS Code API that can mark those folders for deletion on certain staleness criteria ?

**Comment by jdneo** [comment]
I filed an issue at VS Code to ask what's their perspective on this: https://github.com/microsoft/vscode/issues/156519
