### ISSUE TITLE
Bug report: The `new` snippets use the wrong format of ${0}

### ISSUE THREAD

**Issue by doggy8088** [redhat-developer/vscode-java#2605]
Code snippets in VSCode should treat `$0` as a ending position. Some of the snippets such as `new` use `$0` as a replacement which is wrong.

https://github.com/redhat-developer/vscode-java/blob/3ad9749dd8edd63ee4f2e887ec7142a3874e3659/snippets/java.json#L100-L106

Also, some snippets (see below) use `{0:TODO}` as a replacement which is not handy for coding.

https://github.com/redhat-developer/vscode-java/blob/5fa5fbcda04e15e4c60738478c774f89109843b7/snippets/java.json#L20-L40

**Comment by rgrunber** [comment]
Not sure why this didn't close. Closing ..
