### ISSUE TITLE
Sorting server tasks uses compare function that always returns zero

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-java#2627]
https://github.com/redhat-developer/vscode-java/blob/master/src/serverTasks.ts#L37

Unless I'm missing something, this compare function seems to always return zero. This doesn't seem like the correct behaviour.

**Comment by rgrunber** [comment]
That definitely looks like a typo.

**Comment by priyangbhavsar** [comment]
Hello @datho7561 , I am willing to take this issue as the first contribution

**Comment by datho7561** [comment]
Sounds good. Let me know if you have any questions, and feel free to ping me in the review
