### ISSUE TITLE
Generate getters and setters from code action

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#263]
See https://github.com/redhat-developer/vscode-java/issues/100#issuecomment-317569809

For attributes without a getter or setter, a code action should be available to generate them (Generate Accessors)

**Comment by yaohaizh** [comment]
Currently, the design of code action/assist only for one compilation unit while the action for getter/setter involves multiple compilation units. In order to support this, we need introduce the refactoring functionalities. What's the plan regarding the refactoring?

**Comment by fbricon** [comment]
I thought adding getters/setters would only affect the current compilation unit. Since that would add new code (therefore unused code at that point), that shouldn't affect other CUs.
What do you mean by introducing refactoring functionalities? Rename is one part, of course, what else do you need at that point?

**Comment by yaohaizh** [comment]
I originally thought generate getter/setter that reference from A to B CU case. If only for the same CU, it's doable.

**Comment by fbricon** [comment]
@yaohaizh when the private field is used in the class, the code action to generate accessors is not available

**Comment by fbricon** [comment]
Closing this issue since the code will be shipped, following up on #290
