### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by krukah** [redhat-developer/vscode-java#2632]
- Issue Type: `Bug`
- Extension Name: `java`
- Extension Version: `1.10.2022081204`
- OS Version: `Darwin arm64 21.4.0`
- VS Code version: `1.70.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 170,
		"activateCallTime": 18,
		"activateResolvedTime": 15767,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "Pivotal.vscode-spring-boot",
				"_lower": "pivotal.vscode-spring-boot"
			},
			"activationEvent": "onLanguage:java"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Connection got disposed."
		}
	],
	"runningLocation": {
		"kind": 3,
		"affinity": 0
	}
}
```




semantic highlighting all of the sudden disappeared, and then i see "1 Bug" in this extension, which is the only error reported when i view all running extensions. tough to do any work sine i've been spoiled by my trusty IDE

**Comment by jdneo** [comment]
The extension id `pivotal.vscode-spring-boot` indicates that this might be an issue related with https://github.com/spring-projects/sts4?

I'm closing this issue since from the logs it seems out of this repo's scope. But if I'm wrong, please leave comments and let us know.

Thanks.
