### ISSUE TITLE
Generate toString() source action should support inclusion of methods

### ISSUE THREAD

**Issue by rohansatapathy** [redhat-developer/vscode-java#2639]
It would be helpful to add an option to generate a toString with getters instead of attribute names because it would allow the toString to work automatically in subclasses where the getters might be overridden. Currently, the dialog only allows you to select which attributes to include in the toString. It seems like it would be relatively simple to add a checkbox (or maybe a separate dialog box) that allows the user to select whether to use attribute names or getters.

**Comment by rgrunber** [comment]
I think this is possible with just adjusting how we use the `GenerateToStringOperation` and its underlying API. From Eclipse IDE, I see :

![Screenshot from 2022-08-22 15-51-31](https://user-images.githubusercontent.com/1417342/186006963-e6fc6e9e-ef77-40ff-9009-19cc4a77719b.png)

We don't need to support all of these, but clearly generation from methods is supported.
