### ISSUE TITLE
Restart doesn't make change if I edit template pages in my Spring-boot application

### ISSUE THREAD

**Issue by bilymed** [redhat-developer/vscode-java#264]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Can you provide more details on how to reproduce this issue? Environment info, steps to reproduce (ideally with a sample project to test), expected results?

**Comment by bilymed** [comment]
Thank you for your reply, 
the project works just fine if I edit/save my java classes (Automatic Restart) but if I edit jsp/html pages nothing works so I have to restart the server again and again..
please find bellow the project link 
https://github.com/bilymed/spring-boot-vs

**Comment by fbricon** [comment]
See https://docs.spring.io/spring-boot/docs/current/maven-plugin/usage.html

```
Prior to devtools, the plugin supported hot refreshing of resources by default which has now be 
disabled in favour of the solution described above. You can restore it at any time by configuring 
your project:

<build>
  ...
  <plugins>
    ...
    <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
      <version>1.5.6.RELEASE</version>
      <configuration>
        <addResources>true</addResources>
      </configuration>
    </plugin>
    ...
  </plugins>
  ...
</build>
When addResources is enabled, any src/main/resources folder will be added to the application
 classpath when you run the application and any duplicate found in target/classes will be removed.
 This allows hot refreshing of resources which can be very useful when developing web applications.
 For example, you can work on HTML, CSS or JavaScript files and see your changes immediately
 without recompiling your application. It is also a helpful way of allowing your front end developers
 to work without needing to download and install a Java IDE.
```
