### ISSUE TITLE
Constructor in Records with varargs not found

### ISSUE THREAD

**Issue by brunoborges** [redhat-developer/vscode-java#2640]
##### Environment
- JDK version: 17

##### Steps To Reproduce
1. Create a Record with last argument being `varargs`
2. Attempt to instantiate the record using varargs, from another class.

##### Current Result

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/129743/185994032-56cf93b0-303a-4b6b-9472-86b6fd0c1ebc.png">

##### Expected Result

Constructor should be found.

##### Additional Informations

If the record is declared within the same class instantiating it, the extension works fine.

**Comment by snjeza** [comment]
This is an upstream issue. It can be reproduced in Eclipse.

**Comment by rgrunber** [comment]
@snjeza , is there a known bug for this we can reference (even old one in bugs.eclipse.org) ? If none, we should probably filea new one.

**Comment by snjeza** [comment]
> , is there a known bug for this we can reference (even old one in bugs.eclipse.org) ? If none, we should probably file a new one.

@rgrunber I can't find it.

**Comment by rgrunber** [comment]
Just noticed that the code runs just fine for me, if the above is the only error :neutral_face: . @brunoborges , can you confirm that ? I've included it in the report upstream.

**Comment by brunoborges** [comment]
Yeah, code works.

**Comment by snjeza** [comment]
A related PR - https://github.com/eclipse-jdt/eclipse.jdt.core/pull/618

**Comment by snjeza** [comment]
Fixed with https://github.com/eclipse/eclipse.jdt.ls/pull/2538
