### ISSUE TITLE
Change order of "Generate toString"

### ISSUE THREAD

**Issue by xxc-zsz** [redhat-developer/vscode-java#2642]
Is there a way to change order of "Generate toString"?

![image](https://user-images.githubusercontent.com/108051416/186111232-5e101fb7-b723-41ba-a274-1c03440832da.png)

For example, here, I want the order of generation to be the same as the order of fields above, or there is a way for me to adjust the order of generation myself.

**Comment by jdneo** [comment]
It's duplicated with https://github.com/redhat-developer/vscode-java/issues/2502.
