### ISSUE TITLE
[Adoption Required] Use `vscode.extensions.getExtension('vscode.references-view')`

### ISSUE THREAD

**Issue by jrieken** [redhat-developer/vscode-java#2645]
VS Code Team here 👋 

In June we have renamed the references viewlet extension. Its NEW name identifier is `vscode.references-view` (old was `ms-vscode.references-view`, different publisher). This extension still uses the old form when calling the `getExtension` API. With the September milestone and release this will NOT work anymore and the new identifier must be used, until then both variants will work. See https://github.com/microsoft/vscode/issues/153320 and https://github.com/microsoft/vscode/issues/152834 for context and details

Let us know if you have follow-up question. 

Happy Coding

**Comment by Eskibear** [comment]
We already uses the new identifier (if exists), and fallback to the old one (for backward compatibility if users are using older version of vscode). 

See corresponding PR https://github.com/redhat-developer/vscode-java/pull/2517

**Comment by jrieken** [comment]
Ok, that's what I thought. Closing this as you seem all set and ready for the change on our end
