### ISSUE TITLE
Support for predefined workingsets for search operations

### ISSUE THREAD

**Issue by gayanper** [redhat-developer/vscode-java#2649]
Add support to switch workingset such as "Main Source", "Test Source" for search operations such as 
- Call Hierarchy
- Type Hierarchy
- Reference Search
- Implementation Search
etc.

A simple implementation would be to introduce a server setting which will define the default workingset, by default this will be empty or include all main and test sources.

Then from the UI we could provide a picker to switch between Main, Test and All which are predefine values. We will show the current workingset in the status bar as well and clicking on that will trigger picker as well.

On the server side this setting will be used in the all Java search queries to define the scope of the search.

##### Environment
- Operating System:
- JDK version: 17
- Visual Studio Code version: 1.70.2
- Java extension version: 1.10.0

**Comment by gayanper** [comment]
@jdneo @rgrunber WDYT about this ?

**Comment by jdneo** [comment]
I think the request makes sense. I would prefer including all main and test sources as the default preference.

**Comment by rgrunber** [comment]
@gayanper I don't think we did type hierarchy, right ?

**Comment by gayanper** [comment]
> @gayanper I don't think we did type hierarchy, right ?

No @rgrunber , Seems the type hierarchy API in JDT don't have a way of providing the search scope.
