### ISSUE TITLE
Load Java Maven Project automatically after creation

### ISSUE THREAD

**Issue by ENate** [redhat-developer/vscode-java#2654]
[provide a description of the issue]

##### Environment
- Operating System: Linux Debian on Codespaces
- JDK version: 17+
- Visual Studio Code version: 1.70.2
- Java extension version: 0.25.1

##### Steps To Reproduce
1. [step 1] Create a Java Multi-Module (with parent POM) or microservices spring boot application (containing many miro-Java Maven projects).
2. [step 2] Refresh the Java projects extension tab.

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Expected Result 
I will expect the newly added Java Maven or Spring project to appear among the existing projects

##### Additional Information
Since the newly created project do not appear (immediately after creation), I have to either restart, close or open Vscode before the newly created Java Maven or Spring project can appear among the Java Maven/spring existing projects in the 'Java Extension' tab.

**Comment by fbricon** [comment]
The Java Projects tab is provided by the Project Manager extension. [Please open a ticket there](https://github.com/microsoft/vscode-java-dependency/issues).
