### ISSUE TITLE
Add support for .class files

### ISSUE THREAD

**Issue by FileOfName** [redhat-developer/vscode-java#2679]
Currently, you can't open .class files in vscode. To be clear I don't mean the "Go To Definition" action I mean plain .class files. If you try and open one then it'll give you a warning. I've found two extensions that sound like they solved the problem but don't:
1. [Java Decompiler](https://marketplace.visualstudio.com/items?itemName=dgileadi.java-decompiler) on "Go To Definition" decompiles the file if it's not already.
2. [Java CFR Decompiler](https://marketplace.visualstudio.com/items?itemName=perennialinnocence.java-cfr-decompiler) decompiles the file into a new .java file but doesn't open it in a read-only editor which means I can edit it and every time I want to close it I get a popup saying "Do you want to save changes?".

The conclusion is that there is no convenient way of opening a decompiled .class file in vscode.

**Comment by rgrunber** [comment]
Seems like exactly what https://github.com/redhat-developer/vscode-java/issues/304 was suggesting. Looks like https://github.com/dgileadi/vscode-java-decompiler/issues/3 mentions some of the issues you're seeing. Seems to me like this is something one of the decompiler extensions should be supporting.

@fbricon , has our view changed on this ?

**Comment by FileOfName** [comment]
>  we're trying to focus on the Java editing experience.

In my opinion, a built-in class decompiler _is_ part of the Java editing experience and either this extension or any other java decompiler extension should support it. For now, I need to use IntelliJ idea for java class files, which is not ideal because I would want to have all functionality in one ide.

**Comment by rgrunber** [comment]
We could potentially do what the `document/definition` request does at [`JDTUtils.searchDecompiledSources`](https://github.com/eclipse/eclipse.jdt.ls/blob/ed4a7cffc08834c47fdc9e3d032c82b924122697/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/NavigateToDefinitionHandler.java#L186A) -> .. -> [`DisassemblerContentProvider.getContent(..)`](https://github.com/eclipse/eclipse.jdt.ls/blob/ed4a7cffc08834c47fdc9e3d032c82b924122697/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/DisassemblerContentProvider.java#L52). On the client side I think we'd just need to register a content provider for the `.class` files.

This might provide some basic support, though it would be nice to have a way to determine if we should be doing this, or simply letting some existing extension handle it.

**Comment by FileOfName** [comment]
Eclipse and IntelliJ idea have it. Why should this extension not have it?

**Comment by rgrunber** [comment]
@JessicaJHee noted that this is going to require creating a custom text editor, but the text document provider only allows ownership of an entire scheme, but not certain files (eg. "*.class" of `file` scheme). See https://github.com/microsoft/vscode/issues/116627
