### ISSUE TITLE
Class files compiled by this extention run  faster than manually compiled with javac command.

### ISSUE THREAD

**Issue by lucidfrontier45** [redhat-developer/vscode-java#2689]
I was about to benchmark this program.

```java
public class App {
    public static void main(String[] args) {
        int n_iters = Integer.parseInt(args[0]);
        long tInit = System.currentTimeMillis();
        int c = 0;

        for (int i = 0; i < n_iters; ++i) {
            for (int j = 0; j < n_iters; ++j) {
                for (int k = 0; k < n_iters; ++k) {
                    if (i * i + j * j == k * k) {
                        ++c;
                    }
                }
            }
        }
        System.out.println(c);
        System.out.println((System.currentTimeMillis() - tInit) / 1000.0);
    }
}
```

I found the class file compiled by VSCode Java extention runs about 4 times faster than one I compiled manually by the `javac` command.

##### Environment
- Operating System: Windows 11 /Debian 11
- JDK version: java 17.0.3.1
- Visual Studio Code version: 1.71.2
- Java extension version: v1.11.0

##### Steps To Reproduce
1. clone git@github.com:lucidfrontier45/java_bench.git
2. open the cloned directory with VSCode
3. confirm VSCode has compiled `bin/App.class`
4. manually compile `src/App.java` to `src/App.class` by `javac src/App.java`.
5. run manually compiled one `java -cp src App 1000`
6. run VSCode compiled one `java -cp bin App 1000`
7. confirm 6 is faster than 5.

[Please attach a sample project reproducing the error]
https://github.com/lucidfrontier45/java_bench

##### Current Result

```
PS C:\Users\lucid\workspace\java_bench> java -cp src App 1000
3755
1.946 sec
PS C:\Users\lucid\workspace\java_bench> java -cp bin App 1000
3755
0.564 sec
```

##### Expected Result

Both of them end in almost same duration.

**Comment by fbricon** [comment]
That's a nice problem to have. If anything this is something caused by the Eclipse ECJ compiler, can you reproduce the same result in Eclipse IDE?

**Comment by tivrfoa** [comment]
Interesting!

On my laptop: `Linux Lenovo-IdeaPad-S145-15API 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Using ecj-4.5.2.jar:

```sh
$ java App 1000
3755
0.297
```
Using `Zulu17.28+13-CA (build 17+35-LTS)`

```sh
$ java App 1000
3755
1.959
```

Bytecode `ecj-4.5.2.jar` x `Zulu17.28+13-CA (build 17+35-LTS)`:

<table>
<tr>
<th>ecj-4.5.2.jar</th>
<th>Zulu17.28+13-CA (build 17+35-LTS)</th>
</tr>
<tr>
<td>

```java
$ javap -c App-ecj.class 
Compiled from "eclipse-compiler-test.java"
class App {
  App();
    Code:
       0: aload_0
       1: invokespecial #8   // Method java/lang/Object."<init>":()V
       4: return

  public static void main(java.lang.String[]);
    Code:
       0: aload_0
       1: iconst_0
       2: aaload
       3: invokestatic  #13  // java/lang/Integer.parseInt:(Ljava/lang/String;)I
       6: istore_1
       7: invokestatic  #19   // java/lang/System.currentTimeMillis:()J
      10: lstore_2
      11: iconst_0
      12: istore        4
      14: iconst_0
      15: istore        5
      17: goto          75
      20: iconst_0
      21: istore        6
      23: goto          66
      26: iconst_0
      27: istore        7
      29: goto          57
      32: iload         5
      34: iload         5
      36: imul
      37: iload         6
      39: iload         6
      41: imul
      42: iadd
      43: iload         7
      45: iload         7
      47: imul
      48: if_icmpne     54
      51: iinc          4, 1
      54: iinc          7, 1
      57: iload         7
      59: iload_1
      60: if_icmplt     32
      63: iinc          6, 1
      66: iload         6
      68: iload_1
      69: if_icmplt     26
      72: iinc          5, 1
      75: iload         5
      77: iload_1
      78: if_icmplt     20
      81: getstatic     #25        // java/lang/System.out:Ljava/io/PrintStream;
      84: iload         4
      86: invokevirtual #29     // Method java/io/PrintStream.println:(I)V
      89: getstatic     #25       // java/lang/System.out:Ljava/io/PrintStream;
      92: invokestatic  #19     // java/lang/System.currentTimeMillis:()J
      95: lload_2
      96: lsub
      97: l2d
      98: ldc2_w        #35        // double 1000.0d
     101: ddiv
     102: invokevirtual #37     // java/io/PrintStream.println:(D)V
     105: return
}
```

</td>

<td>

```java
$ javap -c App.class 
Compiled from "eclipse-compiler-test.java"
class App {
  App();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return

  public static void main(java.lang.String[]);
    Code:
       0: aload_0
       1: iconst_0
       2: aaload
       3: invokestatic  #7      // Method java/lang/Integer.parseInt:(Ljava/lang/String;)I
       6: istore_1
       7: invokestatic  #13    // Method java/lang/System.currentTimeMillis:()J
      10: lstore_2
      11: iconst_0
      12: istore        4
      14: iconst_0
      15: istore        5
      17: iload         5
      19: iload_1
      20: if_icmpge     81
      23: iconst_0
      24: istore        6
      26: iload         6
      28: iload_1
      29: if_icmpge     75
      32: iconst_0
      33: istore        7
      35: iload         7
      37: iload_1
      38: if_icmpge     69
      41: iload         5
      43: iload         5
      45: imul
      46: iload         6
      48: iload         6
      50: imul
      51: iadd
      52: iload         7
      54: iload         7
      56: imul
      57: if_icmpne     63
      60: iinc          4, 1
      63: iinc          7, 1
      66: goto          35
      69: iinc          6, 1
      72: goto          26
      75: iinc          5, 1
      78: goto          17
      81: getstatic     #19                 // Field java/lang/System.out:Ljava/io/PrintStream;
      84: iload         4
      86: invokevirtual #23                 // Method java/io/PrintStream.println:(I)V
      89: getstatic     #19                 // Field java/lang/System.out:Ljava/io/PrintStream;
      92: invokestatic  #13                 // Method java/lang/System.currentTimeMillis:()J
      95: lload_2
      96: lsub
      97: l2d
      98: ldc2_w        #29                 // double 1000.0d
     101: ddiv
     102: invokevirtual #31                 // Method java/io/PrintStream.println:(D)V
     105: return
}
```

</td>
</tr>
</table>

**Comment by fbricon** [comment]
I'm extremely suspicious about microbenchmarks in general, it's not that trivial to do it right. But given that, in this case, the same JVM runs both versions, there must be something really interesting happening behind the scene. 
Some JVM experts would know better. @forax or @adinn maybe?

**Comment by lucidfrontier45** [comment]
The benchmark program I posted was taken from https://stackoverflow.com/questions/67211077/java-vs-rust-performance .

Since this program is mostly composed by primitive variables without any complex memory allocation, I expected it to be as fast as C or Rust. In fact, the class file compiled with ecj runs as fast as C and Rust. I'm not sure why javac cannot do this.

There is an explanation (though I couldn't understand.)

>I can reproduce this when comparing ecj compiled code with javac compiled code. You are right that there are no optimizations happening at compile time. There’s just a subtle difference in the loop compilation, one is combining a conditional forward branch with an unconditional backward branch whereas the other is combining an unconditional forward branch with a conditional backward branch. Shouldn’t make a difference when the runtime optimizer is fully working, but having the entire program in the main method hinders optimizations. 

https://stackoverflow.com/questions/73814988/why-is-java-program-compiled-by-vscode-faster-than-one-created-by-manually-runni#comment130342732_73814988


I also found that in the triple ijk loop, if I extract jk loop as an function, the JVM JIT can optimize it and it runs faster, close to C and Rust.


```java
public class App {
    public static void main(String[] args) {
        int n_iters = Integer.parseInt(args[0]);
        long tInit = System.currentTimeMillis();
        int c = 0;
        for (int i = 0; i < n_iters; i++) {
            c += inner_loop(i, n_iters);
        }
        System.out.println(c);
        System.out.println((System.currentTimeMillis() - tInit) / 1000.0);
    }

    public static int inner_loop(int i, int n_iters) {
        int c = 0;

        for (int j = 0; j < n_iters; ++j) {
            for (int k = 0; k < n_iters; ++k) {
                if (i * i + j * j == k * k) {
                    ++c;
                }
            }
        }

        return c;
    }
}
```

```bash
PS C:\Users\lucid\workspace\java_bench> java -cp src App 1000
3755
0.583
```

**Comment by forax** [comment]
Hi, this is how Java usually works,
it interprets the code and if something is run multiple times, the VM asks the JIT to generate the corresponding assembly code and jump on it.

For Hotspot (the default OpenJDK VM), that optimization occurs either when a method is called several times (in the thousand) or a loop is called several times. The later optimization is called on stack replacement optimization.

Loop optimizations is a vast subject, but depending on the kind of loops, the JITs optimize them differently. I believe that the question here is, does the JIT is able to prove that the loop will finish fast enough so there is no need to insert a check to maybe trigger the GC when the loop run. If the JIT does not know, it has to insert such check (named a safepoint check).

For that, the JIT will try to prove that the loop finish, here, each loop is bounded and iterate over an int, usually it's enough for the JIT to consider that the loop will finish soon enough.

It seems that depending on the bytecode generated either, the JIT struggles to detect the kind of loops or there is a bad interaction between the loop detection and the on stack replacement mechanism, but clearly there is a bug somewhere.

I suggest you to report that as a bug of the hotspot compiler (the JIT).
