### ISSUE TITLE
Would like to be able to recognise java files without maven too

### ISSUE THREAD

**Issue by mmc41** [redhat-developer/vscode-java#27]
Great initiative. I am using VS code more and more and tools like eclipse less and less. I think however, that this is a big limitation: "Recognizes only projects with maven build files on the directory hierarchy.".

Would love to be able to open any java file in code - even if ANT or some other build tool is used. It would be OK to remove some functionality if there is no recognised project for the java file but simple things like syntax highlighting and completion of calls into standard java packages should continue to work.

**Comment by fbricon** [comment]
This is tricky. Basically all the heavy lifting is delegated to the JDT compiler. If the project classpath is incomplete, the compiler will return a *load of compilation errors.

If there's a way to ignore compilation errors, then *maybe* we could provide a very basic support to any java file. But it's not even guaranteed to work.

**Comment by gorkem** [comment]
In the very early days we had this actually. In addition to missing dependencies recognizing the source folder was the first issue. Assuming the root of the workspace is not always a good option and it quickly starts to go in the direction of creating our configuration file for setting up build path which java does not need another one.

**Comment by gorkem** [comment]
See also https://github.com/gorkem/java-language-server/issues/36

**Comment by fbricon** [comment]
Should be fixed with https://github.com/gorkem/java-language-server/commit/031142fda0e9d4133031f20efcd9d3c19939aa56

Autocompletion of JDK classes is available and syntax validation errors will be reported for standalone java files.
