### ISSUE TITLE
How to automatically implement an interface into a class without typing out all methods?

### ISSUE THREAD

**Issue by MatthewMcConnell** [redhat-developer/vscode-java#270]
I couldn't find a way to do this without copying each method, I know it can be done automatically but I'm not sure if this extension can do this.

Any help is much appreciated :)

**Comment by fbricon** [comment]
We're not there yet. We need a Code Action to implement missing methods.

The least bad alternative right now is to use content assist to override each method. The method body will be generated.

**Comment by fbricon** [comment]
@yaohaizh is this something you or someone from your team could address? It's a important usability feature. 
cc @akaroml

**Comment by yaohaizh** [comment]
@fbricon No problem, I talked about this issue with @aeschli before and would like to add this code action.

**Comment by fbricon** [comment]
@yaohaizh PR works really well 

![aug-04-2017 13-30-14](https://user-images.githubusercontent.com/148698/28984747-776b43a4-792d-11e7-81ad-49ba23b357bd.gif)

we should be able to merge it once you fix the couple issues I mentioned in my review.

**Comment by fbricon** [comment]
New code action is available in the latest CI build. You can get the most recent `java-<version>.vsix` file from http://download.jboss.org/jbosstools/jdt.ls/staging/  and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

**Comment by fbricon** [comment]
Be aware though, for the moment, the implemented methods use tab indentation by default. If you use spaces for indentation instead and enabled automatic format on save (`"editor.formatOnSave": true`), then tabs will be replaced by spaces when the file is saved.

Alternatively, you can add the following to your project's `.settings/org.eclipse.jdt.core.prefs`:
```
org.eclipse.jdt.core.formatter.tabulation.char=space
org.eclipse.jdt.core.formatter.tabulation.size=4
```

**Comment by kdlan** [comment]
How to use this feature? I could not find the `Add unimplemented methods` button in my editor

**Comment by yaohaizh** [comment]
@kdlan  See this [gif](https://github.com/redhat-developer/vscode-java/issues/270#issuecomment-320339674)

**Comment by kdlan** [comment]
@yaohaizh 
It works. Thanks

**Comment by 3langn** [comment]
In Android Studio, ctrl + O 
![image](https://user-images.githubusercontent.com/76799726/118220604-48918800-b4a6-11eb-8d6d-5fcaa964e604.png)

**Comment by Eskibear** [comment]
In VS Code, **Source actions**. 


https://user-images.githubusercontent.com/2351748/118221400-1ab14100-b4b0-11eb-8343-4f91af501eb7.mp4
