### ISSUE TITLE
There is no way to automatically prefer the current class member using the [this] object:

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#2705]
There is no way to automatically prefer the current class member using the [this] object:
##### Environment
Operating System: Windows 10
JDK version: 17.0.6
-Visual Studio Code version: 1.77.3
Java extension version: v0.25.10
Java(TM) by Red Hat：v1.17

**Comment by fbricon** [comment]
It works for me:

![Screenshot 2022-09-28 at 16 49 58](https://user-images.githubusercontent.com/148698/192811329-3f26f254-5eb8-4e49-957c-b65d38107abb.png)

Can you share a screenshot of what you see and a sample project to reproduce this issue?

**Comment by zhouxinghong** [comment]
> Can you share a screenshot of what you see and a sample project to reproduce this issue?

Please take a look at the code completion effect in IDEA!
[Video_2022-09-28_235827.zip](https://github.com/redhat-developer/vscode-java/files/9666872/Video_2022-09-28_235827.zip)

**Comment by fbricon** [comment]
yeah so that's the regular behavior you should see in vscode-java. Can you please share your logs? (run `Java: Open all Log Files` command)

**Comment by zhouxinghong** [comment]
I have double-checked the logs and found no error messages or hints! Everything seems to be fine.

**Comment by zhouxinghong** [comment]
Please take a look at the code completion effect in vscode!
[Video_2022-09-29_09.zip](https://github.com/redhat-developer/vscode-java/files/9669925/Video_2022-09-29_09.zip)

**Comment by zhouxinghong** [comment]
Using the this object does not give preference to current class members:
##### Environment
- Operating System: Windows 10
- JDK version: 17.0.6
-Visual Studio Code version: 1.77.3
- Java extension version: 0.25.1
![image](https://user-images.githubusercontent.com/54253524/232216136-dda48fe7-be9f-460e-8269-1f57f46d6942.png)

**Comment by jdneo** [comment]
Cannot repro with your attached snippets.

![image](https://user-images.githubusercontent.com/6193897/232670381-d9ffc8b2-c0b1-477d-a6d7-6d9177f4e1c3.png)

Please check that value of the setting `editor.snippetSuggestions`

And please make sure only extensions in the Java extension pack are installed and try again

**Comment by aitor-gomila** [comment]
Can you clear up what problem you are facing?

Your feature request will be taken into account when other people find it is a problem and upvote it (👍).

Since VSCode is open source, if you have the time, you can fork it and fix it (in this case the java extension). That way you'll have it working already in your machine.

Then it will be easier for the VSCode team to merge your feature request.

**Comment by zhouxinghong** [comment]
Thanks for your answer! terribly sorry! I'm a total JavaScript noob. . . Otherwise I can't wait to fix this problem. . .

**Comment by zhouxinghong** [comment]
> There is no way to automatically prefer the current class member using the [this] object:
> 
> ##### Environment
> Operating System: Windows 10 JDK version: 17.0.6 -Visual Studio Code version: 1.77.3 Java extension version: v0.25.10

There is no way to automatically prefer the current class member using the [this] object:

Environment
Operating System: Windows 10
JDK version: 17.0.6
-Visual Studio Code version: 1.77.3
Java extension version: v0.25.10

**Comment by jdneo** [comment]
>  v0.25.10

This is the version of extension pack, not `redhat.java`

> I'm a total JavaScript noob. . . Otherwise I can't wait to fix this problem. . .

JS is a nice programing language and not hard to learn. I believe most functions of this extension is implemented in https://github.com/eclipse/eclipse.jdt.ls, which is written in Java. As an open-source contributor, you are very encouraged to contribute a fix for any issue you found.

If you are a Java programmer, it should not be that hard. I can't wait to see your fix! 😉

**Comment by zhouxinghong** [comment]
https://user-images.githubusercontent.com/54253524/232711634-6ef1528e-bdfd-4c3b-8a51-2c1accc896dd.mp4

"editor.snippetSuggestions": "top"

**Comment by jdneo** [comment]
> "editor.snippetSuggestions": "top"

You already found one cause.

**Comment by zhouxinghong** [comment]
Java(TM) by Red Hat
v1.17

**Comment by zhouxinghong** [comment]
After testing, it has nothing to do with "editor.snippetSuggestions": "top", even if you set "editor.snippetSuggestions": "none" or "bottom", "inline" etc.

**Comment by zhouxinghong** [comment]
Environment
Operating System: Windows 10
JDK version: 17.0.6
-Visual Studio Code version: 1.77.3
Java extension version: v0.25.10
Java(TM) by Red Hat：v1.17
