### ISSUE TITLE
Wrongly parsed "throws" part of the method signature

### ISSUE THREAD

**Issue by obrejla** [redhat-developer/vscode-java#271]
Hi,

the keyword `throws` in method signature has a wrong token when there is a `try¨resource` statement in the previous method declaration.

##### Environment
- Operating System: MacOS
- JDK version: 1.8
- Visual Studio Code version: 1.14.2
- Java extension version: 0.8.0

##### Steps To Reproduce
1. create `.java` file
2. puth this content in it:
```
public class Foo {
    public String put() {
        try (final InputStream buf = new BufferedInputStream(content)) {
        }
    }
    public void post() throws IOException {}
}
```
3. put the caret on `throws` keyword
4. show `Developer: Inspect TM Scopes `

##### Current Result
```
meta.definition.variable.java
meta.try.resources.java
meta.try.java
meta.method.body.java
meta.method.java
meta.class.body.java
meta.class.java
source.java
```

##### Expected Result¨
Maybe something like
```
storage.modifier.java
meta.throwables.java
meta.method.java
meta.class.body.java
meta.class.java
source.java
```

Thanks!

**Comment by fbricon** [comment]
The Java TextMate bundle is not handled by the vscode-java extension. It is handled by the [VS Code](https://github.com/Microsoft/vscode) team, but ultimately, this bug most likely is caused by the original https://github.com/textmate/java.tmbundle project.

**Comment by fbricon** [comment]
@snjeza can you check if the latest updates of the textmate bundle fix this one?

**Comment by snjeza** [comment]
It works properly with https://github.com/Microsoft/vscode/issues/36708

I have also tested the VS Code master and https://github.com/atom/language-java/blob/master/grammars/java.cson
