### ISSUE TITLE
weird behavior of the Quick Fix; "Surround with try/catch"

### ISSUE THREAD

**Issue by ArithAuth** [redhat-developer/vscode-java#2711]
[weird behavior of auto generate when generating try-catch]

##### Environment
- Operating System: macOS 12.6(Monterey)
- JDK version: java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
- Visual Studio Code version: 1.71.2 (Universal)
- Java extension version: v1.11.0

##### Steps To Reproduce
<pre>
<-- insert
try {

} catch (Exception e) {
    // TODO: handle exception
}
</pre>
<pre>
throw new Exception(); <-- use Quick Fix; "Surround with try/catch"
try {

} catch (Exception e) {
    // TODO: handle exception
}
</pre>
<pre>
try {
    throw new Exception(); <-- surrounded by Quick Fix
} catch (Exception e1) {
    // TODO Auto-generated catch block
    e1.printStackTrace();
}
try {

} catch (Exception e) {
    // TODO: handle exception
}
</pre>

##### Current Result
Even if this variable name "e1" were "e", it won't conflict any other variables.

##### Expected Result
Maybe (Exception e) is correct behavior.

**Comment by rgrunber** [comment]
I'm able to reproduce as well. In fact, this is basically the same as https://bugs.eclipse.org/bugs/show_bug.cgi?id=36365 (which was fixed long ago), but if one applies the refactoring from the bottom-up it's still reproducible.

**Comment by ArithAuth** [comment]
Thank you.
That the fact is interesting. If new Exception() is inside a scope, using Quick Fix above the existing try-catch does not make this behavior.
Well, should I post this to eclipse bug report?

**Comment by ArithAuth** [comment]
I will wait for it to be fixed. I appreciate it.

**Comment by jjohnstn** [comment]
The following issue has been opened: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/353

**Comment by jjohnstn** [comment]
Fix has been merged but the change for try/catch is in JDT UI and will need to either be refactored or copied for jdt-ls.  The problem also existed for surround with try-with-resources and has been fixed as well.  No refactoring needed for the second fix.

**Comment by rgrunber** [comment]
I can have a look at what needs to be copied and adjust it.

**Comment by ArithAuth** [comment]
I found that it have been fixed. Thank you.
