### ISSUE TITLE
File /usr/lib64/jvm/java-11-openjdk-11/lib/ct.sym does not exist

### ISSUE THREAD

**Issue by olgapshen** [redhat-developer/vscode-java#2714]
I have error in "Problems" tab while building the project.

> The project was not built due to "Failed to init ct.sym for /usr/lib64/jvm/java-11-openjdk-11/lib/jrt-fs.jar". Fix the problem, then try refreshing this project and building it since it may be inconsistent.

The error in the log:

> java.io.FileNotFoundException: File /usr/lib64/jvm/java-11-openjdk-11/lib/ct.sym does not exist

##### Environment
- Operating System: openSUSE Leap 15.3
- JDK version: openjdk version "11.0.13" 2021-10-19
- Visual Studio Code version: 1.71.2
- Java extension version: v1.10.0

##### Steps To Reproduce
1. Open project
2. Wait the IDE will build Java project

[Sample project](https://github.com/olgapshen/vscode_openjdk_issue)
[Logs of 2022-10-03](https://github.com/olgapshen/vscode_openjdk_issue/tree/main/logs)

##### Current Result
IDE raises an error

##### Expected Result
IDE doesn't raises an error

##### Additional Informations
I updated the repo, I created dedicate repository for this issue.

![image](https://user-images.githubusercontent.com/13800244/193565946-3eddc993-9338-4208-8f6a-38838e593715.png)

**Comment by olgapshen** [comment]
Mean a while I commented the lines, but I hope, the problem will be solved:

```
// If you use OpenSUSE, OpenJDK and VisualCode
// and you will keep follo lines uncommented,
// you will meet an issue opened for here
// https://github.com/redhat-developer/vscode-java/issues/2714
// So you should comment and uncomment follow lines every time
// you build the project or push it to the CI.
// If you will push the code with commented lines, you will get
// follow error:
// No matching variant of org.valkovesi:posdbschema:x.y.z was found.
// The consumer was configured to find a runtime of a library
// compatible with Java 8, packaged as a jar, and its dependencies
// declared externally, as well as attribute
// 'org.gradle.plugin.api-version' with value '7.5.1'
// TODO: fix the problem
//sourceCompatibility = 1.8
//targetCompatibility = 1.8
```

**Comment by rgrunber** [comment]
Thanks for the detailed info. I'm able to load your project without issues, so I took a closer look at the JVMs I'm using :

```
$ pwd
/usr/lib/jvm 
$
$ find . -name ct.sym
./java-1.8.0-openjdk-1.8.0.345.b01-1.fc36.x86_64/lib/ct.sym
./java-11-openjdk-11.0.16.1.1-1.fc36.x86_64/lib/ct.sym
./java-17-openjdk-17.0.4.1.1-1.fc36.x86_64/lib/ct.sym
./java-18-openjdk-18.0.2.0.9-1.rolling.fc36.x86_64/lib/ct.sym
```

Can you confirm that your `/usr/lib64/jvm/java-11-openjdk-11/` exists and isn't some broken link ? I would think `ct.sym` should be part of the development package (the JDK) as opposed to just the base runtime packages (needs to include the development version of the package (eg. -devel, -dev).

**Comment by olgapshen** [comment]
Hi!
So I had the folder, it wasn't broken link, and yes, it was missing `ct.sym`.
As you predicted, missing file came with `java-11-openjdk-devel` package.
Now I have:

```sh
olga@psheomopensuse:/usr/lib64/jvm> readlink $(readlink $(which java))
/usr/lib64/jvm/jre-11-openjdk/bin/java
olga@psheomopensuse:/usr/lib64/jvm> cd /usr/lib64/jvm
olga@psheomopensuse:/usr/lib64/jvm> ls /usr/lib64/jvm/java-11-openjdk-11/
bin  conf  include  lib  release  tapset
olga@psheomopensuse:/usr/lib64/jvm> find . -name ct.sym
./java-11-openjdk-11/lib/ct.sym
```

The project successfully built.
Thank you very much!
