### ISSUE TITLE
Java intellisense doesn't filter Java API

### ISSUE THREAD

**Issue by olgapshen** [redhat-developer/vscode-java#2718]
Java intellisense doesn't filter Java API basing on `Gradle` `targetCompatibility` option.
I configure follow configuration in `build.gradle`, but I still get newer Java API as `Stream.takeWhile()` in intellisense advices.
In the same time, when I run tests with the `Java Tests Extension`, I get build errors. The logs provided.

```
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

##### Environment
- Operating System: openSUSE Leap 15.3
- JDK version: openjdk version "11.0.13" 2021-10-19
- Visual Studio Code version: 1.71.2
- Java extension version: v1.10.0

##### Steps To Reproduce
1. Open the project in IDE
2. Run the tests

[Simple project](https://github.com/olgapshen/vscode_intellisense_issue)
[Logs](https://github.com/olgapshen/vscode_intellisense_issue/tree/main/logs)

##### Current Result
IDE permits to use newer than 1.8 Java API with an intellisense

##### Expected Result
New functions should be excluded

##### Additional Informations
![изображение](https://user-images.githubusercontent.com/13800244/193913824-4b7165e3-8504-41b8-b664-e2d1c8951cae.png)

**Comment by jdneo** [comment]
Have you tried right click on `build.gradle` and click `Reload Projects`?

**Comment by olgapshen** [comment]
> Have you tried right click on `build.gradle` and click `Reload Projects`?

Yes... no reaction...

**Comment by jdneo** [comment]
Hmm, I cannot reproduce the problem on my side, but I'm on a Windows machine

![Untitled](https://user-images.githubusercontent.com/6193897/194833910-9917e0bf-2360-4daf-908b-434e99d97c27.png)

**Comment by olgapshen** [comment]
Sorry, but we, as the Humankind, expect VScode will work on Linux as well as on Windows.
Please don't disappoint us.

**Comment by snjeza** [comment]
@olgapshen  could you try to add the JDK8 runtime

```
```
"java.configuration.runtimes": [
        ...
         {
             "name": "JavaSE-1.8",
             "path": "<jdk8_home>",
         },
    ],
    ...
```
It works the same on Linux and Windows.

**Comment by olgapshen** [comment]
Yes! I installed JavaSE-1.8 in addition to JavaSE-11 and now th IDE gives me just Java 1.8 API!
Thank you very much!!!

![изображение](https://user-images.githubusercontent.com/13800244/195014972-1f01bdb2-9733-4dc8-8e14-9e6651c0a1cb.png)

```
{
    "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -Xlog:jni+resolve=off -javaagent:\"/home/olga/.vscode/extensions/gabrielbb.vscode-lombok-1.0.1/server/lombok.jar\"",
    "java.server.launchMode": "Standard",
    "files.autoSave": "afterDelay",
    "files.insertFinalNewline": true,
    "java.jdt.ls.java.home": "",
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "/usr/lib64/jvm/java-1.8.0-openjdk/"
        },
        {
            "name": "JavaSE-11",
            "path": "/usr/lib64/jvm/java-11-openjdk-11/",
        },
        {
            "name": "JavaSE-17",
            "path": "/home/olga/java/jdk-17.0.4.1+1",
            "default": true
        }
    ],
    "editor.unicodeHighlight.allowedLocales": {
        "ru": true
    }
}
```

![изображение](https://user-images.githubusercontent.com/13800244/195014681-7bd1512b-9ac6-4de7-99d2-c29ad2558e57.png)
