### ISSUE TITLE
org.eclipse.jdt.core.prefs overridden with default? values even if specified differently

### ISSUE THREAD

**Issue by stefanrybacki** [redhat-developer/vscode-java#2721]
In a gradle project we have:

```
eclipse.jdt.file.withProperties { props ->
        props.setProperty "org.eclipse.jdt.core.circularClasspath", "warning"
        props.setProperty "org.eclipse.jdt.core.compiler.processAnnotations", "enabled"
        props.setProperty "org.eclipse.jdt.core.compiler.annotation.nullanalysis", "disabled"
    }
```

and we have

```
eclipse {
      synchronizationTasks eclipseJdtApt, eclipseJdt, cleanEclipseFactorypath, eclipseFactorypath
    }
```

so running `./gradlew eclipseJdt` for instance generated a correct `org.eclipse.jdt.core.prefs` file in `.settings`.
However, when clean and rebuilding from within vscode the `org.eclipse.jdt.core.prefs` file will be overridden not honoring the settings we set above, specifically `org.eclipse.jdt.core.compiler.annotation.nullanalysis=disabled` is overridden with enabled which causes class hierarchy issues in the compiler.

##### Environment
- Operating System: Windows but running SSH remote in Linux
- JDK version: 11
- Visual Studio Code version: 1.71.2
- Java extension version: 1.11.0

**Comment by snjeza** [comment]
I can't reproduce the issue.
@stefanrybacki could you attach your settings.json, build.gradle and your log. See [Enable logging](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by snjeza** [comment]
@stefanrybacki you may want to take a look at https://github.com/redhat-developer/vscode-java/issues/2712#issuecomment-1268502179

**Comment by stefanrybacki** [comment]
@snjeza thanks for looking into this. Unfortunately I cannot share the gradle and settings file as is, due to company policies. Let me check if I can create a reproducible project without critical information. I will also check if the linked component fixes my compile issues, however it might only the transitive compile problem I get due vscode overriding the jdt file.

**Comment by snjeza** [comment]
@stefanrybacki  Could you try to add

```
{
    "java.compile.nullAnalysis.nonnull": [],
    "java.compile.nullAnalysis.nullable": [],
}
```
to your settings.json?

**Comment by stefanrybacki** [comment]
@snjeza I can confirm that applying those settings and also changes the value of `org.eclipse.jdt.core.compiler.annotation.nullanalysis` to disabled in the jdt file. 
So do those settings override the settings specified in the gradle file?
