### ISSUE TITLE
Are shared indexes on the roadmap?

### ISSUE THREAD

**Issue by DatGuyJonathan** [redhat-developer/vscode-java#2723]
Large projects can take a really long time to index locally which leads to an unproductive dev flow. Intellij's solution to that seems to be shared indexes. Would that be useful for vscode-java extension as well? Or are there other plans to improve indexing?

**Comment by jdneo** [comment]
There is actually a discussion on upstream side, see: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/110
