### ISSUE TITLE
Unable to turn off org.eclipse.jdt.core.compiler.annotation.nullanalysis

### ISSUE THREAD

**Issue by starkos** [redhat-developer/vscode-java#2725]
As v1.11.0, all of our projects are getting an autogenerated `org.eclipse.jdt.core.prefs`. There are lots of new settings applied, but one in particular is killing us dead:

```
org.eclipse.jdt.core.compiler.annotation.nullanalysis=enabled
```

With flag enabled, we get hundreds of issues like these, which all have to do with missing annotations on external code and Java core libraries:

<img width="1031" alt="Screen Shot 2022-10-07 at 10 42 41" src="https://user-images.githubusercontent.com/249247/194580718-97d75f43-7e17-466f-aa84-66820bc5b9e2.png">

If I change the value to `disabled`, the issues go away and we're able to work again. But if I clean the JLS workspace, they all get enabled again, and all of the errors come back.

I've read through the release notes I see that I can specify the Nullable and NonNull attributes, but I don't see any way to set this particular setting. Any help much appreciated!

In case it's helpful, we use SonarLint and Checker Framework on all of our projects. I think you're seeing the annotations and `package-info.java` that we have in place for those tools and assuming that we have this flag enabled.

##### Environment
- Operating System: macOS 12.6 and Windows 11
- JDK version: 11
- Visual Studio Code version: 1.71.2
- Java extension version: 1.11.0

##### Steps To Reproduce

1. Add `@Nullable` and `@NonNull` annotations to an existing Java project
2. Open the project with v1.11.0; the `org.eclipse.jdt.core.prefs` are generated automatically.

Sample project: [JLS.zip](https://github.com/redhat-developer/vscode-java/files/9735080/JLS.zip)

##### Current Result

`org.eclipse.jdt.core.compiler.annotation.nullanalysis=enabled` gets set in `org.eclipse.jdt.core.prefs`.

##### Expected Result

`nullanalysis` would either not get set automatically, or there would be a way to override it, ideally for the entire workspace.

**Comment by snjeza** [comment]
@starkos You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/2712#issuecomment-1268502179

**Comment by CsCherrYY** [comment]
If you want to disable the null analysis entirely, just set `java.compile.nullAnalysis.nonnull` and `java.compile.nullAnalysis.nullable` to empty array in your VS Code settings.

**Comment by rasitayaz** [comment]
I'm experiencing the exact opposite of this issue, want to enable null analysis but whenever set it to enabled inside `org.eclipse.jdt.core.prefs`, it becomes disabled after window reload. Should I create a separate issue for this?
