### ISSUE TITLE
Doing null check on @Nullable functions via ternary operator still gets highlighted with "Potential null pointer access" problem

### ISSUE THREAD

**Issue by MiG98789** [redhat-developer/vscode-java#2727]
Chaining a function after a `@Nullable`-annotated function causes the `@Nullable`-annotated function to get highlighted with "Potential null pointer access" problem, even if a null check was done via ternary operator.

Original issue: [https://github.com/microsoft/vscode/issues/163128](url)

##### Environment
- Operating System: Windows_NT x64 10.0.19044
- JDK version: JDK 17
- Visual Studio Code version: 1.72.0
- Java extension version: 1.11.0

##### Steps To Reproduce
```
public class Test {

    @Nullable
    public String getSomethingNullable() {
        return "";
    }

    public String getSomething() {
        return getSomethingNullable() == null ? getSomethingNullable() : getSomethingNullable().toString();
    }

}
```

`getSomethingNullable()` is annotated with `@Nullable` and will be highlighted despite having a prior null check. This does not occur when doing if-else null check, only when using a ternary operator.

##### Current Result

![image](https://user-images.githubusercontent.com/15458259/194775653-eb4b4891-c6bd-4408-af56-1e5c8583199b.png)

##### Expected Result

`getSomethingNullable()` should not be highlighted.

**Comment by CsCherrYY** [comment]
looks like a JDT null analysis issue. If you replace the method invocation with a temporary variable, there should be no such tips.
```
public String getSomething() {
    String a = getSomethingNullable();
    return a == null ? a : a.toLowerCase();
}
```

**Comment by Treeston** [comment]
The IDE doesn't (and can't easily) realize that `getSomethingNullable()` will return the same value on both invocations.

**Comment by ENate** [comment]
Maybe this setting in your vscode might help:

````
"java.compile.nullAnalysis.nullable": [
        
        "io.micrometer.common.lang.Nullable",
        "javax.annotation.Nullable",
        "org.eclipse.jdt.annotation.Nullable",
        "org.springframework.lang.Nullable"
    ]
```
Not sure if this helps. I only added ``` io.micrometer.common.lang.Nullable ``` because I was running some code written with the new spring boot 3.0.0-RC1

**Comment by MiG98789** [comment]
> The IDE doesn't (and can't easily) realize that `getSomethingNullable()` will return the same value on both invocations.

@Treeston I see what you mean. I think the comparison I made between the if-else condition and ternary operator weren't equivalent. Rather than assigning `getSomethingNullable()` into a variable beforehand (i.e. what @CsCherrYY suggested), this if-else code should've been used instead:
```
if (getSomethingNullable() == null) {
    return getSomethingNullable();
} else {
    return getSomethingNullable().toString();
}
```

Closing this issue now as resolved. Thanks for the help!
