### ISSUE TITLE
Property LineLength.fileExtensions not recognized

### ISSUE THREAD

**Issue by Campano** [redhat-developer/vscode-java#2732]
Using following rule, [available since CheckStyle 8.24](https://checkstyle.org/config_sizes.html#LineLength) triggers the following error:

```xml
	<module name="LineLength"><property name="max" value="256"/>
		<property name="fileExtensions" value="java, js, less"/>
		<property name="ignorePattern" value="^\s*\*.*$"/>
	</module>
```

```
{"message":"cannot initialize module LineLength - Property 'fileExtensions' does not exist, please check the documentation"}
```

##### Environment
- Operating System: MacOS 12.3
- JDK version: 11
- Visual Studio Code version: 1.72.0
- Java extension version: 1.4.1

**Comment by jdneo** [comment]
Where did you observe this message? Is this from the output channel of the Checkstyle extension?
