### ISSUE TITLE
add a way to ignore jvm from other systems imported from cloud 

### ISSUE THREAD

**Issue by sombriks** [redhat-developer/vscode-java#2735]
currently when i use vscode on different machines i login in order to sync my configs acress all my machines. 

an error always pops up due to different architecture and different paths for jvms across those computers

##### Environment

- Operating System: linux, mac, windows
- JDK version: any
- Visual Studio Code version: 1.72.1 
- Java extension version: v1.12.2022101104

##### Steps To Reproduce

1. configure your jvms on mac. let it sync with cloud 
2. checkout a java project on another machin where cloud config is enabled

[Please attach a sample project reproducing the error] any project will do

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

![issue-jvm](https://user-images.githubusercontent.com/556695/195235244-c97dec93-fbe4-47bc-ba88-2696c8965137.jpg)

**Comment by jdneo** [comment]
How do you sync your settings? All the path related settings are marked as `machine-overridable` which should not be synced across machines according to my understanding.

**Comment by sombriks** [comment]
Hello @jdneo , i just did login with accounts and it brought to me my shortcuts, icons, themes and plugins. 

![configs-vscode](https://user-images.githubusercontent.com/556695/195366005-215f6f45-8c59-4652-8df1-265067237714.jpg)

**Comment by sombriks** [comment]
Just opened latest vscode version here on linux and the mac jvm is gone, which is good!

Also opened the not latest version of vscode here on mac and the issue still was here...

<img width="1680" alt="Captura de Tela 2022-10-12 às 22 35 26" src="https://user-images.githubusercontent.com/556695/195478590-0ac0a9d7-fde6-4eee-816a-9e6d35869a17.png">

However i updated it, removed invalid jvms and looks like it's resolved now!

<img width="1680" alt="Captura de Tela 2022-10-12 às 22 49 21" src="https://user-images.githubusercontent.com/556695/195479993-d7f00a54-e4cf-47df-a445-9ac9a4df2398.png">

I think it's safe to close the issue, since the not synced seems to be honored correctly!

**Comment by jdneo** [comment]
Thanks for the updat.
