### ISSUE TITLE
Signature help is not working correctly for parameterized type

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#2739]
Type: <b>Bug</b>

For ResponseEntity<String> type using keyboard method can not see the suggestion details

Extension version: 1.11.0
VS Code version: Code 1.72.2 
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by jdneo** [comment]
Could you provide repro steps?
![image](https://user-images.githubusercontent.com/6193897/195796378-f214e799-c976-4606-9d08-d8042fcef92c.png)

**Comment by zhouxinghong** [comment]
![2022-10-14_164301](https://user-images.githubusercontent.com/54253524/195803966-8fe205e3-0731-477d-936e-bddf4aa200c3.png)

**Comment by jdneo** [comment]
_Please do not file duplicated issues. You can either file new issues if you think it's a different problem (and close the old one), or just append you comments._

I still cannot get your idea, are you talking about the method document is not shown for the `signature help`? If that is the case, you can turn on `java.signatureHelp.description.enabled`

**Comment by zhouxinghong** [comment]
Only the number of method reloads can be displayed, but not the suggestion details.
只能顯示方法重載的個數，但是不能顯示方法描述文檔信息說明。。。

**Comment by jdneo** [comment]
Have you tried turn on `java.signatureHelp.description.enabled`?

**Comment by zhouxinghong** [comment]
> Only the number of method reloads can be displayed, but not the suggestion details. 只能顯示方法重載的個數，但是不能顯示方法描述文檔信息說明。。。
toggleSuggestionDetails

**Comment by zhouxinghong** [comment]
"java.signatureHelp.description.enabled":true,

**Comment by jdneo** [comment]
Maybe you can provide a gif for the problem.

**Comment by nickzhums** [comment]
@zhouxinghong suggest you provide a video or an animation on how to re-produce the problem, thanks

**Comment by zhouxinghong** [comment]
See example.
[Video_2022-10-18_082302.zip](https://github.com/redhat-developer/vscode-java/files/9805429/Video_2022-10-18_082302.zip)

**Comment by zhouxinghong** [comment]
Anyway! There are more errors that I don't want to mention, you don't seem to be using VSCode For Java internally at all and it is impractical to rely entirely on the community to help you develop the product.

**Comment by jdneo** [comment]
Ok, so we are talking about signature help. Sometimes the description part is missing even the `java.signatureHelp.description.enabled` is turned on.

To be specific, when the method has generic type:
![image](https://user-images.githubusercontent.com/6193897/196318635-ff8acc16-7eba-45e5-b5fa-58124ce3db4a.png)

Removing the generic type, it's working
![image](https://user-images.githubusercontent.com/6193897/196318688-01a47c1b-29e6-4370-a0b5-345c51abd0c3.png)
