### ISSUE TITLE
Only the number of method reloads can be displayed, but not the suggestion details.

### ISSUE THREAD

**Issue by zhouxinghong** [redhat-developer/vscode-java#2742]
Extension version: 1.11.0
VS Code version: Code 1.72.2
OS version: Windows_NT x64 10.0.19044

![2022-10-14_164301](https://user-images.githubusercontent.com/54253524/195803966-8fe205e3-0731-477d-936e-bddf4aa200c3.png)
Only the number of method reloads can be displayed, but not the suggestion details.

**Comment by jdneo** [comment]
Duplicated with #2739
