### ISSUE TITLE
Could no find or load class main

### ISSUE THREAD

**Issue by aadolfo8** [redhat-developer/vscode-java#2745]
[provide a description of the issue]

##### Environment
- Operating System: Windows
- JDK version: 19
- Visual Studio Code version: 1.72
- Java extension version: 0.25.3

##### Steps To Reproduce
1. https://github.com/aadolfo8/Spring_Bootcamp/tree/main/Tema%202.%20Spring%20Beans/Scaneo_de_Clases

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Error: Could not find or load main class example.Main    
Caused by: java.lang.ClassNotFoundException: example.Main
PS C:\Users\34638\OneDrive\Escritorio\Todo\Escritorio\Bootcamp\Módulo 5. 
Spring\Tema 2. Spring Beans\Scaneo_de_Clases>

##### Expected Result
Run

**Comment by snjeza** [comment]
I can't reproduce the issue.

![deb](https://user-images.githubusercontent.com/388609/196784635-307a3688-8942-4f9f-8004-eb74a2daf100.png)


@aadolfo8 could you attach your settings.json?

**Comment by aadolfo8** [comment]
I think this is my settings.json

{
    "workbench.colorTheme": "Monokai Dimmed",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    }
}

**Comment by aadolfo8** [comment]
@snjeza

**Comment by snjeza** [comment]
@aadolfo8 could you try to move the project out of OneDrive, for instance, to C:\Users\34638\ ?

**Comment by aadolfo8** [comment]
OMG!! thx you bro the problem its over <3

**Comment by snjeza** [comment]
> idk why i have this fvckn folder i never used one drive

I don't know.
