### ISSUE TITLE
Opening Gradle project with extension removes settings in buildship prefs

### ISSUE THREAD

**Issue by rianadon** [redhat-developer/vscode-java#275]
I am currently using Gradle (with a wrapper, version 4.0) to build a project, and with VS Code the extension works great. All the functionality built into it is amazing. However, when I try to open the project with Eclipse, Eclipse cannot load the project because the extension modifies the `.settings/org.eclipse.buildship.core.prefs` file, removing the `connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)` line.

##### Environment
- Operating System: Windows 10 64-bit (Creator's update)
- JDK version: 1.8.0_131
- Visual Studio Code version: 1.15.0-insider
- Java extension version: 0.8.0

##### Steps To Reproduce
1. Add `connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)` to the end of `.settings/org.eclipse.buildship.core.prefs`
2. Open the folder (it's already been imported as a project) in Eclipse. It loads fine.
3. Open VS Code
4. The prefs file is modified
5. Open the folder in Eclipse. It reports the following error:
```
Invalid Gradle project configuration file: .settings/org.eclipse.buildship.core.prefs
```

##### `.settings/org.eclipse.buildship.core.prefs`:

```build.commands=org.eclipse.jdt.core.javabuilder
connection.arguments=
connection.gradle.user.home=null
connection.java.home=null
connection.jvm.arguments=
connection.project.dir=
derived.resources=.gradle,build
eclipse.preferences.version=1
natures=org.eclipse.jdt.core.javanature
project.path=\:
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
```

The last line gets deleted upon opening VS Code.

##### `build.gradle`:

```
apply plugin: 'java'
apply plugin: 'eclipse'

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.afester:FranzXaver:master'
    compile group: 'org.boofcv', name: 'core', version: '0.26'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['resources']
        }
    }
}

targetCompatibility = '1.8'

jar {
    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

eclipse.classpath.file.whenMerged {
    def container = entries.find { it.path.contains 'org.eclipse.jdt.launching.JRE_CONTAINER' }
    container.accessRules << new org.gradle.plugins.ide.eclipse.model.AccessRule("accessible", "javafx/**")
}
```

Hopefully that's enough. If you need a sample project I can put one together.

**Comment by gorkem** [comment]
@snjeza Can you please check this one?

**Comment by snjeza** [comment]
@rianadon Could you please attach a sample project?
What version of Eclipse/buildship are you using?

**Comment by rianadon** [comment]
Thanks for getting to this!

I'm using Eclipse Neon version 4.6.0, and its buildship is version 1.0.15.v20160425-1638 if that sounds correct.

[Here](https://github.com/rianadon/eclipse-sample-project)'s a sample project. It was created from the Eclipse new Gradle project wizard (more in the readme).

**Comment by snjeza** [comment]
@rianadon 
Buildship 2.1 removes this property. You will face the same issue if you open this project with Oxygen/buildship 2.1 and, after that, with Neon/buildship 1.0
Can you upgrade to buildship 2.1?

**Comment by rianadon** [comment]
I installed Eclipse Oxygen with Buildship 2.1 and it worked (and also removed the property). Thanks for the solution!

I'm not sure whether backwards compatibility should be expected out of buildship, but since this isn't an issue with the extension I'll close this.
