### ISSUE TITLE
Double Package/Class declaration when generating tests

### ISSUE THREAD

**Issue by ViacheslavP** [redhat-developer/vscode-java#2750]
##### Environment
- Operating System: **Ubuntu 22.04**
- JDK version: **openjdk 18.0.2-ea 2022-07-19**
- Visual Studio Code version: **1.73.0-insiders**
- Java extension version: **v1.12.2022102204**

##### Steps To Reproduce
1. Click `Go to Test`
2. Select `Generate`
3. Select all
4. Observe the duplication

Works in any environment
[logs](https://github.com/redhat-developer/vscode-java/files/9846335/3-Language.Support.for.Java.log)

##### Current Result

[Behavior](https://user-images.githubusercontent.com/20426184/197388240-91223cd6-4963-4f46-a675-44f32017d285.webm)

##### Expected Result
![image](https://user-images.githubusercontent.com/20426184/197388275-028f1ce4-9431-4e2f-937f-ebe7a30ed375.png)

**Comment by jdneo** [comment]
I tried to use the petclinic project to reproduce this issue, select `Go to Test` from `PetClinicApplication.java` and generate tests for it, but could not reproduce the issue.

Could you share a sample project for this bug?

**Comment by ViacheslavP** [comment]
Well, it occurs in the petclinic project too. Strangely, the bug may or may not occur in this project.

[Screencast from 10-25-2022 12:24:45 PM.webm](https://user-images.githubusercontent.com/20426184/197737171-c1d32a96-bdd3-4473-90df-6e622c216d61.webm)

**Comment by jdneo** [comment]
I still cannot reproduce it on my side. But looking into the code, it might be related with the execution order of the [test file generation](https://github.com/microsoft/vscode-java-test/blob/92b74614f27cdbc3d3dbe2edfe190716f7277ac1/src/commands/generationCommands.ts#L13) and the [new file hander](https://github.com/redhat-developer/vscode-java/blob/81482a22f966580a66bdce9745116379e0ebd194/src/fileEventHandler.ts#L40).

**Comment by ViacheslavP** [comment]
Ok, I have investigated it. Turns out I have an installation of Metals plugin and the issue is caused by interference between plugins. I do close this. Thanks for all and sorry for opening it in a first place.
