### ISSUE TITLE
Nested switch collapsing broken

### ISSUE THREAD

**Issue by Redex68** [redhat-developer/vscode-java#2751]
Type: <b>Bug</b>

If there is a nested switch inside of another switch, collapsing the code doesn't work properly when we try to collapse a case from the encapsulating switch.

E.g.
Collapsing case 1 here doesn't properly collapse the code:
```
switch (a) {
    case 1:
    {
        switch (a){
            case 2:
                System.out.println("test1");
            case 3: 
                System.out.println("test2");
        }    
    }
    case 4:
    {
        System.out.println("test3");
    }
}
```

It collapses up untill the first occurance of a "case" keyword, regardles of which switch the case belongs to, instead of collapsing at the first occurance of a case keyword from the same switch.

Regular:
![image](https://user-images.githubusercontent.com/92232592/197396248-49f625fe-f258-4d14-99db-fc8777fa5646.png)
Failed collapse:
![image](https://user-images.githubusercontent.com/92232592/197396276-b00d264c-7d0d-457e-aa8e-d5b3613f25bf.png)
Expected behaviour:
![image](https://user-images.githubusercontent.com/92232592/197396510-769ba45b-5093-465b-b5b9-2a89fbcdb41f.png)

Extension version: 1.11.0
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.36GB (6.81GB free)|
|Process Argv|D:\\Marin\\FER\\5. Semestar\\Odabrana poglavlja razvoja programske potpore 1\\Domaci Radovi\\hw02-0036535607 --crash-reporter-id 36b72c21-ca7f-4ca2-94be-5592b850898e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
vsccc:30566497
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30573243

```

</details>

**Comment by jdneo** [comment]
Yes I can reproduce it

![switch](https://user-images.githubusercontent.com/6193897/197430992-a1e0d39f-3681-45ed-9b98-0c93c391ffad.gif)
