### ISSUE TITLE
Linter was using wrong version

### ISSUE THREAD

**Issue by heolo1** [redhat-developer/vscode-java#2754]
Type: <b>Bug</b>

I set my Java runtimes to Java 17, 18, and 19. I set all the names and paths properly, but some reason, this extension still is using Java 11 only to lint, even after a restart. I set my JAVA_HOME variable to a Java-18 installation, but the linter still refuses to change to Java-11. The status bar in the bottom right says JavaSE11, even though the path it shows is my java18 installation and the only installion in my settings.json lists it as JavaSE18. I've spent severalhours trying to find the issue to no avail.

Extension version: 1.11.0
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.10.131-19115-g2e2fb0ed324d
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7Y75 CPU @ 1.30GHz (4 x 1607)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|14.20GB (14.19GB free)|
|Process Argv|/home/ebh/cs/ap/1025 --crash-reporter-id 1a005c14-e531-4298-9a39-f7595bd97242|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|X-Generic|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537

```

</details>

**Comment by heolo1** [comment]
Update: 
Before, whenever I tried to set the correct runtime on the Configure Java Runtime page, I could set the three versions that I specified above, but when I clicked out of the selection box, it defaulted back to only displaying the text "11". I'm not sure why this happened, as I don't even have Java 11 installed on this computer.
Now, the Configure Java Runtime page doesn't even show up, with the error: "Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.."

**Comment by snjeza** [comment]
@heolo1 What project are you using?

**Comment by heolo1** [comment]
Sorry for the late reply. I am not using a project manager or anything of the sort. I am just using a folder with a couple of Java files in it.

**Comment by snjeza** [comment]
@heolo1 Could you show your settings.json?
