### ISSUE TITLE
Language support wont start

### ISSUE THREAD

**Issue by maxtarquini** [redhat-developer/vscode-java#2756]
Type: <b>Bug</b>

Java language support wonnt start. No logs available and no build status available. The icon on the navbar continue cycling but nothig happen

Extension version: 1.11.0
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.19.16-200.fc36.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1270P (16 x 4076)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.06GB (23.87GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2e590ceb-5cb5-41c4-a1a8-982a893d6130|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by snjeza** [comment]
@maxtarquini could you attach a project example reproducing the error?

**Comment by maxtarquini** [comment]
@snjeza every maven project. everything where working until 2 days ago. Anyway, this is a simple maven project u did for some students.
[esempi.zip](https://github.com/redhat-developer/vscode-java/files/9873006/esempi.zip)

**Comment by maxtarquini** [comment]
![immagine](https://user-images.githubusercontent.com/44928818/198133885-9a9ce858-d2eb-49cb-976c-2009f79ecc59.png)
Some more informations. running tasks: configure vscode prompt for input but nothing else happen. Disabling java language support by red hat the problem is fixed but vscode is not usefull anymore :(

**Comment by snjeza** [comment]
@maxtarquini Could you try the following:
- close VS Code
```
$ rm -rf ~/.vscode/extensions/redhat.jav* # remove VS Code extension
```
- start VS Code and reinstall Language Support for Java(TM) by Red Hat

**Comment by maxtarquini** [comment]
@snjeza did it and nothing change. I did many many tests:
removed vscode, .vscode and .config/Code folders and intalled an older version (1.71) for vs code. **Nothing changed**
removed  .vscode and .config/Code folder, installed java extensions pack and downgraded to older version. **Nothing changed**
vscode update to last version using older version for language pack. **Nothing changed**

May be the rpm installer install something somewhere i don't know?
Once i cleaned .vscode folder and .config/Code folder did i removed everything?
Is there some king of cache?

**Comment by maxtarquini** [comment]
@snjeza some more info. If i ask for build status i got this:

Error: there is no registered task type 'Java'. Did you miss installing an extension that provides a corresponding task provider?
Error: there is no registered task type 'Java'. Did you miss installing an extension that provides a corresponding task provider?

The problem seems to appear when language support try to build the workspace.

**Comment by maxtarquini** [comment]
@snjeza i'm available for a remote session if you desire.

**Comment by snjeza** [comment]
@maxtarquini could you run 
```
$ ls ~/.vscode/extensions
```

**Comment by maxtarquini** [comment]
@snjeza 
╰─$ ls ~/.vscode/extensions
redhat.java-1.11.0-linux-x64                               vscjava.vscode-java-dependency-0.20.0
visualstudioexptteam.intellicode-api-usage-examples-0.2.6  vscjava.vscode-java-pack-0.25.3
visualstudioexptteam.vscodeintellicode-1.2.29              vscjava.vscode-java-test-0.37.1
vscjava.vscode-java-debug-0.45.0                           vscjava.vscode-maven-0.39.0

**Comment by maxtarquini** [comment]
@snjeza if is use ctrl+shiftp+p task: rerun last task result is still the same

_Error: there is no registered task type 'Java'. Did you miss installing an extension that provides a corresponding task provider?_

When i manually use task: run build task vscode shows the messages in the picture
![immagine](https://user-images.githubusercontent.com/44928818/198146027-72533137-0bb7-46d9-92b9-474b52028201.png)

**Comment by snjeza** [comment]
@maxtarquini could you try
- close VS Code

```
 $ rm -rf ~/.config/Code/User/globalStorage/redhat.java/
```
- start VS Code

**Comment by maxtarquini** [comment]
@snjeza nothing changed :(

**Comment by maxtarquini** [comment]
@snjeza i created another user, logged in, executed vscode and created java project. 
Everything works well. May be there is something that may affect vscode within user folder?

**Comment by snjeza** [comment]
@maxtarquini you can try to remove ~/.config/Code and ~/.vscode and restart VS Code

**Comment by maxtarquini** [comment]
@snjeza as you can read in the previous comment i did it  tens of times and nothing change. I'm now moving my productivity to a new user (vscode works as exepected). Will leave old user active for further investigations. My idea is to start cleaning user folder step by step until i find where the problem is.

**Comment by maxtarquini** [comment]
Hello @snjeza as a good noews i found the reason why the extension was blocked. It depends by a environment file. I need to understand which env variable is creating the problem but seems that i definitively fixed.
I can consider this issue closed.

**Comment by pouriamoosavi** [comment]
I have the same issue.
If you found the fix would you please share it here?

**Comment by houtaru** [comment]
Hi, I encountered the same issue:
Here are logs from Output:
```
[Error - 4:35:02 PM] Client Language Support for Java (Syntax Server): connection to server is erroring. Shutting down server.
[Error - 4:35:02 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at S.shutdown (/home/user/.vscode/extensions/redhat.java-1.23.0-linux-x64/dist/extension.js:2:1148447)
	at S.stop (/home/user/.vscode/extensions/redhat.java-1.23.0-linux-x64/dist/extension.js:2:1148028)
	at S.stop (/home/user/.vscode/extensions/redhat.java-1.23.0-linux-x64/dist/extension.js:2:1310318)
	at S.handleConnectionError (/home/user/.vscode/extensions/redhat.java-1.23.0-linux-x64/dist/extension.js:2:1154535)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 4:35:02 PM] Language Support for Java (Syntax Server) client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 4:35:02 PM] Connection to server got closed. Server will restart.
false
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[Error - 4:35:02 PM] Language Support for Java (Syntax Server) client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 4:35:02 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 4:35:02 PM] Connection to server got closed. Server will restart.
false
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[Error - 4:35:02 PM] Client Language Support for Java (Syntax Server): connection to server is erroring. Shutting down server.
[Error - 4:35:02 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at S.shutdown (/home/user/.vscode/extensions/redhat.java-1.23.0-linux-x64/dist/extension.js:2:1148447)
	at S.stop (/home/user/.vscode/extensions/redhat.java-1.23.0-linux-x64/dist/extension.js:2:1148028)
	at S.stop (/home/user/.vscode/extensions/redhat.java-1.23.0-linux-x64/dist/extension.js:2:1310318)
	at S.handleConnectionError (/home/user/.vscode/extensions/redhat.java-1.23.0-linux-x64/dist/extension.js:2:1154535)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 4:35:02 PM] Language Support for Java (Syntax Server) client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 4:35:02 PM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 4:35:02 PM] Connection to server got closed. Server will restart.
false
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[Error - 4:35:02 PM] Language Support for Java (Syntax Server) client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Error - 4:35:02 PM] Restarting server failed
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
[Info  - 4:35:02 PM] Connection to server got closed. Server will restart.
false
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[Error - 4:35:02 PM] Connection to server got closed. Server will not be restarted.
[Error - 4:35:02 PM] Language Support for Java (Syntax Server) client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by pouriamoosavi** [comment]
Turns out our issue was related to windows region/region format setting. It seems that this extension has some issues with Persian/Arabic region formats. 

Can anybody please explain why this happens?

**Comment by tankpow** [comment]
Is the problem with java runtime configure? 
See offcial: https://code.visualstudio.com/docs/java/java-project#_configure-runtime-for-projects
