### ISSUE TITLE
weird intellisense behavior

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#2758]
### Discussed in https://github.com/redhat-developer/vscode-java/discussions/2749

<div type='discussions-op-text'>

<sup>Originally posted by **rafaeltuelho** October 21, 2022</sup>
I noticed a weird behavior when trying IntelliSense on a `java.util.Optional`. Look at this gif recording.
![java-vscode-optional-intellisense](https://user-images.githubusercontent.com/39063/197224002-bf274121-d36b-4cfa-b8ea-c537193d676d.gif)

```
macOS Monterey
Version 12.6
Java openjdk version "17.0.4" 2022-07-19
VSCode Version: 1.72.0
```</div>

**Comment by fbricon** [comment]
This is most likely a manifestation of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/495

**Comment by rgrunber** [comment]
Added https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-off-lombok-support since determining this was happening in JDT-LS as well was tricky.

**Comment by rhystedstone** [comment]
I believe the same issue occurs within comments as well:
![image](https://user-images.githubusercontent.com/12123847/210672391-73cfbc5c-821e-45ef-a74a-c6bc546344b8.png)

**Comment by fbricon** [comment]
@rgrunber / @snjeza  can you check if https://github.com/eclipse-jdt/eclipse.jdt.core/issues/495 is available in the latest jdt.ls/vscode-java build and close this issue if it's fine?

**Comment by snjeza** [comment]
> can you check if https://github.com/eclipse-jdt/eclipse.jdt.core/issues/495 is available in the latest jdt.ls/vscode-java build and close this issue if it's fine?

@fbricon it isn't available in I20230629-1800 - https://github.com/eclipse/eclipse.jdt.ls/blob/da3292f8481561ec3ccaa39cf3021ec4f2487101/org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target#L32

We should update the target platform to https://download.eclipse.org/eclipse/updates/4.29-I-builds/I20230726-1800/
I have created https://github.com/eclipse/eclipse.jdt.ls/pull/2778
