### ISSUE TITLE
Configuring java project stuck in 69%

### ISSUE THREAD

**Issue by jcolladosp** [redhat-developer/vscode-java#2763]
This happens when I open a new cloned Java project
It gets stuck in Opening java Project...

##### Environment
- Operating System: Ubuntu 20.04
- JDK version: 17
- Visual Studio Code version:
- Java extension version: 1.12

##### Steps To Reproduce
1. Open a Java project

Complete log en verbose mode: https://pastebin.com/JqA4iTWs

##### Current Result

![image](https://user-images.githubusercontent.com/9121186/198332870-618218e6-424e-4e50-9f91-02e930492fee.png)
![image](https://user-images.githubusercontent.com/9121186/198332888-2793858e-4646-4c9c-b3d0-cee07ebd1788.png)

![image](https://user-images.githubusercontent.com/9121186/198332970-49b34048-8860-48c5-bc1b-37bbbe7feeb4.png)

**Comment by snjeza** [comment]
@jcolladosp Could you show Java Stack trace?

```
$ jps
...
40189 org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
...
$ jstack -l 40189
```

**Comment by jcolladosp** [comment]
@snjeza 
I think the problem is when I have 2 java projects open

```
$ jps
28161 Jps
25858 org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
17846 BootLanguageServerBootApp
27463 org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
13832 sonarlint-ls.jar
27849 sonarlint-ls.jar
25819 org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
13643 org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
27503 org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
```
```
jstack -l 27503

https://pastebin.com/GBL1gwTb
```

**Comment by snjeza** [comment]
@jcolladosp Could you try https://github.com/snjeza/vscode-test/raw/master/java-1.12.1.vsix
