### ISSUE TITLE
Java .devenviorement xhtml bug while trying to edit project 

### ISSUE THREAD

**Issue by Help3rL** [redhat-developer/vscode-java#2766]
Java ignores all xhtml file updates.

##### Environment
- Operating System: mcr.microsoft.com/devcontainers/java:8-buster
- JDK version: Java 8 202-346
- Visual Studio Code version: 1.72.2
- Java extension version: 0.25.3

##### Steps To Reproduce
1. Open code in docker container with [Dev contianers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
2. Run debugger
3. try editing any xhtml file to see changes in page 

##### Current Result
Ignores xhtml changes 
##### Expected Result
To react to xhtml changes on xhtml modification without rebuilding application
##### Additional Informations
Logs and additional information you can find in [this](https://github.com/microsoft/vscode-remote-release/issues/7399) where person refered me to this github.

**Comment by jdneo** [comment]
Sorry maybe a stupid question, are we talking about JSP related things here?

**Comment by Help3rL** [comment]
Sorry for late reply,
@jdneo yeah thats corect, and keeps ignoring xhtml changes untill java recompile, on most pc's but one.

**Comment by jdneo** [comment]
JSP is not supported now, let's track this request by https://github.com/redhat-developer/vscode-java/issues/138
