### ISSUE TITLE
provide command to build the workspace manually

### ISSUE THREAD

**Issue by ansyral** [redhat-developer/vscode-java#277]
right now workspace is built automatically, and for single file case, the default project won't be built until the file is edited and saved in vscode, could we provide a command to trigger the build manually?

**Comment by gorkem** [comment]
I am reluctant to expose the jdt's internal build to end user, because jdt builds do not really produce artifacts that users can use. What exactly is the use case that you want to support here since this build has little value for end-user?

**Comment by ansyral** [comment]
@gorkem This is mainly for single file debug. if user opens a single file in vscode, if he/she never edits/saves the file, the default project which has a link to the single file won't be built and the classpath might be missing the .class file. Besides, it would be nice to build the workspace before launching a debugger in case of compile errors

**Comment by fbricon** [comment]
Can you provide a PR for the VS Code side as well, so we can test how it behaves?

**Comment by ansyral** [comment]
@fbricon  added #298

**Comment by fbricon** [comment]
The new `Force Java compilation` (id: `java.workspace.compile`) command is bound to the `Shift+Alt+b` shortcut

**Comment by fbricon** [comment]
Thanks @ansyral!

**Comment by liudonghua123** [comment]
@fbricon, Thanks, you save me almost a day.
