### ISSUE TITLE
"Cannot be resolved" after adding maven dependency in module_info.java

### ISSUE THREAD

**Issue by dvargas135** [redhat-developer/vscode-java#2771]
After a couple attempts to declare the dependency in the module_info.java it just throws the error "cannot be resolved to a module". I added the dependency using the tool "Maven: Add a dependency...", my pom.xml got updated but when I declared it on the module_info.java it didn't seem to do anything.

If I delete the module_info.java file, the import works just fine.

##### Environment
- Operating System: Windows 10 ltsc 21h2
- JDK version: jdk-19
- Visual Studio Code version: 1.72.2
- Java extension version: `Extension Pack for Java v0.25.4`, `Maven for Java v0.39.1`

##### Steps To Reproduce
1. Open Java Project with Maven
2. Add a dependency from Maven
3. Declare the dependency in the module_info.java

Sample project: https://github.com/dvargas135/sample-project (it was just a new java project with FXML)

**Comment by jdneo** [comment]
Close but feel free to leave comments if you have more questions.
