### ISSUE TITLE
Recommendation actions not working

### ISSUE THREAD

**Issue by plause** [redhat-developer/vscode-java#2772]
`vscode-java` will recommend the Dependency Analytics plugin when pom.xml file is opened. There are three actions users can choose:

* **Install**, ok, install it;
* **Never**, no, thanks and don't bother me again;
* **Later**, busy coding, next time.

##### Environment
- Operating System: Linux
- JDK version: 17
- Visual Studio Code version: 1.72.2
- Java extension version: v1.12.0

##### Steps To Reproduce
1. open a pom file(pom.xml);
2. a popup shows and recommends Dependency Analytics;
3. choose any of the actions: install, never, later;
4. repeat step 1 for checks.

##### Current Result
- Action names are **lower cased**;
- Your choice is ignored, **nothing happens**;
- The recommendation **repeats** next time even you choose 'Never'.

##### Expected Result
- Install the recommended plugin on action 'Install';
- Remain silent always on action 'Never';
- Ask again next time on action 'Later';

##### Additional Informations
The commit https://github.com/redhat-developer/vscode-java/commit/d6a2fd53b97f8518ece92cbae4d4b580c1aafe69 changed enum names to lower case,

https://github.com/redhat-developer/vscode-java/blob/7b3f1b16e8828dd4dca1f726c99cbc7acd5110e2/src/recommendation/handlerImpl.ts#L18-L22

which **breaks the comparison** between user choice (from enum names, L55) and enum members (values, L51, L57).

https://github.com/redhat-developer/vscode-java/blob/7b3f1b16e8828dd4dca1f726c99cbc7acd5110e2/src/recommendation/handlerImpl.ts#L45-L63

User choices stored in globalState:

````
sqlite> SELECT value FROM ItemTable WHERE key = 'redhat.java';
{"recommendationUserChoice":{"redhat.fabric8-analytics":"never"}}
````

**Comment by rgrunber** [comment]
This was defnitely an issue so thanks for filing. It was addressed in https://github.com/redhat-developer/vscode-java/issues/2892 .
