### ISSUE TITLE
The quickfix "Create class 'X'" generates duplicated code snippets

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#2774]
Reproduce steps:
1. Hover on an unresolved type, and click quickfix "Create class 'X'".
![image](https://user-images.githubusercontent.com/14052197/199374927-0ede353e-97a5-4877-a9b1-cd01d1b078ae.png)

2. It generates duplicated code snippets.
![image](https://user-images.githubusercontent.com/14052197/199375033-528e665d-4e6b-4e10-8d10-19ee827723c0.png)

**Comment by hopehadfield** [comment]
Newer issue #2939 identified the same bug. This was fixed via #2944.
