### ISSUE TITLE
Support making the output folder being the same as the source folder for unmanaged folder projects

### ISSUE THREAD

**Issue by JLP04** [redhat-developer/vscode-java#2786]
According to the documentation, the setting `java.project.outputPath` should be "A relative path to the **workspace** where stores the compiled output. Only effective in the WORKSPACE scope. The setting will NOT affect Maven or Gradle project.", but when I set it, it is instead giving me a path relative to the workspaceStorage folder for the project. 

##### Environment
- Operating System: macOS Ventura 13.0
- JDK version: 17.0.4.1
- Visual Studio Code version: 1.73.0
- Java extension version: 1.12.0

##### Steps To Reproduce
1. Set` java.project.outputPath` to something like `../FOLDERNAME` with FOLDERNAME being anything. 
2. Run the `Java: Configure Classpath` command. 
3. Observe that the Output location is shown as a folder in workspaceStorage. 

[Please attach a sample project reproducing the error]
[Test.zip](https://github.com/redhat-developer/vscode-java/files/9953365/Test.zip)
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging) 
[Logs.zip](https://github.com/redhat-developer/vscode-java/files/9953398/Logs.zip)

##### Current Result
The compiled .class files are being created somewhere in workspaceStorage. 
##### Expected Result
The compiled .class files will be created in the workspace folder.

**Comment by JLP04** [comment]
Just using `Test` works for me. But what I was trying to do with `../Test` was have it output the .class files in the project directory instead of a folder inside of that called `Test`.

**Comment by jdneo** [comment]
> have it output the .class files in the project directory instead of a folder inside of that called Test

Could you share a screenshot about how your project folder structure looks like in VS Code?

**Comment by JLP04** [comment]
My project folder structure is the same as the test project I attached to this issue. It's all the .java files in the top folder of the project. But, if I try to set `java.project.outputPath` to something like `./`, it doesn't work. The language server doesn't initialize properly and then it starts getting really confused.

**Comment by jdneo** [comment]
That's another limitation that the output path cannot be the same as the source folder. You can set it to sth like `bin`.

**Comment by jdneo** [comment]
> why is there a limitation against the output path being the same as the source folder?

Thank you for asking that. I just rechecked the related logic and it seems that there is no such limitation (Sorry for the wrong information I mentioned before).

> See: https://github.com/eclipse-jdt/eclipse.jdt.core/blob/e7f6aea141844d2ac14ef94a9e3493ce121d398a/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/ClasspathEntry.java#L1840

BTW, could I take this issue request as: `Support making the output folder being the same as the source folder for unmanaged folder projects`?

**Comment by JLP04** [comment]
It might be useful for CS students, especially in cases where it's expected that you upload both the bytecode and the source files.
