### ISSUE TITLE
Inline variable gone from suggestions

### ISSUE THREAD

**Issue by stefanrybacki** [redhat-developer/vscode-java#2791]
It seems the option to inline a variable is gone from the available suggestions. It used to be available I am sure but cannot find it anymore when displaying suggestions.

##### Environment
- Operating System: Linux
- JDK version: 11
- Visual Studio Code version: 1.73.0
- Java extension version: 1,12,0

##### Steps To Reproduce
1. In a java function write:
```
var x=1;
var y=x+1;
```
2. go to `x` in the second line and trigger suggestions
3. find there is no option to inline variable x

##### Current Result
inline variable option is not available

##### Expected Result
inline variable option is available

**Comment by jdneo** [comment]
Could you share a sample project? It seems working on my side.

![image](https://user-images.githubusercontent.com/6193897/201246911-61a056dc-6edc-42c1-9800-845f3b6e9492.png)

**Comment by stefanrybacki** [comment]
@jdneo that is interessting, this is what I get
![image](https://user-images.githubusercontent.com/29799350/201312756-84386fa7-7968-4a38-9afe-f407601b96c7.png)

Could it be some kind of setting then?

**Comment by jdneo** [comment]
Yes, it's really strange. I don't think there is any setting that will affect this.

How is your code looks like? What if you declare the type explicitly instead of using `var`?

**Comment by stefanrybacki** [comment]
Code looks like the example given:
![image](https://user-images.githubusercontent.com/29799350/201463324-ddb17233-da59-4751-baa7-a170e3e3e772.png)

I just tested with `int` instead of `var`, same suggestions. No inline local variable suggestion though. Really weird.

**Comment by CsCherrYY** [comment]
can you find other inline suggestions here? e.g., hover on `test`, can you find `Inline Method` suggestion?
![image](https://user-images.githubusercontent.com/45906942/201562813-8bdff417-8011-4882-b45c-ba6cb9ae7e28.png)

**Comment by stefanrybacki** [comment]
@CsCherrYY thanks for the suggestion, 

in fact I can see inline suggestions for constants
![image](https://user-images.githubusercontent.com/29799350/201646963-163d3803-8c73-461c-bd3a-c4b098e1ba54.png)

as well as methods:
![image](https://user-images.githubusercontent.com/29799350/201647048-cdc37227-7449-4791-8020-840637fa2477.png)

**Comment by geon** [comment]
You might have vscode set to using the projects version of tsc. That's sensible, since the errors you get in the editor are the same as when you compile. But you also can't use newer features.
![Screenshot 2024-09-26 at 09 05 31](https://github.com/user-attachments/assets/0be8d7d3-8e9e-4030-945f-be51b8bdcf22)
