### ISSUE TITLE
java compiler level not set correctly after opening new project

### ISSUE THREAD

**Issue by martinlippert** [redhat-developer/vscode-java#2797]
I am observation a problem with setting the correct Java compilation level when opening a project for the first time.

Here are the details:
I clone the repo and open VSCode from this folder:
https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/tanzu-java-web-app

The corresponding project get s imported correctly. The project explorer shows a JavaSE-11 JRE for the project, which is correct. Nevertheless, without doing anything else, the JDT preferences for the project do not contain any information about the Java language level, therefore the sources are compiled for Java 17 (probably because the tooling runs on a JDK17 by default).

Here is the content of the preferences file after opening the project:

```
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.annotation.nonnull=org.springframework.lang.NonNull
org.eclipse.jdt.core.compiler.annotation.nullable=org.springframework.lang.Nullable
org.eclipse.jdt.core.compiler.annotation.nullanalysis=enabled
org.eclipse.jdt.core.compiler.problem.nullAnnotationInferenceConflict=warning
org.eclipse.jdt.core.compiler.problem.nullReference=warning
org.eclipse.jdt.core.compiler.problem.nullSpecViolation=warning
org.eclipse.jdt.core.compiler.problem.potentialNullReference=warning
```

As a workaround, I can fix this by executing the "Reload Projects" action from the context menu of the `pom.xml` file. That causes the preferences to contain the Java 11 compilation level just fine and everything works from there on. The same happens when changing the `pom.xml` file manually.

Nevertheless, the compilation level should be set correctly after opening the project and without changing the file or executing the action.

Side note: the `pom.xml` file of the project contains a property `java.version`, which is something that is specific for Spring Boot, but gets propagated into `maven.compiler.source/target` properties in the effective pom, so this is not a problem with the configuration of the java compilation level in the project itself. The same behavior/problem can be reproduced when the `maven.compiler.source/target` properties are configured in the `pom.xml` directly.

**Comment by fbricon** [comment]
Can you reproduce the issue in Eclipse?

**Comment by CsCherrYY** [comment]
There was a bug about forgetting the compiler level in https://github.com/redhat-developer/vscode-java/issues/2764, and it has been fixed in the newest pre-release version. 

@martinlippert could you try if it works in the pre-release version? Just switch to the pre-release version and clean workspace then.

**Comment by martinlippert** [comment]
> There was a bug about forgetting the compiler level in #2764, and it has been fixed in the newest pre-release version.
> 
> @martinlippert could you try if it works in the pre-release version? Just switch to the pre-release version and clean workspace then.

@CsCherrYY I tried the pre-release and it seems to fix this issue indeed. Awesome! Many many thanks for the quick feedback on this!!! So closing this as a duplicate of https://github.com/redhat-developer/vscode-java/issues/2764
