### ISSUE TITLE
java build failed :The import javax.annotation.processing.Generated cannot be resolved

### ISSUE THREAD

**Issue by magicsong** [redhat-developer/vscode-java#2799]
[provide a description of the issue]
my project(target version JDK8) using querydsl which use code-generation, it is OK using jdk8 to build and run. however vscode-java using higher jdk to build project(which will also regenerate the code), the generate code has wrong import "javax.annotation.proccessing.Generated" instead of "javax.annotation.Generated"(right one). As a result, java test cannot run the project in vscode. 

##### Environment
- Operating System: MACOS
- JDK version: jdk-17.0.1.jdk/
- Visual Studio Code version:
- Java extension version: v1.12.0

##### Steps To Reproduce
1. [step 1] use latest spring data
2. [step 2] use querydsl

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

can i parse args to build like "--release 8"

**Comment by snjeza** [comment]
@magicsong you can try to add 
```
<options>
    <querydsl.generatedAnnotationClass>javax.annotation.Generated</querydsl.generatedAnnotationClass>
</options>
```
to apt-maven-plugin. For example,
```
<plugin>
    <groupId>com.mysema.maven</groupId>
    <artifactId>apt-maven-plugin</artifactId>
    <version>1.1.3</version>
    <executions>
        <execution>
            <goals>
                <goal>process</goal>
            </goals>
            <configuration>
                <outputDirectory>target/generated-sources/java</outputDirectory>
                <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
                <options>
		    <querydsl.generatedAnnotationClass>javax.annotation.Generated</querydsl.generatedAnnotationClass>
	        </options>
            </configuration>
        </execution>
   </executions>
</plugin>
```

See http://querydsl.com/static/querydsl/latest/reference/html/ch03s03.html

**Comment by magicsong** [comment]
@snjeza yeah, it works! thanks !
