### ISSUE TITLE
"bin" Directories Created in Every Gradle Module Folder

### ISSUE THREAD

**Issue by EarthCitizen** [redhat-developer/vscode-java#2801]
This extension creates a bunch of unwanted "bin" directories in all of the Gradle submodule directories.

##### Environment
- Operating System: macOS
- JDK version: 11
- Visual Studio Code version: 1.72.2
- Java extension version: v0.21.1

##### Steps To Reproduce
1. Open Gradle project with multiple modules
2. Observe creation of unwanted "bin" directories

##### Current Result

Creates a bunch of unwanted and inconvenient "bin" directories.

##### Expected Result

Does not create a bunch of unwanted "bin" directories.

##### Additional Informations

This issue was closed, but as can be seen by the large volume of comments after it was closed, the issue is not resolved:

https://github.com/redhat-developer/vscode-java/issues/634

**Comment by jdneo** [comment]
See https://github.com/eclipse/buildship/issues/1131

**Comment by EarthCitizen** [comment]
Looks like that leads back to this:

https://github.com/redhat-developer/vscode-java/issues/1615

I guess the wait then is for this project to add a configuration option to change the directory? The workaround there means that I would have to use the eclipse plugin in Gradle despite not needing it?

**Comment by jdneo** [comment]
The main problem is that the compiled output from JDT might be different from the build tools like Maven/Gradle.

Whether adding an option to change the output location would solve the problem is not clear to me.

> The workaround there means that I would have to use the eclipse plugin in Gradle despite not needing it?

As for now, you can setup the eclipse plugin in your build.gradle as a workaround

**Comment by jdneo** [comment]
Close as dup with #1615.

You can vote for #1615 to help us prioritize.

**Comment by adamsmd** [comment]
For others having a similar issue, here is a workaround I posted in another issue: https://github.com/redhat-developer/vscode-java/issues/634#issuecomment-2485241295
