### ISSUE TITLE
When there are multiple scripts in the folder, they will all be compiled

### ISSUE THREAD

**Issue by xxc-zsz** [redhat-developer/vscode-java#2807]
If I have multiple scripts in my folder and I only want to run one of them, hitting runjava will compile them all. At this point, if there are errors in other scripts, there will be errors, even if the current script I want to run does not have errors.

I have two errors in DemoTwo.java. When I run DemoOne.java, a pop-up window will appear. Click proceed to compile and run demoone normally.

![image](https://user-images.githubusercontent.com/108051416/202604298-c2fd2ddb-b227-46f5-a522-0da851d2d377.png)

I know I can click proceed to continue, but this is not the best solution.

**Comment by jdneo** [comment]
This can be fixed with https://github.com/microsoft/java-debug/pull/459.

@testforstephen FYI

**Comment by testforstephen** [comment]
Yes, this use case will be covered by the debugger PR.

**Comment by fbricon** [comment]
@jdneo can you move this issue to https://github.com/microsoft/java-debug/issues ?

**Comment by jdneo** [comment]
@fbricon Sorry I can't. Only issues between repositories owned by the same user or organization account can be transferred.

**Comment by jdneo** [comment]
Close since it has been fixed by https://github.com/microsoft/java-debug/pull/459.
