### ISSUE TITLE
Support multi root workspaces

### ISSUE THREAD

**Issue by aeschli** [redhat-developer/vscode-java#281]
In VSCode we are working on supporting multi root workspaces. The Java extension should also support this.
- Users can now work with files from more than root folder at the same time. We call these folders  'workspace folders'.
- Workspace folders can be added and removed
- Each workspace folder can have its own settings, overriding the global settings.
-New extensions API to get workspace folders and for notifications of added/removed workspace folders
- New extensions API to access resource specific configurations

Support for this is in vscode insiders since a few weeks.
- New [extension APIs]( https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts)
- Proposed language server API for [workspaceFolders](https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.workspaceFolders.proposed.ts) and [configuration](https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.configuration.proposed.ts)

**Comment by floschnell** [comment]
VS Code will display a warning "Classpath is incomplete. Only syntax errors will be reported" when opening Java files within a multi root workspace environment.
This probably is due to the fact that the "pom.xml" is not at the root anymore, but within the directory of that project.

**Comment by gorkem** [comment]
@aeschli What are the changes on the LSP implementation related to this? Is there a specific LSP client we need to use on the extension?

**Comment by aeschli** [comment]
These are new proposed protocol additions:
- [workspaceFolders](https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.workspaceFolders.proposed.md)
- [resource configuration](
https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.configuration.proposed.md)

The latest vscode-languageclient already supports these requests.

**Comment by fbricon** [comment]
Was released as part of vscode-java 0.14.0
