### ISSUE TITLE
When viewing hover Javadoc, `{@link ...` that points to a binary class doesn't display as a link

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-java#2810]
If you hover over a Java element that has Javadoc (eg. class, method, static/non-static member) that has a `{@link org.example.ClassName}` in it, the `{@link` is rendered as a link and is clickable if the class is a source file, but not if it is a binary file. For example, if you put `{@link java.lang.String}` in a Javadoc, then the hover documentation doesn't display a clickable link.

##### Environment
- Operating System: RHEL 8.6
- JDK version: The bundled Linux JustJ
- Visual Studio Code version: 1.73.1
- Java extension version: v1.13.2022111903 (prerelease)

##### Steps To Reproduce
1. Make a class file:
```java
public class MyClass {

  /**
   * {@link java.lang.String}
   */
  public void myMethod() {
    myMethod();
  }
}
```
2. Hover over `myMethod()` to see the Javadoc

##### Current Result
The reference to `java.lang.String` is not clickable.

##### Expected Result
The reference to `java.lang.String` is a clickable link that opens `java.lang.String` in read-only mode.

##### Additional Informations
You can see in the extension output under the hover response that it tries to link to `java.lang.String` like this:
```
[java.lang.String](jdt://contents/java.base/java.lang/String.class?=quarkius/%5C/home%5C/davthomp%5C/.sdkman%5C/candidates%5C/java%5C/17.0.3-tem%5C/lib%5C/jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/17%5C/docs%5C/api%5C/=/=/maven.pomderived=/true=/%3Cjava.lang%28String.class#140)
```

**Comment by rgrunber** [comment]
The `jdt://` scheme is meant to be resolved by JDT-LS. We register a client-side provider at https://github.com/redhat-developer/vscode-java/blob/ccb75b154c03928d60a2ef423ddfd960fb3b43d9/src/providerDispatcher.ts#L29-L30 , which ends up calling `java/classFileContents` on the server side to resolve the content.

**Comment by datho7561** [comment]
We might not be able to fix this. It looks like VS Code used to be support opening URIs with any scheme at one point, and a few extensions relied on this, but it was patched out:
https://github.com/microsoft/vscode/issues/151720

Then a feature request was opened to provide the old functionality as a feature, but it didn't receive enough votes and was auto closed:
https://github.com/microsoft/vscode/issues/152716
