### ISSUE TITLE
The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by pragyesh7753** [redhat-developer/vscode-java#2815]
Type: <b>Bug</b>

Whenever I open VS Code it is giving me this message --->  The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.
![image](https://user-images.githubusercontent.com/116973800/204026664-5fccf566-e47c-44f9-a04c-77ee8fe7c5d5.png)

Extension version: 1.12.0
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.23GB free)|
|Process Argv|--crash-reporter-id 975d6eaf-4dc5-48bc-8ef6-ce5c5f80bd52|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by rgrunber** [comment]
When this happens, could you go into the command palette and run : "Java: Open All Log Files". There should be a few log files opened. Do any of them show errors from around the time this occurs ?
