### ISSUE TITLE
Loading all the time when hovering class or method

### ISSUE THREAD

**Issue by simahao** [redhat-developer/vscode-java#2816]
[provide a description of the issue]

##### Environment
- Operating System: win10
- JDK version: 11
- Visual Studio Code version: 1.73.1
- Java extension version: 1.12.0

##### Steps To Reproduce
1. open hadoop project
2. hover class or method with mouse

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
![image](https://user-images.githubusercontent.com/4537287/204180749-4bbd9c00-8943-4773-b7b3-c41faff08724.png)

show loading all the time, there is error in the following output log.

2022-11-28 10:40:16.393 [error] [redhat.java] provider FAILED
2022-11-28 10:40:16.394 [error] Error: The request (id: 233, method: 'textDocument/hover') has been cancelled
    at c:\Users\zh\.vscode\extensions\redhat.java-1.12.0-win32-x64\dist\extension.js:2:1036471
    at c:\Users\zh\.vscode\extensions\redhat.java-1.12.0-win32-x64\dist\extension.js:2:1036765
    at Immediate.<anonymous> (c:\Users\zhanghao\.vscode\extensions\redhat.java-1.12.0-win32-x64\dist\extension.js:2:1037130)
    at processImmediate (node:internal/timers:466:21)

server verbose log

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:20.679
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:20.814
!MESSAGE >> document/documentSymbol

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:20.897
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:20.900
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:20.901
!MESSAGE >> textDocument/inlayHint

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:36.590
!MESSAGE >> textDocument/inlayHint

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:36.882
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:36.884
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:36.885
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-11-28 10:55:37.079
!MESSAGE >> java/findLinks

**Comment by jdneo** [comment]
Have you tried to increase the memory allocation size of the JVM? You can do this by updating the VS Code setting `java.jdt.ls.vmargs`, change the Xmx to sth like `-Xmx2G`

**Comment by simahao** [comment]
> Have you tried to increase the memory allocation size of the JVM? You can do this by updating the VS Code setting `java.jdt.ls.vmargs`, change the Xmx to sth like `-Xmx2G`

Yes, I have increased memory size like -Xmx5G, but it doesn't work.

**Comment by jdneo** [comment]
It's working on my side
![image](https://user-images.githubusercontent.com/6193897/204753300-d9195c04-e336-4946-8c2b-784e1b72fcb2.png)

Is it working if you only enable the extensions contained in the `Extension Pack for Java`?
