### ISSUE TITLE
`Reload Projects` There is no obvious accuracy bar

### ISSUE THREAD

**Issue by mozhuanzuojing** [redhat-developer/vscode-java#2821]
i want to rebuild all projects. then click ``Reload Projects` from `build.gradle`.  but i can't see obvious accuracy bar. 

##### Environment
- Operating System:win11
- JDK version:17
- Visual Studio Code version:1.73
- Java extension version:1.13

##### Steps To Reproduce
1. open a gradle project
2. click `Reload Projects` on `build.gradle`

![image](https://user-images.githubusercontent.com/63572041/205043583-4585d736-50a0-4056-bb85-67222225221d.png)

##### Current Result
It's hard to find the progress of the recompilation
##### Expected Result
A compilation progress bar is displayed in the lower-right corner

**Comment by jdneo** [comment]
It's by design. It will appear only when the current active document is a java-like file. For example, .java, .class, pom.xml, *.gradle, ...

**Comment by mozhuanzuojing** [comment]
thank you
