### ISSUE TITLE
Combined classpath view

### ISSUE THREAD

**Issue by varnem2** [redhat-developer/vscode-java#2829]
Is it possible to change the view so that it just shows the classpath and ignores all other files? I dislike the separation between src/test/** and src/main/** and feel like that should be within a single view. Any thoughts or ways I can do this? This is true with both the "flat view" and the "hierarchical view" as well.

##### Environment
- Operating System: Windows 10
- JDK version: OpenJDK 11
- Visual Studio Code version:
![image](https://user-images.githubusercontent.com/42308489/205988149-51842e87-0b9e-41d9-a6a3-c92b27838c07.png)
- Java extension version:
- v1.14.2022120603 

##### Steps To Reproduce
1. Step 1 Create a fresh project using <https://start.spring.io> underneath create files/folder(s) under the following path src/test/java/**.java this pattern follows the standard conventions around maven.
2. Open project with VSCode

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

![image](https://user-images.githubusercontent.com/42308489/205988922-4a67d943-24a9-4237-b2ef-9948fee4ebde.png)

##### Expected Result

![image](https://user-images.githubusercontent.com/42308489/205989177-fd01d267-5a2b-46d4-bb5c-e17e0acdd3e1.png)

**Comment by varnem2** [comment]
I can attach logs and sample project as well, but I feel like it's unnecessary.. Not really a bug, but more of an ask if the feature exists/feature request.

**Comment by jdneo** [comment]
Thanks, let's track this request in https://github.com/microsoft/vscode-java-dependency/issues/706
