### ISSUE TITLE
Source code is unavailable, and was generated by the Fernflower decompiler.

### ISSUE THREAD

**Issue by longxt666** [redhat-developer/vscode-java#2833]
In a local maven project, clicking on a class or method does not jump to the Java source.

##### Environment
- Operating System: WSL2 Ubuntu22.04
- JDK version: openjdk-17
- Visual Studio Code version: 1.73.1
- Java extension version: v1.13.0

##### Steps To Reproduce
1. Use a locallly-installed dependency in your maven project
2. Attempt to view it's source or docs

##### Current Result
Before run `mvn source:jar install` , we just see:
`// Failed to get sources. Instead, stub sources have been generated by the disassembler. // Implementation of methods is unavailable.`

Now, we just see:
`// Source code is unavailable, and was generated by the Fernflower decompiler.`

##### Expected Result
A complete source code.

##### Additional Informations
related issue: #2143

**Comment by tangllty** [comment]
Hi
I'm sorry for my bad english but you can fix it with the following configuration

setting.json config
![2022-12-27_04-34](https://user-images.githubusercontent.com/58468628/209581786-c9c966a5-9f8a-48fb-8043-aa0f06bcd34a.png)

I'm having the same issues and I'm not sure if it's the right way to do it.
