### ISSUE TITLE
Unable to remove source path after 'git mv'

### ISSUE THREAD

**Issue by jrte** [redhat-developer/vscode-java#2835]
I had 2 folders A and B in my workspace included as source paths. Moved B into a subtree of A using 'git mv', committed. After commit I see 2 errors listed, persistently:

- Project 'jrte' is missing required source folder: 'test'
- The project cannot be built until build path errors are resolved

The "Java: List All Java Source Paths" command still lists both folders in the source path
The "Java: Clean Java Language Server Workspace" command did nothing to resolve the problems
Removing the project from the workspace and adding it again was unhelpful

The source path appears to be immutable. Is there no way to clear this condition?

##### Environment
- Operating System: WIndows 10
- JDK version: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
- Visual Studio Code version: 1.74.0
- Java extension version: Extension Pack for Java  v0.25.7 

##### Steps To Reproduce
1. [step 1] create 2 java source trees in root of workspace (<project-root>/A/com/something/other; <project-root>/B/com/something/else)
2. [step 2] add roots of both source trees to source path (2 entries in source path: <project-root>/A; <project-root>/B)
3. git mv B/something/else A/something
4. git add ...
5. git commit ...
6. rebuild project
7. dead in the water with nowhere to go :(

See attached log. Message is:
>!ENTRY org.eclipse.jdt.ls.core 4 0 2022-12-08 22:10:44.400
>!MESSAGE Error occured while building workspace. Details: 
> message: Project 'jrte' is missing required source folder: 'test'; code: 964; resource: F:/Ubuntu/git/jrte;
 >message: The project cannot be built until build path errors are resolved; code: 0; resource: F:/Ubuntu/git/jrte;

##### Additional Informations
[ - Copy.log](https://github.com/redhat-developer/vscode-java/files/10191238/-.Copy.log)

**Comment by jrte** [comment]
Update: I fixed this by accident when I deleted the workspace folder from <don't-recall-very-long-path-tho>. Then created a new workspace from previous <project-root>. No harm done, apparently. But there must be a better way to resolve this condition. Why must "source path" be "read only"?

**Comment by jrte** [comment]
It is back. It returned after the app threw a IllegalFormatException while I was debugging it in VSCode. Normally the debuger traps these, but this time it just terminated the debugging session and informed me of the Java exit code. Not entirely sure but I think I was in the debugger the first time this happened as well. 

![image](https://user-images.githubusercontent.com/24707461/206906249-afba0788-7ec2-438f-9127-f836129a41ee.png)

[project-folders.txt](https://github.com/redhat-developer/vscode-java/files/10202332/project-folders.txt)
[redhat.client.log.zip](https://github.com/redhat-developer/vscode-java/files/10202334/redhat.client.log.zip)
[redhat.state.vscdb.zip](https://github.com/redhat-developer/vscode-java/files/10202335/redhat.state.vscdb.zip)

The redhat zips are from ...\AppData\Roaming\Code\User\workspaceStorage\e8c33cc174493a47b77edc8cc8913c4a

**Comment by jdneo** [comment]
From the pasted log, looks like your project is an Eclipse project.

Is there a `.classpath` file in your project folder? If yes, try update the source paths in that file.

**Comment by jrte** [comment]
Cool. That did the trick! Thanks for helping out. 

That said, I'm surprised that VSCode is that cosy with Eclipse. I switch between Eclipse (in Ubuntu) and VSCode (in WIndows) frequently. I hope not to have any issues with cross-contamination. But perhaps RedHat is supporting both platforms with common code in the Extension Pack for Java? 

As far as I'm concerned you can close this issue. Thanks for helping out.

**Comment by jdneo** [comment]
> But perhaps RedHat is supporting both platforms with common code in the Extension Pack for Java?

The extension should work across different platforms. If there are any problems, file an issue to let us know. :)
