### ISSUE TITLE
debug java via run button should perform auto discovery of localhost accessible java processes

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#2840]
when debugging a springboot or quarkus app or any other already running java app it would be nice that "Debug Java" could offer to scan for localhost running java processes to automatically connect to.

**Comment by jdneo** [comment]
@maxandersen Could you file it to https://github.com/microsoft/vscode-java-debug/issues?

**Comment by maxandersen** [comment]
Done. 

https://github.com/microsoft/vscode-java-debug/issues/1275
