### ISSUE TITLE
Inconsistency between the linter and the javac compiler 

### ISSUE THREAD

**Issue by wzw0101** [redhat-developer/vscode-java#2843]
The linter told me a inner class cannot be resolved but the javac compile can compile this code.

##### Environment
- Operating System: Windows_NT x64 10.0.19045
- JDK version: 17.05
- Visual Studio Code version: v1.74.2
- Java extension version: v1.13.0

##### Steps To Reproduce
1. copy the following code in a file named Inheritance.java into the vscode editor
```
public class Inheritance {
    public static void main(String[] args) {
        Sub sub = new Sub();
        sub.method1();
    }

    static class Outer<T> {
        class Inner {
            void sayHi() {
                System.out.println("hello world!");
            }
        }
    }

    static class Sub extends Outer<Sub.Inner> {
        void method1() {
            Inner inner = new Inner();
            inner.sayHi();
        }
    }
}
```

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:11.727
!MESSAGE Initializing Java Language Server 1.18.0.202212010413

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.892
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.893
!MESSAGE Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.navigate.openTypeHierarchy, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.resolveStackTraceLocation, java.project.getAll, java.reloadBundles, java.project.isTestFile, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.edit.stringFormatting, java.project.getSettings, java.project.updateSourceAttachment, java.project.resolveWorkspaceSymbol, java.project.upgradeGradle, java.project.createModuleInfo, java.protobuf.generateSources, java.project.resolveSourceAttachment, java.project.addToSourcePath, java.completion.onDidSelect]

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.894
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.894
!MESSAGE Non-Static Commands: [java.intellicode.completion, java.intellicode.completion.resolve, java.intellicode.enable]

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.895
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.896
!MESSAGE Non-Static Commands: [vscode.java.checkProjectSettings, vscode.java.isOnClasspath, vscode.java.fetchUsageData, vscode.java.validateLaunchConfig, vscode.java.resolveInlineVariables, vscode.java.resolveClassFilters, vscode.java.resolveMainMethod, vscode.java.resolveClasspath, vscode.java.resolveBuildFiles, vscode.java.resolveMainClass, vscode.java.updateDebugSettings, vscode.java.resolveSourceUri, vscode.java.fetchPlatformSettings, vscode.java.buildWorkspace, vscode.java.startDebugSession, vscode.java.inferLaunchCommandLength, vscode.java.resolveElementAtSelection, vscode.java.resolveJavaExecutable]

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.897
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.898
!MESSAGE Non-Static Commands: [java.project.refreshLib, java.project.list, java.project.generateJar, java.project.getMainClasses, java.getPackageData, java.resolvePath]

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.899
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.900
!MESSAGE Non-Static Commands: [vscode.java.test.findJavaProjects, vscode.java.test.findTestPackagesAndTypes, vscode.java.test.findTestTypesAndMethods, vscode.java.test.resolvePath, vscode.java.test.findTestLocation, vscode.java.test.get.testpath, vscode.java.test.findDirectTestChildrenForClass, vscode.java.test.navigateToTestOrTarget, vscode.java.test.junit.argument, vscode.java.test.generateTests]

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.901
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.902
!MESSAGE Non-Static Commands: [java.maven.initializeSearcher, java.maven.searchArtifact, java.maven.addDependency, java.maven.controlContext]

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.909
!MESSAGE Starting org.eclipse.m2e.core

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.910
!MESSAGE Started org.eclipse.m2e.core 1ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.912
!MESSAGE ProjectRegistryRefreshJob finished 1ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.913
!MESSAGE Starting org.eclipse.buildship.core

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.944
!MESSAGE Started org.eclipse.buildship.core 31ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.961
!MESSAGE RepositoryRegistryUpdateJob finished 1ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:13.999
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:15.894
!MESSAGE Workspace initialized in 1934ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:15.944
!MESSAGE >> initialization job finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:15.952
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:16.011
!MESSAGE >> java/buildWorkspace (incremental)

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:16.021
!MESSAGE >> New configuration: {java={home=D:\Java\jdk-17.0.5, jdt={ls={java={home=null}, vmargs=-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -Xlog:disable, lombokSupport={enabled=true}, protobufSupport={enabled=true}, androidSupport={enabled=false}}}, errors={incompleteClasspath={severity=ignore}}, configuration={checkProjectSettingsExclusions=false, updateBuildConfiguration=interactive, maven={userSettings=null, globalSettings=null, notCoveredPluginExecutionSeverity=warning}, workspaceCacheLimit=90.0, runtimes=[{name=JavaSE-17, path=D:\Java\jdk-17.0.5, default=true}]}, trace={server=verbose}, import={maven={enabled=true, offline={enabled=false}}, gradle={enabled=true, wrapper={enabled=true}, version=null, home=null, java={home=null}, offline={enabled=false}, arguments=null, jvmArguments=null, user={home=null}, annotationProcessing={enabled=true}}, exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**], generatesMetadataFilesAtProjectRoot=false}, maven={downloadSources=false, updateSnapshots=false}, eclipse={downloadSources=false}, referencesCodeLens={enabled=false}, signatureHelp={enabled=true, description={enabled=false}}, implementationsCodeLens={enabled=false}, format={enabled=true, settings={url=null, profile=null}, comments={enabled=true}, onType={enabled=true}, insertSpaces=true, tabSize=4.0}, saveActions={organizeImports=true}, project={referencedLibraries=[lib/**/*.jar], importOnFirstTimeStartup=automatic, importHint=true, resourceFilters=[node_modules, \.git], encoding=ignore, exportJar={targetPath=${workspaceFolder}/${workspaceFolderBasename}.jar}}, contentProvider={preferred=null}, autobuild={enabled=true}, maxConcurrentBuilds=1.0, recommendations={dependency={analytics={show=true}}}, completion={maxResults=0.0, enabled=true, guessMethodArguments=true, favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], filteredTypes=[java.awt.*, com.sun.*, sun.*, jdk.*, org.graalvm.*, io.micrometer.shaded.*], importOrder=[#, java, javax, org, com, ], postfix={enabled=true}}, foldingRange={enabled=true}, progressReports={enabled=true}, codeGeneration={hashCodeEquals={useJava7Objects=false, useInstanceof=false}, useBlocks=false, generateComments=false, toString={template=${object.className} [${member.name()}=${member.value}, ${otherMembers}], codeStyle=STRING_CONCATENATION, skipNullValues=false, listArrayContents=true, limitElements=0.0}, insertionLocation=afterCursor}, selectionRange={enabled=true}, showBuildStatusOnStart={enabled=notification}, server={launchMode=Hybrid}, sources={organizeImports={starThreshold=99.0, staticStarThreshold=99.0}}, imports={gradle={wrapper={checksums=[]}}}, templates={fileHeader=[], typeComment=[]}, references={includeAccessors=true, includeDecompiledSources=true}, typeHierarchy={lazyLoad=false}, settings={url=null}, symbols={includeSourceMethodDeclarations=false}, quickfix={showAt=line}, inlayHints={parameterNames={enabled=literals, exclusions=[]}}, codeAction={sortMembers={avoidVolatileChanges=true}}, compile={nullAnalysis={nonnull=[javax.annotation.Nonnull, org.eclipse.jdt.annotation.NonNull, org.springframework.lang.NonNull], nullable=[javax.annotation.Nullable, org.eclipse.jdt.annotation.Nullable, org.springframework.lang.Nullable], mode=interactive}}, cleanup={actionsOnSave=[]}, debug={logLevel=warn, settings={showHex=false, showStaticVariables=false, showQualifiedNames=false, showLogicalStructure=true, showToString=true, maxStringLength=0.0, numericPrecision=0.0, hotCodeReplace=manual, enableRunDebugCodeLens=true, forceBuildBeforeLaunch=true, onBuildFailureProceed=false, console=integratedTerminal, exceptionBreakpoint={skipClasses=[]}, stepping={skipClasses=[], skipSynthetics=false, skipStaticInitializers=false, skipConstructors=false}, jdwp={limitOfVariablesPerJdwpRequest=100.0, requestTimeout=3000.0, async=auto}, vmArgs=}}, silentNotification=false, dependency={showMembers=false, syncWithFolderExplorer=true, autoRefresh=true, refreshDelay=2000.0, packagePresentation=flat}, help={firstView=auto, showReleaseNotes=true, collectErrorLog=false}, test={defaultConfig=, config={}}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:16.024
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 4 0 2022-12-20 13:53:16.313
!MESSAGE Error occured while building workspace. Details: 
 message: Sub.Inner cannot be resolved to a type; code: 16777218; resource: D:/wzw/projects/java/test/Inheritance.java; line: 15
 message: Inner cannot be resolved to a type; code: 16777218; resource: D:/wzw/projects/java/test/Inheritance.java; line: 17
 message: Inner cannot be resolved to a type; code: 16777218; resource: D:/wzw/projects/java/test/Inheritance.java; line: 17

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:16.892
!MESSAGE >> Updating classpath for project test_17694abe

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:16.984
!MESSAGE Reconciled 1. Took 1 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:16.985
!MESSAGE >> textDocument/inlayHint

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:16.988
!MESSAGE >> textDocument/semanticTokens/full

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.104
!MESSAGE begin problem for /Inheritance.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.106
!MESSAGE 3 problems reported for /Inheritance.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.145
!MESSAGE Validated 1. Took 140 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.177
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.498
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.504
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.509
!MESSAGE >> watchers registered

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.605
!MESSAGE >> workspace/executeCommand java.project.getAll

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.607
!MESSAGE >> workspace/executeCommand java.project.getAll

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.611
!MESSAGE >> workspace/executeCommand vscode.java.test.get.testpath

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.612
!MESSAGE >> workspace/executeCommand java.project.listSourcePaths

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.629
!MESSAGE >> workspace/executeCommand java.project.getClasspaths

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:17.631
!MESSAGE >> workspace/executeCommand java.project.getSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:18.373
!MESSAGE >> workspace/executeCommand java.intellicode.enable

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:19.726
!MESSAGE >> textDocument/semanticTokens/full

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:56.376
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:56.411
!MESSAGE >> workspace/executeCommand java.project.getSettings

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:56.413
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:56.415
!MESSAGE >> textDocument/inlayHint

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:56.576
!MESSAGE >> workspace/executeCommand vscode.java.resolveMainMethod

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:56.581
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:56.727
!MESSAGE >> workspace/executeCommand vscode.java.test.findTestTypesAndMethods

!ENTRY java-debug 1 0 2022-12-20 13:53:56.755
!MESSAGE Starting com.microsoft.java.debug.plugin

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:56.826
!MESSAGE >> textDocument/inlayHint

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:56.837
!MESSAGE >> workspace/executeCommand vscode.java.test.resolvePath

!ENTRY org.eclipse.jdt.ls.core 1 0 2022-12-20 13:53:57.130
!MESSAGE >> document/foldingRange

##### Current Result
In the editor, red squiggly lines are shown under "Sub.Inner" on line 15 and under "Inner" on line 17, saying that Inner cannot be resolved to a type.

##### Expected Result
The code should be correct since I can compile it with the javac command without errors or warnings. "hello world" is printed by compiling and running the code in cmd.

**Comment by snjeza** [comment]
@wzw0101 I can reproduce issue with javac

```
$ javac -version
javac 17.0.5

$ javac Inheritance.java 
Inheritance.java:15: error: type Outer does not take parameters
    static class Sub extends Outer<Sub.Inner> {
                                  ^
Inheritance.java:17: error: cannot find symbol
            Inner inner = new Inner();
            ^
  symbol:   class Inner
  location: class Sub
Inheritance.java:17: error: cannot find symbol
            Inner inner = new Inner();
                              ^
  symbol:   class Inner
  location: class Sub
3 errors
```

**Comment by wzw0101** [comment]
> @wzw0101 I can reproduce issue with javac
> 
> ```
> $ javac -version
> javac 17.0.5
> 
> $ javac Inheritance.java 
> Inheritance.java:15: error: type Outer does not take parameters
>     static class Sub extends Outer<Sub.Inner> {
>                                   ^
> Inheritance.java:17: error: cannot find symbol
>             Inner inner = new Inner();
>             ^
>   symbol:   class Inner
>   location: class Sub
> Inheritance.java:17: error: cannot find symbol
>             Inner inner = new Inner();
>                               ^
>   symbol:   class Inner
>   location: class Sub
> 3 errors
> ```

Sorry, a type parameter after the Outer class definition was missing. I have corrected the code but the issue remains. Can you retry with it please?

**Comment by snjeza** [comment]
@wzw0101 I can reproduce it in VS Code and Eclipse. It works when using OpenJDK (javac).

**Comment by snjeza** [comment]
A related upstream issue: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/612

**Comment by rgrunber** [comment]
I tried this out and don't see any errors being emitted in a recent version. The referenced upstream issue is fixed as well.
