### ISSUE TITLE
Code completion does not show results for all substring matches

### ISSUE THREAD

**Issue by RayyanRiaz** [redhat-developer/vscode-java#2851]
Hi,

Currently, the code completion does not show the results where the partially typed string is in the middle/end. For instance, if I type `Supplier`, I cannot see `IntSupplier` or `BooleanSupplier` in the suggestions. Please see the image below:
![image](https://user-images.githubusercontent.com/8856864/210174616-60da6a08-a14c-4c3f-99d4-aa372583b766.png)
In contrast, a screenshot from Intellij shows what I expect to see in the suggestions.

<img src="https://user-images.githubusercontent.com/8856864/210174525-a8d62a9e-9126-41df-b72d-95a0eecd175d.png" width="600px"/>

Here is the relevant settings file:

```json
    "editor.suggest.matchOnWordStartOnly": false,
    "editor.quickSuggestions": {
        "other": "on",
        "comments": "on",
        "strings": "on"
    }
```

##### Environment
- Operating System: Ubuntu 22.10
- JDK version: openjdk 17.0.5 2022-10-18
- Visual Studio Code version: 1.74.2
- Java extension version: v0.25.7

**Comment by snjeza** [comment]
@RayyanRiaz you can try to set
```
"java.jdt.ls.vmargs": "-Djdt.codeCompleteSubstringMatch=true  <your VM Args>",
```
to your settings.json

**Comment by RayyanRiaz** [comment]
@snjeza, thanks a lot, works perfectly :)
