### ISSUE TITLE
openjdk 17 "is not compatible"

### ISSUE THREAD

**Issue by bitsofinfo** [redhat-developer/vscode-java#2852]
latest vscode, latest extension

![image](https://user-images.githubusercontent.com/1743646/210288684-a8b58b44-2645-43e5-bdeb-55b27358e209.png)

this is a legit java home:
```
  "java.jdt.ls.java.home": "/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home",
  "java.home": "/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home",
  "java.configuration.runtimes": [

    {
      "name": "openjdk-17",
      "path": "/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home",
      "default": true
    }
]
```

```
$ /Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home/bin/java -version
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment Homebrew (build 17.0.4+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.4+0, mixed mode, sharing)
```

**Comment by jdneo** [comment]
@bitsofinfo Do you see this error every time after the extension is activated? (I can see similar one sometimes but failed to find a way to reproduce it stably)

**Comment by bitsofinfo** [comment]
its all the time

**Comment by fbricon** [comment]
"name": "openjdk-17" is not valid, it should be "name": "JavaSE-17",

**Comment by bitsofinfo** [comment]
really? the logical names of the keys must be hardwired to this convention?

**Comment by fbricon** [comment]
Yes, it's mapped to an execution environment 
https://github.com/redhat-developer/vscode-java/blob/c0e0a6376809e6c1d5f60bc5a2bfd07452e9a6db/package.json#L749

**Comment by bitsofinfo** [comment]
ok that fixes it thanks
