### ISSUE TITLE
Classpath resources not copied after LS restart

### ISSUE THREAD

**Issue by dsyer** [redhat-developer/vscode-java#2857]
##### Environment
- Operating System: Linux
- JDK version: 17
- Visual Studio Code version: 1.73.1
- Java extension version: v1.14.2022122003

##### Steps To Reproduce
1. Open a Maven project with resources in `src/main/resources`
2. `mvn clean` in a terminal (deletes `target/classes`)
3. Ctrl-P "Java: Restart Language Server Workspace"
4. Observe contents of `target/classes` - compiled `.class` files but no resources

##### Additional Informations

Workaround: Ctrl-P "Developer: Reload Window" appears to fix it (as does `mvn resources:resources`).

**Comment by fbricon** [comment]
looks similar to https://github.com/eclipse-m2e/m2e-core/issues/1150. Do you have a .mvn folder?

**Comment by dsyer** [comment]
No, I tried it with and without `.mvn`. Same outcome.

**Comment by fbricon** [comment]
Mm can't reproduce with 1.13 or 1.14-pre-release.  On restart the resources are under target/classes as expected, although I don't see any .class files. 
Did you turn off autobuild ("java.autobuild.enabled" setting)?
Have you tried switching to [pre-release](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions)?
Can you provide a sample project reproducing the error?

**Comment by dsyer** [comment]
Sample project is any project generated from start.spring.io. I have tried pre-release (that's where I started and then I downgraded but it didn't fix it). My settings (just the "java.*" ones):

```
{
    "java.configuration.updateBuildConfiguration": "interactive",
    "java.compile.nullAnalysis.mode": "disabled",
    "java.debug.settings.vmArgs": "-noverify",
    "[java]": {
        "editor.defaultFormatter": "redhat.java"
    },
    "java.import.gradle.enabled": false,
    "java.completion.favoriteStaticMembers": [...],
    "java.jdt.ls.vmargs": "-Xmx4096m",
    "java.refactor.renameFromFileExplorer": "autoApply",
    "java.requirements.JDK11Warning": false,
    "java.configuration.checkProjectSettingsExclusions": false,
    "java.semanticHighlighting.enabled": true,
    "java.project.importOnFirstTimeStartup": "automatic",
    "maven.executable.preferMavenWrapper": true,
    "java.dependency.packagePresentation": "hierarchical",
    "java.dependency.showMembers": true,
...
}
```

**Comment by dsyer** [comment]
That works, thank you.
