### ISSUE TITLE
java languge not working

### ISSUE THREAD

**Issue by codelearner2k** [redhat-developer/vscode-java#2858]
So, I have using java in vscode for a long time. Suddenly today when I opened it an error occured like cannot resolve java language. Afterwards it shows the java is crashed 5times in 3 minutes. And java language is not build.

I tried to enable and disable language support. I also changed language support but it did not work.

**Comment by jdneo** [comment]
Have you tried to clean the workspace cache? 

- Open the command palette (F1)
- select Java: Clean the Java Language Server Workspace
- select Restart and delete from the confirmation prompt
