### ISSUE TITLE
How to add additional jars (besides those defined in pom.xml) to Java classpath in launch.json?

### ISSUE THREAD

**Issue by siddjain** [redhat-developer/vscode-java#2859]
Hi,

I would like to know how can I add additional jars (besides those defined in pom.xml) to the Java classpath in launch.json? thanks.

**Comment by jdneo** [comment]
Maybe you can try the `classpaths` field in the launch.json. Details: https://github.com/microsoft/vscode-java-debug#launch

cc @testforstephen

**Comment by siddjain** [comment]
Thanks it works

Sent from my iPhone

On Jan 8, 2023, at 5:40 PM, Sheng Chen ***@***.***> wrote:

﻿

Maybe you can try the classpaths field in the launch.json. Details: https://github.com/microsoft/vscode-java-debug#launch<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvscode-java-debug%23launch&data=05%7C01%7C%7C98f007225cd4413c6d0908daf1e28a45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638088252541546885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=w9zQi16wSVggJIfhg1CuJ1m%2Bdv2OPUbw78vtV4u9QCk%3D&reserved=0>

cc @testforstephen<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftestforstephen&data=05%7C01%7C%7C98f007225cd4413c6d0908daf1e28a45%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638088252541546885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PXDlgMssKrTb70rLuXsCbGTQSnxB3Dby0gdLz5hEWis%3D&reserved=0>
