### ISSUE TITLE
New Java project failed to get added workspace

### ISSUE THREAD

**Issue by rajinder-yadav** [redhat-developer/vscode-java#2864]
Type: <b>Bug</b>

In an empty folder, create a new Java project. Select to add to current workspace.
Project is created but fails to get added to current workspace.

Extension version: 1.13.0
VS Code version: Code - Insiders 1.75.0-insider (11238faea62d570d77afe6edfe05c8b732c44a2b, 2022-12-13T05:22:26.937Z)
OS version: Linux x64 6.1.3-1-default
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3998)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|62.72GB (48.76GB free)|
|Process Argv|/home/yadav/dev/docs/guides --crash-reporter-id 210d9130-10f4-4cf9-ad76-187d60112fd6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30622696
fim-prod:30623723

```

</details>

**Comment by jdneo** [comment]
Which type of the project did you selected?

**Comment by rajinder-yadav** [comment]
I created a java project.
CTRL+SHIFT+P > Create Java project

**Comment by rajinder-yadav** [comment]
Oh I selected "Maven" > "maven-architype-quickstart". Why should this matter?

**Comment by jdneo** [comment]
Depending on the type of the project to be created, the creation request will be delegate to different extensions. For Maven project, it's delegate to https://github.com/microsoft/vscode-maven.

Could you file issue in that repo?

**Comment by rajinder-yadav** [comment]
Ah OK got it, this is kind of silly and something vscode core should handle uniformaly.  Closing!
