### ISSUE TITLE
Don't propose code snippets inside comments

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#2867]
Code snippets inside comments are fairly noisy (they get in the way of JBang directives). I don't think there's a valid reason to propose them there.
<img width="672" alt="Screenshot 2023-01-10 at 09 16 01" src="https://user-images.githubusercontent.com/148698/211497212-eecaa550-7063-4038-b291-41623cc68dfd.png">

**Comment by jdneo** [comment]
They are static snippets defined here: https://github.com/redhat-developer/vscode-java/blob/master/snippets/java.json.

If we want to make them more context-aware, we might need to consider making them become server-side snippets - Maybe unregistered them once server is ready.

**Comment by rgrunber** [comment]
Maybe we could re-use some of the work from https://github.com/eclipse/lsp4mp/pull/338 ?
