### ISSUE TITLE
Indentation configuration

### ISSUE THREAD

**Issue by affanshahid** [redhat-developer/vscode-java#287]
Is there any way to customize the indentation/format rules? The following screenshots should describe what I want to happen

##### Pre Format
<img width="1023" alt="screen shot 2017-08-24 at 10 43 08 pm" src="https://user-images.githubusercontent.com/17955210/29680387-cfe8c34e-891d-11e7-9050-b6448d36fab0.png">

##### Post Format
<img width="1023" alt="screen shot 2017-08-24 at 10 43 47 pm" src="https://user-images.githubusercontent.com/17955210/29680370-c76e130e-891d-11e7-9123-79a86264e89d.png">

I want it to not mess up my custom formatting and simply fix indentation errors. Is this possible?
IntelliJ is able to format code into my pre-format form as well.

**Comment by fbricon** [comment]
vscode-java doesn't expose formatting options of the underlying Eclipse JDT formatter [yet](#2).

You currently have 2 options:
- disable java formatting, by setting `java.format.enabled` to false in VS Code's preferences
- define the formatting preferences in your project's [`settings/org.eclipse.jdt.core.prefs`](https://gist.github.com/fbricon/30c5971f7e492c8a74ca2b2d7a7bb966). 

The 2nd solution is rather tedious, so the best way to do it is to open your project in eclipse and set the formatting preferences for your project there. In Eclipse, right-click on your project, open `Properties` > `Java Code Style` > `Formatter` and create a new formatting profile :
<img width="701" alt="screen shot 2017-08-24 at 2 41 36 pm" src="https://user-images.githubusercontent.com/148698/29683245-a769006a-88db-11e7-87f3-f8d69afd3d9d.png">

Once you save it, `settings/org.eclipse.jdt.core.prefs` will be updated. This file will need to be copied to all your other projects in the same workspace. 

No it's not an ideal solution, but it should be done only once, unless you regularly change your formatter settings.

**Comment by affanshahid** [comment]
Thanks for the work around! Any plans on integrating this type of customization?

**Comment by fbricon** [comment]
It's in our backlog: #2

**Comment by fbricon** [comment]
Will keep the discussion open in #2. Closing this one as duplicate (kinda)

**Comment by ocavue** [comment]
@fbricon The 2nd solution does not works for me.

Below is my code. I can't get 4 blank line before methods. Now I have only 1 blank line, as same as the default setting.

![screen shot 2017-10-29 at 6 19 40 pm](https://user-images.githubusercontent.com/24715727/32142612-cd9748ee-bc68-11e7-817e-c63aca391d35.png)

I don't know if I did something wrong or this is just a bug.

> OS: macOS 10.13
> VSCode: 1.17.2
> Language Support for Java(TM) by Red Hat: 0.12.0

**Comment by fbricon** [comment]
@ocavue the solution works for actual projects. What you have is a folder with a java project and a .classpath file. So what defines what an actual project is? At the root of your folder you need to have either:
-  a Maven `pom.xml`,  
- or a Gradle `build.gradle`, 
- or both Eclipse's `.project` and `.classpath` files.

I strongly suggest you go with making either a [Maven](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html) or a [Gradle](https://docs.gradle.org/current/userguide/tutorial_java_projects.html) project. But if you find that too daunting, a simpler alternative is to use Eclipse to [create a new Java project](https://www.tutorialspoint.com/eclipse/eclipse_create_java_project.htm). 

Then add your java class to your project source folder.

Once you have your project structure created, you can close your IDE to open the folder in VS Code. Changing `org.eclipse.jdt.core.formatter.blank_lines_before_method=4` in  `.settings/org.eclipse.jdt.core.prefs` should now work.

![oct-30-2017 09-57-44](https://user-images.githubusercontent.com/148698/32174667-dc9db60c-bd58-11e7-8f46-501ed200c5a2.gif)

**Comment by ocavue** [comment]
@fbricon Sorry for posting a stupid question. I know little about java and your detailed answer is really helpful. Thanks.
