### ISSUE TITLE
Consider enable `-parameter` compiler arg by default

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#2872]
There are some issues regarding to this:

https://github.com/redhat-developer/vscode-java/issues/2304
https://github.com/microsoft/vscode-java-test/issues/1518

Looks like it's enabled in Eclipse by default
![image](https://user-images.githubusercontent.com/6193897/211806395-49bf445a-af81-44ed-952d-a0437c852e44.png)

> I haven't confirmed yet that the highlighted option is about the `-parameter` option. Correct me if I'm wrong.

**Comment by rgrunber** [comment]
It appears to be https://github.com/eclipse-jdt/eclipse.jdt.core/blob/7f2b6b230ae5f09345d2f0ebbddae00d9a72b9fe/org.eclipse.jdt.core/model/org/eclipse/jdt/core/JavaCore.java#L320-L333 . It seems to be disabled by default though according to the docs.

**Comment by jdneo** [comment]
Oh sorry, I just check the setting in a newly installed Eclipse instance, and it's disabled by default.

Then let's wait to see if more people want this to be enabled by default.

**Comment by bohdan-shulha** [comment]
How to enable this in VS Code? :)

**Comment by jdneo** [comment]
With the latest `Language Support for Java(TM) by Red Hat` (1.31.0) and latest `Extension Pack for Java` (0.27.0). You can now change the compiler options with a GUI with following steps:

1. Click the java status bar
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/82fa54f1-36a2-4982-9c3e-c7b581bb80a0)
2. Select `Open Project Settings`
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/3f8491a1-ceda-4ccb-bffd-4cb1fb64dbc0)
3. Go to the `Compiler` tab, and enable `Store information about method parameters`
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/9f607e86-b6b1-4c72-a32a-e4effe5e9b52)

**Comment by jdneo** [comment]
Close since we have a GUI now to set the setting.

**Comment by fp024** [comment]
Running "Clean Java Language Server Workspace" resets this setting to the default.

It would be nice to have an option to always apply this setting globally so that it is not affected by running "Clean Java Language Server Workspace".

**Comment by jdneo** [comment]
@fp024 Feel free to file an issue your request.
