### ISSUE TITLE
Autocompletion after import

### ISSUE THREAD

**Issue by weiguowilliam** [redhat-developer/vscode-java#289]
I'm learning <Algorithms 4 edtion> now. I import the algs4.jar provided by this book into my code. Nothing in algs4.jar can be autocompleted. But auto-completion for others are right, such as java.util.* can be auto-completed correctly. The program can be run perfectly. The only problem is auto-completion.

I have searched a lot but haven't found the reason. Someone just let me to use IntelliJ. But I love vs code and your extension. And this is the first time that I write an issue. Thank you for your kindness.

##### Environment
- macOS Sierra Version 10.12.6
- JDK version:1.8.0_131
- Visual Studio Code version:1.12.0
- Java extension version:0.8.0

##### Steps To Reproduce
1. import edu.princeton.cs.algs4.*;
2. vs code cannot auto-complete anything from algs4.jar correctly.

![screen shot 2017-08-27 at 10 40 14 pm](https://user-images.githubusercontent.com/31396452/29757285-b9b2ea34-8b78-11e7-998b-0ebb58dc39d8.png)

##### Current Result
cannot auto-complete anything from algs4.jar correctly.

##### Expected Result
auto-complete the part from algs4.jar correctly after imported.
##### Additional Informations

**Comment by fbricon** [comment]
The best way to let vscode-java know that algs4j must be added to the classpath is to use [Maven](https://maven.apache.org/) or [Gradle](https://gradle.org/) as a build tool.
I whipped up a simple Maven project that adds the algs4j dependency.
From a terminal, just:
* `git clone https://github.com/fbricon/algs4j-demo`
* `cd algs4j-demo`
* `code .`
And if you run `./mvnw clean verify` from the terminal, Maven will clean up all compilation artifacts, compile the sources, launch unit tests and generate a jar archive

**Comment by fbricon** [comment]
Closing as there's no changes required in vscode-java

**Comment by weiguowilliam** [comment]
Thank you for your kindness. That's really helpful.
