### ISSUE TITLE
Dependency Analytics extension popup every time I open a pom.xml file

### ISSUE THREAD

**Issue by ziroc** [redhat-developer/vscode-java#2892]
As in title. Every time I open a pom.xml file, the popup that advertises the "Dependency Analytics extension" shows. I click on the "never" button, but it doesn't help.

##### Environment
- Operating System: Windows 11
- JDK version: 17
- Visual Studio Code version: 1.74.2
- Java extension version: 1.14.0

![image](https://user-images.githubusercontent.com/37216225/213558823-78088759-a59a-4371-a19a-1d2218f7ab30.png)

##### Expected Result
My preference to be saved and to not have this pop up every time.

**Comment by fbricon** [comment]
Yeah that way we'll wear down users' patience and they'll cave in and install the extension eventually.

Just kidding. It's a bug, We'll fix it.
