### ISSUE TITLE
Cannot disable auto formatting

### ISSUE THREAD

**Issue by zlargon** [redhat-developer/vscode-java#2897]
I want to turn off auto formatting when saving a file, as it takes too long (5 seconds). I've tried using the configuration java.format.enabled, but it's not working.

##### Environment
- Operating System: macOS 13.1
- JDK version: 11
- Visual Studio Code version: 1.74.3
- Java extension version: v1.14.0

##### Steps To Reproduce
1. Add `java.format.enabled: false` in settings.json
2. Edit java and save file

##### Current Result

The java file is formatted with `java.format.enabled: false` after file saved.

##### Expected Result

The java file should not be formatted with `java.format.enabled: false` after file saved.

##### Additional Informations

video screen recording:

https://user-images.githubusercontent.com/2791834/214286026-bfaf3e04-3b19-436c-9bb2-28460c0d3b07.mov

**Comment by fbricon** [comment]
Can you disable all other extensions, see if you still reproduce it?
Does your build file define some formatter plugin?

**Comment by zlargon** [comment]
@fbricon I have disabled all other formatter plugins. It only stop formatting after I disable `redhat.java`.

**Comment by ronyitc** [comment]
I did everything but none worked. Now I am using `Format: Save file without formatting` from Command Menu using `CMD + p`
