### ISSUE TITLE
Failed build when using records with mapstruct

### ISSUE THREAD

**Issue by yotov** [redhat-developer/vscode-java#2899]
##### Environment
- Operating System: MacOS Ventura 13.1
- JDK version: openjdk-19
- Visual Studio Code version: 1.74.3
- Java extension version: 1.14.0

##### Steps To Reproduce
1. Clone https://github.com/mapstruct/mapstruct-examples
2. Open mapstruct-record in Visual Studio Code
3. Rename source = "email" to source = "name" in CustomerMapper.java

##### Additional Informations
I'm getting strange a error while using mapstruct with records:
`No property named "name" exists in source parameter(s). Type "CustomerDto" has no properties.Java(0)`
The error disappears after running "Java: rebuild project". 

This error is not a new one, I saw it with older versions of the extension too. When I try to run or debug the project a warning for "Build was failed" appears

**Comment by fbricon** [comment]
The same problem appears when running in Eclipse. It's probably an issue with JDT APT, Eclipse's implementation of annotation processing within the IDE, that doesn't like something the mapstruct AP is doing. It might also be fixable in mapstruct's AP implementation.
 
@snjeza, can you please take a quick look?

**Comment by fbricon** [comment]
@yotov as a workaround, you can use the `"Java: Force Java Compilation"  > Full` command

**Comment by yotov** [comment]
@fbricon I've been using the workaround for a month, and now I found time to report the bug :)
But the workaround doesn't work at all in projects with Lombok and mapstruct

**Comment by fbricon** [comment]
Can you check that `java.jdt.ls.lombokSupport.enabled` is set to `true`?

**Comment by yotov** [comment]
Yes, it's enabled

**Comment by fbricon** [comment]
@yotov I think it's a separate bug. Can you open a different issue for lombok please?

**Comment by yotov** [comment]
@fbricon after all It's not related to Lombok. It turned out that the problem occurs when source/target in the mapper comes from a library. I use a multi-maven project and that's how I found it. Here is an example where it can be reproduced - https://github.com/yotov/vscode-mapstruct-example 

When the mapper uses a class that is outside of the project I get the following error:
`Unknown property "testing" in result type Target. Did you mean "null"?Java `

And forcing java compilation doesn't work. 
If you think that it's not related to the current bug I will open a new one

**Comment by snjeza** [comment]
This issue is an upstream jdt.core issue. I have created https://github.com/eclipse-jdt/eclipse.jdt.core/issues/663

**Comment by yotov** [comment]
@snjeza this issue is not reproducible after the latest release, I think we can close it
