### ISSUE TITLE
Code action for getters/setters not available if the private field is accessed internally

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#290]
Following up on #263, when a private field is used in the class, the code action to generate accessors is not available.

```java
	private String s = ""; // no code action available to generate accessors here

	private void foo() {
		System.err.println(s);
	}
```

**Comment by fbricon** [comment]
I'm guessing this is caused by the fact code actions are only proposed on errors/warnings

**Comment by yaohaizh** [comment]
Yes, if there is no problem. There is no code action for this one. On the other hand, if want to trigger code action in this case, user might select the private field to trigger code action. But in this case, we need forward work for refactoring which I'll be following in the coming sprint.

**Comment by yaohaizh** [comment]
Fixed with this PR: https://github.com/eclipse/eclipse.jdt.ls/pull/679

**Comment by fbricon** [comment]
This is not working anymore

**Comment by jdneo** [comment]
![image](https://user-images.githubusercontent.com/6193897/218029963-54df9c44-012f-4315-bab9-cbb3de3cb2bb.png)

It's available in the source action list now.
