### ISSUE TITLE
Add an option not to insert arguments on completion

### ISSUE THREAD

**Issue by felixxing** [redhat-developer/vscode-java#2903]
[provide a description of the issue]

##### Environment
- Operating System: Windows
- JDK version: openjdk 17.0.5 2022-10-18 LTS
- Visual Studio Code version: 1.74.3
- Java extension version: N/A

##### Steps To Reproduce
1. Create any method that has arguments 
2. Type that method and use autocomplete
3. You can see that the name of argument is also fill in, which is unexpected

##### Current Result
<img width="560" alt="Screenshot 2023-01-26 152024" src="https://user-images.githubusercontent.com/101950667/214942166-5735335f-c870-4a0e-b152-31d23f7f054e.png">

##### Expected Result
<img width="562" alt="Screenshot 2023-01-26 152048" src="https://user-images.githubusercontent.com/101950667/214942178-24c70db7-0363-4310-9a4e-a909d2fb2094.png">

##### Additional Informations
If this is a feature, can I turn of this?

**Comment by snjeza** [comment]
@felixxing You can try
```
"java.completion.guessMethodArguments": false
```

**Comment by felixxing** [comment]
> @felixxing You can try
> 
> ```
> "java.completion.guessMethodArguments": false
> ```

That does not work.

**Comment by jdneo** [comment]
It's currently by design that the method arguments will be filled according to the selected method's signature.

Looks like we need to expose this setting from JDT
![image](https://user-images.githubusercontent.com/6193897/215376436-b0bcfa44-75d4-4a0c-b1fe-bc035556cd32.png)

I remember it's not exposed now in VS Code Java, @snjeza is it correct?

**Comment by snjeza** [comment]
> I remember it's not exposed now in VS Code Java, @snjeza is it correct?

Yes, it is correct.

**Comment by thgcode** [comment]
I'm not sure if the images display the same issue, but it would be nice to have the option to not include the argument names on method calls. I use a screen reader (NVDA) / keyboard and deleting all the arguments when selecting a method call everytime makes using this feature a bit annoying, especially if the method has more than 2 arguments. It would be nice if we could have the option to select between the three modes, one for completely turning it off, one for argument names and other for guessing the method arguments.

I don't know much about the LSP protocol, but it seems [the feature is hardcoded on the source code of jdt.ls](https://github.com/eclipse/eclipse.jdt.ls/blob/daa965dd52071ea8ca2142be1bebb4c3672dcc4c/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/contentassist/CompletionProposalReplacementProvider.java#L562).

**Comment by jdneo** [comment]
Hi @thgcode, the image pasted above in this thread is a screenshot from Eclipse configuration page. It shows that Eclipse has the capability to control the behavior and that can be a reference for the implementation in VS Code Java extension.

**Comment by thgcode** [comment]
@jdneo Thanks for the image description!

I tested with Eclipse and the feature can be used correctly on it. Then I was thinking why it worked on Eclipse and not on VSCode and found some information that can help to implement the feature. It seems [the feature is implemented directly on the UI](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/f8ac84e2d3303aa7f9d939e6d6023fc209b61661/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/FillArgumentNamesCompletionProposalCollector.java). The [JavaCompletionProposalComputer](https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/f8ac84e2d3303aa7f9d939e6d6023fc209b61661/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaCompletionProposalComputer.java#L322) reads the preference and sets the completion collector. It seems this the reason it works on Eclipse.

**Comment by jdneo** [comment]
@thgcode Thank you for the information. If it's implemented in UI, then we have to do it separately in JDT.LS. But I guess it won't be too complicated(hopefully). I can take a look at this sometime in next month.

**Comment by jdneo** [comment]
@thgcode, you can now set `java.completion.guessMethodArguments` to `off` stop filling anything on completion. The feature should be available in pre-release version `v1.20.2023061504` or higher now.

**Comment by thgcode** [comment]
I tested it and it's working perfectly, thank you! This feature will save a lot of time for me.

**Comment by jdneo** [comment]
@thgcode Thanks for the feedback!
