### ISSUE TITLE
How to transform `IntelliJ IDEA Community Edition`'s formatter implementation to `redhat.java` plugin from https://github.com/JetBrains/intellij-community

### ISSUE THREAD

**Issue by cloorc** [redhat-developer/vscode-java#2908]
##### Environment
- Operating System: Windows 11 Pro(OS Build 22621.1105)
- JDK version:  openjdk version "17.0.4.1" 2022-08-12
- Visual Studio Code version: 1.74.3
- Java extension version: 1.14.0

##### Steps To Reproduce
1. Export code style settings as `Eclipse XML Profile` from `IntelliJ IDEA 22.3.1` -> `Settings->Editor->Code Style->Schema` named as `style.xml` under path `c:\Users\yi\style.xml`
2. Assign `file://c:/Users/yi/style.xml` to `java.format.settings.url` in `vscode` `settings.json`
3. Open an java project and wait for indexing complete
4. Using `Ctrl+Alt+L` to format source code

![image](https://user-images.githubusercontent.com/13597105/215248760-a66e9934-8f40-4eb5-92a3-13aa4f68e01e.png)
![image](https://user-images.githubusercontent.com/13597105/215248810-ff05ab04-3328-4861-a0d0-af61dbde2927.png)

##### Current Result

Formated source code style is not same as `IntelliJ IDEA` from `Visual Studio Code`.

##### Expected Result

`Visual Studio Code` should format source code style as same as `IntelliJ IDEA`.

##### Additional Informations

How could we make this possible? Can we transform `IntelliJ IDEA Community Edition`'s formatter implementation to `redhat.java` plugin from https://github.com/JetBrains/intellij-community/blob/master/platform/code-style-impl/src/com/intellij/formatting/FormatterImpl.java ?

**Comment by CsCherrYY** [comment]
The code style should be the same. @cloorc Could you explain the exact differences between the two styles? I guess there are some bugs or limitations in the IDEA exporter, since not all the configurations in the two formatter profiles can find their equivalent one in the opposite side.

> How could we make this possible? Can we transform IntelliJ IDEA Community Edition's formatter implementation to redhat.java plugin

There is an existing issue to look for providing the intelliJ default formatter setting: https://github.com/redhat-developer/vscode-java/issues/998, but for transforming the existing intelliJ profile, I suggest you to open a new issue to request.

**Comment by cloorc** [comment]
> The code style should be the same. @cloorc Could you explain the exact differences between the two styles? I guess there are some bugs or limitations in the IDEA exporter, since not all the configurations in the two formatter profiles can find their equivalent one in the opposite side.
> 
> > How could we make this possible? Can we transform IntelliJ IDEA Community Edition's formatter implementation to redhat.java plugin
> 
> There is an existing issue to look for providing the intelliJ default formatter setting: #998, but for transforming the existing intelliJ profile, I suggest you to open a new issue to request.

In IntelliJ IDEA, the long row did not wrap if I manually merge two rows into one, or just wrap with one indent unit according to **previous line**. However, in vscode, the long row wll always wrap with alignment to first **parameter**. That is weired.

**Comment by cloorc** [comment]
> The code style should be the same. @cloorc Could you explain the exact differences between the two styles? I guess there are some bugs or limitations in the IDEA exporter, since not all the configurations in the two formatter profiles can find their equivalent one in the opposite side.
> 
> > How could we make this possible? Can we transform IntelliJ IDEA Community Edition's formatter implementation to redhat.java plugin
> 
> There is an existing issue to look for providing the intelliJ default formatter setting: #998, but for transforming the existing intelliJ profile, I suggest you to open a new issue to request.

Thanks! I've checked the issue #998, it exactly what I need. I'll close this issue. Thanks again!

**Comment by CsCherrYY** [comment]
@cloorc you can vote in that issue so that we can consider to prioritize it :)
