### ISSUE TITLE
Force Reload (JavaDoc+Completion+...)

### ISSUE THREAD

**Issue by gantispam** [redhat-developer/vscode-java#291]
Hi, 
How can I force (re)download of JavaDoc, autocompletion instructions etc...
I don't have all autocompletion and I don't have any JavaDoc. 
I thinks my first download is corrupt.
I try to uninstal Extension, uninstall VSC but without success (existing download seen to be backup).

##### Environment
- Operating System:W10
- JDK version:1.8
- Visual Studio Code version:1.15.1
- Java extension version:last

##### Steps To Reproduce
1. [step 1] Install vscode-java Extension
2. [step 2] Access a javafile for first download Java Instruction
3. [step 32]  Stop Download (juste change windows focus)

**Comment by gorkem** [comment]
Are you using maven or gradle?

**Comment by gantispam** [comment]
For my first/init download i'm used Maven.
(So, I tried on another PC with Gradle project and it's work fine...).

**Comment by gorkem** [comment]
Actually you need to force gradle to update its caches.  Gradle caches are located at`~/.gradle/caches` folder, cleaning them should do the trick.
