### ISSUE TITLE
"java.execute.workspaceCommand" Error

### ISSUE THREAD

**Issue by yaegar** [redhat-developer/vscode-java#2916]
I have a problem when executing "java.execute.workspaceCommand" command in other plugins.

![image](https://user-images.githubusercontent.com/12856549/216486843-95951ae1-06e6-41c2-aca1-83e9cbae0a79.png)

![image](https://user-images.githubusercontent.com/12856549/216486899-f062e6a2-463a-4145-8de0-ef56e5978c3b.png)

This problem did not exist before "v1.15.2023013103"

##### Environment
- Operating System: Win11
- JDK version: 17
- Visual Studio Code version: 1.75.0
- Java extension version: v1.15.2023020203

**Comment by jdneo** [comment]
I didn't observe such error in other extensions which will invoke this command so far. Could you provide reproduce steps?

**Comment by yaegar** [comment]
> I didn't observe such error in other extensions which will invoke this command so far. Could you provide reproduce steps?

When my extension starts loading I need to get all the Java projects.


A simple definition in my code:

"use strict";
import * as vscode from "vscode";

const REDHAT_JAVA: string = "redhat.java";

export async function activate(context: vscode.ExtensionContext) {
  const redhatJavaExtension = vscode.extensions.getExtension(REDHAT_JAVA);
  if (!redhatJavaExtension) {
    return;
  }
  await redhatJavaExtension.activate();
  
  const projects = await vscode.commands.executeCommand(
    "java.execute.workspaceCommand",
    "java.project.getAll"
  );
  // do something
}

It works fine when I use v1.14.0 or 1.15.2023012602 (lower with it)

**Comment by jdneo** [comment]
Please try to wait until the server is ready, then send request. See:

https://github.com/redhat-developer/vscode-java/blob/5c0123f7cfd88086e187112c0a616ac4e90767c6/src/extension.api.ts#L120
https://github.com/microsoft/vscode-java-test/blob/0c14d0b92ef73ffb104d9eaee0bd3db6346b4926/src/extension.ts#L61

**Comment by yaegar** [comment]
> Please try to wait until the server is ready, then send request. See:
> 
> https://github.com/redhat-developer/vscode-java/blob/5c0123f7cfd88086e187112c0a616ac4e90767c6/src/extension.api.ts#L120
> 
> 
> https://github.com/microsoft/vscode-java-test/blob/0c14d0b92ef73ffb104d9eaee0bd3db6346b4926/src/extension.ts#L61

Thanks, it is working fine according to what you provided

**Comment by yaegar** [comment]
Resolved
