### ISSUE TITLE
Code Autocomplete Order Messed Up

### ISSUE THREAD

**Issue by SansPapyrus683** [redhat-developer/vscode-java#2917]
[provide a description of the issue]

##### Environment
- Operating System: Windows 11
- JDK version: 18
- Visual Studio Code version: 1.75.0
- Java extension version: 1.14.0

##### Steps To Reproduce
1. Install the extension
2. Use code autocomplete

##### Current Result

Right now, this is what shows up in the code autocomplete: 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/55369003/216506116-816b6656-ac1a-4b66-b2fc-e0f0897cb9f3.png">

##### Expected Result
I expected the starred completion  (`parseInt()` without any arguments) to show up at the top, but for some reason it's at the bottom.

**Comment by jdneo** [comment]
The response returned from LS is:

```
[Trace - 3:48:43 PM] Received response 'textDocument/completion - (68)' in 54ms.
Result: {
    "isIncomplete": false,
    "items": [
        {
            "label": "★ parseInt(String s) : int",
            "kind": 2,
            "detail": "Integer.parseInt(String s) : int",
            "sortText": "999997579",
            "insertText": "parseInt",
            ...
        },
        {
            "label": "★ parseInt(String s, int radix) : int",
            "kind": 2,
            "detail": "Integer.parseInt(String s, int radix) : int",
            "sortText": "999997835",
            "insertText": "parseInt",
            ...
        },
        {
            "label": "parseInt(CharSequence s, int beginIndex, int endIndex, int radix) : int",
            "kind": 2,
            "detail": "Integer.parseInt(CharSequence s, int beginIndex, int endIndex, int radix) : int",
            "sortText": "999999179",
            "insertText": "parseInt",
            ...
        },
        {
            "label": "parseUnsignedInt(CharSequence s, int beginIndex, int endIndex, int radix) : int",
            "kind": 2,
            "detail": "Integer.parseUnsignedInt(CharSequence s, int beginIndex, int endIndex, int radix) : int",
            "sortText": "999999179",
            "insertText": "parseUnsignedInt",
            ...
        },
        {
            "label": "parseUnsignedInt(String s, int radix) : int",
            "kind": 2,
            "detail": "Integer.parseUnsignedInt(String s, int radix) : int",
            "sortText": "999999179",
            "insertText": "parseUnsignedInt",
            ...
        },
        {
            "label": "parseUnsignedInt(String s) : int",
            "kind": 2,
            "detail": "Integer.parseUnsignedInt(String s) : int",
            "sortText": "999999179",
            "insertText": "parseUnsignedInt",
            ...
        }
    ]
}
```

It's strange because from my understanding, The sort text `"999997579"` should make it rank higher than `"999999179"`, but the actual order is not in that way.

@Eskibear, do you have any idea about this?

**Comment by Eskibear** [comment]
If `filterText` is not defined, it will fallback to use `label`. Here it's better to explicitly set `filterText` to what's in `insertText`.

**Comment by rgrunber** [comment]
Yup, this seems to be what https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem indicates. Just wanted to make sure the change can be justified directly from what the spec says.
