### ISSUE TITLE
x: sugguestion in println();

### ISSUE THREAD

**Issue by tinmont** [redhat-developer/vscode-java#2920]
Type: <b>Bug</b>

 "x:" shows in my println also "s:" in my print and my variable names showing up in parameters

Extension version: 1.14.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.40GB free)|
|Process Argv|--crash-reporter-id e0a559dc-7534-4680-98de-1d1c1cde9e27|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12:30657548

```

</details>

**Comment by tinmont** [comment]
![Screenshot 2023-02-04 125232](https://user-images.githubusercontent.com/123637553/216751536-9db5155e-256d-434a-a3c6-4edb1de0ca50.png)

**Comment by snjeza** [comment]
@tinmont You can try to add
```
"java.inlayHints.parameterNames.enabled": "none",
```
to your settings.json

**Comment by tinmont** [comment]
I found another way to fix this in Extension Settings
![Screenshot 2023-02-05 153456](https://user-images.githubusercontent.com/123637553/216809415-0d805046-cef6-4349-b1bd-5b53929d1730.png)

**Comment by jdneo** [comment]
You can also use `java.inlayHints.parameterNames.exclusions` to config specific rule to disable inlay hints.

Closing since the problem should be addressed already.
