### ISSUE TITLE
Experimental paste handling blocks pasting while project loading

### ISSUE THREAD

**Issue by rgrunber** [redhat-developer/vscode-java#2924]
![slow-paste-handler](https://user-images.githubusercontent.com/1417342/217302967-61ee0670-61ae-4c49-99e5-cf0c4920b3cb.gif)

```
[Trace - 11:43:42] Sending request 'workspace/executeCommand - (3)'.
Params: {
    "command": "java.edit.handlePasteEvent",
    "arguments": [
        "{\"location\":{\"range\":{\"start\":{\"line\":83,\"character\":0},\"end\":{\"line\":83,\"character\":0}},\"uri\":\"file:///home/rgrunber/git/lemminx/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLLanguageServer.java\"},\"text\":\"XMLLanguageServer\",\"formattingOptions\":{\"insertSpaces\":false,\"tabSize\":4}}"
    ]
}
...
...
[Trace - 11:43:56] Received response 'workspace/executeCommand - (3)' in 13986ms.
No result returned.
```

I tried inserting a breakpoint into the delegate to see if some part of the command was being blocked, but it seems like there's a good chunk of time where the language server hasn't received the request, yet the client is clearly waiting, so maybe this is the language client delaying the request until the server is ready.

CC @datho7561 , @CsCherrYY 

**Update:** Note that regular pasting does work if done before the language server starts up, which is probably prior to `onReady`. That would at least seem to imply that `onReady` is not enough, and we need a stronger condition when registering the paste provider. Maybe `ServiceReady` or `Started` ?

**Comment by CsCherrYY** [comment]
> and we need a stronger condition when registering the paste provider. Maybe ServiceReady or Started ?

Agree. and I guess the cause here is that the DelegateCommandHandler (paste handler in here) will be ready after a specific status (maybe `ServiceReady`).

**Comment by datho7561** [comment]
I tried doing

```typescript
apiManager.getApiInstance().serverReady().then((_ignore) => {
  registerPasteEventHandler(context, this.languageClient);
});
```

and that seems to fix it. I can put this is into a PR one second...
