### ISSUE TITLE
Feature request: enable formatter on lightweight mode

### ISSUE THREAD

**Issue by kkocdko** [redhat-developer/vscode-java#2926]
Now, in lightweight mode, the formatter is unusable. Formatter is fast and does not need complex code analysis, it's suitable to be enabled in lightweight mode.

Reason: Sometimes we just want to open a single java file on a big project with lightweight mode, enabling formatter will be helpful.

**Comment by kkocdko** [comment]
Seems that this feature was added to upsteam: https://github.com/eclipse/eclipse.jdt.ls/pull/2450

Awesome!

**Comment by fbricon** [comment]
@kkocdko you can test that feature in the latest pre-release build
<img width="972" alt="Screenshot 2023-02-10 at 11 38 47" src="https://user-images.githubusercontent.com/148698/218071523-38d86432-d213-49ae-9ada-30cdea54f7ed.png">
