### ISSUE TITLE
"java.import.generatesMetadataFilesAtProjectRoot" is not honored

### ISSUE THREAD

**Issue by anandbibek** [redhat-developer/vscode-java#2929]
Type: <b>Bug</b>

I've set the property "java.import.generatesMetadataFilesAtProjectRoot" to TRUE in user settings, remote settings, workspace and even folder. But the project files are never generated in project root.

Also the actual place they are generated in have pretty weird nesting and random numbers. Certainly not straightforward as mentioned here https://github.com/redhat-developer/vscode-java/blob/master/document/_java.metadataFilesGeneration.md

Example: `.vscode-server/data/User/workspaceStorage/647c049edba9537d8fc502620dd6860c/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.core.resources/.projects/protectedModel_48d582b1/`

Extension version: 1.15.2023020903
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.17-2136.302.7.2.1.el8uek.x86_64
Remote OS version: Linux x64 5.4.17-2136.302.7.2.1.el8uek.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.24GB free)|
|Process Argv|C:\\Workspace\\vs-code-workspaces\\OCI\\watchlist-protectedModel.code-workspace|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 100.108.204.190|
|OS|Linux x64 5.4.17-2136.302.7.2.1.el8uek.x86_64|
|CPUs|AMD EPYC 7J13 64-Core Processor (4 x 2445)|
|Memory (System)|31.08GB (24.48GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 100.108.204.190|
|OS|Linux x64 5.4.17-2136.302.7.2.1.el8uek.x86_64|
|CPUs|AMD EPYC 7J13 64-Core Processor (4 x 2445)|
|Memory (System)|31.08GB (24.48GB free)|
|VM|0%|
</details>

**Comment by snjeza** [comment]
@anandbibek Could you show .vscode-server/data/User/settings.json ?

**Comment by anandbibek** [comment]
```
{
    "java.jdt.ls.java.home": "/scratch/anaray/software/jdk-19.0.1/",
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "/scratch/anaray/software/jdk-8u351-linux-x64/jdk1.8.0_351/",
            "sources": "/scratch/anaray/software/jdk-8u351-linux-x64/jdk1.8.0_351/src.zip",
            "javadoc": "https://docs.oracle.com/javase/8/docs/api",
            "default": true
        },
        {
            "name": "JavaSE-11",
            "path": "/scratch/anaray/software/jdk-11/",
            "sources": "/scratch/anaray/software/jdk-11/lib/src.zip",
            "javadoc": "https://docs.oracle.com/en/java/javase/11/docs/api"
        },{
            "name": "JavaSE-19",
            "path": "/scratch/anaray/software/jdk-19.0.1/",
            "sources": "/scratch/anaray/software/jdk-19.0.1/lib/src.zip",
            "javadoc": "https://docs.oracle.com/en/java/javase/19/docs/api/"
        }
    ],
    "java.import.generatesMetadataFilesAtProjectRoot": true,
    "java.project.resourceFilters": [

        "node_modules",
        "\\.git",
        "\\.ade_path"
    ],
    // "java.import.exclusions": [
    //     "**/node_modules/**",
    //     "**/.metadata/**",
    //     "**/archetype-resources/**",
    //     "**/META-INF/maven/**",
    //     "**/.ade_path/**"
    // ]
}

```

**Comment by anandbibek** [comment]
The file is actually in `/scratch/anaray/.vscode-server/data/Machine/settings.json`

**Comment by snjeza** [comment]
> The file is actually in /scratch/anaray/.vscode-server/data/Machine/settings.json

@anandbibek Could you try to move it to  /scratch/anaray/.vscode-server/data/User/settings.json?

**Comment by anandbibek** [comment]
That did not make a difference. I moved the file, but it just got recreated again. I believe it uses the settings.json from `Machine` folder as I'm connected via remote ssh.

I also have this in my workspace file, which is recognized for sure, as folder level settings.json lines are greyed out.

```
{
	"folders": [
		{
			"uri": "vscode-remote://ssh-remote+100.108.204.190/home/anaray/Documents/HelloJava"
		}
	],
	"remoteAuthority": "ssh-remote+100.108.204.190",
	"settings": {
		"java.project.sourcePaths": [
			"src"
		],
		"java.project.outputPath": "bin",
		"java.project.referencedLibraries": [
			"lib/**/*.jar"
		],
		"java.import.generatesMetadataFilesAtProjectRoot": true
	}
}
```

**Comment by snjeza** [comment]
I can't reproduce the issue.
I have started code server as
```
code-server --verbose --log debug
```
@anandbibek you can ask at https://github.com/coder/code-server

**Comment by anandbibek** [comment]
Moved to https://github.com/microsoft/vscode-java-dependency/issues/716

**Comment by jdneo** [comment]
If your project is not managed by any build tool and it's not an Eclipse project, those metadata files will never appear in the project root.

If you want them explicitly persisted in the project root, you need to create an Eclipse project and then open that project in VS Code.

**Comment by anandbibek** [comment]
@jdneo got your point. I've seen that if I'm putting the . project file in root myself, afterwards settings like "referencedLibraries" in workspace or folder setting of vscode does not alter or modify the .classpath file anymore? Is this expected?

**Comment by jdneo** [comment]
> I've seen that if I'm putting the . project file in root myself, afterwards settings like "referencedLibraries" in workspace or folder setting of vscode does not alter or modify the .classpath file anymore? Is this expected?

Yes, referenced libraries are not available for eclipse projects now.

**Comment by anandbibek** [comment]
@jdneo  I'm trying to write an extension myself where I could alter the local .classpath file based on specific wildcards paths from extension configuration or even read the wildcards in .workspace 'referencedLibraries'. 

I believe vscode already does that? Would you be able to point me towards the wildcard expansion code and . classpath creation logic. That'd be of great help.

**Comment by jdneo** [comment]
The raw pattern is set from client to server side, and then the server side parse the global pattern.

The code at Java side is: https://github.com/eclipse/eclipse.jdt.ls/blob/eef3e3f130464e4d27d0864eb307568527de799e/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ProjectUtils.java#L449
