### ISSUE TITLE
Add referenced libraries when using gradle

### ISSUE THREAD

**Issue by chientrm** [redhat-developer/vscode-java#2932]
Add referenced libraries when using gradle

##### Environment
- Operating System: Ubuntu 20.04
- JDK version: 11
- Visual Studio Code version: Gitpod Code 1.75.1
- Java extension version: 1.14.0

##### Description

When there's not `build.gradle` or `pom.xml` in the root project, we can use `java.project.referencedLibraries` to add paths to local `jar` files so that `vscode` will suggest classes from them.
When there's `build.gradle` or `pom.xml` in the root project, `java.project.referencedLibraries` is ignored.

##### Expected
How can I get the same result while using `build.gradle`?

**Comment by fbricon** [comment]
You can't use "java.project.referencedLibraries". 

It then becomes the build tool's job to add your dependencies to the classpath. 
- for gradle: https://docs.gradle.org/5.2.1/userguide/dependency_types.html#sub:file_dependencies
- for Maven: https://stackoverflow.com/a/4955695/753170 is the closest solution, but not the recommended one, you'd better install the dependencies to your local Maven repo, see other SO responses on that page.

**Comment by chientrm** [comment]
> You can't use "java.project.referencedLibraries" for anything other than "unmanaged folders".
> 
> It then becomes the build tool's job to add your dependencies to the classpath.
> 
> * for gradle: https://docs.gradle.org/7.6/userguide/declaring_dependencies.html#sub:file_dependencies
> * for Maven: https://stackoverflow.com/a/4955695/753170 is the closest solution, but not the recommended one, you'd better install the dependencies to your local Maven repo, see other SO responses on that page.

I'll try this solution.
Currently, I disabled gradle importer from the extension, I just use gradle for the building process and manually configure classpath using `settings.json`.
Plus, it's an Android project so that there're `aar` dependencies files requires manual `unzip`.

**Comment by judfs** [comment]
Is there a way to specify "sources" for a gradle file dependency? Looks like at least historically there wasn't? I have wasted my day trying to figure this out and it would be **GREAT** if I could just use `"java.project.referencedLibraries": { "sources": {` with my gradle project.

Edit: Looks like  -sources.jar is picked up on a `flatDir` repository. For anyone else coming across this:
```
repositories { 
    mavenCentral()

    flatDir{
        dirs '/usr/local/share/java'
    }
}
dependencies {
  implementation ':some-lib'
}
```
instead of 
```
dependencies {
  implementation files('/usr/local/share/java/some-lib.jar')
}
```
