### ISSUE TITLE
The server closes automatically after start

### ISSUE THREAD

**Issue by MarcSerret51** [redhat-developer/vscode-java#2933]
When I open a new Spring Boot project (created with Spring Initializr extensions) in a freshly installed VSCode the Java Syntax Server just closes withouth any error. Crashes on startup, a few seconds after opening VSC.
I activated the verbose logging and everything seems to be working fine and then the server closes automatically.
I downgraded the VSCode and the extension version but I'm getting the same error.

In my work machine (with different Windows and JDK) the project (also Spring Boot but much bigger) that worked the last months is also crashing with the same error.

When the server crashes the autocompletion and navigation seems to work but a after a few seconds crashes.

Im also getting "conenction got disposed" if I open the developer tools and in the extension page-> runtime status

##### Environment
- Operating System: Windows 10 and 11
- JDK version: OpenJDK 17 OpenJDK 8
- Visual Studio Code version: 1.75.1 and 1.73
- Java extension version: 1.14 and 1,5 prerelease

##### Steps To Reproduce
1. Open a Spring Boot project
2. The server crashes

##### Current Result
```
[Trace - 10:22:51 AM] Sending request 'shutdown - (5)'.
[Error - 10:22:52 AM] Connection to server got closed. Server will not be restarted.
```

##### Expected Result
Working Java support

**Comment by fbricon** [comment]
Can you attach the logs from the "Java: Open All Log Files" command?

Also can you check if you see any additional log files under `%USERPROFILE%\.vscode\extensions\redhat.java-<version>\server\config_win` and/or  `%APPDATA%\Code\User\globalStorage\redhat.java\<version>\config_win`

**Comment by MarcSerret51** [comment]
Sure, these are the logs from my working machine:
[metadata_log.zip](https://github.com/redhat-developer/vscode-java/files/10731528/metadata_log.zip)
[redhat.java.zip](https://github.com/redhat-developer/vscode-java/files/10731518/redhat.java.zip)

**Comment by fbricon** [comment]
Can you try disabling all Java extensions but vscode-java, and execute the 'Java: Clean Java Language Server Workspace' command?

**Comment by MarcSerret51** [comment]
It doesn't work, same behaviour

**Comment by snjeza** [comment]
> When I open a new Spring Boot project (created with Spring Initializr extensions) in a freshly installed VSCode the Java Syntax Server just closes withouth any error. 

Could you check the Standard Java Server (Language Support for Java in the Output view)? 

> When the server crashes the autocompletion and navigation seems to work but a after a few seconds crashes.

When you open a Gradle/Maven/Eclipse project, Java LS closes the syntax server automatically and starts the Standard server.

> In my work machine (with different Windows and JDK) the project (also Spring Boot but much bigger) that worked the last months is also crashing with the same error.

You can try to set
```
"java.server.launchMode": "Standard",
```
to your settings.json.

**Comment by MarcSerret51** [comment]
> Could you check the Standard Java Server (Language Support for Java in the Output view)?

Seems to work fine, I'm getting what I think is a standard output.

> When you open a Gradle/Maven/Eclipse project, Java LS closes the syntax server automatically and starts the Standard server.

I didn't know that.

> You can try to set
"java.server.launchMode": "Standard",

Worked for like an hour and then suddenly stopped working. I losed the navigation, completion and other features. I had to restart VSC to make it work again.

**Comment by MarcSerret51** [comment]
Seems to happen when I force autocompletion.

For example:
I start to write the name of a class and I hit ctrl+space to get the classes with similar names. Seems to fail when I do this, but the Java Server Output doesn't shows any error or leak.

**Comment by MarcSerret51** [comment]
After a few minutes it seems to recover all the features and then stops working again.

**Comment by snjeza** [comment]
@MarcSerret51 Could you attach your logs - https://github.com/redhat-developer/vscode-java/issues/2933#issuecomment-1429471436

**Comment by jdneo** [comment]
> Seems to happen when I force autocompletion.
> 
> For example: I start to write the name of a class and I hit ctrl+space to get the classes with similar names. Seems to fail when I do this, but the Java Server Output doesn't shows any error or leak.

Does the issue still exist in `1.15.0`?

**Comment by MarcSerret51** [comment]
Sorry for taking so long to reply, I've been out of programming for a few days and haven't been able to test it.
It has happened again. I am attaching the logs in case they help. Sometimes a few minutes after blocking it works again and sometimes not.
[client.log.2023-02-22.2.zip](https://github.com/redhat-developer/vscode-java/files/10801661/client.log.2023-02-22.2.zip)
[log.zip](https://github.com/redhat-developer/vscode-java/files/10801666/log.zip)

Yes @jdneo, is happening on v1.16.2023022203 pre-release.

**Comment by snjeza** [comment]
@MarcSerret51 [client.log.2023-02-22.2.zip](https://github.com/redhat-developer/vscode-java/files/10801661/client.log.2023-02-22.2.zip) is empty.

**Comment by MarcSerret51** [comment]
Sorry, I attach 2 more logs.

[log.zip](https://github.com/redhat-developer/vscode-java/files/10837942/log.zip)
[clientlog.txt](https://github.com/redhat-developer/vscode-java/files/10837964/clientlog.txt)

**Comment by jdneo** [comment]
Have you tried to only enable `redhat.java` extension?

**Comment by MarcSerret51** [comment]
Yes, unfortunately doesn't work.

**Comment by MarcSerret51** [comment]
This comment https://github.com/redhat-developer/vscode-java/issues/2941#issuecomment-1456862036 solved my problem!
