### ISSUE TITLE
[critical] No references are found for methods used inside lambda expressions in pre-release

### ISSUE THREAD

**Issue by gayanper** [redhat-developer/vscode-java#2935]
No references are found for methods used inside lambda expressions in pre-release

##### Environment
- Operating System: All
- JDK version: 17
- Visual Studio Code version: 1.75.1 
- Java extension version: v1.15.2023021503

##### Steps To Reproduce
1. Search for method references of the method that is used inside lambda expressions or blocks

##### Current Result
No references are found

##### Expected Result
Lambda usage references must be counted as well.

**Comment by snjeza** [comment]
@gayanper I can reproduce the issue in pre release vscode-java, but can't when using the latest jdt.core master.
We should update the target platform.

**Comment by fbricon** [comment]
We need to update jdt.ls TP before closing this one

**Comment by gayanper** [comment]
Seems like we need to bump the TP, @fbricon should we bump the pre-release to i-builds instead of Milestones ?

**Comment by snjeza** [comment]
@gayanper https://github.com/eclipse/eclipse.jdt.ls/pull/2469 fixes the issue. Java LS already uses i-builds.

**Comment by rgrunber** [comment]
Closing as this will be addressed with the target platform update.
