### ISSUE TITLE
(Unsupported operation. Please use build.gradle) - Plugin can not recognize generated sources

### ISSUE THREAD

**Issue by anthonylgf** [redhat-developer/vscode-java#2937]
In the project, when I am trying to add a folder as a source using the option `Add folder to Java Source Path`, the IDE is raising the `Unsupported operation. Please use build.gradle`

The files are generated using the antlr-gradle plugin. I tried to follow the steps in this issue https://github.com/redhat-developer/vscode-java/issues/2159 but it did not solve the problem.

##### Environment
- Operating System: Ubuntu 22.04
- JDK version: OpenJDK 17
- Visual Studio Code version: 1.75.1
- Java extension version: 1.14.0

##### Steps To Reproduce
1. Create a gradle project using `gradle init`
2. Add the antlr plugin inside the gradle project
3. Create a simple .g4 file
4. Generate the files using the `gradle build`
5. Use the `Add folder to Java Source Path` to add the generated sources folder to the Java Source Path

Example:
The PR where I configured the Antlr plugin is this: https://github.com/anthonylgf/portugol-reverso/pull/6

Logs:
[client_log.txt](https://gist.github.com/anthonylgf/f2e4661a101f6a9ae55959de696f89db)
[log.txt](https://gist.github.com/anthonylgf/3e923cf86e371a68ecce5b45ac548944)

##### Current Result
The IDE is raising an error with the following message:
```
Unsupported operation. Please use build.gradle file to manage the source directories of gradle project.
```

##### Expected Result
The IDE recognizes the folder as a Java Source Path

##### Additional Information
Gradle Version: 7.4

**Comment by snjeza** [comment]
>  Please use build.gradle file to manage the source directories of gradle project.

You can try to add the following:

```
...
apply plugin: 'eclipse'
...
eclipse {
    classpath {
        containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
        file.whenMerged { cp ->
            def entries = cp.entries;
            def src = new org.gradle.plugins.ide.eclipse.model.SourceFolder('your_source1', null)
            entries.add(src)
            src = new org.gradle.plugins.ide.eclipse.model.SourceFolder('your_source2', null)
            entries.add(src)
           ...
        } 
    }
}
```
to build.gradle.
See https://github.com/eclipse/eclipse.jdt.ls/issues/1667#issuecomment-786101045

**Comment by anthonylgf** [comment]
Thanks @snjeza it worked fine!
