### ISSUE TITLE
Show the new class name repeatedly when moving class

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#2938]
##### Environment
- Operating System: Mac
- JDK version: 17.0.6
- Visual Studio Code version: 1.75.1
- Java extension version: 1.15.0

##### Steps To Reproduce
1. Open a java project, like https://github.com/redhat-developer/vscode-java/tree/master/test/resources/projects/eclipse/simple-app
2. Create a new java file and do steps following the gif showing.
![double-showing-class](https://user-images.githubusercontent.com/31497677/219293597-8d1af536-7dc6-452b-9549-78c381bffab5.gif)

##### Current Result
Show the class name repeatedly after selecting 'move class'.

##### Expected Result
Only show the name one time

**Comment by fbricon** [comment]
The bug already exists in 1.14

**Comment by CsCherrYY** [comment]
I'd like to prepare a fix for this.

**Comment by CsCherrYY** [comment]
this issue can be closed via https://github.com/eclipse/eclipse.jdt.ls/pull/2547
