### ISSUE TITLE
Types are missing from symbols outline

### ISSUE THREAD

**Issue by NaccOll** [redhat-developer/vscode-java#294]
It's useful for me to get the view of symbol tree by [Code Outline](https://github.com/patrys/vscode-code-outline)  in vscode. However, it depends on the symbol parse of various languages.  vscode-java  is helpful for me in most way, but It is slightly flawed about symbol.

As follows:

[![https://gyazo.com/d4dd1ce105c26416759a0cba5520bc9e](https://i.gyazo.com/d4dd1ce105c26416759a0cba5520bc9e.png)](https://gyazo.com/d4dd1ce105c26416759a0cba5520bc9e)

I can not get infomation about class when I pressed `ctrl+shift+o`. So code oultine offer me a flat list of  
 all property in code.

I hope that vscode-java offer me the infomation about class in File.
 
[![https://gyazo.com/f4ef4cab9759b65b138130f5fd71fd07](https://i.gyazo.com/f4ef4cab9759b65b138130f5fd71fd07.png)](https://gyazo.com/f4ef4cab9759b65b138130f5fd71fd07)

**Comment by fbricon** [comment]
The Java Language Server returns symbols according to the [LSP spec](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_documentSymbol), which does not define a tree-like structure for results.

I'm not sure we can do anything more about it. Do you have an example of tree-like structured symbols returned by other extensions?

**Comment by fbricon** [comment]
Ok, I tried with an html page, I can see now how the tree structure is achieved.

The server needs to return classes/interfaces themselves as symbols, so they can be referenced as parent nodes.

**Comment by gorkem** [comment]
@tsmaeder I think this affects Che too.

**Comment by fbricon** [comment]
Turns out this is a very easy fix, I'll make the PR

**Comment by NaccOll** [comment]
@fbricon Code Outline will generate the tree view of symbols. However, it need the infomation of class as the parent of element. If it is difficult to complete, then this is a unreasonable request. But, I can get the class by pressing `ctrl+t`. I think that it is hidden in the symbol of file.

**Comment by NaccOll** [comment]
@fbricon Sorry to bring you inconvenience, but I have to mention that there is no change to happen after I reinstall vscode-java.

**Comment by fbricon** [comment]
@NaccOll the new version of vscode-java with that fix will be released on the 15/09/2017.

There should be a CI build with the fix, under http://download.jboss.org/jbosstools/jdt.ls/staging/ but for some reason, it has not been deployed. We'll investigate why.

**Comment by fbricon** [comment]
@NaccOll Our build issue is fixed. Download the most recent `java-<version>.vsix` file from http://download.jboss.org/jbosstools/jdt.ls/staging/ and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

**Comment by NaccOll** [comment]
@fbricon Awesome! Perfect to meet my needs. Thank you for your help.
