### ISSUE TITLE
Upgrade gradle version doesn't work

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#2942]
##### Environment
- Operating System: Mac
- JDK version: 17.0.6
- Gradle version: 7.5.1
- Visual Studio Code version: 1.75.1
- Java extension version: 1.15.0

##### Steps To Reproduce
1. Open https://github.com/redhat-developer/vscode-java/tree/master/test/resources/projects/gradle/simple-gradle
1. Select 'Upgrade Gradle to 7.4.2' when it prompts 'Can't use java 17.x and gradle 4.x to import Gradle project xxx' > Wait for it completed

##### Current Result
The gradle version of the project isn't upgraded actually. And there is no upgrade installing process output.
![upgrade](https://user-images.githubusercontent.com/31497677/219314365-2bf80947-9384-4e8f-9c07-8af3542a6aa9.gif)

##### Expected Result
Can upgrade gradle version.

**Comment by fbricon** [comment]
I confirm this is a regression from 1.14

**Comment by fbricon** [comment]
Actually no it worked for me, I was just being stupid

**Comment by CsCherrYY** [comment]
I think it's a regression introduced by https://github.com/eclipse/eclipse.jdt.ls/pull/2304/files#diff-4be4f273e609fde1220c2d89f532f1fe207f280c100126555c3747fcf44d18d8, I'm preparing a fix.
