### ISSUE TITLE
Intellisense shows improperly for "import java.awt."

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#2943]
##### Environment
- Operating System: Mac
- JDK version: 17.0.6
- Visual Studio Code version: 1.75.1
- Java extension version: 1.15.0

##### Steps To Reproduce
1. Open a java project, like https://github.com/redhat-developer/vscode-java/tree/master/test/resources/projects/eclipse/simple-app
1. Open a java file > Type "import java.awt." > Press ctrl+space

##### Current Result
![image](https://user-images.githubusercontent.com/31497677/219318866-ac3b230e-a3a7-4bfa-afa4-6d3cd251491d.png)

##### Expected Result
Expect to show including `java.awt.List`.

**Comment by testforstephen** [comment]
this is a known issue from https://github.com/eclipse/eclipse.jdt.ls/pull/2467#issuecomment-1430924232. Assign to @jdneo for further improvement.
