### ISSUE TITLE
未捕获的错误(2) Extension 'redhat.java' CANNOT use API proposal: documentPaste. Its package.json#enabledApiProposals-property declares: [] but NOT documentPaste. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api redhat.java Connection got disposed.

### ISSUE THREAD

**Issue by izilongwan** [redhat-developer/vscode-java#2950]
Type: <b>Bug</b>

未捕获的错误(2)
Extension 'redhat.java' CANNOT use API proposal: documentPaste. Its package.json#enabledApiProposals-property declares: [] but NOT documentPaste. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api redhat.java
Connection got disposed.

Extension version: 1.14.0
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (18.26GB free)|
|Process Argv|--file-uri file:///d%3A/Workspace/TrustworthyEshow.code-workspace --enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id f24fe983-78b2-424b-b832-a858c79abae1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983

```

</details>

**Comment by CsCherrYY** [comment]
could you try to update VS Code version to newest (1.75.1) to see if this issue can be resolved?

**Comment by izilongwan** [comment]
你们都不修复这个问题吗, 都远古问题了, 多少个版本都有

**Comment by izilongwan** [comment]
Type: <b>Bug</b>

Connection got disposed.
Cannot set properties of undefined (setting 'text')
Cannot set properties of undefined (setting 'text')
Cannot set properties of undefined (setting 'text')
Cannot set properties of undefined (setting 'text')
Cannot set properties of undefined (setting 'text')

Extension version: 1.14.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (24.15GB free)|
|Process Argv|--file-uri file:///d%3A/Workspace/mico-service.code-workspace --enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id f24fe983-78b2-424b-b832-a858c79abae1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30662993
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983
vsctsb:30662444

```

</details>
