### ISSUE TITLE
Where does vscode-java takes its maven executable from ? How can this be configured ?

### ISSUE THREAD

**Issue by tchinchow** [redhat-developer/vscode-java#2958]
I'm trying to setup a devcontainer for a legacy project with very specific maven and java versions requirements.

The project builds offline and against a pre-loaded maven repo.
_I'm struggling to understand which extension does what between Microsoft `vscode-maven` and RedHat `vscode-java`._

The following settings seems to work when using the palette `>maven: Execute Commands`. Build is successful:
```
"maven.settingsFile": "/workspace/settings.xml",
```

My understanding is that they come from Microsoft `vscode-maven`...

However

##### Current Result

The output of the "Language Support for Java" fails with a lot of "Non-resolvable parent POM" errors.
Java language support is not usable (does not find any class).

##### Expected Result
I'd expect it to find my classes and be able to browse through the code and use F12, then follow/find implementations of a class, etc...

##### Additional Informations
I see that when the devcontainer starts then a `pom.lastUpdated` file is created in the local repository where the artifact fails to load.

This makes me believe that it finds the `settings.xml` file and attempt to use it

Here is my settings file...
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository>/workspace/maven-repo</localRepository>
  <offline>true</offline>
  <servers>
    <server>
      <id>central</id>
    </server>
  </servers>
  <mirrors>
    <mirror>
        <id>central-secured</id>
        <name>rndsoft-maven-central</name>
        <url>https://repo1.maven.org/maven2/</url>
        <mirrorOf>central</mirrorOf>
    </mirror>
  </mirrors>
</settings>
```

My understanding is that Maven in RedHat `vscode-java` does not seem to honor the `offline` setting...
... but Microsoft `vscode-maven` does ...

I tried many things and I believe that RedHat `vscode-java` searches the `settings.xml` file in the repo and does not need parameters from Microsoft `vscode-maven` extension.

I had this behavior when the Maven version on the project was not the expected maven version ...

I'm starting to believe that RedHat `vscode-java` embedds its own version of maven and this does not play well with my pre-loaded local repo ?
If yes how can I prevent this or force a specific version ? _(I'm using devcontainer precisely because I need to choose Maven and Java versions !)_

**Comment by fbricon** [comment]
vscode-java doesn't know anything about vscode-maven. Try using "java.configuration.maven.userSettings".
However, the underlying Maven tooling vscode-java depends on, is indeed using an embedded Maven runtime to perform dependency resolution, something we can't change.

**Comment by tchinchow** [comment]
Many thanx for your time.

This confirms my doubts.

In my case It was a maven issue and I just found that cleaning the pre-loaded local maven repository helped.
https://stackoverflow.com/questions/5271707/maven-tries-to-download-dependency-despite-it-existing-in-local-repository

So ok I could not change Maven version but I got around it.

Thanx !!!
