### ISSUE TITLE
Auto Completion does not work in a specific place; caused by record class.

### ISSUE THREAD

**Issue by ArithAuth** [redhat-developer/vscode-java#2969]
[If I put inner record that takes at least 1 parameter, Auto Completion does not work in the method above the record.]

##### Environment
- Operating System: macOS Ventura 13.2.1
- JDK version: java version "19" 2022-09-20
- Visual Studio Code version: 1.75.1 (Universal)
- Java extension version: 1.15.0

##### Steps To Reproduce
<pre>
class Test {
    void above_method() {
        // Auto Completion does not work here.
    }

    class AAAA {
        // works here
    }

    record InnerTest(Void v) { // at least one parameter
    }

    void name() {
        // works here
    }
}
</pre>

##### Current Result
Candidate code list does not appear in a specific place.

##### Additional Informations
I use maven-archetype-quickstart and apologize If this is not reproducible.

**Comment by ArithAuth** [comment]
I think this is a separated issue so I changed the title more detail.

**Comment by snjeza** [comment]
A related issue - https://github.com/eclipse-jdt/eclipse.jdt.core/issues/757

**Comment by ArithAuth** [comment]
Oops, thank you.
