### ISSUE TITLE
java.completion.guessMethodArguments is false not working

### ISSUE THREAD

**Issue by Skyxim** [redhat-developer/vscode-java#2970]
When `"java.completion.guessMethodArguments": false`, a parameter will still be filled in when the method is called

##### Environment
- Operating System: Windows 11 22H2
- JDK version: openjdk version "11.0.14.1" 2022-02-08 LTS
OpenJDK Runtime Environment Zulu11.54+25-CA (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.54+25-CA (build 11.0.14.1+1-LTS, mixed mode)
- Visual Studio Code version: 1.75.1
- Java extension version: v1.15.0

##### Steps To Reproduce
1. close `java.completion.guessMethodArguments` 
2. use `Collections.singleton`

##### Current Result
![image](https://user-images.githubusercontent.com/70276018/221772029-5abc94cd-0cd9-4324-a539-77ee02089360.png)

##### Expected Result
```
Collections.singleton(|)
```
##### Additional Informations
![image](https://user-images.githubusercontent.com/70276018/221772241-9af0b907-561b-47a0-9cb0-46193c6a0de0.png)

**Comment by jdneo** [comment]
Duplicated with https://github.com/redhat-developer/vscode-java/issues/2903
