### ISSUE TITLE
Couldn't start client Language Support for Java, both on codespaces and as well as local server

### ISSUE THREAD

**Issue by swapnilxi** [redhat-developer/vscode-java#2971]
the issue with the update of language support for java(tm) by RedHat, fails to configure runtime or import java project properly

##### Environment
- Operating System: windows and codespaces
- JDK version: microsoft-jdk-17.0.6-

- Visual Studio Code version: codespaces
- Java extension version: v.15.0

##### Steps To Reproduce
1. updating language support for java by RedHat
--
2. and launching vs code again either on local or in codespace 

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
![image](https://user-images.githubusercontent.com/54740310/221932433-d6fd390f-d375-41fd-977e-f6ee9cbc2cb1.png)

##### Current Result
no java project detected 
##### Additional Information
- as soon I updated the extension, it fails to catch my project, I tried updating 
- reinstalling, killing java service and reinstalling don't work
- test with a different version but same result

**Comment by jdneo** [comment]
Could you share a sample project?
