### ISSUE TITLE
Slow builds due to large number of project files

### ISSUE THREAD

**Issue by Carson-yy** [redhat-developer/vscode-java#2982]
d0bc8853 Building [Done]
85a443d4 Validate documents [Done]
99449c46 Building: 85% Refreshing '/cloudeasy-cloudmanage'. [854/1000]

Many project files, frequent Building, smart code hints and slow jumps！！！(较大项目开发过程中，编写代码过程中频繁编译，经常出现代码提示慢，跳转实现慢甚至语法检测都会延迟好几秒才会完成！)

![image](https://user-images.githubusercontent.com/12856549/223062795-5b72f838-297b-4f26-8b12-a33f986ea5c7.png)
![image](https://user-images.githubusercontent.com/12856549/223062860-10b59644-c5a9-4152-816b-00f3f1cda3b7.png)

**Comment by parthasaradhie** [comment]
I'm also facing the same issue. Where if you Java project is monolithic with large files or a single Java file containing more than 400 line of code everything becomes slow

**Comment by snjeza** [comment]
@yaegar @parthasaradhie could you attach a project example reproducing the issue?

**Comment by yaegar** [comment]
> I can't share the logs and project details because of company security policy. But few details like It's spring boot project with more than 200 Java classes and if the file has more than 400 lines then the content assist and cmd+click on method is slow
> 
> Other than that if file is small then it's almost smooth
> 
> Mac os Intel chip Java server is running default Java 17

me too

**Comment by snjeza** [comment]
> I can't share the logs and project details because of company security policy. But few details like It's spring boot project with more than 200 Java classes and if the file has more than 400 lines then the content assist and cmd+click on method is slow
Other than that if file is small then it's almost smooth

Could you provide more details?
How long does it take?  Could you show your settings.json? Do you have some other extensions? Do you use lombok?

**Comment by parthasaradhie** [comment]
Here is video recording for above scenario.
1. content assist is too slow 
2. The error line processing very slow

Video
https://user-images.githubusercontent.com/12638462/224462988-2e780eb5-dfba-4d40-a93a-40b9c518ec1b.mov

Attaching the detailed log (class names and file names are obscured) 
https://gist.github.com/parthasaradhie/34bca17c57e45e39e5a0bb35621ed9f6

**Comment by snjeza** [comment]
@parthasaradhie Which VS Code version are you using?
Could you show [your server log](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs)?

-

**Comment by parthasaradhie** [comment]
Vscode Version: 1.76.0
Language Support for Java(TM) by Red Hat: 1.15
Debugger for Java: v0.49.2023022723
IntelliCode: v1.2.30
Maven for Java: v0.40.4
Project Manager for Java: v0.21.1

Also one more point is if i run the springboot application in Debug mode. the content assist and all other functionalities will become even slower of response time of more than 10-15 seconds

Here are the server logs:
https://gist.github.com/parthasaradhie/79c82e3a9dbd10c21c64d9b24d38f395

**Comment by snjeza** [comment]
@parthasaradhie @yaegar Could you test [VS Code 1.16.3](https://github.com/snjeza/vscode-test/raw/master/java-1.16.3.vsix)?

**Comment by parthasaradhie** [comment]
@snjeza 
Good work
Few Observation after testing:
1. Not only content assist but everything became lot faster than before like 100% faster (reference, method usages and all)
2. Lombok is completely broken not at all

Let me know if anything else needed to test.

**Comment by snjeza** [comment]
> Lombok is completely broken not at all working

@parthasaradhie You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/2983#issuecomment-1458753354

**Comment by parthasaradhie** [comment]
@snjeza 
I have enabled the Lombok and getting the same issue as above with 1.16.3
It decreased  the performance

**Comment by snjeza** [comment]
@parthasaradhie I can't reproduce the issue.
Could you show your settings.json?

**Comment by parthasaradhie** [comment]
@snjeza 
I have successfully enabled the lombok. Its working as expected.
But The content assist, method reference navigation performances has degraded a lot 
1.16.3 doesnt improve any performance, show similar effects as shown in the above [video](https://github.com/redhat-developer/vscode-java/issues/2982#issuecomment-1464817077) of mine

**Comment by snjeza** [comment]
@parthasaradhie could you try to set
```
"java.references.includeAccessors": false,
"java.implementationsCodeLens.enabled": false,
"java.referencesCodeLens.enabled": false,
"java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:MetaspaceSize=300M -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx5G -Xms2G -Xlog:disable -XX:-HeapDumpOnOutOfMemoryError -javaagent:<path_to_lombok-1.18.27.jar.jar",
```
[lombok-1.18.27](https://github.com/snjeza/vscode-test/raw/master/lombok-1.18.27.jar)

could you show your pom.xml or build.gradle?

**Comment by parthasaradhie** [comment]
I cant provide the pom.xml
And I can confirm we are not doing much processing or have plugins installed only docker (runs at delploy time) and de-lombok(runs at compile time)



## used your lombok 1.18.27 in both settings.xml  and pom.xml(1.18.26)

### content assist :

- If we type like Str then the result is faster than the issue in video.
- but if i type something after "." like test.get then its very fast
- cmd+space is still slow after "." like (test.(cmd+spce)) but results are getting <6 sec
- After "new" its super slow (String s1 = new (cmd+space)) is very slow

### Red squiggly line (shows error)
- Its verry laggy shows error in previous line  


Got this below error one time :

```WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
[Error - 01:22:16] Client Language Support for Java: connection to server is erroring. Shutting down server.
[Error - 01:22:16] Client Language Support for Java: connection to server is erroring. Shutting down server.
[Error - 01:22:16] Client Language Support for Java: connection to server is erroring. Shutting down server.
[Error - 01:22:18] Stopping server timed out
[Error - 01:22:18] Stopping server failed
Error: Stopping the server timed out
	at /Users/partha.e/.vscode/extensions/redhat.java-1.16.3/dist/extension.js:2:918472
[Error - 01:22:18] Stopping server failed
Error: Stopping the server timed out
	at /Users/partha.e/.vscode/extensions/redhat.java-1.16.3/dist/extension.js:2:918472
[Error - 01:22:18] Stopping server failed
Error: Stopping the server timed out
	at /Users/partha.e/.vscode/extensions/redhat.java-1.16.3/dist/extension.js:2:918472
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
[Error - 01:22:31] Client Language Support for Java: connection to server is erroring. Shutting down server.
[Error - 01:22:31] Client Language Support for Java: connection to server is erroring. Shutting down server.

```

**Comment by snjeza** [comment]
> used your lombok 1.18.27 in settings.xml and pom.xml(1.18.26)

It is fine.

> cmd+space is still slow after "." like (test.(cmd+spce)) but results are getting <6 sec

@parthasaradhie Could you describe the `test` class?

**Comment by parthasaradhie** [comment]
@snjeza 

the test class has 1500 lines of code with almost 70 imports (56 are lombok classes) use spring boot @autowired for dependency injection approximately 30 methods are there (16 are public)

**Comment by snjeza** [comment]
@parthasaradhie Could you show an example of your lombok class?

Could you try to set the following properties:
```
"java.references.includeAccessors": false,
    "java.inlayHints.parameterNames.enabled": "none",
    "java.implementationsCodeLens.enabled": false,
    "java.referencesCodeLens.enabled": false,
    "java.configuration.maven.defaultMojoExecutionAction": "ignore",
    "java.completion.postfix.enabled": false,
    "editor.snippetSuggestions": "none",
    "java.completion.matchCase": "off",
    "java.completion.maxResults": 100,
```

**Comment by parthasaradhie** [comment]
@snjeza 

- With the above config the contentassit became lot better for type ahead content assist very responsive.
- but manual cmd+space content assist still slow but very responsive of <3sec
- Method name cmd+click has better response than before but slow (almost taking 3-5sec) to display the result.
- The Red squiggly line (shows error) is still laggy its not fixed.

**Comment by snjeza** [comment]
@parthasaradhie Could you check https://github.com/snjeza/vscode-test/raw/master/java-1.16.4.vsix ?
You can check the issue with or without the properties from https://github.com/redhat-developer/vscode-java/issues/2982#issuecomment-1465313123

**Comment by parthasaradhie** [comment]
@snjeza 

My Observations for above build:

1. automatic content assist(like on . or type) is faster than previous build with and without that settings.
2. content assist with manual trigger like cmd+space is also improved with and without that settings.
3. content assist after new keyword is slow for both manual and automatic with and without that settings.
4. The error Red squiggly line is still laggay and taking 3-5 sec to respond with and without that settings.

**Comment by snjeza** [comment]
@parthasaradhie Could you check https://github.com/snjeza/vscode-test/raw/master/java-1.16.5.vsix

> 4. The error Red squiggly line is still laggay and taking 3-5 sec to respond with and without that settings.

I can't reproduce this. Could you provide more details?

**Comment by parthasaradhie** [comment]
@snjeza 

Attaching a video for your reference . here you can observer the red line even to show that there is a error takes 5sec and to disappear that red line is very laggy and the file is > 1500 lines (used the above config you have provided and using 1.16.5 provided above)
attaching logs for the same :
https://gist.github.com/parthasaradhie/c3c6a17cff8129c6a457cec55636a8e1

https://user-images.githubusercontent.com/12638462/225058571-c74ce044-c7cf-43ef-bf32-1a2871425c9c.mov

**Comment by snjeza** [comment]
>  here you can observer the red line even to show that there is a error takes 5sec and to disappear that red line is very laggy and the file is > 1500 lines 

@parthasaradhie Do you mean on a red line in the editor?

I have checked your log and completion lasts <= 1116ms (1.1second)

**Comment by parthasaradhie** [comment]
@snjeza 

Exactly I'm confused after seeing logs, in the video it's clearly seen its defenetly taking more than 4 seconds. I think either there might be issue in log time calculation or if server is really responding in 1.1 Sec the why is it taking 4 sec to reflect in the UI

**Comment by snjeza** [comment]
> Exactly I'm confused after seeing logs, in the video it's clearly seen its defenetly taking more than 4 seconds.

@parthasaradhie Does it only happen the first time?

**Comment by parthasaradhie** [comment]
@snjeza it happens all the time but only in these kind of large files >500 line or lot of Lombok classes imported like that

**Comment by snjeza** [comment]
@parthasaradhie Does 1.16.5 improves CA compared to `pre release` or 1.15?

> ... lot of Lombok classes imported like that

I will try to simulate this case. Which lombok annotations are you using?

**Comment by parthasaradhie** [comment]
@snjeza 
Every pojo class is created with Lombok in this repo 
Every pojo has 
@data @NoargConstructor @Allargconstructor @builder

**Comment by snjeza** [comment]
> Exactly I'm confused after seeing logs, in the video it's clearly seen its defenetly taking more than 4 seconds.

@parthasaradhie Could you, please, add
```
"java.jdt.ls.vmargs": "-Dlog.level=ALL -Djdt.ls.debug=false <your_vmargs>",
```
and repeat your screencast and/or log?

**Comment by parthasaradhie** [comment]
@snjeza 

Sharing the video for the same. Here there is a record where response time is 3.9 sec
also sharing logs for the same.  One observation I found here is LS is processing all the opened files in the editor irrespective of the file I'm editing.

Test2.java is exact replica of Test.java
Like in the below Video you can see Two files Test.java, Test2.java opened in VScode even though i'm editing only Test.java in logs I can see LS is processing the Two files. See if this helps in improving it.

If I close the Test2.java LS is not processing the Test2.java but only the file that im editing(Test.java).

https://gist.github.com/parthasaradhie/f74fa76ee00233104019c906b1135b25

https://user-images.githubusercontent.com/12638462/225188419-d2c5367f-2bbb-47b2-92df-9f8836b9aaf6.mov

**Comment by snjeza** [comment]
> Sharing the video for the same. Here there is a record where response time is 3.9 sec
also sharing logs for the same.

Could you, please, check how it works without lombok?

> One observation I found here is LS is processing all the opened files in the editor irrespective of the file I'm editing.

We have to process all opened files. It is possible that editing Test.java fixes or introduces an error in Test2.java.
Steps to reproduce:
- create the `test2()` method in Test.java 
- invoke `new Test().test()` in Test2.java;
- save both classes
  you will see the `The method test is undefined for the type Test` error.
- edit Test.java and update `test2` to `test`; you don't need to save anything
  it will fix `The method test is undefined for the type Test` in Test2.java

**Comment by parthasaradhie** [comment]
@snjeza 

> Could you, please, check how it works without lombok?

I have repetead the same test on the same project DE-lomboked (using delomboked plugin) 
Observations

- Content assist is freakingly fast absolutely no-lag in both manual and auto triggering.
- The Red line response is still laggy but response is coming within a second or two as shown in below video and logs
- I feel because of some lombok processing its getting lagged.

https://gist.github.com/parthasaradhie/eec24a25fb187f7c50e8c974a7545564

https://user-images.githubusercontent.com/12638462/225515299-590b1070-10d6-4b7e-89bd-165e05abe113.mov

**Comment by snjeza** [comment]
> I feel because of some lombok processing its getting lagged.

You are right. Lombok injects its own ast parser - https://github.com/projectlombok/lombok/blob/master/src/core/lombok/eclipse/EclipseAST.java#L62
Are you using lombok.config?

**Comment by parthasaradhie** [comment]
> Are you using lombok.config?

Nope this project desnt uses any custom config

**Comment by snjeza** [comment]
@parthasaradhie Could you try to add
```
"java.jdt.ls.vmargs": "-Dlombok.disableConfig=true -Dlog.level=ALL -Djdt.ls.debug=false <your_vmargs>",
```

**Comment by parthasaradhie** [comment]
@snjeza its still the same

**Comment by snjeza** [comment]
>  ...but error red line...
```
public class Test {
    private void Test() {
        
    }
}
```

@parthasaradhie Could you try to replace `private void Test() ` with `private void test()`?

**Comment by snjeza** [comment]
> ... method (cmd+click) is slower

It should be faster with `-Dlombok.disableConfig=true` especially if your packages have many segments/directories.

**Comment by parthasaradhie** [comment]
@snjeza your right, I have been using your extension for a while with above settings, content assist ,method navigation and Lombok processing works faster than the base extension version.
But one notable difference is it not as fast as intellij editor but its faster to an acceptable usage. Appreciate your hardwork 9n this 
Basically I want to replace intellij with vscode here

**Comment by rgrunber** [comment]
Definitely lombok related (see bottom).

![image](https://user-images.githubusercontent.com/1417342/228706024-6214c6a1-83a6-4e03-be0a-b2cef8eebffc.png)

**Comment by snjeza** [comment]
@parthasaradhie @rgrunber Could you check https://github.com/snjeza/vscode-test/raw/master/java-1.17.3.vsix

settings.json
```
"java.jdt.ls.vmargs": "-Dlombok.disableConfig=true -Dlog.level=ALL -Djdt.ls.debug=false -javaagent:/path_to_lombok-1.18.27.jar<your_vmargs>",
"java.jdt.ls.lombokSupport.enabled": false,
```

**Comment by rgrunber** [comment]
Is there anything left to do here or can this be closed due to https://github.com/eclipse/eclipse.jdt.ls/pull/2535 & https://github.com/eclipse/eclipse.jdt.ls/pull/2574 .
