### ISSUE TITLE
Support for val in lombok

### ISSUE THREAD

**Issue by FunctionDJ** [redhat-developer/vscode-java#2983]
Lombok's `val` doesn't seem to be supported. The type of the variable isn't inferred and becomes `Object` when referenced.

##### Environment
- Operating System: Windows 10 21H2
- JDK version: Java 17
- Visual Studio Code version: 1.76.0
- Java extension version: v1.15.0

##### Steps To Reproduce
1. Import and use `lombok.val`

##### Current Result
![image](https://user-images.githubusercontent.com/34871211/223144302-7d4426ae-8d21-486a-8392-08111979b1a7.png)

##### Expected Result
The type is properly recognized. Similar behavior to `final var`.

**Comment by fbricon** [comment]
Might be an Eclipse JDT bug upstream. Can you check if it works in a [lombokified Eclipse IDE](https://www.baeldung.com/lombok-ide#eclipse)?

**Comment by FunctionDJ** [comment]
@fbricon I followed those instructions and it works in Eclipse. Hovering over the created variable shows the correct type.

**Comment by fbricon** [comment]
@FunctionDJ thanks for checking. So it must be a jdt.ls issue then. @snjeza can you please take a look?

**Comment by fbricon** [comment]
@FunctionDJ does completion work too in Eclipse, with the expected methods from the inferred type?

**Comment by FunctionDJ** [comment]
I think this is what you mean and yes, it works:
![image](https://user-images.githubusercontent.com/34871211/223455954-3c8c9d92-cc84-4807-b978-ff9361766912.png)

**Comment by snjeza** [comment]
@FunctionDJ Which version of Eclipse have you tested?

**Comment by snjeza** [comment]
This is an upstream lombok issue.  See 
- https://github.com/projectlombok/lombok/issues/3332
- https://github.com/projectlombok/lombok/pull/3347
- https://github.com/redhat-developer/vscode-java/issues/2887

@FunctionDJ Could you check [lombok-1.18.27](https://github.com/snjeza/vscode-test/raw/master/lombok-1.18.27.jar)
It includes https://github.com/projectlombok/lombok/pull/3347
You should set the following properties
```
"java.jdt.ls.lombokSupport.enabled": false,
"java.jdt.ls.vmargs": " -javaagent:<path_to_lombok-1.18.27.jar> <your_arguments>",
```

**Comment by FunctionDJ** [comment]
@snjeza I did those changes and it seems to have fixed `lombok.var` but not `val`.

**Comment by snjeza** [comment]
@FunctionDJ Could you try to [clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)?
![lombokval](https://user-images.githubusercontent.com/388609/223794335-cf6be1f1-fb1d-4c5c-9dc9-4cbe4f1e924e.gif)

**Comment by FunctionDJ** [comment]
@snjeza Unfortunately, same result. I also checked `"java.trace.server": "verbose"` and it looks the same there.

**Comment by snjeza** [comment]
@FunctionDJ Could you show your user and workspace settings.json?

**Comment by FunctionDJ** [comment]
Sure. I've limited the entries to the ones that contain "java" somewhere.
I guess the `vmargs` of the user settings look suspicious, but they're being overwritten by the workspace settings.

User `settings.json`:
```json
{
	"java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"c:\\Users\\some-user\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\server\\lombok.jar\"",
	"java.configuration.runtimes": [
		{
			"path": "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.3.7-hotspot",
			"name": "JavaSE-17"
		}
	],
	"java.format.settings.url": "C:/local/foo.xml",
	"java.autobuild.enabled": true,
	"boot-java.live-information.fetch-data.max-retries": 20,
	"boot-java.live-information.fetch-data.retry-delay-in-seconds": 5,
	"java.debug.settings.showLogicalStructure": true,
	"java.debug.settings.showToString": true,
	"java.debug.settings.showQualifiedNames": false,
	"java.debug.settings.showStaticVariables": false,
	"java.debug.settings.showHex": false,
	"boot-java.rewrite.reconcile": true,
	"[java]": {
		"editor.defaultFormatter": "redhat.java"
	},
	"java.inlayHints.parameterNames.enabled": "none",
	"java.sources.organizeImports.starThreshold": 3,
	"java.sources.organizeImports.staticStarThreshold": 3,
}
```
Workspace `settings.json`:
```json
{
	"java.dependency.packagePresentation": "hierarchical",
	"java.jdt.ls.lombokSupport.enabled": false,
	"java.jdt.ls.vmargs": "-javaagent:C:\\Users\\some-user\\Downloads\\lombok-1.18.27.jar -Xlog:jni+resolve=off",
	"java.configuration.updateBuildConfiguration": "automatic",
	"debug.console.wordWrap": false,
	"java.compile.nullAnalysis.mode": "automatic",
}
```

**Comment by snjeza** [comment]
@FunctionDJ I have tested with your settings. It works fine.

![lombokval2](https://user-images.githubusercontent.com/388609/224122552-33d0cee8-7596-4c75-9147-2736558a66b5.gif)

Could you show an example reproducing the error?

**Comment by snjeza** [comment]
@FunctionDJ Could you remove
```
-javaagent:\"c:\\Users\\some-user\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\server\\lombok.jar\"
```
from your settings.java as well as the gabrielbb.vscode-lombok extension? This extension is deprecated.

**Comment by michael-emmi** [comment]
Just in case anybody wants a third data point here: I had the same problem as @FunctionDJ.@snjeza’s proposed fix of disabling LS Lombok support and adding 1.18.27 jar as agent worked like a charm.

**Comment by HueyJ** [comment]
I met this problem, too.
And this is what I figure it.
![lombokval](https://user-images.githubusercontent.com/23316643/224465130-b205167c-c8b8-401b-8359-151f09732f2c.PNG)

[https://projectlombok.org/features/val](url)

**Comment by Rawi01** [comment]
Since version 1.18.22 lombok uses the Java native version of `var`, or at least tries to do that. It also converts `val` to `final var` on Java 10+. I think we have not covered the case that someone imports `lombok.var` if there is also native support for it.

**Comment by FunctionDJ** [comment]
@snjeza I used 4.26.0 but i've installed 4.27.0 and made sure to add the same Adoptium JDK as i use in VSCode and it seems to ignore the lombok import for some reason.
![image](https://user-images.githubusercontent.com/34871211/225863873-0f017f4e-4430-4d52-a85b-a9b4eac8d44b.png)

**Comment by FunctionDJ** [comment]
@Rawi01 Yeah it came up by coincidence because we want to turn more than 3 imports from the same package into a wildcard import. That's how i initially ran into this issue because `lombok.var` got implicitly imported from a wildcard, even though we can easily use native `var`. At the time i thought that `val` was the issue (as seen in the first screenshot of this issue).
Maybe i should check out lombok 1.18.21 where lombok doesn't use the native keywords yet and see if that makes a difference.

**Comment by FunctionDJ** [comment]
The lombok version before 22 that i could obtain was 1.18.20 and while it doesn't show any errors with `val` or `var` imported and used, it also doesn't look right (`toReportList` is `Object` on hover).
![image](https://user-images.githubusercontent.com/34871211/225867240-a5e417ea-71a7-42b6-b2d6-30d95b31d7ad.png)
This is probably similar to my initial issue after which snjeza advised me to update my lombok version, so this result might not be very meaningful to this issue.

**Comment by snjeza** [comment]
@FunctionDJ I used 4.26.0 but i've installed 4.27.0 and made sure to add the same Adoptium JDK as i use in VSCode and it seems to ignore the lombok import for some reason.

It is an upstream lombok issue. See https://github.com/redhat-developer/vscode-java/issues/2983#issuecomment-1473499216

**Comment by FunctionDJ** [comment]
Fixed upstream (edge release is working for me): https://github.com/projectlombok/lombok/issues/3332
