### ISSUE TITLE
Intellisense only autocompletes beginning of function names

### ISSUE THREAD

**Issue by alx1024** [redhat-developer/vscode-java#2987]
[provide a description of the issue]

##### Environment
- Operating System:  Win 11
- JDK version: 17
- Visual Studio Code version: 1.76.0
- Java extension version: v0.25.8

##### Steps To Reproduce
If you type a "." and "upper" after a String variable "toUpperCase()" will not be autocompleted, IntelliJ does this

**Comment by fbricon** [comment]
Works for me:
<img width="581" alt="Screenshot 2023-03-08 at 11 58 59" src="https://user-images.githubusercontent.com/148698/223695689-349159e9-793d-4af5-a9c5-f75c63b4e763.png">

Can you share your settings.json?

**Comment by alx1024** [comment]
Thank you for responding so quickly!
`{
    "editor.formatOnSave": true,
    "editor.suggestSelection": "first",
    "files.exclude": {
        "**/.classpath": true,
        "**/.factorypath": true,
        "**/.history": true,
        "**/.mvn": true,
        "**/.project": true,
        "**/.settings": true,
        "**/bin": true,
        "**/target": true
    },
    "editor.codeActionsOnSave": {
        "source.organizeImports": true,
        "source.addMissingImports": true,
    },
    "explorer.confirmDragAndDrop": false,
    "workbench.startupEditor": "none",
    "explorer.confirmDelete": false,
    "telemetry.telemetryLevel": "off",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "react-native-tools.showUserTips": false,
    "security.workspace.trust.enabled": false,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": true,
    "window.title": "${rootName}${separator}${activeEditorLong}",
    "redhat.telemetry.enabled": false,
    "editor.rulers": [
        160
    ],
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 160,
    "html.format.wrapLineLength": 160,
    "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"c:\\Users\\Alex\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\server\\lombok.jar\"",
    "auto-rename-tag.activationOnLanguage": [
        "typescriptreact"
    ],
    "terminal.integrated.scrollback": 1000000,
    "editor.inlayHints.enabled": "offUnlessPressed",
    "search.exclude": {
        "**/*.code-search": true,
        "**/bower_components": true,
        "**/node_modules": true
    },
    "npm.keybindingsChangedWarningShown": true,
    "search.quickOpen.includeHistory": false,
    "typescript.preferences.quoteStyle": "double",
    "javascript.preferences.quoteStyle": "double",
    "editor.mouseWheelZoom": true,
    "xml.java.home": "C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.5.8-hotspot",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "editor.accessibilitySupport": "off",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        },
        "Windows PowerShell": {
            "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        }
    },
    "terminal.integrated.defaultProfile.windows": "Windows PowerShell",
    "editor.linkedEditing": true,
    "terminal.external.windowsExec": "%LOCALAPPDATA%/Microsoft/WindowsApps/wt.exe",
    "git.openRepositoryInParentFolders": "never"
}`

**Comment by fbricon** [comment]
probably a very long shot, but you can try uninstalling gabrielbb.vscode-lombok extension (vscode-java now provide a better lombok support) and then remove the "java.jdt.ls.vmargs" setting

**Comment by alx1024** [comment]
Suddenly it works, the only thing i changed was removing a obsolete color theme line from settings.json before posting it, seems unrelated. Thank you for your help and time and for showing me how to properly edit json-code!
