### ISSUE TITLE
Config Java Language Servce with Maven Profile

### ISSUE THREAD

**Issue by Nonlone** [redhat-developer/vscode-java#2989]
[provide a description of the issue]

##### Environment
- Operating System: mac os 13.2.1
- JDK version: 1.8 ~ 17
- Visual Studio Code version: 1.76.0
- Java extension version: v1.15.0

##### Steps To Reproduce
1. my project pom defined my pom parent to our private gitlab server
2. my pom does not defined any profile 
3. profile config in ~/.m2/settings.xml，but I don't config activate because I had some project dosen't to point to our private gitlab server

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

log in client.log
message: Project build error: Non-resolvable parent POM for xxxxx:1.0.0: xxxx:commons-app-parent:pom:1.2.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM; code: 0; resource: /xxxxx/pom.xml; line: 6\n

##### Current Result
show the project is not valid java project

##### Expected Result
run with maven profile options

**Comment by fbricon** [comment]
I don't understand your issue with regard to profiles. Can you provide a sample project demonstrating the issue?

**Comment by Nonlone** [comment]
I create a sample project to simulate my real project , here is repository address : https://github.com/Nonlone/NotAValidJavaProjectSample

**Comment by rgrunber** [comment]
I don't think we have a way to activate certain profile options. We do have both `java.configuration.maven.userSettings` & `java.configuration.maven.globalSettings` and you could supply a `settings.xml` to one of those where the necessary profile is activated. Would that work ?

**Comment by jdneo** [comment]
With the latest `Language Support for Java(TM) by Red Hat` (1.31.0) and latest `Extension Pack for Java` (0.27.0). You can now change the Maven active profile with a GUI with following steps:

1. Click the java status bar
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/82fa54f1-36a2-4982-9c3e-c7b581bb80a0)
2. Select `Open Project Settings`
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/3f8491a1-ceda-4ccb-bffd-4cb1fb64dbc0)
3. Go to the `Maven` tab, and type the profile names (comma separated) which you want to enable. For example: `profile1,profile2`
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/c69aedd0-b8db-440c-845f-49c199a7d709)
