### ISSUE TITLE
Syntax highlighting is not work on special named classes

### ISSUE THREAD

**Issue by andxu** [redhat-developer/vscode-java#299]
$ is a valid character in java package name and class name, but the langue server seems not to be able to handle them.

##### Environment
- Operating System: "Win10 Enterprise 64 Bit"
- JDK version:  "1.8.0_131"
- Visual Studio Code version: 1.16.1
- Java extension version: 0.10.0

##### Steps To Reproduce
1. Open java project on https://github.com/vscjavaci/java-debug-ci/tree/master/testcase/15.specialname

##### Current Result
![image](https://user-images.githubusercontent.com/17075863/30580193-50c32be6-9d4e-11e7-9071-b2f4d812c427.png)

##### Expected Result
![image](https://user-images.githubusercontent.com/17075863/30580237-69bb763a-9d4e-11e7-9ca5-5c97c67eeae7.png)

**Comment by snjeza** [comment]
Typescript uses the TextMate grammar files - https://github.com/Microsoft/TypeScript-TmLanguage. I suppose we also need to use it.

**Comment by fbricon** [comment]
VS Code embeds the Java Textmate grammar files : https://github.com/Microsoft/vscode/tree/master/extensions/java/syntaxes

So it's an upstream issue. More importantly, the textmate  grammar needs to be fixed upstream: https://github.com/textmate/java.tmbundle

**Comment by fbricon** [comment]
This is partially fixed with the new semantic highlighting support in vscode-java 0.61.0. Requires `"java.semanticHighlighting.enabled": true` in settings.json. Without semantic highlighting, the Textmate grammar is still broken.
