### ISSUE TITLE
Compilation error due to seemingly misplaced annotation on class/interface method

### ISSUE THREAD

**Issue by d4span** [redhat-developer/vscode-java#2997]
I currently get several compilation errors due to seemingly misplaced `@NotNull` annotations before the return type of certain class/interface methods. For instance, I get a compilation error on the annotation before the return type (`Iterable<S>`) of the following example method (in a class/interface implementing/extending Spring's `CrudRepository`):

```
public <S extends SomeType> @NotNull Iterable<S> saveAll(@NotNull Iterable<S> entities) {
    // implementation goes here
}
```

However, the same code compiles just fine with OpenJDK 17, e.g. when built with Maven or IntelliJ IDEA.

##### Environment
- Operating System: Ubuntu Linux 22.04
- JDK version: 17.0.5
- Visual Studio Code version: 1.76.1
- Java extension version: 1.15

**Comment by d4span** [comment]
Interestingly, it looks like this error occurs since we added Kotlin to our Maven build (which was at the end of last week). We use the most recent Kotlin version and followed pretty much the documentation here: https://kotlinlang.org/docs/maven.html

**Comment by fbricon** [comment]
vscode-java doesn't support Kotlin

**Comment by d4span** [comment]
I see. This might be my fault.

We currently do not have any Kotlin code in our code base, therefore I expected the Java plugin to continue to work (perhaps because I am used to this behavior from other IDEs). But we changed the Maven build, and if this change is not supported, then you can close this issue.

**Comment by rgrunber** [comment]
See https://github.com/redhat-developer/vscode-java/issues/531 to track any changes to this.
