### ISSUE TITLE
error: package org.springframework.boot does not exist

### ISSUE THREAD

**Issue by YuriAz** [redhat-developer/vscode-java#2998]
[provide a description of the issue]

##### Environment
- Operating System: Linux
- JDK version: 17
- Visual Studio Code version: 1.76.1
- Java extension version: 0.25.8

##### Steps To Reproduce
1. Ctrl + Shit + P to run Spring Initialzer. Select 3.0.4 version, Java language, com.example for group id, demo for artifact id, Jar for packaging type, 17 for java version and don't need to add dependencies.
2. Open the project on VS Code, go to src/main/javacom/example/demo/DemoApplication.java and Run. After run, the problem appears to me.

##### Current Result

➜ cd "/home/yuri/demo/src/main/java/com/example/demo/" && javac DemoApplication.java && java DemoApplication
DemoApplication.java:3: error: package org.springframework.boot does not exist
import org.springframework.boot.SpringApplication;
                               ^
DemoApplication.java:4: error: package org.springframework.boot.autoconfigure does not exist
import org.springframework.boot.autoconfigure.SpringBootApplication;
                                             ^
DemoApplication.java:6: error: cannot find symbol
@SpringBootApplication
 ^
  symbol: class SpringBootApplication
DemoApplication.java:10: error: cannot find symbol
                SpringApplication.run(DemoApplication.class, args);
                ^
  symbol:   variable SpringApplication
  location: class DemoApplication
4 errors

##### Expected Result

The expected is to run and the application be running on port 8080

##### Additional Informations

I tryed everything that i found on google but nothing works

**Comment by jdneo** [comment]
Are you clicking the `Run Code` button from the top right corner? Please open the drop down list and select `Run Java` instead.

Or you can click the `Run | Debug` CodeLens above the main method.

**Comment by YuriAz** [comment]
Yes, I'm clicking `Run Code` in the top right corner.

**If I click on** `Run Java`:
 ➜  /usr/bin/env /home/yuri/.vscode/extensions/redhat.java-1.15.0-linux-x64/jre/17.0.6-linux-x86_64/bin/java @/tmp/cp_3a5zbexv06y
icha4hf2ng9p5y.argfile com.example.demo.DemoApplication 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.4)

2023-03-13T23:08:41.526-03:00  INFO 41066 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication using Java 17.0.6 with PID 41066 (/home/yuri/demo/target/classes started by yuri in /home/yuri/demo)
2023-03-13T23:08:41.530-03:00  INFO 41066 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to 1 default profile: "default"
2023-03-13T23:08:41.918-03:00  INFO 41066 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 0.707 seconds (process running for 1.015)

**If I click on** `Debug Java`:
➜  /usr/bin/env /home/yuri/.vscode/extensions/redhat.java-1.15.0-linux-x64/jre/17.0.6-linux-x86_64/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,
address=localhost:41541 @/tmp/cp_3a5zbexv06yicha4hf2ng9p5y.argfile com.example.de
mo.DemoApplication 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.4)

2023-03-13T23:09:32.824-03:00  INFO 42038 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication using Java 17.0.6 with PID 42038 (/home/yuri/demo/target/classes started by yuri in /home/yuri/demo)
2023-03-13T23:09:32.827-03:00  INFO 42038 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to 1 default profile: "default"
2023-03-13T23:09:33.236-03:00  INFO 42038 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 0.781 seconds (process running for 1.263)

**Comment by jdneo** [comment]
Looks like the problem is solved.

The `Run Code` command is contributed by an extension called `Code Runner`. It can only deal with java files which does not depend on any other third-party dependencies.

Please use `Run Java` or `Debug Java` when you are working on a project, not a single java file.

**Comment by taruna880** [comment]
Thanks for the solution it helped me too.

**Comment by tess61** [comment]
Now it works, thanks, just like that easy solution

**Comment by Shivam-120** [comment]
nice bro

**Comment by Shubhamkhodape** [comment]
> Are you clicking the `Run Code` button from the top right corner? Please open the drop down list and select `Run Java` instead.
> 
> Or you can click the `Run | Debug` CodeLens above the main method.

Thanks Buddy!!!!! Worked for me......😊

**Comment by C123456arlos** [comment]
nice and easy solution
Thx
