### ISSUE TITLE
VS Code prematurely kills the java-language-server

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-java#3]
VS Code prematurely kills the Java Language Server and we don't have a chance to finish the application thread and shut down the workspace.

see also https://github.com/gorkem/java-language-server/issues/35

**Comment by rgrunber** [comment]
Marking this as closed for now as it seems it was solved some time ago. VSCode sends a shutdown notification which is only acknowledged by the language server once the workspace has been shut down safely. From there the server responds to the shutdown, permitting the client to send the exit() which terminates the process.
