### ISSUE TITLE
Code action for exception 

### ISSUE THREAD

**Issue by yaohaizh** [redhat-developer/vscode-java#300]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

Current there is no code action for exception ( Surround with try/catch or change method signature)

**Comment by fbricon** [comment]
@yaohaizh can we add that issue to the `End September 2017` milestone?

**Comment by yaohaizh** [comment]
@fbricon  PR is here: https://github.com/eclipse/eclipse.jdt.ls/pull/357

But the changes is more than 1000 loc though most are from the JDT UI and test cases.

**Comment by fbricon** [comment]
PR merged, thanks for the great feature @yaohaizh!
