### ISSUE TITLE
Type mismatch error vanishes when opening file

### ISSUE THREAD

**Issue by FunctionDJ** [redhat-developer/vscode-java#3002]
Java extension shows an error about a type mismatch but when `FooValidation` is opened, the error goes away.

There are at least two possible changes that will stop the error from occurring in the first place:
- making `Foo` not implement `Serializable`
- making `FooValidator` implement `ConstraintValidator` directly instead of extending `AbstractValidator`

Unfortunately, none of those two are acceptable workarounds for the enterprise project where this issue came up.

##### Environment
- Operating System: Windows 10 Pro 22H2, Build 19045.2604
- JDK version: Java 17
- Visual Studio Code version: 1.76.2 (user setup)
- Java extension version: v1.15.0

##### Steps To Reproduce
1. Clone https://github.com/FunctionDJ/constraint-issue-minimal-reproduction
2. Open with VSCode and Java extension installed, using Eclipse Adoptium `jdk-17.0.3.7-hotspot` as runtime

##### Current Result
After opening the project and Java init settles:
![image](https://user-images.githubusercontent.com/34871211/225418565-51470f3c-c67b-4311-9893-5e3449cfcc51.png)

Opening the file makes the error vanish after a moment:
![image](https://user-images.githubusercontent.com/34871211/225418727-3957b432-d0bc-43b8-95ea-93444d5f6d0b.png)

##### Expected Result
No error at all because `FooValidator` is supposed to be an appropriate type.

**Comment by snjeza** [comment]
@FunctionDJ Could you try to set
```
"java.compile.nullAnalysis.mode": "disabled"
```

**Comment by FunctionDJ** [comment]
@snjeza Yes... that fixed the issue in both the reproduction project as well as in our enterprise project... but why? Is this still a bug with the null analysis?

**Comment by snjeza** [comment]
@FunctionDJ Yes, it is. It is an upstream Eclipse bug. Working on that.

**Comment by rgrunber** [comment]
The upstream issue seems to have been closed and we've definitely adopted it, so closing for now. If this is still reproducible feel free to reopen.
