### ISSUE TITLE
Extension fails to load with pre-release version

### ISSUE THREAD

**Issue by gayanper** [redhat-developer/vscode-java#3005]
Fail to start the extension

##### Environment
- Operating System: MacOS
- JDK version: 17
- Visual Studio Code version: 1.76.2
- Java extension version: pre-release

##### Steps To Reproduce
1. Install pre-release version
2. Reload vscode

##### Current Result

Extension loading fails with 
```
rejected promise not handled within 1 second: TypeError: expandHomeDir is not a function
stack trace: TypeError: expandHomeDir is not a function
	at Object.<anonymous> (/Users/gayanperera/Projects/vscode/vscode-java/dist/extension.js:80495:28)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/gayanperera/Projects/vscode/vscode-java/dist/extension.js:80459:58)

```

**Comment by jdneo** [comment]
fixed by https://github.com/redhat-developer/vscode-java/pull/3009
