### ISSUE TITLE
Dependency classes are not longer directly opened

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#3011]
Following https://github.com/redhat-developer/vscode-java/pull/2985, opening a non-project type no longer directly opens the source, but shows the intermediary "Decompile Class File" webview. This is a huge regression in DX.

##### Steps To Reproduce
1. In a Java file, Ctrl+Click on `String`

##### Current Result
"Decompile Class File" webview shows up instead of proper JDK source as before

##### Expected Result
Attached or decompiled sources should  shows up directly during code navigation/references/..., as before

##### Additional Informations
The "Decompile Class File" webview should only show up when manually opening a .class file from the IDE

**Comment by xiangtianyu** [comment]
Is this change released? I used the latest version and have the problem. When i try to enter into jdk class or spring class, it will always show "This file is not displayed in the text editor because it is a Java class file. Click here to decompile and open."
