### ISSUE TITLE
Can't use modular projects without build tools

### ISSUE THREAD

**Issue by Dev-Routine** [redhat-developer/vscode-java#3017]
[provide a description of the issue]

##### Environment
- Operating System: Ubuntu 22.04.2 LTS
- JDK version: java 19.0.2 2023-01-17
- Visual Studio Code version: 1.75.0
- Java extension version: 1.16.0

##### Steps To Reproduce
1. [step 1] Make a non-modular project without build tools.
2. [step 2] Try to make it modular by adding "module-info.java" file under "src" directory .
3. [step 3] Try referencing any external modules by typing "requires javafx.controls" for example.

[Sample project reproducing the error]
[java-modular-test.zip](https://github.com/redhat-developer/vscode-java/files/11039163/java-modular-test.zip)

[Error messages + java lines that produced them]
[log.txt](https://github.com/redhat-developer/vscode-java/files/11039189/log.txt)

##### Current Result
Cannot use intellisense with any external module even after requiring it in module-info.java.

##### Expected Result
Intellisense to work normally & for the language server to recognize the required modules.

##### Additional Informations
The module files (javafx jars) is in project's classpath and recognized by the language server even it auto-completes it for me but after typing gives me an error saying:
"javafx.controls cannot be resolved to a moduleJava(8389908)".

**Comment by jdneo** [comment]
Duplicated with https://github.com/redhat-developer/vscode-java/issues/2272

**Comment by zzpzaf** [comment]
I have the same issue...
