### ISSUE TITLE
Failed to initialize Language Support for Java due to Error: Connection is disposed

### ISSUE THREAD

**Issue by yaegar** [redhat-developer/vscode-java#3019]
Failed to initialize Language Support for Java due to Error: Connection is disposed.

![image](https://user-images.githubusercontent.com/12856549/227105170-f40ff14c-dda3-4a7d-a869-73cbe34fcf77.png)

##### Environment
- Operating System: Windows11
- JDK version: 17.0.6
- Visual Studio Code version: 1.77.0-insider
- Java extension version: v1.17.2023032204
- OS RAM: 16G

my settings:

"java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx4G -Xms4G -Xlog:disable"

**Comment by yaegar** [comment]
I try to open a single project and it works fine, opening multiple projects in the workspace brings up

**Comment by yaegar** [comment]
Sorry, when I restarted my computer, the problem no longer existed

**Comment by jdneo** [comment]
I'll close this issue for now. Feel free to leave comments once you found reproduce steps for this issue. Thanks!
