### ISSUE TITLE
Generate setters/getters in OpenShift DevSpaces (VS Code OSS) is unavailable

### ISSUE THREAD

**Issue by rludva** [redhat-developer/vscode-java#3025]
In Red Hat OpenShift DevSpaces when this plugin is installed, it is not possible to generate setter/getters. It works correctly in VS Code but not where VS Code OSS is used. 

##### Environment
- Operating System: n/a
- JDK version: openjdk version "11.0.18" 2023-01-17 LTS
- Visual Studio Code version: Red Hat OpenShift Dev Spaces with Microsoft Visual Studio Code - Open Source IDE
Version: 1.75.0
- Java extension version: v1.14.0

##### Steps To Reproduce
1. Lunch Workspace in OpenShift DevSpaces
2. Install this exension
3. Crete a simple class and try to generate getter or setter
```
public class lorem {
    private String username;

}
```

##### Current Result
The menu for "Source Action" is not visible.

##### Expected Result
The "Source Action" menu is visible, and the behavior should be the same as in VS Code.

##### Additional Information
_// ping directly on slack if you want lab environment with devspaces where it is possible to reproduce._
You can use the [dev-spaces-extensions-json](https://github.com/agiertli/dev-spaces-extensions-json) repository to reproduce the issue on any Dev Spaces installation (including Dev Sandbox):

It seems none of the source actions are available in Dev Spaces IDE - i.e. you can't seem to generate getters/setters constructor, go to implementation, etc.

**Comment by fbricon** [comment]
Works for me:

<img width="1884" alt="Screenshot 2023-03-27 at 14 07 42" src="https://user-images.githubusercontent.com/148698/227937905-24a49b8c-4980-4cf2-b322-3f7216989bbf.png">

<img width="541" alt="Screenshot 2023-03-27 at 14 09 58" src="https://user-images.githubusercontent.com/148698/227937937-b5ea6a8f-fb1c-40c5-8267-228ac96044a9.png">

Can you provide the logs from the "Java: Open All Log Files" command?

**Comment by fbricon** [comment]
Turns out Devspaces seems to start the Java language server in lightweight mode. One needs to click n the {} Java status to load the projects, to get the full feature set. See https://code.visualstudio.com/docs/java/java-project#_lightweight-mode
