### ISSUE TITLE
be smarter on inferring types when collection type does not match

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#3040]
I had this code first:
```java
		final Map<String, String> messages = new HashMap<>();
```

Then changed it to:

```java
		final List<Map<String, String>> messages = new HashMap<>();
```

Now vscode just complains about not being able to infer the right types and no quick fix available.

Given the left side explicitly says this needs to be a List not a Map derivative anymore could a quickfix
not suggest to make it `new ArrayList<>();` as a decent fix to make it compile ?

Similar would work for Set, Map, and other collection types.

**Comment by rgrunber** [comment]
We'll likely need JDT-LS updated to at least [`I20240628-1800`](https://download.eclipse.org/eclipse/updates/4.33-I-builds/I20240628-1800) ( to be built today) to take advantage of the feature/API.
