### ISSUE TITLE
quickfix for print/println methods

### ISSUE THREAD

**Issue by maxandersen** [redhat-developer/vscode-java#3041]
when writing `println("something")` it would be great that instead of only complaining it cannot resolve println that it offers to quickfix it to `System.out.println("something")`; even better static import of System.out and then just put out.println("something"); to keep things compact.

same would apply for print and printf.

**Comment by fbricon** [comment]
alternatively, and I know this doesn't fix this issue but, you can change your way of writing println statements and do "something".sysout instead. postfix completion FTW

**Comment by fbricon** [comment]
Also helpful: adding `java.lang.System.out` to the list of your "java.completion.favoriteStaticMembers" setting. Won't help with quickfixes, but you'll at least have `out` available in completion, selecting it will auto import the static import.

**Comment by rgrunber** [comment]
@hopehadfield , could we alias the existing `sys` snippets to `print` where possible ? https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/5cb8f7adb7314466cb6d1a0bf25af8e7322cca08/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java#L42-L43 ? That would suggest as the user is typing.

**Comment by hopehadfield** [comment]
@rgrunber that sounds like a good idea. I'll get on that.

**Comment by rgrunber** [comment]
I think this addresses the issue enough to close this.
