### ISSUE TITLE
vscode can not create gradle java project on Macbook

### ISSUE THREAD

**Issue by d95776** [redhat-developer/vscode-java#3054]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
click "Create Java Project" button
Select Gradle - Gradle for java
Select the folder to hold the project
Select Groovy
Enter the project name
Hit Enter button
the process of creating java project runs but did nothing (no gradle project is created.)
[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by CsCherrYY** [comment]
Please check if the VS Code output channel "Gradle for Java" shows any error logs.

BTW, could anyone transfer this issue to https://github.com/microsoft/vscode-gradle?

**Comment by fbricon** [comment]
The project wizard is provided by the `Project Manager for Java` extension. Please open a ticket there: https://github.com/microsoft/vscode-java-dependency/issues
