### ISSUE TITLE
Inputmismatch error coding Java in VSCode but no error in Apache Netbeans.

### ISSUE THREAD

**Issue by xxc-zsz** [redhat-developer/vscode-java#3079]
I've been learning a bit of Java on my own, using vsc and NetBeans interchangeably. I've run into an error in the former that I can't replicate on the latter, and it's bothering me a lot, I have no idea what causes it. I prefered using vscode since I learned a bit of html and js with it but this forces me to move on to NetBeans if I can't figure out what's the problem.

![The code in vscode.](https://i.imgur.com/D1831Iz.png)

![The same code, error free in Netbeans.](https://i.imgur.com/GlQYqVi.png)

My head hurts from this. Can anyone help?

Code below just in case.

```
import java.util.Scanner;

public class example { public static void main(String[] args) { 
   
    Scanner sc = new Scanner(System.in).useDelimiter("\n");
    int age; 
    String name; 
    System.out.println("Enter a name and age:");
    name= sc.next();
    age = sc.nextInt();
    System.out.println(name+" "+age);
    sc.close();
} 
}
```

You can see that there are extra characters when receiving inputs in VSCODE by debugging.

![image](https://user-images.githubusercontent.com/108051416/233271364-f5155771-c94a-4ee8-910e-6ec30d0a4bb2.png)

If you use the NextLine method, everything is normal

![image](https://user-images.githubusercontent.com/108051416/233271455-19ea177f-7dbb-46fa-a159-569457104618.png)

**Comment by Eskibear** [comment]
https://www.google.com/search?q=cr+lf

Windows default EOL is CRLF, and I guess the exception was because it read `\r` and failed to recognize it as an int.

**Comment by jdneo** [comment]
@xxc-zsz

If you compile your source code via `javac` and run it directly in the PowerShell terminal, you will get the same result as VS Code.

Please check @Eskibear 's comment for explanation.
