### ISSUE TITLE
Fail to Preview and Refactor with deleting parameters in Change Method Signature window

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#3089]
##### Environment
- Operating System: Mac
- JDK version: 17.0.6
- Visual Studio Code version: 1.77.3
- Java extension version: 1.18.0

##### Steps To Reproduce
1. In a method which contains two parameters > Change signature from quick action
2. In `Change Method Signature` window, delete one parameter > Preview or Refactor

##### Current Result
![image](https://user-images.githubusercontent.com/31497677/234799256-0816f939-a6e2-4176-a648-550eb6522650.png)

##### Expected Result
Can preview and refactor successfully.

**Comment by v-yuyul** [comment]
- Change Method Signature > Go to Exception tab > Same behavior while deleting existing exceptions.
- Change Method Signature > Go to Exception tab > Add an exception with default name > Refactor (succeed) > Add an exception with default name again, Refactor and Preview don't work without errors.

**Comment by rgrunber** [comment]
I just checked and https://github.com/eclipse/eclipse.jdt.ls/pull/2727 should solve all of these, except the "adding an exception with a default name again". If by default name you mean "Exception"/"java.lang.Exception", while it doesn't appear to be a compilation error, it doesn't really make sense to have `public void someMethod () throws Exception, Exception`. The refactoring is partly correct in pointing out that you haven't really changed anything, although I guess the signature is technically different ?

We could improve this in the future if there really is a case for it.

**Comment by rgrunber** [comment]
I would close this for now as the really annoying aspects of this issue ("change signature" doing downright strange things) should be resolved now.
