### ISSUE TITLE
"Go To Definition" shows overloading methods rather than going to the actual method

### ISSUE THREAD

**Issue by stefanrybacki** [redhat-developer/vscode-java#3095]
When having multiple overloaded versions of a method, the "Go To Definition" (Ctrl+Click, etc.) will not got the actual method but show all overloaded versions.

##### Environment
- Operating System: UI Windows, Remote SSH into Linux
- JDK version: 17
- Visual Studio Code version: 1.77.3
- Java extension version: 1.18.0

##### Steps To Reproduce
1. Create Class like this:

```java
class GoToDefinitionTest {
  public String method1(String param) {
    return method1(param, null);    // Ctrl+Click on method1 here
  }

  public String method1(String param, String otherParam) {
    return method1(param, otherParam, null);
  }

  public String method1(String param, String otherParam, String yetAnotherParam) {
    return "Hello";
  }
}
```

2. In the first `method1` method Ctrl+Click on the other `method1` call.

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

![image](https://user-images.githubusercontent.com/29799350/236013404-78ccec24-d37f-443a-9e69-702c726b5513.png)

##### Expected Result

Expected is a jump the the second `method1` implementation because it is the only correct definition.

##### Additional Informations

If use "Search for references" for the same `method1` call it correctly shows this: 
![image](https://user-images.githubusercontent.com/29799350/236013903-1b967500-bf08-4ac4-90e3-34e65dd44200.png)

Also the reference hints at the methods itself are correct (see the screenshot the first `method1` has 0 references, while the other two have each 1 reference).

**Comment by jdneo** [comment]
Cannot reproduce it on my side:

https://user-images.githubusercontent.com/6193897/236392526-8a5c0d75-d7d8-4b06-ac42-8de6cc84ceb9.mp4

The only difference is that I'm not using Remote extension. I directly tested it locally. - I don't think this has impact on the behavior.

**Comment by stefanrybacki** [comment]
@jdneo I feared that you might not be able to reproduce. It also might be a setting though. I will try to see if it makes a difference on non remote. Thanks for taking the time.

**Comment by jdneo** [comment]
Don't forget to check the enabled extensions. Maybe the definition location is contributed by some other extensions.

**Comment by stefanrybacki** [comment]
@jdneo thanks for the hint regarding other extensions, FYI it seems to be the Metals Scala extension which somehow "overrides" the go to definition command in the java project to a slightly enhanced full text search.

**Comment by jdneo** [comment]
Thanks for the update. If the workspace only contains pure-Java projects, you can consider disable `Metals Scala` in that workspace.
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/e4152837-6c0f-4890-b710-95e50225e824)
