### ISSUE TITLE
Get variable declared in VMArgs

### ISSUE THREAD

**Issue by lucasortigoso** [redhat-developer/vscode-java#310]
I couldn't get variable value declared inside java.jdt.ls.vmargs

##### Environment
- Operating System: MacOS Sierra 10.12.6
- JDK version: 1.8.0_121
- Visual Studio Code version: 1.16.1
- Java extension version:  1.8.0.121

##### Steps To Reproduce
1. In settings.json: "java.jdt.ls.vmargs": "-DJDBC=test"
2. Get the value of environment variable JDBC:
System.getProperty("JDBC");

##### Current Result
null

##### Expected Result
test

**Comment by fbricon** [comment]
Are you expecting that system property to be used by your code? Can you be more specific on how you do step 2?

**Comment by lucasortigoso** [comment]
Exactly! My database connection string must be an environment variable. Can you help me?
` public static void main(String[] args)  {
		System.out.println(System.getProperty("JDBC"));
    }`

Should it work?

**Comment by fbricon** [comment]
vscode-java is not responsible for running your Java code. `jdt.ls.vmargs` are used to configure the Java server responsible for providing Java support to VS Code, so you should not expect adding args there will have an effect on running your code.

Now if you're using this [Java Debugger](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) to launch your app, you can set system properties via the `vmArgs ` property of your launch configuration in launch.json. If you have issues or specific questions related the debugger, I suggest you join this [gitter](https://gitter.im/Microsoft/vscode-java-debug) chatroom.
