### ISSUE TITLE
API to programmatically detect if Java Preview features are enabled

### ISSUE THREAD

**Issue by vojtech-suchy-sonarsource** [redhat-developer/vscode-java#3102]
Hi,

We would like to programmatically detect whether a user has enabled Java preview features.

Would it be possible to add such functionality to the extension's public API?

##### Environment
- Visual Studio Code version: 1.78.0
- Java extension version: v0.25.11

Best,

**Comment by rgrunber** [comment]
I think this is currently possible. If you look at the API you'll see we define a function, [`getProjectSettings(Uri, string[])`](https://github.com/redhat-developer/vscode-java/blob/02deb55dd84f03d9e574b590c24876a66b0ffeb9/src/apiManager.ts#L56)` . You can use this with `org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures`, which is the setting that enables preview features :

```
const vscodeJava = extensions.getExtension(JAVA_EXTENSION_ID);
if (!vscodeJava) {
  throw new Error("VSCode java is not installed");
}

const api = await vscodeJava.activate();
if (!api) {
  throw new Error("VSCode java api not found");
}

const projectSetting: {} = await api.getProjectSettings(
  Uri.file(path.join('some', 'project', 'path')).toString(),
  ['org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures']
);
```
