### ISSUE TITLE
Code completion for constructor is broken with 'java.completion.matchCase' enabled

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#3118]
See screenshot:

https://github.com/redhat-developer/vscode-java/assets/14052197/6e774995-8317-4e8d-89e8-b0dc1fef0d1f

The workaround is to turn off `"java.completion.matchCase": "off"`.

**Comment by snjeza** [comment]
@testforstephen I can't reproduce the issue.

![completion2](https://github.com/redhat-developer/vscode-java/assets/388609/58e7849d-b023-4704-8b83-54b96b9ee746)

 Could you attach a project example?

**Comment by jdneo** [comment]
@snjeza I guess you are using stable VS Code? In stable `auto` maps to `off`
