### ISSUE TITLE
Android Project doesn't recognize dependencies

### ISSUE THREAD

**Issue by JojoFR1** [redhat-developer/vscode-java#3119]
With this [android project](https://github.com/KaarinGaming/AndroidGameTutorial/tree/master), none of the dependencies get recognized and all the import give the error `The import XX.XX cannot be resolved`.

##### Environment
- Operating System: Windows 11
- JDK version: oracle java 19.0.2
- Visual Studio Code version: 1.78.2
- Java extension version: v1.19.2023052604 (latest)

##### Steps To Reproduce
1. Clone https://github.com/KaarinGaming/AndroidGameTutorial/tree/master.
    - You might need to manually set the sources folders in `app/build.gradle`.
3. Wait for Gradle and the Java Server to init and download all the dependencies.

##### Current Result
None of the import is recognized and get the error `The import XX.XX cannot be resolved`.

##### Expected Result
No error on the imports.

##### Additional Informations
I changed the plugin version multiple time, reinstalled it, cleared the gradle cache multiple time, cleaned the Java Language Server multiple time, restarted VSCode multiple time and nothing was able to fix it.
The build (`./gradlew build`) do work completely fine.

**Comment by JojoFR1** [comment]
Nevermind, I just noticed that there's was a config (`java.jdt.ls.androidSupport.enabled`) I didn't turned on. I'm sorry for the useless issue.

**Comment by bogiva** [comment]
I am having the same issue even with the flag java.jdt.ls.androidSupport.enabled set on.
How to troubleshoot?

**Comment by Thaina** [comment]
Thanks for your info about this config `java.jdt.ls.androidSupport.enabled`. I had been stumble for using vscode as java editor for such times

**Comment by coolsoftrf** [comment]
> I am having the same issue even with the flag java.jdt.ls.androidSupport.enabled set on. How to troubleshoot?

@bogiva, have you finally resolved it? I'm stuck with the same trouble. Command `./gradlew build` generates apk successfully, but VS Code doesn't list any library (neither those of android nor my local) in «Project and External Dependencies» section of Java Projects tab, leading to the mentioned error.

**Comment by acheronfail** [comment]
@coolsoftrf it's broken for me too, I think it's related to recent versions of AGP (Android Gradle Plugin).

I believe this issue is tracking it: https://github.com/redhat-developer/vscode-java/issues/3682
