### ISSUE TITLE
Completion for 'new String' is wrong

### ISSUE THREAD

**Issue by yuyully** [redhat-developer/vscode-java#3127]
##### Environment
- Operating System: windows
- JDK version: 17
- Visual Studio Code version: 1.78.2
- Java extension version:1.19.0

##### Steps To Reproduce
1. Type `new String` and select `new String(byte[] bytes)`
![string](https://github.com/redhat-developer/vscode-java/assets/31497677/6022c566-8163-41fd-8563-40b6541eb0a1)

##### Current Result
After select `new String(byte[] bytes)`, it becomes `String(string original)` automatically.
##### Expected Result
It should be `new String(byte[] bytes)` as I select it.

**Comment by jdneo** [comment]
The root cause is that the context (selected item) is not persisted for the signature help. But since now we have the `onDidSelectedCompletionItem` hook, I think it's doable now.

I'll take a look.
