### ISSUE TITLE
Throwable.addSuppressed() called by extension, causing IllegalArgumentException

### ISSUE THREAD

**Issue by moocat** [redhat-developer/vscode-java#3138]
The extension is calling java.base/java.lang.Throwable.addSuppressed() on all thrown exceptions when in a try (resource) catch block, causing it to throw an IllegalArgumentException, as you cannot use addSuppressed() on yourself.
This then results in the try-catch block not catching its defined exceptions.

This does not seem to be the case on version 1.18.0 of the extension.
Also when compiled and run through the command line, it does not happen.

##### Environment
- Operating System: Windows 10
- JDK version: OpenJDK 18.0.2 and OpenJDK 20.0.1
- Visual Studio Code version: 1.78.2
- Java extension version: 1.19.0

##### Steps To Reproduce
Run the code:
```
public class Test {
	public static class TestClass implements AutoCloseable {
		@Override
		public void close() throws Exception {
		}
	}

	public static class TestException extends Exception {
		public TestException() {
			super("Test");
		}
	}

	public static void main(String[] args) {
		try (TestClass test = new TestClass()) {
			throw new TestException();
		} catch (TestException e) {
			System.out.println("Success");
		} catch (Exception e) {
			System.out.println("Failure");
			e.printStackTrace();
		}
	}
}
```

##### Current Result
Prints:
```
Failure
java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1071)
        at Test.main(Test.java:17)
Caused by: Test$TestException: Test
        at Test.main(Test.java:16
```

##### Expected Result
Should print:
```
Success
```
##### Additional Informations
Running from the command line instead of the extension, will give the desired result:
```
java Test.java
```
Prints:
```
Success
```

**Comment by cygri** [comment]
We are seeing this too with OpenJDK 11.0.18.

**Comment by snjeza** [comment]
This is an upstream jdt.core issue.
A related issue - https://github.com/eclipse-jdt/eclipse.jdt.core/issues/934

**Comment by alimoullim91** [comment]
@snjeza just to let you know this issue still pertains however for my work purposes I have reverted to 1.18 and that works fine for me.

You might want to look into it.

**Comment by snjeza** [comment]
@alimoullim91 You can try VS Code `Pre-Release`
