### ISSUE TITLE
Add support for package view 

### ISSUE THREAD

**Issue by varunkumar** [redhat-developer/vscode-java#315]
Add support for package view similar to the one we have in Eclipse Project Explorer. Please let me know if this exists already via some configuration. 

I would be happy to contribute if this is not already available.

**Comment by fbricon** [comment]
This is not available yet. It would require changes to https://github.com/eclipse/eclipse.jdt.ls/
@tsmaeder I guess that might be interesting for che too, no?

**Comment by varunkumar** [comment]
I am a newbie to this plugin. Wondering why would it need changes to language server. We already have the listing of files and information about source location with us right?

**Comment by fbricon** [comment]
The vscode extension should try to avoid embedding any logic of Java smartness, so as to make it reusable by other clients. 
You can certainly achieve to build a pure vscode package view of your projects by inspecting the location or content of each file, but the server has all that information already (and we know it's accurate), it just needs to expose it.

**Comment by sandalyecik** [comment]
I got the same problem.

**Comment by vincentfree** [comment]
+1

Are people working on this?

**Comment by btstream** [comment]
Is there a plan or chance to implement a project explorer like eclipse of idea? 

I really like flat package view in Eclipse.

**Comment by yaohaizh** [comment]
@andxu Will help release a Java dependency viewer as an extension

**Comment by akaroml** [comment]
Java Dependency View extension was just released to address this problem. Here's the link:
https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency

@varunkumar @vincentfree @cruizba @btstream please have a try and see if it solves the problem.

**Comment by FelixDombek** [comment]
> Java Dependency View extension was just released to address this problem. Here's the link:
> https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency
> 
> @varunkumar @vincentfree @cruizba @btstream please have a try and see if it solves the problem.

This view is nice, but it would still be very helpful to have this in the normal file view too.

**Comment by vincentfree** [comment]
> Java Dependency View extension was just released to address this problem. Here's the link:
> https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency
> 
> @varunkumar @vincentfree @cruizba @btstream please have a try and see if it solves the problem.

I really like the new view, @FelixDombek i don't think vscode allows it to change the floder view in the main window. That's why all the extra windows are created for different views on the same stuff.

I love the fact that it also shows the dependencies based upon the maven pom and the JRE

Thanks a lot! 👍

**Comment by varunkumar** [comment]
This looks neat. Thanks. Good to close?

**Comment by balupraveen** [comment]
This solves only for dependencies but what about the project's source ? Wouldn't it be nice if we have the same for project's source
