### ISSUE TITLE
RedHat extension seems to change the original behavior of "cmd + v" on Mac

### ISSUE THREAD

**Issue by zlargon** [redhat-developer/vscode-java#3150]
RedHat extension seems to change the original behavior "cmd + v" on Mac. I want the "cmd + v" to simply paste the text.
This issue won't happen after disabling the RedHat extension.
I don't know the name of this feature is, and I just want to disable it.

##### Environment
- Operating System:
    - macOS: Ventura 13.4
    - Chip: Apple M1 Pro
- JDK version:
   - java.version=17.0.7
   - java.vendor=Eclipse Adoptium
- Visual Studio Code version:
   - Version: 1.79.0
   - Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
   - Date: 2023-06-07T14:31:03.317Z (4 days ago)
   - Electron: 22.5.5
   - Chromium: 108.0.5359.215
   - Node.js: 16.17.1
   - V8: 10.8.168.25-electron.0
   - OS: Darwin arm64 22.5.0

- Java extension version:
Language Support for Java(TM) by Red Hat v1.19.0

##### Steps To Reproduce
Please see the screen recording.

https://github.com/redhat-developer/vscode-java/assets/2791834/2cbe26eb-3e93-46fc-90f7-792e7aee8535

##### Current Result

When press the "cmd + v", it will show two options:
- Paste using 'Language Support for Java (TM) by Red Hat' extentsion
- Insert Plain Text
<img width="778" alt="Screenshot 2023-06-12 at 10 55 48 AM" src="https://github.com/redhat-developer/vscode-java/assets/2791834/9a7448d4-c049-45b6-87f9-7cdd062a2757">

##### Expected Result
I want to simply paste the text from the clipboard as original.

**Comment by jdneo** [comment]
You can do that by turning the setting `editor.pasteAs.enabled` off.

**Comment by zlargon** [comment]
It works, thank you!
