### ISSUE TITLE
How to disable all the on-paste stuff?

### ISSUE THREAD

**Issue by aapeliv** [redhat-developer/vscode-java#3154]
Having a lot of issues with paste actions not working. It's extremely frustrating when you can't copy-paste normally.

What are the config options to disable those features?

[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by sebastien-allard** [comment]
Let's remember this one:

[Please do not override paste](https://github.com/redhat-developer/vscode-java/issues/1115)

**Comment by sebastien-allard** [comment]
To paste the normal way:
Shift + Ctrl + V
