### ISSUE TITLE
IntelliSense & ICompilationUnit error

### ISSUE THREAD

**Issue by JojoFR1** [redhat-developer/vscode-java#3161]
I was trying to make a LWJGL project to try it. But I noticed that I wasn't able to get IntelliSense *after* the Language Server is done compiling. I noticed later that the server is timed out and stopped during the Synchronizing task. I also noticed it's complaning about a `Cannot load Pythia model` while looking in a folder that doesn't exist (it's Portable VSCode so it's located at `VSCode/data/extensions`)

##### Environment
- Operating System: Windows 11
- JDK version: 19.0.2
- Visual Studio Code version: Portable 1.79.2
- Java extension version: v1.20.2023062004

##### Steps To Reproduce
1. Use the project linked below and load it in VSCode.
2. During the Compilation 80% IntelliSense (Ctrl + Space) works fine.
3. After (or during Synchronizing task) IntelliSense don't work and server is stopped.

Tutorial I was following to get used to LWJGL: https://youtu.be/025QFeZfeyM
My Project: [Project.zip](https://github.com/redhat-developer/vscode-java/files/11793504/Project.zip)
Log: [log.txt](https://github.com/redhat-developer/vscode-java/files/11793541/log.txt)
Client Log: [clien_log.txt](https://github.com/redhat-developer/vscode-java/files/11793760/log.txt)

##### Current Result
Server is timed out and stopped and saying `Cannot load Pythia model` while looking at the wrong folder

##### Expected Result
Server working I guess

##### Additional Informations
I cleaned the language server workspace & cache multiple time.
This is also the only project giving me a time out, the other project works fine. (they still give me the `Cannot load Pythia model` error)

**Comment by jdneo** [comment]
What about re-install the IntelliCode extension?

**Comment by JojoFR1** [comment]
I also tried that, I removed it then reinstalled it.

**Comment by fbricon** [comment]
The exception is caused by the IntelliCode extension. Please disable it, execute the Java Clean Server Workspace command and see if the server starts. If it does, then we can close this issue and you can take it to https://github.com/MicrosoftDocs/intellicode/issues

**Comment by JojoFR1** [comment]
I disabled the IntelliCode extension and it did work. So it is a IntelliCode isssue, I will open one in their repository. Thank you for your help.

**Comment by fbricon** [comment]
please provide new log files

**Comment by JojoFR1** [comment]
Here they are:

**Log:** [.log.txt](https://github.com/redhat-developer/vscode-java/files/11801777/log.txt)
**Client Log:** [client.log.2023-06-20.txt](https://github.com/redhat-developer/vscode-java/files/11801786/client.log.2023-06-20.txt)

**Comment by JojoFR1** [comment]
This was fixed by recreating the whole project from scratch with the Java extension disabled (during the set-up of all the build file/settings to avoid any build of the project while it's being configured) then enable it. It worked without any errors (still the Pythia module error, even tho it doesn't do anything and it's on the IntelliCode side).

Still strange but I have no clue why this happened.
