### ISSUE TITLE
Surround with: trycatch only works with the selected word

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#3172]
##### Environment
- Operating System: win10
- JDK version: 17.0.3
- Visual Studio Code version: 1.79.2
- Java extension version: 1.20.0

##### Steps To Reproduce
1. Open a java file > Paste `File f = new File("demo.txt");`
2. Double click in the code to select one word > Select `Surround with: trycatch` in the action list

##### Current Result
Currently it only can detect the selected word to do the surround action.
![image](https://github.com/redhat-developer/vscode-java/assets/31497677/9dc630a4-b2fe-4cb8-9794-ae1bc15c7525)

##### Expected Result
Expect that it can automatically detect the whole line code to surround.
![image](https://github.com/redhat-developer/vscode-java/assets/31497677/12c1911f-63c2-4d17-9873-a0994126ae41)

**Comment by rgrunber** [comment]
I'm assuming you're using the recently contributed snippet for this. As a snippet it lacks the necessary smartness to expand its range to include other java elements. There's an existing PR, https://github.com/eclipse/eclipse.jdt.ls/pull/2727,  in JDT-LS to provide a better "surround with try-catch" experience.

**Comment by rgrunber** [comment]
![surround-with-refactoring](https://github.com/redhat-developer/vscode-java/assets/1417342/4ab238c0-e23a-40d8-b2ea-494d3c70ec5d)

Marking as closed.
