### ISSUE TITLE
Completion list for java.util is missing some items

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#3173]
##### Environment
- Operating System: win10
- JDK version: 17.0.3
- Visual Studio Code version: 1.79.2
- Java extension version: 1.20.0

##### Steps To Reproduce
1. Open a java file > Type `java.util.L`

##### Current Result
![image](https://github.com/redhat-developer/vscode-java/assets/31497677/2d225e1f-5d7f-403d-bae8-48db14452588)

##### Expected Result
It should have something like `java.util.List` in the intellisence list.

**Comment by testforstephen** [comment]
This case works in 1.18, and not work since 1.19.
