### ISSUE TITLE
[critical] No completions for new classes added after loading project

### ISSUE THREAD

**Issue by gayanper** [redhat-developer/vscode-java#3197]
No code completions are working on new files added into project after the project is loaded in vscode.

##### Environment
- Operating System: Any
- JDK version: Any
- Visual Studio Code version: 1.80.0
- Java extension version: v1.21.2023071204

##### Steps To Reproduce
- Open a java project
- Wait till the project is loaded
- Add a new class file

No code completion

- Close and Reopen the vscode
- Open the same file
- Now completions are working

**Comment by snjeza** [comment]
@gayanper You may want to take a look at https://github.com/redhat-developer/vscode-java/issues/3194

**Comment by gayanper** [comment]
@snjeza is this something vscode needs to fix and already reported to vscode project or should this be something vscode java should fix ?

**Comment by snjeza** [comment]
It has been fixed in VS Code 1.80.1.

**Comment by testforstephen** [comment]
Close it since this issue has been fixed in the latest `vscode@1.80.1` version.
