### ISSUE TITLE
F2 rename of Lombok @Singular attribute does nothing

### ISSUE THREAD

**Issue by richlanders** [redhat-developer/vscode-java#3203]
In a class with Lombok @Builder, F2 rename of a List attribute annotated with @Singular does nothing.
Rename a List attribute without @Singular works fine.

##### Environment
- Operating System: MacOS Ventura 13.2.1 (22D68)
- JDK version: OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
- Visual Studio Code version: Version: 1.80.1 (Universal) Commit: 74f6148eb9ea00507ec113ec51c489d6ff
- Java extension version: 1.20.0 (June 29th, 2023)

##### Steps To Reproduce
1. With a DTO with @Builder and @Getters and a List<String> attribute "singulars" marked up with @Singular and
2. ...code elsewhere that uses the "singulars" attribute:
3. Highlight the attribute name "singulars" and hit F2 (rename)
4. Use the dialog to rename the attribute "singulars2"
5. Result: Dialog closes without error but seemingly no action is taken.

##### Project
[lombok-bug.zip](https://github.com/redhat-developer/vscode-java/files/12064735/lombok-bug.zip)

##### Logs
[java-language-server-output.log.zip](https://github.com/redhat-developer/vscode-java/files/12064742/java-language-server-output.log.zip)

##### Current Result
Dialog closes and attribute "singulars" name is not changed.

##### Expected Result
Dialog closes and attribute "singulars" renamed to "singulars2" everywhere. 

##### Additional Information

NOTE: F2 rename works fine from any __usage__ of the attribute "singulars".

**Comment by snjeza** [comment]
This is an upstream Eclipse or Lombok issue. I can reproduce it in eclipse.

**Comment by richlanders** [comment]
Thank you all!
