### ISSUE TITLE
Completion items in wrong order for overloaded methods

### ISSUE THREAD

**Issue by charles-wangkai** [redhat-developer/vscode-java#3206]
In recent versions (from v1.17.0 to v1.20.0), the completion popup list shows overloaded methods from those with more complex parameters to those with fewer parameters from top to bottom. But what I want most times is the fewer parameters version, which leads to more "arrow down" key typing to select the expected item. It is annoying to impact coding productivity.

This seems a regression issue, since in early versions (up to v1.16.0) the order was reversed so that the fewer parameters version generally ranked higher and was placed at the top.

##### Environment
- Operating System: All
- JDK version: 17
- Visual Studio Code version: 1.80.1
- Java extension version: The issue first arose in recent versions (from v1.17.0 to v1.20.0), it was fine in early versions (up to v1.16.0)

##### Current Result
For example, the completion items show the three versions of `Collectors.joining(...)` in from complex to simple order, in the latest version v1.20.0:

<img width="672" alt="Screenshot 2023-07-18 at 08 30 01" src="https://github.com/redhat-developer/vscode-java/assets/8757419/17c9aec8-fee6-4309-9393-5e164b319fe2">

##### Expected Result
While the same three methods were displayed in from simple to complex order, in early versions (up to v1.16.0):

<img width="952" alt="Screenshot 2023-07-18 at 08 31 47" src="https://github.com/redhat-developer/vscode-java/assets/8757419/504979d7-31d2-4a91-837c-c98a8455b5f6">

**Comment by rgrunber** [comment]
I suspect this has a similar cause to https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2705 . After we introduced label detail support (which did produce nicer completion items), we regressed in certain ways (sorting, filter text). Maybe @hopehadfield can have a look here.
