### ISSUE TITLE
Select active Maven Profile

### ISSUE THREAD

**Issue by charleech** [redhat-developer/vscode-java#3213]
To have a selection for active Maven Profile as the same as Eclipse.

![001](https://github.com/redhat-developer/vscode-java/assets/1825591/5e14f82c-9e45-4616-9b10-da17a7182cd1)

![002](https://github.com/redhat-developer/vscode-java/assets/1825591/c1210499-b3f3-44d4-8bf0-4248ef92b56b)

![003](https://github.com/redhat-developer/vscode-java/assets/1825591/8ad34a8e-5ed2-418a-9e61-4f9bf357dd08)

##### Environment
- Operating System: Windows 11 Home Single Language 22H2
- JDK version: OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
- Visual Studio Code version: 18.0.1
- Java extension version: 1.20.0

**Comment by jdneo** [comment]
With the latest `Language Support for Java(TM) by Red Hat` (1.31.0) and latest `Extension Pack for Java` (0.27.0). You can now change the Maven active profile with a GUI with following steps:

1. Click the java status bar
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/82fa54f1-36a2-4982-9c3e-c7b581bb80a0)
2. Select `Open Project Settings`
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/3f8491a1-ceda-4ccb-bffd-4cb1fb64dbc0)
3. Go to the `Maven` tab, and type the profile names (comma separated) which you want to enable. For example: `profile1,profile2`
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/c69aedd0-b8db-440c-845f-49c199a7d709)
