### ISSUE TITLE
Microsoft IntelliCode extension doesn't provide consistence results based on how completions are invoked

### ISSUE THREAD

**Issue by gayanper** [redhat-developer/vscode-java#3222]
Microsoft IntelliCode extension doesn't provide consistence results based on how completions are invoked.

##### Environment
- Operating System: Any
- JDK version: Any
- Visual Studio Code version: 1.80.1
- Java extension version: nightlies

##### Steps To Reproduce
1. Invoke completions on `org.assertj.core.api.Assertions.`
You will get the `assertThat(String)` method with highest score.

2. Now make a static import for `org.assertj.core.api.Assertions.assertThat` method and try to complete behind `assert` on a new line.

Now the completions results are not properly scored. They are just shows with default scoring.

I would expect the same scoring to be applied when using in the static import scenario, since the completions result is same.

**Comment by gayanper** [comment]
@jdneo @CsCherrYY Could this be fixed from the vscode-java or jdt.ls side since Microsoft extension is kind of scoring the completions before they are shown in the editor ?

**Comment by fbricon** [comment]
Shouldn't that be an intellicode issue?

**Comment by gayanper** [comment]
Yes, I did some look into decompiled code in their side, seems like they have an issue in how to compute the receiver type. I will raise it in their bug tracker.
