### ISSUE TITLE
Running a Test File because packages do not exist [QUESTION]

### ISSUE THREAD

**Issue by MatthewMcConnell** [redhat-developer/vscode-java#323]
Quick question, I am trying to run a test file but fails because it says the org hamcrest and junit packages don't exist. Is the red hat extension supposed to get these for me automatically or do I have to do something. First time I've done this so clear step by step instructions would be useful.

**Comment by fbricon** [comment]
If you simply opened a single java test class, the classpath will be incomplete. 

The best way to configure the classpath would be to create a Maven or Gradle project, referencing junit (and hamcrest if you depend on it directly). You should be able to find tutorials on how to setup either [Maven](https://examples.javacodegeeks.com/enterprise-java/maven/junit-maven-example/) or [Gradle](http://makble.com/gradle-junit-helloworld-example) and how to run unit tests.

**Comment by jdneo** [comment]
More information, check: https://code.visualstudio.com/docs/java/java-testing#_enable-testing-and-adding-test-framework-jars-to-your-project
