### ISSUE TITLE
Paste the whole line does not work correctly

### ISSUE THREAD

**Issue by ShuFengMuYu** [redhat-developer/vscode-java#3236]
Ctrl+C or Ctrl+X would copy or cut the entire line behind the caret to the clipboard (including the newline).
Normally, pasting that line with Ctrl+V would insert the line before the line where the cursor is located .
However, when this extension is enabled, I tried to perform the same action, it seems to copy the entire line and then paste it just after the cursor.

Similar issuse has occurred. https://github.com/microsoft/vscode/issues/83003
But It seems that only java files are affected now.

##### Environment
- Operating System: Windows 10 19045.3208
- JDK version: jdk8 for my project, the default jdk for this extension
- Visual Studio Code version: 1.81.0
- Java extension version: 1.21.0

##### Steps To Reproduce (Ctrl+C Ctrl+V for example)
1. keep the cursor in a line normally
![image](https://github.com/redhat-developer/vscode-java/assets/56199046/f69edadb-14d1-42cd-a82d-584f78ce1e3e)
2. Ctrl+C and Ctrl+V 

##### Current Result
![image](https://github.com/redhat-developer/vscode-java/assets/56199046/1dba9861-2b34-4ea5-b889-2b07ebe6c240)

##### Expected Result
![image](https://github.com/redhat-developer/vscode-java/assets/56199046/61242969-0739-47ee-a83c-9a1a04b00406)

**Comment by andy98725** [comment]
This looks related to / possibly caused by #3237 . Are there any additional keyboard shortcuts added when you enable the extension?

**Comment by ShuFengMuYu** [comment]
> 


> This looks related to / possibly caused by #3237 . Are there any additional keyboard shortcuts added when you enable the extension?


I do not think the correlation between these is very strong. Because Paste using 'Language Support for Java(TM) by Red Hat' extension and Insert Plain Text cause the same result. Besides, pasting the whole line is expected to insert the line in front of the line where the cursor is located rather than cause the cursor to move.

**Comment by hopehadfield** [comment]
#3444 fixes this issue. Should no longer be a problem in 1.26.0 of vscode-java.
