### ISSUE TITLE
Language Support for Java(TM) by Red Hat overrides expected Paste behavior

### ISSUE THREAD

**Issue by andy98725** [redhat-developer/vscode-java#3237]
When selecting a block of text, copying and pasting is expected to move the cursor to the end of the block. When I disable the extension, it behaves as expected. With the extension enabled, the behavior is overrided and the cursor does not move.

##### Environment
- Operating System: Windows 11
- JDK version: N/A
- Visual Studio Code version: v1.80.1
- Java extension version: v1.21

##### Steps To Reproduce
1. Set up a fresh VSCode workspace with `Language Support for Java(TM) by Red Hat`
2. Select and copy (`Ctrl+C`) a block of text.
3. With the text still selected, paste (`Ctrl+V`).

##### Current Result
The block remains selected

##### Expected Result
The cursor should move to end of block

##### Additional Information
A "Show Paste options" dialogue comes up, with the options `Paste using 'Language Support for Java(TM) by Red Hat' extension` and `Insert Plain Text`. Presumably, the latter is the desired behavior, but the selection resets to the former option between each paste.

There is no setting AFAIK that disables this behavior override.

**Comment by dainank** [comment]
Bumping this because **there needs to be a plugin setting to disable this paste override**. 

I understand that there is currently a little popup that lets you select the VSCode paste behaviour, but this gets overwritten the next time you paste again through a keybinding. This is not sufficient behaviour, if anything, a bug.

**Comment by fbricon** [comment]
Try
```
"[java]": {
   "editor.pasteAs.enabled": false
},
```

**Comment by dainank** [comment]
> Try
> 
> ```
> "[java]": {
>    "editor.pasteAs.enabled": false
> },
> ```

This works! Thank you very much! I will amend my review of the VSCode extension. 

@fbricon 
I suppose that this trick can be used for all languages that get sometimes overridden by paste behaviours from plugins?

**Comment by fbricon** [comment]
yes, it's a VS Code setting

**Comment by bardware** [comment]
I notice there's something wrong when I want to duplicate a line of code. I select the line, press `CTRL + c` followed by `CTRL + v` twice. I expect my line to be duplicated. Still, there's only one line.
Setting `editor.pasteAs.enabled` as suggested helps. Still, no idea what this is supposed to mean.

**Comment by hopehadfield** [comment]
#3444 fixes this issue. Should no longer be a problem in v1.26.0 of vscode-java.
