### ISSUE TITLE
Highlighting becomes weird after v1.22.2023081612

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#3246]
[provide a description of the issue]

##### Environment
Version: 1.82.0-insider (user setup)
Commit: 7a464d6069a39b7d0e63c3da453d43a53eea7495
Date: 2023-08-16T05:33:47.797Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
- Java extension version: v1.22.2023081612

##### Steps To Reproduce
```
  private String getBuildTaskName(BuildTargetIdentifier btId) {
    GradleBuildTarget gradleBuildTarget = buildTargetManager.getGradleBuildTarget(btId);
    if (gradleBuildTarget == null) {
      throw new IllegalArgumentException("The build target does not exist: " + btId.getUri());
    }
    GradleSourceSet sourceSet = gradleBuildTarget.getSourceSet();
    String classesTaskName = sourceSet.getClassesTaskName();
    String modulePath = sourceSet.getProjectPath();
    if (modulePath == null || modulePath.equals(":")) {
      return classesTaskName;
    }
    return modulePath + ":" + classesTaskName;
  }
```

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
![image](https://github.com/redhat-developer/vscode-java/assets/6193897/bd930ade-b7b8-4925-b7e2-9650c3e90fdb)

##### Expected Result
Those marked tokens should have some color instead of white.

**Comment by rgrunber** [comment]
It was working on `v1.22.2023081104` and failed on `v1.22.2023081004`. It looks like https://github.com/redhat-developer/vscode-java/pull/3230 .

**Comment by 0dinD** [comment]
It does indeed look like #3230 is the culprit, because the non-highlighted tokens in the screenshot are tokens which are not currently reported via semantic highlighting. `if`, `null`, `":"` and `return` all rely on the TextMate grammar.

**Comment by 0dinD** [comment]
Quick tip when debugging this: If you disable semantic highlighting (via the `editor.semanticHighlighting.enabled` setting), so that you only see the TextMate-based highlighting, it might be easier to see what's going on. Also, the scope inspector will probably be useful: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector

**Comment by rgrunber** [comment]
@hopehadfield is considering reverting and just moving the logic into semantic highlighting (should be **much** easier). I think the only reason we tried to keep it in the textmate grammar is because it would have been nice to have it for anyone using just the grammar, and because it looked easier than handling the `record` case (which does reside server-side).

**Comment by 0dinD** [comment]
I agree, that's what I would do too. There is a reason why I have never even touched the TextMate grammar :slightly_smiling_face:. Simply put, I don't think it's maintainable, not for a complex grammar like Java.

> it would have been nice to have it for anyone using just the grammar

Yes, but then again, this is far from the only issue with the TextMate grammar. Anyone using it has probably come to terms with its flaws and limitations at this point. Not to mention, the semantic tokens from JDT LS are exposed via a standardized system (LSP), so it's not *too hard* to consume them, considering there are many LSP libraries out there at this point.

---

In my opinion, the best way forward is to continue improving the semantic highlighting implementation in JDT LS. It is built on top of JDT Core, which already contains a powerful and (mostly) bug-free Java parser.

Perhaps, at some point in the future, we can cover all of our syntax highlighting needs via JDT Core / JDT LS, at which point we can deprecate the TextMate grammar.

**Comment by jdneo** [comment]
Things back to normal with v1.22.2023081804
