### ISSUE TITLE
editing server.json doesn't work

### ISSUE THREAD

**Issue by n1nja88888** [redhat-developer/vscode-java#3247]
[provide a description of the issue]

##### Environment
- Operating System: Windows 10
- JDK version: 8
- Visual Studio Code version: 1.8.1
- Java extension version:1.21.0

##### Steps To Reproduce
I wanted to custom some snippets like `if` and `while` and I found it was defined in `server.json`. So, I just edited it. It worked at first but later when connected to the server, everything just went back as before like nothing changed at all.

**Comment by rgrunber** [comment]
Have a look at https://github.com/redhat-developer/vscode-java/blob/7230165406bbcd2375ff7fa35cb3db86f630aee2/src/standardLanguageClient.ts#L154-L155 . The snippets in `server.json` were meant to be used temporarily until the language server is fully started. Afterwards, I believe they're provided directly from there.

If you want to include your own snippets and play with them, you can try https://github.com/redhat-developer/vscode-java/blob/7230165406bbcd2375ff7fa35cb3db86f630aee2/package.json#L191-L196 .`java.json` is always included (for now). We'll probably be making some changes to snippets in the near future. For example, they currently have no mechanism to disable/enable themselves based on cursor location, and moving them to the language server side would help with that.

**Comment by n1nja88888** [comment]
> If you want to include your own snippets and play with them, you can try
> 
> https://github.com/redhat-developer/vscode-java/blob/7230165406bbcd2375ff7fa35cb3db86f630aee2/package.json#L191-L196
> 
> .`java.json` is always included (for now). You can also contribute your own file to that definition.

But it can't modify the existing snippets. For example, some snippets defined in `server.json` are not what I want, and I just want to customize them but not just be overwritten after being connected to the language server.

**Comment by rgrunber** [comment]
Right. I think all the snippets from `server.json` are defined on the server-side at https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/template/java/CodeSnippetTemplate.java#L80-L90 . If you edited the location there, you should have your custom snippet working prior to the language server starting, and after as well.

**Comment by n1nja88888** [comment]
Thx! I make it out. Btw, I wonder why not this extension just exposes all snippets for users to customize on their own. This approach you mentioned works but it is just way too cumbersome.

**Comment by testforstephen** [comment]
VS Code supports creating your own snippets without an extension. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

**Comment by n1nja88888** [comment]
> VS Code supports creating your own snippets without an extension. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

I know it does but I want to update the existing snippets but not add some new ones.

**Comment by testforstephen** [comment]
> I know it does but I want to update the existing snippets but not add some new ones.

Pls give more reason why you want to modify the existing snippets but not add your own.

**Comment by n1nja88888** [comment]
> > I know it does but I want to update the existing snippets but not add some new ones.
> 
> Pls give more reason why you want to modify the existing snippets but not add your own.

As I said, the `if` and `while` snippets by default are not what I want. If I just add my own `if` and `while` snippets, then there's gon' be 2 of the same existing snippets, which is weird and inconvenient.

**Comment by testforstephen** [comment]
> As I said, the if and while snippets by default are not what I want. If I just add my own if and while snippets, then there's gon' be 2 of the same existing snippets, which is weird and inconvenient.

If that's case, you should use a different alias for your own snippets. The snippets contributed by the extension is not designed for you to modify. They will be overwritten every time you update the extension.
