### ISSUE TITLE
Download and installation of the extension fails due to CDN rate limiting

### ISSUE THREAD

**Issue by ceculbe** [redhat-developer/vscode-java#3250]
Download and installation of the extension fails due to CDN rate limiting.

##### Environment
- Operating System: Windows x64
- JDK version: 17.0.8
- Visual Studio Code version: 1.81.1
- Java extension version: 0.25.13

##### Steps To Reproduce
1. search for extension in Marketplace
2. click 'install'
3. failure is intermittent, but >90% in our tests. If given the option, proceed with manual download

<img width="960" alt="screenshot error" src="https://github.com/redhat-developer/vscode-java/assets/10868522/1c7bf580-46ca-4920-aa06-11e588191451">

##### Current Result
Download of the extension package fails about 90% of the time. A popup appears with the option to download manually via browser. The manual download also fails 90% of the time with a browser error message indicating that "Request was blocked due to exceeding usage of resource . . . " (further details in attached screenshot.)

##### Expected Result
Once clicking 'install' on the extension page, download and installation proceeds without user involvement.

**Comment by jdneo** [comment]
Please file this issue to https://github.com/microsoft/vscode/issues. It's out of this extension's scope.
