### ISSUE TITLE
Static analyzes always show warning in every case of @Nullable field access.

### ISSUE THREAD

**Issue by Burtsev-Alexey** [redhat-developer/vscode-java#3255]
[provide a description of the issue]

##### Environment
- Operating System: Windows
- JDK version: 20
- Visual Studio Code version: 1.81.1
- Java extension version: 1.21.0

##### Steps To Reproduce
See screenshot.

##### Current Result

Always show warning "Potential null pointer access"

##### Expected Result
Some null check code exists that is considered as null check done, so warning is not shown. I understand that t is hard to analyze complex null check scenarios, but I'll be happy if simple code like  "if (obj!=null) {obj.foo()}" will not show warning.

##### Additional Informations
![2023-08-25_17-15-53](https://github.com/redhat-developer/vscode-java/assets/957102/76dfea5e-a38c-4d9a-a4e0-8840f89ca424)

Java language server log contains no errors or warnings:
!ENTRY org.eclipse.jdt.ls.core 1 0 2023-08-25 17:17:34.804
!MESSAGE 4 problems reported for /NullCheck.java

**Comment by fbricon** [comment]
looks like an uopstream JDT bug. Can you check if the same problem exists in Eclipse IDE and maybe report a bug in https://github.com/eclipse-jdt/eclipse.jdt.core?

**Comment by Burtsev-Alexey** [comment]
I have tried "NetBeans IDE 18" it's behavior is same as VSCode.
NetBeans IDE 18 always show warnings on "Nullable" access.

**Comment by fbricon** [comment]
Intellij IDEA performs more accurate null-analysis. Eclipse JDT should work better. The fact Netbeans provide the same broken behavior is irrelevant.

**Comment by Burtsev-Alexey** [comment]
I have created issue at  eclipse.jdt.core
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1311

**Comment by Burtsev-Alexey** [comment]
> Intellij IDEA performs more accurate null-analysis. Eclipse JDT should work better. The fact Netbeans provide the same broken behavior is irrelevant.

I'm sure you are right. Thought I'm a developer, I use IDEs as end user, and dont fully understand how they do their job.

**Comment by Burtsev-Alexey** [comment]
We have figured out this problem with jdt.core team https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1311

Indeed this is a bug in jdt.core and they are going to fix it. But this alone is not enough to make it work as expected in VS Code. By default jdt.core will still show warning, you need to set an "Enable syntactic analysis" option as described in their documentation:
![image](https://github.com/redhat-developer/vscode-java/assets/957102/680626aa-fccf-428a-8d8b-8f3dd7701e6b)

@fbricon Is there a way to configure this in VSCode Java extension now? If no, can you implement it?
I think this option should be on by default because, 99.9% developers would expect code` if (obj.field!=null) obj.field.toString()` - to not show NPE warning.

**Comment by fbricon** [comment]
@rgrunber  @hopehadfield I agree, we should turn that preference on by default in JDT.LS
