### ISSUE TITLE
src.zip is not attached automatically.

### ISSUE THREAD

**Issue by pingu8007** [redhat-developer/vscode-java#3263]
`src.zip` is not attached automatically even if `$JAVA_HOME` is configured.

##### Environment
Local
- Operating System: Windows_NT x64 10.0.19045
- JDK version: N/A
- Visual Studio Code version: 1.81.0 (user setup)
- Java extension version: N/A

Remote - DevContainer (on WSL2)
- Operating System: Linux x64 5.10.102.1-microsoft-standard-WSL2
- JDK version: Temurin-17.0.8+7 (JDK 17)
- Java extension version: v1.21.0

##### Steps To Reproduce
1. Configure `$JAVA_HOME` to actual install path, leave `java.configuration.runtimes` unconfigured.
2. Open project
3. Hover on built-in class and method
4. Go to Implementation of built-in class and method

Sample project not available at the moment.

##### Current Result
Javadoc is shown for class but not method.
Java source is shown for neither class nor method.

##### Expected Result
Javadoc should be shown for both class and method.
Java source should be shown for both class and method.

##### Additional Informations
❗ I use DevContainer heavily to switch between different JDK version, `java.configuration.runtimes` is not an option.
❗ I also works on project other than JDK 17, `java.jdt.ls.java.home` is not an option.

![image](https://github.com/redhat-developer/vscode-java/assets/8936513/c717d5de-ef10-4e36-b4ca-de599ac9fd11)
Without any explicitly settings, external JDK from `$JAVA_HOME` is detected at least for some extension. But ...

![image](https://github.com/redhat-developer/vscode-java/assets/8936513/abf4c7a9-37ae-4249-b5ea-12a3129db319)
bundled JDK is used. `src.zip` is not loaded.

After add following config to `settings.json` and run `Java: Clean Java Language Server Workspace` ...
```json
"java.configuration.runtimes": [
  {
    "name": "JavaSE-17",
    "path": "/opt/java/openjdk"
  }
]
```

![image](https://github.com/redhat-developer/vscode-java/assets/8936513/e11566e6-de7a-41a8-9924-cceda80e6aa5)
external JDK is used. `src.zip` is loaded correctly. Maybe the priority of JDK is the problem?

##### Relate issues

#2277 - Java extension: Failed to get sources. Instead, stub sources have been generated by the disassembler.

**Comment by jdneo** [comment]
I guess the recent PR https://github.com/redhat-developer/vscode-java/pull/3251 might solve your problem. Have you tried the latest pre-release version of redhat.java extension?

**Comment by pingu8007** [comment]
@jdneo Much thanks, the issue is solved. After switch `redhat.java` extension to pre-release channel (v1.22.2023082904), both javadoc and source are shown correctly.
