### ISSUE TITLE
Unable to import static post and similar methods

### ISSUE THREAD

**Issue by RMCampos** [redhat-developer/vscode-java#3265]
##### Description
When trying to import or get a code completion on VSCode I can notice no suggestion are made providing the right package to be imported. Actually, no packages are suggested at all.

##### Environment
- Operating System: Linux (Ubuntu 22.04)
- JDK version: Oracle 17.0.8
- Visual Studio Code version: 1.81.1
- Java extension version: v1.21.0

##### Steps To Reproduce
1. Go to https://start.spring.io/ and pick
  - Maven Project
  - Java Language
  - Latest Spring Boot version (3.1.3 for me)
  - Java version 17
  - Dependencies: Spring Web
  - Click generate, save it, extract it
2. Open the new project on VSCode
3. Create a test class under src/test/java/com/example/demo. E.g.: ImportIssue.java
4. Add `@Autowired private MockMvc mockMvc;`
5. Create void test
6. Type mockMvc.perform()
7. Inside perform write `post()` and try to get a code completion
8. When trying the "Quick fix" option, there's only a create method, no option for importing

[Please attach a sample project reproducing the error]
Here: https://github.com/RMCampos/import-vscode-issue

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
Here: [import-issue.log](https://github.com/redhat-developer/vscode-java/files/12478956/import-issue.log)

##### Current Result
No option for importing or code completion.

##### Expected Result
Optin to staticly import the package `org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post`

##### Additional Informations
The only JDK installed is the one highlighed in the environment information.

**Comment by testforstephen** [comment]
We use a whitelist to specify which static imports are allowed. You can customize this list by editing the `java.completion.favoriteStaticMembers` setting and adding your desired classes to the whitelist.

**Comment by RMCampos** [comment]
> We use a whitelist to specify which static imports are allowed. You can customize this list by editing the `java.completion.favoriteStaticMembers` setting and adding your desired classes to the whitelist.

Awesome. Worked like a charm. Thanks for providing such option, I did not know.
