### ISSUE TITLE
I can't see the javadoc of the jdk

### ISSUE THREAD

**Issue by vipcxj** [redhat-developer/vscode-java#3268]
[provide a description of the issue]
The javadoc of jdk not show. And no source attached. If I jump to the source of a jdk method, the decompiled file show.
I run the vscode on the remote computer. I have export the JAVA_HOME both in ~/.bashrc and ~/.profile.
I can see the javadoc of the thirdpart library.

##### Environment
- Operating System: ubuntu 22
- JDK version: 17
- Visual Studio Code version: 1.81.1
- Java extension version:

##### Steps To Reproduce
1. [step 1] Install jdk 17 on remote ubuntu server using apt
2. [step 2] Export the JAVA_HOME both in ~/.bashrc and ~/.profile
3. [step 2] Using vscode to open the remote project on the server.

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
I can't see the javadoc of the jdk

##### Expected Result
I can see the javadoc of the jdk

**Comment by fbricon** [comment]
did you try `sudo apt-get install openjdk-17-source`?

**Comment by vipcxj** [comment]
@fbricon You are right. It's ok. I have tried to install the source code of OpenJDK, but I tried it a few times. The package name was wrong, and I found that the $ java_home/lib/src.zip file exists, so I gave up.
