### ISSUE TITLE
I can't see the javadoc from parent method

### ISSUE THREAD

**Issue by vipcxj** [redhat-developer/vscode-java#3270]
[provide a description of the issue]
I can't see the javadoc from parent method.
For example I write a interface I extends a interface P.
All methods of P have javadoc, and no javadoc on the interface I.
The javadoc of I doesn't show.

##### Environment
- Operating System: ubuntu 22
- JDK version: 17
- Visual Studio Code version: 1.81.1
- Java extension version:

##### Steps To Reproduce
1. [step 1] Write a interface I extends a existing interface P with full javadoc.
  ```java
   interface P {
    /**
     * description.
     *
     * @param a something about a.
     */
       void foo(int a);
   }

   interface I extends P {
       default void foo(int a) {}
   }
  ```

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
No javadoc shown when I hover on the method I.foo

##### Expected Result
The javadoc of P should shown when I hover on the method I.foo

**Comment by jdneo** [comment]
I cannot repro it on my side.

![image](https://github.com/redhat-developer/vscode-java/assets/6193897/3724face-18ee-413b-811f-63aabb424816)

Is there any errors in the log? See: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging

**Comment by vipcxj** [comment]
It's strange. I can see it, too. Perhaps something wrong with the plugin before. What's ever it works now.
