### ISSUE TITLE
[Java] Lambda expressions are allowed only at source level 1.8 or above

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#328]
I try to use lambda's but I get the following error:

> [Java] Lambda expressions are allowed only at source level 1.8 or above

In my user settings I have set:

> "java.home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home"

How can I set the source level?

##### Environment
- Operating System: OSX
- JDK version: jdk1.8.0_144
- Visual Studio Code version: 1.17.1
- Java extension version: 0.1.0

**Comment by fbricon** [comment]
Do you use Maven to build your app, or something else?

When using Maven, you need set the [maven-compiler-plugin source and target elements to 1.8](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html)

**Comment by Carrein** [comment]
These 'errors' are quite common in Java projects in VS.

```
[Java] Syntax error, annotations are only available if source level is 1.5 or greater
[Java] Method references are allowed only at source level 1.8 or above
[Java] Lambda expressions are allowed only at source level 1.8 or above
```

They don't affect the files, as they compile fine. I was informed such errors occur when the project hierarchy is not properly setup. Is there a way to silence them? I am writing simple class files using an open folder as a mock 'directory' with javac, java to run them.

**Comment by YLiLarry** [comment]
Same problem here. I'm using Gradle. Is there any way I can set it up or suppress the error?

**Comment by UtkarshGupta-CS** [comment]
Change the extension generated file `.settings.org.eclipse.jdt.core.prefs`
```
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8
org.eclipse.jdt.core.compiler.compliance=1.8
org.eclipse.jdt.core.compiler.problem.forbiddenReference=warning
org.eclipse.jdt.core.compiler.source=1.8
```

**Comment by mrpanc** [comment]
@UtkarshGupta-CS  Thank you so much. It has solved my problem.

**Comment by yaohaizh** [comment]
Close this issue as it had been solved. Project setting issue.

**Comment by PhillipMwaniki** [comment]
> Do you use Maven to build your app, or something else?
> 
> When using Maven, you need to set the [maven-compiler-plugin source and target elements to 1.8](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html)

You're the best.

**Comment by AnhNguyen92** [comment]
add  [maven-compiler-plugin source and target elements to 1.8](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html) to pom file sovle this problem

**Comment by Stejnar** [comment]
@ylilarry Can you please elaborate on how you accomplished this?

**Comment by JhonatanJGAmaral** [comment]
If you're still facing a problem by setting the Maven to level 1.8 or above, you can also add or replace the properties in pom.xml, where is either the Maven properties, like that: 
  

>  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  
Or just replace the number that is supposed to be between "<maven.compiler.source>"  and "</maven.compiler.source>" and between "<maven.compiler.target>" and "</maven.compiler.target>", for instance. I strongly hope the information will come in handy someday, for someone.

**Comment by JhonatanJGAmaral** [comment]
> @ylilarry Can you please elaborate on how you accomplished this?

Is there any XML file called "pom" in your app's roots? If so, you can merely try doing what I've reported here: [Upgrade Maven Compiler Level](https://github.com/redhat-developer/vscode-java/issues/328#issuecomment-873634223)
