### ISSUE TITLE
Language Support for Java (Syntax Server) client: couldn't create connection to server.

### ISSUE THREAD

**Issue by yuqingc31** [redhat-developer/vscode-java#3288]
Hi, I opened my java file this morning and found hundreds of red wavy lines. But my java file is compiling fine. The error it gives me is: Language Support for Java (Syntax Server) client: couldn't create connection to server.The source is: Language Support for Java(TM) by Red Hat.I noticed that your Change Log was updated yesterday and I was wondering if it was because of this.

##### Environment
- Operating System: MacOs
- JDK version: openjdk version "11.0.20.1" 2023-08-24
- Visual Studio Code version: 1.82.1 (Universal)
- Java extension version: v1.22.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by rgrunber** [comment]
This may be https://github.com/redhat-developer/vscode-java/issues/3287 . We're working on a fix.

**Comment by rgrunber** [comment]
This was fixed in the issue mentioned above in 1.22.1 . If you're still running into this, feel free to re-open.
