### ISSUE TITLE
"New > Java Class" wizard cannot create a class for Japanese identifiers.

### ISSUE THREAD

**Issue by nagise** [redhat-developer/vscode-java#3289]
When I open the "New > Java Class" wizard and enter a Japanese class name, I receive the message "Invalid Java qualified name." and I am unable to create a Java class.

##### Environment
- Operating System: Windows 11
- JDK version: 17
- Visual Studio Code version: 1.79.2
- Java extension version: v0.25.14

##### Steps To Reproduce
1. Select any package, right-click, and choose "New > Java Class."
2. Enter Japanese characters as the class name. For example, "ほげ" 

##### Current Result

It displays "Invalid Java qualified name."

##### Expected Result

The class is generated.

##### Additional Informations

In Java, we can use characters from languages such as Japanese and others in identifiers.

https://docs.oracle.com/javase/specs/jls/se17/html/jls-3.html#jls-3.8

**Comment by jdneo** [comment]
Transferred to https://github.com/microsoft/vscode-java-dependency/issues/789
