### ISSUE TITLE
miss shortcuts button of The Test Runner for Java extension

### ISSUE THREAD

**Issue by meiliangdeng** [redhat-developer/vscode-java#3304]
[provide a description of the issue]

##### Environment
- Operating System: Mac OS: 12.4
- JDK version: "java.jdt.ls.java.home": jdk-17.0.3.1.jdk
- Visual Studio Code version: 1.82.2
- Java extension version: Language Support for Java(TM) by Red Hat
 v1.23.2023091604 , Test Runner for Java v0.39.1

##### Steps To Reproduce
1. open any java project(eg:maven Project)
2. coding any unit case

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
don`t find The Test Runner for Java extension shortcuts button after coding any unit case
<img width="574" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/7776627/b748feaf-0bd8-4ab5-9c72-43a0f32f2bd6">

##### Expected Result
show shortcuts button, following:
<img width="286" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/7776627/aae6a8a8-9756-480f-b50e-39b5fac9de1b">

##### Additional Informations
The previous version of vscode or Java extension had this shortcut button, but it was not available in the Language Support for Java(TM) by Red Hat v1.23.2023091604 version

**Comment by fbricon** [comment]
This feature is provided by vscode-java-test. Please open a ticket at https://github.com/microsoft/vscode-java-test/issues
