### ISSUE TITLE
Better support for Maven Archetype projects

### ISSUE THREAD

**Issue by jgeorgeson** [redhat-developer/vscode-java#331]
With `java.configuration.updateBuildConfiguration` set to automatic, the `src/main/resources/archetype-resources/pom.xml` is built, creating a `src/main/resources/archetype-resources/target` folder that is then included into the packaged archetype jar. It's nice to have the Eclipse project files (.settings folder, .classpath, and .project) created inside the archetype-resources so that projects generated from my archetypes are Eclipse-ready out of the box, but the target folder definitely doesn't belong.

##### Environment
- Operating System: Windows
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. Create a project with `mvn archetype:generate -DarchetypeArtifactId=maven-archetype-archetype`
2. Open project in VS Code and set to automatically update build configuration when build files are changed.

##### Additional Informations

https://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype.html

**Comment by fbricon** [comment]
I can't get it to create `src/main/resources/archetype-resources/target` (which would be wrong), however setting java.configuration.updateBuildConfiguration to automatic makes jdt,ls go into an infinite loop of project updates, which is definitely wayyyy more wrong

**Comment by jgeorgeson** [comment]
Thanks, can confirm I'm not seeing that target folder show up under src/main/archetype-resources anymore in 0.13.0.
