### ISSUE TITLE
Allow pasting a Java file into the file explorer

### ISSUE THREAD

**Issue by Artur-** [redhat-developer/vscode-java#3323]
A handy way to get a java file from an external source into the project is to copy the source (not the file) and then paste it in the file tree. This has "always" worked in Eclipse and it would be great to have it working also in VS Code.

When pasting into a Java source folder, the file should be placed in the correct package (not the folder it is pasted in) and named according to a public Java class in the snippet. 

So pasting e.g. this
```
package foo.bar.baz;

public class HelloWorld {
}
```

into `src/main/java` in a Maven project should create `src/main/java/foo/bar/baz/HelloWorld.java`

##### Environment
- Operating System: mac
- JDK version: 21
- Visual Studio Code version: 1.82.2
- Java extension version: 1.22.1

##### Steps To Reproduce
1. Copy
2. Paste

##### Current Result
Nothing happens when you paste a Java snippet into the explorer

##### Expected Result
As described above

**Comment by rgrunber** [comment]
Agreed. I really like that feature. Especiall that it creates the folder structure defined by the `package ...` declaration of the code sample (if present). I don't think we can use VS Code's experimental document paste API. That requires a document to be opened. Maybe we could create some key binding around <kbd>ctrl+v</kbd> or <kbd>ctrl+shift+v</kbd> and accessing https://code.visualstudio.com/api/references/vscode-api#Clipboard . Once we have the file, the invisible project support should be enough to handle the rest.

**Comment by hopehadfield** [comment]
This feature is currently in the works. When a java text is pasted in the file explorer using `ctrl + shift + v`, a file is created containing that text and named using the declared type name. It is also added to the appropriate package based on the package name at the top.

![Peek 2023-11-10 14-22](https://github.com/redhat-developer/vscode-java/assets/115827695/fc1b73cc-d103-4175-9b31-0ac47e16255c)

This feature extends to when the language server is not already running, though it works with some delay for the server to get started.

![Peek 2023-11-10 14-26](https://github.com/redhat-developer/vscode-java/assets/115827695/b6c52a48-57f2-46fb-b0bd-c25560ce61ef)

When there is no project currently open, the file is placed in a tmp folder in the user's home directory. The following gif also exemplifies the creation of a folder according to the package name if it does not already exist.

![Peek 2023-11-10 14-24](https://github.com/redhat-developer/vscode-java/assets/115827695/bd864ee2-176e-4a8c-b0c0-e0af2515d938)

There is still some work to be done, particularly with packages. The search for a matching package name is very minimal right now.

**Comment by fbricon** [comment]
@hopehadfield make sure this feature (including overriding the paste shortcut itself) can be disabled via a setting

**Comment by rgrunber** [comment]
Change will end up in the pre-releases. Note that from discussions, we've decided to [not enable this feature when no workspace folders are opened](https://github.com/redhat-developer/vscode-java/pull/3404#discussion_r1417297567). However we could do this if needed.

There's still the case of an invisible project where a file isn't open. Pasting has to wait until the language server is ready. I think we should have a client-side check while the language server is  starting to avoid delays.
