### ISSUE TITLE
Autocomplete ordering lists longest overloads first

### ISSUE THREAD

**Issue by oliviercailloux** [redhat-developer/vscode-java#3327]
When triggering autocomplete on methods that have many overloads, VSCode lists the longest ones first. It is usually the shortest ones that I (and, I suspect, most developers) need. I’d like to see it first. 

Example: [Preconditions#checkArgument](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/base/Preconditions.html) has 25 overloads. I usually need the simple `checkArgument(boolean)`, and occasionally `checkArgument​(boolean expression, Object errorMessage)`, but VSCode lists `checkArgument(boolean expression, String errorMessageTemplate, Object p1, Object p2, Object p3, Object p4)` first, and the two ones that are most needed as 24th and 25th suggestions.

Same with the 93 overloads of [Assertions#assertEquals](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Assertions.html): one usually needs the simple two arguments version, but VSCode suggests all variants of the four arguments overloads first.

Note that the Javadoc displays the overloads shortest first, which seems quite natural to me. Note also that selecting a shorter method then adding arguments is less tedious than selecting a longest one then deleting arguments.

Is this how VSCode normally behaves, or have I misconfigured something? If it is its usual behavior, can it be changed?

##### Environment
- Operating System: Linux
- JDK version: 17
- Visual Studio Code version: 1.82.2
- Java extension version: 1.23.0

##### Steps To Reproduce
1. In a project with Guava added as a dependency, type `Preconditions.checkAr`
2. Trigger autocompletion

**Comment by rgrunber** [comment]
I think we fixed this in the language server in https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2874 so it should be in the pre-releases, and make the next release of vscode-java (end of October). We now sort by number of parameters. It should also be possible to filter by the signature data so one doesn't have to 

This was a regression from the time we introduced `labelDetails`. It made the completion list nicer, but affected ordering/filtering. We're currently going through some of these issues and addressing them.
