### ISSUE TITLE
Add rename after the "Extract to method" refactor

### ISSUE THREAD

**Issue by yaohaizh** [redhat-developer/vscode-java#333]
This is a follow issue from https://github.com/eclipse/eclipse.jdt.ls/pull/381

For rename triggered on refactor, the typescript/vscode-python will use refactor provider to add additional commands in the client side. For Java client side, we need to see how to intervene the actions here.

**Comment by yaohaizh** [comment]
@aeschli Do you have any hint for the protocol layer to support this? I found that the typescript/javascript/python will use refactorProvider to intervene with the refactor process and send another command for rename after the refactor is done. But C# doesn't support this yet.

**Comment by aeschli** [comment]
Thos is done through code actions, right? The result of a code action is a command, which is in Java the "java.apply.workspaceEdit" command. I could expand that command to add instructions to invoke the rename command at a given position after the edits are applied.
I guess the tricky part will be to track the right position as the edits can change everything.

**Comment by yaohaizh** [comment]
yes, that should how typescript implement this: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/refactorProvider.ts

**Comment by testforstephen** [comment]
This can be done by invoking vscode command 'editor.action.rename' to trigger `rename` operation in client side. But it requires the jdt.ls server to compute the document location for the newly created function by "Extract to method" code action.

**Comment by fbricon** [comment]
Screencast of rename after refactoring in action:
![](https://user-images.githubusercontent.com/14052197/60074929-b0297780-9756-11e9-96c1-99907bee918c.gif)
