### ISSUE TITLE
imports of class from src/main/java cannot be resolved in class src/test/java 

### ISSUE THREAD

**Issue by taisbak** [redhat-developer/vscode-java#3332]
I have the following structure in my java project, where `import MyClass` cannot be resolved in `MyClassTest`: 

```
/src
    /main
        /java
            /MyClass.java
    /test
        /java
            /MyClassTest.java
```
It seems to be a problem only for VSCode Language Support for Java - the Maven build works fine, and IntelliJ works fine.
However, if I add the following entry to the file `.classpath`, it works as expected:
```
<classpathentry kind="src" output="target/classes" path="src/main/java"/>
```
which is  similar to another entry:
```
<classpathentry kind="src" output="target/test-classes" path="src/test/java">
    <attributes>
        <attribute name="optional" value="true"/>
        <attribute name="maven.pomderived" value="true"/>
        <attribute name="test" value="true"/>
    </attributes>
</classpathentry>	
```

I suspect that the generation of `.classpath` is incomplete or the analyzer should consider `src/main/java` as default.
It's referenced in the maven `pom.xml` as:
```
  <build>
    <sourceDirectory> ... /src/main/java</sourceDirectory>	
```

##### Environment
- Operating System: Windows 11
- JDK version: 17
- Visual Studio Code version: 1.83
- Java extension version: 1.23

**Comment by fbricon** [comment]
This usually works as expected. Please provide a sample project reproducing this issue.

**Comment by taisbak** [comment]
I understand your scepticism :-)

Please find attached a project with the described behaviour: [sample-with-unresolvable-imports.zip](https://github.com/redhat-developer/vscode-java/files/12820538/sample-with-unresolvable-imports.zip)
It's somewhat crippled - I did my best to reduce it to the point....

It contains a number of source generated classes (the generator plugins have been deleted from the POM) that VSCode cannot resolve.
Therefore the added lines in the POM line 31-33:
```
    <includes>
        <include>/target/generated-sources/src/java/main</include>
    </includes>
```
When toggled on and off, the generated classes are resolved or not.
However, the main classes still aren't resolved from the main classes.

**Comment by taisbak** [comment]
Hmm... it's not a bug.
Turned out that changing http to https in POM + adjusting maven lifecycle made it work.
Just annoying that it worked in IntelliJ but not in VSCode.
Sorry for the inconvenience.
