### ISSUE TITLE
Host textmate definition for kotlin language

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#3334]
Buildship recently added experimental feature -- a language server for the *.kts files, which works for the gradle kts scripts.

It introduces a textmate definition for kotlin language: https://github.com/eclipse/buildship/blob/master/org.eclipse.buildship.kotlindsl.provider/kotlin.tmLanguage.json

Should we consider hosting this file in the extension? Currently there is no hightlighting when user opens *.kts files.

**Comment by jdneo** [comment]
@rgrunber BTW, I saw we already host definitions for `.java` and `.properties`. While the VS Code repo also has `.java` hosted. I forgot the story to re-host another `.java` definition. Could you remind me about that?

**Comment by rgrunber** [comment]
See https://github.com/microsoft/vscode/pull/187725#issuecomment-1633956154,  https://github.com/redhat-developer/vscode-java/pull/3200, https://github.com/microsoft/vscode/pull/188361/files .

Basically the original grammar provided by atom/language-java became read only at the end of 2022. This was the one VS Code was using. We raised an issue about fixing it but the proposal was for vscode-java to "own" the grammar and VS Code is now updating based on ours.

**Comment by jdneo** [comment]
Thank you for the explanation!
