### ISSUE TITLE
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510) when debugging vscode-extension project

### ISSUE THREAD

**Issue by AlbertMZhou** [redhat-developer/vscode-java#3336]
##### Environment
- Operating System: Windows 10
- JDK version: 17
- Visual Studio Code version: 1.83
- Java extension version: 1.24

##### Steps To Reproduce
1. downloud and debug a vscode-extension-sample.
2. In the debugging window, open an explorer of Java project in the workspace, select one of .java file.
3. then the redhat-java will compile and show the error message.

##### Current Result
The error message will output in extension-sample's output channel. And there will be error InformationMessage from Language Support for JAVA(TM). This makes that the extension-sample cannot call the commands provided by Language Support for JAVA
![image](https://github.com/redhat-developer/vscode-java/assets/58078659/7885b0a6-3ad4-4e4f-9049-1a1c64a84ace)
![image](https://github.com/redhat-developer/vscode-java/assets/58078659/0accf42a-b212-4fd7-b7f7-c45f92872ff8)

##### the core error logs are:
```
[Info  - 16:40:55] Connection to server got closed. Server will restart.
false
[Error - 16:40:56] Language Support for Java client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 

{
  message: 'ERROR: transport error 202: bind failed: Permission denied\n' +
    'ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)\n' +
    'JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [s\\open\\src\\jdk.jdwp.agent\\share\\native\\libjdwp\\debugInit.c:734]\n',
  level: 'info',
  timestamp: '2023-10-08 16:40:56.165'
}
```

**Comment by AlbertMZhou** [comment]
if I package my extension to .visx file,  then install it and run java program in the real vscode window, the error won't get out and my extension works out. I got the reason in #1468 , but the author may just kill the extension process. How can I fix the conflict between extension debug process and the auto debug process by Language Support for Java?

**Comment by snjeza** [comment]
>  How can I fix the conflict between extension debug process and the auto debug process by Language Support for Java?

Java LS is listening on the 1044 (the standard server) or 1045 (the syntax server). What port are you using?

**Comment by AlbertMZhou** [comment]
> > How can I fix the conflict between extension debug process and the auto debug process by Language Support for Java?
> 
> Java LS is listening on the 1044 or 1045 port. What port are you using?

I use command "netstat -aon|findstr "1044"" and "netstat -aon|findstr "1045"" to find nothing. Neither of these port are occupied. Besides, there is no the error message  "Address already in use" in OUTPUT window

**Comment by snjeza** [comment]
@AlbertMZhou Can you try
```
netsh interface ipv4 show excludedportrange protocol=tcp
```

**Comment by AlbertMZhou** [comment]
> @AlbertMZhou Can you try
> 
> ```
> netsh interface ipv4 show excludedportrange protocol=tcp
> ```

the result 
![image](https://github.com/redhat-developer/vscode-java/assets/58078659/298bd52c-5427-4353-91b9-6e98bcea4006)

**Comment by snjeza** [comment]
Ports 1044 and 1045 are reserved. You can try to release them using:
```
net stop winnat
net start winnat
```
or change them at https://github.com/redhat-developer/vscode-java/blob/30697c3ad0821f4ca97c56b072988f2cd2b505a8/src/javaServerStarter.ts#L74

**Comment by Vinayynn** [comment]
what is the command for mac?

> > Ports 1044 and 1045 are reserved. You can try to release them using:
> > ```
> > net stop winnat
> > net start winnat
> > ```
> 
> That really works! Thanks a lot! ❤
