### ISSUE TITLE
Upgrading to 1.23.0 makes all tests disappear

### ISSUE THREAD

**Issue by WildPenquin** [redhat-developer/vscode-java#3338]
Greetings!

After upgrading to 1.23.0, all my tests disappear. Downgrading to 1.22.1, tests reappear.

I'm not sure if I should report against this plugin or [the tests plugin](https://github.com/microsoft/vscode-java-test) or some other plugin (Maven???), or perhaps Code OSS, as I have no idea where the actual problem is. However, given that tests plugin has not had a release recently, I reported here as a first step. In case this is invalid/wrong, I apologize.

I can recreate this with a newly created Maven project. I can recreate this with a fresh Code OSS configuration. With the 1.23.0 the template test can not be seen in the test runner UI, with 1.22.1 it can be found.

##### Environment
- Operating System: Arch Linux
- JDK version: 17
- Visual Studio Code version: Code OSS 1.83.0

> Version: 1.83.0
> Commit: e7e037083ff4455cf320e344325dacb480062c3c
> Date: 2023-10-06T10:42:02.233Z
> Electron: 25.9.0
> ElectronBuildId: undefined
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Linux x64 6.5.6-arch2-1

- Java extension version: 1.23.0

##### Steps To Reproduce
1. Install Java Plugin pack ( Java support and test plugins are enough, though)
2. Create a new project with Maven; `mvn archetype:generate -DgroupId=test.wildpenguin.app -DartifactId=Test-App -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false`
3. Open this project in VS Code
4. Try to find the test in the tests section

The sample project can be generated with the above command.

[vscode-app-1697028635332.log](https://github.com/redhat-developer/vscode-java/files/12869953/vscode-app-1697028635332.log)
[.log](https://github.com/redhat-developer/vscode-java/files/12869945/default.log)

##### Current Result

The tests are not shown in the UI tests section (the tests section here, but the single test in this example can not be found in the tree).

##### Expected Result

The tests should be shown in the UI tests section.

##### Additional Informations

The tests are shown in case I downgrade the JAVA plugin to the previous release (1.22.1)

**Comment by WildPenquin** [comment]
I have tested with the VS Code 1.83.0 binary, and test are available.

So, it's a combination of the Java plugin >= 1.23.0, **Code OSS** and the tests plugin (and something else?), which causes the tests to not be available in the UI.

Any input on where I should report this are welcome (if this is not the right place)!

**Comment by snjeza** [comment]
@WildPenquin Could you try to use the v0.40.0 version of the `Test Runner for Java` extension?

**Comment by WildPenquin** [comment]
Hi @snjeza ,

Upgrading to 0.40.2023100808, I can use tests again from the UI! (in Code OSS).

I've never realized Code OSS uses a different marketplace until now. Open-vsx only has vscode-java-test 0.39.1.

**Comment by WildPenquin** [comment]
Hi again,

Any idea who / which would be the right upstream, should I ping them / open another issue, or are they already aware?

Is it perhaps [open-vsx](https://github.com/open-vsx/publish-extensions/issues)?

**Comment by jdneo** [comment]
open-vsx should be the right upstream.
