### ISSUE TITLE
faster plugin startup

### ISSUE THREAD

**Issue by snovo** [redhat-developer/vscode-java#336]
this extension is great but it takes far too much time to be ready as it seems to be rebuilding the workspace everytime a new project/folder is loaded.
opening a medium size project takes up to 15min to rebuild the workspace...

wondering if it wouldn't be possible to reuse the workspace from the last session and provide an option to rebuild the workspace if necessary...

##### Environment
- Operating System: windows 10
- JDK version: 1.8
- Visual Studio Code version: 1.17.1 x64
- Java extension version: 0.11

##### Steps To Reproduce
1. open a medium/large folder.

current folder structure takes up to 15minutes to load:
![capture](https://user-images.githubusercontent.com/2424053/31712767-ec9570fe-b3f3-11e7-97f9-0649f69e0f23.PNG)

**Comment by fbricon** [comment]
vscode-java already reuses the same workspace than the last time the folder was opened. 

From what I see in your screenshot, there doesn't seem to be many Maven modules, unless there's a deeper module hierarchy. So 15min to rebuild seems really excessive. 
Exactly how many Maven modules do you have, how many java files? Any chance you could share your pom.xmls, so that we can see if some rogue Maven plugins are slowing down the build? Any way you can reproduce the issue with an open source project?

**Comment by snovo** [comment]
My development machine is actually a VM and I do have a bunch of VSCode extensions active alongside with vscode-java.
I did disable all extensions but vscode-java and unfortunately, the outcome is pretty much the same. I also tried it out on my host machine and it's faster, but I noticed something weird while testing it. It seems that cleaning up the workspace before opening VSCode makes it faster!

I have been trying to get some measurements either using my project and also this one https://github.com/google/guava, both on my VM and host machine with only vscode-java extension enabled. The following are some average measurements of time the vscode-java needs to be ready:

**Host machine:
Project    | No previous workspace  | Previous workspace present (supposedly reusing it)**
My own  | about 9 minutes              | about 10 minutes --> 40 seconds slower on average
Guava     | about 1 min and 40 sec  | about 2 minutes   --> 20 seconds  slower on average

**VM machine:
Project    | No previous workspace   | Previous workspace present (supposedly reusing it)**
My own  | about 14 min and 20 sec | about 17 minutes      --> 3 minutes slower on average
Guava     | about 5 min and 30 sec   | about 7:20 minutes    --> 2 minutes  slower on average

These results are reproducible on my machine.
None of the projects takes more than 2minutes when compiled from scratch using the command "mvn clean compile" on a powershell/CMD instance (I understand vscode-java does more than just compiling the projects).

My project has 12 modules and 506 java files (not as big as I thought)
Guava seems to have 9 modules and 3432 java files

I can't share the original pom files, but I'm happy to share them with the project and company names "obfuscated".

[POMs.zip](https://github.com/redhat-developer/vscode-java/files/1410956/POMs.zip)

**Comment by fbricon** [comment]
@snovo so CLI build takes 2 mins max in your VM?

**Comment by fbricon** [comment]
@snovo what do you measure exactly to determine the build is finished in vscode?

**Comment by fbricon** [comment]
Windows always had terrible terrible I/O perf, I see that hasn't changed with Win 10 apparently :-(

Running mvn clean test-compile would be a more accurate comparison with what vscode-java actually does. It takes 40sec to compile all files from guava on my MacBook Pro from CLI. 

Looking at the Language Support for Java output logs, between the 1st line to the last one after server reaches 100% startup, a "cold" import takes about 47sec, and a "hot" one is about 10sec slower. So this definitely doesn't work as expected. It should be much faster instead.

**Comment by snovo** [comment]
Hi fbricon,

As a measurement, I was looking for the status progress (percentage) of the extension and calculating the difference between the time it reaches 100% and when the percentage first shows up in the UI.

Btw, I just tried out "mvn clean test-compile" with guava and it took 1:47 min. Executing "mvn test-compile" took 40seconds afterwards.
Quite slower than on your's MacBook... My machine still uses a standard SATA SSD as opposite to the M.2.
With the project I'm working on it took 3:42 min to run "mvn clean test-compile" and 16sec to run "mvn test-compile" afterwards.

You can find the vscode-java log file for guava which contains 2 sessions. The first one is related to a clean compilation and the second one related to a hot compilation (reusage of the workspace): 
[vscode-java.log](https://github.com/redhat-developer/vscode-java/files/1411498/vscode-java.log)

I used to use IntelliJ and it was must faster after the cold/clean compilation. That's why I thought the workspace wasn't being reused at all.

**Comment by fbricon** [comment]
I think the problem comes from our systematic re-import of the projects, when the workspace is reopened. If the projects already exist in the underlying workspace, we might just refresh them and stop there. Hopefully that might help.

**Comment by fbricon** [comment]
So even when skipping the maven import when the project already exist, it still take a minute to start. The server seems to execute a full build, which is what's taking a very long time to run.
Guess I'll need to dig more

**Comment by snovo** [comment]
let me know if you need more info

**Comment by fbricon** [comment]
@snovo still banging my head on it

**Comment by fbricon** [comment]
You can download the most recent `java-<version>.vsix` file containing the fix and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

**Comment by kuntergunt** [comment]
Try to disable virus scanning on the project folder if you trust the sources. That helped to speed up my build times a lot.
