### ISSUE TITLE
Cannot download the Java extention pack in vs code

### ISSUE THREAD

**Issue by Pavanipunymanthula** [redhat-developer/vscode-java#3379]
Cannot download the Java extention pack in vs code and even manually from the browser it's showing "end of Central directory record signature not found"

[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by jdneo** [comment]
Please file issue at https://github.com/microsoft/vscode/issues. Extension downloading is out of scope of this extension.
