### ISSUE TITLE
Javadoc @value doesnt work as expected (also @implSpec and @implNote)

### ISSUE THREAD

**Issue by Nightenom** [redhat-developer/vscode-java#3385]
`{@value target}` is not displayed as expected.
Java spec describing the feature: https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDDCDHH

##### Environment
- Operating System: w11 pro 22H2
- JDK version: adoptium openjdk 17.0.8.1 2023-08-24
- Visual Studio Code version: 1.83.1
- Java extension version: v1.25.2023110903

##### Steps To Reproduce
1. Use supplied code below
2. Hover over class to display its javadoc
3. Suprisingly it works if you dont supply the class name, ie. just #CONSTANT_VALUE

##### Current Result

![image](https://github.com/redhat-developer/vscode-java/assets/17338378/0e929e3c-56c7-415c-a84c-96e4bd88db58)

##### Expected Result

Actual value to be inserted, the value according to latest javadoc generator should(?) be with quotes included

##### Additional Informations

```java
/**
 * {@link Test#CONSTANT_LINK}
 * <p>
 * {@value Test#CONSTANT_VALUE}
 */
public class Test
{
    public static final String CONSTANT_LINK = "hello link";
    public static final String CONSTANT_VALUE = "hello value";
}
```

**Comment by fbricon** [comment]
I confirm this is an issue in upstream Eclipse JDT. Could you please open this ticket in https://github.com/eclipse-jdt/eclipse.jdt.core/issues?

**Comment by Nightenom** [comment]
@fbricon got rejected there, what now?

**Comment by fbricon** [comment]
I'm currently touching the javadoc rendering code in jdt.ls, so I'll see where the problem is then.

**Comment by Nightenom** [comment]
This seems to be working in latest versions
