### ISSUE TITLE
java format on type not working

### ISSUE THREAD

**Issue by AvinashChowdary** [redhat-developer/vscode-java#3396]
[formatOnType setting is not working, formatOnSave works]

##### Environment
- Operating System: Mac os Ventura 13.6
- JDK version: 17
- Visual Studio Code version: 1.84.2
- Java extension version: 1.24.0

##### Steps To Reproduce
1. Enable format on type `"editor.formatOnType": true,`
2. Create a line break in any java statement, cursor beings at the first index of line instead of 2 tabs indentation.

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Line break returns to beginning of the line
```
public String print() {
    return String.format("Value of a: {} and b:{}", 
    a, b);
}
```

##### Expected Result
Line break should start after 2 tabs
```
public String print() {
    return String.format("Value of a: {} and b:{}", 
            a, b);
}
```

##### Additional Informations
Attached a video where the formatting triggers when the file is saved but it should also work when creating a line break while typing.

https://github.com/redhat-developer/vscode-java/assets/8617833/de8032c6-3cb4-4a89-ac1c-1178cedf5fe0

**Comment by rgrunber** [comment]
I don't think we currently do anything with the setting `editor.formatOnType`. It does come from VS Code so I agree that we should probably have our functionality check that setting. We currently have `java.format.onType.enabled` (should be enabled by default) but according to it's description, it's mainly meant for the formatting of semicolon and curly braces. It does mention carriage return as well, but I'm not really finding a case where that does anything interesting.

**Comment by rgrunber** [comment]
For better support, I think we need to look at adopting https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/fe10342ac9a664fb8438fb203eb76cce6ab97e99/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/text/java/JavaAutoIndentStrategy.java . Would be worth looking at how https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2710 was done (which is based on a different class but maybe similar API)
