### ISSUE TITLE
Option to stop the extension from modifying imports on save/format

### ISSUE THREAD

**Issue by WillsterJohnson** [redhat-developer/vscode-java#3399]
This extension keeps modifying my imports either by ordering them differently or by switching into or out of `*` imports. ***I Do Not Want It To Touch My Imports. Ever.***

##### Environment
- Operating System: MacOS 13.6.1
- JDK version: openjdk 17.0.8.1
- Visual Studio Code version: 1.84.2
- Java extension version: 1.24.0

##### Steps To Reproduce
1. Use imported classes and members
2. Save the file
3. Observe the extension modifying imports

##### Current Result

The imports are modified.

##### Expected Result

There should be a configuration option which completely prevents modifying imports.

The star thresholds are not a solution; I am the one to determine whether I use a star import, not some arbitrary number.

Setting import order such that it is 'anything goes' is also not a solution; I want auto-added imports to continue to make a best guess at where to go, however I do not want existing imports to be reordered.

**Comment by snjeza** [comment]
@WillsterJohnson Could you show your `settings.json` and  `<your_project>/.settings/org.eclipse.jdt.core.prefs`?
