### ISSUE TITLE
Improved support for textmate definition for kotlin dsl

### ISSUE THREAD

**Issue by per-steinar** [redhat-developer/vscode-java#3403]
I've made some improvements to the Kotlin grammar based on the official documentation and created a PR in the buildship repo.
It has been siting there for a month. Is there any interest in me porting the content of the PR? 

See: https://github.com/eclipse/buildship/pull/1273

**Comment by fbricon** [comment]
Sure, feel free to open a PR for https://github.com/redhat-developer/vscode-java/blob/master/language-support/kotlin/kotlin.tmLanguage.json
