### ISSUE TITLE
Make the server status a normal status bar item

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#3416]
#### Problem

Currently the server status is put inside the language status. The main problem of that is, user cannot see the server status unless user opens a java relate file. This experience is not ideal since the server status is hidden when the user is, for example, viewing the setting page.

#### Solution
Information like language level and project type can still be hosted by the language status bar, but put the server status as a general status bar item.

**Comment by IllusionMH** [comment]
But now it's either user hides status and there's no way to easy switch from light mode, or this status showed for totally unrelated files. Can it be setting where to show it?
