### ISSUE TITLE
Intellisense cannot resolve dependencies for files under a custom source directory

### ISSUE THREAD

**Issue by littleaj** [redhat-developer/vscode-java#342]
I have a gradle project with a custom source directory _/project/src/**integrationTest**_. Dependencies for these sources are defined using a custom configuration (I followed [this tutorial](https://www.petrikainulainen.net/programming/gradle/getting-started-with-gradle-integration-testing/)). However, the types in the dependencies cannot be resolved by Intellisense. 

It still finds the default classes in rt.jar, just not any of the declared dependencies.

Is there a way to help the plugin find the dependency jars for the custom source directory?
If not, let's call this a feature request :)

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0_144
- Visual Studio Code version: 1.17.2
- Java extension version: 0.12.0
- Gradle version: 4.1

##### Steps To Reproduce
1. Create a gradle project
2. Create a custom sourceSet and configuration in build.gradle (as seen in the aforementioned tutorial)
3. Add a dependency to the custom configuration, e.g. `integrationTestCompile 'junit:junit:4.12'`
4. Create a `.java` file in the custom source directory and try to use the dependency.
5. See squiggles

##### Current Result
Packages and types in dependency jars cannot be resolved by intellisense if the `java` file is under a custom source directory. 

##### Expected Result
Intellisense should be able to resolve dependencies for files under custom source directories, just like `src/main` or `src/test` does with 'compile' and 'testCompile' dependency declarations.

##### Additional Informations
* The project still compiles and runs without any problems.
* One difference from the tutorial (but I did it both ways and it didn't make a difference).
My sourceSets are defined as such:
```
sourceSets {
  integrationTest {
    java {
      srcDir file('src/integrationTest/java')
    }
    resources.srcDir file('src/integrationTest/resources')
  }
}
```

**Comment by fbricon** [comment]
@littleaj can you please setup a test project reproducing the issue? It'll be faster to investigate

**Comment by littleaj** [comment]
This recreates the issue: https://github.com/littleaj/vsc_sense_recreate

Also, I found an interesting case: when _testCompile_ and _integrationTestCompile_ both depended on 'junit', intellisense could resolve the dependency in both source directories, _src/test/main_ and _src/integrationTest/main_.

**Comment by snjeza** [comment]
This is the Eclipse Buildship issue. It can also be reproduced in Eclipse.

**Comment by snjeza** [comment]
See https://github.com/eclipse/buildship/issues/605#issuecomment-341342391
