### ISSUE TITLE
Cannot import gradle project: Could not fetch model of type 'GradleSourceSets' using connection to Gradle distribution 

### ISSUE THREAD

**Issue by planetf1** [redhat-developer/vscode-java#3423]
[provide a description of the issue]

##### Environment
- Operating System: macOS Sonoma 14.2
- JDK version:
```
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode)
```
- Visual Studio Code version: 
```
Version: 1.85.0-insider
Commit: 182f5125f2f8a8469e9dac4ed4795b804671bf7d
Date: 2023-12-07T21:22:47.329Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
```
- Java extension version: v1.26.2023120808

##### Steps To Reproduce
1. `git clone https://github.com/odpi/egeria`
2. `cd egeria`
3. `code-insiders .`
4. In vscode switch to Java profile, ensure the 'extension pack for java' is all installed & up to date. 
5. ensure jdk for extension, and for build is set to the temurin jdk above
6. click on a java file
6. reload window to make sure everything is fresh

Note that under the output for the extension

[Please attach a sample project reproducing the error]
See github ref above. This is a large project, but any pointers welcome

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
tbd after initially raising

##### Current Result
Note that under the output for the extension
```
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Dec 08, 2023 11:58:36 AM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
Dec 08, 2023 11:58:36 AM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
[Error - 12:00:44] 8 Dec 2023, 12:00:44 Initialization failed 
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: org.gradle.tooling.BuildException: Could not fetch model of type 'GradleSourceSets' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.1.1-bin.zip'.
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: org.gradle.tooling.BuildException: Could not fetch model of type 'GradleSourceSets' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.1.1-bin.zip'.
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at com.microsoft.gradle.bs.importer.GradleBuildServerProjectImporter.importToWorkspace(GradleBuildServerProjectImporter.java:171)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:162)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:124)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:260)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: org.gradle.tooling.BuildException: Could not fetch model of type 'GradleSourceSets' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.1.1-bin.zip'.
```

This log continues and is posted as a gist https://gist.github.com/planetf1/d99113908a244775ef47abee73b0bc24

##### Expected Result

Extension can build java project

##### Additional Informations

Project builds fine at command line ie `./gradlew build`
Project imports and builds fine in Jetbrains IntelliJ 2023.3

Project has 329 subprojects, 874000 lines of code, across around 7750 files

Aside: I was a co-founder of this project, am no longer working on it, but have been transitioning to vscode and wanted to try a familiar but large java codebase to see how usable vscode was for java development

**Comment by planetf1** [comment]
Just to add, I do see there are deprecation warnings, but these are not errors. They are warning of features being used in the build with gradle v8 that will stop working in v9

**Comment by fbricon** [comment]
Can you try with [vscode-gradle](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle). Make sure `java.gradle.buildServer.enabled` is `on`

**Comment by fbricon** [comment]
my bad I see you already have it, from the stacktrace. 
- can you report this issue at https://github.com/microsoft/vscode-gradle/issues?
- can you try with `java.gradle.buildServer.enabled`:`off` ?

**Comment by chklump** [comment]
I have exactly the same problem. It started when there was the change to using the gradle build server. It vanishes when I set `java.gradle.buildServer.enabled:off` (however that has other problems).

Therefore I'd like to know: Was there a solution for you @planetf1 or is there a followup issue in the vscode-gradle repo?

Thanks

**Comment by planetf1** [comment]
I don;t have any more info at the moment. I was doing full time java dev until 6 months ago, with intelliJ. I've only done a few test compiles after a job change, but will aim to take a long again with vscode

**Comment by RrkwM** [comment]
I'm having the same issue. This is the only webpage I've found. Do you find any solution now?

**Comment by hannesroth88** [comment]
Try removing cache and some temps on your user dir. 

i did this on mac:
`close VS Code
cd your.project
rm -rf .gradle .project .settings .classpath
rm -rf ~/.cache/tooling
rm -rf ~/.gradle/wrapper
code .`

Now getting other errors tough

**Comment by akojimsg** [comment]
> Can you try with [vscode-gradle](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle). Make sure `java.gradle.buildServer.enabled` is `on`

I had to switch from pre-release to release version
