### ISSUE TITLE
can we make java.cleanup.actionsOnSave trigger manually with a keyboard shortcut?

### ISSUE THREAD

**Issue by moapu** [redhat-developer/vscode-java#3424]
when i want to make a small change to a repo, java.cleanup.actionsOnSave automatically changes lot of the code i wish not to change.
however, I do want this feature available when i really do need it. 

following are the ones i have set right now:

```
  "java.cleanup.actionsOnSave": [
    "addOverride",
    "stringConcatToTextBlock",
    "addFinalModifier",
    "lambdaExpressionFromAnonymousClass",
    "switchExpression",
    "tryWithResource",
    "lambdaExpression"
  ],
```

##### Environment
- Operating System: Windows 10
- JDK version: 17
- Visual Studio Code version: 1.84.1
- Java extension version: v1.25.1

##### Steps To Reproduce
1. open a repo
2. change something slightly 
3. notice it will change lot of the code you are not working with

##### Additional Information
I simply want a way for the actions to be performed with a keyboard shortcut and not on save every time.

**Comment by rgrunber** [comment]
I think this is pretty reasonable. Some code bases may have parts that should not be cleaned up on save, and I don't think VS Code has per-file/folder settings where you could just set ` "java.cleanup.actionsOnSave": []`, and even that isn't as convenient as a keybinding.

This could definitely be done. It's just a matter of whether VS Code provides an existing keybinding we could override, or finding a new one that doesn't clash with anything.

**Comment by moapu** [comment]
if you search for `java.cleanup.actionsOnSave` in command pallette, nothing shows up. meaning there needs to be a command registered first?

**Comment by rgrunber** [comment]
`java.cleanup.actions` will be the new setting to store the list of cleanups to apply. `java.saveActions.cleanup` will be the setting to enable cleanup actions on save. <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>s</kbd> will be the default key binding to activate cleanups (can be configured through the `java.action.doCleanup` command ID)
