### ISSUE TITLE
Plan to upgrade Apache Software Foundation | Commons Lang | 3.8.1

### ISSUE THREAD

**Issue by octopus88888** [redhat-developer/vscode-java#3427]
Any plan to upgrade Apache Software Foundation | Commons Lang | 3.8.1 to latest version?
VAMS marked this as EOL.

**Comment by rgrunber** [comment]
The language server was updated just yesterday. See https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2998#issuecomment-1850929543 . A snapshot of the language server is available at https://download.eclipse.org/jdtls/snapshots/ . The latest vscode-java pre-release should already contain it.

Marking this as closed for now, but feel free to re-open if there's something else you meant.
