### ISSUE TITLE
org.springframework.lang.NonNullApi not supported

### ISSUE THREAD

**Issue by exprassL** [redhat-developer/vscode-java#3431]
Annotation `org.springframework.lang.NonNullApi` is not supported for null analysis.

```
os: win 10 pro
vscode: 1.84.2 (system setup)
redhat.java: v1.25.2023112903
jdk: jdk-17.0.6
springboot: 3.1.2
```

With the method parameter annotated by `org.springframework.lang.NonNull` directly, I got a warning said tha `Null type mismatch: required .... but the provided is null`. It's cool.

But with
```json
"java.compile.nullAnalysis.nonnull": [
    "javax.annotation.Nonnull",
    "org.eclipse.jdt.annotaion.NonNull",
    "org.springframework.lang.NonNull",
    "org.springframework.lang.NonNullApi"
]
``` 
in the user's settings.json, and a `package-info.java` annotated by `org.springframework.lang.NonNullApi`, I got nothing.

When I placed `"org.springframework.lang.NonNullApi"` at the first line in the configuration json like this
```json
"java.compile.nullAnalysis.nonnull": [
    "org.springframework.lang.NonNullApi",
    "javax.annotation.Nonnull",
    "org.eclipse.jdt.annotaion.NonNull",
    "org.springframework.lang.NonNull"
]
```
, I also got nothing about null analysis, but an error from `package-info.java` file saying `The nullness annotation 'NonNullApi' is not applicable at this location` instead.

**Comment by fbricon** [comment]
Can you please provide a sample project? Without knowing anything about the NonNullApi, I'd infer from the name it has a specific behaviour, different from NonNull, and JDT doesn't know anything about that specific behaviour.

**Comment by fbricon** [comment]
@martinlippert is this something STS should take care of?

**Comment by exprassL** [comment]
> Can you please provide a sample project? Without knowing anything about the NonNullApi, I'd infer from the name it has a specific behaviour, different from NonNull, and JDT doesn't know anything about that specific behaviour.

@fbricon the project is accessible only on company's intranet. After posting this issue, I tried IDEA and found it worked well.

**Comment by exprassL** [comment]
> Can you please provide a sample project? Without knowing anything about the NonNullApi, I'd infer from the name it has a specific behaviour, different from NonNull, and JDT doesn't know anything about that specific behaviour.

Sorry to forget telling that I had JDK17 installed and used.

**Comment by exprassL** [comment]
@snjeza It's working. Thanks.

**Comment by martinlippert** [comment]
> @martinlippert is this something STS should take care of?

Hey @fbricon, not sure what exactly the Spring Tools could/should do here. Do you have anything concrete in mind?
