### ISSUE TITLE
Error: Could not find or load main class Main Caused by: java.lang.NoClassDefFoundError: me/dragon/Main (wrong name: Main)

### ISSUE THREAD

**Issue by Nerd10000** [redhat-developer/vscode-java#3437]
[provide a description of the issue]

##### Environment
- Operating System: windwos 10
- JDK version: 17.0.8.1
- Visual Studio Code version:
- Java extension version:  Maven for Java (v0.43.0)

##### Steps To Reproduce
1. [step 1] Just make a new Maven prject
2. [step 2] And run it
![image](https://github.com/redhat-developer/vscode-java/assets/96385928/2e0c890e-347e-41ee-abd2-5de2b6feaa01)

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Expected Result

A jar file 

##### Additional Informations
-

**Comment by jdneo** [comment]
If it cannot run from maven command line, that's an indicator that something is wrong with your project.

**Comment by Nerd10000** [comment]
okay thanks

**Comment by jdneo** [comment]
Closing but feel free to ask questions when if there are problems about the extensions.
