### ISSUE TITLE
compiler shows incorrect error for inner static on record

### ISSUE THREAD

**Issue by robaho** [redhat-developer/vscode-java#3443]
Code like:

```java
public class X {
    public record SomeRecord() {
        public static final int SOMEVALUE = 1;
    }
}
```
is valid.

The compiler reports

`Illegal modifier for parameter SOMEVALUE; only final is permitted Java(67109220)`

The code compiles fine with javac.

**Comment by snjeza** [comment]
@robaho I can't reproduce the issue. Could you try the latest VS Code Java 1.25.1 or Pre-Release?

**Comment by robaho** [comment]
I am running the pre-release. The JDK is JavaSE-17.

It is strange, if I perform a build from the command line - the error goes away. Then as soon as a make a change to the file in the editor (add a space then remove it), I get the error in the editor:

![image](https://github.com/redhat-developer/vscode-java/assets/4958833/f6a9cd6c-7fc3-4930-a184-5b9e3cfacf92)

**Comment by robaho** [comment]
If I close the tab, then reopen, the error is gone. As soon as I use File->Save it will reappear.

**Comment by snjeza** [comment]
I still can't reproduce the issue.
@robaho Could you create a simple project?

**Comment by robaho** [comment]
Btw, this is a gradle based project. I will try and create a simple project shortly.

**Comment by robaho** [comment]
I did some more investigation on this. I created a new project and saw the same error. After using 'clean workspace' the error went away and did not return.

I went back to my original project and did the same and the error disappeared and I could not make it happen again with the save.

So at this point I cannot reliably reproduce and there is a 'workaround/fix' to remove it, so you can close the issue. I am fairly certain there is a bug lurking though...
