### ISSUE TITLE
Make custom pasting less eager

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#3444]
In JBang VS Code, I have my own [paste provider to convert Maven XML dependencies into JBang `//DEPS`](https://github.com/jbangdev/jbang-vscode/pull/60). Now that vscode-java provides its own provider, it takes over and makes the experience less pleasant:

<img width="669" alt="Screenshot 2023-12-25 at 18 05 25" src="https://github.com/redhat-developer/vscode-java/assets/148698/08ae1d55-2e4a-4551-86ad-b9d229ef1998">

IMO, vscode-java should be more clever and do not return a DocumentPasteEdit if no special handling is necessary (eg. pasted content is not java, or pasting site is not within String quotes.

**Comment by rgrunber** [comment]
Interestingly, the vscode-java contributed paste edit isn't always present. If I paste xml within the type declaration, the vscode-java paste edit is never created. However, when done in the import area, it is. I think this might actually be a bug in the language server.

`null` is returned when pasting within the type declaration :

https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/2b7857b1fbc3ff35f7c126c6e7dadb53665977e9/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java#L336-L338

the original paste text is returned in a lot of "failing" cases, or if we're not within a type declaration :

https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/2b7857b1fbc3ff35f7c126c6e7dadb53665977e9/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/PasteEventHandler.java#L286-L301

So we probably need to try returning `null` everywhere, and that probably fixes it.

https://github.com/redhat-developer/vscode-java/blob/b8fd15872fabe5e5b22c73730dd47021f601c40a/src/pasteEventHandler.ts#L103-L104

The client is already set up to ignore the handler if the delegate doesn't return anything.

**Comment by rgrunber** [comment]
@hopehadfield , interested in this ? Should be easy to fix, but just requires a bit of verifying the desired behaviour.

**Comment by rgrunber** [comment]
@hopehadfield , are you able to reproduce the behaviours described in :

https://github.com/redhat-developer/vscode-java/issues/3445, https://github.com/redhat-developer/vscode-java/issues/3236, https://github.com/redhat-developer/vscode-java/issues/3237, https://github.com/redhat-developer/vscode-java/issues/3164 . Does this fix them ?

**Comment by hopehadfield** [comment]
@rgrunber I could reproduce everything except for the issues relating to multi-cursor paste (those seemed to work fine for me even without this PR). This fixed all the other issues for me though!
