### ISSUE TITLE
.classpath file does not contain additional srcDir entry when it does not exist on the fs (yet)

### ISSUE THREAD

**Issue by rubin55** [redhat-developer/vscode-java#345]
When you have additional java source code directories, you can specify this as a sourceSet like so:

```
sourceSets {
    main {
        java {
            outputDir = file("$buildDir/classes/java/main")
            srcDir generatedJava
            // srcDirs += generatedJava // Also works
        }
    }
}
```

When you're dealing with generated code, that code is often generated within the build directory. However, that directory might not exist yet (maybe you just checked out without building or maybe you ran a `gradle clean`)

When the folder does not exist yet, it does not end up in the .classpath file as a src entry. For example, if you generate your code in the directory `build/generated` that has to show up in the .classpath as: `<classpathentry kind="src" path="build/generated"/>`. 

As a workaround, you can make sure you generate the code before you open vscode, but that is error-prone and not very intuitive.

### Steps to Reproduce
1. Checkout a Java project with generated code (`git clone git@github.com:rubin55/reproducer.git`)
2. Open a terminal and cd into the project directory
3. Make sure there's no build artifacts yet (`rm -rf build`)
4. Make sure you have no project files at all yet (`rm -rf .gradle .settings .vscode .classpath .project`)
5. Make sure you have no associated project workspace in `AppData/Roaming/Code/User/workspaceStorage` (not sure where that directory is on Linux or macOS)
6. Open VS Code and open the project directory folder
7. Wait while VS code and vscode-java do their thang, creating the .classpath file. Open it and observe there's no src entry in there for `build/generated`
8. Go to the terminal and generate the code (`gradle generate`) and observe that the generated code folder now exists.
9. Do an edit on build.gradle which will make VS Code prompt that a build file was modified. Click "Now".
10. Observe that the .classpath now *does* contain a src entry for build/generated

 
##### Environment
macOS 10.12.6
Java 8 r144
VS Code 1.17.2
VS Code Java 0.12.0

**Comment by rubin55** [comment]
I noticed also, that when the generated source folder does not exist yet, it will not be added to the .classpath file as a src folder at all. When I do a gradle generate (resulting in that folder being created, with the generated .java files in it), doing F1 -> Java: Update project configuration does *not* update the .classpath file either. *However*, doing a bogus edit on the build.gradle and clicking "Now" in the resultant "Detected change to classpath settings, do you want to update the configuration" *does* update the .classpath file with the relevant src entry.

**Comment by fbricon** [comment]
@rubin55 can you please setup a test project reproducing the issue?

**Comment by rubin55** [comment]
Hey @fbricon, sure, let me get to it!

**Comment by snjeza** [comment]
> Checkout a Java project with generated code (git clone git@github.com:rubin55/reproducer.git)

I can't build this project. 

<details>
<summary>gradle build</summary>
```
./gradlew clean build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'reproducer'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve net.persgroep.gradle:persgroep-gradle-plugins:1.5.0.
     Required by:
         project :
      > Could not resolve net.persgroep.gradle:persgroep-gradle-plugins:1.5.0.
         > Could not get resource 'https://unreachable.site/net/persgroep/gradle/persgroep-gradle-plugins/1.5.0/persgroep-gradle-plugins-1.5.0.pom'.
            > Could not GET 'https://unreachable.site/net/persgroep/gradle/persgroep-gradle-plugins/1.5.0/persgroep-gradle-plugins-1.5.0.pom'.
               > Connect to unreachable.site:443 [unreachable.site/64.98.145.30] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```
</details>

@rubin55 could you try to add the following to build.gradle:

```
eclipse {
	classpath {
		file.beforeMerged { classpath ->
			mkdir generatedJava
		}
	}
}
```

**Comment by rubin55** [comment]
Hi @snjeza , I tried the above and this works around the issue; the initially generated .classpath file now contains an entry for `build/generated`.
