### ISSUE TITLE
Improvement global status item in VS Code Java to be more user friendly

### ISSUE THREAD

**Issue by nickzhums** [redhat-developer/vscode-java#3473]
Here to suggest two improvements of global status item for VS Code Java

Item 1 - Currently, the tooltip of global status item in VS Code Java shows "ServiceReady". This is a bit generic to the user and does not indicate it is relevant to the Java language server. Suggest to update the tooltip to **"Java Language Server Ready".**

![image](https://github.com/redhat-developer/vscode-java/assets/56864335/cc78ce6d-8a2b-4742-b203-cbc646e0a38c)

Item 2 - We are not recording the telemetry of how many users has clicked this icon, thus unable the analyze the usage and effectiveness. Therefore to suggest record the telemetry

**Comment by rgrunber** [comment]
https://github.com/redhat-developer/vscode-java/blob/bd61dc65e8c77ea23504bd4cbc279bf3e62c2235/src/serverStatusBarProvider.ts#L54-L58

Seems like the tooptip could just use a better value.

Another consideration is whether we can do something about https://github.com/redhat-developer/vscode-java/issues/3416#issuecomment-1898859440 . Are there instances where it makes sense to hide (`StatusBarItem.hide()`) it or are we committed to always showing it if some project has triggered the import.

**Comment by nickzhums** [comment]
Yes, for #1 we can just update the tooltip.
