### ISSUE TITLE
Problems with highlighting with some folder names 

### ISSUE THREAD

**Issue by Edsonbs** [redhat-developer/vscode-java#3477]
When you open a folder whose name contains any accent mark (´), the extension don't shows you highlighted errors.

##### **Environment**
- Operating System: Sonoma 14.2.1
- Java version "21.0.1" 2023-10-17 LTS
- Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
- Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
- Visual Studio Code version: 1.85.2
- Java extension version: 1.26.0

##### **Steps To Reproduce**
1. Create a folder with the name "Programación" _(where do you want, for example in the Desktop)_.
2. Open this folder with Visual Studio Code.
3. Create a java file, name it as you want, for example "a.java".
4. Press any random key to make a code mistake.
You will see that you cannot see the code marked with a error in the code writer, just at the bottom in the error counter.
5. Now rename the folder "Programación" to "Programacion", without the accent mark "´".
6. Reopen the folder with Visual Studio Code.
Now the code have the errors marked in the code.

##### **Additional Informations**
If the file has a name with accent mark, and the folder name without accent mark, you will not have problems, the code will highlight the code without errors.
This problem doesnt exist in Windows _(or I don't have it)_.

##### **Folder with the thow names**
[Archivo.zip](https://github.com/redhat-developer/vscode-java/files/14055800/Archivo.zip)

_(Sorry for my english, im not native english speaker.)_

**Comment by fbricon** [comment]
I can't reproduce on Sonoma 14.2.1
<img width="1904" alt="Screenshot 2024-01-25 at 18 59 15" src="https://github.com/redhat-developer/vscode-java/assets/148698/a7ae65d2-9d5a-4c07-82d0-bcfa63f69eeb">

**Comment by Edsonbs** [comment]
Wow, then it's probably because I have to configure something... But I don't find the cause of that problem...
Then I will close this issue.
Thanks for your time!
