### ISSUE TITLE
Language Support for Java couldn't create connection to server since 1.27

### ISSUE THREAD

**Issue by LeducNic** [redhat-developer/vscode-java#3484]
Hello,

     Since yesterday, my Language Support for Java was updated to 1.27 and I get the message:
Language Support for Java (Syntax Server) client: couldn't create connection to server

##### Environment
- MacOS 10.15
- JDK version: 14.0.1
- Visual Studio Code version: 1.86
- Java extension version: 1.27

##### Steps To Reproduce
1. Open a directory containing Java code with no build tool
2. Pop-up that says the Java server cannot be started

##### Current Result
Java not working

**Comment by testforstephen** [comment]
Do you see any additional error logs for this? You can use the command "**F1 -> Java: Open All Log Files**" to get the logs.

**Comment by LeducNic** [comment]
The folowing message repeats on output terminal:
objc[53522]: CLASS: class 'KeyWindow' 0x113dea680 small method list 0x113de4c68 is not in immutable memory
[Info  - 08:21:50] Connection to server got closed. Server will restart.
false
[Error - 08:21:50] Language Support for Java (Syntax Server) client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
objc[53540]: CLASS: class 'KeyWindow' 0x10a659680 small method list 0x10a653c68 is not in immutable memory
[Error - 08:21:51] Client Language Support for Java (Syntax Server): connection to server is erroring. Shutting down server.
[Error - 08:21:51] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at c.shutdown (/Users/hexabit/.vscode/extensions/redhat.java-1.27.0-darwin-x64/dist/extension.js:2:1160123)
	at c.stop (/Users/hexabit/.vscode/extensions/redhat.java-1.27.0-darwin-x64/dist/extension.js:2:1159704)
	at c.stop (/Users/hexabit/.vscode/extensions/redhat.java-1.27.0-darwin-x64/dist/extension.js:2:1325654)
	at c.stop (/Users/hexabit/.vscode/extensions/redhat.java-1.27.0-darwin-x64/dist/extension.js:2:884596)
	at c.handleConnectionError (/Users/hexabit/.vscode/extensions/redhat.java-1.27.0-darwin-x64/dist/extension.js:2:1166209)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 08:21:51] Language Support for Java (Syntax Server) client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 08:21:51] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Error - 08:21:51] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 08:21:51] Connection to server got closed. Server will restart.
false
.... Above messages repeats until ...
[Error - 08:21:52] Connection to server got closed. Server will not be restarted.


And I get this in the logs:
!ENTRY org.eclipse.jdt.ls.core 1 0 2024-02-04 08:21:44.939
!MESSAGE >> shutdown

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-02-04 08:21:44.953
!MESSAGE >> exit

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-02-04 08:21:45.059
!MESSAGE Shutdown received... waking up main thread

!ENTRY org.eclipse.jdt.ls.core 1 0 2024-02-04 08:21:45.070
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is stopping:

**Comment by roojay520** [comment]
<img width="459" alt="image" src="https://github.com/redhat-developer/vscode-java/assets/11495164/a2e6a601-9d59-49b0-b6ec-6cacd7f73665">

[client.log.2024-02-05.txt](https://github.com/redhat-developer/vscode-java/files/14159375/client.log.2024-02-05.txt)

**Comment by testforstephen** [comment]
> objc[89232]: CLASS: class 'KeyWindow' 0x1081ea680 small method list 0x1081e4c68 is not in immutable memory

This error happens in both your machines, this seems to be a macOS specific issue. Thanks for sharing the logs. @roojay520 and @LeducNic

@roojay520 What's your macOS version?

@rgrunber Our data shows that the crash rate for macOS has risen in version 1.27.0. Looks like macOS version got a regression in 1.27.0.

**Comment by testforstephen** [comment]
> objc[89232]: CLASS: class 'KeyWindow' 0x1081ea680 small method list 0x1081e4c68 is not in immutable memory

This error seems not thrown from Java code, my initial suspicion is that the embedded jre 17 in Java extension is incompatible with your x64 macOS. I don't have an x64 Macbook to test it, could you try to use a local jdk17+ via changing the vscode setting `java.jdt.ls.java.home` to launch java extension? @LeducNic @roojay520

**Comment by rgrunber** [comment]
We did go from 17.0.9 ( https://download.eclipse.org/justj/jres/17/downloads/latest/../20231028_0547/org.eclipse.justj.openjdk.hotspot.jre.full.stripped-17.0.9-macosx-x86_64.tar.gz ) -> 17.0.10 ( https://download.eclipse.org/justj/jres/17/downloads/latest/../20240120_0921/org.eclipse.justj.openjdk.hotspot.jre.full.stripped-17.0.10-macosx-x86_64.tar.gz ) in the latest release. Another thing to try is whether the 17.0.9 works without issue as the local JDK with `java.jdt.ls.java.home`.

**Comment by LeducNic** [comment]
I tried to put the 17.0.9 binaries in the 17.0.10 folder of the 1.27 version and I still have the same problem.
I also tried to delete all the content of the 1.27 folder and replace for the 1.26 content, but I think I need to modify some files to make it working, because I still have the same problem...

**Comment by LeducNic** [comment]
After further investigation, if I run manually the command line to start the server, it seems that the problem is :
org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.900.v20240129-1338.jar (v1.2.800.v20231003-1442 in 1.26)
If I copy this file from 1.27 to 1.26, the error appear: 
"objc[67049]: CLASS: class 'KeyWindow' 0x118a60680 small method list 0x118a5ac68 is not in immutable memory"

**Comment by rgrunber** [comment]
> After further investigation, if I run manually the command line to start the server, it seems that the problem is : org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.900.v20240129-1338.jar (v1.2.800.v20231003-1442 in 1.26) If I copy this file from 1.27 to 1.26, the error appear: "objc[67049]: CLASS: class 'KeyWindow' 0x118a60680 small method list 0x118a5ac68 is not in immutable memory"

How exactly did you copy `org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.900.v20240129-1338.jar` to `org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.800.v20231003-1442.jar`. Did you replace (overwrite the existing one) or add it in ?

**Comment by LeducNic** [comment]
I installed 1.26, then 1.27.  After that I deleted org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.900.v20240129-1338.jar in the 1.27 and copied org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.800.v20231003-1442.jar from 1.26 in the same directory and after restarting VSCode I don't have the error anymore.

**Comment by rgrunber** [comment]
If you look inside `config_mac/config.ini` folder (at the same level as the `plugins/` folder that would contain all these jars there's a reference to `reference\:file\:org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.900.v20240129-1338/@4`, which is how the necessary bundles to start the language server are located. If those weren't touched at all, it seems like maybe that equinox.launcher fragment bundle wasn't detected at all.

What happens if you try doing the same steps you described above, but didn't attempt to place the "1.26" version of the bundle into the folder ? Does the error also go away in this case ?

**Comment by LeducNic** [comment]
I have the 1.2.900 and 1.2.80 in the 1.27 folder.  If I rename the file 1.2.900 to 1.2.700 (< 1.2.800) I don't have the error.  Then if I rename 1.2.800 to 1.2.600, the error is back, so it seems to load the more recent version.
- 1.2.900 + 1.2.800 -> ERROR
- 1.2.800 + 1.2.700 (rename of 900) -> no error
- 1.2.700 (rename 900) + 1.2.600 (rename 800) -> ERROR

**Comment by rgrunber** [comment]
Looks like the binary within `org.eclipse.equinox.launcher.cocoa.macosx.x86_64` recently started being compiled against macOS SDK version 11.

As for the behaviour you were seeing above, yes I think it definitely tries to load the more recent version :` https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.equinox.launcher/src/org/eclipse/equinox/launcher/Main.java#L1001 .

As a workaround, can you try to take an installation of 1.27.0, and just remove the `org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.900.v20240129-1338.jar` . As an extra step, can you also remove the following files (if they exist) :

- `$HOME/.config/Code/User/globalStorage/redhat.java/1.27.0/config_mac/org.eclipse.equinox.launcher/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.900.v20240129-1338/eclipse_11900.so`
- `$HOME/.config/Code/User/globalStorage/redhat.java/1.27.0/config_ss_mac/org.eclipse.equinox.launcher/org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.900.v20240129-1338/eclipse_11900.so`

Then just start VS Code as you would normally and see if Java support works as expected.

**Comment by rgrunber** [comment]
If someone having this issue could try https://github.com/rgrunber/vscode-java/releases/download/v1.28.0/java-darwin-x64-1.28.0-134.vsix and let me know if that solves the problem for them, that would be helpful.

**Comment by LeducNic** [comment]
I tried to remove org.eclipse.equinox.launcher.cocoa.macosx.x86_64_1.2.900.v20240129-1338.jar and I have installed 1.28 from your link.  There were no error with the two solutions.  I can open my no built tool project (open folder) and I can run my programs without the Java server crash error.

Question: What is the purpose of org.eclipse.equinox.launcher in VSCode?

**Comment by rgrunber** [comment]
See https://eclipse.dev/equinox/framework/ & https://wiki.eclipse.org/Equinox_Launcher for some info. The launcher is used to start the runtime inside which the language server operates.

You can read my comment at https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3051#issue-2127470995 . We need the launcher, but the platform specific fragments may not necessarily be required.
