### ISSUE TITLE
Separation of shared configuration and IDE project metadata

### ISSUE THREAD

**Issue by lmerynda** [redhat-developer/vscode-java#3486]
In our project we use $project_path/.settings/org.eclipse.jdt.core.prefs to store formatting configuration which everyone shares to achieve common style. This file is checked-in into the repo. It happens from time to time during some interactions that the content of this file will be updated for one reason or another (TODO ignore, compiler version, etc.) which we don't want to share. Why would we hardcode the compiler version here instead of setting it up in our buildsystem (gradle). How can we achieve a separation of configurations so that we can share formatting settings (and potentially some more), while making sure this file will not be updated automatically by tools or actions such as preference change, user's manual change, project import etc.

For example I've just did a clean of my project workspace because it became corrupted and suddenly this config file has received following content in addition to our formatting setup

eclipse.preferences.version=1
org.eclipse.jdt.core.classpath.outputOverlappingAnotherSource=ignore
org.eclipse.jdt.core.compiler.codegen.targetPlatform=17
org.eclipse.jdt.core.compiler.compliance=17
org.eclipse.jdt.core.compiler.source=17

 
##### Environment
- Operating System: Windows + Docker based dev container
- JDK version: OpenJDK17
- Visual Studio Code version: 1.86
- Java extension version: v1.27.0

**Comment by rgrunber** [comment]
Looks like you mentioned your project is Gradle based. You can create a file at the root of your project :

**`.vscode/settings.json`**
```json
{
  "java.settings.url": ".vscode/settings.prefs"
}
```

**`.vscode/settings.prefs`**
```
...
...
Place your format/java preferences here
...
...
```

Another option is to use `java.format.settings.url` as explained at https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings . If you then generated an Eclipse-style format file, you could always reference that one.

**Comment by lmerynda** [comment]
That looks exactly like what we need, thanks i will play with it during next few days and provide feedback. Should we close it and reopen if need arise?

**Comment by lmerynda** [comment]
everything seems to work as I'd expect it to, thanks!
