### ISSUE TITLE
Syntax highlighting broken on import containing upper cased letters

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#351]
Try creating a java file with a package declaration containing upper cased letters, such as : 
`package org.gradle.apiImpl`

Capital letters have a different colour:
<img width="263" alt="screen shot 2017-10-31 at 4 10 54 pm" src="https://user-images.githubusercontent.com/148698/32246734-5379eb80-be56-11e7-9a3e-f997d5d0f875.png">

**Comment by fbricon** [comment]
Looks like a textmate bundle issue though, the same thing looks good in textmate itself. Maybe caused by a stale bundle in upstream vscode, Although I tested with the lates Insiders build supposedly embedding a newer bundle.

@snjeza can you check please?

**Comment by snjeza** [comment]
It works properly with Microsoft/vscode#36708

**Comment by snjeza** [comment]
@fbricon I have created the branch - https://github.com/snjeza/vscode-java/tree/textmate that overrides the VS Code Java syntax highlighting and uses the original textmate syntax highlighting - https://github.com/textmate/java.tmbundle.

**Comment by fbricon** [comment]
@snjeza any chance you can fix the upstream bundle instead? https://github.com/atom/language-java/blob/master/grammars/java.cson

**Comment by snjeza** [comment]
@fbricon Will try.

**Comment by snjeza** [comment]
See https://github.com/atom/language-java/pull/141 and https://github.com/atom/language-java/issues/140

You can test the PR using the https://github.com/snjeza/vscode-java/tree/issue-351 branch.

**Comment by fbricon** [comment]
@snjeza will vscode be able to override the atom settings, as described in https://github.com/atom/language-java/issues/140#issuecomment-392744666?

**Comment by snjeza** [comment]
I suppose it can't be used in VS Code because VS Code uses json.
cc @aeschli

**Comment by aeschli** [comment]
If I understand this right, the Atom Java grammar emits scope `invalid.deprecated.package_name_not_lowercase.java` when it sees an uppercase package.
It's up to the color theme to decide what color to give this. Probably all theme's give everything that starts with `invalid` the red color.

You either have to convince all theme authors to set that scope to the regular package color or you can tell users to do that themselves in the 'editor.colorCustomizations` setting:
```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "invalid.deprecated.package_name_not_lowercase.java",
                "settings": {
                    "foreground": "#d4d4d4"
                }
            }
        ]
    },
```
Obvisouly that's not cool as `#d4d4d4` depends on your color theme.

So either we live with it or we switch to a different grammar.

**Comment by aeschli** [comment]
I'm happy to switch to a different grammar if you recommend me one. It can be of any format (json,cson,tmLanguage,pList)...

**Comment by snjeza** [comment]
@aeschli Could you just remove lines
```
,
{
        "match": "[A-Z]+",
        "name": "invalid.deprecated.package_name_not_lowercase.java"
 }
```
in ./extensions/java/syntaxes/java.tmLanguage.json
Neither Eclipse nor IntelliJ IDEA highlights it.

**Comment by fbricon** [comment]
This is partially fixed with the new semantic highlighting support in vscode-java 0.61.0. Requires `"java.semanticHighlighting.enabled": true` in settings.json. Without semantic highlighting, the Textmate grammar is still broken.
