### ISSUE TITLE
Autocompletion overwrites following characters

### ISSUE THREAD

**Issue by fly1n** [redhat-developer/vscode-java#352]
Autocompletion overwrites following characters

##### Environment
- Operating System: Windows 10 Pro (64 bits)
- JDK version: JDK8_144, JDK8_151, , JDK8_152, OpenJdk8_144
- Visual Studio Code version: 1.17.2
- Java extension version: 0.12.0

##### Steps To Reproduce
1. [step 1] Type "\<Integer\>"
2. [step 2] Put cursor before "\<Integer\>", Type "Array", waiting for autocompletion to show "ArrayList". Select "ArrayList", several characters of the following "\<Integer\>" will be overwriten.

This bug can be easily reproduced on all java files.

##### Current Result
Sometimes "ArrayListInteger\>", sometimes "ArrayListeger\>", sometimes "ArrayList\<Integer\>"
##### Expected Result
"ArrayList\<Integer\>"

**Comment by fbricon** [comment]
This works fine in Eclipse, so definitely a bug in jdt.ls side

**Comment by fly1n** [comment]
Is this bug fixed in 0.13.0? I still have this bug.

**Comment by fbricon** [comment]
Yes it's supposed to be fixed. Can you still reproduce this issue consistently?

**Comment by fly1n** [comment]
Yes. I tried several times. This bug still appear consistently. I am using OpenJDK8_151 now.

**Comment by fbricon** [comment]
@fly1n  please set `java.trace.server` to `verbose` in VS Code's preferences, so we can trace messages exchanged between the server and VSCode. Then you can attach your VSCode logs (see Language Support for Java in the  Output view)

**Comment by fly1n** [comment]
[vscode_log.txt](https://github.com/redhat-developer/vscode-java/files/1454240/vscode_log.txt)

**Comment by snjeza** [comment]
@fbricon it seems that a timeout of 1 sec sometimes isn't enough.

@fly1n could you try the following:

- type Array
- when VS Code shows the ArrayList completion, wait for a few seconds
- apply completion

**Comment by fly1n** [comment]
I know that this bug does not happen when I wait for few seconds, but you can't expect every user to wait for few seconds before autocompletion, right?

**Comment by snjeza** [comment]
@fly1n Right. I just wanted to check if a timeout is the cause of the issue because I can't reproduce it.

@fbricon will we increase a timeout?

**Comment by fly1n** [comment]
Sorry, I thought this does not happen after waiting for few seconds but did not really test it. I test it again for few times, it happens even after I wait for about 10 seconds. I also found another behavior.
In my project, when I type "LSR" before "()", the expected autocompletion is "LSRNIC", apart from the case that autocompletion sometimes overwrites following "()", the autocompletion itself is not consistent as it sometimes ends with "LSRNIC(parent))", sometimes ends with "LSRNIC)" (overwrites one character "("), sometimes "LSRNIC" (completely overwrites "()").

**Comment by fly1n** [comment]
Sorry, I thought this does not happen after waiting for few seconds but did not really test it. I test it again for few times, it happens even after I wait for about 10 seconds. I also found another behavior.
In my project, when I type "LSR" before "()", the expected autocompletion is "LSRNIC", apart from the case that autocompletion sometimes overwrites following "()", the autocompletion itself is not consistent as it sometimes ends with "LSRNIC(parent))", sometimes ends with "LSRNIC)" (overwrites one character "("), sometimes "LSRNIC" (completely overwrites "()").

**Comment by fly1n** [comment]
Sorry, I thought this does not happen after waiting for few seconds but did not really test it. I test it again for few times, it happens even after I wait for about 10 seconds. I also found another behavior.
In my project, when I type "LSR" before "()", the expected autocompletion is "LSRNIC", apart from the case that autocompletion sometimes overwrites following "()", the autocompletion itself is not consistent as it sometimes ends with "LSRNIC(parent))", sometimes ends with "LSRNIC)" (overwrites one character "("), sometimes "LSRNIC" (completely overwrites "()").

**Comment by fly1n** [comment]
Sorry, I thought this does not happen after waiting for few seconds but did not really test it. I test it again for few times, it happens even after I wait for about 10 seconds. I also found another behavior.
In my project, when I type "LSR" before "()", the expected autocompletion is "LSRNIC", apart from the case that autocompletion sometimes overwrites following "()", the autocompletion itself is not consistent as it sometimes ends with "LSRNIC(parent))", sometimes ends with "LSRNIC)" (overwrites one character "("), sometimes "LSRNIC" (completely overwrites "()").

**Comment by snjeza** [comment]
I still can't reproduce the issue with VS Code Java 0.13.0. Please take a look at https://www.screencast.com/t/vTKvleEJcvk

**Comment by fly1n** [comment]
I tried to use the same file as you, and this bug did not happen in that file. I can send you my project. Since it is my course project, I do not want to upload it to github, can you give me your email please?

**Comment by snjeza** [comment]
snjezana.peco@redhat.com

**Comment by fbricon** [comment]
I've tried very hard to autocomplete as fast as I can (definitely sub second)  and can't reproduce it either.

**Comment by snjeza** [comment]
@fly1n try to reinstall the VS Code Java LS extension. It is possible that you are using an older version.

**Comment by fly1n** [comment]
I reinstalled the whole VS code with only Java extension, this bug still appears.

**Comment by fly1n** [comment]
Can you try to just type lower case "ls" before "()", and then select the first autocompletion ("LSR"). This setting is able to reproduce the bug in my side.

**Comment by snjeza** [comment]
@fly1n Could you check your VS Code Java LS version?

![vscode](https://user-images.githubusercontent.com/388609/32626918-04ad294e-c591-11e7-8790-2cde1a2fabee.png)

**Comment by fly1n** [comment]
See this: https://www.screencast.com/t/7s73x82XKb, it is 0.13.0.

**Comment by snjeza** [comment]
@fly1n could you disable other extensions?

**Comment by fly1n** [comment]
https://www.screencast.com/t/aKkFvziNcJt2
I reinstalled VS Code 1.18.0 with only Java LS 0.14.0.

**Comment by snjeza** [comment]
@fly1n could you try with https://drive.google.com/open?id=1nckes1kPJrj791B0KYzv2E0kgEgq_Kj7 ?

**Comment by fly1n** [comment]
Unfortunately the bug still happens.

**Comment by snjeza** [comment]
@fly1n I suppose you have a very fast machine. What hardware are you using?
Could you try to reproduce the issue using https://drive.google.com/open?id=1WZJ8hXd3QuRpAkfLJo0X_uft70LpyRcp ?

**Comment by fly1n** [comment]
Cool! This version works for me. Now I do not have that bug.

**Comment by fly1n** [comment]
This bug happens much less after I use your newest version, but it still happens few times when I wrote code. So, I think this solution is still not a radical one.

**Comment by snjeza** [comment]
@fly1n could you test https://drive.google.com/open?id=1eG0KB3OmbYYSs6Rl_HwDcCPDqK_tuNL5

**Comment by fly1n** [comment]
I used the newest one for one day. It seems that this bug is complete resolved in the newest version.

**Comment by fbricon** [comment]
with @snjeza's fix, not only is autocompletion more robust, it's also now super fast!
