### ISSUE TITLE
JavaSE-22 Runtime is not compatible

### ISSUE THREAD

**Issue by rongxin-liu** [redhat-developer/vscode-java#3553]
I'm getting an error message in Codespace: "Invalid runtime for JavaSE-22: Runtime at '/opt/jdk/' is incompatible with the 'JavaSE-22' environment."

I have specified the correct path to my jdk in settings.json, and my current JDK runtime is JavaSE-22.

##### Environment
- Operating System: Ubuntu 22.04
- JDK version: openjdk 22 2024-03-19
- Visual Studio Code version: 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6)
- Java extension version: 

##### Steps To Reproduce
1. Install OpenJDK SE 22 at /opt/jdk
2. Apply this setting to setting.json:
```json
	"java.configuration.runtimes": [
		{
			"default": true,
			"name": "JavaSE-22",
			"path": "/opt/jdk/"
		}
	],
```

##### Current Result

RedHat Java Language Support extension showing errors:
```
Invalid runtime for JavaSE-22: Runtime at '/opt/jdk/' is not compatible with the 'JavaSE-22' environment.
```

![Screenshot 2024-03-29 at 00 18 19](https://github.com/redhat-developer/vscode-java/assets/10591665/73760b45-3f76-4113-93dd-dcbc122da21f)

##### Expected Result
No error.

**Comment by fbricon** [comment]
you need the pre-release build of vscode-java

**Comment by logonoff** [comment]
/close

this should have been fixed in https://github.com/redhat-developer/vscode-java/pull/3545, if not please open another issue :)
