### ISSUE TITLE
`java.util.List.*` in "java.completion.favoriteStaticMembers" has no effect on completion

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#3564]
As I commented in https://github.com/redhat-developer/vscode-java/issues/1386#issuecomment-2038376575:

For some reason `java.util.List.*` doesn't work

> "java.completion.favoriteStaticMembers": [
>     "java.util.List.*",
> ]
<img width="562" alt="Screenshot 2024-04-05 at 00 44 26" src="https://github.com/redhat-developer/vscode-java/assets/148698/05078818-31d2-40a8-afa4-e426e78c3162">

but `java.util.List.of` does:

> "java.completion.favoriteStaticMembers": [
>         "java.util.List.of",
>         ...
>     ]

<img width="554" alt="Screenshot 2024-04-05 at 00 34 46" src="https://github.com/redhat-developer/vscode-java/assets/148698/2fcc2a22-aa44-4c3b-91d1-841dc4d08362">

**Comment by snjeza** [comment]
This is an upstream jdt.core issue. https://github.com/eclipse-jdt/eclipse.jdt.core/commit/7b4acd1440f0e7c171cc93a86cb5529cff828ab4 fixes it
We have to update https://download.eclipse.org/jdtls/jdt-core-incubator/snapshots/

**Comment by rgrunber** [comment]
Thanks for the info @snjeza . I'll do the update.
