### ISSUE TITLE
Option to switch build tool after initial import of mixed gradle/maven project

### ISSUE THREAD

**Issue by FieteO** [redhat-developer/vscode-java#3567]
When opening a project for the first time, the user is presented with a dialog to choose between maven or gradle when more than one build tool is present.
Correct me if I am wrong, but afterwards there is no easy way to switch to the other build tool.

##### Environment
- Operating System: Ubuntu 23.10
- JDK version: openjdk version "17.0.10" 2024-01-16
- Visual Studio Code version: 1.88.0
- Java extension version: 1.29.0

##### Steps To Reproduce
1. Select the build tool when opening the project for the first time
2. ??

[Please attach a sample project reproducing the error](https://github.com/moderneinc/rewrite-recipe-starter)

P.S Only tangentially related: The Language Support for Java Output is printing the following error when opening [the project](https://github.com/moderneinc/rewrite-recipe-starter) using maven:
```
[Error - 9:33:05 PM] Apr 8, 2024, 9:33:05 PM Error occured while building workspace. Details: 
 message: The project was not built since its build path is incomplete. Cannot find the class file for de.danielbechler.diff.ObjectDiffer. Fix the build path then try building this project; code: 0; resource: /home/ubu/development/oss/rewrite-recipe-starter;
 message: The type de.danielbechler.diff.ObjectDiffer cannot be resolved. It is indirectly referenced from required type org.openrewrite.TreeVisitor; code: 16777563; resource: /home/ubu/development/oss/rewrite-recipe-starter/src/main/java/com/yourorg/AppendToReleaseNotes.java; line: 1
```
Is that an issue with a faulty project setup for maven in the openrewrite project or perhaps an error on the language support side?
It is compiling fine with running maven and gradle from the command line and when choosing gradle as the build tool

**Comment by FieteO** [comment]
Okay, generally changing the build tool works when setting either one of the
```
"java.import.gradle.enabled": false,
"java.import.maven.enabled": true
```
settings to `true` or `false` and then do a `Java: Clean Language Server Workspace`. Just reloading the window for instance is not enough to change it.

In terms of making this more accessible, maybe the `Type` in `Java: Configure Runtimes` could be made editable similar to how the Java version can be changed there:
![image](https://github.com/redhat-developer/vscode-java/assets/41323592/a77d4524-9433-4196-8f06-ed7fa51bbfb7)

**Comment by rgrunber** [comment]
I guess https://github.com/microsoft/vscode-java-pack/blob/main/src/java-runtime/index.ts could be updated to modify the active build tool for the particular workspace. @testforstephen , thoughts on this improvement ?

**Comment by testforstephen** [comment]
Pls note that `Configure Runtime for Projects` page is purely nodejs UI thing, no any Java logic. If we want to open the ability to reimport the workspace with different build tool there, this definitely requires language server to provide the command to do that.

Anyway, I think when you clean the language server workspace, Java extension should prompt and ask you to select the build tool again before importing mixed build tool workspace. If this is not the behavior, then it's a bug in vscode-java extension.

**Comment by rgrunber** [comment]
`Java: Clean Language Server Workspace` should clear the saved build tool selection now.
