### ISSUE TITLE
Java string paste not auto escape

### ISSUE THREAD

**Issue by AYiXi** [redhat-developer/vscode-java#3568]
after update, paste auto escape funtion is not working

Before Update:
String s = "{\\"a\\": 1}";

After Update:
String s = "{"a": 1}";

// my settings.json
{
    "editor.pasteAs.enabled": true,
    "editor.pasteAs.showPasteSelector": "afterPaste",
}

**Comment by rgrunber** [comment]
I noticed that the language server is sending the correct, escaped content, but the client just isn't applying it.

https://github.com/redhat-developer/vscode-java/blob/e578b506363f50d4798e1d2c02b76727dedcb314/src/pasteEventHandler.ts#L64

https://github.com/microsoft/vscode/commit/091987d9431154a3624ba20bc1d6de65d71d6472#diff-b553efc31b13377c3b4765704b0e0a681d7489d1cb819194f327a589def055c8L40-R85

Looks like the API was updated for 1.88.0.

**Comment by rgrunber** [comment]
This should be fixed in the next pre-release. Thank-you for filing this!
