### ISSUE TITLE
Semantic highlighting for lambdas

### ISSUE THREAD

**Issue by Phoenix-Starlight** [redhat-developer/vscode-java#3574]
Can we be able to distinguish between lambdas capturing a variable and the usage of parameters declared by the lambda? I'd like this to be able to color them differently for semantic highlighting.
```java
int i = 0;
list.forEach(
  item ->
  System.out.println(i + item.toString()); // Be able to color the i differently
);
```

**Comment by rgrunber** [comment]
Makes sense. I would actually go further, and say the highlighting doesn't distinguish between class fields and other variables. For example, Eclipse clearly does this :

**VS Code Java**
![image](https://github.com/redhat-developer/vscode-java/assets/1417342/d20d167e-ee47-4f93-94f6-389582de30bd)


**Eclipse JDT**
![image](https://github.com/redhat-developer/vscode-java/assets/1417342/b2fae09f-3551-480e-801d-9e2b804f0f7b)

**Comment by testforstephen** [comment]
If you use the command "**Developer: Inspect Editor Tokens and Scopes**" to inspect the token type, you can see that we already assign different semantic token types for them. For the field, its semantic token type is **property**, and for the variable, its semantic token type is **variable**.  It's the color theme that's responsible for rendering the color highlighting.

A workaround for you is to customize the semantic highlighting color in the settings.json by yourself.

```json
"editor.semanticTokenColorCustomizations": {
        "[Default Light Modern]": {
            "rules": {
                "property": "#9089f4"
            }
        }
    }
```

![image](https://github.com/redhat-developer/vscode-java/assets/14052197/ee285936-7123-4e9f-8adb-74df88bd503d)

**Comment by rgrunber** [comment]
Thanks for looking into this!

In fact, even the lambda parameter has a semantic token type of **parameter**, so this can all be fixed with something like :

```json
"editor.semanticTokenColorCustomizations": {
        "[Default Light Modern]": {
            "rules": {
                "property": "#9089f4",
                "parameter": "#9089f4"
            }
        }
    }
```

![Screenshot from 2024-04-16 10-19-14](https://github.com/redhat-developer/vscode-java/assets/1417342/db6be280-91c7-4d95-8970-8d0d29e6ac1a)


@Phoenix-Starlight , let us know if this works for you. It would have to be configured per-theme. See https://code.visualstudio.com/docs/getstarted/themes#_editor-semantic-highlighting .

**Comment by rgrunber** [comment]
Closing this for now as it's mainly an issue with the themes provided, and there is a way to configure.

**Comment by Phoenix-Starlight** [comment]
Hi, I'm back again. Another case is
```java
public bar(Foo foo) {
  pack(() -> foo);
}
```
This captures the parameter foo, but there is no way to distinguish this.
