### ISSUE TITLE
How can I setup classpaths on win so that vscode won't warn me about incomplete classpath in my java project created by eclipse

### ISSUE THREAD

**Issue by ZZYSonny** [redhat-developer/vscode-java#358]
##### Environment
- Operating System: Win10 16299.19
- JDK version: Java SE Development kit 8 update 152
- Visual Studio Code version: 1.17.2
- Java extension version: 0.13.0

##### Steps To Reproduce
1. create a project through eclipse, add .vscode folder inside
2. open any of .java file

##### Current Result
I get classpath warning on Windows but not on Mac with the same project.
 I didn't ignore the warning in my settings. 
##### Expected Result
get no warning without set ignore in settings and get full feature related to project.
##### Additional Informations

I have also set up "JDK_HOME","JAVA_HOME","CLASSPATH" in environment variables. And here's my settings.
My sample project here [VSCode.zip](https://github.com/redhat-developer/vscode-java/files/1444057/VSCode.zip)

![image](https://user-images.githubusercontent.com/28442838/32415005-086b5d20-c26d-11e7-837f-385865057945.png)
![image](https://user-images.githubusercontent.com/28442838/32415008-13b569f0-c26d-11e7-9482-f723dd2989c3.png)
![image](https://user-images.githubusercontent.com/28442838/32415010-1c139e96-c26d-11e7-9e44-b357436e87c4.png)
![image](https://user-images.githubusercontent.com/28442838/32415011-1ff21de4-c26d-11e7-8f42-04ad695ed163.png)
![image](https://user-images.githubusercontent.com/28442838/32415012-24b9f23e-c26d-11e7-9215-e1e1cf6bf4b3.png)

**Comment by fbricon** [comment]
Can't reproduce on my Mac. Whether I open the project folder or call `code src/Main.java`, the folder is opened as expected. When simply opening src/Main.java from the Code UI (no other folder opened) then VS Code opens the file as a standalone java file, displays the warning. That's expected.

@snjeza can you check on Windows please?

@ZZYSonny one thing you can try is to [clean the workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory) and then reopen the folder in VS Code.

**Comment by snjeza** [comment]
@fbricon I can't reproduce the issue on Windows 7.

**Comment by ZZYSonny** [comment]
I tried clean the workspace directory but the issue remains.
When I move my project to other places, everything goes alright.
Thank you for your help.
