### ISSUE TITLE
Move method refactoring caused syntax errors due to calling privatization methods

### ISSUE THREAD

**Issue by DongChunHao** [redhat-developer/vscode-java#3605]
[provide a description of the issue]

##### Environment
Operating System: Windows11
JDK version: 17
Visual Studio Code version: 1.88
Java extension version: 1.29

##### Steps To Reproduce
1. select "callMethod()"
2. click “Refacator-Move method”

class TargetClass {
public void method() {
System.out.println("Method in SourceClass");
}
}

class SourceClass {
TargetClass s;
public void callMethod() {//move method
System.out.println("Calling method in TargetClass");
anotherMethod();
}

private void anotherMethod() {
    System.out.println("Another method in TargetClass");
}
}

refactoring result:

![image](https://github.com/redhat-developer/vscode-java/assets/77560508/a157319d-4c80-4902-a5d8-bbd3214e4937)

**Comment by rgrunber** [comment]
This could be handled together with https://github.com/redhat-developer/vscode-java/issues/3604 so closing in favour of that one.
