### ISSUE TITLE
Move method refactoring causes syntax errors due to dependency on constructors

### ISSUE THREAD

**Issue by DongChunHao** [redhat-developer/vscode-java#3608]
[provide a description of the issue]

##### Environment
Operating System: Windows11
JDK version: 17
Visual Studio Code version: 1.88
Java extension version: 1.29

##### Steps To Reproduce

1. select "methodUsingPrivateConstructor()"
2. click “Refacator-Move method”

public class OriginalClass {
TargetClass c;
private OriginalClass() {
}
public void methodUsingPrivateConstructor() {
OriginalClass instance = new OriginalClass();
}
}
public class TargetClass{

}

refactoring result:
![Uploading image.png…]()

**Comment by rgrunber** [comment]
I would close this in favour of https://github.com/redhat-developer/vscode-java/issues/3607 . Also there would be an error that `The public type TargetClass must be defined in its own file` with the current example, but once it's moved, the issue is as described.
