### ISSUE TITLE
Renaming a field results in naming conflicts with other fields 

### ISSUE THREAD

**Issue by DongChunHao** [redhat-developer/vscode-java#3613]
[provide a description of the issue]

##### Environment
Operating System: Windows11
JDK version: 17
Visual Studio Code version: 1.88
Java extension version: 1.29

##### Steps To Reproduce
1.select "originalField"
2.click “Rename”
3. new name "anotherFinalField"

interface MyAnnotation {
final int originalField = 10;
final int anotherFinalField = 20;
}

Refactoring result:
![image](https://github.com/redhat-developer/vscode-java/assets/77560508/888eca4c-73d4-46cb-bf7b-f4af0e7bdb5e)

**Comment by rgrunber** [comment]
Closing this as well in favour of https://github.com/redhat-developer/vscode-java/issues/3616 .

Basically, renaming any member should do some check for all accessible members from that context.
