### ISSUE TITLE
Should avoid huge numbers of codeAction operations during typing java code, make the code editing experience bad.

### ISSUE THREAD

**Issue by andxu** [redhat-developer/vscode-java#362]
[provide a description of the issue]

##### Environment
- Operating System: windows 10
- JDK version: 1.8
- Visual Studio Code version: 1.17.2
- Java extension version: 0.13.0

##### Steps To Reproduce
1. Open a java project and edit a java file
2. Input 'a' 100 times  on an empty line.

[attach logs]
##### Current Result
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (29)' in 4643ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (32)' in 4002ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (33)' in 3699ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (34)' in 3406ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (35)' in 3118ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (30)' in 4513ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (36)' in 2857ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (37)' in 2517ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (38)' in 2306ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (39)' in 2000ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (40)' in 1644ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (41)' in 1449ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (42)' in 1218ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (31)' in 4175ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (43)' in 949ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (44)' in 775ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (45)' in 385ms.
[Trace - 4:56:57 PM] Received response 'textDocument/codeAction - (46)' in 110ms.
##### Expected Result
A lot of code actions should be avoid since the action is not valid/useful during typing ahead.
##### Additional Informations
![image](https://user-images.githubusercontent.com/17075863/32596784-7e815988-c56f-11e7-8a81-35823e320e7a.png)

**Comment by andxu** [comment]
Should better to use the similar mechanism of debounce like lodash, https://lodash.com/docs/4.17.4#debounce

**Comment by gorkem** [comment]
I am not sure how vscode-java can optimize them The calls to 'textDocument/codeAction' are generated by the vscode itself.

**Comment by fbricon** [comment]
@andxu can you open a ticket in vscode?

**Comment by rgrunber** [comment]
Closing as I think https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction_resolve improved this a lot.
