### ISSUE TITLE
always uses jdk 1.8

### ISSUE THREAD

**Issue by ewof** [redhat-developer/vscode-java#3630]
[provide a description of the issue]

##### Environment
- Operating System: artix
- JDK version: 21/1.8
- Visual Studio Code version: 1.88.1
- Java extension version: 1.30.0

```
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-21",
            "path": "/usr/lib/jvm/java-21-openjdk",
            "default": true
        },
        {
            "name": "JavaSE-17",
            "path": "/usr/lib/jvm/java-17-openjdk",
        }
    ],
    "java.jdt.ls.java.home": "/usr/lib/jvm/java-21-openjdk",
```
JAVA_HOME is set to `/usr/lib/jvm/java-21-openjdk`
and yet i open a project and see
![image](https://github.com/redhat-developer/vscode-java/assets/26354814/7bb99fa4-2f3d-474d-b500-189c75d835ac)
even the pom.xml has `<java.version>17</java.version>` in properties tag

**Comment by ewof** [comment]
i can even symlink /usr/lib/jvm/java-8-openjdk to /usr/lib/jvm/java-21-openjdk and i will see get stuff like "Arrow in case statement supported from Java 14 onwards only"

**Comment by fbricon** [comment]
is ${java.version} actually consumed by your maven-compiler-plugin configuration? (check the output of mvn help:effective-pom in a terminal)

**Comment by ewof** [comment]
ur right, for some reason the release tag was set to 8 not `${java.version}`
everything works now
