### ISSUE TITLE
bug: 🐛 VSCode JLS error when loading project with lot of Maven sub modules

### ISSUE THREAD

**Issue by philippart-s** [redhat-developer/vscode-java#3637]
As discussed here: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Are.20there.20any.20.20VSCode.20users.20to.20develop.20Quarkus.20extensions.3F

When I open the project [quarkus-langchain4j](https://github.com/quarkiverse/quarkus-langchain4j) JLS take a long, long, long time to scan the project (more than 30 minutes) and end with an error and propose to increase the memory.
Even if I set the memory to 32 Go the error occurs.

##### Environment
- Operating System: Mac OS M1 Sonoma 14.3
- JDK version: openjdk 21.0.2 2024-01-16
- Visual Studio Code version: 1.88.1
- Java extension version: 1.30.0

##### Steps To Reproduce
1. clone the repository [quarkus-langchain4j](https://github.com/quarkiverse/quarkus-langchain4j)
2. open the project in VSCode
3. wait JLS scanning the project

[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Error message and project not parsed by JLS

##### Expected Result
No error, scan faster and project usable.

##### Additional Informations
![image](https://github.com/redhat-developer/vscode-java/assets/26224751/70ac9fdb-03de-4a69-9ba3-01a5a824fad0)
[JLS.log](https://github.com/redhat-developer/vscode-java/files/15165771/JLS.log)

**Comment by rgrunber** [comment]
I tried this on Linux and also noticed a good amount of memory consumption around the build phase (less so during project import). Ultimately the project successfully built (-Xmx1G, which is the default) with no errors (just warnings/info), but it did peak at around 850MB. Overall, it finished importing at 3min, and a total of 5min from startup to complete building. 30min seems like it's running out of memory and basically just trashing.

I did notice from the logs you have the Quarkus integration installed as well so I'll try that also. If you disable both the MicroProfile and Quarkus extensions, does project import+build become less slow ?

**Comment by maxandersen** [comment]
I can confirm i simply can't import this project on osx Mac studio. Had to "increase memory" 3-4 times before it stopped crashing almost immediately.

**Comment by philippart-s** [comment]
> I did notice from the logs you have the Quarkus integration installed as well so I'll try that also. If you disable both the MicroProfile and Quarkus extensions, does project import+build become less slow ?

I tried without these extensions and same result.

**Comment by snjeza** [comment]
@philippart-s @maxandersen @rgrunber Could you, please, try [VS Code 1.32.0](https://github.com/snjeza/vscode-test/raw/master/java-1.32.0.vsix)?

**Comment by philippart-s** [comment]
> @philippart-s @maxandersen @rgrunber Could you, please, try [VS Code 1.32.0](https://github.com/snjeza/vscode-test/raw/master/java-1.32.0.vsix)?

What is this version?

**Comment by snjeza** [comment]
> What is this version?

This is the specific .vsix that includes this PR - See [Install from a VSIX](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix)

**Comment by philippart-s** [comment]
@snjeza I've just tested 12.32.0 and my project is fully operational (Java ready in the status bar) in less than 2 minutes and it's usable in less than 30 seconds 😉 .
