### ISSUE TITLE
Terminal cannot running

### ISSUE THREAD

**Issue by khesyalv** [redhat-developer/vscode-java#3640]
Type: <b>Bug</b>

The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: -1073741819.

Extension version: 1.30.0
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.34GB free)|
|Process Argv|--crash-reporter-id 5545d7de-ebc0-49b4-89a3-48c0d5798039|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp1r6:30993540
dsvsc020:30976470
pythonait:31006305
jchc7451:30973076
showvideoc:31016891
dsvsc021:30996838
0ee40948:31013168
pythoncenvptcf:31022791
fchga941:31038042
dwnewjupyter:31035176

```

</details>

**Comment by rgrunber** [comment]
According to https://stackoverflow.com/questions/57856292/what-does-error-code-1073741819-mean-when-caused-by-ng-build#comment102150432_57856528 , it's likely an "access denied" error. I don't think this is related to VS Code though.
