### ISSUE TITLE
On startup user settings are sent to the server, instead of workspace settings

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#365]
I have a project with .vscode/settings.json, with "java.trace.server": "verbose". My user settings have "java.trace.server": "messages". When jdt.ls starts, I don't see the verbose output, I can see the logged configuration has `trace={server=messages}`

Tested with vscode-insiders.

@aeschli are you aware of recent changes in vscode preferences handling?

**Comment by aeschli** [comment]
That would be a bug in VSCode, but I'm not able to reproduce.
I use the settings editor to edit the workspace settings, and these seem to win over the user settings.
If you have this reproducible, please file a bug against VSCode with steps.

**Comment by fbricon** [comment]
I can't reproduce today after updating to the latest insiders build. Closing.
