### ISSUE TITLE
Cannot Commit

### ISSUE THREAD

**Issue by stevearchuleta** [redhat-developer/vscode-java#3651]
ADD ISSUE DESCRIPTION HERE

Version: 1.89.0
Commit: 1ea844e541d2aec7aaf7156752ee7f6dbf081c4a
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Embedder: Gitpod

Extension version: 1.29.0

**Comment by jdneo** [comment]
Need more info
