### ISSUE TITLE
Import from code actions doesn't work well after delete java file which is created from code actions

### ISSUE THREAD

**Issue by v-yuyul** [redhat-developer/vscode-java#3663]
##### Environment
- Operating System: Linux/Win
- JDK version: 21.0.2
- Visual Studio Code version: 1.88.1
- Java extension version: 1.31.0

##### Steps To Reproduce
1. Set `"editor.pasteAs.enabled": false` in settings.json
2. Copy and paste `File f = new File("demo.txt");` in java file > Save file > Select 'create class 'File'' from code actions > Delete the new created File.java > import from code actions doesn't work
3. Copy and paste `List<String> stringList = new ArrayList<>();` in java file > Save file > Select 'create class 'List'' from code actions > Delete the new created List.java > import from code actions is missing

##### Current Result
![import not work](https://github.com/redhat-developer/vscode-java/assets/31497677/79065507-199d-4698-acf0-16baa2111cda)
![import is missing](https://github.com/redhat-developer/vscode-java/assets/31497677/2654afc4-4cd9-447c-ad96-be05e0413ceb)

**Comment by rgrunber** [comment]
I'm able to reproduce this and have some idea of how we could go about fixing it. Can you confirm that just typing **anything** (even a space) in the file, restores the expected "Import List (java.util)" ?

This looks like a case of the AST model being stale resulting in some incorrect quick-fix suggestions. Modifying the contents of the file in any ways retriggers some operations that restore things.

**Comment by v-yuyul** [comment]
> Can you confirm that just typing anything (even a space) in the file, restores the expected "Import List (java.util)" ?
Yes, if typing something before select code actions, all work fine.

**Comment by rgrunber** [comment]
Not exactly the same as https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/1918 , but similar. Basically the cached AST model was out of date.
