### ISSUE TITLE
ISSUE: Language Support for Java doesn't work properly, it shows unnecessary error underlines

### ISSUE THREAD

**Issue by ihssmaheel-dev** [redhat-developer/vscode-java#3667]
When opening a Java Spring Boot project in Visual Studio Code, unnecessary error underlines are displayed, despite the code being correct.

##### Environment
- Operating System: Windows 11
- JDK version: 17.0.8
- Visual Studio Code version: 1.89.1
- Java extension version: v1.31.0

##### Steps To Reproduce
1. Open Vscode
2. Open any java spring boot project

cannot find symbol\n  symbol:   variable log\n

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Unnecessary error underlines are shown in the code, indicating errors where there are none.

##### Expected Result
The code should be correctly analyzed, and only real errors should be underlined.

##### Additional Informations
Language support for Java - Log
Jun 04, 2024 4:15:57 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
Jun 04, 2024 4:15:57 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
Jun 04, 2024 4:16:08 PM com.microsoft.java.debug.plugin.internal.JavaDebuggerServerPlugin start
INFO: Starting com.microsoft.java.debug.plugin
Jun 04, 2024 4:16:12 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 4
Jun 04, 2024 4:16:12 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 5
Jun 04, 2024 4:16:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 45
Jun 04, 2024 4:21:19 PM com.microsoft.java.debug.core.UsageDataSession recordInfo
INFO: launch debug info
Jun 04, 2024 4:21:22 PM com.microsoft.java.debug.core.UsageDataSession recordResponse
WARNING: abnormal response

**Comment by fbricon** [comment]
In the initial screenshot you published, the error that was shown was not coming from vscode-java, but likely from another Java extension you installed. I suggest you disable all other vscode extensions but the vscode-java one to figure it out

**Comment by ihssmaheel-dev** [comment]
vscode-java means Language support for java right ?

![Screenshot 2024-06-05 095133](https://github.com/redhat-developer/vscode-java/assets/136784079/ddabd2e8-b3b0-4d48-a1bd-3dadb18567b3)

**Comment by ihssmaheel-dev** [comment]
It is working fine now. I suspect the issue may be related to the 'Java Language Support' extension by George Fraser.

**Comment by sumoondev** [comment]
> It is working fine now. I suspect the issue may be related to the 'Java Language Support' extension by George Fraser.

Thank you this helped a lot, It was due to extension by George Fraser - deleting it solved the uncaused error.
