### ISSUE TITLE
Spring Boot Tools extension may conflict with Java extension

### ISSUE THREAD

**Issue by zjwmiao** [redhat-developer/vscode-java#3669]
##### Environment
- Operating System: Windows 11
- JDK version: 17
- Visual Studio Code version: 1.89.1
- Java extension version: 0.27.0

##### Steps To Reproduce
1. Just open a Java project

##### Current Result
![ext](https://github.com/redhat-developer/vscode-java/assets/95580412/fcaf1445-d81b-4da3-9c70-fc9b98cfa386)
Line 3 and 4, the imports should be green
Line 10, the color of  `args`  is incorrect as well

##### Additional Informations

**Comment by rgrunber** [comment]
I'm assuming you imported this as a Gradle project ? Can you check your problems view and see if there are any errors ?

I tried with a sample project and ran into https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/1743 .

```
Status WARNING: org.eclipse.buildship.core code=4 Synchronize project initial failed due to an unsupported configuration in the referenced Gradle build. org.eclipse.buildship.core.internal.UnsupportedConfigurationException: A project with the name spring-boot already exists.
```

**Comment by zjwmiao** [comment]
> I'm assuming you imported this as a Gradle project ? Can you check your problems view and see if there are any errors ?
> 
> I tried with a sample project and ran into [eclipse-jdtls/eclipse.jdt.ls#1743](https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/1743) .
> 
> ```
> Status WARNING: org.eclipse.buildship.core code=4 Synchronize project initial failed due to an unsupported configuration in the referenced Gradle build. org.eclipse.buildship.core.internal.UnsupportedConfigurationException: A project with the name spring-boot already exists.
> ```

Thanks for your reply, I opened the folder as a maven project, all the functionalities are OK, but the syntax highlighting is weird.

Just found out that the problem is caused by Spring Boot Dashboard extension, the syntax highlight become normal as soon as I disable the Spring Boot Dashboard extension.

**Comment by rgrunber** [comment]
It might be worth filing the issue at https://github.com/spring-projects/sts4/issues if it happens when the VS Code Sprint Boot Tools extension happens to be present. The extension does contribute into the JDT-LS runtime : https://github.com/spring-projects/sts4/blob/d779a8466c4c261d699f49bcbb9dddbe217c0e89/vscode-extensions/vscode-spring-boot/package.json#L31-L38 .

**Comment by zjwmiao** [comment]
> It might be worth filing the issue at https://github.com/spring-projects/sts4/issues if it happens when the VS Code Sprint Boot Tools extension happens to be present. The extension does contribute into the JDT-LS runtime : https://github.com/spring-projects/sts4/blob/d779a8466c4c261d699f49bcbb9dddbe217c0e89/vscode-extensions/vscode-spring-boot/package.json#L31-L38 .

OK, I found a issue about the same problem in their repository. https://github.com/spring-projects/sts4/issues/1249

**Comment by rgrunber** [comment]
Looks like this should be fixed (according to the referenced issue), so I'll close for now.
