### ISSUE TITLE
just lint error

### ISSUE THREAD

**Issue by shenguanjiejie** [redhat-developer/vscode-java#3675]
[provide a description of the issue]

##### Environment
- Operating System: macOS 14.4.1 (23E224)
- JDK version: openjdk 11.0.23
- Visual Studio Code version: 1.90.0 (Universal)
- Java extension version: latest

##### Steps To Reproduce
1. gradle build success
2. lint error

![image](https://github.com/redhat-developer/vscode-java/assets/9425605/4d91b689-bf63-4b18-8b7d-15dd8ee8f750)

I opened this project in IDEA, it's no problem.
but open the same project in vscode. it shows 104 errors.
I can debug in vscode. So it may be a lint error?

**Comment by fbricon** [comment]
Those error messages are not coming from vscode-java. Maybe try disabling/uninstalling [georgewfraser.vscode-javac](https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac) or other competing Java extensions.

**Comment by shenguanjiejie** [comment]
Bingo! Thank you very much!
