### ISSUE TITLE
lineSplit not working

### ISSUE THREAD

**Issue by lenghan4real** [redhat-developer/vscode-java#3683]
lineSplit in formatter not working

##### Environment
- Operating System: MacOS
- JDK version: 8
- Visual Studio Code version: 1.90.2
- Java extension version: v1.32.2024062308 (pre-release)

##### Steps To Reproduce
1. configure org.eclipse.jdt.core.formatter.lineSplit=100 locally in a formatter.xml
2. add "java.format.settings.url": "./formatter.xml", 

##### Current Result
not split at all.
##### Expected Result
line split when 100

**Comment by rgrunber** [comment]
I just tried this out and it seems to be working well What does your directory structure look like ? What does your `formatter.xml` file look like ?

Note that the file given to `java.format.settings.url` (in your case, `formatter.xml`) must be a proper xml file. It should be at the root of your project (to match the path your giving) and look something :

**formatter.xml**
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="13">
  <profile kind="CodeFormatterProfile" name="MyProfile" version="13">
    <setting id="org.eclipse.jdt.core.formatter.lineSplit" value="100"/>
  </profile>
</profiles>
```

and in your project's `.vscode/settings.json`, you should have something like :

```
{
	"java.format.settings.url": "./formatter.xml"
}

```

**Comment by lenghan4real** [comment]
Seems the profile is incorrect. After correction, it works. Thanks a lot.
