### ISSUE TITLE
Support linked correction proposals

### ISSUE THREAD

**Issue by hopehadfield** [redhat-developer/vscode-java#3686]
Add support for linked correction proposals, as is done in Eclipse

![linked-proposal](https://github.com/redhat-developer/vscode-java/assets/115827695/482c0d79-0806-4a4e-88ae-7e607d47075c)

Currently, the same quickfix in vscode-java only gives the first option from the list.

![no-linked-proposal](https://github.com/redhat-developer/vscode-java/assets/115827695/740a8d00-170d-4ab3-84d2-eb66ae997150)

**Comment by rgrunber** [comment]
The LSP Spec now supports [`SnippetTextEdit`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocumentEdit), so this is possible for code actions. You may have some difficulty sending it on the language server side with the existing lsp4j library as [it lacks the necessary classes](https://github.com/eclipse-lsp4j/lsp4j/issues/810), but should be possible to work around that. The language client we use (vscode-languageserver-node) also [seems to now support it](https://github.com/microsoft/vscode-languageserver-node/issues/1414).

**Comment by fbricon** [comment]
as. usual, make sure the client supports it before sending SnippetTextEdits

**Comment by rgrunber** [comment]
An update from @hopehadfield :

![dropdown](https://github.com/user-attachments/assets/5660ddc7-e35d-429a-996b-3a990029b2cb)

**Comment by rgrunber** [comment]
We may have to live with the side effects of https://github.com/microsoft/vscode/issues/63129 since the server-side snippets get an additional indentation.
