### ISSUE TITLE
config "java.import.exclusions" should be a real array not a string

### ISSUE THREAD

**Issue by mojo2012** [redhat-developer/vscode-java#371]
##### Environment
- Visual Studio Code version: 1.18
- Java extension version: 0.14.0

##### Steps To Reproduce
1. open config and edit key *java.import.exclusions*

##### Current Result
Config key *java.import.exclusions* is a string:
```
"java.import.exclusions": "['**/node_modules', '**/.metadata', '**/archetype-resources', '**/eclipsebin']"
```

##### Expected Result
It should be a real array to make it easier to edit.

**Comment by fbricon** [comment]
I think the server also accepts arrays. Have you tried?

**Comment by mojo2012** [comment]
I did that and theni got some gson exceptions and i saw that some folders that i excluded were scanned. But i can recheck.

**Comment by snjeza** [comment]
@mojo2012 you can try the following:

```
 "java.import.exclusions": [
        "**/node_modules",
        "**/.metadata",
        "**/archetype-resources",
    ]
```
