### ISSUE TITLE
Properties files does not show context menu options from other extension

### ISSUE THREAD

**Issue by rH4rtinger** [redhat-developer/vscode-java#3717]
I have another extension, which contributes to VSCode with a command in a context menu in properties files. This element will not be visible, when your extension is active. When I deactivate it, then everything is visible.

##### Environment
- Operating System: Windows 10
- JDK version: openjdk 21.0.3 
- Visual Studio Code version: 1.91.1
- Java extension version: v1.32.0

##### Steps To Reproduce
1. create a dummy extension with the `yo code` command. (See [VSCode documenation](https://code.visualstudio.com/api/get-started/your-first-extension))
2. add this to the `package.json` of your extension:
```json
"contributes": {
  "commands": [
    {
      "command": "foo.helloWorld",
      "title": "Hello World"
    }
  ],
  "menus": {
    "editor/context": [
      {
        "command": "foo.helloWorld",
        "when": "resourceLangId == properties",
        "group": "foo"
      }
    ]
  }
```
3. Debug the extension
4. Open any folder and create a `foo.properties` file.
5. Right click in the file to open the context menu.

##### Current Result
When I open the context menu in my properties-file, I do not see my command.
![image](https://github.com/user-attachments/assets/bad6d30b-5321-4b16-9693-477f794b0785)

##### Expected Result
When I am disabling your extension, then  the "Hello World" command is visible.
![image](https://github.com/user-attachments/assets/b02c2f12-b0f0-4ce7-96e5-06e94de32ca6)

My command should be always visible, even if I have your extension active.

##### Additional Informations
-

**Comment by rgrunber** [comment]
I think this has something to do with the fact that the extension takes ownership of `.properties` files, https://github.com/redhat-developer/vscode-java/blob/7350e2c9b750b5125720fd2aefc85bebf07916c3/package.json#L203-L212 .

You could try : `"when": "resourceLangId == properties || resourceLangId == java-properties"` to see if that solves the issue. See https://github.com/redhat-developer/vscode-java/pull/2636 for more details on why we have this.

**Comment by rH4rtinger** [comment]
It does solve the issue, when I set `"when": "resourceLangId == properties || resourceLangId == java-properties"`.

My context menu is now visible.
