### ISSUE TITLE
Unable to launch Java Project on Mac. Failed to launch debuggee VM. Reason: com.sun.jdi.connect.VMStartException: VM did not connect within given time: 10000 ms

### ISSUE THREAD

**Issue by ZZYSonny** [redhat-developer/vscode-java#372]
Unable to launch Java Project on Mac. 

##### Environment
- Operating System: Mac 10.13.1
- JDK version: 8u152
- Visual Studio Code version: 1.18.1
- Java extension version: Langage 0.14.0 / Debug 0.3.0

##### Steps To Reproduce
1. Simply run the project.

![2017-11-17 9 41 47](https://user-images.githubusercontent.com/28442838/32925273-0316810c-cb7c-11e7-8572-223a9dd5a001.png)
![2017-11-17 9 44 44](https://user-images.githubusercontent.com/28442838/32925274-034b36a4-cb7c-11e7-85e0-e6250ec27e78.png)

##### Current Result
Failed to launch debuggee VM. Reason: com.sun.jdi.connect.VMStartException: VM did not connect within given time: 10000 ms
![2017-11-17 9 41 04](https://user-images.githubusercontent.com/28442838/32925272-02e3f07a-cb7c-11e7-8b47-2157d2bef786.png)
##### Expected Result
Should be able to run and output "HELLOWORLD" in output
##### Additional Informations
Sample Project
[Test.zip](https://github.com/redhat-developer/vscode-java/files/1480822/Test.zip)
This Project can be launched on my Win10

**Comment by fbricon** [comment]
@ZZYSonny you need to open a bug at the [vscode-java-debug issue tracker](https://github.com/Microsoft/vscode-java-debug/issues).
