### ISSUE TITLE
[BUG] When settings.json changed, crash

### ISSUE THREAD

**Issue by AYiXi** [redhat-developer/vscode-java#3727]
My vscode setttings is autosaved
when I change the config, java is crash, but I dont chagne any java conifg

<img width="2418" alt="image" src="https://github.com/user-attachments/assets/3b759972-5c7d-46a8-a0e1-e12ba4fd3792">

<img width="470" alt="image" src="https://github.com/user-attachments/assets/0cbd267f-1a38-494c-a404-68bfe6b91cd2">

**Comment by rgrunber** [comment]
What version of vscode-java were you using here ? Do you have any other extensions installed ?

I wonder if some other extension may have attempted to change a vscode-java setting. The other possibility if you were on the latest pre-release 2 days ago, is that it's somehow related to a change we did in  https://github.com/redhat-developer/vscode-java/commit/bf05afb36fb2ba9a5f6b271e07b805ac09ab57b6#diff-bb57a3bd912abc3ec2e729cb8a743838487677a5517683d0c8913a3619ac296a. Could you keep track of the following settings prior to the crash and then see if they changed after the crash : `java.jdt.ls.java.home`, `java.home`, `java.jdt.ls.vmargs`, `java.server.launchMode`, `java.sharedIndexes.location`, `java.transport`, `java.diagnostic.filter`, `java.import.generatesMetadataFilesAtProjectRoot`.
