### ISSUE TITLE
Code Relevance

### ISSUE THREAD

**Issue by Geeprox** [redhat-developer/vscode-java#373]
##### Environment
- Operating System: Windows 7
- JDK version: 1.8.0_144
- Visual Studio Code version: 1.18.1
- Java extension version: 0.14.0

When I open a Project, I can't use "jump to caller", "jump to reference" or "jump to defination" if they are in a file not opened. Only if I open the destination file can I do these operations. It's very unfriendly for reading code.
I hope I can sync all the project forced in the background.

**Comment by gorkem** [comment]
Sounds like you are using the standalone mode? Do you have a maven or gradle build set for your project?

**Comment by Geeprox** [comment]
Yes, It's a AndroidStudio project with Gradle build set.

**Comment by xqliu** [comment]
I believe that's not support at this time(android project with gradle build set)

**Comment by jdneo** [comment]
Android is partially supported. You can turn it on via `java.jdt.ls.androidSupport.enabled`. Please let us know if this is still an issue.
