### ISSUE TITLE
command 'nbls.java.generate.getter.setter' not found

### ISSUE THREAD

**Issue by tanishay** [redhat-developer/vscode-java#3734]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by jdneo** [comment]
Hi @tanishay, The command name seems like it comes from the netbeans language server, it's not from this project.
