### ISSUE TITLE
Add feature if it doesn't already exists: Disable one Java project from building and reporting compiler errors in VsCode workspace having multiple Java Projects.

### ISSUE THREAD

**Issue by sairaghavak** [redhat-developer/vscode-java#3749]
I have 2 java projects 
- `sb1-maven-java11`
- `sb2-maven-java11 `
under one workspace. 
I have some compiler issues in one of the java project say `sb1-maven-java11` , so I have disabled that project from file explorer using the following setting

```json
"files.exclude": {
        "sb1-maven-java11": true,
 },
```

and also excluded it in files watcher

```json
"files.watcherExclude": {
        "sb1-maven-java11": true,
 },
```

Also disabled under maven setting so that it's not scanned/recognized by maven view
```json
"maven.excludedFolders":  [
  "sb1-maven-java11"
] 
```

But the problem is when I reload the Vscode window, the excluded project is still built during startup by Java language server and the compiler errors are reported under `problems` view.

##### Environment
- Operating System: Linux/Windows
- JDK version: 11
- Visual Studio Code version: 1.92.1
- Java extension version: v1.33.0

##### Steps To Reproduce
1. Open VsCode. Ensure that you have Redhat Java language server installed. Create 2 Java projects. Name it as `A`, `B` or as you wish.
2. Add a bad code line in one of the project say project `A` just to have compiler error. Now, try to exclude `A` as mentioned in my issue description with maven settings and file exclude setting

##### Current Result
The compiler errors in project `A` are reported under problems view though that folder is excluded in project view and maven view. 

##### Expected Result
I think it should be ignored by JavaLanguage Server from building that excluded project and stop reporting the problems(Compiler errors, Warnings) related to that project. 

Or may be if there is any specific setting already to achieve this of ignoring a specific Java project from building could help resolve this  issue.

**Comment by snjeza** [comment]
@sairaghavak You can try the following settings:

```
"java.import.exclusions": [
        "**/node_modules/**",
        "**/.metadata/**",
        "**/archetype-resources/**",
        "**/META-INF/maven/**",
        "**/sb1-maven-java11"
        
    ],
```
and clean the workspace directory:
- Open the command palette (F1)
- select `Java: Clean the Java Language Server Workspace`
- select `Restart and delete` from the confirmation prompt

**Comment by sairaghavak** [comment]
This works. 
Which folder does Java language server workspace cleans?

**Comment by jdneo** [comment]
The cache folder for the language server is cleaned.

And there is another approach you can use when you want to import part of the maven sub-modules.

You can set the setting `java.import.projectSelection` to `manual`. And the trigger the command `Java: import Java Projects into workspace`, and select the folder you want to import. In this way, you do not need to set the `"java.import.exclusions"` in the workspace level.

**Comment by rgrunber** [comment]
Can this be closed now ?

If you ever did want to import the project but just suppress the errors/warnings, we also recently added :

`java.diagnostic.filter`: Specifies a list of file patterns for which matching documents should not have their diagnostics reported (eg. '**/Foo.java').

However, in this case excluding the prompt from import seems like the right aproach.

**Comment by jdneo** [comment]
Close and please leave comment if you have more query
