### ISSUE TITLE
Show decompiled content directly on open .class file

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#3759]
It's a feature request.

#### User case
I downloaded a .jar file, extracted it, and was inspecting class files in vscode (opening the extracted folder as root folder). The decompile functionality worked well. When I switched between different .class files I have to re-click the "Decompile Class File" again to see the content, which created a little bit overhead for me. 
Is it possible that I can see the decompiled content directly (e.g. by turning on a setting)? That would create smoother user experience in this case.

**Comment by rgrunber** [comment]
@JessicaJHee , do you remember if there was any reason why we decided to use a button to activate the decompilation in https://github.com/redhat-developer/vscode-java/pull/2985 ? If I remove it and just triggered the decompilation it seems to work. Seems I could just make a setting for it to skip the button.

**Comment by JessicaJHee** [comment]
@rgrunber I believe it was because there wasn't a way to [make the decompile request](https://github.com/JessicaJHee/vscode-java/blob/2d180d112ce8b3a5e778b5b7f033b0d838e1a3e5/src/javaClassEditor.ts#L58-L64) to `jdt.ls` from the custom editor without using [some event](https://code.visualstudio.com/api/references/vscode-api#Webview) triggered by the button. How were you triggering the decompilation after removing it?

**Comment by rgrunber** [comment]
I just did : 

```diff
$ git diff
diff --git a/src/javaClassEditor.ts b/src/javaClassEditor.ts
index 053593c..22141e9 100644
--- a/src/javaClassEditor.ts
+++ b/src/javaClassEditor.ts
@@ -43,14 +43,10 @@ export class JavaClassEditorProvider implements vscode.CustomReadonlyEditorProvi
                <body>
                        <div class="center">
                                <p>This file is not displayed in the text editor because it is a Java class file. Click here to decompile and open.</p>
-                               <button id="btn"><center>Decompile Class File</center></button>
                        <div>
                        <script nonce="${nonce}">
                                const vscode = acquireVsCodeApi();
-                               document.getElementById("btn").addEventListener("click", decompiled);
-                               function decompiled() {
-                                       vscode.postMessage({ command: 'decompiled' });
-                               }
+                               vscode.postMessage({ command: 'decompiled' });
                        </script>
                </body>
                </html>
```

The page becomes unnecessary, but it does seem to work.

**Comment by JessicaJHee** [comment]
@rgrunber Ahh I see, that might be the case. It does make sense to me to remove the page then, iirc there is a comment at the top of the decompiled file saying it was generated anyways 👍

**Comment by Eskibear** [comment]
> Maybe we did it because we wanted to mimic :

VS Code shows this because showing a binary file with unknown encoding is not helpful in most cases. Here since we are "showing" .class files with well generated content, I don't think we need the extra step.

The only corner case I'm concerning is, if a user indeed wants to view binary content of .class file, we should not block them. I.e. allow them to re-open with a text editor, as below:   (command palette -> View: Re-open Editor with ...)

![image](https://github.com/user-attachments/assets/d4692226-0bae-43c1-a9e7-333fa4200258)

Currently, the page with "Decompile Class File" button can be re-open with text editor, but the page with decompiled content cannot work with re-open, which is mainly because it's a content provider instead of a custom editor I guess.  If that's the case, ideally what I expect is, to show decompiled class file content directly in this custom editor, then we have better user experience and it works smoothly with vscode's custom editor.
