### ISSUE TITLE
Regarding performance issues

### ISSUE THREAD

**Issue by Carson-yy** [redhat-developer/vscode-java#3765]
When I open many project files, probably thousands of Java files, and some of them are very long, up to more than 20,000 lines, the response speed of syntax prompts, parsing, and other functions is very slow.

Are there any ways to improve it?

I tried to increase both -Xmx and -Xms, setting -Xmx to 8G, but it didn't improve the situation.

**Comment by rgrunber** [comment]
Do you mean you have thousands of opened files ? All of them in separate tabs ? Does the situation improve if you only have one large file opened at any given time ?

Do you have any example projects you could share to demonstrate this ?

**Comment by Carson-yy** [comment]
Sorry, this project is private and cannot be made public. It's not a matter of opening thousands of Java files at once; in reality, only 5-6 Java files are opened, but each file contains a large number of lines—some have over 20,000 lines, while others have around 2,000 lines. After working for a while, the response speed of features like intelligent suggestions becomes very slow.

**Comment by Carson-yy** [comment]
> Do you mean you have thousands of opened files ? All of them in separate tabs ? Does the situation improve if you only have one large file opened at any given time ?
> 
> Do you have any example projects you could share to demonstrate this ?

Sorry, this project is private and cannot be made public. It's not a matter of opening thousands of Java files at once; in reality, only 5-6 Java files are opened, but each file contains a large number of lines—some have over 20,000 lines, while others have around 2,000 lines. After working for a while, the response speed of features like intelligent suggestions becomes very slow.
