### ISSUE TITLE
It seems "# Go to Symbol" in Workspace not able to search for Java Methods or Classes

### ISSUE THREAD

**Issue by alexandertsukanov** [redhat-developer/vscode-java#3766]
Hey everyone, it seems that I'm unable to find any Java methods, symbols, or classes when I use the "# symbol command". My expectation is that when I type or search in this manner, I should see the corresponding methods and relevant classes, etc. However, that is not happening.  

##### Environment
- Operating System: macOS 14.16.1
- JDK version: 17
- Visual Studio Code version:  1.91.1
- Java extension version: 1.34.0 (August 29th, 2024)

##### Steps To Reproduce
1. Open any Java project
2. Wait until indexing will finish
3. Try to search for some method or symbol

**Comment by rgrunber** [comment]
You would be able to search for any class in the classpath, but currently only methods declared in the project itself (not libraries), assuming `"java.symbols.includeSourceMethodDeclarations": true`. I just tried it out with 1.93.1 & 1.91.1, on vscode-java 1.34.0, and it seems to be working.

Does the project import successfully without errors ? You should see that the language server is in the ready state in the bottom left corner.

![image](https://github.com/user-attachments/assets/ab7d8b5a-e9dd-4409-a5a2-010c3b1a2ab5)

If you open a Java source file, you should see that a JDK has been configured, based on the project's build settings :

![image](https://github.com/user-attachments/assets/2d818ec1-4271-40eb-8377-a7957c0cb89f)

**Comment by alexandertsukanov** [comment]
Hey, @rgrunber ! 
Thank you very much for your support. It seems the option you provided has worked for me:
"java.symbols.includeSourceMethodDeclarations": true
Thanks!

**Comment by rgrunber** [comment]
For reference, if you wanted to look through all method declarations, even from dependencies of the project, this is a feature I definitely want to have adopted (See https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/1712 ). It's just that we need a particular feature (partial search) so it won't be too slow on larger projects.

**Comment by alexandertsukanov** [comment]
@rgrunber Yes, I find this feature very useful, and I would like to be included within the scope of this plugin.

I also have a question: is it possible to search for classes from JDK or external libraries? If so, could you please advise me how?

**Comment by rgrunber** [comment]
Through the workspace symbol search (command palette `#` prefix), it should already be possible to do this. Do you have a sample project somewhere for which this doesn't work ? Is it a Maven, Gradle, or does is it just a folder with dependencies listed at some location (unmanaged) ?
