### ISSUE TITLE
Renaming or creating a java file requires restart

### ISSUE THREAD

**Issue by Personinblack** [redhat-developer/vscode-java#380]
##### Environment
- Operating System: Arch Linux
- JDK version: jdk8 8u152-1
- Visual Studio Code version: 1.18.1
- Java extension version: 0.14.0

##### Steps To Reproduce
1. Rename or create a java file.
2. Try referring to it inside a class after closing its window.

##### Current Result
Can't refer to that file without restarting the Visual Studio Code or having it open.

https://imgur.com/a/nj24x

**Comment by fbricon** [comment]
I confirm there's a bug there. That's a really weird one.
