### ISSUE TITLE
Automatically add /// on new line when editing Markdown javadoc

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#3801]
When editing Markdown javadoc, it should behave like in Eclipse and automatically add /// on new lines
![Oct-07-2024 10-28-44](https://github.com/user-attachments/assets/216c2657-a2dd-4aac-90d8-83ec5ae062db)

**Comment by mickaelistria** [comment]
That is somethign that is most likely to implement in the java languageConfiguration file.

**Comment by mickaelistria** [comment]
https://github.com/redhat-developer/vscode-java/blob/24147e2bacbebb8183bdc3b7d663e3b5f6206779/language-support/java/language-configuration.json#L3
