### ISSUE TITLE
Feature: Option to control polling time interval (when polling for code changes) squiggly line lag

### ISSUE THREAD

**Issue by ADTC** [redhat-developer/vscode-java#381]
I notice sometimes I'm editing Java code, the code linting lags behind. So assuming I type a line of code like so: `String vscodeJava = null;`, the squiggly lines indicating errors **slowly** go like this (you can see it happening slowly in front of your very eyes long after you typed the whole line out):

    S                         // can't find type
    St                        // can't find type
    Str                       // can't find type
    Stri                      // can't find type
    Strin                     // can't find type
    String                    // missing variable name
    String                    // missing variable name
    String v                  // missing semicolon
    String vs                 // missing semicolon
    String vsc                // missing semicolon
    String vsco               // missing semicolon
    String vscod              // missing semicolon
    String vscode             // missing semicolon
    String vscodeJ            // missing semicolon
    String vscodeJa           // missing semicolon
    String vscodeJav          // missing semicolon
    String vscodeJava         // missing semicolon
    String vscodeJava         // missing semicolon
    String vscodeJava =       // missing value
    String vscodeJava =       // missing value
    String vscodeJava = n     // can't find symbol
    String vscodeJava = nu    // can't find symbol
    String vscodeJava = nul   // can't find symbol
    String vscodeJava = null  // missing semicolon
    String vscodeJava = null; // OK

Or see this GIF:

![vscode-lagging-2](https://user-images.githubusercontent.com/6047296/33330422-d9256e50-d484-11e7-9210-dc7764523573.gif)
_(Thank you to [NickeManarin/ScreenToGif](https://github.com/NickeManarin/ScreenToGif))_

While this could be a bug, I think a feature to control the polling interval would be helpful. So it only polls the code for changes every second or two seconds or so.

**Comment by fbricon** [comment]
[Recent changes](https://github.com/redhat-developer/vscode-java/issues/352#issuecomment-345828292) improved the autocompletion performance.

Please download the most recent `java-<version>.vsix` file from from http://download.jboss.org/jbosstools/jdt.ls/staging/ and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

If it still isn't fast enough, you can change your vscode prefs like:
```
"editor.quickSuggestionsDelay": 500 // or some higher value
```

**Comment by ADTC** [comment]
I think there is a misunderstanding here. I'm not really talking about quick suggestions popup, but rather about the squiggly lines that indicate a warning or error. Are you able to see the GIF animation? See how the squiggly lines lag behind what I'm typing in.

**Comment by ADTC** [comment]
@fbricon Btw, I see these errors in Console (under Language Support for Java). Would they be related to this problem in any way?

[_View the Gist of errors_](https://gist.github.com/ADTC/4315fb310201d342af87d0ef84fb4c3b)

**Comment by fbricon** [comment]
@snjeza ^^?

@ADTC have you tried the CI build? I expect the squiggly-related performance to be improved as part of the autocompletion changes

**Comment by snjeza** [comment]
> [_View the Gist of errors_](https://gist.github.com/ADTC/4315fb310201d342af87d0ef84fb4c3b)

These errors are related to https://github.com/eclipse/eclipse.jdt.ls/issues/369

**Comment by ADTC** [comment]
@fbricon I'm trying the latest build **0.15.0-673**. There is a definite improvement in the squiggly line performance and I'm very happy about it. 😄 It looks like instead of lagging behind (as it did in 0.14.0), now it just appears after a delay of about a second. In 0.14.0 you could _especially_ observe the lag when you hold down Ctrl-Z to undo what you _typed out_ (you had to wait several seconds before the language server catches up to your quick multiple undo), but with this CI build, **no lag at all**. 🙂

**Comment by fbricon** [comment]
Ok, let's close this one as fixed then.
