### ISSUE TITLE
Missing command pallette option: Java: Open Java Formatter Settings with Preview"

### ISSUE THREAD

**Issue by aubreyyan** [redhat-developer/vscode-java#3810]
[provide a description of the issue]

I am trying to use the interactive Java formatting editor. Was this removed?

##### Environment
- Operating System: MacOS Sonoma 14.6.1
- JDK version: openjdk version "17.0.12" 2024-07-16
- Visual Studio Code version: 1.93.0
- Java extension version: 8.01

##### Steps To Reproduce
1. Open Vscode
2. Install this extension
3. Open command pallette
4. Look for "Java: Open Java Formatter Settings with Preview"
5. You won't find it

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
<img width="598" alt="image" src="https://github.com/user-attachments/assets/e1e06522-f688-4773-bbde-eef7c1eba1b1">

##### Expected Result
<img width="767" alt="image" src="https://github.com/user-attachments/assets/aa79541f-b703-4d50-b5fc-17dc2cf914e2">

##### Additional Informations

Visual Code docs directly implicate this extension in supporting java format settings **with preview**

https://code.visualstudio.com/docs/java/java-linting#_editing-formatter-settings

**Comment by testforstephen** [comment]
The formatter preview UI is provided by "Extension Pack for Java" extension, pls install it as well.

![image](https://github.com/user-attachments/assets/5228ae43-eaf1-4801-9c05-50b549cbe459)

**Comment by aubreyyan** [comment]
Extension pack for Java isn’t an extension, it’s a grouping of other extensions. One of which includes maven. My workspace cannot install maven for Java, it is forbidden. So you’re saying I can’t get this feature unless I install Maven for Java extension? I should be able to install whatever subset of the extensions in extension pack I want and still get this feature which is a part of your extension, not any other extensions. Unless you can tell me what extension supports the formatter with preview?

**Comment by testforstephen** [comment]
It's `Extension pack for Java` extension itself that provides the formatter preview feature. If you don't install it, you won't get this feature.
