### ISSUE TITLE
Mark unused method parameters

### ISSUE THREAD

**Issue by MartinBernstorff** [redhat-developer/vscode-java#3819]
```java
package com.test;

class RunnerTester {
    public void main(String[] args) {
        var test = 0;
        return;
    }
}
```

##### Current Result
`test` is marked as unused, but `args` is unmarked.

##### Expected Result
`args` is marked as unused.

**Comment by testforstephen** [comment]
It's ignored by default, you can toggle it on by adding a setting file like below.

- Create a settings file such as `java.prefs`, and add the setting `org.eclipse.jdt.core.compiler.problem.unusedParameter=warning` there.
- Change VS Code settings.json `"java.settings.url": "/absolute/path/to/java.prefs"`

**Comment by MartinBernstorff** [comment]
Thanks a ton!
