### ISSUE TITLE
Import Problem : ..cannot be resolved as a type

### ISSUE THREAD

**Issue by Tistou38** [redhat-developer/vscode-java#3831]
Hi, I'm new to Java and am using Visual Studio Code (VSCode) for my development. I’ve encountered a problem when creating a package named "robot" located in "src/robot". The Java linter indicates that a class I used from the default package (located in "src")  cannot be resolved as a type. I use a makefile to compile my code and I don't use maven or anything else.

Here is the error I have : 
![image](https://github.com/user-attachments/assets/72d04340-10c1-4f7d-83a8-4bab782ee14b)

Here is my project structure : 
![image](https://github.com/user-attachments/assets/2b4b31a7-ea19-4b24-b7da-073ecb196bf2)

##### Environment
- Operating System: WSL Ubuntu 22.04.4 LTS
- JDK version: 23.0.1 
- Visual Studio Code version: 1.94.2
- Java extension version: 0.29.0

[Please attach a sample project reproducing the error]
[Please attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
..cannot be resolved as a type

##### Expected Result 
.

**Comment by fbricon** [comment]
As per the Java Spec, you can't reference classes from the default package, in another package.
See https://stackoverflow.com/a/2193298/753170
