### ISSUE TITLE
Option to set/change the Project SDK from Detected SDKs

### ISSUE THREAD

**Issue by mamilic** [redhat-developer/vscode-java#3857]
Would it be possible to allow users to set or modify the "Project Java SDK" in VS Code? Currently, it seems to be auto-detected. This proposed setting would allow users to select from a dropdown of detected SDKs, with an option to include manually configured SDKs.

Scope and Application:
The configured SDK setting would be applied across all relevant Java-related components within VS Code, such as:

- JDT Language Server (JDTLS)
- VS Code Gradle Extension
- Any other Java-related extensions, where applicable

This setting would primarily impact runtime configurations. For example:
- The Gradle daemon version used for project builds()as sometime the version can not be detected from gradle scripts, as it is dynamic)
- The Java version leveraged by JDTLS for code navigation and browsing (e.g., when exploring standard classes like String)
- Maven and other project dependencies as relevant
Important Note:
This setting should not alter the Java version used by the JDTLS server itself.

Thank you for considering this feature. It would provide users with more flexibility in managing their development environment and streamline project compatibility across different Java SDK versions.

**Comment by mamilic** [comment]
@rgrunber , thanks a lot! Did not know that configuration already exist. This issue can be closed.

**Comment by rgrunber** [comment]
We should do a better job at advertising the various options : https://github.com/redhat-developer/vscode-java?tab=readme-ov-file#supported-vs-code-settings . There's quite a lot there.
