### ISSUE TITLE
Store method parameters in compiled classes

### ISSUE THREAD

**Issue by mozsakalli** [redhat-developer/vscode-java#391]
When using compile on save, compiler doesn't recognize compilerArgs in pom.xml file.

```xml
    <build>
        <plugins> 
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

mvn install compiles correctly and all compiled classes contains parameter name information, but when same classes were compiled by compile on save (incremental) classes don't have parameter name information anymore...

**Comment by fbricon** [comment]
This is a [known issue in m2e](https://bugs.eclipse.org/bugs/show_bug.cgi?id=518218), I've been working on a fix.

In the mean time, you can add or change the following parameter in .project/org.eclipse.jdt.core.prefs: 

> org.eclipse.jdt.core.compiler.codegen.methodParameters=generate

**Comment by fbricon** [comment]
Issue has been fixed upstream. We'll pick up the m2e 1.9 M5 bits with that fix, for the next release.
