### ISSUE TITLE
vscode intellisense failing when 2 jdks are on system, despite env var or java.home

### ISSUE THREAD

**Issue by hrsto** [redhat-developer/vscode-java#392]
There seems to be a clash between vscode and multiple jdks. When having both jdk8 and jdk9, and having set JAVA_HOME to point jdk9 dir AND vscode's user setting java.home to point to jdk9 dir, intellisense fails. Compilation succeeds, can use java 9 features. Below for details.

##### Environment
- Operating System: Win10
- JDK version: 8 and 9
- Visual Studio Code version: latest
- Java extension version: latest

##### Steps To Reproduce
1. Have latest maven and jdk 9.0.1 installed along with jdk 8
2. Set env var and vscode's user setting java.home to point to jdk9 dir
3. Use maven's maven-compiler-plugin
4. <configuration> element accepts <source>, <target>, or <release> tags. We just use <release> tag
5. When <release> is set to 9, the whole intellisense fails. Not even java.lang.String is found
6. Set to <release> 8, intellisense works again, but java 9 features are not recognized
7. When compiling, and doing mvn package, every time the manifest file shows that jdk8 is used, even though we have a working java 9 compiled program with java 9 features
---
8. Uninstall jdk8 from system
9. Now set <release> to 9 and intellisense will work as expected and recognize java 9 features
10. When compiling and packaging, the manifest file will correctly show that java 9 was used

**Comment by yaohaizh** [comment]
I had a similar issue here.  It seems the API JavaRuntime.getDefaultVMInstall() cannot correctly detect the right JVM version here and always pick up the 1.8. @fbricon @gorkem  Any insight here?

**Comment by fbricon** [comment]
I haven't looked but I think, eventually, we might need to be able to pass a list of java installations to the server. 
@snjeza any idea?
