### ISSUE TITLE
"Not point to a JDK" error

### ISSUE THREAD

**Issue by Yi-yi** [redhat-developer/vscode-java#393]
Using vscode as a JAVA editor, programs could be compiled and executed successfully, but there is an error message:
 
![image](https://user-images.githubusercontent.com/12591699/34070476-14f6237c-e2bb-11e7-9b9b-a26aa8984a58.png)

##### Environment
- Operating System: Win10
- JDK version: 1.8.0
- Visual Studio Code version: 1.19
- Java extension version: 0.16.0

##### Steps To Reproduce
Settings in Windows 10 Environment system variables:
![image](https://user-images.githubusercontent.com/12591699/34070496-92eac878-e2bb-11e7-8d5b-50b2b1ffcf1b.png)

Settings in VScode setting:
![image](https://user-images.githubusercontent.com/12591699/34070510-c3a2f9e0-e2bb-11e7-9ea2-798d97a1042c.png)

**Comment by fbricon** [comment]
The Java home is one level above the bin directory. Remove bin/ from your settings
