### ISSUE TITLE
Cannot save file in UTF-8 correctly

### ISSUE THREAD

**Issue by sumbrez** [redhat-developer/vscode-java#394]
Saving UTF-8 file makes non-alphabet char unrecognizable characters.

##### Environment
- Operating System: Windows_NT x64 10.0.16299, **Chinese Home**
- JDK version: 1.8.0_111
- Visual Studio Code version: 1.19.0
- Java extension version: 0.16.0

##### Steps To Reproduce
1. Open a UTF-8 java file having non-alphabet char (e.g., Chinese character) in in VSCode
2. Type/delete any char and save the file

[attach a sample project reproducing the error]
Only such info in server log file
```
!ENTRY org.eclipse.jdt.ls.core 1 0 2017-12-19 09:45:34.091
!MESSAGE >> document/hover

!ENTRY org.eclipse.jdt.ls.core 1 0 2017-12-19 09:45:34.707
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2017-12-19 09:45:34.964
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2017-12-19 09:46:54.920
!MESSAGE >> document/codeAction

!ENTRY org.eclipse.jdt.ls.core 1 0 2017-12-19 09:46:54.921
!MESSAGE >> document/documentHighlight

!ENTRY org.eclipse.jdt.ls.core 1 0 2017-12-19 09:46:55.179
!MESSAGE >> document/codeAction
```

All other extensions are disabled, and if this Java extension is disabled, too, VSCode saves the file correctly.

**Comment by sumbrez** [comment]
In previous verions, this issue didn't occur. But often, when hovering on a method having Java doc, Chinese characters in the doc are also shown as unrecognizable characters on the "suspension window".
However, most of unrecognizable characters saved in the Java file are "�" while ones in suspension window are barely used CJK characters (if the Java file is in correct UTF-8).

(I have already set the file encoding as UTF-8 in both VSCode, and Eclipse (GBK, default))

**Comment by developandplay** [comment]
- Operating System: Microsoft Windows 10 Pro - 10.0.16299 Build 16299
- JDK version: 1.8.0_151
- Visual Studio Code version: 1.19.1
- Java extension version: 0.16.0

I do have the exact same problem. Whenever I try to save a file that includes special German caracters e.g. ä, ö, ü, ß they turn into a "�".

In addition to that when I click on the "UTF-8"-button on the bottom right and choose "save with encoding" and after that "UTF-8" the file does not save at all.

**Comment by silascript** [comment]
+1

**Comment by zhuXunRun** [comment]
+1

**Comment by rsmidt** [comment]
+1
