### ISSUE TITLE
Code autocomplete and reference hint are slow in java JDK 9.0.1 

### ISSUE THREAD

**Issue by khe817** [redhat-developer/vscode-java#398]
Code autocomplete and reference hint are significantly slower (5 to 10 seconds waiting for hints to load) in Java JDK 9.0.1 with maven projects  as compared to previous Java JDK versions (1.7.x, and 1.8.x) (hints are loaded under 1 second). Half of the time, hints don't load at all.

##### Environment
- Operating System: windows 10
- JDK version: 9.0.1
- Visual Studio Code version: 1.19.1
- Java extension version: 0.16.0

##### Additional information
- Maven `pom.xml` configurations:
```
<properties>
	<java.version>9</java.version>
</properties>
```
If `java.version` is set to 1.8 in `pom.xml`, code completion and reference hints work fine.

**Comment by fbricon** [comment]
Performance is indeed abyssmal. We need to check if updating to a newer version of JDT helps or if there's something truly broken in jdt.ls

**Comment by fbricon** [comment]
Seems fixed with the update to Eclipse Photon in the latest jdt.ls builds

**Comment by khe817** [comment]
I updated to the newest released version (0.18.1). The issue is now worse with no hint popping up at all when I type an object and wait for its functions hints to show.

Reference hint, peek definition (Alt+F12), and go to definition (F12) for classes defined in a local project (vs classes from imported package in pom.yml)  also now do not work. An error "No definition" pops instead.

Reference hint, peek definition (Alt+F12), and go to definition (F12) also do not work for java core classes like List, String, ArrayList ...
