### ISSUE TITLE
File saving issues 

### ISSUE THREAD

**Issue by etem** [redhat-developer/vscode-java#404]
Hello, 

I'm getting error message `"Failed to save '<filename>.java': The content on disk is newer. Click on Compare to compare your version with the one on disk."` every few minutes while editing a java file. This happens only when the Language Support for Java(TM) by Red Hat extension is installed and enabled. The opened file is local.
Auto save is enabled with following settings:

>     "files.autoSave": "afterDelay",
>     "files.autoSaveDelay": 200,

##### Environment
- Operating System: Fedora 27
- JDK version: java-1.8.0-openjdk-1:1.8.0.151-1.b12.fc27.x86_64
- Visual Studio Code version: 1.19.1/1.20.0-insider
- Java extension version: 0.16.0

##### Steps To Reproduce
1. Install `Language Support for Java(TM) by Red Hat` extension.
2. Open a .java file and make some changes. 

Sample project attached as .txt file (university java course): 
[Rectangle.txt](https://github.com/redhat-developer/vscode-java/files/1609035/Rectangle.txt)

Logs: 
[VSCodeJava.log](https://github.com/redhat-developer/vscode-java/files/1609027/VSCodeJava.log)
[VSCodeJavaLanguageServer.log](https://github.com/redhat-developer/vscode-java/files/1609028/VSCodeJavaLanguageServer.log)
[VSJavaTrace.txt](https://github.com/redhat-developer/vscode-java/files/1609030/VSJavaTrace.txt)

##### Current Result
Below message appears every few minutes while working on a .java file
![vscodejavaerror](https://user-images.githubusercontent.com/8333647/34642053-e658568c-f315-11e7-93c7-fd6127d87d54.png)

##### Expected Result
Save and autosave should work normally.

**Comment by snjeza** [comment]
I can't reproduce the issue.
Could you attach your settings.json?

**Comment by etem** [comment]
Please find it attached as .txt file. 
[settings.txt](https://github.com/redhat-developer/vscode-java/files/1609184/settings.txt)

**Comment by fbricon** [comment]
@snjeza FYI I can reproduce this issue on my mac

**Comment by fbricon** [comment]
I can't reproduce it constantly though. It seems typing for a while triggers it. My gut feeling is this is a vscode bug though. I think vscode waits for a server response to perform some actions and ends up being confused upon file save. @aeschli can probably chime in here ;-)

**Comment by fbricon** [comment]
@etem with "files.autoSaveDelay": 1000, it seems to behave nicely. Saving more often than that doesn't seem that useful. I don't think you'll see much of a difference increasing the save delay. Anything between 2 and 5sec is probably good enough.

**Comment by etem** [comment]
@fbricon Thank you. I can confirm that the message appears only when typing. I've also reported it to VS Code Microsoft/vscode#41159

**Comment by etem** [comment]
Thanks. I have updated "files.autoSaveDelay" to 5000. The message still appears but not so often - once every 5-10 mins. 
VS code issue id - Microsoft/vscode#41159

**Comment by fbricon** [comment]
I can't reproduce this issue with vscode-java 0.18.1 and vscode 1.19.3. @etem do you still have that problem?

**Comment by etem** [comment]
@fbricon I can't reproduce it either. It seems to be working fine now. Thank you!
