### ISSUE TITLE
Provide an option to disable the 'auto build'

### ISSUE THREAD

**Issue by whmmm** [redhat-developer/vscode-java#406]
When I save the changes,the plugin will be build file ,How can I 
build file with command instead of auto build?

**Comment by fbricon** [comment]
Auto-build can not be disabled at the moment. We enabled it by default so that workspace-wide errors can be reported (eg. removing a public method in one class would cause compilation errors in other files consuming that method).

I guess, for large workspaces, it may make sense to be able to disable autobuild if it negatively impacts performance.

**Comment by fbricon** [comment]
Setting the new `java.autobuild.enabled` preference to false disabled the automatic build.

**Comment by whmmm** [comment]
@fbricon  Thanks a lot ！！！

**Comment by sagarmunjal** [comment]
> Setting the new `java.autobuild.enabled` preference to false disabled the automatic build.
Where can I find this option in the online web editor?

**Comment by fbricon** [comment]
@sagarmunjal which online editor?

**Comment by mxxk** [comment]
After disabling autobuilds via the `java.autobuild.enabled` preference, how does one trigger a manual build through the same mechanism? 🤔 (Meaning, through the Java plugin and not a custom task.)

**Comment by yaohaizh** [comment]
@mxxk  Command "Java: Force Java Compilation"

**Comment by carlosdanielrodriguezortiz40-ctrl** [comment]
Lo que tienes que hacer es un código de una API Y subirlo para que funcione Así como la página que hicimos
 Pero lo que el profe quiere ver en tu código es que tenga un endpoint como lo puedo aser en python

**Comment by carlosdanielrodriguezortiz40-ctrl** [comment]
no me esta dejan con java scrip

**Comment by carlosdanielrodriguezortiz40-ctrl** [comment]
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional

# -----------------------------------------------
# Inicializar la aplicación FastAPI
# -----------------------------------------------
app = FastAPI(
    title="API de Productos 🛒",
    description="API para gestionar productos de una tienda",
    version="1.0.0"
)

# -----------------------------------------------
# Modelo de datos (esquema del producto)
# -----------------------------------------------
class Producto(BaseModel):
    id: int
    nombre: str
    precio: float
    categoria: str
    disponible: bool = True

class ProductoCrear(BaseModel):
    nombre: str
    precio: float
    categoria: str
    disponible: bool = True

# -----------------------------------------------
# Base de datos simulada (lista en memoria)
# -----------------------------------------------
productos_db: List[Producto] = [
    Producto(id=1, nombre="Laptop HP", precio=12500.00, categoria="Electrónica", disponible=True),
    Producto(id=2, nombre="Mouse Inalámbrico", precio=350.00, categoria="Accesorios", disponible=True),
    Producto(id=3, nombre="Teclado Mecánico", precio=890.00, categoria="Accesorios", disponible=False),
    Producto(id=4, nombre="Monitor 24\"", precio=4200.00, categoria="Electrónica", disponible=True),
    Producto(id=5, nombre="Audífonos Bluetooth", precio=1100.00, categoria="Audio", disponible=True),
]

# -----------------------------------------------
# ENDPOINTS
# -----------------------------------------------

# Endpoint raíz - bienvenida
@app.get("/")
def inicio():
    return {
        "mensaje": "¡Bienvenido a la API de Productos!",
        "version": "1.0.0",
        "endpoints_disponibles": [
            "GET  /productos          → Obtener todos los productos",
            "GET  /productos/{id}     → Obtener producto por ID",
            "POST /productos          → Crear nuevo producto",
            "PUT  /productos/{id}     → Actualizar producto",
            "DELETE /productos/{id}   → Eliminar producto",
        ]
    }

# GET - Obtener todos los productos
@app.get("/productos", response_model=List[Producto])
def obtener_productos(categoria: Optional[str] = None):
    """
    Retorna la lista de todos los productos.
    Puedes filtrar por categoría con el parámetro ?categoria=Electrónica
    """
    if categoria:
        filtrados = [p for p in productos_db if p.categoria.lower() == categoria.lower()]
        return filtrados
    return productos_db

# GET - Obtener un producto por ID
@app.get("/productos/{producto_id}", response_model=Producto)
def obtener_producto(producto_id: int):
    """Retorna un producto específico según su ID."""
    for producto in productos_db:
        if producto.id == producto_id:
            return producto
    raise HTTPException(status_code=404, detail=f"Producto con ID {producto_id} no encontrado")

# POST - Crear un nuevo producto
@app.post("/productos", response_model=Producto, status_code=201)
def crear_producto(producto: ProductoCrear):
    """Crea y agrega un nuevo producto a la tienda."""
    nuevo_id = max([p.id for p in productos_db], default=0) + 1
    nuevo_producto = Producto(id=nuevo_id, **producto.dict())
    productos_db.append(nuevo_producto)
    return nuevo_producto

# PUT - Actualizar un producto existente
@app.put("/productos/{producto_id}", response_model=Producto)
def actualizar_producto(producto_id: int, datos: ProductoCrear):
    """Actualiza los datos de un producto existente."""
    for index, producto in enumerate(productos_db):
        if producto.id == producto_id:
            productos_db[index] = Producto(id=producto_id, **datos.dict())
            return productos_db[index]
    raise HTTPException(status_code=404, detail=f"Producto con ID {producto_id} no encontrado")

# DELETE - Eliminar un producto
@app.delete("/productos/{producto_id}")
def eliminar_producto(producto_id: int):
    """Elimina un producto de la tienda según su ID."""
    for index, producto in enumerate(productos_db):
        if producto.id == producto_id:
            productos_db.pop(index)
            return {"mensaje": f"Producto con ID {producto_id} eliminado correctamente"}
    raise HTTPException(status_code=404, detail=f"Producto con ID {producto_id} no encontrado")

    

o que le falta el codigo

**Comment by carlosdanielrodriguezortiz40-ctrl** [comment]
> desde fastapi importación FastAPI, HTTPException desde pydantic importación BaseModel desde la importación de tipado Lista, Opcional
> 
> # -----------------------------------------------
> # Inicializar la aplicación FastAPI
> # -----------------------------------------------
> app = FastAPI( título="API de Productos 🛒 ", descripción="API para gestionar productos de una tienda", versión="1.0.0" )
> 
> # -----------------------------------------------
> # Modelo de datos (esquema del producto)
> # -----------------------------------------------
> clase Producto(BaseModel): id: int nombre: str precio: float categoria: str disponible: bool = True
> 
> class ProductoCrear(BaseModel): nombre: str precio: float categoria: str disponible: bool = True
> 
> # -----------------------------------------------
> # Base de datos simulada (lista en memoria)
> # -----------------------------------------------
> productos_db: List[Producto] = [ Producto(id=1, nombre="Laptop HP", precio=12500.00, categoria="Electrónica", disponible=True), Producto(id=2, nombre="Mouse Inalámbrico", precio=350.00, categoria="Accesorios", disponible=True), Producto(id=3, nombre="Teclado Mecánico", precio=890.00, categoria="Accesorios", disponible=False), Producto(id=4, nombre="Monitor 24"", precio=4200.00, categoria="Electrónica", disponible=True), Producto(id=5, nombre="Audífonos Bluetooth", precio=1100.00, categoria="Audio", disponible=True), ]
> 
> # -----------------------------------------------
> # PUNTOS FINALES
> # -----------------------------------------------
> # Endpoint raíz - bienvenida
> @app.get("/") def inicio(): return { "mensaje": "¡Bienvenido a la API de Productos!", "version": "1.0.0", "endpoints_disponibles": [ "GET /productos → Obtener todos los productos", "GET /productos/{id} → Obtener producto por ID", "POST /productos → Crear nuevo producto", "PUT /productos/{id} → Actualizar producto", "DELETE /productos/{id} → Eliminar producto", ] }
> 
> # GET - Obtener todos los productos
> @app.get("/productos", response_model=List[Producto]) def obtener_productos(categoria: Optional[str] = None): """ Retorna la lista de todos los productos. Puedes filtrar por categoría con el parámetro ?categoria=Electrónica """ if categoria: filtrados = [p for p in productos_db if p.categoria.lower() == categoria.lower()] return filtrados return productos_db
> 
> # GET - Obtener un producto por ID
> @app.get("/productos/{producto_id}", response_model=Producto) def obtener_producto(producto_id: int): ""Retorna un producto específico según su ID.""" para producto en productos_db: if producto.id == producto_id: return producto raise HTTPException(status_code=404, detail=f"Producto con ID {producto_id} no encontrado")
> 
> # POST - Crear un nuevo producto
> @app.post("/productos", response_model=Producto, status_code=201) derrotó a crear_producto(producto: ProductoCrear): """Crea y agrega un nuevo producto a la tienda.""" nuevo_id = max([p.id para p en productos_db], default=0) + 1 nuevo_producto = Producto(id=nuevo_id, **producto.dict()) productos_db.append(nuevo_producto) devuelve nuevo_producto
> 
> # PUT - Actualizar un producto existente
> @app.put("/productos/{producto_id}", response_model=Producto) def actualizar_producto(producto_id: int, datos: ProductoCrear): """Actualiza los datos de un producto existente.""" para index, producto in enumerate(productos_db): if producto.id == producto_id: productos_db[index] = Producto(id=producto_id, **datos.dict()) devuelve productos_db[index] raise HTTPException(status_code=404, detail=f"Producto con ID {producto_id} no encontrado")
> 
> # ELIMINAR - Eliminar un producto
> @app.delete("/productos/{producto_id}") def eliminar_producto(producto_id: int): ""Elimina un producto de la tienda según su ID.""" para index, producto in enumerate(productos_db): if producto.id == producto_id: productos_db.pop(index) return {"mensaje": f"Producto con ID {producto_id} eliminado correctamente"} raise HTTPException(status_code=404, detail=f"Producto con ID {producto_id} no encontrado")
> 
> o que le falta el código
