### ISSUE TITLE
Java formatter will be not working when I use lombok plugin

### ISSUE THREAD

**Issue by whmmm** [redhat-developer/vscode-java#408]
"java.jdt.ls.vmargs": "-noverify -Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication  -Dfile.encoding=UTF-8 -javaagent:e:\\jar\\lombok.jar  -Xbootclasspath/a:e:\\jar\\lombok.jar",

When I use the lombok plugin ,the Java formatter will be  not working.

**Comment by whmmm** [comment]
If you add lombok  annotation to the class (such as @Data,@Sl4j...),the formatter will not working

**Comment by fbricon** [comment]
Closing as duplicate of #243
