### ISSUE TITLE
Autocomplete for package statement has the correct suggestion on top, but by default the last used package is selected

### ISSUE THREAD

**Issue by ChiriVulpes** [redhat-developer/vscode-java#409]
##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0.131
- Visual Studio Code version: 1.19.2
- Java extension version: 0.16.0

##### Steps To Reproduce
Example package: `package yuudaari.soulus.common.serializer;`
The file is located inside this folder, so it correctly guesses that this is the package it needs to be. However, if I type `package y`, the package used previously from the giant list of other suggestions is selected, instead of the correct (first) one. The list is so long for me, I assume because [my project](https://github.com/Yuudaari/soulus) is so big, that if the last package name I used is from a package elsewhere in the project, it's usually useless to try to navigate to the correct (first) suggestion in the list, and is instead faster to just type the whole package out myself.

**Comment by fbricon** [comment]
I can reproduce the issue. jdt.ls sends the proper package in the 1st position, but vscode 1.19 tries to be smarter and [selects the most recently used item](https://code.visualstudio.com/updates/v1_19#_smarter-intellisense), overriding the server's proposal. @aeschli any idea on how to mitigate that?

**Comment by yaohaizh** [comment]
VSCode has this setting:  "editor.suggestSelection": "first"

@Yuudaari  Does this solve your issue?
