### ISSUE TITLE
Question about java classes.

### ISSUE THREAD

**Issue by EwoutLeo** [redhat-developer/vscode-java#412]
[VS code automatically generates java classes when compiling]

##### Environment
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. Open a java Project.
2. Compile and run it.

##### Current Result
https://imgur.com/a/fhYBy 

When i compile and run my project, VS code automatically generates a java class for each Java. (as you see in the image for Test and Main). For me this is really annoying, cuz it then looks like I have 2 times the same file.
##### Expected Result
https://imgur.com/a/LA8WK

I want it to be like this, this is also the way I see it in a lot of yt-vids and google-images. Like this,

https://www.google.be/search?q=vs+code+java&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiG8s_b8tnYAhVNbVAKHUrvAtgQ_AUICygC&biw=1536&bih=759#imgrc=Nf2TLV4MgFV5iM:

You see that there only are Java files and not .class files.
##### Additional Informations

Is there a way to do it like that?

**Comment by fbricon** [comment]
Our extension generates the class files on purpose, but they're normally separated from your java classes, into a separate compilation folder. Are you sure you're using [vscode-java](https://marketplace.visualstudio.com/items?itemName=redhat.java) and not some other Java extension?

**Comment by EwoutLeo** [comment]
Im pretty sure I'm only using vscode-java, cuz its the only extension i have installed.(As you can see in the picture)

https://imgur.com/a/TUhQK
https://imgur.com/a/OhM0m

So how can i solve this? Cuz it would be really helpfull to have the classes automatically generate in a separated folder.

**Comment by fbricon** [comment]
@EwoutLeo what kind of project is that? Maven, Gradle, plain Eclipse? Can you provide a sample project reproducing the issue?

**Comment by EwoutLeo** [comment]
@fbricon It's not really a project, im trying to learn some java, (I'm a beginner); It's just a stand-alone java file, just some things like the "Hello World" basic tutorials. Is that what causes this issue?, Sorry if my problem is really stupid xD.

**Comment by fbricon** [comment]
ok, when you said compile and run it. did you actually call `javac`?

**Comment by EwoutLeo** [comment]
@fbricon Yeah i did:
javac Main.java
and then to run i did:
java Main

**Comment by fbricon** [comment]
`javac` creates Main.class, that's it's only job :-), so vscode-java did nothing.

You have a few alternatives if you don't want to mix sources and classes:
- call [javac -d outputdirectory](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html)
- don't call javac, but use F5 (select Java) to let the [Java debugger automatically compile your class before running it](https://blogs.msdn.microsoft.com/visualstudio/2017/11/10/run-and-debug-java-9-in-visual-studio-code/)
- create an actual project using [Maven](https://maven.apache.org) or [Gradle](https://gradle.org/) to cleanly organize your code, you'll need to search for tutorials to get started.
