### ISSUE TITLE
Add support for Optimizing Imports

### ISSUE THREAD

**Issue by kameshsampath** [redhat-developer/vscode-java#417]
It would great to have actions that helps to optimize imports in a Java source file.

**Comment by fbricon** [comment]
There are both  an [`Organize imports` code action](https://github.com/redhat-developer/vscode-java/issues/56), visible on unused imports, and a [command, mapped to `Shift+Alt+O`](https://github.com/redhat-developer/vscode-java#available-commands).

If you try the [latest CI Build](http://download.jboss.org/jbosstools/jdt.ls/staging/), you can also organize imports as a [save action](https://github.com/redhat-developer/vscode-java/pull/402).
