### ISSUE TITLE
Code is broken for no reason. 

### ISSUE THREAD

**Issue by vincent1147** [redhat-developer/vscode-java#418]
Hi,

I've set up VS Code and created some projects a month ago. 
Then I didn't run any Java Code for a month. I was busy with c# projects.
Today I open VS Code and tried to run the Java code. 

The IntelliSense doesn't work.
The program output errors.

I tried the test program too. It didn't work.

.classpath is correct. The same setting worked a month ago. Nothing has been changed except the VS Code updates.

Could it because of the updates?

##### Environment
- Operating System: MacOS Sierra 10.12.6
- JDK version: 1.8
- Visual Studio Code version: Version 1.19.2 (1.19.2)
- Java extension version: 0.2

![screen shot 2018-01-24 at 4 07 04 pm](https://user-images.githubusercontent.com/26737365/35339481-080c52f6-0121-11e8-844e-69fabe106af2.png)

**Comment by fbricon** [comment]
Java extension version: 0.2? Are you talking about Microsoft's Java Extension Pack? This issue tracker is for [Language Support for Java(TM) by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java) (embedded in the extension pack). You should have version 0.17.0.

Your screenshot doesn't show the thumb up icon vscode-java has when jdt.ls is started.
<img width="74" alt="screen shot 2018-01-24 at 10 22 32 am" src="https://user-images.githubusercontent.com/148698/35340235-8c49f3d8-00f0-11e8-9dad-59149ce3d105.png">

Can you attach the server [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs) and see if [cleaning up the workspace](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory) helps?

**Comment by fbricon** [comment]
Also, your manual compilation can't work since you're not adding the json jar to the classpath, but that's outside the scope of vscode-java

**Comment by vincent1147** [comment]
Ah right. The version is 0.17.0. 
I was reinstalling the Language Support by Red Hat.
I've cleaned the workspace. The Intelligence is working now.

The test program still doesn't work. The classpath is correct. 

![screen shot 2018-01-24 at 5 43 27 pm](https://user-images.githubusercontent.com/26737365/35344876-7057fa74-012e-11e8-9a02-767b57b19963.png)
![screen shot 2018-01-24 at 5 46 27 pm](https://user-images.githubusercontent.com/26737365/35344930-903fad46-012e-11e8-8005-84bdbf1e7c7c.png)
![screen shot 2018-01-24 at 5 41 24 pm](https://user-images.githubusercontent.com/26737365/35344934-94bcacac-012e-11e8-82d9-c4e6addfe5c7.png)

**Comment by vincent1147** [comment]
Is there any update about the .classpath?

**Comment by vincent1147** [comment]
I think it's the Code Runner issue.

The code works fine in Debug.

**Comment by vincent1147** [comment]
Yeah. I've repeatedly tested. The problem is in Code Runner.

Thank you for the quick reply. :)
