### ISSUE TITLE
Google Java Format

### ISSUE THREAD

**Issue by azdanov** [redhat-developer/vscode-java#419]
Is there a way to setup formatting with [Google Java Format](https://github.com/google/google-java-format)?
Or an entirely new extension is needed which will run the `jar` formatter on opened file?
If so, what would be the best way to implement this as an extension, e.g running external `jar`?

**Comment by ddcprg** [comment]
This would be cool.

I'm looking for a way of configuring the formatter and the code organizer with similar settings to eclipse/intellij even better if I can import the files directly. Seems like this extension comes with predefined settings which cannot be changed.

**Comment by fbricon** [comment]
The only way you can set it up currently is to save the google java format as eclipse formatter settings, in your .settings/[org.eclipse.jdt.core.prefs](https://gist.github.com/fbricon/30c5971f7e492c8a74ca2b2d7a7bb966).

**Comment by fbricon** [comment]
I added an entry to the [wiki](https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings)

**Comment by azdanov** [comment]
I've found a solution that works ok.

https://code.visualstudio.com/docs/editor/tasks

For that to work make sure `java-google-format` can be executed from terminal. In my case:

* Installing via `brew install google-java-format` does the trick.
* Create a `tasks.json` file in `.vscode` directory inside your workspace with necessary commands.
* Run from vscode command palette by running `task` and finding `format` task

Here's my `tasks.json` file:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Run google java format",
      "type": "shell",
      "command": "google-java-format --replace ${file}"
    }
  ]
}
```

**Comment by ddcprg** [comment]
thanks @fbricon @azdanov for the swift response

**Comment by garymm** [comment]
Would be nice to have this built into the extension so it can work with "format on save".

**Comment by power-5000** [comment]
@azdanov Could you go into a bit more detail about the process you found? I am running on a Windows system what exactly is the brew program and is is that the required method to install the formatter?

**Comment by lackovic** [comment]
There is a new _Google Java Format_ extension released a couple of months ago available in [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=mngrm3a.vscode-google-java-formatter&ssr=false#overview) whose source code is [hosted on GitLab](https://gitlab.com/mngrm3a/vscode-google-java-format). 

To make it work you need to:

1. download the [latest version of google-java-format all-deps jar](https://github.com/google/google-java-format/releases)

1. move the jar in a folder (e.g. `/opt/`)

1.  enter the full path to the jar in `gjf.jarPath` of your user or workspace settings as follows:

      ```
      "gjf.jarPath": "/opt/google-java-format-1.9-all-deps.jar"
      ```

**Comment by khaver-syed** [comment]
How do you run this please?

**Comment by milic-marko** [comment]
You can try new extension which can be found here.
https://marketplace.visualstudio.com/items?itemName=mmilic.java-google-format

It works without any hustle, there is no configuration.

**Comment by Sax388** [comment]
> I added an entry to the [wiki](https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings)

@fbricon This doesn't seem to work for me anymore. I don't like using a third party extension for something that looks like a tiny setting in the `settings.json`. I tried it with
```json
  "[java]": {
    "editor.defaultFormatter": "redhat.java"
  },

  "java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml",
  "java.format.settings.profile": "GoogleStyle"
```
