### ISSUE TITLE
Issues downloading the additional extension files

### ISSUE THREAD

**Issue by joewood** [redhat-developer/vscode-java#42]
I'm using 0.0.4. After I install the plugin I see the files appear in ~./vscode/extensions/redhat.java-0.0.4. However I don't see any files (other than `.gitignore`) in the .../server dir. VSCode shows "Java" but there's no *thumbs up*. Is there a log file that I can look at? (and there's a pom.xml file in the root which compiles with **mvn**).

**Comment by gorkem** [comment]
On 0.0.4 release we have added a server download indicator that should say _"Completing Java Installation"_ and a percentage. Do you see it?

**Comment by fbricon** [comment]
Also, are you behind a proxy?

**Comment by joewood** [comment]
No, I don't see that. I just ran it in verbose mode and it appears that the post install script failed. I see the following error:
```
Detected VS Code engine version: ^1.5.0
Error installing vscode.d.ts: Error: self signed certificate in certificate chain
```
I assume this is an SSL root CA (man-in-the-middle) issue. Yes, I'm behind a proxy - but I have the strict SSL option switched off - but maybe the install script doesn't use that setting.

**Comment by gorkem** [comment]
_http.proxyStrictSSL_ configuration is passed on to the connection. How is your proxy configured? Do you use _http.proxy_ setting?

**Comment by joewood** [comment]
Yes, I use `http.proxy`. It's also configured in the environment vars - `HTTP_PROXY`.
How is the `http.proxyStrictSSL` passed onto the install process?

**Comment by gorkem** [comment]
It is passed on https://github.com/gorkem/vscode-java/blob/master/src/downloadManager.ts#L81

**Comment by mattshields** [comment]
I am seeing the same issue with version 0.0.4, 
Windows 7, 
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

http.proxy and https.proxy both explicitly set
// Whether the proxy server certificate should be verified against the list of supplied CAs.
"http.proxyStrictSSL": false,

**Comment by gorkem** [comment]
It appears passing http.proxyStrictSSL preferences to the connection was not the only issue.
