### ISSUE TITLE
We plan to feature your VS Code extension

### ISSUE THREAD

**Issue by auchenberg** [redhat-developer/vscode-java#421]
Hi,

It's Kenneth from VS Code. First a big congrats on reaching the 2mio installs, hope the cake was good! 🎂🎉

I'm reaching out to tell you that we plan to feature your awesome VS Code extension on our marketplace https://marketplace.visualstudio.com/#VSCode in the next iteration. I'm opening an issue here as there seem to many contributors on this extension, and I'm not sure who the owner is.

Please work with your community to resolve any major issues, as you'll probably see a significant bump in new users trying your extension.

Thanks for the great work, and happy coding! 

/k

------
Kenneth Auchenberg
Visual Studio Code
Program Manager, Microsoft

**Comment by gorkem** [comment]
Thanks, Kenneth. This is great news. We do not have anything major and should be good to go. 
When is the next iteration?

**Comment by auchenberg** [comment]
@gorkem That will be the release of our January iteration which most likely will happen on Feb 5-9th.

**Comment by fbricon** [comment]
It is on!
<img width="1183" alt="screen shot 2018-02-02 at 1 14 25 am" src="https://user-images.githubusercontent.com/148698/35757224-2ad8aeb6-083c-11e8-999c-bd6a9fb5faaa.png">

Thanks @auchenberg. Guess we can close this one now.

**Comment by auchenberg** [comment]
@fbricon Yes, we updated a bit earlier. I hope this will drive some numbers for you!
