### ISSUE TITLE
Sort the quick fix menu for imports in a order that makes sense

### ISSUE THREAD

**Issue by ADTC** [redhat-developer/vscode-java#424]
I'd be happy if the menu is sorted in a more sensible manner. Right now it looks so random and messy. It doesn't even look like a lexicographic sort. **And it's hard to look for the correct import when the menu is very lengthy.** 😞 

![unsorted random list of import and change to suggestions](https://user-images.githubusercontent.com/6047296/34165285-d7ac2a18-e501-11e7-8b42-ef52beeeccba.png)

Can it be sorted so that all the "Import" suggestions appear on top? Followed by "Change to", because more often than not, the class name is correct and I don't need to change it, I just need to import it. And within each type of suggestion, sorting could be lexicographic by default _but_ also any recent/plausible imports or favorites could bubble to the top (within the type).

Related: #56, #368

**Comment by fbricon** [comment]
This is definitely a bug invscode-java/jdt.ls. Comparing vscode-java:
<img width="578" alt="screen shot 2018-01-30 at 9 44 55 am" src="https://user-images.githubusercontent.com/148698/35572378-7fdd7b22-05a2-11e8-84f2-636e3cedc540.png">

to the same file opened in Eclipse: 
<img width="560" alt="screen shot 2018-01-30 at 9 45 25 am" src="https://user-images.githubusercontent.com/148698/35572397-873280ca-05a2-11e8-8df8-74c1d7bbe262.png">


(tested with https://github.com/spring-projects/spring-petclinic)

**Comment by ADTC** [comment]
Thanks for the confirmation!

**Comment by fbricon** [comment]
The fix in VS Code will be available in the March 2017 release. Or, if you can't wait, in the VS Code Insiders build on Monday.

**Comment by ADTC** [comment]
Awesome. I can't wait! :)
