### ISSUE TITLE
"Implement missing methods" is not available anymore

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#426]
With the latest 0.18.0 release "Implement missing method" code actions are gone!

##### Steps To Reproduce
1. Open file like 
```java
package foo.bar;
import java.io.Closeable;
public class App implements Closeable{}
```
2. put cursor on App, which has an error

##### Current Result
code action to implement missing methods are missing

##### Expected Result
code action to implement missing methods should be available

##### Additional Informations
Other code actions still work

**Comment by fbricon** [comment]
Weirdly enough, code action shows up  for anonymous classes, like:
```java
    public static void main(String[] args) {
        Closeable c = new Closeable(){
        };
    }
```

**Comment by kdlan** [comment]
seems this feature is still missing

**Comment by yaohaizh** [comment]
@kdlan, please provide the sample project. 

As checked, it works as code action. 
![repro](https://user-images.githubusercontent.com/17268517/50067025-deebf180-01f9-11e9-95ca-9d5cba304de6.gif)

**Comment by kdlan** [comment]
@yaohaizh  
This gif works. Thanks.

May be should reference this gif to redhat-developer/vscode-java#270
