### ISSUE TITLE
Code autocomplete and reference hint do not work in java JDK 9.0.1

### ISSUE THREAD

**Issue by khe817** [redhat-developer/vscode-java#428]
Continued from this issue that was closed: #398 

I updated to the newest released version (0.18.1). The issue is now worse with no code completion popping up at all when I type an object and wait for its functions hints to show.

Reference hint, peek definition (Alt+F12), and go to definition (F12) for classes defined in a local project (vs classes from imported package in pom.yml) also now do not work. An error "No definition" pops instead.

Reference hint, peek definition (Alt+F12), and go to definition (F12) also do not work for java core classes like List, String, ArrayList ...

**Comment by fbricon** [comment]
Everything works and seems pretty snappy for me on some simple projects.

It rather looks like you get no java support at all, as if the server was non-responsive. Can you paste [your server log and trying cleaning your VSCode workspace directory?](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs)

**Comment by khe817** [comment]
@fbricon Cleaning the VSCode workspace directory did it for me.

Everything works smoothly now.

Thank you very much for you help!
