### ISSUE TITLE
Java language support requires Java 8 (using C:\Progra~1\Java\jdk-9.0.4\bin\java.exe)

### ISSUE THREAD

**Issue by Clevi-Villa** [redhat-developer/vscode-java#431]
I have the latest JDK installed, as well as the latest version of Java installed, but I still get this message. I've set the java.home variable in the VS Code settings file, and the JAVA_HOME environment variable to the appropriate path. 

Do I need a different version of Java, or is there a problem with this:

![image](https://user-images.githubusercontent.com/33530965/35760561-13567d5a-084f-11e8-9486-fb9be1666fe2.png)

The description for the same setting (or 'these settings', rather) applies to 2 different system paths, one for JDK, and one for the Java installation, I'm assuming.

**Comment by fbricon** [comment]
You have both vscode-java (aka redhat.java) and [georgewfraser.vscode-javac](https://github.com/georgewfraser/vscode-javac/blob/master/package.json#L74), 2 competing java extensions, installed. It's generally not a good idea to have both installed at the same time, as you can see there's a settings key conflict. I suggest you remove one of them. If you keep vscode-java, make sure your java.home path points at the home folder, not the java binary, so in your case that'd be `C:\Progra~1\Java\jdk-9.0.4\`

**Comment by Clevi-Villa** [comment]
Ah-ha... I suppose I installed 2 Java Support extensions upon downloading VS Code without realizing I did... I forgot about that. I uninstalled Fraser's extension, and that did the trick. 

Thank you, and... 
my apologies.
