### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by cryptojonnyboy** [redhat-developer/vscode-java#442]
[provide a description of the issue]
@fbricon Do one of you guys know how I can sol
![git](https://user-images.githubusercontent.com/35565338/36239545-c55636a2-120a-11e8-9791-fd1462849d60.JPG)
ve yet another issue with the Git repository?
##### Environment
- Operating System: windows 7 
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Sorry I have no idea what this error means. This issue is not related to vscode-java. 
Please report git related problems to https://github.com/Microsoft/vscode/issues

**Comment by cryptojonnyboy** [comment]
@fbricon thanks
