### ISSUE TITLE
Extension completely broken

### ISSUE THREAD

**Issue by shawmanz32na** [redhat-developer/vscode-java#445]
I'm sorry, but I can't come up with a more specific title.

When I load up my Java project's workspace, which is a multi-module Maven project, none of the Java features are available. I tried uninstalling and reinstallling the extension as part of the Java Extension Pack, restarting VS Code each time, but there was no change. I have then tried each of the possible Java commands from the command palette, but each shows an error notification along the lines of `command 'java.projectConfiguration.update' not found`. I can't attach the logs, since I get `command 'java.open.serverLog' not found` when I try.

I opened VS Code's dev tools, and these errors show up in the console:
![image](https://user-images.githubusercontent.com/5596570/36323199-f6e89eee-1304-11e8-8e29-82bf5d1f6c5c.png)

I'm open to troubleshooting steps, but these are the most current versions, and I already did the classic 'Did you turn it off and on again?'...

##### Environment
- Operating System: Windows 10 Pro 1709 16299.248
- JDK version: 1.8.0_161
- Visual Studio Code version: 1.20.1
- Java extension version: 0.19.0

##### Steps To Reproduce
1. Open a Java workspace

**Comment by shawmanz32na** [comment]
I was able to "resolve" this problem by uninstalling the extensions from VS Code, then manually removing the extension's directories from `~/.vscode/extensions` and also removing the `~/.vscode/extensions/.obsolete`.

I'd hardly call it "graceful", though.

**Comment by fbricon** [comment]
Looks like a faulty vscode extension update, nothing we can do on the vscode-java side

**Comment by maroc81** [comment]
Same thing happened to me.  Opened up a java project and it was like the extension wasn't even installed.  I removed this extension and dependencies, removed the java extension directories, and reinstalled the extensions.  Now it works again.
