### ISSUE TITLE
Add support for "Go to implementation"

### ISSUE THREAD

**Issue by Ravenow** [redhat-developer/vscode-java#446]
Hello. Im new to vscode and java extension.  I wanna see all implementation of target interface, like in jetbrains idea (crtl+alt+b). I setted up ctrl+alt+b  for command java.show.implementations, but it always fail. IMHO thats strange becase implementationsCodeLens works fine. Any help? 

Thanks.

##### Environment
- Operating System: fedora 27
- JDK version:  1.8.0.161
- Visual Studio Code version: 1.20.1
- Java extension version:  0.19.0

##### Additional Informations
![2018-02-16 22-03-20](https://user-images.githubusercontent.com/20242363/36324935-1c002d8e-1367-11e8-91f1-1ba949f03f84.png)

**Comment by fbricon** [comment]
The current `java.show.implementations` command is actually internal, not designed to be called manually from the UI, or be bound to a shortcut.

However, VSCode now has a show implementation shortcut (Ctrl+F12) (see https://github.com/Microsoft/vscode/pull/18346), so we should eventually be able to plug into that mechanism, but it's [not been standardized yet](https://github.com/Microsoft/language-server-protocol/issues/156).

**Comment by LQR86** [comment]
Also, it seems that "Go to super definition(or go to super method)" command doesn't exist in VSCode. And I really need it when navigating through Java or any other object-oriented code. Sigh.

**Comment by shawmanz32na** [comment]
@fbricon Unless I'm misreading, both the dependency issues you listed are now merged/closed. Can this get put on the queue of things to do?

I'd love to be able to quickly navigate to implementing classes.

**Comment by darkgem666** [comment]
It looks the new update for VSCode has now the implementation for this,  can we please make this happen?

**Comment by kainazzzo** [comment]
I would also like this feature a lot. I've switched to VS code for all my java projects but miss this feature mostly.

**Comment by aabuniaj** [comment]
Any updates on this functionality?

**Comment by fbricon** [comment]
I'm working on it. It should be available in a CI build next week and should be generally available for the end of August release

**Comment by aabuniaj** [comment]
Thank you! I appreciate the update.

**Comment by fbricon** [comment]
BTW the find implementors behavior in VSCode is a bit weird, always opens the 1st result then displays the list under that result: https://github.com/Microsoft/vscode/issues/55603

**Comment by fbricon** [comment]
@jrieken I can't seem to be able to cancel textDocument/implementation queries. Is it me or a limitation in vscode?

**Comment by aeschli** [comment]
@fbricon Can you elaborate? Cancel would be initiated by the UI and signaled to the server through the LSP. Are you saying it doesn't arrive on the server?

**Comment by fbricon** [comment]
@aeschli indeed I don't see any cancellation event when hitting `esc` while implementation search is running

**Comment by dbaeumer** [comment]
This is implemented generically as soon as a request provides a cancelation token.

**Comment by dbaeumer** [comment]
I tested this and pressing Esc when Goto Implementation is executed doesn't cancel the request. Please file an issue against VS Code itself so cancelation can be implemented there.

**Comment by aabuniaj** [comment]
Is this feature available to try? How can I get it to test it out?

**Comment by amplexdenmark** [comment]
I just tried this, installed java-0.31.0-1204.vsix
But it does not work for me hitting cmd+12 (Mac) or selecting "Go to implementation" from the menu both shows "No implementation found for: <methodname>"
But "Go to definition" works and takes me to the interface and my implementation class is right next to it in the same folder. 
Must I do something to enable this feature?

**Comment by JavaHello** [comment]
I am very happy that this feature is ready to use. 
> From google translate

**Comment by amplexdenmark** [comment]
Okay, I figured out how this works.
But IMO it can be improved.

If you are placed on method call to an interface and select "Go to implementation" it will show you "No implementation found...", what you need to do is first select "Go to Definition" which navigates to the method definition in the interface and here you can select "Go to implementation" which correctly navigates to the implementation.

I had hoped this was a one step process, usually I do not care about the definition, and it opens an extra file in my workspace.

But it is still nice to be able to do it at all :-)

**Comment by FinallyFinancialFreedom** [comment]
yes, in VSCode, " Go to Definition" first and then "Go to implementation" works fine.
But i'm using coc.nvim in neovim, everytime i open a java project, "Go to Definition" works fine, but "Go to implementation" doesn't work at first time, after i call it serveral times, it begin works and works fine after that. i don't know why. i have installed the latest snapshot of jdt.ls

**Comment by liudonghua123** [comment]
It's nice to have this features.

**Comment by openvita** [comment]
Would be nice to have this feature. VSCode for Java rocks !

**Comment by fbricon** [comment]
@openvita see keymapping in vscode:
<img width="475" alt="Screen Shot 2019-10-28 at 3 09 49 PM" src="https://user-images.githubusercontent.com/148698/67685274-11778680-f995-11e9-8452-8136be906d32.png">

**Comment by meydominic** [comment]
I'm on version 0.52 but it's not working:
![image](https://user-images.githubusercontent.com/2743382/68280765-81ad9880-0076-11ea-9fc6-8c8ff25101d3.png)
