### ISSUE TITLE
Full build always performed on startup when using project that imports eclipse files

### ISSUE THREAD

**Issue by rsalvador** [redhat-developer/vscode-java#451]
We are importing a big java project in vscode-java using eclipse files (.classpath/.project) and on startup vscode-java always performs a full build which takes several minutes.

The reason for the full build seems to be the CLEAN_BUILD done in JDTLanguageServer.didChangeConfiguration(). VS Code always sends a workspace/didChangeConfiguration on startup and that forces a full build even though
the settings didn't change.

Note: if I remove the CLEAN_BUILD from JDTLanguageServer.didChangeConfiguration() the old markers (i.e. warnings/infos) are not imported. They get imported quickly (a few secs) if I replace the CLEAN_BUILD by an incremental build: JDTLanguageServer.buildWorkspace(false).

##### Environment
- Operating System: Mac OS 10.13.3
- JDK version: 1.8.0_131
- Visual Studio Code version: 1.20.1
- Java extension version: 0.19.0

##### Steps To Reproduce

1. import java project using eclipse files
2. stop/start vscode and see that a full build is always performed

[jdt.log](https://github.com/redhat-developer/vscode-java/files/1759679/jdt.log)

##### Current Result

Full build done on startup

##### Expected Result

Load old errors and only perform incremental build if files changed since last time vscode was opened. Perform full build only if setting/jvm changed.

**Comment by fbricon** [comment]
Fixed with https://github.com/eclipse/eclipse.jdt.ls/pull/572
