### ISSUE TITLE
Unable to set Java source level

### ISSUE THREAD

**Issue by fishnet37222** [redhat-developer/vscode-java#452]
There does not seem to be a way to set the Java source level for a Maven-based project in Visual Studio Code using this extension.

##### Environment
- Operating System: Linux Mint
- JDK version: 9.0.4
- Visual Studio Code version: 1.21.0-insider
- Java extension version: 0.19.0

##### Steps To Reproduce
1. Set the following properties in the POM file for a Maven project:
```
<maven.compiler.source>1.9</maven.compiler.source>
<maven.compiler.target>1.9</maven.compiler.target>
```
2. Include code in the project that depends on Java 9 features, such as a multi-catch parameter in a try-catch block.

##### Current Result
Compilation fails with an error stating that the Java source level is too low.

##### Expected Result
The project should be configured to use the Java source level mentioned in the POM file.

##### Additional Information
I've provided a sample project which reproduces the issue.
[fndice.zip](https://github.com/redhat-developer/vscode-java/files/1759774/fndice.zip)

**Comment by fbricon** [comment]
You need to use 
```xml
<maven.compiler.source>9</maven.compiler.source>
<maven.compiler.target>9</maven.compiler.target>
```

I'm surprised the Maven compiler still supports the `1.9` value though
