### ISSUE TITLE
The encoding "TAB" missed when peeking a reference in Java source code

### ISSUE THREAD

**Issue by afterhill** [redhat-developer/vscode-java#453]
- VSCode Version: 1.193
- OS Version: macOs 10.13.3

Steps to Reproduce:

1. Open a Java+Maven based project;
2. Use command + click to peek a reference which is located in a JAR and the the source is downloaded by maven automatically;
3. A file with .class extension is opened in the VS code;
4. Try to change the encoding by click the "encoding TAB" in status bar, but the "TAB" is not existing;

----------

Does this issue occur when all extensions are disabled?: Yes

refer for the screenshot: Microsoft/vscode#44475

**Comment by fbricon** [comment]
Class content are provided via https://github.com/redhat-developer/vscode-java/blob/36da57f52e1ae33e41417c4637efc0f68f042643/src/extension.ts#L207-L215

Given 

> The editor will use the returned string-content to create a readonly document

I'm assuming that makes encoding selection impossible. Anything we can do @jrieken @aeschli?

**Comment by jrieken** [comment]
Not sure what @MengJueM wants. Changing the encoding (reopen with encoding, save with encoding) only makes sense for files from disk. For a virtual document, that our API defines as JavaScript string, no such logic applies.

**Comment by fbricon** [comment]
@jrieken I'm assuming the problem is we return UTF-8 encoded source at the moment (https://github.com/eclipse/eclipse.jdt.ls/issues/524), but if it's actually some chinese @MengJueM  wants to see, there's nothing we can do.

**Comment by jrieken** [comment]
Yeah, utf-16 is what our strings want ;-) The node buffer apis might help you with that.

**Comment by fbricon** [comment]
@jrieken that won't help users in selecting encoding, unless I'm missing something

**Comment by jrieken** [comment]
I meant that it can help you create a correct string when having just bytes

**Comment by MengJueM** [comment]
As @fbricon mentioned, the virtual document is encoded with "UTF8" by default, it will make the text messed up when the actual character is GBK encoded. The intellij idea can handle this properly by giving the choice by reloading document with proper encoding.
![image](https://user-images.githubusercontent.com/2742842/36829693-59c54fca-1d5b-11e8-8c8b-57d9cecb97c5.png)

**Comment by MengJueM** [comment]
peek is also not working
![image](https://user-images.githubusercontent.com/2742842/36829994-8e49902a-1d5c-11e8-8220-ac54f940bfbe.png)

**Comment by MengJueM** [comment]
vs code can handle the encoding problem perfectly by detecting per Microsoft/vscode#5388.

**Comment by jdneo** [comment]
Is this still an issue?
