### ISSUE TITLE
Autocompletion does not work with enum ctors

### ISSUE THREAD

**Issue by personinblack** [redhat-developer/vscode-java#454]
The title explains it all. You can't use intellisense in enums' ctors:
```
public enum ExampleEnum {
    ValueOne("You can't use intellisense in here") // <------
    ;

    ExampleEnum(String string) {
    }
}
```

##### Environment
- Operating System: Arch Linux
- JDK version: 1.8.0_162
- Visual Studio Code version: 1.20.1
- Java extension version: 0.20.0

##### Steps To Reproduce
1. Create an enum
2. Try typing a few words and pressing ctrl + space to bring intellisense

##### Current Result
You don't get any autocompletion

##### Expected Result
Intellisense should work normally

**Comment by fbricon** [comment]
What sort of completion are you expecting? a default string value? from a constant in the imports?

**Comment by Personinblack** [comment]
It's not about strings. String was to show it. It could be something like this:
```
public enum ExampleEnum {
    ValueOne(Parameter.) // Typing `Parameter.` and trying to autocomplete the method / variable will not work.
    ;

    ExampleEnum(Parameter parameter) {
    }
}
```

**Comment by fbricon** [comment]
I can reproduce the same problem with stock Eclipse. Opened upstream issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=532366

**Comment by neel-suthar** [comment]
Yup!! Having the same issue. So anybody working on it ??

**Comment by fbricon** [comment]
It was fixed upstream today: https://bugs.eclipse.org/bugs/show_bug.cgi?id=532366#c16

It might take a few weeks before we can consume those bits.

**Comment by 0dinD** [comment]
Looks like the fix has finally made it into eclipse.jdt.ls with the recent updates to the target platform! I can no longer reproduce the bug after trying eclipse/eclipse.jdt.ls@5483c3a, so I think this issue can be closed now.
