### ISSUE TITLE
Nashorn script support

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-java#456]
We received a features request in the debugger repo Microsoft/vscode-java-debug#152. This is to request launching debugger from nashorm scripts when 'debugger;' statement is executed.

Do you guys have any thoughts on this one?

**Comment by fbricon** [comment]
@akaroml I guess the debugger needs to expose a javascript-jvm (or nashorn) launch configuration. But I'm not sure what can jdt.ls provide here.

**Comment by anthonyvdotbe** [comment]
@fbricon Nashorn has been [deprecated](http://openjdk.java.net/jeps/335) in Java SE 11, so imho this can be closed

**Comment by fbricon** [comment]
Agreed

**Comment by ahmednrana** [comment]
OpenJDK still publishes it as standalone now.
https://github.com/openjdk/nashorn
