### ISSUE TITLE
TODO comments highlight bug

### ISSUE THREAD

**Issue by Eugenii10** [redhat-developer/vscode-java#457]
After editing a java source file and saving changes with Ctrl + S, "TODO" comments are stopped to be underlined and recognized as TODO tasks (don't show in the PROBLEMS tab and don't have green marks at the vertical scroolbar).

##### Environment
- Operating System: Windows 7 and 10
- JDK version:  1.8.0_60
- Visual Studio Code version: 1.20.1
- Java extension version: 0.20.0

##### Steps To Reproduce
1. Add some TODO comments in the java source file.
2. Save file.
3. Close IDE.
4. Open IDE and file.
5. Edit any line in the file.
6. Save file with "Ctrl + S".

[project.zip](https://github.com/redhat-developer/vscode-java/files/1777237/project.zip)
[vscode-java.log](https://github.com/redhat-developer/vscode-java/files/1777233/vscode-java.log)
[java_lang_server.log](https://github.com/redhat-developer/vscode-java/files/1777234/java_lang_server.log)

##### Current Result
![vscode_java](https://user-images.githubusercontent.com/26702097/36931903-bdbbc764-1f0b-11e8-9f75-ea79971235fc.gif)

##### Expected Result
TODO comments are underlined, displayed in the PROBLEMS tab of the bottom panel and have green marks at the vertical scrollbar.

**Comment by fbricon** [comment]
Another manifestation of that dubious diagnostics issue we've seen on and off

**Comment by gruvw** [comment]
I still have this issue, is there a way to fix it?

**Comment by snjeza** [comment]
@gruvw could you try to add

```
org.eclipse.jdt.core.compiler.taskCaseSensitive=enabled
org.eclipse.jdt.core.compiler.taskPriorities=NORMAL,HIGH,NORMAL
org.eclipse.jdt.core.compiler.taskTags=TODO,FIXME,XXX
```
to <your_project>/.settings/org.eclipse.jdt.core.prefs

**Comment by gruvw** [comment]
I tried that but it did not work. I am using VSCode.

**Comment by matthewelmer** [comment]
I have a burning hatred for the default TODO wavy underlines, especially since there's no setting to remove the eyesore. @snjeza 's suggestion to create .settings/org.eclipse.jdt.core.prefs and put org.eclipse.jdt.core.compiler=<what you want underlined, which should be nothing if you are gifted with the sense of sight> inside of it worked, cause I just set it to nothing. 

My question is: how do I make this setting apply to all java files?

**Comment by snjeza** [comment]
@matthewelmer could you provide a project example reproducing the issue?

**Comment by matthewelmer** [comment]
@snjeza oops, right. My post was unrelated to the issue.

**Comment by shanike** [comment]
Same problem here. VS Code with Java: 
![image](https://github.com/redhat-developer/vscode-java/assets/56911506/ea6204a2-d4bd-4909-ae4a-d1b6707d002d)
(Don't get confused with Eclipse: It's just  an "Eclipse" theme inside vscode)

Happens immediately when I type a "TODO" in a comment. (inline comment and java-doc comment)

I work with Java 8 and am running on a Linux Ubuntu 20.04

**Comment by snjeza** [comment]
@shanike You can add

```
org.eclipse.jdt.core.compiler.taskTags=
```
to <your_project>/.settings/org.eclipse.jdt.core.prefs

**Comment by Kalightortaio** [comment]
Still present in late 2024.

**Comment by erikweibust** [comment]
Please reopen. This issue is still present.

![Image](https://github.com/user-attachments/assets/6ed7dcc6-8472-4194-8062-dc10dd92b837)
