### ISSUE TITLE
Lombok Support officially in Visual Studio Code

### ISSUE THREAD

**Issue by GabrielBB** [redhat-developer/vscode-java#460]
Hi, i'm writing this because i see you have something about manually adding lombok to VS Code. I saw people where i work that struggle to follow that simple step, i don't know why, people were asking if they have to include the "a:" and stuff and if they should add it on user settings and workspace settings, someone who deleted the lombok.jar from the path cleaning his downloads folder and then his VS Code was all messed up for a whole day saying the java language server failed to start  Well, in conclusion, i thought this needs a simple extension so i published this:

Marketplace: https://marketplace.visualstudio.com/items?itemName=GabrielBB.vscode-lombok 
Github: https://github.com/GabrielBB/vscode-lombok

I just thought you might be interested

**Comment by gorkem** [comment]
Funny. I was just looking at the extension. Looks like a simple enough solution. I see that you are not listing vscode-java as a dependency is that on purpose? Otherwise [something like this](https://github.com/Microsoft/vscode-java-debug/blob/master/package.json#L350) on the package.json would guarantee that you have the java support installed all the time.

**Comment by GabrielBB** [comment]
Oh, it was not on purpose. Thanks for that very important correction. Published

![image](https://user-images.githubusercontent.com/8752823/37258644-fdc1dbe6-2550-11e8-95cf-a82438be2dff.png)

**Comment by fbricon** [comment]
Nice! I've updated https://github.com/redhat-developer/vscode-java/wiki/Lombok-support with a reference to your extension.

Utlimately I still think we can do better at providing lombok support, (eg. detect lombok is a classpath dependency, download the jar if necessary, update the vm args only when necessary...), but your extension should do the work for now and help struggling users with lombok support.

**Comment by tristan957** [comment]
@GabrielBB are you just downloading releases of Lombok and hosting it within the extension?

**Comment by fbricon** [comment]
> are you just downloading releases of Lombok and hosting it within the extension?

@tristan957 indeed, see https://github.com/GabrielBB/vscode-lombok/tree/master/server

**Comment by GabrielBB** [comment]
@tristan957 Yes, for now I have the last stable version inside the extension. But my first intention was to use Gulp to download the last version from the page, just when you install the extension. I have the initial code for that, I’m gonna make an update as soon as i get time

**Comment by GabrielBB** [comment]
Closing “issue”. https://projectlombok.org/setup/vscode
