### ISSUE TITLE
Second argument is replaced upon completing the first argument in a method call

### ISSUE THREAD

**Issue by michelkaporin** [redhat-developer/vscode-java#462]
**Moved from https://github.com/Microsoft/vscode-java-pack/issues/12:**

- VSCode Version: Latest Insiders
- OS Version: Mac OS

Steps to Reproduce:
1. Insert cursor before the first argument (that accesses some property) to the method.
2. Start typing new argument that also accesses property. 
3. On suggestion appearance, press Tab to enter suggestion value
It replaces the old first argument instance with the property from the new argument. 

![vscode](https://user-images.githubusercontent.com/2239563/35227216-bad6a62e-ff8d-11e7-9291-85fc71e8e9f9.gif)

Sample code:
```java
public class Test {
    public int testInt;

    public boolean method(int x, int y, int z) {
        return true;
    }
}

public class Main {
    public static void main(String[] args) {
        Test t = new Test();
        t.method(t.testInt, t.testInt);
    }
}
```

**Comment by gorkem** [comment]
@snjeza If it helps I can easily repro this.

**Comment by snjeza** [comment]
@gorkem Thanks. I have reproduced it. It isn't reproducible in Eclipse.

**Comment by SummerSun** [comment]
Did repro it in Mac OS with VSCode Latest Insiders. But in Windows 10, the issue is a little different.

Repro steps are the same.

![java_intellisense](https://user-images.githubusercontent.com/5179063/37325469-0b33d170-26c9-11e8-9f9e-e1c398859472.gif)

**Comment by SummerSun** [comment]
Tried with vscode 1.21.0 with windows 10, easily repro this issue.

![java_intellisense](https://user-images.githubusercontent.com/5179063/37501852-11c3a576-290b-11e8-953b-1b0fb2cdb02f.gif)

 Attach the request from client, hope it helps.
```
[Trace - 3:41:00 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///d%3A/java-debug/com.microsoft.java.debug.core/src/main/java/com/microsoft/java/debug/core/Breakpoint.java",
        "version": 22
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 109,
                    "character": 35
                },
                "end": {
                    "line": 109,
                    "character": 45
                }
            },
            "rangeLength": 10,
            "text": "className()"
        }
    ]
}
```

**Comment by fbricon** [comment]
the fix introduces a new preference : `java.completion.overwrite` (boolean). The default (current) behaviour has the value set to true. @michelkaporin you'll be able to change it to false to get what you want.
