### ISSUE TITLE
"Classpath is incomplete" error when using local jar files 

### ISSUE THREAD

**Issue by colinrc** [redhat-developer/vscode-java#469]
When I open a Gradle project that uses files dependencies they don't seem to be being picked in the classpath - I get the standard "Classpath is incomplete...." error even though the project builds properly in gradle. 

I have tried adding classpath entries in settings but the extension still does not seem to resolve the files.

I have to do this as I cannot communicate with maven behind the firewalls where I am and I would prefer not to have to set up a local maven repository for only four jar files unless I have no choice.

**Comment by colinrc** [comment]
I think I found it. The problem seemed to have been related to me having two Java extensions active. Both the RedHat Language Support one and another one, also called Java Language Support - by Gorge Fraser. It seems like they don't like to co-exist. 

I removed that extension and VSC start finding the classes correctly when I just use compileClasspath entries in my build.gradle file.

**Comment by colinrc** [comment]
Resolved, a spelling mistake in the build.gradle.

**Comment by fbricon** [comment]
please attach a sample project reproducing this issue

**Comment by colinrc** [comment]
[testvs.zip](https://github.com/redhat-developer/vscode-java/files/1827550/testvs.zip)

Sure - done....

**Comment by colinrc** [comment]
On an additional note; if I try to debug the project it won't start - instead showing "Failed to resolve classpath: The project 'Project' is not valid java project.

Presumably for the same classpath reason.

Again, if I copy the folder onto my mac it works perfectly; neither environment have CLASSPATH environments set and I am using the same Java8 release on each 1.8.0_161

**Comment by fbricon** [comment]
Builds fine on my Mac. @snjeza can you please check on Windows?

**Comment by snjeza** [comment]
It works fine.
Windows 7
VS Code 1.21.1
Java LS 0.21.0

![img](https://user-images.githubusercontent.com/388609/37782098-5d863a32-2df2-11e8-8b83-9bba722948be.png)

**Comment by colinrc** [comment]
Thanks very much for your help on this - it must be something at my end with the installation. 

At least I know the project is good so I can use that to test the environment.
