### ISSUE TITLE
Display package names in Type completion proposals

### ISSUE THREAD

**Issue by qiukeren** [redhat-developer/vscode-java#47]
![image](https://cloud.githubusercontent.com/assets/2325492/18952136/2ead652a-867b-11e6-8376-0869cbf6a2ab.png)

i think it is better to add the package name after the classname

**Comment by fbricon** [comment]
You mean add it for all occurrences, like the highlighted one?

**Comment by fbricon** [comment]
@gorkem I believe this is the stock VS Code behavior right now. I think that would require customizing rendering the results.  WDYT?

**Comment by qiukeren** [comment]
yes,in my mind, it may be better to display the package like other IDEs does


![image](https://cloud.githubusercontent.com/assets/2325492/18954693/af5da0e4-8686-11e6-949d-de49c1590a44.png)

**Comment by gorkem** [comment]
The very first version of reported FQN for every item. I think I have changed the behavior around 0.0.3 to omit the package name to give more space to code completions for method names. Appearently, this does not work well for Type completions. I think we will split the way we create code completions for Types and method names.

**Comment by gorkem** [comment]
fixed on server with https://github.com/gorkem/java-language-server/commit/5cab6aad8cb230f7e161656b18dbeb070fd34bb0
