### ISSUE TITLE
Open classes/sources of maven/gradle dependencies

### ISSUE THREAD

**Issue by 38leinaD** [redhat-developer/vscode-java#475]
When I have a maven/gradle project open that has external dependencies on the classpath, i would like to have an option (like ctrl+p for the source/classes directly in the project) to find and open any class on the classpath (Obviosuly, this only makes sense for classes where sources are published for the jar-file).

**Comment by fbricon** [comment]
Use the "Go to Symbol" command: Ctrl+T (Cmd+T on MacOS)
