### ISSUE TITLE
Extension executing failing process indefinitely

### ISSUE THREAD

**Issue by BigBallard** [redhat-developer/vscode-java#481]
For some unknown reason, the extension runs a pair of commands (one I believe to be initiating the other) that continuously fail and continue to retry resulting in eating up a lot of CPU time and resources. 

Restarting VSCode stops this for some time but what starts this is unknown. As simple as it is, it seems unnecessary and is rather expensive on the system, not to mention cluttering syslogs.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0_162
- Visual Studio Code version: 1.21.1
- Java extension version: 0.21.0

##### Steps To Reproduce
Unknown

##### Additional Informations
This is the full command that starts this:
`"C:\Program Files\Java\jdk1.8.0_162\bin\java" -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar C:\Users\dphillips\.vscode\extensions\redhat.java-0.21.0\server\plugins\org.eclipse.equinox.launcher_1.5.0.v20180207-1446.jar -configuration C:\Users\dphillips\.vscode\extensions\redhat.java-0.21.0\server\config_win -data C:\Users\DPHILL~1\AppData\Local\Temp\vscodesws_b508c\jdt_ws`

And this command follows (being produced?)
`cmd /c "tasklist /FI "PID eq 36948" | findstr 36948"`

**Comment by fbricon** [comment]
can you run the offending command manually to see why it fails?

**Comment by fbricon** [comment]
this command is used to determine if the parent process is still running and if not, would trigger the java language server to exit. See https://github.com/eclipse/eclipse.jdt.ls/blob/8654474dd7fa5f0d1fb33c0c38ab254efe41c4df/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java#L64

**Comment by fbricon** [comment]
@gorkem https://github.com/eclipse/eclipse.jdt.ls/blob/8654474dd7fa5f0d1fb33c0c38ab254efe41c4df/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java#L70 should use the timeout flavoured method

**Comment by DallasP9124** [comment]
I have run both and the longer command just hangs without action. The following command executes and exits. The PID(s) that are looked for don't get found.

**Comment by fbricon** [comment]
@DallasP9124  does `cmd /c "tasklist.exe /FI "PID eq 36948"` respond?

**Comment by DallasP9124** [comment]
`C:\Users\dphillips>cmd /c "tasklist.exe /FI "PID eq 36948"
INFO: No tasks are running which match the specified criteria.`
Is what I get. The PID changes though when I shutdown Code and restart it.

**Comment by fbricon** [comment]
ok, so tasklist.exe responds but tasklist doesn't is what I'm getting

**Comment by DallasP9124** [comment]
No they both work just fine, but the PID that is searched for is never found, then the command continues to repeatedly execute

**Comment by fbricon** [comment]
> then the command continues to repeatedly execute

From CLI??

**Comment by gorkem** [comment]
The command executed every 2 seconds to check if parent process is alive. Is that what you are seeing?

**Comment by DallasP9124** [comment]
No, not from CLI. This machine uses OSQuery to aggregate and collect logs. That is how we know what is going on. Today alone there have been 24k+ hits. This image shows that. The PID changes per runtime of VSCode. But yes that is what is happening. 
![image](https://user-images.githubusercontent.com/13224109/37998745-bb1e13a0-31d4-11e8-870b-acda8ecb7a47.png)

**Comment by gorkem** [comment]
It is strange that the query can not find the PID? The PID is passed down from VSCode to the extension. I suppose it should be correct since VSCode is running

**Comment by markerikson** [comment]
I'm a new VS Code user, and I'm seeing this behavior consistently.  The `tasklist` processes are kicking off every couple seconds.

System details:

```
Version: 1.30.1 (user setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Date: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.16299
```

Looks like I'm using VS Code-Java 0.36.0

**Comment by rgrunber** [comment]
I would close this as the section that performs the check has improved a bit. The polling delay is now every 10s, but as before, the check requires that the language server has had no communication with the client in over 30s. We also use `ProcessHandle` to check the process so `tasklist` has become a fallback that shouldn't be used in most cases.

https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/8f0f822a89bf1f6109a9d95d048e7b53110df19f/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java#L77-L94
