### ISSUE TITLE
No progress shown on implicit builds

### ISSUE THREAD

**Issue by rsalvador** [redhat-developer/vscode-java#484]
The extension doesn't show progress when performing autobuilds.
For example during startup it shows the progress while the Java Language Server is starting:

<img width="556" alt="screen shot 2018-03-29 at 8 59 07 am" src="https://user-images.githubusercontent.com/1301827/38099461-7fc5fa96-332f-11e8-8e1c-1eeed7636c07.png">

but then it doesn't show any progress while doing the initial full or incremental build.
In our big project the initial build takes more than 1 minute and without the progress is confusing.

There is no progress either if an implicit incremental build is done while VSCode is already  up (i.e. if one updates the source doing a git pull)

Progress is shown though for explicit builds started with the "Java: Force Java Compilation" command

##### Environment
- Operating System: Mac OS 10.13.3
- JDK version: 1.8.0_152
- Visual Studio Code version: 1.21.1
- Java extension version: 0.21.0

##### Steps To Reproduce
1. Start VSCode
2. See that no progress is shown while the initial or subsequent implicit builds are performed

**Comment by fbricon** [comment]
Fixed with https://github.com/redhat-developer/vscode-java/pull/387. Please try the latest *.vsix from http://download.jboss.org/jbosstools/jdt.ls/staging/
