### ISSUE TITLE
Support for intellisense/autocomplete in maven pom.xml files

### ISSUE THREAD

**Issue by mogarick** [redhat-developer/vscode-java#487]
Hi,

Is there any plans to support intellisense/autocomplete on Maven pom.xml files? I love this feature in Netbeans and IntelliJ because it suggests groupId, artifactId and also show available versions.

**Comment by fbricon** [comment]
We have to figure out whether to include this as part of the Java extension or a companion Maven extension

**Comment by MeikTranel** [comment]
Why not start by working with XSD schemata already linked in all maven poms?
That way we'd have support for about 50% of what pom intellisense would require?

Implementing dynamic intellisense of maven plugin configuration properties is a little more complex, but i'd assume validating and giving intellisense for the core skeleton of the pom using XSD shouldn't be quite that complex a task?

**Comment by MeikTranel** [comment]
Theres more to POM than just the XML/XSD part though. Is that never going to happen because POMs reside in xml files or what? Package Version intellisense for example would be really nice.

**Comment by fbricon** [comment]
FYI our VS Code XML extension is live at https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml (and it works pretty well for an alpha release). Doesn't have any actual Maven related stuff (dependency completion), but has XSD support, formatting, autocompletion (for schema related stuff) and more.

**Comment by akaroml** [comment]
@eskibear please consider add support to provide auto-completion for dependencies.

**Comment by Eskibear** [comment]
FYI the dependency completion feature has been shipped with the [Maven extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven), including snippets and groupId/artifactId/version suggestions. Example [here](https://github.com/Microsoft/vscode-maven/blob/a294046e899c05344b1b5c2c73ad5dbe9680ba10/images/completion.gif).

**Comment by jdneo** [comment]
Some extensions that can help:

- [Maven for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven)
- [XML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml)
