### ISSUE TITLE
Resume all pausing threads

### ISSUE THREAD

**Issue by erihanse** [redhat-developer/vscode-java#488]
Is there some way to resume all waiting threads? 
Sometimes when I set a breakpoint, I only want one of the threads to pause, to inspect some behaviour. 

![image](https://user-images.githubusercontent.com/9251274/38279934-f1d68732-37a2-11e8-8112-78e9d813dd2c.png)

The way it is now, I need to right-click all paused threads to carry on.

**Comment by yaohaizh** [comment]
I don't think there is an options to pause only specific thread. 

You can log issue for vscode  java debugger here:  https://github.com/Microsoft/vscode-java-debug

**Comment by fbricon** [comment]
Closing as not a vscode-java issue. Please open a ticket at https://github.com/Microsoft/vscode-java-debug/issues
