### ISSUE TITLE
Java 10 support

### ISSUE THREAD

**Issue by ninjamyst** [redhat-developer/vscode-java#489]
Does the latest release support Java 10?  I pointed Java.Home to the Java 10 directory and restarted VS Code but still get compiler error with Var.

**Comment by fbricon** [comment]
Please try the latest Continuous Integration build, which can be installed from http://download.jboss.org/jbosstools/jdt.ls/staging/. Download the most recent `java-<version>.vsix` file and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

**Comment by anyflow** [comment]
Same issue arises on me. I've installed version 0.36.0(the latest version) via Java Extension Pack(version 0.5.0), and using Java 11(11.0.1).

Whether or not I designated Java 11 path on java.home, vscode spit an error with var keyword.

The belows are a part of Java Language Server log file. The server seems to load Java 11.
```
!ENTRY java-debug 1 0 2018-12-28 09:51:33.959
!MESSAGE Stopping com.microsoft.java.debug.plugin
!SESSION 2018-12-28 09:54:15.852 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=ko_KR
Command-line arguments:  -data /Users/anyflow/Library/Application Support/Code/User/workspaceStorage/eb80e8e43067d7bf2770fd3973a22754/redhat.java/jdt_ws

```
