### ISSUE TITLE
Fix all imports in single quick fix action

### ISSUE THREAD

**Issue by gitorko** [redhat-developer/vscode-java#490]
![capture1](https://user-images.githubusercontent.com/616726/38328521-c44e92c0-3868-11e8-9239-222811945226.PNG)

Is there an option to fix all imports in single action similar to netbeans? 

Quick fix supports this one line at a time. However would be nice if all imports got fixed in single go. When we copy code from other places resolving the imports one line at a time is time consuming.

**Comment by fbricon** [comment]
There's an "Organize imports" command (Ctrl+Shift+o)

**Comment by fbricon** [comment]
Closing as  duplicate of #56.

You can also organize imports as a [save action](https://github.com/redhat-developer/vscode-java/pull/402).

**Comment by gitorko** [comment]
@fbricon 
Ok gave that a try, it works. all unambigous imports are added.

I was earlier doing organize imports via the quick fix helper so wasnt seeing quick fix when there were no imports. Once i did Alt+Shift+O or right click and Organize Imports it adds those import statements automatically. Thanks.

**Comment by ZaLiTHkA** [comment]
just out of curiosity, is it possible to perform the "Organise Imports" action on multiple files?

I've been tasked with refactoring a ton of projects from Ant to Maven, so I have a rather large number of `import x` statements to update at the moment.. so I'm wondering of this action could help me here?
