### ISSUE TITLE
Missing progress during startup

### ISSUE THREAD

**Issue by rsalvador** [redhat-developer/vscode-java#494]
After this change https://github.com/redhat-developer/vscode-java/pull/387 the extension now shows progress for background processes, but still doesn't show progress for most of the startup sequence, for example it doesn't show progress for the build performed during startup here: https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java#L312

##### Environment
- Operating System: Mac OS 10.13.4
- JDK version: 1.8.0_152
- Visual Studio Code version: 1.21.1
- Java extension version: 0.22.0

##### Additional Information

See attached video for the startup progress. It would be good to show progress for any startup tasks that take appreciable time.

[vscode-startup.mp4.txt](https://github.com/redhat-developer/vscode-java/files/1879411/vscode-startup.mp4.txt)

**Comment by jdneo** [comment]
Should be available via `Java: Show Build Job Status`
