### ISSUE TITLE
Running the contributed command:'java.open.output' failed. - Language server crashes

### ISSUE THREAD

**Issue by hrsto** [redhat-developer/vscode-java#496]
After a some 5 minutes of running with a java project, the java language server crashes and there is no intellisense.

VS Code notification says: `Running the contributed command:'java.open.output' failed.`

##### Environment
- Operating System: Windows 10
- JDK version: 9.0.1 and 9.0.4
- Visual Studio Code version: latest
- Java extension version: latest

##### Steps To Reproduce
1. Just open any java project
2. After a while, say 5 mins, intellisense stop working, nothing is recognized

Developer tools log:
[-1523010033903.log](https://github.com/redhat-developer/vscode-java/files/1883562/-1523010033903.log)

**Comment by hrsto** [comment]
Actually it happen even without any open projects. Just plain VSCode with Java Language mode (selected manually from bottom-right corner of VS Code window). Empty Untitled-1 file.

**Comment by fbricon** [comment]
Can you run `jps` from a terminal and see if you have any org.eclipse.equinox.launcher_*.jar process running? Get a thread dump of those processes (`jstack <process-id>`). Kill those processes and try again.

**Comment by hrsto** [comment]
Before i launch anything, `jps` shows just it's own process. After i launch VS Code, `jps` show it's own process and `6716 org.eclipse.equinox.launcher_...jar`. After a while the pid of `equinox.launcher` changes - this coincides with the language server crash and the `Running the contributed command:'java.open.output' failed.` error. Subsequent `jps` executions will show only `jps`'s own pid, nothing else.

Here's a thread dump from equinox process while VS Code was running and working.
[equinox-thread-dump.txt](https://github.com/redhat-developer/vscode-java/files/1884187/equinox-thread-dump.txt)

Now i see there is one more thing. In vs code output window i get the following. Crash occurs even with just an Untitled-1 file set to Java language mode, i didn't type anything, no folders opened:

> WARNING: Using incubator modules: jdk.incubator.httpclient
> [Warn  - 4:50:29 PM] Apr 6, 2018, 4:49:55 PM The workspace will exit with unsaved changes in this session.
> [Info  - 4:50:30 PM] Connection to server got closed. Server will restart.

Tried to completely reinstall vs code (deleting AppData/Roaming/Code; deleting Users/me/.vscode) and the JDK/JRE. Very strange. The whole thing used to run flawlessly for so long...

**Comment by fbricon** [comment]
Shooting in the dark here: can you disable whatever antivirus you have running (you might want to disconnect your internet connection) and try again?

**Comment by fbricon** [comment]
@snjeza any ideas?

**Comment by hrsto** [comment]
Well... i don't use anything outside the Windows out of the box things. Disabled Windows Firewall/Defender/Safescreen... didn't help.

However... i ran VS Code as an **ADMINISTRATOR** using the **same settings file, same extensions**. So far Language Server hasn't crashed. Neither in the Untitled-1 empty file or a Java project. I will leave it for a while like that and monitor it. `jps` reports the same `equinox` pid since launch.

Can we keep this open for a day or two? Will keep tab open and come back and close it in a day-two, if it doesn't go nuts on me again.

Thank you for your time and ideas. The `jps` was extremely helpful.

**Comment by fbricon** [comment]
> However... i ran VS Code as an ADMINISTRATOR using the same settings file, same extensions. So far Language Server hasn't crashed.

@aeschli @yaohaizh @hexiaokai does it make sense?
