### ISSUE TITLE
How to hide warning box after go to next/previous error/warning/info

### ISSUE THREAD

**Issue by erihanse** [redhat-developer/vscode-java#497]
After pressing F8/Shift F8 we can toggle next/previous error/warning/info. I expect there to be a way to cross out this box to hide it, or even better: pressing escape hides it. What is the intended way to hide this box if possible?

![image](https://user-images.githubusercontent.com/9251274/38470546-c1a3c49c-3b64-11e8-96ea-c038a75a8005.png)

**Comment by fbricon** [comment]
This is a [vscode](https://code.visualstudio.com/docs/editor/editingevolved#_errors-warnings) behaviour, nothing specific to vscode-java. Pressing `esc` closes the warnings/errors for me.  If that doesn't work for you, please open a ticket at https://github.com/Microsoft/vscode/issues
