### ISSUE TITLE
Rename extension name from 'Language Support for Java(TM) by Red Hat' to 'Java'

### ISSUE THREAD

**Issue by pretodor** [redhat-developer/vscode-java#498]
I would like to suggest the extension be renamed from 'Language Support for Java(TM) by Red Hat' to 'Java'. This way the name will be consistent with the extensions for:

- [Python][python]
- [C/C++][c/c++]
- [C#][c#]
- [Go][go]

[python]: https://marketplace.visualstudio.com/items?itemName=ms-python.python
[c/c++]: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
[c#]: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
[go]: https://marketplace.visualstudio.com/items?itemName=lukehoban.Go

**Comment by gorkem** [comment]
Java is a trademark and Oracle has some restrictions to its usage on product names. We can not really use plain "Java" as the name of the extension.
