### ISSUE TITLE
extract method doesn't work with empty lines

### ISSUE THREAD

**Issue by darkgem666** [redhat-developer/vscode-java#499]
Extract method refactoring doesn't work when there's an empty line between to instructions that you want to extract to the same method.

##### Environment
- Operating System: Mac OS X 10.3.4
- JDK version: 8
- Visual Studio Code version: 1.22.1
- Java extension version: 0.22.0 

##### Steps To Reproduce
1. Open any java file
2. Try to extract method selecting 2 or more lines that I have an empty line between them.

##### Current Result
The extract method option is not available

##### Expected Result
Extract method option should be available

**Comment by fbricon** [comment]
Well, actually it works for me:

![extract-ml-method](https://user-images.githubusercontent.com/148698/38559529-4587773a-3ca1-11e8-91cf-255ad920bfb9.gif)

**Comment by fbricon** [comment]
Just select some code and a Code Action icon (light bulb) will appear. Either click on it or do `Ctrl+.` (`Cmd+.` on Mac) to display the available action(s).

If you see some cases where it doesn't work, please attach a screencast.
