### ISSUE TITLE
Deleted/Renamed modules are rebuilt as empty projects

### ISSUE THREAD

**Issue by alexandervalencia** [redhat-developer/vscode-java#502]
When deleting or renaming OSGi modules in a gradle project the renamed/deleted folder will be recreated as (mostly) empty with the following file structure:
```
root-module
|- bin
|   |- .project
| - .project
```

Image of original folder "my-npm-react-portlet" recreated after being renamed to "alex-react-portlet": 
<img width="173" alt="screen shot 2018-04-11 at 10 25 31 am" src="https://user-images.githubusercontent.com/22045453/38633047-4ebc5de8-3d73-11e8-8a77-17e25f96c16f.png">

##### Environment
- Operating System: macOS Sierra 10.12.6
- JDK version: 1.8.0_141
- Visual Studio Code version: 1.22.1
- Java extension version: 0.22.0

##### Steps To Reproduce
1. Create new OSGi module
2. Remove or rename root folder
3. Restart VSCode--deleted folder is recreated

##### Current Result
Deleted folders come back (almost) empty with .project files.

##### Expected Result
Deleted/renamed folders/modules stay deleted.

Thanks!
Alex

**Comment by fbricon** [comment]
Can you please attach a sample project?
