### ISSUE TITLE
Extra bracket generated when auto-completing constructor

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-java#503]
When creating a class instance with nested constructor calls, an extra bracket is generated when pressing Enter to confirm. Here's a screen recording that shows how to reproduce.

![extra bracket](https://user-images.githubusercontent.com/16755094/38662891-0fba8778-3e68-11e8-8c95-82199b6d1fde.gif)

**Comment by fbricon** [comment]
I think the 1st closing parenthesis is automatically added by vscode-java as you type `(`, then applying the completion adds the originally exoected closing `)`. Not sure who's to blame here honestly.

**Comment by fbricon** [comment]
you can reproduce by just typing `new String(` then tab or enter, this has nothing to do with nested declarations.

**Comment by snjeza** [comment]
VS Code adds an extra bracket.  You won't be able to reproduce the issue if you set the 'editor.autoClosingBrackets' property to false.

**Comment by jdneo** [comment]
@akaroml @fbricon @snjeza 

It seems that the VS Code team has fixed this issue in the Insider version.

![image](https://user-images.githubusercontent.com/6193897/63820203-f085bb80-c97a-11e9-9b34-bc67b5c672a8.png)

See gif below:

![demo](https://user-images.githubusercontent.com/6193897/63820248-0bf0c680-c97b-11e9-93a6-89f7b3383b98.gif)

**Comment by jdneo** [comment]
Tested in VS `Code@1.64.0` + `vscode-java@1.3.0`. The issue has been resolved.

**Comment by jdneo** [comment]
Closed as fixed.
