### ISSUE TITLE
Generate package declaration with class code snippet

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-java#505]
When generating a code snippet for class, the class name is correct, but the package declaration is missing.
![image](https://user-images.githubusercontent.com/16755094/38721025-2a0a5838-3f2b-11e8-82d6-270ea70dc06a.png)

The language server already has the knowledge because user can fix this using quick fix suggestion. So please also generate the package declaration along with the class body.

Reported by @biezhi

**Comment by fbricon** [comment]
the `class` template is currently coming from the vscode extension and is rather dumb. Instead, we'd need to generate a specific completionItem, server side, with a whole new template. This is currently not provided by jdt AFAIK.
@yaohaizh wanna give it a shot?
