### ISSUE TITLE
My package is not detected

### ISSUE THREAD

**Issue by tormath1** [redhat-developer/vscode-java#506]
Issue Type: <b>Bug</b>

#### 1. Create a java project. 

```shell
└── src
    ├── main
    │   ├── java
    │   │   └── com
    │   │       └── company
    │   │           └── scheduler
    │   │               ├── App.java
    │   │               └── middleware
    │   │                   └── Middleware.java
    │   └── resources
    │       ├── resource.json
    │       └── log4j2.xml
    └── test
        └── java
            └── com
                └── company
                    └── scheduler
                        └── middleware
                            └── MiddlewareTest.java
```

My `MiddlewareTest` runs perfectly with `gradle` however in `MiddlewareTest.java` my package is not recognised.

```java
package com.company.scheduler.middleware;
```

Is red underlined, with this message: 

> The declared package "com.company.scheduler.middleware" does not match the expected package ""

Ask me if you need more informations, thanks ! 

Extension version: 0.22.0
VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T00:24:49.616Z)
OS version: Linux x64 4.15.15-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2700)|
|Load (avg)|2, 2, 2|
|Memory (System)|7.29GB (0.18GB free)|
|Process Argv|/opt/visual-studio-code/code .|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by fbricon** [comment]
can you please attach your sample project here, including all the gradle files?

**Comment by tormath1** [comment]
Hi ! 

Thanks for your response. After restarting vscode, my project has been updated. Sorry for the issue. :disappointed:

**Comment by debjit1702** [comment]
> can you please attach your sample project here, including all the gradle files?

package com.company.scheduler.middleware;
public class Main{	// Entrypoint into the application
	public static void main(String[]args){
		System.out.println(“Hello World”);
	}
}
