### ISSUE TITLE
Allow disabling of underlying language server settings

### ISSUE THREAD

**Issue by ThadHouse** [redhat-developer/vscode-java#507]
I have project that has a lot of `@SuppressWarnings` annotations for pmd and checkstyle. The eclipse parser however does not know about these extra warning names, and because of this intellisense has a warning on every usage. This is a bug in the backing language server, but however the recommendation for years has been to disable all Unhandled Token warnings in eclipse. However, I can't find a way to set that from the vscode extension. I don't expect the actual backing issue fixed in here, but being able to disable that warning would be really helpful.

https://stackoverflow.com/questions/5017569/unsupported-suppresswarningspmd-donotcallsystemexit

![warningmessage](https://user-images.githubusercontent.com/7727148/38758132-7284e58a-3f24-11e8-8e39-627e6916e9ec.PNG)

**Comment by fbricon** [comment]
See https://github.com/eclipse/eclipse.jdt.ls/issues/581#issuecomment-373804678
set `org.eclipse.jdt.core.compiler.problem.unhandledWarningToken=ignore`

**Comment by ThadHouse** [comment]
That doesn't seem to work for that error. I have both done a full rebuild, along with a restart and I am still getting the warning.

**Comment by fbricon** [comment]
works for me, after a restart

**Comment by ThadHouse** [comment]
Ah I didn't realize that the setting had to be set in every project, and not just the root. Is there any way to avoid that?

**Comment by fbricon** [comment]
not at the moment

**Comment by fbricon** [comment]
Related to https://github.com/eclipse/eclipse.jdt.ls/issues/624

**Comment by ThadHouse** [comment]
We've been getting more and more complaints about this specific warning from our users. It seems kind of backwards that a warning specifically designed to suppress warnings is actually causing more warnings. I feel like that warning specifically should be silenced by default, because otherwise its backwards from what it actually is designed to do.

**Comment by fbricon** [comment]
"Unsupported SuppressWarning" warnings are now ignored by default. To get a different behaviour, one needs to set org.eclipse.jdt.core.compiler.problem.unhandledWarningToken=ignore|warning|info|error
