### ISSUE TITLE
Move 'Organize Imports' to be a CodeAction

### ISSUE THREAD

**Issue by mjbvz** [redhat-developer/vscode-java#513]
Hi, I'm on the vs code team. We recently introduced a more standardized way to implement `Organize Imports` with code actions (https://github.com/Microsoft/vscode/issues/47845). Using code actions instead of commands allows vs code to provide a more standard and consistent experience across languages. We are also using the new code action based implementation to power new UI like the `Source Action` context menu

![screen shot 2018-04-18 at 11 59 22 am](https://user-images.githubusercontent.com/12821956/38952303-f8adc1e8-42ff-11e8-8548-d2e3be8c99d0.png)

Our JavaScript and TypeScript organize imports feature has already been migrated from a command to a code action: https://github.com/Microsoft/vscode/issues/46647 I suggest that the Java extension do the same so that the developer experinace is more consistent and to prevent conflicts with other extensions. This is currently blocked by https://github.com/Microsoft/language-server-protocol/issues/389

**Comment by fbricon** [comment]
Now that https://github.com/eclipse/eclipse.jdt.ls/issues/796 was merged, this should be doable.
@mjbvz do you know if it's possible to bind keys to a code action?

**Comment by fbricon** [comment]
The `Organize imports` command is no longer available directly at the root of the context menu, via  the `Source actions...` menu:  

![new-organize-imports](https://user-images.githubusercontent.com/148698/48855569-57d66580-ed82-11e8-95a9-80ded6efdd91.gif)


The `Shift+Alt+o` shortcut is still working as before.
