### ISSUE TITLE
vscode intellisense pop up truncates the api details.

### ISSUE THREAD

**Issue by gitorko** [redhat-developer/vscode-java#514]
![vscode-intellisense](https://user-images.githubusercontent.com/616726/39035320-32aba962-4497-11e8-8653-1f8dfc9404a4.PNG)

There is a vertical scroll bar but no horizontal scroll bar. 

vscdoe: 1.22.2

**Comment by fbricon** [comment]
This is not controlled by vscode-java. Please open an issue in https://github.com/Microsoft/vscode/issues

**Comment by fbricon** [comment]
Can no longer reproduce with vscode 1.23.1
