### ISSUE TITLE
var inferred type not shown in an enhanced for loop

### ISSUE THREAD

**Issue by rlundy** [redhat-developer/vscode-java#515]
When I use var to declare the loop variable in an enhanced for loop, VS Code doesn't display the correct inferred type.

##### Environment
- Windows 10
- 10 (2018-03-20); JSE runtime 18.3
- Visual Studio Code version: 1.22.2
- Java extension version: 0.23.0 (April 16th, 2018)

##### Steps To Reproduce
1. Create a new Java project as you see fit.
2. Create a new Java class file and create a class in it.
3. In the class, put this method:

```
    private void infer()
    {
        String[] x = {"a", "b"};
        for (var y : x)
        {
            
        }
    }
```

4. Hover over `y` and examine the information shown.
5. In the loop braces, type `y.` and examine the autocomplete results.

##### Current Result
`y` is typed as `Object`.

##### Expected Result
`y` is typed as `String` (or as the relevant type for any such enhanced for loop).

**Comment by fbricon** [comment]
Same problem exists in Eclipse JDT. I'll check with the latest JDT build to see if it's fixed

**Comment by fbricon** [comment]
Same issue with latest JDT build. I opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=533884

**Comment by oakad** [comment]
Still have this issue with extension version 0.3

> [Java] var cannot be resolved to a type
> [Java] Type mismatch: cannot convert from element type String to var
