### ISSUE TITLE
Broken syntax highlighting for multiple exceptions.

### ISSUE THREAD

**Issue by ghost** [redhat-developer/vscode-java#516]
Syntax highlighting breaks when I have more than one exception
##### Environment
- Operating System: Mac OSX 10.13.4
- JDK version:
     java 10.0.1 2018-04-17
    Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
    Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
- Visual Studio Code version: Version 1.23.0-insider (1.23.0-insider)
- Java extension version: 0.23.0 (April 16th, 2018)

##### Steps To Reproduce
1. import some exceptions
2. throw a couple in a method
3. colourizing is erroneous

##### Current Result
![output](https://user-images.githubusercontent.com/23425023/39095123-90a08e16-4609-11e8-9923-13cd8729488d.png)

##### Expected Result
![expected](https://user-images.githubusercontent.com/23425023/39095126-94e381ea-4609-11e8-9072-ad09ce354996.png)

##### Additional Informations
I know this is trivial but it's annoying.

**Comment by Halcyonations** [comment]
My bad 

Alternative FileNotFoundException is a subclass of alternative IOException

**Comment by fbricon** [comment]
There are 2 problems actually:
- If the opening brace is on a new line after the method declaration, the last Exception is colorized differently when there are multiple exceptions
- in the catch statement, regardless of the opening brace position, the the last exception is colorized differently when there are multiple exceptions.

The textmate syntax for java is actually owned by [vscode](https://github.com/Microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json), upstream, which gets it from [atom](https://github.com/atom/language-java/blob/master/grammars/java.cson), so we can't fix it directly.

**Comment by Halcyonations** [comment]
@fbricon I actually closed because I realized that the exceptions where inherited from each-other.

**Comment by fbricon** [comment]
@Halcyonations the issue is real, you can check with other exceptions

**Comment by Halcyonations** [comment]
@fbricon Yep, mb. 😅

**Comment by fbricon** [comment]
See upstream PR: https://github.com/atom/language-java/pull/144

**Comment by fbricon** [comment]
This has been fixed some time ago.
