### ISSUE TITLE
Errors not shown

### ISSUE THREAD

**Issue by wimalopaan** [redhat-developer/vscode-java#519]
If I remove a method no error ist shown on the callers side.

In the example below, there is no static method test() in class B but no error is reported in editor of file A.java.

##### Environment
- Operating System: Linux
- JDK version: 8
- Visual Studio Code version: 1.22
- Java extension version:0.23

##### Steps To Reproduce

Use the following two Java files:

A.java:
```
public class A {
    public static void main(String[] args) {
        B.test();
    }
}
```
B.java
```
class B {
}
```

**Comment by yaohaizh** [comment]
@wimalopaan Need more information for this issue. Could you share your sample project?
