### ISSUE TITLE
Add command to create new Java formatter settings

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#521]
Following up on https://github.com/redhat-developer/vscode-java/pull/517#issuecomment-384768400:
> The idea is to give users something to start from. So the command would be like "Add Java formatter settings", maybe ask for a file location, a complete formatter xml file would be added there and the java.formatter.url would be updated

**Comment by snjeza** [comment]
Requires https://github.com/eclipse/eclipse.jdt.ls/pull/640 and #517.
