### ISSUE TITLE
Failed to install 'redhat.java'.

### ISSUE THREAD

**Issue by ozzioma** [redhat-developer/vscode-java#522]
Why am I getting this error when I try to install

> Failed to install 'redhat.java'.

This is my environment
Windows 10 Home x64
JDK 8
Latest Visual Studio Code

Every other extension installs but only Java extensions repeated fail.
What could be wrong?

**Comment by fbricon** [comment]
As @gorkem said, that's happening before vscode-java is involved, so it's really more a vscode problem. I suggest you open an issue at https://github.com/Microsoft/vscode/issues/, the vscode team will be able to provide you with steps to troubleshoot the issue.

I can just tell you to check if you have some `redhat.java*` folders in `%USERPROFILE%\.vscode\extensions` and delete them before retrying.

**Comment by yaohaizh** [comment]
Close this since this is vscode related project.
