### ISSUE TITLE
Syntax Highlighting for SQL in Strings?

### ISSUE THREAD

**Issue by scgm11** [redhat-developer/vscode-java#525]
Have syntax highlighting for SQL inside Strings

##### Environment
- Operating System: Mac OS High Sierra
- JDK version: JDK 8
- Visual Studio Code version: 1.22.2
- Java extension version: 0.24.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
No Highlighting on SQL inside Strings
##### Expected Result
Have Syntax Highlighting

**Comment by fbricon** [comment]
SQL support is outside the scope of vscode-java and the Java syntax highlighting is provided by vscode itself. 
I believe what you need is a way to *inject* language highlighting into another language file, similar to https://stackoverflow.com/questions/30753512/intellij-idea-syntax-highlighting-of-sql-inside-java-code. Please open an enhancement request in https://github.com/Microsoft/vscode/issues
