### ISSUE TITLE
Incomplete module-info.java syntax highlighting

### ISSUE THREAD

**Issue by augustocdias** [redhat-developer/vscode-java#527]
I've cloned this project https://github.com/verhas/module-test and opened as it is and the extension fails to recognize the project. In fact it does not even provide syntax highlighting for the module files.

##### Environment
- Operating System: Max OS
- JDK version: tested with 10 and 9
- Visual Studio Code version: 1.22.2
- Java extension version: 0.24.0

![code](https://user-images.githubusercontent.com/1080789/39565058-d43dde20-4eb6-11e8-8a26-52cd2fdb1619.png)

Here's the log:
[log.log](https://github.com/redhat-developer/vscode-java/files/1969968/log.log)

**Comment by fbricon** [comment]
Your source/target 1.9 are not valid, [according to the javac spec](https://docs.oracle.com/javase/10/tools/javac.htm#GUID-AEEC9F07-CB49-4E96-8BC7-BCC2C7F725C9__GUID-B4EE2436-E146-428D-A3CB-E0DAE27BA5B7) (even though it currently works from CLI for the Oracle JDK, it might fail in a future version or for others JVMs).

Try source/target = 9

**Comment by augustocdias** [comment]
It worked but still I have no coloring in the module definitions, which can be theme's fault... What are the scope names for the textMateRules to customize them?

**Comment by fbricon** [comment]
So this is a problem with the [java textmate bundle](https://github.com/atom/language-java/) vscode [uses](https://github.com/Microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json#L3). This bundle is maintained by the Atom team, you'll see the same coloring issue in Atom. Can you open a ticket there?

**Comment by snjeza** [comment]
See https://github.com/atom/language-java/pull/143
