### ISSUE TITLE
cannot find class to run in multi root workspace

### ISSUE THREAD

**Issue by myguddy** [redhat-developer/vscode-java#532]
VSCode Version: 1.23.1
OS Version: High Sierra 10.13.4
Steps to Reproduce:

1.Create simple java and configure the launch.json
{
"type": "java",
"name": "Debug (Launch)-Main",
"request": "launch",
"cwd": "${workspaceFolder}",
"console": "internalConsole",
"stopOnEntry": false,
"mainClass": "Main",
"args": ""
},
2.run task then ok
3.create multi-root-workspace
4.add the directory(step1.)
5. run task
error come out "java.lang.ClassNotFoundException: ...."

**Comment by yaohaizh** [comment]
This issue was moved to Microsoft/vscode-java-debug#299

**Comment by andxu** [comment]
@myguddy Thanks for using vscode java debugger, can you provide us the folder structure: by
```
cd <your project >
tree`
```
and give us the snapshot of the error popup?
