### ISSUE TITLE
Possible to update Gradle version ?

### ISSUE THREAD

**Issue by colinrc** [redhat-developer/vscode-java#544]
I was wondering if it is possible to update the internal Gradle version used.  It would be great to be able to use Gradle's native Junit 5 support but that needs Gradle 4.6 or higher. 

The internal version with the extension seems to be 4.3 - is that correct?

**Comment by fbricon** [comment]
can't you define a gradle wrapper pointing at 4.6+?
Do you have a sample project exposing the issue?

**Comment by colinrc** [comment]
I have one project that works and another which won't import with identical test code in the gradle file.

test {
    useJUnitPlatform ()
    testLogging {
        // Make sure output from
        // standard out or error is shown
        // in Gradle output.
        showStandardStreams = true

    }
}

This is valid for 4.6 but likely invalid for 4.3, when I try to import the folder I get exceptions and the class path won't build, on the useJunit line.

org.gradle.tooling.BuildException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-4.3-bin.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.tr

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/colin/Projects/Health/auslab/build.gradle' line: 25
A problem occurred evaluating root project 'auslab'.
	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74)


Sorry, I can't share this project. I have tried to make another one, however it seems to parse - although the test runner cannot find any tests.

The gradle file works perfectly if I run it from bash (using gradle 4.7) so it does seem to be a 4.3 issue.

I haven't tried using a wrapper, will this still let me use the test runner extension ?

**Comment by colinrc** [comment]
An update - the same project that I was able to import once, I can no longer import. It gives me a class path issue as well, and the error line in the log file is the same.

From build.gradle
	useJUnitPlatform()

Trace...
(I can include the entire trace if desired).

Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/colin/Projects/junit5-samples/junit5-jupiter-starter-gradle copy/build.gradle' line: 18
A problem occurred evaluating root project 'junit5-jupiter-starter-gradle copy'.
	at org.gradle.initialization.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:74)
	at org.gradle.initialization.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:47)
	at org.gradle.initialization.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)

.....

**Comment by colinrc** [comment]
You can see the behaviour using the Junit teams example project for gradle. 

The git repo is 
https://github.com/junit-team/junit5-samples/tree/r5.2.0

**Comment by colinrc** [comment]
For anyone else with the same issue, I have found a work around, although I'm not sure if this is creating other issues due to the import process not fully processing the gradle file.

This is the steps that seem to help, I would still love to be able to import the file properly - it just needs a newer gradle version.


Comment out the Test task within gradle,
Import your project
Remove the comments

Once removing the comments the TestRunner plugin seems to find the tests correctly, and junit is found correctly as long as you add it via the maven repo


(for me the test task is )

test {
    useJUnitPlatform ()
    testLogging {
        // Make sure output from
        // standard out or error is shown
        // in Gradle output.
        showStandardStreams = true

    }
}

The requirements to find the junit libraries is the following to your dependencies


    testCompile "org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}" 
    testCompile "org.junit.jupiter:junit-jupiter-params:${junitJupiterVersion}"     
    testRuntime "org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}"

**Comment by colinrc** [comment]
solved - I built the gradle wrapper before importing the project and it worked perfectly!

Thanks for the suggestion.

**Comment by fbricon** [comment]
Closing stale issue. Embedded Gradle is now 6.3
