### ISSUE TITLE
Feature Request: Assign return value to new variable

### ISSUE THREAD

**Issue by jcjolley** [redhat-developer/vscode-java#547]
![assignreturnfromvariable](https://user-images.githubusercontent.com/2086176/40849990-b1260f12-6580-11e8-848c-a34a3d20b15a.gif)

One of my favorite Netbeans features is creating a new variable (correctly typed) from the return value of an expression.  The addition of this feature would greatly help ease my transition to VSCode for Java.

Thank you for your time and consideration.

**Comment by KaRkY** [comment]
Is there any progress on this issue?

**Comment by testforstephen** [comment]
@jcjolley @KaRkY The extension has provided the quick fix `extract to local variable` feature for return value.  The quick fix bulb will appear when the cursor stops at the bracket `()`. The keyboard shortcut is `ctrl + .`
![assignvariable](https://user-images.githubusercontent.com/14052197/54513143-654ad780-4991-11e9-9d4c-fecb693daf12.gif)

Did this resolve your issue?

**Comment by KaRkY** [comment]
@testforstephen yes that solves it for me.
