### ISSUE TITLE
Could not open Formatter Settings file

### ISSUE THREAD

**Issue by adrianmoya** [redhat-developer/vscode-java#548]
Hi, I'm trying to open the formatter settings by ctrl+shift+p -> Java open formatting settings. It asks for a path, I put the absolute path to my file "/home/adrian/java/eclipse-java-google-style.xml" and it says "Could not open Formatter Settings file". The file is there, was downloaded from git. Also, I tried putting a new file name and it says the same. File permissions are for my user: adrian:adrian.

##### Environment
- Operating System: Ubuntu Linux 16.04
- JDK version: OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
- Visual Studio Code version: 1.23.1
- Java extension version: 0.26.0

##### Steps To Reproduce
1. Ctrl+Shift+P -> Java: Open Java formatting settings
2. Type absolute path to an existing file and hit enter

##### Current Result

"Could not open Formatter Settings file" error is shown.

##### Expected Result

Formatter settings file opened.

##### Additional Informations
These are my settings:
```
{
    "java.jdt.ls.vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:\"/home/adrian/.vscode/extensions/GabrielBB.vscode-lombok-0.9.4/server/lombok.jar\" -Xbootclasspath/a:\"/home/adrian/.vscode/extensions/GabrielBB.vscode-lombok-0.9.4/server/lombok.jar\"",
    "maven.executable.path": "./mvnw",
    "java.completion.importOrder": [
        "com",
        "java",
        "javax",
        "lombok",
        "org"
    ],
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "editor.tabSize": 2,
    "editor.detectIndentation": false,
    "editor.insertSpaces": true,
    "extensions.autoUpdate": false,
    "java.import.gradle.enabled": false,
    "java.format.settings.url": "/home/adrian/java/eclipse-java-google-style.xml",
    "java.format.comments.enabled": false,    
}
```

What I notice from the logs is that the file I type in the input is not passed, instead it takes whatever value is there by default. I.E. I type "/home/adrian/java/eclipse-java-google-style.xml" and the logs show "gogglestyle,xml":
```
            "format": {
                "enabled": true,
                "settings": {
                    "url": "gogglestyle.xml",
                    "profile": null
                },
```
which was a random name I typed trying to make it work.

**Comment by snjeza** [comment]
@adrianmoya Could you check your workspace settings?

**Comment by swarnendubiswas** [comment]
I have a similar problem. I have the formatter settings file in `.settings/org.eclipse.jdt.core.prefs`. I also have the following set in `Workspace Settings`.
```
"java.format.settings.url": "${workspaceRoot}/.settings/org.eclipse.jdt.core.prefs"
```
However, opening the formatter settings do not work. It prompts for the path: `${workspaceRoot}/.settings/org.eclipse.jdt.core.prefs`, and then says "file does not exist". Trying to create one makes no difference.

**Comment by fbricon** [comment]
`${workspaceRoot}` or any other variables are not supported. 
Variables would need to be resolved before being sent to the server, not sure we can do that

**Comment by fbricon** [comment]
@snjeza I can reproduce the issue. https://www.screencast.com/t/TYPyGmgGgL

**Comment by snjeza** [comment]
@fbricon I'm working on that.

**Comment by zmunro** [comment]
I am on the latest version of VSCode for MacOS and this is still happening.

**Comment by snjeza** [comment]
@zmunro  could you send your setting.json and [server log](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
