### ISSUE TITLE
Support jumping to the override method from the sub class

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#553]
Is there any shortcut to jump to the original override method from the sub class's method?

**Comment by fbricon** [comment]
No there's no such support. How do you suggest it would look like? some code action?

**Comment by testforstephen** [comment]
Context menu or code lens both be OK.

**Comment by yyoncho** [comment]
IMO user should be able to access this functionality even with code lenses turned off.

**Comment by testforstephen** [comment]
Finally we decided to leverage the hover to expose the link to jump to the super implementation.

![image](https://user-images.githubusercontent.com/14052197/65011505-4cbe7880-d946-11e9-910a-6615653e66df.png)
