### ISSUE TITLE
Add "add missing import" quick fix/action

### ISSUE THREAD

**Issue by ivanz** [redhat-developer/vscode-java#56]
In order to quickly fix missing imports when pasting code or writing code - it would be great to have a quick fix to "add import" similarly to e.g. the C# vscode extension or various Java IDEs

**Comment by scgm11** [comment]
+1

**Comment by rubin55** [comment]
When! This is a great feature to have, especially since you can have quite a list of imports when you get going :-).

**Comment by typekpb** [comment]
well, as I'm used to from the eclipse world, I'd prefer to have: "Organize imports" functionality => add missing + remove unused (as those are already reported as warnings in "Problems" section).

To go one step further I'd love to see this functionality on the whole package as well (all files within would have imports organized).

**Comment by gorkem** [comment]
This is now available bot as part of code assist and a code action. closing

**Comment by apemberton** [comment]
Does this feature have the ability to "remove unused imports"?

**Comment by gorkem** [comment]
@apemberton yes, it does. It is also available as an action on the command palette
