### ISSUE TITLE
The progress text of import maven project first time is annoying [Keep on flashing]

### ISSUE THREAD

**Issue by andxu** [redhat-developer/vscode-java#567]
[provide a description of the issue]

##### Environment
- Operating System: Win10 64bit
- JDK version: 1.8
- Visual Studio Code version: 1.24.1
- Java extension version: 0.27.0

##### Steps To Reproduce
First time open the gs-spring-boot/complete folder:
https://github.com/spring-guides/gs-spring-boot-docker/tree/master/complete, the message "Refreshing Maven model" has pushed the progress bar text changing with one second interval:

![image](https://user-images.githubusercontent.com/17075863/41575564-98bfbd9a-73b5-11e8-81a1-971c1f28ce6c.png)

![image](https://user-images.githubusercontent.com/17075863/41575556-9341b648-73b5-11e8-9c6a-d8adad024461.png)

**Comment by yaohaizh** [comment]
@andxu, This is the design behavior of Java language server. We need this status for end user.
