### ISSUE TITLE
Moving files do not clear problems view for original file location

### ISSUE THREAD

**Issue by aholstenson** [redhat-developer/vscode-java#568]
When moving a file containing errors from one package to another the VS Code will continue to report errors for the original file location.

##### Environment
- Operating System: Linux
- JDK version: 1.8
- Visual Studio Code version: 1.25.0-insider
- Java extension version: 0.27.0

##### Steps To Reproduce
1. Create a new Java-file
2. Introduce a syntax error
3. Move the file using the explorer within VS Code

##### Current Result

Errors for the original file location and the new location is displayed in the Problems view.

##### Expected Result

Errors should only be displayed for the new location.

**Comment by yaohaizh** [comment]
@adelasofia  I cannot repro this on the latest VSCode java extension. Could you provider your example project and share your log by invoking commands "Java: Open Java Language Server log file"

**Comment by adelasofia** [comment]
@yaohaizh I think you tagged the wrong person 😃

**Comment by yaohaizh** [comment]
@aholstenson  I cannot repro this on the latest VSCode java extension. Could you provider your example project and share your log by invoking commands "Java: Open Java Language Server log file"

**Comment by aholstenson** [comment]
After investigating this more I can't reproduce it reliably. It does happen more frequently when I have several VS Code windows and projects open, so I'm thinking this is more likely to be a bug in VS Code than in this project.

I'm going to close this issue until such a time I can reproduce it reliably.
