### ISSUE TITLE
Support configurable indentation format for auto generator

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#570]
Currently, when creating a new method with the same name as the parent class, the language server will show the auto-complete list and auto generate the override method template, but the indentation it takes is `tab` by default. 

If the extension provides the configuration options to allow user to choose his favorite indentation  (for example, 2/4 white spaces or tab), that will be very helpful.

**Comment by yaohaizh** [comment]
Duplicate issue with: https://github.com/redhat-developer/vscode-java/issues/557

**Comment by fbricon** [comment]
Fixed with #557
