### ISSUE TITLE
Java 8 missing when Java 8 is installed ?

### ISSUE THREAD

**Issue by stehgold** [redhat-developer/vscode-java#571]
I get an error message: Java 8 or more recent is required to run. Please download and install a recent JDK

##### Environment
- Operating System:
Windows 10
- JDK version:
C:\Users\Stephan>java -version
 java version "1.8.0_171"
 Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)    
- Visual Studio Code version:
1.24.1
- Java extension version:
0.27.0
##### Steps To Reproduce
1. [step 1]
Just start vscode and the message pops up.
2. [step 2]
The funny thing is I can runJava code from within vscode using the "Play button".
[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
did you install a JDK or a JRE? (JDK required)
Have you tried setting the java.home preference in vscode settings?

**Comment by SudoNhim** [comment]
Thanks, for me setting the java.home path in settings.json worked.

I wasn't able to get it working from PATH. Is this a bug?
