### ISSUE TITLE
Use with Java Version < 8?

### ISSUE THREAD

**Issue by rdotg** [redhat-developer/vscode-java#573]
Because I run projects that run on multiple versions of Java (including Java 7), I receive this message in VS Code:

```
Java 8 or more recent is required to run. Please download and install a recent JDK
```

Is there a work around to use this plugin with Java versions less than 8 like Java 7?

##### Environment
- Operating System: macOS High Sierra
- JDK version: 7
- Visual Studio Code version: 1.24.1
- Java extension version: 0.27.0

**Comment by fbricon** [comment]
Are you trying to compile or run the projects? Are they based on Maven, Gradle or Eclipse?

**Comment by protoEvangelion** [comment]
I am not trying to compile or run the projects from VS Code.

My hope was to simply benefit from from other features like being able to look up functions within a java file or being able to hover over a function call and see its signatures.

Regarding what is the project based on, it's a Liferay project which uses Ant as it's build tool.

**Comment by Andriuslima** [comment]
Same problem here. Trying to change the 'java.home' properties in settings to JDK 6 and getting the same error message.

This plugin supports JDK versions < 8????
If not, I'm gonna stop using. That's is a bummer 

Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Comment by rgrunber** [comment]
You need to set `java.home` to point to a JDK 11 (or newer) for the runtime. However, for your projects, you can configure any JDK you like https://github.com/redhat-developer/vscode-java#project-jdks with `java.configuration.runtimes`.
