### ISSUE TITLE
couldn't read the .java file after renaming it

### ISSUE THREAD

**Issue by bazindes** [redhat-developer/vscode-java#578]
[provide a description of the issue]

##### Environment
- Operating System: OSX
- JDK version: 1.8
- Visual Studio Code version:1.24.1
- Java extension version:0.3.0

##### Steps To Reproduce
1. [step 1] create a abc.java and compile
2. [step 2] rename abc.java to abd.java and compile
3. [step 3] when run the code, the sever log file shows "!MESSAGE Error occured while building workspace. Details: 
message: The project was not built since the source file /jdt.ls-java-project/src/abc.java could not be read;
code: 0
"

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Fixed with https://github.com/eclipse/eclipse.jdt.ls/commit/064a6a57ff1eb751bf3cc6279909a97e126f501a
