### ISSUE TITLE
Syntax highlight and language parsing doesn't work on source-only subprojects

### ISSUE THREAD

**Issue by aegroto** [redhat-developer/vscode-java#584]
I have a main project which includes a subproject with no main class, using it as a library. I find it really comfortable while developing as i want to release those two projects separately later. However coding in the subproject is not pleasant as VS code keeps marking half of the code red, even if the compilation dependencies are satisfied. Build works correctly, so this is a linting only issue. I'm still a newbie so I can't exclude that this project structure is unreliable and brings to similar problems.

##### Environment
- Operating System: Ubuntu 16.04
- JDK version: 1.8
- Visual Studio Code version: 1.24.1
- Java extension version: 0.28.0

##### Steps To Reproduce
1. [step 1] Download https://github.com/aegroto/TowerMonkeyExample or create any project with a similar structure.
2. [step 2] Open it in VS code.

[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

Many errors are shown while coding, but builds works perfectly.

##### Expected Result

No errors about missing imports or package name should be shown if they're not present.

It's not easy to include logs as they're enormous. However, if required, I can provide any part of it.

**Comment by jdneo** [comment]
@aegroto I noticed that your project is using lombok, have you installed the lombok extension?
