### ISSUE TITLE
The value of the local variable XXXX is not used ERROR

### ISSUE THREAD

**Issue by zhanggang807** [redhat-developer/vscode-java#585]
[provide a description of the issue]

##### Environment
- Operating System: **macos high sierra**
- JDK version: **jdk1.8**
- Visual Studio Code version: **1.25.0**
- Java extension version: **0.28.0**

##### Steps To Reproduce
1. [step 1]  `int length = -1;
        try {
            FileInputStream fis = new FileInputStream(foo);
            while ((length = fis.read(buffer)) != -1) {
                System.out.println(new String(buffer));
            }
            fis.close();
        } catch (Exception e) {
            e.printStackTrace();
        }`
2. [step 2] 

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result 
The value of the local variable **length** is not used

##### Expected Result
should not appearance this error tip

**Comment by fbricon** [comment]
actually even though the `length` value is assigned, it's never accessed.
`while ((length = fis.read(buffer)) != -1)` is equivalent to `while (fis.read(buffer) != -1)`

Both Eclipse and Intellij IDEA report the same warning.
