### ISSUE TITLE
Org.Mockito cannot be resolved

### ISSUE THREAD

**Issue by JarrodBlanton** [redhat-developer/vscode-java#587]
Currently working on a Java8 Maven project (I have all of the Java extensions along with Maven for Java) and when trying to compile and run the tests, the compiler is throwing this error. 
![image](https://user-images.githubusercontent.com/6411787/42574938-9e376234-84ed-11e8-9201-250515147375.png)

My import statement is this:
`import static org.mockito.Mockito.*;`

I have tried everything short of importing the individual methods that I am using, but I don't believe that I should have to do that. Has anyone else encountered this problem?

**Comment by JarrodBlanton** [comment]
EDIT:

Several different variations:
![image](https://user-images.githubusercontent.com/6411787/42575446-8076a6e6-84ee-11e8-9721-4bb7e3d5745d.png)

When hovering over the error it says the following:
`The import org.mockito cannot be resolved

Mockito is a mock library for java - see org.mockito.Mockito class for usage`

**Comment by JarrodBlanton** [comment]
.classpath needed to be updated *face palm*

**Comment by andreydmitrenko** [comment]
@JarrodBlanton could you, please, tell me, what exectly I should write in my .classpath ? thanx.

**Comment by fbricon** [comment]
you're not supposed to update the .classpath manually. Normally, updating the dependencies in your pom.xml and saving the file should do all the work for you in the background. Sometimes you might need to right click on your pom.xml and trigger the "Update project configuration" command, but that's rather the case for plugin configuration changes.

@andreydmitrenko what exactly is your problem?

**Comment by yaohaizh** [comment]
@jdneo, have you met this issue on the vscode tester side?

**Comment by jdneo** [comment]
@JarrodBlanton Could you please try:

1. Trigger the command :`Java: clean the java language server workspace`
2. Select `restart and delete`
3. See if the errors still occur

**Comment by saumilsdk** [comment]
@jdneo Thanks that vs code command helped.
