### ISSUE TITLE
LSP functionality stops working very often

### ISSUE THREAD

**Issue by hexa00** [redhat-developer/vscode-java#592]
When editing code, the LSP functionally stops to works often, sometimes once every 2 minutes.

In the LSP logs I can see:

```
!ENTRY org.eclipse.jdt.ls.core 1 0 2018-07-18 13:47:53.406
!MESSAGE >> document/didSave
```

This is the last entry.

I can also do a ps and see the LSP still running:
```
/usr/lib/jvm/java-8-oracle/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:/home/a/.vscode/extensions/gabrielbb.vscode-lombok-0.9.4/server/lombok.jar -Xbootclasspath/a:/home/a/.vscode/extensions/gabrielbb.vscode-lombok-0.9.4/server/lombok.jar -jar /home/atremblay/.vscode/extensions/redhat.java-0.28.0/server/plugins/org.eclipse.equinox.launcher_1.5.100.v20180611-1436.jar -configuration /home/atremblay/.vscode/extensions/redhat.java-0.28.0/server/config_linux -data /home/atremblay/.config/Code/User/workspaceStorage/45a4e3cffe2ce93e37ee8055c276153a/redhat.java/jdt_ws
```

However in the VSCode LSP output I see that it is still trying to reach the LSP:

```
[Trace - 13:50:54] Sending request 'workspace/executeCommand - (427)'.
Params: {
```
.

However it seems these never reach the LSP, I see nothing in the logs of the LSP whatever I do.
Also I see a lot of Sending request but no responses there.

In the console log all I see is:

`WARN Aborted format on save after 750ms`

It's like it has lost communication ?

##### Environment
- Operating System: Ubuntu 18.04 (Can repoduce on Arch too)
- JDK version: 1.8
- Visual Studio Code version: 1.25.1
- Java extension version: 0.28.0

##### Steps To Reproduce
1. Hard to tell just edit code and it arrives eventually.

Is there a way I could debug this better ?

**Comment by hexa00** [comment]
Another one 
[threaddump2.txt](https://github.com/redhat-developer/vscode-java/files/2206968/threaddump2.txt)

Note that to get out of this situation I reload the window and thus create a new lsp.

The thread dumps you see are ones I took from JSP hanging processes that were not cleaned up after I did reload.

**Comment by hexa00** [comment]
OK this may take a while since I have less code to write ATM but I will report back asap.

What makes you think it could be the cause?

**Comment by fbricon** [comment]
since `com.microsoft.java.test.plugin.internal.JavaModelEventProvider.elementChanged` is in the stacktrace, I just want to rule it out

**Comment by hexa00** [comment]
Maybe too soon to tell but I started writing a lot of code to test and it seems to be much better.

**Comment by hexa00** [comment]
After a full day with no problems I think I can confirm the test extension is the culprit.

**Comment by julianosam** [comment]
Hey @hexa00 how did you disable the Test Runner extension only? I am trying to disable or even uninstall it but vscode won't let me. The only way is if I remove the entire extension pack.

**Comment by hexa00** [comment]
@julianosam that's what I did I removed the extension pack and reinstalled them separately :)

**Comment by yaohaizh** [comment]
Close this as it is tracked by vscode java tester.
