### ISSUE TITLE
Unusable after update to jdk1.8.0_181 x64

### ISSUE THREAD

**Issue by Nightenom** [redhat-developer/vscode-java#593]
It was working perfectly prior jdk update, it's unusable after jdk update - occasionally causes system lags, high CPU usage

##### Environment
- Operating System: W10 Pro, 1803, x64, 17134.165
- JDK version: jdk1.8.0_181 x64
- Visual Studio Code version: 1.25.1 x64
- Java extension version: 0.28.0

##### Steps To Reproduce
1. update jdk to the latest version

[attach a sample project reproducing the error]: any Forge Gradle project
[extension.log](https://github.com/redhat-developer/vscode-java/files/2216095/extension.log)

##### Additional Informations
A possible solution is jdk downgrade, but there is no public link to ver 171 or 172 (without the need of account creation)

**Comment by Nightenom** [comment]
@snjeza I did everything as you suggested even before I made this issue. Btw nice Windows commands.
I don't think that this looks like a working extension, this message appears in a log each minute
```
!ENTRY org.eclipse.jdt.ls.core 1 0 2018-07-23 15:00:17.785
!MESSAGE Starting Gradle update for minecoloniesLive
```

**Comment by Nightenom** [comment]
The Ctrl + left_mouse future for following a link works really slowly even when linking inside of one file

**Comment by snjeza** [comment]
Your project isn't build because timeout (five minutes) has expired.
```
!ENTRY org.eclipse.jdt.ls.core 1 0 2018-07-21 13:10:32.343
!MESSAGE Timeout while waiting for completion of job: Building workspace(4)
```

Building your project takes a few seconds on my machine when using the workaround described at https://github.com/redhat-developer/vscode-java/issues/582#issuecomment-406890086

@gorkem @fbricon can we increase the timeout when initializing a workspace? - https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java#L174

**Comment by Nightenom** [comment]
That won't be a solution, since my last comment, every action takes ages to happen after update (not just initializing or loading workspace)

**Comment by snjeza** [comment]
> That won't be a solution, since my last comment, every action takes ages to happen after update (not just initializing or loading workspace)

This issue can happen when a project isn't built (because of the timeout of five minutes, for instance)

> Edit: which workaround? I can't see any in both conversations

- build the project using the gradle command line
```
cd <YOUR_PROJECTS>/minecolonies
gradlew.bat build
```
- remove Eclipse files/directories
```
rm -rf .classpath .project .settings
```

- clean Java VS Code workspace -
https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory

- start VS Code
```
code .
```

See https://www.screencast.com/t/ZLhvho7VqE

**Comment by Nightenom** [comment]
I wouldn't call this a workaround but it didn't change anything
I just downgraded, it works better but still slower than before the upgrade

**Comment by snjeza** [comment]
Could you restart VS Code and attach your log again?

**Comment by Nightenom** [comment]
171: [171.log](https://github.com/redhat-developer/vscode-java/files/2240992/171.log)
181: [test.log](https://github.com/redhat-developer/vscode-java/files/2241038/test.log)
I gave each version around 15 minutes -> for me it now looks like something had changed/got an update in the same time I upgraded jdk so it might be a different cause

**Comment by Nightenom** [comment]
Can it be `"java.configuration.updateBuildConfiguration": "automatic"`?

**Comment by snjeza** [comment]
Your issue can be caused by setting "java.configuration.updateBuildConfiguration" to "automatic" . Your project builds too often. Try to set "java.configuration.updateBuildConfiguration" to "interactive"?

**Comment by Nightenom** [comment]
I did but the popup gets a bit annoying over time

**Comment by fbricon** [comment]
then set it to "never"

**Comment by Nightenom** [comment]
Setting it to "never" is not so handy, is there a way to call it manually from the console?

**Comment by Nightenom** [comment]
Or can I call it when executing a gradle command?

**Comment by snjeza** [comment]
Could you try the following (File>Preferences>Settings):

```
"java.configuration.updateBuildConfiguration": "disabled",
```

**Comment by Nightenom** [comment]
Why I should disable it?

**Comment by snjeza** [comment]
> Why should I disable it?

To avoid the popup window.

**Comment by Nightenom** [comment]
It will not disable the function?

**Comment by snjeza** [comment]
> It will not disable the function?

It won't. Your project will be built when you start VS Code or call Ctrl-Shift-P>Java:Update Project Configuration.

**Comment by Nightenom** [comment]
Ok, thanks, closing
