### ISSUE TITLE
Bulk generation would be useful

### ISSUE THREAD

**Issue by yaohaizh** [redhat-developer/vscode-java#597]
From the thumbups emoji  of this closed issue: 

https://github.com/redhat-developer/vscode-java/issues/100

> bulk generation like in jetbrains or eclipse would be pretty useful also.
> 
> And would be nice to have generators not only for getters and setters, but also for constructors, toString, hashCode, equals and overrides

**Comment by fbricon** [comment]
See https://github.com/eclipse/eclipse.jdt.ls/issues/163

**Comment by yaohaizh** [comment]
- `Add override/implement methods` code generation

**Comment by fbricon** [comment]
Bulk generation of getters/setters is now available. The associated source action kind is "source.generate.accessors". 
Keybinding is [partially broken at the vscode level though](https://github.com/Microsoft/vscode/issues/64824).

But if/when it works, adding something like this to one's keybinding.json should do the trick
```
{
        "key": "shift+alt+g",
        "command": "editor.action.sourceAction",
        "args": {
          "kind": "source.generate",
        }
}
```

**Comment by testforstephen** [comment]
Add `Generate Constructor` code generation.

**Comment by yaohaizh** [comment]
Close this issue. The left one will be tracked on #972

**Comment by xiuluo211314** [comment]
![image](https://user-images.githubusercontent.com/17724127/87239297-2c652a80-c440-11ea-86f1-0538d130217a.png)
open keybinding.json file, and add code like @fbricon  said， back to the editor , you can get it!
