### ISSUE TITLE
Extension JDK search does not match gradlew JDK search

### ISSUE THREAD

**Issue by ThadHouse** [redhat-developer/vscode-java#599]
We have some users who are using gradlew based projects, and in all cases their project builds properly through the command like and gradlew. However, when they attempt to open their project in VS Code, some get an error saying a JDK cannot be found. Through some testing, we've determined that the extension only searches either its vs code variable, JDK_HOME or JAVA_HOME. However, gradlew also directly searches the path for java as well. Its order is first check JAVA_HOME, and then check path. This extension should also check in path in case the specific environmental variables were not found.

**Comment by jdneo** [comment]
Close since we now have embedded JDK now. And using `jdk-utils` to do JDK installation search when necessary.
