### ISSUE TITLE
Language Support Java(TM) by Red Hat cannot lanuch

### ISSUE THREAD

**Issue by BigZG** [redhat-developer/vscode-java#609]
Issue Type: <b>Bug</b>

The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

Extension version: 0.29.0
VS Code version: Code - Insiders 1.27.0-insider (b00ab5288f314f6ef8d82923d89a0555ad15eb06, 2018-08-16T09:38:37.976Z)
OS version: Windows_NT x64 10.0.17738

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (3.86GB free)|
|Process Argv|G:\VSCode\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|67%|

</details>

**Comment by fbricon** [comment]
I'm closing the many duplicates for this issue, please keep an eye on #112 for further informations.
