### ISSUE TITLE
[Question] Is it possible to get the add-on working with JDK 7?

### ISSUE THREAD

**Issue by Xivolkar** [redhat-developer/vscode-java#61]
I would really love to use this extension and VS Code but we aren't yet on JDK 8 and so are many enterprises I'd guess.

**Comment by fbricon** [comment]
No this is not possible. The Java Language Server is built on the Eclipse JDT and m2e projects which require Java 8 to run.

I feel for you being stuck on Java 7 but there's nothing we can do on our side

**Comment by gorkem** [comment]
In the next release we will bring in the option to specify a Java path that will be used for running the vscode extension, see #28. This will allow developers to use a different JDK other than the system JDK for running the extension. So you will be able to use a JDK 8 for running the extension but the rest of your system will still be able to use an earlier JDK. Does that help with your case?

**Comment by Xivolkar** [comment]
Well, I'll take a look when that is released 🙂
