### ISSUE TITLE
There is no document formatter for 'java'-files installed.

### ISSUE THREAD

**Issue by xriu** [redhat-developer/vscode-java#610]
There is no document formatter for 'java'-files installed.

##### Environment
- Operating System: Xubuntu 18.04
- JDK version: 
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

- Visual Studio Code version:
1.26.1
493869ee8e8a846b0855873886fc79d480d342de
x64

- Java extension version: 0.29

##### Current Result

I can't format any java files.

On output console I get the following error:

```
[Error - 12:59:23 PM] Connection to server is erroring. Shutting down server.
[Error - 12:59:23 PM] Connection to server is erroring. Shutting down server.
```

**Comment by xriu** [comment]
Sorry for late response, I don't remember how I fixed the problem, but I think just reinstalling vscode and their extensions again

**Comment by szaffarano** [comment]
I had the same problem.  It seems that there is a conflict with [Java Checkstyle plugin](https://marketplace.visualstudio.com/items?itemName=shengchen.vscode-checkstyle).  After I uninstalled this plugin, everything works fine again.
