### ISSUE TITLE
Unable to use the extension without `JavaVM.framework` in macOS

### ISSUE THREAD

**Issue by zihengCat** [redhat-developer/vscode-java#611]
I try to use  use the extension in my macOS local environment, but I found that the extension could not be used without `JavaVM.framework`, a system framework provided by Apple. 
**UnfortunateIy, I deleted `JavaVM.framework` by accident long time ago and it's hard to recover......**
It seems that the extension try to use `java_home` executable provided by `JavaVM.framework` to detect and locate the JDK installation directory.

<img width="1277" alt="screen shot 2018-08-19 at 13 00 22" src="https://user-images.githubusercontent.com/19472493/44305803-8f182d80-a3b3-11e8-83c8-36198804a6a3.png">

<img width="1112" alt="screen shot 2018-08-19 at 13 28 12" src="https://user-images.githubusercontent.com/19472493/44305837-e074ec80-a3b4-11e8-8c01-3dd93c8bc2da.png">

Is there any way to use the extension without `JavaVM.framework`?
Or maybe do I have to reinstall macOS to get `JavaVM.framework` back?

##### Environment
- Operating System: `OS X Yosemite 10.10.5`
- JDK version: `JDK_1.8.0_181 (build 1.8.0_181-b13)`
- Visual Studio Code version: `Version 1.26.1 (1.26.1)`
- Java extension version: `0.29.0 (July 31rd, 2018)`

##### Additional Information
[#74](https://github.com/redhat-developer/vscode-java/issues/74)

**Comment by yaohaizh** [comment]
You can reference this link for how to set the JAVA SDK path: https://github.com/redhat-developer/vscode-java#setting-the-jdk

**Comment by jdneo** [comment]
Hi @zihengCat,

Will the JavaVM.framework be restored by installing the [package from Apple](https://support.apple.com/kb/DL1572?locale=en_US&viewlocale=en_US)?

**Comment by zihengCat** [comment]
@jdneo 
Could not restore. The package `JavaForOSX.pkg` only provides an old `JDK1.6`.
![slice 2](https://user-images.githubusercontent.com/19472493/44323626-46c94000-a485-11e8-8324-5d00653da267.png)

**Comment by jdneo** [comment]
@zihengCat Cool!
