### ISSUE TITLE
Support update multiple project configurations 

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#621]
Currently when the user executes `Java: Update java configuration` command, he must open a pom.xml/build.gradle file first, and then the command will update the focused project only. If the active editor is not a pom.xml or build.gradle, the command does nothing and no notification to tell user what's the right behavior.

The expected experience for this command is popping up a QuickPick to show the available projects (pom.xml/build.gradle) in the whole workspace, after the user multi-selects the target projects, then update the project configuration.

Because this is a hard job for the workspace with multiple projects. For example, for an application with multiple maven modules, when the user modifies the parent pom.xml, the extension will only notify user to update the project associated with parent pom.xml. But actually the inherited child projects also will be out of date and need an update. Based on current policy, the user has no knowledge about that. Even he knows that, he need open each pom.xml one by one and update it separately.

**Comment by RuiffCardoso** [comment]
This would also improve my workflow. Right now, I go to the tree view and have to right click each pom.xml  which is prone to errors and slow.

**Comment by yaohaizh** [comment]
Have been fixed.
