### ISSUE TITLE
Provide Quick Fixes from the Problems view

### ISSUE THREAD

**Issue by fwcd** [redhat-developer/vscode-java#622]
As proposed and implemented by Microsoft/vscode#52627, it would be incredibly useful to be able to trigger quick fixes from the `Problems` view.

#### Environment
- Operating System: `Windows 10`
- JDK version: `1.8.0_144`
- Visual Studio Code version: `1.26.1`
- Java extension version: `0.29.0`

#### Steps To Reproduce
1. Create a compile error in Java that has a `Quick Fix`
2. Open it in the `Problems` view

#### Current Result

For example, after moving a class file to another package, the editor shows an appropriate Quick Fix:

![image](https://user-images.githubusercontent.com/30873659/44787086-73bcd780-ab96-11e8-9339-57ee8f9f08e8.png)

...but the `Problems` view does not:

![image](https://user-images.githubusercontent.com/30873659/44786797-8be02700-ab95-11e8-95e1-d79689bb2b48.png)

#### Expected Result

`TypeScript`, however, does provide similar functionality:

![image](https://user-images.githubusercontent.com/30873659/44786891-e6798300-ab95-11e8-964a-2599cfc37b6f.png)

**Comment by fbricon** [comment]
@yaohaizh can you please investigate on this issue?

**Comment by yaohaizh** [comment]
Blocked by CodeAction class which is already lsp 0.5.0.  

@fbricon  When will eclipse.jdt.ls adopt the new version of LSP4J 0.5?

**Comment by fbricon** [comment]
@yaohaizh lsp4j 0.5.0 is available in jdt.ls now

**Comment by yaohaizh** [comment]
https://github.com/Microsoft/vscode/issues/58572

**Comment by yaohaizh** [comment]
This is fixed in the latest published extension.
