### ISSUE TITLE
Indent case blocks within switch statements

### ISSUE THREAD

**Issue by mark-wiemer** [redhat-developer/vscode-java#623]
vscode-java does not honor Eclipse formatting preferences for indenting statements within 'switch' blocks

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0_171-b11
- Visual Studio Code version: 1.26.1 493869ee8e8a846b0855873886fc79d480d342de x64
- Java extension version: 0.29.0

##### Steps To Reproduce
1. Create a new Java project in Eclipse
1. Create a `Main.java` with a simple switch statement:
```java
public static void main(String [] args) {
  int x = 0;
  switch (x) {
    case 0:
      return;
  }
}
```
1. Change [project-specific formatting settings](https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings): indent `case` statements as seen above (`case` is indented further than `switch`)
    * Indentation > Indented elements > Statements within 'switch' body [checked]
1. Format the project in Eclipse, noting how the indentation is preserved
1. Open the project in Visual Studio code, and note how the code is reformatted

##### Current Result
Code is reformatted so `case` statements align with `switch` statements:
```java
switch (x) {
case 0:
  return;
}
```

##### Expected Result
Eclipse settings are honored, and VS Code formats the same as Eclipse:
```java
switch (x) {
  case 0:
    return;
}
```

##### Additional Informations
The checkbox changes the following line in `org.eclipse.jdt.core.prefs`: 
`org.eclipse.jdt.core.formatter.indent_switchstatements_compare_to_switch=true` (`true` when checked, `false` when unchecked)

[Here is a project that follows these steps](https://github.com/mark-wiemer/indent-switch)

**Comment by mark-wiemer** [comment]
Hmm... closing and re-opening my project seemed to fix this. Strange it was so persistent until now, probably an issue with cached data.

**Comment by tommai78101** [comment]
@mark-wiemer Where do you see this option? 
> Indentation > Indented elements > Statements within 'switch' body [checked]

I could not find this option anywhere in Visual Studio Code, nor know how to set the `eclipse-formatter.xml` with this option included?

**Comment by mark-wiemer** [comment]
> 
> 
> @mark-wiemer Where do you see this option?
> 
> > Indentation > Indented elements > Statements within 'switch' body [checked]
> 
> I could not find this option anywhere in Visual Studio Code, nor know how to set the `eclipse-formatter.xml` with this option included?

The `Indentation > Indented ...` instructions are how to set it in Eclipse, which I figured were relevant.

Setting it in Eclipse is equivalent to adding the line `org.eclipse.jdt.core.formatter.indent_switchstatements_compare_to_switch=true` to the file `org.eclipse.jdt.core.prefs`.

I would like to reiterate that I closed this issue because the system works as expected after I restart Visual Studio Code.

**Comment by tommai78101** [comment]
@mark-wiemer Ah ok, thanks for the info. 

Technically you don't need to restart Visual Studio Code. You just need to open `settings.json`, add a whitespace at the end of the value for "java.format.settings.url", save, delete the extra whitespace, and save again to complete the refresh.

It's a quirk of Visual Studio Code only updating the settings cache when an "onchange" event occurs.

**Comment by mark-wiemer** [comment]
Oh sick, thanks for the info!
________________________________

**Comment by tommai78101** [comment]
@mark-wiemer Ah, you replied by email, so you didn't see my answer to what `eclipse-formatter.xml` is doing. Just repeating what I said earlier. :+1: 

> The eclipse-formatter.xml file is used for Visual Studio Code's extension, Redhat's vscode-java extension, to interface with and format your Java source files inside Visual Studio Code, based on Oracle's Java standard implementation for the formatter.

**Comment by ZinoKader** [comment]
I'm having the same issue, only for switch blocks. The cases are at the same indentation level as the switch block.

**Comment by fbricon** [comment]
@ZinoKader see #1261
