### ISSUE TITLE
Env vars not set in debug

### ISSUE THREAD

**Issue by BlackJad** [redhat-developer/vscode-java#624]
In my project debug configuration there are some env variables linked by properties file and also used into code.

Since yesterday (I've never had these problems before) when I debug my application, there is always an error reading the environment variables from the properties file, for example:

"VARIABLE_REST_PORT": "8181",

I don't know if it may depend on visual studio code updates, because in any case the extension has no updates available.

Can I make some checks on specific system settings or visual studio settings?

##### Environment
- Operating System: Windows 10 Pro
- JDK version: 1.8.181
- Visual Studio Code version: Insiders 1.27.0
- Java extension version: 0.29

##### Steps To Reproduce
1. Create debug configuration for java
2. Add some variable into env section
3. Try to load variable from application.properties or via code

**Comment by andxu** [comment]
It is related to java debugger version 0.12.0, we will publish a hotfix version 0.12.1 in a few hours.
see https://github.com/Microsoft/vscode-java-debug/issues/393

**Comment by testforstephen** [comment]
Debugger for Java extension 0.12.1 released.
