### ISSUE TITLE
التحسين

### ISSUE THREAD

**Issue by ralshammrei2** [redhat-developer/vscode-java#636]
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Please use English for communication and provide details of the issues you have or enhancements you want to suggest (as per the template we provided)
