### ISSUE TITLE
export the utility method requirements.resolveRequirements() as extension API

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#639]
Currently the Java Debugger and Test Runner have the duplicated logic to check JDK installation directory.  Could the vscode-java return the resolved `RequirementsData` value as the return value of `activate` function? By this way, other extensions can get the resolved java_home info directly.

```
   const extension = vscode.extensions.getExtension("redhat.java");
   const extensionApi = await extension.activate();
   return extensionApi.requirementsData;
```

**Comment by ThadHouse** [comment]
I'm having to do the same thing in an extension that runs gradle commands, so this would definitely be something very useful to any extension that needs the JDK.

**Comment by fbricon** [comment]
Thanks for the fix @testforstephen
