### ISSUE TITLE
vscode-java under linux is not working

### ISSUE THREAD

**Issue by Viterzgir** [redhat-developer/vscode-java#64]
Under linux  ~/.vscode/extensions/redhat.java-0.0.5/server is empty. Trying to compile java-language-server with maven and when copy to server folder,  but editor show message Starting Java Language Server... 
P.s. Sorry guys it working after adding in settings java.home. option, and with compiled  java-language-server which placed in server folder.

**Comment by fbricon** [comment]
were you trying to build the vscode extension from source?

**Comment by gorkem** [comment]
I no longer see problems on at least with fedora with 0.0.6 release. Reopen if you still have problems.
