### ISSUE TITLE
Automatically rename file when renaming a class

### ISSUE THREAD

**Issue by fwcd** [redhat-developer/vscode-java#640]
Automatically change the file name when renaming a class. (As implemented in eclipse/eclipse.jdt.ls#614 ?).

#### Environment
- Operating System: `Windows 10`
- JDK version: `1.8.0_144`
- Visual Studio Code version: `1.27.2`
- Java extension version: `0.30.0`

#### Steps To Reproduce
1. Rename a (top-level) class

#### Current Result
1. The file is not renamed

#### Expected Result
1. The file should be renamed to match the new class name

**Comment by yaohaizh** [comment]
Add lsp4j issue: https://github.com/eclipse/lsp4j/issues/257

**Comment by fwcd** [comment]
This seems to be working in the current extension version.

**Comment by kmumahesh** [comment]
[https://user-images.githubusercontent.com/65785/43784301-72c87018-9a6c-11e8-8ddb-1a9349638761.gif](url)

I'm facing the same issue as shown in the gif here. I'm not able to record my VSCode window for some reason, hence reusing this.

I'm on VSCode 1.67.2 on Windows 10. "Rename Symbol" of a class does not rename the file name.
Language Support for Java(TM) by Red Hat - v1.6.0
Extension Pack for Java - v0.22.4
