### ISSUE TITLE
Can I use WSL Java for this extension?

### ISSUE THREAD

**Issue by dgdsingen** [redhat-developer/vscode-java#647]
I'm using WSL(Windows Subsystem for Linux) Git & Maven with Windows VS Code. 
But can't use WSL JDK with this extension. It work only with JDK in Windows. 
Can I use WSL JDK rather than Windows JDK?

##### Environment
- Operating System: Windows 10 Pro
- JDK version: Oracle JDK 1.8.0_181 in Windows, OpenJDK 1.8.0_181 in WSL
- Visual Studio Code version: 1.27.2 (user setup)
- Java extension version: 0.31.0

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
I'm not using Windows or WSL. @yaohaizh @hexiaokai @akaroml that's probably something you guys can help troubleshoot

**Comment by priyeshdiukar** [comment]
Is this a feature under process ? I was trying to do exactly the same thing.

**Comment by yaohaizh** [comment]
@dgdsingen @priyeshdiukar https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack 
https://code.visualstudio.com/docs/remote/remote-overview
Now the VSCode Remote is available in preview. Give it a try in the VSCode Insider edition and provide your feedback if any.  Thanks.

**Comment by yaohaizh** [comment]
Close this as it has been supported by vscode remote.
