### ISSUE TITLE
Inheritance hierarchy support

### ISSUE THREAD

**Issue by Yanpas** [redhat-developer/vscode-java#649]
Add support for inheritance hieararchy.

[cquery](https://github.com/cquery-project/cquery/wiki) (C++ language server) implements it via extension method `$cquery/inheritanceHierarchy` to langauge server. On the vscode side it introduces pane in the explorer sidebar:

![image](https://user-images.githubusercontent.com/7345761/46076312-d903e880-c195-11e8-8686-6282c130e7ab.png)

##### Environment
- Operating System: kubuntu
- JDK version: 10
- Visual Studio Code version: 1.26
- Java extension version: 0.31.0

**Comment by fbricon** [comment]
This depends on https://github.com/eclipse/eclipse.jdt.ls/issues/28 and before that, https://github.com/Microsoft/language-server-protocol/issues/136.

**Comment by langlan** [comment]
Call Hierarchy and Type/Method Hierarchy are the two features I've been looking forward most eagerly which are both not implemeted yet, sadly. 
For Type Hierarchy, as I noted, for now we at least can see a `interface`'s implementations which showed a link: ***xx implementations*** above a Inteface definition by a vitrual-line. We can click it or by command **Peek Implementation**, for a super `class` there's no link but can still peek by command. (Of course, there's no hierarchy structrue)
For Method Hierarchy, for now we at least  can hover a implemented method, and in the hover pane, there's a ***Go to Super Implementaton*** link, but seems no corresponding command.  On a Interface/abstract method, Theres's no link but can use command to peek/goto. e.g. **Peek Implementation**.
**Peek References** seems only show this list of explicitly occurs in extends/implements/new/method-call statements.
**Peek Definition** are always display two columns even the result list contains only one and it seems always only one and never related to super or implementations, maybe the team can leverage the **Peek Definition** with the above logic to add more candidates? For compatibility current logic may should be the first candidate, but for a method-invoke people actually want to jump to the implemented code in most scenarios. It's a cure for thirsty although it's not a solution for hierarchy.

**Comment by rgrunber** [comment]
We've had call & type hierarchy support for some time now so I'll close this issue. Method inheritance hierarchy would be a great addition, which is also very convenient.
