### ISSUE TITLE
Implement "Open Call Hierarchy"

### ISSUE THREAD

**Issue by BuZZ-dEE** [redhat-developer/vscode-java#650]
Currently it is only possible to get the references of a function. I would like to see the call hierarchy of a method etc.

**Comment by hak33m16** [comment]
There is officially an available call hierarchy view in VS Code now: https://code.visualstudio.com/updates/v1_33#_call-hierarchy

This is a really critical development feature for a lot of people, and for me is probably the major reason that I can't use VS Code as my sole IDE. Any progress towards implementing it would really help consolidate peoples' development toolset.

**Comment by langlan** [comment]
For now Peek/Find All References will do some help, but it only worked for project files, not for dependency library. Is there any possibilities to enhance it with library files before the true call hierarchy feature?

**Comment by fbricon** [comment]
Fixed with https://github.com/eclipse/eclipse.jdt.ls/pull/1306 and https://github.com/redhat-developer/vscode-java/pull/1194, thanks to @kittaakos and @testforstephen
