### ISSUE TITLE
Hover over and "definitions  not found" messages in java files

### ISSUE THREAD

**Issue by talmanes** [redhat-developer/vscode-java#662]
Hover over and definitions don't appear to be working, they did for a bit but have stopped with a particular error.  I don't really recall any changes or updates that caused this.  Project builds correctly with maven, and works correctly in IntelliJ, just wanted to see if I could set it up with VSCode.

It's entirely possible I have missed some setup from the https://code.visualstudio.com/docs/languages/java guilde, but I have been over this a few times and am unable to determine what I am doing wrong.

##### Environment
- Operating System: Windows 10 Ent, 1803, 
- JDK version: jdk1.8.0_171
- Visual Studio Code version: 1.27.2 (user setup)

User settings is set
`"java.home": "C:\\Program Files\\Java\\jdk1.8.0_171",`

**Debug tool in vscode**
```
ERR Cannot read property 'kind' of undefined: TypeError: Cannot read property 'kind' of undefined
	at asHoverContent (C:\Users\USERNAME\.vscode\extensions\redhat.java-0.32.0\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (C:\Users\USERNAME\.vscode\extensions\redhat.java-0.32.0\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
	at propagateAslWrapper (C:\Users\USERNAME\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\index.js:502:23)
	at C:\Users\USERNAME\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\glue.js:188:31
	at C:\Users\USERNAME\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\index.js:539:70
	at C:\Users\USERNAME\.vscode\extensions\vscjava.vscode-java-pack-0.4.0\node_modules\async-listener\glue.js:188:31
	at <anonymous>
```

**Comment by yaohaizh** [comment]
@talmanes It is hard find any useful information from these information.  Could you share your error log using this trick: https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs


If possible, could you share your sample project?  Thanks.

**Comment by JRiggenbach** [comment]
I had this same problem, but clearing the language server workspace resolved it for me

New in 0.33.0

You can clean the workspace directory in the following way:

Open the command palette (F1)
select Java: Clean the Java language server workspace
click Restart and delete

**Comment by talmanes** [comment]
Steps from @JRiggenbach worked for the project.  Since I'm changing environments a lot based on the version I need to troubleshoot, I have to make sure I clean out the language workspace.

Thanks again.

**Comment by MoxxiManagarm** [comment]
@JRiggenbach Thanks I just had the same issue and this worked for me too! You saved my ass :-)

**Comment by mlujan476** [comment]
That didn't work for me.  Anybody have another potential solution?
