### ISSUE TITLE
maven modules do not  support well

### ISSUE THREAD

**Issue by chengbaobao630** [redhat-developer/vscode-java#668]
[provide a description of the issue]

##### Environment
- Operating System: macos mojava
- JDK version: 8
- Visual Studio Code version: 1.27.2 (1.27.2)
- Java extension version: 0.4.0

##### Steps To Reproduce
1. [step 1]

import an aggregation project with several child modules;
like:
```java
    <artifactId>c</artifactId>
    <modules>
        <module>a</module>
        <module>b</module>
    </modules>
```

2. [step 2]
compile project

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
i got three maven root 
a
b
c
    -  modules
          - a
          - b

and when i  compile  project a , b 。it works like an independent project，not an aggregation project。
i'll see a lot of errors and warnings  like Missing version ...
##### Expected Result
only one maven root 

c
    -  modules
          - a
          - b

**Comment by fbricon** [comment]
Please attach a set of sample projects. Maven mutimodules  are generally well supported. We need more informations to be able to help you

**Comment by chengbaobao630** [comment]
I solved it with command on child pom.xml : Update project configuration
