### ISSUE TITLE
Support Java 12 preview features

### ISSUE THREAD

**Issue by fwgreen** [redhat-developer/vscode-java#671]
So far, Java 12 has two new language additions:

- Switch Expressions [JEP 325](http://openjdk.java.net/jeps/325)
- Raw String Literals [JEP 326](http://openjdk.java.net/jeps/326)

Please consider adding support for those of us testing early access builds.

**Comment by fbricon** [comment]
Unfortunately we can't provide support for new Java versions until very late in the development process, often only after GA, because it depends on the availability of full JDT builds. 
We can't consume their earlier patch features in our builds, for technical reasons. Unless someone figures out how to get Tycho to install feature patches.

**Comment by fbricon** [comment]
Fixed with https://github.com/eclipse/eclipse.jdt.ls/pull/970

> 
> So far, all kind of projects support Java 12, with some caveats. Experimental features (like advanced switch expressions - [JEP-325](https://openjdk.java.net/jeps/325)) may need specific tuning:
> - default/invisible projects have features enabled features by default, without warnings
> - Maven projects need to have the --enable-preview added to the maven-compiler-plugin configuration, in pom.xml. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=545462#c0, warnings are disabled automatically.
> - Eclipse projects need to add the the following preferences to .settings/org.eclipse.jdt.core.prefs:
> 
>       org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=enabled
>       org.eclipse.jdt.core.compiler.problem.reportPreviewFeatures=ignore
> - Gradle projects can also maintain the same .settings/org.eclipse.jdt.core.prefs. Alternatively adding an  `eclipse.jdt.file.withProperties` hook is possible, but requires the `gradle compileJdt` task to be invoked manually, as [buildship doesn't use those hooks](https://discuss.gradle.org/t/when-does-buildship-eclipse-customization-run/20781/2) :
> ```groovy
> plugins {
>     // Apply the java-library plugin to add support for Java Library
>     id 'java-library'
>     id 'eclipse'
> }
> sourceCompatibility = JavaVersion.VERSION_12
> targetCompatibility = JavaVersion.VERSION_12
> 
> repositories {
>      jcenter()
> }
> compileJava {
>     options.compilerArgs += ["--enable-preview"]
> }
> compileTestJava {
>     options.compilerArgs += ["--enable-preview"]
> }
> //Buildship doesn't use that hooks (https://discuss.gradle.org/t/when-does-buildship-eclipse-customization-run/20781/2)
> //you need to run `gradle eclipseJdt` separately
> eclipse.jdt.file.withProperties { props ->
>     props['org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures']= 'enabled'
>     props['org.eclipse.jdt.core.compiler.problem.reportPreviewFeatures']= 'ignore'
> }
> 
> test {
>     jvmArgs '--enable-preview'
> }
> ```
>

**Comment by fbricon** [comment]
For anyone trying to run Java 12 code using preview features, with the [vscode-java-debug](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) extension, make sure you enable the `--enable-preview` flag in the launch configuration's `vmArgs`:
```json
{
    "configurations": [
        {
            "type": "java",
            "name": "CodeLens (Launch) - Demo",
            "request": "launch",
            "mainClass": "foo.bar.Demo",
            "projectName": "Demo",
            "vmArgs": "--enable-preview"
        }
    ]
}
```

**Comment by fbricon** [comment]
Similarly, running Unit Tests with [vscode-java-test](https://github.com/Microsoft/vscode-java-test) requires setting the `--enable-preview` flag in the test configuration, in settings.json:
```json
    "java.test.config": [
        {
            "name": "java12",
            "workingDirectory": "${workspaceFolder}",
            "vmargs": [ "--enable-preview" ],
        },
    ],
    "java.test.defaultConfig": "java12"
```

**Comment by stevenzeck** [comment]
@fbricon what do we have to do to enable this? Keep receiving the preview features not available error when running in vscode

**Comment by fbricon** [comment]
Can you be more specific?
- Do you use vscode-java 0.42.1? 
- What kind of java code are you looking at? standalone java files? maven, gradle projects?
- is this for actually executing the java code or tests, or compiling?
- what JDK are you using? If executing your code Java 12, did you configure your launch configuration as per https://github.com/redhat-developer/vscode-java/issues/671#issuecomment-477999284?

have you tried cleaning up the Java workspace directory?

**Comment by stevenzeck** [comment]
* 0.42.1 yes
* Standalone Java file
* Executing java code (just a simple hello world)
* JDK 12. Is it necessary to have a launch config? It was working fine until very recently

**Comment by fbricon** [comment]
If you run with a JDK 12, then standalone java files have preview features enabled by default, which means they need to run with the --enable-features flag, which you need to add to a launch configuration for now.  Once https://github.com/Microsoft/vscode-java-debug/issues/553 is fixed, it should be completely transparent again.

If you don't want to change that flag, you need to downgrade the JDK used to launch the Java language server

**Comment by stevenzeck** [comment]
Weird, I've been using JDK 12 for quite some time without this issue

**Comment by fbricon** [comment]
before 0.42.0, your code could not use JDK 12 preview features (advanced switch expressions) in vscode-java.
