### ISSUE TITLE
"Organize imports" ignores ambiguous results

### ISSUE THREAD

**Issue by simahao** [redhat-developer/vscode-java#673]
I want to use TimeCharacteristic class(org.apache.flink.streaming.api.TimeCharacteristic),after execute organize imports command,TimeCharacteristic was not imported.I set log level to verbose, then i found there are two possibilities in log,one is org.apache.flink.api.common.state.StateTtlConfig.TimeCharacteristic,the other is org.apache.flink.streaming.api.TimeCharacteristic that i want to use,i guess organize import can not decide which one to use,right?

##### Environment
- Operating System:win10
- JDK version:1.8
- Visual Studio Code version:1.28.1
- Java extension version:0.32.0

![image](https://user-images.githubusercontent.com/4537287/46899859-a4996780-cecb-11e8-837f-284d908b7fad.png)

[trace.log](https://github.com/redhat-developer/vscode-java/files/2474962/trace.log)

[Trace - 9:16:31 AM] Received response 'textDocument/codeAction - (58)' in 50ms.
Result: [
    {
        "title": "Import 'TimeCharacteristic' (org.apache.flink.api.common.state.StateTtlConfig)",
        "command": "java.apply.workspaceEdit",
        "arguments": [
            {
                "changes": {
                    "file:///D:/project/dev/java/flink-study/hjzh/src/main/java/hjzh/CEP.java": [
                        {
                            "range": {
                                "start": {
                                    "line": 1,
                                    "character": 57
                                },
                                "end": {
                                    "line": 1,
                                    "character": 57
                                }
                            },
                            "newText": "\r\n"
                        },
                        {
                            "range": {
                                "start": {
                                    "line": 1,
                                    "character": 57
                                },
                                "end": {
                                    "line": 1,
                                    "character": 57
                                }
                            },
                            "newText": "import org.apache.flink.api.common.state.StateTtlConfig.TimeCharacteristic;"
                        }
                    ]
                }
            }
        ]
    },
    {
        "title": "Import 'TimeCharacteristic' (org.apache.flink.streaming.api)",
        "command": "java.apply.workspaceEdit",
        "arguments": [
            {
                "changes": {
                    "file:///D:/project/dev/java/flink-study/hjzh/src/main/java/hjzh/CEP.java": [
                        {
                            "range": {
                                "start": {
                                    "line": 2,
                                    "character": 46
                                },
                                "end": {
                                    "line": 2,
                                    "character": 46
                                }
                            },
                            "newText": "\r\n"
                        },
                        {
                            "range": {
                                "start": {
                                    "line": 2,
                                    "character": 46
                                },
                                "end": {
                                    "line": 2,
                                    "character": 46
                                }
                            },
                            "newText": "import org.apache.flink.streaming.api.TimeCharacteristic;"
                        }
                    ]
                }
            }
        ]
    },

**Comment by fbricon** [comment]
Indeed, organize imports doesn't do anything when there are ambiguous results.  In regular Java IDEs, you would usually get a wizard pop-up to let you decide which class to import. But that model doesn't fit well in the context of an editor like VS Code, with minimal interaction options.
Until we can think of a better approach, I guess we should rather display a message pop-up, when ambiguous results were found.

**Comment by fwcd** [comment]
@fbricon Would it be possible to "guess" the correct type by inferring it from its context? For example when declaring a list:

```java
List<String> list = new ArrayList<>();
```

it should be unambigous that `java.util.List` is meant and not `java.awt.List`. Furthermore, VSCode does provide the `window.showQuickPick` API that could be used to introduce something like this:

![image](https://user-images.githubusercontent.com/30873659/47373530-57e43680-d6ec-11e8-8a89-537d8bd68d1a.png)

This would match the way Eclipse resolves imports too:

![image](https://user-images.githubusercontent.com/30873659/47373685-9bd73b80-d6ec-11e8-8e79-44297becb7e3.png)

**Comment by fbricon** [comment]
showQuickPick might not fit if multiple ambiguous imports are found.
Context sensitive import might be something to explore, although it might not be trivial to implement.

**Comment by fwcd** [comment]
@fbricon Actually, multi-step quick picks are possible:

![image](https://user-images.githubusercontent.com/30873659/47375323-5157be00-d6f0-11e8-93db-b080617295dc.png)

[There is an example of this dialog in Microsoft/vscode-extension-samples](https://github.com/Microsoft/vscode-extension-samples/blob/master/quickinput-sample/src/multiStepInput.ts).

**Comment by yaohaizh** [comment]
@fwcd  For multi imports, you can just select the ambiguous type and trigger code action (ctrl +  . ), pick up the right lib from the context menu, which has the similar experience as the eclipse quick fix(ctrl + 1)

**Comment by fbricon** [comment]
Management of ambiguous imports integrates seamlessly into VS Code:

![organizeImports](https://user-images.githubusercontent.com/14052197/54737801-8a875200-4bec-11e9-8a6e-c5f2b3f57367.gif)

Again, kudos to @testforstephen!

**Comment by fwcd** [comment]
This is really great, thanks!

**Comment by simahao** [comment]
Really great,thanks!

**Comment by liangjacky** [comment]
Would it be possible to have a flag that opens this window on "Organize Imports on Save"?

**Comment by fbricon** [comment]
@liangjacky I'm not sure this would work well with autosave. And because the save action is currently implemented at the server level, things might get tricky, but I'm open to the idea. Please open a new ticket.

**Comment by liangjacky** [comment]
@fbricon https://github.com/redhat-developer/vscode-java/issues/900 done. Thanks for the hard work.
