### ISSUE TITLE
visual studio code removes import statements on save

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-java#675]
Copied from Microsoft/vscode-java-pack/issues/44

@viraj1994 reported that the import statements are removed on save. Here's a video of the issue:

https://drive.google.com/file/d/16bxoqj-4pA_aJAOChTpLpinpaiZCwwQf/view

**Comment by MarcelloPerathoner** [comment]
> Those imports are not used. If you set `"java.saveActions.organizeImports": true` in your vscode settings, it's expected to see them removed.

Has this become the default? Because I surely did not set that one in my settings. Where else can it come from?

This is a dangerous thing because if you save with syntax errors, maybe just a curly brace too many, it will happily remove most of your imports.

**Comment by fbricon** [comment]
@MarcelloPerathoner sounds similar to https://github.com/redhat-developer/vscode-java/issues/3370. If you have a .settings/org.eclipse.jdt.ui.prefs file with:

```
editor_save_participant_org.eclipse.jdt.ui.postsavelistener.cleanup=true
...
sp_cleanup.organize_imports=true
```

Setting either to false, or deleting the prefs file should help.

@rgrunber vscode-java should probably disable JDT UI prefs support. It's a definitely a source of confusion/frustration.

**Comment by MarcelloPerathoner** [comment]
Thanks. I had both those settings. But that file was last committed 6 years ago, and I don't remember it happening before. Something must have changed in vscode lately.

**Comment by fbricon** [comment]
@MarcelloPerathoner yes, this is caused by https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2870

**Comment by girotomas** [comment]
I disabled my java extensions searching for "@enabled java" in extensions
