### ISSUE TITLE
Q: classpath configuration

### ISSUE THREAD

**Issue by leidegre** [redhat-developer/vscode-java#678]
You have to provide some examples on how to configure a minimal working project.

The first thing I notice is this warning, https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning

I'm not a Java expert and I just happen to need to write a few lines of Java, your extension is great but I feel as if I'm missing out on a quite rich feature set.

What's the simplest thing I need to do, to get the extension to work. I just have a folder with a single Java file in it and I want the tooling to understand where it can find the things I use. In this case I have a single .jar file with all the dependencies that I'm consuming.

I've looked at `pom.xml` but it looks absolutely bloated. What's this `.classpath`  file thing, would that suffice, what exactly is it that I have to configure?

**Comment by andxu** [comment]
try the command "Create Java Project" after installing https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency will scaffold a minimal working project

**Comment by leidegre** [comment]
Ok, thanks, I'll try that next time.
