### ISSUE TITLE
Completion on import statements is broken

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#68]
- type _import java._`<ctrl+space>`
- select `java.util<enter>`
- you end up with _import `java.java.util`_

**Comment by fbricon** [comment]
@gorkem said:
> I think we need to send back a TextEdit and to change the replacement range in certain cases

**Comment by gorkem** [comment]
Fixed with https://github.com/gorkem/java-language-server/commit/9357f3eb5134d187cfeaee6bd48729e50e032614

**Comment by go1done** [comment]
@gorkem , when can this fix be merged  in master ?

**Comment by fbricon** [comment]
@go1done that fix was merged 3 years ago. 
This week, we pushed some [changes affecting completion](https://github.com/eclipse/eclipse.jdt.ls/pull/1298), so If you still had some issues with completion,  you can download the most recent `java-<version>.vsix` file from [http://download.jboss.org/jbosstools/jdt.ls/staging/](http://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D) and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).
