### ISSUE TITLE
Beetle emoji os not rendered on linux

### ISSUE THREAD

**Issue by Yanpas** [redhat-developer/vscode-java#680]
Beetle :beetle:  emoji used by java language server is not rendered on linux:
![image](https://user-images.githubusercontent.com/7345761/46680420-bfc95600-cbf1-11e8-822b-7e049ddb7beb.png)

`    "editor.fontFamily": "'Twitter Color Emoji', 'Fira Code','Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback', 'Noto Color Emoji'"`

Seems like there is color-emoji rendering problem on linux, kubuntu 18.04

Not sure if it's the right place, see also https://github.com/Microsoft/vscode/issues/32840

**Comment by fbricon** [comment]
The Run/Debug code lenses are not contributed by vscode-java, but by [vscode-java-debug](https://github.com/Microsoft/vscode-java-debug). Please open a bug [there](https://github.com/Microsoft/vscode-java-debug/issues/) (although most likely this is a VS Code issue upstream).
