### ISSUE TITLE
Java server crashed 5 times in last 3 minutes

### ISSUE THREAD

**Issue by toramanan** [redhat-developer/vscode-java#681]
I am getting below error message for java application

The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

Source: Language Support  for Java(TM) by Red Hat (Extension)

##### Environment
- Operating System: Mac OS Mojave
- JDK version: java version "1.8.0"
- Visual Studio Code version: Version 1.28.2 (1.28.2)
- Java extension version:

##### Steps To Reproduce
1. During first Java application activation

**Comment by yaohaizh** [comment]
@toramanan Is this the first time that you are using vscode java to open the application or the project was opened before?

**Comment by toramanan** [comment]
This is happening every time the plugin is trying to load when I add a Java app folder to the workspace. Since the plugin is crashing, it is not recognizing Java app, so it is more of a text editor for java apps.

I tried the latest versions and few previous versions for Mac and I am still getting the issue.

JDK_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home

**Comment by toramanan** [comment]
There is no other java process running. JPS just gave me the pid of its own process.

**Comment by toramanan** [comment]
Looks like after my OS X upgrade, something messed up my Java. I had to re-install JDK and I installed 11 this time and it is working fine now. Thank you.

**Comment by toramanan** [comment]
Looks like after my OS X upgrade, something messed up my Java. I had to re-install JDK and I installed 11 this time and it is working fine now. Thank you.
