### ISSUE TITLE
Local variable completion fails after auto parameter completion in Java method call

### ISSUE THREAD

**Issue by safield** [redhat-developer/vscode-java#687]
Version: 1.29.0-insider
Commit: 9e83209
Date: 2018-10-18T05:14:11.586Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Java Language Support by Red Hat version 0.32.0

Linux Mint 19

When I am typing out a java method which takes parameters, and then auto completion presents me with to option to complete the method, I select this option. Subsequently, the auto completion also fills in the parameter name for the method call. When I delete this parameter, and start typing the name of a local/member variable, there is no completion suggestions for this variable.

Observe the following code:

public class VscodeTest {

    int blah;

    public VscodeTest() {
    }
    public void someMethod(int bar){
    }
    public void test() {
        int backet;

        someMethod();
    }
}

Scenario 1:
-In the test() method, I start typing out "some" and the select the completion suggestion someMethod(int bar).
-someMethod gets completed to someMethod(bar);
-I then delete bar and start typing either backet or blah
-no completion suggestion appears.

Scenario 2:
-In the test() method I manually type out someMethod();
-I place the caret in the method call brackets and start typing either backet or blah
-in both cases, autocomplete suggestions pop up for the variables.

**Comment by safield** [comment]
I think this issue is actually solved by using the following vscode setting....

```
    // Control whether an active snippet prevents quick suggestions.
    "editor.suggest.snippetsPreventQuickSuggestions": false,
```

The default is set to true, and when I when a java method is auto completed, it must create a snippet to fill in the parameters.

**Comment by snjeza** [comment]
That fixes the issue. @safield Thanks.

**Comment by kzinglzy** [comment]
@safield that helps me a lot, thanks!
