### ISSUE TITLE
Overloaded methods Info

### ISSUE THREAD

**Issue by RuiffCardoso** [redhat-developer/vscode-java#688]
Looking at [https://code.visualstudio.com/docs/editor/intellisense](https://code.visualstudio.com/docs/editor/intellisense), a feature that vscode-java is missing is joining overloaded methods as seen in this gif:

![Overloaded method example](https://code.visualstudio.com/assets/docs/editor/intellisense/intellisense.gif)

This would help mitigate the issue with the parameter window fixed size

**Comment by yaohaizh** [comment]
You can enable the signature help in user setting:    "java.signatureHelp.enabled": true.

By default, this is turned off since the Java compltion list will provide all the overload versions.

**Comment by imba-tjd** [comment]
It's too crowded to have all the overloads in ctrl+space compltion list.
I didn't use other Java IDE before. Do they have the same behavior?

I think it's better to move the overloads intellisense to ctrl+shift+space (i.e. *Trigger Parameter Hints*)

**Comment by fbricon** [comment]
> I didn't use other Java IDE before. Do they have the same behavior?

Yes:
- Intellij IDEA
<img width="542" alt="Screenshot 2021-05-05 at 10 43 32" src="https://user-images.githubusercontent.com/148698/117116695-f4442500-ad8e-11eb-8c21-8ba9e5bc486a.png">

- Eclipse IDE
<img width="369" alt="Screenshot 2021-05-05 at 10 46 11" src="https://user-images.githubusercontent.com/148698/117116869-2b1a3b00-ad8f-11eb-9162-d231d9f2da0f.png">

- Netbeans IDE
![](https://i1.wp.com/www.linuxandubuntu.com/wp-content/uploads/2019/06/netbeans-code-completion.png?ssl=1)

**Comment by jdneo** [comment]
It's supported by signature help.
