### ISSUE TITLE
The java.home variable defined in VS Code settings points to a missing folder

### ISSUE THREAD

**Issue by danieltedev** [redhat-developer/vscode-java#690]
The java.home variable defined in VS Code settings points to a missing folder

##### Environment
- Operating System: windows 7 64
- JDK version: jdk1.8.0_191
- Visual Studio Code version: 1.28.2
- Java extension version: 0.33.0

##### Steps To Reproduce
user settings vscode: "java.home": "C:\\Program Files\\Java\\jdk1.8.0_161"
system environment variable: name variable = JAVA_HOME / value variable = c:\Program Files\Java\jdk1.8.0_191
system environment variable: name variable = JDK_HOME / value variable = c:\Program Files\Java\jdk1.8.0_191

error: The java.home variable defined in VS Code settings points to a missing folder

I have already taken a look at all the problems already reported but I did not find a solution, can you help me?

**Comment by snjeza** [comment]
You can try the following;
```
"java.home": "C:\\Program Files\\Java\\jdk1.8.0_191\\",
```

**Comment by danieltedev** [comment]
good morning, i already tried "java.home": "C:\\Program Files\\Java\\jdk1.8.0_191\\" but not working @snjeza....
thank for helping me!!!

I going continue trying

sorry for ingles

**Comment by fbricon** [comment]
@danieltedev did you try to use double backslashes? (`\\`)

**Comment by danieltedev** [comment]
sorry my message removed the double backslashes, but yes, I used double backslashes

**Comment by fbricon** [comment]
have you tried using forward slashes (`/`) instead?
`"java.home": "C:/Program Files/Java/jdk1.8.0_191"`?

**Comment by Inukares** [comment]
You say that you've set the settings in vsCode to point to `\jdk1.8.0_161`, but in env variable you have `\jdk1.8.0_191`
Maybe you wrote wrong sdk version?

**Comment by Agredo** [comment]
I have the same problem. Cant use Java in VS Code.

**Comment by danieltedev** [comment]
Sorry I figured out what I did wrong, I put the settings inside the workspace and for this reason it was not working.

**Comment by apsmono** [comment]
what did you mean by this??

> 
> 
> Sorry I figured out what I did wrong, I put the settings inside the workspace and for this reason it was not working.

**Comment by vintprox** [comment]
Bruh. I set following in User Settings
```
    "java.home": "C:\\Program Files\\RedHat\\java-1.8.0-openjdk-1.8.0.222-4"
```
But it still cannot locate actually installed JDK.

**Comment by iaxat** [comment]
Same problem

**Comment by ditordccaa** [comment]
I had the same problem. What I did additionally is setting the environment variable too.
export JAVA_HOME=C:/Program Files/Java/jdk1.8.0_131
and it worked.
Cheers,

**Comment by fcastresana** [comment]
Hi! i had the same problem. try downloading this AdoptOpenJDK\jdk-11.0.8.10-hotspot\ then configure your system variables like this tutorial https://javatutorial.net/set-java-home-windows-10
other important thing check if you have two java versions installed and uninstall the one you dont need.

**Comment by alishah730** [comment]
this is my java home in mac and still getting same issue
`"java.home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home"`

**Comment by veedata** [comment]
> this is my java home in mac and still getting same issue
> `"java.home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home"`
> 
> ![image](https://user-images.githubusercontent.com/15693925/89799155-79055980-db03-11ea-80ae-49c650348364.png)

Hey, i was facing the same issue, i tried all the solutions above but they did not work and still gave an error.
It seems to be a problem with the Red Hat extension. It required Java 11 minimum. To bypass this i went to a version of the extension where this wasn't the case
What fixed it for me was downgrading to v0.62.0 (maybe it works in a more recent )

This is not a fix in itself, so, i hope someone does find a better way out, but till that point in time, this is a monkey fix

**Comment by fbricon** [comment]
Since vscode-java 0.65.0, "java.home" needs to point to a JDK 11 installation, so the Java Language Server can run. 

You can still use a JDK 1.8 (actually anything from 1.5 to 14) to compile your projects, if you configure the "java.configuration.runtimes" preference, as documented in https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements.

**Comment by iaxat** [comment]
I have found the solution for this issue that worked for me, I installed the Java.deb file and then the issue got removed.

[https://gofile.io/d/lNjQkz](url)

**Comment by thanhle-phd** [comment]
Better using java.home settings by workspace. Given vscode for mobile app dev using react-native with 32-bit JDK but some Java apps using 64-bit JDK, workspace settings should help.

**Comment by bphariharan1301** [comment]
> You can try the following;
> 
> ```
> "java.home": "C:\\Program Files\\Java\\jdk1.8.0_191\\",
> ```

are you sure that it's working??
Since, i tried and its not working..

**Comment by victorbombella** [comment]
I just had the same problem and I noticed that the problem was in the workspace configuration, so, you need to change the "java.home" path in both, User json and Workspace json, following the rule of using "\\" (doble slash) and setting the same path in both.

**Comment by LaoLiulaoliu** [comment]
I met the same problem too in win10 with settings.json "java.home": "C:\\Program Files\\Java\\jdk-11.0.10",

**Comment by Eskibear** [comment]
@LaoLiulaoliu 
> following the rule of using `\\` (doble slash) 

@bphariharan1301
As mentioned in https://github.com/redhat-developer/vscode-java/issues/690#issuecomment-673376270 , it requires JDK 11+ to launch the language server itself.

**Comment by Thengsenghong** [comment]
> Bruh. I set following in User Settings:
> 
> ```
>     "java.home": "C:\\Program Files\\RedHat\\java-1.8.0-openjdk-1.8.0.222-4"
> ```
> 
> But it still cannot locate actually installed JDK.
> 
> Using path to Java SE Development Kit `C:\\Program Files\\Java\\jdk-13.0.1` doesn't help either.

java.home is deprecated please use "java.jdt.ls.java.home" in stead.

**Comment by huykon** [comment]
I'm facing with same issue on my ubuntu vscode

**Comment by MikeT3ch** [comment]
Hi! if you have jre and jdk in your machine at the same time, uninstall one of them (uninstalling jre works for me). JDK already have jre embedded.
