### ISSUE TITLE
Outline contains strange '{...}' when enums override methods

### ISSUE THREAD

**Issue by Poytr1** [redhat-developer/vscode-java#695]
When I open a source file of enum class in `google/guava` project, I found that OUTLINE shows a strange result containg '{...}' like below:
![image](https://user-images.githubusercontent.com/20534718/47700887-fc1d2e80-dc52-11e8-997f-75e938381951.png)
It seems that `textDocument/documentSymbol` returns an unexpected result in this scenario.

##### Environment
- Operating System: OS X
- JDK version: Java 8 or 11
- Visual Studio Code version: 1.28.2 (1.28.2)
- Java extension version: Extension Package 0.4.0

##### Steps To Reproduce
1. `git clone https://github.com/google/guava.git`
2. `code guava`
3. open `guava/src/com/google/common/base/CaseFormat.java`
4. open OUTLINE

##### Current Result
OUTLINE contains `{...}`, and the response of `textDocument/documentSymbol` is like:
```
{
            "name": "convert(CaseFormat, String)",
           ...,
            "containerName": ""
        },
{
            "name": "{...}",
            ...,
            "containerName": "LOWER_UNDERSCORE"
        }
```
##### Expected Result
The response should be:
```
{
            "name": "convert(CaseFormat, String)",
           ...,
            "containerName": "LOWER_UNDERSCORE"
        },
```
and no '{...}'

**Comment by fbricon** [comment]
This is caused by the enum defining/overriding an abstract method. This can be reproduced with:
```java
package example;

public enum EnumWithAbstractMethod {
 
    Foo {
        @Override
        void bar() {}
    };

    abstract void bar();
}
```

**Comment by fbricon** [comment]
Eclipse actually has same behaviour. `{...}` indicates an anonymous type, so it works as intended.
<img width="500" alt="screen shot 2018-10-30 at 11 06 20 am" src="https://user-images.githubusercontent.com/148698/47728320-7b4f3a00-dc34-11e8-97e3-e3bd392e4bb6.png">
