### ISSUE TITLE
enhance java Generate  toString()

### ISSUE THREAD

**Issue by gongxun0928** [redhat-developer/vscode-java#696]
[provide a description of the issue]

##### Environment
- Operating System: 
    Mac OS Darwin bogon 17.5.0 Darwin Kernel Version 17.5.0
- JDK version:
    java version "1.8.0_151"
 Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
 Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
- Visual Studio Code version:
   version 1.28
- Java extension version:

##### Steps To Reproduce
1. use MyBatis Generator  generate some classes.
2. choose a field with docs comment
3. click generate toString()

##### Current Result
the method generated like this:
@Override
    public String toString() {
        return "{" +
            " ='" + get() + "'" +
            ", ='" + get() + "'" +
            ", @mbg.generated='" + get@mbg.generated() + "'" +
            ", entityId='" + getEntityId() + "'" +
            "}";
    }

##### Expected Result
@Override
    public String toString() {
        return "{" +
            " entityId='" + getEntityId() + "'" +
            "}";
    }

##### Additional Informations
could it skip the docs comment？

**Comment by fbricon** [comment]
vscode-java doesn't provide a menu to generate toString() methods. This must come from another extension.
As for actually providing toString() and other methods generation, see #597.
