### ISSUE TITLE
VSCode can't detect JDK !!

### ISSUE THREAD

**Issue by YousefSaber** [redhat-developer/vscode-java#697]
although that JDK is installed on my OS VSCode or your extension can't detect it!!

![image](https://user-images.githubusercontent.com/33742499/47722686-a600b900-dc5b-11e8-85aa-7f030e716527.png)

![image](https://user-images.githubusercontent.com/33742499/47722703-aef18a80-dc5b-11e8-8872-2a384fcbc76f.png)

- Operating System: elementary OS v5.0 juno
- JDK version: 1.8.0_181 
- Visual Studio Code version: v1.28.2
- Java extension version: v0.33.0

**Comment by fbricon** [comment]
have you tried setting "java.home" in VS Code's settings.json?

**Comment by snjeza** [comment]
You can try the following:

```
"java.home": "/usr/lib/jvm/java-1.8.0-openjdk-amd64/",
```

**Comment by fbricon** [comment]
How did you install vscode? via flatpack? 
In any case, [try to point to a JDK in another directory](https://github.com/redhat-developer/vscode-java/issues/510#issuecomment-381602935)

**Comment by YousefSaber** [comment]
@snjeza @fbricon it's over nothing works I'm tired of trying I'll only use VSCode on Ubuntu since it has the largest community and I'll post issues only from there

**Comment by juliosilvacwb** [comment]
> How did you install vscode? via flatpack?
> In any case, [try to point to a JDK in another directory](https://github.com/redhat-developer/vscode-java/issues/510#issuecomment-381602935)

You save me
