### ISSUE TITLE
缺少快捷键；Java development lacks shortcut keys 

### ISSUE THREAD

**Issue by zjun2** [redhat-developer/vscode-java#701]
在eclipse中鼠标悬浮在类名上 使用ctrl+T可以查看接口的所有实现类，或者所有的继承类。vscode似乎没有这个快捷键。还有鼠标悬浮在方法名上按住ctrl后出现选项可选择跳转到接口定义或者选择跳转到方法的实现。这两个快捷键对开发者来说很重要，但目前我不知道在vsvode中怎么使用这两个功能。如果有这两功能我可能会放弃使用eclipse。

In eclipse, hover over the class name and use Ctrl + T to view all the implementation classes of the interface, or all the inherited classes. Vscode does not seem to have this shortcut. There are also options that appear when the mouse hovers over the method name and holds down Ctrl to choose to jump to the interface definition or to choose to jump to the implementation of the method. These two shortcuts are important to developers, but I don't know how to use them in vsvode at this point. If I have these two functions, I may give up using eclipse.

**Comment by 410919244** [comment]
Open Declaration
Open Implementation
Open Return Type

**Comment by 410919244** [comment]
click click click →→→[look image](http://wx-mmbiz.oss-cn-shanghai.aliyuncs.com/aaaa.png)  ←←← this this this

**Comment by yaohaizh** [comment]
![image](https://user-images.githubusercontent.com/17268517/47830300-48d54680-ddc6-11e8-8043-b10553378c3b.png)

See the snapshot. 
For Open Declaration, you can use F12.  For Open Return Type, you can use Go to Type Definition.  You can also binding your own key stroke use VSCode Settings. See: https://code.visualstudio.com/docs/getstarted/keybindings

For Open Implementation, you can track the feature on these links: https://github.com/eclipse/eclipse.jdt.ls/issues/820

**Comment by yaohaizh** [comment]
Also, the type hierarchy is in pipeline, you can track here: https://github.com/redhat-developer/vscode-java/issues/701

**Comment by 410919244** [comment]
The function of vs code "shift+12" is inferior to eclipse's "Open Implementation". But it is better than nothing, thank you for your answer. Thank you 3Q @yaohaizh

**Comment by 410919244** [comment]
@akaroml 那个我很早就用过了，不太好用。很多快捷键都没有。我现在遇到新的问题。这工具没法跟进源码。一般源码中才有注释，而且很多时候需要去看源代码，如果不能跟进去看源代码体验感就差很多了！也不能想idea那样反编译过来，那看不到源码的javadoc注释

**Comment by liuxin2533** [comment]
@410919244 请问您问题解决了吗?我也遇到了同样的问题

**Comment by yaohaizh** [comment]
@liuxin2533 具体什么样的问题？
What kind of problem do you meet?
