### ISSUE TITLE
Type inference doesn't work in a standalone java file

### ISSUE THREAD

**Issue by Yanpas** [redhat-developer/vscode-java#705]
[provide a description of the issue]

##### Environment
- Operating System: arch linux
- JDK version: 11
- Visual Studio Code version: 1.28
- Java extension version: 0.33

##### Steps To Reproduce
code example:
```java
var scanner = new Scanner(System.in);
int i = scanner./*here*/
```
Code completion doesn't work. `scanner`'s type is unknown

**Comment by fbricon** [comment]
Are you testing a single, standalone java file? or is it part of a Java 11-based project (as configured by Maven/Gradle)?

**Comment by Yanpas** [comment]
It's a single file

**Comment by fbricon** [comment]
@Yanpas did you set the java.home preference to point towards your Java 11 install?

**Comment by Yanpas** [comment]
java.home is null
Hm, AFAIR I was using java 8, then I've installed java 11 and ran `sudo archlinux-java set java-11-openjdk`. `java -version` showed 11 and the issue was reproducible. After reboot it seems to work. Closing.

**Comment by Yanpas** [comment]
Faced it again with java 11. Tried to debug this, then ran command "Clean java langauge server workspace" and that helped
