### ISSUE TITLE
Highlighting is wrong

### ISSUE THREAD

**Issue by V0idk** [redhat-developer/vscode-java#707]
![image](https://user-images.githubusercontent.com/17514799/47998590-dd2f0880-e13a-11e8-8061-cc0535885da6.png)

**Comment by fbricon** [comment]
Syntax highlighting is provided by vscode proper, which itself depends on the [atom grammar](https://github.com/atom/language-java/blob/master/grammars/java.cson). So it needs to be fixed there first

**Comment by fbricon** [comment]
This is partially fixed with the new semantic highlighting support in vscode-java 0.61.0. Requires `"java.semanticHighlighting.enabled": true` in settings.json. Without semantic highlighting, the Textmate grammar is still broken.
