### ISSUE TITLE
Add initial support for renaming

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#71]
We should add some refactoring options for renaming 
- [x] parameters
- [x] fields. Getters/Setters are a special case
- [x] methods
- [ ] classes (although my understanding is vs code/language server protocol doesn't support file renaming)
- [ ] packages

**Comment by gorkem** [comment]
see also https://github.com/gorkem/java-language-server/issues/43

**Comment by yaohaizh** [comment]
@fbricon @gorkem Could you guys help assign this one to me?  I would like to work on this one.

**Comment by fbricon** [comment]
Initial support for renaming as landed. Because the language server protocol doesn't support renaming files, only renaming symbols is available now.

Renaming a class, will change the class name but won't rename the file, you'll have to fix the class/filename discrepancy manually.

Kudos to @yaohaizh for the contribution
