### ISSUE TITLE
Exclude certain packages from autocomplete/autoimport

### ISSUE THREAD

**Issue by liangjacky** [redhat-developer/vscode-java#710]
Autoimport does not work when you have packages that have the same class name. 

For example, when typing `List<String> a = new List<String>()`, there will be errors because it doesn't know whether to resolve against `java.util.List` or `java.awt.List`. 

If I know in my project I never use the `java.awt` package, can we add a setting to ignore that from the autocomplete/autoimport feature?

**Comment by fbricon** [comment]
We need a `java.completion.filteredTypes` preference, that basically behaves as JDT UI's type filter preference:

![](https://bsi-software-qbzxeqguxv.stackpathdns.com/fileadmin/daten/Scout_Blog/2015/list_import_img3.png)

**Comment by MuhammadimYusoff** [comment]
Guys I am having problem with 'javax.swing.*' and related GUI library in VSCode, other thread explain I need to exclude it from my settings.json but nothing related to 'java.completion.filteredTypes' is placed  as I have clean uninstall VSCode (The previous extensions and settings, this is a fresh install).

is there any related thread that mention about GUI related libraries fixes?
