### ISSUE TITLE
Static imports order

### ISSUE THREAD

**Issue by fbn-roussel** [redhat-developer/vscode-java#711]
The _organize imports_ feature puts the static imports at the beginning of the _imports_ block (just after package).
It would be nice to have an option that gives you the choice to put it either at the beginning or at the end.

##### Environment
- Operating System: Fedora 29
- JDK version: 1.8.0_191
- Visual Studio Code version: 1.28.2
- Java extension version: 0.33.0

##### Steps To Reproduce
1. Add some static imports before the class definition
2. Fire organize imports

**Comment by fbricon** [comment]
Hey Fabien, long time no see :-)

If JDT has the option, then we can expose it.

**Comment by fbricon** [comment]
Matching issue in upstream JDT: https://bugs.eclipse.org/bugs/show_bug.cgi?id=304415

It's been opened since 2010. Fixing it in vscode-java requires fixing it upstream 1st. Probably not gonna happen anytime soon, unless people massively vote for that feature.

**Comment by kusnier** [comment]
Hi, I have configured my vscode with working ordering of static imports.

```json
    "java.completion.importOrder": [
        "",
        "java",
        "javax",
        "org",
        "com",
        "de.mycompany",
        "#",
        "#de.mycompany"
    ],
```

All unknown imports will be added first. Then java, javax, org, and com.
After that, I see all my import from my company.

As of last I want to have static imports. The most important imports are again from my company so I will have them as last. (You have to use # for the ordering of the static imports.)

**Comment by rgrunber** [comment]
Nice discovery here! Yes, according to https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/cb1093315376859558a838c6934880f87921d816/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/ImportOrganizeConfigurationBlock.java#L96 , static imports are prepended by a `#`. I think this is definitely something we should mention in the settings description.
