### ISSUE TITLE
Suggestion : contribute "extract variable" and "extract method" Code Action kinds

### ISSUE THREAD

**Issue by dlicois** [redhat-developer/vscode-java#714]
Hello,

 vscode-java introduced "extract to variable" and "extract to method" refactoring as quick-fixes a while ago. #303 #459 

However, the extension doesn't contribute Code Action kinds or commands, as the typescript extension does.

> Code Action kinds are specified by extensions using the enhanced CodeActionProvided API

https://code.visualstudio.com/docs/editor/refactoring#_keybindings-for-code-actions

https://github.com/Microsoft/vscode/blob/758206be09ddfaac46e941a77375ec34ed928b4b/extensions/typescript-language-features/src/features/refactor.ts#L107

Adding "refactor.extract.function", "refactor.extract.constant" and "refactor.extract.variable" code action kinds would allow contribution to keybinds for direct "extract method" refactoring. Which would be useful for vscode-eclipse-keybindings extension (Alt+Shift+m and Alt+Shift+l keybinds).

**Comment by fbricon** [comment]
should be doable now that the server returns code actions. we need to adjust the code action kinds on the server side though.

**Comment by yaohaizh** [comment]
The server side already adjusted the code action for refactor.extract. Need update for organize import, the PR should be ready by the end of this week.

**Comment by fbricon** [comment]
See https://github.com/eclipse/eclipse.jdt.ls/pull/909

**Comment by fbricon** [comment]
Key mappings can now point to 

- refactor.extract.function
- refactor.extract.variable
- refactor.extract.constant
