### ISSUE TITLE
Any config to disable Circular Dependencies warning/error?

### ISSUE THREAD

**Issue by hcapp01** [redhat-developer/vscode-java#718]
Any config to disable this warning/error? The same project can be loaded in intellij fine without any warning/error.

"A cycle was detected in the build path of project xxx - Build Path Problem"

##### Environment
- Operating System:windows 10
- JDK version:1.8
- Java extension version: 0.33

![image](https://user-images.githubusercontent.com/3634644/48652699-a5835480-e9b5-11e8-9683-f72caf8104a9.png)

**Comment by fbricon** [comment]
No it's not possible to disable it. You need to break the cycle.
What kind of project allows such cyclic dependencies? gradle?

**Comment by hcapp01** [comment]
Yes, gradle.

**Comment by coopstah13** [comment]
Can we reopen this? This is a feature of eclipse, so I'm presuming this can be done. Gradle does not allow for cyclic dependencies within configurations. As I understand it, the problem is that you need to be able to support multiple classpaths, one per gradle configuration basically. I know that eclipse cannot support this capability (IntelliJ does), I'm wondering if this extension could.

This is the related issue in buildship:
https://github.com/eclipse/buildship/issues/460

**Comment by ragurney** [comment]
I'm also experiencing this issue. Might make me switch over to IntelliJ after all :/

**Comment by ganezdragon** [comment]
Why is this closed? Still not able run gradle projects with circular dependencies.

**Comment by fbricon** [comment]
We merely take upstream Eclipse projects and integrate them together so they can work in a headless scenario. We definitely rely on other people's work for Core functionalities.
It **might** be possible in the future for Eclipse Buildship to support some sort of circular project dependencies, when referencing test folders from one project to another, but we can't do anything here in vscode-java until that upstream issue is fixed.

**Comment by coopstah13** [comment]
what we're asking for here, is for you to support the option as outlined here: https://github.com/eclipse/buildship/issues/460#issuecomment-297953710

**Comment by snjeza** [comment]
@coopstah13 you can try to add 
```
org.eclipse.jdt.core.circularClasspath=warning
```
to <your_project>/.settings/org.eclipse.jdt.core.prefs

**Comment by ganezdragon** [comment]
@snjeza nope didn't work for me!

**Comment by snjeza** [comment]
@ganezdragon Could you provide a project example?

**Comment by shua** [comment]
following @snjeza's suggestion, but since I have a multi-project set up with many subdirectories that vscode decided should all get their own `.settings` folder, I had to update it for every `.settings` folder in the repo before vscode allowed builds to pass.

**Comment by shua** [comment]
Trawling through https://docs.gradle.org/current/userguide/eclipse_plugin.html , I've found the magic to automate the change above in my `build.gradle`:
```groovy
eclipse.jdt.file.withProperties { props ->
  props.setProperty "org.eclipse.jdt.core.circularClasspath", "warning"
}
```
may require `gradle eclipseJdt` to be run

**Comment by y0ns0n** [comment]
@fbricon is it possible to add this as a workspace setting? I work in multi-project gradle build with a few 100 projects, would be tough to maintain setting this per-project.

**Comment by snjeza** [comment]
@y0ns0n We will enable it within https://github.com/eclipse/eclipse.jdt.ls/pull/1579
