### ISSUE TITLE
Manual Installation Support 

### ISSUE THREAD

**Issue by santhoshr** [redhat-developer/vscode-java#72]
I'm behind corporate proxy with heavy restriction, I was able to install the plugin using vsix file, but automatic installation of additional language-support files fails, any chance of bundling it for offline installation ? or instruction to get it working manually ?

**Comment by gorkem** [comment]
Basically you need to manually download a .tar.gz file and extract it to ./server folder on the plugin installation. Here is some steps. 

1. Find the URL server binaries to download from [downloadManager.ts](https://github.com/redhat-developer/vscode-java/blob/master/src/downloadManager.ts#L98) 
2. extract the contents to _~/.vscode/extensions/redhat.java-0.0.6/server/_ folder
3. restart

Let me know if this helps.

**Comment by santhoshr** [comment]
It went well, it was little slow initially. Java language support working now, thanks a lot.

**Comment by santhoshr** [comment]
It went well, it was little slow initially. Java language support working now, thanks a lot.
