### ISSUE TITLE
Incorrect constructor being generated for private classes

### ISSUE THREAD

**Issue by afzaal-ahmad-zeeshan** [redhat-developer/vscode-java#725]
This is different than another issue already registered, here, https://github.com/redhat-developer/vscode-java/issues/683. 

##### Environment
- Operating System: Windows 10
- JDK version: JDK 9
- Visual Studio Code version: 1.29.1
- Java extension version: 0.34.0

##### Steps To Reproduce
1. This can be seen in the cases where you have a private class alongside a public class in the same file. 
2. Upon generating a constructor via `ctor`, constructor code for public class is inflated, even in the private classes. 

![screenshot 479](https://user-images.githubusercontent.com/3237834/48870147-7d568400-ee01-11e8-9173-f34d95b81675.png)

##### Current Result
```
package com.afzaalahmadzeeshan.utils;

class Employee {
    public Person() { // <--
        super();
    }
}

public class Person {
    public Person() {
        super();
    }
}
```

##### Expected Result
```
package com.afzaalahmadzeeshan.utils;

class Employee {
    public Employee() {
        super();
    }
}

public class Person {
    public Person() {
        super();
    }
}
``` 
It looks as if the code generator only looks for the public classes in the file, and generate the constructor for that.

**Comment by fbricon** [comment]
Right, this code snippet is rather [dumb](https://github.com/redhat-developer/vscode-java/blob/master/snippets/java.json#L46). The logic needs to be moved to jdt.ls, where the context will be available to provide an accurate completion.
