### ISSUE TITLE
Improve the extension load time by using webpack

### ISSUE THREAD

**Issue by yaohaizh** [redhat-developer/vscode-java#732]
References: 

1.	[VS Code extension sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/webpack-sample)
2.	[Improving load times and performance of Python Extension for VS Code with WebPack](https://medium.com/@don.jayamanne/improving-performance-of-python-extension-for-vs-code-with-webpack-8e4469533f09)

**Comment by fbricon** [comment]
Good idea. I entertained the thought of doing something similar actually, but given my crappy knowledge of the npm ecosystem, it never materialized.

**Comment by fbricon** [comment]
@yaohaizh have you measured the time spend initializing the extension on the vscode side?

**Comment by yaohaizh** [comment]
not yet

**Comment by yaohaizh** [comment]
![perf](https://user-images.githubusercontent.com/17268517/50203899-f6fc7600-039d-11e9-8430-e8a72cc663a6.png)
Not so bad for vscode-java extension. Working on fixing  other java related perf issues.

**Comment by yaohaizh** [comment]
Close it as the extension using webpack now.
