### ISSUE TITLE
Feature request: exclude certain files from triggering autobuild

### ISSUE THREAD

**Issue by paulnortonopi** [redhat-developer/vscode-java#734]
It would be great to have a way to exclude certain files from triggering the autobuild. I'm using an H2 database, and every time I log in it updates the `.h2.server.properties` file in `src/main/resources`. This triggers a restart on the server, which logs me out of the H2 console and creates a vicious cycle. Is there any way to exclude this file from the autobuild detection?

**Comment by fbricon** [comment]
what kind of project is that? maven? gradle?
is .h2.server.properties supposed to be in src/main/resources if it's generated during runtime?
how is your app/server launched?

**Comment by paulnortonopi** [comment]
@fbricon It's a Spring Boot application using Maven and the default H2 configuration. I wondered the same thing, is there a way to configure spring to set a different location for that file? Regardless, the exclusion list would still be useful for issues like this.

**Comment by fbricon** [comment]
@paulnortonopi try this in your pom.xml:
```xml
<build>
  <resources>
    <resource>
      <directory>src/main/resources</directory>
      <excludes>
        <exclude>.h2.server.properties</exclude>
      </excludes>
    </resource>
  </resources>
  ...
</build>
```

**Comment by paulnortonopi** [comment]
@fbricon Fantastic, that worked perfectly! Thank you for taking the time to look into this.

**Comment by fbricon** [comment]
Cool. Closing then.
