### ISSUE TITLE
SourceAction is too heavy, should support lazy load

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#735]
Currently the SourceAction operations will be computed in advance every time when the cursor hovers on editor or typing in the editor. This will cause huge of unnecessary computation. Can we change it to lazy load? 

Always show the source actions on the editor context menus, and only when the user clicks the corresponding menu, then compute the target action and replace WorkspaceEdit.

**Comment by yaohaizh** [comment]
This is an eclipse.jdt.ls issue. Please also log an issue there.

**Comment by testforstephen** [comment]
Tracked on eclipse.jdt.ls side. https://github.com/eclipse/eclipse.jdt.ls/issues/885
