### ISSUE TITLE
Does vscode-java support javaFx11or openFx11?

### ISSUE THREAD

**Issue by jiayaoO3O** [redhat-developer/vscode-java#737]
I can use maven to run javaFx11, but every time I run the program I type in the powershell: `mvn exec:java`, which makes me wonder how to use the breakpoint to debug the program. If I try to click the debug button directly, vscode Will tell me: `Error: JavaFX runtime components are missing, and are required to run this application`, how can I do this to run and debug the javaFx11 application directly?
Here is the javafx11 plugin I added for maven's pom.xml:
![image](https://user-images.githubusercontent.com/22891632/49645078-88422300-fa55-11e8-8116-253cad998c61.png)

**Comment by fbricon** [comment]
can you provide a sample project reproducing this issue?

**Comment by yaohaizh** [comment]
This issue was moved to Microsoft/vscode-java-debug#507
