### ISSUE TITLE
Last Update Issue: Does not recognize Main

### ISSUE THREAD

**Issue by tatecapone** [redhat-developer/vscode-java#738]
[provide a description of the issue]

##### Environment
- Operating System: MacOs Mojave
- JDK version: 10
- Visual Studio Code version: 1.29
- Java extension version: 0.35.0

##### Steps To Reproduce
After creating a project in intellij idea and then opening it in code visual studio, I get the following error. The main class can not be found, when it is declared, the String type (of the main method's argument is not recognized as type).

![captura de pantalla 2018-12-07 a la s 15 13 55](https://user-images.githubusercontent.com/38765698/49665146-bcf0b300-fa32-11e8-961e-0ec68eff7d6a.png)

Thanks!

**Comment by fbricon** [comment]
what sort of project? maven? gradle? intellij?
