### ISSUE TITLE
Usability Improvement: Support `/usr/libexec/java_home` to find path for JDK on macOS

### ISSUE THREAD

**Issue by hannni** [redhat-developer/vscode-java#74]
On macOS there is a standard way to find the location of the JDK, invoking `/usr/libexec/java_home`:
http://stackoverflow.com/questions/18144660/what-is-path-of-jdk-on-mac
https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/java_home.1.html

I was a bit confused that vscode-java didn't work out of the box (also no apparent error message, just a message about installing something in the corner that didn't change. I had to set `java.home` in the settings to the value returned by `/usr/libexec/java_home` and then it worked. I guess this should be true on most macOS systems and vscode-java could use it directly to find the java home path, making installation easier.

**Comment by gorkem** [comment]
We are actually using a [utility](https://www.npmjs.com/package/find-java-home) to resolve JAVA_HOME which in turn seems to be using the mac utility that you have mentioned.

Does your JAVA_HOME (the value returned from mac utility) point to a JRE or JDK?

**Comment by hannni** [comment]
`JAVA_HOME` is not set. I tried doing the same thing as the library does and it should work:

```bash
 > env | grep JAVA
 > which javac
/usr/bin/javac
 > readlink /usr/bin/javac
/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/javac
 > ls /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/ | grep home
java_home
 > /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home
 > /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home
```

When I remove ` "java.home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home"` from my `settings.json` again, the status bar keeps says again "Starting Java Language Server...".

**Comment by hannni** [comment]
I guess the bug is here: https://github.com/redhat-developer/vscode-java/blob/810cc60af28fbe22ff27863455fd56e77d24dbdb/src/requirements.ts#L71

This always sets the `JAVA_HOME` environmental variable, even if there isn't a correct one found. find-java-home then takes this variable and returns it as a valid java home directory.
