### ISSUE TITLE
The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by scotshall** [redhat-developer/vscode-java#743]
Receiving the following error when opening a Maven project folder:

The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

##### Environment
- Operating System: Windows 10
- JDK version: both **java version "1.8.0_141"** AND **openjdk version "11.0.1" 2018-10-16**
- Visual Studio Code version: Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

- Java extension version: 0.35.0 (November 30th, 2018)

##### Steps To Reproduce
1. Install the **Language Support for Java(TM) by Red Hat** extension (no other extensions are active)
2. Create a new Maven project using the quickstart archetype
2. Open the folder with the new Maven project
3. See the error

I am unable to attach the Java Language Server log file.  I followed the steps [here](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging), but when I run the the `Java: Open Java Language Server log file` command nothing happens.

**Comment by scotshall** [comment]
I've also set up Code to run on the Windows Ubuntu app an am getting the same error.

**Comment by scotshall** [comment]
I tried cleaning the workspace directory as per the instructions found [here](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory), but I am getting the same error.

**Comment by fbricon** [comment]
do you see any org.eclipse.equinox.launcher*.jar processes when running `jps`? If you find any try to kill them.
Also, try to run with the latest Java 1.8 version.

**Comment by scotshall** [comment]
There are no jps processes running other than jps itself.

I've updated to the latest version of JDK 8 (**java version "1.8.0_191"**), but I'm getting the same error.

I was able to manually start the Eclipse JDT Language Server following the instructions [here](https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line), so I know it will run (although I still get the same error in code even if the server is manually started).

**Comment by fbricon** [comment]
any antivirus running?

**Comment by scotshall** [comment]
It's a corporate PC, so, unfortunately, yes.  However, I'm not see anything in it's logs about it blocking any java or code processes.  Also, I was able to (temporarily) borrow a PC and I'm not getting any errors there when I load a Java project in code.  (I suppose they could be using different antivirus definitions, but they're both corporate so they should be in sync.)  

Those in change of such things have decided to use Carbon Black for AV protection.  Do you know of any specific issues with Carbon Black?

**Comment by fbricon** [comment]
I'd be curious if disabling the AV (probably wanna be offline for that) makes any difference. And I know nothing about AVs, except they can wreak havoc sometimes.

In your settings.json, try to :
- set `"java.trace.server":"verbose"`
- add `-Dlog.level=ALL` to the default "java.jdt.ls.vmargs" value

after restarting, get the Java server logs from VS Code's Output view

**Comment by scotshall** [comment]
Thank you for giving me the "java.jdt.ls.vmargs" setting, I was able to figure out what was going wrong.

I had installed the [Lombok Annotations Support for VS Code](https://github.com/GabrielBB/vscode-lombok) extension awhile back and decided to remove it.  However, the extension added some parameters to the **java.jdt.ls.vmargs** setting:
`"-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:\"C:\\Users\\SHall\\.vscode\\extensions\\gabrielbb.vscode-lombok-0.9.7/server/lombok.jar\" -Xbootclasspath/a:\"C:\\Users\\SHall\\.vscode\\extensions\\gabrielbb.vscode-lombok-0.9.7/server/lombok.jar\""`

When I removed the extension, the settings were still present but the Language Server was unable to the load the manifest from the lombok.jar file (because it was deleted).  This caused the Language Server to fail to start.

After adding the `-Dlog.level=ALL` parameter to the **java.jdt.ls.vmargs** setting, I was finally able to see the error in the output view.  I've put the **java.jdt.ls.vmargs** setting back to its default value and everything is working properly again.

Thank you for your help!  You can close this issue.

**Comment by fbricon** [comment]
Ok, good to know, that info might be helpful to others

**Comment by Ivaylo2017** [comment]
I had this problem too and it had occurred after i changed my _JAVA_OPTIONS env variable on Windows. I noticed that some plugins import their own setting in VS Code Settings -> settings.json 
To fix the error - You have to update them with -Xmx to be larger than the system -Xms value. 
I made them identical in both locations and the error is gone. Hope this helps!

**Comment by FieteO** [comment]
I also had this error caused by lombok in combination with the [Remote - SSH Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh).
The `java.jdt.ls.vmargs` setting in settings.json was set to the path of lombok on my local machine. (`- javaagent:\"C:\\Users\\<user>\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\lombok.jar\"`)

However it needs the path of lombok on the remote machine. (`-javaagent:\"/home/ubuntu/.vscode-server/extensions/gabrielbb.vscode-lombok-1.0.1/server/lombok.jar\`")

**Comment by testforstephen** [comment]
@FieteO Your concern is fair enough, i also created an issue at the vscode-lombok extension side https://github.com/GabrielBB/vscode-lombok/issues/43.

**Comment by ThiagoAnd** [comment]
> Thank you for giving me the "java.jdt.ls.vmargs" setting, I was able to figure out what was going wrong.
> 
> I had installed the [Lombok Annotations Support for VS Code](https://github.com/GabrielBB/vscode-lombok) extension awhile back and decided to remove it. However, the extension added some parameters to the **java.jdt.ls.vmargs** setting:
> `"-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:\"C:\\Users\\SHall\\.vscode\\extensions\\gabrielbb.vscode-lombok-0.9.7/server/lombok.jar\" -Xbootclasspath/a:\"C:\\Users\\SHall\\.vscode\\extensions\\gabrielbb.vscode-lombok-0.9.7/server/lombok.jar\""`
> 
> When I removed the extension, the settings were still present but the Language Server was unable to the load the manifest from the lombok.jar file (because it was deleted). This caused the Language Server to fail to start.
> 
> After adding the `-Dlog.level=ALL` parameter to the **java.jdt.ls.vmargs** setting, I was finally able to see the error in the output view. I've put the **java.jdt.ls.vmargs** setting back to its default value and everything is working properly again.
> 
> Thank you for your help! You can close this issue.

Thanks !! I had the same problem here . Installed lombok and after that deleted it but the settings for it remain, just deleted it.

**Comment by somilrana** [comment]
I have tried all the above hacks nothing works as I tried to fix one another got breaked up.. But here is  a simple solution to realy get rid of this error.
1. Unistall visual Studio code Editor.
2. Go to the following directory: 
    Windows: <code> %APPDATA%\Code </code>
    macOS:  <code> $HOME/Library/Application Support/Code </code>
    Now Delete this code folder.
3. Go to  directory: <code> C:\Users</code><code>\<username></code>
    Delete <code> .vscode </code> folder in it too.
4. Now reinstall visual studio code editor and the extension. 
5. Now it will surely Work. You good to go.

**Comment by Pedroteixeirabisognin** [comment]
Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace. 
It works for me.

**Comment by akuhelmi** [comment]
> 
> 
> Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace.
> It works for me.

This worked. Thank you.

**Comment by benzekrimohammed** [comment]
> Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace.
> It works for me.

Thanks , it worked for me

**Comment by AnasAar06** [comment]
> Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace.
> It works for me.

It works also for me, Thanks .

**Comment by rafidka** [comment]
> Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace.
> It works for me.

![image](https://user-images.githubusercontent.com/442447/134264916-2062a4d5-9589-42c4-b55f-36eea5d18959.png)

**Comment by Teague-S** [comment]
> Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace. It works for me.

So helpful and simple, thanks, man.

**Comment by faxterol** [comment]
I had this issue in code-server and that fix didn´t work for me. I found this another fix:


Delete and recreate this folder: ~/.local/share/code-server/User/workspaceStorage
Restart code-server

Let code-server reload the extensions.

**Comment by jconlon** [comment]
Had this issue but Cleaning and Restarting the server did not fix it.  (Note: Having a second vscode instance running another Java project may have suppressed the Cleaning process.  So I brought both instances down and just deleted my `/.config/Code/User/workspaceStorage` directory.  Restarting my VsCode recreated it and all was good.

**Comment by xjwwjx** [comment]
where is the ~/.config/Code/User/workspaceStorage in windows ?

**Comment by xjwwjx** [comment]
> Had this issue but Cleaning and Restarting the server did not fix it. (Note: Having a second vscode instance running another Java project may have suppressed the Cleaning process.) So I brought both instances down and just deleted my `~/.config/Code/User/workspaceStorage` directory. Restarting my VsCode recreated it and all was good.

where is the ~/.config/Code/User/workspaceStorage in windows ?

**Comment by liechtir** [comment]
same issue here when using the http://dcevm.github.io/ DCEVM enhanced JVM. when using the regular openjdk, all works like a charm.

**Comment by xingzhuimeteorite** [comment]
> > Had this issue but Cleaning and Restarting the server did not fix it. (Note: Having a second vscode instance running another Java project may have suppressed the Cleaning process.) So I brought both instances down and just deleted my `~/.config/Code/User/workspaceStorage` directory. Restarting my VsCode recreated it and all was good.
> 
> where is the ~/.config/Code/User/workspaceStorage in windows ?

i delete that folder , did not fix . 
i use windows, it is  C:\\Users\\<username>\\AppData\\Roaming\\Code\\User

**Comment by xingzhuimeteorite** [comment]
AppData\Roaming\Code\logs\20220303T100346\exthost1 
in this path , i find log 
```

[2022-03-03 10:03:54.913] [exthost] [warning] [redhat.java] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.

[2022-03-03 10:03:54.991] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[java]', provide the URI of a resource or 'null' for any resource.

```

i do not known this is issuse?

**Comment by ktarun73** [comment]
Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace.
It works for me you can also do the same.

**Comment by xingzhuimeteorite** [comment]
> Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace. It works for me you can also do the same.

I'm trying and I'm failing.

**Comment by xingzhuimeteorite** [comment]
i solve my question, i download latest file of .visx from this repo. 
use 
`code --install-extension [value].visx`
 after open vscode , fix this question .

 at the sametime i check the exthost.log ,
 the error message[cannot read property sendrequest] still exist. hope this way can help .

**Comment by PedroVCorsino** [comment]
> Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace. It works for me.

Thanks bro

**Comment by Armaan533** [comment]
> Press CTRL + SHIFT + P, and type Java: Clean Java Language Server Workspace. It works for me.

Thank you!! It worked

**Comment by snjeza** [comment]
@scotshall Could you try to remove
```
c:\\Users\\51140\\.vscode\\extensions\\redhat.java-1.7.0-win32-x64
``` 
and reinstall VS Code Java?

**Comment by scotshall** [comment]
> @scotshall Could you try to remove
> 
> ```
> c:\\Users\\51140\\.vscode\\extensions\\redhat.java-1.7.0-win32-x64
> ```
> 
> and reinstall VS Code Java?

@snjeza , This item was resolved for me over 4 years ago.  The recent comments are from other users experiencing similar, but different issues from mine.

**Comment by Yanksi** [comment]
> > @scotshall Could you try to remove
> > ```
> > c:\\Users\\51140\\.vscode\\extensions\\redhat.java-1.7.0-win32-x64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and reinstall VS Code Java?
> 
> @snjeza , This item was resolved for me over 4 years ago. The recent comments are from other users experiencing similar, but different issues from mine.

the problem gets fixed by itself when I switched to the pre-release version of the extension. Thanks for your help anyway!!

**Comment by RicoAfoat** [comment]
I've tried all the methods upon but failed to find a solution. There's a magic solution for remote users. Just quit vscode and use other tools to connect to remote machine and delete the whole vscode server configuration folder. Then use vscode to connect again. Re-download extensions needed (java developer pack). Everything will work smoothly. At least on my computer.

**Comment by quinnInChina** [comment]
i have tried everything above-mentioned, but also exist this issue. 
![image](https://user-images.githubusercontent.com/2950260/204687879-827923f0-1de2-4fec-a498-b11d86129fad.png)
the java log shows this:

> /Users/kwin/.vscode/extensions/georgewfraser.vscode-javac-0.2.42/dist/launch_mac.sh: line 13: /Users/kwin/.vscode/extensions/georgewfraser.vscode-javac-0.2.42/dist/mac/bin/java: cannot execute binary file

Any idea?

**Comment by snjeza** [comment]
> the java log shows this:

@quinnInChina Could you try to remove the `Language Server for Java using the Java compiler API` extension. It isn't compatible with `Language Support for Java by Red Hat`

**Comment by quinnInChina** [comment]
> > the java log shows this:
> 
> @quinnInChina Could you try to remove the `Language Server for Java using the Java compiler API` extension? It isn't compatible with `Language Support for Java by Red Hat`
oh great! thank you, its ok now

**Comment by tassoneroberto** [comment]
> I have tried all the above hacks nothing works as I tried to fix one another got breaked up.. But here is a simple solution to realy get rid of this error.
> 
> 1. Unistall visual Studio code Editor.
> 2. Go to the following directory:
>    Windows: ` %APPDATA%\Code `
>    macOS:  ` $HOME/Library/Application Support/Code `
>    Now Delete this `code` folder.
> 3. Go to  directory: ` C:\Users``<username>`
>    Delete ` .vscode ` folder in it too.
> 4. Now reinstall visual studio code editor and the extension.
> 5. Now it will surely Work. You good to go.

Deleting the folder `%APPDATA%\Code` worked for me
