### ISSUE TITLE
a package notice err

### ISSUE THREAD

**Issue by hjb912** [redhat-developer/vscode-java#750]
Issue Type: Bug

a.java empty file in package A, i write "package A", then notice me "The declared package "A" does not match the expected package ""Java(536871240)", however, i move this a.java to B directory, then move back to A directory, this notice disappear! why is it..

VS Code version: Code 1.30.0 (c6e592b, 2018-12-11T22:22:15.793Z)
OS version: Darwin x64 18.2.0

**Comment by yaohaizh** [comment]
@hjb912 What the type of your project? Could you provide a gif for reproducing this issue. 
Thanks.

**Comment by danjmillier** [comment]
I'm also getting this same error myself:

![image](https://user-images.githubusercontent.com/2092466/51639262-73025480-1f2e-11e9-8b92-1e046b41be85.png)

**Comment by fbricon** [comment]
@danjmillier can you reload vscode?

**Comment by danjmillier** [comment]
@fbricon I've tried reloading and even restarting my laptop, still no dice. Oddly enough, if I make a "main2" folder and change "package main" to "package main2" it works and I'm not sure why..

**Comment by fbricon** [comment]
So this is caused by jdt.ls's invisible project mechanism, that initializes it's source directory as "_/whatever/package", because the opened Java file was empty, so the initial package could not be inferred.

**Comment by the1derer** [comment]
I am also facing the same issue.

**Comment by yaohaizh** [comment]
@testforstephen Could you help investigate this issue?

**Comment by testforstephen** [comment]
When the language server is activated by an empty standalone java file, a new idea is trying to search a non empty java file from the same directory. If found, use the non empty java file to resolve package name, otherwise, take the workspaceRoot as source root and then the relative path to workspaceRoot should be the package name.

@fbricon any thoughts?

**Comment by fbricon** [comment]
yeah you can try that
