### ISSUE TITLE
Configuring SSL connection for debugging web app

### ISSUE THREAD

**Issue by woogers** [redhat-developer/vscode-java#755]
I'm attempting to move to VSCode for debugging a Spring web app. My organization requires SSL connections to our database, and this works fine on our Tomcat server, when specifying trust store, key store, and passwords by setting them in a $JAVA_OPTS environment variable. I have tried both passing these values to java.jdt.ls.vmargs and using them in application-internal.properties, but when debugging the app, any action that tries to query the database results in the application not being able to acquire a connection to the database. Disabling the SSL requirement on the database results in the application being able to connect successfully, so I assume there is an issue with the way I am configuring the SSL settings for the VSCode extension.

my vmargs setting looks like this:
` "java.jdt.ls.vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:\"C:\\Users\\user\\.vscode\\extensions\\gabrielbb.vscode-lombok-0.9.7/server/lombok.jar\" -Xbootclasspath/a:\"C:\\Users\\user\\.vscode\\extensions\\gabrielbb.vscode-lombok-0.9.7/server/lombok.jar\"  -Djavax.net.ssl.trustStore=C:/Users/user/Desktop/app/cacerts -Djavax.net.ssl.trustStorePassword=pass -Djavax.net.ssl.keyStore=C:/Users/user/Desktop/app/keystore -Djavax.net.ssl.keyStorePassword=pass",`

Is this the correct way to configure the Java extension, or is there a way to pass the JAVA_OPTS environment variable to the jvm?

##### Environment
- Operating System: Windows 7 Professional 
- JDK version: 1.8.0_121
- Visual Studio Code version: 1.29.1
- Java extension version: 0.36.0

##### Steps To Reproduce
1. set keystore and truststore in java.jdt.ls.vmargs in settings.json
2. start debugging app
3. launch action that queries the database

**Comment by fbricon** [comment]
Running java code is out of scope of vscode-java. You should open a ticket with [vscode-java-debug](https://github.com/Microsoft/vscode-java-debug/issues).

That being said, since it's a runtime issue, you probably want to set the "vmArgs" property in your .vscode/launch.json's launch configuration instead.
