### ISSUE TITLE
Errors are not being highlighted or detected in Ubuntu

### ISSUE THREAD

**Issue by marianolc** [redhat-developer/vscode-java#759]
Using the same code, same versions but different OS. I have different behavior in the IDE. Windows is able to detect the errors and show them on screen. Meanwhile Ubuntu doesn't show anything.

##### Environment
- Operating System: Ubuntu 18.04.1 LTS
- JDK version: openjdk version "1.8.0_191"
- Visual Studio Code version: 1.30.1
- Java extension version: Extension pack 0.4.0 / Language support for java: 0.36.0

##### Steps To Reproduce
1. Open the directory in Visual Studio Code
2. Obvious errors are not remarked in the code (missing import, using variables that weren't declared).
3. Open the same directory in Windows. The errors are highlighted.

[javaCert.zip](https://github.com/redhat-developer/vscode-java/files/2729858/javaCert.zip)

Developer Console logs:

![imagen](https://user-images.githubusercontent.com/2932154/50728888-83c16680-10f6-11e9-9205-4bf866896b52.png)

[javaserver.log](https://github.com/redhat-developer/vscode-java/files/2729874/javaserver.log)

Some screenshots of how is working on windows and ubuntu: 

Windows(errors highilighted, and listed in the "Problems" tab):

![imagen](https://user-images.githubusercontent.com/2932154/50728809-5b853800-10f5-11e9-9029-fa678e0bf1bb.png)

Ubuntu(Errors are not highlighted, "Problems" is only showing one warning):

![imagen](https://user-images.githubusercontent.com/2932154/50728808-52946680-10f5-11e9-991b-a79dbd3c1c9d.png)

**Comment by snjeza** [comment]
Your log shows that you are using the 0.30.0 version of Java LS on Ubuntu.

**Comment by marianolc** [comment]
Interesting.. I was using the "Java Extension Pack" that include that package. Uninstalled it and installed every part separated and it's working.
