### ISSUE TITLE
How to tell vscode-java extension to add jars to the classpath.

### ISSUE THREAD

**Issue by negiDharmendra** [redhat-developer/vscode-java#760]
[provide a description of the issue]

##### Environment
- Operating System: osx
- JDK version:  1.8.0_181
- Visual Studio Code version: 1.30.1
- Java extension version: 0.36.0

##### Steps To Reproduce
1. Create a java project.
2. Try to import something outside of project root.

**Comment by jdneo** [comment]
@negiDharmendra What's your project kind? Maven/Gradle/No build tools?

**Comment by rgrunber** [comment]
If it's a Maven or Gradle project, you'd likely need to do that through the build metadata files (eg. pom.xml, settings.gradle, etc.). If you're dealing with an unmanaged/invisible/standalone project, see https://github.com/redhat-developer/vscode-java/issues/1946#issuecomment-842434515 . It can be done through `java.project.referencesLibraries`.
