### ISSUE TITLE
Extract Interface from class

### ISSUE THREAD

**Issue by vairamsvsjdo** [redhat-developer/vscode-java#761]
Need ability to extract interface from class  or update interface from available methods not already in an interface or provide option to update an interface if an interface is implemented in the class as an additional option

##### Environment
- Operating System: Windows_NT x64 10.0.18309
- JDK version: 11
- Visual Studio Code version: 1.30.1
- Java extension version: 11

1. RIght click a class script in editor
2. Have option to extract Interface

**Comment by okonon** [comment]
This would be awesome!

**Comment by sirReeall** [comment]
yes this would be great

**Comment by vulkman** [comment]
+1

**Comment by prakritidev** [comment]
any update on this feature ?

**Comment by SlappyAUS** [comment]
Any updates?

**Comment by Osolemio44** [comment]
+1

**Comment by itaygoz** [comment]
+1

**Comment by prakritidev** [comment]
I can take this up if nobody is working on this. As this is very old requested feature.

**Comment by lucksjb** [comment]
+1

**Comment by edurbs** [comment]
+1

**Comment by dax-westerman** [comment]
+1

**Comment by CsCherrYY** [comment]
I would like to take a look and make a prototype these days. @snjeza WDYT?

**Comment by snjeza** [comment]
@CsCherrYY np

**Comment by CsCherrYY** [comment]
Now we have an upstream PR making the related utility available in jdt.ui side: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/344
