### ISSUE TITLE
Automatically add package line to new file on creation

### ISSUE THREAD

**Issue by botscholar-scott** [redhat-developer/vscode-java#770]
When creating a new file through the context menu from the Explorer View (right mouse click and choose the first item New File). It would be fantastic to automatically add the package line based on the directory structure (or perhaps provide a UI to type it in).

##### Environment
- Operating System: macOS Mojave 10.14.2 
- JDK version: 1.8.0_191
- Visual Studio Code version: 1.30.2
- Java extension version: 0.37.0

##### Steps To Reproduce
1. Open Explorer View (shift-command-E)
2. Right click on a folder and select New File
3. Type in filename followed by return 

##### Current Result
An empty file is created.

##### Expected Result
An new file is created with a package line and class stub

**Comment by fbricon** [comment]
that goes beyond vscode-java's scope. This is controlled upstream, in VS Code itself.
Currently, what you can do is, once the java file has been created, invoke the class snippet, like in https://www.youtube.com/watch?v=o4BTKD3iyYE

When the file is in a package directory, the package is automagically added.

**Comment by rgrunber** [comment]
This has been the case for some time now.
