### ISSUE TITLE
Option to add 'final' modifier where possible.

### ISSUE THREAD

**Issue by ncastrocosta** [redhat-developer/vscode-java#774]
It'd be nice to have an option to add 'final' modifier where possible.

Thanks!

**Comment by DavisZeidaks** [comment]
This would be awesome together with some sort of passive check with quick fix to quickly add final to method arguments and local fields

**Comment by fbricon** [comment]
@NikolasKomonen please look into this one

**Comment by NatoBoram** [comment]
Hey! I see this issue is closed, but I can't figure out how to use this lint. How do we enable it?

**Comment by testforstephen** [comment]
![finalModifier](https://user-images.githubusercontent.com/14052197/108709682-fc414680-754d-11eb-8bb0-de9bfbfe7e7d.gif)

**Comment by NatoBoram** [comment]
Is there a way to enable the red squiggly lines when this is possible?
