### ISSUE TITLE
Could not create parent directory for lock file

### ISSUE THREAD

**Issue by franciscocpg** [redhat-developer/vscode-java#781]
After upgrading visual code and this extension I'm seeing the following error when opening my gradle projects and trying to run it.

```
[Error - 11:07:49] 29/01/2019 11:07:49 Error occured while building workspace. Details: 
message: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-4.10-bin.zip'.
Could not create parent directory for lock file /usr/share/java/gradle/wrapper/dists/gradle-4.10-bin/bg6py687nqv2mbe6e1hdtk57h/gradle-4.10-bin.zip.lck;code: 0
```

##### Environment
- Operating System: 
Antergos Linux 4.20.4-arch1-1-ARCH

- JDK version:
openjdk version "1.8.0_202"

- Visual Studio Code version:
1.30.2

- Java extension version:
0.37.0

##### Steps To Reproduce
1. Open a gradle project
2. Try to run it

**Comment by fbricon** [comment]
do your projects use the gradle wrapper? or do you have a gradle installation on the machine? Do those projects build from CLI?

**Comment by franciscocpg** [comment]
> do your projects use the gradle wrapper? or do you have a gradle installation on the machine?

Both. My project uses gradle and I also have gradle installed on my machine.

> Do those projects build from CLI?

Yes, it does build from cli (I'm using the wrapper to build).

**Comment by psxvoid** [comment]
Having the same error message (not verified whether it happens after an update or not) - for me, it just broken.

Reporting because of I on a different platform (**Environment**):
Operating System: Windows 10 x64 1809

JDK version: "11.0.2 LTS"

Visual Studio Code version:
1.31.0-insider (system-setup)

Java extension version:
0.38.0

**Comment by snjeza** [comment]
>>    do your projects use the gradle wrapper? or do you have a gradle installation on the machine?

> Both. My project uses gradle wrapper and I also have gradle installed on my machine.

@franciscocpg do you have the gradlew file in the project's root directory?

> Gradle is installed via chocolately first time but then reinstalled as binary

@psxvoid could you try the following:

```
set GRADLE_HOME=<your_gradle_home>
vscode ...
```

**Comment by franciscocpg** [comment]
@snjeza 
Yes, I do.

**Comment by snjeza** [comment]
@franciscocpg could you provide a project example?

**Comment by snjeza** [comment]
@franciscocpg could you try the following:
```
cd <your_project>
export GRADLE_USER_HOME=~/.gradle
code .
```

``

**Comment by franciscocpg** [comment]
@snjeza 
I had already tried it before without any luck. It looks like `GRADLE_USER_HOME` environment variable value is not being respected.

I don't know if there is another way to see the environment variable value set at vscode, but I'm printing the value from the vscode terminal to confirm it.
```
echo $GRADLE_USER_HOME
/home/francisco/.gradle
```

**Comment by snjeza** [comment]
@franciscocpg could you show the gradle/wrapper/gradle-wrapper.properties file?

```
cd <your_project>
cat gradle/wrapper/gradle-wrapper.properties
```

**Comment by franciscocpg** [comment]
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by snjeza** [comment]
```
cd <your_project>
./gradlew build
```

**Comment by fbricon** [comment]
@franciscocpg can you open the project in Eclipse IDE (with Buildship -the gradle integration- installed)?

**Comment by franciscocpg** [comment]
@snjeza 
About https://github.com/redhat-developer/vscode-java/issues/781#issuecomment-460375874.
It works as expected.

**Comment by snjeza** [comment]
```
ls ~/.gradle/wrapper/dists/gradle-5.1.1-bin/
```
if the gradle-5.1.1-bin directory exists you can try:
```
export GRADLE_HOME=~/.gradle/wrapper/dists/gradle-5.1.1-bin
code .
```

**Comment by franciscocpg** [comment]
The folder exists but still got the same error but running the command you've mentioned I still get the same error in `vscode`.

**Comment by snjeza** [comment]
@franciscocpg Could you attach your VS Code and workspace settings?

**Comment by franciscocpg** [comment]
I found the root cause.
`vscode-java` was creating a file called `.settings/org.eclipse.buildship.core.prefs` with `gradle.user.home` value fixed to `/usr/share/java/gradle`.

I was able to fix the problem by removing `.settings/org.eclipse.buildship.core.prefs` and running `Clean the java language server workspace`. Now `vscode-java` creates the file with the following content:
```
connection.project.dir=
eclipse.preferences.version=1
```
and everything is working as expected. 

It looks like the problem is a mix of files cached at java language server workspace and `GRADLE_HOME` set. So when you change its value, it has no effect until you clean the java language server workspace.

**Comment by franciscocpg** [comment]
Here is the previous `.settings/org.eclipse.buildship.core.prefs` content before I remove it and clean the java language server workspace.
```
arguments=
auto.sync=false
build.scans.enabled=false
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=
eclipse.preferences.version=1
gradle.user.home=/usr/share/java/gradle
java.home=
jvm.arguments=
offline.mode=false
override.workspace.settings=true
show.console.view=true
show.executions.view=true
```

**Comment by MuhammadIrfanKhan9484** [comment]
HI i'm facing issue 

Could not create parent directory for lock file C:\Program Files\Android\Android Studio1\plugins\gradle\lib\wrapper\dists\gradle-6.1.1-all\cfmwm155h49vnt3hynmlrsdst\gradle-6.1.1-all.zip.lck

**Comment by Rohitkanna1999** [comment]
![IMG_20200627_133740](https://user-images.githubusercontent.com/66553982/85919309-b4b3cf00-b887-11ea-80c8-b6bbf7ec8af2.jpg)

**Comment by juhijha170** [comment]
I am getting this same error please help with the solutions

Could not create parent directory for lock file C:\Program Files\Android\Android Studio\gradle\gradle-4.10.1\wrapper\dists\gradle-6.1.1-all\cfmwm155h49vnt3hynmlrsdst\gradle-6.1.1-all.zip.lck

**Comment by wadewadewadewadewadewade** [comment]
On WIndows 10 I just went to `C:\Users\<my_user>\` and deleted .gradle, then re-ran `react-native run-android` in vscode and it worked.

**Comment by m-arslan-hafeez** [comment]
On Linux I faced this issue when I tried to open a project that was built with an old SDK, I was able to solve this issue by making my bin folder writable in the user directory. You can try following these steps:
Step 1: Open the terminal as root
Step 2: Write the following command:
`sudo chmod 777 /usr/bin/`
Step 3: Enter
Step 4: Now try again to update your build.gradle file in the app level.
