### ISSUE TITLE
Cause of server startup failure is no longer logged

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#782]
A bad lombok path in jdt.ls.vmargs can prevent the jdt.ls VM to start, this used to be logged as described in the [wiki](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-vscode-java-logs), but we lost that capability somehow. This makes troubleshooting issues like #681 extremely difficult.

So, we need to be able to log that kind of startup failure, like before.

**Comment by rgrunber** [comment]
Looks like this was resolve in the mentioned issue. https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs will show the additional information.
