### ISSUE TITLE
Code completion disappearing when typing too fast

### ISSUE THREAD

**Issue by veluria** [redhat-developer/vscode-java#787]
When I'm typing the beginning of a method name I want to auto complete, the code completion simply disappears. I need to type character by character for it to stay available. 

##### Environment
- Operating System: Arch Linux 
- JDK version: openjdk 11.0.2
- Visual Studio Code version: 1.30.2
- Java extension version: 0.38.0

##### Steps To Reproduce
1. Start auto complete on any kind of object
2. Type a method name rather quick
3. See no suggestions anymore (or simply wrong one's)

##### Current Result
Suggestions disappear when typing to fast.

##### Expected Result
Auto complete narrows down suggestions by typed text.

##### Additional Informations

![new](https://user-images.githubusercontent.com/1119538/52418553-96143300-2aee-11e9-9d0d-192d0942645e.gif)

Am I doing something wrong here/is perhaps something wrong with my setup or is this always the case?

**Comment by fbricon** [comment]
Try disabling all other Java extensions, see if that gives you a better performance. Maybe someone is being naughty. 
If it doesn't work, please attach your server [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs) here.

**Comment by fbricon** [comment]
How big is you project (number of modules, classes)?

**Comment by veluria** [comment]
> Try disabling all other Java extensions, see if that gives you a better performance. Maybe someone is being naughty.
> If it doesn't work, please attach your server [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs) here.

You are right. Sorry, I should have tried that before opening a bug report. Once I disable 'Spring Boot Tools', the problem goes away. The auto complete also feels much smoother again and starts suggesting things right away. Rather sad, because otherwise it's a pretty useful extension. I'll see if this can somehow be disabled.

**Comment by fbricon** [comment]
Thanks for checking. I'm gonna close this one then.

poke @martinlippert @kdvolder ;-)

**Comment by veluria** [comment]
Should have looked there first, perhaps. So if anyone stumbles upon this: https://github.com/spring-projects/sts4/issues/193

**Comment by martinlippert** [comment]
Installing the latest CI build of the Spring Tools extension from here (http://dist.springsource.com/snapshot/STS4/nightly-distributions.html) solves the issue.
