### ISSUE TITLE
No Reload Adoption: Update `javaExtensions` contributions when extensions are added/removed

### ISSUE THREAD

**Issue by sandy081** [redhat-developer/vscode-java#794]
Hi, I am a developer from VS Code and in the last release `1.31`, we added a new feature - no reload is required on installing an extension - https://code.visualstudio.com/updates/v1_31#_no-reload-on-install

But there are some exceptions to it as mentioned in the doc. If the extension is contributing to external contribution points, then the extension requires reload after installing. Hence, we added a new listener API for the owners of the external contribution point to listen to extension addition/removal and can update its state - https://code.visualstudio.com/updates/v1_31#_extensions-change-event.

Our plan is to give extensions one milestone/month for adopting to the above API and make the other extensions consuming their contribution points ready for no reload. It means that from next release, above exception will be removed and all extensions are added to VS Code window immediately after installation and no reload is shown.

We scanned the extensions in the marketplace and found out that this extension uses an external contribution point `javaExtensions` and requires reload on install. I found out from code that this extension owns this contribution point and couple of popular extensions (vscjava.vscode-java-test, vscjava.vscode-java-debug) contributes to it which forces them to reload on install. So please adopt to the above API and make this and other contribution extensions ready for no reload.

Thanks

**Comment by yaohaizh** [comment]
@sandy081 Thanks for bringing up this issue. We will adopt the API shortly.

**Comment by yaohaizh** [comment]
@sandy081 
Something need further clarify: 

> Hence, we added a new listener API for the owners of the external contribution point to listen to extension addition/removal and can update its state - https://code.visualstudio.com/updates/v1_31#_extensions-change-event.

What's the state mean here? Could we change some internal specific state via vscode API inform VSCode to reload? Or it is required for extension to provide no reload behavior?

**Comment by sandy081** [comment]
@yaohaizh You do not need to say any to VS Code. By state I mean following:

I think when your extension is activated, you will be accessing all extensions using `vscode.extensions.all` and their contributions to read `javaExtensions` contribution. You need to do this again when there is a change in `vscode.extensions.all` to accept new `javaExtensions` or remove existing `javaExtensions`. 

Let me know if it makes sense?

**Comment by yaohaizh** [comment]
@sandy081 Thanks for the answer. 

@fbricon For the first step, we need check the javaExtensions and provide reload hints if the change require reload. 

In order to provide a fully no reload behavior, I logged an issue here: https://github.com/eclipse/eclipse.jdt.ls/issues/932

**Comment by fbricon** [comment]
Our current approach is to display a message when we detect the Java language server requires a reload.
<img width="461" alt="Screen Shot 2019-03-14 at 12 37 13 PM" src="https://user-images.githubusercontent.com/148698/54375225-074b8680-4657-11e9-8637-397dea6fcf82.png">

which is not the ideal solution. 
Now, we might still be able to comply with the no-reload requirements in a next iteration, if we manage to stop and reload the Java Language server within vscode-java, without restarting the extension. 

@yaohaizh, please let me know if this is possible. I'll keep this issue open in the meantime

**Comment by jdneo** [comment]
Install a new extension does not need to reload now, supported via https://github.com/redhat-developer/vscode-java/pull/2729
