### ISSUE TITLE
Code action: add static import

### ISSUE THREAD

**Issue by jnesspro** [redhat-developer/vscode-java#796]
Hi. I wonder that there is no way to quickly add static import (+ refactor all occurances).
It is really actual while writing tests or using spring 5 functional routing for example.

* Visual Studio Code version: 1.32
* Java extension version: 0.38

**Comment by cedric05** [comment]
static import itself throwing error, in my case

**Comment by testforstephen** [comment]
@jnesspro By default, the Java extension will only recommend static import for the members below.
```
    "java.completion.favoriteStaticMembers": [
        "org.junit.Assert.*",
        "org.junit.Assume.*",
        "org.junit.jupiter.api.Assertions.*",
        "org.junit.jupiter.api.Assumptions.*",
        "org.junit.jupiter.api.DynamicContainer.*",
        "org.junit.jupiter.api.DynamicTest.*",
        "org.mockito.Mockito.*",
        "org.mockito.ArgumentMatchers.*",
        "org.mockito.Answers.*"
      ]
```

If you want to enable static import for spring 5 members, you need modify the user settings and append your favorite package into `java.completion.favoriteStaticMembers`.

**Comment by testforstephen** [comment]
@cedric05 Can you execute VS Code command `Java: Open Java Language Server log file`, and share us the log?

**Comment by cedric05** [comment]
@testforstephen sorry for filing wrong. its working.

**Comment by fbricon** [comment]
You asked for it, @testforstephen delivered:

![Mar-26-2019 15-56-04](https://user-images.githubusercontent.com/148698/55029144-b422ed80-4fdf-11e9-965b-67a4bf9625ee.gif)

**Comment by notmattlythgoe** [comment]
@fbricon How are you bringing up the menu?

**Comment by fbricon** [comment]
Click on static method, `Ctrl+.` (`Cmd+.` on mac) or click on lightbulb or right-click -> Code Action

**Comment by slide222** [comment]
![image](https://user-images.githubusercontent.com/47318227/87243675-31be7700-c438-11ea-89da-b27efefe819a.png)
![image](https://user-images.githubusercontent.com/47318227/87243738-b6a99080-c438-11ea-86bb-e0f2c60aa543.png)

@fbricon I don't have the convert to import static in the Code Action menu and the shortcut is not working either. The only way to add static imports for me is by using "java.completion.favoriteStaticMembers" in the settings file. Can you please help ?

**Comment by bvedant** [comment]
@fbricon thanks for the update! any chance we could have this feature in _Show Code Actions_ dropdown like it is in IntelliJ, perhaps a toggle to move the feature function to there for those who want it?
