### ISSUE TITLE
Copy Qualified Name of a class or a method results in copying always the following string "io.github.jiangdequan"

### ISSUE THREAD

**Issue by blassmegod** [redhat-developer/vscode-java#799]
Copy Qualified Name of a class or a method results in copying always the following string "io.github.jiangdequan".

##### Environment
- Operating System: Windows
- JDK version: 1.8.202
- Visual Studio Code version:1.31.1
- Java extension version: 0.38.0

##### Steps To Reproduce
1. Open a Java class
2. Select the class name and try to "Copy Qualified Name" from right click menu.

##### Current Result
"io.github.jiangdequan"

##### Expected Result
the correct package, class and/or variable name of the selected item.

**Comment by yaohaizh** [comment]
@blassmegod Our extension doesn't provide this functionality yet. Could you list what other extensions that you have installed? 
Thanks.

**Comment by fbricon** [comment]
This feature is not provided by vscode-java. Looks like you need to report the issue in https://github.com/jiangdequan/vscode-java-saber/issues
