### ISSUE TITLE
unsupported java project

### ISSUE THREAD

**Issue by safderali5** [redhat-developer/vscode-java#80]
when ever i open a java project or file, it gives this message (unsupported java project) in bottom where thumb icon is.
nothing works with it.
![screenshot from 2016-10-27 11 29 34](https://cloud.githubusercontent.com/assets/16339187/19760137/e14846b4-9c38-11e6-8000-6235e9215903.png)

**Comment by edewit** [comment]
@safderali5 at the moment it only works with maven based and basic Eclipse projects

**Comment by gorkem** [comment]
From the screenshot it looks like you are using an ANT build.xml. At the moment, we do not see a good way to provision a project from a build.xml. We have [improvements](https://github.com/redhat-developer/vscode-java/issues/27) planned for files without a recognized build artifact such as pom.xml that may improve this case.
