### ISSUE TITLE
Organize Imports moves focus from code section to import section

### ISSUE THREAD

**Issue by gitorko** [redhat-developer/vscode-java#802]
Version: 1.31.1
Windows & Linux

On earlier versions organize imports didnt change the focus from current selected line to the imports sections. When you are editing code and choose to do an organize import the cursor shifts to the top of the import section instead of staying in the section where you were editing. You have to again scroll back to the place where you were editing code. Is there a flag to avoid the cursor from jumping to the top section when organize import is invoked.

**Comment by testforstephen** [comment]
Cannot reproduce this issue in my environment.
```
Language Support for Java Version: 0.40.0
VS Code Version: 1.32.2
```
@gitorko Can you update VS Code and Java extension to the latest version, and try again?

**Comment by gitorko** [comment]
Issue does not occur in 1.33.1
Thanks.
