### ISSUE TITLE
How to send parameters to 'java.exe'

### ISSUE THREAD

**Issue by Jomme5** [redhat-developer/vscode-java#803]
These parameters should be passed to the interpreter(java.exe) every-time a run a program in vs-code with java-language support:

`-DproxySet=true

-DproxyHost=127.0.0.1

-DproxyPort=8888

-Djavax.net.ssl.trustStore=<path\to\FiddlerKeystore>

-Djavax.net.ssl.trustStorePassword=<Keystore Password>`

How to?

**Comment by snjeza** [comment]
See https://github.com/redhat-developer/vscode-java/wiki/Using-a-Proxy
