### ISSUE TITLE
Unable to generate getter and setter for inner class

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#804]
_created by @pehalo at Mon 2/18/2019 9:12 AM_
Original issue https://github.com/Microsoft/vscode-java-pack/issues/96

**Comment by testforstephen** [comment]
This is a vscode regression issue https://github.com/Microsoft/vscode/issues/68487

**Comment by fbricon** [comment]
VS Code fixed that issue weeks ago.
