### ISSUE TITLE
  I really like VSCode and thinks for redhat-developer, the biggest regret is the support for JSP.

### ISSUE THREAD

**Issue by superadmini** [redhat-developer/vscode-java#808]
I checked the previous Related Issues about JSP support. That was recorded in December 2017. More than a year has passed since today. I think there should be a lot of developers who have this regret like me: that is the support for JSP.
Anyway, thank you very much for your work. I am willing to wait for the day of redhat's perfect support for JSP

**Comment by fbricon** [comment]
Closing as duplicate of #138
