### ISSUE TITLE
Adding the package name (at least) in a new Java file

### ISSUE THREAD

**Issue by ppatierno** [redhat-developer/vscode-java#809]
When I create a new Java file (i.e. MyClass.java) under a specific (folder) in the project I expect that the file will have (at least) the package line at the beginning.
It could be great having the skeleton for a class or interface but it needs a way for the user to chose which one he wants.

##### Environment
- Operating System: Fedora 29
- JDK version: 1.8.0
- Visual Studio Code version: 1.31.1
- Java extension version: 0.39.0

##### Steps To Reproduce
1. Create a new .java file under a folder in the project

##### Current Result

Empty Java file

##### Expected Result

Java file containing (at least) the package declaration based on the folder where it's created.

**Comment by fbricon** [comment]
Just type class, select the snippet and it'll add a minimal class skeleton with package and class name

**Comment by fbricon** [comment]
Same thing with interface

**Comment by ppatierno** [comment]
Thanks, I didn't find any information about that.
