### ISSUE TITLE
JavaFX sample not working, class not found

### ISSUE THREAD

**Issue by criscola** [redhat-developer/vscode-java#810]
So I was reading here https://github.com/Microsoft/vscode-java-debug/issues/507 and found that https://github.com/openjfx/samples/tree/master/CommandLine/Modular/Maven/hellofx. 
Now it says: 
```
Error: Could not find or load main class org.openjfx.MainApp
Caused by: java.lang.ClassNotFoundException: org.openjfx.MainApp
```
Why? Is there some other step I'm unaware of? How can I use JavaFX along this extension? Thanks!

##### Environment
- Operating System: Ubuntu 18.04 
- JDK version: openjdk 11.0.2
- Visual Studio Code version: 1.31.1
- Java extension version: 0.39.0

**Comment by fbricon** [comment]
Works for me. How are you trying to launch your app?

![](https://user-images.githubusercontent.com/148698/53377785-319c0500-3931-11e9-9124-1ef17684e076.gif).

Most likely, the problem is not related to vscode-java itself and it's either a Maven CLI or vscode-java-debug issue.

**Comment by criscola** [comment]
I tried re-running that and it shows `Error: JavaFX runtime components are missing, and are required to run this application`. I try to run it by clicking on "Run" like you do.
