### ISSUE TITLE
Completing /** no longer generates Javadoc with params 

### ISSUE THREAD

**Issue by mwschultz** [redhat-developer/vscode-java#811]
Previously, when entering `/**`+`Enter`, Javadoc was generated with parameters. Now, this is no longer occurring (see #228 -- this was addressed, but is no longer working). 

##### Environment
- Operating System: Ubuntu 18.04.1
- JDK version: 10.0.2
- Visual Studio Code version: 1.31.1
- Java extension version: 0.39.0

##### Steps To Reproduce
1. When a Java file is open, and the user enters  `/**`+`Enter` above a method, the params in the method are not generated for the Javadoc. See example below: 

##### Current Result
![examplevscode1](https://user-images.githubusercontent.com/8883161/53315483-6bb5ca00-3891-11e9-972b-250e62f6cf01.gif)

Thanks -- please let me know if anything is needed.

**Comment by fbricon** [comment]
please attach the [server logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-java-language-servers-workspace-logs) and the [vscode logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server) from the Output view

**Comment by ppatierno** [comment]
@fbricon I have the same problem with same version.
Attached my logs.

[server.log](https://github.com/redhat-developer/vscode-java/files/2909892/server.log)
[developer_tools.log](https://github.com/redhat-developer/vscode-java/files/2909893/developer_tools.log)

**Comment by fbricon** [comment]
please add the logs from the [output view](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server) after enabling `"java.trace.server":"verbose"`

You can try the "Java: Clean the Java language server workspace" command.
If it still happens, try uninstalling all other java extensions and try again.

@yaohaizh [developer_tools.log](https://github.com/redhat-developer/vscode-java/files/2909893/developer_tools.log) shows problems with vscjava.vscode-java-dependency

**Comment by mwschultz** [comment]
@fbricon 

Thank you for the prompt reply, apologize for the delay in getting back to you. I set  "java.trace.server": "verbose" in my settings.json file and I have attached the logs here. 

[java language server.log](https://github.com/redhat-developer/vscode-java/files/2918010/java.language.server.log)
[vscode-java.log](https://github.com/redhat-developer/vscode-java/files/2918011/vscode-java.log)

One note -- This is now for Java extension version: 0.40.0. 

Please let me know if there is anything else needed. Thanks!

**Comment by fbricon** [comment]
you might want to disable the vscode-java-saber extension, in case it causes a conflict.
Please attach the content of the output view for `Language Support for Java`

**Comment by mwschultz** [comment]
Thanks -- I have disabled the vscode-java-saber extension. Attached are the results of the output view for Language Support for Java. 


[output view Language Support for Java.log](https://github.com/redhat-developer/vscode-java/files/2918156/output.view.Language.Support.for.Java.log)

**Comment by mwschultz** [comment]
Hi, 

Just checking in on this issue -- is there anything else you might need from me that could help? 

Thanks!

**Comment by bobjiang1988** [comment]
The same issue on the version of 0.40.0

**Comment by henriquesqs** [comment]
> The same issue on the version of 0.40.0

Unfortunately Im having the same issue on this version. Is there something that we could do to help solving this?

**Comment by fbricon** [comment]
I found this is caused by the Intellicode extension. I reported the issue there: https://github.com/MicrosoftDocs/intellicode/issues/72

**Comment by fbricon** [comment]
In the meantime, you can try to uninstall or disable the Intellicode extension and Javadoc completion should be restored

**Comment by Eskibear** [comment]
It's confirmed to be a bug of IntelliCode Java module, and here is a private build with the fix:
[vscodeintellicode-1.1.5-fix-javadoc-completion.vsix.zip](https://github.com/redhat-developer/vscode-java/files/2969341/vscodeintellicode-1.1.5-fix-javadoc-completion.vsix.zip)
Can you give it a try, and let me know if it works for you? @mwschultz @henriquesqs @fbricon 

Unzip it, and install the .vsix file via:
![image](https://user-images.githubusercontent.com/2351748/54407006-5822b400-4717-11e9-88b4-8227386a317c.png)

**Comment by henriquesqs** [comment]
> It's confirmed to be a bug of IntelliCode Java module, and here is a private build with the fix:
> [vscodeintellicode-1.1.5-fix-javadoc-completion.vsix.zip](https://github.com/redhat-developer/vscode-java/files/2969341/vscodeintellicode-1.1.5-fix-javadoc-completion.vsix.zip)
> Can you give it a try, and let me know if it works for you? @mwschultz @henriquesqs @fbricon
> 
> Unzip it, and install the .vsix file via:
> ![image](https://user-images.githubusercontent.com/2351748/54407006-5822b400-4717-11e9-88b4-8227386a317c.png)

Unfortunately I'm not able to test it right now. I will check it asap. Thank you!

**Comment by fbricon** [comment]
@Eskibear your extension works

**Comment by henriquesqs** [comment]
@Eskibear still not working for me. How do I proceed?

**Comment by bobjiang1988** [comment]
@Eskibear 
Works for me. Thank you!

**Comment by Eskibear** [comment]
@henriquesqs You may try to totally remove Java extension and IntelliCode extension, then re-install them. If the issue still exists, look for clues in both output channels "VS IntelliCode" and "Language support for Java" .

**Comment by henriquesqs** [comment]
Hello @Eskibear, I tried to completely remove Java extension but it still not working for me. I'll attach my output for you to see. If there is something else that I should do I'll be glad to help.

[VSIntellicode.txt](https://github.com/redhat-developer/vscode-java/files/2977673/VSIntellicode.txt)
[LanguageSupportForJava.txt](https://github.com/redhat-developer/vscode-java/files/2977674/LanguageSupportForJava.txt)

**Comment by henriquesqs** [comment]
@Eskibear for some reason now I (think that I) can use javadoc. But I can't figure out why it just works with this function and this file. Am I doing something wrong? :p

![image](https://user-images.githubusercontent.com/36971021/54526647-23e90680-4956-11e9-8d01-91175467b5a0.png)

**Comment by Eskibear** [comment]
@henriquesqs  Actually the completion item provider in intellicode follows exact the [same logic](https://github.com/eclipse/eclipse.jdt.ls/blob/2986d90d46e1589b607defe96081b6cb3ee0c585/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionHandler.java#L116-L117) as in eclipse.jdt.ls . From the log, I can only tell that for some reason the exception occurs in `SnippetCompletionProposal.getSnippets`, so the next line is not executed, thus no javadoc completion items added.  So I guess your exception should also occur without intellicode enabled? And if you can stably reproduce it, please also attach a piece of code for us to diagnose maybe. 

@yaohaizh Could you take a look at the log, see if there's any potential issue in jdt.ls completion handler?

**Comment by henriquesqs** [comment]
@Eskibear I tried disabling the Intellicode extension and now there's nothing to see in output. Both "VSIntellicode" and "Language Support for Java" channels now disappeared. Also, the Javadoc is still working in the same way as I mentioned [here](https://github.com/redhat-developer/vscode-java/issues/811#issuecomment-473869610).

I tried reenabling the extension to generate a new output on those channels and I attached the new generated logs:

[LanguageSupport.txt](https://github.com/redhat-developer/vscode-java/files/2983039/LanguageSupport.txt)
[VSIntellicode.txt](https://github.com/redhat-developer/vscode-java/files/2983040/VSIntellicode.txt)

Here's the code I'm using to check it (some text is in portuguese but nothing to worry about):

```java

public static void main(String[] args){
                
        Scanner leituraString = new Scanner(System.in);
        
        System.out.printf("\nDigite uma frase: "); // enter a string
        String Frase = leituraString.nextLine();
        
        Vowels vogais = new Vowels(Frase.length(), Frase);

        vogais.vowelsQuantity(); // função que faz a contagem das vogais na frase
        
        System.out.println("\nFrase em letras maiúsculas: " + Frase.toUpperCase()); // string in uppercase
        
        System.out.printf("\nDigite uma segunda frase: "); // enter a second string
        String Frase2 = leituraString.nextLine();

        if(Frase.endsWith(Frase2))
            System.out.println("\nA primeira frase termina com a segunda"); 
        
        else if(Frase.startsWith(Frase2))
            System.out.println("\nA primeira frase começa com a segunda");
        
        else 
            System.out.println("\nA primeira frase nem começa, nem termina com a segunda");

        leituraString.close();
    }

```

**Comment by Eskibear** [comment]
Hey guys, the fix has been released with the Intellicode extension v1.1.5 for a week. Please update and see if the issue is gone.

**Comment by yaohaizh** [comment]
Close this as it has been fixed. Please reopen it if still existing.

**Comment by playeriv65** [comment]
I'm using the latest version of red hat java extension, and the same problem occurred.
`
package Project_2;

public class BiggestCardAI extends AI {
    /**
     * Constructor for BiggestCardAI
     */
    public BiggestCardAI() {
        super.nameString = "Biggest Card AI";
    }

    public Card getPlay(Hand hand, CardPile cardPile) {
        Card PlayCard = null;
        int maxRank = 0; // lower than the lowest possible rank
        for (int i = 0; i < hand.getSize(); i++) {
            Card tempPlayCard = hand.get(i);
            if (!cardPile.canPlay(tempPlayCard) || tempPlayCard.getRankNum() < maxRank)
                continue;

            maxRank = tempPlayCard.getRankNum(); // update the max rank
            PlayCard = tempPlayCard;
        }

        return PlayCard;
    }
}
`
I tried to type /** before the getPlay function, nothing happend. But if I change the function name into "getplay", the java doc comment suddenly worked, very weird.
