### ISSUE TITLE
Error: The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by adriantomas** [redhat-developer/vscode-java#815]
Receiving the following error when opening a Spring Boot Maven project folder:

The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

##### Environment
- Operating System: Windows 10 Pro
- JDK version: Oracle 1.8.0_201
- Visual Studio Code version: 1.31.1
- Java extension version: 0.39.0

##### Steps To Reproduce
1. Install the **Language Support for Java(TM) by Red Hat** extension after a fresh VS Code installation.
2. Open a file of the Spring Boot Maven app or generate a new one through Spring Initializer.
3. Wait for the error to come.

[Java Language Server log.txt](https://github.com/redhat-developer/vscode-java/files/2911952/Java.Language.Server.log.txt)
[Language Support Java Output.txt](https://github.com/redhat-developer/vscode-java/files/2911955/Language.Support.Java.Output.txt)

##### Additional Informations
I have the Windows system AV. Also followed the steps [here](https://github.com/redhat-developer/vscode-java/issues/743) and in many other related issues. I've cleaned the language server workspace.

**Comment by fbricon** [comment]
try to disable every extension but vscode-java, clean the workspace and see what happens

**Comment by adriantomas** [comment]
@fbricon Hi and thank you for answering. I've done both things with the same result.

My settings.json in case needed.

`{
    "java.home": "D:\\Program Files\\Java\\jdk1.8.0_201",
    "java.configuration.checkProjectSettingsExclusions": false,
    "java.trace.server": "verbose",
    "java.jdt.ls.vmargs": "-Dlog.level=ALL"
}`

**Comment by fbricon** [comment]
please resend your Language Support Java Output, when all extensions are disabled

**Comment by adriantomas** [comment]
[Language Support Java Output (other extensions disabled).txt](https://github.com/redhat-developer/vscode-java/files/2912236/Language.Support.Java.Output.other.extensions.disabled.txt)

**Comment by fbricon** [comment]
the STS extensions are still active apparently

**Comment by adriantomas** [comment]
That's strange... 

![image](https://user-images.githubusercontent.com/22175056/53523087-26390d00-3adc-11e9-86a2-c97a76cdf5c5.png)

**Comment by adriantomas** [comment]
I uninstalled the other extensions and removed its folders from `%UserProfile%\.vscode\extensions`

[Language Support Java Output (no extensions).txt](https://github.com/redhat-developer/vscode-java/files/2912418/Language.Support.Java.Output.no.extensions.txt)

**Comment by fbricon** [comment]
@snjeza any idea?

**Comment by snjeza** [comment]
@adriantomas could try the following:

- stop VS Code
- remove the %UserProfile%\.vscode\extensions\redhat.java-*\server\config_win\org.eclipse.* directories
- start VS Code

or remove and reinstall the RedHat Java LS extension.

**Comment by adriantomas** [comment]
Done above steps. This is the output of removing those directories:
[Language Support Java Output (removing eclipse directories).txt](https://github.com/redhat-developer/vscode-java/files/2913971/Language.Support.Java.Output.removing.eclipse.directories.txt)

Also reinstalled VSCode removing related directories at `%AppData%`, `%LocalAppData%` and `%UserProfile%`. Then installed vscode-java as the only extension.
[Language Support Java Output (reinstall).txt](https://github.com/redhat-developer/vscode-java/files/2913996/Language.Support.Java.Output.reinstall.txt)

**Comment by yaohaizh** [comment]
@adriantomas Do you have install any vscode-lombok extension? Or do you make any changes to your user settings: "java.jdt.ls.vmargs"?

**Comment by snjeza** [comment]
@adriantomas could you send the output of the following command:

```
tasklist /FI "IMAGENAME eq code.exe"
```

**Comment by adriantomas** [comment]
[Tasklist otuput.txt](https://github.com/redhat-developer/vscode-java/files/2923029/Tasklist.otuput.txt)

**Comment by mattesko** [comment]
Have you tried deleting the contents under `%UserProfile%/AppData/Roaming/Code`, and `%UserProfile%/.vscode`, before performing a fresh install of VSCode?

I had the same issue under similar circumstances. I deleted all my settings and extensions, reinstalled VSCode and it fixed the issue.
__Environment:__
* Windows 10 Home
* JDK version: Oracle 1.8.0_201
* Visual Studio Code version: 1.31.1
* Java extension version: 0.40.0

**Comment by snjeza** [comment]
@adriantomas could you try the following:

```
cd E:\Users\DrMonkey\Desktop\TFG\contrast
tasklist /FI "IMAGENAME eq code.exe"
echo %errorlevel%
```

You can also check the following VS Code Java - https://drive.google.com/open?id=1m91etQ-3JugTjBYQbptWGsw3Nq89-GvI. It includes https://github.com/eclipse/eclipse.jdt.ls/pull/946

**Comment by adriantomas** [comment]
This is the output of the commands. Sorry for misunderstanding them at first.

[Tasklist output in E drive.txt](https://github.com/redhat-developer/vscode-java/files/2923815/Tasklist.output.in.E.drive.txt)

Then I installed the 0.41.0 version of vscode-java and cleant the java language server workspace. This is the output of the Language Support for Java extension and the output of the above commands with this version.

[Language Support Java Output (0.41.0).txt](https://github.com/redhat-developer/vscode-java/files/2923830/Language.Support.Java.Output.0.41.0.txt)
[Tasklist output (0.41.0).txt](https://github.com/redhat-developer/vscode-java/files/2923833/Tasklist.output.0.41.0.txt)

**Comment by snjeza** [comment]
@adriantomas Could you, please, try the following version - https://drive.google.com/open?id=1yIYJyeDbvshorQgH7OVYt5_-m8CDR5PQ ?

**Comment by adriantomas** [comment]
Just for cleaning things up I performed a fresh vscode installation again, deleting `%UserProfile%` related folders. Then installed the version 0.41.1 and opened the project. I performed some actions but noticed they were being captured in the output, so I stopped typing just for not messing things up. This is the Language Support for Java Output and the cmd commands typed above (though it seems you included them in the Java Output).

**The Language Support for Java server is actually working and has not crashed a single time**

[Language Support Java Output (0.41.1).txt](https://github.com/redhat-developer/vscode-java/files/2926112/Language.Support.Java.Output.0.41.1.txt)
[Tasklist output (0.41.1).txt](https://github.com/redhat-developer/vscode-java/files/2926113/Tasklist.output.0.41.1.txt)

I would like to know how this ended up working. Thank you a lot @snjeza @fbricon

**Comment by snjeza** [comment]
> though it seems you included them in the Java Output

I have tried to test your the tasklist and findstr command. You can ignore it or try the following build - https://drive.google.com/open?id=1mnSeXB5JBVNhWbC9Osmx_lzzk6DEQBpe .

> The Language Support for Java server is actually working and has not crashed a single time

It seems that you have a corrupted tasklist or findstr command.

> I would like to know how this ended up working

https://github.com/eclipse/eclipse.jdt.ls/pull/946 fixes the issue. The 0.41.1 and 0.41.2 versions includes it.
It is also possible that you have removed a corrupted tasklist or findstr. You can check it with standard Java LS 0.40.0.

**Comment by adriantomas** [comment]
So I installed the 0.41.2 version and it worked. Then rolled back to the standard 0.40.0 and it's working! I'm confused but happy is finally running.

**Comment by snjeza** [comment]
> Just for cleaning things up I performed a fresh vscode installation again, deleting %UserProfile% related folders.
...
> So I installed the 0.41.2 version and it worked. Then rolled back to the standard 0.40.0 and it's working! I'm confused but happy is finally running.

I suppose that you had a corrupted tasklist or findstr command and removed it.

**Comment by adriantomas** [comment]
> I suppose that you had a corrupted tasklist or findstr command and removed it.

A couple things to notice that maybe caused the error and what I did. These are some possible workarounds for users that have the same problem I had:

- I noticed that at first I couldn't use `tasklist` command in other drives rather than C. This was due to cmd not being in PATH environment variable. By the way my vscode and vscode-java installation were in D and my project files in E.

- When I used `sfc /scannow` in cmd, something was broken and it fixed it.

I don't know if this means something to you @snjeza

**Comment by snjeza** [comment]
@adriantomas Thanks, that is helpful.
@fbricon we could update the wiki.

**Comment by di3663** [comment]
> @adriantomas could try the following:
> 
> * stop VS Code
> * remove the %UserProfile%.vscode\extensions\redhat.java-_\server\config_win\org.eclipse._ directories
> * start VS Code
> 
> or remove and reinstall the RedHat Java LS extension.

Not work, maybe new vscode cause this.

**Comment by snjeza** [comment]
@di3663 please send your Language Support Java Output,

**Comment by pehalo** [comment]
I also have this problem. ![image](https://user-images.githubusercontent.com/15843581/54171687-3aa2df80-44b6-11e9-8201-ed8d93e0c36c.png)
But I don't know how to collect specific crash information. How do you collect crash information, such as logs?
This situation is occasional and difficult to reproduce.

**Comment by yaohaizh** [comment]
@pehalo Does this issue still happen?

**Comment by pehalo** [comment]
It just happened, but the automatic restart was successful. My computer's memory is full during the reboot process.

**Comment by yaohaizh** [comment]
@pehalo  Could you help invoke the "Java: Clean workspace" to see whether the issue persist

**Comment by pehalo** [comment]
@yaohaizh After running the "Java: Clean workspace" command, I found some other problems. 
![YR~S3V6KG{N(~NMJUPH{11U](https://user-images.githubusercontent.com/15843581/54184630-12c97100-44e2-11e9-8275-ed8f73ea2504.png)
Trigger full gc every 5 seconds

**Comment by fbricon** [comment]
A GC is performed every 10sec, to prevent a file handle leak on Windows
