### ISSUE TITLE
References Code Lens: do not show "0 referenses"

### ISSUE THREAD

**Issue by jnesspro** [redhat-developer/vscode-java#816]
do not show code lens if there are no references
![image](https://user-images.githubusercontent.com/5245360/53562030-5d9dcd00-3b61-11e9-925f-19e30aeb40b2.png)

**Comment by fbricon** [comment]
It's actually complicated. The Codelens mechanism has 2 phases:
- 1 compute code lens locations for the document
- lazyly resolve code lenses when region is visible

After step 1, VS Code inserts an extra line, waiting for the codelens values to be returned in step 2, and if nothing is returned, then you end up with a weird looking gap on top of each method/class. So instead we have to show something. It's annoying but it's the least bad looking option

**Comment by jnesspro** [comment]
ok, shift f12 still our choice. Thanks
