### ISSUE TITLE
Ability to disable import completions in Java 

### ISSUE THREAD

**Issue by goxr3plus** [redhat-developer/vscode-java#818]
I want auto completions for Java to show only Java methods and not import completions .... it's very messy : 

Messy **autocompletion** 

![untitled](https://user-images.githubusercontent.com/20374208/53572817-cb9fbf80-3b74-11e9-938b-89596cb9a82d.png)

**Comment by fbricon** [comment]
This is the completion from https://marketplace.visualstudio.com/items?itemName=tushortz.java-imports-snippets, completely unrelated to vscode-java. You shouldn't need it.

**Comment by yaohaizh** [comment]
@goxr3plus These are code snippets which the vscode java extension doesn't provide. 

Could you check your extension see what other extensions installed for Java?

**Comment by goxr3plus** [comment]
@fbricon  I will try today , thank you so much :)
