### ISSUE TITLE
"trigger parameter hints" (shift+cmd+space) action doesn't work

### ISSUE THREAD

**Issue by jnesspro** [redhat-developer/vscode-java#819]
1) System.out.println(<cursor is here>);
2) shift+cmd+space
3) no parameter hints appeared
same for a constructor parameters.
I tried on 2 mac os machines, on stable and on insiders versions. Other languages support this feature (tried with golang, typeScript)

![image](https://user-images.githubusercontent.com/5245360/53645985-29064000-3c4b-11e9-95a1-e05585dcfe44.png)

![image](https://user-images.githubusercontent.com/5245360/53646040-49ce9580-3c4b-11e9-9c19-794aec862e1c.png)

Mac OS
VSCode 1.32.0-insider, 1.31
extension version: 0.40

**Comment by fbricon** [comment]
Add `"java.signatureHelp.enabled": true` to your settings.json

**Comment by jnesspro** [comment]
Oh. I'm sorry. Hope, I not only one and this issue will help someone.

**Comment by Delice0** [comment]
> Add `"java.signatureHelp.enabled": true` to your settings.json

This worked for me! Thanks.
