### ISSUE TITLE
Refactor package name

### ISSUE THREAD

**Issue by AmitaiMazliah** [redhat-developer/vscode-java#823]
Is there a way to refactor the package name which will trigger a change in all the classes inside that package?
Couldn't find a way...

**Comment by fbricon** [comment]
not yet. IIRC, the Language server protocol is still lacking ways to distinguish files from folders when you issue a move command. @yaohaizh should know better.

**Comment by yaohaizh** [comment]
@fbricon @AmitaiMazliah This is blocked by VSCode side issue: https://github.com/Microsoft/vscode/issues/62663 The VSCode doesn't provide an official way to create a folder. Thus, this feature is partly blocked.

**Comment by stodge** [comment]
Any updates on this? Similarly, will this fix moving packages where source files that import the package aren't updated? It's hard to push for adoption without these features. Thanks.

**Comment by fbricon** [comment]
Renaming a folder in the explorer view now triggers package refactoring. The 1st time, you'll be prompted to always apply the changes or always preview them:

<img width="952" alt="Screen Shot 2020-05-13 at 11 33 52 AM" src="https://user-images.githubusercontent.com/148698/81796518-d4787900-950d-11ea-82e5-8af82a39fe94.png">

The behavior is controlled by a new preference:
 
* `java.refactor.renameFromFileExplorer`: Specifies whether to update imports and package declarations when renaming files from File Explorer. Defaults to `prompt`.
  - `never`: Don't enable refactoring for rename operations on File Explorer.
  - `autoApply`: Always automatically update the imports and package declarations.
  - `preview`: Always preview the changes before applying.
  - `prompt`: Ask user to confirm whether to bypass refactor preview.
