### ISSUE TITLE
missing highlight on some non-ASCII identifiers

### ISSUE THREAD

**Issue by yaohaizh** [redhat-developer/vscode-java#826]
_From @nobodxbodon on March 5, 2019 18:43_

Hi,

the differencies are in Line 4 between the English and Chinese versions as below:
![screen shot 2019-03-05 at 10 34 48 am](https://user-images.githubusercontent.com/392497/53828430-81329000-3f32-11e9-99bd-ce08f083fe9f.png)
`Calculator` class:
```java
class Calculator {

  public static void main(String[] args) {
    Calculator calculator = new Calculator();
  }
}
```
Identifers in Chinese:
```java
class 计算器类 {

  public static void main(String[] args) {
    计算器类 计算器 = new 计算器类();
  }
}
```
I'm using vscode 1.31.1 with Java Extension Pack 0.6.0 under Mac.

Thanks.

_Copied from original issue: Microsoft/vscode-java-pack#109_

**Comment by yaohaizh** [comment]
_From @nobodxbodon on March 5, 2019 18:57_

One additional test shows the method argument shows different too:
![screen shot 2019-03-05 at 10 55 41 am](https://user-images.githubusercontent.com/392497/53829612-63b2f580-3f35-11e9-84a8-2071651f99df.png)
```java
  public void test1(Calculator calculator) {
    calculator.test1(this);
  }
```
Chinese version:
```java
  public void 测试1(计算器类 计算器) {
    计算器.测试1(this);
  }
```

**Comment by fbricon** [comment]
This is an issue with the textmate based grammar from upstream [VS Code](https://github.com/Microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json), itself forked from [Atom's](https://github.com/atom/language-java/blob/master/grammars/java.cson).

**Comment by nobodxbodon** [comment]
@fbricon thanks for the diagnose. May I ask if you refer to the `[A-Za-z$_]` part in section like [this](https://github.com/Microsoft/vscode/blob/1adb3256ea092a0d47d1d02439f3fa0678025039/extensions/java/syntaxes/java.tmLanguage.json#L1609)? Would you suggest to move this issue to VS Code or Atom?

**Comment by fbricon** [comment]
This is partially fixed with the new semantic highlighting support in vscode-java 0.61.0. Requires `"java.semanticHighlighting.enabled": true` in settings.json
