### ISSUE TITLE
The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by JoeyRxy** [redhat-developer/vscode-java#828]
[provide a description of the issue]
when you open the vscode and java,everything is OK!
You can write,the auto-complementionstill work,the debugger work very well.Evrything looks fine
BUT,after some minutes and doing NOTHING,the java server crushed suddenly!Why?What happened to the extension?
You wait and do NOTHING,and the extension goes wrong.
Unbelieveable!
##### Environment
- Operating System:Win10
- JDK version:jdk-11
- Visual Studio Code version:Latest(include stable version and insider)
- Java extension version:0.40.0

##### Steps To Reproduce
1. Open a single Java file.Brand new folder,Brand new java file,Brand new workspace.With no `.vscode` folder.
2. Run it with **Run|Debug**.Work this time.(error maybe occur without this step,I just donnot know)
3. Wait for some minutes.
4. It just crushed and the **Run|Debug** symbol above the `main` method disappears.Show the error message:

> The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

and I find using prompt `javac` and `java` simply works!

[attach a sample project reproducing the error]
just "hello world" program.
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

> [Warn  - 3:02:32 PM] Mar 6, 2019, 3:02:32 PM The workspace will exit with unsaved changes in this session.
> [Info  - 3:02:32 PM] Connection to server got closed. Server will restart.
> [Warn  - 3:04:26 PM] Mar 6, 2019, 3:04:26 PM The workspace will exit with unsaved changes in this session.
> [Info  - 3:04:27 PM] Connection to server got closed. Server will restart.
> [Warn  - 3:05:11 PM] Mar 6, 2019, 3:05:11 PM The workspace will exit with unsaved changes in this session.
> [Info  - 3:05:11 PM] Connection to server got closed. Server will restart.
> [Warn  - 3:05:55 PM] Mar 6, 2019, 3:05:55 PM The workspace will exit with unsaved changes in this session.
> [Info  - 3:05:56 PM] Connection to server got closed. Server will restart.
> [Warn  - 3:06:39 PM] Mar 6, 2019, 3:06:39 PM The workspace will exit with unsaved changes in this session.
> [Info  - 3:06:40 PM] Connection to server got closed. Server will restart.
> [Warn  - 3:07:24 PM] Mar 6, 2019, 3:07:24 PM The workspace will exit with unsaved changes in this session.
> [Error - 3:07:24 PM] Connection to server got closed. Server will not be restarted.

##### Current Result
crash after some minutes.
##### Expected Result
JUST FIX IT

**Comment by JoeyRxy** [comment]
There's no problem using vscode on linux with the same configuration.
So weird

**Comment by fbricon** [comment]
Download the most recent `java-<version>.vsix` file from [http://download.jboss.org/jbosstools/jdt.ls/staging/](http://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D) and install it by following the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

**Comment by snjeza** [comment]
@JoeyRxy you can also try the following:

```
sfc /scannow
```
See https://github.com/redhat-developer/vscode-java/issues/815#issuecomment-469826697

**Comment by JoeyRxy** [comment]
Thanks,everybody!
Finally,I reset my PC,and reinstall everything,now there's no problem.

**Comment by 2020-abhilash** [comment]
This is still an issue with the latest version of vscode, extensions and everything. Not sure how to resolve this. I have tried all the solutions mentioned above.

**Comment by saumilsdk** [comment]
hey @2020-abhilash you might have installed lombok plugin. if so remove it and it's settings from user settings of VS code.
