### ISSUE TITLE
Duplicate entry in code-completion within Java file

### ISSUE THREAD

**Issue by masbaehr** [redhat-developer/vscode-java#829]
For some reason code completion suggestions are duplicate. I don't know how to "debug" this exactly or to find out what the cause of this might be. I'm using Gradle to Build

![image](https://user-images.githubusercontent.com/38694044/53950041-9a227900-40cb-11e9-998e-7082c0e7032f.png)

##### Environment
- Operating System: Windows
- JDK version: latest
- Visual Studio Code version: latest insider
- Java extension version: latest

**Comment by fbricon** [comment]
Can you please share your project (we don't need the source files, just the config)?
Please enable `"java.trace.server":"verbose"` in your settings.json and attach the [Java Language server output](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server)

**Comment by masbaehr** [comment]
Using Version 1.33.0-insider and latest version of the plugins the problem seems to be fixed :D
