### ISSUE TITLE
Add some Java code snippets

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#83]
We can add a bunch of java code snippet, to make vs code more productive:
- syserr -> System.err.println()
- sysout -> System.out.println()
- if, if/else, if not null, if null
- try catch block
- static main method
- enhanced for loop
- private/protected/public methods

and probably also a bunch of others

**Comment by gorkem** [comment]
Can we actually have a converter script from [eclipse JDT](http://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.ui/templates/default-templates.xml) ones to VS Code snippets?
