### ISSUE TITLE
Support syntax highlight for embedded SQL languages

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#831]
When embedding SQL into the Java code, it will be helpful to show the syntax highlight for the SQL.

VS Code provides a guide about how to support embedded languages. https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages

There is a VS Code extension already providing SQL support.
https://github.com/mydesireiscoma/es6-string-html/issues/10
https://marketplace.visualstudio.com/items?itemName=hjb2012.vscode-es6-string-html

**Comment by yaohaizh** [comment]
Add previous closed issue: https://github.com/redhat-developer/vscode-java/issues/525

**Comment by fwgreen** [comment]
With [Text Blocks](https://bugs.openjdk.java.net/browse/JDK-8222530) coming in Java 13, this feature could have real utility.  Maybe support for HTML should be considered as well.
