### ISSUE TITLE
`net` support.

### ISSUE THREAD

**Issue by IdkGoodName** [redhat-developer/vscode-java#833]
I am getting error when using `net` as package prefix.

##### Environment
- Operating System: Windows 10
- JDK version: 1.8.0 162
- Visual Studio Code version: 1.32
- Java extension version: 0.40.0

##### Steps To Reproduce
1. Create some package which starts with `net`, instead of `com`
2. Import it.

##### Current Result

Getting error `The import net cannot be resolved`.

##### Expected Result

It should import `net` and make it work same as `com`.

**Comment by fbricon** [comment]
please provide a sample project
