### ISSUE TITLE
VS Code settings does not point to a JDK.

### ISSUE THREAD

**Issue by yossefEl** [redhat-developer/vscode-java#835]
## Thank you in advance 😄 😃 

I set up VScode as described on Extension instruction(JAVA_HOME, JDK version ..) but i still getting this error.
##### Environment
- Operating System: Windows 10
- JDK version: jdk1.8.0_171
- Visual Studio Code version: 1.32.1
- Java extension version: 0.40.0

#### Error
![error1](https://user-images.githubusercontent.com/39236784/54279308-0a7e3e00-4595-11e9-9626-e8a4e352a08f.png)

#### the VSCode settings
![Capture](https://user-images.githubusercontent.com/39236784/54279307-0a7e3e00-4595-11e9-92b9-f03a8f2c359f.PNG)

#### JDK envirenment varibale
![jdk](https://user-images.githubusercontent.com/39236784/54279310-0a7e3e00-4595-11e9-8ef0-b924c08fe529.PNG)

**Comment by Eskibear** [comment]
Dude, remove the "bin" part please. Your java home should be  "C:\\Program Files\\Java\\jdk1.8.0_171" .

**Comment by muha365** [comment]
You can open command line elevated as administrator and execute the next line 
SET JAVA_HOME="C:\Program Files\Java\jdk1.8.0_171"

**Comment by fbricon** [comment]
This mistake is now better captured and surfaced to the user:
<img width="458" alt="Screen Shot 2019-03-14 at 4 48 47 PM" src="https://user-images.githubusercontent.com/148698/54390554-23f8b600-4679-11e9-888e-a3be2a683018.png">

The "Open Settings" action will be available only if the java.home is already being set.
