### ISSUE TITLE
"Java runtime could not be located" for Windows + Oracle JDK

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#836]
For Windows, if JDK installer is downloaded here from Oracle, the java executable is special, JAVA_HOME is not set either. I don't understand why Oracle did such a tricky thing. 

Setting `java.home` to "C:\Program Files\Java\jdk1.8.0_201" do help me out. But the user experience is terribly bad, especially for new Java developers. Can we find a way to optimize for Windows+OracleJDK users? (i.e. recognize Java home automatically for them)

![image](https://user-images.githubusercontent.com/2351748/54280278-0de3ea80-45d2-11e9-805c-07be7985f3c1.png)

```batch
C:\Users\username>where java
C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe

C:\Users\username>java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
##### Environment
- Operating System: Windows 10 
- JDK version: Oracle JDK 8u201
- Visual Studio Code version: 1.32.1
- Java extension version: 0.40.0

**Comment by fbricon** [comment]
Isn't javapath pointing at a JRE? We need a JDK

**Comment by Eskibear** [comment]
Yes, you are right. Just tried printing the `java.home` and it's "C:\Program Files\Java\jdk1.8.0_201\jre
". I never knew that before.  

Yet I have to say the experience is not friendly enough to new comers. When I saw the message "Java runtime could not be located", I was thinking "fool me? I do have a java runtime and I can execute java program in CLI".  I'm wondering whether there is any possibility to infer the JDK home? Or maybe at least the error message should be more concrete, e.g. something like "JDK is required but can be located." Just my two cents.

**Comment by fbricon** [comment]
Updated message:
<img width="459" alt="Screen Shot 2019-03-14 at 4 54 22 PM" src="https://user-images.githubusercontent.com/148698/54390926-f52f0f80-4679-11e9-911e-b253a3b596fc.png">

**Comment by Eskibear** [comment]
I was always wondering why the library `find-java-home` could not recognize a newly installed Oracle JDK, until I step into the code. With some simple testing, I find several issues:  https://github.com/jsdevel/node-find-java-home/issues/19
