### ISSUE TITLE
junit Testing 

### ISSUE THREAD

**Issue by Zirhi** [redhat-developer/vscode-java#837]
So I am writing a test file for a program. 

The instruction requires me to use: 
**_import static org.junit.Assert.*;
import org.junit.Test;_** 

However, when I get an error: _The import org.junit cannot be resolvedJava(268435846)_

Please what is this issue and how do I go about resolving it.

**Comment by yaohaizh** [comment]
@Zirhi Could you share your sample project here?

**Comment by Zirhi** [comment]
Hi, do you want only the test file? I am not allowed to share the project on public sites as it is a school assignment

**Comment by yaohaizh** [comment]
@Zirhi Do you have add the junit as the project dependency?

**Comment by Zirhi** [comment]
The assignment doesn't specify, but if it helps I think I can do that.

**Comment by yaohaizh** [comment]
https://github.com/redhat-developer/vscode-java/issues/501

**Comment by Zirhi** [comment]
So I tried the procedure from the provide gif in #501 

I created a **_lib_** folder and used the command _user$ cp ../lib/*.jar lib/_

**Returned**
       cp: ../lib/*.jar: No such file or directory

**Comment by Zirhi** [comment]
or is that not what solves my problem

**Comment by Zirhi** [comment]
Issue has been resolved

**Comment by fbricon** [comment]
So what solved it?

**Comment by Zirhi** [comment]
I downloaded these two files from junit.org/junit4/ 

https://github.com/junit-team/junit4/wiki/Download-and-Install

Seems to get rid of the resolving error

**Comment by Zirhi** [comment]
So I do not get the _red line_ error on my import statements anymore, but on compiling the program I still get this error: 

TestOne.java:1: error: package org.junit does not exist
import static org.junit.Assert.*;

**Comment by fbricon** [comment]
compiling as in calling javac from a terminal? If that's the case, you need to add the jars to the classpath. 

     javac –classpath C:\path\to\junit.jar;C:\path\to\hamcrest-core.jar TestOne.Java

and, to run the class:

     java –classpath C:\path\to\junit.jar;C:\path\to\hamcrest-core.jar TestOne

if you're on Mac or Linux, the path separator is `:`.

If you google about how to set the Java classpath, you'll find alternative ways of doing it like in https://howtodoinjava.com/java/basics/java-classpath/

Now in vscode-java, all that is not necessary, as compilation happens under the hood, and if you installed the [Java Debugger extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) and/or the [Java Test runner](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test), you'll be able to run your code directly from within VS Code, by clicking on "code lenses".
