### ISSUE TITLE
How to get the Java Abstract Syntax Tree?

### ISSUE THREAD

**Issue by 0160582749** [redhat-developer/vscode-java#840]
I want to build a VSCode Extension using the Java AST nodes' information and was wondering if it is possible to get the Java AST?
I went through the Language Support code and found out it uses the Eclipse servers, so in my understanding it should be possible to get the AST since in Eclipse you can?

##### Environment
- Operating System: Ubuntu 18.04.1 LTS
- JDK version: 11.0.2
- Visual Studio Code version: 1.31.1
- Java extension version: 0.6.0

**Comment by fbricon** [comment]
In theory it should be possible. You could develop a custom [extension](https://github.com/redhat-developer/vscode-java/wiki/Contribute-a-Java-Extension) that'd make the Java language server load some new jars, to expose a new command.

**Comment by 0160582749** [comment]
Cannot find out how the Java langauge server loads new jars and where get/find these jars? I had a look at some extensions that use the Java language server and besides "mentioning" the jars in the package.json under contributes: javaExtensions I don't understand how they are used?

**Comment by yaohaizh** [comment]
https://github.com/Microsoft/vscode-java-test & https://github.com/Microsoft/vscode-java-dependency For your reference.  You need register your own jar. 

Implementations details: 

https://github.com/eclipse/eclipse.jdt.ls/blob/ba7ebe64e4afa8aab6513a87993f7308c4127a0f/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceExecuteCommandHandler.java

https://github.com/eclipse/eclipse.jdt.ls/blob/f8a427e0b6a9a91615f537209be052c31d38280e/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/InitHandler.java#L143
