### ISSUE TITLE
newline stopped working in debug console

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#845]
Somewhere in the last week new line stopped working for me:

##### Environment
- Operating System: OSX 10.12.6
- JDK version: 10.8
- Visual Studio Code version: 1.32.3
- Java extension version: 0.41.0

```java
    public static void main(String[] args) {
        System.out.println("Hello");
        System.out.println();
        System.out.println();
        System.out.println();
        System.out.println("\n");
        System.out.println("There");
    }
```

This is the output:

<img width="430" alt="Screen Shot 2019-03-19 at 17 48 46" src="https://user-images.githubusercontent.com/738650/54625295-4cb0ef00-4a6f-11e9-83ef-16975ff7c5c4.png">

It only happens with the debug console, If I use the internal terminal or the external terminal then the issue is not there.

If I use `println(" ")` with a space then it DOES WORK!!

In python the issue is not there so it is really a java thing.

**Comment by fbricon** [comment]
I confirm this is an issue, but execution of Java code is out of scope of vscode-java. Please open a ticket in https://github.com/Microsoft/vscode-java-debug/issues. cc @Eskibear @testforstephen @yaohaizh

**Comment by testforstephen** [comment]
Windows 10 doesn't have this issue. Opened a bug in vscode. https://github.com/Microsoft/vscode/issues/70789
