### ISSUE TITLE
location of certain icons

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#846]
Not really a issue but I was wondering if someone could help me with this:

Does someone know the location of those icons?
(I don't even know if they are from VSCode or from any of the java extensions).

<img width="43" alt="Screen Shot 2019-03-19 at 18 20 36" src="https://user-images.githubusercontent.com/738650/54627516-e67a9b00-4a73-11e9-8754-89b239295526.png">

**Comment by fbricon** [comment]
They're provided by vscode. vscode-java doesn't contribute any UI assets. See https://github.com/Microsoft/vscode/blob/57edc531924622ca41fc82b993b86e3907dabc49/src/vs/editor/contrib/documentSymbols/media/symbol-icons.css and https://github.com/Microsoft/vscode/tree/57edc531924622ca41fc82b993b86e3907dabc49/src/vs/editor/contrib/documentSymbols/media
