### ISSUE TITLE
Autocompletion on overridden methods should create the method body

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#85]
if an interface declares the method `void foo()`,  then when typing `foo+<ctrl+space>` on an implementor body, an overriding foo() method body should be appended:

```java
@Override // <- depending on the Java target/ maybe preferences
public void foo() {
}
```

**Comment by gorkem** [comment]
reported on https://github.com/gorkem/java-language-server/issues/72

**Comment by fbricon** [comment]
gorkem/java-language-server#72 is fixed
