### ISSUE TITLE
windows system computer must use jdk1.8.201 or newer

### ISSUE THREAD

**Issue by Groupby0925** [redhat-developer/vscode-java#852]
[provide a description of the issue]

##### Environment
- windows 10 64bit:
- JDK 1.8.0_05:
- Visual Studio Code version:1.32.3
- Java extension version: 0.41.0

##### Steps To Reproduce
1. uninstall jdk1.8.05, and install 1.8.201
2. restart  vs code 

##### Current Result
everything is ok.
##### Expected Result
Please note jdk version is 1.8 newest . this is very important

**Comment by yaohaizh** [comment]
@Groupby0925 What's the point here?

**Comment by Groupby0925** [comment]
In Readme.md file,  as Quick Start need change.
old content:
1. Install the Extension
2. If you do not have a Java Development Kit correctly set 
Download and install a Java 8, 9, 10 or 11 compatible development kit.
3. Extension is activated when you first access a Java file 
Recognizes projects with Maven or Gradle build files in the directory hierarchy.

change to  

1. Install the Extension
2. If you do not have a Java Development Kit correctly set 
Download and install a Java 8 , 9, 10 or 11 compatible development kit.
( Java 8 newest , jdk 1.8.0_05 nocompatible)

3. Extension is activated when you first access a Java file 
Recognizes projects with Maven or Gradle build files in the directory hierarchy.
