### ISSUE TITLE
cannot resolve the 'var' keyword in maven project

### ISSUE THREAD

**Issue by shaka0919** [redhat-developer/vscode-java#854]
I can use var in java project
but when i created a maven project from archetype quickstart
var cannot be resolved to a typeJava(16777218)
is there something wrong with my env or configuration?

**Comment by fbricon** [comment]
You need to tell Maven to compile against Java 11. Typically, add this to your pom.xml:

```xml
<plugin>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.8.0</version>
	<configuration>
		<release>11</release>
	</configuration>
</plugin>
```

**Comment by shaka0919** [comment]
> You need to tell Maven to compile against Java 11. Typically, add this to your pom.xml:
> 
> ```
> <plugin>
> 	<artifactId>maven-compiler-plugin</artifactId>
> 	<version>3.8.0</version>
> 	<configuration>
> 		<release>11</release>
> 	</configuration>
> </plugin>
> ```

thanks !
but this code cannot work for me.

I tried another way to fix this issue
 <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
  </properties>

could you help to explain whats the  difference between these two solution?

**Comment by Danniel13** [comment]
Any answer about this?

I use Vstudio Code and in a project to maven i can't use the variable "var" and i need this!

I have my poom.xml:
  <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>

Mistake tag:
var cannot be resolved to a typeJava(16777218)

**Comment by snjeza** [comment]
@Danniel13 Could you attach a sample project reproducing the error?

**Comment by Danniel13** [comment]
> @Danniel13 Could you attach a sample project reproducing the error?

Hi, thank you for your answer I changed the value version to 10 on the maven compiler, and it worked normally, no problem. It's very strange..
