### ISSUE TITLE
It doesen't work 

### ISSUE THREAD

**Issue by VienzaTV** [redhat-developer/vscode-java#855]
When I run my Java command I just get a bunch of errors { 
	"resource": "/D:/!course/j-s basics/myfirstjava.js",
	"owner": "typescript",
	"code": "8009",
	"severity": 8,
	"message": "'public' can only be used in a .ts file.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 7
} {
	"resource": "/D:/!course/j-s basics/myfirstjava.js",
	"owner": "typescript",
	"code": "8009",
	"severity": 8,
	"message": "'public' can only be used in a .ts file.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 3,
	"endLineNumber": 2,
	"endColumn": 9
}{
	"resource": "/D:/!course/j-s basics/myfirstjava.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' expected.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 22,
	"endLineNumber": 2,
	"endColumn": 26
}{
	"resource": "/D:/!course/j-s basics/myfirstjava.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "';' expected.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 22,
	"endLineNumber": 2,
	"endColumn": 26
}{
	"resource": "/D:/!course/j-s basics/myfirstjava.js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 36,
	"endLineNumber": 2,
	"endColumn": 40
}. 

And when I try to delete the extension in order to install it again then this comes up: "Cannot uninstall extension 'Language Support for Java(TM) by Red Hat'. Extension 'Debugger for Java' depends on this."

**Comment by fbricon** [comment]
Looks like you're using JavaScript files. These errors are not generated by the Java tooling. Your Java files need to have a .java extension

**Comment by VienzaTV** [comment]
Hey so I fixed that, a dumb mistake from me. I really appreciate that you answered to fast.
I get this error message when I launch Visual studio codes now:
Java runtime (JDK, not JRE) could not be located

And when I try to run my code it doesn't work even tho there’s nothing wrong with the code.

Best regards:
Kevin Jansson
kevin-jansson@hotmail.com


Från: Fred Bricon<mailto:notifications@github.com>
Skickat: den 22 mars 2019 22:06
Till: redhat-developer/vscode-java<mailto:vscode-java@noreply.github.com>
Kopia: VienzaTV<mailto:kevin-jansson@hotmail.com>; Author<mailto:author@noreply.github.com>
Ämne: Re: [redhat-developer/vscode-java] It doesen't work (#855)


Looks like you're using JavaScript files. These errors are not generated by the Java tooling. Your Java files need to have a .java extension

**Comment by VienzaTV** [comment]
And I did download the JDK

________________________________
Från: Fred Bricon <notifications@github.com>
Skickat: Friday, March 22, 2019 10:05:58 PM
Till: redhat-developer/vscode-java
Kopia: VienzaTV; Author
Ämne: Re: [redhat-developer/vscode-java] It doesen't work (#855)


Looks like you're using JavaScript files. These errors are not generated by the Java tooling. Your Java files need to have a .java extension

**Comment by VienzaTV** [comment]
A guy from discord helped me.
