### ISSUE TITLE
 Formatter Does Not Work If Create New File in VS Code

### ISSUE THREAD

**Issue by byyxx128** [redhat-developer/vscode-java#856]
If I open an existed JAVA file, everything is OK.
However, if I **create a new file and select to Java language mode**, the formatter doesn't work (neither context menu or Ctrl+Alt+F).
Otherwise, if I save the new file, everything is OK again.
In one word, the issue only occurred on **new unsaved files**.

Another extension has similar issues https://github.com/Microsoft/vscode-cpptools/issues/3343, so cannot exclude if it's the limitation by VS Code. But other extensions don't have this issue. So I have no idea about what caused this problem.

**Comment by fbricon** [comment]
This works as designed. The Java language server requires an existing file URI to work correctly. 
We tried to get unsaved file support in the past, but it introduced unnecessary complexity and didn't even work properly, so we abandoned that option.

**Comment by byyxx128** [comment]
@fbricon I agree that. But what I means is just supporting formatting for unsaved files, no other features required. Is it still not feasible? Just format.

**Comment by byyxx128** [comment]
@fbricon I agree that. But what I mean is just supporting formatting for unsaved files, no other features required. Is it still not feasible? Just format.

**Comment by fbricon** [comment]
Not possible. Formatting requires loading the document's AST, which, again, depends on the file URI being accessible by the server.

**Comment by byyxx128** [comment]
OK, got it. In this case, I suppose it is necessary to have a prompt while users use formatting or any other functions for unsaved files. Just like this:
![image](https://user-images.githubusercontent.com/20079289/54862164-f06afb00-4d0c-11e9-9dd6-7a3d09da3c67.png)
