### ISSUE TITLE
Implement vscode supported tracing

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-java#86]
vscode jsonrpc client supports `$/setTraceNotification` and `$/logTraceNotification` notifications. Implement these notifications for tracing messages between server and client.

**Comment by fbricon** [comment]
Isn't it just a server side change?

**Comment by gorkem** [comment]
yes it is.

**Comment by gorkem** [comment]
LSP 3.x has a new mechanism which replaces this one.
