### ISSUE TITLE
Multiple code lines commented with Single-line comments can't be  folded

### ISSUE THREAD

**Issue by lxhmavis** [redhat-developer/vscode-java#860]
##### Environment
- Operating System: Windows/Mac/Linux
- JDK version:1.8.0/11.0.2/12
- Visual Studio Code version:1.32.3
- Java extension version:0.42.0

##### Steps To Reproduce

There are multiple code lines commented with Single-line comments “//”, they can't be folded.
![image](https://user-images.githubusercontent.com/41565966/55148127-980b8180-5182-11e9-9f1a-e64cd384611c.png)

##### Expected Result
It can be folded.

**Comment by fbricon** [comment]
I can see this is supported in ts files, but not for Java files at the moment, so not regression. This is an enhancement we can introduce later.

**Comment by yaohaizh** [comment]
Yes, target the fix for next release.
