### ISSUE TITLE
images not available in bin directory at runtime

### ISSUE THREAD

**Issue by grgendron** [redhat-developer/vscode-java#864]
[provide a description of the issue]Images are not being copied from the the resources directory to the bin directory when running my Java app from VS Code using the debugger interface. The command 'gradle build' from a terminal handles resources getting where it needs to in the build dir.

##### Environment
- Operating System: Windows 10 (1809)
- JDK version: Oracle jdk 11 2
- Visual Studio Code version: 132 and 133
- Java extension version: current

##### Steps To Reproduce
1. [step 1]Create java app that uses an image
2. [step 2] Put the image in the Resource folders for test and main. Run the app

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
can you please attach a sample project reproducing this problem?

**Comment by grgendron** [comment]
Fred:


That was bogus bug report. I am new VS Code. Sorry. Very sorry.

**Comment by fbricon** [comment]
@grgendron it's fine, no worries :-)
