### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by demanLiu** [redhat-developer/vscode-java#866]
[provide a description of the issue]
I use spring-boot 2.1.3.RELEASE ,when I run application 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: net/bytebuddy/NamingStrategy$SuffixingRandom$BaseNameResolver

mvn dependency:tree | grep -10  byte-buddy

[INFO]    +- org.springframework.boot:spring-boot-test:jar:2.1.3.RELEASE:test
[INFO]    +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.1.3.RELEASE:test
[INFO]    +- com.jayway.jsonpath:json-path:jar:2.4.0:test
[INFO]    |  +- net.minidev:json-smart:jar:2.3:test
[INFO]    |  |  \- net.minidev:accessors-smart:jar:1.2:test
[INFO]    |  |     \- org.ow2.asm:asm:jar:5.0.4:test
[INFO]    |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO]    +- junit:junit:jar:4.12:test
[INFO]    +- org.assertj:assertj-core:jar:3.11.1:test
[INFO]    +- org.mockito:mockito-core:jar:2.23.4:test
[INFO]    |  +- net.bytebuddy:byte-buddy:jar:1.9.10:test
[INFO]    |  +- net.bytebuddy:byte-buddy-agent:jar:1.9.10:test

HibernateJpaConfiguration.class needs byte-buddy ,but byte-buddy's scope is "test",So application can not find byte-buddy at runtime,then I remove scope in  pom.xml, it's ok
   <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            
     </dependency>

But when I execute "mvn clean package && java -jar  xxx.jar "  ,it is ok 
 at the same time ，it‘s also ok using IntelliJ IDEA

##### Environment
- Operating System:archlinux
- JDK version: 1.8.0_202
- Visual Studio Code version:1.32.3
- Java extension version:
Language Support for Java(TM) by Red Hat 0.42.1
Maven for Java 0.15.2

**Comment by fbricon** [comment]
vscode-java itself doesn't cover running code on its own. Can you please open a ticket in https://github.com/Microsoft/vscode-java-debug/issues, with a sample project reproducing the problem?
