### ISSUE TITLE
Java runtime (JDK, NOT JRE) COULD NOT BE LOCATED

### ISSUE THREAD

**Issue by Santiagoarego** [redhat-developer/vscode-java#868]
Hey, im having this problem with VS code, i installed the extension to use JAVA but im getting this message
![imagen](https://user-images.githubusercontent.com/48213222/55431028-15553e80-5555-11e9-8dee-4f06dddf2acc.png)

I downloaded JDK from oracle's webpage and when I look the settings I get this
![imagen](https://user-images.githubusercontent.com/48213222/55431066-328a0d00-5555-11e9-9e85-0c94a2efaaec.png)

It says that my version is jdk1.8.0_161 but in my program files I have this.

![imagen](https://user-images.githubusercontent.com/48213222/55431140-606f5180-5555-11e9-93cb-94f68713495c.png)

I don't know what I have to do, i need help please
##### Environment
- Operating System: Windows 10 Home
- JDK version: 1.8.0_201
- Visual Studio Code version: Last ONe
- Java extension version:

**Comment by fbricon** [comment]
The setting you're seeing is an example ( i.e). You need to click on Edit in settings.json and point the java.home preference to your actual JDK

**Comment by yaohaizh** [comment]
@Santiagoarego If you new to the VSCode Java, you can follow this tutorial: https://code.visualstudio.com/docs/java/java-tutorial

**Comment by anks333** [comment]
I had the same issue. Removed the Open JDK and installed Oracle JDK, then it started working.

**Comment by Tariqafridi36** [comment]
I am facing the same issue. Even i download the Java Runtime.

**Comment by hemangjoshi37a** [comment]
I have same issue. Anyone have found any solution yet?

**Comment by DazSheehan** [comment]
I had this issue today,  It needs access to the javac program to compile the java.

On windows open CMD and type `where javac`

Hopefully it will come back with a not found error indicating that the jdk is not in your path. 

On windows 10 
- go to start and type **'env'** to bring up 'Edit the system environment variables'
- Click '**Envirionment Variables**'
- Under user variables select **Path** and **Edit**
- Add the path to the jdk bin folder ( for me it was C:\Program Files\Java\jdk-12.0.2\bin) 

Go back to cmd and type `where javac` - this time it should come back with a path.  Resart vscode and cross your fingers.

**Comment by RanjithKumarPeddala** [comment]
Thanks dude @Santiagoarego

**Comment by hiroga-cc** [comment]
I want to specify my JDK version and had the same issue with macOS.

## works

```setting.json
{
    "java.home": "/Users/myname/.sdkman/candidates/java/8.0.222.j9-adpt" // works
}
```

## not works

```setting.json
{
    "java.home": "${env:HOME}/.sdkman/candidates/java/8.0.222.j9-adpt" // not works
}
```

## Environment
* OS: macOS Catalina
* VSCode: 1.41.1

**Comment by Dr-Irv** [comment]
For what it's worth, my colleague was having the same problem, and the issue was that the SonarLint extension was causing this problem.  We uninstalled that extension.  Then we had to clone his repo into a new directory, and everything was fine.  His existing workspace/folder with a complex Java project was a mess, most likely due to SonarLint.

**Comment by Eskibear** [comment]
FYI that a JRE is embedded into this extension for most platforms since v1.2.0. So you can only focus on the JDK/JRE for your projects, and you probably won't see this error again.

See https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements#setting-the-jdk

**Comment by Eskibear** [comment]
and setting `java.home` is deprecated in favor of `java.jdt.ls.java.home` (if you are using a universal version or you do want to launch language server with a specific runtime)
