### ISSUE TITLE
Invalid/stale syntax errors are sometimes shown while typing

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#87]
Typing java code sometimes (I haven't found a pattern yet) displays syntax errors. There's no way to get rid of them but to delete big chunks of code or restarting vscode. It seems as if the working copy was desynchronized at some point.

**Comment by fbricon** [comment]
It seems the problem can be reproduced after doing some auto-import and deleting some code:

http://screencast.com/t/fqogyV8SKPRe

**Comment by fbricon** [comment]
I have a hunch  https://github.com/redhat-developer/vscode-java/issues/77 might be a side effect of that problem.

**Comment by gorkem** [comment]
I think https://github.com/gorkem/java-language-server/commit/82475bcc820352b32c990f8ab367bf3fb00e54f4 is now the final solution for this one.
