### ISSUE TITLE
Java does not execute unless package statement is commented out

### ISSUE THREAD

**Issue by grantjayy** [redhat-developer/vscode-java#877]
When opening any Java project, or maven project, new or old, Java throws "Error: Could not find or load main class App" at runtime. Java will only run if "package foo;" is commented out i.e. "//package foo;". 

I am using the code runner extension, which works with every other language. It runs as expected in java if the package statement is excluded or commented out.

This is able to be replicated in every new java program created or opened inside VS Code, even projects created in IntelliJ (Which run as expected) and opened in VS Code.

##### Environment
- Operating System: Mac OSX Mojave 10.14.4
- JDK version: 1.8.0_202
- Visual Studio Code version: 1.33.0
- Java extension version: 0.6.0

##### Steps To Reproduce
1. [step 1] Create new java file (Shift + Command + P, Java: Create New Java Project")
2. [step 2] Attempt to run App.java 

##### Current Result
Java throws: 

Error: Could not find or load main class App

When "Package foo;" is uncommented.

##### Expected Result

Java executes program normally

##### Additional Informations
<img width="1436" alt="Example1" src="https://user-images.githubusercontent.com/47218341/55919277-867a9e80-5bb2-11e9-91f9-fa60b84b879f.png">

<img width="1440" alt="Example2" src="https://user-images.githubusercontent.com/47218341/55919278-867a9e80-5bb2-11e9-99a2-44a8a1a84c92.png">

**Comment by cressceaux** [comment]
Same problem.

**Comment by testforstephen** [comment]
@grantjayy This is a bug from **code runner** extension, please open a bug there.
However, you can try [Debugger for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) extension to run the Java code.

**Comment by yaohaizh** [comment]
Please log an issue to coder runner repo: https://github.com/formulahendry/vscode-code-runner

I will close this issue instead.

**Comment by MichaelScu** [comment]
Same problem here, did you already solve this problem?
