### ISSUE TITLE
Renaming annotated class

### ISSUE THREAD

**Issue by jnesspro** [redhat-developer/vscode-java#878]
When I rename (F2) annotated class I getting broken code, what is wrong with me?

`
@Slf4j
@RequiredArgsConstructor
public class Asserts {
`
rename to Asserts1 =>
`
@Slf4j
Asserts1edArgsConstructor
public class Asserts1 {
`

i see this bug since a beginning of time I using vscode for java

##### Environment
- Operating System: MacOS
- JDK version: 1.8
- Visual Studio Code version: all versions

**Comment by fbricon** [comment]
Chances are lombok integration is misbehaving. Please attach your server logs

**Comment by jnesspro** [comment]
Yes, with lombok's annotations.
I disabled lombok plugin and removed *.class - result is the same. Logs attached
Also, I see that annotation associated with class name somehow (cursor highlights both classname and annotation)

**Comment by jnesspro** [comment]
Yes, with lombok's annotations.
I disabled lombok plugin and removed *.class - result is the same. Logs attached
Also, I see that annotation associated with class name somehow (cursor highlights both classname and annotation)
<img width="314" alt="Screenshot 2019-04-15 at 11 01 54" src="https://user-images.githubusercontent.com/5245360/56116623-f8fecc00-5f6e-11e9-931c-070dc048530a.png">
[java.log.zip](https://github.com/redhat-developer/vscode-java/files/3079065/java.log.zip)

**Comment by schmalzi-compax** [comment]
This is an annoying bug, would be great to have it fixed in further releases.

**Comment by snjeza** [comment]
See https://github.com/eclipse/eclipse.jdt.ls/pull/1779
