### ISSUE TITLE
Javadoc hides errors/warnings

### ISSUE THREAD

**Issue by danstewart** [redhat-developer/vscode-java#879]
The javadoc hover popup sometimes clashes with the error/warning hover popups.
Is this a vscode-java issue or just a vscode issue? 
Is it possible to disable the javadoc hover popup?

I'm hovering over the first `Map` here:
![image](https://user-images.githubusercontent.com/10670565/55957781-0cecba00-5c5f-11e9-858b-f1c3354d7219.png)

Thanks

**Comment by fbricon** [comment]
scroll down, you should see the warning at the bottom. that's vscode's behavior

**Comment by danstewart** [comment]
Thanks
