### ISSUE TITLE
Invisible project could not be automatically resolve the dependencies

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#882]
When adding a dependency into the lib, the syntax error still occurs and could not compile the project.

##### Environment
- Operating System: Windows
- JDK version: Oracle 11.0.2
- Visual Studio Code version: 1.33.1
- Java extension version: 0.42.1

##### Steps To Reproduce
See the GIF:
![issue](https://user-images.githubusercontent.com/6193897/56120340-83135880-5fa0-11e9-8dc7-b6172bd6dba1.gif)

**Comment by fbricon** [comment]
It works on my Mac, but I can reproduce the issue on Windows. Will check on Linux

**Comment by fbricon** [comment]
I see the problem is caused by the server sending filewatcher glob patterns with a `c:/path/to/lib` syntax. The device part (`c:`)doesn't seem to be handled by VS Code properly. I found a couple other issues with the filewatchers, but the device part is the main one.
