### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by 1035311527** [redhat-developer/vscode-java#885]
I open the file with encoding utf 8 ,but i cant run the code because of the encoding.Is there any way to solve the problem?
![深度截图_选择区域_20190416173219](https://user-images.githubusercontent.com/24894908/56198616-d1425d80-606d-11e9-87d7-8467883d8c06.png)

**Comment by yaohaizh** [comment]
@1035311527 Which extension that you used to run the code?

**Comment by 1035311527** [comment]
code-runner

**Comment by 1035311527** [comment]
@yaohaizh code-runner

**Comment by yaohaizh** [comment]
@1035311527 Please log an issue aganist the code runner repo. This is not related to VSCode language server. Or you can use VSCode Java debugger to run code for encoding issue.
