### ISSUE TITLE
Support go to implementation for method/function

### ISSUE THREAD

**Issue by khsing** [redhat-developer/vscode-java#886]
go to implementation just to works on import/definition section. It's not work for method of entity. 

how to make it works.

##### Environment
- Operating System: macOS 10.14.4 (18E226)
- JDK version: java version "1.8.0_201"
- Visual Studio Code version: 1.33.1 (1.33.1)
- Java extension version: 0.42.1

##### Steps To Reproduce
1. move cursor to a method of entity object.
2. cmd+F12 will display no implementation found, but actually it exists.

##### Expected Result
cmd+F12 should go to method of implementation directly.
##### Additional Informations

**Comment by fbricon** [comment]
Works for me. Can you give us more details on your setup? Maven, Gradle, Eclipse project or standalone Java files? Do you use lombok? Providing a sample project to reproduce the issue would help.
Can you enable [verbose logging](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server) and attach the content of the Output view (select Language support for Java in the view menu)?

**Comment by fbricon** [comment]
![Apr-16-2019 09-17-18](https://user-images.githubusercontent.com/148698/56212671-7df9ec00-6028-11e9-9688-664b1c2dce13.gif)

**Comment by khsing** [comment]
for example: 
```java
public interface FoobarInterface {
    public String foo();
}
```
Implementation 
```java
public class Foobar implements FoobarInterface {
    public String foo(){
        return "hello";
    }
}
```
Other service
```java
public class FoobarService {
    private FoobarInterface foobar;
    
    public void bar(){
        foobar.foo(); // if my cursor in foo() and click go to implementation, it should jump to FooBar.foo directly. 
    }
}
```

**Comment by testforstephen** [comment]
This is a bug of eclipse.jdt.ls. Go to implementation only works when selecting a method declaration, and doesn't handle well for the method invocation.
