### ISSUE TITLE
Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by yilufengshun** [redhat-developer/vscode-java#887]
[provide a description of the issue]

##### Environment
- Operating System:Win7
- JDK version:jdk8
- Visual Studio Code version: 1.33
- Java extension version: 42.1

##### Steps To Reproduce
Steps to reproduce: Open vscode, open a java file, then wait, then the console will get this error

I tried all the current options for this, but none of them are useful.

I ruled out the issue with the vscode version and the java plugin version.

And there is no log.

I tried to run the command to start the java language server directly in cmd, but I will prompt:
The java virtual machine has stopped running.

Finally I think and https://github.com/redhat-developer/vscode-java/issues/828
Similarly, running java should only be related to jdk.

So I tried to replace jdk, I first used oracle jdk, 8, 9, 12

But they are all the same,

So I tried to use openjdk8

Surprisingly, he is able to run normally

I don't know if it is because of my jdk configuration problem, or the problem of oraclejdk itself.

I don't know why this happened. On my other computer, he is normal.

I hope you can solve this problem.

The above content is from Google Translate, please understand if there is a grammatical error.

My English is very bad

**Comment by fbricon** [comment]
I'm closing the many duplicates for this issue, please keep an eye on #112 for further informations
