### ISSUE TITLE
VSCode Java extension activate should not wait for workspace initialize event

### ISSUE THREAD

**Issue by yaohaizh** [redhat-developer/vscode-java#888]
Currently, the vscode java extension will resolve as activated after the workspace is loaded, which is not quite accurately. 

IMO, 
1. Extension ready: The extension should resolve as activate when the initialization(detect JDK, start language server, non language server command ready)  work is done.

2. Language server ready: The extension should send another events/signal when the language server is ready.

**Comment by snjeza** [comment]
Related issue: https://github.com/eclipse/eclipse.jdt.ls/issues/981

**Comment by jdneo** [comment]
Addressed via https://github.com/redhat-developer/vscode-java/blob/31b0a60974d1c8f8b35790ee34781fb4510af46a/src/extension.api.ts#L120
