### ISSUE TITLE
cannot work very well

### ISSUE THREAD

**Issue by chwentao** [redhat-developer/vscode-java#89]
![image](https://cloud.githubusercontent.com/assets/13378254/19965168/b53f1660-a200-11e6-8a3c-90ff7171fc25.png)
 can not work very well, can you help me?

**Comment by fbricon** [comment]
I'm sorry but you'll have to be more explicit than that. What do you define as "can not work very well"? Please give us more details, like step-by-step instructions on how to reproduce your issue.

**Comment by chwentao** [comment]
I have install jdk8,but IT can not support java project too.
![image](https://cloud.githubusercontent.com/assets/13378254/19992203/fca6a45c-a276-11e6-8710-e592892a28b2.png)
