### ISSUE TITLE
Releases do not have `vsix` files

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/vscode-java#892]
A Github release should contain not only source code but also vsix file - https://github.com/redhat-developer/vscode-java/releases/tag/v0.40.0
from `VS Code marketplace rate limit error ` perspective it is important to have vsix file for latest and all upcoming + `0.38.0`

**Comment by ibuziuk** [comment]
@fbricon will you be able to give a hand with this?

**Comment by fbricon** [comment]
@ibuziuk yes

**Comment by fbricon** [comment]
Uploaded 0.38.0 and more recent releases to https://github.com/redhat-developer/vscode-java/releases

**Comment by nickboldt** [comment]
As of 0.48.0, releases no longer include vsix files. I was about to open a new issue like https://github.com/camel-tooling/vscode-wsdl2rest/issues/142 or https://github.com/redhat-developer/vscode-project-initializer/issues/40 but reopening seemed easier.

Can you either:

* copy the tarball from the GH release over to dl.jb.o when publishing the vsix there, or 
* publish the vsix on GH again?

Looking for sources to align these (and newer ones):

* https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.50.0-1825.vsix
* https://github.com/redhat-developer/vscode-java/releases/tag/v0.50.0 -> https://github.com/redhat-developer/vscode-java/archive/v0.50.0.tar.gz

**Comment by nickboldt** [comment]
Ping! any progress here?

**Comment by fbricon** [comment]
I've pushed all the tags, then downloaded each missing vsix curl like
```
version=0.54.2; \
curl -o redhat.java-${version}.vsix https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/java/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
```
Then manually attached the vsix files to their matching tags in https://github.com/redhat-developer/vscode-java/releases
