### ISSUE TITLE
disable unused import warnings

### ISSUE THREAD

**Issue by clankill3r** [redhat-developer/vscode-java#894]
Is there a way to disable unused import warnings.
At some stages I don't care about them and I have hundreds of them, they get in the way of things I do care about.

**Comment by snjeza** [comment]
You can add the following preference:
``` 
org.eclipse.jdt.core.compiler.problem.unusedImport=ignore
``` 
to <your_project>/.settings/org.eclipse.jdt.core.prefs

**Comment by AntSworD** [comment]
> You can add the following preference:
> 
> ```
> org.eclipse.jdt.core.compiler.problem.unusedImport=ignore
> ```
> 
> to <your_project>/.settings/org.eclipse.jdt.core.prefs

It doesn't work for me，can I figure out what happen by myself?
Another config of org.eclipse.jdt.core.prefs is not working too, such as `org.eclipse.jdt.core.compiler.problem.missingSerialVersion=ignore`

**Comment by snjeza** [comment]
@AntSworD could you provide a sample project?

**Comment by HarveyTvT** [comment]
@A

> > You can add the following preference:
> > ```
> > org.eclipse.jdt.core.compiler.problem.unusedImport=ignore
> > ```
> > 
> > 
> > to <your_project>/.settings/org.eclipse.jdt.core.prefs
> 
> It doesn't work for me，can I figure out what happen by myself?
> Another config of org.eclipse.jdt.core.prefs is not working too, such as `org.eclipse.jdt.core.compiler.problem.missingSerialVersion=ignore`

if you are working on a java project with multiple sub-projects, you can try to copy org.eclipse.jdt.core.prefs to each sub-projects`s .settings folder

./main-project
----./.settings
----./sub-project
--------./settings
------------./org.eclipse.jdt.core.prefs

**Comment by clankill3r** [comment]
I can no longer get this to work.
I'm not using maven or gradlle but I just use 'vscode' (I have no idea how to call it), with the lib folder, and where I can add libs using the + button under the `Java Projects` in the EXPLORER.

This is what my structure looks like:

![Screen Shot 2020-08-28 at 10 40 04](https://user-images.githubusercontent.com/738650/91540319-e9411700-e91a-11ea-84e2-5df08b2c5629.png)

**Comment by clankill3r** [comment]
It seems like org.eclipse.jdt.core.prefs magically works again so I close this issue for now.
