### ISSUE TITLE
Java language server crashing (5 times error)

### ISSUE THREAD

**Issue by jakegt1** [redhat-developer/vscode-java#897]
Language server fails to start after 5 times.

##### Environment
- Operating System: MacOS
- JDK version: 1.8.0_201
- Visual Studio Code version: 1.33
- Java extension version: 0.43.0

##### Steps To Reproduce
N/A

##### Current Result
Requires deletion of the redhat-java folder in workspaceStorage to fix

##### Expected Result
Should not require this folder to be deleted and recreated, and instead should either report to the user the problem or have the problem fixed.

##### Additional Informations

I am sorry for the lack of info for this issue, but i do not know how it happened and i cannot provide a project it happened in, but there has been other people have been having this issue (https://github.com/redhat-developer/vscode-java/issues/887) and there seems to be no logic or reason to it.

I can inform that deleting the redhat-java folder inside a specific workspaceStorage folder will fix the issue and reload the server. It seems likely that something went wrong, i reloaded the server and during that time botched config was left inside the redhat-java folder.

**Comment by pavkum** [comment]
I'm also facing the same issue.

**Comment by yilufengshun** [comment]
I have this problem when using oracle jdk, I changed it after changing openjdk, you can try it.

**Comment by veredcon** [comment]
I have also the same issue. Is there any solution for it?

**Comment by SeriousMan-NJ** [comment]
I faced the same issue, and solved by entering "Java: Clean the java language server workspace" In the Command Palette. I hope this might help..

**Comment by NikolasKomonen** [comment]
One thing to maybe try is to run the 'jps' command (with all IDE's closed)

```bash
$ jps
```

and then see if one of the processes that looks like the following
is still running: 

```
2438 org.eclipse.equinox.launcher_1.5.400.v20190515-0925.jar
```

The Java language server process may not have ended and could be causing issues.
