### ISSUE TITLE
Folder with dot does not identified as a valid package

### ISSUE THREAD

**Issue by mong0520** [redhat-developer/vscode-java#902]
[provide a description of the issue]

##### Environment
- Operating System: MacOS
- JDK version: 1.8.0_201
- Visual Studio Code version: 1.33.1
- Java extension version: 0.43.0

##### Steps To Reproduce
1. A folder structure looks like "src/main/java/com/foo.bar/Test.java"
2. Set "src/main/java" as the source search path
3. Declare package as `package com.foo.bar ;` in Test.java

##### Current Result
VS Code complains on `package` which is `The declared package "com.foo.bar" does not match the expected package ""`. The warning message shows the expected package is EMPTY which means VS Code can not identify folder "com/foo.bar" is a source search path.

It won't happen in IntelliJ.

##### Expected Result
Treat dot in folder name as a valid package.

##### Additional Informations

**Comment by mong0520** [comment]
close

**Comment by mong0520** [comment]
close

**Comment by tim8917** [comment]
I have the save issue. How to manage it?
