### ISSUE TITLE
A simple JavaEE/maven project - dependencies not recognized

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#905]
> Originally created by @zemiak at Microsoft/vscode-java-pack#137

The code is here: https://github.com/zemiak/javarocks
Simple: Java 1.8.0.212, maven 3.6, MacOS 10.14.3
Maven project declares JavaEE 8 as "provided"
Packages not recognised, errors popping up.
No meaningful output in the "OUTPUT" window

See at least https://raw.githubusercontent.com/zemiak/javarocks/master/docs/Missing%20Packages.png

Thanks,
Miro

**Comment by yaohaizh** [comment]
@zemiak https://github.com/redhat-developer/vscode-java/issues/62
Java EE projects is not officially support yet.

**Comment by zemiak** [comment]
It’s a simple maven project. With one maven dependency. It does not matter if the dependency is JavaEE or something different. 
It should recognize packages brought in by the dependency.

**Comment by yaohaizh** [comment]
Java EE dependencies are not on the Java SE libraries, nor in the maven dependency. 

@fbricon Any additional we need to do to support Java EE?

**Comment by snjeza** [comment]
@zemiak See https://github.com/redhat-developer/vscode-java/issues/906#issuecomment-487380739

**Comment by fbricon** [comment]
@zemiak works for me. Please follow the instructions in https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting to collect detailed server logs. Check if your project builds in CLI, there might be an issue with a corrupt jar. If it's not that, chances are, cleaning the server directory should fix the issue.

**Comment by zemiak** [comment]
java.import.maven.enabled helped as @snjeza suggested. How come this option was turned off?

**Comment by fbricon** [comment]
Either you disabled it manually or you have a rogue extension that did it on its own (I'm not aware of such extension).
