### ISSUE TITLE
JavaSE/Maven project - maven's commons-lang3 dependency not recognized

### ISSUE THREAD

**Issue by zemiak** [redhat-developer/vscode-java#906]
A simple dependency from Maven is not recognized

##### Environment
- Operating System: MacOS 10.14.4 (18E226)
- JDK version: 1.8.0_212-b10
- Visual Studio Code version: 1.33.1 (1.33.1)
- Java extension version: 0.7.0

##### Steps To Reproduce
1. clone project: https://github.com/zemiak/javarocks-javase
2. see docs/ - images with errors

https://github.com/zemiak/javarocks-javase
in the project, "docs" folder

##### Current Result
commons.lang dependency not recognized

##### Expected Result
code completion should work, no error should be reported

##### Additional Informations
mvn test and mvn package works
There are multiple problems, but I will report it one by one

**Comment by snjeza** [comment]
Could you try to set the following property:
```
"java.import.maven.enabled": true,
```

**Comment by zemiak** [comment]
And it helped. How come, that this was turned off? Thank you!
