### ISSUE TITLE
The quick fix label for generating getter and setter has an unnecessary ellipsis

### ISSUE THREAD

**Issue by testforstephen** [redhat-developer/vscode-java#908]
So if you have 2 fields without accessors, the quickfix to generate them has an ellipsis, yet no wizard is shown as you'd expect from the ellipsis.
<img width="378" alt="Screen Shot 2019-04-29 at 7 05 30 PM" src="https://user-images.githubusercontent.com/148698/56932428-c9dd7400-6ab1-11e9-86c2-5c2e5714ea88.png">

**Comment by fbricon** [comment]
@testforstephen it's an easy fix, so I opened https://github.com/eclipse/eclipse.jdt.ls/pull/1019 myself
