### ISSUE TITLE
[javac] package org.junit doesn't exists but it is imported in the pom.xml

### ISSUE THREAD

**Issue by petrux** [redhat-developer/vscode-java#91]
[provide a description of the issue]

`[javac] package org.junit doesn't exists` but it is imported in the pom.xml -- and everything works fine from the command line. I assume there is some wrong `-cp` for the `javac` command.

##### Environment
- Operating System: Ubuntu 16.04
- JDK version: Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
- Visual Studio Code version: Version 1.7.1
- Java extension version: 0.0.6

##### Steps To Reproduce
1. [step 1] create an empty project
2. [step 2] add the following depende  to your pom.xml:

<dependency>
    
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
    </dependency>

3. [step 3] create a test file and import `org.junit.Test`.

[attach a sample project reproducing the error]

**Comment by fbricon** [comment]
This is most likely caused by the fact pom.xml changes are not reported as classpath changes, yet. See https://github.com/redhat-developer/vscode-java/issues/17.

What happens if you close and reopen your project?

**Comment by petrux** [comment]
> What happens if you close and reopen your project?

Nothing. The error is always there.

**Comment by gorkem** [comment]
@fbricon Does m2e has a mysterious cache?

**Comment by fbricon** [comment]
@gorkem not really. the maven model is cached during while the server is running but restarting it (by reopening the project) should reset it.

@petrux do you have a sample project reproducing the error? I can't reproduce the issue. Or you could also record a screencast of what's happening.

**Comment by petrux** [comment]
Apparently, erasing the directory and re-creating it from scratch removes the error. As far as I remember, I changed the junit version after creating the project, maybe that's something harmful?

**Comment by Akuukis** [comment]
I have the same problem.

1. today installed fresh debian 9 + GNOME
2. installed openJDK 8 and gradle via apt-get (along a lot other not related packages)
3. installed code and it's extensions (along a lot other not related extensions)
4. `gradle init --type java-library`
5. Saw this `package org.junit doesn't exists` in test file but `gradle test` works
6. Edit, click around, paste in my own file, but point 5. stands true.
7. Restart VSCode, but point 5. stands true.
8. copy project to another folder, restart VSCode and open the second, but point 5. stands true.

**Comment by Akuukis** [comment]
I found that solution is to disable/remove another extension "Java Language Support".

Sorry for writing in the wrong place!

**Comment by solerman** [comment]
Tks, removing that extension resolved the very same issue for me. This issue can be closed

**Comment by fbricon** [comment]
`[javac]` prefixed messages indicate https://github.com/georgewfraser/vscode-javac has been installed (I should have noticed way earlier). So not a vscode-java issue.
