### ISSUE TITLE
"Generating Effective POM" renders the PC unusable on startup and causes Maven releases to fail

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-java#910]
My workspace has 3 Maven projects, with in total 17 modules.

Sometimes when opening VS Code (it doesn't happen on each startup, and I haven't been able to find a logic in it yet. For example, it has already occurred, even though none of the POMs had changed since the previous occurrence), it shows "Generating Effective POM" and the PC becomes effectively unusable for several minutes (to the point where VS Code itself says the windows is no longer responding, see screenshot below).

Another manifestation of this issue, is when doing a release (using Maven's release plugin) of a larger project (1 of the projects has 11 submodules): since all the POMs are changed multiple times in a short period, VS Code goes nuts trying to keep up with generating effective POMs, which causes the build to fail.

##### Environment
- Operating System: Windows 10 1809
- JDK version: 12.0.1
- Visual Studio Code version: 1.33.1
- Java extension version: 0.43.0

##### Steps To Reproduce
I can't readily share my projects, but I believe it's a simple combination of large effective POMs (mine are 1000+ lines) and the fact that they're all being generated in parallel.

##### Current Result
The PC becomes unusable on VS Code startup, and releases fail.

##### Expected Result
The PC remains usable at all times, and releases don't fail.
Some ideas:
- make sure to regenerate effective POMs only when there's been an actual change, and that change might have an impact (e.g. if the project's description was changed, there's no need to regenerate)
- generate effective POMs sequentially
- detect when a Maven release is going on, and avoid generating effective POMs during that time
- provide a folder-specific setting to have VS Code ask me each time it wants to generate an effective POM

##### Additional Informations

![image](https://user-images.githubusercontent.com/15714253/57008853-504d9f00-6bf3-11e9-9d99-fca78847b1df.png)

**Comment by fbricon** [comment]
"Generating effective pom" is an feature of [vscode-maven](https://github.com/Microsoft/vscode-maven/). Please report this problem in its [issue tracker](https://github.com/Microsoft/vscode-maven/issues). cc @Eskibear
