### ISSUE TITLE
Allow navigation to overridden method

### ISSUE THREAD

**Issue by rhwood** [redhat-developer/vscode-java#911]
Moving from NetBeans, I miss the ability to navigate directly to the super implementation of an overridden method (either where it is defined in an interface or in a parent class). In NetBeans, this is a directly available action as a keyboard shortcut or from a context menu. There seems to be no such discoverable mechanism in VS Code.

##### Environment
- Operating System: macOS Mojave 10.14.4
- JDK version: 1.8.0_202
- Visual Studio Code version: 1.33.1
- Java extension version: 0.43.0

**Comment by testforstephen** [comment]
This has been supported in java extension. It provides two entries for that.
- Javadoc
![image](https://user-images.githubusercontent.com/14052197/218384129-a7091180-958d-47aa-a15e-53e2aebc997c.png)

- Context menu
![image](https://user-images.githubusercontent.com/14052197/218384388-b15b2686-9472-495a-9d18-4329c6bd0bcd.png)
