### ISSUE TITLE
On PC restart, VS code java server fails to restart: The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by K2Prasanna** [redhat-developer/vscode-java#913]
Everytime I restart my computer and open VS code, My java language server fails. So it requies reinstalling extensions everytime. please let me know in what can be the issue. I am attaching logs for more information.

I did go through the existing issues few times and got some debugging tips which I have used to extract information about the issue. But not able to resolve it.

##### Environment
- Operating System: Win 10
- JDK version: jdk1.8.0_201
- Visual Studio Code version: 1.33.1
- Java extension version:0.44.0

##### Steps To Reproduce
1. restart PC
2. Open VS code
3. Open java file
Please not attached log for more information. 

##### Current Result
Java language server does not start.

##### Expected Result
Language server should be up and running
##### Additional Informations
[1557207543107.log](https://github.com/redhat-developer/vscode-java/files/3151000/1557207543107.log)

**Comment by fbricon** [comment]
Can you try to [clean](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory) the server workspace directory?

**Comment by K2Prasanna** [comment]
Thank you, Fred! I tried cleaning the workspace. It didn't work. then I tried to clean up and then restart my PC as well. That also landed in the same issue. 

On the surface, It seems to have to do with loading sequence of the extensions or libraries. But I am not sure of this.

Thank you for your prompt response 

Regards,
Prasanna

[1557291952635.log](https://github.com/redhat-developer/vscode-java/files/3155626/1557291952635.log)
!

**Comment by snjeza** [comment]
@K2Prasanna could you attach your C:\Users\<YOUR_USERNAME>\.vscode\extensions\redhat.java-0.44.0\server\config_win\config.ini?

**Comment by wkurzius** [comment]
I'm having the same issue, or at least a very similar one.

- Windows 10
- openjdk version 1.8.0_201
- Visual Studio Code 1.33.1
- Language Support for Java 0.44.0

[config.ini](https://github.com/redhat-developer/vscode-java/files/3164146/config.ini.txt)

**Comment by snjeza** [comment]
Do you have write permission on C:\Users<YOUR_USERNAME>.vscode\extensions\redhat.java-0.44.0\server\config_win?

**Comment by wkurzius** [comment]
> 
> 
> Do you have write permission on C:\Users<YOUR_USERNAME>.vscode\extensions\redhat.java-0.44.0\server\config_win?

Yes. And just to see if it had any effect, I ran VSCode as admin and got the same error.

`The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.`

**Comment by snjeza** [comment]
Could you provide VS Code-Java log - https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-vscode-java-logs and https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-vscode-java-logs ?

**Comment by wkurzius** [comment]
I just started VSCode back up to get these and now it's working again. I've been wrestling with this for days and I have no idea what caused it to fix itself. The last thing I tried was a clean install of VSCode (removed everything from user folder and appdata, too), but the error popped up again after reinstalling the extension. That's when I decided to post here.

Let me know if you still want the logs, and thanks for the help. Sorry I couldn't be more helpful.

**Comment by yaohaizh** [comment]
@wkurzius Do you have upgraded vscode java extension or installed JDK before this happened?

**Comment by K2Prasanna** [comment]
> @K2Prasanna could you attach your C:\Users<YOUR_USERNAME>.vscode\extensions\redhat.java-0.44.0\server\config_win\config.ini?

Thank you! Please note attached, the config file.

[config.txt](https://github.com/redhat-developer/vscode-java/files/3165797/config.txt)


thanks,
prasanna

**Comment by K2Prasanna** [comment]
Hi,
Now I notice that when restart the PC, the config.ini is not at the location **(C:\Users<YOUR_USERNAME>.vscode\extensions\redhat.java-0.44.0\server\config_win\config.ini)**.

It looks like somehow on startup, the file gets deleted. Is there a way to configure the location for extensions?

Thanks,
Prasanna

**Comment by wkurzius** [comment]
> 
> 
> @wkurzius Do you have upgraded vscode java extension or installed JDK before this happened?

Between when I posted here first and when it started working I upgraded nothing. And I only first installed the extension a few days ago. At that time I had openjdk version 1.8.0_201 and Visual Studio Code 1.33.1.

**Comment by snjeza** [comment]
@K2Prasanna Could you try the following:

- close VS Code
- remove C:\Users<YOUR_USERNAME>.vscode
- start VS CODE
- install your extensions

**Comment by K2Prasanna** [comment]
> @K2Prasanna Could you try the following:
> 
> * close VS Code
> * remove C:\Users<YOUR_USERNAME>.vscode
> * start VS CODE
> * install your extensions

Sorry for the delayed reply. I performed the steps, but still, on restarting the servers I face the issue and I see that config.ini does not exist in the directory post restart.

Thanks,
Prasanna

**Comment by snjeza** [comment]
@K2Prasanna do you have write permission on C:\Users\<YOUR_USERNAME>.vscode?

**Comment by veredcon** [comment]
I get the same issue with the exact mentioned versions.

**Comment by fbricon** [comment]
I'm closing the many duplicates for this issue, please keep an eye on #112 for further informations
