### ISSUE TITLE
Build on save skips on 0.43.0 and 0.44.0

### ISSUE THREAD

**Issue by riccardobl** [redhat-developer/vscode-java#916]
It appears that version 0.43.0  introduced a bug that causes the autobuild (build on save) to randomly skip.

I'm not sure if this is related to the size or layout (main gradle project with 3 subprojects) of my project, but this is what is happening:

- A program that is started after the code has been changed will run with the old code (the changes are not reflected). 
- If the program is already running in debug mode, hot reload doesn't work.

If vscode is restarted after the save, the program will always start with the updated code as expected, if the same file is saved multiple times (literally spamsaved), one of the saves will trigger the build, also sometimes but very rarely it seems to just work on the first save ¯\\_(ツ)_/¯.

I've tried to downgrade to 0.42.1 keeping the same project and same configuration and this version worked as expected, then i tried again 0.43 and 0.44 and both presented the issue.

- Operating System: Ubuntu 18.04 - 5.0.7-050007-generic
- JDK version: Zulu 8.38.0.13-CA-linux64 (openjdk8)
- Visual Studio Code version: 1.33.1
- Java extension version: 0.44.0

**Comment by snjeza** [comment]
@riccardobl Could you provide a project example?

**Comment by riccardobl** [comment]
Sure:  [Test.zip](https://github.com/redhat-developer/vscode-java/files/3156518/Test.zip)

So... my first guess of it being somehow related to the project layout was wrong, since it presents itself even on this simple single file project.

I've also uploaded a short video to show it: https://www.youtube.com/watch?v=FMX0qtNA-YA

**Comment by fbricon** [comment]
Tested with Zulu JDK 1.8.212, on Ubuntu 19.04, still works perfectly.
- Try to [clean the server workspace directory](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)
- and/or try disabling all your extensions, except for vscode java and the java debugger

**Comment by snjeza** [comment]
> My user settings are

Do you have the <your_project>/ .vscode/settings.json file?

**Comment by riccardobl** [comment]
> Do you have the <your_project>/ .vscode/settings.json file?

No, everything i have is included in the zip file.

**Comment by snjeza** [comment]
@riccardobl I can't reproduce the issue too.
Could you try add the following properties:

```
"java.debug.settings.forceBuildBeforeLaunch": true,
 "java.debug.settings.enableHotCodeReplace": true,
```

**Comment by riccardobl** [comment]
So i started with a clean install and i tried to enable settings and extensions one by one until it broke, it turned out being caused by a typo in the java.format.settings.url path.

Sorry if i made you waste time, I didn't even thought about this since the older version worked.

**Comment by snjeza** [comment]
> So i started with a clean install and i tried to enable settings and extensions one by one until it broke, it turned out being caused by a typo in the java.format.settings.url path.

That is a bug.

**Comment by riccardobl** [comment]
`Java Debug: Force Build before launch` seems to be on by default.

My user settings are

```json
{
    "telemetry.enableCrashReporter": false,
    "telemetry.enableTelemetry": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "java.home":"/DEV/VMS/zulu8.38.0.13-ca-fx-jdk8.0.212-linux_x64",
    "window.menuBarVisibility": "toggle",
    "debug.toolBarLocation": "docked",
    "window.zoomLevel": 0,
    "java.autobuild.enabled": true,
    "extensions.autoUpdate": false
}
```

And extensions:
![Screenshot from 2019-05-08 16-10-44](https://user-images.githubusercontent.com/4943530/57381817-fc6f2700-71ab-11e9-91c7-3d395a82c6cc.jpg)
