### ISSUE TITLE
Cannot navigate types through fully qualified name

### ISSUE THREAD

**Issue by andxu** [redhat-developer/vscode-java#920]
![image](https://user-images.githubusercontent.com/17075863/57594222-90a50980-7571-11e9-9a86-bfeb83a81adf.png)

**Comment by fbricon** [comment]
@NikolasKomonen you can probably look into this one. See https://github.com/eclipse/eclipse.jdt.ls/blob/fc6b40e58808d23a324628a1e79e50f117c534de/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/WorkspaceSymbolHandler.java. Eclipse support FQCN searches so it must be doable.

**Comment by fbricon** [comment]
@NikolasKomonen FYI, it's `Ctrl+T` to open this type search

**Comment by rgrunber** [comment]
We supported this with https://github.com/eclipse/eclipse.jdt.ls/issues/2084  :sunglasses:
