### ISSUE TITLE
Quick fix is not good for use in 1.33.1 , it can not create a method in java, but in 1.30.2 is OK

### ISSUE THREAD

**Issue by Bergv** [redhat-developer/vscode-java#926]
Quick fix is not good for use in 1.33.1 , it can not create a method in java, but in 1.30.2 is OK

##### Environment
- Operating System: windows 10
- JDK version: 1.8.0_201
- Visual Studio Code version: 1.33.1
- Java extension version: 0.44.0

**Comment by fbricon** [comment]
Can you please attach [logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#turn-on-message-tracing-between-vs-code-and-the-java-language-server) to this issue?
