### ISSUE TITLE
Exposing properties like compiled classes and libraries for SonarLint integration

### ISSUE THREAD

**Issue by ChrisTrenkamp** [redhat-developer/vscode-java#934]
The Java plugin is almost at the point where I can use VSCode full-time.  However, it's missing SonarLint Java support, which I feel dramatically increases productivity.  

Some people tried to get Java support added to the SonarQube VSCode Plugin, but was not accepted.  This is their response: [https://github.com/SonarSource/sonarlint-vscode/pull/28#issuecomment-467444765](https://github.com/SonarSource/sonarlint-vscode/pull/28#issuecomment-467444765).

They need access to your compiled classes and imported libraries in order for it to be useful.  [https://docs.sonarqube.org/display/PLUG/Java+Plugin+and+Bytecode](https://docs.sonarqube.org/display/PLUG/Java+Plugin+and+Bytecode)

Is it possible to expose these properties for consumption for other plugins?  I imagine there's other tools besides SonarLint/SonarQube that need these kinds of properties as well.

**Comment by fbricon** [comment]
the [java dependency extension](https://github.com/Microsoft/vscode-java-dependency), extends the Java language server to expose similar project classpath informations. @yaohaizh might be able to contribute some of those commands back to jdt.ls itself.

**Comment by yaohaizh** [comment]
@ChrisTrenkamp Please log an issue against the https://github.com/Microsoft/vscode-java-dependency for project classpath information. I will contribute code back to jdt.ls if necessary.
