### ISSUE TITLE
bogus build error

### ISSUE THREAD

**Issue by gahisee** [redhat-developer/vscode-java#936]
After day or two of debugging a java app, on two occasions now, I have run into following two situations:

    hitting F5 to debug, VSC reports it cannot find the class MainApp which clearly has and presently exist.
    VSC reports there are build errors but in fact, there are none.

in both instances, i resort to deleting the cache directory
$HOME/.config/Code/User/workspaceStorage/

upon restart, all is well.

VS Code version: Code 1.34.0 (a622c65, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 5.0.0-13-generic

##### Environment
- Operating System:
- JDK version: OpenJDK 11
- Visual Studio Code version: 1.34.0
- Java extension version:0.45

##### Steps To Reproduce
1. happens only after fairly extensive debugging period over days
2. no definitive steps to reliably reproduce but has occurred 2 or 3 times; each time the solution is to delete the above-mentioned cache

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by fbricon** [comment]
Please attach the server logs when build errors are reported

**Comment by gahisee** [comment]
it happened again this morning; same remedy.
where is the server log that you need to see. please advise how to obtain it.
besides the build error message, there are tons of compile errors as well. vsc clearly is not reading the project correctly due to corrupted cache.
