### ISSUE TITLE
Javadoc Syntax highlighting

### ISSUE THREAD

**Issue by 3ximus** [redhat-developer/vscode-java#94]
Not sure if i should ask this here, but would it be possible for you to add syntax highlighting for javadoc?

**Comment by fbricon** [comment]
Can you be more specific? 

This is hovering over the String class:

<img width="649" alt="capture d ecran 2016-11-15 a 12 30 07" src="https://cloud.githubusercontent.com/assets/148698/20316314/52cd4bae-ab2f-11e6-8a40-a72f29b52442.png">

**Comment by 3ximus** [comment]
I meant custom javadoc like this:
![2016-11-15-184646_1104x174_scrot](https://cloud.githubusercontent.com/assets/9083012/20319032/93252052-ab64-11e6-9952-32054cc9dd1e.png)

as I have for example on eclipse or Gvim:
![2016-11-15-184723_999x129_scrot](https://cloud.githubusercontent.com/assets/9083012/20319044/98d2acae-ab64-11e6-8aa1-2ae2f3f0e933.png)

Also hovering over a class (String for example ) doesnt give me any javadoc popup like the one you showed...

**Comment by fbricon** [comment]
I see. And I agree that's a perfectly legitimate request. 

You only get javadoc on hover when the java file is opened within a project directory (must be an Maven or Eclipse project), not as a standalone file.

**Comment by 3ximus** [comment]
I do have a maven project open. Everything works, like completion and my custom javadoc is displayed, but not javadoc of classes or methods that I didnt define.
Dont know if it matters but I have java.home set to:  `"java.home": "/usr/lib/jvm/java-8-openjdk",` and I'm running this on Arch Linux.

**Comment by fbricon** [comment]
While javadoc syntax highlighting is probably fixable in vscode-java, I believe this is something that should be fixed upstream, in https://github.com/Microsoft/vscode/blob/master/extensions/java/syntaxes/java.json. @gorkem WDYT?

**Comment by fbricon** [comment]
@3ximus I don't see why this behavior would be missing on linux, given the rest works. Can you try on another OS?

**Comment by 3ximus** [comment]
Yeah. I've tried it on Kali Linux and it has the exact same problem. However on Windows 10 it works fine.

**Comment by gorkem** [comment]
@fbricon Syntax highlights are on the vanilla vscode, I think it is best to handle it in there. Opened https://github.com/Microsoft/vscode/issues/15527 let's see what vscode team responds.

**Comment by gorkem** [comment]
@3ximus Are you missing javadocs for 3rd party libraries or JDK classes?

**Comment by 3ximus** [comment]
I haven't tried on any third party libraries, only on JDK classes

**Comment by gorkem** [comment]
You probably do not have the source files or javadocs for the JDK classes on your JVM installation. We extract javadocs from either sources or javadocs.

**Comment by 3ximus** [comment]
Yes, you are right... My bad. Thanks, keep up the good work 😉

**Comment by fbricon** [comment]
Upstream got it almost working, except for closing tags. See https://github.com/Microsoft/vscode/issues/16041
<img width="358" alt="capture d ecran 2016-11-24 a 16 30 07" src="https://cloud.githubusercontent.com/assets/148698/20610219/6113abfe-b264-11e6-8e3c-12b8ba69480a.png">

**Comment by fbricon** [comment]
So Microsoft/vscode#16041 has been fixed. Until VS Code 1.10 is released, you need to use the [Insider build.](https://code.visualstudio.com/insiders)

**Comment by fbricon** [comment]
VS Code 1.10 was released today, Javadoc looks good now.
