### ISSUE TITLE
Plugin doesn't seem to support no_proxy/systemProp.http.nonProxyHosts for gradle

### ISSUE THREAD

**Issue by jakegt1** [redhat-developer/vscode-java#943]
When downloading gradle distributions/packages with the http.nonProxyHosts system property active, http requests still seem to route through the proxy rather than respecting the system prop.

##### Environment
- Operating System: CentOS 7
- JDK version: 1.8
- Visual Studio Code version: 1.34.0
- Java extension version: 0.45.0

##### Steps To Reproduce
1. Use the no_proxy environment variable/set the system property anywhere (also in the vmargs section of vscode settings)
2. Attempt to use a gradle project that requires a valid no_proxy to be able to download content.

##### Current Result
Fails to download due to routing through the proxy rather than respecting the no_proxy variable

##### Expected Result
No issue

I'm unsure if this is a problem with the plugin or the downstream jdt.ls server, although the stacktrace seems to come from the server.

**Comment by jakegt1** [comment]
Any update on this?

**Comment by fbricon** [comment]
You can try the latest CI build of the vscode-java extension from https://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D, and see if the new gradle preferences added via #973 are any useful:

**Comment by jakegt1** [comment]
Doesn't seem to fix it unless you have a command that might work - i simply tried to set `-DsystemProp.http.nonProxyHosts` in the vm arguments.

Quite a confusing issue if im honest, i really don't know why setting the system properties inside the language server doesn't work. It respects http_proxy and https_proxy, it just doesn't respect no_proxy (or nonProxyHosts).

**Comment by snjeza** [comment]
@jakegt1 You can try the latest CI build and set the following property:

```
"java.import.gradle.jvmArguments": "-Dhttp.nonProxyHosts =<your_hosts>"
```

**Comment by jakegt1** [comment]
ye, i noticed i said `-DsystemProp.http.nonProxyHosts`, but i did actually try the above line you have just provided (it didn't work). Still returns a 502 (becuase it tries to route through the proxy.)

**Comment by jakegt1** [comment]
Sorry about this, it actually works now. Does it need a java language server clean up before it picks up the changes or something? I'm unsure why it did not work the first time, but it does now.

**Comment by jakegt1** [comment]
So to finally confirm: fix for this is to set `-Dhttp.nonProxyHosts` in the "java.import.gradle.jvmArguments" section.

To note otherwise though, this feels like a bit weird due to me having these set inside my `gradle.properties` file in my GRADLE_USER_HOME, so i'm unsure why that just isn't picked up instead. Maybe possible to do?

**Comment by snjeza** [comment]
@jakegt1 could you provide a project example?

**Comment by jakegt1** [comment]
Not really, but a base gradle project (just run `gradle init`) is (almost) enough to reproduce this, with the following two caveats:

1. Set the gradle-wrapper distributionUrl to a location that requires no_proxy set (or add a java dependency with the repository url that requires the same)
2. Use a proxy.

I expect you could reproduce this by using a proxy in docker (just make it return 502 on any URL), and any sort of maven repository in docker (artifactory is pretty simple to set up.)

I could probably construct a project that includes this entire setup if needed.

**Comment by snjeza** [comment]
> I could probably construct a project that includes this entire setup if needed.

It would be helpful.
