### ISSUE TITLE
Test source mapping in workspaceStorage not updated when test case is deleted

### ISSUE THREAD

**Issue by sappersix** [redhat-developer/vscode-java#944]
Issue Type: <b>Bug</b>

When I delete a test case from a test Class and click "Run Test" in CodeLens, my test shows failure.  When I open the Java Test Report, I see a list that looks like this:

```
case1 - Passed
nameOfTestClase#nameOfDeletedTest - Failed  <----- There is an enty for the deleted test
case3 - Passed

```
I have tried "Java: Clean the Java language server workspace" and "Java: Force Java compillation" and the problem persists.

I have to go to %userprofile%\AppData\Roaming\Code\User\workspaceStorage and delete my workspace.  Once I restart VSC all my tests are clean.

Is there a setting I'm missing or something I need to do to refresh what tests VSC thinks are present?

Extension version: 0.45.0
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (3.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by fbricon** [comment]
@yaohaizh can you transfer that issue to vscode-java-debug?

**Comment by jdneo** [comment]
Might be related to this issue: https://github.com/microsoft/vscode-java-test/issues/42.

**Comment by fbricon** [comment]
@jdneo can you transfer this ticket?

**Comment by jdneo** [comment]
@fbricon I have no permission to transfer it. But the comments are referenced here: https://github.com/microsoft/vscode-java-test/issues/42#issuecomment-503836853

This issue could be closed I think.
