### ISSUE TITLE
Linting cannot be configured: Method arguments with long name are not shown in multiple line.

### ISSUE THREAD

**Issue by chandr3sh** [redhat-developer/vscode-java#945]
Although this extension performs linting but there is no way to configure it. If I put multiple arguments with long names on different lines, it automatically compresses them in one or two lines when "formatOnSave: true".

##### Environment
- Operating System: Windows 10 version:1903
- JDK version: 11.0.3
- Visual Studio Code version: 1.34.0
- Java extension version: 0.45.0

##### Steps To Reproduce
1. Edit setting `formatOnSave: true`
2. Create a new class file Foo.java
3. Add the following method to `class Foo`:
```
public class Foo {
  void bar(boolean booleanWithVeryLoneName, 
           int intergerValueWithVeryLongName,
           double decimalValueWithVeryLongName,
           String stringValueWithVeryLongName) {
    return;
  }
}
4. Save the file.
```

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Method arguments are compressed into 1 or 2 lines depending upon the number of characters in name of arguments:
```
  void bar(boolean booleanWithVeryLoneName, int intergerValueWithVeryLongName, double decimalValueWithVeryLongName,
      String stringValueWithVeryLongName) {
    return;
  }
```

##### Expected Result
Method should stay like:
```
  void bar(boolean booleanWithVeryLoneName, 
           int intergerValueWithVeryLongName,
           double decimalValueWithVeryLongName,
           String stringValueWithVeryLongName) {
    return;
  }
```
OR
```
  void bar(boolean booleanWithVeryLoneName, 
    int intergerValueWithVeryLongName,
    double decimalValueWithVeryLongName,
    String stringValueWithVeryLongName) {
    return;
  }
```
##### Additional Informations
There should be a setting to override such behavior of the extension.

**Comment by snjeza** [comment]
@chandr3sh try to add

```
org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration=83
```
or
```
org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration=81
```
to
<your_project>/.settings/org.eclipse.jdt.core.prefs

**Comment by chandr3sh** [comment]
@snjeza Thanks for replying. The solution you provided doesn't work (**Current Result** doesn't changes).

**Comment by snjeza** [comment]
Do you use the java.format.settings.url property?

**Comment by chandr3sh** [comment]
No. Currently, "java.format.settings.url": null
What should be the required value here?

**Comment by snjeza** [comment]
Could you try the following project?
[test.zip](https://github.com/redhat-developer/vscode-java/files/3244119/test.zip)

**Comment by chandr3sh** [comment]
It works now!
Sorry, it was my bad. I added the setting in org.eclipse.jdt.**apt**.core.prefs file instead of org.eclipse.jdt.core.prefs.
Thanks a lot. 👍

**Comment by chandr3sh** [comment]
The setting `org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration=83` makes sure every method argument appears on new line and this behavior is consistent across the whole project. So, this creates situations like this...
![image](https://user-images.githubusercontent.com/12244518/58752910-69888a80-84d4-11e9-9710-a99d810e293b.png)
Is there a way to have arguments on new line if argument name is longer than a certain amount of characters, otherwise it stays on the same line. So, we can have it like this...
![image](https://user-images.githubusercontent.com/12244518/58752937-d2700280-84d4-11e9-9559-ef036a3d8bfe.png)

**Comment by snjeza** [comment]
You may want to take a look at https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings

**Comment by chandr3sh** [comment]
I already checked it. Currently using it as of now.
The [Formatter-settings](https://github.com/redhat-developer/vscode-java/wiki/Formatter-settings) provides [xml file](https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml) for the property `java.format.settings.profile`. The **xml** assigns `org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration` a value of _16_. So, I am confused with all these values like _16, 81, 83,_ etc.
Now, I am trying to figure out all the possible values for this setting and which one is suitable (if any) in this case.

**Comment by snjeza** [comment]
See
https://www.wikihow.com/Change-the-Default-Format-Settings-in-Eclipse
https://stackoverflow.com/questions/23153805/how-to-format-method-with-more-parameter-in-eclipse

**Comment by chandr3sh** [comment]
Made it work! The required value is **82**.

**Solution:**
In summary putting these two settings <your_project>/.settings/org.eclipse.jdt.core.prefs will be enough.
```
org.eclipse.jdt.core.formatter.alignment_for_parameters_in_method_declaration=82
org.eclipse.jdt.core.formatter.alignment_for_arguments_in_method_invocation=82
```
_References_: [declaration setting](https://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/formatter/DefaultCodeFormatterConstants.html#FORMATTER_ALIGNMENT_FOR_PARAMETERS_IN_METHOD_DECLARATION), [invocation setting](https://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/formatter/DefaultCodeFormatterConstants.html#FORMATTER_ALIGNMENT_FOR_ARGUMENTS_IN_METHOD_INVOCATION)

**Explanation:**
So, these two settings takes the value returned by the [method](https://help.eclipse.org/mars/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/formatter/DefaultCodeFormatterConstants.html#createAlignmentValue-boolean-int-int-):
```
org.eclipse.jdt.core.formatter.DefaultCodeFormatterConstants.createAlignmentValue(boolean forceSplit, int wrapStyle, int indentStyle);
```
1. `wrapStyle=DefaultCodeFormatterConstants.WRAP_NEXT_PER_LINE` The wrapping is done by putting each element on its own line except the first element.
2. `indentStyle=DefaultCodeFormatterConstants.INDENT_ON_COLUMN` The wrapping is done by indenting on column under the splitting location.
3. `forceSplit=false` wrapping and indentation should not be forced, i.e. wrap and indent only when needed.

Passing these three values through the function, I get the value 82.
Checking it in VSCode, I see the desired result. Now, I can rest in peace. ✌

**Result**:
![image](https://user-images.githubusercontent.com/12244518/58754364-06a2ed80-84ec-11e9-9b49-6d13f536ed29.png)

**Comment by zlsmith86** [comment]
@kumarchandresh Would you be willing to share your whole settings file <your_project>/.settings/org.eclipse.jdt.core.prefs?  I have tried the settings above, but am still missing something

**Comment by kumarchandresh** [comment]
@zlsmith86 I don't have it anymore.
