### ISSUE TITLE
Java Override annotation problem

### ISSUE THREAD

**Issue by ennish** [redhat-developer/vscode-java#948]
Issue Type: <b>Bug</b>

When I add a '@Override' annotation on the method I want to override, it tips: The method must override a supperclass method.

Extension version: 0.46.0
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 x 2591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by anthonyvdotbe** [comment]
@ennish this is a standard message to inform you that the signature of the annotated method doesn't match any superclass method. If you're confident that the message is shown incorrectly, please provide the actual Java source code that demonstrates the issue

**Comment by rsrini7** [comment]
If java compiler property not provided, maven takes java version as by default 1.5. Adding below properties fixes the issue. No issue from plugin side.

<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
