### ISSUE TITLE
Cannot set up dev environment following contributing instruction

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#949]
I'm not sure if it's out of date, but following the instruction I couldn't manage to debug the language server. I find it's extremely hard to set up the dev environment **from scratch** (once successfully set up, it's much easier to configure it for a second time), which I think should be a big obstacle for the community to contribute to either eclipse.jdt.ls or this extension.

`eclipse.jdt.ls` is the core, so it would be good if I can easily debug the language server. But the corresponding section is confusing.

> #### Run with a remote JDT language server
> - Open VSCode on the `vscode-java` folder
> - In the debug viewlet, run the launch _Launch Extension - Remote Server_
> - The extension will open a socket on port 3333 and will wait for the JDT language server to connect

This part is clear to me.

> - In Eclipse, run the JDT language server as an Eclipse application. 
>     - Create a debug configuration of type _Eclipse Application_.
>     - in the main tab of the debug configuration set the product to `org.eclipse.jdt.ls.core.product`.
>    - in the Environment tab, define a variable `CLIENT_PORT` with value `3333`.
>    - if your workspace contains 'org.eclipse.jdt.ui', use the Plug-Ins tab in the debug configuration to exclude the plug-in. The presence of 'org.eclipse.jdt.ui' will cause the language server to hang. 
> - In the debug console of VSCode you can see if the connection was successful.

**But following this part, I failed** 
- Merely excluding 'org.eclipse.jdt.ui' didn't work. Following the error log, I tried diabling several '*.ui' package but still didn't get it working. And I could not find out what to do from the error messages. 
- Since the purpose of above steps is to create a launch configuration, it would be better if `eclipse.jdt.ls` has the .launch file in its repo. BTW I notice that there's already a [jdt.ls.socket-stream.launch](https://github.com/eclipse/eclipse.jdt.ls/blob/f51ccd656de81d112aa062f0a4297cdaea5d9de8/launch/jdt.ls.socket-stream.launch) (although I'm not sure what's it for), so I think  **a  `jdt.ls.vcode-java-remote-server.launch` would be a great help to new developers like me.**

**Comment by snjeza** [comment]
>  BTW I notice that there's already a jdt.ls.socket-stream.launch (although I'm not sure what's it for)

See https://github.com/redhat-developer/vscode-java/pull/646 and https://github.com/eclipse/eclipse.jdt.ls/pull/799
