### ISSUE TITLE
Find reference returned a wrong result

### ISSUE THREAD

**Issue by jdneo** [redhat-developer/vscode-java#955]
##### Environment
- Operating System: Windows 10
- JDK version:  11.0.2
- Visual Studio Code version: 1.35.1
- Java extension version: 0.46.0

##### Steps To Reproduce
1. Open the [Spring-Petclinic](https://github.com/spring-projects/spring-petclinic) project
2. In `ValidatorTests.java`, add the following code
```java
    ...
    public void test() {
        this.test(1);
    }

    public void test(int i) {

    }
```
3. trigger `peek reference` on `this.test(1)`

##### Current Result
![image](https://user-images.githubusercontent.com/6193897/59655996-c7a0b780-91ce-11e9-98fe-227d5d1056c1.png)

##### Expected Result
I think the second reference `KotlinDefaultMask.class` should not appear in the list

**Comment by snjeza** [comment]
I can't reproduce the issue. There isn't KotlinDefaultMask.class in spring-petclinic.
@jdneo could you try to clean the workspace directory - https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory

**Comment by jdneo** [comment]
Hi @snjeza, I tried the clean workspace command but no help.

Some update: I cannot repro it on Mac. The problem occurs on my Windows Machine.

**Comment by snjeza** [comment]
> Some update: I cannot repro it on Mac. The problem occurs on my Windows Machine.

@jdneo  I can't reproduce the issue on Windows and Linux. Could you try to clone the spring-petclinic project to a new directory?

**Comment by jdneo** [comment]
After renaming the folder, the problem could not be repro anymore.
