### ISSUE TITLE
compiler.err.doesnt.exist vscode

### ISSUE THREAD

**Issue by Saifulbappi** [redhat-developer/vscode-java#956]
[provide a description of the issue]

##### Unix
- MacOS Mojave version(10.14.5)
- JDK version:"1.8.0_60"
- Visual Studio Code version:1.35.1 (1.35.1)
- Java extension version:0.7.1

##### Steps To Reproduce
1. External Library is added in lib folder in the root directory.. in this project one library jar for  log4j is added. Project Run is producing result. But in App.java file
  import org.apache.log4j.Logger;
is showing package org.apache.log4j.Logger does not exist
Sample Project
[HudaJava.zip](https://github.com/redhat-developer/vscode-java/files/3305690/HudaJava.zip)

##### Current Result
package org.apache.log4j.Logger does not exist
##### Expected Result
no language error

**Comment by fbricon** [comment]
Works for me. Try restarting vscode?

**Comment by Saifulbappi** [comment]
hi @fbricon , i've restarted it . Also rebooted pc !!  Attaching a screenshot.
![Screenshot 2019-06-20 at 8 56 43 AM](https://user-images.githubusercontent.com/5940938/59815174-a4464b80-9339-11e9-8eb9-46bd06dd3eec.png)

**Comment by fbricon** [comment]
can you try [cleaning the server workspace](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory)?

**Comment by fbricon** [comment]
Oh I now realize the error code `compiler.err.doesnt.exist` doesn't come from vscode-java. It might be caused by https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac, which conflicts with vscode-java. So you should disable or uninstall it.

**Comment by ahofmeister** [comment]
@fbricon Thanks! I honestly invest 4-5 hours into this and even uninstalled Java and Maven multiple times. I uninstalled the extension and the errors are gone! :)

**Comment by pshettyk** [comment]
@fbricon Thanks.  Solved the issue.

**Comment by ganeshkumar-opscruise** [comment]
@fbricon thanks a lot

**Comment by anserwaseem** [comment]
@fbricon Tysm

**Comment by TP-mimanchi** [comment]
thanks a lot

**Comment by aironsg** [comment]
Thanks, you have no idea how this solved my problems.

**Comment by sirbuni** [comment]
@fbricon Thanks. Uninstalling the extension fixed the issue.

**Comment by sherrif10** [comment]
Thanks alot. it wortheth like a charm

**Comment by KeiJeff** [comment]
🙏 Thank you! This held me up for a while.

**Comment by mrblacklicorice** [comment]
Thank you so much, been struggling for the past 6 hours

**Comment by AltSpaces** [comment]
God bless you, been struggling for for a while

**Comment by kola110** [comment]
Thank you!

> Oh I now realize the error code `compiler.err.doesnt.exist` doesn't come from vscode-java. It might be caused by https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac, which conflicts with vscode-java. So you should disable or uninstall it.

**Comment by Mark-Vu** [comment]
Can I still use the extension because it is still useful but I wanna fix the "compiler.err.doesnt.exist" error

**Comment by antonimarczuk123** [comment]
> Oh I now realize the error code `compiler.err.doesnt.exist` doesn't come from vscode-java. It might be caused by https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac, which conflicts with vscode-java. So you should disable or uninstall it.

Thank you :)

**Comment by nellygakuru** [comment]
> Oh I now realize the error code `compiler.err.doesnt.exist` doesn't come from vscode-java. It might be caused by https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac, which conflicts with vscode-java. So you should disable or uninstall it.

Thank you!

**Comment by phoenix24** [comment]
> Oh I now realize the error code `compiler.err.doesnt.exist` doesn't come from vscode-java. It might be caused by https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac, which conflicts with vscode-java. So you should disable or uninstall it.

thank you, that helped! 🙏

**Comment by Connor-Baldwin** [comment]
THANK YOU!

**Comment by gerson-paula** [comment]
> Oh I now realize the error code `compiler.err.doesnt.exist` doesn't come from vscode-java. It might be caused by https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac, which conflicts with vscode-java. So you should disable or uninstall it.

Thank you!

**Comment by iibrahemali** [comment]
> Oh I now realize the error code `compiler.err.doesnt.exist` doesn't come from vscode-java. It might be caused by https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac, which conflicts with vscode-java. So you should disable or uninstall it.

Thanks!

**Comment by denizyldrm123** [comment]
wow thank bro God bless you,

**Comment by maneeelmns** [comment]
thank you so much God bless you brother !!

**Comment by MockingBill** [comment]
thanks NB plus

**Comment by dragonffruit** [comment]
Thank you very much! May god bless you!!!

**Comment by drebander2024** [comment]
> Oh I now realize the error code `compiler.err.doesnt.exist` doesn't come from vscode-java. It might be caused by https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac, which conflicts with vscode-java. So you should disable or uninstall it.

it works,thanks
