### ISSUE TITLE
new class autocompletion always adds <>

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#96]
Autocompleting a new class always adds <>at the end.

##### Steps To Reproduce
1. type _StringBuilder s = new StringBui_`ctrl+space,enter`

##### Current Result
_new StringBuilder`<>`()_ is generated 

##### Expected Result
should be _new StringBuilder()_

**Comment by fbricon** [comment]
This is a consequence of https://github.com/gorkem/java-language-server/commit/b42df7607811c1a46eba199f9f3e18901bff626a

**Comment by gorkem** [comment]
Fixed with https://github.com/gorkem/java-language-server/commit/469e9d02d20dc193b3b2bedd14bafc4d410df922
