### ISSUE TITLE
Feature Request: organize imports with the asterisk (*) wildcard character

### ISSUE THREAD

**Issue by xdango** [redhat-developer/vscode-java#964]
It would be great to organize imports from same package with a single asterisk (*), which makes the import section a little shorter.

In `eclipse`, there are two settings related to this feature:
1. `number of imports needed for .* (e.g. org.eclipse.*)`
2. `number of static imports needed for .* (e.g. java.lang.Math.*)`

Unfortunately, these options are not available in the eclipse formatter xml file ([available options](https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fformatter%2FDefaultCodeFormatterConstants.html)).

**Comment by rafaelrenanpacheco** [comment]
That would be a nice feature, it is the default behavior in IntelliJ.
