### ISSUE TITLE
Automatic import add unnecessary blank line

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#97]
When autocompletion generates an import statement, an unnecessary blank line is added after that import 

##### Environment
- Visual Studio Code version: 1.8 (Insiders)

##### Steps To Reproduce
1. type _Map_`ctrl+space,enter` to import java.util.Map
2. type _Map m = new HashM_`ctrl+space,enter` to import java.util.HashMap

##### Current Result
```
import java.util.HashMap;

import java.util.Map;


```
##### Expected Result
```
import java.util.HashMap;
import java.util.Map;
```

**Comment by fbricon** [comment]
I seems this problem doesn't occur with VS Code 1.7.1.
So it's either a regression upstream or we're missing some updates in our dependencies. @gorkem can you confirm?

**Comment by fbricon** [comment]
Actually this happens in 1.7.1 too. Now with even more blank lines following https://github.com/gorkem/java-language-server/commit/b9d0991a370530ccab99edde6018fd488bf1b0c3

**Comment by gorkem** [comment]
I can no longer reproduce this one. Closing
