### ISSUE TITLE
Java Language Server is not always initialized successfully

### ISSUE THREAD

**Issue by veredcon** [redhat-developer/vscode-java#970]
[provide a description of the issue]

##### Environment
- Operating System: debian
- JDK version: 1.8.0_192
- Visual Studio Code version: (theia)
- Java extension version: 0.46

##### Steps To Reproduce
1. [step 1] Open theia/vscode without creating any workspace yet

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result
Sometimes the LSP initialize does not succeed

##### Expected Result
LSP initialization should always succeed

##### Additional [Informations](url)
Attached log files when lsp sometimes succeed the initialization and when it doesn't.
[loglsp_successinit.txt](https://github.com/redhat-developer/vscode-java/files/3350625/loglsp_successinit.txt)
[loglsp_notsuccess.txt](https://github.com/redhat-developer/vscode-java/files/3350627/loglsp_notsuccess.txt)

Seems like there is a logic of generating vscodews_<*****> under temp directory but I see that this folder is not always created and I think it causes the crash.
When I refresh I get the message of "The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted."

When I create a workspace this it doesn't happen as the -data path is stable and I see in the log it points to:
Command-line arguments:  -data /home/user/.theia/workspace-storage/20b95fe70fa2abdf2225e59057b67a41/redhat.java/jdt_ws

Seems like race condition but I'm not sure where exactly.
Hope you can assist
Thanks

**Comment by snjeza** [comment]
> Visual Studio Code version: (theia)

@veredcon How did you run it?

**Comment by veredcon** [comment]
We are running the vscode extensions in theia 0.8.0 https://github.com/theia-ide/theia.

**Comment by snjeza** [comment]
I can't reproduce the issue.
I have tried the following:
```
$ git clone https://github.com/theia-ide/theia 
$ cd theia
$ yarn
$ cd examples/browser
$ ls ../../plugins
redhat.java-0.46.0.vsix  VisualStudioExptTeam.vscodeintellicode-1.1.7.vsix  vscjava.vscode-java-debug-0.20.0.vsix
$ yarn run start
```
