### ISSUE TITLE
Highlight code throwing exception

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-java#972]
From @lukaseder's [tweet](https://twitter.com/lukaseder/status/1147156405687848960): 

    when I mouse-over a checked exception, it will highlight who could be throwing it.

I don't think we can trigger highlight on hover, but should be doable on click, on `throws`, the `catch` statement and its Exception

**Comment by lukaseder** [comment]
Thanks for the reference. I mistakenly said "mouse-over". I meant putting the caret on an exception
