### ISSUE TITLE
Enum : first item is not correctly hightlight

### ISSUE THREAD

**Issue by orblazer** [redhat-developer/vscode-java#974]
Hello,
The color of first item when the enum overwrite is wrong

##### Environment
- Operating System: Windows 10
- JDK version: jdk1.8.0_212
- Visual Studio Code version: 1.35.1
- Java extension version: 0.46.0

##### Steps To Reproduce
1. Create an enum with function
2. Override that function in enum items

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

##### Current Result

![wrong](https://user-images.githubusercontent.com/1344792/60839221-e8a46900-a1cc-11e9-9d97-66cefebf8ff1.png)

##### Expected Result

![right](https://user-images.githubusercontent.com/1344792/60839225-ec37f000-a1cc-11e9-9065-77cc7ed6b0b9.png)

##### Additional Informations

The path for color is different :

**Path of current result :**
![wrong-dt](https://user-images.githubusercontent.com/1344792/60839319-2e613180-a1cd-11e9-9fb2-69c83899d944.png)

**Path of expected result :**
![right-dt](https://user-images.githubusercontent.com/1344792/60839345-3a4cf380-a1cd-11e9-9ac7-95761af8535d.png)

I think the path for the `current result` is right bug its just parsing is broken.

**Comment by fbricon** [comment]
The textmate grammar is defined in [vscode itself](https://github.com/microsoft/vscode/blob/master/extensions/java/syntaxes/java.tmLanguage.json), but the source of the grammar is actually atom, so the problem should be reported there: https://github.com/atom/language-java/issues

**Comment by Vigilans** [comment]
This issue has been solved in https://github.com/atom/language-java/pull/212.

**Comment by fbricon** [comment]
Fixed upstream some time ago.
