### ISSUE TITLE
Extension is not loading when opening first file

### ISSUE THREAD

**Issue by dsnowdon** [redhat-developer/vscode-java#98]
Won't load the extension when opening my first java file.

##### Environment
- Operating System: Mac Osx 10.12.1
- JDK version: 8 
- Visual Studio Code version: 1.7.1
- Java extension version:
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Comment by gorkem** [comment]
I think these logs are from [georgewfraser.vscode-javac](https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac) vscode extension.  Please install [vscode-java](https://marketplace.visualstudio.com/items?itemName=redhat.java)

**Comment by dsnowdon** [comment]
I don't have the installed anymore yet when I open a java file Java support is still not opening and i'm setting prompted to install JDK8

**Comment by gorkem** [comment]
Do you see a _Starting Java Language Server..._ prompt on the corner?

**Comment by dsnowdon** [comment]
Yeah it just waits stays there

**Comment by gorkem** [comment]
Can you try setting the java.home on your settings.json to the location of your JDK? It should detect the JDK location but somehow in your case it does not. This should override any detection problems.

**Comment by dsnowdon** [comment]
the java.home setting in VS Code settings (workspace then user settings)
the JDK_HOME environment variable
the JAVA_HOME environment variable
on the current system path

I did see this on the page, could you provide a example of the seeing that i need to set?

I've set "java.home": "/usr/libexec/java_home" in my settings.json

What else do I need?

**Comment by gorkem** [comment]
execute "/usr/libexec/java_home" on command line and use its output as `"java.home"` value in my system it reads something like `/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home`

**Comment by dsnowdon** [comment]
Thats got it mate thank you! is there anything I can post to help you debug why its not detecting the location?

**Comment by gorkem** [comment]
yes, I was going to ask the values of JDK_HOME environment variable
the JAVA_HOME environment variable if they are defined and the output of `/usr/libexec/java_home`.

**Comment by dsnowdon** [comment]
/usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home

**Comment by gorkem** [comment]
I am closing this one for now, I can not reproduce this on my system.
