### ISSUE TITLE
Feature request: Using maven settings to get java dependencies

### ISSUE THREAD

**Issue by iKoru** [redhat-developer/vscode-java#983]
##### Environment
- Operating System: Windows 7 (32bit)
- JDK version: Oracle JDK 1.8.0.201
- Visual Studio Code version: 1.35.1(user setup)
- Java extension version: 0.46.0

##### Steps To Reproduce

-  Note that my developing environment is **offline**, and I am using sonatype nexus to get many java dependencies.

- I got useful extensions: vscode-java(red hat) and maven for java(MS). 

- I set up maven settings to use nexus proxy, and it works fine - using maven extension to build my project. 

- However, java extension seems not to use maven settings to get java sources informations.

- Even though there is a proxy settings(http.proxyHost, http.proxyPort, http.proxyUser, ...), it seems not to work properly as I can find logs to access central maven repository directly and it failed 

- So I can see informations only on java(e.g. java.util.*, java.io.*, ...) itself when hover.

##### Current Result
- Even a project is using maven, the extension continues to try to get sources/informations of dependencies directly on maven central repository(https://repo.maven.apache.org/maven2); regardless of settings.xml on maven.

- Or, maybe I set proxy settings wrong, would you like to show a little more details to set proxy? It's too short for me in wiki descriptions.

##### Expected Result
- When it's a maven project, I want the extension to try to use settings.xml(effective pom) and reflect <servers> / <mirrors> settings in there.

- Or, support some more details about using nexus for offline users like me to set proxy settings well..

Thanks in advance. I really appreciated about this great extension.

**Comment by snjeza** [comment]
You can try to use the java.configuration.maven.userSettings property.

**Comment by iKoru** [comment]
OMG... the property on my workspace settings was
"path/to/settings/file/directory"
and when I changed it as
"path/to/settings/file/directory/settings.xml"
it works very well.

Thanks @snjeza !!!! you saved my 4 days!!!
