### ISSUE TITLE
Adopt SnippetString API

### ISSUE THREAD

**Issue by jrieken** [redhat-developer/vscode-java#99]
With the December release VS Code will have real API to define a CompletionItem that is inserted as snippet, for details see https://github.com/Microsoft/vscode/issues/3210. 

In short, we now support a subset of the more common TextMate syntax: `$1`, `$2` etc define tabstops, `${1:value}` and `${2:this is${3:nested}}` placeholders, and `$0` is for the final tabstop. 

The API for this is contained in a new type [`SnippetString`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2035). It can be used as the `insertText` of a [CompletionItem](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2364).

During a transition phase we will still support the internal, unspecified snippet syntax your extension is using but eventually remove it (roughly 2 or 3 milestones from now). 

The language server protocol supports the SnippetString in its next-branch - see https://github.com/Microsoft/vscode/issues/15577#issuecomment-262160802

**Comment by gorkem** [comment]
@jrieken Thanks for the heads up
