### ISSUE TITLE
Please support tomcat servers for the development environment of Spring MVC.Spring MVC in China accounts for more than 70% #379

### ISSUE THREAD

**Issue by beyond369** [redhat-developer/vscode-java#990]
Please support tomcat servers for the development environment of Spring MVC.Spring MVC in China accounts for more than 70% #379

**Comment by fbricon** [comment]
Closing as spam
<img width="1103" alt="Screen Shot 2019-07-18 at 10 55 25 AM" src="https://user-images.githubusercontent.com/148698/61443865-9c82c280-a94a-11e9-8ec5-32fe27eb075a.png">

Moreover, this is out of scope of vscode-java, there's a vscode extension for that already: https://marketplace.visualstudio.com/items?itemName=adashen.vscode-tomcat
