### ISSUE TITLE
How to modify jdt compiler into javac compiler

### ISSUE THREAD

**Issue by lzxz1234** [redhat-developer/vscode-java#992]
Can not compile projects with custom annotation processor based on `com.sun.tools`.

##### Environment
- Operating System: Win10
- JDK version: 1.8
- Visual Studio Code version:  1.36.1
- Java extension version: 0.46.0

##### Steps To Reproduce

In annotation processor project:
1. Define `CustomProcessor extends javax.annotation.processing.AbstractProcessor`
2. Construct JavacTrees by `com.sun.tools.javac.api.JavacTrees.instance(processingEnv)`

Then execute compile command in target project .

##### Current Result

Throw IllegalArgumentException because `org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeBuildProcessingEnvImpl` is not a  `com.sun.tools.javac.processing.JavacProcessingEnvironment`

**Comment by fbricon** [comment]
I'm not sure such thing is possible. I suggest you try in Eclipse and if it doesn't work (it probably won't), then open a ticket in JDT: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT. You should get a definitive answer.

**Comment by anson0370** [comment]
So is it not possible to use javac instead of ECJ? Many other tools use javac by default such as Intellij IDEA, Jenkins, Maven(These all can be configured to use ECJ but sometimes you are not in control).
