### ISSUE TITLE
M2E in VsCode (or terminal) as Apache Maven Eclipse Plugin has retired 

### ISSUE THREAD

**Issue by anishmittal2020** [redhat-developer/vscode-java#995]
I have to update `.classpath`, `.project` and `.settings` for a Maven project in VS Code. I read that `mvn eclipse:eclipse` has been retired and I tried that but it doesn't gives me correct files.

How can I use M2E in VScode to regenerate these files? Or, how can I use M2E from the terminal (independent of IDE)?

##### Environment
- Operating System: Ubuntu 18.04
- JDK version: openjdk version "1.8.0_212"
- Visual Studio Code version: Version: 1.36.0
- Java extension version: 0.47.0

**Comment by jcrben** [comment]
@lamyergeier how was this completed?
